### ISSUE TITLE
Output not wrapped in the cells

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#1020]
@africanmathsinitiative/instat 
This is related to the first issue above.

The output with large figures is n

ot being wrapped in the cells.

I hope someone can find a way on how to fix this too.

Thanks

**Comment by dannyparsons** [comment]
It seems that wrapping in cells is only not done for the last column. This could be a bug with reogrid or an option that can be changed. Needs to be looked into.
This issue is visible because the setting of decimal places for column is not completely functional yet.

**Comment by dannyparsons** [comment]
Possibly contact reogrid about this.

**Comment by dannyparsons** [comment]
Seems to be a reogrid issue. Not a problem for us if this is not fixed.
