### ISSUE TITLE
Import matrix to instat object

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#1538]
set_data method of data object should allow a matrix (possibly other types) to be given as the new data. Currently it gives an error if the new data is not a data frame.

**Comment by dannyparsons** [comment]
Important when using, for example t() command to transpose which produces a matrix.

**Comment by dannyparsons** [comment]
@lilyclements could you add your example of an object not importing here which was neither a matrix nor a data frame?

**Comment by lilyclements** [comment]
When you import from the library, there is a package called "Matrix". This contains three datasets, all of whom are neither a matrix nor data frame.

**Comment by dannyparsons** [comment]
matrix objects now accepted, dsCMatrix objects from Matrix package we are not supporting as this package is not in library now. Now also accepts ts objects and non list vectors. Some "datasets" in library still don't import but these are mostly things which cannot usefully be data frames.
