### ISSUE TITLE
Improving the Factor - Levels and labels dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1741]
1. I was really pleased to hear that the levels/labels in this dialogue can be changed by pasting as well as typing.
2. I also like the fact there are currently 3 "columns", so the row number is also shown.
3. One small change - could the counts at each level be right-justified.
4. Could the space for the grid be wider - there is some blank space on the left of the grid.
5.  Now a bigger suggested change.  Either have (always) an additional column.  So the first real column gives the "Old-levels" and is not editable.  The second is called "New-Levels" and is the one that is editable.  It starts with the same names as the "Old-levels", but there could perhaps be a button to clear.  
6. The alternative is to have an optional checkbox.  "Add column for new levels".

Roger

**Comment by dannyparsons** [comment]
@rdstern are any of these features still desired/relevant given the other changes to this dialog recently?

**Comment by rdstern** [comment]
No - this is now great.  Can be closed.
