### ISSUE TITLE
Model > Probability Distributions > Show Model dialog

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1752]
This is under Models > Probability Distributions.  For now call it "Tables Plus".  It is additional to the two existing entries.
It is to give probability tables and also to provide graphs of individual distributions.
It uses the pdst and qdist commands in the mosaic package.  
1. At the top of the dialogue there are radio buttons with the 2 labels "Probabilities" and "Quantiles".  Quantiles is the default.
2. There is the usual control with the data frame and columns.  It should just display numeric columns.
3.  There is a (possibly new?) single receiver.  The new aspect is that you could either there have a single number or a set of numbers, or a (single) column. 
4. The label for this receiver is "Values" if the radio button is set to "Probabilities".  Otherwise it is "Probabilities".
5. Below the receiver is the same user control for the distributions as for the random samples.  That control needs some improvements, but not to be taken here.  For now just use the control as it is.
6. On the left, below the data control have a checkbox with the label "Graph Results".  The default is for it to be checked.
7. Below that, have a checkbox "Save Results".  Default is unchecked.  If checked, then the default names could be Prob1, if radio button is set to "Probabilities" or Quan1 otherwise.
8.  Then the usual controls at the bottom of the dialogue.

Now some additional points:
1. In using the dialogue the simplest way is if we insist that a data column is used in the receiver if the results are to be saved.   So you can type a value there (or more than 1) if the results - and possibly the graph are just produced as results.  But you need a data column from a data frame if the results are to be saved.
2. We can start with a default of 0.5 in the receiver.  (It will be overwritten if a column is selected.  We can also start with a default of the normal distribution.
3.  With those defaults OK can be enabled.  It needs something in the receiver and a distribution.  If Save Results were now selected, then OK would be disabled, because it needs a column in the receiver.
4. The data typed into the receiver need not be in order.  If it is probabilities, then all the values need to be between 0 and 1.  The commands pdist and qdist trap that situation quite well.  They also trap when values for a probability distribution is out of range, but not so nicely.  I suggest we accept those traps for now, and just make sure we display those messages in R-Instat.
5. The command to run is pdist for probabilities and qdist for quantiles.  The "object" saved is just the set of probabilities, or quantiles, which is perfect for our tables.  The graph is not a ggplot and is therefore not saved.  But I think the commands are fine in what they do, and we will have another dialogue to save the graphs for the different distribution.
6. Later we may wish to add some further options for pdist and qdist, but the defaults seem OK for now.
7. Here is an example of the command in quite a complicated situation:
pdist("evd",c(0,1,2,-5),loc=0,scale=0.5,qevd.type="GEV").  The only complication I found was that giving the last argument simply as "type="GEV" wasn't sufficient, because the pdist command didn't know exactly where to look for that argument.

Roger

**Comment by rdstern** [comment]
This is the main use of the dialogue.  It will be good to get this version working.
Then a second version will be when a model has been fitted (usually from the Model > Once Variable > Fit Model dialogue.  Then a second selector could be available to choose an object instead of choosing a distribution.

**Comment by Lunalo** [comment]
Hi Roger,

I will Start working on this now. Thanks for the reminder.

**Comment by Lunalo** [comment]
@rdstern 

I am now set to add the r code to this dialog
Do we need to do it for all the distribution or for some for the start?

**Comment by rdstern** [comment]
Hi John,

Just do it for one distribution - say normal - for now.  perhaps for 2, so also binomial or Poisson.  Later we will consider how this should be generalised to many distributions.  We expect it to work for any distribution where the "p" and "d" and "q" exist, e.g. pnorm.  In each case it will either use the pdist or qdist commands from Mosaic.

Roger

**Comment by dannyparsons** [comment]
Hi John, I've had a look at this now. You were right that to do this there would need to be a change to single receiver or receiver expression. Having thought about it, we can achieve the same with a single receiver and a input textbox on top of each other with an option above for column or enter values, which hides/shows the controls. This means we don't need to change and receiver controls and makes it easier for you.
However, we will need to make changes to the distribution user control as you need this to get the parameters correctly for the dialog. This isn't in place yet. So discuss with me or David before starting on this. It may be this dialog has to wait until work on that control is done.

**Comment by rdstern** [comment]
Danny, I am not sure whether there has been progress on the control yet?  It would be good if we could  get this dialogue working soon, so we can test the new distributions with this dialogue as well as random samples and the one variable stuff.  We are starting to add more distributions into the software now.

**Comment by dannyparsons** [comment]
@Lunalo We may build functionality in to the Distribution class to make this easier later, but for now you can get all the information you need.

From looking at the `pdist` function quickly, the main things you need are the distribution name and the parameters entered by the user for that distribution. If you have a `ucrDistributionsWithParameters` control then you access both of these from the `clsCurrDistribution` (a Distribution object) and `clsCurrRFunction` (an RFunction) inside that control:

Get the distribution name from the current distribution object: `ucrDistributionsWithParameters.clsCurrDistribution.strRName`
This will be e.g. "binom".

Add parameters to your dialog from the current distribution function:
```
ucrBase.clsRSyntax.ClearParameters()
For Each clsTempParam in ucrDistributionsWithParameters.clsCurrRFunction
     ucrBase.clsRSyntax.AddParameter(clsTempParam.Clone())
Next
```
This is basically just "copying" the parameters from one function into another function. So you will need to do this every time the parameters change (there are Events for this). You want the parameters from the current distribution function copied in your dialog's function.

All this should be possible already and that should allow you to get the dialog working. If you are not that familiar with the distributions control then I suggest having a look at something like Random Samples dialog which uses it in a similar way. And if there is any code you don't understand, just ask.

**Comment by rdstern** [comment]
I have tried this dialogue in Version 012 and it works!  Great, really great!

There is one improvement I would like and one small edit.  

1. Small edit:  When you first use it, could the graph checkbox be enabled.  Then you could just go into  the dialogue and press OK!
2. The improvement is when you uncheck "Single Value".  Then it gives you a receiver.  I would like to be able to type into that receiver or choose a column.  If you type in then it is presumably just a textbox?  You can't save anything then - have to choose a column for that.  But I would like to be able to type -1, -0.5, 0, 1, 2 (say) and it would give me the probabilities and the graph.
3.  There are other small changes I would like.
a) When you run with a single value then it doesn't save the object.  I suggest (as a general rule we should alsways do this.  In this case, one reason is that I would like more control on what is printed in the output window.  So (for now) just display the object once saved and you should get the same.
b) When I saved I thought it would be called prob1, but it is called prob11.  I don't think this function is being called correctly.  The next time it still says it will save into prob1, but I am sure it will actually be prob12!
c) Possibly for later - but this applies to many commands, so we should examine it fairly generally.  the default is to give about 7 figures in R, e.g. 0.02275013.  That's far too many.  We need ot have control over precision, both generally, and in special cases.  So here is a special case where I suggest for probabilities we just display 4 decimals.  For small probabilities we might more to significant figures.  (This needs careful discussion!)

**Comment by dannyparsons** [comment]
Have these issues been addressed now?

**Comment by Lunalo** [comment]
I can still have a look at this

**Comment by dannyparsons** [comment]
Can this be closed?

**Comment by volloholic** [comment]
@Lunalo Can this be closed now

**Comment by dannyparsons** [comment]
@Lunalo can you respond to this?

**Comment by Lunalo** [comment]
This can now be closed .

**Comment by maxwellfundi** [comment]
@dannyparsons  this looks like it can closed now
