### ISSUE TITLE
Dialogue for Models > One Variable > Fit Model 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1756]
This dialogue seems easier than I thought - at least to get started!

It will be similar and could start by adapting a copy of the Two Variable > Fit Model dialogue.  
In a copy of that dialogue for now:
a) Change the label "Response Variable" to "Variable".
b) Get rid of the "Explanatory Variable" control and the Function checkbox.
c) Move the Distribution drop down over to the right-hand side.
d) Get rid of the Model Preview checkbox and field.
e) The default prefix can be "dist"
f) For now change "Model Options" to "Fitting Options"

For now the fitting options sub-dialogue has just 4 options (radio buttons) on the main part
Maximum Likelihood (mle) - the default
Moments (mme)
Quantiles (qme) (inactive for now)
Goodness of fit (mge)

It has a tab called "Optimisation"

There is a label for a box with radio buttons "Optimisation method"
Inside the alternatives are:
1) Default (which is the default!)
2) Nelder-Mead
3) BFGS
4) Conjugent Gradient (CG)
5) SANN

The second sub-dialogue includes a plots tab.
This has 6 radio buttons:
:
No Plot
Plot all (default)
cdf plot
density plot (not for discrete distributions)
qq-plot (not for discrete distributions)
pp-plot (not for discrete distributions)

I describe how to run this dialogue below.

**Comment by rdstern** [comment]
This dialogue will make use of commands from the fitdistrplus package.  It looks excellent and has commands that correspond well to all our three dialogues, namely Fit, Choose, Use!

For the fit, described above, we can have a drop-down list of distributions.  We just choose one of these.  I need to discuss the best control with Danny, because the "Choose" will have the same distributions, but we would then be able to choose more than 1.  I wonder what control would be better, so it looks the same in both dialogues?

The distributions are (roughly) the same as we would have in the plotting of distributions and also in the random number generation, i.e. any distribution where the d, p, q functions exist (e.g. dnorm, pnorm, qnorm). So, ideally (at least now) we might be able also to type the distribution name into the pull-down.) 

One small difference in the dialogues is that plotting distributions would often be useful for the sampling distributions, t, chisquare and F.  We would not usually be wanting to generate random numbers, nor fit a model to them.  And, the plotting and random number generation requires us to provide the parameters of each distribution.  here we just need the name, because the output is to estimate those parameters.

The main command for this dialogue is fitdist(data, distribution).  This produces an object on which summary and plot etc can be used.

One slight complication (perhaps for the future) is that some of the plots are different for discrete and continuous distributions.  Hence we may want to have two separate lists?  Initially let's just get it started.

In the reasonably short term I suggest this is the simplest set where we could have all three of the dialogues we need.  Hence I strongly suggest we try this for the beta version

**Comment by rdstern** [comment]
More on the fit model  - and others a bit.
Lily, this seems to be working pretty well
1. It would be good to add the help IDs, they are 296 for Fit, 174 for Compare and 375 for Use.
2. The items below mean that the "Display Options" will have 3 tabs, namely Plot (as now), Likelihood, and Save 
2. I haven't looked in detail in the fitdist object, but assume it includes the fitted values and (possibly also the residuals).  It may have more than 1 type of residual.  If so, it would be good to have a Save tab on the sub-dialogue so these can be saved back to the data frame.  For the way this is done I assume you could check in the 2-variable case where Steve already does this.
3. This is not to spend too long, but (if it works) there is one element from fitdistrplus we could use.  That is the plotting of the likelihood curve and also the likelihood surface - I am more interested in the curve, because it is simpler, but no harm having both if they are easy.  This is only from the method of maximum likelihood.  I think this would seal the "deal" because Jane Hutton particularly said she wanted to teach them about likelihoods.  It will be worth trying a bit of this (using the fitdistrplus examples) in R-studio first to check that it is sensible.
4. In the plot sub-dialogue can you also add a Save Plot checkbox with a default name.  And also probably the same for the likelihood plot.  If it is easy, then you could add the code behind - using other dialogues that save a graph.  Then disable it, because we will only want it when the types of plot change to being ggplot graphs.
5.  This will mean that the sub-dialogue is considerably larger than it was.  That's fine.

Thanks

Roger

**Comment by lilyclements** [comment]
I haven't collected the laptop from the office yet but intend to tomorrow. I'll add in the ID's and have a start on this list tomorrow!

**Comment by rdstern** [comment]
I tried the dialogue with the survey data to model yields and it seems not to be working now.  It is working in Version 0.1, but not in the latest code I am using.

**Comment by lilyclements** [comment]
Is this latest code from after Thursday?
I think I know the issue if so and can fix it today

**Comment by rdstern** [comment]
Yes, it is the latest code.

**Comment by dannyparsons** [comment]
Need to test this again.
