### ISSUE TITLE
New Dialogue for Model > Two Variables > Use Model

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1766]
Again I have assigned this to Steve.  But someone else may construct the dialogue.
1. This can be adapted from the Fit Model dialogue.  It is likely to be a single (or at least similar) dialogue - for all the regression models.  We can start with the Two Variable case.
2. The selector is as before.  But it is for fitted models, rather than for columns of data.
3.  There is a single receiver with the label "Model".
4.  There is no "Explanatory Variable" or Function.
5.  The distribution can remain, but greyed out.  Once a model is chosen it can be completed.
6. The Model Preview becomes "Model Formula" and is again taken from the object.
7.  There is no Save Model.
8. The Display Options are as for Fit Model.  I hope they all work from the fitted object anyway, so they can all be used as they stand.
9. The "Model Options button becomes "Predict"
   I think that is all that is needed for the main dialogue.  The new feature is then the Predict sub-dialogue.  That will come as an additional comment below.

**Comment by stevekogo** [comment]
I am going to start working on this right away.

**Comment by rdstern** [comment]
Great.  Many thanks.

**Comment by AlexSananka** [comment]
@dannyparsons can this be closed now?

**Comment by dannyparsons** [comment]
thanks
