### ISSUE TITLE
Adding infilling of missing values in Organise > Data Frame > Replace

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1779]
This is still to be added.
There is a routine, called fill in the tidyr package.  I think Danny is reluctant to use this, because it takes (or returns) a data frame, rather than a column.  There is an alternative called na.locf in the zoo package.  I can not judge if this is better.

If neither of these is simple to implement, then I suggest we mark this as a "still-to-do" task and consider writing our own routine.  It should be quite easy to do.  This would then wait until after the beta is released.  (I would like this feature eventually, but it could wait.)

Roger

**Comment by dannyparsons** [comment]
na.locf looks very powerful with lots of extra options and happy using something from zoo package. I think it's good enough.

**Comment by stevekogo** [comment]
@rstern If this task is not taken by someone else, I  am happy to handle it.

**Comment by rdstern** [comment]
Can do, but there is a lot starting to come in on climatic.  I think that might be better?

**Comment by stevenndungu** [comment]
I think this has been implemented on dlg Replace. @dannyparsons this could closed.

**Comment by dannyparsons** [comment]
We haven't actually done this part yet and Roger will be very pleased you're raised this again, it's still to do!

**Comment by stevenndungu** [comment]
Ok great. I was looking at both functions; `na.locf` and `fill` which sounds easy and quick to put this in place. I will be OK to have  `na.locf`  done now that you seemed to have agreed on with Roge unless otherwise.

**Comment by dannyparsons** [comment]
Thanks. What do they both return? I think my issue before was the one function was done on a whole data frame, and returned a data frame, whereas it's more sensible for us to use a function that works on a column.

**Comment by stevenndungu** [comment]
`fills`  replaces missing values in, using the previous entry. This can either be  backwards or forward approach.  This is to mean  that for the forward approach it  replaces subsequent missing values using the  first value encountered till the next value in the column that is found to be non-missing, again the next non- missing value is used to replace missing values to the next non-missing value all the way to the bottom of the column. For the backward approach the vice vice-versa happens.

For  `fill`;
`fill(data, ..., .direction = c("down", "up"))`
-this can take multiple columns at the same time doing the same thing through the columns intended.
-updates the existing data frame

`na.locf`
`na.locf(object, na.rm = TRUE, ...)` Does a similar thing to  `fill` with change of parameter  `fromLast` from `TRUE` to `FALSE`.
-This can only work with one column at a go. ie works with a vectors
-if the first or the last value  of the vector is missing ,it reverses using the opposite approach to fill up the missing value which is a plus for this over `fill`  ie
`> bz
[1] NA  1  4 NA NA  5 NA
> na.locf(bz)
[1] 1 4 4 4 5 5
> na.locf(bz, fromLast = TRUE)
[1] 1 1 4 5 5 5
> na.locf(bz, fromLast = FALSE)
[1] 1 4 4 4 5 5`

compare this with;

`bz1 <- c(NA,NA,4,NA,NA,5,NA,NA,NA)
bz2 <- c(NA,NA,10,NA,NA,5,20,NA,NA)

bz=as.data.frame(cbind(bz1,bz2))
fill(bz,bz1,bz2)
fill(bz,bz1,bz2, .direction = "up")
`
`na.locf` is quite good if especially we want to have a column to be appended to replace to to be added as replacement of an already existing column.

**Comment by stevenndungu** [comment]
therefore we can go with  na.locf which quite better than fill with more parameters that are useful over fill  ie `na.rm`, `rev`...

**Comment by dannyparsons** [comment]
Thanks Steven, this is really useful. How will this work with our dialog which allows multiple columns? I think `na.locf` should work on a data frame as well?

**Comment by dannyparsons** [comment]
I agree, na.locf looks the most useful and it could work on a single column which is useful for us as well.

**Comment by stevenndungu** [comment]
Yes. Actually for case of our dialogue we could have the multiple receiver cum single receiver which is used in plot dialogues so that as you switch from what we have to na.locf a single receiver is visible. Or have both one on top of the other (which I think is better).

**Comment by dannyparsons** [comment]
`na.locf` can work with multiple columns in a data frame so no need to change the dialog I think.

**Comment by dannyparsons** [comment]
This has been implemented.
