### ISSUE TITLE
Improvements to existing dialogues in the Organise menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1781]
I write about a number of issues here.  Any of these could later be separated into its own issue if there were a lot of discussion.
1. **Column: Calculate > Calculate.**  The feature to remember the previous calculations is not yet implemented.  Ideally this would continue (as examples) onto a new session.  Similarly Danny says that adding the "try" facility should be relatively easy?
2. **Data Frame > Rename columns.**  This currently is only for one name at a time, and that is probably a good default.  Ideally it would also be possible a) to make a sequence of names and b) to have a grid where the existing names are in one column and the new names can be typed into the second.  An alternative (is it possible?) is to type directly into the column header field?
3. **Column: Factor > Levels/Labels.**  This is already looking good.  I would like an additional second column in the grid.  The heading on the first column would be "Old levels" and the second - which would now be editable, is "New Levels".  Initially this could be the same as "Old Levels".
4. **Data Frame > Replace Values.**  This is for infilling of missing values.  It has its own issue, but I also mention it here.

None of these is vital, but they would each be useful.

**Comment by maxwellfundi** [comment]
@Lunalo was this addressed so that @dannyparsons  can close?

**Comment by dannyparsons** [comment]
I think only 1 is done so far. Others will need some discussion.
