### ISSUE TITLE
Organise menu, metadata

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1782]
This is an important set of dialogues mainly in the second half of the Organise > Data Object menu.  This is mainly a place-holder for reporting progress on these dialogues.  

At the same time there is also the Data Frame > Column MetaData dialogue to sort out, and also the Data Frame > Metadata dialogue.

**Comment by Lunalo** [comment]
@dannyparsons  

I am not sure if creating a new design for each dialog or improving the existing ones is the right option?

**Comment by dannyparsons** [comment]
We're discussed this and have some additions:

General tidying needed of the design. Dialog gives an error when creating new metadata property. Needs to be tested well. (John)
class property should not be editable (Danny)
The selector should have an "Overall" option for the Data Frame metadata (Danny)
We agreed to delete the reorder metadata dialog as metadata doesn't really have an order (John)
We agreed to combine the rename and delete metadata dialog into one dialog (John). This would be simply selecting a single property to rename or multiple properties to delete. Probably a radio button to choose between options. There may not be R methods to do this yet so discuss with Danny.

**Comment by rdstern** [comment]
The **Organise > Data Frame > Column Metadata** should go to a dialogue, not the form.  This is the same dialogue as in **Organise > Data Object > Data Frame Metadata** and  **Organise > Data Object > Metadata**.

This dialogue should have an easy access to the corresponding grid(s).
There is a new menu item, namely Organise > Metadata, (below the current Organise > Data Object menu item.  It will have 2 items, namely Metadata and Rename/Delete metadata.
In the Organise > Data Object menu delete the line and the bottom 4 items.

The view of the Metadata dialogue may depend on where it is viewed from.  Also there will be a button to get to either grid. 

One of the dialogues for Rename or Delete metadata will be changed to cover both operations.
