### ISSUE TITLE
adding discrete scales options to plot sub dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#1789]
By default ggplot ignores unused factor levels, but it should be easy to include them. e.g. for bar chart it can be done like this: http://stackoverflow.com/a/10835659/6424231
We should look into how we could have these options generally.

**Comment by dannyparsons** [comment]
This is part of the `scale_x_discrete` function which needs to be implemented generally on the axes tabs of the plot options sub dialog.

**Comment by Ogik99** [comment]
@dannyparsons  can i pick up this issue

**Comment by dannyparsons** [comment]
Yes this would be a great piece of work to get done. Although it is not a small task!

The first step is to design the tab for the sub dialog that will correspond to the `scale_x_discrete` function. Currently the continuous option (`scale_x_continuous`) has been done - if you go to Plot Options > X-Axis > choose "Continuous".
So we need a design of the controls for the "Discrete" option which will control all the parameters of the function https://ggplot2.tidyverse.org/reference/scale_discrete.html
There will need to be some careful though about how each parameter will correspond to controls but if you can come up with a proposed design that would be really good.

I would not start with doing any dialog code to link the R code until we have agreed on the design, but you should be knowing how your design will eventually link up with the R code so you'll need to understand the `scale_x_discrete` function well.

**Comment by Ogik99** [comment]
#5436

**Comment by lilyclements** [comment]
What needs to be done here? Alternatively, are functions like `scale_x_binned()` to be considered here as well?

**Comment by rdstern** [comment]
@COLIEWO can we return to this now - as part of the work on improving the bar charts dialogues.  It will still be quite tricky, so start with R first - probably using the script window in R-Instat, but maybe (also) RStudio if you need.

There is a really nice example [here](https://ggplot2.tidyverse.org/reference/scale_discrete.html#ref-examples), that will also be useful in the bar-chart practice and video.

**Comment by N-thony** [comment]
@Vitalis95 how is it going here?
