### ISSUE TITLE
Describe > Two Variable > Graphics

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#1805]
Some of the combinations are not producing sensible graphs so there are some changes we propose. A second message will follow on changes to options in the sub dialog. This is just for the main dialog:
1. Numerics by a factor - the factor column should also be x aes and not fill (the fill is also sensible and will be an option in the sub dialog)
2. Numerics by a numeric - This should do facets instead of colouring by the second numeric column.
3. Factors by a factor - swap the x and fill aes and do dodge not stack for the bars. Also add scale = "free_x" to facet_wrap so that we only see the levels for each factor in each plot (and not lots of empty levels).
4. Factors by numeric - This should have the same options as numeric by factor, but here we also need scale = "free_x" in facet_wrap because of multiple factors.

**Comment by dannyparsons** [comment]
In the sub dialog, change the word "variate" to "numeric" and "factor" to "categorical". 
Then we define categorical as "factor", "logical" or "character". So e.g. numeric by factor is treated the same as numeric by character (eventually we would like to be able to do a combination of factor/character in the receiver, but will need some work later)

The graph options are mostly ok, but can you change the radio buttons in each group box into one combox box instead.

Numeric by categorical and Categorical by numeric can have these types in the combo box: boxplot, dot plot, point plot, histogram, density plot, frequency polygon.

The others options seems ok for now.

**Comment by stevenndungu** [comment]
I have worked on rewriting this dialogue to the new system and I see this was fully addressed. @dannyparsons  this could be closed as well
