### ISSUE TITLE
Distributions in R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1813]
We will need to have the same distributions available for quite a number of dialogues in R-Instat.  Currently these include the **Organise > Generate > Random Samples**, **Model > Probability Distributions > Show Models**, and **Model > One Variable > Fit Model**.

This is my initial list of distributions.  David suggests that these should be added into the code by me working together with Lily.  Sorry Lily!

In addition to the existing information on the distributions, I would like to be able to categorise them, so we don't have to give a very long (and overwhelming) list. Of course one distinction is discrete and continuous, but my categorisation would be additional to this.  

And there is the **distr** package, which David says will change the way they implement distributions in the code.  This will be done first, before we start.

So there is quite a list of distributions in the main stats package.  I guess we want all of them.

Some are "Sampling", " "Main"
beta,
binom,
cauchy  
chisq, (sampling)
exp,
F, (sampling)
gamma
geom,
hyper,
lnorm,
multinom,
nbinom
norm,
pois,
t, (sampling)
unif,
weibull (extreme)

So far the multinomial is "odd" and important for us, (because of treatment of categorical data) so we may want to look into it separately.

Another category is **non-central**.  In R the t, chi-square and F are available as non-central.  I really like that, but as a (small) separate category.

We want extreme value distributions.  They are available in a number of packages and I don't know whether there are reasons to prefer one or other of them.

They are (from the extRemes package:
In the extRemes package there is a devd command.  This is for the extreme value distributions in the package.  This is quite important, because there is also an fevd command where we can fit any of these distributions.  And we can include covariates.  The distributions there are "type = c("GEV", "GP", "PP", "Gumbel", "Frechet", "Weibull", "Exponential", "Beta", "Pareto").  The most important (for me) is GEV, but the list is good.  Whether we should look elsewhere, so the names are clearer is for us to research.  This command produces pevd, qevd, and revd, which is what I think we need.  It may complicate the R code that the actual distribution is specified inside the devd command.
I hope Alex will be looking at extremes for R-Instat, so he can include this aspect.
For circular data we have the package circular which has a good list of distributions.  We will not want all of them, but should have examples that include skew distributions and there is a generalised von Mises distribution.  It also has a mixed von Mises distribution, which is good.
I would also like to have more mixtures of distributions, particularly a mixture of 2 normal distributions.  There is an R task view on https://cran.r-project.org/web/views/Distributions.html .  This gives far too many distributions.  And for mixtures I assume we might have a special command or use the distr package.
Finally there are also a number of distributions specially used in survival analyses.  They are in the survival package.
At the end of all this our list in dialogues should not be overwhelming.  Ideally there would also be a way of calling another distribution from our installed package if we wish.

**Comment by lilyclements** [comment]
Okay, sounds good. Is there anything you would want me to do on it right now?
Also, I assume the above list is not exhaustive or do we wish to leave out the circular distributions? I have never worked with the likes of von Mises before so not sure how it differs from the other distributions but will have a look into it on R if we do wish to include it!
Thanks,
Lily

**Comment by rdstern** [comment]
No, this isn't urgent.  For now it would be good to continue with the commands and distributions that are already there.  This is likely to be work for after our demonstration to SSD at the end of next week.

**Comment by lilyclements** [comment]
Tomorrow I will continue to add in distributions to ucrDistributions.
I have been told that @dannyparsons and @volloholic are planning to have a discussion about the distributions at some point? I'm happy to get involved
