### ISSUE TITLE
Improved toolbar

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1814]
We want to be able to view each window easily, namely Grid, Output, Log, Script.  Also the Column Metadata window and the Data Frame metadata window.  That's 6 windows, i.e. 6 new items on the toolbar.
Also important is a 7th, namely to rest the windows to our default, which is the vertical tiling of just grid (on left) and output on the right.  Informing our users about this option (i.e. toolbar item) when they start using R-Instat will help a lot with beginners.

Note there may be a better "system" of managing the Windows generally, but this is a simple addition to our current system.

We do need to think carefully about the icons for each item. 

At the same time we should review the existing items on the toolbar.  

We could also consider whether there could be an option for the size of the toolbar, etc.  This would be in our Tools > Options dialogue.

I would like this to be quite soon, so in time for our beta release.

**Comment by dannyparsons** [comment]
This is sill relevant, we need to decide on toolbar items.

**Comment by rdstern** [comment]
Genstat has lots and I find that is self-defeating.  SPSS is better.
I would like a set to be on the windows, both to set an arrangement and to view a particular window, e.g. the column metadata, sheet metadata and log windows in particular.

**Comment by dannyparsons** [comment]
We should do something on this for the next version.

**Comment by volloholic** [comment]
@maxwellfundi this is related to the other toolbar issue. Would be nice to have something reasonable for next week. Doesn't have to be you working on this but could you make sure someone is.

**Comment by maxwellfundi** [comment]
Just to keep a record we want to have a toggle button to include commands on output or not on the tool bar.

**Comment by maxwellfundi** [comment]
@dannyparsons do we know what icons we can use for these tools bar items?

**Comment by dannyparsons** [comment]
I don't have any images in mind. Are there free ones we can use online?

**Comment by maxwellfundi** [comment]
I think we can have just toggle buttons here with a tool tip if the user rolls the mouse over those icons. @dannyparsons @rdstern Could we just have like small icons. Possibly find some online which i would share and see if we could use them?

**Comment by dannyparsons** [comment]
Yes I think many toolbar buttons would be toggle buttons. There are lots of free and open icon images online. Search around, the problem will be finding ones that match the different windows. However, they don't need to be perfect at first.
