### ISSUE TITLE
Organise Factor Contrasts Dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1838]
I think this is John, at least for some of the front end!

This is the organise > Factor > Contrasts dialogue.

It starts deceptively simply.  You need:

a)  The data selector within a data frame.
b)  A single data receiver.  This is already a factor column, so the data selector should show only factor columns.
c)  A set of radio buttons, possibly as follows:
a.  Current contrasts  (I think there always are a default set.  I think it is Helmert for an ordinary factor and polynomial for an ordered factor)
b.  Helmert
c.  Polynomials
d.  Treatment/Control
e.  Sum to Zero
f.  User Defined (overwrite)
d)  There is a checkbox “Overwrite existing contrast columns.” The default is that it is ticked.  If so, then the new contrasts will be the same as the existing ones.  If not, then there will be an additional set of columns. 
e)  Then there is a grid.  The first two columns of the grid are the factor ordinals, and the Level/Label.  There may (of course) be more columns for some factors.  
f)  There are then (number of levels – 1) columns.  They could be called Contr1, ….
g)  Ideally you should be able to give them your own names if you wish.  But the factor command would know them as the contrasts.  Ideally so would the Instat object.
h)  Now come the tricky bits.  
i)  If you look at the Factor itself, then you should be able to extract the current contrasts.  These would be displayed – with their names.
j)  If you choose another option in the menu – not “User Defined”, then you may have to run the contrasts command to find the contrasts, so they can be displayed in the grid.  (This command would be “behind the scenes”.  It would not appear in the output Window.
k)  The user defined contrasts would allow you to type into the grid.  (I am not sure whether we would then check that each contrast column sums to zero.  That’s what I always think of as a “contrast”, but R  may be more general.
l)  Could you also check on the possible number of contrasts.  If there are 3 levels, then can you have just one contrast?  Could you have 3?  If so, then we would need an up-down control too, “Number of Contrasts” with the default being (n-1).

This dialogue links somewhat with the other missing dialogue for factors which is to be able to look at the factor columns in a data frame.  That needs more discussion.

Roger

**Comment by Lunalo** [comment]
@rdstern  I am happy working on this

**Comment by Lunalo** [comment]
@lilyclements  can i have yor skype contact please?

**Comment by lilyclements** [comment]
@Lunalo it is Lclements1004@outlook.com

**Comment by Lunalo** [comment]
Thanks very much

**Comment by Lunalo** [comment]
Hi @rdstern  

I have done research on this and below are some of the things I found out:

1.) For unordered factors we can use contr.treatment as default but still accept "contr.poly" as default for ordered.
2.) Default number of contrast can be k-1( I settled on k to avoid confusion).

3) Let us save the output as r object since we might want use these matrices to do anova.

Lastly, I have started implementing the dialog and I happy to receive any changes that you can suggest.

Thanks.

**Comment by Lunalo** [comment]
@rdstern  @lilyclements  @dannyparsons 

I was also wondering whwther we can add contr.SAS for SAS procedures which also happen to be awrapper of contr.treatment?

**Comment by rdstern** [comment]
John,
You may want a pause on completing this dialogue to work on the factor data frame one, perhaps with Steven.  I am writing about that dialogue in relation to vlookup in Excel.  (There will later be a connection between the contrasts and the new factor data frame dialogue.)

**Comment by dannyparsons** [comment]
I have now added a method in R for John to use to set the contrasts.

It forced me to have a quick look at contrasts in R. You may know all this already but here's what I found:

Have you seen this? http://rstudio-pubs-static.s3.amazonaws.com/65059_586f394d8eb84f84b1baaf56ffb6b47f.html
It seems quite comprehensive.
I noticed the **DIY Contrasts** section talks about the confusing way R uses a matrix of contrasts and suggests you may have to do some transformations before setting it. Does this apply to us? I don't know enough about contrasts to tell. We can do transformations internally but then the stored contrasts will be different to what the user sets in the dialog if this was needed.

I also noticed that the "default" contrasts in R are also global options that can be changed.
Try running:
```
options("contrasts")
#$contrasts
#        unordered           ordered 
#"contr.treatment"      "contr.poly"
```

This may be something we also want to change?
I think the R options are something we want generally, but would need some careful thought implementing to make sure we don't mess up the user's R. So I don't think we do this now, but something to consider longer term.

**Comment by dannyparsons** [comment]
@Lunalo What is the state of this dialog now? It is disabled on the menu still.

**Comment by Lunalo** [comment]
The dialog is currently working. I will enable it on the frmMain.

It will however need further improvements in the future.

Thanks

**Comment by maxwellfundi** [comment]
This looks like it needs to be closed @dannyparsons

**Comment by Lunalo** [comment]
@maxwellfundi 

We still need to work on it. 

I will confirm when am done

**Comment by dannyparsons** [comment]
I think some more thought is needed about how exactly to display the current contrasts from within this dialog and be able to set new ones and how this links to selecting pre defined contrasts. I think 2 grids makes more sense, then but maybe the dialog is messy.

As a start I suggest @Lunalo tries to implement the option of being able to set the contrasts by typing them into a grid.

On the dialog, this means an extra radio button - user defined. When it is checked, a blank grid appears with n rows and (n-1) columns, where n is the number of levels of the selected factor. When all cells have been filled in with a number, OK can be enabled, and this will be passed to R as the new contrasts in matrix form.

I suggest @maxwellfundi gets involved in this dialog and you do it with him. @Lunalo needs to explain contrasts and what is needed in the dialog. @maxwellfundi if you look at what I've suggested above, it should seem very familiar to what you needed to do for the grid layout of combine graphs and this is where I think you can help John pass the data from the grid on the dialog to an R command as a matrix. I think between the two of you, you have everything you need to complete this task.

**Comment by lilyclements** [comment]
@Lunalo I believe I remember this dialog was finished?
Can this issue be closed or do we have further enhancements to make on the Contrasts dialog?
