### ISSUE TITLE
Adding Excel's vlookup partly through the Factor Data Frame dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1876]
For John and Steven, I wonder if you are clear on the vlookup in Excel.  At some stage it would be good for you to know about this.  James Musyoka is good at it, so you could ask him.
Here is the problem.  You have (say) a survey where one question is:

Did you like this food?
1 Yes
2 Not Sure
3 No
98 Refused to answer
99 Absent

This is quite a common situation in many surveys.  When the data are entered, then the numbers 1,2,3,98,99 are entered.  Then it could be made into a factor column and the labels added.  But there could be some practical problems in R, as follows:
a) When you add the labels you will lose the numbers 98 and 99.
b) If you have 2 districts, where in one of them there were no 98's but there were in the other, then merging could be difficult.

In Excel you would put the numbers and labels above onto a separate sheet to the data and then use vlookup to add the labels.  In R-Instat we should be able to do the same - but easier, because vlookup is nasty to use!

So eventually in R-Instat we want to be able to go both ways, i.e. from a "factor sheet" to the factor labels, and from the factor (with labels perhaps) to a factor sheet.  

The factor to the sheet is the last menu item on the factor menu.  The dialogue should be simple, i.e.

a) Usual selector, just with factor columns.
b) Single receiver
c) Checkbox (default is unchecked) with label "Add Current Contrasts" 
d) Checkbox (default unchecked)  "Replace current Factor Sheet".  This is disabled unless the factor sheet already exists.  Default is to make a new sheet.
e) Then the usual controls.

Roger

**Comment by Lunalo** [comment]
@rdstern  Thanks for task.

We have started working on it and dont forget to look at the calculator please.

**Comment by dannyparsons** [comment]
@Lunalo This is sort of working but not quite as Roger specified. Check a) - e) on Roger's message. 

There is also some work to do on the R method for this, which you said you wanted to get involved in. I made several comments to help you with this here #1887. Do you still want to work on the R method, otherwise I will do it?

**Comment by Lunalo** [comment]
@dannyparsons 

I think will start working on this tomorrow
