### ISSUE TITLE
More types of column including Ordered Factors

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1878]
This item will need discussion on this thread.  Here are my ideas:
a) We need to add "Ordered Factors" as a type of column.  I suggest this could also be on the right-click menu.
b) It would also be an additional option on the "Convert Columns" Dialogue - just below "Factor". 
c) This will make the dialogue a bit longer, which is fine.
d) We may also want another option "Logical".  This would enable us to produce logical columns.  However, we will need to be careful, because for numeric column it makes all non-zero values into TRUE.  For character or factor columns it uses the labels and is liberal with NA if it doesn't understand.  So "T" is TRUE, but "t" seems  to be NA, through "True", or "true" is TRUE, while "TRue" is NA. One safe thing to do could be to make the logical as a new column, rather than overwriting the existing column?  This is an item for discussion.
e) Are there other types?  I assume making things into date columns will be handled under our special date dialogues?
f) Now the other new aspect.  We also want to be able to take a factor sheet and use a column from that sheet.  That is our equivalent of vlookup.  This could be a separate dialogue, or could be an option on this dialogue.  My initial suggestion is that it should be a sub-dialogue on this sheet.
g) If so, then there could be a checkbox (default unchecked) that says "Use Factor Sheet".  If checked then a button becomes visible (or enabled) that says "Choose Sheet".  These are only possible if either Factor or Ordered Factor is chosen. 
h) The sub-dialogue would have a data selector, plus 2 single receivers.  The first is "Matching Column" (Optional).  This should match (in values with the column being selected in the main dialogue.  (If not chosen then the positive integers are assumed.)
i) The second is "Levels/Labels (Optional)".  If that is chosen then it adds those labels to the factor column.
j) Although each of the columns is optional at least one should be chosen.  So if the checkbox is ticked (on the main dialogue then OK is not enabled until one of those columns is selected.

RDS

**Comment by rdstern** [comment]
Out of the list above, please could we make the main change to the **Organise > Data Frame > Convert Columns** dialogue.  This is to add the option "Ordered Factor" just below "Factor".  There should also be a small change to the same dialogue when opened from the Organise > Column: Factor > Convert to Factor menu.  Then there is currently just the option for Factor and the new one should also become available.

For now we don't need to add it to the Right-Click menu.

It may make a change in the Contrasts Dialogue, but that is less urgent - what is the current state of that dialogue?

**Comment by rdstern** [comment]
Thank you for adding the Convert to ordered factor to the dialogue.  In your bug checking I wonder if (and how) you have checked if it is working?  Who is doing that checking?

I tried it and was not sure it works.  So I tried again and have found 2 problems (so far).

1. I looked at the R command that you generate.  Here it is for a column from our "standard survey data set:
_# dlgConvertColumns code generated by the dialog Convert Columns
InstatDataObject$convert_column_to_type(data_name="survey", col_names="Fertgrp.")_

Then I looked at the equivalent code when you make it into an ordinary factor:
_# dlgConvertColumns code generated by the dialog Convert Columns
InstatDataObject$convert_column_to_type(data_name="survey", col_names="Fertgrp.", to_type="factor")_

So, it isn't working yet, because you don't include all the command!

2. Usually I choose the column and then decide what it is to be converted to.  So I decided to press the keys (deliberately) in the other order.  I changed the radio-button first (to ordered factor) and then chose the column.

When I do this, then OK is not enabled.  I can enable it by clicking on the radio button again, but I want OK to be enabled whichever order I press the keys.

Let's continue our bug-hunting!

Roger

**Comment by rdstern** [comment]
I am adding Francois and Maxwell to the assigned people here.  This is because at least some of the graphics dialogues don't (yet) cope with Ordered Factors.  This may also be a problem with other dialogues and is an instance where we should investigate general as well as piecemeal solutions.  

The famous ggplot2 diamonds data set is an example.  It imports and already has ordered factors.  So we can check we are coping with them in parallel with John being able to produce them in R-Instat.

If you use the **Describe > One Variable > Summarise** dialogue - just default use with all data columns, you will see that it produces the required summaries. However **Describe > One Variable > Graph** does not.  It complains about the presence of ordered factors.  If you restrict to graphing the numeric columns it is fine, except that one column (price) is integer.  It thinks this is different to numeric.

In your bug-hunting it will therefore also be good for you to consider how it chooses to graph data where some of the variables are logical!  We can produce logical columns with our calculator, e.g. with the survey data set we can do calc1=yield>40.  This sort of works, in that it treats the logical sort of as a factor.  But then there is still the inconvenience that it considers it to be a different "type".  So, if you plot the Village, Variety, FertGrp, and Calc1 together, it assumes you need a combined graph - and not facets.
Of course you can make it into a factor and then it offers facets and (oddly as we have said before) not the option of combined graphs.

Roger

**Comment by dannyparsons** [comment]
@maxwellfundi This bug of combine/facets option we discussed so hope you can fix. 
I can look at the R method to get the ordered factor/integer cases handled well. This is more an Instat object issue of handling ordered factors than ggplot implementation.
The case of logical and factors wanting to do facets I agree, but this would require more complex changes in the code and I would hope it's not urgent for the beta.

**Comment by rdstern** [comment]
My point is more general.  The (factors with logicals) is the same issue as (integers with numeric).  I hope that we can treat them as the same in the graphs, i.e. ordered factors or un-ordered factors or logicals are simply "factor-type" and hence we can have facets or combine.  Similarly "numeric" or "integer" are "numeric type" and hence are treated the same, from the possibility of the range of graphs, and hence facets or combine.

**Comment by dannyparsons** [comment]
The numeric/integer case should be working, so I'll fix that if not. Getting the other "categorical" case to allow facets generally is harder to check in the dialog as we don't have the code for the checks yet.

**Comment by dannyparsons** [comment]
@maxwellfundi I'm changing a bit of the code on the One Variable Graph dialog, let me know if you're already working on this.

**Comment by dannyparsons** [comment]
Ordered factors should be handles correctly by dialogs now. But testing is still needed to be done by everyone, maybe using the Diamonds data set as Roger suggested.

**Comment by maxwellfundi** [comment]
I am currently not editing this dialog.

**Comment by dannyparsons** [comment]
Thanks, I made some changes to fix the issues we discussed, you should check to see the changes make sense.
