### ISSUE TITLE
Climatic dialogue - presentation of daily data

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1883]
I am not yet assuming the code has been written, but I think there is something in the climate object.  Here is my go at the dialogue.  

To look at what is needed it is good that whoever works on the climatic dialogues also has tried the old Instat, so good to download this and use (say) samaru56 from the library.  Once there I can take you through the old dialogue so you see the starting point.

The new one is different in many ways.  One is that the old one only displays the results in the output window, while the new one could also display in a grid.  The old one only has one plot at a time, while now we can have facets.  Exciting!

The dialogue could have the following components:
1.  Usual data selector (just numeric columns)
2.  Single receiver with label “Date Column”
3.  Multiple receiver with label “Daily Data”.  (This may need discussion on whether there are Single/Multiple radio buttons and either single or multiple as a result.  If so, then this may come above the Date field.)  For now have multiple receiver.
4.  Label “Starting Month” with a listbox containing the months – default is January.
5.  Next to label above is another label.  “Starting Month” with up-down control from 1 to 12, with default 12.
6.  Below this is checkbox with label “Only display if Missing in Year”.  Default is unchecked.
7.  Below is checkbox with label “Save to Sheet”  If checked, then there is a text field with the label "Name".  Default for the sheet name is "Daily1".
8.  Next to item 7 (or below, or above if there isn't enough space) is an “Options” button.
9.  Then the usual controls at the bottom of the dialogue.
10. That’s the proposed main dialogue.

Now the Options:
There is the main part and 2 tabs.  In the main part you have the options in the old Instat.  They are:
a)  “Decimals” – and up/down with 0,1,2 and default 1.
b)  “Multiply by” with a text field that takes a number.  The default is 1.
c)  A checkbox with “Code Low”.  This is initially unchecked.  If checked, then there is a text field for a value, with default 0.05 and a pull-down with sample codes.  They include <blank>, (gives blank), “.”, “—“,”_”. Default is “—“ (that’s 2 minus signs, as in the old Instat.
d)  A similar checkbox with “Code High”.  Again initially unchecked.  If checked then there is a text field with default 30 and pull-down codes with <blank>, “.”, “+”,“++”.  Default is “++”.
e)  A checkbox called Shading.  Initially unchecked.  If checked, then there is a pull-down with “Low”, “Middle”, “High”.  If “Low” or “High” is chosen then there is a textbox with either 0.05, or 20 as defaults.  (There could be 2 separate textboxes, with just one visible.)  If “Middle” then both textboxes are opened. 

The first tab is called “Summary”. It just has 6 checkboxes, for the monthly and annual totals:
a)  First one is “Missing”.  Default is that this is checked. The others are unchecked.
b)  Sum
c)  Count >. This also has a textbox, with the default value 0.85.
d)  Maximum
e)  Minimum
f)  Mean

The second tab is “Plot”

For now it just has 3 options.  I assume radio buttons:

0 No Plot (This is the default)
0 Vertical Plot
0 Line Plot

Then there is a checkbox with label “Colour by Month”.  Default is unchecked.
There can be more later, but this will do for the start.  I am not even sure of the best way to do the vertical line plot (for rainfall) yet. One way is to use bar geom with stat = identity.  This site gives useful information and shows what we need. http://neondataskills.org/R/time-series-plot-ggplot/

**Comment by dannyparsons** [comment]
@rdstern I believe this has been specified somewhere else now. This is from Oct 2016. Can it be closed?

**Comment by rdstern** [comment]
It is specified in more detail as 3067.  So this can be closed.
