### ISSUE TITLE
New version of ggplot2 coming!

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1886]
This seems important, see https://blog.rstudio.org/2016/09/30/ggplot2-2-2-0-coming-soon/ 

When I look at the new features in this blog, I like them all!  It includes enhancements to the facets, which are already a great feature, to bar charts - which can now stack in "the right order" and to the themes.  It can be downloaded from github now.  

I leave it to you what you decide to do, but it does look interesting given our efforts to keep working on the graphics for the next few weeks.

Roger

**Comment by dannyparsons** [comment]
Yes all very interesting stuff! The one thing that I saw an immediate use for is `geom_col`:

> (Note also the new geom_col() which is short-hand for geom_bar(stat = "identity"), contributed by Bob Rudis.)

Because we have had to put checks in place to ensure `stat` was included to prevent an error so we could just use `geom_col` as a shorthand for standard bar chart as an option.
