### ISSUE TITLE
Climatic > Inventory plot

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1903]
This is the start of a series of points on the forthcoming climatic dialogues.  This point is more general (at this stage), because I am not sure we are ready yet for the dialogue.

In our climatic work we have been making use of an "Inventory plot".  This is a very nice feature.  We need it in the new R-Instat software.  It would be good as soon as possible.  However, if it is a lot of work, then it might wait until after November.
[Examples of inventory plots.docx](https://github.com/africanmathsinitiative/Instat/files/529234/Examples.of.inventory.plots.docx)

The attached are examples of inventory plots.  One key use is to show where there are missing values.  So:
1) First example has stations on the y, with one "row" for each station.  The years are on the x axis.  This is for rainfall and for Rwanda stations.
2) Second example has also years on the x axis and the time of year is on the y-axis.  This shows a single element in detail for one station.
3) Another instance could be elements on the y-axis for one station.
4) Also could consider elements and stations on the y-axis.

Now the current code works (I think).  But it isn't using ggplot.  So an initial question is whether we include the code "as-it-is" or do we produce a ggplot version.  Now I would obviously prefer a ggplot version, but not if it will take too long.  If it were to take (say) 2-3 days to produce a ggplot version and include it as a dialogue I would very much welcome this in the work to end November.  If it would take (say) 2 weeks, then I would suggest we leave it for now.
If we leave it for now, then a second question is whether we include the existing non-ggplot code for now?  That depends on how well the existing code is working and how much time this will take.
I think the existing code is with Francis and James, and presumably also it is part of the current climate object.  I welcome discussion.

Roger

**Comment by dannyparsons** [comment]
I had a quick look into doing the second example in ggplot before, and it seemed fairly straightforward using point plots, I think. I'm not sure about the first one but it doesn't look like it would be difficult in ggplot either. It may take more time to get more flexible options working well, but my initial reaction is that this should be possible by end of November in ggplot, at least for two examples in your document, and possibly more.

**Comment by rdstern** [comment]
Great.  Let's try that.

**Comment by stevekogo** [comment]
I am going to handle this issue. @jamusyoka should share a more stable version of the climate object since the version in github is quite unstable and the inventory plot does not even work.

**Comment by volloholic** [comment]
Danny and I will work on a totally new implementation of the climate object based on the Instat object. I suggest this waits until that has been moved on a bit maybe next week.

**Comment by dannyparsons** [comment]
Yes, the old climate object will not be useful to look at at the moment. 
But learning how to do these inventory plots in ggplot could be done any time. Again, the old climate object did them without ggplot so looking at that code probably isn't useful. James may have some images of the output from the inventory plots in the climate object which might be useful to compare with what can be done in ggplot.

**Comment by maxwellfundi** [comment]
This is also on my list of things to do. I will have a look at how to create the inventory plot in ggplot. @stevekogo will maybe later on with climate object

**Comment by maxwellfundi** [comment]
I have looked at how to make the Inventory plot and its easy to do using point plots. 

We have discussed with @stevekogo  and we are happy with it.

**Comment by maxwellfundi** [comment]
@dannyparsons this can now be closed. We already got the new great version of inventory plot
