### ISSUE TITLE
Wind roses

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1908]
I would now like to catch up with the current state of the windrose dialogue and plot.  This also linkis to the possible packages we could be using.  Maxwell, perhaps you have already?  I am also copying Steve Kogo on this topic, because I raise some general issues.

The general issue is that Met Services seem to be obsessed by wind roses.  So it would be good to "nail" that area by the end of November.  And it should be quite easy.
However, wind roses are (usually) to plot wind direction and wind speed together.  There are also:

a) Other types of data where the same type of plot would apply.  For example extreme rainfall and date at which it occurs.  Time of day for rainfall starting together with the amount.

b) The wind rose is also special in plotting a circular variable (wind direction) together with another numerical variable.  It would be good to also have other graphs for circular data, e.g. to plot just the wind direction.

There are 6 packages I have found with procedures for wind roses.  Most also have other types of graph for circular data too.  I list them below, because they are also interesting for other parts of R-Instat.

**1) clifro.**  I list this one first, because it is the only package I have found that uses ggplot2 for the wind roses.  It is designed mainly to make it easy to extract and use New Zealand Met data.  It would be good to explore the package more.  It could have other routines that are of interest, and also could give ideas for our future work in relation to climsoft. I have not been able so easily to run the examples in clifro. 
More in ggplot2.  Before going to other packages I found this reference useful.  http://rstudio-pubs-static.s3.amazonaws.com/3369_998f8b2d788e4a0384ae565c4280aa47.html 
It shows a sensible histogram using polar coordinates in ggplot2.  It then uses the circular package for more plots.  But it raises the question for me on whether we could (at least initially) stay with just ggplot2 graphs?

**openair.** This is a package for air pollution data.  It does not use ggplot, but does have a facility for facets. 
**plotrix.**  This has lots of plotting, but not using ggplot2.  It was an early contender, because it has an example of the wind rose in the way done by the Australian Met Service.
**oce.**  This is a huge package and for oceanographic data.  It has a vignette and claims to be also for teaching.
**circular** This has not been updated since early 2015 and is not much approved of by CRAN.  But it has a range of circular plots.  We will (I think) have to make use of this package for other aspects of analysing circular data - though perhaps not before the end of November.
However this package does have other types of graph for circular data that goes round a circle.  I wonder how easily they can be done in ggplot2?
**CircStats** This may be one we don't need to use.  It is the other package on circular statistics.

I now realise that I am falling into the standard R "trap", namely that there are often many packages for a given task.  Part of our job in R-Instat is to make it easy for users, and an aspect of this is that we make some choices for them.

So, having given this long list I suggest we proceed initially by using clifro for the wind roses, simply because it uses ggplot.  Maxwell, it would be good to see the current dialogue.  Then perhaps this can be the start.  Then we can decide whether other circular plots will have a different dialogue, or can use options on this one.

 Roger

**Comment by isedwards** [comment]
This is definitely not meant to distract you... but I'd be interested to know whether it would be possible to extract the coordinates of the polygons that make up each of the components of the wind rose.

Using the x, y polygon data from the plot, it would not be too difficult to transform the data into longitude and latitude values with the center point on the original sensor location.  This would allow wind roses to be drawn (at various sizes) on maps, e.g.

![Wind rose plotted in Google Earth by WRPlot](http://www.weblakes.com/products/wrplot/images/features/wrplot_view_google.jpg)

**Comment by rdstern** [comment]
I was trying the wind rose diagram in preparation for the ICCS5 meeting.  It is very disappointing and I suggest it shouldn't be used
[Legon_Seth_Owusu_aimsgh-essay-1516.pdf](https://github.com/africanmathsinitiative/Instat/files/801786/Legon_Seth_Owusu_aimsgh-essay-1516.pdf)

I gave the list of possible packages above to look at.  And there is Seth's MSc project to guide us as well.  That shows how exciting we could be here.  

I tried the existing dialogue and it ignores all that and simply produces a ggplot histogram.  I tried it on a library dataset, called mydata from the openair package.  This has columns called wd and ws.  It took so long (perhaps 15 minutes) I first assumed it was broken, and it then produced a miserable plot (I think because the histogram width is set to 1 degree!).

Has this been tried?  We must do better than this.  Please can we discuss what our plans should be, after the meeting.  Currently this does not show R-Instat in a very good light.  Steve I suggest you don't demonstrate it at the meeting.

**Comment by rdstern** [comment]
My suggestion would be that we don't get into circular too much before July.  But we do show the potential in 2 ways:

1) For circular data we make sure that it is easy - in our ordinary graphics - to get polar plots with ggplot2.
2) Then we do a version of wind roses using (at this stage only the clifro package - which I think is not yet installed because it is mainly for New Zealand data.  But it does do a general wind rose and it produces a ggplot object - which is good!  So let's make the special wind rose dialogue so it can do all these options - 


**Description**
Plot a windrose showing the wind speed and direction for given facets using ggplot2.
Usage
**_windrose(speed, direction, facet, n_directions = 12, n_speeds = 5,
speed_cuts = NA, col_pal = "GnBu", ggtheme = c("grey", "gray", "bw",
"linedraw", "light", "minimal", "classic"), legend_title = "Wind Speed",
calm_wind = 0, variable_wind = 990, n_col = 1, ...)_**
Arguments
speed numeric vector of wind speeds.
direction numeric vector of wind directions.
facet character or factor vector of the facets used to plot the various windroses.
n_directions the number of direction bins to plot (petals on the rose). The number of directions
defaults to 12.
n_speeds the number of equally spaced wind speed bins to plot. This is used if speed_cuts
is NA (default 5).
speed_cuts numeric vector containing the cut points for the wind speed intervals, or NA
(default).
col_pal character string indicating the name of the RColorBrewer colour palette to be
used for plotting, see ’Theme Selection’ below.
ggtheme character string (partially) matching the ggtheme to be used for plotting, see
’Theme Selection’ below.
legend_title character string to be used for the legend title.
calm_wind the upper limit for wind speed that is considered calm (default 0).
variable_wind numeric code for variable winds (if applicable).
n_col The number of columns of plots (default 1).
... further arguments passed to theme.
Details
This is intended to be used as a stand-alone function for any wind dataset. A different windrose is
plotted for each level of the faceting variable which is coerced to a factor if necessary. The facets
will generally be the station where the data were collected, seasons or dates. Currently only one
faceting variable is allowed and is passed to facet_wrap with the formula ~facet.

**Comment by rdstern** [comment]
For now the main change, which is easy, is to move the dialogue, so it is in the Climatic > Describe > Wind Speed/Direction dialogue - which is currently empty.  
I wonder if each of these might be a single dialogue, with the new radio buttons at the top.  This would be one of them (currently the only one) for the wind variables.

**Comment by dannyparsons** [comment]
@AlexSananka can you make this frmMain change?

**Comment by AlexSananka** [comment]
Yes I'll make this changes

**Comment by AlexSananka** [comment]
Can this be closed now?

**Comment by dannyparsons** [comment]
Will keep it up but move to a later milestone, thanks.

**Comment by maxwellfundi** [comment]
@evanstats please take on this task

**Comment by Muthenya** [comment]
@rdstern and @maxwellfundi first an item to clarify then a suggestion:
1.Concerning the adding of the Colour Palletes, I went through the documentation and found the try types of palletes, namely;  sequential, diverging, and qualitative. I believe this is what we need for the three radio buttons?
2. For the case of the radio buttons, I propose that they are set up the same way as in the Conversions dialog, where the elements radio buttons are set horizontally and their respective drop downs below them. This at least helps in sorting out the issue of order,i.e, the radio button checked determines the items in the drop down.

**Comment by rdstern** [comment]
I am happy with your radio buttons.

The second tab is called Titles and is a copy of the Titles tab on the full plot sub-dialogue.  I assume it can actually be the same, though perhaps not, because the code may be different for a (wind rose) function than in general.

And incidentally I find the space for the titles is very small.  There could be more visible space to type.

**Comment by rdstern** [comment]
It would be good - for an odd reason - if this could be completed and reported on (documented) by mid-March if it is not completed for this deadline.
The reason is that the CLIMSOFT meeting will discuss simplifying the installation process (of CLIMSOFT).  Currently a special wind rose programme is installed.  I believe that the wind roses in R-Instat are an improvement and it would be good to have a small document on this aspect available for the meeting.  

This document could be done using the existing version, plus judicious use of the scripts, but it would be much better if the dialogue were completed as described above.  Then adding the relevant help and also producing a separate document (our documentation team) would be excellent.

**Comment by maxwellfundi** [comment]
Am now on this today 💯

**Comment by maxwellfundi** [comment]
I have found that the colour palletes have the following options

**sequential**,-  `Blues BuGn BuPu GnBu Greens Greys Oranges OrRd PuBu PuBuGn PuRd Purples RdPu Reds YlGn YlGnBu YlOrBr YlOrRd`

**diverging**- `BrBG PiYG PRGn PuOr RdBu RdGy RdYlBu RdYlGn Spectral`

 **qualitative**- `Accent 8 Dark2 8 Paired 12 Pastel1 9 Pastel2 8 Set1 9 Set2 8 Set3 12`

I feel these options are too many and I am suggesting to have a few that make more sense to the Met people which am not sure would be which ones. These options can be overwhelming I think. @rdstern what do you think.

**Comment by maxwellfundi** [comment]
@rdstern @dannyparsons  because the titles for this plot are the same as those we currently have for the general plots, could maybe have a button that says `Add Titles` on the main dialog and then have it just open the sdgPlots but just the titles tab with others disabled? I am thinking of  not repeating code aspect here. 

Else I could just get those controls on the subdialog, or main dialog and save the user a few more clicks which is also desirable...

What do you  guy think?

**Comment by rdstern** [comment]
Hi @maxwellfundi.  I hope my description of what could be done, above - on October 11th is an answer to the question on palletes.  We currently don't have them at all in our graphics, which is a big omission generally.  This is the first example, so it would be interesting (and perhaps worthwhile) to consider having them all.  Then we have an example, at least of the range of palletes if ever we need to add them manually to another type of graph.

If this means that the process takes a little longer, then just change the milestone to the next one.

**Comment by dannyparsons** [comment]
I agree, its easier to start by adding them all in, otherwise we have to decide which ones to use. 
We can get user feedback about which ones are common and whether there are too many for them once implemented.

But I do agree in general that this list could be overwhelming to users if they are not at least categorised, so it was a good point to bring up.

For titles, I don't mind either way. It depends how important @rdstern thinks they are. If very important, then we make it as easy as possible and include the controls on the main dialog. If not so much then a link to the sub dialog might be enough.

**Comment by maxwellfundi** [comment]
@dannyparsons  As we saw in Rwanda with @Muthenya  and @rdstern  the met people were impressed by the windrose already but wanted titles as every graph like this needs a title. So I actually think the titles are very important. 

As on of now i have added all the options for the colors, just getting them to work with the dialog.

**Comment by dannyparsons** [comment]
Ok then sounds like the title controls should be on the main dialog to make that really easy for them.

**Comment by maxwellfundi** [comment]
Yeah
Regards
Maxwell Fundi
|| Phone :+254728508241||


Powered By  SalesHandy
<https://www.saleshandy.com/signup/?utm_source=gmail&utm_medium=emailfooter&utm_campaign=branding>

**Comment by maxwellfundi** [comment]
This is being reviewd by @Muthenya

**Comment by dannyparsons** [comment]
I don't think this is the best layout for choosing the colour palette. Horizontal radio buttons are meant to be for an overall choice for the dialog or tab. So it looks a little odd just as a choice for a type of palette. It's fine for a start and good the option is now there, but I think we can do better.

![image](https://user-images.githubusercontent.com/11214914/53199237-6f89e800-3616-11e9-912d-8f550e250a08.png)

I suggest either a combox box for the three types. So two combo boxes with the first controlling the other.

Or a single combo box with items categorised like below. I think this would look good.

![image](https://user-images.githubusercontent.com/11214914/53199529-39993380-3617-11e9-9873-adccff15f058.png)

I'm happy that we still want a simplified list as there are many choices here. This could just be a combo box with a few "common options" whatever we decide these are, where we just give the name and not the categories.

In general I think we could also give them better names e.g. I assume "RdBu" is Red-Blue.

**Comment by maxwellfundi** [comment]
@dannyparsons this is a good suggestion to just have the list of all these. I will look on to how we can have this kind of a combo box as it seems easier for the user.

**Comment by rdstern** [comment]
It is great that the wind rose updates are now included in Version 4.30.

A very small suggestion for an improvement.  When you click on the windrose options the colours is the default tab and then there are the windrose options.

Could they please be the other way round - so users see the options first and can then opt to do something about the colours later.

**Comment by rdstern** [comment]
Yet more windrose - small again!
a) It seems that the number of cuts **n_speeds** and **speed_cuts** are probably alternatives?  The first time I run the command (or after reset) I get the default 5 cuts.  If I go into the windrose options it adds speed_cuts="NA" to the R-code and now the number of cuts is down to 3.  I suggest that if speed_cuts="NA" or is blank then the argument should not be given.
b) If I give speed_cuts as "3,6,9,12,15, then it puts speed_cuts="3,6,9,12,15" into the command.  It should be c(3,6,9,12,15) instead.
c) In the dialogue options, the speed-cuts and the number of cuts are (correctly) alternatives.  But once I have specified the speed_cuts, the number of cuts is disabled until I type NA into the speed_cuts.  Having it blank should also do the same - it is much more intuitive.  
d) So, our "rule" is that if the speed_cuts is given, i.e. is not NA and not empty (or just spaces), then it is used.  Otherwise the n_speeds is used.  They are never there together.
e) Now the palette.  When I change it, that seems fine.  It works.  But if I then change the options, the palette changes back to its default
f) I have also been able to get the developer error on occasions, when I go into the sub-dialogue.  That is that there are multiple R conditions.  Then it goes in fine.  I assume that is probably due to the code being inter-linked.

**Comment by rdstern** [comment]
That's great if all is fixed even excluding the palette one.  There is a lot to do for the next version, so if that can be found quickly, then fine.  Otherwise I suggest you leave it for now and possibly open a new issue , that references back to this.  Then we can return to the problem on a later date after testing the dialogue more.  It isn't critical for now.

**Comment by stevenndungu** [comment]
@maxwellfundi For the two things you mentioned to me I should test - It works well. @dannyparsons this is ready for you.

**Comment by maxwellfundi** [comment]
@stevenndungu You would have commented on the actual PR, The things fixed are checked above
