### ISSUE TITLE
surveys, missing values and SPSS import into R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1918]
During our discussions with SSD we were asked about:
a) Importing into SPSS including value labels
b) Coping with multiple "missing" values or special codes in surveys, e.g. 1, 2, 3, 77=Don't know, 88=Refused, 99=Absent.

There is a good discussion of the multiple missing value issue here:
http://stackoverflow.com/questions/16074384/specify-different-types-of-missing-values-nas

That also mentions the **memisc** package, which seems interesting as follows:

a) It discusses importing from SPSS in detail, including labels in a useful vignette.
b) It explicitly discusses its way of dealing with multiple missing values.
c) It includes specific added metadata for surveys - including the question!
d) It also seems potentially useful on tabulation

The SSD staff pointed us towards the survey package, but that is much more advanced - mainly on modelling (taking account of the design), which is useful, but at a more advanced level.  This package looks much more relevant for the basic SPSS-type survey tasks, and seemingly with a set of simple commands.
It says it is: Tools for Management of Survey Data and the Presentation of Analysis Results
And the description is as follows:

"One of the aims of this package is to make life easier for R users who deal with survey data sets. It provides an infrastructure for the management of survey data including value labels, definable missing values, recoding of variables, production of code books, and import of (subsets of) 'SPSS' and 'Stata' files. Further, it provides functionality to produce tables and data frames of arbitrary descriptive statistics and (almost) publication-ready tables of regression model estimates, which can be exported to 'LaTeX' and HTML."

One of the examples is:

vote <- sample(c(1,2,3,8,9,97,99),size=30,replace=TRUE)
labels(vote) <- c(Conservatives = 1,
Labour = 2,
"Liberal Democrats" = 3,
"Don't know" = 8,
"Answer refused" = 9,
"Not applicable" = 97,
"Not asked in survey" = 99
)
missing.values(vote) <- c(97,99)
description(vote) <- "Vote intention"
wording(vote) <- "If a general election would take place next Tuesday,which party would you vote for?"
annotation(vote)
annotation(vote)["Remark"] <- "This is not a real questionnaire item, of course ..."
codebook(vote)

RDS

**Comment by rdstern** [comment]
[M2 data.zip](https://github.com/africanmathsinitiative/Instat/files/562203/M2.data.zip)

Here is an example of a data file to import from SPSS.

When I tried it seems to import sort of OK.  But nothing comes as factors, it is character or numeric.  I suppose that is OK.  But the 4th column (E_DATE) is a date and comes as a character.  I tried making it into a date.  The first time I omitted the format of the column and it crashed R-Instat.  The second time it appeared to work, but the column is still character.

The column S_DATE seems very odd.  

I also tried putting the data back into SPSS and found it came in exactly the same way and there were problems there too - perhaps this is a tough one.      

I'll also look for simpler data sets.

Roger

**Comment by rdstern** [comment]
[All household data excl subtables.zip](https://github.com/africanmathsinitiative/Instat/files/562305/All.household.data.excl.subtables.zip)

Here is a better example.  This goes easily into R-Instat and the dates are seen as dates, though they are described oddly as "POSIXct.POSIXt"

When I import into SPSS it looks exactly the same.  But I can also (in SPSS) go to View > Value Labels and then -99 9s seen as missing and the other labels (e.g. Male, Female) are also attached.

When I look at the help I find that a package called Haven seems to allo0w what we need - and (as usual) written by Hadley Wickham!  It is described here:  http://scs.math.yorku.ca/index.php/R/Importing_data_from_SPSS

What I am not clear is how R can keep track of both the -99, 1,2 and also the value labels.  Of course we probably have "space" for that in "our" metadata.  I wonder if we need that!  I think the article above seems to imply you can either import from SPSS and then transform for R, OR you can arrange that the resulting file can be exported back to SPSS.  You can't have both!

We could have some work here!  I think being able to import from SPSS and also from Stata would be useful.  I am less concerned about export back to those packages, but export to Excel remains important I guess - I suppose at least to csv.

Roger

**Comment by dannyparsons** [comment]
This is now detailed in other issues
