### ISSUE TITLE
Climatic dialogue  - climdex

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1920]
This looks like another free gift from R!  It is to implement the climdex.pcic package as a dialogue (perhaps more than one?) in the climatic menu in R-Instat.

It needs testing first and then we should conceptualise the dialogue.  One potential issue to be discussed also with David and Danny is that it seems to work in 2 stages.  The first is to produce a climdexInput object.  This comes from the climdexInput.raw command in the package, i.e. for us it comes from data already within R.  There is a dataset provided on page 45 of the guide.

For a dataset I am not yet clear whether the reference quantiles come from the same dataset, or could be from a reference period that is different, and hence they could be input separately.  This needs some playing in R before we move to the dialogue.  

The idea of the package seems to fit well with our way of using R-Instat, namely that we could have a dialogue to (perhaps have an initial look at the data, provide a summary and then produce the required object.  Then the main dialogue (or dialogues) use that object.  This will enable us to be able to choose different objects (e.g. different base periods, etc  even for a given station, if we wish.  Also I expect (and hope) that our filters can be used, so we can choose the periods in the year, etc, for when we produce the indices.  Whether we can filter once we have the object, or would filter first is for us to investigate.

Exciting.  This will be very useful.  It is different from other parts of R-Instat, which encourage flexibility.  So it helps us explain that the user can choose - R-Instat is OK with either approach, and both have their uses.  It is correct that WMO (as a central body) should aim for standards that can be compared across countries and districts.  It is also important to permit users to demand special products that fit their specific needs.

Roger

**Comment by stevekogo** [comment]
@rdstern @dannyparsons I have made some progress on this issue. It entails creating a new object for creating climdexinput object then calling the object to generate the different indices. The codes in a mess since in involved editing quite a number of files. I am going to tidy it up and make a formal pull request on this issue.

**Comment by stevekogo** [comment]
@rdstern @volloholic @dannyparsons Here is a file containing the arguments necessary for climdexInput object. We can have a discussion any time doon to discuss this. 

[Creating ClimdexInput Object from data already in R.pdf](https://github.com/africanmathsinitiative/Instat/files/547643/Creating.ClimdexInput.Object.from.data.already.in.R.pdf)

**Comment by stevekogo** [comment]
@volloholic  @rdstern @dannyparsons Here is a comprehensive document on climdex indices.
[Climdex Indices.pdf](https://github.com/africanmathsinitiative/Instat/files/548028/Climdex.Indices.pdf)

**Comment by rdstern** [comment]
Steve, it is great that this is now done.  Of course it can't be used until we link to their climate object.  I hope that will come soon.  In the meantime:
a) Could you disable OK completely, and possibly put a temporary note on the main dialogue - "Still to be enabled"
b) I really like it that you have included tool-tips on the sub-dialogue.
c) Could the indices be numbered - as in the list from climdex.
d) The whole dialogue could be called "Climdex Indices, and then the siub-dialogue could just be called "Indices".

In the longer term I wonder about the following, but I suggest we test this version first: 

d) We might choose to separate the indices into temperature (1 to 16) and rainfall (17-27).  If those were buttons on the main dialogue, then that would make the main dialogue much simpler.  And I don't think users should be encouraged to do all 27 routinely.  And if they want to, then I don't mind if they have to use the dialogue twice, particularly as the data records are likely to be of a different length for the rainfall and the temperatures - and decisions on missing values etc, could well be different.
e) I still find the main dialogue to be quite "busy".  If you agree with the split above of rainfall and temperaure, then that might solve this aspect.  Otherwise we might have either another subdialogue as well, or the one with the indices could revert to being "Options" with tabs.  Then the indices could be on the main tab and some of thje other aspects, e.g. missing value options, could be on another tab.

Well done.  I really look forward to seeing this dialogue "in action"

Roger

**Comment by rdstern** [comment]
I have been checking this dialogue.  Some parts run well.
a) It does not recognise the defined climate data.  The firlds could be completed automatically, as is done in  some of the other dialogues, e.g. start of the rains.
b) My first test - with the Dodoma data - was the annual rainfall indices.  OK except for 2.  Got error message with the percentile ones:  (indices 25 and 26), e.g.
---------------------------
Error running R command(s)
---------------------------
Error in names(pq) <- paste("q", qtiles * 100, sep = "") : 
  'names' attribute [1] must be the same length as the vector [0]
The error occurred in attempting to run the following R command(s):
InstatDataObject$add_climdex_indices(data_name="Dodoma", freq="annual", indices=list(Total_Daily_Precipitation_Exceeding_95th_Percentile_Threshold=climdex.r95ptot(ci=climdex_input)))
---------------------------
OK   
---------------------------

**Comment by rdstern** [comment]
I now did the 2 monthly rainfall indices.
They seem to work nicely except for the formatting.  The 5-day looks like this:  82.79999999999999715783 in the sheet.
I suspect this might be a more general formatting issue.  Good to discuss with David and Danny.

**Comment by rdstern** [comment]
Missing values  seems not to work.
In the Dodoma data the last year has 2 months missing and 2012 has one month missing.  I changed the criteria in the dialogue to 75 days, but couldn't see that anything has changed in the commands.  Certainly the results are unchanged.  Good if this could be checked.

**Comment by rdstern** [comment]
I tried the temperature inidces - all of them - bravely - and it just threw me out of the program.  I was using the latest compiled version.  perhaps you could check what happens here?

**Comment by rdstern** [comment]
Another thought.  Our data sets will often have multiple stations with station an extra factor column.  What happens then?  Ideally it would do each station in turn, adding the station as another column into the summary data frame.

**Comment by volloholic** [comment]
@stevekogo Can you give an update on the current state of this so someone can take over.

**Comment by stevekogo** [comment]
I did some edits on this dialog which were merged in. Someone can start with fixing the package names in the dialog.

**Comment by dannyparsons** [comment]
@shadrackkibet Can you add the package names so that this is stable for tomorrow?

**Comment by shadrackkibet** [comment]
adding packages to this shortly.

**Comment by dannyparsons** [comment]
@AlexSananka This is now done?
