### ISSUE TITLE
File > Export to OpenRefine

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#1923]
This dialog and 'Import from OpenRefine' are very similar. 

The idea is that you can export your dataframe to OpenRefine where you can make advanced changes that R-Instat cannot offer. We do not need to worry about coding anything in OpenRefine, only this dialog to export to OpenRefine, (and then another dialog which I will write up to Import From OpenRefine)

This dialog will consist of
1. A Dataframe selector, where the user can select which dataframe they wish to export
2. An input box where the user can note what they want the new name to be in OpenRefine.
The default for this could be "TheCurrentDataSetName _ cleanup" or something.
3. A check box to open the browser for OpenRefine. This is default unticked.
4. The base buttons

We could perhaps have an option to convert to CSV file too since that file type seems to work best on OpenRefine?

The R-Code for this is using the package 'rrefine'. You will need to work with @dannyparsons to get this added in

The code is
refine_upload ( file = "", project.name = "", open.browser = )

Where
File = the dataframe in 1.
project.name = the new name given in 2.
open.browser = TRUE or FALSE, depending whether 3. is checked or not.

_e.g. refine_upload(file = "MyDataFrame.csv", project.name = "MyDataFrame_cleanup", open.browser = FALSE)_

**Comment by stevenndungu** [comment]
refine_upload uploads csv files only, so the file to be uploaded by this
function needs to be converted first to csv  then uploaded (using the
refine_upload function)...I have been implementing that, (but unfortunately
am told they are overwriting one another since I was using ucrBase for both
functions). Consulting with John, Francois and Maxwell to see how to
overcome this.

**Comment by maxwellfundi** [comment]
@stevenndungu can @dannyparsons close this or is there anything else remaining?

**Comment by dannyparsons** [comment]
Some initial work has been done but it needs to be revisited. I think more discussions are needed before any more work is done on these, so I'll leave it open.

**Comment by stevenndungu** [comment]
Could we revisit our discussion on this dialogue, interested on working on further.

**Comment by dannyparsons** [comment]
Eventually, yes this would be nice to have working, but it's not a priority for the 0.2 or even 0.3 probably.
