### ISSUE TITLE
Bugs and issues from Lesotho analyses on 24 October

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1941]
**Summary:**  I did a summary by a factor where I had filtered out one level. It still insisted on giving precip as a level of the factor, though it correctly ignored the data in it. So the filter is working correctly there, but I usually don't want it to display the levels I have omitted.
I checked this with summary leaving out 15 years in the data. It still includes those levels, but with zero counts.
1. **Number of rows displayed:**  I changed the rows displayed from 1000 to 30,000 to show the data. It took ages. I pressed apply, and then it took ages again when OK was pressed. Eventually I had to restart.  This seems to be when I have a set of data frames open.  I had about 5.  When I have a single data frame it seems OK.  I wonder if we should look at this feature more generally.  We could just extend the visible data frame, or all data frames.  Perhaps we can also have options for which subset to display, i.e. not just the first 1000.  In my current data (daily from 1971) the first years are boring, because all the temperatures are missing.  Perhaps at least we could choose to disp0lay the first 1000 or the last 1000?  Perhaps more general than that.
2. There is a problem after data frames are deleted. It seems to keep something here. So when a column in a remaining sheet was then deleted (or a column was changed into a factor) it gave an error. When you look at the R code it still referred to the previously deleted data frame. I think this might be to do with the right-click menu?
3.  A more general one. If you start R-Instat and straight-away look at a dialogue - I think any dialogue, then it generates an error. Whether we want to permit dialogues to be used without a file open is a possible question.
4. A File > Save-As problem. The saving of the data file works when you click on the main part of the menu, but not on the sub-menu.
5. In the file open dialogue I had 3 files to open. In the first I had to change directory, which I did. I then had 2 further files to open from the same directory, but each time it started from the same place, i.e. it didn't seem to start from the last directory.  (This one is confusing, as on other occasions it has remembered the last file/directory.)
6. That message to change illegal names in R when you open a file is a minor curse. I suggest it be done automatically.
7. The calculator (still?) has the feature that when you double-click at the top, then it is full-screen.
8. More generally what is the difference between the initial position of the dialogue? I thought we had a rule here. I am working on 2 screens, with R-Instat on the second screen. So Organise > View Data is nicely centred on my second screen, but the next one, namely Rename Column comes of the first screen. So does the Row names dialogue. Most are OK, but Combine factors is not. Neither is Text Split, which also doesn't have a heading at the top of the dialogue. Ditto for Unstack. Transpose has a name, but is not centred. And none of the Data Object dialogues are centred, or have names. And for Organise > R-Objects only Reorder is centred. I have not checked the other menus yet.
9.  I deleted a number of data frames, so down to only one of them. The data selector in a dialogue didn't choose the remaining data frame. It was just blank. Not serious as it was there, but with just one data frame left it should have known! More generally I think there are a few tests that need to be conducted on what happens when data frames are deleted, and you te=hen want to continue with the work.
10. On filter a common one is to want to filter out NAs. I was asked how to do this.  This is very easy, i.e. !=NA works, but our main audience might need some help with that. Is there something we can do? Could we have a keyboard perhaps?

More as they arise.

Roger

**Comment by lilyclements** [comment]
Just as an additional bug which I feel we should note here,

11. On sdgLayerOptions, if I put in a variable to my geomAesthetics, then press return to my dlg, then I wish to change said variable so reopen my sdg - it is no longer enabled so I have to reset the entire dialog to be able to change this again.

**Comment by Lunalo** [comment]
@rdstern 

It is very true that some of the dialogs are losing our desired properties.

In fact, some are losing label text of the controls and also messing up with the organization of the entire dialog.

I am keen at going through the whole manage menu and other menus to correct this problem

Thanks
