### ISSUE TITLE
Please let's stop misusing Radio buttons!!!

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#1944]
This is an issue particularly for Roger but will need to be implemented correctly by others. 

Radio buttons should never be used at the top of dialogues to for things like General / Specific. They have the right functionality but are simply the wrong tool for the job. @dannyparsons Please show Roger how this should be specified.

**Comment by dannyparsons** [comment]
I think radio buttons at the top to change the dialog layout can be thought of as almost changing between two tabs, but we don't want to have tabs on the main dialog. 
But having command buttons next to each other as an alternative to radio buttons at the top could look much nicer, where the buttons change colour when clicked. 
Radio buttons going down to specify an option works well, but going across the top, buttons look clearer (also nicer for touch screen eventually). 
Some examples below of buttons implementation:

1. Two buttons that ask as "tabs"
![](http://i.imgur.com/G4HCH5X.jpg)
2. Three buttons used in the same way
![](http://i.stack.imgur.com/YAFCd.jpg)

**Comment by rdstern** [comment]
If by mentioning radio buttons I can stop David commenting on other aspects of my suggested dialogues this is good to remember for the future.

**Comment by rdstern** [comment]
I am also assigning John to this, in case he wants to change the radio buttons at the top of the Models > Probability Distributions > Show Models dialogue.  John you may want to discuss this point with the others in Maseno as well.   I don't feel as strongly as David, so you may have more important things to do.  But perhaps we can make the sort of improvement he suggests.

By the way, David is not against radio buttons overall, but just this use at the top of a dialogue I think.  If you want a discussiondirectly, then he or Danny can explain.

Roger

**Comment by dannyparsons** [comment]
I would hold off before making this change from radio buttons to command buttons at the moment. We should first decide if this will be a user control and how exactly it should work so that's it consistent across dialogs.

**Comment by dannyparsons** [comment]
There is a simple, very quick solution to this which we could implement now. For radio buttons that we would like to have as "buttons" instead of "circles" we can just change the Appearance property in design view to "Button" for each radio button. I suggest we do this now for these kind of radio buttons.

The appearance could still be improved on but I think that's something we could improve later - and do through our panel control so we could change colours etc. through the control.

**Comment by lilyclements** [comment]
I have put these new buttons on a dialog. I'm not sure about the layout chosen, however. Do we want bigger buttons, smaller buttons, do we want them in a group box? It doesn't look right to me like this but I can't pinpoint what to change
@africanmathsinitiative/developers what are your thoughts?

![image](https://cloud.githubusercontent.com/assets/21180424/24799722/be01b3ee-1b94-11e7-9e4c-6745ce7168c2.png)

**Comment by dannyparsons** [comment]
I think the examples I showed above look good. So that's probably a bit too big and I like them with no gap in between. I also like the consistent border colour of my examples. Could we try something like a blue border for these buttons?

**Comment by lilyclements** [comment]
I'll look into border colour.

I'm not so keen when there is no gap since it goes like this with the tiny gap between them
![image](https://cloud.githubusercontent.com/assets/21180424/24800815/a04627f4-1b99-11e7-85cc-11eef43fb345.png)

**Comment by lilyclements** [comment]
When I make the border thicker then this is no longer a problem with the gap. How about this?

![image](https://cloud.githubusercontent.com/assets/21180424/24802567/57b91d46-1ba0-11e7-9054-057249529e14.png)

I can't seem to change the font colour for the checked item, otherwise I would. What are your thoughts?

**Comment by dannyparsons** [comment]
That looks much nicer, I like it. I think the buttons are still a bit too dominating in the dialog, but that's a detail.

**Comment by lilyclements** [comment]
@dannyparsons this can now be closed
