### ISSUE TITLE
GeneralForGraphics -?-> PlotOptions

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#1947]
Dear all,

For the moment, GeneralForGraphics doesn't have plot options (hence no facets, no title, no themes, no scales, ...). We discussed with @dannyparsons  and @volloholic  whether we could add on dlgGenForGra a plot options button pointing to sdgPlotOptions, knowing that there is a ucrAdditionalLayers (layers tab) on both sdgPlotOptions and dlgGeneralForGraphics. Should that tab be hidden ? If not, can we then edit Layers on both the sdg and the main dlg ? 

@volloholic  wants both dlgGeneralForGraphics and sdgPlotOptions to simply mirror each other. So we could edit layers from both ends. I think that in this case, GeneralForGraphics should maybe include more "basic options for designing a general graph" than merely the Add Layers functionality. Otherwise GeneralForGraphics will just look like if it is one specific tab in sdgPlotOptions. It's a bit dry, and might benefit from some more exciting features. Maybe if we add facets or the possibility to set a title or whatever functionality seems most useful and reasonable, then the PlotOptions button would nicely consist in a link to more customisation possibilities, including all the features that where present on the main dlgGeneralForGraphics. 

@maxwellfundi @rdstern (@volloholic, @dannyparsons)  let me know what you think about this. When we agree on something we will start implementing with @maxwellfundi. 

Cheers,

François

**Comment by maxwellfundi** [comment]
I would agree that we need the plot options button on the dlggeneralforGraphics to add more functionality and features not only to the plot but to the dialog too as one would want to include things like facets to layers they create. 
It would be okay to have the Aditional Layers  on both the main dialog and the sdgplotoptions (I am not sure how easy it would to link the two) but i think it would be more clear to the user that the layers tab does the same work as the main dlgGenrealforGraphics and hence intuitively go back.  
I would suggest to have the layers on the main dlgGenrealforGraphics to be populated on the ucrAdditionalLayers on the sdgPlotOptions when the user gets to it from main dlgGenrealforGraphics and hence it could be easier to edit layers or even delete.

**Comment by dannyparsons** [comment]
Reminding you about this.
I know there's the issue of the layers tab on plot options, but starting by getting the plot options working on General is easy and makes a big different. Not being able to do facets on General is quite a drawback for example.

**Comment by FrancoisJRenaud** [comment]
Ok first challenge: no data frame on GenerellForGraphics, which one do we give to facets ? See #2270

**Comment by dannyparsons** [comment]
If a layer has been added, then the global data frame, otherwise, there's a free choice for facets.
