### ISSUE TITLE
SpecificGraph --> PlotOptions : first layer is the SpecificGraph layer? (Layers Tab >< Additional Layers Tab)

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#1948]
When we go to PlotOptions (coming from a specific graph), the Layer from the specific graph is not displayed in the Layer tab. This looks like the tab should be called "Additional Layers". After a discussion with @dannyparsons and @volloholic, we think that the first layer should be displayed as the layer coming from the main dlg. We agreed on keeping this first layer non-editable from the sdg. If it becomes editable on the sdg in the future, at least the geom should be fixed. This will also make it possible to clean the method for choosing if ApplyOnAllLayers should be default or not: if very first layer, yes, if not, no... 

If this is ok for everyone, I will implement this as stated above.

**Comment by volloholic** [comment]
Go ahead, remember that there may be more than one layer coming from the main dialog. In short we no longer want the concept of additional layers we would like all layers to be displayed on the layers tab of the sub-dialog.

**Comment by FrancoisJRenaud** [comment]
@rdstern @volloholic @dannyparsons,
I am implementing issue #1948, together with debuging #1973, within the pull request #1964 and hopefully fixing some others bugs (to be determined). I just wanted to know if you were ok with the following: 

- Instead of fixing the layers coming from the specificplotdialog, I am implementing the case where we can edit them from the plot options side as well, but then with fixed geom. I find it more coherent with what the plan is for the link between GeneralForGraphics and PlotsOptions in #1947 . On the user's side, it's more convenient to be able to edit all the layers from the layer tab, rather than having to go back to the main dialog and potentially click on SpecificGraphOptions to edit that first layer. I will consider the case of different Layers coming from the main dialog.

- Now considering that previous point is ok, I was wondering if there is any other situation in which we want the geom to be fixed when editing a layer ? If yes I can add it in the procedure deciding this when setting up the sdgLayerOptions.

**Comment by dannyparsons** [comment]
On the first point, we're happy with the idea of allowing editing of "core" layers (layers from the main diaog) and fixing the geom so it can't be changed. 
Our concern is that implementing this may be time consuming and doesn't add huge value at this time. If you can edit the core layers in this way, then when you go back to the main dialog or the "boxplot options" subdialog, everything needs to be synced which might take time to get details right. Especially if the main dialogs get more complex like point + line on one dialog, and extra options such as notchwidth on boxplots dialog. It would need edits to all specific plot dialogs. So we agree it's sensible, but I don't want you to have to spend a lot of time getting the details of this work generally, when just disabling editing those layers its still very sensible, at least for now.

Slightly confused by your second point. Fixing the geom through setting up sdgLayerOptions should already be an option. So this is how I expect you are fixing the geom in the case for point 1. So it should be needed in that setup function, even if there's only one use of it?
