### ISSUE TITLE
Bug: AdditionalLayers - EditLayer -> fixed geom :(

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#1973]
When edit a Layer in the AdditionalLayers setting, the geom is fixed. We don't want that right ?

**Comment by dannyparsons** [comment]
Probably not, the geom should be changeable. If this is changed, it has implications on the layer name which needs to be updated.

**Comment by FrancoisJRenaud** [comment]
After discussion with David, decided to keep the geom associated to a Layer fixed but start reflecting about the possibility to change the order of the Layers ... In that respect the list of parameters in the ROperator need to be an ordered list of parameter. This is not really a bug anymore...
