### ISSUE TITLE
Describe > Multivariate Dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1984]
I like the improvements in the sub-dialogues for Correlations etc.  However my favourite plot is still a mess.  

This is the ggpairs plot, which (I think you said) works fine in R itself, but not in R-Instat.  I can make it go wrong in a similar way in R itself.  What is happening is that R-Instat is treating the columns as factor columns, and not numeric.  they were numeric, so this must be in the code in R-Instat, becode ggpairs is called.

**Comment by volloholic** [comment]
Danny and I figured this out. It is actually problem with how GGgally check for column types Danny's going to write a work around and we'll suggest a fix for their code.

**Comment by rdstern** [comment]
I hope this can be fixed by us (at least temporarily) without waiting for the ggally folks.

**Comment by lilyclements** [comment]
@dannyparsons This can be closed now as we fixed this problem
