### ISSUE TITLE
Changing the dataframe

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#1985]
@africanmathsinitiative/instat 
I have been going through one variable summary and other dialogs on the describe menu .

I am not sure if we would like to be showing the current data frame on the grid whenever we change the data frame in the dialog.

One of the advantages with this is that the user is allowed to view the variable types of the current data frame.

Any idea pleas?

**Comment by rdstern** [comment]
If it is quick, then I quite like your idea that the grid changes to show the data frame in a dialogue.  I don't know if there is any downside to that.  The only one I could see is that we can change the number of rows we display in the grids.  If we had long data sets and set the number displayed to (say) 50,000, then this could take a long time.  In that case we could also have the change in data frame as an option, with the default being that it is changed.

I am also looking forward to being able to filter data-frames on the columns displayed, as well as on the rows.  I am now using some data frames with a few 100 columns and this is making both viewing the data frames and also the data selector more tedious to use.

**Comment by dannyparsons** [comment]
Switching data frames wouldn't need any additional commands to be run because the data is already loaded in the gird.
This could be an option in the Options dialog as there are cases when both implementations would be useful.

**Comment by dannyparsons** [comment]
For discussion: what is the priority of implementing this.

**Comment by lilyclements** [comment]
This would be nice to have - for the reasons outlined but also I would appreciate it as often when I do SSD work on R-Instat, I open a dialog and I'm on my dataframe_by_factor rather than my dataframe and don't notice due to similar variables. This would help to eliminate that confusion. However, the software can function and deal without it. I think this is a case of: How difficult would it be to implement?

**Comment by rdstern** [comment]
Genstat has a "Set as active sheet" on the menu and also on the right click.  For us it could be natural to have it on the right click on the bottom tabs of the spreadsheet.

**Comment by dannyparsons** [comment]
I've implemented changing the data frame in the grid when changed in a dialog. This doesn't affect how the dialog reopens to the previous data frame used by the dialog. That would be more like the "active sheet" idea which could later be implemented.

@maxwellfundi This is now in the options class, I've set the default to False. Can you add a checkbox on the options dialog for this, something like "Display dialog's selected data frame in grid".

**Comment by maxwellfundi** [comment]
@dannyparsons will have a look at this. 


thanks.

**Comment by volloholic** [comment]
@dannyparsons update?

**Comment by dannyparsons** [comment]
I believe it just needs to be added in the options dialog, unless this is already done @maxwellfundi?

**Comment by maxwellfundi** [comment]
Can be closed now
