### ISSUE TITLE
Help in Subdialogs

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#2000]
I have noticed that we do not include help in the subdialogs. As in dialogs, it would be nice to have the subdialog having its help. 
I would like the help button to lead to some help or to get disabled till we know where the subdialog help leads to. 
@rdstern  I wonder if you have any ideas about this.

**Comment by rdstern** [comment]
I quite like that idea.  In some instances (like the calculator) it is already explicit in the Help file/system.  I think it could work quite simply as corresponding sub-dialogues within the help system itself.

**Comment by dannyparsons** [comment]
@maxwellfundi You could add a Help button to subdialog buttons and then similar methods to be able to set the ID for the Help button if we did have special help pages for the sub dialog.
I think we could also find a way of having the subdialog help button automatically go to the help page of the main dialog if no ID has been set in the sub dialog, so we wouldn't have to repeat a lot of code in subdialogs.

**Comment by maxwellfundi** [comment]
There already exists a help button that currently do nothing. I wonder if we need a cancel button too. 

I am looking at how to do this. we can have a discussion later on the same.

**Comment by dannyparsons** [comment]
The Cancel would be nice but we decided not to implement at the time as it was not clear how it could work with our initial implementation.

**Comment by maxwellfundi** [comment]
Do we now know what the cancel should do?

**Comment by dannyparsons** [comment]
This relates to a general discussion we need on sub dialog implementation which we will have soon with everyone.

**Comment by maxwellfundi** [comment]
Okay, it will be good to have it actually. It will help in consistency.
