### ISSUE TITLE
dlgRestrict

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2022]
I have found a couple of bugs under Filter.
Organise - Data Frame - Filter.

1. If I apply a filter and select "Apply as Subset" and name it the same name as my current dataset it does not work (as expected) but then we get an issue if I try to re-open the dialog where it crashes
2. Sometimes when you click to "Apply as Subset" the filter does not apply to the dataset and nothing occurs upon clicking "OK"

**Comment by dannyparsons** [comment]
Can you disable to subset options for now? If we have time good to fix but don't think it has to be working for beta.

**Comment by lilyclements** [comment]
It's been disabled, shall I close this issue?

**Comment by dannyparsons** [comment]
I've removed the milestone but left open, as it's not fixed but it's been "resolved" for the beta now.

**Comment by dannyparsons** [comment]
This now appears to be working correctly.
