### ISSUE TITLE
Adding layers to specific plots

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2033]
When I do a specific plot and add a layer through Plot options, additional layers, when I click Add to do a new layer, the aes filled in from the main dialog are not pre filled in.
I'm not tagging this as beta as I still seem to be able to do the layer but I have to re-add the aes I did from the main dialog if I want them again. If this is easy to fix would be good, but if not, other urgent tasks should be done first.

**Comment by FrancoisJRenaud** [comment]
In general the link between specific plots and the plot options is quite obscure to me. For the moment I don't really understand how it's doing it's job. Now Functions such as sdgPlots.SetGgplotFunction and sdgPlots.SetRSyntax could be used in the same way as sdgPlots.SetDataFrame is in cmdOptions_Click to setup plots. And other similar functions and, if necessary, fields, could be created to fully setup sdgplots, however I suppose that things are a bit more sophisticated than what I suggest as the importance is to link our specific plot to the ucrAdditionalLayers on sdgPLots. Need to think of how this is done now and or later, ... but if I m not mistaken, all this is fully related to the sdg and linking coherence project. Could also be approched together with issues such as #1948. I m not sure it's particularly easy to fix now...
