### ISSUE TITLE
Display of more rows in the grid

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2037]
This is a feature that always comes up when people start using R-Instat.  I wonder if something could be done for the beta release.  Two suggestions are as follows:

1. It is a question of rows, so could the right-click for the rows give another little section, i.e. a line to break up, and then "Display First Rows" which is ticked by default.  You can choose instead "Display Last Rows".  This would have the nice aspect of then being sufficiently informative that a video on the grid could make a point of mentioning this aspect, and why we do it, and what the limits are, etc.
2. I also liked Danny's suggestion of a blank line and then the display of the last row in the grid, when there are more than the default number to display.  An alternative could be to have "(more)" , perhaps in the last and empty row of the initial column.  That could either just indicate that there are more, or it could be something you could press and get, say, the next 1000.

**Comment by dannyparsons** [comment]
I would like that but nervous to make such a core change at this point. I will check what could be done simply though for the beta

**Comment by dannyparsons** [comment]
Decided to delay this until after beta but mention in release notes.

**Comment by dannyparsons** [comment]
We now have a sensible way of indicating there are extra rows. Moving 1. into a new issue as may want to implement still.
