### ISSUE TITLE
Controlling the digits displayed in the grid and output

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2038]
We will have to face discussion, by people using the beta, on the precision with which we display results.  I suggest we investigate whether there is a simple, at least partial, solution.  Then at least we have started discussing the problem.

My hope is that the use of **options(digits = 5)** would itself be an improvement. Currently, by doing nothing, we are using **options(digits=7)**. 

The discussion here is quite good:
[http://stackoverflow.com/questions/4540649/retain-numerical-precision-in-an-r-data-frame](url)

It refers to another good web page and they alert us to the following:

"A discussion with many easily followed examples is in Appendix G “Computational Precision and Floating Point Arithmetic”, pages 753–771 of Statistical Analysis and Data Display: An Intermediate Course with Examples in R, Richard M. Heiberger and Burt Holland (Springer 2015, second edition). This appendix is a free download from [http://link.springer.com/content/pdf/bbm%3A978-1-4939-2122-5%2F1.pdf](url)

For more information, see e.g. David Goldberg (1991), “What Every Computer Scientist Should Know About Floating-Point Arithmetic”, ACM Computing Surveys, 23/1, 5–48, also available via [http://www.validlab.com/goldberg/paper.pdf](url)
"

My ideal would be to have this in an "options" tab in the Tools > Options dialogue.  It could be there by itself now, (i.e. for the beta release) but would later be joined by further options, including not displaying significance stars, see
[http://stackoverflow.com/questions/10638961/how-to-hide-anova-significance-levels-on-the-bottom-of-the-table ](url)

I have copied Lily on this message, because it would also be good to have more control of the precision where appropriate on individual features, and the dialogue to get correlations (**Describe > Multivariate > Correlations**) is a prime example.  We could have the (default) precision as 3 places there when the correlation matrix is displayed.  To avoid complicating the dialogue I would be happy in this instance if it were fixed at 3.  It is fixed at 7 now, and that isn't needed.

**Comment by dannyparsons** [comment]
Implemented in Options dialog
