### ISSUE TITLE
Various small issues to consider for the beta and beyond

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2039]
This thread is to start a set of smaller topics.  Most would be useful to discuss, even if no immediate action is taken.
**1) The custom control for data.**  This (usually) shows the name of the data frame, and then the columns within the chosen data frame.  When new sheets are derived their names are sometimes quite long.  This raises 2 issues:  
a) There seems no reason why the part of the control to choose the sheet couldn't be considerably wider - at least if need be.  
b) We may wish to re-think the way we automatically generate the names of new sheets.  The left part is the name of the original sheet, and an extension shows the new sheet.  So for long names they look the same in the control.
c) Where sheets have long names, perhaps there could be a right-click in that field to right justify the names.
d) That made me check, and there is a right-click in that field with lots of options I don't understand.  And nothing useful that I could find, except possibly the facility for reading right-to-left!  So right-click here would be a good issue to look at anyway!

**2) Right click in general**.  The above made me look more generally at the right-click action.  I started with the multiple receiver, and this has (sensibly) just 2 actions, namely remove and clear.  But the single receiver has, what I presume is the default. - same as mentioned above.  Is there a better default or do we treat each control separately.  Or do we disable right-click unless we have programmed it ourselves?

**3) Long column names and Types of column**.  I am concerned here with the same sort of issue in the grid, in particular with the fact that the column names can get long, and this can then hide the information about the type of column.  Here the right-click is already used a lot, and right justifying the names isn't important enough.  It would be a good right-click in the left-hand corner cell if we can use that in the future in the grid.
Here there are 2 separate issues, one is the long names themselves, and the second is the information about the type of column.  Perhaps the type could go first?  This has already been discussed.  David is keen on a different system for column types, but is cagey on what that is.

**4) Improving the look of the output.** I know there are lots of longer-term plans for this, but am concerned that this should not delay us from making small changes now that are useful and show our intentions.
a) Could there always be a blank line before the comment?  That sounds easy to me, but I have a sneaky feeling that it may be harder than it seems.
b) Could we have the option to display, or not, the R commands.  Not all our potential users will (at least some of the time) be interested in the R commands.  We should live up to "Options by (our users) context".
c) A lot of the time the R commands split into those that are interesting to any user, (who might have an interest in R)  and other commands that are largely "housekeeping".  For some of our audiences the display of all the commands is hence going to be more confusing than it helps.  Might there be a halfway house where the action commands are displayed, but not the housekeeping ones.

**Comment by dannyparsons** [comment]
On 2. have now replaced default right click menus with custom ones. But there are still some remaining default menus on things like radio buttons.

**Comment by dannyparsons** [comment]
@rdstern are there any points in here that would be worth extracting into separate issues?
