### ISSUE TITLE
ucrGeomListWithAes and relation to specific plots

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#2174]
Two small but bad looking bugs :

- Fix Aes is set to true for specific plots when calling SetupLayer (sdgLayerOptions). I don't know if this is necessary for some reason. The only real necessity that I see comes from MultipleVariables. Is there any other case where fixing is required ? Otherwise I think aesthetics that come from the main should be editable on the subdialogue. It is even necessary to not fix aesthetics that cannot be edited on the main, but only on the sub. Several calls of sdgLayerOptions result in fixing aesthetics that can then not be edited anywhere any more. 

- When doing two successive specific plots, and using the LayerOptions in both. The second time, the receivers on my subdialogue remember what has been filled in on the LayerOptions at last use. These values are never passed through to the main though. 

-

**Comment by FrancoisJRenaud** [comment]
Ah, things are going completely wrong with the ucrGeomListWithAes SetAes or whatever is not working. I ve been working on it for hours and no progress. Sometimes aes receivers are cleared, sometimes not, sometimes they remember from other dataframe (which is the worst case as then everything crashes). I don't know what to do with it...

**Comment by FrancoisJRenaud** [comment]
One clue I had at some point is that when a ucr is disabled, it cannot be filled and when it is enabled, it seems to hide/clear the prefilled content. Or something like that. But then I m not sure as the testing gave me quite unexpected random behaviours

**Comment by FrancoisJRenaud** [comment]
Got a new crash bug:  in the dlgHistogram, after coming back from LayerOptions,
        For Each clsParam In clsRaesFunction.clsParameters
            If clsParam.strArgumentName = "x" AndAlso (clsParam.strArgumentValue <> "value" OrElse ucrVariablesAsFactorforHist.bSingleVariable) Then
                ucrVariablesAsFactorforHist.Add(clsParam.strArgumentValue)
            ElseIf clsParam.strArgumentName = "fill" Then
                ucrFactorReceiver.Add(clsParam.strArgumentValue)
            End If
        Next
Pointing at next, I get : An unhandled exception of type 'System.InvalidOperationException' occurred in mscorlib.dll

Additional information: Collection was modified; enumeration operation may not execute.

At that stage clsParam.strArgumentValue is "fill"

**Comment by FrancoisJRenaud** [comment]
I think I found the problem. The problem is that in the process of opening the sdgLayerOptions, the link between ucrGeomListWithAes.clsGgplotAesFunction and dlgHistogram.clsRaesFunction is lost. Maybe when in sdgLayerOptions.InitialiseDialog(), or somewhere else. The last call of SetAes is then clearing the content of all the receivers. Will try both following fixes:

- show sdgLayerOptions, first, then setupLayer, with the risk that internal links between ucrGeomListWithAes.clsGgplotAesFunction and other clsGgplotAesFunction on other ucr's may be lost/ overwritten as it happens in the other direction...

- Not clear all receivers in the call of setaes as it is done for the moment. 

None of these is very satisfactory. The link between ucrGeomListWithAes.clsGgplotAesFunction and dlgHistogram.clsRaesFunction should be reestablished not only for SetAes to work ! Also if we don't clear the receivers, then previous values, coming from other dataframes might remain...

**Comment by FrancoisJRenaud** [comment]
Haha, showing the dialogue before setting it up obviously doesn't work... So the only way is to figure out the links better... Arf, not for beta for sure. So will leave things as they are now. See closed pull request #2200

**Comment by FrancoisJRenaud** [comment]
There is one idea that I got that works and improves things when ApplyOnAllLayers is unticked : it consists in passing dlgSpecificPlot.clsRaesFunction in the setupLayer as both Local and global aes function. Should I implement this for the beta ? Or too dangerous...

**Comment by dannyparsons** [comment]
I don't think for now, but can be noted for later.

**Comment by FrancoisJRenaud** [comment]
Should be tackled during linking rewriting between graphics sub-dialogues, ucr's and main dialogues, together with #2147
