### ISSUE TITLE
Licenses in files

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2185]
Should update licence header, maybe using https://visualstudiogallery.msdn.microsoft.com/5647a099-77c9-4a49-91c3-94001828e99e
Not for beta

**Comment by dannyparsons** [comment]
This may be a good things to revisit now that we have to edit each dialog anyway. @maxwellfundi did you look into this already?

**Comment by dannyparsons** [comment]
Implement this if easy? As a minimum we need to remove the incorrect licence header we currently have.

**Comment by volloholic** [comment]
@maxwellfundi update?

**Comment by maxwellfundi** [comment]
We can add this so easily to all files actually. So i am not sure what licence to put here. So do we need to draft our licence that will replace the current old one? 

@volloholic  @dannyparsons @rdstern i would like to hear your suggestions. 

Thanks.

**Comment by volloholic** [comment]
The current one looks fine except the first two lines.

**Comment by maxwellfundi** [comment]
@volloholic is it okay if i changed `'Instat-R`  to `R-Instat` or i just get rid of it?

**Comment by volloholic** [comment]
R-Instat is correct

**Comment by dannyparsons** [comment]
Copyright date should be 2015-2017 and second last line should not have `k` at the end.
