### ISSUE TITLE
Convert to date ?

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#2191]
Just a silly question that arose from "trying to do things with the software for testing"... Would it make sense to convert a column to date, as we convert a column to numeric etc ? I know there is make date...

**Comment by dannyparsons** [comment]
You mean other than make date dialog? Because there are so many parameters, it needs its own dialog.

**Comment by FrancoisJRenaud** [comment]
I guess make date is the one yes. I just wanted to do something like, right click, convert to date. Maybe make date could go into right click ? Doesn't really matter for now.

**Comment by dannyparsons** [comment]
Because you need to choose parameters it can't be one click, but could go to the dialog.

**Comment by FrancoisJRenaud** [comment]
Yes that's what I was thinking of.
