### ISSUE TITLE
Open file and open from library

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#2192]
Again just a small suggestion for later. Could it be nice to have open from file and open from library to be two tabs of one Open dlg ?

**Comment by dannyparsons** [comment]
Possibly yeah

**Comment by rdstern** [comment]
As we consider this option I would like the Open > File to be tested on more different file types - so we understand it better, and perhaps particularly for Stata and SPSS files that are reasonably common.

1.  I have a stata file that is called KE14_Village.  This is from Chris Clarke and looks interesting.  It has 47 columns and 4443 rows.  It doesn't import into R-Instat.
2.  I have gone into Stata and exported the file as Excel, and that imports easily.
3.  I have zipped the file.  I also had various tiny Stata files that I have also added.  They don't import either.  Can we import anything from Stata?

[village2.zip](https://github.com/africanmathsinitiative/Instat/files/667077/village2.zip)

4.  There is also a file from SPSS that we can't import - it is this nice example from a PICSA survey that had about 900 columns - so perhaps that is why.

5.  At some stage it would be good to look at the importing facilities.  However I would first like to solve the problems of importing labels (in SPSS etc).

Roger

**Comment by dannyparsons** [comment]
We can definitely import some STATA files because I've imported the corruption data from STATA. For these files, the first thing to check is whether they import into R, if not R-Instat.
Possibly a good task for @Lunalo who's done this checking before.
