### ISSUE TITLE
dlgDotPLot questions and suggestions

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#2241]
Questions about/Proposal for a few changes on  the dlgDotPlot dialogue:

- radio button to choose binaxis x or y would then associate the VariablesAsFactor main receiver to the binaxis aes and the first factor optional receiver to the other x/y aesthetic.
- The first optional receiver can then stay a factor receiver. However in genreral x axis should be allowed to get numeric values in the binaxis = "x" case.
- In multiple variables mode and binaxis "x", "variables" would be mapped to "y" aesthetic, however then the different stacks don't seem to fetch the y axis labels corresponding to their factor. They just stay at the bottom on the x axis.
Try

> ggplot(survey) + geom_dotplot( mapping = aes(x=Yield, y=Village.),binaxis = "x", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 20, stackdir = "up",stackratio = 1)
> ggplot(survey) + geom_dotplot( mapping = aes(x=Yield, y=Village.),binaxis = "x", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 20, stackdir = "up",stackratio = 0.2)
> ggplot(survey) + geom_dotplot( mapping = aes(x=Yield, y=Village.),binaxis = "x", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 20, stackdir = "up",stackratio = 0.2, stackgroups =  TRUE)
> ggplot(survey) + geom_dotplot( mapping = aes(x=Yield, y=Village.),binaxis = "x", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 10, stackdir = "up")
> ggplot(survey) + geom_dotplot( mapping = aes(x=Yield, y=Village.),binaxis = "x", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 10, stackdir = "up", position = "dodge")
> ggplot(survey) + geom_dotplot( mapping = aes(x=Yield, y=Village.),binaxis = "x", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 10, stackdir = "up", position = position_dodge(width=5))

When the roles of x and y are reversed though, everything is going as expected.

> ggplot(survey) + geom_dotplot( mapping = aes(y=Yield, x=Village.),binaxis = "y", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 10, stackdir = "center")
> ggplot(survey) + geom_dotplot( mapping = aes(y=Yield, x=Village.),binaxis = "y", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 10, stackdir = "up")

So my question would be, when going to multiple variable, should go as default to binaxis y, or even fix binaxis y ? Or leave it as it would be. Or change the mapping of variables to "fill", but then sometimes dodge would be welcome... : 

> ggplot(survey) + geom_dotplot( mapping = aes(y=Yield, x="", fill=Village.),binaxis = "y", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 10, stackdir = "center")
> ggplot(survey) + geom_dotplot( mapping = aes(y=Yield, x="", fill=Village.),binaxis = "y", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 10, stackdir = "center", position = "dodge")
> ggplot(survey) + geom_dotplot( mapping = aes(y=Yield, x="", fill=Village.),binaxis = "y", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 10, stackdir = "up", position = "dodge")
> ggplot(survey) + geom_dotplot( mapping = aes(y=Yield, x="", fill=Village.),binaxis = "y", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 10, stackdir = "up")
> ggplot(survey) + geom_dotplot( mapping = aes(x=Yield, fill=Village.),binaxis = "x", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 10, stackdir = "up")
> ggplot(survey) + geom_dotplot( mapping = aes(x=Yield, fill=Village.),binaxis = "x", colour = "red", method = "histodot",dotsize = 0.2, binwidth = 10, stackdir = "up", position = "dodge")

**Comment by dannyparsons** [comment]
I think we just need sensible defaults for the Dotplot dialog while still allowing all possibilities through the sub dialog and the general. 

> The first optional receiver can then stay a factor receiver. However in genreral x axis should be allowed to get numeric values in the binaxis = "x" case.

If you are saying x can be numeric, why are you suggesting it should only accept factors? Also, why do you say it should only be numeric when binaxis = "x"?

I don't see anything special about the VariablesAsFactor case, it's still just a numeric column and a factor column. The choice of binaxis can just be chosen as x or y for any graph.

I suggest you implement something simple, without thinking about ensuring the user gets a sensible plot. Once you've implemented something, it will be easier for people to give feedback and then others can suggest changes if they think we should prevent certain cases.

**Comment by FrancoisJRenaud** [comment]
Ok yeah, so I m just saying, if the optional receiver is not limited to x, but changes according to radio buttons to be always the non-binaxis, then it makes sense for it to be factor because when it's numeric it just does nothing. If it's just fixed to x then it should take numeric. The trick is that x as factor when y binaxis is ok, but y as factor when x binaxis is not very nice... (see examples above) On the main dialogues we want sensible graphs to appear, without too many opportunities for people to do silly things right ? So I was just asking if we want to avoid the bad case. I would agree that just leaving as it is works, but in other dialogues fill is used and it works fine as well. 

 but yes I can implement a simple thing without too much thoughts and get feedback... will be easier
