### ISSUE TITLE
Filters by column

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2248]
Danny's system for filtering by rows is excellent.  We also need to be able to manage columns.  One place that this will be done is through the "Data Options" button that is on all dialogues.  But there should also be a menu item (perhaps more than one).

The "Data Options" button will also have to be able to handle other types of information (particularly saved objects) that is increasingly being in the data selector custom control.  But this shouldn't delay our discussions on what we should be doing to be able to organise the ncolumns in a data frame well when they contain a large number of columns.

One aspect - visible one - is the name of the column.  So this links with improving the rename dialogue, which is on our list to do.  That's perhaps not so urgent now, because I would like that dialogue to be thought out as part of this more general system.

I don't think R insists on unique names within a sheet.  Perhaps we do already.  If not, then we should.

OpenRefine can do clever things with the actual names themselves, for example being able to select all those with particular strings.  I suggest we should do the same.  Then we already have a system for adding our own extra metadata and this could then be used to include (or exclude) different sets of columns.  It looks as though we can do clever find/replace on names in R using standard functions, and/or plyr or stringr, which we already use, see for example [http://stackoverflow.com/questions/11367485/rename-columns-of-a-data-frame-by-searching-column-name](url)

I am not ready for a dialogue yet, but would like more discussion on how to implement this soft of feature.  It is all like hiding columns in a spreadsheet.  But, in our case the grid is just a window onto (part of) the data frame.  Currently it is for a subset of the rows and this would be the same for the columns.  Then a partner to this is the set of columns displayed in the data selector.

**Comment by dannyparsons** [comment]
If I understand correctly, then you are not suggesting we need other concepts on top of hidden columns, but we should have more sophisticated ways of selecting which columns to hide/show 1. in the data grid and 2. in the selector through Data Options.

I think this wouldn't be too difficult to achieve once we know what we want, and it would help as part of our efforts to handle wide data.

One question - the grid is always going to be slower the more data it displays. Should we have a max columns to display? As we do for rows, which by default makes all columns past x hidden. This might be useful but I can also see complications and confusion it may cause.
