### ISSUE TITLE
Non parametric tests

### ISSUE THREAD

**Issue by stevekogo** [africanmathsinitiative/R-Instat#2251]
@rdstern We still have a collection of statistical tests yet to be added to the software. As with the non-parametric, we have sign-test(binomial test), Mann-Whitney-Wilcoxon test, Wilcoxon-signed rank test, Kruskal-Wallis test(implemented as non parametric one way ANOVA) etc. Should we implement all these in the same dialogue or have a separate dialogue for each case?

**Comment by dannyparsons** [comment]
@rdstern is it useful to keep this open?

**Comment by rdstern** [comment]
This is part of the discussions on the Fit Model 2 variables and 3 variables

**Comment by volloholic** [comment]
@stevenndungu are these part of the not general part of the 2 and three variable fit model?

**Comment by stevenndungu** [comment]
No, they are part of the Two sample case.

**Comment by stevenndungu** [comment]
This can be closed since all this options are on  the two sample option for the two var fit model and exact case of one var fit model. Once the this is enabled this will be sorted out.
