### ISSUE TITLE
Describe > One Variable > Graph

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2252]
This is looking good.

1) The sub-dialogue could be larger if need be.
2) Could the coord-flip be added?  I would be happy if (for simplicity it applied to all graphs.  Does it work well with combine?
3)  Please could the extra possible graphs be added.  We discussed before and that issue may still be open.  We certainly want jitter and violin.  Then also some combinations.  To make it simple I suggest they be added to the list, rather than making combinations "by hand".  So, in particular,  box + jitter, and violing + jitter and violin + box.

Thanks

**Comment by maxwellfundi** [comment]
@rdstern  i am looking at the open issue on this to add the violin plot 
this could be part of that work too. 

Thanks.

**Comment by maxwellfundi** [comment]
And just to make sure we are on same page, these should be for the numeric variables.

**Comment by dannyparsons** [comment]
Yes - for violin and jitter.
Of course coord flip is for everything.
It's very good you have asked for clarification - please keep doing that!

**Comment by rdstern** [comment]
I like the enhancements in this dialogue, though it seems to have taken a lot of work.  It is worth it though!
For my testing I am using the usual survey dataset (36 rows) and also the ggplot2 diamonds (50,000 rows).

Some suggestions below should be easy - like the coord-flip.  Others could wait as there is a lot of other work!

I initially take all the columns.  (By the way, I like the fact I can right-click inside the data selector and there is an option to "Add Selected", and another to "Select All".  Could we have yet another right-click option which is "Select All and Add".)
    
1. I am happy with the coord-flip on the main dialogue, but I assume it is still work in progress, as I couldn't get it to be active.  This would be very useful for the diamonds, where I currently can't see the labels for the factors - they overlap and would be much clearer if on the y axis.
2.  When (with the usual survey data) I switch to facets, then the command looks OK, and the outline of the graphs is fine but no data is visible on the graphs.

The remaining points are really enhancements:
  
3. I really like the fact you can now have the jitter.  Try it with the survey dataset.  For me the jitter is too much.  Good for discussion among you guys as you try it, i.e. whether you reduce it, (about half its current setting?) or allow another argument to be set, so the user can choose.

4. Now try box + jitter (or violin + jitter) for the diamonds data set.  Of course you should not expect too much with 50,000 points in one simple graph, but you are now the graphics experts.  Is there anything you can do to make those default plots just a bit better.  (Or could there be further options.  For example you can't see the box, or violin parts at all.  Could you, see them if the jitter were less?  Or could there be an option to make the points smaller, or partly transparent?

5. Then you could also have a quick look at violin + boxplot.  Here I think the boxplot is too wide.  The violin is the main layer and the box is mainly showing where the quartiles are.  So it could be narrower?  Is that easy?  Does it look good?

6.  Of course you could then equally experiment with Violin + Boxplot!  They would not then be equal, so I wonder if a (reasonably narrow) violin plot inside a boxplot would look good?

7.  In the "experiments" is this a good time to consider adding violin plots (and possibly both) as another option to the Describe > Specific > Boxplot dialogue?  That might be a better dialogue for any "experiments".
