### ISSUE TITLE
Describe > Specific Graphs

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2253]
I know you have been working hard on the geoms and on developing a general system.  As a bit of "light relief" could you consider what can usefully be added to the main dialogue.  This would make some simple alternatives/combinations easy, without providing the full flexibility.  If you weant the flexibility, then you have to use the sub-dialogues.

We will have to be careful that we don't clutter the main dialogues.  Francois has the graphics book and that might give ideas.  

1) I would like violin to be added as an alternative to box plots, just as pie is an alternative to bar charts.  Then could we have a checkbox to "Add Jitter".  That would apply to either and would add the default second layer.
2) For bar charts when there is a second factor, then perhaps a checkbox, or pull-down becomes enabled.  This is for dodge, etc.

3) there must be more for some of our other specific plots?  And perhaps one or two more can be added - just as Francois added rug plots.  And perhaps rug plots are an optional additional later on point (and jitter) plots?

Roger

**Comment by maxwellfundi** [comment]
I am happy to be assigned this task. 

It would be a good start next week.
