### ISSUE TITLE
Dates in the calculator

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2265]
The date buttons are disabled but we use the lubridate package already so at least the buttons that use lubridate should be enabled now.

**Comment by lilyclements** [comment]
@Lunalo I have done this since I happened to be editing on the calculator!
Do you happen to know what 'dek' and 'doy' are meant to do, however? I cannot work them out!

**Comment by rdstern** [comment]
dek is for dekades, which is 10 day periods within each month.  So in any month they are 1-10, then11-20 of the month.  The third dekad is 21-30, or 21 to 31of 21-28 or 21-29 of the month, depending on which month and also whether it is a leap year.

I need to check more on doy.  We need 2 different ones.  One is from 1-365 in ordinary years and 1-366 in leap years.  The alternative (which we use more) is 1-366 every year.  So (starting from January) 28 Feb is day 59 and 1 March is always day 61.  Day 60 only exists in leap years.  This has the advantage that days match-up irrespective of whether it is a leap year or not.

**Comment by dannyparsons** [comment]
We have methods for `doy` in the old climate object so we should look into those for these. I think R has standard methods for the 365 doy but not 366 based.

**Comment by lilyclements** [comment]
I see. Okay, so I'll leave doy and dek disabled for the time being?

**Comment by dannyparsons** [comment]
If we want 365 and 366 doy then there could be an R command for 365-doy, if we find that we could use it. Also not sure if there is a dek function already in R. Might be worth someone having a quick check for these (and any others).

**Comment by lilyclements** [comment]
I'm struggling to find an R-Command for "dek".

For "doy" I am still exploring.
So, my understanding is that if we have say "10/04" (my birthday, fyi) then this will be "101" regardless of on a leap-year or 100 on a non-leap-year.
What I have found so far is:

x <- c('10/04/2016')
yday(dmy(x))
[1] 101

Or a non-leap-year
> x <- c('10/04/2015')
> yday(dmy(x))
[1] 100

So it seems to take this into account already under the command "yday". However, "yday" is already being used in the calculator menu so I'm a little confused what we want "doy" to do?

**Comment by dannyparsons** [comment]
So `yday` is doing the 365-doy, I didn't know we already had it.

In the 366-based doy, we want, for example, 10/04 to ALWAYS be day 101. So that every day has the same day number, regardless of leap year or not. This measn 31/12 is always 366, and also in non leap years day 60 (29/02) is missing.
I don't know if any R command that does this already, if not we have written one for climate object before.

**Comment by lilyclements** [comment]
Great, got it. I'll have a look although I'm not holding my breath.
Earlier i found this
> strptime(x, "%d/%m/%Y")$yday+1
[1] 101

Which is obviously not ideal since it is a) a calculator and b) we don't always do +1.

I'll let you know if I find anything.

**Comment by lilyclements** [comment]
I see. I looked at the Lubridate PDF and couldn't see anything on there about having 366 days set for all years unfortunately. I haven't found anything in other packages (yet?) either.

I have been using a dataset lately with decimal dates, There's a really easy code to transform from decimal dates to year dates, which is date_decimal(ColName)
What are thoughts on including it? I agree it's not necessary, however, it's quick and easy to implement and could be useful?

**Comment by rdstern** [comment]
A couple of comments on the date calculations.  

1) The function called date, I was assuming would call the ISOdate function, so you give 3 arguments, namely the year, month,day coilumns.
2) The day of year with 366 days is probably simpler to do, rather than to look elsewhere.  It is just something like yday(x)+(!leap(x))*(month(x)>2). What is also useful, both in the calculator, and in the Use Date dialogue is to get the same, but starting from a given month as a second argument.  If should probably be made into a simple function.  Perhaps ask Sam to write it.
3) Maybe Sam could do dekades (and pentades - which are 5-day periods at the same time.  dekade is something like (month(x)-1)*3+(mday>10)+(mday>20).  (I am assuming mday gives the day number in the month?

Roger

**Comment by lilyclements** [comment]
1) ISOdate does make a lot more sense now I think about it! Would this be used as a way to "combine" three columns; date, month and year?
2) Sounds good.
@dannyparsons if I do this code "yday(x)+(!leap(x))(month(x)>2)" do I have to have it all displayed in the dialog calculator? Or can it just run "yday(x)" and do the rest in the background?
3) Okay sure, can speak to Sam about it next week perhaps?

**Comment by dannyparsons** [comment]
We will write our own little functions for each of these so that's its clear in the calculator. We have 3660-doy in old cliimate object. dekades and pentades we don't have so if Sam or someone can do this, great.
