### ISSUE TITLE
dlgDescribe Two Variables, ucrMultipleReceiver crashes when given a variable that has been moved using dlgReorderColumns

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#2269]
Hi, following badly step by step data analysis problem that @dannyparsons sent to @maxwellfundi and I, I skipped the step where I was supposed to convert a column to factor. Apparently that column had type NULL or something (maybe I misunderstood), but when I entered it in the First Variable receiver of dlgDescribeTwoVariables, it crashed. Get an error in the ucrMultipleReceiver GetCurrentItemTypes, at the line:
` strDataTypes = frmMain.clsRLink.RunInternalScriptGetValue(clsGetDataType.ToScript()).AsCharacter.ToList()`

Argument cannot be NULL. I guess it's clsGetDataType.ToScript() that returned strAssignTo that is Nothing or something similar. Can probably be solved easily by inserting a reality check !

**Comment by dannyparsons** [comment]
I can look into that. What were you doing that caused the crash there?

**Comment by FrancoisJRenaud** [comment]
It's explained above...

> but when I entered it in the First Variable receiver of dlgDescribeTwoVariables, it crashed. Get an error in the ucrMultipleReceiver GetCurrentItemTypes, at the line:

**Comment by FrancoisJRenaud** [comment]
> Hi, following badly step by step data analysis problem that @dannyparsons sent to @maxwellfundi and I, I skipped the step where I was supposed to convert a column to factor.

**Comment by dannyparsons** [comment]
I mean can you say generally what triggers the problem. Are you saying any time you put a variable in the receiver it crashes? Or just for this specific variable? If so, what's special about this variable that could cause the crash.

**Comment by FrancoisJRenaud** [comment]
Yes sorry, this was not clear enough indeed... So initially I thought that one of the variables I entered in the ucrMultipleReceiver had no type or something as type NULL. I got this from the error messages. Now I went through the process again, and all the variables I m working with have indeed a type. 

I was trying to find the bug again. I thought that when I did it, save result was ticked, and for the moment it seems to be constantly disabled (is that normal ?). As I couldn't find which settings would enable it, I tried to tweak the code by adding a line enabling chkSaveGraph in the set defaults and then click reset on the dilog. Didn't work, but then I added a variable in the receiver again... and there is the bug actually: I got it again when running the R command
" InstatDataObject$get_columns_from_data(data_name="", col_name="Year")" 
 where the dataframe is missing from parameters somehow, (it was still showing up in the available data frame cbo). So the error is exactly at the same place in the VB.Net code, but then it comes when trying to run an R command: " InstatDataObject$get_columns_from_data(data_name="", col_name="Year")"  I think. Didn't manage to reproduce it with another dataframe though.... I ll try a last time with the All_Prep one

**Comment by dannyparsons** [comment]
Ok that makes sense. Now it would be good to find out why the data frame string passed in is empty. Maybe it is not updating the string when the data frame is changed in the cbo? I would expect something to be handling the DataFrameChanged event.

**Comment by FrancoisJRenaud** [comment]
Didn't manage to raise the bug by simply changing dataframe and sending variable to the receiver. So I see a series of options: 

In All_Prep, the variable that causes problem (Year) is a variable created from Date (a date column created using MakeDate), using the calculator and year(Date). I also moved these variables around on the dataframe. Finally the dataframe is big...

**Comment by FrancoisJRenaud** [comment]
Yup, I think I found it... It's when you move a column around using reorder columns ... let me try to identify which of the two arrows is the bad one

**Comment by FrancoisJRenaud** [comment]
Tried on another dialog, with little arrow (moving the variable only one step). The multiple receiver on the DescribeOneVariable didn't give an error. Then again on the DescribetwoVariables it crashes same way. So little arrow is bad for dlgDescribeTwoVariables' multiple receiver...

**Comment by FrancoisJRenaud** [comment]
So tried different receivers. Only the multiple on the dlgDescribeTwoVariables crashes whenever you give it a variable that has been moved around using any of the arrows on dlgReorderColumns

**Comment by FrancoisJRenaud** [comment]
for the details of the crash, see above ... Are these pieces of info enough for you ?

**Comment by dannyparsons** [comment]
Ok that's useful, I can look into it as well.

**Comment by FrancoisJRenaud** [comment]
Oh forgot to mention there are some Or s and And s in the TestOkEnabled of dlgDescribeTwoVariables...
