### ISSUE TITLE
Tabs order in dialogs

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#2273]
@africanmathsinitiative/instat I have just noted that we might have abandoned the practice of making sure that the tabs order in a dialog is correct so that the user could also use the keyboard to Navigate around dialogs. 

Please keep in mind to set this as part of dialog implementation.

@stevenndungu  @FrancoisJRenaud  if you may not be aware of this, I am happy to help you guys get it right. 

Thanks.

**Comment by lilyclements** [comment]
@maxwellfundi I never knew this were a possibility! Would you mind explaining to me later how to do it? Perhaps via skype?

**Comment by maxwellfundi** [comment]
@lilyclements  yeah i can do that when you are ready to. maybe this afternoon. 

maxwellfundih is my skype username, please send me a contact request

**Comment by lilyclements** [comment]
Thanks, I've sent a request. My afternoon or your afternoon?

**Comment by maxwellfundi** [comment]
Your afternoon.

Regards
Maxwell Fundi
|| Phone :+254728508241||

**Comment by stevenndungu** [comment]
This is practised well by everyone now in the team which is quite nice. It could be closed now.
