### ISSUE TITLE
Grid reloading

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2279]
When the grid is refreshing, it should be disabled and there should be some visible indication to the user that it is updating. This is only really noticable for large data frames, but particuarly for things like converting columns from right click, where there isn't a dialog so you can't tell when it's finished updating.

**Comment by volloholic** [comment]
With our general fix can this now be closed or do we still need to disable the grid?

**Comment by dannyparsons** [comment]
This is less of an issue now with the new pop up box appearing after 2 second, but we should probably still disable the grid when running a command.
