### ISSUE TITLE
Graphs in Output window

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#2285]
Created this issue to keep record of our progress and start the few discussions that will be necessary for deciding the implementation strategy.

@maxwellfundi identified how to save a ggplot graphs easily with ggsave function :+1: http://docs.ggplot2.org/0.9.2.1/ggsave.html
He will add more details below.

Then I m exploring the Richtextbox and Flow document to see what's possible. So far there are different features available, such as resizing the splayed graph within the output window, saving copying image directly from the output window, inserting command buttons etc. So would probably be good to discuss a little what we want to be able to do with these graphs in the output. I remember Roger mentioning that it would be nice to open different graphs at the same time in different windows, and being able to drag them around and compare them. So might want to have something like _Right-click_ on the graph,  _open in new window_, or something ?

https://msdn.microsoft.com/en-us/library/aa970779(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/aa970909(v=vs.110).aspx

**Comment by maxwellfundi** [comment]
Yea, i found out that we could use ggsave to save graphs as an image relatively easy. This supports different types of images which include ps, tex (pictex), pdf, tiff, png, bmp and wmf as documented in 
http://svitsrv25.epfl.ch/R-doc/library/ggplot2/html/ggsave-ao.html

Now we need to decide what to fromat to use depending on what we want and their characterisctis.

**Comment by FrancoisJRenaud** [comment]
It seems like the only way we add content to the RichTextBox so far is by using AppendText in RLink, which is called in theRunScript sub.

```
 Private Sub AppendText(box As RichTextBox, color As Color, font As Font, text As String)
        Dim iStart As Integer
        Dim iEnd As Integer

        iStart = box.TextLength
        box.AppendText(text)
        iEnd = box.TextLength


        ' Textbox may transform chars, so (end-start) != text.Length
        box.[Select](iStart, iEnd - iStart)
        box.SelectionColor = color
        box.SelectionFont = font
        'TClears selection
        box.SelectionLength = 0
        ' clear
        box.SelectionStart = box.Text.Length
        box.ScrollToCaret()
    End Sub
```

So a RichTextBox is supposed to contain a FlowDocument. I didn't see where this one was set. Maybe if not set, one is created internally ? That FlowDocument is however the one where the content of the RichTextBox is stored though (as far as I understand). 

Adding grphs in the output window could be done by adding a _paragraph_ or _section_, or even _Float_ **Block** to the identified FlowDocument in the RichTextBox. That **Block** would then contain a _Float_ **Inline** that would contain the saved image.

Alternatively, I ve found this thread on the net with different methods toadd graphs in a RichTextBox. 
https://social.msdn.microsoft.com/Forums/vstudio/en-US/36a6dac3-f14e-4d8f-b376-246bb6a56717/insert-pictures-in-rich-text-box?forum=vbgeneral
A few methods are simply using Paste() into the RichTextBox immediately from the clipboard. 
This is the most elaborate one : 

Public Class Form1

```
  Dim myDir As String = "C:\Users\trujade\Desktop\temp\"
  Dim myImg As Image

  Private Sub RichTextBox1_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles RichTextBox1.KeyDown
    Try '-- since you are working w/files, use the Try..Catch not to freeze/crash your app
      Select Case e.KeyCode
        Case Keys.A
          myImg = Image.FromFile(myDir & "A.png")
        Case Keys.B
          myImg = Image.FromFile(myDir & "B.png")
        Case Keys.C
          myImg = Image.FromFile(myDir & "C.png")
        Case Else
          Exit Sub
      End Select
    Catch ex As Exception
      MsgBox(ex.Message)
      Exit Sub '-- to skip trying to add a "no image" to the clipboard.
    End Try
    Clipboard.SetImage(myImg)
    RichTextBox1.Paste()
  End Sub

  '-- block letters from being typed
  Private Sub RichTextBox1_KeyPress(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyPressEventArgs) Handles RichTextBox1.KeyPress
    e.Handled = True
  End Sub

End Class

```
I m thinking that when a graph is created in R-Instat, the temp image could simply be sent/saved to the clipboard, then this method could be used to paste the content of the clipboard in the outputwindow. Don't really know how the clipboard works, if it could be used as temp file or if we would need to create a temp file (or other). 

Then finally there is this track: 
https://msdn.microsoft.com/en-us/library/aa970917(v=vs.110).aspx
Where the methods called by the buttons could be adapted and run internally ?

there is that warning in the LoadFile function description ( https://msdn.microsoft.com/en-us/library/d76176b1(v=vs.110).aspx ) :
When loading a file with the LoadFile method, the contents of the file being loaded replace the entire contents of the RichTextBox control. This will cause the values of the Text and Rtf properties to change. You can use this method to load a previously created text or rich text format (RTF) document into the control for manipulation. If you want to save the file, you can use the SaveFile method.

But maybe the range function (used in the example above) can be used to only change part of the content...

**Comment by FrancoisJRenaud** [comment]
Note: concerning the previous comment: 

> So a RichTextBox is supposed to contain a FlowDocument. I didn't see where this one was set. Maybe if not set, one is created internally ? That FlowDocument is however the one where the content of the RichTextBox is stored though (as far as I understand). 

there is indeed a FlowDocument automatically created when not mentioned, then the property: **Document** can be used to get the FlowDocument of the RichTextBox... :)

**Comment by FrancoisJRenaud** [comment]
Scrolling through the RichTextBox methods, found that there is an undo :) and AddHandler, which sound exciting, but nothing equivalent to Addtext for images... 

The paste method or editing the FlowDocument by adding a Float (or figure depending on what features we want) are thus the options I see... + the loadfile one potentially. Still need to make sure images can be added in a Float _Inline_ object but I m pretty sure it works.

**Comment by dannyparsons** [comment]
@maxwellfundi on the file types for images - great that you've found different alternatives, but what we need is comparison of different methods. What are the advantages/disadvantages of each and particularly in relation to our use.

**Comment by dannyparsons** [comment]
@FrancoisJRenaud sounds like you are finding useful things about rich text boxes. Another thing to consider is html windows. Would that help us/make it easier/hard to add the images from R?

**Comment by FrancoisJRenaud** [comment]
> @FrancoisJRenaud sounds like you are finding useful things about rich text boxes.
Thanks !
>Another thing to consider is html windows. Would that help us/make it easier/hard to add the images from R?
 :+1: 
Will explore this tomorrow

**Comment by FrancoisJRenaud** [comment]
> great that you've found different alternatives, but what we need is comparison of different methods. What are the advantages/disadvantages of each and particularly in relation to our use.

Just to check if I get you: you want us to find other methods than ggsave to save graphs and compare them ? Or do you understand "method" in a wider sense ?

**Comment by dannyparsons** [comment]
> Just to check if I get you: you want us to find other methods than ggsave to save graphs, and compare them ? Or do you understand "method" in a wider sense ?
Not necessarily, Maxwell said:
> This supports different types of images which include ps, tex (pictex), pdf, tiff, png, bmp and wmf 
This is useful, but not useful yet for making a decision as we need to now know what the implications of using any of these different file types.

It may mean looking at different methods other than ggsave is useful, but might not be necessary if ggsave is enough for us.

**Comment by FrancoisJRenaud** [comment]
Ok, I think we are on the same page. So for instance one important thing to check is which types of files would be compatible with the options I have been drafting for adding images in the output window...

**Comment by FrancoisJRenaud** [comment]
So my knowledge on these subjects is quite limited. There exists a System.Windows.Forms.webBrowser control (_https://msdn.microsoft.com/en-us/library/sxc145fz(v=vs.110).aspx_), which makes it easy to display html files.

However, displaying/"render" html files in a richTextBox seems to be problematic. Either need to get an enriched richtextbox with added methods (_http://www.codeproject.com/Articles/12172/An-extended-RichTextBox-to-save-and-load-quot-HTML_), (_http://stackoverflow.com/questions/13509760/displaying-html-content-inside-of-a-textbox_), or convert file to RTF (_http://stackoverflow.com/questions/150208/how-do-i-convert-html-to-rtf-rich-text-in-net-without-paying-for-a-component_). 
Also found this option to "Load" html file in richtextbox, but not "render" : 
`txtBody.Text = IO.File.ReadAllText("C:\testmal2.htm") `

_https://www.experts-exchange.com/questions/27017013/How-to-load-html-file-to-richtextbox.html_

So I guess that's not what you had in mind ? The webBrowser would be separate from the output window. Can be used to display graphs separately, but then the ones that are sent to the output window would necessarily be in another format ? So not sure graphs in output + webrowser works smoothly... Can investigate the webBrowser option as merely an alternative to displaying in output window.

Asked to @Lunalo why you were suggesting html option, he said that you can indeed save graphics outputs into html files. Maybe @Lunalo you can expand on this here ? ggsave doesn't save graphics into html files though... 

So far I have the feeling that this option is a bit more tricky, but might just be because I don't have enough info yet. If we want to display graphics in another window, from what I know so far, we could simply use another flowDocument viewer or something like that. I don't know how things are done for the moment. Could check on this.

**Comment by volloholic** [comment]
Ok good to catch up on all this and see the progress being made. 

In an effort to digest all of this and move the discussion forward. From everything I've read above I would like @maxwellfundi  and @FrancoisJRenaud  to try to bring what they have done together.  Can you save the same graph using ggsave into each of the mentioned file formats. And then insert them in a Rich text box with a line of text (i.e. file type) between the images, using UIcontainer, ideally opening them directly not going via the clipboard.  

This might be most easily done in a totally new dummy project and should take more than an hour or two, if it does come back to us and explain what the difficulty is.

In particular this should help us check for differences in image quality and size of the different file types.

**Comment by FrancoisJRenaud** [comment]
Good, thanks for the feedback @volloholic ! We will try this with @maxwellfundi.

**Comment by Lunalo** [comment]
Sure @FrancoisJRenaud 

You can  achieve this by inserting the code into html tags and knit the document.

please look at https://cran.r-project.org/web/packages/knitr/knitr.pdf

**Comment by FrancoisJRenaud** [comment]
So apparently there is no FlowDocument in the RichTextBox when working on a Windows Form type of project, or something like that... 
So that option goes to rubbish. The paste option works ok, but didn't manage to find options to adapt the size of the image. For the moment it's just cut and can't resize which is not great. Otherwise need to set ReadOnly to false for pasting. Could do a set, reset before and after each paste. Also I think we are using Multiline = True in Instat for the moment, which is what gives best outcome here indeed.
Read a bit more about rtf... Rich Text Format. Could insert the image immediately as Rich Text Format in the rtf code of the RichTextBox... However this is quite technical, I have not found a ready to use kind of answer. I ve been trying to insert rtf code but didn't display. There is no append function to the Rtf property in RichTextBox. The only way is to insert the right array of characters at the right index, but I don't know how to locate that index yet... 
Still need to explore html window more ...

**Comment by FrancoisJRenaud** [comment]
> or you can disable default Internet Explorer functionality and use the control as a simple HTML document viewer. You can also use the control to add DHTML-based user interface elements to your form and hide the fact that they are hosted in the WebBrowser control. This approach lets you seamlessly combine Web controls with Windows Forms controls in a single application.

Also
https://msdn.microsoft.com/en-us/library/sxc145fz(v=vs.110).aspx

**Comment by FrancoisJRenaud** [comment]
> or you can disable default Internet Explorer functionality and use the control as a simple HTML document viewer. You can also use the control to add DHTML-based user interface elements to your form and hide the fact that they are hosted in the WebBrowser control. This approach lets you seamlessly combine Web controls with Windows Forms controls in a single application.

Also
https://msdn.microsoft.com/en-us/library/sxc145fz(v=vs.110).aspx

**Comment by FrancoisJRenaud** [comment]
Also the output window is in good progress and I have a clearer picture of what's possible or not. At this stage, it would be good to start making choices so that I don't do 4 times the amount of work that is required. The best implemented option is the WPF RichTextBox that is now including text, graphics and html reader boxes. There are just a few things that need to be fixed, such as the copy of graphs or html reader content, but I am confident that this will be feasable. In general this option is arguably more flexible than the others, but it sometimes requires a bit of coding. A last concern about it is that I add a webbrowser for each html code that is send to the output window (can be in the form of a file, or a string of html code). This might be source of inefficiency ? I am not particularly skilled at efficiency testing. Things seem to run smoothly for now. I ve implemented a class for these "added at run" webBrowsers so that this potential efficiency problem could be handled there.

I had a long and very helpful/pleasant skype with Danny yesterday during which he mentioned I should not put too much efforts on getting the two other output windows to work in case this one is doing all the job well.

However, I would like to suggest another option that you might not have considered yet, which is the use of the knitr R package, which is pretty much doing, again "for free", all, or almost all, what we are trying to display on our output window, and produces it in the form of a html file that can then be read very easily in the webBrowser output window... According to John, this file can be edited dynamically. It is also possible to add our comments and potentially to identify blocks within the html file code, but that might be a bit more tricky... Just an idea... it would require quite a bit of rewriting but it is worth at least knowing the option exists.

There are two remaining options so far. One is using the old output window, which I wouldn't recommend. It has still nice features such as zooming and the copy pasting is doing very well with pictures. However, I think blocks and almost certainly html readers are not available there (would need to translate html to rtf, I ve been exploring translation for the WPF RTB, but it is not a reasonable option, especially when it comes to translate sophisticated tags such as tables, etc...). The quality of the graphics is not as good as in the WPF RichTextBox, and the method to include graphics is copy-pasting from the clipboard...

The webBrowser output window is still quite appealing. The Windows Form version of the webbrowser actually works with some sort of block system like in the WPF RTB. It is based on the structure of the html code itself I think. I haven't been able to get it to work yet, but I hope it would be possible. That might then be a good option as well. Maybe the import of html file could be done by opening different pages ? But I don't really know how it works. Importing strings of Html code could hopefullly be performed within the same document. For the moment this is not working at all as I need to figure out how to deal with the documents supporting the content...

**Comment by rdstern** [comment]
This all sounds great, and excellent to be discussing these alternatives at this stage.  I will also forward the e-mail version to Ian Edwards, who may have some words of wisdom to help us choose between the alternatives.  And we should harass David tomorrow or Tuesday if we can find a slot.  he is going to be in Reading from Monday afternoon, and then travelling to Mtwara on Wednesday.

Francois, in the github discussion about the viewer, you mention stargazer.  Once we are able to display lots in the output window I am keen to return to the use of stargazer, or sjmisc/sjplot, etc.  We will want to display the results from our Model menu, better than we (well really R through lm and glm, etc) does, and there are lots of packages competing in this field.  It is all part of the important area of "reproducible research".  But I would like it initially also just to be able to display model outputs in ways that are really clear for our users.

**Comment by FrancoisJRenaud** [comment]
Okok, sounds good. Let us know when you manage to gather everyone for a Skype.
