### ISSUE TITLE
Make date dialogue and convert from Factor

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2295]
I have put these items together for a reason that I hope will become clear below.

If I make a date from 3 columns, (year, month, day) then sometimes those columns will have already been defined as factors.  The result is fine as long as labels have not been given to the months, in which case all the dates are given as NA.

One possible solution - and I don't see a big down-side is to use the ordinals for the months - when labels have been attached.  It is ONLY for the months, because the "labels" for the years are the years themselves.

There is one rather subtle downside that I mention below.  We might want some clever code to check for this.  But, to start I would like to know how easily this could be done.  It would improve on a whole column of missing values.

Please read on though.

When I have this labelled month column, with Jan, Feb, Mar as the labels, you might think it would be easy to right-click and make that column back to numeric.  It is very easy.  Lo and behold the whole column is immediately made into NA and there is no undo (yet!).  Please could we trap this feature on the right-click menu and improve it.  If instead you use the Organise > Convert, then it gives you the option of using "Levels" or "Ordinals".  In that situation we want to use Ordinals.  Even on that dialogue if you mistakenly use "Levels" you immediately get a column of NAs and cannot go back.  (This IS a big problem and is not so difficult if you use commands in R - it is much easier to look (and go) back.

If a factor column has non-numeric labels, then this will happen.  Could we guard against it.  With right-click for example, could we be more friendly - perhaps initially getting a new column of NAs and then saying this, and asking whether the ordinals should be used instead?  (We could do the same in the dialogue.)

Must go.  I'll write about the hidden problem with dates later.

**Comment by rdstern** [comment]
I report on some issues with dates and climatic data.  I am adding Danny into the discussion, because the problems I am hitting are simple - but messy - and affect multiple dialogues.

I am using the dodoma data from the Instat library climatic data sets.  This is a good example to test the climatic dialogues.

This file has Year, Month, Day in 3 columns.  What seems like a detail is messing me up and I think will mess others similarly.  It is just the sort of thing that should be simple, but sort of goes on-and-on.  

(This is no one's fault in R-Instat - it is more a set of R issues.  But we should do a=something and I am not quite sure what.)

When I bring in the data the Month column comes in as strings (type c), because it is coming from Excel.

1.  This is something we should resolve easily:  I remembered that changing to a factor, or numeric could result in a whole column of NA - mercilessly - and with no undo!  We should do something about that issue eventually!
2. So I thought I would copy the column.  Have I missed it?  I can't find a simple way to copy a column?  That's my first question.
3. So I used Organise > Column: Calculate > Calculations and that works fine.  I now have a copy.
4.  Without thinking I now used the Organise > Column: Dates > Make Date.  It gives me a whole column of "NA".  Of course - because month is still of type (c).  This isn't too bad, because it is a new column - it doesn't overwrite any existing column.  But do we have plans to trap this situation?
5. So I make the Month column into a factor.  I wondered if the make Date can (yet) cope with this situation.  The factor still  (of course) has the labels attached.  I try the Make Date again and the issue remains, so I get another column of NA.  Humpf!
6. I know (now) the problem of changing a factor with non-numeric labels into numeric.  So I use the Convert dialogue and convert the ordinals.
7.  Now the Make Date would work.  But it would get the wrong answers.  That's because the ordinals are in alphabetical order - and hence for example - Jan is 5, because April, August, December and February come earlier in the alphabet!
8.  So I should have made it a factor, then re-ordered the levels, then made it numeric - using ordinals and not the obvious right-click, and then I can use the make Date dialogue.  And do we still claim R-Instat is easy to use!!!

Now what are the answers.  Well there are certain points that are general and I suggest we should do them.  They may not be urgent but they should be on the list.
a) We should have a simple way of duplicating, or copying one (or more) columns.
b) When we convert from Factor to Numeric we should not change the existing column into a whole column of NAs.  Or at least, if we do, then we have an undo available.
c) We should be able to get the date column from a labelled factor for the months.  (Assuming it is labelled correctly in order.)
d) But now I am a bit stuck.  I can't see any alternative to what Genstat does.  This involves us recognising these special cases - in our Tools > Options dialogue.  We have a tab (like Genstat see below) for Date format.

![date options in genstat](https://cloud.githubusercontent.com/assets/11226469/21012633/e60fa34a-bd4e-11e6-9f44-fc62711ac7a4.jpg)

Then we could do something!  This isn't easy for us, but we need to make it easy for users.

**Comment by dannyparsons** [comment]
We should be able to cope with Month columns or any other columns as factor, character or numeric, so either a change in the dialog or method should be able to fix this.

**Comment by Lunalo** [comment]
I think i can work towards fixing this in instat method

**Comment by rdstern** [comment]
Great.  Ideally it would work easily for the special Month and day of week columns in climatic.  And also we could make it work for other special columns that will be ordered factors.  The ggplot dataset on diamonds has 3 ordered factors that could be used to check the more general capabilities.

In addition most ordered factors are "linear", e.g. going from the 5 categories of "Very Bad", "Bad" to "Very Good".  Some however are circular - like the months, going from "Jan" to "Dec".  In the circular case we want to preserve the order, but may also want to start at any point, e.g. August to July - though there will usually be an obvious default starting point - here January.
