### ISSUE TITLE
Code indentation in R

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#2296]
Hi Team,

This is for those interested in writing r methods.

I have done some research about the convention especially when it comes to spacing.

I came across formatR package in r which can do the spacing and indentation for you but has  some drawbacks. https://cran.r-project.org/web/packages/formatR/formatR.pdf

Another way of doing this is to highlight the code you need to the formatting and use the shortcut  ctrl + shift + A  http://stackoverflow.com/questions/15703553/auto-format-r-code-in-rstudio

Happy coding.

**Comment by maxwellfundi** [comment]
@Lunalo  thanks alot for this insight. 

I had a lot of trouble but i now know how i can handle that next time. 

Well done for finding this.

**Comment by dannyparsons** [comment]
> I came across formatR package in r which can do the spacing and indentation for you but has some drawbacks. 

What are the drawbacks?

**Comment by Lunalo** [comment]
@dannyparsons  One main drawback is that you have to set the path of the file meaning that you edit the whole document every time you do it.
