### ISSUE TITLE
Typing in values for Generating regular sequence

### ISSUE THREAD

**Issue by mmumbo** [africanmathsinitiative/R-Instat#2297]
From Organise dialog when you want to create Regular Sequence over some range of values, is it possible to manually type the the values besides using the arrows to adjust the values?

**Comment by dannyparsons** [comment]
It is possible to type in, but as you've probably found out, it isn't always very easy to do, especially when you have some decimal places. This is a feature of that control with the up/down arrows. We are looking into ways to make this easier, which may be changing those up/down controls into plain text boxes. Although each control has it's own advantages/disadvantages.
Do you have a suggestion on how you would like it to work?

**Comment by dannyparsons** [comment]
The up/down controls have now been replaced with text boxes with numeric validation to make it easier to type in any numeric value.
