### ISSUE TITLE
describe > multivariate > correlations bugs

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2302]
I open the diamonds (ggplot2) data.  Also the standard rice survey data.  (The bug looks like an issue for any two data sets).
I use correlations for the survey and also the option to do a pairwise plot. 

a) First bug: I get the pairwise plot, but not the correlation matrix, though that option was still ticked.
b) Second bug:  I now change data set and use the diamonds.  It still gives me the old pairwise plot for the survey.  
c) I can try a third time.  It is still very happy with the original pairwise plot for the survey.  
d) If I do reset then it changes.

This is all part of my claim that we do need to check dialogues with multiple data sets, and used multiple times.

**Comment by dannyparsons** [comment]
Could either be Lily or Steve depending on who has time/wants to fix this.

**Comment by stevekogo** [comment]
@dannyparsons @rdstern @lilyclements I am going to fix this bug.

**Comment by lilyclements** [comment]
Double checked and these bugs have been fixed, @dannyparsons this can be closed.

@africanmathsinitiative/developers this is a dialog which still needs to be updated, in case anyone is looking for a task!
