### ISSUE TITLE
Merge dialog and sub dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2310]
@africanmathsinitiative/instat I've had a go at redoing the merge dialog/sub dialog. The pull request is here #2309, any comments on the code are appreciated.
Can anyone come up with a better design, mainly for the main dialog? I don't like what I've got so far but haven't come up with anything better. There's quite a lot to fit on the dialog. It looks squashed because I wanted the size to be maximum 640 x 480 to consider small screens.
It's functional so not urgent to get a better design but would be nice since it's a fairly key dialog in Organise.

![merge dialog](https://cloud.githubusercontent.com/assets/11214914/20524878/947083e8-b0b4-11e6-8c04-7388af6b4473.jpg)

**Comment by Lunalo** [comment]
I was wondering  whether  to have two sub dialogs in this case

**Comment by FrancoisJRenaud** [comment]
If not two subdialogues, I would at least get the "Key Columns" and things below to be aligned at the top with one of the two lines of labels on the left.

**Comment by dannyparsons** [comment]
Yes alignment isn't right, sorry should have mentioned I haven't tidied it up because I wanted to decide on a layout first.
@Lunalo I don't see how two sub dialogs will help much. If there was a sub dialog just for choosing the key columns it would be almost the same size because it needs all the big controls from the main dialog. Or did you have another idea in mind?

**Comment by Lunalo** [comment]
Let me think and then will get back to you

**Comment by Lunalo** [comment]
I have an idea. I think key columns list box is displayed when Choose which columns to merge by is checked. 
The part with key columns listbox can be hidden on load and can only be shown whenever the radio button is checked.

**Comment by lilyclements** [comment]
Just to clarify - do you mean it is display in the dialog box or on a separate sdg once it is checked? :)

**Comment by Lunalo** [comment]
It displays this part  
![image](https://cloud.githubusercontent.com/assets/13945088/20528334/db9955ba-b0dc-11e6-9f4a-314bad9c49d1.png)

**Comment by Lunalo** [comment]
Danny can also elaborate on that

**Comment by dannyparsons** [comment]
What's the question?

**Comment by lilyclements** [comment]
I meant for that part that you highlighted - are you suggesting that section comes up in as a sub dialog when you click "Choose", or comes on the main dialog?

**Comment by rdstern** [comment]
I hope that my main request is possible (at least in the future) with the Data Options.  Currently they allow a filter to be set.  I assume they will also allow us to select which columns are "hidden"?  That would allow us to have the merge copy only a selection of the columns across.  

Incidentally, what happens to merge if there is a filter in operation?

**Comment by dannyparsons** [comment]
I think one option already there is showing or not showing the currently hidden columns in the data selector. I think this works but it's not what you're asking for.
Your comment sort of implies that hidden columns should be excluded from commands which have the data frame as an argument - such as merge. Another would be append data frames. 
I think this what's happening at the moment. Is that how it should work? Then we would just need options to hide columns - I'm not sure if hide is an appropriate term then. 
I could see issues appearing, for example, in ggplot you pass in the data frame, if you somehow then chose one of the hidden columns for your aesthetics, it wouldn't be in the data frame so would crash. So we should check things like that but I don't think it's too difficult.

The merge should respect a filter. By default all dialogs do (should), unless they have specified otherwise.
