### ISSUE TITLE
 ucrInputcombobox Methods

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#2311]
Hi Team, 

As i was tackling the contrast dialog, I wanted to implement a functionality that could allow the user to only select items from the existing list but not edit. so I did a small method below

`Public Sub SetEditable(bEditable As Boolean)

    If bEditable Then
         cboInput.DropDownStyle = ComboBoxStyle.DropDownList
    Else
       cboInput.DropDownStyle = ComboBoxStyle.DropDown
    End If
  End Sub`

But after discussions with Danny, we thought if it is appropriate to be calling this method in every place we the control is used?

It was after this that other issues came up since we were now viewing the software in general. We have some places that we want this control to only accept certain characters e.g in the ucrDistributionswithParamaters. 

I thought of an approach of regular expression. I researched about regular expressions in vb and here are some of the useful links: https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regex(v=vs.110).aspx
 ,https://msdn.microsoft.com/en-us/library/hs600312(v=vs.110).aspx ,

These are just my thoughts, any idea that can enrich the above method is welcomed

**Comment by dannyparsons** [comment]
There are build in auto complete options for combo boxes I think. You could start by looking into that and seeing what's possible. I'm not sure if you can have auto complete (which requires editable) and also a restriction on items without writing some of our own code.
