### ISSUE TITLE
sdgPlots -> Axis Tab -> Scale -> max value

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#2314]
The maximum value in the nud for the maximum value on X/Y Axis is 100... There should be no limit I think. Or is this a percentage ? @maxwellfundi  could you have a look at this ?

**Comment by lilyclements** [comment]
@maxwellfundi I believe you're working on these at the moment in #3087, I just wanted to bring your attention to this issue. I assume this is only 100 because 100 is the default. Can you make this so that the x/y nuds for under the **scale** groupbox have no maximum?

**Comment by dannyparsons** [comment]
We have discussed that these should not be nuds because the range and scales of the values are too varied. They should be input controls with validation set.

**Comment by maxwellfundi** [comment]
great, i will change this to inputs from nuds
