### ISSUE TITLE
Dialogues for links and keys

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2320]
I hope this may be the last large new set of dialogues - if it becomes a set.

We need to be able to manage key columns and also the links between data frames.  

1. Often data frames will be linked because one is derived from another.  For example the **Organise > Column Reshape > Summarise** dialogue could go from daily to annual or monthly summaries.  And the summary columns will be linked to the original data frame with the daily data.  
2. Some commands don't yet set up links (I think?) and perhaps they should.  For example stack and unstack.
3.  Sometimes files will be entered and we want to say what the links are.  For example, in climatic, we will often have (daily) data, and there will also be a factor column giving the station number.  There is also another data frame with a single row for each station, giving its name, location and so on.  We want to say they are linked and explain how.
4.  In the example in 3 that is where we would expect the key columns to figure.  

I am consciou this information is totally inadequate to start conceptualising the dialogues.  But I hope it is enough to "seed" the discussion on this topic.

Roger

**Comment by rdstern** [comment]
Not sure who will do this set of dialogues, but I assume they will be discussed this week?

**Comment by lilyclements** [comment]
@dannyparsons can this be closed now? There are three open discussions on links and keys
