### ISSUE TITLE
Describe > One Variable > Graph and Two Variable > Graph also, with examples

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2321]
The Describe > One Variable > Graph options are looking much better now.  I don't want continued work there to be at the expense on the general enhancements to the graphics system, and other tasks.  But the results are good enough it is a shame if those facilities were forgotten.

1.  The sub-dialogues seem to be unnecessarily small.  I would be quite happy for them to be larger.
2.  In the one variable, we now have some good additions for the continuous plots.  Could we also consider what can be done to improve the categorical plots.  What comes to mind is staken also from the examples in the sjplot vignette, though I am not necessarily suggesting we jump to that system.  But see [http://www.strengejacke.de/sjPlot/sjp.frq/](url)  It would be good to be able to add counts and/or percentages to these bar charts.  This is the geom "text".
3.  It would also be good to be able to change the theme easily.  Here I hope that will be easy, because we are not going to give flexibility to define new themes (yet), just to be able to choose from the available themes would be excellent.  For example I prefer the sjplot theme to the default one.

4. Then it would be good for our graphics experts to now look at the 2-variable plotting and (hopefully now easily) add more flexibility to those plots.  For example I tried the survey data with the 3 other continuous variables against the yield.  There I would like the yield as the y-rather than the x.  And also to be able to have a few more of the options that we now have for the one variable situation.  And for bar charts there are obvious options, such as the dodge, stack, etc, plus options (with stacked particularly) to also add the individual counts within the stacks.

5.  Overall the 2-variable will need some discussion, but I suggest some enhancements could follow from the improvements in the one-variable case - and are obvious.  Others will be new, perhaps.  For example there should be a place for rugplots in some situations and I don't yet see jitter.  As with the one variable, it could be good to play with the diamonds as well as the survey dataset.

6.  Then I think we should also look for a third dataset to play with to test these dialogues.  We have the simple one, namely survey, and a long one, namely diamonds.  Let's find a convenient one that is also quite wide, i.e. quite a lot of columns to describe.  I'll look and perhaps others can too.

Roger

**Comment by FrancoisJRenaud** [comment]
Hi all,

I ll work on 2, explore a bit what they do in sjplot, try to add the text geom to our available geoms as well as hline, vline and abline probably. They stand out of our current geom collection in a similar way I think.

**Comment by maxwellfundi** [comment]
We will have a look at this some together with @FrancoisJRenaud to address this issue.

**Comment by dannyparsons** [comment]
@stevekogo Worked on the 2 variable dialog so could also be involved here

**Comment by rdstern** [comment]
I have attached a file that is causing some issues with the Describe > One Variable > Graph dialogue.

I admit it is an awkward file, but hey what do you expect from me.

1) I have checked and the problem is that one column of data is totally missing.  So it is now easy to try, using File > New and then accepting the default, so you get 2 logical columns and there is no data.

2) If you try **Describe > One Variable > Summarise** it all seems OK.  It works, and tells me the columns are logical.  Then I use <Right Click> and make them numeric and it is still OK.

3) Now try the **Describe > One Variable > Graph**.  Try various combinations.  For me it seems to work if I use both columns.  But it crashes if I have just one column.  I know it is really crazy to try with just all missing, but it shouldn't crash!

4) While I am there I think the default graph on the dialogue is now Violin + Jitter and it should still be boxplot.  Is it choosing the last option rather than the first?

5) Also I did not find that **coord flip** is working. That was with the data below.

You may not need to try this example.  It is the same awkward data set I used earlier from Ghana Met.

1) **I hope it reads into R-Instat for you?**  The version I had was Excel95.  It read OK after I moved up 4 rows.  Before reading in can you look in Excel.  If you keep it as an xlsx file then delete the first 4 rows, because the option to skip rows isn't available.  Or save it as an xls file and then you can skip the first 4 rows.
2) Now I made the first 4 columns into factor columns.  
3) Then I used the Organise > Column:Date and made the date column into a proper date.  So far so good.
4) Then I tried the Describe > One Variable > Graph and used all the columns and that gave the error.  It is actually the same as above, because one column is totally missing.  But that can happen when importing data.
5) That's also when I found that the coord-flip doesn't seem to work.  And the default now seems to be Violin + Jitter.
6) And if you are looking to improve this dialogue further, then adding to the bar charts with labels giving counts and percentages would be good!

 



[GH_DATA3_17112016_2.xlsx](https://github.com/africanmathsinitiative/Instat/files/629243/GH_DATA3_17112016_2.xlsx)

**Comment by dannyparsons** [comment]
Sorry, I have been working on the one variable graph to test out the new linking system so that's why there are a few strange things on the dialog now, such as different defaults. I forgot to change them back after testing, but will fix these soon.

**Comment by rdstern** [comment]
No problem.  It will be good to have the new linking working.
