### ISSUE TITLE
Stargazer package for well formatted table output

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#2322]
Hi @rdstern , @dannyparsons , @stevekogo , @volloholic , @lilyclements, 

I have been doing some deep research on stargazer package https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf, https://cran.r-project.org/web/packages/stargazer/index.html.

 Stargazer produces well formatted table for regression output in LATEX, HTML or text format. I hope we want to dwell on text format since the other options produces the code as output unless if we still need to use knitr package to knit the code output.

First of all stargazer supports a number of of models listed in this link https://cran.r-project.org/web/packages/stargazer/index.html.

Example

if we do linear regression of Yield against  Size then  this what we get.

**code**
> stargazer::stargazer(lm(Yield~Size), type="text")
**output**

![image](https://cloud.githubusercontent.com/assets/13945088/20660193/46f41b8a-b559-11e6-88cb-ee422c435668.png)

What if we do a  logistic regression?
i recode the variety into two levels.
surveyData$Variety1<- dplyr::if_else(Variety.=="OLD", 1, 0)

stargazer::stargazer(glm(surveyData$Variety1~Yield, family =binomial(link = "logit"), data = surveyData), type="text")

![image](https://cloud.githubusercontent.com/assets/13945088/20660147/f95fe87c-b558-11e6-9390-3f391ebbeb10.png)

I am not happy with the doted lines which come as default. I am still exploring on how to display the table with solid lines.

Stargazer also provide option for renaming the title of the output, keeping or omitting  some statistics in the output  and also renaming the the column names in the output.

I tried also to explore on how to display summaries for dataframes . One thing I found out is that you just need to pass in a data frame as a parameter but the problem is that it returns the summary for numeric data type only. I think this is weakness.

![image](https://cloud.githubusercontent.com/assets/13945088/20660535/37b3a2a6-b55b-11e6-87b1-d56a39557566.png)

I am still looking into this and any idea is welcome.

**Comment by rdstern** [comment]
Can you also look at the sjplot package for the same thing?  

For example sjt.df can display the data in data frames, (like our Organise > Data Frame > View while sjt.corr is for correlations and sjt.lm and sjt.glm are for linear models.  There is also the partners of sjp.lm and sjp.glm to produce the relevant plots and these plots use ggplot2. 

Thanks

Roger
