### ISSUE TITLE
Define climatic data dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2336]
This is a new dialog to define a data frame as being climatic. So after importing data if you have climatic data then you go to this dialog to tell the Instat object to treat this data frame as climatic.
When you define a climatic data frame you need to identify some key variables. This means in the metadata we will store which column is for "rain" which is for "max temp" etc. Because the column names might be different to these.

So this dialog is very simple. First you select a data frame to be climatic. Then there will be a long list of single receivers - one for each "climatic type". The first should be Date as this is mandatory for climatic. The others will be "Rain", "Temperature minimum", "Temperature Maximum", "Wind", "Sunshine" etc. 
@rdstern can you provide a list of types we want to detect? We don't need them all now but it would make the dialog look impressive if it did, and it's no more complicated to have them. 
If it gets very long we may want to group them or put them on different tabs or a sub dialog or something, but that could come later.

You do not need to define every climatic type, the only mandatory one for OK to be enabled is Date.

The R method for this is not written yet, but the dialog can start. The method will be quite simple as it is just going to be adding metadata to the instat object/data object and I can work on this shortly.

**Comment by rdstern** [comment]
Exciting.

Let me first answer the question from Danny above - as best I can.  Then I add some questions and points of my own:

1) I agree that Date is mandatory, so this is the first column.
2) Then Rain
3) Then TMax and Tmin (Temperature Maximum and Temperature Minimum)
4) Sunshine Hours
5) Radiation
6) Wind speed
7) Wind Direction
8) Cloud Cover (possibly)

9) Now the first question - and this may add another set of columns.  What should we do about "derived" columns.  An obvious one is **Temperature Range**, or Diurnal, which is simply (Tmax - Tmin).
10) There are usually more temperature variables measured.  So **Wet Bulb** and **Dry Bulb** are obvious ones.
11) They are often used to calculate **Relative Humidity**.
12) We could consider groups of variables perhaps.  So Precipitation is more general than Rain, and would also include Snow, etc.  (Snow is important for our forthcoming work in Lesotho.)
13) Another question:  In "ordinary" data frames we already have this same sort of concept with data columns being **Layout**, **Treatment** and **Measurement**.  That is usually for sets of columns.  This sounds like a similar concept, but more detailed?
14) In the "olden days" I think we has special names, e.g. rain for some columns.  So we would know by those names.  Will there still be special names?  The OpenAir package (which is the closest other R package to what R-Instat is doing) has "Date" and "ws" and "wd" as special names for date, wind speed and wind direction.  It is general, but is mainly designed to process hourly data.

**Comment by rdstern** [comment]
More questions - these are issues, so I am not expecting immediate answers:

1) Sometimes Date will come into the data frame as (say) Year, Month, Day and we already have the dialogue to calculate the **Organise > Column: Date > Make Date** dialogue to make the date column.  Then I assume R-Instat will link and hence will know they are consistent.   I assume we will (at least to some extent) now **protect** the original columns, so they remain consistent?
2) On other occasions we might be supplied with both in an input file.  Will we then check for consistency and then link them so we get to the same place?
3) These consistency checks and also be applied to other variables.  For example the "Range = Tmax - Tmin" may be calculated by us, or may be entered.
4) Often a Met service will have a well-defined order of the variables, which corresponds the their data entry sheets.  Might we make it easy - at a later time - to attach then a whole set of names?
5) You have not mentioned "Station" for when there is data from multiple stations.  Our default will be to have Station as a factor, so the data "go down".  For example, if there are 5 stations, with 20,000 observations in each, then the data frame will have 100,000 rows.  Again the default is that the data on different elements will "go across", i.e. each element is a column.
6)  But sometimes we may want the stations to **go across**.  This is usually then for a single element.  It is the more natural layout if we want to do spatial checks, e.g. is Tmax similar (on the same day)  in stations that are close together.  Will we allow this "shape"?  It could be the way the data arrive, or we may sometimes wish to unstack the data?

**Comment by dannyparsons** [comment]
Thanks for these. I'll respond quickly to a few.

This is exactly the same as the column structure: Layout/Treatment etc. So we will have climatic_type as a column in the variables metadata and each column will have a value like Rain, Date etc. Some columns may have no climatic type.

Yes we should have Station. And yes I don't see a problem with having calculated columns in here as well, e.g. Temperature Range. And we can build up methods to check these for consistency. 

I would say the other date columns e.g. Year, Day, Day of Year, can all be detectable. But they are not a substitute for Date. You need to use the Make Date dialog first before making it climatic. 

"Season" should be another column to detect.

The other option we need on the dialog is "Time period" of the data. Either "Subdaily", "Daily", "Subyearly" or "Yearly". So this is just a combo box with "Daily" as the default.

@stevenndungu You can see this list is getting quite long. We may group them by types as Roger suggests later, but for now if you put them all on one dialog but inside one box that is scrollable so the dialog doesn't become really long, that will be fine. If you look at the "Indices" subdialog on the "Climdex" dialog, that's the sort of thing I mean.

**Comment by rdstern** [comment]
I agree that is fine for now.

I am still not clear exactly how it will be used in the further dialogues.  In this dialogue eventually perhaps the 4 basic ones may be (as for Dodoma in the Instat library climatic guide) rain, tmax, tmin and sunh.  Then there might (perhaps) be a More button.  That could either be a sub-dialogue, or it could open up another column - as we do for the calculator dialogue.

We should then be able to add our own.  For example the excellent (I think) openair package deals with pollution data and that brings in some new elements in addition to our standard dates and wind speed and direction.  I assume they will come in our Tools > Options dialogue?  Or perhaps there might be a sub-dialogue here itself?

Where does "scale" come in?  For example rain could be one minute totals, or the more common of daily or annual?  Will we distinguish between primary and derived.  I think Danny and David have discussed this?  For example on an annual basis the total could be number of rain days, or the maximum (daily), or the annual (or seasonal) total.
