### ISSUE TITLE
Climatic Analyses - quality control

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2339]
This issue is to set out some of the general facilities we need for the quality control of the (daily) climatic data.

This is perhaps the parallel to the climate indices, in that the same basic software that calculates the 27 indices (RCLIMDEX) has RCLIMDEX-PCIC for the indices, and RCLIMDEX-QC for the quality control.  My general view on our proposed strategy have been re-enforced by my visit to the ClimDex people in Canada, and also correspondence with a key person on quality control of climatic data - Enric Angular.

For the indices we (at least initially) fit within the existing R package as far as possible. But for the QC we take the ideas from RCLIMDEX-QC and totally redo it ourselves.  I suggest there could be 3 key components to what we produce and they are all relatively general concepts already in R-Instat.
1) The rows of data where observations look "odd" needs a filter.  That is already working.  What is not yet operational, but has already been asked for, is to permit "or" in the filtering conditions.  To help users we may have (say) 10 different QC checks and we would like to know if the data - in any month - or from any element is "odd" for at least one of the checks.
2) The set of checks will produce a monthly data frame - from daily data.  (It might later produce a daily data frame from hourly data).  This is because the data are usually entered from monthly sheets.  Possibly we will produce a monthly data frame for all months/stations and then have special comments for the oddities.  Or we may produce one with just the months where there are oddities.  It won't matter, because if we have all the months, we can always filter later.
3) Initially we may want to do the checks one at s time.  Each check will add a column to the monthly data frame.  We don't even need the "or" on the filter for this option.  Ideally (as in the current R-Climdex-QC) we would be able to produce a set of checks all together, producing (probably) multiple columns in the monthly data frame.
4) We should also be able to indicate any "suspect" month within the daily data frame.  Now our boxplots come in.  We do the boxplots as we can now, but with a different colour - say - for any month that is suspect.  Possibly we can do this already.
5) The only real inconvenience in the current boxplot "system" is the axis labels for the years.  Ideally we should be able to just give a subset of the labels if it is an ordered factor.  Or we use the theme aspect to be able to display the x-axis at 90 degrees.  The latter will be easy.  I am not sure about the former.

**Comment by dannyparsons** [comment]
@rdstern are we doing anything on this before 0.4.1?
