### ISSUE TITLE
Data Frame metadata oddity

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2363]
![data frame metadata2 diamonds](https://cloud.githubusercontent.com/assets/11226469/21040230/7c11c3be-bddb-11e6-9588-dc0c60a180eb.jpg)

The last line is the oddity/bug.

This was from the diamonds data.  I used the **Organise > Column: Reshape > Summary** three times, each time getting the minimum and maximum price for each level of the ordered factor.

The third time - which was by **clarity**, which has 8 levels, I then went back and did a second summary to show it simply adds columns to the existing sheet.  This time I got rid of min and max, and got the median instead.  It worked fine.  Then I realised I still had the count as a column and so deleted that column.  Then I used **Organise > Data Frame > Reorder Columns** to move the median betwwen the minimum and maximum columns.

It all looks fine in the actual data.  But the meta-data seems to be messed up by one of those operations.

Roger

**Comment by lilyclements** [comment]
So I looked into this a bit to pinpoint when the issue occurs.

This issue occurs **any time** you reorder any columns, so they don't have to be made via the calculation system - just running 
InstatDataObject$reorder_columns_in_data
means some columns become NA - such as, data_name, is_calculate, is_linkable and label.
