### ISSUE TITLE
New dialogues for keys and links?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2383]
This follows discussions with David, though some details may need correcting, and there are some questions.

It is in the Organise menu and could be an entry just above Data Object and at the same level.  So there is a new menu item, possibly **Organise > Keys and Links**.
there are 2 dialogues on keys, with the first being **Organise > Keys and Links > Add Key...**, and the second **Organise > Keys and Links > View and Remove Keys...**. (Links will be in the next message.

In the **Organise > Keys and Links > Add Key...** dialogue we need to allow for a single column being the key, (e.g. Station) or multiple columns, (e.g. Station and Element).  We could also have multiple sets of keys, (e.g. Date, and also Day_in_Year and Year).

Keys are within a data frame, so the Add key dialogue could be like this:

1. "Usual" data selector, 
2.. Multiple receiver.  
4. Field for the name for the key - unless this is automatic?  Default is "Key1" if there is no existing key in that data frame - otherwise Key2, etc.  (I think that code exists.)
5. Then we need to check whether the column (or set of columns) is unique.  I suggest a **Check Unique** button that is enabled, once there is something in the receiver.  It does the check, and then if is alright, then OK is enabled?  Ideally there could be a message in the dialogue if the column (or set of columns is not unique.

6. The second dialogue is for "View and Remove Keys"
7. The selector is as before, but it chooses keys, rather than columns.  
8. There is a single receiver.  If there is just one key, then that is put into the receiver automatically.
9. There is a checkbox, default unchecked, which says "Remove Key".
10. OK is enabled when the receiver has a key.
11. There is a display in the dialogue of the column(s) that make up the key. 
12.  When OK is pressed, then there is either a printout in the Output window that lists the column(s) making up the key, or the key is deleted, and a comment to this effect is put into the output window.

**Comment by rdstern** [comment]
Before setting up the dialogues I need to be clear of what we want from these links.

1.  We have one data frame with a (unique) key.
2. We have a second data frame with the same columns as make up this key.  My obvious example is that we have a data frame with climatic station names, plus other "station-level" data, such as lat and long.  Then we have a second data frame with (daily) climatic data from these stations.  This (daily) data frame needs to have the station name, etc to link to the station-level data.
3.  The name of the columns in the 2 sheets will often be the same, but this need not be the case.
4.  There can be stations in the station-level data frame, for which we don't have daily data.  That way round is fine.  What do we want to do when there are station names in the daily file for which there are no stations?  CLIMSOFT does not allow this.  We could:
a) Also not allow
b) Add records to the station file, with the other information missing
c) Ignore the problem - but comment
d) Ignore the problem without a comment.  (It's just life!)

This may arise  just because it does, or (often) because we have mis-typed a station name in part of the daily data file.

5. I am proposing that we need to set up a (unique) key first?  Is that OK?  So we use the Add key dialogue, before the **Organise > Keys and Links > Add Link** dialogue?
6.  I also assume there will be 2 dialogues, for **Add Link** and then **View and Delete Links**.
7. So on the Add Link dialogue it will look a bit like a much simpler version of the Organise > Column: Reshape > Merge dialogue, i.e. with 2 data frames side-by-side.
8. The first will say "Data Frame with Key".  Then there is the data frame selector, together with the keys in the selected data frame.  perhaps if no keys have been setup then there could be a message instead?
9.  When a key is selected, perhaps the columns that make up the key could be shown below the selector.
10.  If there is just one data frame, and just one key, then this is shown automatically?
11.  Then the parallel selector has the other data frame and also a multiple receiver.  Once a key is selected in the first data frame, then when the second data frame is selected, it would be good if the default would be to select the columns automatically if they have the same names.  otherwise the user has to select them.
12.  OK is enabled once the second receiver is filled.
13.  Do links have names?  I assume so.  And some are setup automatically.  My impressions is that we might be calling them Link1 upwards, and probably don't want to change that?
14.  Now we move to the View and Delete Links dialogue.  On the lhs it could be a bit like the control in the Describe > General > Graphics dialogue, with the label "Links".  You can select a link.  Then it shows the two data frames and the columns in those data frames that are linked.  I don't suppose there need be any difference between links we have setup ourselves, and those that R-Instat has done automatically?
15.  Then there is a checkbox - default unchecked - that says "Delete Selected Link".
16.  Once you pres OK it either deletes the link and puts a message in the output window, or it lists the selected link in the output window.

**Comment by dannyparsons** [comment]
@maxwellfundi @Lunalo @stevenndungu Can someone work on the design for the **View and Remove Keys** dialog as described in Roger's first message? Some of it may need additional code written so just do what's possible. The **Add Key** dialog is now complete.
The links dialogs can be done next week.

**Comment by Lunalo** [comment]
okay fine

**Comment by maxwellfundi** [comment]
Great, task taken . 

Thanks

**Comment by lilyclements** [comment]
I'm having a look at the Add Key dialog and there are a few changes to make.
Layout,
Reset Button
Add default name - Key1
OK to be enabled if one variable is inputted (e.g., Date)?

Does that sound about right? Judging from the above comments that's what I can gleam.
I assume when OK is pressed, our 'item' becomes a key. Is this key a new column? Or just a key which is not seen?

On View and Remove Keys, it doesn't yet have the 'key' items as what you can select in the receiver. Is this because the 'Add key' isn't working or because the SetItemType("key") option isn't yet implemented?

**Comment by dannyparsons** [comment]
Yes feel free to make those changes. The dialog should work with only visible changes in the metadata at the moment. There is still some work to do on item types for keys and links so combo boxes/selectors can't have the right info yet. You could add this code as comments because it should be included soon.

**Comment by dannyparsons** [comment]
We need to start work on the other dialogs here for 0.2. @Lunalo @stevenndungu @maxwellfundi 

The **View/Delete Key** dialog is specified above and can be done. There is a small amount of work to get keys to display in the selector, which I can do if needed.

The **Add Link** dialog can also be started. It is specified above but below is a rough sketch as well. This dialog has a sub dialog, but we suggest this is created but left blank for now.
![whatsapp image 2017-01-17 at 11 13 36](https://cloud.githubusercontent.com/assets/11214914/22018413/a5a1cf8c-dca6-11e6-90d1-90c08179e134.jpeg)

The View/Delete Link dialog can also be started. It will be similar to the dialog for Keys. Below is a sketch.
![whatsapp image 2017-01-17 at 11 14 54](https://cloud.githubusercontent.com/assets/11214914/22018447/c8e15724-dca6-11e6-9281-67ec60d41130.jpeg)

These are quite urgent so I think they take priority over most other tasks at the moment.

**Comment by Lunalo** [comment]
Thanks @dannyparsons 

We are working on them.

**Comment by dannyparsons** [comment]
The initial work on this is done, further improvements can be in a new issue.
