### ISSUE TITLE
Saving Graphs

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#2384]
If I remember well (not sure anymore, might be that we want something in the save menu somewhere) @volloholic  has asked us to add a Save Graph As Image check box on graphics dialogues... Ticking it would need to do something like this -once the new implementation of RSyntax is complete, and also in respect with the new linking methods I am not yet familiar with ... correct If I am wrong- : 

> Dim clsSaveFunction As RFunction
> clsSaveFunction.SetRCommand("ggsave")
> 
>If checked then
> Using dlgSaveFile As New SaveFileDialog
>             dlgSaveFile.Title = "Save Graph As Image"
>             dlgSaveFile.Filter = "PNG (*.png)|*.png"
>             dlgSaveFile.InitialDirectory = clsInstatOptions.strWorkingDirectory
>             If dlgSaveFile.ShowDialog() = DialogResult.OK Then
>                     clsSavefunction.AddParameter("filename", Chr(34) & dlgSaveFile.FileName & Chr(34))
>                     Add that function to the RunAfterMain commands of RSyntax.
>             End If
>         End Using
> Else If not checked
>            clsSaveFunction.RemoveParameter("filename")
>            remove function from the RunAfterMain commands of RSyntax
> End If

**Comment by maxwellfundi** [comment]
This looks sensible thing to do actually as the user wold be able to save graphs as images. I will have

**Comment by maxwellfundi** [comment]
@FrancoisJRenaud The plan for this is i could add a new checkbox that would say "Save Graph as Image" which when checked it could call the ggsave which would be run after the other commands have been run. 
So  i think this would be on something like afterclickok, but now that you are working to edit the rsyntax to make this easier, we can discuss how to do this when we meet up. 

Thanks.

**Comment by FrancoisJRenaud** [comment]
Yup, just for record you mentioned you were thinking of adding this on the ucr Save Graph which is sensible ! Also when you come to implementation in January, have a look at the suggestion above, the chk box should open a dlgSaveFile and use it to choose the filename argument of ggsave... @dannyparsons if that's indeed how we want this to be implemented, we've got new usages of chkBoxes (opening sdgSaveFile, and adding an RCommand to the secondary RCommands of RSyntax as well as a parameter to that RCommand).

**Comment by volloholic** [comment]
Hi All 
I think we need to rethink this. GGsave has many options including saving as different types I'm more inclined to focus currently on a really good implementation with as many of the GGsave parameters as possible in use graph and to leave it out elsewhere at the moment.
