### ISSUE TITLE
Changing when packages install/load and version checks

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2441]
We want to make packages install/load(?) when they are needed by functions, not all at the start on first load. Each function should specify which packages it requires then they are loaded if needed.

When installing packages for users, we also need to check that if the user has the package, they have an up to date version. This becomes important for example so we can ensure users have the new version of ggplot2. This should be simple by modifying our installation checks.

**Comment by dannyparsons** [comment]
Is this a 0.3.0 issue?

**Comment by volloholic** [comment]
Yes this is almost certainly 0.3.0 it should be no later but it needs some substantial changes.
