### ISSUE TITLE
New Output Window

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2447]
It is great to have the graphs going to this window.

One "feature" that I hope can be changed is that once the window is filled the window should (by default)  show the most recent output.
One feature that we had with the single graphs, that is now "lost" is the ability to resize the graphs once the output window size is changed.  Now it seems to be a fixed size, e.g. even if I make the output window into the full screen that graph only fills half of it.
That may be something that can be changed.  Or, I assume we will soon have the option (in Tools > Options?) to choose the output for the graphs?

**Comment by dannyparsons** [comment]
Also added to this is the image resolution, which is too low at the moment.

**Comment by stevenndungu** [comment]
@dannyparsons , is this complete?

**Comment by dannyparsons** [comment]
Not yet. Should be for 0.3 I think.
