### ISSUE TITLE
Make Date

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#2475]
I have been trying to use this dialog and it doesn't seem to work well. 

I have a date column, that is in the format day/month/year which is a factor and i want to convert it to a date.
The new column which is the is of date data type looks really messy.

When i select either of the options on the specify format, it still does the same thing.

I believe @stevenndungu worked hugely on this, could you have a look at this.

**Comment by dannyparsons** [comment]
Good that you've been testing this. If you can share an example with @stevenndungu you can look into it together.

**Comment by maxwellfundi** [comment]
I have demonstrated what i wanted to achieve to @stevenndungu  and @Lunalo . they are working to get it resolved hopefully.

**Comment by rdstern** [comment]
While here, there is a bug in the command when making the date from 2 columns, with the first being the year and the second being the day of year, going from 1 to 366 each year, with a gap from 59 to 61 in non-leap years.

An example of the data is in the library for Instat, namely Samaru56.  It would be good to fix this one urgently.

**Comment by stevenndungu** [comment]
@Lunalo is this complete, so that it can be closed?

**Comment by maxwellfundi** [comment]
@lunalo @stevenndungu could @dannyparsons close this now? has it been complete?

**Comment by maxwellfundi** [comment]
@dannyparsons  this was done, it could be closed

**Comment by rdstern** [comment]
It would be good to add to the options for transforming a single date-type column into a real date.

More options could be added.  I am also not sure what is meant by the default.  And could we add in the option to specify the format, which seems to be there, but disabled.

Among others to add that I have come across are 6101972 for 6 October 1972, i.e. no spaces and also no zero in the days.  And 06.10.1972.

I am also not sure how the Format Field will work.  I would understand better if these were up-down controls giving the order 1 to 3.

Could there be an option to type in the format directly?  Perhaps this would be instead?
[https://www.stat.berkeley.edu/~s133/dates.html](url) is one readable reference.

This perhaps needs some discussion.

**Comment by dannyparsons** [comment]
This dialog is currently very messy, it has lots of options, some duplicated, and many are not as flexible as we need, even converting from 3 columns is pretty inflexible in the formats you can give.
It's a pretty complex dialog, so I'd like someone to rethink the design and functionality if more work is to be done on this.

**Comment by dannyparsons** [comment]
This has been improved to allow more options in the single column case and help on how to construct the format. More could be done on thinking about the design for future versions.
