### ISSUE TITLE
More on the climatic dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2491]
It would be good to move forward to complete some of the dialogues in the climatic menu.  It is possible that some are already complete - in that case we just need examples of how they can be used.  They link to the work on keys and links (I think), because they generally involve 2 data sets, one with the station (or location) information and the other with the actual data.  

I hope the others can get the dialogues for links and keys finished also for Version 2.  It is possible that the climatic dialogues won't need them.  Danny (and David) can be our guides if need be.

1. The reading of SSTs into R-Instat (**Climatic > File > Open SST**) .  I assume this is working, so could we have examples to test?  Perhaps from ENSO 3.4 region? 
2. The writing of data to CPT (Climatic > File > Export to CPT).  Perhaps this could use your Ghana data as an example?  A second could be Dodoma data (i.e. a single station) with multiple summaries.  I think this is working, but perhaps with files "hard-wired".  Again I would like data sets to test myself also.

Or, in the spirit of the local testing, there could be sufficient information for the Maseno team to test.  Though as they will be very occupied this week, I suggest that James also becomes a tester of this information also.  So James and I can be the main testers.

3. (Perhaps not finished in Version 0.2, but good to make progress and will need discussion with Danny/David).  Work to get **Climatic > Climdex** working.  I am not sure what this entails, but that would be great. 

It would be good to (at least start) this work by Friday if possible, though I suggest 1 and 2 a bove are more urgent - partly because they are smaller. 

At some stage I would like to re-examine the structure of the dialogue and consider sub-dialogues.  But, for now I am happy there are no sub-dialogues, because I suggest that getting this working can proceed either for Version 0.2 or in parallel with the forthcoming work on sub-dialogues and user controls.

Roger

**Comment by stevekogo** [comment]
@dannyparsons, @rdstern  I intend to carry on improving the output for climdex, particularly displaying the data frames. My thought is to have two data frames, one for yearly data and another for monthly data. I think we should implement links between these data frames with the parent data frame but my concern is, at what stage should we populate these data frames? We can have a skype call to discuss this implementation challenge once you have time.

**Comment by rdstern** [comment]
I have now followed your instructions an importing the SST files.  Good to have that.  I attach your document, because it shows most of the points I want to make:
[Open SST.docx](https://github.com/africanmathsinitiative/Instat/files/723081/Open.SST.docx)

1. On page 2 most of my points relate (I think) to the ECHAMS4.5 sheet.  This has 130,000 rows, from 3450 points.  The columns includes the same lat-long columns as the other sheet.  And there seems no options to avoid this.  To me the idea of having 2 liniked sheets is that we don't need the lat, long to be repeated?
2.  The date is given as a factor - why not a date?  I thought it is monthly data, so why is it a date/time column.  Can this be improved?
3. In the view > Column Metadata I note that Lat and Long are denoted as key columns.  That's great.  I assume they make up a key together.  But I am surprised then that the station is not a key column.  To me that is the obvious linking column (single column), and hence the obvious key?
4. I don't see a link made between the two files?  Could that be added?
5.  You say at the end of page 2 that this importing works for NetCDF files - which is great.  Could we have an example of this.  You say this still has to be "optimised".  What does this mean?  Could you do it?  If so, then perhaps the Climatic > File menu might have Open NetCDF dialogue as well as Open ST, or the Open SST might just go into the SCF Support menu.

**Comment by rdstern** [comment]
The export to CPT.  Here is Steve's dialogue.

[Exporting data to CPT.docx](https://github.com/africanmathsinitiative/Instat/files/723202/Exporting.data.to.CPT.docx)

1. I first followed your instructions with the Ghana set.  Initially I didn't get OK enabled, because I hadn't given a file name.  I suppose that is OK that you don't give onhe by default, because you then have to browse and this will show you where the file is going to be.  I wonder if the dialogue could write a different default note that shows the location of the file, or perhaps there could be another line in the output window, that shows this file with the full name?
2. In your document it would be good to capture a shot of part of the resulting file, so readers know what the output will look like.
3.  I then tried to export data for just a subset of the stations and also changed the order of the stations in the station file, and changed the station name to be a factor.  It coped with this fine.  great.
4.  Then I renamed the column called lon to long and (of course) it didn't like it.  That is something you mention in your document and we need to change.  We don't want special names "hard-wired" into the commands.  I assume we can use the Climatic > Define Climatic Data dialogue in some way for this?  This might need some discussion with Danny.

Overall this is looking very promising.  Exciting.

**Comment by rdstern** [comment]
More on the SST files document.

Steve, I wonder if your document could start a bit earlier.  It could mention the website where you get the sst data from, together with advice on what should be done on that site.  If you have web access, (or go from within CPT?) then I assume you would still suggest a 2-stage process where you download first, and then import.  Or could we import directly?  I assume not.  You could show the downloading process.

Then you could perhaps show a bit of the file that is to be imported? 

Then, either here, or elsewhere, I assume the radiation data from EUMETSAT is an example of NetCDF.  This was syudied in the MSc essay last year.  Could you consider how this could be imported - again this could be using this dialogues or perhaps a similar one?

**Comment by stevekogo** [comment]
@rdstern I am going to address these concerns right away

**Comment by rdstern** [comment]
[maproom_netcdf.zip](https://github.com/africanmathsinitiative/Instat/files/752231/maproom_netcdf.zip)

These data are from Ghana's maproom.  They are output from ENACTS, but (I think) on a 10-day basis.  What I do not know is whether it would be better to have a single dialogue for any NETCDF data - and that is all we need.  
Or if we have a single dialogue, but with special options if reading ENACTS, or SSTs or the radiation data (are these needed.  
Of if they are different enough that we might have separate dialogues for each type of data - as well (perhaps) as a general dialogue for any type of NETCDF?

This is all less urgent then the current task with the set of dialogues, but might be something to discuss (at least) in parallel.  Perhaps doing each option in R directly will help to resolve how this should be done?

**Comment by rdstern** [comment]
[Ojo_Oluwasegun_Project_With_Rcodes.pdf](https://github.com/africanmathsinitiative/Instat/files/752239/Ojo_Oluwasegun_Project_With_Rcodes.pdf)

In case it is useful, here is the MSc essay that used the radiation data.

**Comment by dannyparsons** [comment]
Reopen if needed but I suggest this can be closed.
