### ISSUE TITLE
Issues from a climatic analysis

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2518]
I was impressed that the initial analysis of the rainfall data for Guyana has proceeded well.  There are some small inconveniences, which I note below:

1) Importing from Excel.  This was different for the xls and xlsx files.  Ideally it would allow the initial lines to be omitted.
2) The name column is just 1, 2, 3,...  In xlsx files this is imported as names, X1, X2, ... which is fine.  In xls the names import as X1.0000, which looks odd.
**3) I suggest that this importing be considered for version 0.3 along with more general improvements to importing from SPSS and Stata (possibly using the sjmisc package).**
4) I then stacked the data, and this worked fine.  Then I deleted the first character from the stacked name column and that worked well.  Then I combined 3 columns to produce a date column.  
5) This produces some impossible dates.  So I then filter on the Date1==NA and delete all those observations, then get rid of the filter.
6) Then I infill the missing observations.  This isn't strictly necessary for the next step, but works fine.  Then I generate 2 columns for the year and day366 within the year.  Then use the inventory plot, which also worked fine. 
7) The real issue was when I worked on 2 sets (one after another).  This crashes with some commands, usually because it is confused and trying to do something to the wrong sheet.  Danny has reported this.
8) One small improvement would be if R-Instat remembers which columns have been calculated from the date column.  Then the infilling could perhaps also infill those columns.

Overall I was really pleased.

**Comment by dannyparsons** [comment]
On 6. this shouldn't be a general issue so it would be good to now which dialogs had this issue and they can be corrected.
