### ISSUE TITLE
The Describe > One Variable > Graph dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2525]
The violin plot does not plot.  It is just a blank.  It plots nicely on the main (Describe > Specific > Boxplot) dialogue.

Could the same person also look at the amount of jitter.  I think the default is 40% and that currently totally blanks out the box plot (or violin plot) if there is a lot of data, such as the ggplot2 diamonds dataset.  

Try (boxplot + jitter) to see what I mean.
We don't need an option here (yet) but try setting the jitter to 20 (or is it 0.2) instead, as a fixed value and see if that is better.

**Comment by dannyparsons** [comment]
I will be editing this dialog as part of new dialog linking so I can investigate this.

**Comment by rdstern** [comment]
Oh, if you are going to do this, then with the new dialogue structure it should be soooooo easy to also add the options for bar charts to display counts and/or percents.

And, of course I wonder how easily we could add a choice of the standard themes.  

No point in having this new structure if you don't try something fun!

**Comment by dannyparsons** [comment]
Have the original bugs been resolved?

**Comment by volloholic** [comment]
@maxwellfundi Can you check this is done.

**Comment by maxwellfundi** [comment]
@dannyparsons Just one original issue of violin not showing is done. Adding width is yet to be done. I am looking into adding that .

**Comment by maxwellfundi** [comment]
@dannyparsons We have width and height of jitter 0.2 with box_jitter and violin_jitter

@rdstern could you confirm that is what is needed?

**Comment by dannyparsons** [comment]
Violin would be the only urgent issue for 0.3 I think.

**Comment by maxwellfundi** [comment]
Okay then thats done.

**Comment by dannyparsons** [comment]
Great will close this. Further improvements for this dialog can go on a new issue
