### ISSUE TITLE
View of data in viewer or output window - no decimals

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2532]
I don't remember this before, but both now seem to be unhappy showing decimal places.  For example with our usual ggplot diamonds data, try the viewer.  All the values like 0.23 are now displayed as 0.

The same seems to be done when you use the dialogue and put the results into the output window.

**Comment by Lunalo** [comment]
@rdstern 

I have checked the occurrence of this error. I will look for a way of solving it.
Thanks.

**Comment by Lunalo** [comment]
Hi @rdstern 
As you might have noticed, when the software loads, the number of digits for options is set to zero as ahown below
![image](https://cloud.githubusercontent.com/assets/13945088/22098029/317f117e-de35-11e6-93a8-993855f354bc.png)

You then need to go to option dialog and change it to desired number of digits to display.
![image](https://cloud.githubusercontent.com/assets/13945088/22097852/52e99c22-de34-11e6-95ca-c59b68313c82.png)

I hope this helps.

**Comment by Lunalo** [comment]
@maxwellfundi 

I think you are editing this dialog. can you make the default for digits to be 2. 
@dannyparsons 
I am not sure if this is what we need but it is necessary

**Comment by Lunalo** [comment]
I have checked the default for digits in r is 7 but I think we might want 4?

**Comment by Lunalo** [comment]
@rdstern 

I have been looking at this since in the code digits is set to 4
can you go to Name]\AppData\Roaming\RInstat\RInstatOptions.bin
and delete RInstatOptions.bin
@dannyparsons 
We should find a solution for this.

**Comment by Lunalo** [comment]
@dannyparsons 

This issue has now been solved
