### ISSUE TITLE
Display of factors in grid

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2539]
1. When a factor is generated from a numeric column, then it can be displayed poorly.  This is (I assume) because it takes the levels of the factor as the actual number and then displays it as a string in R, which is then put into the grid.

As an example use Open from Library > ggplot2 with the 4th data set namely **faithfuld**.  Then use right-click and make the 3rd (and last) column into a factor or ordered factor.  See what I mean?  I am not sure what the easy solution can be.  We could just accept it, or we could perhaps allow formatting of numbers, even when they are transformed into (ordered) factors.

2.  A much easier one.  Please could ordered factors have its own letter, presumably "o" if we have just a single letter.

@Lunalo I have assigned you, but it could be anyone, and in discussion with Danny.

Thanks

**Comment by Lunalo** [comment]
Hi Roger, 

I am happy to work on this

**Comment by dannyparsons** [comment]
We could have an option for number of digits when converting numeric to factor, which could be on the dialog. The default could be the number of digits being used to display the column in the grid. This isn't too difficult to implement but needs some modifying of some of our R methods. Unless it's urgent I would maybe prioritise the other more straightforward tasks now.

For 2. I guess it's easier I just quickly do that.

**Comment by dannyparsons** [comment]
The first part of this has been implemented. Second part relates to general display of column types, which I think should be a separate issue.
