### ISSUE TITLE
New calculator keyboard and bug-fixes in the general calculator

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2540]
David and Danny's calculating "system" is working quite well.  But I gather there are some items to be sorted out.  And we are using R functions that are not yet part of a keyboard.

I hope David and Danny can specify (or do) the changes in the calculator as a whole.  Then that Lily can specify the remaining keyboard, which perhaps John could implement?

**Comment by lilyclements** [comment]
There's a few bugs I noticed the other day, I can't go on to the calculator but off the top of my head they were that reset does not reset, that the 'probability' setting is quite wide (the buttons are wider than with other dialogs) and that on 'Dates', DEK and DOY can now be implemented. Is this DOY366 or DOY?

I have a few suggestions of what else to include in the calculator such as 'length', 'rollapply' and 'match'.

These are just some thoughts anyway!

**Comment by dannyparsons** [comment]
Let's have a separate issue for calculator additions if needed.
