### ISSUE TITLE
New user control for panel

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2542]
As part of the new dialog linking, we have a user controls for each of the standard controls that we use. We have most of them already, and we've decided that instead of having a radio button user control, we will have a Panel user control and put radio buttons in it, so that radio buttons still function as normal.

So could someone make a new user control that just contains a panel that fills the control. It should also inherit from ucrCore?

**Comment by maxwellfundi** [comment]
Great, i am on this task

**Comment by maxwellfundi** [comment]
@dannyparsons  do we need to remove the existing ucrRadioButton?

**Comment by dannyparsons** [comment]
Yes good point. We do, but maybe not right now as we might need to copy some of that code to somewhere else first.

**Comment by maxwellfundi** [comment]
@dannyparsons  please close this too.
