### ISSUE TITLE
R-Instat Installers

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#2553]
@africanmathsinitiative/instat 
Hello everyone, 
We have and we will keep creating installers and uploading them to our African Maths Initiative Google Drive folder. The installers will be available on this link - http://bit.ly/2jvRoje

**Comment by dannyparsons** [comment]
Remember these comments are public for anyone online. I've changed the privacy of the folder so you need to be signed in. Anyone who can't access just send a request to @maxwellfundi.

**Comment by maxwellfundi** [comment]
Thats perfect @dannyparsons . Incase anyone is unable to access then i can help.
