### ISSUE TITLE
dlgDeleteDescriptive - bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2588]
Before changing code, I found a bug with this dialog which might exist elsewhere.
This dialog has a multiple receiver, when the user puts an object in the receiver to delete, then presses OK - it deletes as we want.
However, upon re-opening, if the user puts a new object in the receiver, it does go into the receiver but is not visible.

 
![image](https://cloud.githubusercontent.com/assets/21180424/22404749/4ed9fdf4-e62f-11e6-8728-0a874145d61e.png)

First time opening the dialog, it allows me to see the object in the receiver
 
![image](https://cloud.githubusercontent.com/assets/21180424/22404750/52c22978-e62f-11e6-8992-bef44c24a894.png)

Second time, it does not allow me to see the object once I put it in the receiver (it does enable OK and delete the object so does know the object is in the receiver)

**Comment by stevenndungu** [comment]
This was sorted by #2589 it can be closed

**Comment by lilyclements** [comment]
I don't believe this was sorted in that pull request, I only referenced it there to say that I have reported this bug for when it would be reviewed. I think this is still a bug

**Comment by dannyparsons** [comment]
Thanks, can it be fixed then?

**Comment by dannyparsons** [comment]
This appears to be fixed from my testing, but reopen if there are still issues.
