### ISSUE TITLE
dlgReorderDescriptives - bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2590]
This is an existing bug before any code changes.
If I have two graphs, then open this dialog, I can rearrange the graph order as I wish.
If I then create a third graph and reopen dlgReorderDescriptives, it does not show up on this dialog. We can still only see the other two objects previously created.
On the other three dialogs with descriptives (View, Delete, Rename) the third object does show up.

On this dialog, there is an issue with displaying objects which are added after opening this dialog for the first time.

**Comment by dannyparsons** [comment]
This was general for the reorder control. It now means that it refreshes when you reopen, which means it doesn't always reopen as it closed, but it shows the current order. Possibly what we want anyway.
