### ISSUE TITLE
Updating of Climatic > Define Climatic Data dialogue and related dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2627]
Background first.  I would like to take a (new) version with me next Tuesday - 7th February - when I go to Senegal for a few days.  There I will meet with various people, including Jim Hansen, who funded part of our recent climatic work.

I hope the initial suggestions for this, and other climatic dialogues can still fit within the reforming process that you are doing now.  They are suggestions for considerations when you revise this dialogue.

I assume this dialogue is simple to update into the "new system".  The main change I suggest is to avoid the long list, which has to be scrolled down.  Perhaps - as this is a design issue it is something for lily to try sometime?  I have 2 suggestions.  In both cases I would like to separate the columns that relatre to place and time, from those on the actual elements.  Currently Date and Station are first, and then year, etc is right at the bottom.

So either could we try:

a) The date and time columns are in a separate box below the selector.  The dialogue will be just a bit larger.
b) there are two parallel sets of columns, so all are visible immediately.

There is a bigger issue, which is why I have copied David and Danny into this message.  This is that there are also location columns, particularly latitude and Longitude.  So there could in fact be 3 sets of column, namely  "When", "Where" and "What".  I even quite like those as simple labels.

**When** gives the date and other columns with the year, etc.
**Where** gives the station and latitude and longitude.  (There is a potential issue that they might be in a linked data-frame, and not in the main one.  There may be a clever way to do this, but for now, I suggest you could open the dialogue twice, going first to the data and second to the lat and long frame?  Perhaps if the link is already in place and lat and long have default names, then it can complete these fields automatically. 
**What** gives the elements.  Maybe "Elements is a better name than "What"?
For the elements we could have them all visible, (I think my preference?) or have a "More" button.  When that is pressed, then either it opens another set on the rhs, (like our calculator) or it opens a sub-dialogue.  
I am not convinced this is worth a sub-dialogue.  I quite like the way our calculator can open another part to the same dialogue.

**Comment by rdstern** [comment]
A second dialogue to update to the new "system" is the one for the start of the rains.  What would be great here is for this dialogue to automatically fill some of the columns if it is used after the define climatic data dialogue.  Then it should know which column is the rainfall and could then complete this information automatically.

**Comment by stevekogo** [comment]
@rdstern I am going to start on define climatic data factoring in your suggestions.

**Comment by dannyparsons** [comment]
The autofilling of a single receiver has already been implemented. We have just turned it off by default. So someone (@lilyclements?) just needs to turn it on for any receiver that we want it for.

**Comment by lilyclements** [comment]
Yep, I was told the plan was that @rdstern and I would discuss which dialogs to turn this on for
