### ISSUE TITLE
Some dialogue not to be updated

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2635]
In the **model** menu the last 4 main items are all called **Other**, e.g. **Other (One Variable)**.  They correspond to at least 10 dialogues.

Ignore all these dialogues - at least for now.  It is likely that all their functionality will be handled by the earlier (more general) modelling dialogues in the same menu.

In the Excel list of dialogue names Lily is adding "Ignore for Now" as a comment.
 
Thanks

**Comment by lilyclements** [comment]
I believe I have done this now for all dialogs which are in the "other" part and not also above the line (such as dlgRegressionSimple)

These are
dlgGeneralANOVA
dlgGeneralRegression
dlgGoodnessofFit
dlgNon-ParametricOneSampleTests
dlgNon-ParametricOneWayANOVA
dlgOneSample
dlgOneWayAnova

I've put "ignore for now" next to these dialogs

**Comment by maxwellfundi** [comment]
@dannyparsons This can now be closed
