### ISSUE TITLE
Adding method for checking if ucrDataFrame is empty 

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#2644]
Hello @africanmathsinitiative/instat 

As i was working on dlgExport. I realized that we needed this method in the TesTOKEnabled.

The reaso why i didn't implement it  because we need ucrCombo instead of current  normal combobox.

I hope we will discuss on the preferred implementation soon.

Thanks.

**Comment by dannyparsons** [comment]
@Lunalo This message is quite vague, I'm not sure others will understand what you mean from your message. For example, you said: 
> we need ucrCombo instead of current normal combobox

Where do you need ucrCombo? What for? Why? etc.
If you can explain bugs more clearer it will be easier for others to help with them.

**Comment by Lunalo** [comment]
@dannyparsons  Thanks 

We need user control to replace the existing ucrAvailableDataFrames for consistency. I think this will make it easier to systematically  implement the method for checking if the ucrDataFrame is empty. 

This check is useful in some dialogs that requires ucrDataFrame to contain name for ok to be enabled 
I am still convinced that there are some  other factors to be considered when implementing this.
