### ISSUE TITLE
Graphics bugs with the latest version

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2666]
I was preparing for a demonstration to AIMS Senegal.

a) Describe > One Variable > Graph.
Worked OK for GGPLOT diamonds with all columns, and flipping.
But **no violin plots** appeared.
b) Also on this one variable graph, when it does jittered plots they are to the default width, which blots out the background plot.  Could you make the jittered width, say 20, rather  than what I think is the default of 40? 
c) Correlations worked fine, and I like the graph in the separate window by default, because the graph in the output window still doesn't expand fully when you use full screen.  But it is an example where adding the graph options would be good.  Also for PCA and (I think) CCA.
d) Did a line plot and then tried to **change the y axis limits**.
1) It doesn't have any effect.  I don't think it is connected.
2) If it did, then it would have totally messed up, because the limits are an up-down control with a maximum of 100.  We don't want up-down controls here, because we have no idea of the scales for the graph.
e) I now looked at the Describe > Two Variables > Graph  This needs imporvements to bring it to the level of the one variable.  There is no Coord Flip.  Then the options added to the one variable, like violin plots and jitter need to be added so the dialogues are consistent.

I am now also adding Maxwell and Steven, so they see this.  But I am not assuming they necessarily make these corrections.

**Comment by dannyparsons** [comment]
@stevenndungu can you check that these have all been done or report anything still to do?

**Comment by stevenndungu** [comment]
a) Done
b) Not done yet. width of 20? or a smaller number..width default is NULL. 
c) Working fine. Disabled rdo scatter matrix plot on the sub-dialogue (was breaking), tried to fix but sounds more demanding. Added in package names
d) Fixed already
 e) Improvements suggested on e) have not yet been added. Will have a look at it later.

**Comment by dannyparsons** [comment]
Sounds good, thanks for investigating.
