### ISSUE TITLE
Testing Dialogs

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#2678]
Hi  @africanmathsinitiative/developers 

I have found it a good practice to test dialogues  with multiple data sets opened. 

After working with @AlexSananka  on Permute Rows, Our Dialog seemed working very well. We encountered a shock after Alex decided to open a new data Set. You can guess what popped on the screen! An Error. And so we had to adjust our code before committing the changes. 

I wrote this because we had dialog online with the same error but no one noticed the existence of that error.

Thanks.

**Comment by rdstern** [comment]
Delighted you have found this point.  I usually open the ggplot diamonds data set as a default, before opening the one used for the testing.  So I always have at least 2 sheets open for any testing.

**Comment by dannyparsons** [comment]
This is a great idea.

I would also add that you should test dialogs when you have a filter on the data. Firstly to make sure it doesn't crash and then that it does the correct thing with the filter.
Most dialogs should use the filtered data, however some should not (e.g. calculator). Just ask if you're not sure what a dialog should do.
