### ISSUE TITLE
Dialogues for frequency and summary tables

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2720]
This dialogue should be easy to construct - hopefully with our new dialogue system.  I hope that the R part will also not be too difficult and that it will build on:
1) Our summary system
2) The new system for the output windows that lets us have HTML tables.

I am sure the "system" will need some David/Danny discussions, and it would be great if this could be tried out with the dialogue already in place.  It is **Describe > Specific > Frequency** in the current menu system.

To see a picture of roughly the layout look at the old Instat under **Statistics > Tables > Frequency**.  It will be  similar to that dialogue.  Later we will be able to use the old Instat to check the results too.   

So there is the usual data selector control and a multiple receiver with the label "Factors".  The selector only has factors.

Below that receiver is a block with the label "Display" and 3 options.  Unlike the old Instat I suggest these should be check-boxes so more than 1 can be selected at a time.  These three check boxes say:
1) Counts  (default is for this to be checked)
2) Overall Percentages  (default unchecked)
3) Percentages of (default unchecked)

Part of option 3 above is a single receiver.  If the focus is there then (ideally) you could only choose from the factors that have been selected.  I assume this would still be from the original selector, restricted to the selected columns in the main receiver.  This might be a new feature of the control?

Under the selector is a check box (as in the old Instat) with the label "Weights"  If that is checked, thyen there is a single receiver and the data selector then shows only number columns.

Finally there is another set of controls with the overall label "Layout".  Inside is (as with the old Instat)
1. )A checkbox with the label **Display Margins**. Default is for it to be checked.
2) A label Column Factors, followed by an up-down control.  It can be anything between 0 and the number of factors in the main receiver.  Default is 1.  (Could be 0 if no columns are selected.
3) Decimals with an up-down control between 0 and 5 with default 0.

OK is enabled when:

a) There is at least one factor in the receiver.
b) And at least one "Display" checkbox is selected
c) If **percentage of factor** check box is selected, then a factor column must be selected for OK to be enabled (again?)
d) If the **weights** check box is selected, then a column must be selected for the OK to be selected (again?)

For now also have an options button - currently disabled.  The two extra elements will later be as follows:
1) How to display the results when the display has multiple elements checked.  

a). The default could be "Separate Tables".  
b). The two other possible Options could be "Vertically" and "Horizontally".

2) Display of some margins but not others.  This could be very confusing in general and needs more thought.

3) I am sure there will be other options to produce nice HTML tables.

**Comment by rdstern** [comment]
This is now the next dialogue, i.e. **Describe > Specific > Summary**.

The start is similar to the first part of the frequency tables above, i.e. as far as:

1) Selector ready for just factors.
2) Multiple receiver for the Factors with the label "Factors"
3) Check box for the weights.
4) Block, with label "Layout" and the same 3 options for Display Margins, Column Factors and Decimals.

Now the extra parts:
1.) Below the main receiver is a second multiple receiver with the label "**Summary Columns**".  When this is filled it is just for numeric columns.  (for now).
2) There is a checkbox below the Weights which says "Treat Summary Columns as a Further Factor".  This is possibly only enabled when there is more than one summary column. (need to check this point with David.)
There is a button (as for other summary dialogues) that says "Summaries".  For now it calls the same Summary sub-dialogue as the others - but that will change, because it is only for numeric columns.

**Comment by AlexSananka** [comment]
@rdstern I am taking up the task.

**Comment by AlexSananka** [comment]
@rdstern On the extra parts the second point isn't clear ''2) There is a checkbox below the Weights which says "Treat Summary Columns as a Further Factor". This is possibly only enabled when there is more than one summary column.''Should it be a checkbox or a button or just a text message?

**Comment by rdstern** [comment]
As said in point 2, it should be a checkbox.  Let me explain.  Suppose you use the data set called **survey** from the Instat Introductory guide (Open From Library).  You want tables of (say) the count of how many farmers used each combination of the 3 varieties in each of the 4 villages.  You also want to min, mean and max of their yields.  So you are asking for 4 summaries in each cell of the table.  This could be 4 separate tables.  It could also be a 3-way table, where the 4 different summaries are treated like a third dimension of the table.

**Comment by AlexSananka** [comment]
@rdstern the layout and designer for the summary tables is ready,what is the Rcode for it so that we can know which functions are being used.
