### ISSUE TITLE
Standardise Country Names dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2734]
New dialog for corruption. Just has a selector and a multiple receiver.
Method not written yet but will be instat method `standardise_country_names`.
Parameters: `data_name` and `country_columns`
It should also have a way of having some columns already in the receiver when the dialog opens - as we have on other dialogs that open from right click menus.
This is quite urgent for tomorrow. Could someone do it in the morning? I can take over later if needed.
[SKM223 HP R17030118260.pdf](https://github.com/africanmathsinitiative/Instat/files/812075/SKM223.HP.R17030118260.pdf)

**Comment by maxwellfundi** [comment]
@dannyparsons  close this too .
