### ISSUE TITLE
Linking controls with receivers

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#2743]
We would like a feature where, we could link controls with receivers. 

In my case i wanted to link a numeric up down, such that is shown when a receiver is not empty, but this has not been implemented yet.

**Comment by lilyclements** [comment]
To add to this, I've come across one (dlgDefineCRI) where one thing is displayed if the item is of one data type (e.g. Numeric) and another thing is displayed if of another datatype (e.g. factor)
