### ISSUE TITLE
File menu new items

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2751]
Could you add "Import from CSPRO"  and then "Import from Databases" to the file menu.  They should be visible but disabled.  They can go just under the "Import from ODK".

I am sending this to John, but it could be anyone who has the time.

**Comment by Lunalo** [comment]
@AlexSananka  can add the two dialogs and I will edit the menu

**Comment by AlexSananka** [comment]
I think I can handle this

**Comment by lilyclements** [comment]
Has this been done? (Can we close this issue)

**Comment by AlexSananka** [comment]
This should be closed
