### ISSUE TITLE
Describe > One Variable > Summarise problem

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2753]
Open the diamonds dataset from the ggplot library.

The command works OK with the default settings.  If you customise and just use the factors, there is a bug.  I think it isn't coping well with ordered factors.

I also tried with the survey dataset.  When I made the Fert column into an ordered factor then I got the same bug.

**Comment by stevekogo** [comment]
I will have a look at this.

**Comment by rdstern** [comment]
I tried the above, again with the diamonds dataset.  As before the default works OK.

But I had all columns and then tailored the summary to give max and min plus some others - and got:
---------------------------
Error running R command(s)
---------------------------
Error in c(, , "summary_sum", "summary_count_non_missing", "summary_count") : 
  argument 1 is empty


The error occurred in attempting to run the following R command(s):

InstatDataObject$summary(columns_to_summarise=c("carat","cut","color","clarity","depth","table","price","x","y","z"), data_name="diamonds", return_output=TRUE, object=c("carat","cut","color","clarity","depth","table","price","x","y","z"), summaries=c(, , "summary_sum", "summary_count_non_missing", "summary_count"))
---------------------------
OK   
---------------------------

**Comment by lilyclements** [comment]
To the first problem you were having: An issue we've had for a while that needs to be fixed is that it brings an error if you have at least one factor and do not select a summary-factor-option, that is, if you don't select something from the "common" groupbox. Does that sound similar to what you were doing or is this another issue?

I'm struggling to replicate your second problem which will make it difficult to fix! I'll have another go at replicating it tomorrow!

**Comment by dannyparsons** [comment]
Second problem as been fixed already in the subdialog.
First should be fairly easy to fix in the R code.

**Comment by dannyparsons** [comment]
fixed first issue, if no valid summaries, output will be NULL

**Comment by lilyclements** [comment]
Great, just tested it and it looks good! Can this be closed now?

**Comment by dannyparsons** [comment]
Already closed it :wink:

**Comment by lilyclements** [comment]
Always one step ahead!
