### ISSUE TITLE
New menu item: Describe > One Variable > Frequencies

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2757]
This is after Graph, i.e. at the bottom of the One variable menu.  There is a line before it.   It will do either a frequency graph, or a frequency table, or both!  It will be useful in its own right and possibly for Danny and for the IASE paper.

1. The dialogue could be called "**One-way Frequencies**"
2. There is the **usual selector** and (to start with at least) a **single receiver**.  For now, all columns can be allowed (we may restrict to Factors later.)  The label is therefore the same as the other dialogues in this menu.
3. It will generate either a frequency table, or a ggplot graph, or both.  So there is the control to **save a graph** at the bottom of the dialogue.
4. There is also a checkbox (default unchecked) with the label **Weights**: If it is checked, then a **single receiver** is visible.  The selector is now restricted to numeric columns.
5. There is a checkbox with label "**Table**".  Default is checked.
6. There is a checkbox with label "**Graph**".  Default is unchecked.  (Don't worry now that both could be unchecked.  If so, then for now we could still produce the ggplot graph object and not dispaly it. 
7. There is a set of 3 **radio buttons** with the overall label "Sort".  They have the 3 options "None, Ascending, Descending".  The default is None.
8. There is a checkbox (as in the existing one variable graph, for "Flip Coordinates".
9. There is an **Options button** leading to a sub-dialogue.  For now leave this blank.
10.  I am getting concerned that the dialogue may look "cluttered".  If you feel that is the case, then there will be items for the sub-dialogue and perhaps the sorting options could be moved there?

This will use the sjplot package.  There are 2 commands, namely sjt.frq and sjp.frq that will be run to get the table and the graph.  Lily to check on these in R, and to consult with Danny if needed.  At the same time to see whether they could be run through the wrapper commands sjplot and sjtab.  If so, then the same 2 commands could be used for the 2-way tables - coming in the next issue. 

In the sjplot package information there are useful examples for each of these two functions.  You get to them easily online from the sjplot reference manual.

**Comment by stevenndungu** [comment]
@rdstern thanks, looking on this.

**Comment by lilyclements** [comment]
So I like this a lot. The sjPlot and sjTab contain everything we wish to do because by default they call
`fun = "frq"`
and this "calls sjp.frq or sjt.frq. If data has more than one variable, a plot for each variable in data is plotted."

So, lets use sjPlot for the graph and sjTab for the table. This way we can use the same functions for one way and two way frequencies.

**sjtab**
This function has many parameters (mainly because sjt.frq does). The ones we are currently interested in are
data = dataframe name
var.cnt = variable of interest
sort.frq = "none", "asc" or "desc" (with quotation marks). The default is "none"
weight.by = variable of interest

**sjplot**
this is the same as before, but also has
coord.flip = TRUE/FALSE. This is false by default

One thing is that weight.by wouldn't work for me until I downloaded Hmisc.

Additionally, ggPlot needs to be updated to the 3.3.1 version in order for the sjPlot package to run.

We also have options for the table labels/type of plot/etc which I assume will be options in the sub?

**Comment by lilyclements** [comment]
Okay so after a discussion with Steven we have made some decisions and feel sjtab and sjplot are not ideal. This is in part because their parameters do not have names for the variables which is confusing.

We feel what is best is:
One Variable - Table: sjt.frq(data = variable)
Two Variables - Table: sjt.xtab(var.row = variable1, var.col = variable2)

One Variable - Plot: sjp.frq(var.cnt = variable)
Two Variables - Plot: sjt.xtab(x = variable1, grp = factorvariable)

**Comment by rdstern** [comment]
The dialogue seems to work.  For the graphs why disable the sort option?  It would be useful.
I assume the work will resume (at some stage) on the tables being in the output window?

**Comment by rdstern** [comment]
Steven thank you for the drafts of the sub-dialogues.  I have now looked at the function in more detail - in RStudio.  I used the ggplot diamonds data as an example.  Some of those columns (3) are factors and the others are numerical.  Here are my thoughts - here on the graph - next on the table:
a) We do want to allow either type of data to be used to be used (numeric or factor).
b) We don't need all the options for the **types** of graph.  We do the violin, histogram and boxplot better ourselves.  So just permit **bar** (default), **dot** and **line**. 
c) So now many of the options in the function immediately become redundant.
d) The sort is important and should be activated for the graph.  
e) The option to save the ggplot graph object is important. 
f) Keep the coord.flip as now.
g) One check box is "Show Missing".  Default is unchecked.
h) Check box with label "Show Counts".  Default is checked.
i) Check box with label "Show Percentages".  Default is checked.
j Check box with label Group Data.  If checked, then Up down with minimu 2 and maximum 100 in steps of 5.  Default (when open) is 10.  
k) Check box with label "Vertical Label Positions" If checked, then can choose from drop-down.  The options are given in the description of the function.
l) Ditto for "Horizontal Label Positions".

I think that's all for the graph.

**Comment by rdstern** [comment]
Now I look at the details for the table, most of them are different from the graph.

So it could be that the items that are the same would be on the main dialogue, and those that are different are on the sub-dialogue, in their respective tabs - sort of as you have.

This could mean that the "Group Data" option (see item j) above, is on the main dialogue.  And you may want to move the saving of the graph to the sub-dialogue.

Then add (on the sub-dialogue):
a) Check box for "Alternate Rows Coloured".  Default not checked.
b) Check box to "Emphasise Median".  Default not checked.
c) Check box for "Show Summary" Default not checked.  (That will then have to be in the command, because the package default is checked.  But it makes little sense for nominal factors.
d) So don't bother at all with quartiles, or skewness or kurtosis.  This isn't the place for them.
e) Check box with label "Omit Zero Counts from Table".  Default unchecked. (That's the skip.zero)
f) Check box with "Decimal places for percentages".  If checked there is an up-down from 0 to 4, with default 0.  (This is the digits argument)

And just a reminder for something we leave now.  But when we use the stringdist package (later) then there is another option here - which looks really interesting!

**Comment by stevenndungu** [comment]
Wauw! Well simplified. Thanks for this, I will make the adjustments and have the sub-dialogue working tomorrow.

**Comment by rdstern** [comment]
For reference for later.  This would be great to get working with these options, and in this form.
There are then some further possible steps that could be welcome given this command and the menu.
a) Investigate the stringdist package.  The place for the dialogue is already there, namely Prepare > Column:Text > Distance.
b) Consider having a "wrapper" for this command, so that it can be used for columns of different types, i.e. factor, numeric, text.
c) In the wrapper consider saving the graph and providing no output, but then using combine, or facets to produce a single graph later.  Or a sequence of tables - that should be easier.
d) Applying the stringdist options - in the command, to the text columns.  That could also be explored, (without the wrapper), for a single graph.
e) It is possible that we don't even need a wrapper - but could apply the command repeatedly, for multiple columns.

**Comment by rdstern** [comment]
[http://www.lse.ac.uk/methodology/tutorials/SPSS/describingCategorical.aspx](url)

This is an interesting and simple video that shows the use of the same function in SPSS.  In the tutorial there are some interesting things to notice.  One is the dialogues that contain the variable labels rather than the short names of the columns.  Notice also the use of value labels - which are our factor labels.

**Comment by rdstern** [comment]
One extra check box for the table output is as follows:
g) Name for the Counts.  If checked, then  you can input a string.  The default is N.  The is the string.cnt argument.  

One reason I think this could be useful is shown by the example with the standard survey data.  Get the table with Village as the factor and Yield as the weights.  Then the values in the N column are the total yields in each village, and the overall total is added over all villages - it is just the total yield overall!  It is a bit confusing to have that column called "N" so nice to be able to change the label.  I don't think we need to change any of the others.

**Comment by rdstern** [comment]
When I use the little survey data set, I can do the graph for any column, but the table only works for numeric columns.  It won't work for the Village or Variety.  They come in as string columns, but making them into factors.  

Have you tested doing tables for this dialogue for factor columns?

At the same time I strongly suggest you change the command and use sjplot or sjtab rather than the special commands.  We discussed this issue over skype.

**Comment by dannyparsons** [comment]
For me tables work fine with numeric or factor columns, however it doesn't work with character columns. Did you notice this @stevenndungu?

If I do multiple columns and one is a character it just gets ignored, but if I just do a character column on it's own I get this error:

> object 'page.content' not found

I suspect this is (another) bug with the sjPlot package which we should report.

Graphs do not seem to have the same issue.

**Comment by dannyparsons** [comment]
Also, I found the Sort option confusing at first. I thought it was going to sort by the order of the levels of the factor or if numeric - ascending and descending values. Could the radio buttons be changed to "Ascending/Descending frequencies" to make it clearer? Unless it was just me that was confused by that.

**Comment by rdstern** [comment]
I wasn't confused, but I like that change, i.e. "Ascending Frequencies" etc.

I also confirm the bug Danny found for character columns.  I wondered if that would not be the case for data imported from SPSS, but the problem remains.

**Comment by dannyparsons** [comment]
Ok thanks, will report it on sjPlot issues.

**Comment by AlexSananka** [comment]
Can this be closed too?

**Comment by dannyparsons** [comment]
I think just changing the radio buttons to "Ascending/Descending frequencies" is still to be done.

**Comment by AlexSananka** [comment]
I can fix this.

**Comment by AlexSananka** [comment]
This should be closed now
