### ISSUE TITLE
New Menu Item: Describe > One Variable >Rating Data

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2761]
This does not have a milestone, and might be done in April rather than for the current version.  Howver it may be very easy to do, because it follows the same format as the other graphs from the sjplot package.  

First you could look at what you are aiming for.  In the sjplot Reference Manual, page 61 there is a "See Also - sjPlot manual: sjp.likert and similarly on page 95 for sjp.stackfrq and page 146 for sjt.stackfrq.

1. The name can be "Rating Scales"
2. There is the usual selector and a multiple receiver.  The label for the receiver could be "Selected Ordered Factors".  If this is too long, then perhaps just "Ordered Factors".  This dialogue is only for Ordered Factors.
3. It is also for (Multiple) Ordered factors with at least all the same number of levels, and probably the same set of labels, e.g. a set of questions all with the same labels "Very Bad", "Bad", "Middling", "Good", "Very Good". (We need to think how to check this.  It relates to being able to easily distinguish different blocks of columns.)  We need to be able to check the number of levels at least and get access to this in the dialogue.
4. The next options are all similar to those from #2757 namely first :
It will generate either a frequency table, or a ggplot graph, or both. So there is the control to save a graph at the bottom of the dialogue.
5. There is also a checkbox (default unchecked) with the label Weights: If it is checked, then a single receiver is visible. The selector is now restricted to numeric columns.
6. There is a checkbox with label "Table". Default is checked.
7. There is a checkbox with label "Graph". Default is unchecked. (Don't worry now that both could be unchecked. If so, then for now we could still produce a ggplot graph object and not display it.
8. If checked then there is a choice (2 radio buttons) between "Stacked" and "Likert".
9. In item 8 if Likert is chosen and the number of levels is an odd number for the factor, then there is an Up-Down control visible with the label "Neutral Level".  It is between 1 and the number of levels with the default being (nlev+1)/2, i.e. the middle level.
9. There is a set of 5 radio buttons with the overall label "Sort". They have the 5 options "None, Low Ascending, Low Descending, High Ascending, High Descending". The default is "None".
10. There is a checkbox (as in the existing one variable graph, for "Flip Coordinates".
11. There is an Options button leading to a sub-dialogue. For now leave this blank.

**Comment by stevenndungu** [comment]
@AlexSananka  how is this going?

**Comment by AlexSananka** [comment]
@dannyparsons  was to work on it from somewhere.#2872

**Comment by dannyparsons** [comment]
Yes on my list of things to get around to.

**Comment by rdstern** [comment]
I like what is working here now.  I tried it wil the example from sjmisc, columns cop1 up to cop9)
a) The table was OK,  Will these tables later be in the output window?
b) the graph (stacked) was OK when the columns were numeric.  I made them factor and then it gave the levels twice so was unclear.  When I made it numeric again it was OK - which is good.
c) A further remaining bug which is more general is that I made them ordered factors - and this doesn't work for the labelled columns.

**Comment by stevenndungu** [comment]
@AlexSananka  was the above mentioned issue addressed?

**Comment by AlexSananka** [comment]
This are still not addressed we can maybe have a look together and see what we can do

**Comment by volloholic** [comment]
@AlexSananka Update?

**Comment by rdstern** [comment]
This dialogue is currently for viewing only.  It is Describe > One Variable > Rating Data.  It uses plot_likert from the sjplot package.  The function is (I think) now imporved and it would be very good to get this working.

**Comment by Gioche6** [comment]
@Patowhiz , this is the issue I just informed you about. I have updated the functions already.
