### ISSUE TITLE
Simple dry spells dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2772]
I suggest a simple dialogue for now - as sort of "partner" to your start dialogue.  I suggest that both (and water balance!) will change, but these will be useful.

1. One missing aspect (to ignore for now) is that there is no mention of "Station" in the existing start dialogue.  For now I suggest similarly for the spells one.  Need to think about this later.  

2. Also, in the start, I don't quite understand the need for the Year and day of year fields?

3. For the start, I assume the resulting worksheet is linked, so another definition would go into the same sheet?  Hence a similar calculation of spell lengths would also (automatically?) go into the same sheet?

4. So, in the new dialogue, instead of threshold you have "Condition".  This has 2 parts to it, with the first having just 3 options, namely "<", "Between" and ">".  Default is "Between" and this then has 2 text boxes open with default values 0 and 0.85.  If < the second box is hidden, and if > the first box is hidden.

5. The "From" and "To" fields remain as you have them.  perhaps they could instead say "From Day:" and "To Day:" - on both dialogues.

6.  So, for now, the spells dialogue will produce just a single column - as does the start of the rains.

7.  There is a checkbox underneath - default unchecked, with label: "Conditional on Rain at start of spell".  If checked this starts the count of the spell length only as 1 on the first day.

That's all for now!

**Comment by rdstern** [comment]
What is next on spell lengths?  

1. Well clearly we will produce multiple spells at the same time - as we can with the existing Instat.
2. We will also be able to do "relative" spell lengths.  That is when the days start with day zero (say) from the start date, i.e. they must be able to pick up a column from the new start sheet.
3.  We will change both dialogues, to include sub-dialogues - and make them more consistent.
4. A bigger one is that I see this (at least for spells) as being then ideal for the Climatic > Prepare menu - where it is now.  In the Climatic > Describe menu the resulting columns may only be intermediary and would then be further processed to produce a graph.  This is also a separate dialogue in the old Instat - but quite difficult to teach and use.

**Comment by lilyclements** [comment]
The DOY field is needed so the user can specify which days they are interested between (e.g. 122 and 366). The year field is needed so we can do a "by" for year - this enables us to look at each individual year for the start of rains rather than the overall.

As to your point that the Dry Spells automatically goes into the same sheet, this is correct (unfortunately). Something we should fix for the future.

Also I'll change the From and To, good idea.

I'll get working on this now

**Comment by lilyclements** [comment]
If we want this done quickly, I should use the old system because it's more or less written in that system so shouldn't take too long. However, if we want this done with the new system then that is fine but will take longer. What are your thoughts?

**Comment by rdstern** [comment]
I thought the DOY and Year could follow from knowing the date?

"As to your point that the Dry Spells automatically goes into the same sheet".  That isn't a problem to me.  I am really happy with that.  Then we are getting all our "events" together in a "year" sheet.

You say: "I'll get working on this now".  Great! Thanks

**Comment by rdstern** [comment]
I am all for quick.  There will be more changes later

**Comment by lilyclements** [comment]
Okay I did start in the new system earlier but hit a few hurdles. I'll save that somewhere in case Danny has some spare time when he arrives to help me with this. For the meantime, I should have it done in the old system shortly

**Comment by lilyclements** [comment]
I wanted to check a few of these new features. So, on "Condition:" with the between/>/<, what does this do? Is this just the threshold so I want a threshold >0.85 (say) or <0.85 etc?
Currently, presumably, we have Rain >= 0.85 for the threshold?

Also, can I do >= and =< instead of > and <?

**Comment by rdstern** [comment]
If we repeat what was in the old Instat, then this works as a general spells dialogue.  Could be dry spells, or wet spells, or hot spells, etc.  So the condition is what is TRUE for the spell.  So if thr condition is < 0,85 then  that is what is true.  If 0 to 0.85 then all values between these values (inclusive) is in the spell.

And yes please to adding <= and >= to the set.  In the future we may want to link this with the Filter condition - so it may become a button, with the current condition shown.  (Then we may want an AND for the two conditions, but I don't want to go there yet, because we would also want an OR allowed.

So quite happy for now is just < or > for now, i.e. just a single number allowed.

**Comment by lilyclements** [comment]
Okay thanks, would I therefore want it to be on a dialog called Spells instead of Dry Spells then?

**Comment by rdstern** [comment]
Yes.  I would say **Spells** or even **(Dry) Spells** - as that is its main use

**Comment by lilyclements** [comment]
Great. This is getting there - has an issue which I cannot solve at the moment where you have to do the things for the dry spells last (i.e., the length of time and maximum day nuds) to avoid an error. This is that we need the Dry_spells filter to run before the number of days filter as otherwise we have an error. This canbe fixed inthe new system where we can give the parameters an order
I just need to add in the checkbox. What do you mean by "If checked this starts the count of the spell length only as 1 on the first day."?

**Comment by rdstern** [comment]
You may want to plant on a particular day, say 20 April - because there was rain.  Now you want to calculate the length of the longest dry spell in the 30 days from 21st April assuming 20th April had rain.  If you restrict yourself to just the years when 20 April really did have (enough)rain then you don't get many years.  So let's pretend that **20th April had rain every year**.  So start counting dry spells from 21st April with a zero - for rain - on 20th!

Hope that is clear?

**Comment by lilyclements** [comment]
@rdstern what needs to be done to this dialog for this release? Or is this ready?
This hasn't been updated yet (i don't believe it has anyway) but other than that seems to run well

**Comment by rdstern** [comment]
This needs some minor improvements.  In particular it is not just for rainfall.  It could be hot spells, cold spells, windy spells etc.  So:
1) Change the menu item from **Dry Spells** to **Spells**
2) Change the field called **Rain Column** to **Element**.  Still put the Rain element in there by default.
3) Change the position so that all the date fields are first.  So this moves to position 5.
4) Change the Condition fields.  I suggest no text where it currently says "Amount of Rain".  That will make the control smaller too.
5) I need that same set of controls in the Display of Daily data dialogue.  So consider making them (as a set?) into a user control.
6) "Conditional on Rain etc at Start of Spell - i.e. add etc to label.
That's all the simple ones.

But when you consider getting start days from a column for the water balance, then this applies here too (and for the climatic summaries).  Thus you might want the longest dry spell between the start and end of the season, i.e. different for each year.

Ideally this would also be in the next release?

**Comment by shadrackkibet** [comment]
working on this.

**Comment by lilyclements** [comment]
@shadrackkibet 
For 2. you can change the label to Element, but this receiver is also currently restricted to only select rainfall columns only. This should be removed and instead we should accept any numeric column (is any numeric column correct @rdstern ?)

**Comment by shadrackkibet** [comment]
@lilyclements  what does Roger's point 5  mean here?.. Do we need  a user control??

**Comment by rdstern** [comment]
Sorry, that point 5 wasn't clear.  It refers to point 4 where there are 3 fields in the row labelled "Condition".  It is that set that could become a control as it could then also be used in the display of daily data.  There it would permit a special symbol to be provided for some of the data when the daily data are being presented.  For example in the display of daily rainfall I usually show "--" for zero rainfall values.  That then shows the non-zero amounts more clearly than if they are given as "0.0".
