### ISSUE TITLE
Show Non-Missing for Inventory plot

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#2786]
Basically this feature would take the data that is present and split it into 2 categories - where the user can decide what values are in one category, and what are in the other.  In rainfall it could therefore permit a different colour for dry and rainy days.  In temperature it could distinguish between hot and not-hot, etc.
Usually you will specify a single value.  This (of course) could be taken further.  It was quite nice for the "old" plots of the rainfall that you could do before, but it isn't that important now.  I have no problem if you leave it for now.  There will be other suggestions for improvements to the dialogue besides that!

@stevekogo  I have put this here so that we wont forget about this option.

**Comment by rdstern** [comment]
Another reason for the delay is to combine that feature with others that are requested.  For example the "old" inventory plots also permitted a useful label to be on the right-hand side of the plot as well as the left.  Then (with multiple stations we may want to sort in a particular order.  By default the stations are likely to be in alphabetical order whereas it may be more useful for them to be presented in latitude order.  These latitudes could also be a label and could come from the station (i.e. factor level) information.

**Comment by dannyparsons** [comment]
This is now implemented, with more flexibility to be implemented on the dialog. There is a duplicate issue for this so closing this.
