### ISSUE TITLE
Various small issues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2793]
These may not be essential for the next version.  But...

1. Prepare > Data Frame > Rename
a) I used it for 4 columns in turn.  When I first went in I changed the name of X1.  It offered me X11 as its choice.  I made the name "Number.
b) When I went in again to change X2 the dialogue suggested the same name, i.e. Number - that it had before.  I can see why it might do this, but it is a pretty bad idea to have lots of columns with the same name.  
c) We should not spend too long on this feature just now, because the dialogue needs to change  - soon I hope - but not for Version 0.3.  It needs to permit easy changes of names for multiple columns.

2. Change decimals displayed

The first column had 2 decimals.  I wanted zero.  I could not see where/how to do this?

3. Describe > One Variable > Graph

I am a sort of broken record on this.  

a) I keep trying a violin plot and it continues to give me an error. 
b) I now found that violin + jitter does work - perhaps.  But you can't see the violin, because of the amount of jitter - at least for the diamonds data set.  Could the jitter be a fixed 20% (perhaps) rather than the default (which I think is 40%.

**Comment by Lunalo** [comment]
I will fix issue number three for now as the other two needs more discussion
