### ISSUE TITLE
Issues with Prepare > Reshape > Column Summaries and Unstack and decimals for multilevel paper

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2800]
[heart.xlsx](https://github.com/africanmathsinitiative/Instat/files/852587/heart.xlsx)
Here is the dataset I used - thinking of the multilevel paper.

I made days and sex into factors.  I wanted just the count, not the sum, or the count with missing.  So I unticked them.  I wanted just the counts for these 2 factors.  It needed a variable or OK wasn't enabled.  Maybe there should be a separate dialogue for just counts?  Anyway you can put any other column in as the variable.

But then I got the sum of that variable and both counts, though I had unticked those options.

**Comment by rdstern** [comment]
I continue here as it involved the same data set.

After the summary, I did an unstack.

I gave the 2 columns, and it wouldn't let me continue, i.e. OK enabled, unless I gave an ID column.  Are ID columns necessary for the command.  I didn't think I needed one this time?

I then got to the data in the attached document
[cs11_checked.docx](https://github.com/africanmathsinitiative/Instat/files/852612/cs11_checked.docx)


Of course except that my counts still all have 2 decimal places.  As they came from counts, zero would have been better!

**Comment by dannyparsons** [comment]
- Column summaries can now run without choosing variables. It ignores whatever summaries you have chosen and just does counts. Better long term solution for this needed but was simplest to implement now.
- Counts also display as integers now.

Only remaining task is looking at the unstack dialog - this could be a separate issue to look at enhancements to this.
