### ISSUE TITLE
Prepare > Data Frame > Sort not working

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2808]
Gives error as follows:

---------------------------
instat
---------------------------
Developer error: no state of control ucrPanelMissingValues satisfies it's condition. Cannot determine how to set the control from the RCode. Modify control setup so that one state can satisfy its conditions.
---------------------------
OK   
---------------------------

**Comment by stevenndungu** [comment]
Thank, looking at it.

**Comment by stevenndungu** [comment]
@dannyparsons  this should  be closed, fixed it some time back but forgot to reference it.
