### ISSUE TITLE
Numeric up-down controls

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2810]
**On key press the focus is lost.  So only 1 digit can be typed.**  Last observed on Climatic > Prepare > Specific Events > Start of Rains rainfall amounts.

**Comment by lilyclements** [comment]
I see. So this is occurring on the nuds: "Percentile" and "Amount", I also managed to make it crash. I've fixed the crashing problem and waiting to hear if it's too late to go in for this version. I'll work on the problem you outlined as well and hopefully can solve that before the new version!

**Comment by rdstern** [comment]
Thanks.  We are finding enough issues that this isn't quite ready yet for CIMH next week.  That may not stop a version being prepared today to make the testing process easier.  That's still for discussion, presumably when Danny and David can skype.  We are just continuing testing!

**Comment by lilyclements** [comment]
Okay I see - I've fixed the bugs found in here but unsure if it'll be merged in time. With Water Balance, Dry Spells and Start of Rains you have to make sure if you change the day values then you change the other nud values after to avoid a bug (with SoR this just applies to Dry Spells and Dry Period checkboxes I believe)

**Comment by lilyclements** [comment]
The crashing problem has been merged. I'm not sure if the nud fix will get in or not, sorry

**Comment by lilyclements** [comment]
Both crashing and nud problems have been merged. Not sure if it's too late for the new version, however.

**Comment by lilyclements** [comment]
When we make the new version today, this will be fixed in it. This issue can be closed now.
