### ISSUE TITLE
Prepare > Links and Keys dialogues not working

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2815]
They display variables, not links or keys.  Were they checked?  We can't see how to use them.

For Danny to consider.  I wonder who worked on these dialogues.  It isn't needed for this version directly, but it is needed for one of the papers!

**Comment by rdstern** [comment]
Please could work resume on the keys and links dialogues?
I am suggesting John and Steven, because I assume they will become world authorities on the Prepare menu!  That's your paper after all.
The recent SPSS datasets I have attached could be used as a realistic check on the system, see #2757 .
The first 2 columns in the main file can make a key.  This dialogue seems to be working.
But the View key dialogue isn't working yet and neither are the links dialogues.  For example, it should be showing the existing keys, and not variables.  And if there is only one key for a given data frame, then I assume it should automatically be put into the receiver.

If you need help, then Danny is ready.
If this is all too easy, please continue to the comments dialogue!

**Comment by stevenndungu** [comment]
@dannyparsons   this could be closed, already worked on

**Comment by dannyparsons** [comment]
Thanks, I think I'd like @rdstern to test these and confirm it

**Comment by volloholic** [comment]
@rdstern Can you check so we can close

**Comment by dannyparsons** [comment]
View/Delete keys now working
Add Link dialog working

Still to do, I suggest for 0.9:
> if there is only one key for a given data frame, then I assume it should automatically be put into the receiver.
Also check all the dialogs in this sub menu.

**Comment by volloholic** [comment]
@Lunalo Can you check this is all done so I can close.

**Comment by stevenndungu** [comment]
This can be closed now.Checked the sub-menu as well.
Note: dlgAddComments is disabled for now since it is not fully implemented

**Comment by dannyparsons** [comment]
Individual issues can be opened for remaining issues related to this.
