### ISSUE TITLE
Column summaries no longer working correctly

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2834]
Simple use of this dialogue seems not to work any more.  Climatic daily data input (using the file attached) and yearly totals specified.  The resulting file did not contain the factor as the column.  
Then, when the statistics were changed in the dialogue, (to ask for maximums) the statistics calculated remained the same as in the command as executed before.
[R04_TIMEHRI_PICSA.txt](https://github.com/africanmathsinitiative/Instat/files/863634/R04_TIMEHRI_PICSA.txt)
.

**Comment by dannyparsons** [comment]
@stevekogo Is on this now. It needs to be fixed for today's version.
