### ISSUE TITLE
Climatic Events not saving correctly

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2835]
The climatic commands specify a fixed name (and possibly a long one) for the resulting column, (start of the rains, dry spells at least.

The name should be dictated by the user, with a default suggested.  It should also become different each time the command is used.  Now multiple uses overwrite, because they are giving the same name.

I assume there is a custom control for this?  The feature is in many dialogues.

**Comment by lilyclements** [comment]
I am sorting this out now, have done for Water Balance and will get to Start of Rains and Spells now

**Comment by lilyclements** [comment]
I have sorted this now. There is a small issue with prefixes I need to fix but the column names have been successfully added for the time being.
