### ISSUE TITLE
Climatic events - water balance

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2837]
I had thought this was ready?  It seems not yet.  It doesn't recognise the climatic columns yet, so I can't get started.

**Comment by rdstern** [comment]
I add the request from CIMH which will be a great addition, and show our "system" well, once it is working.

They don't want a fixed number for the evapotranspiration.  They currently calculate the Evapotranspiration on a daily basis.  Eventually they would really like to be able to do this within R-Instat.  That should be easy for us to add (for them) because they do it in the "proper" way, i.e. assuming all the variables have been measured that are needed.  There is an R package for this.  (The problem is on what to do when some elements are not available - which is the situation in some countries.  Great that we can start where that is not an issue.)

For now they are happy to input the results with the file already containing the evapotranspirations.

Then they get the mean value each day of the year.  (We can already do this with our summary commands I think).

Then, in the water balance, they use that column to give the evapotranspiration each day.  So we use that column, from that data frame, rather than a constant.

**Comment by lilyclements** [comment]
It doesn't recognise the climatic columns? That's very odd. I just updated my branch to check and it is for me?

![image](https://cloud.githubusercontent.com/assets/21180424/24235045/46501c12-0f93-11e7-8f88-71190b45aeed.png)

Should I change the Evaporation label to Evapotransition out of interest? Giving the option as a column not fixed value is working in R already so the R-code is set at least
