### ISSUE TITLE
Naming corruption dialogs

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#2841]
I have been going through some corruption dialogs this morning and we have not had a standard way of naming them. 
Some are named with this format- dlgCorruptionDescribe, while others have just the standard way of naming dialogs. 
My suggestion is, we use the first format as it is easier to distinguish the corruption dialogs easily unlike when they mix up with all other dialogs. 
We do not do this for all other menus, I wonder if this would be an appropriate approach.

**Comment by dannyparsons** [comment]
This is still useful to consider.
