### ISSUE TITLE
dlgImportDataset bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2846]
There are two bugs in this part:
* If I have a dataset called A and then import another dataset where in "New dataframe name:" it has the same name as a previous dataset (e.g. A) then it overwrites the previous dataset. We need a prefix of some sort to have A1 as the second dataset and/or a warning if you overwrite a file
* Sometimes when importing from xlsx, it only imports the first nine lines. This is because it is importing the "Preview" and not the dataset itself. We shouldn't have the code in the preview frame being used when you press OK.

To layout:
* Colons required after all labels on this dialog
* "New Dataframe Name" should read "New Data Frame Name:" as we have been using data frame as two separate words throughout R-Instat

**Comment by dannyparsons** [comment]
Can you specify conditions for the 9 lines bug? That should be fixed urgently.

**Comment by lilyclements** [comment]
So, it seems to be with xlsx files,

**Comment by lilyclements** [comment]
So, it seems to be with xlsx files (potentially any excel file?). For example, any of the Climatic_guide_datasets:

```
Runoff <- rio::import(file="C:/Users/Admin/Source/Repos/Instat/instat/bin/Debug/static/Library/Climatic/Climatic_guide_datasets.xlsx", which=21, readxl=FALSE, **rows=1:10**)
InstatDataObject$import_data(data_tables=list(Runoff=Runoff))

```

If I close and reopen then press OK, it runs it fine

**Comment by rdstern** [comment]
On names I am happy with the actions in other software, where it warns you and allows you to overwrtie if you wish.  I sometimes do wish.  Ideally it would also have the option to add a prefix.  I don't particularly need the option to make a new name myself.  But I don't mind if it gives me the old name and then asks, or if it gives me its proposed new name.
