### ISSUE TITLE
Metadata bug with Climatic_Type and Class alterations

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2848]
There is a bug with the metadata. I can set my variables as a climatic_type, and then if I alter the class of one of these variables, that variable has a climatic_type as NA now as opposed to what I set it as before.

![image](https://cloud.githubusercontent.com/assets/21180424/24250911/58eb3a0e-0fd0-11e7-8419-a93a935bef5e.png)

**Comment by dannyparsons** [comment]
Metadata is now retained when converting columns.
