### ISSUE TITLE
Receiver label-names consistency - enhancement

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2862]
@africanmathsinitiative/developers There is very little consistency between the label names for the receivers. I just opened five random dialogs and got:
Selected Variable(s):
Columns to Transform:
Factor Selected:
No name at all - _(Steve is working on that dialog so I mentioned that on the pull request as that needs to be fixed!)_
Variable:

I mentioned this to Danny and he made the point that we probably want to use something like we have been in "Columns to Transform:" as that's more informative than "Selected Column:" etc.

What do others think?

Just something worth doing while we're changing dialogs and what not.

**Comment by dannyparsons** [comment]
Having this consistency as much as possible very soon is important. If possible we should have an informative label other than "Selected Column:".
We don't have time to have long discussions about this so I'm happy for people to make sensible decisions about the labels on dialogs they work on. If you can't think of something short and sensible then ask for someone else's opinion.

**Comment by lilyclements** [comment]
In general, this has been good. There has been improvement among the software of the receiver labels in the past month or so which is great. I'm sure there's still dialogs which need this edit but it's not as common :)

**Comment by dannyparsons** [comment]
Great. @africanmathsinitiative/developers please have a quick check through the menus for this.

**Comment by lilyclements** [comment]
Polynomial and Permute have something like "Selected Variable:" on their label receiver still.

1. Should the label on dlgPermute be changed to "Columns to Permute:"?

2. I'm not sure of a suitable alternative for Polynomial. I can't see how to get Polynomials to work because "Polynomial" isn't a verb.

**Comment by dannyparsons** [comment]
1. Yes.
2. Can stay as selected variables if there's nothing else sensible.

**Comment by AlexSananka** [comment]
@lilyclements did you make this edits on permute columns or should I go on and make them?

**Comment by lilyclements** [comment]
@AlexSananka sorry just saw this. I haven't made the changes but will now!

**Comment by AlexSananka** [comment]
I have already made this changes on the pull request you just reviewed.

**Comment by dannyparsons** [comment]
I think we've good on this now?
