### ISSUE TITLE
Passing NULL value in the receiver  for columsns to Carry in dlgStack

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#2873]
Hi Team,

I learnt from  @stevekogo  review that if the ucrChkColumnsToCarry is unchecked then we should pass a NULL value to id.vars.

id.vars parameter is set for the ucrColumnsToCarry which is linked to the above named checkbox.

The checkbox need to be unchecked on default which means the receiver should be invisible. If the checkbox is unchecked then the focus should be on this receiver.

We can not pass NULL value in the SetDefault since this will appear in the Receiver when the dialog is loaded making checkbox to be checked on default.

I would like to pass NULL value to this parameter without populating it in the reciever since this affects the liked controls.

One easier way of solving this is write instat Object method while setting id.var=NULL by default.

I am not sure if a method exist for solving this issue?

**Comment by dannyparsons** [comment]
Thanks for specifying this issue. This is something we need to incorporate into the new system. I will investigate.

Your suggestion of setting the parameter default to NULL won't work for Stack because it use's the `melt` function not an instat object method.

**Comment by Lunalo** [comment]
Thanks @dannyparsons 

This will be very helpful

**Comment by Lunalo** [comment]
If actually we want to pass NULL value by default then why should we have the checkbox to control the passing of id.vars.

I would suggest we remove the checkbox since a value of parameter is being passed whether it is checked or unchecked ? @dannyparsons  @rdstern  @stevekogo

**Comment by dannyparsons** [comment]
The checkbox is because id columns are optional. If it is checked then it should pass the column names - not NULL.

**Comment by dannyparsons** [comment]
This is now working correctly.
