### ISSUE TITLE
Include package names in functions?

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2875]
In R you can include the name of the package with the function name. For example: 

`rio::export(data, "mydata.csv")` 

is equivalent to:

`export(data, "mydata.csv")`

This can be useful if you have multiple packages using the same function name. In our setup we make sure to load the packages in the correct order so this is not needed.

However, we may still want to include these: 

1. As good practice - if someone uses R-Instat code without doing our setup there will be no confused about duplicate functions in different packages. 

2. It promotes the packages that we do use in R-Instat by making them visible in the commands. Probably will please package creators.

The only downsides I can think of are that it makes the R code slightly longer (depending on how long the package name is) and it's a less common way to write R code (although we might argue this is a better way to write R code).

Any thoughts?

**Comment by Lunalo** [comment]
@dannyparsons  this is very interesting . I partly like the idea of calling the functions with their packages  because:-
1) Because of some of the reasons you gave
2) It will encourage learning .

But i tend to believe this might only work well for the functions we are calling directly from r.
We should also understand that this is not the only way of importing/ loading  R packages because we still have require() and library() which might lead to another topic.

So, what is the best way? waiting for software to load the packages or waiting for packages to be loaded when we click ok on a dialog?

One question for you; Why is it that when you add a package it creates many additions ?

**Comment by dannyparsons** [comment]
For instat methods they don't have a package so this doesn't apply (but eventually they will be in an R package as well) so eventually we will be able to do this consistently.

The separate point on loading packages I think we discussed that this should be done by each dialog as there are too many packages and it's too slow to load all at the beginning - also inefficient as a user may only use a small number of the packages each time.
And actually if we do change to this method we no longer control the order packages are loaded so we would have to implement my initial suggestion to ensure the correct functions are being run.

> Why is it that when you add a package it creates many additions ?

Can you explain what you mean by additions?

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers
This is now being implemented well. We need to make the switch over very soon so that in v0.3.0 on 9 June we no longer load all packages in setup. I suggest that on Saturday 3 June after the next release I make this change. We then have a week to update remaining dialogs. Make sure any dialogs you work on have the package name set if needed otherwise they will no longer work after 3 June.

**Comment by dannyparsons** [comment]
A few core packages will still be loaded, like `dplyr`, and a few others which prevent small bugs like `svglite` can be loaded too. Although the package should really handle this itself, can you get the message for this so we can see if it's a known issue?

**Comment by dannyparsons** [comment]
A few core packages will still be loaded, like `dplyr`, and a few others which prevent small bugs like `svglite` can be loaded too. Although the package should really handle this itself, can you get the message for this so we can see if it's a known issue?

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers 
This is now implemented #3184. The only packages loaded now are: `plyr`, `dplyr`, `ggplot2` and `svglite`  because we need features in these not available without loading them. If there are other packages that need loading, let me know.

There will now be bugs in dialogs where the package name hasn't been set for functions. 

Every dialog needs to be checked before the next release. 

Then it's an easy fix, but please check first if there is an open pull request on the dialog before adding the package name. If so, discuss with the owner of the pull request. This is also a good reason to get all pull requests merged before the next release.

**Comment by lilyclements** [comment]
On the excel documents there's a column named "LILY". These have a "yes" next to any dialogs I have edited to sort layouts, add package names and such.
Therefore the dialogs with a "yes" in this column all any dialogs already have the package name so there is no need to check these dialogs.

Note: don't add a "yes" in these columns, however, if you add their package name. I'm making more changes to these dialogs than package name and don't want to miss any.

**Comment by lilyclements** [comment]
Also note that base and stats packages are automatically implemented.
