### ISSUE TITLE
dlgDescribeOneVariable - Summaries bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2878]
There is a problem with the sub dialog (sdgSummaries) for dlgDescribeOneVariable. An error occurs if I have a factor and a variate in my receiver, and under custom summaries, only apply summaries suitable for a variate. (i.e., do not apply the checkboxes in the "Common" groupbox)
Since the factor is only running NA's in this instance as it does not have any suitable summary statistics from what has been selected, the following error occurs.

_Error in match.fun(y[[1]]) : 
  c("'(if (length(d.call) < 2L) newX[, 1] else array(newX[, 1L], d.call, ' is not a function, character or symbol", "'    dn.call))[[1]]' is not a function, character or symbol")

The error occurred in attempting to run the following R command(s):

InstatDataObject$summary(data_name="Blocking", columns_to_summarise=c("Block","Yield","x3","Trt"), return_output=TRUE, summaries=c("summary_median", "summary_sum"))_

I've looked into the other dialogs using this subdialog and it is not a problem there since they are not interested in summaries per individual variables.

**Comment by stevekogo** [comment]
This is an interesting bug. Let me dig into the summaries method and try to fix it.

**Comment by dannyparsons** [comment]
I'm pretty such this is still an error and needs to be addressed soon.
