### ISSUE TITLE
Data Options error

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#2898]
@africanmathsinitiative/developers .I was testing dialogues and found that when you choose data options and move to to the data frame selector it allows you to choose "no_filter" .once to select "no_filter" and want to return back to the main dialogue  by pressing the return button **severally** it breaks.  you can check at this screenshot for the error.

![image](https://cloud.githubusercontent.com/assets/26301973/24744515/fbaefd76-1aba-11e7-97aa-4f621a7c3525.png)

**Comment by dannyparsons** [comment]
Thanks for finding this. @lilyclements is this related to the bugs you were working to fix on the filter dialog?

**Comment by lilyclements** [comment]
I don't believe this is related.
@shadrackkibet Which dialog were you using to get to this sub dialog? I can't seem to replicate this error. However, I am able to select "Return" several times if I click really fast which does not seem right at all!

**Comment by shadrackkibet** [comment]
@lilyclements . The issue was with most of the dialogues that i tested for example The two way frequency.when you click return on the subdialog once it works well. my question is; can there be a problem when the subdialog allows you to select "no_filter"???. @africanmathsinitiative/developers

**Comment by dannyparsons** [comment]
"no_filter" is an acceptable option since it removes all filters. However, it shouldn't crash. Maybe you could demonstrate to Lily?

**Comment by lilyclements** [comment]
@shadrackkibet let's have a skype over the issue because I can't seem to replicate this crash

**Comment by shadrackkibet** [comment]
@dannyparsons .Thanks for explaining the point of choosing a "no_filter". @lilyclements  i have checked this with @AlexSananka  and the reason why i was getting this error was because i  was pressing the return button for long time and thus the dialogue crashes.This seems not be a big deal.

**Comment by lilyclements** [comment]
If it crashes then I feel it is a big deal which we need to fix! It's a good bug to find, however, I do not know how to fix it but would be interested if someone else knows for them to explain it through to me?

**Comment by dannyparsons** [comment]
@shadrackkibet Yes it good to try all sorts of strange things with the software. Of course, it's not sensible to press buttons in strange ways but users might do it, especially our target audience who may be inexperienced computer users. It wouldn't be good if the software crashed when they did something that we allowed in the software.

My guess is that we need to do something like what we do for dialogs where they are disabled when you click return until it closes so that you can't click multiple times. Does that sound like something that would resolve this issue?

Please keep trying unusual things with the software, this is how we will find more bugs.

**Comment by shadrackkibet** [comment]
@dannyparsons . i will get in touch with @lilyclements  to explain how i got this error , so that possibly she can figure it out. otherwise @africanmathsinitiative/developers can also suggest a solution to this because it seems crazy.

**Comment by shadrackkibet** [comment]
@lilyclements .I hope you can now replicate the same error in your machine.

**Comment by lilyclements** [comment]
I'm trying to but I can't get more than eight clicks in before it actually returns!

**Comment by dannyparsons** [comment]
We should do something on data options soon so that it's stable in 0.4

**Comment by dannyparsons** [comment]
This is now stable and creating and applying a filter works correctly - the data frame is now fixed so it must match dialog data frame. Modified sub dialog buttons so they are disabled when you click Return like on main dialog base buttons. This prevents repeated pressing.

There's lots more to do data options but I think immediate bugs have been resolved, please check and report any further issues.
