### ISSUE TITLE
Auto scrolling in main windows

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2900]
When we add something to the Output, Log or Script window, it should automatically scroll to the bottom of the box so you can see the new text/images. We had this with the old output window but not since we implemented the html version. I hope this is straightforward to do.

**Comment by dannyparsons** [comment]
@maxwellfundi I think this is done? Is it done on log and script windows as well?

**Comment by maxwellfundi** [comment]
This is done on output window. Will get it done for other windows too
