### ISSUE TITLE
Adding Remove button on the Data Selector 

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#2901]
I was using our software and in the process of adding variables to the receivers I added one variable by mistake.

So, I got into the receiver to get that variable back to the selector. I realized we only have two  command buttons on selector (Add and options) and the only option I was left with was to double click on that variable in the receiver in order to remove it.

Can we have an additional command button (Remove) for removing variables from the Receiver?

@africanmathsinitiative/developers

**Comment by dannyparsons** [comment]
I think the original reason for not having the remove button was to avoid having too many buttons on a dialog. Removing can be done by double clicking, backspace or delete keys, or for a single receiver just replacing it with another variable. The add button was seen as more important than the remove button.

However, if users are going to find this confusing then it's something we can consider adding. This might be something that is best to get feedback from users on before making a change.

**Comment by dannyparsons** [comment]
This is something we can get feedback on once we get more users and review if needed.
