### ISSUE TITLE
dlg Summary Tables not working.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#2903]
@africanmathsinitiative/developers .I was testing summary tables dialogue and found that it is not working as expected. Test ok and click reset not working. Can someone check this ?

![image](https://cloud.githubusercontent.com/assets/26301973/24789042/9da6332e-1b79-11e7-81b9-85cd77352341.png)

**Comment by dannyparsons** [comment]
I believe this dialog is not complete. But then OK should not be enabled. Can you fix the dialog so that OK is disabled for now?

**Comment by shadrackkibet** [comment]
@dannyparsons. yes I can do that.
