### ISSUE TITLE
R instat window restore button.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#2908]
@africanmathsinitiative/developers .I was using our software and comparing with other statistical softwares i.e R and SPSS and i found something crazy. when you click on the "restore" button up there you find that our software minimizes too much such that the user cannot navigate on R Instat anymore.According to me i find this not really good as this might inconvenience  the user "probably". check this comparison on my screen.

![image](https://cloud.githubusercontent.com/assets/26301973/24801900/9e3308be-1bae-11e7-9377-73377ccb4066.png)

**Comment by dannyparsons** [comment]
Yes it is a bit small when you click restore. I think this might be something to do with the original size of frmMain which is set in its Properties. You could see if changing that has an effect, although I guess it is also screen size dependant. If it's not quick to change then I suggest we don't worry about it as I don't think Restore is commonly used.

**Comment by dannyparsons** [comment]
@shadrackkibet Does this change if you change the size of the frmMain? If not let's come back to this later.

**Comment by shadrackkibet** [comment]
@dannyparsons This can now be closed.
