### ISSUE TITLE
dlgScatterplot.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#2910]
@africanmathsinitiative/developers .I was testing dialogues and found that on the Scatter plot dialogue the multiple receiver is hidden such that the user might not easily see it.Is there a way that we can make the multiple receiver easy to trace?. Maybe when the user selects more than one variables the multiple receiver pops or maybe have a multiple receiver separately.

**Comment by maxwellfundi** [comment]
The graphics dialogs have a special control, where you have to select if you want a multiple or single receiver.

**Comment by mmumbo** [comment]
Hi Max,

I agree with you, its a bit confusing for the first time user. Could we
have something like a drop-down arrow where one can select whether single
or multiple variables instead of double clicking?

Thanks,
Mike.

**Comment by dannyparsons** [comment]
Currently the button at the top allows you to switch between single or multiple variable with one click. I agree it's that obviously, would be very happy if someone came up with something that they felt was easier to use.

**Comment by dannyparsons** [comment]
Although you should remember that the most common use of the dialog will be the single variable case, so we don't mind if a bit of understanding is needed to use the multiple case (e.g. a video!)
