### ISSUE TITLE
Radio Buttons as Buttons

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2913]
@africanmathsinitiative/developers I think it is good for people to say their thoughts on the radio buttons and buttons situation. Such as colour, size, location, thickness, etc, etc. Anything!

Currently it looks like this:

![image](https://cloud.githubusercontent.com/assets/21180424/24860089/dc62d518-1dea-11e7-8847-e9092f1d1d53.png)

To do this, select your radio button on the designer and change the following in Properties:

* Under **Appearance**, change **Appearance** to **Button**
* Under **Layout** change **Autosize** to **False**. This means that the size of the button can be changed
* Change the **Size** to **100, 28**
* The **layout** of the first button should be at a height of **10**. The other location should be such that the buttons are all central (e.g. if you have two buttons, then the split between the two buttons should be at the centre)
* Under **Appearance**, change **Flat Style** to **Flat**
* Under **Appearance**, change **TextAlign** to **Mid Centre**
* Click the little "+" by **Flat Appearance**

![image](https://cloud.githubusercontent.com/assets/21180424/24860248/9ee6155a-1deb-11e7-8379-97b6a51e002c.png)

* Then change the **Border Colour** to **Active Caption** under the **System** tab
* Change the **Border Size** to **2**. I'm not sure if I'm keen on this thickness. however, it means that the two buttons can be touching in the centre which I do like.
* Change the **Checked Back Colour** to **Active Caption** under the **System** tab

I don't mind this appearance but I think it could look better, however, I can't work out how! I would like to hear peoples opinions on the location, size, colour, etc, preferably as soon as possible before these are implemented in many dialogs to avoid having to change them all!

**Comment by dannyparsons** [comment]
I think this looks pretty good already. I agree it could be improved maybe but not sure it's a priority now. Could possibly try something like a darker blue and then white text when the button is selected? I like when the colours are inverse for the selected button.

**Comment by lilyclements** [comment]
I agree, however, I couldn't find a way to make the text colour changed for when it's checked

**Comment by maxwellfundi** [comment]
Thanks @lilyclements for this and taking me through it too.

**Comment by dannyparsons** [comment]
@maxwellfundi  I'm going to close this but this would be really good for developer documentation. Could you copy Lily's comment including the images and put it in your developer documentation?
