### ISSUE TITLE
String handling

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2914]
We want R-Instat to become very good at handling string columns.  This has started and here is a suggestion for a dialogue that could be Prepare > Column: Text > Find/Replace.

Danny may have further suggestions.  This is not for the forthcoming release on Thursday, but the task in the comment below this suggestion IS to be done this week if possible.

So for the forthcoming dialogue:
1. We'll start simply, but you can leave some space for a keyboard later.
2. At the top there is our new replacement for the radio buttons with 5 options, namely 
a) Count, 
b) Detect, 
c) Extract, 
d) Locate, 
e) Replace

3. They each produce a new column in the same data frame.  The commands are all from the stringr package.
4.  There is the usual selector.  At this stage **do not restrict** it to text columns.  It will be interesting to see what it can do with date columns, factors and even numeric columns.
5. There is a single receiver with the label "Column".
6. There is a second field which you can type into.  It has the label "Pattern".
7. If **Replace** is selected then a third field is visible with the Label "Replace by".
7. Towards the bottom there is the usual field with label "Save result to:".  It has the default name depending on the function used, e.g. Count1,

**Comment by rdstern** [comment]
OK, now what you should do this week if possible is to notice that all we want in this dialogue can already be done with our calculator.  So please try that and comment on improvements you would like.  Us the examples in the stringr package as follows:

1. Use **File > New** to make a new worksheet with one column of length 4.
2. Enter the data into this column of the example used for these commands in the **stringr** package, i.e. apple, banana,... I found this data entry a bit inconvenient.  Is it OK for you, or can you suggest what's wrong?
3. Use **Column > Calculate > Calculations**.  Then try at least the first example (i.e. "a" is the "pattern", for each of the 5 commands.  What do you find anything that needs improving on the calculator?  Please discuss with John.

**Comment by shadrackkibet** [comment]
I can work on this dialogue for a start with the help of @Lunalo and @dannyparsons.

**Comment by Lunalo** [comment]
This is great.

That is what I was thinking  @shadrackkibet  You can get the latest version and start with creating empty dialog before you can continue. 

@rdstern  I think there is no problem with passing numeric to these string functions .

It will work appropriately but am not sure if we can have alternative cases for numerics instead

**Comment by dannyparsons** [comment]
This sounds good. There's some details I think should be discussed - like the menu item name and which functions should be in this dialog - but generally it would be good to start working on.

**Comment by rdstern** [comment]
There is also a very similar dialogue - at least initially - which has already a space in the menu.  This is the  **Prepare > Column: Text > Distance** dialogue.  It is a pretty powerful feature which uses the R **stringdist** package.

As with the dialogue above:

1. There is the usual selector. At this stage do not restrict it to text columns. It will be interesting to see what it can do with date columns, factors and even numeric columns.

2. There is a single receiver with the label "Column".

3. There is a second field which you can type into. It has the label "Pattern".

4. Towards the bottom there is the usual field with label "Save result to:". It has the default name Dist1.

5. Above that is a button with the label "Method".

This calls essentially the command stringdist(Column,Pattern)

You could (initially) stop there, but doing the sub-dialogue should also be easy. 

The main thing this will do is to allow the method to be changed.  This could be a list of radio buttons I suppose.  It could be a combo box, but better if they are all visible.  A few do have extra arguments, to be checked out, but that could come later.

A second aspect could be to make the checks case insensitive.  One of the examples shows how to do this.  This would be a checkbox, either on the main dialogue or on the sub-dialogue.

**Comment by shadrackkibet** [comment]
@rdstern  i completed working on the string handling dialogue we are waiting for someone to test it before it is merged.  I will start working on this other dialogue from tomorrow.

**Comment by rdstern** [comment]
Now the "sting-in the tail".  This demonstrates the power of R.

In the command for the Extract command consider the example given by stringr to illustrate the extract command.  Look at the string called **phone**:

strings <- c(" 219 733 8965", "329-293-8753 ", "banana", "595 794 7569",
"387 287 6718", "apple", "233.398.9187 ", "482 952 3315",
"239 923 8115 and 842 566 4692", "Work: 579-499-7527", "$1000",
"Home: 543.355.3679")

**phone <- "([2-9][0-9]{2})[- .]([0-9]{3})[- .]([0-9]{4})"**
str_extract(strings, phone)
I'll explain the first bit, i.e. [2-9][0-9]{2})[- .]
a) Phone numbers start with a number between 2 and 9
b) The next 2 numbers (note the {2}) can be anything between 1 and 9
c) Then [- .] there is either "-" or space, i.e. " " or "."
d) And so on.
How do we make this easy?  
**Answer:**  We start with a relevant keyboard.  Perhaps without numbers or letters, but with all the special keys and groups of letters/numbers.
This is the clearest explanation I have found to help
[Regular Expression in R.docx](https://github.com/africanmathsinitiative/Instat/files/931208/Regular.Expression.in.R.docx)

**Comment by rdstern** [comment]
Shadrack it is great that you have these 2 dialogues working.  

There is a small enhancement to the Find/Replace that would be useful and then quite a big extension that I discuss in the next comment.
The small change is on the Replace option.  Under the Replace by field could there either be a checkbox, or 2 radio buttons.  If a checkbox then the label could be "Replace All".  Default is checked.  If radio buttons then one would say All and the other would say First.  (If there is the checkbox, then a tool-tip could say "If unchecked, only the first match is replaced."
If checked, then the command becomes str_replace_all.  If unchecked, then the command is as you have it now.

**Comment by dannyparsons** [comment]
I think two radio buttons would be clearer. Alternatively an additional radio button at the top for "Replace First"/"Replace All".

**Comment by rdstern** [comment]
Happy with either.  Perhaps at the top is even clearer.

**Comment by dannyparsons** [comment]
It would certainly be much easier from the code perspective so if you don't have strong opposition I think another option at the top would be good.

**Comment by rdstern** [comment]
Very happy with that.  It is then a simpler dialogue and so clearer for the user.

**Comment by shadrackkibet** [comment]
I think it will be good to add another radio button at the top for 'Replace all'  so that we now have six radio buttons.

**Comment by rdstern** [comment]
The stringdist is less important as a dialogue than the Find/Replace.  If you have spare time, then there are various enhancements - but they probably need more discussion.  I list them while they are fresh in my mind.  In the end I would like this to parallel the Find/Replace, where there are different options for approximate string matching, e.g. locate, distance, etc.
Currently:
a) At the top there could be two buttons, one with Column and the Second is String.  You have done the String one.  If Column is selected, then the second field becomes a second column instead.  I think the command will work as before.
b) There could be an **Ignore Case** checkbox.  This would add tolower() to both columns, or to the column and the string.
c) We need to be able to do something about the input of the strings.  This is a general issue where we can type into a field.  For example you put quotes round the string.  If I do that also in the string, then it generates an error.
d) I think the different measures will (later?) have to go onto a sub-dialogue.  This is because some have options that have to be set, which others don't.

**Comment by rdstern** [comment]
There are also still some enhancements that can be made to the Find/Replace dialogue.  

1. If you start with the Replace and then move to (say) Count, the replacement string is still visible.
2. There are some excellent examples to test out this dialogue.  Go to Open from Library and then stringr.  Then there is a file called words, with 980 words.  The one called fruit has 80 fruits, and the best for us is one called sentences which has 720 sentences.  (This is particularly interesting, because we could often have this sort of data in surveys.
3. Now the big feature I had missed in the stringr guide.  I had wondered why you couldn't search for patterns in a **case-insensitive** way.  Of course you can, but this changes the command that you give, and also shows some interesting new features.  In the **stringr guide** look at **modifiers**.  
4. So we can have a checkbox for **Ignore Case**.  
5. At the same time we have a checkbox for "Include regular expressions.  Default (unlike stringr) is unchecked. 
6. When unchecked, instead of **pattern = ...** in the R command we have **fixed(pattern= , ignore_case=TRUE or FALSE)**.  That is if we don't want to allow regular expressions.
7.. If we do want to allow regular expressions, then we replace the pattern argument by regex(pattern,ignore_case=...).  
8. The **stringr** defaults are **regex** and **ignore_case=TRUE**, which would permit the simpler command you have now.
9. In the dialogue, when regex is checked, we open a panel (as in the calculator) with a keyboard.  I have been struggling with the layout and will discuss with David tomorrow.
10. There are other options with regex, but I am not sure how useful they will be.  You may want to discuss them with Danny.  I suspect they may be more interesting in later versions of R-Instat (e.g. in multiple languages).  If so, then we might ignore them for this forthcoming release.
11. One more feature I did like is **"boundary"**.  I assume this is an alternative to regex and fixed, and you would not have a pattern.  The examples in stringr are for count and allow a count of characters, or words or sentences - which seems a nice feature.  I wonder if this means that Count would have another button at the top.  Perhaps one is a simple **Count** and the other is **Count Pattern**.

**Comment by rdstern** [comment]
This comment is on the regex keyboard.  I assume Shadrack will attempt this, with support from John, who was responsible for the keyboards in our **Prepare > Column: Calculate > Calculations**.  I wonder if that dialogue has been updated yet.  If not maybe now is the time, while Danny is around to support.  Also, for Shadrack this should be one of the tasks he takes on, not the only one.  It could easily eat up a lot of time and this is time we need to share with multiple tasks.

The regex sequences can already be typed into the pattern string.  So testing the dialogue and improving the keyboard can be done at the same time.

This is an ideal one also for tool-tips, so I'll give them.  I suggest a keyboard with 6 columns and 4 rows, or perhaps v.v.
Top row could be:
" ",' ', [ ], [^ ], { }, ( ).
Then perhaps:
*, +, ?, ., ^, $ 
Then |, \,  \b, \B, \w, \W
Then:
\s, \S, \d, \D, \\
In the tooltips \d "Numbers, [0-9]", \D "Not numbers, [^0-9]"
and so on

**Comment by shadrackkibet** [comment]
I am now working on string distance enhancement.

**Comment by volloholic** [comment]
@shadrackkibet is this now done? Can this be closed?

**Comment by shadrackkibet** [comment]
This is not yet done , i am sorting out @lilyclements  reviews now.

**Comment by dannyparsons** [comment]
Status of this?

**Comment by shadrackkibet** [comment]
I have three issues on this now at #3213  which i have tried to solve but i haven't managed.
1. The radio buttons and a checkbox for include regular expressions are reseting on reopen.(which i have fixed temporarily)
2.I have disabled some buttons on the regexkeyboard which are causing a crash when the user does something senseless- perhaps this needs further improvement of the regex keyboard to avoid such characters.
3.On  the Inputtextbox for the pattern there is  text(instat.RFunction)  that pops up when i run the dialog once i reopen it.-someone to help me fix this.

@africanmathsinitiative/developers  i feel that with disabling of some characters on the keyboard the user can use the characters which are there.Can someone test  #3213  this now and assess whether this is can be in good state for the user.
I am happy to get suggestions on how i can fix this issues.

**Comment by dannyparsons** [comment]
Disabled regex options for now as not yet stable. To be completed by 0.9.
