### ISSUE TITLE
dlgDuplicateColumns - bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2921]
There's two issues on this dialog.

The "New Column Name" cannot be a ucrSave since it contains a parameter ("new_col"). This means that it is a ucrInput which means that the receiver does not clear upon pressing reset. I know this is an issue with other ucrInputs so I suppose it can be fixed when those are fixed.

If I duplicate a column, give it a new name, and press OK, and then duplicate another column and give it the same name, the second column does not come in.
We plan to implement for the ucrSave to warn you if you rename a column something already in the dataset as it will overwrite it. However,
a) This is not using a ucrSave so we will have to implement that separately (which is fine)
b) Even if we get the warning, we wouldn't overwrite the first column with that name. We would just not get the new column altogether.

**Comment by dannyparsons** [comment]
The first thing is a bug with ucrInput but you shouldn't need to reset it because it should read its value from the function anyway right?

For the second I think we can have special checks here because we don't want to allow users to rename a column as an existing column. Overwriting a column is fine but this seems different because we need to have unique column names. So I don't mind if we do something just for this dialog.

**Comment by lilyclements** [comment]
The first point makes sense. It's an issue in general with inputs that they are not resetting properly. How can that be fixed?

Okay, as for the second point I'll make OK disabled if the new column name is the same as something already in the data frame
Should I put in a pop-up box too explaining why OK is disabled?

**Comment by dannyparsons** [comment]
We just need to add a line in the reset method which clears the text. However, still not sure this should be needed as it should clear automatically when reading from the function if it's parameter is not there.

Possibly this check should be in the R method and not the dialog.

**Comment by volloholic** [comment]
@lilyclements status of this?

**Comment by lilyclements** [comment]
We need to still implement in the ucrSave to warn you when overwriting. This extends to further than overwriting columns.
Something which is really important and probably to discuss after 0.3.0 for next Friday's release?

**Comment by dannyparsons** [comment]
Sounds good.
