### ISSUE TITLE
Case Study from Ghana

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2941]
[PICSA tools.zip](https://github.com/africanmathsinitiative/Instat/files/943732/PICSA.tools.zip)

[Copy of FarmerQuestC_Ghana.xlsx](https://github.com/africanmathsinitiative/Instat/files/943773/Copy.of.FarmerQuestC_Ghana.xlsx)

The first file contains the data from an evaluation of PICSA in Northern Ghana.  This includes an SPSS file with over 900 columns, and 416 rows, that (now) imports easily into R-Instat.  The labels also give many of the questions in the questionnaire.

This is interesting for testing R-Instat, particularly the tabulation and graphics.  A paper is almost complete to be submitted, and I will add that when I have it, to show the sort of analyses that were done in Excel and SPSS.  

The analysis includes a "Likert" summary, that we call rating scales here.

The data come from an ODK survey and we could also try importing the data directly from the ODK site.  Graham Clarkson writes "The ODK data s is still on our PICSA ona.io account and I can download the data from there in any option it gives (CSV, CSV [windows compatible], Excel, CSV Zip, JSON, SAV, KML). Otherwise I have the downloaded and cleaned data in Excel or in SPSS."

The SPSS (and Excel files are so "wide" largely because of the multiple response questions.  I wonder whether the R-Instat system could access the data better in multiple data frames?

This seems to be an excellent example to "test" R-Instat.  I am also looking for a set of interesting case studies for our forthcoming Malawi workshop and suggest this is a good example.  In addition to9 these data there was a qualitative component.  I don't expect much to help with this by August, but would like to mention this important topic.

**Comment by rdstern** [comment]
I am having some serious issues in processing these data.

1. The data set has 416 observations and 938 columns.  Great that it reads in reasonably quickly.
2. **Speed issue loading a dialogue:** - I tried Describe > One Variable > Frequencies took about 1 minute to load the dialogue.  I assume that is the selector control.
3. It is also great that with our "new system" we make the changes just once!  There are quite a few changes I think we need for this control.  (Some need some thought.)
4) I can't find the column I want to analyse.  
a) That's partly because there are **no numbers besides the columns** - could that be an option?
b) Also, in SPSS, when you hover over a column in the control it gives **the full name** - even if it goes outside the control.  With us there is a "...".  Some of my column names are very long texts. 
c) As an example, here is the name of the one I want to analyse, (as it was imported!): **SectionSectionCLLSectionCropSectionCropaSectionCropa13other**
d) Of course one way to proceed would be to implement "groups of columns".  Interesting that this feature is on the toolbar in SPSS!
5) This continues to be an excellent example for our "making it easy" objective.

**Comment by rdstern** [comment]
One specific issue is how to perform actions on column names (in particular) - and perhaps also other column attributes.  This is in the "wide" data set so it would be very tedious to have to edit these names manually - which is already easy.
I think R has the answer which is in the dplyr rename command, and which can take regex formulae.  I assume that could be the way we wish to proceed.  
I am struggling a bit already on the production of (say) a keyboard in the Prepare > Column: Texts > Find/Replace dialogue to "make regex easy".  Once we have this keyboard I wonder if we could extend our **Prepare > Data Frame > Rename** dialogue for multiple columns with that same keyboard, i.e. they would cope with regex?
I wonder how we would rename labels?

**Comment by rdstern** [comment]
I have now discussed this dataset with Sebastian and two interesting points result.

1. It seems on terminology ODK distinguishes between **Multiple Choice** questions and **Repeat Groups**.  Multiple choice questions are options where any number can be selected, i.e. multiple response.  But just a single question like that.  Then ODK outputs the data always in our "wide" format, i.e. as many columns as there are choices, and each one is coded 0 or 1 for TRUE or FALSE, i.e. logical columns.

Repeat Groups is when there is a set of questions on each choice.  So, effectively, multiple choice is a trivial case of repeat groups, with just a single question.  For repeat groups ODK permits the downloading in a set of files, e.g. to multiple Excel sheets.

We don't seem to have the data in that multiple format from Graham, but I will ask.  He is away till mid-May.

There is a very similar survey from Tanzania (about 800 records) and Malawi (about 200 records) and we are enquiring from WFP whether we could also use those data as further examples.

**Comment by volloholic** [comment]
@rdstern What remains to be done and can these data go into the library?

**Comment by rdstern** [comment]
[PICSA data_SPSS_July_17.zip](https://github.com/africanmathsinitiative/R-Instat/files/1136563/PICSA.data_SPSS_July_17.zip)
Here are the Ghana PICSA evaluation data in Excel and SPSS form.  They are together with the questionnaire and some other processed data in Excel.
I suggest in the Instat library they go in a PICSA directory, so the files stay together.
