### ISSUE TITLE
Prepare menu still has Column metadata option?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2945]
In our new system do we still want to be able to call the column metadata in this way?  I suggest this menu item should be deleted.

**Comment by dannyparsons** [comment]
I think we could still use this since it has some nice features like editing a property for multiple columns at once and seeing existing values in a drop down.

**Comment by volloholic** [comment]
@dannyparsons is this still working?

**Comment by dannyparsons** [comment]
No it needs some work and needs to be updated.

**Comment by dannyparsons** [comment]
I was confusing this with the editing of column metadata dialog. This item just shows the column metadata grid. It's working, but shall we remove it?

**Comment by dannyparsons** [comment]
Leaving this as it is but can be removed if needed.
