### ISSUE TITLE
File > Export R Workspace

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2951]
This is a new dialog. Not exactly sure where it should go yet but for now on the File menu as "Export R Workspace" under "Export Data".
The idea of this dialog is to export an .RData file which can be imported into R. The difference between .RData and .RDS is that .RDS contains a single R object whereas .RData can contain a collection of objects in a single file. It is like exporting an R workspace. This will be useful if users want to export a collection of data frames, graphs, models etc. to continue working on them without using the instat object. I expect this will mostly be used by people who already know R and want to transfer their work from R-Instat into "standard" R.

This dialog should have a basic selector (without data frame selector at the top) because the selector should show all data frames. (Not sure we have any dialogs like this yet so check if it works, should be set up to dot his already)

There is a multiple selector for choosing multiple data frames that you want to export.

There are then a set of checkboxes to choose which other objects to include: metadata, graphs, models. There may be others to add later.

Finally a textbox with a Browse button to choose the file to save as - just like we have on Export data. The only file type is .RData.

This will use an instat method while doesn't exist yet. But the parameters will roughly be:
data_names (names of selected data frames)
file (the path of the file chosen)
metadata (TRUE/FALSE)
graphs (TRUE/FALSE)
models (TRUE/FALSE)

Function name will be "export_workspace"

Anyone looking for tasks can take this for themselves.

**Comment by AlexSananka** [comment]
@dannyparsons  am taking up this task
