### ISSUE TITLE
Prepare > R Objects > Export

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2952]
This is a new dialog. It is similar to Export Workspace except it exports objects only (graph, model etc.) as an .RData file.

It will just have the usual selector with data frame selector which will show all saved objects and a multiple receiver for objects.

Then a textbox with Browse button for choosing the file to save.

This will use an instat method which doesn't exist yet called "export_objects".

Parameter will be:
data_name (data frame selected)
file (file path to save to)
object_names (list of names of selected objects)

Anyone looking for tasks can take this up.

**Comment by AlexSananka** [comment]
@dannyparsons am happy to take up this task

**Comment by rdstern** [comment]
In the Help file I have added it at the bottom of the Prepare > R Objects menu.  ID is 538.
Should it also go in the File menu?

**Comment by dannyparsons** [comment]
We could have File > Export as a sub menu with Data, Objects etc. as sub items?

**Comment by rdstern** [comment]
Yes.  To me having File > Export > Sub-menu is the obvious place.
Where is the exporting using rio now?  How would I export to (say) SPSS?

**Comment by dannyparsons** [comment]
Export data is exporting data frames as different file types.
