### ISSUE TITLE
Describe > Export Graph as Image

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2953]
This is a new dialog to export a saved graph as an image file.

It will just have a usual selector with data frame selector showing saved graphs and a single receiver for the graph.

Then a textbox with Browse button to choose the file to save to.

I assume this will use the ggsave function but someone should looked into it to make sure it's appropriate. I don't think we need a huge set of options yet - if there are any you feel are important and easy to include on the main dialog then put them in. Eventually we will probably have a sub dialog for Options.

It would be nice if the user could choose from different file types if possible - I expect this will be done in the Save dialog depending on what types ggsave allows.

Anyone looking for tasks can take this up. Possibly @maxwellfundi has already looked into ggsave because we use it for the output window display?

**Comment by maxwellfundi** [comment]
@dannyparsons  i am happy to take up this task as we had previously looked at ggsave earlier on. 

Thanks.
