### ISSUE TITLE
Right-click in the column metadata window 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2967]
I have been pondering more on how we "make it easy" to cope with "wide" data sets.  I suggest this is important as an advance we can make, because of the neat way we will be able to handle multiple data frames.
In this context it is clear we need simple ways to select subsets of the columns.  Effectively we need to be able to filter on column names.  This could be neat if it is available through a right-click in the rows of the column metadata! We already make good use of the right-click facility and also have a way of keeping the information when we show a subset of the data.  So, for the meta-data could we have filtering on the column names/labels, etc. and also enable (and show this) through the window?
This right-click is more general than the filtering, but I see this as a key element of it.

**Comment by dannyparsons** [comment]
Now implemented.

**Comment by rdstern** [comment]
Would it be quick to also implement the bottom tab on the column metadata and also on the sheet metadata?

**Comment by dannyparsons** [comment]
you just don't want any issues to be closed!

**Comment by dannyparsons** [comment]
(but yes we can do that)

**Comment by dannyparsons** [comment]
@Lunalo should be simple to add as it will be a copy of the data viewer one.

**Comment by shadrackkibet** [comment]
> Would it be quick to also implement the bottom tab on the column metadata and also on the sheet metadata?

@rdstern by this point do you mean that the same right-click (see below) in the data viewer available via column metadata?
![image](https://user-images.githubusercontent.com/26301973/106275755-6a446780-6247-11eb-916b-f4f3a3f75e13.png)

Currently, we got this in column metadata right-click. I think it should be the same?
![image](https://user-images.githubusercontent.com/26301973/106275840-9364f800-6247-11eb-9428-0e04dfd8d863.png)

**Comment by rdstern** [comment]
I agree it could usefully be the same.  This links with another suggestion on the Windows, (I forget the issue) that sometimes it would be good to have column metadata instead of the data - where we only have 1000 observations anyway.

**Comment by shadrackkibet** [comment]
@HawardKetoyoMsatsi this looks like an easy one to look into. Happy with this?

**Comment by shadrackkibet** [comment]
@rdstern the column right clicks are also different in column metadata and data view. I think both should be the same.
Column metadata
![image](https://user-images.githubusercontent.com/26301973/106280980-a7145c80-624f-11eb-9230-db90692be7a7.png)

Data View
![image](https://user-images.githubusercontent.com/26301973/106281093-d0cd8380-624f-11eb-9e61-f9ac5d55d44c.png)

**Comment by rdstern** [comment]
Agreed
