### ISSUE TITLE
Adding shift option to the Prepare > Column: Dates > Use Date dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2968]
I suggest this work could be for Shadrack with support from Steve and Danny.

This is under (or next to to the Day in Year (366).  It is called something like Shifted day.  You might change the layout of the boxes perhaps, so there is one that goes right across with the label "Day" and is above , 3 of which are there already"Other Functions".  There are 4 options inside this box 3 of which are there already (and don't change).  The first could now be labelled "In Month" and is the one called Day now.  The second and third are as now and labelled "In Year" and "In Year (366)".  
The new one is called "Shifted".  If checked, then 2 up-down controls become also visible,  The first goes from 1 to 12 with 8 as the default.  The second goes from 1 to 31 with 1 as the default.
This will simply generate a variate which is the same sa the "In Year (366)" but starting from a different month/day.  
1. This will generate a column called shiftx e.g. shift8 (where x = 1 to 12), if the day of the month is 1.  Otherwise the name of the column could be shift8.11 if the start day is 11th August.
2. Spend just a little time on the code (15-30 minutes) and then discuss, with Steve and/or Danny, on how to do this calculation neatly.
3. Discuss also how (and particularly where) you will check that the date is valid, You could (perhaps) organise that the second up-down control (day of month) only goes to 30 if the month is 4, 6, 9, 11 and 29 if it is 2.  Alternatively this could be a check that is a preliminary when OK is pressed.  (There must be other dialogues where combinations of controls are not OK, though individually they are OK.)
4. Finally there will also be a small change in the **Climatic > Define Climatic Data** dialogue.  The "Day of Year" field is currently filled by one of the two options if they have been generated.  Now, if a Shiftx column exists this has priority.  (No extra field is needed.)  And while on that dialogue you may wish to change the label above from **"Day" to "Day in Month"**.

**Comment by rdstern** [comment]
I have realised we also need another column to go with this dialogue.  We need a shift year column to go with the Shift day.  I suggest we define the corresponding Shiftyr column.  This is the year that the shifted day begins.  So if the shifted day starts on 1 August, then the shifted year is the year number whn the shifted day begins.  And it stays at that year until the shifted day reaches 366.
Let me give an example.  If the shifted year starts on 1st August then the shifted year starts then too. 
 So 1st August 2010 defines 2010 as the year and that shifted year remains as 2010 until 31 July 2011. 
In the Climatic > Define Climatic Data then both the Year and the Day_in_Year  are shifted if the shifted ones exist.

**Comment by dannyparsons** [comment]
We implemented this in the old climate object as a "season" i.e. a year that starts on any day. So when someone works on this we should discuss what was done in the climate object to avoid redoing work that's already been done.

**Comment by rdstern** [comment]
Happy to see it supplementing what was done earlier.  I have now called it "Shift" rather than Season, because some people seem to feel that "Season" has a specific meaning.  I assume you also had the shifted year?

**Comment by dannyparsons** [comment]
Yes we had both. We had "Day of Season" and "Season" (year). So now we have `shift_x` and `shift_yr`? Also for the shift year we usually had something like 2010-11. But we could have options for this, including just 2010.

**Comment by rdstern** [comment]
Could the implementation of this feature be discussed while you are together.  Once implemented in the Use Date dialogue these columns would become the defaults in the Define Climatic and they would then be used in the inventory plots when the DOY is one of the axes.

**Comment by dannyparsons** [comment]
Yes we can work on this as we update the inventory plot as well.

**Comment by dannyparsons** [comment]
@rdstern this could be tested now (also try converting the shifted year between numeric and factor)
