### ISSUE TITLE
Interactive Plots using ggplot

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2970]
While doing non-R-Instat work, I have been discovering the world of interactive plots for ggplot.
I had a go at seeing how this works in R-Instat today because it's a quick, easy code and looks quite nice.
It opens the graph in a new Internet tab, like our HTML tables do.

In R-Instat I used the Dodoma dataset and looked at scatterplots.
This feature allows me to hover my mouse over the scatterplot points to see their values:

![image](https://cloud.githubusercontent.com/assets/21180424/25442751/c680b89a-2a9d-11e7-96aa-b48257f8daae.png)
_Here we can see on the Dodoma Dataset the highest rainfall amount is 119.8mm in 1964_

Or I can easily create a subset to look at a more specific area:
![image](https://cloud.githubusercontent.com/assets/21180424/25442826/f92888ea-2a9d-11e7-9512-49315476a8b3.png)
![image](https://cloud.githubusercontent.com/assets/21180424/25442834/042d917c-2a9e-11e7-9785-16f9d368dd66.png)
_I can look easily at the subset 1935-1945, rather than the entirety of 1935-2013_

The particular code I've been using to do an interactive plot is very simple, it's with the "plotly" package and the code is just
`ggplotly()`
By default it calls in your last ggplot

Additionally, `ggplotly(p=GraphName)` enables you to call in a previous ggplot object.

@africanmathsinitiative/developers I think this would be a nice feature, and it is very easily to implement.
What are thoughts on:
* A new dialog where you can view a plot in this way?
* And/or adding this to options in graph display

**Comment by dannyparsons** [comment]
I like this. I think a new dialog where we can choose to display a saved graph in a variety of different ways, one being interactive, would be good.

**Comment by rdstern** [comment]
I agree completely.  Being able to look interactively at a graph would be great.

**Comment by lilyclements** [comment]
After a discussion with @dannyparsons we are thinking of a new dialog "View Graph"

This dialog can have a selector which contains saved graphs
Then a single receiver.
There can then be a group box titled "Display Options"
In this group box are four radio buttons:
* Display in Output Window
* Display in R-Viewer
* Display in Separate Window
* Display in Interactive Viewer


**Output Window** displays it in the output window, as we usually expect (I assume this is the default). This would run the code
`InstatDataObject$get_graphs(graph_name = ..., data_name = ...)`
With a call type of 3

**R-Viewer** displays it in the r-viewer, so this would use the same code as Output Window. Only difference is that this has a call type of 0

**Separate Window** can be disabled for now

**Interactive Viewer**, as explained above. This uses the line `ggplotly(p = ...)`

Then that's it (I think!)

@africanmathsinitiative/developers if anyone is short of a tak, there's a quite nice one here.
Note you will probably need to install the package: plotly

**Comment by stevenndungu** [comment]
@lilyclements  am happy taking up this task, since am kind of done with what am doing apart from small things to sort out with Danny when he comes.

**Comment by maxwellfundi** [comment]
I like this feature and i agree completely that a new dialog which would produce a saved graph dynamically would be a sensible thing. 
I am just wondering if the "View Graph" would be used as the current use graph. 
I think the current use graph can be used to incorporate these additional features, because for example, when you select a graph on the use graph dialog and click OK, you can be able to view this graph. Additionally, you can edit the graph. How about adjusting this dialog abit to incorporate these new options? @africanmathsinitiative/developers what eould be your thought on this.

**Comment by maxwellfundi** [comment]
In addition we can have this feature in all the ggplot  dialogs. I have been playing with it and it looks  really impressive. 
We will need to have the ggplotly command as our base operator then add in the other gglot functions to achieve the same result. 
`require(plotly)
ggplotly(ggplot(data=survey_temp, mapping=aes(fill=Variety., y=Yield, x=Village.)) + geom_boxplot())
`

**Comment by lilyclements** [comment]
@maxwellfundi I had the same thought about it being incorporated into Use Graph. However Danny convinced me otherwise. This dialog is to do with displaying the graph in different ways (like how we have a view data dialog which is concerned with viewing data in different ways). In Use Graph, you can edit the Graph. I think we don't want too much in one dialog and it's quite nice to have a dialog for just viewing the graph

Glad you've been playing with the feature. However doesn't
NameofGraph <- Ggplot(data = ...., mapping = ..., x = ...) + geom_boxplot
Ggplotly(p = Name of Graph)
Also work? It did for me when I tried it out

I suppose my method gives it in the output window and in an interactive window on a new tab which the user may not want. Does your method give it as a new tab instead of in the output window?

**Comment by lilyclements** [comment]
@stevenndungu sounds great! I look forward to seeing it!

**Comment by maxwellfundi** [comment]
@lilyclements either of those ways work. So when i run the ggplotly, the graph comes in the output window and its interactive. You would actually not notice its interactive, until you move the mouse over the graph.

**Comment by lilyclements** [comment]
Are you doing this on R-Instat or on R?
On R-Instat I can't get it in the output window, it opens in a new tab on Internet like a HTML plot does.
Have you managed to get it to be interactive in the output window on R-Instat?

**Comment by maxwellfundi** [comment]
I have been working on this in R, we will work with @stevenndungu  to see if we can get it to the output window of R-Instat.

**Comment by stevekogo** [comment]
I think this is tied up with displaying frequency tables on the output
window. @stevenndungu <https://github.com/stevenndungu> can advice further
on this.

**Comment by stevenndungu** [comment]
Yap, it is possible to have it on the output window easily. Working on it now

**Comment by lilyclements** [comment]
I think when we look into getting HTML tables into the output window of R-Instat then we can look into getting these interactive graphs in. However, for the time being it is okay to have it in a separate window, just like we have the HTML tables in a separate window.
Unless it's a really simple job!

**Comment by rdstern** [comment]
When I do the box-plot with facets I am able to do the View Graph dialogue.
But when I use the Describe > One Variable > Graph dialogue and produce box-plots with facets then it says:
---------------------------
Error running R command(s)
---------------------------
Error in UseMethod("ggplotly", p) : 
  no applicable method for 'ggplotly' applied to an object of class "c('gtable', 'gTree', 'grob', 'gDesc')"


The error occurred in attempting to run the following R command(s):

plotly::ggplotly(p=InstatDataObject$get_graphs(data_name="survey", graph_name="last_graph"))
---------------------------
OK   
---------------------------

I accept that a combined graph, can perhaps not be displayed.,  But I just used the survey data and just the numeric columns, so it was facets.

**Comment by maxwellfundi** [comment]
@stevenndungu This seems to be persistent till now, has anything been done on it? Is it something we that can be fixed quickly?

**Comment by lilyclements** [comment]
I don't know how easily this can be fixed. So, the problem is that when we use Describe > One Variable > Graph and use facets, the object is not a ggplot object, which is why plotly() cannot work for it. However, when we do a boxplot the object is a ggplot so it'll work.
The only foreseeable way here is to get the One Var Graph to be a ggplot object which I don't believe is easy.

I've looked into alternative functions through the plotly package, but not found any suitable yet unfortunately. There is a lot in that package to look into though for other things.

Is it possible yet to restrict the receiver to only ggplot objects?

**Comment by dannyparsons** [comment]
I can look at restricting this today.

**Comment by dannyparsons** [comment]
This was a bug in one variable graph where it was always producing a combined graph even when asking for facets. It now produces facets and this can be used in the View Graph dialog.
