### ISSUE TITLE
Open from file

### ISSUE THREAD

**Issue by mmumbo** [africanmathsinitiative/R-Instat#2974]
When opening file from a specific location i believe it would be clearer if we replace **select file** with **Browse** since from the **import** dialogue you will be browsing where the file is located

**Comment by dannyparsons** [comment]
I agree, let's have consistency across dialogs. I think `Browse...` is what we want. Anyone to implement this? @africanmathsinitiative/developers

**Comment by lilyclements** [comment]
I am planning to systematically go through five dialogs a day to make everything perfect and consistent with layouts and code.
I will add this to the "To Do" list for when I go through dialogs

**Comment by lilyclements** [comment]
^ Starting from when I finish reading these documents on Window's idea of a perfect layout

**Comment by volloholic** [comment]
Has this been done on all file dialogs?

**Comment by lilyclements** [comment]
I'll check and make amendments where necessary tonight

**Comment by dannyparsons** [comment]
Thanks @mmumbo for the suggestion, all selection files have been replaced with Browse now.
