### ISSUE TITLE
Adding an extremes dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2976]
There are still 2 new dialogues to add to **Climatic > Prepare > Specific Events**, which will become **Climatic > Prepare > Extremes** and **Climatic > Prepare > End of the Rains**.  This issue is about the **Climatic > Prepare > Extremes**.  This dialogue will take (usually) daily data and find the annual extremes.   Then there is a second dialogue, Climatic > Model > Extremes which will model the extremes we have calculated from the Prepare dialogue.

So the Climatic > Prepare > Extremes does exactly that - it prepares the extremes for fitting a model!
a) At the top of the dialogue there are 2 buttons, namely **Max/Min** and **Peaks**. 
b) The middle of the dialogue can be the same as the Climatic > Prepare > Transform dialogue.  There is no threshold button needed, but the others, namely 1)Station, 2) Date, 3) Year, 4) Day of Year, 5) Data are the same.
c) There are also From and To fields as in the Start of the rains dialogues.
d) Then there are two alternative blocks one with the label **Max/Min** and the other with the label **Peaks**.
e) In the Max/Min block there is a checkbox  - default checked - with the label Maxima.

f) The second block is labelled Peaks
g) The first field is labelled Threshold - any number can be entered into this field.  
h) The second is a checkbox Default checked - "Values above threshold"
i) The year is saved automatically.  Two more columns can be saved. The usual one is **Value**.  The second one has a checkbox, default checked, **Day Number**.

**Comment by shadrackkibet** [comment]
I am working on this

**Comment by stevekogo** [comment]
@shadrackkibet and I are suggesting we have a skype call to discuss this dialog. The main focus is on peaks above threshold where I think we can use filters or subset in order to address the issue.
@dannyparsons, can you call us anytime so that we can discuss this.

**Comment by dannyparsons** [comment]
We could Skype after the meeting with the team, but yes that part should be done with filters

**Comment by shadrackkibet** [comment]
@dannyparsons this can now be closed.
