### ISSUE TITLE
Changing Water Balance dialogue to become End of the Rains

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2978]
The current Water Balance dialogue is just used for the end of the rains.
1. I have suggested elsewhere that the menu name be changed to "End of the Rains"
2. Within the dialogue have the title as "End of the Rains/Season".
3. At the top add three buttons with the labels Rain, Water Balance, Both.
4. Add a field to the top with the label "Station"
5. Change the order to have Station, Date, Year, Day of Year, Rain.  
6. Keep the current fields From and To.
7. Have 2 blocks with the first labelled **Rainfall**, and the second labelled **Water Balance**.  Their positions are below each other (or possibly side-by-side).  So if Rain is selected, then just the Rainfall block is visible, ditto for Water Balance.  Both are visible (with Rainfall on top or to the left) if **Both** is selected.
8. The rainfall block is similar to a simpler version of the labels for the controls for the start of the rains.  It says **Total Over** <up-down control> **Day(s)**.  Amount <Input box> mms. In the up-down control the limits are 1 and 31 with the initial setting as 1.  The amount has 10 initially as the default.

9. The other block has the label Water Balance.  It has the controls on the existing dialogue, namely Evaporation, Capacity and Water Balance <=.  

10. The New column name is now End, i.e. End1, etc.

**Comment by stevekogo** [comment]
I am going to work on this.

**Comment by lilyclements** [comment]
Is this to have this End of Rains instead of Water Balance or as well as?

**Comment by rdstern** [comment]
As well as.  This is to be renamed as "End of the Rains", so the other menu item is no longer there.  Then it incorporates the Water balance plus another popular definition for the end of the rains.

One reason to combine the dialogues is that you sometimes want to start the water balance on the date of the last occurrence of rain - which is another definition.

**Comment by stevekogo** [comment]
@rdstern I don't think we need two grou boxes for end of rain and water balance radio buttons.
This is because end of rains depends on water balance column hence depends on those controls. We might have to disable the controls whenever we move from one radio button to another,
