### ISSUE TITLE
Climatic > Prepare > Summary dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2982]
This should be a relatively simple dialogue to construct initially, because it is based simply on the stanard summary system.  I give my idea for the design below, but suggest that you discuss aspects of this dialogue to make it simple to use, but powerful.
It is the same as the Climatic > Summary dialogue in the old Instat.
1. It is usually used to give annual summaries like total rainfall or total number of rain days.  One special case is that it could provide the total rainfall between the date of the start and the end of the season - which could be different each year.  And it could also provide summaries within a year, e.g. monthly.
2. So I suggest we emphasise these three possibilities by three buttons at the top of the dialogue, They say Annual, Annual-Variable, Within Year.  The whole dialogue is just called Summary, so we don't need to repeat that.
3. The next part of the dialogue is the same as the others in this section, i.e. Usual selector on the left, then Station, Date, Year, Day in Year columns and Data (with rainfall as the default element in the data column.)
4. Then it depends on which of the 3 options at the top are chosen.  So there is a small block with the same label as the options at the top.
a) If **Annual** is chosen, then it is the same as for start of the rains, i.e. **From Day <up-down> To Day (up-Down**.  Each can be between 1 and 366 with the default being 1 for the first and 366 for the second.
b) If **Annual-Variable** is chosen then the two up-down controls are replaced by receivers.  When one of those receivers is active the data frame is changed to the linked annual data frame - if it exists.  
c) If **Within year** is chosen then the original data frame remains there, restricted to factors, and if there is a Month factor defined then this is included.  (The results are then not an annual dataframe, but one with up to 3 factors, namely Station, Year, Month.
5. There remain 2 more components, namely what summary is to be produced and what to do if there are missing values.  I consider them in turn:
6. There are many possible summaries, and hence I think this should be a sub-dialogue.  As with the old Instat - and different from our full summary system - I suggest (usually) a single summary column be generated.  And hopefully the name of the summary could be on the main dialogue.  So there could be a Summary button - with the label after that button showing which summary type has been selected.  
7. In the sub-dialogue there is a list of 10 radio-button, as follows:
i) Totals
ii) _Counts_
iii) Missing
iv) Minima
v) Means
vi) Medians
vii) Maxima
viii) Std. Devs.
ix) _Percentiles_   
x) _Proportions_

The 3 in italic have additional field if they are selected as follows:
ii) If Counts then there is a drop down with the options >, >=, =, <=, < (< is the default) then a field for a number with 0.85 there as the default.
ix) For Percentiles there is a drop down into which a list can be typed.  There are default values "50", "20, 50, 80", "25, 50 80", "10, 20, 50, 80, 90", "80, 90, 95"
x) For Proportions there is a drop-down as in ii) plus a field into which a list of numbers can be typed. There is also a check-box default checked, saying "Percentages".        
8) There is also a "Missing" button on the main dialogue, though this could alternatively be on the **Define Climatic Data** Dialogue.  I suggest it might more appropriately be there, even though currently this is the only dialogue that will use it.  This would define the number of values that can be missing for annual data and monthly data.  The default would be that if anything is missing then the result is missing.  The opposite is that the summary is given if it can be calculated.  Both of these are standard in R.  The intermediate cases are specified here.

**Comment by dannyparsons** [comment]
This looks good and I think all possible within our summary system - apart from the missing values options which we haven't yet implemented.

Would it be useful to be able to do summaries in this dialog without the year column? For example, summaries which could add into the Station data frame. If so then could it be more like the column summaries dialog where there is just a multiple receiver for factors - which could have year included by default? It would simplify it in some ways by not needing options at the top - but maybe makes it too general for what's needed?

**Comment by rdstern** [comment]
No, that would be fine.  And useful too.

You would then often want to restrict data to a subset of the years, which would be simply with a filter.

On the missing values I am becoming more convinced that we should start by putting this feature into the Define Climatic Data.  Then ther might (later?) be a facility in the individual dialogues, which would then take precedence.  Otherwise the general setting would be used.

Given that, I would ignore that aspect in the dialogue for now.  There will anyway be more changes when we move to a sub-dialogue system.  Whether that will be instead or as well as what we do now has yet to be determined.

**Comment by dannyparsons** [comment]
Ok great. And yes we could put data frame options on define climatic like missing value thresholds and rain day thresholds etc. which could then just be added to the data frame metadata. These could be used to set the dialog defaults but could be overridden by specific dialogs.

**Comment by AlexSananka** [comment]
Can this be modified to maybe go to another milestone?

**Comment by shadrackkibet** [comment]
@dannyparsons @rdstern  we need to discuss some of the aspects of this dialog. I have started adding controls at #3708.

**Comment by lilyclements** [comment]
I understand the "Annual" options (probably because that's what we've been doing on the other climatic dialogs!)
However, not sure on the "Annual-Year". What is in a linked-annual-data-frame? Is that like my Start_of_Rains_By_Year data frame?
Similarly for "Within Year" I'm unclear. Is this looking at the monthly summaries? And if so, is it looking at all the "January" observations across all years, or is it looking at "January 1970", "February 1970", ..., "January 1971"

**Comment by rdstern** [comment]
So let's take (daily) rainfall data and assume we want totals or counts of rain days etc.  
1.  These could be annual totals just like your start of the rains gives one number per year.
2. Or they could be (say) monthly totals (or 10-day, or weekly).  That is the summary with the 2 factors of year and month (or week) within the year.
3. The third possibility is to give the annual totals but taking the start and end dates from an annual file.  So that could give the annual total between the dates of the start and end of the season, say.  Or it could be between the start and 90 days later, etc.
I am not sure whether this third option needs a radio button or it is just a generalisation of the first and last dates to get the annual totals.  Happy to discuss.  Also happy to get the other two options working first.

**Comment by lilyclements** [comment]
So did we agree that the sub dialog for this can use sdgSummaries?
If so, @rdstern specified a few extra things for the sub, such as a dropdown box for counts. Do we want this to be an option for other dialogs which use this sub, such as dlgColumnStats?

**Comment by dannyparsons** [comment]
Some overlapping information on this issue is here #3516. Further discussion should stay here and not on #3516 which is now closed.

I will keep this issue open. An initial implementation is merged but further work needed for later milestones.

**Comment by dannyparsons** [comment]
@shadrackkibet @rdstern what's the state of this? Is there more to implement from the initial messages or should this be closed?

**Comment by shadrackkibet** [comment]
@dannyparsons .This can be closed.
