### ISSUE TITLE
Defining and Using Groups of Variables

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2985]
I am using SPSS as a sort of model for us to be able to have facilities to cope well with "wide" data sets.  In some ways we can do better than SPSS, because we can cope with multiple data frames.  And one reason SPSS files are often so wide is that it doesn't do that so well.
1. Hence one strategy will be to transform wide frames into long ones.  I suggest here we might explore adding a facility to strengthen our stack dialogue (or we have a second dialogue) so we can stack multiple sets.  This seems to be available in the to_long function in sjmisc.
2. The second strategy is to be able to select **groups** of variables (SPSS calls them "**sets**".) What name do we want?  This issue is concerned with the second option.  I first show SPSS figures:
![spss variable sets](https://cloud.githubusercontent.com/assets/11226469/25517397/26aa36b6-2be7-11e7-8817-f461debe243d.jpg)
This shows the initial use of variable sets.  The toolbar includes these elements - though we may be able to do better!  See below.
![spss define variable sets](https://cloud.githubusercontent.com/assets/11226469/25517697/7794533a-2be8-11e7-9e99-e8f0c78cdd50.jpg)
This shows the dialogue to define, change and remove variable groups.  It is a pleasingly simple dialogue, though I found it initially confusing that you click on one of the 3 buttons at the top, rather than an OK button.

In our dialogues we have the possible **right-click** in the data selector.  We also have a **Data Options** button that has yet to be used for selecting variables.  It can be used for filtering rows.
One problem in SPSS is that I can't find a way of choosing a subset of the columns automatically.  It does have facilities for defining new attributes, and also for sorting on any attribute.  (Could we add this easily in our column metadata window?)
Back to the task in hand.  There is a very nice looking function in **sjmisc** called **find_var**, e.g. **find_var(efc, "cop")**.  It seems to be very powerful in that it can include regex - when we want to.  And it has the options of searching in any combination of the **variable names, variable labels and value labels**. 

I wonder where it should go?  This could be the Columns tab in the Data Options dialogue?  Perhaps that could also be accessed from right-click in the selector field and also from right-click when in the column metadata window.  There could be a "full-use" of the facility, where options can be set.  Then the right-click could allow just the matching string to be typed?
Once a subset is selected, it could perhaps be just for that dialogue, or defined as a set to be used?  In SPSS the column variables shown are just those in the sets to be used.

If we are to have an ordinary dialogue then it could go naturally(?) in the **Prepare > Column: Text** though it is a bit different - so there would be a line before the dialogue(s).  Or there should be a new **Prepare > Variables** menu.  Could we use this opportunity to divide the **Prepare > Data Frame** menu which is a bit long already?

**Comment by Lunalo** [comment]
Hi @rdstern 

I have gone through this and still I don't understand some of the things involving its usability. I will skype for more insights

**Comment by dannyparsons** [comment]
Defining sets of columns is something we should be able to do easily since a group is just a metadata property for columns, and having an option of regular expression would be nice. If we did that then I think we should have a preview so you can see which columns match the regular expression.

I suggest we have a single dialog/sub dialog for defining a set of columns - possibly with two options for now 1. just selecting them from the list 2. selecting through a regular expression.

This could then be a dialog in the Prepare menu as well as accessible through the Data Options where it could be defined globally or locally for the dialog.

How does that sound?

**Comment by rdstern** [comment]
That sounds ideal.

**Comment by AlexSananka** [comment]
I have gone through the comments in this issue and this sounds to be a new dialog?Can this also be moved to the next milestone?or anyone with updates on this.

**Comment by rdstern** [comment]
Agreed, there are still improvements needed to our select system, but they are not mentioned here.
