### ISSUE TITLE
Calculations

### ISSUE THREAD

**Issue by mmumbo** [africanmathsinitiative/R-Instat#2989]
I'm trying to find out the duration taken by each individual to complete filling ODK form, the calculate dialogue is not working for me. Is it functional at the moment?

**Comment by dannyparsons** [comment]
It depends what the type of columns you are using are? Can you check in the column metadata grid to see the class of those columns? If they are not numeric, or a variation of numeric, then it won't be able to do a subtraction on the columns.

We do need to think about time columns at some point now that we have date working. I believe there are a number of packages for having a time class, as well as standard classes for date-time. We should investigate these, but I don't know what priority it is.

**Comment by dannyparsons** [comment]
Is there still an issue with this data? If you send it I can have a look at it.

**Comment by volloholic** [comment]
@mmumbo Can you help confirm if this is still an issue.

**Comment by mmumbo** [comment]
Thanks a lot, its working perfectly well now. Well done!!

Attached is the data i was using @dannyparsons in case you are interested in looking at it.

[Time_Dates.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/1122271/Time_Dates.xlsx)

**Comment by dannyparsons** [comment]
Great, and interesting data. The columns import as a specific date type and we can do calculations on them. But we can't do everything we would like with the time components. This is useful to think about when we implement this @rdstern
