### ISSUE TITLE
Bug in calculated with calculated columns

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2992]
```
# dlgDefineCRI code generated by the dialog Define CRI
CRI1 <- instat_calculation$new(calculated_from=list(wb_raw_calc_subset1 = "signature_period5Q", wb_raw_calc_subset1 = "roll_share_winner", wb_raw_calc_subset1 = "contract_value_share_over_threshold"), function_exp="(((0 * (signature_period5Q=='4')) + 1 * (signature_period5Q=='5') + 0 * (signature_period5Q=='3') + 1 * (signature_period5Q=='1') + 1 * (signature_period5Q=='2')) + roll_share_winner * 1 + 1 * contract_value_share_over_threshold)/3", save=2, result_name="CRI1", type="calculation")
InstatDataObject$run_instat_calculation(display=FALSE, calc=CRI1)

wb_raw_calc_subset1_temp <- InstatDataObject$get_data_frame(use_current_filter=FALSE, data_name="wb_raw_calc_subset1")
attach(what=wb_raw_calc_subset1_temp)

# dlgCalculator code generated by the dialog Calculations
CRI_scaled <- CRI1/max(CRI1, na.rm = TRUE)
InstatDataObject$add_columns_to_data(col_data=CRI_scaled, col_name="CRI_scaled", data_name="wb_raw_calc_subset1")


detach(unload=TRUE, name=wb_raw_calc_subset1_temp)

wb_raw_calc_subset1_temp <- InstatDataObject$get_data_frame(use_current_filter=FALSE, data_name="wb_raw_calc_subset1")
attach(what=wb_raw_calc_subset1_temp)
```

The code above is from two dialogs. First, I create a calculation called CRI1 and then add  a column with that name to the data. 
Then when I try to use the new CRI1 column in the calculator, because a variable with that name is in the global environment, it tries to use the calculation instead of the column - and gives an error. 

This is an issue because of the attach and detach. When we redo the calculator so that it goes through our calculation system this shouldn't be an issue. This is something to be aware of as I imagine this error could happen after doing summaries using the climate dialogs as well.

We may want options like clearing the global environment in R through R-Instat.

**Comment by lilyclements** [comment]
So, this is the same error as that Roger describes in #2854 on Water Balance. Thank you for explaining the problem!
However, I'm now a little confused. When I tested it out on R previously, I found that if I run

```
Water_Balance1 <- InstatDataObject$get_columns_from_data(use_current_filter=FALSE, col_names="Water_Balance1", data_name="Damango_by_Year)"
```
before the calculation then it works.

Why does running it as an r function as oppose to a string fix it? I don't see how this relates to the attach and detach. Would you mind explaining?

Thank you for explaining that the update of calculate will fix this issue!
Should we keep Roger's issue on the matter open?

**Comment by dannyparsons** [comment]
when you attach a data frame you can then just refer to column names directly:
```
attach(survey)
mean(Yield)
detach(survey)
```
But when there's also a variable in the global environment called `Yield` it uses that instead of the column from the data. So, in particular, for us it's trying to use a calculation object in the calculation and it's getting messed up. This is why renaming the column fixes it because then the new column name is no longer a calculation in the global environment.

It does sound like the same bug as in #2854 good to know the cause at least now.

**Comment by lilyclements** [comment]
Great, that makes a lot of sense! Thank you!
