### ISSUE TITLE
Changes to the file menu?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3003]
Danny, I think you have ideas from Ric that could add an item to the file menu?
I have been looking at that menu in relation to the help numbers, and have noticed the following:

Import from CSPRO has help number 515
Import from Databases has help number 516
Convert has help number 469
Save As for Data has help number 470
For the other 3 options here there is a standard save as dialogue.  It doesn't have a help button, but I wonder if that might be an option in the dialogue?  If so, then 
Output has help number 471, Log is 472 and script is 473.
Export is help number 221

The next issue is Print and Print Preview.  They look very odd as dialogues.  I wonder if they need discussion while you are in Maseno, or this should initially be with David?
if they get to the stage of hyaving a help button then Print is 334 and Print Preview is 335

**Comment by dannyparsons** [comment]
We can't edit anything on the Windows Save dialogs - so we can't add buttons. But I think we could still have help pages on them ad you just have to access them from the Help menu?

I assume Print and Print Preview are not priorities? But probably we can get something simple working on them before the first release. I expect it's something someone can investigate on their own and then have a go at so don't see it as urgent for this week. I think they will need help pages though.
