### ISSUE TITLE
Help IDs in Prepare, Describe and Climatic

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3004]
In Prepare the only dialogues I found that did not go to the correct place were:

Factor > View Factor Labels  - new dialogue ID 517
Text > Find/Replace ID 406
Text > Distance ID 347

Describe > One Variable > Frequencies ID 518
Describe > One Variable > Rating Data ID 519

Describe > Two Variables > Frequencies ID 415

Describe > 3 or 4 Variables > Summarise ID 521
Describe > 3 or 4 Variables > Graph  ID 522
Describe > 3 or 4 variables > Frequencies ID 523

Describe > Export Graph as Image ID 524
Describe > View Graph > ID 525

Climatic > File > Import Gridded Data (IRI) ID 526
Climatic > Dates > Infill Missing Dates ID 497

Climatic > Prepare > Transform ID 358
Climatic > Prepare > Climatic Summaries ID 510
Climatic > Prepare > Start ID 199
Climatic > Prepare > Spell ID 200 
Climatic > Prepare > Extremes ID 203
Climatic > Prepare > End > 201

@dannyparsons  There isn't currently any help menus for the corruption menu.  I thought it was to change to Procurement and possibly change within the menu.  Do you want me to constru8ct the help for the current menu or wait?

**Comment by dannyparsons** [comment]
The title of the menu may change, I think the sub menus and items will largely stay unchanged, but if it's better to do the help pages once the names have been changed it can wait.

Will you also upload the latest help file the to Instat help repository?

**Comment by rdstern** [comment]
Here are the Help IDs for the current menu:
Define ID 499
Corruption > Prepare 8 dialogues with ID 530 to 537
Corruption > Describe ID 501
Corruption > Define Outputs ID 191
Corruption > Model > Fit Model ID 529
Corruption > Define Red Flags ID 202
Corruption > Calculate Corruption Risk ID 527
Corruption > Tools ID 528

**Comment by dannyparsons** [comment]
Thanks, can someone add these in?

**Comment by stevekogo** [comment]
I am going to add these in

**Comment by maxwellfundi** [comment]
@stevekogo were all these added in so that this can be closed by @dannyparsons ?

**Comment by maxwellfundi** [comment]
@stevekogo can this be closed?

**Comment by maxwellfundi** [comment]
@stevekogo could @dannyparsons  close this issue? Were all of these added in ?

**Comment by dannyparsons** [comment]
Can someone check the help id numbers are correct?

**Comment by AlexSananka** [comment]
I can go through this and confirm.

**Comment by AlexSananka** [comment]
I have gone through all this and found that they are correct except two dialogs which when I click on help takes me to introduction.
Climatic > Prepare > Climatic Summaries ID 510
Climatic > Prepare > End > 201

**Comment by AlexSananka** [comment]
Also when you click on end of rains you get the dialog water balance.

Do we need the dialog and the menu item to have the same name?

**Comment by maxwellfundi** [comment]
@AlexSananka can you add those in?

**Comment by dannyparsons** [comment]
Yes dialog and menu item should have same time

**Comment by AlexSananka** [comment]
In this case what do we change,the menu item or the dialog?

**Comment by AlexSananka** [comment]
Did you mean same time or same name?

**Comment by dannyparsons** [comment]
There was a renaming of water balance/end of rains recently so check with @rdstern as to how these dialogs and menus should be labelled now.

**Comment by rdstern** [comment]
This is now the end of the rains and I will change that on the help

**Comment by AlexSananka** [comment]
Ok am renaming this dialog now

**Comment by maxwellfundi** [comment]
This can now be closed @dannyparsons
