### ISSUE TITLE
Size of the software

### ISSUE THREAD

**Issue by mmumbo** [africanmathsinitiative/R-Instat#3006]
This might not be urgent but i feel it's important to note that the size of R-Instat software is too huge that computers with low internal memory finds it difficult to run the software. This is a challenge that users at the Lewa Maths Camp were experiencing with their laptops.

**Comment by dannyparsons** [comment]
Thanks Mike, this is important. What were the issues specifically? Was it the size of the software and additions being installed which took up too much storage on the computer? Or was it the slowing down because of memory usage by R-Instat? Or both?

**Comment by maxwellfundi** [comment]
Hi Mike, this is a good point. I remember you mentioned that they had to uninstall some stuff. Currently, the software that takes up alot of disk space is Rtools, which take up 1.01 GB the rest take up less than 400 mb. There is very little we can do about the size of Rtools currently but i hope its something we can look at in the future.

**Comment by mmumbo** [comment]
@dannyparsons From my observation, it was memory usage by R-Instat because sometimes they can load for a long time without launching the software

**Comment by dannyparsons** [comment]
We can't reduce the size of Rtools but we can not include it, or at least have that as an option. Currently it is only used for export to Excel but it adds 100MB to the installer.

We will also need to set minimum system requirements/recommendations before the release and this is useful for that.

**Comment by AlexSananka** [comment]
there is a great improvement on the speed of how the software loads even using large data sets,I do not know if this issue was related to the same,If so then I think it should be closed.
