### ISSUE TITLE
Line of Best Fit in Scatter Plots

### ISSUE THREAD

**Issue by PatrykNjoroge** [africanmathsinitiative/R-Instat#3018]
We were creating a scatter plot while writing video scripts and this got me thinking, should there be an option to draw a line of best fit in R-Instat?

**Comment by dannyparsons** [comment]
I think this can be done by simply adding a `geom_smooth()` layer to the plot. We should definitely have this geom in our geom list @maxwellfundi can you add this as a geom?

Then the next question, should we have this extra geom as an option on the scatter plot dialog? Is it a common enough option? @rdstern

**Comment by volloholic** [comment]
@maxwellfundi can you add a checkbox for `geom_smooth()` on the scatter dialog?

**Comment by maxwellfundi** [comment]
Done
