### ISSUE TITLE
Factors in R-Instat updated

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3031]
I am excited by the new facilities in R-Instat that will allow:
1) What I call "Levels", i.e. numbers as well as labels for a factor.
2) Intelligently transform between text, factor and numeric without losing information on either levels or labels.
I will be bug-hunting and will report in comments below.  Meanwhile I have a few items - not for the forthcoming release - but that could usefully be discussed while you are all together.
1) The Factor > Levels/Labels dialogue needs to be "enhanced" by adding a further column.  There is a column to edit the combined levels/labels.  Now there needs to be one column for the levels, i.e. the numbers (e.g. 0,1, or 1,2,3,8,9) and another column for the corresponding labels. 
2) The Factor > Reorder Levels could usefully be enhanced for factors with many levels.  The simplest (to me would be to be able to make it the same order as the rows in a corresponding factor data frame.  There might be a number of steps before this can be implemented.  As an example my factor could be (Climatic) Station and I want the order to be latitude.  The latitude is stored in the factor data frame.  It could (of course) become the levels of the factor.
3) In the column metadata the label display is tricky if the factors have many levels.  I wonder what should be done about that?  There is nothing that can be done with that field, so I suggest there is a "..." with a maximum width for that field. (David doesn't like the "..." but agrees that the width of that field should be limited.)

**Comment by rdstern** [comment]
I took the Dodoma data:
1. The obvious factor column was the month.  I made that into a factor from character. etc.  I fiddled with this column and it behaved well.  Character or numeric it did what I wanted.  The metadata showed the labels were there, but of course in alphabetical order.  So far so good.
2. I used the Factor > Reorder Levels (so Jan =1, Feb = 2, etc)  and I think that has worked.  But the labels are no longer in the labels metadata.  Shouldn't they be?
3. I made the year column - numeric - into a factor.  It now said it had labels with 1935 = 1935 as the first label - which I know!  If I make it back to numeric it keeps those labels!  All looks very odd.  (While it is a factor I would have been happy with 1 = 1935... as being informative.  With numeric to factor do we need labels?  I did the same with the rainfall column.
![image](https://cloud.githubusercontent.com/assets/11226469/25821923/cce96e30-342e-11e7-99d6-a4c686353361.png)

**Comment by rdstern** [comment]
1. In the survey data I made Fert into an ordered factor.  It seemed to have no labels.
2. I added labels from 0 = None, etc.  It seemed to add the labels, but they did not appear in the metadata.
3. I made it into a text and it kept the labels as the text.
4. I now made it numeric and it now added labels, but coded 1 to 7 in alphabetical order.  I appear to have lost the original numerical values.
5. This perhaps not surprising, but it would be good to be able to add labels to the original levels and keep them in the order if possible.
![image](https://cloud.githubusercontent.com/assets/11226469/25825430/e4c16dda-343a-11e7-92de-a75cd239e44d.png)

**Comment by rdstern** [comment]
Found the bug we saw when looking at factors together.
With the survey data from the Intro guide in the library.
The factor-type columns start as character data.
a) Made it into a factor.  Works fine (as before), but nothing appears on the labels in the metadata.  Not a great problem, but quite nice if it did, because it comes later.
b) Made it numeric.  This gives the numbers 1, 2, 3 and also puts the numbers and texts as the labels.
c) Made it character again.  Now the texts appear.  I am now sort of full circle.
d) made it factor again and now all is NA!

Tried some other combinations and they seem OK so far, i.e. 
a) Convert village to factor
b) Back to character.  All still OK - nothin in the labels metadata.
c) Back to factor again - still all OK.
d) Made numeric and fine.  Now the labels appear.
e) back to factor - still labels there and factor is OK.
f) Now made character and then back to factor - that's where the problem is.  All now NA.
g) Also tried that with a third column, just character, straight to numeric and the labels appear.  Back to character is OK, but then to factor 9for the first time) all is NA.

**Comment by dannyparsons** [comment]
Fixed so far (not yet merged just as notes):

- renaming levels, adding new levels, reordering levels - all retain correct labels
- adding a new level to a factor gives a default numeric value (max of current values + 1) for the label

> I made the year column - numeric - into a factor. It now said it had labels with 1935 = 1935 as the first label - which I know! If I make it back to numeric it keeps those labels! All looks very odd. (While it is a factor I would have been happy with 1 = 1935... as being informative. With numeric to factor do we need labels? I did the same with the rainfall column.

I have implemented something to improve this, I think best for you to test and see instead of explaining the details here.

**Comment by dannyparsons** [comment]
Fixed issue converting character -> factor correctly.

**Comment by dannyparsons** [comment]
The issues of converting between types should now be solved. There is still work to do making the labels editable through dialogs.
