### ISSUE TITLE
Regular Sequence

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3033]
Two bugs to fix here, which are slightly linked.

1. This will run if I have no data frame. We need to add to the testOK to not run if the Data frame is empty

2. If I clear the data frame in the receiver (so that it's blank) then press OK, it runs still
If I then re-open the dialog, put a dataframe back in the selector and then try to run it, it runs the code but not the AssignTo and doesn't add the column.

@AlexSananka I believe you worked on this dialog before. Can you fix these problems for tomorrow's release?

**Comment by AlexSananka** [comment]
Yes I am going to try and solve this for today's release.

**Comment by AlexSananka** [comment]
@lilyclements  Thanks for spotting this
This seems to be a general  issue with the ucrDataFrame control and it affects all dialogs using this control,This needs a careful thought and discussion before its implementation since we need to be confirming what is typed in the control to be one of the available data frames. also, we need to decide whether we should be allowing users to be typing the control  and whether to use a user control in place of cboAvailableDataframes control.
We have discuss this with @dannyparsons  and @Lunalo.

You will realize that when you do not have any data frame in your selector then your TestOk is disabled which I think it is working appropriately.

**Comment by lilyclements** [comment]
The TestOK is not always disabled - only sometimes. A quick check of the code and I saw

```
If ucrNewColumnName.IsComplete Then
            If rdoNumeric.Checked Then
                If ucrInputFrom.GetText <> "" AndAlso ucrInputTo.GetText <> "" AndAlso ucrInputInStepsOf.GetText <> "" AndAlso ucrNudRepeatValues.GetText <> "" AndAlso ucrSelectDataFrameRegularSequence.cboAvailableDataFrames.Text <> "" Then
....
End If
```

There is nothing to disable OK if the `ucrNewColumnName `is not complete. This is why my OK was enabled for me; I can have my New Column Name empty and nothing in the data frame and it runs fine.

**Comment by AlexSananka** [comment]
I agree with you this is really a different and tiny issue which we noticed with @Lunalo  but maybe I didn't say I am fixing it.

Ok I can fix this now.I only need an else and that's it?

**Comment by lilyclements** [comment]
Yep that only needs an else to be fixed.
I think if that's the only thing we can fix for now then that's it!

**Comment by AlexSananka** [comment]
Should this be closed?

**Comment by lilyclements** [comment]
I think this still has some issues noted in it that we need to fix at a later date. I'll check tomorrow if these problems are covered in another issue

**Comment by AlexSananka** [comment]
Ok great but I think it has the same issue as #3034.
Maybe you can chech tomorrow anyway.

**Comment by lilyclements** [comment]
Is point 2.) fixed that I noted at the top of this issue?

**Comment by AlexSananka** [comment]
yes I think point 2 is fixed.

**Comment by lilyclements** [comment]
I've just updated my branch and I'm running the new Regular Sequence. The OK is still enabled when I remove the data frame name
Could you look into the code to what the issue is here?

![image](https://cloud.githubusercontent.com/assets/21180424/25891277/5b42e938-3568-11e7-9ea6-abedea24309d.png)

**Comment by AlexSananka** [comment]
But I think this is what is explained up there on my second comment,try re open the dialog and see what happens.

This is an issue with the control if am not wrong,

**Comment by lilyclements** [comment]
Yes of course, I forgot this was an issue in the control! Thanks for clarifying. I'll close this now, thank you for fixing these problems.
