### ISSUE TITLE
Data Frame Selector Bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3034]
Two (linked) crashes but different bugs:

These apply to dialogs which only have a data frame name selector - e.g. Random Samples or Regular Sequence.

1. If I delete a dataframe, (and that was the last data frame I used), and then I open a dialog where it has only the data frame name selector, then it crashes.

2. If I accidentally type in the "Data Frame Name Selector" part, then OK is enabled. (lets say I had "Survey" and I changed it to "Surveyj" without realising)
(In other dialogs, OK is not enabled here since I haven't any variables to go with that made up data set. In these instances with a data frame name selector only, it is enabled)
Then I press OK because I haven't realised I accidentally wrote in the data frame selector
And I get an error that "surveyj" does not exist.
I then re-open my dialog (or any dialog) and it crashes because it cannot find "surveyj"

Is it possible to have a combo box where we cannot input new values but instead can only choose from current options? I feel that is appropriate for (2) but not sure how do-able it is.

**Comment by volloholic** [comment]
The data frame selector is now non editable. Does 1. still cause a crash?

**Comment by lilyclements** [comment]
This is fixed, thanks
