### ISSUE TITLE
Correlations

### ISSUE THREAD

**Issue by PatrykNjoroge** [africanmathsinitiative/R-Instat#3039]
I was looking at the Correlations dialog under Multivariate sub-menu on the Describe Menu and I found something confusing. Even though a bivariate correlation qualifies to be a multi variate, I think it would be better to rename the correlations dialog into Bivariate Correlation because it is specifically dealing with relationships between two variables.

**Comment by shadrackkibet** [comment]
@dannyparsons can this be closed or i change this in an open pullrequest i am working on?.

**Comment by dannyparsons** [comment]
Yes this dialog has now been updated.. The bivariate/multivariate could be on the radio buttons in the dialog. Because we have two columns vs multiple columns option so in general it is multivariate but one of the dialog options in bivariate.
