### ISSUE TITLE
R link not using correct version of R

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3047]
Something we need to be aware of. We discovered that @Lunalo's R-Instat was using R 3.3.0 even though he had R 3.4.0 installed and working through RStudio.
When we uninstalled R 3.3.0 then R-Instat used R 3.4.0. Very strange since the R link should use the most recent version of R.

@Lunalo what happened when you reinstalled R 3.3.0?

**Comment by volloholic** [comment]
@Lunalo  update?

**Comment by dannyparsons** [comment]
We discovered that R edits the registry each time you install R so if you install an older version later then that is the one that will be detected by the RLink (and RStudio). This should be fairly uncommon, but its worth knowing this in case it comes up and it could go in the installation documentation somewhere.
