### ISSUE TITLE
Excel files

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3058]
Is it just my version, but I can't now read Excel files.
The problem seems to be both xlsxs and xls types.  

csv, Stata, rds seem ok

**Comment by lilyclements** [comment]
I checked and I'm having this issue too. "OK" is disabled if I try to import an xls/xlsx file

**Comment by dannyparsons** [comment]
Check now I have tried to fix it.

**Comment by lilyclements** [comment]
Great (or should I say, **Excel**lent...) its working for me now. Thanks.
