### ISSUE TITLE
Busy indicator?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3072]
We will have to be able to break out of commands as has been noticed earlier.
It would also be good to have a busy indicator when a command is working.
I have just turned a column into a factor and it took over 30 seconds on my computer.

I am not complaining, because there were over 3 million rows!  But it would be good to know when to be patient!

**Comment by dannyparsons** [comment]
Links to #2882 and as well need to disable the grid and other features when commands are run outside of dialogs otherwise users can edit while code is running - a potential big mess.
