### ISSUE TITLE
Three-Variable Modelling Dialogue

### ISSUE THREAD

**Issue by jkmusyoka** [africanmathsinitiative/R-Instat#3088]
I could not get to use the above-mentioned dialogue to fit a model with two predictors. After specifying both the first and second predictors, the dialogue fitted the second predictor only ignoring the first. I have tried this with several datasets including the ExperimentalSurveyData.RDS located in the Instat collection library. I was trying to fit village and variety to the yield.

**Comment by dannyparsons** [comment]
Urgent bug to fix in the next day or two @africanmathsinitiative/instat

**Comment by rdstern** [comment]
While waiting, it would be good to check whether the model can alternatively be fitted now using **Model > General > Fit Model**.
And, in general, when we improve the Two Variable, Three Variable and Four Variable dialogues they should all also be possible with the Model > General > Fit Model dialogue.  It will just be that xcompleting the dialogue will be easier using the special cases.  Hence logical to use them in teaching - including e-sms.

**Comment by jkmusyoka** [comment]
The Model > General > Fit Model can be used to fit the model but returns quite complicated results for my students i.e. analysis of deviance. I was thinking that the general dialogue was for fitting glms???

**Comment by volloholic** [comment]
All the dialogues (should and I presume do) fit both LMs and GLMs depending on options such as the distribution you choose for the error term.

**Comment by Lunalo** [comment]
@volloholic 

I don't understand your last part of the statement  "distribution you choose for the error term"  when you link it to GLMs

I would like to get more understanding on this.

**Comment by dannyparsons** [comment]
@Lunalo There's lots to do on the modelling menu still. Would you like to become more involved in this? with @lilyclements and @stevenndungu This could help improve your understanding of modelling generally. Of course there is still your main priority work on the Prepare menu.

**Comment by Lunalo** [comment]
@dannyparsons 

This will be a great opportunity to learn more. Actually, we have been discussing with @stevenndungu  on the same. I will now be happy to  get actively involved .
