### ISSUE TITLE
Random subset of a factor column

### ISSUE THREAD

**Issue by jkmusyoka** [africanmathsinitiative/R-Instat#3089]
I have this dataset in eSMS which contains a variety column with 10000 cases. The column is a factor. I want to select 4 random samples of 250 each for some exercise with my students. I thought the random subset was build for such task but I could not use it because in the dialogue, the variety column does not appear in the Variables box for selection. I think it is because it is of the factor type. Trying the same task with a numeric column seems to work well. Is there a bug there or am I using the wrong dialogue?

**Comment by dannyparsons** [comment]
I believe this command should work on factors just as well as numeric columns. If it does then we should allows factors in the selector 
@africanmathsinitiative/instat could someone check this urgently and report back?

**Comment by stevenndungu** [comment]
Yest, it works with factors as well.

**Comment by jkmusyoka** [comment]
Which version? I am using version 0.2.5.

**Comment by stevenndungu** [comment]
Sorry, I meant the dialogue can work with factors as well, but it was restricted to numeric columns only as you pointed out. 

I have set it now to allow all columns in my branch `RandomSubsets`

**Comment by stevenndungu** [comment]
The changes are on pull request #3090.

**Comment by dannyparsons** [comment]
@jkmusyoka do you still have access to the development version through Visual Studio? This may be useful for you to see the latest version before a new installer is released.
