### ISSUE TITLE
Case study from Kenya - climatic

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3095]
[WKenya_StationInfo.zip](https://github.com/africanmathsinitiative/R-Instat/files/1008263/WKenya_StationInfo.zip)

Here are the data from James Musyoka for the rainfall stations.  

There also should be some stations with multiple elements.  It would be very good to get those as well.  We have some stations (particularly Dodoma) with rain, maxtemp, mintemp and sun hours.  It would be good to get at least one example with both multiple stations and multiple elements, and with more elements than these four.

**Comment by dannyparsons** [comment]
I don't believe this data is in the R-Instat library? Could it be?

**Comment by volloholic** [comment]
@maxwellfundi can you add this data set to the library?

@jkmusyoka @stevekogo what's the status of this data through CLIMSOFT?

**Comment by stevekogo** [comment]
I already loaded the rainfall data to climsoft. I will add the data for other elements then create a sql file. This will be done by tomorrow morning

**Comment by maxwellfundi** [comment]
Adding this data to the library Climatic folder
