### ISSUE TITLE
One Variable Describe bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3111]
@africanmathsinitiative/developers 
On One Variable Describe there is a bug with the linking. I believe @stevekogo you had this bug before on a similar dialog (Two Variable Describe perhaps?) and I'm not sure how you fixed it.

So, if you
1. Open One Variable Describe
2. Put a couple of variables in the receiver
3. Check "Customise"
4. Add more variables to the receiver
5. Uncheck "Customise"

Then when you uncheck it, you can see the variables in the receiver reduces to the amount of variables that were in the receiver before it was checked.
We want the variables in the receiver to stay the same when it is checked and unchecked.

**Comment by dannyparsons** [comment]
I believe this be solved by having the receiver linked to both functions so that the receiver contents in both functions is always in sync. It should be a simple fix to add additional parameters to the receiver.

**Comment by AlexSananka** [comment]
I am going to fix this.

**Comment by AlexSananka** [comment]
Can this be closed?
