### ISSUE TITLE
Summaries r-code, 10000 bytes

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3115]
@dannyparsons Occasionally in the new system I get the following bug:

> variable names are limited to 10000 bytes

The two situations I have got this is as follows:

1. Damango and Georgetown datasets. Perhaps other Climatic too
Go to the New Summary Tables dialog
In the factors receiver, input Year
In the columns to summarise receiver, input Rain
Select the "Mean" summary statistic
Check to include margins
If you click OK you get the error described above.

1. Georgetown dataset (which I can send to you)
Go to the Column Stats dialog
In the Variates receiver, input Rainfall
In the Factors receiver, input Month
In the summaries sub, check "Mean"
Then if you click OK, you get the error mentioned above.

**Comment by dannyparsons** [comment]
Thanks for this. 
Just to confirm, this also gives a bug if run in R? Do you have an output of R code that causes this?

**Comment by lilyclements** [comment]
Bug occurs if you run in R or R-Instat.

So, if I use Dodoma from the R-Instat library this is the error/R-Code running I get


> Error in summarise_impl(.data, dots) : 
>   variable names are limited to 10000 bytes
> 
> The error occurred in attempting to run the following R command(s):
> 
> summary_table <- InstatDataObject$summary_table(data_name="Dodoma", columns_to_summarise="Rain", summaries=c("summary_mean"), factors="Year", store_results=FALSE, include_margins=TRUE, signif_fig=2, na_display="", rnames=FALSE)
>

**Comment by lilyclements** [comment]
Just to add in @stevenndungu's bug here:

![image](https://cloud.githubusercontent.com/assets/21180424/26455131/2f049cd6-4161-11e7-9872-66dfd80980fa.png)

I believe one reason why this is occurring because "summary_mean" is checked.

It looks like Steven ran this on the Column Stats dialog from the code

**Comment by dannyparsons** [comment]
@lilyclements @stevenndungu I've followed all your examples and can't get this bug now. Can you check this again?

**Comment by lilyclements** [comment]
I'm not able to get this issue anymore. @stevenndungu how about you?

**Comment by stevenndungu** [comment]
Confirmed! No error now. Working perfectly well.Great!
