### ISSUE TITLE
Bug with Column Summaries

### ISSUE THREAD

**Issue by ZIRANA11** [africanmathsinitiative/R-Instat#3117]
i selected two variables to be summarized but on checking the summaries i wanted, this error came up.

![image](https://cloud.githubusercontent.com/assets/28622260/26440002/16ade5b2-4133-11e7-9d22-2d18a3f29e1a.png)

**Comment by lilyclements** [comment]
Yep this has been fixed in the new system, thanks!

**Comment by maxwellfundi** [comment]
@ZIRANA11  well done for finding this bug and reporting it. This is useful to make the software better.

**Comment by dannyparsons** [comment]
Yes please continue to find bugs at @ZIRANA11 it is very helpful. But before you post a bug, first search the current issues to see if it's already been reported. This isn't easy because there's so many! but it's good to have a quick check before posting.

**Comment by maxwellfundi** [comment]
Now that this is fixed, I t could be closed.

**Comment by dannyparsons** [comment]
Well the pull request isn't merged yet, but once that is it can.

**Comment by maxwellfundi** [comment]
Okay, great. I hope @lilyclements will reference this issue so that it automatically closes.

**Comment by dannyparsons** [comment]
It's already been sent, but merged now.
