### ISSUE TITLE
dlgOneVarUseModel - enhancement

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3120]
We are discussing dlgOneVarUseModel in #3110 and I had a point which to avoid confusion through multiple conversations occurring in that branch, I thought would be better in an issue

The initial issue for this dialog is written up in #1763, this is now closed otherwise I'd add to that. Additionally, a lot of the conversation from there is not relevant/a problem anymore

To save reading all of the issue in #1763 - "Insert Values" is meant to be a combo box with some suggestions already in it. Alternatively, the user can input their own values. So, suggestions in the combo box would be
0.25, 0.5, 0.75
0.1,...0.9

Then the user can input values too, separated by comma, for quantiles to read in.
Say the user uses the first example, the code is `probs=c(0.25, 0.5, 0.75)`.

Since this is quantiles, the user should not input values below 0 or above 1.

If you do, an R-error comes up saying:

> Warning message:
> In qnorm(p = c(0, 0.5, 1.1), mean = 10.6944444444444, sd = 7.52336894262893) :
>   NaNs produced

My question here is, do we have a way to limit values put in a ucrInput?
Or, would we say that the user should know to input values between 0 and 1 so if they don't and as long as the program doesn't crash then it's okay?
My issue is the error doesn't say "`probs` values out of bounds. Must be between 0 and 1" so the user may not realise why they are getting the error?

@AlexSananka @rdstern @dannyparsons

**Comment by AlexSananka** [comment]
@lilyclements I agree with you the error message should be more informative so that the user will understand what exactly is needed or what they are supposed to do so that they can continue.I think Lily's suggestion message makes sense.

**Comment by AlexSananka** [comment]
On the merging part of the subdialogs I think we can make them all tabs and this will avoid the subdialog being too long.We again do not want lot's of subdialogs in one dialog if it can be made one.I think merging them shouldn't affect the coding part of the dialog.

**Comment by rdstern** [comment]
I am enjoying this discussion.  One further issue is that some sub-dialogues are used in multiple places, while others are used just once.  So, for example, the looking at residuals is needed all over the place in our model-fitting dialogues, while options on prediction are only needed  in the Use Model dialogue.  

I can still see an argument that a common sub-dialogue could become a tab in another dialogue - but that may also become more complicated for users. 

So I do think we will sometimes have multiple buttons and corresponding sub-dialogues.  On the other hand, I also do like the idea that the sub-dialogues can be tabbed if we need.

**Comment by AlexSananka** [comment]
This works needs to continue,It will be in appropriate to change subdialogs shared by lot's of dialogs  since some options in the subdialog will lose meaning.I don't think this specific dialog is being used in any other dialog.If doing this will make the dialog 'not easy to use' then it's good to maintain as it is.

Anyway we need to make a decision since this work needs to continue.

**Comment by AlexSananka** [comment]
If we're to merge the two sdg's then it will be good of course to suggest a different label for the sub dialog?but just before then let's here @lilyclements suggestions on whether to merge them or not.

**Comment by lilyclements** [comment]
I think we should make it one sub dialog.

The plot dialog adds parameters to the `quantile` function and the bootstrap dialog adds parameters to the `bootdist` function. 
On the Plot dialog, as just mentioned, there is one option under "plots" which is only enabled when bootstrapping is checked
On the bootstrap dialog, there is one option (CI's) which does not affect the `bootdist` function, but instead affects the `quantile` function on the other sub. I always felt this was a little out of place.

Having it as one dialog could be nice since it will reduce this overlap between the two subs. 

So to conclude, we can have one sub dialog and it can have three tabs:
Plot, which can remain as radio buttons for options for reasons I'll explain below.
Quantile
Bootstrap

And the Bootstrap tab can be hidden or disabled when Bootstrapping is not checked.


As for the plot options - I like the idea of the plot option being a combo box, however, one of those radio buttons are only visible when bootstrapping is checked. So, we'd have to make it that that can't be an option unless it's checked. I think for this reason it works better as radio buttons, especially if we're going to combine everything to one sub.

**Comment by AlexSananka** [comment]
@lilyclements can this be closed now?

**Comment by lilyclements** [comment]
The initial question of this issue was "My question here is, do we have a way to limit values put in a ucrInput?"
And if not, then how can we combat this issue that the user can input any (numerical) value and get this error that isn't clear what the problem is?

**Comment by dannyparsons** [comment]
If you check the options when setting validation type as numeric there will be options for max and min values.

**Comment by lilyclements** [comment]
Excellent! @AlexSananka I believe you're on this dialog at the moment. Can you sort this?

**Comment by lilyclements** [comment]
@AlexSananka I believe the line to add to the sub is
`        ucrInputQuantiles.SetValidationTypeAsNumeric(dcmMin:=0, dcmMax:=1)`

**Comment by AlexSananka** [comment]
at least this makes sense and more informative pop up when the user inputs values out of range.

**Comment by lilyclements** [comment]
So, I think on ucrInput we need to change it to something along the lines of

`    Public Sub SetValidationTypeAsNumericList(Optional bNewAllowInf As Boolean = False, Optional MinValue As Integer = Integer.MinValue, Optional MaxValue As Integer = Integer.MaxValue)`?

Then on the sub we can set the min and max values as 0 and 1.

**Comment by AlexSananka** [comment]
Can I also add the option  for `SetMinMax`?

**Comment by AlexSananka** [comment]
But wait,why don't you think this    `ucrInputQuantiles.SetValidationTypeAsNumeric(dcmMin:=0, dcmMax:=1)`
is what we need?

**Comment by lilyclements** [comment]
We can't use that because
1. This is for TypeAsNumeric not NumericList. We want a list as it's numbers separated by a comma
2. I realised dcm is short for decimal. We don't want to limit the decimal places at all, we want to limit the minimum and maximum values.

**Comment by AlexSananka** [comment]
For a list I think you can only set the length of the list but setting the maximum value is something different.If you want to set the value then you might have to do it a the `SetValidationTypeAsNumeric` sub.

**Comment by dannyparsons** [comment]
@AlexSananka this should be simple, either your control is for entering a list or for entering a single number. If that's clear it should be clear which one of `SetValidationTypeAsNumericList` or `SetValidationTypeAsNumeric` to use.

**Comment by AlexSananka** [comment]
This dialog is in good shape now except a few issues which we've discussed with @lilyclements ;
First is the fact that it doesn't produce a graph when you don't open the `sdg` and yet the default is the multi plot so we should have multi plots,I do not know if this reason is good enough to make the` rdoNo Plot `a default,but I we should find a good way to implement the option for no plot since that's what is causing this problem because I have to run the script if` sdg.rdo `is checked.

Second is On setting the defaults for the `ucrinput` am still having some developer errors which I think we can discuss this with @dannyparsons if there are conditions I should give the `ucrInput` to behave as required.

**Comment by volloholic** [comment]
@AlexSananka status of this?

**Comment by AlexSananka** [comment]
We discussed this with @dannyparsons  and he was to fix the issue on setting the defaults for the ucrinput.
maybe he can confirm this.

**Comment by AlexSananka** [comment]
This can only be closed if we have the defaults for the ucrInput

**Comment by maxwellfundi** [comment]
@dannyparsons  can this now be closed?

**Comment by dannyparsons** [comment]
@AlexSananka resolved?

**Comment by AlexSananka** [comment]
let me  have a quick check
