### ISSUE TITLE
Column metadata resetting when changing column

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3122]
This is a bug that's likely across dialogs. When a column is changed, sometimes the column metadata is lost and reset. This has become obvious to me when using labels for factor columns. I've noticed this on factor dialog but it will be an issue in others. It should be a simple fix but we need to identify where it's happening.

As an example, take a numeric column, change the significant figures value in the column metadata grid to some number, convert the column to, say numeric, and the significant figures value will be reset to the default. (I'm about to fix this one) We need to keep the column metadata when we make changes otherwise it's not useful.

Can everyone test dialogs and look out for this, and report here the issues found? @africanmathsinitiative/instat 

Thanks

**Comment by volloholic** [comment]
@africanmathsinitiative/developers can everyone check this and report any issues.

**Comment by volloholic** [comment]
@rdstern Can you check this

**Comment by dannyparsons** [comment]
@rdstern have you noticed this issue on any dialogs still?

**Comment by dannyparsons** [comment]
Doesn't appear to be an issue now, but we should continue to check on this through testing.
