### ISSUE TITLE
Adding text to remove unused levels dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3125]
I think we've discussed before that this dialog is a bit confusing because it's not clear what you have to "do" apart from choosing a factor. It just removed all the unused (empty) levels so there's no other selection to make.

To improve this I suggest adding a label or text box under the factor grid which will either say "no unused levels to remove" or "x unused levels will be removed". The number `x` can be calculated by `sum(table(col) == 0)` where `col` is your factor column, it should clear why if you try this in R.

@africanmathsinitiative/developers should be a fairly straightforward task for someone.

**Comment by AlexSananka** [comment]
I think this should be closed
