### ISSUE TITLE
Combo box types

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3137]
@africanmathsinitiative/developers 
We now have 2 or 3 different combo box types for use on dialogs. (Thanks @shadrackkibet for bringing some of these suggestions, and I think @Lunalo also brought this up previously.)

1. Non editable - the user cannot type into the combo box and can only choose values from the list
Set by using `.SetDropDownStyleAsNonEditable()`
2. Editable and can type anything - the user can type into the combo box. There are values in the drop down, but the user is also allowed to type something other than one of these.
Set by using `.SetDropDownStyleAsEditable(bAdditionsAllowed:=True)`
3. Editable but restricted - the user can type into the combo box. There are values in the drop down and they user is only allowed to type if they type something from the drop down list.
Set by using `.SetDropDownStyleAsEditable(bAdditionsAllowed:=False)`

This can be accessed once https://github.com/africanmathsinitiative/R-Instat/pull/3053 is merged.
I say 2 or 3 because type 3. isn't implemented yet, but could be soon.

We need to be consistent on how we use these types. Type 1. looks very nice and easy to use (you can't choose a wrong value) - but it has less functionality of course. I suggest that type 1. is only used when there is almost no value to be gained from allowing the user to type. The example on Shadrack's String Distance dialog is an excellent one. There are 10 drop down items for the method, for example: "Jaccard Distance between q-Gram Profiles" and "Cosine Distance between q-Gram Profiles". There is no way the user will know these items already and would want to type in their favourite method. So we don't lose anything by making it non editable - and we simplify the dialog and reduce potential for error.

A good example of type 2. would be the combo box in ucrSave. If you want to overwrite a column you could choose it from the drop down list. But you could have hundreds of columns and searching it on the drop down would take time, it's nice you can just type it in because you know it. Of course it doesn't have to be an existing column so you can also type anything.

A good example of type 3. would be the data frame selector. We would like users to be able to type the name of the data frame if they know it, but of course they can only type one of the existing data frames, so it is restricted.

I think these are good general guidelines of which ones to use, but we can discuss if it's not obvious for a particular dialog.

Note that 2. is the default so most dialogs won't need a change.

Note that 3. is not yet implemented as it links to the validation. If we get short on time to implement option 3, would could make anything we wanted as type 3., type 1. temporarily.

**Comment by lilyclements** [comment]
Excellent, sounds good. Is it possible to implement Type 1 on the ucrDataFrameSelector? I assume that is the correct type for the selector unless you can think of otherwise?

**Comment by dannyparsons** [comment]
If we decide not to implement type 3 in the near future then type 1 is good option yes.
There's an added complication that I don't the data frame selector has an input combo box yet so that needs careful updating, but it should be done very soon.
