### ISSUE TITLE
Consistent display of separator characters etc. in Text dialogs

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3138]
@africanmathsinitiative/developers 
I noticed that Text dialogs don't have consistent ways of displaying characters in combo boxes. For examples, I've seen "Space" vs "Space ( )", and "Underscore" vs "Underscore _" in different dialogs.

I'm happy with the second display in each case so we show the name of the symbol and the symbol itself. Unless there's disagreement, could this be changed to be implemented consistently throughout the Text dialogs?

**Comment by shadrackkibet** [comment]
I am working on this now.
