### ISSUE TITLE
Multivariate Dialogs

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3153]
@africanmathsinitiative/developers the Multivariate dialogs are waiting to be updated still. I've started work on the sub dialog for Canonical Analysis (CCA) since it's dialog is updated and merged but sub is not so has lost functionality.

We need to update:
- dlgCorrelations and it's sub dialog
- I think I have a branch with the updates for dlgPrincipalComponentsAnalysis. The sdg isn't yet complete. Someone can pull the branch and make changes to the sdg if they wanted to work on that. The sdg is not more complicated for that than the other two multivariate subs. I just worked on the CCA sub before this sub since CCA is more urgent.

**Comment by volloholic** [comment]
Status of this? Probably for 0.9 now.

**Comment by lilyclements** [comment]
I think we should aim to have this done for next Friday

**Comment by volloholic** [comment]
@shadrackkibet  is this done?

**Comment by shadrackkibet** [comment]
-dlgCorrelations and it's sub dialog is now ready.
-I am still working on sdgcanonical , i am in the middle updating.
-dlgCorrelations and it's sub dialog are in my list of TODO:
