### ISSUE TITLE
Frequencies/Levels and Labels bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3156]
So, this is a bug which gives me my levels in the frequency table twice.
Very generous of the software to give it to me twice, however, this is one time too many.

I open _survey_, and I convert **Village** to numeric
It gives the new levels automatically
Then I decide I no longer want it to be numeric so convert it back to a factor
Then I run the "One Way Frequencies" dialog for **Village**
It gives all my levels twice

![image](https://cloud.githubusercontent.com/assets/21180424/26724271/63d2fa0e-4790-11e7-97ff-9c48be2dc145.png)

**Comment by dannyparsons** [comment]
This is caused by a bug in sjPlot, I've put a temp fix in our code to remove labels when it's not numeric. We should report this to sjPlot people.
