### ISSUE TITLE
Display of column types in grid

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3159]
Our current way of displaying column types in the grid is not adequate because it is not visible unless column names are short. We need both a better solution that is quick to implement and a longer term solution.

The easiest is adding the type before the name of the column instead of after. Are there other quick alternatives? Colours in the headers doesn't seem possible yet in the grid.

We also want a code for ordered factors which current just display as factors.

**Comment by rdstern** [comment]
I am happy that we put the type before the name as a short-term solution.
Again short term, let's have (o) or (of) for ordered factor?
Can we have italic for factors?  If so, then we could consider having both factor types in italic, and leaving the label (f) etc at the end of the name.  The other types are reasonably clear, i.e. dates look like dates in a column, and texts ((usually) look like texts!

**Comment by dannyparsons** [comment]
We now have a different colour for factor column headers so its sufficient to keep the code at the end of the column name.
