### ISSUE TITLE
Resetting sub dialogs with tabs

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3179]
When a sub dialog opens with reset as True, we should reset the sub dialog to display the first tab
There could be other "non code" things to reset such as current receiver

This is now done for plots sub dialog. Could someone do this on all other sub dialogs with tabs?

**Comment by lilyclements** [comment]
In addition, is it possible to say on the one/two/three-way frequency dialogs that if Graph is checked then the tab automatically selected on the sub is the Graph tab?
If both or Tables are checked, then the Tables tab can be selected on the sub.

**Comment by dannyparsons** [comment]
yes that info could be passed through from the main dialog, good idea.

**Comment by AlexSananka** [comment]
Am happy to take up this task

**Comment by AlexSananka** [comment]
What about saying that that if Graph is checked then the tab for the table options is disabled and vise versa?

**Comment by dannyparsons** [comment]
No because the user may want to edit the table options on the sub dialog and then go back to the main dialog and check table. We generally don't want to disable things unless we have to. 
I think setting the default tab when opening is a good idea.

**Comment by AlexSananka** [comment]
This is also fixed,expect on sdgonevarcompare which am working on now

**Comment by dannyparsons** [comment]
Great reference to here and we will close when that is merged.

**Comment by volloholic** [comment]
@AlexSananka is this done? Can we close?

**Comment by AlexSananka** [comment]
This is done,the remaining subdialogs need to be updated which I don't think is possible for tomorrows version.
This can be closed.
