### ISSUE TITLE
Tools > Options > Output Window

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3188]
In preparing for Stats4SD I tried to turn off the commands and comments to the output window.

I can turn of the commands OK, but the comments keep coming!  I would like the option to turn them off.

If there is time (0.9 timeline) I would also like options on what menu items to display, in particular the climatic and procurement menus.

**Comment by dannyparsons** [comment]
The comments option in the sub dialog sets the **default** value for the comments check box in the sub dialog. It can still be checked or unchecked. 
If a dialog is reset the checkbox should be unchecked by default if the global option is unchecked. This is how I believe it should be working at the moment, but good to check, and also discuss if this behaviour should be different.
