### ISSUE TITLE
Developer Error in subdialogs with ucrInput Combobox Control

### ISSUE THREAD

**Issue by AlexSananka** [africanmathsinitiative/R-Instat#3194]
I was trying to use the current version of the software and when I used sub dialogs with the `ucrInput Combobox `and then go back to the main dialog and reset then try reopen the sub dialog I get the error
![image](https://cloud.githubusercontent.com/assets/25578150/26823320/e9fffaa0-4ab5-11e7-860f-982840fc5be0.png)

This was hapening in `sdgOnewayFrequencies`,`sdgtwowayFrequencies` and `sdgClimdexIndices` and probably some other unnoticed ones,but @dannyparsons recent changes have fixed the errors on the frequencies sub dialogs but the errors for` sdgclimdexIndices` still exist.I believe these are just the ones we have noticed.

@africanmathsinitiative/developers could someone else try this and see how this is happening and maybe someone could try fix it.
It's annoying to have such bugs in the most recent version.

**Comment by lilyclements** [comment]
So, this occured to me the other day on a different dialog. Have you changed the designer? A line automatically is coming in for ucrInput which if you comment it out, it fixes this problem.

**Comment by lilyclements** [comment]
It's this line here that caused the problem for me. Perhaps have a check if this is the same for you?
`        Me.ucrInputSeparator.AddQuotesIfUnrecognised = True
`

**Comment by AlexSananka** [comment]
I haven't changed the designer,I just updated my branch and run it.Maybe I can check if this line is adding itself but  am not sure.

Does this happen in all branches,I have tried switch between branches and the error still occurs.

**Comment by lilyclements** [comment]
Did you look at the designer for if these changes occurred? That's a problem i've been having on ucrInputs anyway. I just thought I'd check in case it were that!

**Comment by AlexSananka** [comment]
I finally found this line and commented out and unfortunately doesn't fix my problem.

try this in `sdgClimdexIndices`

**Comment by lilyclements** [comment]
If it doesn't fix the problem then uncomment it out. I'll have a look shortly in sdgClimdexIndices

**Comment by lilyclements** [comment]
How did Danny fix it on the frequencies subs? Why can't we apply the same method to fix it there to this climdex dialog?

**Comment by dannyparsons** [comment]
that was an accidental fix of something else which apparently fixed for frequencies, not sure why though. I can look into this later if needed.

**Comment by volloholic** [comment]
Is this still an issue on climdex?

**Comment by AlexSananka** [comment]
I fixed this on my branch I'll push it up

**Comment by dannyparsons** [comment]
Thanks, please refer to this when you do so this can be closed.

**Comment by AlexSananka** [comment]
I have now fixed the issue of developer errors on climdex via #3318

once that is merged then this can be closed.
