### ISSUE TITLE
instat_object packages to add

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3195]
The following are packages to add to the instat_object_R6.

1. Line 1256, add `RMySQL`, so that we have: `...drv = RMySQL::MySQL())...`

2. Line 1257, add `getPass` so that we have: `getPass::getPass(...`

**Comment by dannyparsons** [comment]
If you look in the master currently, it's slightly different to this: https://github.com/africanmathsinitiative/R-Instat/blob/master/instat/static/InstatObject/R/instat_object_R6.R

**Comment by lilyclements** [comment]
Why is that line commented out for getPass?
It now gives my password in the right-hand-side of the code

**Comment by lilyclements** [comment]
And thanks, I've removed the netCDF one from my list as this is fixed. The other two need their packages though.

**Comment by lilyclements** [comment]
`is.Date` function needs the package `lubridate` to it.
This is in DataManipulationMethods.R, line 74 
And seven more times in data_object_R6
