### ISSUE TITLE
One Variable Frequencies - Core bug?

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3208]
One Variable Frequencies is calling auto.group = 2 when you first click OK even though this option is not checked.

If you then check and uncheck it, it runs as you would want it to.

I think this is a problem in the core control, partly because I can see no one has edited this dialog for the past few weeks, but yet this problem has only started occurring either today or yesterday.

**Comment by rdstern** [comment]
I think this was reported before, but the graph from this dialogue is supposed to be a ggplot2 object, but it gives the following error when using the View Graph dialogue:
---------------------------
Error running R command(s)
---------------------------
Error in UseMethod("ggplotly", p) : 
  no applicable method for 'ggplotly' applied to an object of class "c('gtable', 'gTree', 'grob', 'gDesc')"


The error occurred in attempting to run the following R command(s):

plotly::ggplotly(p=InstatDataObject$get_graphs(data_name="diamonds", graph_name="one_way_freq3"))
---------------------------
OK   
---------------------------

**Comment by dannyparsons** [comment]
I'm not getting the auto.group bug anymore. Are you still getting it?

**Comment by lilyclements** [comment]
I'm not getting it anymore either :)
