### ISSUE TITLE
Keys, links and comments dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3211]
1. I don't know whether the Comments dialogue is supposed to work yet.  When I try the menu item it throws me out of R-Instat.
2. I was able to make a key column.  But the next dialogue says View and Delete keys.  I wanted to view a key, but don't see what there is to view?  The view links does something.  Should we be able to "View" a key, or should we just call the dialogue "Delete keys"?
3. When I make the link I find I have to put the column without the key first.  then it finds the variable with the same name in the column with the key.  It doesn't seem to work the other way round.  Is that what we intend?  
4. These dialogues don't suggest names for the keys or links.  Most of the other dialogues seem to suggest defaults.  Is this what we want here?
5.  Now a more complicated question.  Once we have a key column and then set up a link, should there be a short report on how well the link works?  As an example could someone else also try the climatic datasets from James that have been added.  There the station names are the columns to link.  But I am noit sure if there are any errors in typing the names and hence in the links.  I asked David who suggested I can test by doing a simple summary, e.g. just the counts for example.  I will try this again when the summaries are working better.  They crashed for me, but then they also crashed on simpler data sets - so I can't test yet this way.  In the future will there be any other ways to evaluate how well the links are working?

**Comment by lilyclements** [comment]
I did some minor edits/bug fixes on these dialogs the other day which are waiting for @Lunalo to review before they are merged.
To 2: On "View and Delete Keys", it is no longer a checkbox. The option is now a radio button now between "View Key" and "Delete Key". This is because this is how it was in "View and Remove links"

There are other bugs on here that need to be fixed:
6. On When creating a key, the background colour goes green if it'll work and red if it won't work. However, on links, the text colour goes green or red. i think on Links, the background colour needs to go green or red, not the text colour

7. I was able to press OK on Links when the colour was red. OK should be disabled in that situation

**Comment by volloholic** [comment]
@Lunalo can you comment on points from Lily?

**Comment by Lunalo** [comment]
I agree for consistency we should be using bsckcolor . I will do the testing to confirm the all the issues mentioned are fixed . 

Thanks

**Comment by lilyclements** [comment]
@Lunalo how is this coming along?

**Comment by dannyparsons** [comment]
Colour issue now resolved. Still to be done/discussion (for 0.9):
> 3. When I make the link I find I have to put the column without the key first. then it finds the variable with the same name in the column with the key. It doesn't seem to work the other way round. Is that what we intend?
> 4. These dialogues don't suggest names for the keys or links. Most of the other dialogues seem to suggest defaults. Is this what we want here?
> 5. Now a more complicated question. Once we have a key column and then set up a link, should there be a short report on how well the link works? As an example could someone else also try the climatic datasets from James that have been added. There the station names are the columns to link. But I am noit sure if there are any errors in typing the names and hence in the links. I asked David who suggested I can test by doing a simple summary, e.g. just the counts for example. I will try this again when the summaries are working better. They crashed for me, but then they also crashed on simpler data sets - so I can't test yet this way. In the future will there be any other ways to evaluate how well the links are working?

**Comment by rdstern** [comment]
What is the plan for the Comments dialogue?  It looks nice.  Is it still intended for the forthcoming release?

**Comment by Lunalo** [comment]
@dannyparsons 

We had a discussion and you suggested to do a method. I am ready to implement it when the method is ready. We are also not sure of the package to use. Should it be done almost the same way column labels are implemented?

**Comment by dannyparsons** [comment]
This is largely working apart from comments which has it's own issue #2300
