### ISSUE TITLE
List of dialogs on prepare menu which are bugging 

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#3216]
Hi team, 

I have been testing functionality of all prepare menu dialogs .

I think we should now give priority to the following list of dialogs 

(View, Sort, Dummy variables, View R objects) These are breaking on load. I think there is a problem with how the panels are being set

Add comment: This might be due to lack of the r method. It can be dissabled for now 

Delete Rows or Columns : Data name cannot find its value in the control.

Recode and reorder : I have already fixed these.

Here are some tasks in case someone is looking for things to do.

Cheers.

**Comment by lilyclements** [comment]
I just found this issue on Sort too. I traced it back to when the line

        ucrPnlMissingValues.bAllowNonConditionValues = True

Was introduced. This line is causing an immediate crash on the Sort dialog.

**Comment by lilyclements** [comment]
As for Delete Rows or Columns: The `data_name `problem has been fixed.

**Comment by dannyparsons** [comment]
Thanks for this list John.

Has anyone discovered the cause of the `bAllowNonConditionValues` bug?

**Comment by lilyclements** [comment]
So on Sort it crashes to this line


```
        If objTemp IsNot Nothing Then
.....
        Else
            'If no value reset to a default value
            **dctRadioButtonValues.Keys(0).Checked = True**

```

I just checked and this was introduced two days ago.

the problem is starting to make sense. My vague attempt at a solution would be to make it:
```
        If objTemp IsNot Nothing Then
.....
        Else
            If bAllowNonConditionValues = False Then
                'If no value reset to a default value
                dctRadioButtonValues.Keys(0).Checked = True
            End If
        End If
```

But, this may be a terrible suggestion. I'm not so good at the ucr codes!

**Comment by dannyparsons** [comment]
Thanks for identifying the location! Without looking in the code, possibly there are no values in the dictionary, in which case there no index 0 and it will crash. Instead it should just get the first radio button in the panel or something. But I'll have to check in the code to see if this is actually the cause.

**Comment by dannyparsons** [comment]
I've tried to fix this. It doesn't give errors on mine now. Can you check?

Also when I went to Prepare > R Objects > View. It opened the View Data dialog. This isn't right? @Lunalo could you have a look at this too.

**Comment by Lunalo** [comment]
I am going to test it.

Thanks.
