### ISSUE TITLE
Importing from Library - xls

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3222]
A bug we've had for a while which needs to be fixed: Upon importing an xls file, often it only imports the first 9 lines. This is because it's reading in the "Preview" box and not the data set.

**Comment by dannyparsons** [comment]
I've attempted to fix this. I couldn't get the bug, but since you said it's only sometimes, can you check to see if you still get it?

**Comment by lilyclements** [comment]
So it is working better.
It now imports the nine lines and immediately reopens the dialog and when you press OK the second time it imports the rest. It's very quick but the user has to press OK twice. I'd say it's okay for 0.3.

**Comment by dannyparsons** [comment]
Strange - will check this again tomorrow.
