### ISSUE TITLE
Describe > General > Graphics

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3225]
Is working - great.
1. The help goes to the wrong place.  The help number is 420.
2. The help on the sub-dialogue goes to the top, i.e. it is unset.  I have added a sub-dialogue called Add/Edit, with number 569.
3. The Plot Options dialogue has number 136.
4. I started with a boxplot.  I assume there is a good reason why most of the other geoms have x before y, but boxplots has y before x.  Why can't everything have y before x?
5. I was able to make a sensible set of boxplots (survey data of course) and add a jitter to it.  It didn't break.  I made them green too!  Great.
6. Maybe not now, but what will I be able to save?  How can I save, not just the picture, but also the layers, and perhaps the separate layers if I were to get a good one?
7. I am sure there will be more, but so far so good!

**Comment by volloholic** [comment]
@maxwellfundi can you do this or check it is done?

**Comment by maxwellfundi** [comment]
Working on this now.

**Comment by maxwellfundi** [comment]
@rdstern The boxplot has y before x because y is the mandatory aesthetics for the boxplot. This can be changed easily when we decide which aesthetic should come before which. 
I can easily change all aesthetics to start with y easily. Its a copy paste job. Should that be needed for this release?

**Comment by rdstern** [comment]
Happy for others to comment too, particularly @volloholic .  I would like us to be consistent where possible, and y before x is my natural order, i.e. you start with what you are plotting and then think what it is being plotted against.

So my vote is to make y before x everywhere we have them both.

**Comment by dannyparsons** [comment]
That's how we have it on most main dialogs too. Do this for 0.9?

**Comment by rdstern** [comment]
Sounds good.  I have added that milestone.
