### ISSUE TITLE
Climdex bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3226]
So I believe the issue is occurring because of a core problem. If I run the contents of this dialog on a branch from a few days ago, it runs fine - although it does not give any output. I'm not sure if this is what we expect by just pressing OK on the dialog.
If I run the contents of this dialog on an updated branch, I get the following error:

> "no applicable method for 'as.PCICt' applied to an object of class "character""
> The error occurred in attempting to run the following R command(s):
> climdex_input <- climdex.pcic::climdexInput.raw(prec.dates=PCICt::as.PCICt(x=as.character(x=InstatDataObject$get_columns_from_data(data_name="Damango", col_name="Date1")), cal="gregorian"), prec=InstatDataObject$get_columns_from_data(data_name="Damango", col_name="Rain"))
> 

There are also clear issues in the setup for `SetRCodeForControls` which need to be addressed!

**Comment by dannyparsons** [comment]
@rdstern which milestone does this need to be working well for?

**Comment by rdstern** [comment]
It could be worth a quick look for 4.0 to see if it can be fixed very easily, but probably leave it to 4.1 (August)

**Comment by dannyparsons** [comment]
@lilyclements from looking at the code, can we get this in a working state for 0.4.1?

**Comment by lilyclements** [comment]
I've been making major changes to this dialog code to fix it up. There are changes required in the `add_climdex_indices` function in the `instat_object` before I can continue (I believe! Or at least until a bug hunt in this dialog becomes much easier!)

I want to flag up the sub dialog design.
Currently we have three tabs: Settings, Temperature and Prediction. Explaining this is easier for myself if I get a diagram up!
Settings contains Parameter options
Temperature and Prediction contains the 27 climdex functions between them for new columns for the user.

![explanations](https://user-images.githubusercontent.com/21180424/29122861-a7cbdf2c-7d0b-11e7-9563-6e9f49aa0eba.png)

In Settings there are options which apply to both the base function on the main dialog as well as some of the climdex functions on the sub dialog.
The options with a square box around them are parameters for functions in the Temperature or Predictions tab. 
I think the Settings tab should only contain the options which apply to the base function on the main dialog. Then the parameter options for the climdex functions can be moved next to their checkbox-function on the tabs.

This is for several reasons:
* Avoids switching between tabs
* The user may not know how to enable one of these options. Then they may not realise when they flip to another tab, check something, and come back again, why it's suddenly an option
* Similar to that, the user may check several options on the Temperature or Predictions tab, go back to the Settings tab, and not know what function the parameter is for.
* Or more specifically in cases: We have a "Prediction Exceeding Specified Amount" checkbox option on one tab and that "Specifed Amount" (Threshold) is back on the Settings tab. If the user is asking for a specified amount, they may not realise this is what the "threshold" nud is for.
* Another specific case: the "Maximum Spell Length Span Years" checkbox adds/removes a parameter for four climdex functions on another tab. This checkbox is default `FALSE` for two of the functions and default `TRUE` for two others. If it remains on this tab then the user is restricted to either selecting this to be `TRUE` for the four climdex functions or `FALSE`. (Unless we make it a combo box and add a "default" option).


Finally, In the Settings tab, there is an option of "annual" or "annual/monthly". This seems to add a parameter to the `add_climdex_indices` function in the `instat_object` where a parameter is `freq="annual"` or `freq="monthly"`. 
I really don't understand.
If I select `freq="monthly"` then all my checkbox climdex options are enabled so I can select whatever I want!
If I select `freq="annual"` then only half of my checkbox climdex options (the ones under a heading of "Annual") are enabled.
If all options can be enabled anyway on `freq="monthly"`, how come we have this `freq="annual"` distinction? I can't see a benefit to this.

If this is a mistake, and we're meant to only have Annual/Monthly options visible when Monthly is selected from the combobox, then I don't understand why this is a combo box and instead not two radio buttons along the top as then we'd always have 50% of climdex checkboxes disabled (Annual checkboxes disabled when Monthly is selected and vice versa)

**Comment by lilyclements** [comment]
Update: I just found for the `freq` option that this is a parameter for about 10 climdex functions.
Is this meant to be used on those climdex functions? Currently, it's being run in the `add_climdex_indices` function. I think using it for those climdex functions makes a lot more sense

**Comment by rdstern** [comment]
Some climdex indices can be used on either a monthly, or on an annual basis.  One example is diurnal temperature range (dtr).  Others can only be used on an annual basis, e.g. fd, gsl, id.
In practical terms this all starts with the daily data.  Suppose we have 30 years of data.  For all indices they can be summarised by year, i.e. to give annual summaries, i.e. columns of length 30.  Some can (alternatively) be summarised by year and month, i.e. by both "factors".  This gives the summaries at the year and month level, i.e. the resulting columns are of length 30*12 = 360 observations.
