### ISSUE TITLE
Describe > Three Variable Dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3245]
1. I think the first 3 menus should be disabled at this stage, i.e. Summarise and Graph
2. So, in Frequencies the table was OK, but the graph didn't work.  It gave an error.  I tried with the diamonds data set, using the 3 factors as an example.  What it said was:

And I assume the group_by is corrct in being before the dplyr?

Error running R command(s)

Error in group_by_(.data, .dots = lazyeval::lazy_dots(...), add = add) : 
  object 'clarity' not found

The error occurred in attempting to run the following R command(s):

dplyr::group_by(clarity) %>% dplyr::select(cut, color, clarity) %>% sjPlot::sjplot(fun="grpfrq", show.prc=TRUE, show.n=TRUE) %>% diamonds_temp
---------------------------
OK   
---------------------------

**Comment by dannyparsons** [comment]
This just seems to be the order of parameters, the `diamonds_temp` should go first and then it should work. This should be easy to fix.

**Comment by AlexSananka** [comment]
I am not experiencing this in my branch,Have this been fixed?

**Comment by AlexSananka** [comment]
This is the code running in my case 
```
diamonds_temp <- InstatDataObject$get_data_frame(data_name="diamonds")
diamonds_temp %>% dplyr::group_by(clarity) %>% dplyr::select(cut, color, clarity) %>% sjPlot::sjplot(fun="grpfrq", show.prc=TRUE, show.n=TRUE)
```

**Comment by rdstern** [comment]
I agree.  I don't get it now.  But there are still 2 curious features:
1. I had the Tools > Options set to graphics in a separate window.  Now this option on the 3-way frequencies runs for quite a time and then gives no graph.  It doesn't give an error though.
2. The setting of the new radio buttons isn't remembered.  It always seems to go back to the Tables option

**Comment by dannyparsons** [comment]
1. I think is a general issue.
2. I'm getting as well @AlexSananka can you check this?

**Comment by dannyparsons** [comment]
Also, it only displays one graph when it should display one for each group. I think this is a general issue with the output window as well.

**Comment by dannyparsons** [comment]
A solution to not display all graphs for each group is to combine them in one graph.
e.g.
```
diamonds_temp <- InstatDataObject$get_data_frame(data_name="diamonds")
graphs <- diamonds_temp %>% dplyr::group_by(clarity) %>% dplyr::select(cut, color, clarity) %>% sjPlot::sjplot(fun="grpfrq", show.prc=TRUE, show.n=TRUE)
gridExtra::grid.arrange(grobs = graphs)
```

@AlexSananka could you implement this?

**Comment by AlexSananka** [comment]
Yes I can implement this
