### ISSUE TITLE
Describe > General  > Menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3246]
A suggestion first for the menu.

Could we consider a swap (or two!).  I think this is simple - but important.

We currently have:
Column Summaries
Tabulation (not enabled)
Graphics
Frequency Tables 

1. Could we change the menu item Frequency Tables to **Use Summaries**
(We have Use Graphs elsewhere.  This isn't quite a parallel, but close.)
For now we move the existing dialogue Describe > Specific > Bar Chart from Summary there.  So its new name is Use Summaries.  For now it can have the same dialogue as the Bar Chart from Summary.  Later we may add more types of graph.  What we could do now if we wish is to add another button "**Table**", which is disabled for now.  In the future - I hope Version 0.9 - this will take the results from the Column Summaries dialogue - which the bar chart does now - and unstack - so we again have a table.

2. So my suggestion is that this menu becomes:
Column Summaries
Tabulation (not enabled)
Graphics
(line)
Use Summaries

Meanwhile the existing Frequency Tables moves to its duplicate position in Describe > Specific > Frequency.  If that is not the way we will be doing frequency tables in the future, i.e. Based on ftable and prop.table, then we should check whether there is still a place for both, or the ftable is no longer needed.

**Comment by lilyclements** [comment]
Happy to make these changes.
By "the existing frequency tables" I assume you mean the ftable dialog and not the summary-system frequencies dialog?

**Comment by lilyclements** [comment]
Does this also mean to remove "Bar chart from summary" from the specific sub menu options?

**Comment by rdstern** [comment]
1. I did mean the ftable one, because the one using the summary system doesn't seem to exist yet.  So the ftable one could add prop-teble and do what's needed (I think).  That could be instead of (or as well as) a dialogue using the summary system.  I am still not sure how the results will compare for the user?

2. My understanding is that Maseno folks found the bar chart from summary to be confusing.  So yes, I am suggesting the Specific dialogues are all assuming "primary" data.  And hence the bar chart from summary is a bit of an oddity there and so would move.

**Comment by lilyclements** [comment]
@rdstern I have made the changes and they have been merged. Can you take a check on an updated master branch and let me know if any further changes are needed?

**Comment by dannyparsons** [comment]
Has this been done now?

**Comment by lilyclements** [comment]
Yes and has been merged in. This can be closed
