### ISSUE TITLE
Describe > Specific > Summary Tables

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3247]
1. When going into this dialogue I first get a message:

instat

Developer error: no state of control ucrInputPageBy satisfies it's condition. Cannot determine how to set the control from the RCode. Modify control setup so that one state can satisfy its conditions.

I don't remember getting this message the first time I went in.  The dialogue then appears.  Perhaps this message is because of the errors I got later, see below:

2. The control for the number of column factors does not "remember".  It resets to 0 each time.  

3. I tried with the default (for diamonds) using cut and color as the factors and carat as the variable.  That was fine.  But when I change the statistics to ask for the minima it gave the error below:

Actually I got the error first by asking for 3 summaries, i.,e. mean, min and max and assumed it was because I was asking for multiple summaries.  Now I tried with just the min and it gives the error.  But now I can't summarise with the mean either.

**Error running R command(s)**

Error in self$apply_instat_calculation(combined_calc_sum) : 
  No data specified for calculation.

The error occurred in attempting to run the following R command(s):

last_table <- InstatDataObject$summary_table(data_name="diamonds", summaries=c(), store_results=FALSE, rnames=FALSE, n_column_factors=1, columns_to_summarise="carat", factors=c("cut","color"), as_html=FALSE, include_margins=TRUE, signif_fig=3)

InstatDataObject$add_table(data_name="diamonds", table=last_table, table_name="last_table")

InstatDataObject$get_tables(table_name="last_table", data_name="diamonds")

**OK**

**Comment by dannyparsons** [comment]
- Fixed developer error on reopen.
- Fixed number of column factors resetting on reopen.
- Bug with choosing summaries due to bug in sub dialog so was fixed by fixing it for column summaries
