### ISSUE TITLE
Describe > Frequencies dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3267]
1. The buttons at the top do not remember the previous settings.  They always reset to the Table option.  This applies to all 3 dialogues.
2. The One variable dialogue still gives the categories twice.  This is on the rmisc efc data where I used gender, employment, and level of education.
3. The 3-way graphs do not show all the labels.  I assume this may be us or a "feature" of the sjplot programming?

**Comment by volloholic** [comment]
2 is Done by Danny 1 is working except for both
