### ISSUE TITLE
Updating Models Dialogs

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#3279]
Hi team, 

Now that ucrDistributions is in a good shape we can start updating model dialogs.

To avoid members working on the same thing I would advise those involved  to be commenting on this issue with the dialog you are working on.

I will start with the show models.
@africanmathsinitiative/developers

**Comment by dannyparsons** [comment]
Thanks John. Also, comment on the Google Doc sheet so we know who is working on what.
