### ISSUE TITLE
Importing data frame crash.

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3282]
Trying to upload a data frame from excel. It worked for me initially, then I deleted the last row of the data frame and it crashed.

I re-opened R-Instat and tried importing the data frame again and it crashed again. Both times, it crashed to this:

![image](https://user-images.githubusercontent.com/21180424/27027286-b1b12b22-4f58-11e7-9777-4d37de5d9b30.png)

**Comment by dannyparsons** [comment]
Can you share the file?

**Comment by lilyclements** [comment]
[2015-UK-general-election-data-results-WEB.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/1067665/2015-UK-general-election-data-results-WEB.xlsx)

I was importing the sheet named "Results for analysis". I thought initially it could be the grid lines, but I'm not so sure now. Sometimes it imports fine but midway crashes to this line when doing grid-changes (e.g., converting to a factor, deleting a row)

**Comment by dannyparsons** [comment]
I get this crash as well. I believe this is our "wide" dataset issue which can cause a crash any time the grid is updating. My guess is if you try again there will be different points where you get the same crash.
To see where the crash is, click "OK" and then go into clsGridLinks and you should see a line highlighted in grey, likely line 100-120. Go into the definition of the highlighted line and you will see the line inside which is causing the crash. It is usually line 320.

**Comment by dannyparsons** [comment]
This should be fixed by recent improvements, I have tested with this data and it works well.
