### ISSUE TITLE
General Graphics

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3284]
**General**
1. When I press **Edit**, and go to the **Layer Parameters** tab, it seems to be back to its default state. That is, all my checkboxes are no longer checked. This occurred more often than not, except in geom_violin a couple (such as draw_quantiles) did remain checked.

2. Had an issue of updating. So the **Layer Dimensions** and the **Layer Parameters** tabs both update the data frame if you change it on one tab to the other. However, it doesn't update how this affects the options.
a) I open the sub, I go to **Parameters**, then to **Dimensions** and change to **geom_bar**. I then go back to **Parameters** and my options are as I would get for **geom_boxplot**

![image](https://user-images.githubusercontent.com/21180424/27035834-a73b06dc-4f7a-11e7-803f-69f8f9ac168e.png)

b) I open the sub, I go to **Parameters** and I change to **geom_point**. Then I go to **Dimensions** to input my variables. My options are given to me as I would get them for **geom_boxplot** (the default) not **geom_bar**:
![image](https://user-images.githubusercontent.com/21180424/27035877-d2ed265c-4f7a-11e7-84a0-0e81ef8ef44b.png)

3. There are several ucrInputs here which we presumably want to make non-editable

4. When pressing **reset**, could we have a warning that this will erase the current layers?

5. In the future, is it possible to add the option to rearrange layers?

**geom_point**
This may be an issue with other geoms.
I did a layer of a factor against a variate. (Constituency against Conservative Party votes)
Then I did another layer of a factor against a factor (Constituency against Labour Party votes)
since I "forgot" to convert my second factor into a variate.
This crashed it.

**geom_violin**
When the 7th option (trim) is checked, and you then click **edit** to reopen that option, there is a developer error

> Developer error: no state of control ucrInputCboParamValue satisfies it's condition. Cannot determine how to set the control from the RCode. Modify control setup so that one state can satisfy its conditions.

**geom_bar**
This crashes on `stat = "count"` 

**geom_jitter**
This allows you to press OK if none of the receivers are filled. This results in a crash
This needs y to be filled to not crash.

**geom_freqpoly**
This seems to crash when other ones are used but not by itself. This is not always the case - it's only if certain things are checked, `centre = 0`

Causes crash with geom_hline
geom_dotplot
geom_jitter

On R, when running centre = 0, you get this warning:

> Warning: Ignoring unknown parameters: center

This is so far, I'll add to this. I just want to press submit in case I lose this list!

**Comment by lilyclements** [comment]
**geom_label**
You can't specify both nudgex/nudgey and position.
(you can specify nudgex and nudgey)
> Error: Specify either `position` or `nudge_x`/`nudge_y`

**Comment by dannyparsons** [comment]
@maxwellfundi can you check on these? Fix anything serious and the simple stuff and report back?

**Comment by maxwellfundi** [comment]
@dannyparsons the tabs issue is fixed. The Issue of developer error still persists as well as well as when a geom is changed on aesthetics tab doesn't update the layer parameters despite the combobox with the geoms being changed.

**Comment by dannyparsons** [comment]
Developer errors on combo boxes fixed. 
When I change the geom on the aesthetics tab, it update on the other tab.

@maxwellfundi what are the remaining issues here?

**Comment by maxwellfundi** [comment]
Did it update the parameters for the new geom? That was an issue too

**Comment by maxwellfundi** [comment]
@dannyparsons So we have it still when i change the geom on the aesthetics, it chnges on the layer parameters but it doesnt populate the correct parameters.

**Comment by dannyparsons** [comment]
That's fixed now. You're saying all of the crashes Lily got with different geoms is fixed now?

**Comment by lilyclements** [comment]
I would like to test this out again in that case! Hopefully will get some time this afternoon

**Comment by maxwellfundi** [comment]
@dannyparsons @lilyclements I have been testing this and most of the issues here have been addressed. 
With jitter, that happens because there has no mandatory aesthetics defined.
I could not find the developer error anymore, but we need to have ucrcolour to be non editable because if something that doesnt correspond to a colour is typed in then it causes a crash

**Comment by lilyclements** [comment]
Surely with jitter then we need to say for OK to not be enabled (on the layers main dialog) if nothing is in any of the selectors. SO just we don't mind which selector is filled. As long as one is filled.

Good find with the colours bug!
