### ISSUE TITLE
Dlg Describe Two variable Bug

### ISSUE THREAD

**Issue by stevenndungu** [africanmathsinitiative/R-Instat#3286]
@africanmathsinitiative/developers Can someone help in fixing a bug in describe two variable dialogue.
Problem to be fixed:
Both receivers cannot receive the variables from the selector. They are automatically cleared as soon as they get to the receiver.

I have tried debugging and found the issue to be with setrcode of both receiver, though apparently  @AlexSananka and I don't see a better way of setting the r code for the receivers.  It deems to be correct.

**Comment by volloholic** [comment]
@stevenndungu is this fixed? Can we close it?

**Comment by stevenndungu** [comment]
Yes, I fixed it yesterday. Can  be closed now
