### ISSUE TITLE
Issue with re-ordering columns

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3288]
If you rearrange your columns, I've realised a few dialogs act strangely.

1. dlgReplace
At the moment if I open dlgReplace, put in my column(s), it then crashes straight away before pressing any options:

> Error in self$get_data_objects(data_name) :  not found
> 
> The error occurred in attempting to run the following R command(s):
> 
> InstatDataObject$get_variables_metadata(column="Fert", data_name="", property=data_type_label)

2. dlgView has an issue as it can't read in the data_name = "" either:
`utils::View(x=InstatDataObject$get_columns_from_data(force_as_data_frame=TRUE, col_names=c("Village.","Variety."), data_name=""))`

I imagine this will occur on other dialogs. Presumably this is to do with that when you rearrange columns, you lose your data_name in the metadata.

![image](https://user-images.githubusercontent.com/21180424/27044942-4794ec4e-4f97-11e7-94f4-6ec903fb8fa1.png)

**Comment by dannyparsons** [comment]
Are you still getting a bug on replace dialog? I don't have this issue. It was updated recently.

**Comment by lilyclements** [comment]
I'm still getting the issues if I rearrange the columns first. I'm getting it with multiple dialogs.

**Comment by dannyparsons** [comment]
Ok I see, I misread the connection to the reordering, will look into that.

**Comment by dannyparsons** [comment]
Should be fixed now, set the reordering function to not drop the data frame metadata.
