### ISSUE TITLE
What happens with View Coumn Metadata when you covert numeric column to Factor 

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#3299]
![image](https://user-images.githubusercontent.com/13945088/27072738-1797afe8-502a-11e7-9c42-c7035fbef248.png)

I tried converting numeric columns to factor and tried to view  column metadata. The information concerning levels is not being wrapped.

Is there any solution for the grid to get rid of this problem?

@dannyparsons

**Comment by dannyparsons** [comment]
This is a wrapping issue with the reogrid. When we looked into this I think it's a bug in reogrid which hasn't been fixed, therefore we can't do anything about it now.
