### ISSUE TITLE
frmMain to do for release

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3300]
Changes to make to the Main Form for 0.3:

dlgRatingScales (Describe) - disable on frmMain
dlgExportOpenRefine (Prepare > Check Data) - enable on frmMain if the pull request is merged.

@africanmathsinitiative/developers feel free to add any extra to this, then we can make all these changes at the end

**Comment by maxwellfundi** [comment]
Additional things @lilyclements you could disable on frmmain

File>Import From CSPro
File>Import From Databases
File>Convert

**Comment by lilyclements** [comment]
dlgFrequency - add to frmMain

**Comment by Lunalo** [comment]
@lilyclements 

please desable prepare>Data Object> Metadata

**Comment by Lunalo** [comment]
Disable  Prepare>keys and Links>Add Comments

**Comment by dannyparsons** [comment]
I thought keys was working? @lilyclements did you look at these recently?

**Comment by volloholic** [comment]
Print and Print Preview should be disabled.

**Comment by lilyclements** [comment]
Good point - as a reminder to my future self (or to someone else if they do this!) for print and print preview need to be disabled by both their dialog and by the shortcut in the toolbar menu

@Lunalo - Keys is working fine to my knowledge? Why does that need to be disabled? 
If it has a major issue, keys is an example of a dialog which should not be disabled on the main form but should have OK disabled.
Can't you let me know what the issue is there?

**Comment by lilyclements** [comment]
Made changes except:

- Keys isn't disabled as I'm waiting to hear from @Lunalo why it should be. 
- I didn't disable Data Object > Metadata because the dialog looks okay and has a ucr on it to say it's not functioning. Similarly for Add Comment.

**Comment by rdstern** [comment]
I agree that **Prepare > Data Object > Metadata** needs to be disabled unless something can be fixed, and it is a bit late for that now.  It crashes the current version.
As a more general point, I am happy with the dialogues, like Prepare > Keys and Links > Comments.  It is useful to see that this is on the way.  So I prefer that remain as it is.
I am also happy with some of the menu items (e.g. current rating scales) where there is a totally empty dialogue.  I don't feel strongly whether the menu item is disabled or not, but it doesn't do any harm as it is.

**Comment by Lunalo** [comment]
@lilyclements 
I think @rdstern  has clarified my point. I was suggesting addComments to be disabled but now Roger has explained why it should not be disabled.

**Comment by lilyclements** [comment]
Apologies, I wasn't aware that Prepare > Data Object > Metadata crashed upon opening. I saw that it currently has the OK disabled and has a ucr saying "This dialog is not yet functioning" so the user can't run it. I'll disable that from the frmMain

Hopefully rating scales will go in for this release. I'm testing it now and it seems do-able for today!

**Comment by dannyparsons** [comment]
Metadata should now be stable by #3338 so it could stay in the menu

**Comment by Lunalo** [comment]
@lilyclements  

here is the list of dialogs to disable 

climatic>file>clidata
''    ' '       dates>use time
"    "         Quality control > QC procedures
"     "        Describe (All the dialogs on describe)
"      "        PICSA ( All the dialogs)

**Comment by shadrackkibet** [comment]
add
climatic>prepare
>displaydailyclimaticdata
>ClimaticSummaries

**Comment by shadrackkibet** [comment]
@Lunalo  there are some dialogs on climatic>describe>climaticGraphs> which are working.

**Comment by lilyclements** [comment]
That's fine, I've only disabled the ones which aren't working and don't have the "This dialog is disabled" note on them.
