### ISSUE TITLE
Climatic>Describe>ClimaticGraphs>Cumulative distribution bug.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3311]
on testing this dialog using samaru data with stations as factors and Rain as a variable. This dialog bugs on click ok .
![image](https://user-images.githubusercontent.com/26301973/27091483-edf61b0e-5068-11e7-9edd-7ecf30e1340e.png)

**Comment by dannyparsons** [comment]
I have fixed this issue on a similar dialog here #3309 Can you update and check if it's working now?

**Comment by shadrackkibet** [comment]
I have tested the latest version. This can now be closed.

**Comment by shadrackkibet** [comment]
just before this is closed. Do we still need this dialogs to go this far on the menu?

![image](https://user-images.githubusercontent.com/26301973/27096894-309ef7fc-507b-11e7-9a11-1d86a0f3f626.png)

**Comment by dannyparsons** [comment]
Good point. For this release they can stay, but we should review this before 0.9.
@shadrackkibet  Can you create this as a separate issue so this can be closed?
