### ISSUE TITLE
climatic>File>ImportGriddeddata developer error.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3315]
This is  developer error on ucrinputcombobox when user types in and the reopen the dialog.

![image](https://user-images.githubusercontent.com/26301973/27097306-7bdd8ffc-507c-11e7-8304-78183cade99d.png)

**Comment by volloholic** [comment]
I think this should be non editable if the user is not allowed to type their own value.

**Comment by dannyparsons** [comment]
Still getting this error?

**Comment by shadrackkibet** [comment]
Yes this still has and error.

**Comment by dannyparsons** [comment]
Download From and Data File should be non editable. Can you change this?

**Comment by shadrackkibet** [comment]
yes will change this quickly.

**Comment by lilyclements** [comment]
This has been fixed on #3337 so this issue can be closed now
