### ISSUE TITLE
Climatic>prepare>startofRains bug.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3316]
was testing this dialog and found that we have a bug here.Is this fixed elsewhere in an open pullrequest?

![image](https://user-images.githubusercontent.com/26301973/27097516-22dee350-507d-11e7-850c-887874c0c626.png)

**Comment by volloholic** [comment]
Is there a station receiver on this dialog? 
If so then you need to fill then when you have multiple stations, otherwise the error message is correct because the dates will not be unique without the stations.
All climatic dialogs like this should have a station receiver.

**Comment by shadrackkibet** [comment]
No station receiver on this dialog .

**Comment by shadrackkibet** [comment]
@dannyparsons  should this dialog be disabled for now?

**Comment by dannyparsons** [comment]
@rdstern @volloholic what do you think? It doesn't have a Station receiver so can't work with multiple stations, but can work with single station. Also has other bugs because it's not yet been updated.
