### ISSUE TITLE
Climatic>Describe>ClimaticGraphs>Cumulative distribution  going far.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3320]
we earlier agreed that dialogs should not go far on the menu.On climatic menu.we have two dialogs which are far.

![image](https://user-images.githubusercontent.com/26301973/27100667-85ef1b04-5087-11e7-8384-fca5dde175e8.png)

**Comment by rdstern** [comment]
Well spotted.  Of course rules are to be broken, and I think this menu might be one of them!  However not with these two graphs like that.
a) The Wind rose will become one of the dialogues to go under wind speed/direction.
b) Not sure where the cumulative will go, but it might be under PICSA.

So these items will move.  For now I suggest we (temporarily) leave them there, till we decide finally where they go to!

**Comment by AlexSananka** [comment]
I think we no longer have that sub menu for climatic graphs and this was sorted,can  this be closed?

**Comment by dannyparsons** [comment]
@shadrackkibet?

**Comment by shadrackkibet** [comment]
This should be closed.
