### ISSUE TITLE
Describe > Two Variable > Graph Improvements

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3323]
> This needs improvements to bring it to the level of the one variable. 
> There is no Coord Flip. 
> Then the options added to the one variable, like violin plots and jitter need to be added so the dialogues are consistent.
Improvements need from @rdstern. Any more can be listed here.

**Comment by volloholic** [comment]
@maxwellfundi Thoughts?

**Comment by maxwellfundi** [comment]
This would be really good to have similar options for as those of one variable graph. Am not sure we can have this for tonight.

**Comment by volloholic** [comment]
@maxwellfundi what about now?
