### ISSUE TITLE
climatic>prepare>dryspells bug.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3336]
Recently tested this using samaru data with stations. The bug is here.

![image](https://user-images.githubusercontent.com/26301973/27127003-0502605c-5102-11e7-9fe7-b555c89e1f4b.png)

**Comment by dannyparsons** [comment]
Same issue with non unique columns. I assume you added station? Can you try to create a key with Station and Date columns from the Add Key dialog to see if the columns are unique?

**Comment by shadrackkibet** [comment]
This can be closed. It works on creating a key to have unique columns. This procedure needs to be explained to avoid such bugs.

**Comment by dannyparsons** [comment]
If a key can be created then it shouldn't give a bug here. So do we know why this gives an error?

**Comment by volloholic** [comment]
@shadrackkibet this relates to the station issue if that is doe this can now be closed.

**Comment by shadrackkibet** [comment]
This bug is still there.

**Comment by shadrackkibet** [comment]
@volloholic  this can now be closed.
