### ISSUE TITLE
Diablibling these two sub menus

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#3347]
![image](https://user-images.githubusercontent.com/13945088/27135600-9d742e50-5121-11e7-949c-fa3584908cc0.png)

Other(One Variable) and other (two variables)

@rdstern  I think these two should be disabled. What do you think ?

**Comment by rdstern** [comment]
I agree.

**Comment by Lunalo** [comment]
Thanks @rdstern 

@lilyclements  I think you should disable these two

 @africanmathsinitiative/developers  milestone  0.3

**Comment by lilyclements** [comment]
Great, I'll disable them along with others in #3300
