### ISSUE TITLE
Climatic>Prepare>Transform bug

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3351]
This dialog is not in good state. most controls are disabled,should it be disabled for the next release? 

![image](https://user-images.githubusercontent.com/26301973/27139331-66d4a302-512b-11e7-87b9-3149f82f2eb7.png)

**Comment by shadrackkibet** [comment]
This has been improved on #3082 . can this be merged if it is better than this?

**Comment by lilyclements** [comment]
It can't find the function rollapply because that is from the zoo package. Can you add this in before rollapply to use zoo?
What are the other issues on this dialog?

**Comment by shadrackkibet** [comment]
@stevekogo has commented on pullrequest #3082  that this is in good state to go in. @lilyclements  was reviewing this pullrequest what can you say about this?

**Comment by lilyclements** [comment]
Great, I've been told you're fixing the developer error. The only other error is quite small - when I reopen the dialog, the ucrSave has in it "moving_sum", even if I close and reopen on an rdo which isn't moving sum

**Comment by dannyparsons** [comment]
@shadrackkibet are you continuing to work on this?

**Comment by shadrackkibet** [comment]
@dannyparsons  this issue can be closed because it is not there in the latest version.Also there is a lot of enhancements by @stevekogo  in the latest version with a developer error which i fixed temporarily in the latest installer.I am going to work on fixing the developer error properly.

**Comment by dannyparsons** [comment]
Ok thanks, any further comments can become a new issue.
