### ISSUE TITLE
Climatic dialogues need station and date to define Key

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#3366]
All the climatic dialogues need to finish being updated to the ucr controls and include station as well as date when they are defining a key! @africanmathsinitiative/developers we need to make sure this is complete for the next release!

**Comment by volloholic** [comment]
@shadrackkibet can you confirm I can now close this

**Comment by shadrackkibet** [comment]
Start of rains has a station receiver now.. Unfortunately there is a bug still.
![image](https://user-images.githubusercontent.com/26301973/27736520-2bdbf460-5dad-11e7-8394-b69c67dff759.png)

**Comment by dannyparsons** [comment]
@shadrackkibet This is the same error message you showed before where I then explained it was because the Date and Station do not have unique combinations to define a key. Do the Date and Station columns give unique combinations in your data?

**Comment by shadrackkibet** [comment]
My data do not have a unique combination of Date and station. How can i avoid this error?

**Comment by rdstern** [comment]
What data are you using?  I would like to see it.  I suggest that we have an issue for the Define Climatic Data, for it to check that the Station and date do define a unique combinations.  This could be a similar control (check) that we already have in the Define key dialogue.

Often we will have done that check earlier, but not necessarily.

If it fails, this is where we need the new Prepare > Check Data > Duplicates dialogue.  There is already an issue on this.  I hope this can be in place for the 4.0 milestone (July), but it might have to wait for 4.1 (August).

**Comment by shadrackkibet** [comment]
[samaru_stations.zip](https://github.com/africanmathsinitiative/R-Instat/files/1115525/samaru_stations.zip)

This is the data that i am using.
