### ISSUE TITLE
Prob Distributions > Show Model

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3371]
I chose Bernouli and used 0.1, ..., 0.9 as the values and got the error below.

![image](https://user-images.githubusercontent.com/11214914/27154655-bd6e8ee0-514d-11e7-9598-f9ee4e724d5d.png)

**Comment by rdstern** [comment]
Interesting issue.  Probably the qdist doesn't have Bernoulli so we need to add size=1.  If it treats it always as Binomial, then Bernoulli is the special case of a single binomial "trial", e.g. a single coin toss.

**Comment by volloholic** [comment]
@Lunalo update?

**Comment by stevenndungu** [comment]
This issue is fixed. This should be closed now.
