### ISSUE TITLE
Convert to Ordered Factor not working for labelled data

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3372]
Using efc data tried to make several different columns into Ordered Factor, but it just made it a Factor.

**Comment by rdstern** [comment]
Yes, this is what I found.  This is with the imported labelled data from numeric to factor.  Once we are able to add labels ourselves to columns a la SPSS in the metadata we should be able to check whether it is a quirk of the efc data coming from SPSS or it is more general.

**Comment by dannyparsons** [comment]
Just to clarify this is only for labelled columns.
