### ISSUE TITLE
Describe > Specific > Frequencies

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3374]
It is looking good and lots seems to work.  Of course I found a bug, and it is a dialogue where there can be lots of suggestions.
First the bug.  With the survey data simply do a 2-way table of Village by Variety and save the counts.  Or the percentages, any one you like.  I think the first one works OK whichever it is.  Now do another, also saving.  I was keen to see the counts and percentages together.  But it crashes the second time round with a comment about the NAs.
1. Suggestions include the possibility of doing counts and percentages together.  At least when you save the results it would be good to have the option of having the counts as well as the percentage.
2. Second is a possible option, when you show percentages that the margin would show the counts.
3.  Different sort of suggestion now, but related.  When you add the margins you get a lot of data frames.  It would be good to have an efficient way also of deleting data frames you don't want.  How about having the right-click also on the data frame metadata.  There each data frame is just a row, so you could select more than 1 and opt for delete.

**Comment by rdstern** [comment]
Today I tried getting the counts (and storing them) from the frequencies dialogue.  I used Village and Variety.
Then I went to the Summary dialogue and got the mean.  It sensibly added to the same data frame!  Great.
Then I went back and got the min and max, but then put the factors in the other order.  It was unaffected - still added to the same new data frame.  Fantastic.  And I didn't get the crash I got above
However:
1) I think it is putting the factors in its own order?  I had Village first and the resulting data frame had variety first.  Is there any reason why it doesn't keep the order of the dialogue?  Could it?
2) Could there please be an option on the dialogue to include the zero counts.  So you get the full table.
3) I wondered if I could also do a summary from the Column summaries dialogue.  So I used the same factors as above - and it crashed with (I think) the same NA message as above.
4) This is all pretty close though.  Wow.

**Comment by rdstern** [comment]
Here is the error:

Error running R command(s)

Error: NA column indexes not supported


The error occurred in attempting to run the following R command(s):

InstatDataObject$get_data_frame(convert_to_character=TRUE, include_hidden_columns=FALSE, use_current_filter=TRUE, data_name="survey_by_Village._Variety.")

OK

**Comment by dannyparsons** [comment]
1. Counts and %s now saving - this could get messy as we use default names and there is overwriting at the moment. Need to consider this in more detail.
2. We don't currently have the flexibility of margins but this is entirely possible.
3. We should adapt the Delete Data Frame dialog to be able to delete multiple data frames at once. Not sure we should allow users to do this through metadata - you might think you're only deleting the row and then all your data disappears. I prefer the dialog change solution.

Will close this and open separate issues for remaining tasks.

**Comment by dannyparsons** [comment]
Bug causing the crash is fixed by https://github.com/africanmathsinitiative/R-Instat/commit/d696ebead26b753ff69f8f41c6e2bf37e191b753.

**Comment by dannyparsons** [comment]
The other feature useful for saving the calculations is hidden data frames, which is still to be done.
