### ISSUE TITLE
Unstack dialog - Updating and Enhancements

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3377]
I worked a while ago on dlgUnstack to update it. It had a few comments in the review stage and wasn't a priority. I plan to continue work on updating this dialog, however, I've been told that there are plans to enhance this dialog.

I was wondering what these enhancements were and if I should add them in to the code while updating, or if I should leave them for now

**Comment by lilyclements** [comment]
@africanmathsinitiative/developers this needs to be updated. I've done most of the work and will hopefully find a time to finish it. However, it would be really helpful to know what enhancements were planned for this dialog.

**Comment by dannyparsons** [comment]
I think if it can easily be updated as it is, we should start with that and then see if there will be time to make enhancements later. I don't think there will be major changes to the dialog any time soon so enhancements shouldn't change too much if we want to do them.

**Comment by lilyclements** [comment]
Great  updated in #3562
