### ISSUE TITLE
dlgStartofRains - needs updating

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3386]
dlgStartofRains needs updating to the new system still.
This also needs a Station receiver

**Comment by lilyclements** [comment]
Closed because this is mentioned in #3366

**Comment by dannyparsons** [comment]
This can stay open as it needs general updates as well as the Station receiver.

**Comment by shadrackkibet** [comment]
i am now going to work on this.

**Comment by shadrackkibet** [comment]
@lilyclements  are you on this?

**Comment by lilyclements** [comment]
Yep I'm working on this at the moment, sorry!

**Comment by dannyparsons** [comment]
@rdstern this is now merged (#3467) and ready for your testing
