### ISSUE TITLE
dlgRegressionSimple - Needs Updating

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3387]
@Lunalo I believe you're working on this?

**Comment by Lunalo** [comment]
Yes. Am now working on it.

**Comment by volloholic** [comment]
@stevenndungu update?

**Comment by stevenndungu** [comment]
Almost done, we have worked closely with Danny. The only thing remaining now is the save tab which i Have encountered slight challenge with it. #3530

**Comment by stevenndungu** [comment]
This can be closed now.
