### ISSUE TITLE
Layers control in plot options

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3399]
Adding layers is not enabled on the plot options dialog. However, the control is working on the General Graphics dialogs so should be easy to link up now on all dialogs.

Also the control should say "Layers" and not "Additional Layers".

We decided before that all layers should appear in the list i.e. including the first layer from the main dialog.

**Comment by volloholic** [comment]
@maxwellfundi to be closed?

**Comment by maxwellfundi** [comment]
@dannyparsons  this will be fixed by the pending pull request #3399. its current state is okay
