### ISSUE TITLE
Graphics menu changes

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3403]
I suggest we simplify the **Describe** and **Climatic** menus slightly as follows:

**Describe**

1) Get rid of Describe > Graphs menu.
2) It currently has 4 options.  Put the Cumulative Distribution under Describe > Specific. It can be at the bottom.
3) The other two options that are enabled, (wind rose and inventory) are also in climatic.  So they can just go.
4) The final option is population pyramid.  It doesn't (I think) use ggplot.  It is basically a bar chart.  So I suggest we leave that till after July and then consider whether a ggplot version is produced as a third option in the bar chart dialogue.

**Climatic**

5) Similarly we get rid of **Climatic > Describe > Climatic graphs**
6) Wind rose should move.  To make it simple, for now it could be under the Climatic > Describe > Wind dialogue.  If you wish and have time, then it could **be** that dialogue.  
7) I think the cumulative frequency is the same as is also under SCF support, So we don't need it twice.
8) While there I suggest that **Climatic > SCF Support** becomes "**Seasonal Forecast Support**"

**Comment by dannyparsons** [comment]
@AlexSananka can you make these changes?

**Comment by AlexSananka** [comment]
Yes I'll make this changes

**Comment by AlexSananka** [comment]
This should be closed

**Comment by dannyparsons** [comment]
Thanks. Also, if you tag the commit or pull request with the issue it can automatically close
