### ISSUE TITLE
Graphics sub dialogs tabs opening

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3415]
Try this:

1. Open scatter plot dialog
2. Click Scatter Plot Options
3. Click Layer Parameters Tab
4. Close
5. Click Reset
6. Reopen Scatter Plot Options

** layer parameters tab still shows - it should reset to the first

Worse than this

7. Now open Boxplot dialog
8. Click Boxplot Options

** layer parameters tab still shows - it should reset to the first

When opening sub dialog from a reset, need to reset to first tab. We have done this for other sub dialogs. I thought this is implemented in methods for graphics subdialogs so just need to link it up.

**Comment by volloholic** [comment]
@maxwellfundi update?

**Comment by maxwellfundi** [comment]
This was done already. It can be closed.
