### ISSUE TITLE
Stacking with multiple groups or sets of columns

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3425]
This would be a very useful addition.  I think the R command side is not too difficult.  What is difficult (to me anyway) is to have a clear and simple dialogue.  And that is important for us.  So I have some alternative suggestions:

1) We don't do it!  But we do keep the linking information, so if we return to the same data frame as before and then stack again with the same number of columns, it goes (by default) into the same new data frame.

2) As 1) above, but this is one of a number of dialogues where it would be even easier if we kept the dialogue open. (Or re-opened it once the result was there - perhaps a "Re-open dialogue" tick box.  (Genstat has a general "system" for keeping any dialogue open.  I would prefer this extra tickbox on those where it may be common.

3) We decide to do it, but later.  So all we do now is to have the two buttons at the top with perhaps Single and Multiple as the options.  And Multiple is disabled for now.  So we are signalling our intentions.

4) We add to the dialogue for multiple groups being stacked.  For each group we need to give the columns to be stacked and the name of the resulting column.
a) This could be a more complex receiver on the main dialogue. I have played with that idea and don't like it.  
b) So, the only way I can see to make this into a simple procedure is to use a sub-dialogue.  In that case we could have a button on the main dialogue with the label "More Groups".  This is only enabled when the main receiver is not empty.  If we take this route, we probably don't have the button at the top, but perhaps it would still be useful.  Most of the time we will stack a single set of columns.  
c) Then we have to see how to make the sub-dialogue simple, when we don't know how many additional groups.  I suggest a tabbed sub-dialogue, where the main tab is also Group 2 and there are other tabs labelled Group 3, etc.  This arrangement would make it easy to go to (say) 6 and that would be neat, and probably overkill".  On each tab there is a multiple receiver and a single field for the "Stack Data Into" name.
d) At some stage there needs to be a check that each multiple receiver has the same number of columns to stack.

**Comment by dannyparsons** [comment]
Multiple column sets now implemented on the dialog - more options to be added to allow flexibility in defining output column names etc.

To use: put all stacking variables in the receiver. Then check "Stack multiple column sets" and choose number of sets. The selected columns will be split into the number of sets selected - so the order of columns is important. The number of variables must to stack must be a multiple of the number of sets - error given if not.

Note that ID columns receiver is hidden when stacking multiple sets as this is not available in the function used. However, there is a drop parameter when stacking multiple sets which can be implemented to be able to not carry all columns. Specifying the values of the "variable" column and specifying the names of the stacked columns is possible and to be done - possibly on a sub dialog.
