### ISSUE TITLE
Right click in the column and sheet metadata

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3427]
My suggestion is that we add the same right-click to the (rows of the ) column metadata that we have for the columns of the data.

We could also add the right-click that is at the bottom of the data (and applies to the sheets).  This would be also for the tabs of the column metadata.  And it would be active for the rows of the sheet metadata, because there a single row is for a sheet.

The tab metadata includes the option to view the data, which is great.  There is already the feature in the metadata window to choose a subset of the columns.  Ideally this would then show the data for just these columns?

This is part of further moves to make the column metadata into a more used window.  When we have large sets of data and multiple data frames it becomes less useful to have the data window, because it shows only a small subset of the data.  It is likely to be more useful to see the metadata. This is the situation in SPSS and Stata.

**Comment by volloholic** [comment]
@Lunalo  update?

**Comment by Lunalo** [comment]
Yes, I had also wrongly referenced it
