### ISSUE TITLE
Windows layouts and toolbar

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3428]
I think we agreed to have a defined set of windows layouts for the release.  I suggest some of these and would very much like the toolbar to add these as options.
1. I am happy with the ones we have now. This goes naturally from 2 windows to (all) 6 windows.
2. Do we want to make it easy to have one window situations?  If so:
a) The obvious single window is then the Output, 
b) There could be a case also for the 1) data, 2) column metadata, 3) log

Could the toolbar have the obvious one , i.e. output if you click on it, and a down arrow which would allow the others?
3) 2 window situations.  a) data plus output, b) column metadata plus output c) log plus output
4) 3 windows. a) as now with column metadata added, b) sheet data c) log 
5) 4 windows a) as 3 windows etc.
 
I assume we will also be looking at the Tools > Options dialogue.  There I suggest we could have an option on the relative importance of the different windows.  The output is always important, but users could differ on the relative importance of the data, column metadata and log windows.  This would affect the default options on the toolbar.  Otherwise we might have more toolbar buttons

**Comment by rdstern** [comment]
I suggest also a toolbar button to hide or show the R commands in the output window.  It is a toggle.

**Comment by rdstern** [comment]
I have now added Maxwell to this item.  It will need discussion with Danny and may be allocated to someone else in the team.  I hope it is now easy to implement something.
Rachel is now going to be looking for interesting icons for the items below.  So in the work for now use any old icon - and possibly the same for each item.  We can use the tooltips to distinguish between them for now.
The existing toolbar has 3 sections so far.  One is essentially devoted to the file menu, the second to the edit menu.  The third section - which I use quite a lot - is the dialogues - it recalls the last dialogue or the last 10 dialogues.  The main suggestion here is to add a section, which uses the View menu.
Before that I have suggestions for the File Menu options.
1) In the **File > Open** some other packages (RStudio in particular) use this item to also give access to the recent files that were opened. We have this item at the bottom of our file menu.  I would like it here as part of the toolbar instead?
2) Could we add a toolbar item that is the same as **File > Open from Library**?  Again any old icon for now, e.g. same as **File > Open**.  Would it be possible for this to also have the More button which gives access to the recent files from the library?
3) Now the new section.  This has 7 items, because there are 6 different Windows in R-Instat (see the View menu) plus the Reset.  This is simply the View menu made even simpler:
a) **Data Window**: Tool-tip is simply “Show/Hide the Data Window”.  (Ideally it will say Show, when the Window is hidden and Hide when it is visible).  Like the others the icon should also look a bit different when it is enabled.  It is the same as **View > Data View**.  It should also be linked, so when the data window is visible, the View > Data View should be ticked and vv.  (This will also be the same for the other windows.
b) Column Metadata: Same as **View > Column Metadata**.  Tool-tip is simply: “Show/Hide the Column Metadata”.  As with the others, it could always say the same thing, or it could say Show when hidden and Hide when shown.)
c) Data Frame metadata: Tool-tip is simply: “Show/Hide Data Frame Metadata”.  The menu item is View > Data Frame Metadata.
d) Log file: This is View > Log Window. Tooltip is “Show/Hide log of R commands”.
e) Script Window:  This is View > Script Window.  Tooltip is "Show/Hide Script Window".
f) Output Window: This is View > Output Window.  Tooltip is "Show/Hide window with the results".
g) Reset: This is View > Reset to Default Layout.  Tooltip is "Reset Windows to their Default Layout"



impler!

**Comment by rdstern** [comment]
The one item left from this discussion is the current window to delete the contents of the output window.
I suggest this be moved to the end of the Windows block of commands.

**Comment by rdstern** [comment]
Rachel has now produced a set of useful icons.  I understand it is now a simple job to improve our toolbar, because all the operations are being done already.  Suggested tool-tips are given above, and please improve them if you can. 

I have made it 0.4.5 milestone, but assume that will be moved to be 20th October

**Comment by dannyparsons** [comment]
We're now finalising these for a first implementation.
