### ISSUE TITLE
Improved comments in dialogues.

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3429]
The current default comment is OK for R-type users.  It concentrates on the command.
I suggest a more useful default comment would include information on the data frame at least that is used.  Perhaps this would not necessarily change in the comment within the dialogue.  It could be there as <data frame>.  Or it could change dynamically.

There may be other changes people would like.

This was suggested as a feature by Carlos.  It would be good to reconsider the contents.

**Comment by dannyparsons** [comment]
It definitely needs to be improved for the next version.

I like the idea of including the data frame name, although I believe this will require a change on all dialogs to do this. So not for next release.

We could ask a few people if they have any suggestions.
