### ISSUE TITLE
Updating all data selector headers

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3434]
A comment from a tester:

> I then tried what you said below using Describe > Specific > Frequency , and then the resulting dialogue box showed none of the data variables It was totally empty.  Could not work out why. I did the down-loading following instructions in the earlier pdf file you sent me

Because they had no factor columns, the selector was blank. So this was correct. However, the header says "Variables" so there's no way to know it's only showing factors. Notice how confusing this was for them and that they thought it could be a problem with the whole software and installation.

We should indicate what the selector is showing. We could do more when it's blank, but I suggest immediately we need to change the header from "Variables" to "Factors" for factor receivers and "Numerics" for numeric receivers etc. unless there are other ideas for this. When a receiver allows all, or multiple types, then I suggest the default "Variables" is ok.

We are already doing this on some dialogs like Use Graph, where the header is "Graphs".

This is a property of the receiver called `strSelectorHeading` which changes the selector heading when it's the current receiver.

Can everyone please go through all dialogs and make sure each receiver has the correct header set?

If it's not clear what to do on a particular dialog, comment on this issue.

**Comment by volloholic** [comment]
@shadrackkibet Can you follow up to see if people have done this and feed back here. 
@dannyparsons I suggest we also do something in the selector core for when it is empty in this case a label "no factors in dataset" would be appropriate.

**Comment by shadrackkibet** [comment]
@maxwellfundi  has worked on described menu already. @stevenndungu will be checking on prepare menu.  @africanmathsinitiative/developers  someone should work on models menu as i work on Climatic menu.

**Comment by AlexSananka** [comment]
On the model menu, @Lunalo is working on `showmodel` so I believe he can make that edit, @stevenndungu or @dannyparsons  is currently working on `twovariable fit model `so that can be edited too. @lilyclements is on` onevarcompare model` so she can change this too.I can make the edits on `Threevar modelling` and `one var use model`.

**Comment by lilyclements** [comment]
@AlexSananka I can't guarantee I'll be able to continue working on one var compare model, as stated in my email sent Friday. Can you pull the branch and make the necessary changes?

**Comment by AlexSananka** [comment]
Yes I can make the edits.Did you change something or should I just pull it from the master?

**Comment by lilyclements** [comment]
I made very minor changes. That dialog needs a few fixes though, or the sub does, so you can either pull what I've done or it may be easier to start from scratch. I can't remember specifically what fixes - but controls are disabled on the sub.

**Comment by shadrackkibet** [comment]
@dannyparsons this can now be closed.

**Comment by dannyparsons** [comment]
Are you sure this is done on every single dialog active in the software? 
Also remember that the default is "Variables" so for column receivers with no specific data type we don't need to change anything.

**Comment by lilyclements** [comment]
I haven't done this on SOR, EOR or spells yet. I know SOR and EOR are open on pull requests. I'll sort these three dislogs shortly

**Comment by shadrackkibet** [comment]
@lilyclements i have worked on dlgspells to change selector headers.Did you had a pullrequest on this?

**Comment by lilyclements** [comment]
Great thanks. No I don't have an open pull request on spells, thank you

**Comment by shadrackkibet** [comment]
@lilyclements  did you do this on SOR and EOR so that this can now be closed?

**Comment by shadrackkibet** [comment]
This can be closed.
