### ISSUE TITLE
Improve Filter Dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3440]
This is another dialogue which needs to be discussed for this release, even if some of the enhancements, below, wait for after July.
1. I class this as a bug - perhaps not though.  I use the survey data and would like to filter on village.  I choose village, which is a character variable.  I now realise that I wanted it as a factor.  So I close the dialogue, make it a factor and return.  The village remains in the condition and is not recognised as a factor.   I need to delete it from the receiver and then put it back.  I wonder what could be done better than this?
2. A confusion (to me) is the label "Select All".  I have sometimes pressed it, thinking I am selecting all of the condition.  Could the label be changed to "Select All Levels" and be moved to the right in the dialogue?
3. Conditions can have AND but nor OR currently.  I seem to remember that Danny said adding OR would be easy???  Does this mean we need also a facility to add brackets?
4. The sub-dialogue has **Edit Condition** and **Remove Condition**, though these are inactive.  Is the thinking that a condition is part of a filter?  We will need sometime to be able to **Edit Filter** and **Remove Filter**.
5. In Genstat, once you filter, then when you return to the dialogue it asks you whether you want to add this condition to the existing filter, or start again and have it instead.  What do we plan?  I think I would rather that the new filter is always applied **instead** of the existing one.  If we want it as well, then we just make the condition include the previous filter.

**Comment by rdstern** [comment]
A common filter will be to omit the rows when a particular variable is missing.  This is easy (if you know how) for a variate, but not so obvious for a factor.
I found that if you select all levels then it automatically misses out the missing values.  I assume that if you select no levels, then you might just get the missing rows.  But it is a common thing to filter on, so perhaps there could be an option to make this clearer?

**Comment by rdstern** [comment]
@shadrackkibet has been improving the filter system.  I don't know if this is still relevant?

**Comment by shadrackkibet** [comment]
Yes, 4 is still relevant. However I am going to close this because we have a duplicate issue #5793
