### ISSUE TITLE
Specific > Frequency tables

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3442]
I tried un-ticking the html option with the survey data.  (Simple table with Village and Variety).  Just totals, with no percentages. I am not sure what to expect.  

Error running R command(s)

Error in self$get_data_objects(data_name)$remove_columns_in_data(cols = cols) : 
  Cannot delete all columns through this function. Use delete_dataframe to delete the data.

The error occurred in attempting to run the following R command(s):

last_table <- InstatDataObject$summary_table(data_name="survey", summaries=count_label, factors=c("Village.","Variety."), n_column_factors=1, as_html=FALSE, signif_fig=2, rnames=FALSE, percentage_type="factors")

InstatDataObject$add_table(data_name="survey", table=last_table, table_name="last_table")

InstatDataObject$get_tables(table_name="last_table", data_name="survey")

OK

**Comment by dannyparsons** [comment]
Could you send a full log file for this? I'm struggling to replicate it.

**Comment by rdstern** [comment]
I can't repeat it myself now.  It seems to work well!
I noticed there is an R-command now just after the output.  So I tried with the option to not present the commands in the output window and it all looks very neat now.  I wonder about having this as a toggle on the toolbar?

**Comment by volloholic** [comment]
@maxwellfundi is there someone who could be assigned to toolbar and can you take not of this enhancement.
@rdstern Can this then be closed?

**Comment by volloholic** [comment]
@maxwellfundi Progress? we want to close today!

**Comment by maxwellfundi** [comment]
This can be closed. I am adding the enhancement for a toggle button to include commnads on output window on the new issue for tool bars
