### ISSUE TITLE
Max columns to display option

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3444]
We now have a max columns to display options, as we do for rows. The reduces the chance of crashes with wide data sets. Currently the default is 30.

This needs to be in the options dialog. There is a variable for this in GirdLinks like for rows.

**Comment by rdstern** [comment]
I have been using this with a larger number of columns, so not all are visible.
a) The option to view the whole data using the R viewer is very useful.  It works well.
b) What I do miss is the option to use the right-click to make columns into factors, etc.  I suggest having this right-click available now on the column (and sheet) metadata is now even more useful.  I suggest that is now urgent.

**Comment by volloholic** [comment]
@Lunalo Have you worked on right clicking options in the past? If so I propose you take this off danny's plate!

**Comment by Lunalo** [comment]
Yes, I will fix this

**Comment by Lunalo** [comment]
@rdstern 

Should this rightclicks  open a dialog for the case of converting to factors?

**Comment by volloholic** [comment]
@Lunalo the right click should work as similarly as possible to the right click on the Data grid view Skype me if you want more detail.

**Comment by rdstern** [comment]
I agree.  I was hoping it might even be the same, but that may not be practical.
And the right click that is at the bottom of the data view, would now also work for the columns of the data frame metadata

**Comment by dannyparsons** [comment]
@Lunalo what's the state of this?

**Comment by dannyparsons** [comment]
There is a separate issue for this already #3427
