### ISSUE TITLE
Climatic Import netcdf

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3446]
I tried importing the netcdf file from Rwanda.  Earlier we were only able to import one time point.  Steve told me the importing is now OK.  It is 3 million rows I think.
When I import I get the following error:

Error running R command(s)

Error in nc_open(filename = "C:/Users/Roger/Documents/Roger new/Roger/AIMSNEI/MSc essays/Essays in 2016_7/Fauste/ENACTS data NetCDF_GrADSdata.nc") : 
  **could not find function "nc_open"**

The error occurred in attempting to run the following R command(s):

`InstatDataObject$import_NetCDF(main_data_name="Rwanda", loc_data_name="RwandaLatLong", latitude_col_name="Lat", longitude_col_name="Long", nc_data=nc_open(filename="C:/Users/Roger/Documents/Roger new/Roger/AIMSNEI/MSc essays/Essays in 2016_7/Fauste/ENACTS data NetCDF_GrADSdata.nc"))`

I will add the file.

I also found that we could make the dialogue easier to use.  I think (assumed anyway) that all I have to input in the dialogue is the name of each of the 4 fields.  Usually in this situation we give a suggested name.  Could we do that here?
[ENACTS data NetCDF_GrADSdata.zip](https://github.com/africanmathsinitiative/R-Instat/files/1084747/ENACTS.data.NetCDF_GrADSdata.zip)

**Comment by dannyparsons** [comment]
@lilyclements has an open pull request on this which should fix this error. There will probably be further changes needed to this dialog still though.

**Comment by rdstern** [comment]
Great.  Look forward to trying this.

**Comment by dannyparsons** [comment]
Good to have this example file as another test, and for when we implement subsetting. Will close this as there is an active issue on netcdf import generally.
