### ISSUE TITLE
graphics display in output window

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3450]
When I use the correlations dialogue and ask for a pairwise plot it comes in its separate window - not the output window.  I wonder if that need be the case - both for this and for other graphics dialogues?

**Comment by dannyparsons** [comment]
It's a simple fix @maxwellfundi can do.

**Comment by maxwellfundi** [comment]
@shadrackkibet  is editing this currently so he will set the right i call type for this to display on output window.

**Comment by rdstern** [comment]
Great.  It could be good to look at the same time at other dialogues that produce graphs.  I'll try too.

**Comment by volloholic** [comment]
@shadrackkibet update? Can I close this?
@maxwellfundi Have you checked other places?

**Comment by maxwellfundi** [comment]
All the graphs produced from the describe menu are all produced in the output window. @africanmathsinitiative/developers if you might know a graph that is not showing properly in other menus, please report it.

**Comment by shadrackkibet** [comment]
This is not yet fully updated , it has issues which i have highlighted at #3438.

**Comment by volloholic** [comment]
@maxwellfundi  can you do a check. Get others to tell you where there are graphs produced but please test yourself

**Comment by dannyparsons** [comment]
I think someone needs to systematically go through every dialog, or one person per menu, and check this instead of just waiting to come across it.. Maxwell says Describe is done. 
@shadrackkibet can you continue checking Model and Climatic menus. Model menu is being updated so check with whoever is working on a dialog before making changes.

**Comment by volloholic** [comment]
@shadrackkibet @maxwellfundi which of you is taking responsibility to ensure this is done by the end of today so this can be closed?

**Comment by shadrackkibet** [comment]
I have completed working on correlations and it is now ready for review #3438 . I have also gone through Models and climatic Menus to check this and i can confirm that no plot is produced on a separate window.

**Comment by maxwellfundi** [comment]
great, so this can now be closed?

**Comment by dannyparsons** [comment]
Great, when #3438 has been reviewed and merged, this can be closed.

**Comment by shadrackkibet** [comment]
@dannyparsons this can now be closed.
