### ISSUE TITLE
Comparing one variable models with ggplot 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3451]
The graphcomp command in fitdistrplus now has an option to display graphs using ggplot2.  I wonder if we use this option?  If not, then could we?  I hope this would be a very minor change so have suggested it in the forthcoming version.
I am assuming the graphics system can detect whether graphs are ggplot, or not, because other plots from this package still use the ordinary graphics.

I would like to contact the developers again with the forthcoming release - as potential testers - and for information.  It would be good to have taken account of their work (partly for us) when I do that.

**Comment by dannyparsons** [comment]
This is simple to add I believe @lilyclements looked into this already.

**Comment by lilyclements** [comment]
Yes I added this in, however, there are other changes to make to that dialog so still on the pull request. I was going to continue with those other changes either today or tomorrow, but I can do sooner if that's preferable.
This will also be added to One Var Fit when that is being updated

**Comment by rdstern** [comment]
Any time is fine.  I can easily wait till the weekend to send information to the fitdistrplus developers.

**Comment by lilyclements** [comment]
@stevenndungu @AlexSananka how is One Variable Fit Model going?
Four of the plots (the ones from fitdistrplus, such as cdfcomp etc) can have a new parameter added: 
`plotstyle = "ggplot"`

Similarly so for One Variable Compare Models, which I started working on but that dialog needs more changes/fixes to it.

**Comment by stevenndungu** [comment]
I have added in the `plotstyle = "ggplot"` parameter...I like the ggplot graphical inter phase. The rewrite is still in progress.

**Comment by lilyclements** [comment]
Which dialog have you added it to? It is needed in a couple (2 or 3 use cdfcomp/etc)

**Comment by stevenndungu** [comment]
I have added in one var fit model.
 So, i added to `"cdfcomp", "denscomp", "qqcomp", "ppcomp"` functions, leaving out plot function (rdoall) it does not work with plot function.

**Comment by stevenndungu** [comment]
Alex and I  have added this to all one var models. So this is addresed. I think this issue can be closed now(?)
