### ISSUE TITLE
Factor levels and labels

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3452]
Until this bug R-Instat has been impressive - very impressive.  I jhave been analysing the Sudan data that gave us so much grief last Summer at AIMS.  No crashes so far and I did quite a bit.  It has 145 columns and 15,000 rows.

Then I made Urban/Rural, column HH6 into a factor.  It added the labels 1=1, 2=2.  Then I used Column: Factor > Levels and Labels to change 1 to Urban and 2 to Rural.  It then gave the following error:

Error running R command(s)

Error in self$get_data_objects(data_name)$set_factor_levels(col_name = col_name,  : 
  object 'old_levels' not found

The error occurred in attempting to run the following R command(s):

InstatDataObject$set_factor_levels(data_name="hh", col_name="HH6", new_labels=c("Urban","Rural"))

OK   
[hh_Module2_CLEAN.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/1086796/hh_Module2_CLEAN.xlsx)

**Comment by dannyparsons** [comment]
It's that's the worst you could do with this data then I'm very pleased!

**Comment by rdstern** [comment]
I agree.  When I compare this to the trouble the AIMS students had with this data set last September it is so different.

**Comment by dannyparsons** [comment]
should be fixed now, please test again

**Comment by dannyparsons** [comment]
This should now be fixed.
