### ISSUE TITLE
Describe > Specific > Frequency and Summary tables

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3457]
My amazement continues.  I can do great graphs with the Sudan data and also get tables.  No error messages yet.  But some oddities with the tables as follows:
1) **Frequency tables** doesn't seem to take account of **filters**.  (Which summary tables does.
2) **Frequency tables** seems "curious" in its interpretation of **significant figures**.  When it is set to two I got far too many.  I had to set it to zero to get the table I wanted.  Perhaps this is a feature?
3) **In summary tables** it seems to get the significant figures about right within the table.  That's when I did the mean, so the significant figures were also roughly the decimal places.
4) But the **margin column** has **19 decimal places**.  That seems slightly too many!
5) This summary table does seem to take account of the filter - so the NA was zero, but it included the row in the table for NA.
6) So I used the option (which isn't there I think for frequencies) to omit missing values and that seems to have no effect.  The missing row was still there.
7) Aaah no the significant figures has no effect in the summary table.  Whether it is 1 or 6 I get the same results.
8) When I did multiple statistics, count, mean and sum the factors in the table swapped round.  The table that was essentially 5 rows and 2 columns became 2 rows and 5 columns. 
9) In the count non missing it includes the missing!  The other summaries (mean and sum) it has them as zero - which is right because I think I have filtered out all those rows. 

This was all with the Sudan data we used with AIMS last year.  I am looking at these data in more detail, to see if we can use the SPSS files instead.

**Comment by dannyparsons** [comment]
I have fixed the main issue here - which is that the current filter was ignored by the dialogs. I don't think the summary table could have been using the current filter, because it's the same method. This fix also means Column Summaries now uses the current filter since it's the same method again.

Remaining issues can be done for 0.4

**Comment by dannyparsons** [comment]
@rdstern to update on remaining issues here

**Comment by rdstern** [comment]
So far so good.  Filtering seems to work now on frequency.  I get a reasonable number of decimal places.  I still need to check on the NA.

I think I remember that having it always also appear in a separate window in the browser is harder to fix?

**Comment by dannyparsons** [comment]
Yes that''s a bit more work. We can have a separate issue for this now.
