### ISSUE TITLE
Opening log file in R-Studio directly

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#3460]
This should be a really easy but powerful addition. We could have this as a right click option from the log window for example. 
I believe if we save the log text to a file in an appropriate directory and then it's just a question of running:
 
Process.Start("logname.R") 

If R-Studio is installed and the default program to open .R files with this should simply work!

**Comment by dannyparsons** [comment]
Also place this on the Tools menu.

We could start by saving to a temporary location - like we do for graphics.

@maxwellfundi If this is simple please go ahead, discuss with David if it becomes time consuming.

**Comment by volloholic** [comment]
@maxwellfundi update?

**Comment by maxwellfundi** [comment]
I had not gotten to this yet. Its on my to do list
