### ISSUE TITLE
Core Changes - Sub Dialog changes to make

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3473]
@africanmathsinitiative/developers 
Due to a core change in #3467 there has to be a few minor changes made on sub dialogs.
I'm happy to make some of these changes, however, I know people are working on subs on their branches.

Could you let me know what sub dialogs you are currently editing and also add in the following changes (once #3467 has been merged).

The change is:
On the sub dialogs, you need to add to the `SetRCode` the line `bCloneIfNeeded:=True`

For example
`ucrInputGraphTitle.SetRCode(clsLabsFunction, bReset)
`
Will now become
`ucrInputGraphTitle.SetRCode(clsLabsFunction, bReset, bCloneIfNeeded:=True)`

Any sub dialogs people aren't currently editing, I can make the changes to before 0.3.1 release.
Any sub dialogs people are editing - it would be helpful if you made this change to avoid a conflict.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers This is a very important issue, please respond to Lily's questions.

**Comment by AlexSananka** [comment]
Currently am editing `sdgmodeloptions `

**Comment by shadrackkibet** [comment]
I am working on sdgCorrplot now.

**Comment by stevenndungu** [comment]
Ok great, I am currently editing  the following subdialogues....SdgSimpleRegOptions & sdgVariableTransformations

**Comment by volloholic** [comment]
Hi All can I confirm that bCloneIfNeeded:=True has now been correctly added to all subdialoge setRCode calls? if so we can close this issue.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers

**Comment by AlexSananka** [comment]
I have already added to the subdialogs I am working on

**Comment by volloholic** [comment]
Alex thanks for responding. I need a response from someone to say they are accepting responsibility for this being done everywhere by the end of the day so I can close this today!!!

**Comment by shadrackkibet** [comment]
I have updated this on the two subdialogs i have been working on i.e sdgcorrplot and sdgcanonical.

**Comment by stevenndungu** [comment]
Addressing this
