### ISSUE TITLE
File new and significant figures 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3479]
In the getting started guide we generate a small data set - 10 rows and 2 columns.
1. The columns now come with the (l) -logical data type.  I know this will happen when data are imported from Excel, (because all values are missing) but why when File > New?
2. I then followed the guide, and generated the data 0.05 to 0.95.  Then I deleted the 2 initial columns. This just left the one column.  It was now shown as 0 or 1, i.e. with just one significant figure.  I tried changing the significant figures, but to no effect.
(The data are still OK, it is just the formatting.  When I continue and generate the probabilities, then this column is now correctly formatted.)

**Comment by dannyparsons** [comment]
1. We have included (l) for display logical columns now. In R NA columns are logical so unfortunately we get this for new columns, although it is technically correct for the type of column. We could remove (l) for logical but this would also remove it for genuine logical columns as well.

2. This was an issue which would have occurred with any data frame with one column.
