### ISSUE TITLE
climatic>Describe>windspeed/direction>windroseplot

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3493]
This dialog has ok enabled even without input of anything, when you click ok it bugs.I am not sure how this dialog should work.I think there is a problem here.
![image](https://user-images.githubusercontent.com/26301973/27638067-98215b68-5c1a-11e7-9a54-0c3098a38d42.png)

**Comment by dannyparsons** [comment]
This looks old. Let's delete it I think, we already have a Windrose dialog now.
