### ISSUE TITLE
Extremes first last date

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#3507]
Extremes.  This doesn’t yet have any control to select first and last days.  That needs to be added.

**Comment by lilyclements** [comment]
I'm updating Climatic Extremes now so will add this

**Comment by lilyclements** [comment]
This seems to have a date receiver which isn't used for any of the R-Code. What is the date receiver for?

**Comment by dannyparsons** [comment]
@lilyclements did you get a answer to this?

**Comment by lilyclements** [comment]
No, this dialog doesn't seem to need a key so I'm still unsure of this. There's also a Date receiver in other dialogs which aren't using it, such as Transform.

**Comment by dannyparsons** [comment]
let's discuss with @rdstern and @volloholic about Dates on climatic dialogs generally.

**Comment by lilyclements** [comment]
@dannyparsons this can be closed now that Extremes is merged
