### ISSUE TITLE
NETCDF importing.

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#3518]
NETCDF importing.  This at least in a limited way.  Possibly with a critical look at the Climatic > File menu at the same time.

**Comment by dannyparsons** [comment]
@volloholic something we could do fairly quickly?

**Comment by dannyparsons** [comment]
This has now been reworked, possibly enough for 0.4.1. The next feature needed is subsetting options (by variables and dimensions) which must be done for 0.4.2.

**Comment by dannyparsons** [comment]
Also consider merging files (combined with subsetting and importing)
