### ISSUE TITLE
Climatic boxplots

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#3523]
Climatic > Check data > Boxplots conceptualised and constructed.  Should be easy, because it is just ordinary boxplots with the climatic factors largely specified.  (Important, because it will be visible and clearly more flexible than existing climatic QC procedures.)

**Comment by rdstern** [comment]
I hope this will be easy to construct.
1. The top buttons and the whole left-hand side of the dialogue are taken from the existing Describe > Specific > Boxplot dialogue.
2. The right-hand side top part looks like the top part of all the other climatic dialogues, e.g. Climatic > Prepare > Start of the rains.
a) Station
b) Date
c) Year
d) Month
e) Data
f) Check box with field **More Data** for a second column of data 

Then possibly a group box below with label **Layout**.
There are 5 options here.  The first 2 refer to a single plot and the second set of 2 refer to the facets.
1) X-Variable  This has the Year column as the default.
2) Checkbox (default unchecked) 2nd X-Variable.  If checked, then default is the 2nd data column.  
3) Checkbox (default unchecked) If checked, then default is Month
4) Checkbox (default unchecked).  If checked, then Default is Station.
5) Checkbox which is only enabled when both facet variables are checked.  It has the label **Margins**.  If checked, then the facets include the margins.

Now there must be something in the Data variable for OK to be enabled.  Default is rainfall.
1. If nothing in the layout has any contents, then this gives a single boxplot of the data column (rare but possible)
2. If Station is blank and Year is in the layout for the x-variable, then this is a single boxplot of the data by year.  
3. The one bit of coding is that if it is not horizontal then the x-variable label should be vertical.
4. If there is a second data column (e.g. Tmax and Tmin), then this should work with either the second variable given second, or first.  (Only 2 data columns are permitted here.)
5. Then we have facets.  The default is to produce the facets by month.
6. If there were a second facet variable, then this would usually be the station, with the rows now being months and the columns being stations.

We would then try switching these elements round - except I don't see how the 2 data columns can be in the facets.

**Comment by maxwellfundi** [comment]
@volloholic please close this issue now as i have combined it with #3076
