### ISSUE TITLE
One Variable Fit Model

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3560]
1. I'm not keen on that when you use a factor, a checkbox comes up that says "Convert to Variate" and is checked and won't let you uncheck it.
If this bug is planned to be fixed in the future, then can we make it so this option is disabled as otherwise it may confuse the user?
If this isn't a bug but is instead that you have to convert it to a variate in order to use a factor, then I don't agree with using a checkbox to do this since a checkbox implies the user has a choice.
It would be helpful if someone would explain to me why it's currently permanently checked

2. If I click the "Plot Likelihood" checkbox and then select "Plot Log-Likelihood" radio button. When I reopen that sub dialog, the "Plot Likelihood" checkbox is unchecked, which is not as I left it when I pressed return.

Other than that, this is looking really good!
@AlexSananka @stevenndungu @dannyparsons (I think it was Alex and Steven who were working on these? If I'm wrong then very sorry!)

**Comment by dannyparsons** [comment]
The convert to Variate should behave as it does on the two/three variable dialog, which is different to how you've described. @stevenndungu @AlexSananka can you get it to behave as the other dialogs?

**Comment by stevenndungu** [comment]
Thanks for reviewing this, addressing the issues highlighted
