### ISSUE TITLE
Add maxsum to one variable describe (base R summary)

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3564]
base R `summary` has a `maxsum` parameter:

> integer, indicating how many levels should be shown for factors

Very useful to have this on the dialog. It only applies when using base R `summary` so when customise is checked this option should be hidden/disabled. The R default is 7. Ours could be 7 as well unless we want something different.

**Comment by stevenndungu** [comment]
Addressing this
