### ISSUE TITLE
Increase size of reorder dialogs

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3588]
The reorder controls are quite small. I think we can make them bigger to help make them easier to use, which in turn means a larger dialog.

**Comment by dannyparsons** [comment]
Agreed. 

When someone does this, the reorder control should be the same size on each dialog for consistency. Also, dialogs should be smaller than 640 x 480 because this is the minimum screen size a user might have (I don't think we want these dialogs that big anyway but good to keep in mind)

**Comment by shadrackkibet** [comment]
should this be done on the reorder control or on individual dialogs?

**Comment by dannyparsons** [comment]
Good question. It could be both. If you resize it on the control it won't automatically resize on the dialogs so you'll have to do both anyway.

Resizing on the control means when we add it to new dialogs it will be the correct size - so I think yes, do both. It's probably easier to get a consistent size that way too.

**Comment by shadrackkibet** [comment]
@dannyparsons  this can now be closed.
