### ISSUE TITLE
Reorder control enhancement

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3589]
I think that the reorder dialogs can be improved in a few ways.

It would be good if we could select multiple items to reorder. For example, with months the order sometimes goes: 1,10,11,12,2,3,4,5,6,7,8,9. I would just want to put 10,11,12 at the end. It would be good if I could just select 10,11,12 and click to move them all to the bottom at once

**Comment by rdstern** [comment]
I now have another example of data where this feature would be very useful.
I have a data frame where variables called ...6, ...8, ...10 etc are the data and ...7, ...9, ...11 etc are the flag fields.
The feature already half works now, in that I can select multiple variables in the control.  But then it just moves one of them.
Here are some examples
[togo_daily_6_elements.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/5212385/togo_daily_6_elements.xlsx)
[togo_synoptic_3_elements.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/5212386/togo_synoptic_3_elements.xlsx)

They read in easily, namely make -99999 into missing and untick the option to make the first row into names.

**Comment by dannyparsons** [comment]
@Patowhiz could you check if this is easy to add as an enhancement to our reorder control?

**Comment by Patowhiz** [comment]
Yes, I'll check this.
