### ISSUE TITLE
Count in Factor on Factor menu

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3594]
I noticed that Count in Factor is on the Generate menu but not the Factor menu. Should it be on both? If it should, in which position on the Factor menu does it belong?

**Comment by rdstern** [comment]
I think it is in the right place.  There are many dialogues that **use** factors, e.g. column summaries.  I see the factor menu as dealing with the factor columns themselves, not necessarily calculations that depend on factors.

**Comment by dannyparsons** [comment]
Thanks, that makes sense.

**Comment by dannyparsons** [comment]
Just thinking, isn't this what you want for duplicate/unique columns not just factors?

**Comment by rdstern** [comment]
That's right - sort of.  If the count within the set of columns is more than 1, then the columns are not unique.
I don't know whether we could use this function in a way?
Did you see that Sam wrote a function for the count in duplicates?
