### ISSUE TITLE
Packages to add

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3601]
Check whether to add the R package called gapminder.

This seems too good an introduction to gapminder to omit.  It seems little, though the gapminder unfiltered example may not read easily.  But the main example should show how our dialogue makes it really easy to access.

**Comment by volloholic** [comment]
Danny is adding now

**Comment by dannyparsons** [comment]
Good find! Renamed this to be about any new packages needed for next version. Add any other suggestions here.

**Comment by rdstern** [comment]
Could you also check here on the datasets that become available once a package is loaded?  I noticed that dae is one of our packages, but it is not listed, though it has some datasets.  Is that a data type issue?

**Comment by dannyparsons** [comment]
We have to manually add the packages to the library dialog now so nothing gets automatically added. I can add the dae datasets to the dialog.
