### ISSUE TITLE
Number of columns displayed

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3611]
1. I had earlier changed the number of columns displayed to 45 from 30.  This was a number of R-Instat sessions ago.
I am now using the Sudan data and wanted to look at all the columns.  There are 96.  So I went into the Tools > Options, to find that my 45 is still there, but ignored by the current session of R-Instat.

I don't actually mind if I always have to start with 30 and 1000, but then shouldn't it change this in the Tools > Options dialogue.

2. As a second thought the Sudan data has 6 data frames, ranging from about 15,000 rows to over 80,000 and 70 variables to 260.  Would it be sensible (in the future, not necessarily for this release) to be able to make one data frame wider/longer without affecting the others?

3. I then (later) remembered I could have used the View right-click to examine the whole data frame.  I wonder if that could be a "Did you know" "you can always look at a complete data frame by using the Right-Click at the bottom and selecting the View option". 

4.  More generally should we explain (also possibly on this tab?) why we don't show the whole data frame for each set of data.

**Comment by dannyparsons** [comment]
1. Possibly this was set before it was fully functional. And so the Options dialog had the correct value, but the R link didn't. Mine works correctly, including displaying the correct number of columns on reopen. If yours works fine now that I think that was the issue.

2. Yes I think we could have these options as well.

3. Yes that would be good. If you have time to write a few of these "Did you knows" I can add them to the waiting dialog.

4. In the help?

**Comment by dannyparsons** [comment]
Sorry, 1 is wrong. On reopening it was reverting back to 30. I'm correcting this now.
