### ISSUE TITLE
Save data shows error

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3613]
I have the Sudan data, which is now an rds file.

I made a few changes (columns into factors) and then tried the Save icon.  I got an error:

_Error running R command(s)

External component has thrown an exception.

The error occurred in attempting to run the following R command(s):

saveRDS(file="C:\Users\Roger\Documents\Roger new\Roger\AIMSNEI\AIMS Tanzania\Statistics course 2016\Week 3\Sudan\Sudan 2010 MICS_Datasets\Sudan_MICS4_Datasets\Sudan MICS 2010 SPSS Datasets\sudan_mics4.RDS", object=InstatDataObject)

OK_   

The **File > Save** gave the same problem.  When I did **File > Save As** (and made it a different name) it was OK and seems to have saved fine.
I changed the file again and did **File > Save As** overwriting the same name and it seems fine with that too.

**Comment by rdstern** [comment]
Now odd.  I tried again now with Save, and it is working now.

Is this our occasional RDOTNET error?

**Comment by dannyparsons** [comment]
No I don't think so because it would have crashed completely. Possible the file was in use when you tried to save it?

**Comment by dannyparsons** [comment]
This has been fixed.
