### ISSUE TITLE
Label for margins in tables

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3615]
Currently, with frequency tables, the margins are labelled "count".  This is a bit confusing when the dialogue has selected a percentage, as opposed to the count!

I understand why, but suggest it should change.  I notice in ggplot2, where you can get margins, it labels them as **(all)**.  

For other statistics the name may continue, but I suggest we change the counts one - at least in the frequency tables.

**Comment by dannyparsons** [comment]
What should we change it to?

**Comment by volloholic** [comment]
We think we should go with all for now

**Comment by dannyparsons** [comment]
Done
