### ISSUE TITLE
Create messages for the waiting dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3623]
These could be "Did you know", links to the help, links to external websites.

Having a bank of these to rotate would be good so that the waiting dialog isn't static.

**Comment by rdstern** [comment]
And these messages could be in different colours.
1. The message we have now should mention that you need to be connected.
2. **Did you know:** You can easily View the whole of a data frame.  Just **Right Click** on the bottom tab and select **View**. 
3. **Did you know:** Importing data from many other packages is easy.  Use **File > Open** and choose the source you have.  You can export to other software too, with **File > Export > Export Dataset**
4.

**Comment by dannyparsons** [comment]
Now implemented. An issue is sometimes the box is blank, possibly an issue with the random selection.

**Comment by shadrackkibet** [comment]
@dannyparsons can this be closed? I see this has already been implemented.

**Comment by dannyparsons** [comment]
I did an issue that sometimes the box is blank so I would like to fix this first, but I think that's something I can look into.
