### ISSUE TITLE
Column metadata window

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3635]
I like the changes you have made.
1. When there are more than 4 value labels can this be indicated?  A "..." or plus, or ... perhaps.  Something easy, because, in the longer term it would be great to have a little grid opening.
2. Is it possible for the scroll bar at the bottom to be set to be narrow?  So the default is to show more tabs.    If it is a fraction of the width of the window, then perhaps it could be 20%.  If that made it minimal when lots of windows are open, then so be it.  Usually this will be across the top, or at least half the screen.  

(I have made this into a 0.40 milestone, largely because you have been working on that window.  But you may wish to move these to 0.41.)

**Comment by dannyparsons** [comment]
1. It should produce `...` at the end already.

2. The simplest thing I could do is when the grid becomes visible, it ensures the tabs have a width of at least 300. This looks ok on my screen but let me know if it should change.

**Comment by rdstern** [comment]
Great.  Thanks.  I must have had multiple examples which had exactly 4 levels!
