### ISSUE TITLE
Display R-Viewer Graph Option - Bug

### ISSUE THREAD

**Issue by stevenndungu** [africanmathsinitiative/R-Instat#3638]
In our latest version, when you want to view your graph from the R-Viewer Option. The graph appears then disappears (Its totally not available for viewing).  I am not sure why this is happening. @africanmathsinitiative/developers could someone help to fix this..Both Dlg Options and Dlg View Graph has the same issue

**Comment by dannyparsons** [comment]
This is because of the changes in the R link. I can fix this.
