### ISSUE TITLE
File > Export > data gave error

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3640]
This was not on the official version, so this may not happen on Version 0.33.  I was trying to write an excel file - didn't realise it would need a zip application anyway?

It didn't crash and I was able to save a csv version.

Error running R command(s)

Error: zipping up workbook failed. Please make sure Rtools is installed or a zip application is available to R.
         Try installr::install.rtools() on Windows. If the "Rtools\bin" directory does not appear in Sys.getenv("PATH") please add it to the system PATH 
         or set this within the R session with Sys.setenv("R_ZIPCMD" = "path/to/zip.exe")

The error occurred in attempting to run the following R command(s):

rainfall_subset1_temp <- InstatDataObject$get_data_frame(data_name="rainfall_subset1")

rio::export(x=rainfall_subset1_temp, file="C:/Users/Roger/Documents/R-Instat/lesotho duplicate days.xlsx")

OK

**Comment by dannyparsons** [comment]
Possibly you don't have Rtools installed? Or it hasn't detected it? Can you check if you have it?

**Comment by dannyparsons** [comment]
This should be an RTools issue but should be checked.

**Comment by dannyparsons** [comment]
It works on mine, so I think it's an RTools not being installed issue. If not, this can be reopened for 0.4.1.
