### ISSUE TITLE
Factor columns are too persistent!

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3642]
There still seem to be some issues concerned with factor columns.

Whether they can be dealt with by 4.0 is not clear.  
 Once a column is a factor I cannot make it an ordered factor it seems.  And I wonder about dates?
 here are my issues.
1) I had a date column.  From that column I got a year column and also a month column.  It made the month into an ordered factor which is fine.  I made the year into an ordinary factor column, which was fine.  Then I decided to change that into an ordered factor and it seems to refuse.  It persistently treats it as an ordinary factor - or at least it labels it as (f) rather than (o.f).
2. I made a date column into a factor column.  (I know that is strange, but I wanted to see if it caused any issues.  It seemed fine.)  Then I made a combined factor from the date and station.  Then I looked for the number of observations in each factor level.  That took over an hour on my machine, so I don't recommend this route - at least not with 200,000 rows of data and almost as many factor levels.  But it worked! Much to my surprise!
3. But then I wanted my date column to stop being a factor and become a date again.  Perhaps it is, but it still has the (f) rather than (D) after the column name.

**Comment by dannyparsons** [comment]
Factor into Ordered Factor has an issue currently. We need to rewrite some of the converting methods we use.
Factor to Date should work using Make Date. Should check why not.

**Comment by dannyparsons** [comment]
The ordered factors issue is because the `sj` factor functions don't handle ordered as well.

But I've played with a date column converting between Date and factor and ordered factor and that seems to work fine. Could you check this again?

**Comment by rdstern** [comment]
One recent problem I have had - with climatic data.
I change year into a factor column.  Then I realise it should be an ordered factor.  So I make it ordered factor.  It doesn't change.
If I make month into an ordered factor and then change to factor, it doesn't change.
I can make the month into a variate and then a factor.  But if I make my ordered factor into a variate and then back to ordered factor it doesn't.  It is only an ordinary factor.
