### ISSUE TITLE
File > Open problem reading R files

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3643]
CAST (Doug Stirling) has provided 5 small files, which the File > Open dialogue recognises, but can't handle.
They all have the R extension.
The first is a single column as follows:
boxPlot5.2<-data.frame(Eruption.duration.sec=c(216,108,200,137,272,173,282,216,117,261,110,235,252,105,282,130,105,288,96,255,108,100,207,184,272,216,118,245,231,266,258,268,202,242,230,121,112,290,110,287,261,113,274,105,272,199,230,126,278,120,288,283,110,290,104,293,223,100,274,259,134,270,105,288,109,264,250,282,124,282,242,118,270,240,119,304,121,274,233,216,248,260,246,158,244,296,237,271,130,240,132,260,112,289,110,258,280,225,112,294,149,262,126,270,243,112,282,107,291,221,284,294,265,102,278,139,276,109,265,157,244,255,118,276,226,270,136,279,112,250,168,260,110,263,113,296,122,224,254,134,272,289,260,119,278,121,306,108,302,240,144,276,214,244,270,245,108,238,132,249,120,230,210,275,142,300,116,277,115,125,275,200,250,260,270,145,240,250,113,275,255,226,122,266,246,110,265,131,288,110,288,245,238,254,210,262,135,280,126,261,248,112,276,107,262,231,116,270,143,282,112,230,205,254,144,288,120,249,112,256,105,269,240,247,245,256,235,273,245,145,251,133,267,113,111,257,237,140,249,141,296,174,275,230,125,262,128,261,132,267,214,270,249,229,235,267,120,257,286,272,111,255,119,135,285,247,129,265,109,268))
comment(boxPlot5.2)="Eruptions of Old Faithful geyser"

There seem to be 2 separate issues here:
a) It should be possible to read certain files of type R?  Perhaps even this type?
b) There should be error trapping for files that can't be read.

Here are the 5 files he provides:
[oneFactor2.2.zip](https://github.com/africanmathsinitiative/R-Instat/files/1132705/oneFactor2.2.zip)

Doug writes about the files he could produce from CAST:
"I did manage to think a bit about how the CAST data sets might be turned into an R data package. I reckon that I should be able to write a program to go through CAST HTML files and produce ".r" data files from them. This may need a bit of manual intervention for each data set — mainly to insert a comment describing the data — but a lot could be done automatically.

I haven't actually done any coding yet and probably won't be able to do so for a couple of months, but I have manually created five R files for data sets that have most of the main features — they produce data frames that have row names, numerical variables and factors. It should be possible to produce such files programatically from the HTML code, other than the descriptive comments in HTML files that contain multiple data sets.

I haven't had time to look into how these might be included in an R data package yet, but I think they could go into its "data" directory. Was this what you were looking for?"

For now it would be great if those 5 files could go into a CAST directory - in a form that can be read of course, so they can be input from the **File > Open from Library**.

Ooops - this is probably 2 or 3 issues!

**Comment by volloholic** [comment]
@lunalo this should be easy just run the script in r studio and import into an instated object and save as rds

**Comment by dannyparsons** [comment]
and just change the comment line to: `attr(data, "label") <- "comment"` to be consistent with our metadata labels
