### ISSUE TITLE
Themes - bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3656]
@stevenndungu I believe you did work on themes. I've found a few small bugs on the themes tab on sdgPlots

1. The themes checkbox has a colon. This should be removed as checkboxes shouldn't have colons

2. If I uncheck themes and reopen, then themes is checked again and a developer error comes up

3. Should there be a default for the themes combo box?

**Comment by stevenndungu** [comment]
@lilyclements 
1)That went unnoticed.
2) I get why the developer is given
3)Yeah, it should be `theme_grey`
Let me see the best way of addressing this. Thanks
