### ISSUE TITLE
dlgRandomSamples - bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3666]
This is a bug potentially generally in SetRSyntax. I can change the name if so!

I had a look at dlgRandomSamples and found a few issues with the checkbox.
This checkbox used to be working well, and it's since the `AddRSyntaxContainsFunctionNamesCondition`/`etc` codes have been added to this checkbox that these bugs have been introduced.

I don't fully understand this new bit so not sure if it's an issue in the method or in the dialog-code. However, I believe the dialog-code is fine so I think it's in the method somewhere.

The issues are all linked together (presumably) in the `.SetRSyntax/AddRSyntax/etc` code:
* If I uncheck the checkbox, run the code and then open - the checkbox is checked
* It does not reset
* On occasion it would run the value if unchecked (`set.seed = 5`) and the value if checked (`set.seed = whichever_value_I_pick`)

(Note that to the third point, I was struggling to replicate this after restarting R-Instat)

**Comment by AlexSananka** [comment]
This is easy to fix,you just need to clear the codes in the `SetDefaults`

**Comment by AlexSananka** [comment]
@lilyclements I have fixed this in my open pull request,were there any other issues with this check box apart from the ones listed above?

**Comment by dannyparsons** [comment]
@lilyclements @AlexSananka can you tag the this issue in the pull request so this can be closed when the pull request is merged.

**Comment by AlexSananka** [comment]
That pull request has already been merged,this issue can be closed.
