### ISSUE TITLE
Nud resetting bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3668]
If I write a new number into a ucrNud and press reset then it resets as we would expect

If I clear the nud (so that OK is disabled) and then press reset, then nud does not reset.

**Comment by dannyparsons** [comment]
Hopefully the value has reset just that the text might be blank since it's been cleared. Should be able to resolve by setting the `Text` property when the `Value` property is set.

**Comment by dannyparsons** [comment]
Interesting. So this only occurs when the value is the same as the resetting value. When you change the value in the code it sets the text as well so it's fine. But if the new value is the same as the current then it doesn't update the text and it stays blank. I guess this is a "feature" of the nud control. I have added a line to set the text every time the value is set so this fixes the issue.
