### ISSUE TITLE
Main form - edits to make for 0.4

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3680]
@africanmathsinitiative/developers add here what we need to disable/etc on the main form.

So far I have:
* Climatic > File > NetCDF
* Possibly Jitter if it's not updated and merged in time (not urgent)

**Comment by AlexSananka** [comment]
Climatic>Display Daily Climatic Data

**Comment by lilyclements** [comment]
Disable End of Rains
