### ISSUE TITLE
prepare>columnText>distance.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3684]
@lilyclements i believe you worked on the distance dialog recently.When you open the dialog for the first time without running anything and then click on string rdo then reopen the dialog is fine (no developer error). But when you click on column rdo and then reopen there is a developer error.

![image](https://user-images.githubusercontent.com/26301973/28250990-d69d2e9c-6a7c-11e7-9386-30862d7c7de6.png)

**Comment by lilyclements** [comment]
Thanks for this Shadrack, good find. I'll fix that.

**Comment by dannyparsons** [comment]
@lilyclements were you able to look into this?

**Comment by lilyclements** [comment]
@dannyparsons you fixed this, but I will take credit if you wish.
