### ISSUE TITLE
File > Open (or Open from Library) problem

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3689]
I open a file which gives a preview.  

It is a large file so takes quite a time.  The message comes multiple times.  That's OK.

But when I want now to open a new different file it insists on showing me the old preview first.  This can take up to 30 seconds overall and is annoying, because I now want a new file.  I suggest that either the old view image is kept, or it doesn't try to load it again.

**Comment by dannyparsons** [comment]
This now doesn't refresh on reopen (unless you click from the recent files list). It opens as it was closed so the old preview remains in the display. So in a rare case where the file has been edited the preview might not be up to date. For this any other cases I suggest we have a refresh button which refreshes the views.

**Comment by rdstern** [comment]
Sounds great.
