### ISSUE TITLE
Modelling bugs

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3697]
@africanmathsinitiative/developers these are fixes needed by the end of the day. I'm currently working on the One Variable case where I found other bugs.

**Display Options**
* If I check "Residual Plots", close the sub and reopen, then the checkbox is checked but the groupbox isn't visible. I think this should be a manual fix for now.
* Similar problem to above, but with "Fitted Model"
* On the Fitted Model tab, I think the significance level should be 0.95
* On Model > Fitted Model we are running the visreg function. Is this running the bExcludeAssignedFunctionOutput = False line? It needs to be if it's not because we're not getting the plot

**Model Options**
* On Three Variables: If I use the Normal distribution, I get an error on "Three Variable Modelling" if I run on Model Options "log" or "inverse". Should we disable the "Model Options" box for now if the **Normal, Gamma, Inverse Gamma or Quasi** distributions are used?
* On Three Variables: If I use a log-link for Binomial or Quasibinomial, I also get an error. However, the other options seem to run okay. What should we do about this?
* I don't think this code is running on Four Variables. Should it be disabled?

**Three Variables**
* Sometimes I get a bug if I use certain operators with certain variables
e.g. Poison dataset I'm using two-level factors. I get a bug if I do Sick ~ Vomiting / Nausea
What do we do about these sort of bugs?

**Four Variables**
* I put in my four variables. I did Village. ~ Variety + Variety + Fertgrp. Converted Village. to numeric, clicked on the Display tab and it crashed. I could not replicate this error when I tried!

**Comment by stevenndungu** [comment]
Addressing the bugs mentioned above: starting with display option

**Comment by stevenndungu** [comment]
@lilyclements  elaborate on this
"On Model > Fitted Model we are running the visreg function. Is this running the bExcludeAssignedFunctionOutput = False line? It needs to be if it's not because we're not getting the plot" I did not get you right here

**Comment by AlexSananka** [comment]
'I put in my four variables. I did Village. ~ Variety + Variety + Fertgrp. Converted Village. to numeric, clicked on the Display tab and it crashed. I could not replicate this error when I tried!''

I cannot replicate this as well.

**Comment by AlexSananka** [comment]
I finally got that crash,actually it's making all the model dialogs to crash.It's this         `ucrSaveLeverageColumnName.SetRSyntax(clsRSyntax, bReset, bCloneIfNeeded:=True)` line that's causing it to crash.I think it should be `ucrSaveLeverageColumnName.SetRCode(clsRLeverage, bReset, bCloneIfNeeded:=True)
`

**Comment by rdstern** [comment]
OK.  That is an unusual model, because Village has just 3 d.f. and the model has many more than that, including Variety twice!  It still shouldn't crash, but if it crashes when you put Yield ~ Village + Variety + Fertgrp I would be more worried.

**Comment by lilyclements** [comment]
@AlexSananka We need to fix that crash, how have you managed to get it in the end? You said you're getting it on all models dialogs, can you talk me through how you got it to crash?

@stevenndungu Yes sorry for being unclear, I've commented on your pull request where the line needs to go in. Happy to add it in, but it may be easier for you to and I'm not sure if you've got un-synced commits so don't want a conflict!

**Comment by AlexSananka** [comment]
That crash is fixed in @stevenndungu  pull request.
So that should be sorted once #3700 is merged

**Comment by AlexSananka** [comment]
It seems there isn't a procedural way of getting to that crash.You just play around the dialog and then click the subdialog and it crashes.But at least it's sorted now.

**Comment by lilyclements** [comment]
Where in his pull request is it sorted?

My reference to adding the line is to do with Stevens earlier comment 
"@lilyclements elaborate on this
"On Model > Fitted Model we are running the visreg function. Is this running the bExcludeAssignedFunctionOutput = False line? It needs to be if it's not because we're not getting the plot" I did not get you right here"
