### ISSUE TITLE
Exporting R workspace

### ISSUE THREAD

**Issue by mmumbo** [africanmathsinitiative/R-Instat#3729]
On R workspace dialog, while selecting specific data frames should it be labelled variables or data frames?
Attached is the image showing the same.
![issue01](https://user-images.githubusercontent.com/11607243/28562901-b73d12a4-712c-11e7-928a-ef1bcaa1daf6.png)

**Comment by AlexSananka** [comment]
This should definitely change,please let us know all those dialogs which still do not have a sensible name.
Thanks for this spot.

**Comment by AlexSananka** [comment]
@volloholic what do you think?

**Comment by volloholic** [comment]
Hi All this is certainly a change that is needed well spotted. As @AlexSananka suggested it would be good to get a list of all the dialogs where this is a problem before we decide on the best solution. I guess we need to think about what all the possible sets of objects are and how they can be consistently named. This becomes even more critical as we think about translation! These hard coded names need to be in a single place not on individual dialogs!

**Comment by dannyparsons** [comment]
This is now changed on this dialog. We can have separate issues for the general method of doing this.
