### ISSUE TITLE
Not the calendar control

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3732]
Many of the climatic dialogues ask for a day in the year to be chosen.  Currently you have to enter the day number simply as a number.  That is more difficult than in the old Instat.
It would be simpler if you could use a calendar instead.  So could we construct a calendar control?

Originally I assumed we would use a proper calendar from VB.Net, but this assumes you use a particular year.  So I now think what we need is simpler than this - and perhaps close to what we had in the old Instat.
![calendar](https://user-images.githubusercontent.com/11226469/28578655-43ee96ee-7152-11e7-88d0-22bbdbdef9cf.jpg)
![pickadate](https://user-images.githubusercontent.com/11226469/28578660-4bb10bd2-7152-11e7-931a-655b820f6af3.jpg)

It is more a pick-a-day than a calendar.  Then it uses the day number in the year (could be shifted) to translate that Month/Day-in-Month to a day number in the year.

The alternative is for the dialogue to have the two fields with a drop down for the Month and a special up-down for the day in the month.  These together could be a special control.  So that is what you give in the dialogue and the VB then translates that into the day numbers in the year.

Note that this day number is what you give if it is fixed, e.g. for the start of the rains dialogue.  For the spells this may be the case, but we may alternatively want the day numbers to come from a column from a data frame at the year level.  That would be the case if we wanted the longest spell between (say) the start date (a column in the yearly data frame) and the end date (say).

**Comment by lilyclements** [comment]
> Originally I assumed we would use a proper calendar from VB.Net, but this assumes you use a particular year

I had a little look into the calendar control the other day and I'm not sure what you mean by this? I found if I click on the "header" (e.g. where it says July 2017) then it gives me options of all months in 2017. If I click again, it gives me an option of different years. I quite like this.

![image](https://user-images.githubusercontent.com/21180424/28581607-8900cbe6-715a-11e7-8059-4a63ce624b1d.png)

It then goes on a little more to years from 2000-2099 and I can use arrows either side to navigate to 1900-1999, etc

**Comment by rdstern** [comment]
Yes, but we aren't wanting the day number for any particular year.  It is for all the years in turn that it starts on (say) day 92.

**Comment by lilyclements** [comment]
Of course! I understand now, thank you for clearing that up.

**Comment by lilyclements** [comment]
This is also mentioned in #3506 - can someone add a duplicate tag?

Would we want two date-picker sub dialogs: for From and for To?
Or would we want one sub dialog and the options are duplicated to give From and To?

How about a date picker sub with the three options you mentioned as rdos:
1. Select by Day of Year
2. Select by Day and Month
3. Select by Column (this won't always be visible - such as on the SOR dialog. But, where it is visible the user can put the SOR and EOR columns).

**Comment by dannyparsons** [comment]
I think we discussed this could be done but isn't as urgent as other climatic tasks so will be delayed.

**Comment by rdstern** [comment]
agreed

**Comment by rdstern** [comment]
I have changed this back to 0.4.7 so we discuss (at least) for this version.  We have the (tricky) up-down controls for the start and end dates in all the 4 main dialogues, namely **Climatic > Prepare > Start, Spells, Extremes, End**.  (Also Climatic > Prepare > Summary, though it may be a bit more complicated there.

I assume it should not be so difficult to adapt the calendar control to not show the years?  (The ordinary calendar is used already in Climatic > File > Open netCDF.  
There is then one (small?) extra complication, namely that we could have defined a shifted year in our climatic data, e.g. day 1 could be 1 August.
The display in the dialogue can be the month and day, e.g. %b%d.  It doesn't need to present the day number - though an option would be ideal.

**Comment by rdstern** [comment]
I have re-instated this into pending, because I suggest it should be easy to improve on what we have now.
It seems that adapting the calendar control is going to be complicated.  So I suggest we replace the single up-down control by a new custom control that has a drop down with the month plus an up-down with the values 1 to 31.  Default is Jan 1.
There may be a second control that inherits from this and provides the two dates, namely From and To.
This then delivers the day number to the code, using either the actual day or the shifted day number - whatever is in that dialogue.

**Comment by dannyparsons** [comment]
It's possible to restrict the VB calendar control to a single year - I'm not sure if we could then hide the display of the year so it doesn't confuse users. If not, then the other suggestion can also be a user control. We can always change the design later.

**Comment by dannyparsons** [comment]
We now have this "Day of Year" control
