### ISSUE TITLE
Filter dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3736]
1. A simple enhancement that I would welcome is to have the <Shift> <Click> added when choosing a set of factor levels.  For rainfall I often want to have all years from 1968.  It would be nice to be able to select multiple adjacent levels together.

2. Could the Select All become "**Select All Levels**" and move over so it is closer to the right hand side of the grid.  The other could become **Deselect all Levels** or **Clear all levels**.

3. There are many other desirable features of the filter.  We cannot yet (as far as I know) delete any filters, nor can we see what a filter does, once it is produced.  And there is OR to include, etc.  

But I would expect 1 and 2 can be done quickly - 4.1?  

I would also see filtering as a good candidate for the toolbar.

**Comment by dannyparsons** [comment]
Some of these can be done for 0.4.1.

**Comment by maxwellfundi** [comment]
Another feature that we need is to view a filter that has been applied. Further to that, being able to edit a filter and as @rdstern says, - at least (perhaps) add another condition.

**Comment by dannyparsons** [comment]
1 and 2 now done.

**Comment by shadrackkibet** [comment]
- 3 i.e deleting of filters was implemented in #5818
- OR was implemented in #5921
- @maxwellfundi request was implemented in #6183

Therefore this should be closed.
