### ISSUE TITLE
New Column Names - Capitalised first letters?

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3740]
There is an inconsistency among the software of new column names. I think we need to clarify what formatting our new column names use.
e.g. I have a new column name called "New Name" we have used different formatting layouts, such as:

new_name
newName
NewName
new.name

I think the one I like the most is the one which is implemented the least which isn't ideal and suggests others disagree to it. So, I don't have any preference - I just want this to be consistent.
What should we do in the case of "new name"?

**Comment by dannyparsons** [comment]
Can you give an example so I'm clear what you mean? We normally have just one word for default column names I thought?

**Comment by lilyclements** [comment]
I see your one point, and raise three:

1. For one worded columns would we want a capital first letter?

2. In dlgTransformClimatic, there are column names called "moving_sum", "moving_mean", etc. are you suggesting these should just be one word?

3. In addition, with any ucrSave can we have consistency. For example, sometimes the plot names have capitals and sometimes they do not. Also we have "last_plot" but then we have "frequencypolygon1" so consistency with "_" and capitals and what not would be nice.

**Comment by dannyparsons** [comment]
I think because these are R names we should follow something that's sensible in R, which any of your original examples are. Lower case and underscores for spaces is used quite a lot e.g. `ggplot2` so I think going for that in R-Instat is fine.

**Comment by lilyclements** [comment]
Great. I know some dialogs have a capital first letter. I won't go through everything but will check when editing dialogs in the future for this.

Another question - so when we assign something to our instat_calculation$new function, should that have a capital first letter? I know I've used day_from_and_to in one place and Day_From_And_To in another.

**Comment by dannyparsons** [comment]
Those are R variables as well so I think should be the same formatting without capitals

**Comment by lilyclements** [comment]
Great. Those are just things I need to fix in my climatic dialogs I'm on (Start of Rains, End of Rains, Extremes and Transform)
@shadrackkibet @stevenndungu in any climatic that you're working on now can you make sure that your R-variables are non-capitalised?

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers let's check this on dialog before the next release
