### ISSUE TITLE
Quality control of climatic data

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3745]
[Mokhotlong checking daily.docx](https://github.com/africanmathsinitiative/R-Instat/files/1191175/Mokhotlong.checking.daily.docx)

At some stage we will be adding facilities to support NMSs in their quality control.  This is to improve on what is available in the old RCLIMDEXQC and QC Extra.
One facility already is the climatic boxplots.  They exceed what RCLIMDEX provides.
The display of daily data (tables and graphs) will also be useful.  We should remember that the checking will be against paper records that are monthly.

For Lesotho I prepared the following in the old Instat and then coloured it in Word.  I just did 1 year and Lesotho Met asked me to do the colouring for all years.

The idea was for users to check against the paper records:
a) 1st of month
b) Last day of month
c) Maximum value in the month
d) For temperatures etc also the minimum value in the month
e) For rainfall the length of the longest dry spell in the month
f) The number of missing values (if any)
g) A special check if all days are dry for rainfall that the month isn't missing.

Of course often the paper records include the monthly totals and that is also a good check.

One error that is difficult to correct in CLIMSOFT now is where the data for a period have been entered one day shifted from the correct day.  I wonder how this could easily be corrected in R-Instat?

One other interesting check is when consecutive values are identical.  This gives a "flag" in R-CLIMDEX if this is for 4 days or more.

For rainfall we could also check if there is a long sequence of rain days (particularly if the values are close, i.e. small std. dev.  In Lesotho this indicates that perhaps temperatures were entered rather than rainfall.

**Comment by rdstern** [comment]
I have changed this to 0.4.2.  This is the Display Daily which may not be complete by then.  But it is important in my new strategy for Lesotho (which should be useful more generally).  And David is visiting in early September, while Danny will likely go there in October.

**Comment by shadrackkibet** [comment]
@rdstern is this display daily data or it is a separate dialog?

**Comment by dannyparsons** [comment]
This is separate. Maybe this can be closed as this is specified in more detail elsewhere?
