### ISSUE TITLE
Bug in deleting columns (ordered factor related?)

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3748]
I was using the diamonds data set and only wanted my ordered factors.
I deleted the columns from depth to the end in one.
Then I deleted the first column (carat)
This bug occurs either way which I delete the columns so isn't too important.
Anyway, after the last deletion, my data seemingly changed class.

My cut and clarity changed from an ordered factor to a non-factor-type
My color changed from an ordered factor to a factor.

![image](https://user-images.githubusercontent.com/21180424/28868870-b65c2a2c-7772-11e7-8b34-39931dfce776.png)

In the metadata it still says they are ordered factors and it still treats them as ordered factors so it is just the display which is the issue.

Now to bug 2, which I believe is linked because I'm not getting this issue on another data set
If I then convert all three to a numeric via right click
Then convert all three to an ordered factor via right click
The code says `to_type = "ordered_factor"`
However, the metadata now says they are a factor.

![image](https://user-images.githubusercontent.com/21180424/28869060-70c22e0c-7773-11e7-82ab-a8159d1fc46e.png)

**Comment by dannyparsons** [comment]
Great bug to find! This is a bug in the grid retrieving the column types from R. For some reason the R method behaves differently when the data only contains ordered factors, so quite a rare case! Easy to fix and would have been a general issue for columns with more than one type.

The second bug in unrelated and is a general issue with ordered factors. It's reported elsewhere so I will close this when 1. is resolved.
