### ISSUE TITLE
File>Load From Library>ImportDataset?

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3753]
This is a bug in this dialog , the Maximum rows to import text box allows you to type in characters and also negative values? 
![image](https://user-images.githubusercontent.com/26301973/28875990-4654ea56-77a0-11e7-9710-1f2927796d72.png)

**Comment by lilyclements** [comment]
Good one, I'll fix this now

**Comment by lilyclements** [comment]
Mainly offering to fix it since I see in your picture that the checkbox has "WhiteSpace" as one word...!

**Comment by lilyclements** [comment]
This can be closed. This bug was fixed in #3757 and has been merged now
