### ISSUE TITLE
New R package sjlabelled instead of sjmisc

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3760]
We currently make quite a lot of use of the sjmisc package for labelled data.

Danny has prompted me to look and all the functions to do with labelled data and with tagged missing values are now in a new sjlabelled package, and are reported as follows in the sjmisc documentations:

"This function is deprecated. Please use sjlabelled for labelled data functions now."

So I suggest we add the sjlabelled and move those functions over.  I hope this is a simple task?

**Comment by dannyparsons** [comment]
This should be a simple move over to the updated functions and package.
@lilyclements are you able to look into this? I can look into the missing values separately.

**Comment by lilyclements** [comment]
We use three `sjmisc` functions: `to_label`, `to_value` and `to_character`

**`to_label`**
`sjmisc::to_label` is equivalent to `sjlabelled::as_label` so this one can be a simple conversion.
When checked, these two functions run the exact same code so we should not encounter any issues in changing this over.

**`to_value`**
`sjmisc::to_value` is equivalent to `sjlabelled::as_numeric` so this can hopefully be a simple conversion. There is one minor addition to the new function which is that it has an additional parameter `use_labels`. By default, `use_labels = FALSE`  which is good as this means that `sjlabelled::as_numeric` runs the same code as `sjmisc::to_value`.

**`to_character`**
This function was a wrapper for `as.character(to_label)`. I can't find an equivalent function for this in `sjlabelled`. I'm not sure if he's now running `as.character(as_label)` for this instead or if there are plans for a new version in `sjlabelled`, or if he's keeping it all as `as.character(to_label)`.

Shall I update the `to_label` and `to_value` to the new packages?

**Comment by dannyparsons** [comment]
Good time to implement these changes now, thanks.
