### ISSUE TITLE
Sort from right click uses the wrong data frame

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3777]
When I have multiple data frames I right-click and choose Sort.
It takes me to the dialogue - which is fine.  But it is not always the visible data frame, which I would assume for the right-click option.
The example I had was climatic data where I had used sort before on the date column.
I then got a subset (using the filter) and wanted to sort on a column in the new data frame.  It went back to the previous data frame - as would (I assume) be correct if I had gone directly to the Sort dialogue.

But this way should (I assume) clear the fields and assume my new data frame?
Perhaps there are other right-click options that have the same problem?

**Comment by dannyparsons** [comment]
I also realised there are a few right click items which are not linked up to the selection on the grid. This just needs a simple modification to the dialog code. It can be done in the same way as other dialogs are already working so it is a simple task.

I suggest someone goes through each menu item and link up the ones that haven't been done yet.

**Comment by stevenndungu** [comment]
Ok , working on this.
