### ISSUE TITLE
Windows Forms to Delete

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3812]
There are a few windows forms I know of to delete. @africanmathsinitiative/developers if anyone has others then add to this list. This isn't necessary for 0.4.1, however!

dlgEndofRains
dlgEndRain
dlgDrySpells
sdgClimaticSummary

**Comment by shadrackkibet** [comment]
dlgSummaryofDailydata

**Comment by AlexSananka** [comment]
deleting these now,in case there are others just keep adding

**Comment by AlexSananka** [comment]
We also don't need sdgOneVarUseModBootstrap

**Comment by dannyparsons** [comment]
Is this done now?

**Comment by lilyclements** [comment]
Yes, @AlexSananka fixed most of these in #3839 however, I believe sdgOneVarUseModBootstrap still needs to be deleted

**Comment by AlexSananka** [comment]
Yes that needs to be deleted still, @dannyparsons merged the pull request I was using to delete this before I delete this.

**Comment by lilyclements** [comment]
You can still delete on the same branch and create a new pull request?

**Comment by AlexSananka** [comment]
Yeah I will

**Comment by AlexSananka** [comment]
This should be closed.
