### ISSUE TITLE
rollapply - bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3817]
We get an issue where using `rollapply` (from the `zoo` package) if the width of the rolling sum is greater than the column length. By "column length", I mean, the variable after manipulations are used.

So this was first noted with the Western Kenya dataset. In here, there is only one rainfall value for 2007 for NANDIHILLS.
This causes a bug if I use `rollapply` (with a width greater than 1) by Year and Station. Therefore, this problem is found at least in four of the climatic dialogs I've been on, and perhaps others?

There is a different package which doesn't bug and will instead give a `NA` value in this situation, this is 
`RcppRoll` and it uses different functions depending what function you want, (e.g., `roll_sum`, `roll_mean`, etc).

**Comment by dannyparsons** [comment]
Sounds like RccpRoll is a good choice then. Would be good to see if there's any online discussion to know of other differences in the packages as there seems to be quite a few ways of doing this.

**Comment by lilyclements** [comment]
Great. I'll look into it a little more
 So, for Start of Rains and End of Rains, this is an easy transfer since it will always use `roll_sum`
It isn't a quick change for Transform because currently it's running `rollapply(... FUN = ...)` for the different functions. This may not be necessary, however, if we don't need to do by Year and Station - but just by Station. This can all be discussed after 0.4.1.

**Comment by dannyparsons** [comment]
Great yes let's do this directly after 0.4.1. As long as we know the issue we can explain it if it happens to come up before then.

**Comment by lilyclements** [comment]
I've started to add this in to Start and End of Rains. Can you add the RcppRoll package?

**Comment by dannyparsons** [comment]
This is now added.
