### ISSUE TITLE
Climdex Fixes

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3824]
A few things are required for Climdex in the R-Code.

One bug to fix is that when you run this code the first time, the row numbers become the respective years. The second time you run this, the row numbers revert back to 1,2,3,...,n

Should we add other problems with climdex r-code here? Or should we do that in another issue?

**Comment by dannyparsons** [comment]
I think this can go in the general climdex issue unless its too long and messy already.

**Comment by dannyparsons** [comment]
yes I think that's fine together
