### ISSUE TITLE
Column Statistics extended

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3845]
This dialogue is working well.
The first extension is to add proportions and percentiles.  This might be on an additional tab.  It could perhaps be similar to what is offered in the old Instat.
The second is to extend the options for missing values.  The 2 options currently are what is offered by R as standard.  This is first to give a summary as missing if any values in the calculation are missing.  The second is to only make the result missing if all observations are missing (or so many that the calculation cannot be done.
It would be good to add an intermediate case.  This is to give the result as missing if more than a given fraction (or number) are missing.  For example if more than 3 observations are missing, or more than 10% are missing.  This might add yet a further Missing tab to the Summaries sub-dialogue (or it could be a separate button.)  That might be like Facets in the graphics where there is an initial checkbox labelled:
Missing value options.  If checked the dialogue opens.  There are 2 radio buttons for **Number** or **Percent**.  If Number there is an up-down.  Text says "Summary set to missing if more than this value are missing."  The number for the up-down starts at 0 and is up in 1's with no upper limit.  Default is 3.
The percent starts at 0 and is up in 10s to 90.  The limit if you type in which you can is 99%.
When these are set the number of missing (and the total number) are always calculated (as well as the other statistics.  Then the result is set to missing if needed.

**Comment by shadrackkibet** [comment]
@dannyparsons is percentiles and proportions ready to implement in this dialog?

**Comment by rdstern** [comment]
There are also some other summaries we could add.
1. Make the sub-dialogue a bit wider.
2. Move Range to after Maximum.  It is (after all) just the (Max-Min)
3. Add the quartiles, but separate them, i.e. Lower Quartile, Upper Quartile  and implement them.
4. Put Variance before Standard Deviation.
5. Add Coefficient of Variation - it is just 100*s/xbar  (of course missing if xbar =0)
6. If you are feeling a bit ambitious you could also add skewness and kurtosis (3rd and 4th moments).  This needs a bit of thought on which ones to add.  I suggest you could be consistent with SPSS and SAS perhaps?)  You could look at [https://www.researchgate.net/post/Different_result_of_skewness_and_kurtosis-any_thoughts](url) 
There are various packages and I suggest R package e1071 looks good - use type = 2 in their skewness and kurtosis commands.  (It isn't important enough a topic to allow options - which they do.)

**Comment by rdstern** [comment]
When this becomes a tabbed sub-dialogue - with Missing and Proportions as the 2 tabs, then the main sub-dialogue will have all the statistics.
Perhaps at the bottom there could be 2 checkboxes - one for each of the tabs.  One says Missing Options and the other says Proportions.  Initially they are unchecked and also visible but disabled.
When you go to the Missing, or Proportions tab it says initially Missing options - just as it does for the Graphics > Facets tab.
When you tick this checkbox it also checks it on the main sub-dialogue.  Then you can set the missing options on the tab.  Now the missing (or proportions) checkbox is available.  So you can see on the main sub-dialogue that you are using these, and can turn them off there if you wish.  
If you un-check this checkbox, it also unchecks on the tab.  But it might keep the settings within that tab.  Then, if you check again, it is all as before?

**Comment by shadrackkibet** [comment]
working on this at #3854

**Comment by rdstern** [comment]
I am now wondering about adding a further tab to the sub-dialogue.  Good to discuss with David/Danny, because this is an important dialogue for us.
It would be a **More** tab. There could then be 3 sections on **Scale**, **Skewness** and **Kurtosis**.

This would have the advantage that we could move some summaries from the main sub-dialogue.
We would leave the quartiles and the interquartile range on the main sub-dialogue.  But the skewness and kurtosis would all more to the **More** tab.

1. Under the **scale** group we could have Coefficient of Variation (cv) first. 
2. Then we could have **Median Absolute Deviation (mad)**.  (This is in the R **stats** package.)
3. For reference (in case anyone is curious) I am suggesting we don't bother - now anyway - with the mean absolute deviation.  This is available as function aad in the lst package, but I don't think it i sufficiently important to warrant that package.
4. More interesting are **Sn** and **Qn**.  That are in the robustbase package that we will be using (soon) for a number of other things.
5. Now in the skewness group we have the skewness mentioned above, from the e1071 package.  This has 3 options and we just include option 2 - for consistency with SAS and SPSS.
6. We also have Medcouple (mc) from the robustbase package.
Perhaps this doesn't need a group box, just the 2 entries side-by-side
7. Then we also have Kurtosis again with option 2 from package e1071.

**Comment by rdstern** [comment]
This new dialogue looks really good.
Except I don't like a tab in the sub-dialogue with a single checkbox.

What I was hoping for was a single extra tab called perhaps **More**.

This has a box labelled **Scale** with the 4 measures you have there, under the Scale Tab.

Under that is the Skewness checkbox
And then the Kurtosis checkbox

There is no real hurry on this.  We will have a Version 0.4.3 by the end of next week (I hope) and it could be for then.

**Comment by shadrackkibet** [comment]
@dannyparsons  this can now be closed.

**Comment by rdstern** [comment]
I have realised that there is still an important option missing from the More tab.  It was only mentioned briefly above.
I hope this will be very simple to add.  You already have Qn and Sn from the robustbase package.  We need to add mc to the measures of skewness.
I suggest as follows:
a) The first 4 statistics are all about Scale.  So put a box round them with the label Scale.
b) Now there will be 2 measures of skewness.  So have a box with the label Skewness.  In this box there are 2 measures.  The one you have already- also called Skewness, but add (3rd moment), so it reads "Skewness (3rd Moment).  Then the other one is mc.
c) Then move the kurtosis down.  This doesn't need a box, because there is only 1 measure.

Those are the main changes for now.  I have one more in mind, but that takes a bit longer to think out.

**Comment by rdstern** [comment]
OK, what I wanted is easier than I thought!

Here is a reference: [https://www.stat.nus.edu.sg/~stazjt/teaching/ST2137/lecture/lec%206.pdf](url)

So for now we will have the first block in the More tab, with the label **"Location"**
So the 3 blocks are (in turn) Location, Scale, Skewness and then there is the single measue of Kurtosis.
The main (perhaps only) measure of location is called the "Trimmed mean".  As usual, just a checkbox, but followed by "Fraction Trimmed".  This is an up-down control into which you can type.  Lower limit is 0 and upper limit is 0.5.  It moves in steps of 0.01.  The default is 0.  ( That's the ordinary mean).
The function is in Base R.  It is just the mean function that is already used.  The second argument is "trim".

**Comment by shadrackkibet** [comment]
@dannyparsons  i am not sure how we can implement the summary "Trimmed mean" in our current way we do summaries. I have checked our mean function and it has `trim` parameter  with default as 0. Is it possible  to pass this value using a control? Here is the screenshot of the subdialog:
![image](https://user-images.githubusercontent.com/26301973/30911934-4531517c-a393-11e7-895e-b4445cfd4271.png)

**Comment by dannyparsons** [comment]
Yes just pass it through to the method and it should just work. As long as trim is a parameter of `summary_mean` as well and this is passed through.

**Comment by rdstern** [comment]
This is looking good.
Can you change the order, so Location is on top and Scale is below - before Skewness.

And the m in mc is in lower case

**Comment by shadrackkibet** [comment]
@dannyparsons This is now done.Can now be closed.
