### ISSUE TITLE
Sorting Columns for Climatic

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3846]
This isn't too big of a problem, but a request from Francis which I agree would be useful.

I may run Start of Rains, and then it only gives values for my years without NA's as their start date.
This means some years are missing.
e.g.

> 1935  78
> 1936  61
> 1938  72

Then I may run End of Rains.
If this now gives values to the years which were NA in Start of Rains, their years are added to the bottom.
e.g.

> 1935  78  212
> 1936  61  244
> 1938  72  234
> ... 
> 2013  88  299
> 1937 NA  222 

It was requested that this is sorted in order of year and I agree.
It would be great if this "sort" was automatically run in the code. However, the part I'm unsure of is that I have to sort the data frame after running my codes, ergo I have to sort the data frame for "Dataname_by_Year" (or by_Year_by_Station, or by_year_by_station, etc) which I don't think is possible to call because I'm currently working on "Dataname",

Am I missing a really simple way to do this?

It's not a huge problem and the user can sort it manually. However, it would be nice if this could be automatic.

I know that we have this problem of not being able to call Dataname_by_Year for if the user wishes to set a prefix to their column. (It doesn't create a prefix because it's looking for a column called "start" in the current Data frame despite that it will place the new column in Dataname_by_Year).

If this "sort" issue were to be something that could then be fixed when that problem was fixed, that would be great.

**Comment by rdstern** [comment]
If there are NAs in the data then (I hope the start of the rains gives NA.  I would still like it to give the result (including NA for each of the years.  Same for the End of the rains/season.  Then thisproblem would not exist.

The second possibility is that there isn't a start to the rains - no missing, but the criterion is never satisfied.  The old Instat gave zero there and that was a problem.  Once we have multiple missing values in R-Instat I would like to use a different missing value code for those instances.  It might be labelled None.

**Comment by dannyparsons** [comment]
The issue of years not appearing is because after initial filtering on the daily data you might get no records for that year, which mean it then doesn't appear in the summary. We have an issue written on this somewhere that I can't find but `tidyr::complete` can solve this.

This would prevent the issue in many case, so that unordered years was less likely. I think if we solve this then there then any kind of automatic sorting, which is more tricky, probably becomes less urgent.

**Comment by lilyclements** [comment]
I see a bigger discussion on this issue in general here #3394. I assume that's the issue that you were referring to too. In that issue, you suggest that it is fixed in the summary system so I'll close this pull request since the solution is a duplicated issue elsewhere!
