### ISSUE TITLE
Climatic menu - minor changes

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3853]
Change **Climatic > Prepare > Display Daily Climatic Data** to just **Display Daily**, i.e. delete Climatic data.
It is the same dialogue as **Climatic > Check Data > Display Daily**.
I am happy for it to appear twice.
Delete **Climatic > Prepare > Summary of Daily Data**.

**Comment by shadrackkibet** [comment]
working on this.
