### ISSUE TITLE
Opening multiple files at once

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#3857]
From the workshop experience, there is a feature that would be great to include in R-Instat in the future. his is being able to Open/Load multiple files.
In the case of our workshop, we had six datasets(all from Excel) but it was really annoying to load one at a time

So from File>Open from File the dialog that appears should enable selection of multiple files of the same time so that they could be loaded at once.

**Comment by rdstern** [comment]
I sort of agree, but am not completely convinced by this.  I would like to be able to open multiple sheets (when appropriate) from an Excel file.
In (for example) the Sudan data for the MICS survey there are 6 files.  This is a bit of a pain.  But a solution, if this is to be used, is to import them (even one-by-one) and then set up the links and then save them as an Instat object.  
In examples I have used, thism works ok, and the resulting rds file is about 10% of the size of the other files together.  That is how users then have an easy life.  If we make it too easy to import, then they are more likely to just keep the data as SPSS files and import every time - avoiding links and other simplifications that can arise from looking at thee data "properly".

So support the request, but as part of an important discussion.

**Comment by dannyparsons** [comment]
The example was actually csv files, not Excel files. I think if we have this feature it might only be for files of the same type. Because you might need to be careful importing files in different formats using different options. I think multiple importing only really works when you have files in a consistent format.

**Comment by shadrackkibet** [comment]
The duplicate issue here #5789
