### ISSUE TITLE
dlgAppendDatafreames

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#3858]
This resets the receiver on re-opening.

**Comment by AlexSananka** [comment]
Just tried looking at this and realised some other dialogs are behaving like this,I have seen dlgDeleteDataframes and dlgdelete rows/columns.

**Comment by dannyparsons** [comment]
now fixed for append. I think for deleting/renaming dialogs we decided that we would always clear on reopening otherwise we are likely to have receivers containing objects that no longer exist.

**Comment by AlexSananka** [comment]
It's good that  you fixed it,we were fixing this with @Lunalo .Lack of internet has costed us.
