### ISSUE TITLE
Viewing applied filter in dataframe

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#3859]
Another feature that from the workshop came out clearly we need is being able to view a filter that has been applied.

**Comment by rdstern** [comment]
That's great.  Delighted.  Filters are a key and excellent feature for us.
I recently had another issue on filters #3736.  This includes adding OR in the condition.
And not just viewing a filter, but also being able to edit a filter - or at least (perhaps) add another condition.

If your request here is combined with the earlier issue on Filters, perhaps this one could look more generally at Objects?

Can we also generalise this.  We have objects of which the filters are one type, then we have calculations - closely related to filters.  And graphs and models.  What else?

So, in the current Prepare menu we already have **Prepare > R Objects > View**, and also Rename, Reorder, Delete.

**Comment by maxwellfundi** [comment]
great, i can add this on the earlier issue

**Comment by maxwellfundi** [comment]
I close this now as i have combined it with  #3736.
