### ISSUE TITLE
Adding a further option to the single receiver?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3884]
When I use the Describe > View Graph often the only graph to view (in a given data frame) is last_graph.  I wonder why it isn't automatically put into the receiver? (I like it that our climatic dialogues help me by completing some of the fields in the single receivers.)
  
I assume this applies to many dialogues that use the single receiver? I also assume that sometimes even if there is only one eligible column we may not want to assume it goes into every single receiver?  So I guess the VB code has to give an option and we would then go dialogue-by-dialogue, where we either "opt-in" or we "opt-out"

**Comment by AlexSananka** [comment]
So what happens if you may happen to have more than one graph?say you didn't save your graph and it's last graph and then again you saved another graph say two-var-graph so when you go to view graph you will  have two graphs in the selector.In this case which one will be auto filled to the receiver?

**Comment by dannyparsons** [comment]
This is exactly what our autofilling can do. So a single receiver can be set to auto fill and when there is only one valid item in the selector it will fill in.

@AlexSananka when there's more than one item, the autofilling doesn't do anything.
Can you set the autofilling for this receiver?

**Comment by AlexSananka** [comment]
I have seen @lilyclements have made changes in this dialog at #3838.Making other edits on this will definitely cause conflicts.

@lilyclements do you mind doing this on the same pull request?
