### ISSUE TITLE
Date issues including Make Date dialogue with data from Bangladesh

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3906]
[Rajshahi.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/1292088/Rajshahi.xlsx)

These data are not (yet) to be shared, or put into the library.  But they illustrate (to me some "interesting" issues still with dates.
The file imports fine.  Our **File > Open** has been working well!
Then I noticed that the date is given in 2 alternative ways in the file.  Neither are recognised (yet) by us.
1. On the positive side I can proceed with the existing Prepare > Column: Date > Make Date dialogue.  So I can suggest a "work-around" if needed.  But it would be good if we could cope even better!
2. I first looked at the Datetime column.  This is not (yet?) recognised by our Control.  I assume i9t is a Datetime column  and we are not yet including types of data we don't recognise?
3. It is "interesting", because it is a datetime column, which IS just the date.  So it could perhaps be recognised as such?
4. I changed it into a text column.  Then I made it a date and that worked fine - that's my work-around!
5. Then I looked at the Julian date column.  This roughly in the format "year"+"dayofyear", i.e. the first value in the file is 1984001 for 1 Jan 1984.  I assume sometimes it may be given as a 2-digit year which could be confusing in some instances.  But it is easy here.  I assume there are functions already written for this in the R-packages we use?  It would be a good option to add to the conversion of a single column into a date.

**Comment by rdstern** [comment]
I now notice another issue with the file I have just sent.  The julian date column and the column called Datetime are not consistent with each other.  I assume the Julian date column is the correct one, because that one is in order, but I will check.

So I DO want to use the Julian date column to convert into a date.  I therefore made the Julian date column into a text and then took the sub-string that was just the day in the year.  Then I used the Make Date dialogue with the 2 columns of year and day in year.  It worked fine!  And gave me the correct date column (I think!)

I then had a small issue (not with dates, but with the View in R (i.e. right-click)  I note here, but it may need to be a separate issue.  When I used the View it didn't seem to give me that last column, that I had just generated.  Perhaps this was an aberration on my part?  Anyway, I then changed the order of the columns and it was fine.  So I just report that curiosity for now.

**Comment by dannyparsons** [comment]
You can convert the `JulainDate` column in one step. 
In the Make Date dialog select Single Column then check "Specify Format" then in the combobox type in your own format "%Y%j". This should work. It's not easy if you don't know the format but we tried to make it easier by having the description text box and an additional help button for the R help on date formats.

Interestingly the Datetime column has imported as a POSIXct,POSIXt which is basically a date column but can have a time and a time zone. We didn't want to get into the mess of this so it isn't recognised as date. But we should at least be able to convert it to Date without making it a character first.

**Comment by dannyparsons** [comment]
On the View window, I think it doesn't show all column by default but enlarging the window should show more columns.

**Comment by shadrackkibet** [comment]
@dannyparsons can this option be added on the drop down so that it is visible to the user instead of typing `%Y%j`?

**Comment by rdstern** [comment]
Agreed.  As we get more examples I would like to take the opportunities to add to the set of predefined formats.  So that would be good.

**Comment by shadrackkibet** [comment]
@dannyparsons this can now be closed.
