### ISSUE TITLE
CM SAF > Plot Region dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3908]
This is the dialog needed for the Germany meeting. It is new dialog on the climatic menu under `Climate > CM SAF > Plot Region...,` where `CM SAF` can go below `PICSA` for now.

This is only really a demonstration dialog at the moment to show that we can have the functionality of the CM SAF R Toolbox (http://www.cmsaf.eu/EN/Products/Tools/R/R_node.html) which has functions to produce output from Net CDF files. 
So this dialog will implement their plotting of a region for a single time point. I have written an R function called `plot_region` in the stand_alone_functions.R file which is an adapted version of code in the CM SAF R toolbox.

The main dialog is fairly simple: 
4 single receivers, latitude, longitude, element and Date.
Under the Date receiver is a DateTime picker to choose a date. I have not yet implemented this as a core control yet, but see the Open Net CDF sub dialog for how to use the DatePicker at the moment, it's simple because it's done manually.

We may want things like auto filling and setting limits on the DateTime picker but this isn't urgent for the meeting, just a demonstration of something that works is needed.

There will be many other options on the sub dialog. I will specify this below but the main dialog is the most urgent to get working.

To test you need data with all four of those columns in the format that we import NET cdf files. Attached is an example which could be used for initial testing.
[SISmm_1983.2015_nc4.zip](https://github.com/africanmathsinitiative/R-Instat/files/1292715/SISmm_1983.2015_nc4.zip)

**Comment by dannyparsons** [comment]
You will need to install the following R packages to get this working:
```
cmsaf
maptools
RColorBrewer
colorRamps
mapdata
rworldmap
rworldxtra
```

**Comment by dannyparsons** [comment]
The sub dialog has the following options where the parameter names are in brackets:

On one tab

1. Add to title (add2title): textbox for title text (default blank)
2. Min Longitude (lonmin): numeric textbox (default NA)
3. Max Longitude (lonmax): numeric textbox (default NA)
4. Min Latitude (latmin): numeric textbox (default NA)
5. Max Latitude (latmax): numeric textbox (default NA)
6. Plot height (height): numeric textbox (default 600)
7. Plot width (width): numeric textbox (default 600)
8. Plot Anomaly (plot.ano): checkbox (default FALSE)
9. Set Colour Breaks (set.col.breaks): checkbox (default FALSE)
10. Min Break Point (default 240), Max Break Point (default 340), Interval (default 5) - three numeric textboxes which create the parameter: `brk.set = seq(240, 310, 5)`. These are only visible when Set Colour Breaks is checked
11. Colour Bar Min (colmin0) numeric textbox (default NA)
12. Colour Bar Max (colmax0) numeric textbox (default NA)
13. Number of colours (ncol) nud (default 14)

On the second tab:

1. Plot High Resolution (plotHighRes) checkbox (default FALSE)
2. Plot Coast Lines (plotCoastline) checkbox (default TRUE)
3. Plot Countries (plotCountries) checkbox (default TRUE)
4. Plot Rivers (plotRivers) checkbox (default FALSE)
5. Plot Cities (plotCities) checkbox (default FALSE)
6. Thickness (contour.thick) nud (default 2)
7. Size of cities (cex.cities) nud (default 1) only visible if Plot Cities checked
8. Label Cities (label.cities) checkbox (default TRUE) only visible if Plot Cities checked
9. Plot Capitals (combo box) with parameter/display items: 0 = "no capitals", 1 = "country capitals", 2 = "provincial, state, regional capitals", 3 = "local capitals" (default 1)
10. Size of city labels (cex.label.cities) nud (default 0.5)
11. Latitude offset of label (dlat) nud (default 0.25)

I haven't thought much about design so feel free to suggest something different if you think it could be better.

If any options are difficult then don't spend a lot of time on them, but it's important they are at least visible on the sub dialog.

**Comment by shadrackkibet** [comment]
working on this.

**Comment by dannyparsons** [comment]
One more checkbox for the sub dialog: Plot Own Locations (plotOwnLocations) this can be disabled for now but the default is FALSE.

**Comment by maxwellfundi** [comment]
And on this sub dialog, what should be the titles of the two tabs?

**Comment by dannyparsons** [comment]
"Layout" and "Additional Features"

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers This is now looking good and an exciting new feature for us to have, well done Shadrack and Maxwell. It's really only a demonstration for use with NET cdf file output at the moment so here I'll explain the sequence of steps to use the dialog starting from the data so you can try it out and understand the use better (once Shadrack's code is merged).

1. Import data from a NET cdf file. I will send a file separately you can work with which has monthly mean radiation values at equally spaced locations for the whole world for 2015. NET cdf files are extremely efficient on storage so if you try to import the whole file it will likely crash because it's just too large for R to handle. So when importing go to the Options sub dialog where you can choose to import a subset of the file. Select a small region to import by choosing a latitude and longitude range. For example, lon 32 to 44 and lat -5 to 5 will include Kenya. You can choose the time range as well, for the plot you only need one point but you can select more if you like. I chose 1 December 2015 for min and max.

2. Once this is imported now use the Plot Region dialog to plot the radiation values for the region you selected. This only plots one point in time, so after filling the receivers, choose a time point from the data picker that is within your data. (There are currently no dialog checks to make sure the Date is within range.).
You should then get a nice plot of your region with a sensible colour scale for the radiation values.

The code for this comes from the CM SAF R Toolbox (http://www.cmsaf.eu/EN/Products/Tools/R/R_node.html) developed by EUMETSAT, slightly modified for R-Instat. They currently have it as an R script which is set up for people to use without needing to do much R code. In Germany, we will present this as another potential way for people to use their code i.e. through R-Instat as well as RStudio. If they like it, then we may work together to implement more of their scripts into dialogs in R-Instat.
