### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3922]
The released versions now have the nice R-Instat icon in the top left corner. This should be in our current code, not just added when an installer is made.

**Comment by rdstern** [comment]
It is excellent to have this icon now.  However the Instat part is very light blue and is hardly visible sometimes.  Could that be changed to be darker, or to stand out better in some way.  I am happy the emphasis is on R itself, but it is a bit confusing to have it to this extent.

**Comment by dannyparsons** [comment]
Was it @myleskg who created the icon originally?

**Comment by dannyparsons** [comment]
@maxwellfundi The old icon is still showing in the current code. Can you replace it in the project?
