### ISSUE TITLE
Plotting by dates

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3925]
I have called this a bug, and think there should be an easy fix, even if temporary.
We were asked for a plot of temperatures, etc where the x-variable is a date column.  We will be doing some of these in the quality checking in the climatic, but they should also be allowed in the ordinary graphs.  

Currently we only allow certain types of column as the x-variable for the graphs.  I am thinking of line and scatter-plots.  We have discussed on occasions that R has many types of column and perhaps we should exclude the types we don't want, rather than include the types we do want.

That is longer term.  I would like a quick fix (also).  I suggest we consider the following:
a) Date is a special sort of numeric column.  Isn't it?  Could we therefore include date columns generally, whenever we include numeric columns?  (Would that do any harm? 
b) there are lots of types of column in R.  But there are only a few that we **produce** in R-Instat, and Date is one of them.  So if we have other types of column that have been imported, we can always change them into one of our limited types if we want.  But we want to leave a date type as it is, because of other properties.  So, in a sense date is special.
c) A more general fix - while keeping our current way of working could be to have a right-click option to "Show all Variables" - if we wish.  Or we could have that under the Data Options button.

**Comment by dannyparsons** [comment]
The correct fix isn't too difficult so I think we could do that over a short term solution. However, if we run out of time before its really needed then a) is quick to do.

**Comment by dannyparsons** [comment]
Dates are now considered numeric so this should be ok now
