### ISSUE TITLE
line plot and scatter plot with fitted line

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3931]
1. The **Describe > Specific > Scatter Plot** dialogue has a checkbox for the fitted line.  Could you please add this to the **Line Plot** dialogue as well.
2. When you tick that option (in either dialogue) it should also make visible another checkbox (default is unchecked) with label "with ses"  or in full "with Standard Errors".  Default is unchecked.  If it is unchecked then the geom_smooth adds the extra argument "se=FALSE".  If checked, then what you do now is fine.

**Comment by dannyparsons** [comment]
@maxwellfundi this should be straightforward?
