### ISSUE TITLE
Line plot 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3932]
[ThreeStns_by_Year2.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/1309247/ThreeStns_by_Year2.xlsx)

In this file I use a line plot of **MeanTmax** against **JYear** with the factor **ID**.  I also tick the box to add the points.  It works fine.

I return to the dialogue.  There I click on **Options > Layers > Add**.  

![error_in_plotting](https://user-images.githubusercontent.com/11226469/30523479-f9ac8f48-9bd9-11e7-8e87-78e22bf80266.jpg)

I try again after reset, etc, but fail to be able to get past this point.

Same issue with histograms, and with dot plot, rug plot, bar chart and cumulative plot

**Comment by rdstern** [comment]
I was able to get to the Add Layer from the scatter plot dialogue, though it looked as though there might have been a message when I click the Add, before it gives the sub-dialogue.
I notice that once I have got there it insists on adding a Layer.  I don't know how to return without an extra layer, though I can delete the additional layer if I wish.  I think this is how we sometimes get added boxplots, because that seems to be the default.

Sometimes when I have the extra boxplot layer added and then try to remove it, I get the message that I can't because it was created on the main dialogue.  It wasn't, because that was the scatter plot dialogue. 
![error2_in_plotting](https://user-images.githubusercontent.com/11226469/30524000-76d4f402-9be3-11e7-9b2f-955e78147b89.jpg)

**Comment by maxwellfundi** [comment]
@dannyparsons I dont remember why the layers from the main dialog could not be deleted. Do you remember that?

**Comment by dannyparsons** [comment]
Yes because you can't go to the Line Plot dialog, delete the line layer and then add a boxplot layer because then it's not the line dialog. You can do all that through the general.
The point @rdstern was making is that I think he couldn't delete some of the additional layers from the sub dialog, which should be possible. If that's working then this is ok.

**Comment by rdstern** [comment]
The problem is also related to the fact that (I think) the code sometimes gets the layers "the wrong-way-round".  So an additional; layer is thought later (when you return next time after the plot) to be the base layer.  
That swapping also may be the reason that when I added jitter to the boxplots the jitter was underneath and the boxplots were done second.

**Comment by dannyparsons** [comment]
Yes, I think that is the issue with deleting. Maxwell - I don't quite understand:

>  a layer made on the layer options dialog which has been made when you come from the main dialog

But just to be clear, the layer(s) created on the main dialog, usually one, sometimes two (like line + points), cannot be deleted. But any layers added after that should be delete-able, even if it's another layer of the same type.
