### ISSUE TITLE
plotting adding geom_smooth

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3933]
This isn't there yet.  Can it be added?

**Comment by dannyparsons** [comment]
Yes I think @maxwellfundi can add this to our list of geom definitions.

**Comment by maxwellfundi** [comment]
yes its been added just testing and adding appropriate parameters.

**Comment by rdstern** [comment]
Is it still coming in Version 0.4.7?

**Comment by maxwellfundi** [comment]
Yes it is. We have been discussing with @dannyparsons  about it actually and the issue it has is a general issue.

**Comment by rdstern** [comment]
Can this issue be discussed with David?  Danny is pretty busy just now.  It would be great to get this feature working.
