### ISSUE TITLE
plotting adding equation on the line

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3934]
There is a package called ggpmisc which has some useful additions to ggplot2.
One that we have been asked about is a stat to add the equation of a line to geom_smooth.

I am not sure we have a system to add stats?

A default version could perhaps be on the main dialogues of scatter plot and line plot

**Comment by Ogik99** [comment]
Issue #5037  addresses similar concerns.  There's an open pull request #5132 which tries to resolve this issue.
