### ISSUE TITLE
Define climatic data

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3935]
Currently I think the date column is added to the define climatic data dependent on its name and irrespective of its type.  We should only add it, if it is a of type Date.
We should also perhaps only add the station if it is a factor.

**Comment by dannyparsons** [comment]
Yes we should, so as well as the auto fill options, the date receiver should be restricted to columns of type Date. This causes errors later when this is the wrong time.
Station is preferable as a factor but I don't think causes as serious issues if it isn't, so not sure we have to enforce that as strongly.

**Comment by shadrackkibet** [comment]
@rdstern  which data did you use to check this?. Dates Seems to be working fine for me.

**Comment by dannyparsons** [comment]
It's not a specific data set issue. For example, take the Dodoma data set and in the define climate dialog put the Rain column under the Date header. This is allowed. Then this causes issues in other dialogs like inventory plot when your date column is actually the rain.

So to solve this, the date receiver on define climatic should be restricted to date columns.

**Comment by shadrackkibet** [comment]
The date receiver is already restricted. Can't see where Rain column is allowed into date receiver in this dialog..

**Comment by dannyparsons** [comment]
Ah ok, I think this has been fixed recently, so nothing to do, sorry!
