### ISSUE TITLE
Tools menu with option for user menus

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3941]
Could we please have a discussion on the tools menu.
It currently has a variety of useful sounding items that are yet to be enabled.

And a particular item I would like to resolve is the special menus, namely now climatic and procurement.  We need to have a facility to show or hide them.  We were asked about this point at the recent workshop.

My suggestion is that we keep this aspect very simple for now and also very visible.  So we have a line below the current Options entry.  Below that we have **Climatic Menu** and then **Procurement Menu**.  When ticked they are visible and otherwise they are hidden.

Later we may want to move this down a level and be able to show or hide specific dialogues.  But this is currently an important component of R-Instat so we make it clear for now.

**Comment by rdstern** [comment]
In the items above for the tools menu, the urgent item is a way to show/hide the special menus.  These are Climatic and Procurement for now, but there will be more.  
Danny is keen that this be an easy process and not merely hidden deeply in the Tools > Options menu.

I would at least like it somewhere soon, and happy with the simplest way possible.  One obvious place is the View Menu, where there could be a bottom section saying just Climatic Menu and also Procurement Menu.  You tick or not this option just as you do for the Windows.  I would be very happy with this as a solution.  It would make good use of the View menu, becvause now all the other items there will be on the toolbar.

**Comment by dannyparsons** [comment]
I was wondering about something a bit like this:
![image](https://user-images.githubusercontent.com/11214914/31229387-6e0b5ea8-a9d8-11e7-843c-ee56f9871899.png)

Where the plus button is how you can hide/show special menus, either as a drop down menu or leading to the section of the Options dialog. Not sure if plus is the right symbol or if this is any better than having it on the VIew menu but just something I thought as a way of having it on the menu itself.

**Comment by rdstern** [comment]
I have no strong views.  I'd be quite happy with it here.  It may also be the sort of thing David has strong views on?  If it was this (and a +) then perhaps it would be a little smaller, but I like the symbol.  If all the optional menus were visible would it change to minus!

**Comment by dannyparsons** [comment]
The first step is to have this in the Options dialog which turn them on and off @maxwellfundi can you start with this? It should be simple to add these on the dialog.

**Comment by maxwellfundi** [comment]
So just to get clarification on this @dannyparsons . I have read the issue and i understand that @rdstern  would like to have this in the view which is great and i think it goes well with other windows. 
If we are putting this on the options dialog, are we having them hidden/shown by default?

**Comment by dannyparsons** [comment]
I'm happy with it in the View menu. But the main place is the Options dialog. We can then have "shortcuts" to this like in the View menu, but the functionality should be done through the Options dialog. And then we could use the same methods to have it in the View menu (or elsewhere) as well.

**Comment by maxwellfundi** [comment]
great that then means we will have checkboxes for each special menu so that its visible when the checkbox is checked? Is that what would be appropraite?

**Comment by dannyparsons** [comment]
yes. and default as checked for both...although once it is also on the View menu, we might change the default to be off for both.

**Comment by dannyparsons** [comment]
@maxwellfundi have you worked on this?

**Comment by dannyparsons** [comment]
Ok, this should be urgent as it effects the screenshots for documentation and also should be quick.
