### ISSUE TITLE
Describe>specific>summary...

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3945]
It took me a while before a get this dialog(Summary tables)  should we change the menu item to **Summary Tables** for now since we only have this dialog here. @rdstern ?

**Comment by rdstern** [comment]
Good point.  I would be quite happy for the 2 dialogues on **Describe > Specific** to be called **Frequency Tables** and **Summary Tables**.

**Comment by shadrackkibet** [comment]
@dannyparsons  this can now be closed.
