### ISSUE TITLE
Old display daily dialogs

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3949]
There are at least two old display daily dialog that we don't need. Can they be deleted?

**Comment by shadrackkibet** [comment]
sure, i had noticed this. I am going to delete them.Thanks.

**Comment by shadrackkibet** [comment]
There are other dialog like `dlgDisplayDoyofYear,dlgDisplayRainRunningTotal and dlgDisplaySpellLength` .I think we don't need them again.Shall i delete them?

**Comment by dannyparsons** [comment]
Yes please delete anything we don't use now.

**Comment by shadrackkibet** [comment]
Here is list of some of the forms we do not need again. @africanmathsinitiative/developers  can someone confirm this before i delete them?
 ```
- dlgDisplaySpellLength
- dlgDisplayRainRunningTotal
- dlgDisplayDoyofYear
- dlgDisplayDoyofYear,
- dlgDisplayRainRunningTotal 
- dlgDisplaySpellLength
- dlgGeneralRegression
- dlgGeneralTables
- dlgGoodnessOfFit
- dlgNaList
- dlgLines
- dlgMakeFactor
- dlgMissingValuesPlot
- dlgModelProbabilities
- dlgMonthlySummaries
- dlgMovingAverage
- dlgMultipleRegression
- dlgNewWorksheet
- dlgOutputForCDT
- dlgProbabilityPlot
- dlgRainStats
- dlgRainCount
- dlgYearRainCount.
```
- Renaming` dlgWaterbalance` to `dlgEndOfRainsSeason`.

**Comment by dannyparsons** [comment]
Nothing there looks like keeping. Especially if the designer is quite empty or clearly old then we don't lose anything by deleting. I think go ahead, we can always undo if there's a mistake.

**Comment by shadrackkibet** [comment]
@dannyparsons  this can be closed.
