### ISSUE TITLE
prepare>checkdata>Export to OpenRefine

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3951]
Could someone explain how this dialog should work?, Why do we need this? I haven't got this working for me.Everytime i use this i get a bug!
![image](https://user-images.githubusercontent.com/26301973/30708593-19616a94-9f08-11e7-860b-14a8a5aeca29.png)

**Comment by dannyparsons** [comment]
There is a software called Open Refine which does nice data cleaning. This dialog uses the rrefine package to export a data frame for Open Refine. However, you need the Open Refine software installed on your machine for this to work. I believe it should work when Open Refine is installed. You can try it if you like, but it's not an important dialog at the moment.

I actually just noticed that Import from Open Refine has a developer error when it opens. Could you look at this? Don't spend long on it so we might just disable something if that's the easiest way to fix it.

**Comment by shadrackkibet** [comment]
@dannyparsons the problem with this is using "NULL" as an R default.How can we deal with such a case?

**Comment by dannyparsons** [comment]
I think that control should not be set with validation as an R variable. Because NULL is only excluded when the control is used for an R variable name. If it's just a parameter then it shouldn't need that validation.
