### ISSUE TITLE
Undo - of sorts - using our backup facility?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3959]
One of the requests in the EUMETSAT meeting was an undo facility.
In the long run this is something we should consider as a general feature - even if it only works for certain actions.
However, we already have a 5-minute backup.  This is currently only accessible at the start of a session, but perhaps it could be made available more generally?  I wonder if the (5 minute) backups should anyway cycle - perhaps they do already, so there is always one from over 5 minutes ago and then also the most recent?
Then could we permit users to return to that - or to either of those - as an option.  Perhaps we have at last something for our edit menu, or it could go into Tools or File?

This would also become a useful place to include the help for the backup facility.

**Comment by dannyparsons** [comment]
While the software is running, we don't have to restrict ourselves to the backup log, since we've got the full log. So we could be more flexible, like running all but the last command, or all but the last two commands. But the general idea could be a good thing to do until we have a full system.

**Comment by rdstern** [comment]
I wasn't thinking of the backup log as much as the backed-up data.

**Comment by dannyparsons** [comment]
Oh yes, that's useful too. We only save one backup at the moment. We could save more - the only issue would be storage space but it will rarely be very large. Then it would be easy to access them and indicate the time it was backed up.
