### ISSUE TITLE
Position of calculated column in data frame

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3961]
My particular example is the dialogue **Prepare > Column: Generate > Count in Factor**.  This puts the calculated column at the end of the data frame.  I would almost always prefer it just after the factor.
We have this option for **Prepare > Column: Calculate > Duplicate Column**.

So, for **Count in Factor**, perhaps we could make it simpler and give the option "**After Factor Column**" or "**At End**".  If we do this, then perhaps we could check whether this option could usefully be applied elsewhere too.

An alternative would be to have a simple dialogue/right-click (maybe just right-click) which makes an empty column and gives it an unusual name, e.g. "_no_name".  It contains NA throughout.  If this column exists, then it is automatically filled with a new calculated column. 

This is assigned to Danny/David first, because it needs a discussion.

**Comment by rdstern** [comment]
I have discussed with Danny and thought a bit more about this topic.
It is an important feature for us, because we don't show all columns in a worksheet, if there are more than our default (currently 30).  So, with a wide worksheet you often don't see the new column you have derived.
I suggest we need another custom control here.  It could start perhaps with a reworking of the **Prepare > Calculate > Duplicate Column** dialogue that already has the feature.  I suggest the radio buttons be replaced by a drop down which is on the same line as the "New Column Name" field.  It just says Position:, because it will then be obvious that it refers to the new column name.  Then the 4 options, namely Beginning, Before, After, End, can be given as those options.  So there will be no difference for that dialogue.  
Then, for some dialogues the custom control could be the 2 fields together, i.e. the new column name and the position.
This is also a field where I wonder whether the chosen option might be "remembered" in other dialogues that use the control. 

There will be some exceptions that might make the code more complicated in some instances.  For example in the **Prepare > Column: Date >Make Date** dialogue there are sometimes multiple columns used.  Then **Before** is before the earliest of those columns and **After** is after the latest one. 

There are also a few dialogues where the names are given automatically.  For example Prepare > Column: Date > Use Date produces multiple columns.  Then the position is relative to the Date column.

**Comment by rdstern** [comment]
Danny and I discussed this possibility in more detail, ready for some work soon.  It would affect quite a number of dialogues, i.e. initially those that write new columns to the same worksheet.

W now propose a new button that becomes part of the user control that saves a new column.  It might be called Position, but ideally it could have a name that indicates something about where the column will be saved.  Imaginative thought is needed here!

It would open a sub-dialogue that allows the position to be specified.  
1. The name would be **"Position of New Column"**

2. We thought that could have 4 new-style radio buttons at the top, namely **Start, End, Before, After**.
3.  Underneath could be a field that gives a summary of what is happening.  e.g. **New Column will be at: Start**. This would change, depending on the button selected.
4. If Before or After are chosen then it opens our Data Selector (no Data Frame - just the columns - same as the data frame on the main dialogue.  There is a single receiver that is filled with a default column - if that can be detected, from the main command.  Or the user has to insert a column.
5. Then the usual Return and Help buttons.

There are 4 stages to developing this feature - after David and others have considered possible improvements:

1) Construct this sub-dialogue.
2) Add an optional button to the existing Save control and ensure it is consistent, within the existing control.
3) Link the Save Control to the sub-dialogue, i.e. get the sub-dialogue/save control to write the appropriate R code.
4) Link the Save Control to a default receiver on the main dialogue, to get the position of the column being use in that dialogue.  For example, in the Duplicate column it is the column being duplicated.

**Comment by Patowhiz** [comment]
@rdstern from the explanation above this will be the design. Would you like me to change anything?

![sdgcolumnposition](https://user-images.githubusercontent.com/21179007/44450068-a72cbe80-a5f8-11e8-97d4-20028963390a.JPG)

**Comment by rdstern** [comment]
Discussed also with Danny and we think it looks fine.  The initial default for the radio buttons is "After".  In operation I hope there will also be a way that there is always a default in the Column above, i.e. it is filled in. So the only time this is used is when we want to change from that.  There may be dialogues where there is no sensible After, and then the default would be End.  This would need to be set individually for each dialogue.

And the data frame is fixed of course - in the same way it is fixed when you go into the sub-dialogue in Filter.

On the main dialogue this is an extra button that becomes part of the user control for saving a column.

There are some dialogues that save multiple columns, e.g. Use date.  We'll consider those once something is working for the others.

**Comment by dannyparsons** [comment]
And just to be clear what it means by _The initial default for the radio buttons is "After"_. When we want the default to be After with a specific column, there would have to be something done on the main dialog to set the code to reflect this. Then if the sub dialog was opened, it would be reading the code and display After with the columns set in the code.

To do the code on individual dialogs we might want to add some functionality to the save control to do this. For example, link the save control to a single receiver which is the default After column, then little code would need to be added on dialogs. We would need to think carefully however, about how this works when the user changes the position e.g. if the user changes to End and then a new column is selected in the linked receiver, I would suggest this is not then set back to After. However, if Before was selected and then the column was changed, we probably do want to update the Before column (but not reset back to After).

**Comment by Patowhiz** [comment]
Okay. And the Data Options on this subdialog will be disabled

**Comment by rdstern** [comment]
Yes indeed!

**Comment by Patowhiz** [comment]
@rdstern @dannyparsons should the column selected on the receiver of this subdialog always change whenever the main dialog changes its selected column? I mean should the receiver of this dialog always show the column selected on the main dialog, even after a user launches the subdialog and changes the selected column?

**Comment by dannyparsons** [comment]
This isn't so obvious to me. I would probably say no for this specific case, but we might need to see how this works in practice. If the user has changed it to be before or after a specific column then I would say this isn't reset if the main dialog changes (unless Reset is clicked). That's generally how the dialogs work so it's a sensible starting point.

Remember, there are other cases where no column is selected (start/end) which also need to be considered, as I mentioned above. Are these also taken into account?

> We would need to think carefully however, about how this works when the user changes the position e.g. if the user changes to End and then a new column is selected in the linked receiver, I would suggest this is not then set back to After. However, if Before was selected and then the column was changed, we probably do want to update the Before column (but not reset back to After).

**Comment by Patowhiz** [comment]
In regard to the above, my fear is, If I was working with column say "Anne" and set I had set the column position to before "Anne". If I change the column I'm working on to say "Station", won't it be great if the before position goes changes automatically to before "Station" rather than stay at "Anne". @rdstern  I'm trying to look a t a scenario where the default won't be hectic for most scenarios

**Comment by dannyparsons** [comment]
This is what I think is sensible to start with:

- If the user hasn't opened the subdialog and changed column or position then when the main receiver on the main dialog changes, it updates the position.

- If the user has made any changes to receiver on the subdialog then that stays until the dialog is reset.

That might not be ideal in absolutely all cases but it is simple and consistent with other dialogs. It's better we don't try to be too clever and guess what the user wants in complicated situations. If it proves to be problematics we can adapt this later.

**Comment by dannyparsons** [comment]
Also there should be something to indicate the position on the save control. So if it's not what the user expects, they can see this and change it.

**Comment by rdstern** [comment]
I am still trying to catch-up, so this is partly to make sure I am understanding the discussion correctly.  On the main dialogue this is an extra button on the Save control.  Usually it isn't used, because the default is what is wanted.  And that default is **After**.  The reason this is more important here compared to other software is because of the limited window onto the dataset.  So, currently, when the calculated column is at the end, you don't see it.
So, if I have columns x1, x2, ... x31 and want to get a logical column after x1 (when I use x1 in say Prepare > Check Data > Non-Numeric Cases) then it comes after x1.  Then I return to the dialogue and use x26, then the next logical column comes after x26.
I may want them collected together, say all after x31.  Then I could enter x31 in the sub-dialogue, first time.  Now it would put the logical x1 after x31,  When I use x26 it doesn't change, so would remain after x31.  If I clear the x31, then we revert to the default.  So, if I clear the x31 before saving the x26 logical, then it reverts to the after, and is after x26.
So if I choose to select a variable in the sub-dialogue, then that is fixed, until I clear it, or Reset or we opt for Start or End, which would also clear it?
If I opt for End, (or Start) then it clears the column in the sub-dialogue.  The option may not even be visible.
Let's look at some other options:
a) Use Date.  Then multiple columns are produced, but all relative to a single Date column.  So the After refers to the Date column.
b) Prepare > Column: Calculate > Calculations.  Here I assume I click on columns in the selector.  If multiple columns are selected, then it uses the last one.  This also applies to Summary, etc, where it is the last main column (not including factor columns).  If it isn't sure, then they go (as now) at the end.  So, no columns selected in a calculation (or typing the column name into the calculation, puts the calculated column at the end.

**Comment by Patowhiz** [comment]
@dannyparsons something like what? We currently only have a button with text position.
@rdstern yeah that's how it's now implemented except for multiple receiver. I had not thought about when there are several columns selected. I'm changing that.

**Comment by dannyparsons** [comment]
I think we are in general agreement here. Just one point I want to question:

> If I clear the x31, then we revert to the default. So, if I clear the x31 before saving the x26 logical, then it reverts to the after, and is after x26.

I'm not sure about this. If you clear the receiver but you have still selected the **After** option then the subdialog is incomplete. We might want to give a warning about this and not allow the dialog to be run. If a new column is then selected on the main dialog, we could maybe have this selected, or keep it incomplete and the user has to redo this on the subdialog.
There's quite a few details to consider here but I think it's worth getting them right.

The dialog examples you gave will all be special cases, because they don't use the standard save control. We can still have this functionality but it won't be available immediately from this work.

**Comment by dannyparsons** [comment]
@Patowhiz this was mentioned in an [earlier comment](https://github.com/africanmathsinitiative/R-Instat/issues/3961#issuecomment-345528729)

> We now propose a new button that becomes part of the user control that saves a new column. It might be called Position, but ideally it could have a name that indicates something about where the column will be saved. Imaginative thought is needed here!

I was assuming you would attempt something on the "imaginative thought". We didn't have a clear way to do this but felt it is important.

**Comment by Patowhiz** [comment]
Probably @africanmathsinitiative/developers could come up with more ideas on this.

**Comment by maxwellfundi** [comment]
@Patowhiz @dannyparsons @rdstern  I wonder if something like "New Column Position" is good enough or it would be too big for the button on the control.

**Comment by dannyparsons** [comment]
@maxwellfundi we are looking for something that indicates what the position is

**Comment by maxwellfundi** [comment]
Like a number indicating the position or what do you mean?

**Comment by rdstern** [comment]
I would like to resolve this quickly, so the feature can be finalised.  The importance (to me) is that the current situation, where the calculated column is at the End is messy.  It would be messy for any software, but in R-Instat the "End" is not always visible.  Hence it sometimes is not clear that the command has done anything.

But back to the point about the extra button - which is attached to the control for saving the calculated column.  If we can't do any better, then I would be happy with the label **Position**.  This (at least makes it clear what its role is.  But it doesn't indicate the current setting.  For that you have to press the button - nice if you didn't need to.

So it could be **Position: After**, etc, but that's a bit long - so a big button.  Perhaps **Pos: After**, or **Posn: After** or **At: After**.  Or just **Start, Before, After, End** as the alternative label on the button.  Or how about **@After**?

**Comment by dannyparsons** [comment]
I agree this doesn't have to be done before this new feature is used, but we should keep considering this. I think it could lead to confusion otherwise because of our rules of when the reference column is updated.

Even **Pos: After** is not sufficient because you can't tell which column it is after, and that's important to know when it changes. Aside from **Pos: After Date** for example, which is too long I don't have a good suggestion yet.

**Comment by Patowhiz** [comment]
@rdstern  @dannyparsons  

This is how dialog that uses this feature will now look like. The code is ready with the main functionalities stated above. However, I'd like clarify on the part of state of controls, what should happen to the selector and the receiver of the subdialog when radio button start or end are checked. Should we be disabling them or should we be clearing the receiver. Of course we are already changing the underlying Rcode  for but what about the state of the 2 controls? 

![pos2](https://user-images.githubusercontent.com/21179007/45216889-cd19ba80-b2aa-11e8-8862-1564c4bd20f0.JPG)

**Comment by dannyparsons** [comment]
Looks good, I think selector/receiver should be disabled when start or end is selected. Not hidden because it might be useful to still see the data frame and columns on the subdialog.

**Comment by rdstern** [comment]
That looks good to me.  I would be happy to stick with that for now.
The position button should be made slightly thinner, so it is identical to the other part of the control.

Then I would be happy for now.  If you want to know what position, then you press on the button!  That's why it's there!  We want the main dialogue to be simple.

**Comment by rdstern** [comment]
Is this now ready, at least for some dialogues?
I see 4 situations where this control might "take over", at least partially.
a) **Simple situations**, e.g. **Prepare > Column: Date > Use Date**, and **Prepare > Column > Calculate > Duplicate Column**.  Here there is a single existing column and the calculated column is also a single one.  The dialogues that write more than one column are also "simple" in the sense that the calculated columns would all go together.
b) A situation, like **Prepare > Column: Generate > Enter**, where  there is no column to calculate from.  In that case would it be possible to detect the current position (variable) of the active cell.  Then that becomes the existing column.
c) Situation, like the Prepare > Column: Calculate > Calculations, where there could be 2 or more existing columns (in the calculator there could also be none!).  If there are 2 or more existing columns, then After is after the last of them, and before is before the first.
d) There are dialogues - at least the **Prepare > Column: Reshape > Summary** that usually write to another data frame - in which case the new control doesn't count.  But it can write to the existing data frame.  Probably ignore that possibility for now.

**Comment by Patowhiz** [comment]
This is ready, awaiting @dannyparsons further review. I understand it touches deeper code and he has to take time to probably carefully review. But once it's merged the dialogs that will use it, would probably just need 1 line of code.

**Comment by maxwellfundi** [comment]
@dannyparsons  Could you please have a look at this. This will need alot more time to test before release so the earlier we get this done the better.

**Comment by dannyparsons** [comment]
Good idea, I have another deadline today but will try get to it by tomorrow.
