### ISSUE TITLE
Column Statistics with missing values in the factor

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3972]
R-Instat is unhappy when a factor defining a summary contains missing values.  (This happened with the World Bank procurement data.)  It can't then do the key properly and complains.  There may be an obvious (general) solution to this, or there may be options, in which case there could be an additional control needed on the dialogue.
In the future there may be multiple different missing value codes.  Whether the solution - perhaps to add missing as another level to the factor can cope with this, will be another matter.

**Comment by dannyparsons** [comment]
Fixed by #4046. Once we get multiple missing values, that's a whole other issue.
