### ISSUE TITLE
Country Coloured Map Dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3973]
Following from #3937. I now have an idea for a first dialog for the Procurement menu for mapping. This will be for the simple country coloured map. I'm not sure where this will go in the Procurement menu at the moment, for now it can just go at the bottom. It will probably also go under Describe > Maps as it will be general.

The code for this map is quite simple but there are several steps.

1: `world <- ggplot2::map_data(map = "world")`

From the help, `map_data` "Easily turn data from the maps package in to a data frame suitable for plotting with ggplot2." So this is just getting the outlines of each country in a form that `ggplot2` can plot.

2: `merged_country <- right_join(world, country_counts, by = c(region = "country"))`

This joins our own data (`country_counts`) with the `world` data because the `country_counts` has the values for the colouring - see #3937.

3: `ggplot() + geom_polygon(data = merged_country, aes(x = long, y = lat, group = group, fill = count)) + coord_quickmap()`

The `x` and `y` are obvious, `group` is a variable from `world` and there is one group for each country, in `geom_polygon` this makes sure the points are connected in the right order, `fill` is a variable from `country_counts` for colouring the inside of the polygons.
`coord_quickmap` does sensible default scaling for a map.

I would like more flexibility on choosing subsets of maps etc. but that can come later on a subdialog. For example, there is a `region` argument to `map_data` which allows choosing a subset of countries, and then we might do a `left_join` instead of a `right_join` so that we get the outline of countries not in our data. We could also subset the world data for a latitude, longitude box.

For now, this should be a simple main dialog. A selector with a receiver for the Country column ("country" in my example) and a receiver for the Colour By column ("count" in my example). So the complete code is:

```
world <- ggplot2::map_data(map = "world")
merged_country <- right_join(world, country_counts, by = c(region = "country"))
ggplot() + geom_polygon(data = merged_country, aes(x = long, y = lat, group = group, fill = count)) + coord_quickmap()
```

Other than the country_counts data frame and the "country" and "count" column, everything else is fixed because it comes from world which is sort of an internal data frame - the user won't see this.

In terms of dialog code, I think map_data will be a before function of the base, and then the plot will be the base function, with the right_join as the data argument assigned as a fixed name "merged_country" for now.

This could be a good first complete dialog for @Muthenya to do since the R code is all ready to implement, but I would suggest it's done together with @maxwellfundi or @shadrackkibet because you will learn faster by working with someone (and I also want this dialog finished quite soon).

(An potential issue I see is that the Colour By variable needs to go in both right_join and the geom_polygon, one with quotes and one without. If this is difficult for our controls to do automatically, then just do one of them manually in the dialog.)

**Comment by dannyparsons** [comment]
Small change needed here: the country receiver should only accept factors or characters

**Comment by maxwellfundi** [comment]
that has now been added in.

**Comment by dannyparsons** [comment]
More to do for sub dialogs but will open new issues for that.
