### ISSUE TITLE
Improving the right-click menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3979]
In #3978 I have suggested deleting 2 items from the right-click menu and adding the Levels/Labels dialogue.
I also use the **Prepare > Data Frame > Reorder Columns** dialogue quite a lot.  Perhaps that could go into the top section, either before or after **Duplicate Column**.
If we want to make the right-click menu shorter, then I have never used the section on hiding columns.  There are 3 dialogues there.  Could they be deleted from this right-click menu- at least for now?

**Comment by shadrackkibet** [comment]
@dannyparsons?

**Comment by dannyparsons** [comment]
I agree making it shorter is needed and some of the converts could go, all the hide and freeze could go as well. 
Then adding levels/labels seems sensible too. But this should only be enabled when only one column is selected and that column is a factor.

**Comment by shadrackkibet** [comment]
@dannyparsons This can now be closed.

**Comment by rdstern** [comment]
The Levels/Labels on <Right-Click> works really well for Factor Columns.  But it is not enabled for Ordered Factors.  It should be.  Thanks

**Comment by dannyparsons** [comment]
Thanks, hadn't noticed that.

**Comment by rdstern** [comment]
Please could Levels/Labels be spelt like this.  It is currently Levels/Lables.
At the same time I suggest we could get rid of (or hide at this stage) the 2 entries **Insert Column Befor**e and **Insert Column After**.  Does anyone use them?
