### ISSUE TITLE
Pasting into the script window

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3994]
I have added Shadrack into this issue.  This is because it looks like a very simple point, but David and Danny have very strong views in this areas.  It would be good for those views also to be shared with the AMI team.

It is I think already possible to select a subset from the log window, or the output window.  Then you could paste it into (for example) RStudio.  I suggest you should also be able to paste it into the Script window.

That would make the script window more useful.

**Comment by shadrackkibet** [comment]
@dannyparsons  what are your views on this?

**Comment by dannyparsons** [comment]
We can definitely do something on this, but need to see what will be stable as well. I think David's idea was that you could paste from a dialog into the script window, edit and run. If you then pasted from another dialog, it would overwrite this. So different from our current use, but it would be easier to ensure output is correct because the script window is linked to a dialog.
I think it needs more discussion before implementing anything.

**Comment by rdstern** [comment]
This was one of the requests in my first day of training in Guyana Met.  Namely to be able to make a small change in a "command" and then "run" it.
I really like David's idea of being able to populate a dialogue from the code already in the output window.  I would also like more, and don't see the importance of having the script button on each dialogue if we can't also edit it a bit (in the script window, and then submit that.
David and Danny feel we should always got to RStudio for that.  I am very happy that we can go to RStudio, but not that we force that strategy onto our users.  I believe more in "Options by Cointext", i.e. that different users may wish to use R-Instat in different ways.
David is a believer in Options by Context, except when it contradicts his ideas.  He will come round as the pressure from users grows.
To be fair to him (I wonder why in need to do that?) he is worried about the error trapping and feels it would be time-consuming to produce a good editor.  And there already is one in RStudio.  But we already have the problem of error trapping in our calculate dialogue.  And I am not wanting to encourage big coding - just tweaking of a command.  It'll come.  We just have to be patient.

**Comment by shadrackkibet** [comment]
I think you can now paste into the script window and you can also edit content. So this can now be closed.
