### ISSUE TITLE
Column metadata right click - Insert Columns

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3997]
The insert columns items are disabled on the right click from the column metadata window. I'm not sure why, but assume it was just never finished. It should be simple because it's similar code to the data view right click. Can someone enable these and add the code?

**Comment by maxwellfundi** [comment]
@shadrackkibet I have now changed this to a milestone for this Friday. Could you have a look?

**Comment by dannyparsons** [comment]
We've resolved this now.
