### ISSUE TITLE
Create labels option for convert dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3998]
I am just about to add a `keep.labels` parameter to the convert columns method. This is a parameter of `sjlabelled::as_numeric` and determines if labels are added to the new column (which is how we can convert back from character to numeric and back to character). So it's useful but I've found a case where it breaks.

I have a character column storing numeric values and some have leading zeros. So when it tries to create labels there are a different number of unique character value to unique numeric values.

Example:
```
sjlabelled::as_numeric(c("011", "11", "123"))
# More values in "x" than length of "labels". Additional values were added to labels.
# Error in names(attr(x, attr.string)) <- labels : 
#   'names' attribute [4] must be the same length as the vector [2]
```
Because "011" and "11" convert to the same number it's messing up the labels. It's quite a small issue but I'm now stuck because I can't get this column as numeric. And annoying because base `as.numeric` would work fine.
However, `sjlabelled::as_numeric(c("011", "11", "123"), keep.labels = FALSE)` works because it doesn't try to add labels.

That's the explanation, so the solution is we need keep.labels as an option on the dialog. I've already added it in the convert columns method. So it just needs a checkbox on the convert dialog only when converting to numeric. The R default and our default should be TRUE. I suggest the label is "Create labels". Should be a quick task which someone new might like to take.

**Comment by Muthenya** [comment]
@dannyparsons do we need to be checked by default?

**Comment by dannyparsons** [comment]
Yes.
