### ISSUE TITLE
Bar Chart of non factor columns

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3999]
The bar chart dialog currently only allows factor (and character?) columns to be plotted. But I sometimes want to plot a numeric column because it's something like "number of days" so only has a limited number of values. I don't really want it as a factor just to do a bar chart. And other column types could make sense as a bar chart too, like logical. The command will work fine with pretty much any column. Can we change this to allow any column to be plotted?

**Comment by rdstern** [comment]
I am OK with this for numeric columns.

Two related comments are as follows:
One potential issue could be the labelling.  For a factor ggplot tries to label each bar.  For some factors this isn't sensible and is often illegible.  I assume this will automatically be OK for numeric columns, but it would be good to check.  If so, then it might actually be sensible (for some ordered factors) to have an as.numeric option when producing the bar chart.
I wonder about bar charts for character columns.  For large data sets this is often hopeless and our plotting takes forever - and we can't interrupt.  Our Describe > One Variable > Graph is an offender here.

I would allow numeric and not include character columns.

**Comment by dannyparsons** [comment]
I wouldn't mind if this just accepted any variable? And then if you chose a strange character column, you might get a useless graph. I find it a nice checking tool to see the unique values without having to make it a factor and see the levels.

**Comment by dannyparsons** [comment]
Often columns which should be factor import as character, like from Excel, and I find this a nice way to quickly check the different values I have. So I would quite like it for characters too, even if it isn't always sensible.
A dialog to see the unique values would be good as well though, I think. I have been doing this in the calculator at the moment, but it's not obvious for most users.
