### ISSUE TITLE
Reorder sheets

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4007]
This is still disabled.  It is on the bottom Tab and also as a dialogue **Prepare > Data Object > Reorder Data Frames**.  This may have been fixed, see #3099 ?  

It would be good if it could be enabled?  I seem to remember there might be a reogrid problem here?  If not - and if it is easy?

**Comment by dannyparsons** [comment]
Yes it was a reogrid problem, we can relook at it.

**Comment by maxwellfundi** [comment]
@dannyparsons  did you have a look at this?

**Comment by dannyparsons** [comment]
Not yet but will try to for 0.4.7

**Comment by maxwellfundi** [comment]
@dannyparsons  we need to re look at this reogrid issue you mentioned fro the next version.

**Comment by rdstern** [comment]
I am now closing this issue, because it has been overtaken by #4557.  I am making #4557 into end of May, i.e. milestone0.4.17.
