### ISSUE TITLE
Help when packages don't install

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4014]
@africanmathsinitiative/developers I'm trying to come up with something to help with the issue of what to do when some of the R packages do not install when R-Instat is run. This often happens for various technical reasons and so we should help users better. Also, we shouldn't prevent users from doing anything in R-Instat just because 1 of the 200 packages can't install. It might only be used in one dialog. And there are things that can be tried when packages don't install. So far I am doing this:

1. If package(s) cannot be installed, it doesn't stop and give an error. Instead a new window opens explaining the issue with different things to try. I'm thinking of adding a Help button so there's a help page with more detail:
![image](https://user-images.githubusercontent.com/11214914/31276059-dcfe8cc2-aa91-11e7-8caf-8e814a53e6b6.png)

If you click Close you can carry on, and depending on what packages are missing, some dialog might not work properly.

2. The online install is the final option. If you click the Install button, you then either get this:
![image](https://user-images.githubusercontent.com/11214914/31276109-15577494-aa92-11e7-9720-eed43c8115d6.png)
and when you click OK it closes and you carry on.

Or if it didn't work:
![image](https://user-images.githubusercontent.com/11214914/31277739-4ab4b7f2-aa9a-11e7-9fd0-a44c0133a69d.png)
And when you click OK you go back to the that form to see the options the packages that haven't installed box updates.

The pull request is here #4015.

Any thought on whether this is a good idea? Improvements on the text or options? Anything I missed?

**Comment by rdstern** [comment]
From a quick read through this seems excellent - and potentially very useful and motivating.  Happening at the start can be demoralising and this is comforting because it also indicates that you are not alone.  You are probably not the first person this has happened to.

**Comment by dannyparsons** [comment]
Slightly changed the dialog to include a "Close R-Instat now" button, since it's common to want to restart if you get this message. I tried having a "Restart" button instead but this seems complicated in VB.NET and so probably not worth the effort over close.

![image](https://user-images.githubusercontent.com/11214914/36481013-5abcccb0-1706-11e8-9d07-606ba4c174ee.png)
