### ISSUE TITLE
Make Date problem with data types

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4021]
I imported some data from Excel.  It included a "date-type" column with entries like 1930-01-01.  It was not recognised by R-Instat as a Date column i.e. it didn't have a D after it.
So I went to the Prepare > Column: Date > Make Date dialogue.  Then **Single Column** and my date column wasn't in the data selector to choose from.

The meta-data showed it is POSIXct,POSIXt. so this might be why it is excluded.  I suggest the single receiver be altered to include all types of column. 
 (A solution now is to convert this column into a character column.  Then it is recognised.)
When making this change to the dialogue could you also add after default date (yyyy-mm-dd), so that what the default date is, is clear.

**Comment by dannyparsons** [comment]
Agreed, the single receiver should accept any type.

The default actually means: 

> If not specified, it will try "%Y-%m-%d" then "%Y/%m/%d" on the first non-NA element

So we should find a way to express this. Or get rid of that and always have a specific option as "our" default, if we don't feel there's much advantage to having this.

**Comment by rdstern** [comment]
I would like to have this information somewhere.  Of course it can be in the help.  It could be on a tool-tip.  Could there be a button, say with a ? that you can click on and then it gives the infomation?

**Comment by Patowhiz** [comment]
To minimise the amount of GUI objects on the form and at the same time
achieve that purpose we could have a distinct nicely styled tool tip  that
that gives a brief and clear information to help the end user.I'll append a
tooltip for such purpose.

**Comment by shadrackkibet** [comment]
This can be closed!

**Comment by maxwellfundi** [comment]
This has been addressed on #4034
