### ISSUE TITLE
File where variables not visible in some dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4022]
[Mokhotlong temperatures.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/1364378/Mokhotlong.temperatures.xlsx)

The sheet I imported is not the default, but Mokhotlong.  It imports easily.  This sheet is also a mess, so I tidied the sheet into a new Sheet5 to see if that would solve the problem.  I saved as an Excel file and then imported that sheet.  The problem remained.

I then exported the corrected sheet as csv.  Importing this sheet seems to have solved the problem.

This file is an oddity.  The problem I found is that the columns don't show in some dialogues, e.g. Prepare > Column: Reshape > Column Summaries, or Describe > Specific > Boxplots.  Both these dialogues have a receiver for the data (numeric type) and also for factors.  The factor columns do appear.
This was not a problem for all dialogues.  For example the columns do appear in Describe > Specific > Scatter.

I am "clutching at straws" here - at least in R-Instat.  It may be clearer in RStudio?  When I import from csv it makes the station into a factor (1 level) and also Date as a factor.  When from Excel it makes Station as character and Date as the funny POSIXct,POSIXt.

**Comment by dannyparsons** [comment]
This was caused by one of the columns having multiple classes in R which caused an error in the R code.
