### ISSUE TITLE
Climatic > Check > Boxplots

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4024]
Here are some specific points about this dialogue.  But it would be useful if John and/or Beryl could look systematically at some of the graphics and try them.  I start the list here.

They could also use the climatic data from the library, both the Dodoma data (1 station, 4 elements) and the Ghana data (2 stations, more elements).  I started with the Dodoma data and applied a filter for just 1988.  So just 366 values.

I would like the default (for the climatic) to have the x as the month and the y (if it exists) as Tmax.  If not, then leave the y variable empty.
No facet by default.

1. I tried a jitter plot.  Then did the plot. The default jitter is too wide (0.4).  So I returned, and used jitter options and made it 0.2.  This worked well, but the x variable of month_abbr was no longer the x variable.  Could you make sure the x-variable is remembers correctly - whatever it is.  It is remembered when you return to the dialogue, but not when you return from the sub-dialogue.
2. Having set the jitter option to 0.2 I decided to do a violin plot.  I found the violin plot also used the 0.2 setting of jitter.  And when I changed the jitter width to 0.4 it changed the width of the violin plot.  I wonder why?
3. I was then asked to add the jittered points to the violin plot.  I therefore started with the violin plot and added a layer for the geom jitter.  I returned and checked that these were the 2 geoms, (i.e. violin + jitter).  I then did the plot - and it worked except I got boxplots with the jittered points.  That was great if I had wanted that!  But I had asked for violin!
4. There is also another problem with the boxplots (and the forthcoming violin plot.)  I seem to be getting jitter + boxplot, rather than boxplot + jitter.  By this I mean that the boxplot (and later the violin plot means that I don't see all the jittered points.  I suggest the R command for the layers is given the wrong way round. (This may be a general problem?)
5. So I do the plot the other way round.  Namely jitter plot with the added layer on top of box plot.  I now get the plot I wanted, but had to "remember" the x-variable was month_abbr, because that wasn't included.
6. Now I decide I would like to edit the boxplot layer I just added.  (The dialogue is still on jitter).  I go to the sub-commands and notice that R-Instat has swapped the order of the layers.  (So boxplot is now the first layer - even though it wasn't!)  It now says I can't do an edit, because that is the main layer.  Hey - who is in charge here!!! 
7. If that is not challenge enough, then (and I would like John and Beryl to do this as well!) I would like to be able to pose problems and see how to do the corresponding plot.  The first one is the be able to connect the medians in the boxplots.  This is shown here [https://stackoverflow.com/questions/18599411/create-a-boxplot-for-multiple-stations-and-line-joining-median-of-the-stations](url), but I don't see how it fits into our current system.  (I can do it in my old Instat, and I can also add the means!) A second challenge is in the Hadley Wickham book and is where there is an additional factor (here say the day of the month) and I would like to connect those values across my successive boxplots.  

I think the points above may be easier to see if John or Beryl try to repeat them so you can see them locally.  (I would be happy to show them over skype)  Then I hope they might do similar analyses to try more aspects of the plotting, and not just this dialogue.  In general the graphics is looking very good indeed!

**Comment by dannyparsons** [comment]
@maxwellfundi Can you make sure everyone has a GitHub account, even if they're not developing, so they can be involved in issues?

**Comment by maxwellfundi** [comment]
@dannyparsons  they already have the github accounts

**Comment by dannyparsons** [comment]
Ok then they need to be added to our AMI teams

**Comment by rdstern** [comment]
I now really do have a possible structure for this dialogue.
1. It builds on the existing boxplot dialogue.  That is being changed a bit now, and the changes can also be included on the climatic boxplot.
2. So the radio buttons (Boxplot, Jitter, Violin) are the same.  So are all the buttons on the left hand side and of course the bottom.
3. The change is just in the buttons on the right-hand side, where it says Single/Multiple, down to Swap Parameters.  We don't need any of those.
4. Instead it looks a bit similar to the Climatic > Prepare > Climatic Summary dialogue.  Indeed it should be as consistent as possible with them when the second button there for the within year option is there.
5. So there are 5 controls there, namely a) Station, b) Date, c) Element, d) Year and e) Within Year.  There is no Day of Year control (which there is on the climatic summaries).
6. Now the new controls.  To the right of each of 3 the 5 controls - all except element (which is the y in the boxplots)  and Date (which isn't really necessary as a control, but is there for consistency).  there is a drop down.  This has 4 options and one of them is visible always.
7. They say x, Facet 1, Facet 2 and None.
8. The defaults are that Station is Facet 1, Year is None, and Within Year is x.
9. To the right (or possibly below) the Element control is a checkbox (default unchecked) that says Omit below.  This has a small field with the value 0.05 and you can type a number into that field.
10. Now the VB coding for the 3 drop-downs.  They must have a different value each, except they can all be None.  So, if anyone is changed to an existing value on the other two, then the value on other is changed to None.  (They could all be None - in which case you get a single boxplot of all the data!)
11. The Facet settings could alternatively be done with the Facets tab on the dialogue sub-command - they should be in synch.
11. The Element control must be filled for OK to be enabled.
12. If the Element checkbox is filled then it adds the filter to whatever filter may already be in operation. If it is ticked and empty, then use 0.05 as the value.

**Comment by Patowhiz** [comment]
@rdstern . I'm trying to translate your suggestions ofthe design. I'm not understanding point 4 to 9. Below is a screenshot of the previous design of this dialog. I have added drawings to illustrate the visual bits than I could grasp from your points. Please expound more, I'm I close to what you are trying to explain?

![climatic boxplot](https://user-images.githubusercontent.com/21179007/39199951-69ce3bee-47f3-11e8-8ce5-b601c16d63ea.JPG)

**Comment by rdstern** [comment]
So yes, you are right to get rid of the special layout buttons on the left.  So, on the left, it looks like the ordinary boxplot/jitter/violin dialogue.

Then have a look at the Climatic > Prepare > Summary dialogue with the Within year option button selected.  The right-hand side is consistent with that dialogue - except the day-of-year control isn't needed.  So the field headings are as for the Climatic Summary dialogue, i.e. not x-axis there.  That's point 5 above.  And they are in the same order in the dialogue as for the Climatic summary.

Then - point 6 - to the right of the **Station, Year and Within Year** fields there is the drop-down with the options as explained in points 7 and 8.

Then, just below the Element field is the Omit below 0.05 that you have above.

Great that this is being done.

**Comment by maxwellfundi** [comment]
@Patowhiz  Are you working on this or should I assign it to @Muthenya  to recreate  this layout?

**Comment by Muthenya** [comment]
@rdstern I've began work on the issue and I've noticed a bit of a mix up. Your explanation is based on the Boxplot in Describe > Specific > Boxplot... and not Climatic > Check Data > Boxplot..., though this doesn't really influence the changes that need to be done on Climatic > Check Data > Boxplot... . I just wanted to mention that.

**Comment by rdstern** [comment]
That's right.  I didn't feel that the current Climatic > Check Data > Boxplot dialogue is much help to us.  I was keen now on a change that is consistent (as far as possible) with the Describe > Specific > Boxplot (that's the LHS of the dialogue) and also with the other climatic dialogues.  There I used the Climatic > Prepare > Climatic Summaries as ab example.

**Comment by Muthenya** [comment]
@rdstern this is how far I have gone with the designer. I just want to check if I have captured your explanation correctly.
![image](https://user-images.githubusercontent.com/32125033/39244082-41ad42ae-4898-11e8-86fe-d9941530b2a4.png)

**Comment by Patowhiz** [comment]
@Muthenya I hope you have had a look at my drawings too. I think Rogers response to it was that the layout should go.

**Comment by Muthenya** [comment]
Okay. Now I see @Patowhiz .

**Comment by rdstern** [comment]
Yes, perfect, except, as Patrick says, the Layout box is not needed.

**Comment by Muthenya** [comment]
@rdstern I made the corrections. I'm currently not certain of the functionality of the new controls. I would like to understand how the controls will work so that I can set them up correctly.

**Comment by rdstern** [comment]
The climatic boxplot dialogue looks excellent.
But I tried with the library data from Dodoma.  And I cannot get anything to display in the Year variable.  I was assuming it would autofil the Year column, but it is blank and does not include the possibility of including the year column in the dialogue.

**Comment by Muthenya** [comment]
@rdstern this is because the Year Receiver is set to only include factors. Once you change the Year column to factor it will autofill.

**Comment by rdstern** [comment]
Ok, thanks.  I was hoping that the Year column need not be a factor for this dialogue, because the command could do the add.factor() to it.  This is usually a pain, but in the results for this dialogue will not display the label for the x variable, because it is obvious.

**Comment by Muthenya** [comment]
I understand. I restricted it to factor because of the options the receiver could have from the drop-down required factors expect for None.

**Comment by Muthenya** [comment]
Okay. If that's the case, I can begin work on it to have it as an extra option.

**Comment by rdstern** [comment]
The first part should be simple, i.e. to allow a numeric year column to be used in the dialogue.  I am keen on this.  This part doesn't need an extra control.  It just needs (I think) for  as.factor(year) to be used.
The second part would be great - but only if it works.  It changes the structure of the boxplot command a bit.  Maxwell tried that change for the general boxplot dialogue and it caused other complications - so we dropped it.  I hope that same change is OK here, but it will need testing. Please look at issue #4211 where this was discussed.  It maybe OK here, because part of the problem generally was with multiple variables - which we don't have here.

**Comment by rdstern** [comment]
Agreed.  Try it and let's see what happens.  The extra control can always be hidden again later.
No, just a minute, not an extra control.  Have it as an extra option instead on the Year pull down, i.e. **X Axis Numeric**, just below the **X Axis** option.

And, while you are there can you check on the Facet options?  Currently they are for **Facet Row** and **Facet Column**.  Same is for Within Year.  Now the Year will usually have a lot of levels, and so I would usually want **Facet Wrap**.  So can you see whether this can be added?  I will mean that if you have it for one element (Year, Within Year and Station) then you can't have another Facet Row or Column in the others.

Try with the Dodoma data first where there are many years - though only the one station.  To me the usual will be a single facet, with Facet wrap.  For example with the Months, they will be 3 by 4 or 4 by 3.  We won't usually want 12 by 1 or 1 by 12!
We still do want to keep the options of Facet Row and Facet Column, for example if we have 3 stations and 4 quarters.

Thanks

**Comment by Muthenya** [comment]
I have already began work on the first part, that is, including X Axis Numeric option.

Now for the second part, I went through this initially with @volloholic and he strongly suggested that it be possible for one to have two elements as Facet Row or Column, hence the current functionality.

**Comment by rdstern** [comment]
That's right when you want to have the possibility of 2 variables for the facets.  When you have a single variable, then we will usually use Facet wrap.  So it could usefully be added as an option.  But it is as well, and not instead, of what you have now.  See the reference [here](http://ggplot2.tidyverse.org/reference/facet_wrap.html).

**Comment by Muthenya** [comment]
@rdstern this is how I have implemented the **as.factor** option so that I don't really interfere with the initial set up. I know it's a bit different but still works well. I would really like to get your take on it.

![image](https://user-images.githubusercontent.com/32125033/41117892-fb9023d8-6a96-11e8-9e58-347b39bf1935.png)

The other issue is clarification on whether this implementation is only necessary for Year, since Month can also be numeric, as in the case of Western Kenya Rainfall Data(at least before it is converted to factor).
Lastly is on the issue of the facets. Again just for clarification, facet wrap is to be added as another option in the drop-downs, right?

**Comment by rdstern** [comment]
That looks great.  2 things to confirm.  
When you have x-axis, and the year could be numeric, what does it do exactly?
a) The year column may then already be a factor - which is fine.
b) If numeric it could do an as.factor() and then treat it as a factor.
c) Ideally, if numeric it would treat it as numeric - as discussed in #4211.  But (if that isn't there yet), then it might take too much time. 

Yes please add Facet Wrap as an option.  The only complication is that you can only have one factor if it is Facet wrap.  So if another (out of Station, Year and Month) was already set to Facet wrap, or Facet Row of Facet Column, then they would be reset to None.

Don't worry about Month being numeric.  I am happy that this is a factor.  It usually will be.

**Comment by Muthenya** [comment]
For a) and b) that is the case, but maybe just to clarify further;
1. When Year is already a factor, both **X Axis** and **X Axis Factor** options will treat it as factor.
2. When Year is numeric, **X Axis** will treat it as numeric and **X Axis Factor** will do an as.factor() and then treat it as a factor.

**Comment by rdstern** [comment]
Perfect!  That's absolutely right.

**Comment by dannyparsons** [comment]
It's good that this is working with numeric/factor x-axis. I think we could find solutions which are less confusing for users as I think "X axis" and "X axis factor" is not ideal, however this does get complicated to have x numeric as we saw before. So I don't think it's straightforward to get this better and if it is working well as it is I think we keep it like this.

For the facet wrap option, one simple solution is to always do `facet_wrap` when there is only one variable. This slightly restricts us by not doing `facet_grid` with one variable, but it would make the dialog very simple and if `facet_grid` was important we could always have a checkbox for something like "Force grid layout for facets"

**Comment by rdstern** [comment]
I'd like that solution of Facet wrap whenever there is a single facet.  I am also assuming that the options are linked, so the ordinary sub-dialogue remains available?  And would be set to correspond to the settings chosen..  Is this true?

If so, then we could always change the facet to Facet grid there.  So everything remains available - it is just that those options we need 99% of the time are really simple.

**Comment by dannyparsons** [comment]
We are able to link it up correctly with the sub dialog, yes. @Muthenya can check this

**Comment by Muthenya** [comment]
I have two suggestions:
1. Concerning the Year as the X Axis, in order to help reduce the confussion, what if we have the options for Year as X Axis(Numeric) and X Axis (Factor). I feel  this will guide the user to see which option to use depending on data type of the Year.

2. Concerning the facet_wrap; I have already set up the (facet_wrap) option for all the drop-downs(hence receivers). It's just awaiting review. 
Is it still necessary for the facet options in the main dialog to be in sync with the sub-dialog since the facet options on the main dialog offer more capabilities as compared to the sub-dialog?

**Comment by rdstern** [comment]
Today is when we used the climatic boxplots for the first time.  I had thought that the year as a variate was already implemented, but it appears not yet (as of 4.18).  It would have helped quite a lot as Maxwell saw, so I hope these can be implemented for the next version.

Great on the facet wrap being available too.  I am not so worried about synchronisation except I worry what will be done if they are then inconsistent.

**Comment by dannyparsons** [comment]
I don't think having X Axis (Numeric) and X Axis (Factor) is a good solution. It still requires users to know about the types and then its just as simple to convert the column before using the dialog. However, implementing something better isn't trivial in our dialog system and I haven't had time to support on this so I'm not sure what to suggest.
Syncing is also non trivial and will require thinking through.

I think the dialog is almost there in general but needs some more thought and support for Lazarus to be able to complete, but I'm not sure how to make that happen.

**Comment by rdstern** [comment]
The minimum is trivial and that is the same as is very helpful in the climatic summaries.  That's what I started with and is the most important, namely that the Year field (as in the summaries) allows the year column whether it is numeric or a factor.  Then it does an as.factor() in using the column.

I thought we had agreed that at least.  Anything more would be a welcome bonus, but it was confusing that this had not been done yet, after the amount of discussion.

That would have been less painful for us today.

We had to make it a factor for this boxplot dialogue to work.  We had already setup to use just the data from 1971 in a filter (Year > 1970).  That was from when it was numeric.  Now we needed to re-apply that same filter and of course there appeared to be no data, because it was now a factor!  In a class that all takes a lot of explaining, and I was trying to discuss quality control, bot types of column.

**Comment by dannyparsons** [comment]
If we want x to always be a factor then adding `as.factor()` is easy because it does nothing to existing factors. I thought the idea was sometimes wanting it to stay numeric, and then that gets more complicated. 
If it can just always be a factor always then that's easy, then I don't see why both the X axis factor/numeric options are needed in the combobox?

**Comment by rdstern** [comment]
We don't if that is all we are doing.  I was under the impression that it might also be possible to have the year as numeric as we showed earlier (in general).  It got too complicated for this option in the general  dialogue, but I was under the impression that it might be easier in this special case.

But I don't want to delay this small (but important) step, if the more general solution (even for this dialogue) remains complicated.

**Comment by maxwellfundi** [comment]
@Muthenya  I thought you had done this already?

**Comment by maxwellfundi** [comment]
Okay closing this
