### ISSUE TITLE
Describe > Specific > Line plot error

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4025]
The dialogue crashes out when I specify a plot (y and x) and the go to Options and then try Layers > Add. It seems OK to do this with boxplots and scatter plots, but not with line plots.  The message is that: 

System.NullReferenceException was unhandled.

It would be good to check other geoms as well.  I wonder why scatter and boxplots are different?

**Comment by maxwellfundi** [comment]
@dannyparsons  this was addressed on layer bug fixing so it can be closed too.
