### ISSUE TITLE
Scatter plot and line plot with line of best fit

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4027]
I was trying the scatterplot with the recently added line of best fit.  It works!  Great.  But there are some things to add - of course!
1. It needs to be on the line plot as well as the scatter plot.
2. Add an option when this is ticked, which is "with confidence bands".  The default in ggplot is to provide them.  I suggest our default should be to omit them.  In geom_smooth you add se=FALSE for this.
3. For further options we need the geom smooth also to be added to the plotting.
4. And an obvious request in the future will be to add the equation and perhaps R-squared to the graph.  But that can wait for later!

**Comment by Ogik99** [comment]
#5037

**Comment by dannyparsons** [comment]
@Ogik99 are these all done (apart from 4.)?

**Comment by Ogik99** [comment]
> @Ogik99 are these all done (apart from 4.)?

Yes Danny, part four is yet to be implemented.

**Comment by dannyparsons** [comment]
Ok great I'll close this and reopen the general issue on adding text to graphs.
