### ISSUE TITLE
Model > Fit Model > Two Variable Test to be enabled

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4029]
The Two sample option is disabled for me.  Is this general?  I wonder why?  It will be needed for Stats Made Simple.

**Comment by dannyparsons** [comment]
It was unstable so we disabled it for the release. Needs to be worked on soon! Or at least we accept it is unstable and get it to work in the cases needed.

**Comment by dannyparsons** [comment]
I tried enabling it but it crashed. I don't think it would take long to get working if I looked at it with someone who could explain how it should work.

**Comment by Muthenya** [comment]
@dannyparsons what's the state of this?

**Comment by dannyparsons** [comment]
Not been able to look at this again. I don't think it's urgent for the upcoming releases but we should fix this quite soon after that.

**Comment by maxwellfundi** [comment]
@shadrackkibet  is currently looking at this for tomorrows version.

**Comment by shadrackkibet** [comment]
Can someone explain how this should work?

**Comment by rdstern** [comment]
I propose it is time to re-instate this option.  Perhaps @Wycklife with @shadrackkibet could check on the state of the "old code".  I would be happy to share the screen over skype.
My assumption is that the old code may now be sufficiently messy that it will be quicker to start again.

This is the option for the common 2-sample tests, that are mainly in the stats package or adapted from them, e.g. t.test.  I am suggesting this for @Wycklife, because it is also an opportunity for him to become really confident with the basic statistical ideas here.  So he has both a programmer and a statistical hat.

The work on this may wait until @Ivanluv has completed the changes to the general parts of this dialogue - though it will be a separate part of the code.  But there is also plenty of other work to do.

**Comment by rdstern** [comment]
@Ivanluv I hope you are ok with this work.  It is important and I have spent a long time trying to conceptualise how it should work.  I describe proposed changes in this dialogue.  In parallel we should also add more keyboard to the Model > Fit > Hypothesis Tests Keyboard, particularly for DescStats and also for Mosaic and perhaps for others.

a) The old code should be examined and tidied.  Perhaps this could be done by @shadrackkibet of he could support @Ivanluv in this initial stage.  Shadrack did this tidying in the one variable dialogue.
b) This second button should be called Test and not 2 sample.  That is like the one-variable case.  There is (currently) no third button.
c) With the Test button the first receiver is simply called First Variable.  The second is called Second Variable.
d) Under each of these controls perhaps in brackets and perhaps coloured, there is a more complete version of what @dannyparsons has included in the Describe > Two Variable > Summarise and Graph.  There it says Numeric or Categorical.  Here is says that - if Ordered, then add Ord  in front.  I assume logical would be given as Logical?  
e) But in addition for Categorical it needs to know and report the number of levels.  so Levels: and the number.  BUT it isn't just the nlevels, but the number of levels with non-zero frequencies.  I think this should be easy, adapting [here for example](https://stackoverflow.com/questions/30019933/how-to-find-unused-factor-levels). Our standard survey set will be an example where Variety has 3 levels, but we may filter so only two are used.  Some tests only work for 2 groups.
f) Then there is the pull-down which gives the tests available.  This is just like for the One Variable case.  The contents (tests) will depend and change with the contents of the 2 receivers.
g) Then - as with the one Variable - there will be more controls on the right, depending on the test.
h) Keep the Try, and Model Preview and Save Model controls.  Many of the tests can be given as a formula of first variable ~ second variable.  We'll use this when we can.
h) Once the work starts I'll add a lit of the tests, etc to undertake.

**Comment by rdstern** [comment]
Here is a sort of script to remind me of some of the tests to be implemented:
```

library("DescTools")
kruskal.test(x, g)

ConoverTest(x, g)
DunnettTest(x, g)
DunnTest(x, g)



# Code generated by the dialog, Hypothesis Tests

survey <- data_book$get_data_frame(data_name="survey")
attach(what=survey)
MosesTest(yield , size)
NemenyiTest(yield,variety
PageTest(yield,variety,village)
RunsTest(yield ~ variety)
ScheffeTest(yield,variety)
SiegelTukeyRank(yield, variety)
SignTest(yield,size)
VanWaerdenTest(yield,variety)
VarTest(yield ~ variety)
GTest(village,variety) 
JonckheereTerpstraTest(yield ~ fert)
LehmacherTest(variety,fertgrp)
LeveneTest(yield,village)
LillieTest(yield)
Last_Test <- chisq.test( village,variety)
data_book$add_model(model_name="Last_Test", model=Last_Test, data_name="survey")
data_book$get_models(data_name="survey", model_name="Last_Test")
detach(name=survey, unload=TRUE)
rm(list=c("Last_Test", "survey"))

coffee <- data.frame(time=c(447,396,383,410,438,521,468,391,504,472,513,543,506,489,407),grp=Untable(c(4,6,5), type="ordered")[,1])
JonckheereTerpstraTest(time ~ grp, data=coffee)

```

**Comment by rdstern** [comment]
The tests more clearly:  The stats package is the default and it is just given.  The package name doesn't need to be added.  I (usually) add the package name if different.

(Note that some variables could be logical - that is noted as logical and is the same as categorical with 2 levels here.  A date variable is given as such, and is numeric.  For now give ordered categorical as such, but nothing special.  They may have their own section later.)

**_numeric/numeric_**
t :  As for one variable
t-paired (Does the paired t-test.  Just need to give paired=TRUE I think in the command
wilcox - As for one variable
wilcox - paired  (as t-paired)
Line here
var
ansari  (also from stats package)
mood
Line here
cor
spearman
kendall

**_Numeric/Categorical (any number of levels)_**
oneway
kruskal
bartlett
fligner

Numeric/Categorical 2 (Categorical just has 2 levels - perhaps after filtering)
The first 5 are the same as numeric/numeric.  Give the model - at least here
The next 4 are the same as above - i.e. where the factor has any number of levels
t
wilcox
var
ansari
mood
--------
oneway
bartlett
kruskal
fligner
--------


**_categorical/categorical (either has any number of levels)_**
chisq  (use xchisq from Mosaic package)
fisher
mcnemar

categorical/ categorical 2
I don't have anything yet, so just those above

categorical 2/categorical 
Just those above for now

categorical 2 by categorical 2
prop (from Mosaic)
(There will be more
------------
those above, for any number of levels.


I will be adding to this list, but that is more than enough for now.
