### ISSUE TITLE
Bug with datasets on the Lubridate package. 

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#4033]
When loading data from lubridate package, it appears like it has two datasets as shown below. 

![image](https://user-images.githubusercontent.com/9798689/31343430-48d6071c-ad18-11e7-9bbb-e6a8a0b87612.png)

However on clicking the second on the list, it throws an error saying lakers is not found. 

![image](https://user-images.githubusercontent.com/9798689/31343462-5ddc515c-ad18-11e7-9c45-8651a48e150c.png)

On running the command to view the datasets on this package, `data(package='lubridate')` It appears to only have one dataset called lakers as shown 

![image](https://user-images.githubusercontent.com/9798689/31343611-c95c7402-ad18-11e7-9d66-ba462837e1fd.png)

I have found out that the second dataset on the dialog in R-instat under lubridate package is the description of the lakers data set

**Comment by dannyparsons** [comment]
Great spot. That's right, so the display of datasets in R-Instat was wrong for `lubridate`. Turns out it displayed incorrectly for any package with only one dataset. Fixed this by making a small change to how we get the datasets to display in the dialog.
