### ISSUE TITLE
Infill Dates dialog improvements

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4035]
- [ ] Put the dialog on the Prepare > Dates menu, not just the Climatic > Dates (@rdstern is this ok?)
- [ ] Make the Date receiver auto fill
- [ ] Reposition the Date label so it lines up correctly
- [ ] Add checkbox for `resort` parameter

@rdstern Should the factors be called "By factors"? or "Fill by factors"? Would that make it clearer?

**Comment by dannyparsons** [comment]
I've assigned to multiple people so you can decide between you who takes it up.

**Comment by dannyparsons** [comment]
I've also added a new parameter: `resort`, to the command so that the user can choose not to resort the data after infilling. Can this be added on the dialog, default is `TRUE`. At least then the user is aware that sorting will be done, and they can turn it off if they want.

**Comment by shadrackkibet** [comment]
@rdstern ?

**Comment by shadrackkibet** [comment]
which data can be used to test this dialog?

**Comment by dannyparsons** [comment]
The Ghana data from the climatic library, but it's hard to see the changes made by the dialog there other than the number of rows added. I would make a small example data set with a Date column, either make a column of Dates in Excel and import or use the calculator to do a sequence like `seq(as.Date("2000/1/1"), by = "month", length.out = 12)`
