### ISSUE TITLE
Converting from ordered factor to Factor and Vice versa ?

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#4041]
Seems this is not working. I accidentally changed my column to ordered factor instead of factor(unordered).So i got my column as ordered factor and now  wanted to change this to factor but seems this isn't working . I checked the code and this is running well `InstatDataObject$convert_column_to_type(data_name="WKenyaRain", to_type="factor", col_names=c("Year","Month"))` but the column datatype hasn't changed it is still `o.f`. Is this something to worry about?

**Comment by dannyparsons** [comment]
yep this is a bug, our R code isn't able to do that conversion from ordered back to factor because of the methods we're using. so we still need to be able to find a way around this.
