### ISSUE TITLE
Data selector again

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4054]
In preparing the tutorial I like the current improvements.  I think I'll explain about showing the type of a column.
1. It still jumps back to the top of the list of variables after one is selected.  Is this usual?  If not can it stay?
2. I would like to be able to select multiple columns by holding down the left button as the mouse is dragged.  I know I can use <Shift> Click and would like both, because some beginners will be familiar with dragging.
3. And just to confirm for later that I would still like to be able to choose between showing the variable name and the variable label in the selector - though that could come later.

**Comment by dannyparsons** [comment]
1. I've solved, I thought it was more difficult to achieve this than it was.
2. Is sort of possible already, except it's only possibly when you start by clicking outside the selection part. So if you reduce the width of the header, you can then click and drag to select multiple. But I don't think doing it that way is useful for anyone, so in the way you ask it's not really possible.
3. I wasn't sure if that was still wanted now we have the tooltips, but we can keep it on the todo list.
