### ISSUE TITLE
Add copy of Describe > Specific > Boxplot to Prepare menu 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4062]
Could we replace the current **Prepare > Check Data > Jitter** by a copy of the Boxplot dialogue and enable it.  It would be given as **Prepare > Check Data > Boxplot**.

**Comment by maxwellfundi** [comment]
yeah, will be on this and put it there.

**Comment by dannyparsons** [comment]
That's fine, but the original Jitter dialog was to add a random jitter to a column to anonymise it. Do we want to have graph dialogs in the Prepare menu?

**Comment by rdstern** [comment]
Good question.  I feel we do, with (just?) this particular dialogue, because it is useful for examining primary data and looking for outliers.  So it fits in the **Prepare > Check Data** menu, just in the same way it is in the Prepare part of the climatic menu.

I didn't realise that was the use of jitter here.  Perhaps then we should leave the Jitter (even disabled) to remind ourselves later, but I'd still vote for a copy of the boxplot dialogue here. 

I am considering using it in the tutorial for the second example, where we discuss the prepare menu with the data. Good to introduce checking the data. That's when I didn't want to go to describe at that point.

**Comment by maxwellfundi** [comment]
Then thats fine to keep both Jitter and the boxplot dialog which also has jitter as an option. In that case, would it not be confusing to have the two jitters in different places? Shall we instead have the jitter on the boxplot dialog to add the anonymizing features of the other dialog and we end up with just one dialog?

**Comment by dannyparsons** [comment]
The original jitter isn't the same as a jitter graph, so they can't be combined, but we could change the name. Although the jitter dialog was originally for a "Prepare to Share" menu, (which we changed to Check data?). Does it still fit under Check Data?

I could then say one variable summarise, one variable graph and one way frequencies dialogs are also for examining the primary data as well. Should they go under check data too? I'm just wondering where the distinction is now if we include a graph dialog?

**Comment by rdstern** [comment]
Interesting in that in the tutorial I have just suggested the Describe > One Variable > Summarise dialogue to explore the data.  So I would be quite happy to have them there too.

On the prepare to Share idea, with jitter, this is different.  I suggest it stays there for now and maybe for ever, because checking data so they can be shared remains logical.  But could we have a line with the Prepare to Share (sdc package) and jitter below that line.

I would be quite happy to have a reasonable set of dialogues above the line in the Check Data section.  It emphasises the importance of the topic.

**Comment by Muthenya** [comment]
@rdstern  on Describe > One Variable > Summarise dialogue do we want this dialog alone or the entire onevarible menu dialogs?

**Comment by Muthenya** [comment]
@rdstern this is what I've come up with. 

![Uploading image.png…]()

**Comment by Muthenya** [comment]
![capture](https://user-images.githubusercontent.com/32125033/31666708-e0861e74-b355-11e7-8823-3f485da57880.PNG)

**Comment by maxwellfundi** [comment]
@Muthenya  I am fixing this now.
