### ISSUE TITLE
Dealing with POSIXct and POSIXt classes

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4072]
These are types of date classes in R. We use Date to store dates. POSIXct and POSIXt are more complex because they include a time and timezone, which we have decided to keep separate.
Dates in Excel import as POSIXct, POSIXt classes so we need to handle them well. The display looks the same so it's not obvious you don't have a Date without looking for the (D) in the header or going to the column metadata.
So we need to decide how we handle these columns, particularly for climatic users.

Options:

1. Allow POSIXct, POSIXt to be considered as a date in R-Instat, so no conversion needed. This might work because most of the functions such as year(), month() etc. work on these classes as well. But if there are time components here it might be sub daily data, and then things gets messy if it's assumed to be daily. You also get issues with historical dates in this class such as when timezones shifted which introduces NAs. We decided on Date because it's simple.

2. Allow these columns to be converted by the Make Date dialog. Currently convert from a single column only allows numeric columns. This needs to change anyway to allow character columns. Then we could convert to Date.

3. Put back the "Convert to Date" right click item but only make it visible when the column is POSIXct, POSIXt types. Making converting quicker.

4. Automatically convert POSIXct, POSIXt classes to Date on import. Or have it as an option. However, if there is a real time component then this will be lost (unless we duplicated and then converted?)

I think 1. doesn't make sense. 
2. and 3. are sensible to do.
4. is the only one I can think helps solve the issue of someone opening a dialog to use a date column and not seeing their date variable and probably getting stuck there. Unless you know about converting you might not find it. Although not sure we want to mess around with importing too much.

Not sure any of these are good enough. Any other thoughts?

**Comment by rdstern** [comment]
1. I would certainly like your option 2, i.e. the Make Date can make a date column from these columns.  I don't see a down-side to this, because it is not overwriting the original column.  It makes a new Date column.
2. Then the define climatic data should not recognise the original column as a date column - whatever the name.
We may want to do more, but we should at least do this.

**Comment by dannyparsons** [comment]
2. is now done. Any column can now be used to convert to Date. 
This makes it slightly less stable as some columns may not convert. We should also better detect what options are sensible for different types e.g. origin only applies to numbers.

But at least POSIXct, POSIXt classes now convert to Date with the default options so this solves our issue with this type of column.
