### ISSUE TITLE
Regular sequence of dates implemented

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4075]
I assume this is quite easy at least to start with.  Our main use will be to have a date column that goes up one-day at a time.  That is the default, though there is a lot of flexibility in the **seq** command.
Initially I assume we could just enhance the **Prepare > Generate > Regular Sequence** dialogue slightly.  This already has a radio button with the label "Sequence Type" and one of the 2 options is Dates, though that is disabled.

I assume this would now move to the top and become one of our new-style radio buttons.

Then the start date must be given.  I suggest the default is 1/1/1970, because that is the starting reference date in R.  Initially we would just type our initial date, but later it would be good to have a calendar.
Is there an obvious end date.  Perhaps just a year later?

**Comment by dannyparsons** [comment]
We could just have the start and end date the same. Maybe 1/1/2017? I don't think there's any sensible default that will help many users so might as well make it simple.
I suggest we use the calender control from the start, but first this needs to be made into one of our core controls. Not a big task but depends on priorities.

**Comment by rdstern** [comment]
I have changed the milestone to 4.11 in the hope that this might be a really easy job.  I have sometimes been confused that what I thought was an easy task (1-2 hours?) has sometimes seemed to take forever.

So I wonder about the team trying some "possibly easy" tasks while David or Danny are around - and that's partly to confirm that it is really easy.

In this case the existing dialogue seems fine, because the seq command can still be used.  As an example I was able to use the existing dialogue for the Samaru climatic data, from 1/1/1928 to edit the initial use of the seq command in the script window.

It was:
# code generated by the dialog Regular Sequence
Regular1 <- rep(x=seq(from=1, to=20454, by=1), each=1)
InstatDataObject$add_columns_to_data(data_name="SAMARU56", col_name="Regular1", col_data=Regular1)

rm(Regular1)

I changed the seq bit to:
Regular1 <- rep(x=seq(from=as.Date("1928/1/1"),length=20454, by=1), each=1)

And it ran fine.
So (to me) it is largely a question of sorting the dialogue.  And hey presto!
It may be a waste to do this while David/Danny are there, but could it be examined and then be a task once (perhaps) David leaves?

**Comment by dannyparsons** [comment]
yes the code is easy, the complicated part is creating our specific date user control that inherits from ucrCore, but I agree that's something easier to do together. @shadrackkibet do you want to take this up?

**Comment by shadrackkibet** [comment]
yep i am happy to pick up this task.

**Comment by dannyparsons** [comment]
This can now be implemented as the DateTimePicker control exists. The function for dates is still `seq` (or `seq.Date`, both the same so whatever is easiest for the dialog).
by is a character of the form `"x ???s"` where `x` is an **integer** and `???` is either `day`, `week`, `month` or `year`. So I suggest this is an nud/textbox and a combo box. See `?seq.Date`.
The other parameters such as `length.out` work in the same way so shouldn't need to change any of that.

Use the DateTimePicker control like this:
```
UcrDateTimePicker1.SetParameter(New RParameter("d", 1))
UcrDateTimePicker1.SetParameterIsRDate()
```

`SetParameterIsRDate()` means it will return an R Date object e.g. `as.Date("2000/1/1")`. 
We may also need another option for just returning a string e.g. "2000/1/1" if there are functions where we just need the date as a character and not a Date type, but I haven't implemented that yet.

**Comment by shadrackkibet** [comment]
This is now implemented . This can be closed.
