### ISSUE TITLE
Disable the Remove Current Filter?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4079]
We currently disable the Levels/Labels dialogue when the current column isn't a factor.  I like that.
Could we also disable "Remove Current Filter" when no filter is applied in a particular data frame?

If so, then remember it is on the row right-click as well.

**Comment by dannyparsons** [comment]
yes we can

**Comment by shadrackkibet** [comment]
This is also on column metadata and cell right clicks.
