### ISSUE TITLE
Remove the filter on a subset

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4080]
I applied a filter and used it (on the WB data) to put 5 countries into a subset.  The row numbers are still in red as though a filter is being applied.  It isn't.

It is easy to get rid of, by Remove Current Filter.  Is there a reason it is there in the first place?

**Comment by dannyparsons** [comment]
no that's a bug

**Comment by shadrackkibet** [comment]
This is now fixed here #6186. Please close.
