### ISSUE TITLE
Loading Data from tm Package.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#4097]
R-Instat is unable to load the two datasets from this package. I think this is because this datasets are not Dataframes.
![image](https://user-images.githubusercontent.com/26301973/31999383-b896f27a-b99b-11e7-9e98-304f09e985a9.png)

**Comment by dannyparsons** [comment]
Good spot. You are right, these objects are not data frames and there doesn't seem a sensible way to treat them as one since they are lists of different things. Since `tm` isn't a package loaded with R-Instat I'm not too worried about this. The error message is the best we can do at the moment.
