### ISSUE TITLE
Adding layer to boxplot dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4098]
I added a layer to the boxplot dialog. It also worked except the second layer appeared under the boxplot, which wasn't very useful. I assume this is just an issue with parameter positions. Can this be fixed? And checked on all other graphics dialogs?

**Comment by maxwellfundi** [comment]
I have been looking at this and it appears that the order of layers change when dialog is closed. It appears in the right position when its added but once dialog is closed, on return is the other way round.

**Comment by dannyparsons** [comment]
Have you checked how the parameter positions change when this happens? This should be controlling the order.
