### ISSUE TITLE
Prepare > Column: Reshape > Merge

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4100]
In general this worked well.

- [x] 1. In the sub-dialogue tab "Columns to include" it includes the key columns in the list you could choose to exclude.  This doesn't work - it is logical to get rid of one copy - which is automatic in the merge, but then the command gives an error.  The change isn't trivial because you might choose to do this before organising the key columns.  But perhaps the key columns should come first and then this list.
- [x] 2. When returning with different data frames the sub-dialogue on the key column pairs should clear if the data frames are different.  In the example we used the relevant key columns were almost the same and this generated an error.

**Comment by rdstern** [comment]
I just fell foul of the first point above.  I chose not to include the date variable in the second file, because it is there anyway.  And it then told me it couldn't do the merge!

**Comment by dannyparsons** [comment]
2. is very simple to fix.

1. is a bit harder but could be done  and would be nice since it's a difficult dialog so good to make it as easy as we can.
