### ISSUE TITLE
Climatic > Dates > Infill Missing Dates

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4102]
In the attached data there are missing years towards the start of the record.  It is multiple elements but only a single station.

In the infilling I get:

Error running R command(s)

Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index

The error occurred in attempting to run the following R command(s):
InstatDataObject$infill_missing_dates(data_name="data_RDS", date_name="Date1")

[GT54_86.zip](https://github.com/africanmathsinitiative/R-Instat/files/1418173/GT54_86.zip)

**Comment by shadrackkibet** [comment]
oh! I added By factor element on this and it works.Not sure if this is correct.

**Comment by dannyparsons** [comment]
Yes I think adding by element is correct here, since it's similar to having multiple stations - although we may want infilling to be done differently because it will do each infilling for each element separately.

Aside from this we should have better error messages than this when there's something missing from the dialog.

**Comment by rdstern** [comment]
This bug - if it is the same has messed us up in the Mozambique workshop.
We had data for a single station that needed infill.  But there was no station variable.  It doesn't like it.  
It needs a station name, if there is infilling to be done.  It works fine if nothing needs to be infilled.
It may be simply that it now says something like:
336 values filled in for station xxx.
Perhaps all that needs to happen is to check that if no station is give, then it just says
366 values filled in

**Comment by shadrackkibet** [comment]
I don't seem to get this Bug. @rdstern  can you attach Mozambique dataset you used? I used above dataset GT54_86 and this now works properly.

**Comment by rdstern** [comment]
Good you don't get it!  Let me test your new version and get back to you.

**Comment by shadrackkibet** [comment]
Seems this is not closed automatically when PR was merged from another PR.

**Comment by dannyparsons** [comment]
I think maybe because you put "fixes" in a comment, and not in a commit or the PR description, but not sure...
