### ISSUE TITLE
Climatic menu changes

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4114]
These seem clearer now following the Guyana workshop.

1. Move the **line** down, or **Climdex** up.  So Climdex becomes part of the Prepare section.  It remains in the same position, i.e. below **Prepare**.
2. Delete **Display Daily** from the **Climatic > Prepare** sub-menu.  It is also in **Climatic > Check Data** menu and it was confusing to have it twice, so close together.
3. In **Climatic > Check Data > Boxplot** item add the "..." to Boxplot".
4. In the **Climatic > Check Data** change QC Procedures to **QC Rainfall**. I include the dialogue from Lazarus, see #2392.
5. In **Climatic > Check Data** add a further item **QC Temperatures** at the bottom, below QC Rainfall.   
6. In the **Climatic > Prepare** menu move Climatic Summaries below the line.  (There is then just Transform above the line.)

**Comment by Muthenya** [comment]
@rdstern I've already began working on the changes, though I've noticed that from proposed changes 4 and 5 (see #2392) QCRainfall and QCTemperature are also in the climatic menu as Rainfall and Temperature, that is, under Climatic > Describe. Should we keep these as well, or delete them from the menu?

**Comment by rdstern** [comment]
Well spotted.  Keep them there.  That's different.  That will do descriptive analyses for these elements (like the describe menu).  That's different from checking that the data are OK, which is part of the Prepare stuff.

**Comment by Muthenya** [comment]
Okay. Thank you.

**Comment by maxwellfundi** [comment]
Addressed on pull request #4117
