### ISSUE TITLE
Making the script window editable

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4115]
This is not just from me, but now from David!  We think it is a good possible task for Maxwell?

It is to make the Script window editable.
Then to be able to submit (run) either the window or the selected section.

According to David there are then 3 or 4 ways this could be run.  So the alternatives would be on a right-click menu.
There is then a health warning that running after editing the code carries a health risk.  Do you want to continue.  Like the warning when you delete columns.

But if it crashes we do now have our recovery options, so that's a good thing!

**Comment by dannyparsons** [comment]
There's a complication to this which is knowing how to display any output from the code. This is currently stored within the structures that produce the code. Once we paste the command into the script window that's all lost and we just have a string. Then we don't know what output to expect which we have to know to use the RLink properly. It's equivalent to when we rerun the log and don't get the graphs or output in the output window.

For anything that doesn't produce output there's no problem. For graphs, we could get them in an R viewer, but nowhere else. Text output we couldn't get. I think experimenting with the R link we might get a solution to this but not any time soon.
So if we allow this we might describe it as an "alpha" or "beta" feature which we know isn't going to work in all cases but people can try it at their own risk.

**Comment by rdstern** [comment]
I would still go for that.  It will work for most things in the Prepare menu and that's a good start.

**Comment by dannyparsons** [comment]
There are two separate issues needed to be solved here:

1. Deciding how we allow users to populate the script window e.g. just from one dialog, or allow it to build up as a script, pasting from other places etc.

2. Getting the text in the script window to run.

They can be done separately. I suggest @maxwellfundi can start on 2. This will probably use similar code to what is needed for #4116. I would guess there might be two options:
a) a right click option to run just the selected text
b) a button/right click to run the whole script window

but feel free to suggest something else.

**Comment by maxwellfundi** [comment]
I think getting scripts from individual dialogs would be great because if we wnated to have all the scripts run, that is available in the log window. 

So another question would be would we want these just to be re- run in R-Instat or could be opened in RStudio too. This would be a question for #4116

**Comment by maxwellfundi** [comment]
So here we now have two menu items for Running Selected text and the whole script. I prefer it that way other than having a button and its now editable. 

![image](https://user-images.githubusercontent.com/9798689/32884493-9cc35214-cacb-11e7-9731-9638ee3389f8.png)

**Comment by dannyparsons** [comment]
I would rather have a button for Run. It just seems more natural to click a button to run than a right click option. Right click I see as more being for additional options, not the main functionality.
I would be happy changing the Clear button to Run and putting Clear on right click instead.

Open in RStudio seems like another sensible option as well.

**Comment by maxwellfundi** [comment]
great, so i will have to change that to run and have the clear on the right click. However running in Rstudio will have a little more complications. I assume i have run R-Instat and did a couple of things then send say nth dialog code To Script. If i open just  that in RStudio it iwll not run because instatobject will not have been initialized.

So, would that be useful here and if yes, then do we have to run everything like we do for the log? @dannyparsons  what are your thoughts here?

**Comment by rdstern** [comment]
I would be assuming, in RStudio,  that if you run a single command, then you would have run others previously that set up the Instat object.  
Often you could run the first few commands to set this up.  Then you do a dialogue with the same data and want to extend that command.

If you run a random script then it would give an error!  That's OK!

**Comment by maxwellfundi** [comment]
I understand and  completely agree.

**Comment by rdstern** [comment]
I would like both - of course.  But running in RStudio may not be trivial, because that would only work if the Instat object used in the script were already in RStudio.  Though that could be up to the user perhaps to organise.

But this is also for those who would like to continue working in R-Instat.

Perhaps related (or not) I have been giving the command:

robustbase::adjbox(TMPMAX ~ month_abbr,plot=FALSE)  to see what it produces.
  
I have been typing it into the calculator as the only place I can do this.  I found the results (in the output window) to be very useful!

**Comment by dannyparsons** [comment]
We can do the same as we do for the Log window and have an Open Script file option or similar. I don't see this as being very useful because it will usually be quite short and you can just copy and paste it into RStudio. And since it's likely needed to be added to a bigger script anyway (so that it runs properly), it's less likely you want it in a separate file. 
However, since it's easy we might as well do this. If we find it's not useful we can always remove it.

**Comment by maxwellfundi** [comment]
@dannyparsons  great adding the "Run in R Studio". I think we could have two of these-  A button of opening all Script in R studio like we have for the run, and a right click for opening Selected text in R Studio.

**Comment by dannyparsons** [comment]
I don't think we can do "Run in RStudio" instead it's "Open Script" (it might not be RStudio if they don't have it)
I don't think we need an Open Selected Text because that's probably easier to do as Copy and Paste.

**Comment by maxwellfundi** [comment]
Okay then i think the best in that case is to have an "Open Script" button next to the Run which does a similar thing as the Opening log

**Comment by maxwellfundi** [comment]
@dannyparsons  Another question on this is if we will use the same directory as the log files, or we could creare a new scripts directory.
