### ISSUE TITLE
Calculations - mainly Statistics keyboard

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4125]
There are going to be a series of issues concerned with the calculator.  Perhaps Maxwell could propose one person who might concentrate on it.  Perhaps the work can start on this dialogue in 0.4.7 - which I have given as the current milestone.  But it is unlikely to finish then.  It also depends on the other tasks for AMI staff.

The first set - in this issue concerns the current Statistics keyboard.

1. Please could it be called **Summary** instead, both in the pull-down and also above the keyboard.
2. The keyboard is currently 3 columns of 4 rows.  Others are larger.  I now suggest **5 columns by 4 rows**.
3. **All the existing 12 items remain**, though I suggest in a different order.
4. Most of them use the default argument na.rm=FALSE.  So when there are any missing values the result is missing.  I suggest this should be changed to **na.rm=TRUE**.  
5. I think they all work, except quantile.  This has an additional argument names=TRUE.  It should change to **names=FALSE**.
6. The width of the buttons could change, so the full names can be on a single line.  This is currently not the case for **quantile**.
7. The button called count should change to say **length**.  The word count is perhaps clearer, but length is the command in R and we might as well use that when we can. 
8.  The common feature of this keyboard is that each button here produces a single summary value.  If it displays in the output window, or with the helpful Try feature in the dialogue we can see this.  When writing to a column it produces a column with this single value repeated.
9. It is a good time to add tool-tips.  I'll give them below.
10. The first column is then length (old count), non-miss (that's new and in our summary), miss (already there) and distinct (also new, it is the n_distinct function from dplyr.)
11. The second column is sum, mean, var, sd (all there now).
12. 11. The third column is max, median, min, range  (all there now).
13. The 4th column is cv, iqr, skew, anyDup, (iqr is there now, cv, and skew are all now part of the Summarise dialogue.  anyDup is short for anyDuplicated in the Data Table package and can be typed now.)
14. The fifth column is mad, mc, propn, quantile  (mad and mc are part of the summarise, quantile is there now and propn is new.)

So propn (proportion) is new.  It is the inverse of quantile.  For quantile you supply a value, e.g. 0.5 and it gives the corresponding value.  For example with 0.5 it gives the median.  For proportion you give the value, e.g. 10 and it gives the proportion.

It is described in the R discussions as coming from the ecdf function.  Calculated directly it is (I think) just mean(x= **column** <= **value**, na.rm = TRUE).  Put the default as 1 as the value, just as 0.5 is the default for the quantile.

The only other new one is the number of unique values in a column.  This is given by length(unique(x = **column**)).

**Comment by shadrackkibet** [comment]
This is related with #4126 and  #4128 which i am working on.

**Comment by shadrackkibet** [comment]
> It is a good time to add tool-tips. I'll give them below.

@rdstern Which Tooltips should we have in this keyboard?

**Comment by shadrackkibet** [comment]
@rdstern ?
