### ISSUE TITLE
Calculations - Logical keyboard

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4126]
We currently have a keyboard called Logical and symbols.

I suggest it becomes a Logical keyboard only.  It still has  4 rows and 4 columns; the keys could become wider if needed in some of the columns.

1. First column could be **< , <=, > >=**.  They are all there now.
2. Second column could be **==, !=, |, &.**  (i.e. equals, not equals, or, and). They are all there now, but & is currently given as And.
3. Third could be **ifelse, match, when and between**.  These are new.  **ifelse** is really **useful**. match is the same as %in% and the others help to turn missing rows into logical.  For **ifelse** consider using the if_else function from dplyr. (Still call it ifelse on the keyboard.)  when is case_when from dplyr and between is also from dplyr.
4. The fourth column is **is.na, !is.na, duplic (for duplicated) and near**.  These are new again.  near is from dplyr.

In addition we could have a 5th column with any, all, isTRUE and isFalse.  However, they are different as they give a single value.  Needs discussion to see if they are needed.

**Comment by dannyparsons** [comment]
There's no `isFALSE` command in base, unless it's in another package I don't think it exists. Otherwise this looks good.

**Comment by rdstern** [comment]
I am not sure we need the 5th column of functions at all in the keyboard.  One item missing is xor(), so that could be instead of isFALSE.  But neither isTRUE or isFALSE may be that useful.

[https://stat.ethz.ch/R-manual/R-devel/library/base/html/Logic.html](url) does give the impression that isFALSE is available?

**Comment by dannyparsons** [comment]
Very strange it's there in documentation but not in R. I updated to the latest version of R but still not there. Maybe it's been removed? Does anyone else have this function in their R?

**Comment by shadrackkibet** [comment]
Working on this in combination with #4128

**Comment by shadrackkibet** [comment]
@dannyparsons  this can now be closed.
