### ISSUE TITLE
Calculations - new keyboard

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4128]
I (very imaginatively) called this keyboard **More**, which Danny doesn't like.  So ideas welcome on a more informative and appropriate name.  Perhaps **Transform**?

Two important functions are to lag a column and also to take differences.

Here is the suggestion.  4 rows as always, and 4 columns (so far).

1. First column from the top is **lag, diff, ecdf, ntile**.  The lag and diff are from the zoo package (which is already installed).  Then ecdf is also simpler as cume_dist in dplyr and ntile is also in dplyr.
2. Second column is all from zoo and is moving (running) statistics, namely movmax, movsum, movmean, movmed (or movmedian if there is space).  (Note there isn't a moving min, but you could do -movmax(-x)!
3. Third column is cumulative functions, namely cummax, cumsum, cummean, cummin.  (Here all except cummean are in base, while cummean is in dplyr.)
4. Fourth column is ranks in different ways and is all from dplyr. It is rank, m_rank, d_rank, %rank.  (rank is row_number, m_rank is min_rank, d_rank is dense_rank and %rank is percent_rank.

And advance notice that we may also need a symbols keyboard, with :, %%, %/%, [ ], etc.  Not sure what else is needed or where it should go?

**Comment by shadrackkibet** [comment]
Starting some work on this. Where should this be in climatic menu for now.

**Comment by rdstern** [comment]
That's great.  For now it should just stay where it is.  So it is just an extra keyboard in the Prepare Columns: Calculations > Calculations dialogue.

The functions are very useful for climatic, but when they go there it could be a simpler dialogue for lagging, differences, etc.  We start with the general facility

**Comment by shadrackkibet** [comment]
I see we already have most of this options in our current calculator.Does this mean i add this options since they are from this packages?

**Comment by rdstern** [comment]
I don't understand? Where do we have these options for this keyboard, i.e. diff, lag, etc?

**Comment by shadrackkibet** [comment]
In the dropdown we have;

![image](https://user-images.githubusercontent.com/26301973/32546071-e6ef306c-c48e-11e7-934a-27f0b4b00173.png)

**Comment by shadrackkibet** [comment]
We have some of this options on **Rows** and **logical and symbols**.

**Comment by rdstern** [comment]
You are right.  I hadn't looked there, because (on the rows) keyboard it is only really the pmax and pmin that are row operations.  But you could expand that keyboard, rather than starting a new one.  Let's call it transform for now.

The lead and lag are just what is needed.  Except that when you give the arguments it doesn't include the n=1 argument - which is the default.  But it is sometimes useful to have other values.  So please check what is there.  Also the existing keyboards have some instances where the text is very small.  We should avoid that.  It may mean we have a few double-size keys, or one column of keys is wider than others.

I have also made another 2 issues, one to improve the logical keyboard and the other for an improved statistics keyboard.

**Comment by shadrackkibet** [comment]
> First column from the top is lag, diff, ecdf, ntile. The lag and diff are from the zoo package (which is already installed). Then ecdf is also simpler as cume_dist in dplyr and ntile is also in dplyr.

@rdstern i can't see **lag** and **diff** functions from zoo package here.
**ecdf** also is nowhere from dplyr package.

**Comment by rdstern** [comment]
You don't need lag from zoo, because you have it (and lead) from dplyr.
In the zoo documentation diff is hidden under lag.zoo.  This is the version of diff that we want, because the one in base (or stats) does it fin, but produces a column of shorter length.  The one in zoo pads it automatically with NA, which is what we want.

ecdf is in dplyr.  I am suggesting the label ecdf, but (as mentioned above) it is **cume_dist** in dplyr.  It is in the section on ranks.

**Comment by shadrackkibet** [comment]
@dannyparsons this can now be closed.

**Comment by rdstern** [comment]
The diff from the zoo package isn't yet implemented in the transform dialogue.  The button gives lag instead.
