### ISSUE TITLE
Enable and disable model and climatic features

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4135]
This is a small task for Maxwell to allocate.

1. Could we enable two features so I can check what is working:

a) The Model > Two Variable > Fit Model dialogue.  Enable 2 sample button.
b) The Model > Two Variable > Fit Model Display options sub-dialogue.  The Save Tab has all options disabled.  Could they be enabled.

2. Climatic > Check Data > Boxplot should now be disabled.  (Fixing it will be moved as an issue to 0.4.9.)

**Comment by Muthenya** [comment]
@rdstern I've made the changes, though I've noted some of the issues with the dlgTwoVariableFitModel dialog's designer, on which when changed an error message pops up.

**Comment by maxwellfundi** [comment]
@Muthenya  whats happening with this?

**Comment by Muthenya** [comment]
@rdstern I'm going to open a pull request on the changes that I've made.
