### ISSUE TITLE
Single boxplot not working

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4170]
On some machines a single boxplot doesn't display.  It is just a blank screen.  The corresponding R code was ...

**Comment by dannyparsons** [comment]
Can you paste the R code? Could this be the issue of using R 3.4.2? This will be fixed in the new version.

**Comment by Ogik99** [comment]
I think this issue was resolved. Could we close it?

**Comment by dannyparsons** [comment]
I think so, it can be reopened if not.
