### ISSUE TITLE
French version?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4176]
I have set it to French to see what happens.
I think it is leaving the size of the controls OK, but hence not always including all the words from the translation.
I think that is OK, but note a couple of controls that could usefully expand that I use frequently.  This is mainly the filter menu, but one point is the data selector:
1. On all dialogues we have Data Options.  I assume this translates to Options de donnees.  But all that appears so far is Options de.  If the control had space for a third line it would be OK.
2. On the filter sub-dialogue we have (in English) Add Condition.  In French I assume it is Ajouter une Condition.  But it only gets as far as Ajouter une.  No problem making the control larger.
3. This is now a different point.  At the bottom of the Filter sub-dialogue in English it says "New name of filter".  this translates to Nouveau nom du filter.  But Nouveau is so much longer than new so it doesn't fit.  Here is an example where I question the English.  Why do we say "New" and not just Name of filter?  Then there would be space!

**Comment by Patowhiz** [comment]
Well, @dannyparsons  I'm interested in knowing how you will solve this problem, because I think French is probably not the only language with long _"spellings of words"_ . If we generally increase the size of controls during design because of French Translation what about other translations. Does it mean we will keep on increasing the controls till _"one size fits"_ all is achieved.

**Comment by dannyparsons** [comment]
Yes, French won't be the only language with this problem, and even within languages some phrases will be longer and some shorter.

With the localisation of forms now done, the size and location of controls is actually language dependent. So we can actually have controls being different sizes for different languages. So we shouldn't need to increase sizes for every language just to suit one language.

This sounds good, but there's some details that I haven't figured out yet. For example, if I change the size of a control on the designer, it updates the size in the resource file. However, it seems that the "translated" size for other languages remains the old size. If I change the language of the form (under localisable) to one of our other langauges, it still has the old size.

So what we need to understand is how do we get the sizes to update for all languages when it's changed in the base language? It can't be that we have the do this manually for every dialog - that would be terrible. Maybe, we have to run through the auto-translate again? But will that override translations we have already changed. That's the problem of keeping things the same for different languages.

If I do decide to have a control in a different size for one language, will rerunning the autotranslate reset this size, or keep it?

So there's quite a few questions I still have about the resource files and how this relates to what we will want to do for different languages. It would be great for someone to look into this more and report back findings.

**Comment by dannyparsons** [comment]
@isedwards have you come across these issues with the Multilingual toolkit in CLIMSOFT?

**Comment by rdstern** [comment]
Great that we have the French version now.

Oddities I have noticed so far:
a) Data Options has become Options de - no space for donnees in the button.
b) line plot is translated as Terrain en ligne.  Is that correct, i.e. terrain?
c) When we return to English it remains as Terrain en Ligne
d) A lot remains to be translated.  I remember before that Add Condition (in the filter) became Ajouter de - no space for condition.  Now it is still in English.  Is it just that only a few dialogues etc have been translated?

**Comment by dannyparsons** [comment]
It's a mixture of some things not being translated yet and also the translation system sometimes not translating certain controls. I will soon send the instructions and process for someone to work on translations.

**Comment by rdstern** [comment]
Great.  We discussed translation into Swahili and decided it wasn't an immediate priority.  But getting the French working well would be good, now it has started.  Then possibly Spanish, or even Portuguese!  I have suggested mid-August, i.e. Version 0.5 it will have advanced a bit.  It is a good innovation for Version 0.5.0.  I am conscious that 0.5.0 (August) might become 0.4.21 and 0.5.1 then becomes 0.5.0.

**Comment by rdstern** [comment]
I wonder what happens with error messages etc in French?  It looks as though output may also be possible?
See [here](https://stackoverflow.com/questions/13575180/how-to-change-language-settings-in-r) for example.

**Comment by dannyparsons** [comment]
We could easily set the R language in this way so that R errors display in the set language. We also then need to ensure our own error messages get translated too as they are not automatically added to the resource file but could be done manually.

**Comment by dannyparsons** [comment]
On the version numbers, I like having V 0.5 timed with the new version of rdotnet which will be compatible with R 3.5.0, the coincidence of these numbers will be useful to users too I think. I'm following the progress of rdotnet and there is now a testing version which looks promising for working with R 3.5.0 but not yet clear when it will be officially released.

**Comment by rdstern** [comment]
Now the issues with the French version seem more resolved, could we have a translation table for the French version please?

I assume this will be mentioned in the deliverables from the current Oxford grant.  On my side I would like to move forward, because a second Haiti workshop is on the cards - and Carloline Staub is likely to be able to help with translation.

I also think that the existence of the table could be interesting to ask Alex and Carlos about Spanish.

When I ask David he says (as he does for many things) that to do this all properly needs to wait for his mythical (UK) programmer to be added to the team.  But here he has said that producing some sort of table should be easy - and I presume Zed may already be using one?

**Comment by dannyparsons** [comment]
I have created a new repository to store the translation files, since they are quite large, and to keep them separate from the code https://github.com/africanmathsinitiative/R-Instat-Translations. In the readme file are instructions for how to contribute to translations which anyone should be able to follow.

In the long term there are issues with our current implementation, however we can easily add new languages now and even if we change systems I expect the translated texts will still be usable.

**Comment by Ogik99** [comment]
#5096 addresses similar concerns (and has since been closed).
@maxwellfundi  is there need to close this issue as well?
