### ISSUE TITLE
Issues in Version 0.4.7

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4189]
There are some issues with the new radio buttons.  I don't know how serious.

1. Prepare > data Frame > Insert Columns/Rows ony has one button for columns (I think).
2. Delete columns rows looked fine - the first time I went in.  But then not the second time.
3. Check data > Duplicates buttons moved but all usable.
4. Same for boxplots.  I guess they are always a bit messed up.  I'll only report when they are unusable.
5. One Variable > Frequencies ok first time then buttons move.
6. Factor > Contrasts crashes, but can press Continue.  Guess resource file again?
7. The text columns have the new buttons to be fixed.  **Transform** gave errors a few times, but then showed the dialogue.  No error message second time.
8. String > Distance is more extreme than the others in moving the buttons.
9. Add comment is not yet used, but the button is seriously moved.
10. Rename Data frame doesn't work and gives error.
11. Copy Data Frame has same problem.
12.  Now into Describe menu - 2 variable graph has a problem.  Then shows the dialogue, but it is a bit messed up.
13. Bar chart had radio button so pie chart is not visible.
13a Model all OK - ish
14. Climatic Open SSTs doesn't and gives error.
15. Check > Display daily has unusable button after first time in dialogue.
16.  Rest of climatic sort of Ok as is Procurement.
17. ODK has unusable buttons on second time round.  Rest of File is OK.

**Comment by maxwellfundi** [comment]
Am checking on Describe now.

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/developers I have not figured exactly what is causing the mess in the new style radio buttons. 

I suggest for this version, we simply have a temporary solution by getting back the localizable= False for the dialogs that have issues as it was before, before we figure out completely whats happening.  

What are your thoughts?

**Comment by Patowhiz** [comment]
And also I think it's important to **LOCK** the controls once you are **DONE** with designing the form. There is a **feature** in visual studio  for locking a form to ensure the controls don't move even when they are opened in other computers. I have gone through the entire forms and I have seen several forms having the radio buttons offset.

**Comment by dannyparsons** [comment]
@patowhiz I'm not sure Lock will solve this problem because the issue is occurring when we apply the resources during translating - but it might do so worth checking. The reason for the offset is the way in which we use ucrPanel and buttons in them, it's an issue about the relative location being different after the first time it's opened.

I'm going to change the translation class temporarily to stop the Panels being "translated" so it will stop shifting. Although this isn't a good long term solution since radio button text won't be translated with this fix.

Can you try locking one of the problem forms and seeing what this does?

**Comment by dannyparsons** [comment]
@maxwellfundi If I can't fix it through the translations class then your solution is the next best idea. I'll try this first since this is less work than changing all those forms if it works.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers please check that the dialogs mentioned now do not have any issues

**Comment by Patowhiz** [comment]
I have verified that the mentioned dialogs don't have any issues. The radio buttons are now very well arranged.
