### ISSUE TITLE
Extra help in Open from library

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4193]
I wonder if this is just my machine?

In the Open from Library on R data sets there is a second help button.  For me now the command is given fine - as before - e.g. 

Opening help page for abbey dataset. Generated from dialog Open Dataset from Library
utils::help(topic="abbey", package="MASS", help_type="html")

but no help appears in the browser.

**Comment by maxwellfundi** [comment]
This seems to be working correctly on my machine. It could be an issue with yours. @africanmathsinitiative/developers can everyone check if this is happening to your machines.

**Comment by shadrackkibet** [comment]
This is not working in my machine .I have tried running this in R and it doesn't appear in the browser but i see help is there in R. Seems this is an R issue.

**Comment by dannyparsons** [comment]
Which version of R is everyone using?

**Comment by rdstern** [comment]
I am using 3.4.2 - RDS

**Comment by shadrackkibet** [comment]
3.4.2

**Comment by Patowhiz** [comment]
3.4.1

**Comment by Patowhiz** [comment]
3.4.1

**Comment by maxwellfundi** [comment]
MFN is currently using 3.4.2 which has same issue as RDSs. I was using 3.4.1 before so it might be an issue with the latest version.

**Comment by dannyparsons** [comment]
If it's an issue with R 3.4.2 then this could be similar to the problem we had with graphs not displaying as well. Will continue to look into this.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers please check if #4242 has resolved this. On my machine it is now working.

**Comment by shadrackkibet** [comment]
This is now working on my machine.

**Comment by Patowhiz** [comment]
Its working on my machine

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/developers  This seems to work properly now.
