### ISSUE TITLE
Adding mosaic plots

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4196]
In extending bar charts, and generally plotting multiple factors, the way seems to be through mosaic plots.
 Another variation seems to be a double-decker plot.

These now seem to be implemented in ggplot2 through the ggmosaic package.  It basically adds geom_mosaic to the types of geom that can be used.  

There is a useful vignette 

My guess is that it will become a **Describe > Specific > Mosaic** menu item, but it needs a bit more exploration first.

It may be easy, which is why I am suggesting we at least look at it for version 0.4.9.

**Comment by maxwellfundi** [comment]
The link here seems to be broken. It does not lead to a page

**Comment by rdstern** [comment]
Odd.  If you look for "CRAN ggmosaic" on google, that was where you go.  But you are right.  It does not appear.

The team in Colombo, Sri Lanka have asked for a dialogue they can use to learn to start programming.  I have suggested this is a good one.  They are statisticians with computing - mainly R (and I think python) experience.  

We should also be adding the geom_mosaic to the list of geoms.  That seems potentially tricky as a starter, but perfect for Maxwell.  I am beginning to wonder if it is the right starting dialogue?

What do you think?

**Comment by dannyparsons** [comment]
> There is a useful vignette https://cran.r-project.org/web/packages/ggmosaic/vignettes/ggmosaic.html

**Comment by maxwellfundi** [comment]
I have looked at mosaic and I have a feeling it might be confusing and a little complicated for a beginer who might not understand how ggplot works.  

I will add the geom Mosaic on the list of geoms and maybe create the dialog too for the mosaic.

**Comment by rdstern** [comment]
Yes, I wasn't sure about the dialogue, which we could discuss next week.  It might become another button on the bar chart dialogues instead.  meanwhile ig the geom can be added that would be great.

**Comment by maxwellfundi** [comment]
Sounds good.

**Comment by dannyparsons** [comment]
@maxwellfundi Could you or could you assign someone to add this geom now? I would like this for the workshop in the next release. I am going to think about the design of the dialog and specify that but the geom can already be added.

**Comment by dannyparsons** [comment]
@rdstern I think this is a separate **Describe > Specific > Mosaic** dialog as opposed to extending the existing bar chart dialog. Although bar char is technically a subset of what `geom_mosaic` can do, there's lots of different concepts and I think keeping them separate makes sense.

**Comment by maxwellfundi** [comment]
I will take on this task today.

**Comment by Ogik99** [comment]
Seems like this task was completed. Can it be closed now
