### ISSUE TITLE
Boxplots (and others) by more than factor columns?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4211]
The command in ggplot as follows

ggplot(nass.corn, aes(year, acres)) + geom_boxplot(aes(group=year))

Seems to indicate that ggplot can cope with boxplots by year, where year is numeric.  That will allow much more flexible x-axis labelling.  

I wonder how this can be incorporated into our dialogues - at least for boxplots, but perhaps there is a more general option here?  It may need some thought and discussion.

**Comment by rdstern** [comment]
With the new script window I first used the boxplot dialogue and got the following command:

**code generated by the dialog Boxplot**

_Dodoma <- InstatDataObject$get_data_frame(data_name="Dodoma")
last_graph <- ggplot2::ggplot(data=Dodoma, mapping=ggplot2::aes(y=Tmax, x=Year)) + ggplot2::geom_boxplot() + theme_grey()
InstatDataObject$add_graph(data_name="Dodoma", graph=last_graph, graph_name="last_graph")
InstatDataObject$get_graphs(graph_name="last_graph", data_name="Dodoma")
rm(list=c("Dodoma", "last_graph"))_

I ran it twice - nice: Here is the graph:
![image](https://user-images.githubusercontent.com/11226469/32988387-a3cde9b6-ccfb-11e7-9f9e-9240ec9033c4.png)

Then I edited one line of the text to:
last_graph <- ggplot2::ggplot(data=Dodoma, mapping=ggplot2::aes(y=Tmax, x=**Year1**)) + ggplot2::geom_boxplot(**aes(group=Year1)**) + theme_grey()

(My small changes are in bold.)  The column Year1 is the same as the original Year, but is numeric.  It runs fine and I get:

![image](https://user-images.githubusercontent.com/11226469/32988415-5d3b2698-ccfc-11e7-8a79-a2cdf857bcd9.png)

I think that justifies a whoopee!  The x-axis is now fine, and the unused "levels" at the start have been ignored automatically.

So here are some suggestions:
1) **Improve the R code for the boxplot anyway.**  Need to check with people who know R better, but I think that you could add the **aes(Group=Year)** in the original boxplot code with no problem.  Then a quick solution is to change the type of column in the data and it will run with Year as a numeric column.  This can then be done through the dialogues, without using the script file.
2) Use **Data Options** within the dialogue.  Could you permit column types to be changed through this, (perhaps on the fly) as one of your column options?
3) Once in the receiver, permit the data selector right-click to allow more column types on this occasion.  There could be a special option - below a line - "Include numeric columns".  Perhaps also "Include all columns" and "Include factor columns".  This is then sort of - at your own risk!  It would allow us toi choose inappropriate columns for a given command.
4) In this particular (boxplot) case have a checkbox with the label "Numeric also".  

I think my bias - at least for now - would be option 3, i.e. data selector right-click in addition to doing option 1 anyway.

**Comment by rdstern** [comment]
OK, after discussion with Danny the urgent actions on the Boxplot dialogue are as follows:
1) Change the R-code, so it adds the code **aes(Group=Column selected)** to the R code.  This is to be added inside the boxplot geom, i.e. what was boxplot() now becomes boxplot(aes(Group=Column selected)"
2) In that receiver allow any column, not just the factor columns.
3) We may want to change the label from Factor (Optional).  For now leave that, because it will almost always be a factor.
4) At this stage don't bother with any changes (e.g. right-click) in the data selector.

**Comment by rdstern** [comment]
The change has introduced a new problem, so has to be considered again. 
The second factor in the boxplots is now ignored.  This affects the ordinary boxplot (Single) when you include both factors and the multiple columns when you add a factor.

**Comment by maxwellfundi** [comment]
I just have noticed this now, should this mean we could remove (undo) the change we included recently?

**Comment by rdstern** [comment]
Then I think we lose the option of having the x variable as numeric.

**Comment by dannyparsons** [comment]
From here https://stackoverflow.com/questions/45101003/fill-and-dodge-boxplots-by-group-on-a-continuous-x-axis it seems that in this case you then have to group by both "by" variables, e.g:

`ggplot(data=survey, mapping=aes(y=Yield, fill=Village., x=Fert)) + geom_boxplot(aes(group=interaction(Fert, Village.)))`

This is ok, for this case, but if I then went to the boxplot sub dialog and added a colour, I would get the same issue, unless I added the colour variable to the interaction.

By default ggplot groups by all discrete variables so by overriding it we lose the grouping of any factors that we use unless we add them back manually. I'm not sure there is an easy way to get around this in general.

**Comment by maxwellfundi** [comment]
@dannyparsons  would you then suggest that we revert back to the old way by removing the group then move this issue to a later time so that we will have known how to do it?

**Comment by dannyparsons** [comment]
I think we should probably remove it for now since it prevents other receivers working.

**Comment by rdstern** [comment]
@maxwellfundi was something done on this?

**Comment by maxwellfundi** [comment]
@rdstern  from the previous discussion you were not sure if we wanted to remove it or not but from @dannyparsons  view, if its preventing other receivers from work then we can remove it, which was my initial thought. 
I am going to remove the  geom_boxplot(aes(group=year)) then we can think more carefully how we get it to work in the future.

**Comment by rdstern** [comment]
You are right, we have to remove this for now.   As a temporary measure we might be able to edit the script file.  And possibly the special climatic boxplot in the future might include the feature.  But that's not for the next release.
