### ISSUE TITLE
Cannot open R-Instat after installing

### ISSUE THREAD

**Issue by Wendso** [africanmathsinitiative/R-Instat#4217]
Hello, Please help me find a solution
I just installed R-Instat using the instructions. Even the R packages were installed. But when I am trying to open R-Instat, i get an error: "Unhandled exception has occured in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately". Then i clicked on Continue, but it is running since one hour without showing the menu and i can't work on the software. Please help me to fix this
Thank you

**Comment by dannyparsons** [comment]
Hi, there does seem to be an issue with this current version for users installing R-Instat for the first time.

We will shortly upload an updated version which will fix this.

As a temporary fix for the version you have, you can extract the `Options.bin` file in the zip file below and then put it in the folder: `C:\Users\[UserName]\AppData\Roaming\RInstat`
where `[UserName]` is the name of your user account.

[Options.zip](https://github.com/africanmathsinitiative/R-Instat/files/1485818/Options.zip)

Close R-Instat before doing this and then rerun it again and it should work.

**Comment by Wendso** [comment]
Thank you so much, it is working Agathe W. A. OUEDRAOGO
Engineer in Water Infrastructures - Ph.D Student Option: Arid and Semi-Arid Lands/ Environment 
Phone: (+254) 734 85 75 03
WhatsApp: +226 70 99 05 40
Skype: edisonoued



Postal Address: P. O. Box 62000 00200 Nairobi
Physical Address: JKUAT – Juja Campus AICAD – Block C, Room 101
Tel: +254 718 092 689 , 0788 427 710
Email: directorpauisti@jkuat.ac.ke 

    Le Dimanche 19 novembre 2017 21h26, Danny Parsons <notifications@github.com> a écrit :
 

 Hi, there does seem to be an issue with this current version for users installing R-Instat for the first time.We will shortly upload an updated version which will fix this.As a temporary fix for the version you have, you can extract the Options.bin file in the zip file below and then put it in the folder: C:\Users\[UserName]\AppData\Roaming\RInstat
where [UserName] is the name of your user account.Options.zipClose R-Instat before doing this and then rerun it again and it should work.—

**Comment by dannyparsons** [comment]
Great to hear that. You're welcome.
