### ISSUE TITLE
Resizing data frame selector

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4229]
We resized the selectors, including the data frame selector. This all looks fine apart from dialogs which have the data frame selector on it's on. One is the merge dialog, so the data frame selectors need to be resized on that dialog. There are others - I think on the File menu. Could someone go through and check dialogs and do the resizing? It shouldn't be too many dialogs.

**Comment by maxwellfundi** [comment]
@Muthenya  could you take on this task?

**Comment by Muthenya** [comment]
Okay.

**Comment by Muthenya** [comment]
**@africanmathsinitiative/developers** I have gone through the dialogs and I've found those with issues with the Data Frame Selector. Please go through them and let me know if you are working on any of them.

**In the Prepare Menu**
1. Reoder Columns
2. Export to OpenRefine
3. Regular Sequence
4. Enter
5. Generate Random Samples
6. Append Data Frames
7. View and Remove Links
8. Delete Data Frames
9. Hide Data Frames
10. Add Comment
11. Rename Data Frame
12. Reorder.

**In Climatic Menu**
1. Import from Climsoft
2. Export to CPT
3. Fit an Extreme Distribution

If there is any that I've missed, please let me know. Thank you.
