### ISSUE TITLE
Additional feature on column summaries

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4230]
When using the general summaries I accidentally put the summary back into the original worksheet.

This reminds me that it is a useful feature for the Column Summaries dialogue.  I assume it should be quite simple to add?

**Comment by rdstern** [comment]
After discussion with David and Danny, the route for this - which still seems simple - could be as follows:

a.	The Option “**Store Results in Data**” should be shortened to “**Store Results**”.  When this is ticked, then a new option just beneath that, and indented, has the label “**Original Level**”.
b.	This dialogue **Prepare > Column: Reshape > Column Summaries** and the **General Summaries** dialogue be added to the **Prepare > Column: Calculate** menu.  It is just under Calculations and above the line.  
c.     The Original Level checkbox is (by default) ticked in this version of the Column Summaries Dialogue.
d.	In the **Prepare > Column: Reshape > Column Summaries** version of the dialogue the **Original Level checkbox** is (by default) unchecked.

**Comment by dannyparsons** [comment]
I have now added `original_level` as a parameter to `calculate_summary` (#4351) so the modifications to the dialog should now be possible.

**Comment by shadrackkibet** [comment]
**c** and **d**  are contradicting. @rdstern could you please clarify this?

**Comment by rdstern** [comment]
The idea is that the Column Summaries is now to be in 2 places, namely also in **Prepare > Column: Calculate** (under Calculations) and above the line.  It is still (of course) the first item in Prepare > Column: Reshape.  
So item c) refers to the version in the **Column: Calculate** menu, while d) refers to the version in the **Column: Reshape** menu.

**Comment by dannyparsons** [comment]
Will need to think about how to have different defaults from different places in the menu. First step is just to get the new checkbox working. We can discuss about the defaults then.
