### ISSUE TITLE
Group aes for geom_line

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4238]
The group aes is very useful for geom_line http://ggplot2.tidyverse.org/reference/aes_group_order.html

In the layer subdialog for Line Plot there is no group aes so it needs to be added.

**Comment by maxwellfundi** [comment]
I see it is similar to the boxplot in the issue #4211 because it needs group to be passed in the geom like- ` geom_line(aes(group = Subject))`

Can we add it on the main dialog @dannyparsons ?

**Comment by dannyparsons** [comment]
It's also about group but it's different. In #4211 the group needs to be added automatically for boxplot.
Here I am just saying group should be part of the definition of geom_line so that I can add group from the subdialog. I don't think it's common enough to be needed on the main dialog, yet.

**Comment by maxwellfundi** [comment]
Well okay. Thats easy.. on it now
