### ISSUE TITLE
How do I do coord_flip?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4251]
This may be a silly question, but I couldn't find it.

I can do coord_flip on some of the graphs, because it is on the main dialogue.  

I don't mind that it is missing on some, (e.g. Line Plots, Scatterplots)  because they have enough on the main dialogue.  And I haven't yet missed it for those graphs - but where is it?

I assumed it might be on the Coordinates Tab, but there is nothing there.  If I am right, then could it go there? The only complication would be that it should automatically be the same as on the main dialogue, for those plots that now have it in 2 places.

I can now do it, by editing the command in the script window.  Great we have this at last.  But there should be an easier way for this feature.

**Comment by maxwellfundi** [comment]
I suggest that we do coordflip either on the main dialog for all graphics dialogs/on the coordinates tab to maintain our 'spirit' of consistency. I would rather we have the coordflip on the coordinates tab for all dialogs.

**Comment by rdstern** [comment]
That's fine.  I agree.  
Does that mean that (for consistency) you are taking it away from (say) box-plots?  I'd be happy with that too.
I suggest on the coordinates tab you could say **Horizontal Plot (coord-flip)**.  We have more space there!

**Comment by maxwellfundi** [comment]
I would like it more if all the Horizontal plots are taken there and we remove them completely from the main dialogs.

**Comment by rdstern** [comment]
I agree completely.  Let's do that.

**Comment by rdstern** [comment]
A good consequence of this strategy (of making clear and good use of the plot sub-dialogue) is that the **legend** pull-down could usefully go onto the main screen of the Themes tab.  
I had earlier suggested it could go on the main dialogue for the parallel coordinate plot.  But I think the main themes sub-dialogue will be fair to all the specific plots, while continuing to help keep the main dialogues relatively simple.

**Comment by maxwellfundi** [comment]
That sounds good to have the legend on the themes. Will add those there too.

**Comment by dannyparsons** [comment]
> I suggest that we do coordflip either on the main dialog for all graphics dialogs/on the coordinates tab to maintain our 'spirit' of consistency.

I don't agree with these being the only two options. The coordinates flip should definitely be on the sub dialog because it is a general option.
Then a separate decision is whether it is common enough to be needed on main dialogs. I can imagine that for some graphs coord flip is common (boxplots) and others not (scatter plot). So I don't see a problem it being on some main dialogs and not others. 
If we decide it's not common enough for any main dialogs that's fine, but that's a separate decision from adding this option as a general option.

**Comment by maxwellfundi** [comment]
Okay. Then from what you say I think we could then leave the flips where
they are on some dialogs but still have itas a general option.

**Comment by dannyparsons** [comment]
Sounds fine. We may still decide we want to remove from some main dialogs if we feel they are not common enough or the main dialogs get too full.

**Comment by maxwellfundi** [comment]
Great.
