### ISSUE TITLE
The theme tab on sdgplot

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4252]
The legend is part of the them tab.
I wonder if we could also have one aspect of the legend on the main plot dialogues?
This is initially for discussion.  It would be an easy way to add the argument theme(legend.position) to the ggplot command.
I assume it might be a check box, but I am not sure. 
The options could then be Default, right, left, bottom, top, none.  Default would the default! - which is why I wonder if we need the checkbox.  This would not give the argument.  I can see some uses for Bottom, but am particularly interested in none.  That gets rid of the legend and makes more space for the plot.  That can be particularly useful with facets when it is good to have all the area we need.

**Comment by maxwellfundi** [comment]
I will be adding this legend position on the theme tab on the sdgPlots.

**Comment by rdstern** [comment]
Great.  This is all coming together well.

**Comment by rdstern** [comment]
I have changed the title of this issue, because I propose the legend be just one of the items on the (main) theme tab.  Now I am using the plotting more I have more items that could warrant inclusion on this tab - rather than having to go into the details of the themes.  

We had always assumed this would be the case, but were not sure what to put there.  I now see more clearly, at least some of the items, as follows:

1) Legend as started this all off.  Including the option of no legend.
2) Grid lines for x and y separately.  They are on Panel (More Options).  I suggest just Width and Colour is needed on the main tab.
3) x and y axis labels - this is to change the size particularly, and we might as well include the font ( called family in the sub-dialogue) and face (bold etc.)

There may late be others, but these are the aspects I use regularly in drawing plots. 

I suggest also that the items here might also be on the initial tab of the themes main dialogue.

**Comment by maxwellfundi** [comment]
@rdstern  there was a fourth thing here that needed to go onto this themes tab on the graphs subdialog which I do not seem to remember.

**Comment by rdstern** [comment]
How could you forget!  It is my angle of the x-axis labels!

**Comment by maxwellfundi** [comment]
Great thanks. I think there is too much in mind

**Comment by rdstern** [comment]
What has happened to this issue.  What is the current state?

**Comment by rdstern** [comment]
Following use of the plotting in the Benin workshop I confirm that having commonly used options also on the main themes sub-dialogue would be useful.
The list above is roughly what we needed here, namely:
1. Legend position (including no legend).  This still doesn't work so we had to edit the script file for this.
2. Angle for x-axis tick-mark labels.
3. Size of x-axis label (and y-axis label).  Above we suggest more, but I wonder if we should keep this aspect simple.
4. Size of x-axis tick-mark labels (and also y-axis tick-mark labels)

These would all be in a box called something like **Common theme options**.  It would be good to sort out the dialogue soon, even if it is disabled for now.  The two complications in the code are:
1. To get these options "in synch" with the same option in the detailed list.
2.  To get the legend options working properly.

**Comment by dannyparsons** [comment]
There shouldn't be any complication getting this to work as our dialog system is set up to all be in sync so I don't see why this can't start now.

**Comment by bethanclarke** [comment]
@maxwellfundi @rdstern is anyone assigned to this? I can make the necessary changes to the themes sub-dialog. This will be good for the documentation where we want to change labels but have that huge themes dialog!

**Comment by maxwellfundi** [comment]
@bethanclarke  I have design ready for this, just the back end code. Woud you like to take over? You could pull my branch called **sdgplotss**

**Comment by bethanclarke** [comment]
Yes, thanks @maxwellfundi that would be great. 

I see that you have created user controls for changing the text. Do we use the same ucr for titles, axis titles and axis labels?

**Comment by bethanclarke** [comment]
@rdstern I'm going to create another themes sub-dialog which is simpler and maybe then this themes sub-dialog could be the main dialog?

**Comment by maxwellfundi** [comment]
What do you mean the user controls for text? you mean the ones on the sdgThemes? If its those then we can be able to use them in our case. We have Axis custom control that is used in the sdgPlots.

**Comment by maxwellfundi** [comment]
This has already been done. Closing this now
