### ISSUE TITLE
Adding parallel coordinate plots

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4253]
This is a function from the **ggally** package.  It should be relatively easy to add and could be extremely useful.  It would go into the specific graphs under the current mosaic plots menu item.  I have put Maxwell down, because it is graphics, but on the assumption he may suggest who could do this.

I will explain more when I visit and show a variety of examples.  It is a different sort of graph and is designed to look at lots of variables (columns) at the same time.  

It returns a ggplot object so will fit nicely into our system.  I think it should be easy to do.  I consider the main dialogue first.

0. The title is Parallel Coordinate Plot.
1. Left hand side is as for all the other plotting dialogues.  Our usual selector and the Two buttons for the sub-dialogues (Parcoord Options, Plot Options) below that.
2. On the right-hand side is a multiple receiver with the label X Variables (note the s on Variables).  Let's start with it just for our set of numeric columns. 
3. You may be surprised there is no Y variable - but read on!
4. Below that is a single receiver with our usual label Factor (Optional).  (Just factor columns for this receiver.
5. On the lhs at the bottom (as for all the other graph dialogues) is our usual **Save Graph** and then the comment plus 5 button control.
6.  Below the 2 buttons is a Scale label.  This is a drop down with 6 possibilities - default is std.  The others are robust, uniminmax, globalminmax, center, centerObs.  Later the last 2 will have to open a further control.
7. Now I am not sure.  I would like to add the following, but I don't want the main dialogue to get cluttered.  If you do add all the items below, then some could perhaps go on the right hand side of the dialogue.  Or they could go on the sub-dialogue.  Let's see.
a. Checkbox with the label **Boxplots**.  Default is unchecked.
b) Checkbox with the label **Points**.  Default is unchecked.
c) A label **Transparency**. Then our **up-down** from 0 to 1 in steps of 0.01.  Default is 1.  Or a text field that checks 0 to 1 that is typed.
d) The coord-flip, as for boxplots, with same label **Horizontal Plot**.
e) Possibly the Legend option if that is going on all main dialogues.

Now the sub-dialogues.  The Plot options connects to our usual sub-dialogue. 
The Parcoord Options buttons opens a special sub-dialogue, because this is a function and not a geom.

This might have some of the items above, if the main dialogue is looking cluttered.
The 2 main items are Missing and Order

Checkbox for **Missing**.  If activated there is a label for a drop down with a set of options on how to cope with missing values.  Default is Exclude and is the first.  The others are mean, median, min10, random.
Checkbox for **Order** is the order of the columns in the display.  This is a pull-down with 5 options: Namely As Given, AnyClass, AllClass, Skewness and Outlier.

**Comment by maxwellfundi** [comment]
@Muthenya  Please create this new dialog and add the controls as described by @rdstern  then I can work on the code for this.

**Comment by rdstern** [comment]
[Ch06 Investigating Multivariate Continuous Data Graphical Data Analysis with R_files.zip](https://github.com/africanmathsinitiative/R-Instat/files/1544630/Ch06.Investigating.Multivariate.Continuous.Data.Graphical.Data.Analysis.with.R_files.zip)

Here are the examples from Unwin, using these plots.  Note that they also include a variety of other features that are in our general plotting sub-commands.

**Comment by maxwellfundi** [comment]
@rdstern  Where does this graph go into our menu?

**Comment by rdstern** [comment]
I had originally suggested below mosiac, but I think above that.  It is still possible that mosaic will go into the bar charts dialogue.

**Comment by maxwellfundi** [comment]
Okay thats sounds good. We did not discuss exhaustevely if the mosaic goes to the bar charts. I gues its not a very urgent task.

**Comment by maxwellfundi** [comment]
@rdstern  I have found that, this parameter could be a vector of column Indices or any of the list you provided above. I am not sure how we could that with the column indices(which appears to be the default. 
I will have the list in the drop down controls and it also appears there are more options. Given does not seem to work here too. We can only have skewness, allClass, anyClass and Outlying which uses `scagnostics` package. We seem to have other options which am not sure we need for now which use the same package. 

@dannyparsons  please remember to add the `scagnostics` package.

**Comment by rdstern** [comment]
Yes, for us it will be the list of columns.
Once the basic "system" is working, I hope it will be useful for us to also have it for a single column, by a factor.  Then we would do an unstack (quietly - just as we do stack in some other plotting functions, e.g. boxplot).  Then we might use the indices on the unstacked data frame.  But let's get it working first.

**Comment by maxwellfundi** [comment]
We also need the help id for this dialog too
