### ISSUE TITLE
Multiple Filters

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4259]
Could we have a feature to define multiple filters (at one go) when they are the levels of a factor.

The main Filter dialogue adds our new-style radio buttons, possibly labelled **Single** and **Factor**.

If factor then the second box changes and becomes **Define Filters**.  The sub-dialogue is limited to factor columns.  If there is only 1, then it is included automatically.  You can tick the levels you want.  This time each level is going to be a filter.  And the name of the filter will be the factor label.  You can only have one set of filters at any one time for a given factor.  You can add further conditions to this filter in the usual way.  They are then added to each of the filters to be defined. 

For example, with climatic data by Month, then you could add (Year > 1957).  this would still create the 12 filters Jan, Feb, etc with that double condition.

This would help in itself.  But in addition:

The second part of this is that the Month (or generally factor) control in various dialogues would change if a filter has been defined for that factor.  It now has a checkbox after the control with the label Filter.  If ticked, then the control becomes a drop-down and you can choose from those levels (i.e. filters!)

**Comment by shadrackkibet** [comment]
As far as I can see this has been implemented and merged here #5932.
