### ISSUE TITLE
Adding to the duplicates dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4270]
In my recent use of the dialogue I really could have used the missing option to give a count, 1, 2, 3, etc to successive duplicates.

I asked Sam and he supplied this function.

[dupcount2.zip](https://github.com/africanmathsinitiative/R-Instat/files/1510096/dupcount2.zip)

There is already a place in the dialogue, so I hope this will be really easy to add.  That's why I made it 4.10.  If it takes any time then change the milestone.

**Comment by Patowhiz** [comment]
@rdstern  expound on this please. There is already the Successive Values option in the duplicates dialog which gives you something similar.

**Comment by Patowhiz** [comment]
@rdstern do you mean something similar to this
Station      Duplicate
Saltpond   1
Saltpond   2
Saltpond   3
Pond         1
Pond         2
Saltpond   4
Pond         3
Saltpond   5

**Comment by rdstern** [comment]
What has happened to this issue?  I thought it would be done just by adding the function given above?
Just to be clear, whenever there are duplicate records this function gives the index number, as Patrick shows above.
