### ISSUE TITLE
Runtime Warnings

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#4275]
@africanmathsinitiative/developers  Everytime I run R-Instant in my visual studio I get all these warnings that I think are fixable. Are the unused variables left there intentionally? 

![warnings](https://user-images.githubusercontent.com/21179007/33403802-cea17ab6-d572-11e7-82d2-a7833b283fe6.JPG)

**Comment by dannyparsons** [comment]
No. Unused variables can be removed. It's good practice to solve all the warnings so we should try to clear all of these.

**Comment by Patowhiz** [comment]
Fixed some of those warnings above

**Comment by Patowhiz** [comment]
This has been solved.
