### ISSUE TITLE
New Restore Hierarchy dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4278]
The initial reason for this dialogue was data from 54 climatic stations for minimum temperatures.  There were 450,000 observations.  The first 5 columns were are the station level, i.e. with just 54 different values.  They were Station ID, Station name, lat, long, elevation.

We would like to produce a data frame with these data at this original level.  Of course we should have exported the data from CLIMSOFT that way (i.e. in 2 data frames).  But that isn't what happened and we have to live in the world as it is.

In Genstat this facility is offered as "Carry" in the data summary dialogue.  We think it is sufficiently important here to warrant its own dialogue.  We claim to deal well with data at multiple levels.

There are 2 obvious places for this dialogue.  It could go into **Prepare > Column: Reshape > Restore Hierarchy just under General Summary**.  Or we could change Check Data to **Check and Tidy Data** and put it there. 

here is the structure of the dialogue:
1. Title: Restore Level in Hierarchy
2. Usual selector.
3. Single receiver with label **Key Variable**.
4. Multiple receiver with label **Other Variables**.  It should have a tool-tip with text **Variables at the same level as the key column.**
5. Check-box with message **Warn if the other variables are not constant**.   Tool tip states columns at the same level as the key column should take a single value at each level of that column.
6. Check-box with the message Delete other variables from the original data frame.
Tool-tip with the message **Columns are only deleted if they are constant within levels of the key column**.
7. Data-frame name control
8. Usual keys at the bottom.

If all is well then this gives the new data frame (54 rows) with the same column names as the original.
If the warning is given - of anyway if the values are not the same, then this gives 2 columns with one called column_nameMin containing the minimum and the other containing the maximum values

**Comment by dannyparsons** [comment]
This sounds good.

1. The Key could be multiple columns, if this is equivalent to "summarise by" in Column Summaries? So this should be a multiple receiver?
2. Can we have something else instead of **Other Variables**, like **Carry Columns**?

Maybe not needed right away but we could have more options for what to do when the Carry Columns are not constant, like give any of: min, max, first, last, median etc.

**Comment by maxwellfundi** [comment]
Danny, you could look at the pull request on this where i have put the
design. Further, i was wondering what method/funtion to use on this dialog.

**Comment by maxwellfundi** [comment]
This is now being closed because after discussion with @volloholic  it appears that we will have incorporate it to the current unstack dialog.
