### ISSUE TITLE
Frequency tables problem 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4288]
I do have a complicated data set!
It is the data set from Rwanda - which I can share if needed.
I have merged station names from the station set.  Now I find that there are 12 ID numbers that do not have a name.
I have filtered the data to find those ID numbers.  I therefore used ID (factor) and asked for a one-way frequency table.  I think the filtering has something to do with the problem.

I got this:

Error running R command(s)

**Error in dim(ordered) <- ns : 
  dims [product 1] do not match the length of object [0]**

The error occurred in attempting to run the following R command(s):

.temp_val <- last_table <- InstatDataObject$summary_table(data_name="withname", summaries=count_label, factors="ID.", n_column_factors=0, store_results=FALSE, rnames=FALSE)
InstatDataObject$add_table(data_name="withname", table=last_table, table_name="last_table")
InstatDataObject$get_tables(table_name="last_table", data_name="withname")

OK   
This was the R command in the output window - of course very similar to the above:
# code generated by the dialog Frequency
last_table <- InstatDataObject$summary_table(data_name="withname", summaries=count_label, factors="ID.", store_results=FALSE, rnames=FALSE)
InstatDataObject$add_table(data_name="withname", table=last_table, table_name="last_table")
InstatDataObject$get_tables(table_name="last_table", data_name="withname")

I then tried the column summaries as reported below.  This didn't give an error message.  But it also didn't give the result.  There were no lines of summary - though there were clearly some data - I could see them.

So I went back to the data and applied the filter again - which was when the name field was NA.  This time I opted to get the subset.  I notice that in the subset the filter is still set in the sense the numbers are red.  They I have all the data.  I took the filter off and tried the summary again and got what I wanted.
I also then tried the frequency table again and it was fine, giving the result:

        ID.     .
1  20102000   638
2  20513000   304
3  20603000   638
4  20607000  1338
5  30103600 12662
6  30105000  1004
7  30204000   852
8  30608000   607
9  40314000   516
10 40401000  1005
11 50410000   640
12 50511000   945

This was now the command:
# code generated by the dialog Frequency
last_table <- InstatDataObject$summary_table(data_name="withnoname", summaries=count_label, factors="ID.", n_column_factors=0, store_results=FALSE, rnames=FALSE)
InstatDataObject$add_table(data_name="withnoname", table=last_table, table_name="last_table")
InstatDataObject$get_tables(table_name="last_table", data_name="withnoname")

**Comment by dannyparsons** [comment]
Might be easiest to look at this problem in a live demo

**Comment by rdstern** [comment]
I wonder if we will be changing our "system" for frequency tables?  Se #4640.  In which case I suggest we close this one!
