### ISSUE TITLE
Missing word

### ISSUE THREAD

**Issue by ZIRANA11** [africanmathsinitiative/R-Instat#4297]
On the Histogram dialog, On plot options, when **Vertical** is selected the word **Columns** is missing on the statement **Fixed number of**
![column](https://user-images.githubusercontent.com/28622260/33611222-a0f19694-d9de-11e7-89ba-8eebf9e909cb.PNG)

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers a trivial change for someone to make please

**Comment by shadrackkibet** [comment]
will make this  change.

**Comment by shadrackkibet** [comment]
@maxwellfundi  i see you have a pullrequest working on this file. Could you make this change?

**Comment by maxwellfundi** [comment]
yeah i have been working on this. I think i will have to change it before
it causes conflicts

Regards
Maxwell Fundi
|| Phone :+254728508241||
