### ISSUE TITLE
Prepare > Column: Reshape > Column Summaries

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4302]
We wanted to use the column summaries to get summary statistics (median) of 2 columns into a dataframe.  It would only have one row.

But OK is not enabled unless there are some factor columns.  I suppose we could have had a factor with a single level - but it could be enabled anyway!

**Comment by dannyparsons** [comment]
That's simple to change, assuming the code will still work ok, which it should.
