### ISSUE TITLE
The summaries dialogue, with first and last, etc

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4309]
dplyr has the functions **first, last and nth and n_distinct**.
Could they please be added to the summary keyboard in the calculator (n_distinct is already there)  and also to the set of **summary statistics** for Prepare > Column: Reshape > Column Summaries.
(As an aside I notice that mode is in the summary statistics, but not in the calculator!.  So perhaps we should add that to the calculator?  I wonder what it does with missing values and also when there are multiple modes?)  My reason for questioning that comes below!  

They (first, last, nth) are quite useful in their simple form, for example for the survey data: 
dplyr::first(Size) gives 2, the size of the first field in the dataset.  Also
dplyr::first(Size,order_by=Yield) gives the size of the field (4) for the observation with minimum yield!

In the summary statistics for the column reshape it becomes much more powerful, of course!

However, it is not so obvious how we should allow the second column in these calculations.  Very nice if we could.

My limited solution could parallel cor and cov, i.e.  when there are exactly 2 columns then this is an extra option.  But it might be time for a "proper" solution.  This could have the 2-variable summaries on a separate tab - called 2-variables.  Then there is also a single receiver for the "second" column.
Then cor and cov would be calculated for each of the variables in the main dialogue, with the single second variable.
For first, last and nth the second column would provide the **order_by** column.  So they would appear twice.  First:

a) n_distinct can go at the top of the main summary page - as N Distinct and together with the other N statistics.  Mode seems a bit of an oddity, but does no harm!
b) I hope there is space for the other 3 - in their simple form - on the main page also, because I think they should also work on all sorts of column.  So they can go with max and min.
c) Then  - if you agree - we move the cor and cov to a new tab and put the 5 summaries there.  I am sure we will add more later!  We will need the data selector there, restricted to the same data frame.  And then a single receiver, perhaps with the labels 2nd variable.

**Comment by Patowhiz** [comment]
@shadrackkibet how is this coming up.

**Comment by shadrackkibet** [comment]
The calculator part is done here #4277

**Comment by rdstern** [comment]
I am pleased to see the "original levels" has now been added to the summaries.  I presume it could also be added to the climatic summaries dialogue?
But I also wanted to query how the other improvements to the column summaries are coming on - including first, last and nth - and correlations, etc.
And to tempt discussion on another suggestion now David and Danny are there.  This is a sort of carry column facility.  When doing the first, last, max, min, etc, i.e. those that sort of give a filter of one row in the data that corresponds to the summary.  Then could there be a carry facility.  So when we get the first value in a group, we could also "carry" the date of the first, say.

**Comment by shadrackkibet** [comment]
ok, i will add that on climatic summary.

**Comment by rdstern** [comment]
The summaries dialogue (and hence climatic summaries has changed a lot.  It is looking very impressive now.  I have changed the name of this issue to list what I think remains.  It is getting very exciting!

1. We now have **First and Last and nth**.  What remains is the add the OrderBy facility to these summaries.  I suggest we keep First/Last/nth where they are now.  In addition we repeat them in the 2-variable tab - with the OrderBy label for that block of summaries.  So it is effectively another statistic - I hope that is OK?
2. Similarly (usually for max and min) Danny has added the facility (in the Climatic extremes dialogue) to provide the observation number (i.e. day of the year) when the max and min occurred.  So in the 2-variable summary we add 2 more blocks, one for Maximum and the other for Minimum.  Inside are First, Last, Count.
3. In any of the items in this tab I assume the summary will be ignored unless the second variable is included 
4. We add the facility in the Missing tab to make the result missing when a given number, or proportion of the observations are missing.  The items in the dialogue are there, but Danny says an addition is needed in the calculation system.

**Comment by dannyparsons** [comment]
Can these be separate issues, one for each point? For the workflow I think it's better if this can be closed and new ones opened.

**Comment by shadrackkibet** [comment]
I think this issue can now be closed. @rdstern  the remaining aspects now are;

1)  Adding `order_by`  to first, last and nth which has an open issue  #4497
2) Min and Max Blocks for first, last and count which has an open issue  #4498.

Anything else remaining here?
