### ISSUE TITLE
Adding annotate to our plotting system?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4312]
I wonder if it would be useful for a tab in the ggplot sub-dialogue to include the **annotate** function  in our plots.  It is described in the ggplot2 manual as follows:

"This function adds geoms to a plot, but unlike typical a geom function, the properties of the geoms
are not mapped from variables of a data frame, **but are instead passed in as vectors**. This is useful
for adding small annotations (such as text labels) or if you have your data in vectors, and for some
reason don’t want to put them in a data frame."

It is similar to geom_label or geom_text (which we have) and the first argument provides the geom.

One place it is used is [http://www.sthda.com/english/wiki/ggplot2-texts-add-text-annotations-to-a-graph-in-r-software](http://www.sthda.com/english/wiki/ggplot2-texts-add-text-annotations-to-a-graph-in-r-software)
 Another variation - simple if it has its own tab, or there is a **More** tab is **annotation_custom**.

**Comment by rdstern** [comment]
I wonder if this could now be added as another tab to our plotting sub-dialogue.  Could @jkmusyoka and/or @lilyclements do an investigation.  Then - perhaps like the scales - it could be a good task to be handed over to Ivan to implement?

**Comment by lilyclements** [comment]
I've had a look into this.

There seem to be three things to consider

1. The `geom`. The four examples of these I've seen in the literature are `"text"`, `"rect"` (a rectangle), "`segment`" (a line), `"pointrange"` (a line with a point)
2. The position (x/y values)
3. Other aesthetic details that apply to this geom and not other geoms

| geom | Position | Other details |
| ------------- | ------------- |------------- |
| `"text"` | `x`, `y` | `label = "..."`, `parse` |
| `"rect"` | `xmin`, `xmax`, `ymin`, `ymax` | `fill` |
| `"segment"` | `x`, `xend`, `y`, `yend` | |
| `"pointrange"` | `x`, `y`, `xmin`, `xmax`, `ymin`, `ymax` |  |

So the position is where differences mainly occur between the four geoms:
* For "text", an `x` or `y` value is read in. This is the position for the text to be placed. It can be a single value, or multiple values. Note that if `x` is multiple values, `y` has to be the same length or a length of `1` (and vice versa).
Both parameters have to be given.
* For "rect", the four parameters specified give the minimum and maximum co-ordinates. Only one value should be specified. All four parameters should be specified.
* For "segment", 
If `x` is specified, `xend` must be given. Similarly for for `y`.

**Comment by rdstern** [comment]
So it looks as though the Annotate tab would not be a separate tab.  Instead it would add a label: Annotate and 3 more buttons in the existing Layers tab.  They would again be Add, Edit and Delete. for Annotation.  It would be called geom_annoate in the list of layers.
Then they go to a new copy of the layer-sub dialogue called `Annotation Layer Options` that is almost the same as for general geoms.  It has a limited number of geoms, including `label, pointrange, rect, segment, text`. 
Then the rest is the same as for the other geoms except that the choice of data frame columns is optional.  You can enter a single value into the aesthetics - perhaps more than 1 if we want to live dangerously!  Otherwise you choose a data frame and include those variables.
  
Is that what's needed?

**Comment by lilyclements** [comment]
This sounds like a good idea - the function itself is just `annotate` not `geom_annotate`, but seeing as this is a geom and adding a layer (and has similar options to other geoms - such as `alpha`, `colour`, etc) then this sounds like a good solution. 

While a data frame would make sense for the `text` option, I'm not sure if it would make sense for all of the options such as `rect` - I can investigate this properly tomorrow?
Additionally, from a quick look, there are other geoms we can consider for annotate which are just variations of the geoms already outlined above. For example
* `geom = "curve"` can have the same parameters as `geom = "segment"`
* `geom = "linerange"`, `="crossbar"`, `="errorbar"` can have the same parameters as `geom = "pointrange"`

I can look into any others that I may have missed tomorrow and draw up a list of geoms alongside their parameter options.

@Ivanluv are you okay to take up adding this new "annotate" option in the "layer options" tab?

**Comment by Ivanluv** [comment]
@lilyclements I would be happy to take this up

**Comment by lilyclements** [comment]
Options for the `annotate` function:

### **geom = "text" or geom = "label"**

| Parameter | Values | Description | R Default |
| ------------- | ------------- |------------- |------------- |
| `x` | Single or multiple values. If `xend`, `y`, or `yend` are multiple values, `x` must be the same length, or of length 1.  | lower x-coordinate to place the text. | `NULL` |
| `xend` | See above | upper x-coordinate to place the text. | `NULL` |
| `y` | See above | lower y-coordinate to place the text. | `NULL` |
| `yend` | See above | upper y-coordinate to place the text. | `NULL` |
| `fill` | colour (as string) | For Label only. Fill colour of label | |

_Note `x`, `y`, `xend`, `yend` arguments must be supplied_


### **geom = "rect"**

| Parameter | Values | Description | R Default |
| ------------- | ------------- |------------- |------------- |
| `xmin` | Single or multiple values. If `xmax`, `ymin`, or `ymax` are multiple values, `xmin` must be the same length, or length 1. | minimum x-coordinate for the rectangle. | `NULL` |
| `xmax` | See above  | maximum x-coordinate for the rectangle. | `NULL` |
| `ymin` | See above  | minimum y-coordinate for the rectangle. | `NULL` |
| `ymax` | See above  | maximum y-coordinate for the rectangle. | `NULL` |
| `fill` | colour (as string) | fill colour of rectangle| |

_Note `xmin`, `xmax`, `ymin`, and `ymax` arguments must be supplied_
_note there is also "raster" and "tile" which perform very similarly but have different parameters. I can outline these as well if you want?_

### **geom = "segment"**
| Parameter | Values | Description | R Default |
| ------------- | ------------- |------------- |------------- |
| `xmin` | Single or multiple values. If `xmax`, `ymin`, or `ymax` are multiple values, `xmin` must be the same length, or length 1 | minimum x-coordinate for the rectangle. | `NULL` |
| `xmax` | See above  | maximum x-coordinate for the rectangle. | `NULL` |
| `ymin` | See above  | minimum y-coordinate for the rectangle. | `NULL` |
| `ymax` | See above  | maximum y-coordinate for the rectangle. | `NULL` |
| `lineend` | "butt", "square", "round" | Shape of the end of the line | `"butt"` |
| `linetype` | Numerical value from 1 | Type of line (dashed, etc) | `1` |

### **geom = "curve"**
Same options as `geom = "segment"` and additionally
| Parameter | Values | Description | R Default |
| ------------- | ------------- |------------- |------------- |
| `curvature` |  -Inf to Inf | Amount of curvature (curve changes side is <0) | `0.5` |
| `angle` | Single value between 0 and 180 | Skew the curve to the left point (<90) or right point (>90) | `90` |

### **geom = "linerange" or geom = "errorbar"**
| Parameter | Values | Description | R Default |
| ------------- | ------------- |------------- |------------- |
| `x` | Single or multiple values. If `y`, is multiple values, `x` must be the same length or length 1 | x-coordinate of where the line is placed | `NULL` |
| `y` | See above  | y-coordinate of where the line is placed (if it is horizontal) | `NULL` |
| `xmin` | Can be a single value, or multiple values. If `xmax`, is multiple values, `xmin` must be of length 1, or the same length as `xmin`.  | minimum x-coordinate of the line. | `NULL` |
| `xmax` | See above  | maximum x-coordinate of the line. | `NULL` |
| `ymin` | Can be a single value, or multiple values. If `ymax`, is multiple values, `ymin` must be of length 1, or the same length as `ymax`.  | minimum y-coordinate of the line. | `NULL` |
| `ymax` | See above  | maximum y-coordinate of the line. | `NULL` |
| `linetype` | Numerical value from 1 | Type of line (dashed, etc) | `1` |

_If `xmin` and `xmax` are given, the line is vertical (and hence `y` must be given)|_
_If `ymin`, `ymax` are given then the line is horizontal (and `x` should be given)_

### **geom = "crossbar" or geom = "pointrange"**
Same parameters as above, however, `x` and `y` must be given as these signify where the point is.
Either `xmin` and `xmax` **or** `ymin` and `ymax` should be given.

Additionally,
| Parameter | Values | Description | R Default |
| ------------- | ------------- |------------- |------------- |
| `fatten` | 0-Inf | Width of point/bar in the centre | `2.5` for crossbar; `4` for pointrange |
| `fill` | colour (as string) | fill colour of object| |
| `shape` | 1-255 | For "pointrange" only - shape of point | 1 |

### **Parameters that apply to all options**
| Parameter | Values | Description | R Default |
| ------------- | ------------- |------------- |------------- |
| `alpha` | 0-1 | Transparency of annotate object | 1|
| `colour` | colour-values as string | Outline/line colour of annotate object |  |
| `size` | 0-Inf | Size of annotate object | |

**Comment by shadrackkibet** [comment]
Okay. @lilyclements are these the R defaults or just the defaults you would like in the dialog?

**Comment by lilyclements** [comment]
@shadrackkibet  They are the R defaults
