### ISSUE TITLE
Adding geom_lm and geom_spline and more geoms?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4330]
The package **ggformula** contains a geom (**geom_lm**) that (I think) answers a problem I have had, namely to be able to fit parallel lines to a linear model plot.  It also has **geom_spline** that would be useful.

It also references many other "standard" geoms from ggplot2 that we don't yet include.  Some sound useful and I wonder why not?  This is not urgent, but is there any reason (in particular for the general plotting) that we omit geoms that are in the ggplot2 package?  

I realise there are many other tasks in R-Instat, but is other work the only reason?

Incidentally the mosaic project used to use the lattice package for the graphics, but it seems to have migrated recently to ggplot - now allowing both.  They seem to have written the ggformula package partly to have a similar command structure for ggplot as for the lattic graphics system  They also have this simple vignette that compares the graphs for the 2 systems 
[https://cran.r-project.org/web/packages/mosaic/vignettes/ggformula-lattice.pdf](url)

**Comment by dannyparsons** [comment]
Yes time was the only factor because it takes quite a while to figure out the complete set of options for a geom, the documentation doesn't describe the complete specifications so it takes a lot of testing.
But I feel now it would be worth adding more geoms and getting them tested would be the best way to check if they are correctly defined.

**Comment by rdstern** [comment]
Great.  There is a good document on graphs, [here](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html).  This is the third in an interesting series. 

It may be useful for our documentation team to examine this list (and perhaps the other 2 tutorials) and see what we can already do - and what remains.  It makes use of (at least) the following geoms that we don't yet include:
**geom_count
geom_encircle
geom_text**
**geom_segment** (my first priority would be this)
**geom_curve
geom_area**
**geom_tufteboxplot** (may be useful for our climatic boxplots, when we have data for many years - and also multiple stations)
**geom_tile**

Then the **ggextra** package includes **ggmarginal** and there is a **gganimate** package that looks fun.

**Comment by dannyparsons** [comment]
If geom are being added it would be great to get the stat_summary "geom" added from here https://github.com/africanmathsinitiative/R-Instat/issues/4420.

**Comment by Ogik99** [comment]
Seems like majority of these geoms have been implemented except for geom_spline and geom_tufteboxplot(can I add these).

**Comment by rdstern** [comment]
I would like that.  As mentioned above, I could use the Tufte boxplots for climatic work.

**Comment by rdstern** [comment]
That sounds an Excellent solution.  Great!

**Comment by Wycklife** [comment]
This seems okay from my end

**Comment by maxwellfundi** [comment]
@Wycklife  this comment should have been on the PR
