### ISSUE TITLE
Importing Files - bug?

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#4339]
Two small bugs. Firstly, If I pick a csv file such as Survey, I get this

![image](https://user-images.githubusercontent.com/21180424/34207356-0848302e-e582-11e7-95ea-d5745fcf34b4.png)

All great, except for something is called "Label1"

Then I reopened the dialog and it's like this -

![image](https://user-images.githubusercontent.com/21180424/34206616-3047022e-e57f-11e7-992f-823be1913c03.png)

1. How come reopening the dialog looks different?
2. There's a label called "Label1" that shouldn't be. I also noticed another "Label1" on the Open from Library dialog which shouldn't be called label1.

**Comment by Patowhiz** [comment]
The Label1 issues is caused by `autotranslate(me)` code which is a subroutine of class `Translations`. It kinder overwrites the set text of the ucrSave control .  @maxwellfundi I'm happy to discuss with you about this.

**Comment by dannyparsons** [comment]
One thing to check if looking carefully at the code to see if there are any differences in the controls which don't translate properly. e.g.
- Is the designer or resource file code for these controls any different to others that work well? Is there anything extra/missing that isn't there for controls that work
- Is the SetText done any differently in the dialog code for the controls that don't work?

Might not find the solution here but a good starting place.
