### ISSUE TITLE
Saving and opening a script file?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4348]
I have two problems, both saving and loading:

1. Saving a script file: I had some data in a script file, as follows:

**code generated by the dialog Calculations
age <- wakefield::area(20,x=c("a","b","c","d"))
InstatDataObject$add_columns_to_data(col_data=age, col_name="roger", data_name="data1")
rm(age)**

I used **File > Save As** to save these contents.  It seemed to save as a text file.  But the file was then empty.  I tried, both with the text selected and without.

2. So I copied the file to the clipboard and saved it as a txt file myself instead.  Then I went to the script file, cleared it and then used the right-click option **Open Script**.  This was a surprise as it took me to RStudio.  Perhaps that is also useful, but how do I open a script file I have saved?

3. I do rather like the **right-click** option to open a script file, so I wonder if we have both - assuming opening from RStudio is what is also wanted.  And perhaps we could also have **Save As** on the right-click menu as well?  Can **Save As** also be to either save the whole script window or the selected text?

**Comment by maxwellfundi** [comment]
@rdstern  my immediate reaction to this would to be to add two more options to suit this need namely

1. Having a right click to save the script file as a text file
2. Open saved script

Further, we would need to edit the open  script that we currently have to Open Script in R-Studio or something like that.

**Comment by maxwellfundi** [comment]
This would then mean we do a similar thing to the log window too

**Comment by rdstern** [comment]
I agree with your 2 further right-click options.  A bit more on them below.  At the same time this (I assume) will solve the issue that the File > Save As doesn't yet work for the script file.

In your 2 options you state we first add:

**1) Right-click to save the script file as a text file.**
Two questions here.  What will this saving do if I have selected part of the script file?  Does it a) Ignore that and save the whole file, or b) Save the selection, or c) Give me an option?
That's because we could always have another option to Save Selection, which is only enabled if part of the script file is selected.
Second is the clearing of the script file when it is saved.  We (currently) only have a single script file at a time and using Script from a dialogue adds to the current script file.  This sometimes messes me up, because I usually want to run a slightly changed dialogue script, not a sequence of commands.
We can Clear the script file of course - that is already there.  But I wonder about an option (or default?) to clear the script file when it is saved.  This might be yet another option, i.e. Save and Clear.

Your second new option is to:
**2) Open Saved Script**

I agree that we need this and that the right-click is a good place.  There is less point (for R-Instat use) in saving if you can't then open it again!  We can already paste, having opened elsewhere, but that is contorted.  The remaining question is whether this is the only place where the saved script file is opened.  I would say - yes it is the only place for now.  There are other more general issues concerning the script file, that can be discussed later.

**Comment by maxwellfundi** [comment]
Very good concerns here. the File>Save as does not work for Log too and similarly saves an empty textfile. 

For your first concern, a sensible thing in my mind would be having the option then to save entire script or selected text on the script window. We could have Save and clear as you suggest but am not convinced we need to necessarily want to clear every time we save the script. 

On your second point, I think we could make it possible to open the script/log from the file menu.

**Comment by rdstern** [comment]
Agreed to add this to the File menu too.  We open lots of files of different types, so good to be able to do this.  I wonder what options it will have?

David's view is that we would automatically Open a txt file into the script window and it would replace the current script file there.  And if we wanted to open the log file (or any other txt file) then that's where it would go.

We certainly don't want to open the log file into the current log, so there is (currently) nowhere else for a txt file to go to.

**Comment by dannyparsons** [comment]
I'm not convinced about saving a section of a script window. That seems a bit strange to me, if I select parts of different lines how does that look in the saved file etc. I would think if you want to use parts of the text then it's easier to copy and paste into RStudio or a text editor, or remove the parts you don't want directly. But if people think it will be useful I don't have strong views.

We had only been thinking about saving the script as a one way thing, where you save it and open it in another program. I hadn't considered loading a text file into the script window. It's easily possible, although that gets us further into an overlap with RStudio's functionality.

**Comment by maxwellfundi** [comment]
I see the sense @dannyparsons  in not saving bits of the script but its still possible that people would want to do it. But initially we could have the save and open script menus then decide on the rest later

**Comment by dannyparsons** [comment]
I think my point is if you want parts of the script that's easier to do through copy and paste. But let's just do something on this and then review.
