### ISSUE TITLE
Improvements to climdex dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4350]
I have modified the R method for importing the climdex indices to get the linking working better (#4349) which mean the dialog needs updating to these changes.

We decided that year (for annual summaries) and year & month (for monthly summaries) should be required columns on the dialog. This isn't required to calculate the climdex indices because it uses the date column, but we need those columns to do the linking correctly. They do not have to be a specific data type.

So the dialog needs a year and month receiver added. The choice of annual or monthly summaries is currently on the sub dialog. I think this has to come to the main dialog now since the visibility of the month receiver depends on it. I'm not sure whether it should still be a combo box, and where it should go on the main dialog, or whether it should change to radio buttons at the top of the dialog. Maybe @shadrackkibet @rdstern @volloholic can discuss.

The sub dialog also needs a rethink probably. The R method we've written only allows either annual or monthly summaries to be calculated in one go. If we're happy with that restriction, then the choice of indices visible should change depending on this choice which I don't think it does currently. I know @lilyclements had a go at tidying up the sub dialog before so she might have thoughts on this too?

**Comment by rdstern** [comment]
On the main dialogue I suggest either: 

1) We have Year and Month as compulsory fields below the date.  I would be happy if they are both compulsory.  It is so little trouble to get the Month column from the date and pretty rare that you would not want to consider some of those indices.  I assume it will make the code simpler.
2) Or we could have our new-style radio buttons.  This is similar to the Climatic > Prepare > Climatic Summaries dialogue, where the first 2 buttons would (in this case be **Annual** and **Monthly**.  When you click on Monthly, then the extra field opens up - just as in the climatic summaries.
3) I understand you can only do either Annual or Monthly, on a single run of the dialogue.  So perhaps 2 is better than 1 above.  There are then 3 types of index, namely 
a) Those that are only Annual
b) Those that are only Monthly
c) Those that can be either.
They would be enabled accordingly.  

4) I am not sure about the Station field.  Does the command only work for one station?  If so, then can we (anyway) include a Station field on the main dialogue, but disable it for now.  That will remind us that we need to filter before using the command for now.  Later we might be able to add a loop when we call the command?

**Comment by dannyparsons** [comment]
I think 2 is a good option as well. 
If it was needed we could get it to work with doing a mix of annual and monthly summaries in one go. It would mean more manipulation of the code to sort out the different summaries etc. Given that it's working well now I don't think we should do this now, but it's technically possible if we want it as a longer term aim.
Only allowing one type is simpler since your 3c) summaries could be either or both.

I believe it only works with one station, although it's worth checking in the documentation of the R package. That would be annoying because we then couldn't use the package functions directly more multiple stations.

**Comment by dannyparsons** [comment]
@rdstern, @shadrackkibet has worked on improving this, it might not be the design we want in the long term but it would be good to now test again to check that it is at least reasonably functional.

**Comment by rdstern** [comment]
Great.  Will do.
