### ISSUE TITLE
Attaching package: ‘dplyr’ Warning

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#4366]
When I run the code below in Rstudio , a warning shown in the image is displayed.
# Setting working directory, sourcing R code and loading R packages
setwd(dir="C:/Users/PatoWhiz/Source/Repos/R-Instat/instat/bin/Debug/static/InstatObject/R")
source(file="Rsetup.R")

Was it made intentional to load package dplyr  before plyr ? R seems to be fiving a warning here

![plyr](https://user-images.githubusercontent.com/21179007/35114382-8ee0cfc2-fc95-11e7-897a-778b02c1f8e0.JPG)

**Comment by dannyparsons** [comment]
This is good to check. We do want to load plyr first. If you look in Rsetup.R, plyr is loaded first, however there could be something else causing dplyr to load first.
But I would guess it might also be that you loaded dplyr in R doing something else before running this code. So check if you still get this in a fresh session of R.

**Comment by Patowhiz** [comment]
Let me check

**Comment by Patowhiz** [comment]
@dannyparsons  it appears I had been loading dplyr in R before opening the log file in Rstudio. I'm closing this issue.
