### ISSUE TITLE
Prepare > Data Frame > Column Structure

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#4367]
The check box  colour columns by structure does not maintain its previous state of being checked.
![column structure](https://user-images.githubusercontent.com/21179007/35114585-52694154-fc96-11e7-9408-13dfc594efb6.JPG)

**Comment by dannyparsons** [comment]
Good thing to notice. I have labelled it as ANYTIME since it would be good to fix but not particularly urgent.

**Comment by Patowhiz** [comment]
I've noticed that the reset button does not reset any of the ucrReceiverMultiple receivers too in this dialog.

**Comment by dannyparsons** [comment]
That's different because the receivers should show which columns are currently defined as those type. So "reset" ins't the same as "clear" in this case.

**Comment by Patowhiz** [comment]
Okay. The Colour check box should be an easy fix.
