### ISSUE TITLE
Graph in R viewer does not reset

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4390]
This may be a repeat of an issue raised earlier.

The default is for the graphs to appear in the output window.  To get a clear graph I sometimes then use Describe > View Graph and choose to have the graph in the R viewer.

This now changes the display forever.  I just wanted that graph in the R viewer.  But I find that it has changed the setting in the Tools > Options dialogue.  I hope this can be fixed easily.

**Comment by dannyparsons** [comment]
Yes I think this is just an issue of not resetting the graph option, maybe when closing the dialog without running. It should be simple to find and fix the issue.
