### ISSUE TITLE
Calculator problem with a particular variable name

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4400]
I have had a problem with the use of the calculator and a particular variable name I have been using.

I had a variable called Tmin.  I changed some values in that Variable and put the result in a new variable called Tmin1.

I then calculated another variable when Tmin1<0 and it worked fine.  But Tmin1<-5 gave the wrong answer.  It gave FALSE every time, even when Tmin1 was NA.  I tried brackets etc, but nothing seemed to help.

When I renamed Tmin1 to Tmina, then Tmina<-5 works fine.  

I wonder what I, or R-Instat, or R are doing wrong?

**Comment by dannyparsons** [comment]
It should work with `Tmin1<(-5)` or `Tmin1< -5`. WIthout the brackets you have `<-` which is assignment so that messes up the inequality you want. I think that's why it's always suggested to put spaces between symbols.

**Comment by shadrackkibet** [comment]
I think to fix this problem we need to add a space on both sides automatically on this symbols  (<,>, <=, >=,==).

**Comment by rdstern** [comment]
I agree

**Comment by shadrackkibet** [comment]
This can now be closed.
