### ISSUE TITLE
Adding a new option on the Make Date dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4402]
This should be a simple additional format to add.  It has come from the chillR package which has a special format for this function.
For us it can be simply an additional format (I hope) in the existing dialogue.

It is for a single column and is simply "Year(4 digit)MonthDay (YEARMODA)".  We have many variations of this format.  It does not have a separator so is something like 20170514.  It is a common format - and so has a name which we could also supply, see above.

**Comment by dannyparsons** [comment]
Do you mean a format to convert from? So we should add `%Y%m%d` to the list of formats for a single column? Where does the chillR package come into this?

**Comment by rdstern** [comment]
That's correct.  chillR only comes in because that this packages introduced me to this format - which is called YEARMODA, (and seems quite common) so we might mention that name when we give the format.  I assume we don't need its function specially for that format.  It has a YEARMODA2Date function.

We may well make use of the chillR package for other functions, with patch_daily_temperatures looking interesting for our Riga and other work.

It says: 
"This function uses auxiliary data sources to fill gaps in daily weather data. It can accommodate
multiple sources of auxiliary information, which are used in the user-specified sequence. There
have to be some overlapping records for this to work, because without bias correction, this procedure
could produce erroneous records. Bias correction is done by computing the mean difference
between main and auxiliary data for each variable and adjusting for it in filling the gaps. You can
specify a maximum mean bias and a maximum standard deviation of the bias to exclude unsuitable
records that aren’t similar enough to the original data."

That looks like quite a good gift - if it works well?
