### ISSUE TITLE
Custom control for day of year

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4406]
Many of the climatic dialogues have a first and last day of the year - set now to 1 and 366.  It would be much better to have a control where you could give the Month and then the day of the month.  They could each be drop-down lists.  This would be easy to use, because often what is needed is the 1st of the month and hence one would only have to change the month drop-down.
1. This would still pass the day number in the year to the R code (which would therefore not need to change.
2. It would recognise the shifted year when making the calculations.
3. It could even have a right-click (perhaps) on how to present the months!  That would be a luxury!
4. I would be quite happy for the day of the month to always go to 31, because it isn't clear which order you should give the day of the month and the month.  It is only when passed to the R-code that the day number needs to be sensible.
5. Whether the first and last day are a single control, or are 2 controls I leave to the programmers!

**Comment by rdstern** [comment]
After discussion with Danny I suggest a new custom control here.  The current From <daynumber_in_year> To (Day_number_in_year) e.g. From 1 To 366 could be replaced by a **From/To button**.  This opens a sub-dialogue.

This has a selector on the left with just the linked data-frames.  Usually there will be only 1.  If there are none, then the control could still be there with no data frames available.

There are then 2 frames, one labelled **From** and the second (beneath it), labelled **To**.  
1) The From has 2 radio buttons, with the labels **Fixed** and **Variable**.  
a) For **Fixed** it then has 2 fields, labelled **Day** and **Month** (I believe Danny has done some of the R work for this?).
b) For Variable it takes a column from the linked data frame.
2) the To has 3 radio buttons labelled Fixed, Length (days), and Variable.
a) For Fixed it is as above.
b) For Length it is an up/down from 1 to 366.
c) For variable it takes a column from the linked data frame.

Ideally, somewhere in the dialogue there is a check that the length of the columns (if Variable) is sensible for the number of years of data?

This will then replace the From and To fields on most of the Climatic > Prepare dialogues.  Perhaps start with the Summary one?

**Comment by shadrackkibet** [comment]
@dannyparsons  i think most of this is now done, can this be closed?

**Comment by dannyparsons** [comment]
Yes this is done! And any new dialogs can have this from the beginning now.
