### ISSUE TITLE
Spell lengths with variable start

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4408]
Danny has added the possibility of being able to read from a linked data frame in a dialogue.
 The Spells dialogue is a good example to start with.

Here are 2 examples:
a) I would like the longest spell length in the x (say 21) days after the start.
b) Flowering takes about 20 days and starts, say, 40 days after planting.  So what is the longest spell length between day 41 and 60 after planting.

a) We replace the from date (which is now fixed) to a column in the linked data frame.  Perhaps there could even be a default?
b) We have another option where you can either fix the number of days For xxx days.  That's an up-down with default 21.  Or it could alternatively be variable (as the start)  That would facilitate getting the longest spell between the start and the end of the rains.

The layout of the controls will need some discussion.

Once done then the climatic summary will be the next one to include this feature.

**Comment by shadrackkibet** [comment]
@dannyparsons i think this is now done. Can this be closed?
