### ISSUE TITLE
Giving commands to R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4446]
Here is a common situation in example files in R.  This doesn't (yet?) run in the script window, but might be solved through the enhanced File > New option suggested in #4439. 

(It is part of the first example in the rms package)

**n <- 1000 # define sample size
set.seed(17) # so can reproduce the results
treat <- factor(sample(c('a','b','c'), n,TRUE))
num.diseases <- sample(0:4, n,TRUE)
anova.rms 7
age <- rnorm(n, 50, 10)
cholesterol <- rnorm(n, 200, 25)
weight <- rnorm(n, 150, 20)
sex <- factor(sample(c('female','male'), n,TRUE))**

There are 2 main problems - then the bigger issue.
1) n is set to 1000 on the first line.  But not to R-Instat in a way that can then be used.  So all lines from the 3rd give an error.  
2) Each line then gives it own error.  From the first error - on line 3 - it was clear that all the remaining lines would have the same error.  But there is no way to stop.

Now:
3) This file does run if we change n to 1000 from line 3 onwards.  (Wouldn't a find-replace be nice!  That just may be easy to add?)
4) The resulting data are now in R.  And they are OK for a data frame.  Now my next big question - how can I put them into R-Instat, rather than just in R and separate?  One answer (maybe) from #4439 is to allow this set of commands also in the File > New dialogue.  
(Note that this is the same issue in Genstat.  There you can get a set of columns in the Genstat server and they have a special dialogue to transfer the data into a spreadsheet.  Is that type of facility/dialogue also possible/useful for us?)

**Comment by dannyparsons** [comment]
This all runs fine for me in the script window (except line 5 which seems to be a mistake)

**Comment by dannyparsons** [comment]
You might not have had spaces around the assignment. So `n<-1000` instead of `n <- 1000` could have been the cause.

**Comment by rdstern** [comment]
OK
