### ISSUE TITLE
When adding a second layer to a scatter plot, geom_point is replaced with geom_boxplot 

### ISSUE THREAD

**Issue by bethanclarke** [africanmathsinitiative/R-Instat#4452]
When adding a second layer to a scatter plot, `geom_point` is replaced with `geom_boxplot`. I found this problem when I was trying to recreate the first graph in Top 50 ggplot2 Visualizations - The Master List 
http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html#Marginal%20Histogram%20/%20Boxplot

Example
Say we want to create a scatter plot of area vs population where we map colour to state and size to population density, using the midwest data frame from the ggplot2 package. We get the following code from R-instat:
```
# Code generated by the dialog, Scatter Plot
midwest <- InstatDataObject$get_data_frame(data_name="midwest")
last_graph <- ggplot2::ggplot(data=midwest, mapping=ggplot2::aes(colour=state, x=area, y=poptotal, size=popdensity)) + ggplot2::geom_point() + theme_grey()
```
Note: to map colour to state and size to population density we click on Scatter Plot options.

Then when we add a smoothing line using `geom_smooth`, we can see that `geom_point` is changed to `geom_boxplot`. Se here: 

```
# Code generated by the dialog, Scatter Plot
midwest <- InstatDataObject$get_data_frame(data_name="midwest")
last_graph <- ggplot2::ggplot(data=midwest, mapping=ggplot2::aes(colour=state, x=area, y=poptotal, size=popdensity)) + ggplot2::geom_boxplot() + ggplot2::geom_smooth(se=FALSE, method="loess") + theme_grey()
```
Note: to add this layer, we went back to the scatter plot dialog and clicked on Plot Options.

What's really weird is that this problem doesn't occur if we don't map colour to state and size to population density!

**Comment by bethanclarke** [comment]
This issue occurs on other plot dialogs too!

**Comment by bethanclarke** [comment]
Additionally this problem does NOT occur when creating this graph using the general graphics dialog

**Comment by Muthenya** [comment]
@bethanclarke I'm not encountering this issue when I do the same. I'm not certain if it has already been resolved.

**Comment by dannyparsons** [comment]
We think we have fixed this so I will close, @bethanclarke can you double check the issue is resolved now?

**Comment by bethanclarke** [comment]
I've double checked this and it has been resolved
