### ISSUE TITLE
Climatic summaries

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4484]
I really like the improvements with the climatic summaries.

There is an issue I found when using Dodoma.rds.  I used the dialogue as it, for annual.  Then I wanted to check that it is OK also for within year, so I clicked at the top tab for within year and put in abbr month.
I did not run that.  Instead I went back to the annual summary.  The error is that the information on the months is not clearing properly.  So, see below, it sometimes gives me monthly summaries though the dialogue appears to show what I want, i.e. annual summaries only.

Then I added rain as the element, and ran.  Seemed OK.  I just got n not missing, n-total and sum.  I had also set the dates to start from 1 April.  

I now went back to the dialogue and changed the dates to 1 Jan.  However, now when I ran it gave me a monthly summary.  I went back to the dialogue and ran again and it was fine - gave me my annual summaries. 

I now returned to the dialogue and changed to look at tmax.  It only shows the annual on the dialogue.  I changed the summaries to give n not missing, mean and max.  It again decided to give me the monthly summaries.   

While making the edits there are 2 more that could be useful to the dialogue.  I think elsewhere we use the word Element instead of Data.  Could we make that change here.

Also, on the within year control, that could be limited to just showing factor (or ordered factor) columns.

**Comment by shadrackkibet** [comment]
I am struggling to replicate this Bug, Perhaps because i am using Dodom.xlsx  instead?(I have an issue loading dataset from instat collection #4455). But i think the error should be the same.
Could you paste the code produced on the output window when you moved from one Top radio button to the other. What i am expecting to change between the two chunks of code is just` factor=c("Year")` for annual and for within year you should have `factor=c("Year","Month")` for the` calculate_summary` function.

**Comment by rdstern** [comment]
I don't think that is the issue.
It comes from having (at some stage) included the monthly factor.  Then returning to looking at annual data summaries.
For example if (with just annual) I now change the element to sunh it runs fine  - the first time.  Now return to the dialogue, which still looks fine - and press OK again.  Now you get monthly summaries.  And (as you say) it has put the 2 factors in the command.  Then, when you return to the dialogue again, you see it has reset so the Within-year button is now the active one.

**Comment by dannyparsons** [comment]
I've been able to replicate it as well. Will look into the issue.
