### ISSUE TITLE
Summaries - first and last and nth

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4497]
The summaries dialogue (and hence climatic summaries has changed a lot. It is looking very impressive now. 

We now have First and Last and nth. What remains is the add the **OrderBy** facility to these summaries. I suggest we keep First/Last/nth where they are now. 

In addition we repeat them in the 2-variable tab - with the OrderBy label for that block of summaries. So it is effectively another statistic - I hope that is OK?

**Comment by dannyparsons** [comment]
I think this will get confusing for our summary system to have it in two places. Not sure what a good solution is though.

**Comment by rdstern** [comment]
It is like the max and min being in 2 places.  I assume it is complicated for the coding, rather than the user? In that case let's put it back into the 2 variable tab only.  However these will then run with, or without, the variable on that tab.  That is unlike correlations, etc, for which the additional variable is needed.

**Comment by shadrackkibet** [comment]
@dannyparsons shall i go ahead and move this summaries to Two-Variables Tab and add `order_by` parameter?

**Comment by rdstern** [comment]
@dannyparsons it would be great to have this.  My only query first is whether it should be moved or should be duplicated there?  Getting the value of the first and last is useful - with the order_by especially?  Then, in addition, it is sometimes useful to have an associated column.

**Comment by shadrackkibet** [comment]
I think it will be easy to have a receiver for the `order_by` parameter and then move this to 2-Variables tab. @dannyparsons  what are your thoughts on this?

**Comment by dannyparsons** [comment]
They should not be on the two variable only, it is only a two variablesl summary when you have order_by. 

I don't see that it has to be on the 2 variable tab, it's own place with an optional order_by would be fine to me. It is not exactly the same as purely 2 variable summaries like correlations so I don't think it's a must to be in the same place.

**Comment by shadrackkibet** [comment]
I am going to have this in it's own Tab - **Position**

**Comment by shadrackkibet** [comment]
Here is my design suggestion.
![image](https://user-images.githubusercontent.com/26301973/44808519-2744bc80-abd5-11e8-81ce-943b940be59f.png)

**Comment by rdstern** [comment]
Looks good.

I wonder where we don't have the first, last nth on the More tab any more.  They are just here.

And there is a check-box (default selected) with label "Order by another variable".  If not ticked, then the selector etc is hidden.

**Comment by dannyparsons** [comment]
Agreed. But I would have default unchecked, I thought without the order by is more common (and a simpler tab to look at initially)

**Comment by rdstern** [comment]
OK. Agreed to have the default unchecked.
