### ISSUE TITLE
Summaries - missing tab implemented

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4499]
The tab is there to set the result to be missing if the number of missing values in a column (or the proportion) exceeds a threshold.  

I hope this is easy to implement, because we already have the summary of the number of missing.  So, behind the scenes, it can include this extra calculation.  

So we add the facility in the Missing tab to make the result missing when a given number, or proportion of the observations are missing. The items in the dialogue are there, but Danny says an addition is needed in the calculation system.

**Comment by shadrackkibet** [comment]
@dannyparsons  i saw you added some Rcode on this should this be implemented now?

**Comment by dannyparsons** [comment]
yes I've added code and implemented for one summary function. This can be replicated for each summary function now. I don't think @bethanclarke has started on it so go ahead if not.

**Comment by rdstern** [comment]
I am unsure of the state of this option now.  
I set the missing option for climatic data, e.g. Dodoma to 32
I return to the main dialogue
I return to the missing tab and it is unset again.

Am I right that this isn't working yet?
