### ISSUE TITLE
Climatic summaries - the third tab

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4501]
I think this is an easy one!

I am getting very pleased with the **Prepare > Column: Reshape > Column Summaries** and the related **Climatic > Prepare > Climatic Summaries**.

Now the climatic dialogue has 3 of the new-style Radio Buttons at the top.  The first 2 currently say **Annual** and **Within Year**.  If there is space then I suggest that **Within Year** becomes **Annual + Within Year**.  It then currently adds a field to include a within year factor - usually the Month factor.  That's all fine.  Nothing changes here.

The third button is no longer needed for the original use that I thought.  Instead, what would be useful is to have this third one say **Within Year**.  This then has the Within Year (say Month) Factor and also hides the Year factor.  That would then give summaries for each combination of Station and Month over all the years. 

This will cover all the obvious combinations.  If anyone wants anything else, then they go to the more general **Prepare > Column: Reshape > Column Summaries** instead.

Neat! And I think this is also just the sort of structure we can also use for the climatic boxplots!  I'll give that some more thought, before adding another issue!

**Comment by shadrackkibet** [comment]
@rdstern  Do we then hide the year receiver when you are on **Within Year** option?

**Comment by rdstern** [comment]
Right.  Just as  you hide the Within Year on the first option, now you hide the Year on the third option.

**Comment by dannyparsons** [comment]
@shadrackkibet done?

**Comment by shadrackkibet** [comment]
Yep this is done but Pullrequest is not yet merged.

**Comment by shadrackkibet** [comment]
This is now done. Can be closed.

**Comment by maxwellfundi** [comment]
@rdstern this is now done. Closing this now.
