### ISSUE TITLE
Regular Sequence dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4509]
Most people on this course are using R-Instat in French, i.e. with their language set to French.

This is sort of OK for most things and Tape (from Ivory Coast) will look at the translations.  But the regular sequence dialogue has a real issue in that the control for the data frame is now moved and almost hidden behind the new radio buttons.  And those radio buttons have moved to the left of the dialogue.

They are doing OK, but I wonder what it is about this dialogue that has changed in this way?  I am sure they can move to English, but they are happier with the French and this will help us find the problems.

**Comment by dannyparsons** [comment]
This is a general issue with radio buttons and our translation system shifting the positions during translation. There are probably other dialogs with the same issue. 
So once we correct our translation system this should be fixed.

**Comment by rdstern** [comment]
This is getting more major as an issue.
For the Display of daily data the OK and other buttons are hidden on the French machine.
Also the Check data QC for rainfall and temperature are disabled!  (Fine on mine - in English.)

Danny you were wondering if Ian might be able to point us in the right direction.  It would be good if this could be done soon.  In addition Tape is happy to work on the actual translation and that would be good to take advantage of, and arrange while he is here.

**Comment by lloyddewit** [comment]
@rdstern This seems to be fixed now so I am closing.
