### ISSUE TITLE
Toolbar for script window

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4510]
This would have been so useful today in the workshop.

We discussed how to automate data transfer to R-Instat.  This made us open the script window.  Now they want to know how to close it!  So much easier if only it were on the toolbar.  We will need to consider the design, because I think we used the proposed script design for the log window.  Maybe bwe could swap the two!!!

**Comment by rdstern** [comment]
In discussions on the use of R David proposed that we have a new toolbar item which is to be able to turn on-or-off the display of R commands in the output window.  

Sounds good to me.  I wonder what the icon would be?  
At the same time I wonder again about the script window being on the toolbar.  I use that much more than the log file.  So I would opt to have that instead and the sort of scroll we have would be more appropriate for the script window.  So we don't spend too long, I give my suggestion that we either swap these icons, or we add Rachel's log for the log file.  I remember David liked that!

In the longer term I assume we will have an item to tailor the toolbar?  Given that, I feel it is useful to have one or two more items now.  It does no harm.  I find it useful!

**Comment by shadrackkibet** [comment]
I think this was fixed during the previous sprint (2020 Feb). See issue #5616 and PR #5667. Please open a new issue if there is anything remaining.
