### ISSUE TITLE
Column names

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4512]
I am not sure whether this will be resolved once the language issues are behind us.

A column was named annees, but with an acute accent on the first e.  Proper French!  The computer was set to French.  The Merge dialogue was distinctly unhappy with that name, which it changed so something like ann@es or ann$es, I forget.  And then it complained a lot, before giving the sub-dialogue.
All was OK once we renamed the column, but the Column Rename command didn't like it either - though not so much.  It complains and eventually gives in and gives the dialogue.  Merge was much more persistent, before giving in.

**Comment by dannyparsons** [comment]
I also now have an example of the same problem with another dataset so I can test this and fix.

**Comment by rdstern** [comment]
Great, thanks.  What does "fix" mean?  I have assumed they will have to avoid accents forever, but that may be over negative?

**Comment by dannyparsons** [comment]
Fix means we remove accents in columns names at import. There seems to be good methods for this in R already.

**Comment by rdstern** [comment]
That's fine.  And I assume the renaming won't allow them to be added there?

**Comment by dannyparsons** [comment]
Yes we can catch it there too.
