### ISSUE TITLE
Graphics: the facets tab 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4514]
A very small issue I hope.

On the facets tab (sub-dialogue for the graphs), the "Free Y axis" option had been ticked.  It wasn't needed so we de-selected the option.  And the resulting graph was OK.  But coming back to that TAB it has re-selected itself.
I assume this may be the case with other options also, at least on this Facets TAB, but I haven't checked.

**Comment by maxwellfundi** [comment]
I have tested this. This  issue is only with the **"Free Y axis"** but not with other checkboxes.

**Comment by dannyparsons** [comment]
Do you know why this is happening?
