### ISSUE TITLE
Using geom text in plotting

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4524]
I have been trying to add text to a graph, using geom_text.  I may be trying to do the wrong thing?  If you look at all the examples of geom_text (or geom_label, [see](http://ggplot2.tidyverse.org/reference/geom_text.html)  they use data from the same data frame as the other plotting elements.  I am using data from a different data frame.  Logically I feel this should work and be useful.  But adding a single piece of text (which I try to do here) could also use an **annotate** layer, which we don't seem to have (yet?). Annotate is described [here](http://ggplot2.tidyverse.org/reference/annotate.html).  It isn't a geom, but it calls a geom, often it calls the geom_text!  I am not sure whether we need it in our implementation, i.e. I don't quite see where it would fit.  It does add a layer, so presumably on the layer tab - if we have it.  But the examples seem to indicate that if we can use geom_text (and other geoms) as I am trying here, then perhaps we don't need annotate.  Instead we make a small extra data frame and use whatever geom is appropriate - usually that will be text or label.  (But it could be different, say to draw a rectangle in a particular place on a plot.)

So, for geom_text I made a new data frame with one row and 3 columns, x and y and a label.  For example x=1950, y = 120, label = "Hello".
I then had a simple line plot (say with samrain, (from the library) plotting the day of the start (strt1) versus year. Then I added the text from my new trivial worksheet as a second layer.  It gave an error, as follows:

**Error running R command(s)
Error in FUN(X[[i]], ...) : object 'year' not found
The error occurred in attempting to run the following R command(s):
data1 <- InstatDataObject$get_data_frame(data_name="data1")
data1 <- InstatDataObject$get_data_frame(data_name="data1")
last_graph <- ggplot2::ggplot(data=data1, mapping=ggplot2::aes(x=year, y=start)) + ggplot2::geom_line() + ggplot2::geom_text(mapping=ggplot2::aes(x=x, y=y, label=label), data=data1, inherit.aes=FALSE) + theme_grey()
InstatDataObject$add_graph(data_name="merge1", graph=last_graph, graph_name="last_graph")
InstatDataObject$get_graphs(graph_name="last_graph", data_name="merge1")
OK**   

When I return to the dialogue it has erased the x and y on the main dialogue.  It now has the new (one line) data frame as the current data frame.  It still has the 2 layers, even though the main dialogue is now blank.
 
I have just checked with geom_label and that gives the same message and makes the same changes as geom_text.  They do the same thing, with geom _label putting a box round the text.

**Comment by dannyparsons** [comment]
This is because it is incorrectly setting "data1" as the data frame for both layers, so the first layer crashes. I've now fixed this and checked that your example works.
This all works with geom_text or label but I like annotate as well because it means for just a single piece of text you don't need to create a whole data frame for it. However, with what we now have everything should be possible.

**Comment by rdstern** [comment]
So are you suggesting we add annotate as another (sort of) layer as well?
