### ISSUE TITLE
Adding to remove or adding remove to filter?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4528]
In preparing climatic data for R-Instat I usually have to remove unwanted rows of data.
These are usually for non-days, like 31 June or 29 Feb in non-leap years.

I can do this now 
1) By filtering to keep the unwanted days and then removing the rows (right-click) on rows, 
2) By filtering to drop the unwanted days and putting the data to keep into another data frame.

After discussion with Danny I suggest we consider making it even easier by either:
1) Being able to Remove IF a condition is true, or
2) Adding a third option to filter to remove the filtered data

In either case I would like the corresponding command that is generated to be one that is easy to put into a script.  This is part of a likely candidate to become a script file, so it can be done easily for multiple data sets.  Currently the method 1 - that I use - generates a command that is often very long and removes each row by giving its number.  That's very specific and would be awkward to edit in a script file.

**Comment by dannyparsons** [comment]
David suggested that this is just a subset where the data goes back into the same data frame. This is currently possibly in the filter/subset dialog, so we may not need any new additions?
This is separate from improvements to the filter capabilities which we do want to do like NOT and OR.
