### ISSUE TITLE
Improving the filter sub-dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4529]
Currently it is easy to choose levels of a factor in the filter sub-dialogue.  But the system with other types of column would be helped if a keyboard could be added.  
With the current layout there could at least be some help for users, e.g. a pull-down for what is typed that includes NA and some other examples.  Better could be a simple keyboard with the numbers, a minus and also NA.  (Anything else?  Does a character column need quotes, if so, these should be added.

Could there possibly also be an option - perhaps one of our new radio buttons that says General as opposed to Basic or Simple.  If General then there is our whole logical keyboard and we just give the condition exactly as in the calculator, possibly including the Try facility, which is useful.

One use of this is to add the OR possibility to the filter, rather than having to go through the calculator and produce the column first.  The example I had on the workshop was 
(Tmin == NA) & (Tmax == NA).  This was actually not what was wanted - we needed OR (|) rather than &.  But that doesn't work in the calculator.  - you use is.na(Tmin) instead.  (I am still curious as to how it works in the filter!)

This is for discussion.  I realise there are many improvements needed to the filter.

**Comment by maxwellfundi** [comment]
In addition, it got people very confused when, the year was a factor in the data and they wanted to do a filter of the year > 1970. 
So when the year is selected while still a factor, it displays the grid showing the levels of factors, which of course you can tick the ones you want. However, to do a proper filter on this, it was needed to get the year as a numeric column, but when you come back on to the filter dialog, while the year is selected it still shows the grid with the levels of factor. It needed to have the year removed from the receiver and then added afresh to be able have the input to type in 1970 and the drop down with the symbols. Can we keep updating the column type when this dialog is reopened?

**Comment by dannyparsons** [comment]
Updating the display when reopened should be done, yes.

I wouldn't have thought a keyboard for numbers would be needed since its just a single number being entered but if users would like that there no problem. NA is useful but should be a drop down item in the textbox which should become a combo box, because NA should be there on its own if you're using it. I'm not sure why you would need TRUE and FALSE for a numeric column? The evaluation should always be against a number or NA. For logical columns TRUE, FALSE and NA could be in the drop down and you would not be able to type anything else in because there are no other options.

I don't see anything difficult about any of these changes so someone could take this up.

Having the option of AND or OR is also just a small change in the R code if someone wants to investigate that.

**Comment by rdstern** [comment]
In discussion on 26 June the suggestions were clarified.
1. Updating the display as mentioned above should be done.
2. Adding the simple improvements, should also be done, namely
a) When date is chosen there should be a date picker.  Also dates could be NA.
b) With numeric and character columns NA should be on a pull-down.
c) With logical columns NA, TRUE and FALSE should be on a pull-down.

The discussion of the possibility of adding OR led to a longer consideration of whether, in addition, consideration should be given to changing the system to the way it was implemented in CLIMSOFT.  This is a challenge, but one that could now be within the reach of the AMI CLIMSOFT team.  Whether it should start before David/Danny are back from Niger is more debatable.

**Comment by rdstern** [comment]
In the climatic documentation I am using the Filter sub-dialogue, both with thye condition Date1 == NA and with Dup1 ==TRUE.
I know Lazarus has been making improvements to this dialogue.  Are they close to being in a new version yet, or do I assume the filter is the same as now, i.e. you have to type NA and TRUE?

**Comment by shadrackkibet** [comment]
As far as I can see much of these has been implemented elsewhere. Open a new issue with the specific aspects of the filter that still remain.
