### ISSUE TITLE
Labels on plotting to reset correctly

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4533]
Overall the graphics are working well now.  So it is a good time for them to work brilliantly!

There are some (minor) things on this dialogue that could usefully be improved on boxplot (and some other dialogues):

1. When you move from boxplot to jitter or violin, then the label Boxplot Options correctly changes to Voilin or Jitter options.  But when you close the dialogue and then return it now says Boxplot Options.  The tab at the top is still on Violin or Jitter, so it is just a question of keeping the control setting when on violin or jitter.

This (feature) is the same on histogram.  It is not the same on bar chart, where the option for a pie chart remains the next time the dialogue is used.

2. Another general "feature", this time on many plotting dialogues is when you move from single variable to multiple variables.  Then, when you return, the label says **single variable** again, though **multiple variables** are still there.  It is just the label to correct.

**Comment by dannyparsons** [comment]
@maxwellfundi this should be simple to get back in sync, especially the buttons, can you look into.

**Comment by maxwellfundi** [comment]
yeah fixed the sync already on the plot dialogs- Box and hist

**Comment by rdstern** [comment]
Great

**Comment by Ogik99** [comment]
Seems this issue was already resolved. Can it be closed?
