### ISSUE TITLE
Export of graphs doesn't work

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4536]
I tried export of the last graph using file > export > graph as image.  When I pressed OK I get

**Error running R command(s)
Error in UseMethod("grid.draw") : 
  no applicable method for 'grid.draw' applied to an object of class "list"
The error occurred in attempting to run the following R command(s):
last_graph <- InstatDataObject$get_graphs(data_name="Guinee2_by_year_Station", graph_name="last_graph")
ggplot2::ggsave(filename="C:/Users/Roger Stern/Dropbox (SSD)/Roger/ICRAF/Benin/Data/Guinee/debut.jpeg", plot=last_graph)
OK**

**Comment by maxwellfundi** [comment]
What sort of a graph was this? ggplot object? I seem to get the same issue when I try exporting none ggplot

**Comment by rdstern** [comment]
Yes it was an "ordinary" ggplot

**Comment by maxwellfundi** [comment]
@dannyparsons I have been investigating this issue. Our Dialog is set up properly, everything passed in as needed. I get the below error even in R where I use the function withwhich seems to be an internal issue with ggsave where it cant handle List psroperly. 

```Saving 5.6 x 4.75 in image
Error in UseMethod("grid.draw") : 
  no applicable method for 'grid.draw' applied to an object of class "list"```

However, I still run the ggsave with the plot parameter as `last_plot()` and that seemed to work.
`ggplot2::ggsave(filename="C:/Users/Fundi/Pictures/bargraph.jpeg", plot=last_plot())`

I am not sure if our `InstatDataObject$get_graphs(data_name="survey", graph_name="myBar")` is not working properly.

**Comment by dannyparsons** [comment]
If `InstatDataObject$get_graphs(data_name="survey", graph_name="myBar")` is returning a list containing the ggplot object instead of just the ggplot object then that is the problem. You can more easily check this by running the R code in RStudio.

**Comment by maxwellfundi** [comment]
@dannyparsons  we have checked this with @shadrackkibet  and ` InstatDataObject$get_graphs(data_name="survey", graph_name="myBar")` returns a list containing ggplot objects. It could be the reason why this does not work.

**Comment by dannyparsons** [comment]
Yes that will be the issue. There should be a parameter to control this I think its `as_list`.

**Comment by maxwellfundi** [comment]
@dannyparsons  When you have sometime, please have a check at the `InstatDataObject$get_graphs(data_name="survey", graph_name="myBar") ` to see how better we can get the outputs for the graphs.
