### ISSUE TITLE
Add a formula control to the arguments for geom smooth.

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4539]
This is an extra field.  It could usefully be one where some examples are given, but you could type.  This is like some of the fields in the Climatic > PICSA > Crops dialogue.
So there is a pull-down, which gives some examples:
y ~ x (This is the default)
y ~ poly(x,3)
y ~ log(x)
y ~ splines::bs(x,3)

**Comment by Ogik99** [comment]
@maxwellfundi this issue can now be closed. It's addressed by #5382
