### ISSUE TITLE
Setting for the Filter sub-dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4567]
Is the setting for the filter sub-dialogue correct?
I am busy capturing screens and find that the Filter sub-dialogue insists on being on top whatever other application I move to, e.g. Powerpoint.  The other R-Instat dialogues seem more polite!

Is this a feature of all sub-dialogues or is this one just being too insistent?

**Comment by dannyparsons** [comment]
Kind of a general problem that it was the only way we could ensure that subdialogs appear above main dialogs. But it shouldn't need to be on top of everything - just the main dialog. @maxwellfundi @Patowhiz  can this be looked into again?

**Comment by Patowhiz** [comment]
Okay. This is just an issue of TopMost property of the Form. Fixing this
