### ISSUE TITLE
Small change in Climatic > Prepare dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4572]
There are 6 dialogues in the Climatic > Prepare menu.
What is good about them all is that most fields are automatically completed.  That's the climatic "system".

A small edit would be useful in Transform, Climatic Summaries and Extremes.

In these dialogues the system cannot complete the element, because it could be one of many - in general.
But could it be the control with the initial focus, i.e. it should be in turquoise.  This is the case for the Spells dialogue already.

**Comment by Patowhiz** [comment]
This works fine on my end. The element receiver for the dialogs in the climatic prepare menu gets the focus by default now.
@dannyparsons this is ready for you.
