### ISSUE TITLE
Infill missing dates 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4585]
I tried, for I think the first time, doing the infill without a station factor.  It didn't seem to like this and gave an error.  I then made the (single) station code into a factor and included it.  Then it ran OK.  And it infilled.

I can't generate the error again.  It seems to be OK when there is nothing to add.  If the error isn't easy to find then I can clarify in more detail.

**Comment by dannyparsons** [comment]
Could I have a look at the data set?

**Comment by rdstern** [comment]
It was the station data sent by Jorg on Tuesday.  I think you have a copy?
