### ISSUE TITLE
Small change in Make Date

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4587]
In the make date dialogue when there is a **single column** and the **specify format option** then could the data selector be set to only show **non-numeric** columns. 

Note that this is only set in this way for **single column + specify format**.  (If it were single column + specify origin, then the column would be numeric!)

I hope this is really simple, so could be done for the forthcoming release.  But could be later if there is too much other work. 

The reason for this change is the YEARMODA format, which is popular and works fine if the column is set to be character.  But it is something like 19810101, and so usually comes in as a numeric column and that doesn't work.  The dialogue then says to give an origin, which is not the correct thing to do.

**Comment by dannyparsons** [comment]
Note that this should be excluding numeric only, because character/factor are all fine.

**Comment by Muthenya** [comment]
This seems to have been done. I guess it can now be closed.

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/developers This doesnt seem to have been referenced on a pull request. Was it solved so that i can close it now as @Muthenya  suggests.

**Comment by shadrackkibet** [comment]
I did this, this can be closed.
