### ISSUE TITLE
New dialogue for PICSA rainfall graphs

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4605]
We currently have a **Climatic > PICSA > Rainfall** menu.  The item is disabled.
It might now be called Rainfall Graphs, because that is the part of the PICSA that it makes really easy.  And that is the bit that is now a bit time consuming.

It is based on the **Describe > Specific > Line plot** dialogue.  So use that to start with.
It uses the annual summary data frame that has the data to be plotted.  So PICSA retains total flexibility in what is in the graphs.  This dialogue makes it easy to have consistent graphs of the different rainfall events.

1.  The x-axis is the year column, so that can be filled automatically.  It is always plotted as a variate, so it could be transformed with as.variate if it is a factor.
2.  There need not be a label for the x-axis.  It is obvious that they are the years.
3. Just one column is plotted.  We probably don't need the option here to have multiple Y columns, but perhaps leave it initially.
4. The option to add points is ticked by default.
5. One complication usually is the default size of the points is too small.  And on the current line dialogue it can't easily be changed.  It is the geom_point and possibly (at least in this dialogue) we add options to change the size and colour (and possibly the shape).  Then the defaults are for PICSA, rather than the ggplot defaults.
6.  On the line dialogue there is the Factor (Optional).  I suggest we keep this, because it does no harm.
7. We omit the option (in the line plots, for the line of best fit.  But there are sufficient additions that we  have a button labelled PICSA Options.
On this sub-dialogue we have:
a) A checkbox with Plot Mean.  Default checked.  This is an hline layer.  Possibly also have thickness and colour of this line.
b) A checkbox with Plot Median.  Default unchecked.  Ditto.
c) A checkbox with Plot Terciles.  Default unchecked.  This is 2 hlines.  They can be the same thickness and colour.
d) The current Y-Axis title.  Default is the current title.  (This will often be typed in the local language)  After that is the Size, which is the Theme Y-axis label size.  (That's the size of the y-axis title.)
e) Also from the theme is Y-axis labels size, default perhaps 15.
f) And then X-axis angle.  and x-axis labels size.
g) For each of these (y-axis and x-axis) have a checkbox (default unchecked) with Specify x-axis tick marks and Specify Y-axis tick marks.  If checked, then it opens the same From To Steps Of, that is on the current x-axis and y-axis sub-dialogues.
h) Then (some experimentation is needed for this) could have a further checkbox for the mean, median and terciles called Add Label.  This adds a label (with a box round) giving the value.
i) Would it be easier to add the dates option here, compared to doing it generally?  (So 92 is shown as 1 Apr.  If so, it should allow for shifted dates.
j) there is a footnote option, and sub-footnote.  One of these gives the acknowledgement for the source of the data.  The second gives the definition of the event.  There are defaults for each of these.  The default for the acknowledgement is the label for the data frame.  The default for the event is the label for the variable being analysed.

I have tentatively allocated this to David to see whether it could usefully be done by someone from AMI - if so, then who?) and whether it would be useful to involve Beth?

**Comment by rdstern** [comment]
Here are some examples of possible graphs.  And I forgot one element above.  It is good to have a footnote, acknowledging the source of the data.  And also a second one that provides the definition being plotted.  

![image](https://user-images.githubusercontent.com/11226469/40347866-b56f3754-5d99-11e8-94ba-0f0a267fee65.png)

And then:
![image](https://user-images.githubusercontent.com/11226469/40347930-e4cc9d20-5d99-11e8-89c7-818d7f2f1e06.png)

And:
![image](https://user-images.githubusercontent.com/11226469/40347979-0fbe77b0-5d9a-11e8-9788-b87f23ccdefa.png)

Here is the start of a more general idea for this dialogue.  PICSA is under pressure to also provide exceedance plots, which we have e.g. (from the old Instat)

![image](https://user-images.githubusercontent.com/11226469/40348456-aa6ecf3e-5d9b-11e8-8f8c-5fd2193f1171.png)

And we might also offer options to provide tables of results.  

I am increasingly happy with the idea that the PICSA dialogues would start once the data have been summarised in the appropriate form.  So they take data from an appropriate data frame and present the results as tables and/or graphs.  This is for the rainfall and later also for the temperature analyses.  The crops aspcect is different.

**Comment by rdstern** [comment]
Here is perhaps our first example of independent work using R-Instat.  It is mainly rainfall graphs.  I am not sure I like quite so many points on the axes, but that is a detail.  
These graphs have all the components above except the footnotes to give details of what is plotted, plus acknowledgement of the source.

The graphs above were with the old Instat, while the ones in the pdf file here are with R-Instat.

[Graphiques de données climatiques de Kankan (Guinée).pdf](https://github.com/africanmathsinitiative/R-Instat/files/2038445/Graphiques.de.donnees.climatiques.de.Kankan.Guinee.pdf)

**Comment by rdstern** [comment]
Having discussed the forthcoming Malawi workshop it would be great if this dialogue could be started - possibly finished - in time for the workshop.  It should be easy to make some quick progress, because it is essentially an adaptation of the prepare > Specific > Line Plot dialogue.  There will be an extra PICSA sub-dialogue.

I am assuming Maxwell is the obvious person to do this.  he could then cover this topic in the forthcoming Malawi workshop.

**Comment by maxwellfundi** [comment]
I will take on this task hopefully complete by the time for the workshop

**Comment by maxwellfundi** [comment]
@rdstern  Will this have the button to our general plots sub dialog? 

Just to seek Clarifications on 
**1. Just one column is plotted. We probably don't need the option here to have multiple Y columns, but perhaps leave it initially.**
Can we then just have a single receiver for this instead of the current multiple/single if we will only plot one variable?

**2. One complication usually is the default size of the points is too small. And on the current line dialogue it can't easily be changed. It is the geom_point and possibly (at least in this dialogue) we add options to change the size and colour (and possibly the shape). Then the defaults are for PICSA, rather than the ggplot defaults.**
On this can we have have these  options(Nud for size and a colour control) next to the add points checkbox and visible when the checkbox is checked?

**Comment by rdstern** [comment]
You ask:
Just one column is plotted. We probably don't need the option here to have multiple Y columns, but perhaps leave it initially.
On item 1 almost all plots will have a single y variable, so one possibility is (as you say, to disable this option and that would make the dialogue simpler.
There are just a few exceptions.  In particular it may be useful to plot the start of the rains together with the end of the rains.  Or the end of the rain, together with the end of the season.  Of course this could always be a second layer (in those rare occasions), which is why I suggest we could limit it to the single Y.  But keeping the multiple for now may be no work.  Then we could get rid of the option later if we find it isn't useful.

You also ask:
2. One complication usually is the default size of the points is too small. And on the current line dialogue it can't easily be changed. It is the geom_point and possibly (at least in this dialogue) we add options to change the size and colour (and possibly the shape). Then the defaults are for PICSA, rather than the ggplot defaults.

This is linked to the failure in the line plot dialogue that you can add points on the main dialogue but then can't change aspects of this geom.  That's because it is on the main dialogue.  For edits to the lines that has the special sub-dialogue.  I think Danny was suggesting there is no real need to stop us using the general editing of geoms that are on the main dialogue.  

If that becomes possible, then I would be happy that the default size of the points in this dialogue is larger than the ggplot default and then other changes just use the general editing of the geom.

**Comment by maxwellfundi** [comment]
So am not sure how we could edit more than one geom from the main dialog, but for this case it would be easy to add the size and colour for the points by using the colour control and a nud to pass in size which are only visible when add points checkbox is checked. 

![image](https://user-images.githubusercontent.com/9798689/40870544-71f30844-663a-11e8-9399-531fd21678e1.png)

**Comment by rdstern** [comment]
@maxwellfundi this is possible, but I would still prefer the simplicity of the main line plot command, but:
a) With the default on this plot being larger points
b) Hopefully with the facility added generally to be able to edit the geoms (such as this one) from the main dialogue just as the geoms on other layers can be edited.  If I understand Danny correctly, there isn't a good reason why this can't be done
c) If that isn't possible, then these options could be added to the list of PICSA Options, i.e. on the sub-dialogue when that button is used.
d) In your proposed layout above you have **PICSA Options** instead of **Line Options**.  I was thinking (with our current system) there would be 3 option buttons, namely Line Options, Plot Options and also PICSA options. Of course if we could edit the layers that are determined by the main dialogue, i.e. Line Options and Point Options, then your layout would be fine.  Let's check this point with @dannyparsons.

**Comment by maxwellfundi** [comment]
I will then have to remove the colour and size from the main dialog then we can have them added by default or moved to the PICSA options subdialog. I will be adding the extra Line options buttons too. 
I will consult Danny how we can edit these kind of additional geoms generally so that we give the users the chance to edit them .

**Comment by maxwellfundi** [comment]
@rdstern  I have now, from your above text desiged the initial PICSA Sub dialog design.  Please have a look 

![image](https://user-images.githubusercontent.com/9798689/40964755-92b2dda8-68b4-11e8-963e-9153bd5bff21.png)

**Comment by rdstern** [comment]
Looks good.
a) At the top I would say **Add Mean**, **Add Median, Add Terciles**. Default unticked.
b) If any is ticked, then the option tickbox **Add Label** appears. So don't need the Add label section, which will simplify the sub-dialogue a bit.
c) On the same line as Y-axis Title have a checkbox **Y Axis Labels** for their size (as you have for the x axis.
d) Under that line the checkbox for Specify Y axis Tick Marks.
e) Under that we start with the x axis.  Start (as you have) with X-axis Angle.
f) then (on the same line.  "X Axis Labels" for their size - as you have.
g) Then the X Axis Tick Marks as you have it.
h) The footnote and Sub-footnotes could be quite long.  So could make the field bigger.

**Comment by dannyparsons** [comment]
Having two buttons to open the layer options for the two geoms is definitely possible.

**Comment by maxwellfundi** [comment]
@dannyparsons, Yes that should be very possible to implement. So then that would mean we have an extra button next to the control adding the other geom I think so that it does not confuse people with the other ones. I wonder how the dialog would be if we had like 3 geoms passed in this way, we would have too many buttons ???

**Comment by dannyparsons** [comment]
With many layers, or even two, we could have a drop down button i.e. like the last 10 dialogs button, which gives the layers on the drop down. That will reduce the number of things on the dialog.

**Comment by rdstern** [comment]
I asked Sam about the easiest way to get the line for the mean and also the quantiles.  There seem to be 3 possible ways!
1) just use hline( y=mean(rainfall column)), or quantile(rainfall_column,prob=0.333, na.rm=TRUE), etc .  I assume this will work with facets, but Sam wasn't sure.
2) use stat-summary
3) use our brute-force method of producing another column with these summaries first.

I assume 1 or 2 and 1 would be neat if it works!

**Comment by maxwellfundi** [comment]
@rdstern @dannyparsons  On the sub dialog  I was wondering if we can save the user the many clicks of checking the checkbox then filling in the other things otherwise we can simply have it the way it currently is.

**Comment by maxwellfundi** [comment]
@rdstern  the points here are `size=3`

![image](https://user-images.githubusercontent.com/9798689/41332578-12af19a8-6ee7-11e8-91e0-75256cb9bae9.png)

And this is  `size=4`

![image](https://user-images.githubusercontent.com/9798689/41332598-31ba59b6-6ee7-11e8-9459-9d5a818631d2.png)

Which size would you prefer? Is red color okay?

**Comment by rdstern** [comment]
Red is fine. I prefer 3.

**Comment by rdstern** [comment]
Didn't mean to close it!

**Comment by dannyparsons** [comment]
According the [this question](https://stackoverflow.com/questions/35701663/ggplot2-add-hline-with-population-median-for-each-facet/35701887) and the [ggplot2 documentation](https://ggplot2.tidyverse.org/reference/geom_abline.html) the way to do this is either create the summary data frame and use that for the lines or create columns for the summaries in the same data frame. Neither of these are ideal but adding the summaries to the same data frame is probably easiest for us.
It would be a bit easier if it was always by station but since the sub dialog is accessible it will do strange thing if the facets are changed there. Doing it for general facets is not much harder.

The code would then change to:

```
dt <- dt %>% group_by(station) %>%
  mutate(med = median(y))

ggplot(dt, aes(x = x, y = y)) +
  geom_boxplot() +
  geom_hline(aes(yintercept = med)) +
  facet_wrap(~ station) +
```

**Comment by dannyparsons** [comment]
Please collect the error messages and R code when this happens otherwise it's difficult to fix.

**Comment by dannyparsons** [comment]
I suggest we close this as other issues have been raised separately now.
