### ISSUE TITLE
Importing text or Excel file

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4608]
Our File > Open is pretty good already.  Item 1 below may be complicated to fix, but item 2 (from Excel) should be easy.

1. This was provided as a txt file that doesn't preview (I don't think that is easy to change) and doesn't import.  It is given below.

2. So I imported into Excel and saved as an Excel file.  It does import from Excel, but a simple feature seems missing from the Excel Import.  That is a checkbox saying something like Provide Column Names.

This is the col_names argument.  If I copy to a script file and then add col_names=FALSE that is what is needed.  Please could this be added to the Excel-type import. 

[haiti_156stations_mensuelles_coordonnées.txt](https://github.com/africanmathsinitiative/R-Instat/files/2025878/haiti_156stations_mensuelles_coordonnees.txt)

**Comment by Patowhiz** [comment]
I'm working on this.

**Comment by Patowhiz** [comment]
@rdstern which one will you prefer between Provide Column Names and Generate Column Names, as the label of the checkbox?

**Comment by rdstern** [comment]
Either, I think Add Column Names perhaps!  Then it should also add them into the preview window?

**Comment by rdstern** [comment]
[haiti_156stations_mensuelles.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2027716/haiti_156stations_mensuelles.xlsx)

Here is the data file - and my second problem.  I wanted to change the NaN in this file to missing (in R-Instat) and don't think we currently have an easy way to do this.

It is an easy edit in Excel, which I used.  But what should/could be used in R-Instat?

**Comment by Patowhiz** [comment]
To answer your question above. On the import dialog, there is a Missing Value String textbox. You can just type in the NaN inside the textbox and that will change those values to missing. Please note currently, this doesn't show up in the preview until you change leave the control( the event happens on change of focus) but I have fixed that.

Upon more research I had to use `readr `library for the text files import, it seems to be much better in functionality than the `rio` library.  There are still other additional functionalities like **locale** (which will help people in countries that don't speak english ) but we have agreed with Danny that those can be added later in a sub dialog.

The issue of using different separators for CSV files has also been solved.
