### ISSUE TITLE
Editing an awkward data file in R-Instat 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4610]
[haiti_156stations_mensuelles_plus.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2026282/haiti_156stations_mensuelles_plus.xlsx)

This is already a better file than I was sent as that did not have the station names.  I suspect from the NaN that it may actually have come from R.
But my issue is how (in R-Instat) do I change these NaN strings to be proper missing values?  I tried a few obvious possibilities, but I also wonder whether our handling of labels is adding to our complications for these data.

I do not have a problem importing these data, if I make the obvious change in Excel, i.e. replace NaN by blank.  What do I do in R-Instat?

**Comment by dannyparsons** [comment]
On the Import dialog I just changed the missing value string to NaN and it worked.

**Comment by rdstern** [comment]
I accept this was a possibility I missed.  But otherwise how could I make this edit once in R-Instat?

**Comment by dannyparsons** [comment]
You can use the replace dialog and set NaN as old value and "Missing" as new value. It can do multiple columns in one go but only if they are the same type.

**Comment by rdstern** [comment]
I tried that.  It seems the obvious one.  But they were all character variables and so did not appear in the data selector.  Let me look again.

**Comment by dannyparsons** [comment]
There is an issue with that dialog where the receiver gets restricted to a type when you add a variable but doesn't get back to all variables when you remove it. So that should work when this is fixed.

**Comment by rdstern** [comment]
I think this is the other main problem.  I am now importing another awkward data set into R-Instat.  
[Cape Perrin.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2034644/Cape.Perrin.xlsx)
[Haiti rainfall 1993-2010 mm_eng.pdf](https://github.com/africanmathsinitiative/R-Instat/files/2034645/Haiti.rainfall.1993-2010.mm_eng.pdf)


I started with the pdf file (attached) and after some effort got as far as the Excel file - also attached.
I imported and then filtered out the Total column (which I had left there for checking).
The problem is that other columns (some of them) are character.  When I make them numeric it proceeds via the factor labels - which I don't want.  I can get it looking OK by making the columns into factors, but that doesn't help really.  I want the labels as the numbers!

I usually treat this situation (columns that should be numeric but come as character) as an indication I should edit something in the Excel file.  But I would like to be able to solve this problem also in R-Instat.

1. When the column is of type character and I right-click and choose numeric it doesn't work.  It is the same (I think) as when the column was a factor.  I can make it work in the calculator by doing **as.numeric(as.character(April))** etc.  And this is what I think the convert to numeric should do (on right-click) when the column has been made into a character column.  I am assuming the fact this doesn't work is a bug.

2. We should do item 1 above, but I would like us to also consider more, either in the calculations or in the filter, or both.  In the data set here there is a real reason the columns are given as character.  The copying    did not work perfectly and there are some extra spaces added, e.g. 1<space>2.5, i.e. 1 2.5 instead of 12.5.  I hope our editing of strings can correct this, but I would also like to detect the issue (as I do in Excel, by attaching a filter, and looking at the contents of the column.  here I would like to be able to (easily) filter and/or make a logical column that is true or false depending on whether the value is a column.  I think usually we can use:
ifelse(is.na(x), NA, TRUE) & is.na(as.numeric(x))  

Here is the screen with the October problems:
![image](https://user-images.githubusercontent.com/11226469/40514684-01c389fc-5fa2-11e8-8086-73fc94fddf8f.png)

3. So the above would help.  Now to make the corrections, we can click and edit a cell.  I wonder if (a bit like Excel) we could right-click in the cell and press an Edit key and it would open a field with editing in it.  This would be particularly useful for string fields.

4. Instead I tried the Prepare > Column: Text > Replace.  It gave me an error. It worked fine when I removed the filter.  I didn't realise the commands are among those that don't  work with a filter?

**Comment by dannyparsons** [comment]
I used the Text Find/Replace dialog to replace spaces with blank and that worked for me with and without a filter. After that replacement they convert to numeric correctly.

It might be good to have a quick way of looking at "non numeric" values in a character/factor column. Possibly a special filter, although not sure we can make it as easy as the filtering in Excel.

**Comment by rdstern** [comment]
When I filtered to select all the rows where a space need be removed and then used Prepare > Column: Text > Find/Replace and then Replace all it gives me:

**Error running R command(s)
Error in self$get_data_objects(data_name)$add_columns_to_data(col_name,  : 
  Length of new column must be divisible by the length of the data frame
The error occurred in attempting to run the following R command(s):

October <- InstatDataObject$get_columns_from_data(data_name="Cape.Perrin", col_names="October")
Octrep2 <- stringr::str_replace_all(string=October, replacement="", pattern=" ")
InstatDataObject$add_columns_to_data(col_data=Octrep2, col_name="Octrep2", data_name="Cape.Perrin")
OK**   

If I don't have the filter on, then it runs fine.

**Comment by rdstern** [comment]
I am now more convinced we need to change something in the way we convert between types of data.  With the current system I have managed to completely mess up the column for the day of the month - see below.  It came as text because I had a Total value as well as the levels 1 to 31.  But the fact that 10(th) is coded 2, etc is already confusing.

![image](https://user-images.githubusercontent.com/11226469/40532548-b970eebe-5ff7-11e8-8914-aa740d3c046e.png)

**Comment by dannyparsons** [comment]
A simple option we need is to remove the labels. Which could be from the metadata or the levels/labels dialog.

**Comment by rdstern** [comment]
Sounds good.  That would work.

**Comment by rdstern** [comment]
[cape Perrin.zip](https://github.com/africanmathsinitiative/R-Instat/files/2053877/cape.Perrin.zip)

This shows the importance of being able to have text columns without insisting on labels.
1. I imported the data from the Excel file - cape.perrin.
2. Used the filter to make another sheet called cape.perrin2 without the Total rows at the end of each year of data.
3. Used Stack to stack the data by Month and produce cape.perrin3.

Now the data column, called **rain** has the values above, with an extra space within the number.
So I used the Text > Replace and got rid of those extra spaces, made it the column called **Rain**.  I am now ready with (I hope) the column that just has numbers.

Make numeric for the column Rain doesn't now work it says:

**Error running R command(s)
Error in names(attr(x, attr.string)) <- labels : 
  'names' attribute [385] must be the same length as the vector [362]
The error occurred in attempting to run the following R command(s):
InstatDataObject$convert_column_to_type(data_name="Cape.Perrin3", to_type="numeric", col_names=c("Rain"))
OK**   

I assume this is the labels that no longer exist now?
I therefore used the calculator with as.numeric(as.character(Rain)) and pit the results into Calc1.  I think that's the number column I want?

**Comment by dannyparsons** [comment]
Yes this is an issue with the labels. A work around is to use the Convert Columns dialog and untick the option to "Create labels" and this will prevent it trying to create labels and you won't get this error.

**Comment by rdstern** [comment]
[Toussaint Louverture 1943.txt](https://github.com/africanmathsinitiative/R-Instat/files/2064717/Toussaint.Louverture.1943.txt)
This is an interesting file to import.  I used the new importing, which looks great. 

Then found it would be better to make 99.99 into NA and not make factor columns.  All seems to work!

Now a problem.  Not with the importing, but a text editing problem.  The rainfall column has usually 4 numbers followed by a letter.  For example 0.00G.  But it is sometimes 11.16H, i.e. 5 numbers.  I would like to split, so the letter is separate from the number part.  How do I do this a) anyway (so perhaps in the script window) b) using the dialogues?

**Comment by dannyparsons** [comment]
I think this has been resolved with the Text Split function

**Comment by rdstern** [comment]
Is it with Text Split?  I agree it has been resolved.  For the record I used Text > Transform > Substring.  Then I found the substring from 1 to -2 as you suggested.  The use of negative values works a treat!

**Comment by dannyparsons** [comment]
Yes thanks it's substring not split.
