### ISSUE TITLE
Issue with Importing from Climsoft Database

### ISSUE THREAD

**Issue by mhabimana** [africanmathsinitiative/R-Instat#4635]
We have been trying to import data from Climsoft database with R-Instat version 0.4.16 but we keep getting this error message. 

![image](https://user-images.githubusercontent.com/10340170/40712499-911c96b2-6406-11e8-8f56-b53399868448.png)

**Comment by rdstern** [comment]
It will be useful to get this feature working again.  The first version was done by Marcellin and David a long time ago, so I am not surprised that it needs to be tested now.  I am assuming that the final tests of this feature will be when CLIMSOFT is implemented in Maseno with the Western Kenya data.

Meanwhile it is also important to test the ease with which R-Instat can read data exported from CLIMSOFT.  This applies to both the actual data and also to the meta-data, particularly the station data.

Once this is working, then that aspect is a high priority for a guide and perhaps also a video.  The guide will connect with those we are starting for the system of analysis of climatic data in R-Instat

**Comment by mhabimana** [comment]
@rdstern Thanks, It is connecting well to climsoft database and get the metadata but unable to display these in R-Instat worksheet for further climatic analysis as a result it display the error message below:
![image](https://user-images.githubusercontent.com/10340170/40723386-831b87fa-6427-11e8-884b-5b587bac6fc7.png)

**Comment by mhabimana** [comment]
@maxwellfundi This has finally worked with the new version 0.4.17. Now I am able to load data into R-Instat worksheet.

**Comment by maxwellfundi** [comment]
Great!  Am happy to hear the new version has now worked properly.

I think it's important for us to know why that wasn't reading properly so
that it doesn't happen in the future.

**Comment by dannyparsons** [comment]
The error originally posted is a general error in connecting the front end to R. It could be that 0.4.16 did not install R packages correctly for example, so the error may not have been with the specific dialog.

@mhabimana are you able to test this again with the old R-Instat 0.4.16 to see if it still gives the same error?

**Comment by mhabimana** [comment]
@dannyparsons: Both 0.4.16 and 0.4.17 are now importing data without error:Below is the dialogue is using 0.4.16
![image](https://user-images.githubusercontent.com/10340170/40980988-7d6184a8-68e2-11e8-8b48-f1524db1acc3.png)

**Comment by dannyparsons** [comment]
Thanks @mhabimana that's great, then I am quite sure it was an installation issue with 0.4.16 and not the dialog. I will close this issue but now you are able to import the data please feel free to make any suggestions for improvements to the importing dialog in a new issue.
