### ISSUE TITLE
Date Pickers Controls for Import from Climsoft dialog

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#4641]
I would suggest that, now that we have date picker controls it will be good to have that implemented everywhere we have the date to be selected. 
On this dialog, the start date and end date should be changed to date pickers 

![image](https://user-images.githubusercontent.com/9798689/40772948-163f510e-64ca-11e8-9e63-e1e04787eb0e.png)

**Comment by dannyparsons** [comment]
Yes good idea.

**Comment by shadrackkibet** [comment]
This has been implemented here #5957 also see below the current design.

![image](https://user-images.githubusercontent.com/26301973/108603937-d7b56500-73bb-11eb-8446-99863cb6c88b.png)
