### ISSUE TITLE
Summary statistics to add a Model tab

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4651]
I suggest an additional tab in the statistics offered by the Prepare > Column: Reshape > Column Summaries dialogue (and others that share the same sub-dialogues).

This is called Model and it has (initially) just one checkbox which is Standard Error of the Mean.  This is just sem<-sd(x)/sqrt(length(x)).

I don't know whether this should be a function (as Beth did for the trimmed mean) or just done like this?

**Comment by dannyparsons** [comment]
I think this needs to be it's own function but is easy to add. Need to make sure it handles missing values carefully.

**Comment by shadrackkibet** [comment]
I am working on this.
