### ISSUE TITLE
Unstack has a new problem

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4652]
Unstack has lost its power between 4.16 and 4.17.

It now has the buttons at the top for restore hierarchy.  And I think this is OK - but not tested propoerly.

But Tutorial 2 uses the ordinary unstack and this has lost the control that gives the column to unstack!  This needs to go back.  In the meantime could someone quickly say how we can use the script file to be able to do an ordinary unstack in Tutorial 2!

I have resolved this.  It works fine in version 4.16, so a comparison shows the command to use.

**Comment by Muthenya** [comment]
@dannyparsons I have already added back the control and the paremeter. @rdstern is there any other issue that you have come across with the dialog?

**Comment by Muthenya** [comment]
Since this was fixed in #4658, I guess it can now be closed.
