### ISSUE TITLE
New dialogue to reshape climatic data

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4659]
In the Haiti workshop I decided to include the steps to reorganise daily data into the "shape" needed.  This was tough and - in hindsight - unnecessary.

When data are a real mess the initial steps are usually taken outside R-Instat.  There are then 3 common shapes:
a) One column (variable) per year.  This is the old Instat.
b) One variable per month - so the 12 months have to be stacked.  There is a day-of-month column.
c) One variable per day of the month - so the 31 days have to be stacked.  One row is a month.

If a) then it is a single element from a single station in a file (or Excel sheet).  It is usually rainfall.  
If b) Then there will also be a year variable, possibly a station variable and possibly an element variable.
If c) then there will be a year variable.  There can be a station variable, and there can be an element variable.

**Comment by dannyparsons** [comment]
Yes this would be good to have as a dialog.

We also considered whether it should be able to do this for multiple files/data frames in one go e.g. if you have the format in a) for the same element for 20 stations it could do them altogether using the sheet name as the station ID.

Should the dialog take file(s) as the input or data frame(s)? i.e. do they have to import the data into R-Instat first and then use the dialog to reshape, or do it directly as a special import?

**Comment by rdstern** [comment]
I give a possible design for the dialogue below.  I would also really like it to be able to use multiple data frames, but would be happy if we started with just one for now.
In the use of multiple data frames, as Danny says, this could then be through multiple files, or the import could be done first and then the multiple data frames are used.  I would be happy with (just) multiple data frames.  This is for 2 reasons:
1) It keeps life simple.  We also work on making it simple to import multiple (identical) files, or multiple identical sheets from Excel.  But we don't get clever by mixing the two.  Both these steps are pretty ambitious, perhaps for us, but also for users.
2) I am a believer in encouraging users to look at data before doing ambitious steps.  So, once imported, then perhaps the names of the sheets need to be changed.  And perhaps some are not quite as identical as we thought.
So I am quite happy that this remains a 2-step process.

**Comment by rdstern** [comment]
There are 3 or our modern buttons at the top.  Perhaps a label first, on the left **One column per:**.  Then the first button says **Year**, the second says **Month (1 to 12)**, and the third says **Day (1 to 31)**.

Then there is our usual data selector on the left.

On the right, start with the second and third options.  

The second option is one column per month.  So there will be 12 monthly columns and they are always (in examples I have seen) Jan to Dec in that order.
There also needs to be a Station column.
And there is always a column showing the Day of Month (1...31)
So the right-hand side can (like many of our dialogues):
a) First field is Station.  (There may be just one station, so this doesn't have to be filled for OK to be enabled)
b) Second field is Year.  This must be filled.
c) Then Months.  This is a multiple receiver.  There might even be a check that it has 12 months?
d) Then Day of Month.  This is a single receiver.

For the 3rd option it is just the same except that Month is a single receiver and Day of Month is multiple.
There needs to be 31 variables in this receiver.

For the first option it is the Year that is the multiple receiver.  A complication is that data sets may not have variables for Month and Day-of Month.  I suggest there be a Day of Year field, but that is optional.  If left blank then we can generate a column that goes from 1 to 366.  
There could be a tooltip that says "Days are assumed to be from January 1 to December 31 - 366 days.  There could also be a check that the data frame has 366 rows.

(This also would not usually have data for multiple stations.  This is because appending them will only be simple if the years are the same.  So this is an example where we may later want to be able to take the Station information from multiple files.  I suggest that is for later.  Let's get it working in a simple way first.
The second complication is how we find the years in this format.  The columns may be named X1, X2, etc, or X1935, X1936.  If labelled X1, X2, then we have to supply the earliest year in the dialogue and also assume the years continue with none missing.  If taken from the names, then there could be missing years.
Then we just need a field for the new Data frame name, which should relate to the existing one.  The user can always change it.

I think that's all we need.  The dialogue will be quite simple.  The code behind may not be?  It will do:
a) Stack (melt) columns carrying whatever else is needed, Station, Year, Month, (if Station included), etc.
b) For the 2nd and 3rd options the resulting factor column (once stacked) could perhaps be made numeric?  This should then have the values 1 to 12 or 1 to 31.
c) Then can generate a date column.
d) Now have to eliminate all dates that are NA.  They correspond to non-existent dates like 31 June.  Interactively I do this with a filter, but it could also be sorted on the date column.  Then  I assume the NA are either a block at the top or the bottom.  They need to be eliminated.
e) Then (finally) sort of Station and Date - assuming multiple stations.  If only I station this isn't needed.

It is slightly different for the first option where we may need to generate the Year column from the factor labels.  Then get the date from the Year column and the doy column.

I suggest getting this to work should be relatively easy.  Perhaps Beth could do the R part, or I could even ask Sam?  It would be good if it could be a function?

Then (once a basic version is working it would be good to add some error trapping.  This could be for oddities in the columns (e.g. some non-numeric values), or duplicate days, etc.

**Comment by maxwellfundi** [comment]
I suggest @muthenya  could start designing this dialog.

**Comment by dannyparsons** [comment]
I think this sounds good. I'm happy with the decision to have the importing into R-Instat as a separate step.

I would though like to consider how this will look/work for multiple data frames - particularly for option 3. I don't mind if we decide it's too complicated for now but I also don't want to have to redo large parts of the dialog and R code when we want to do the multiple data frames extension, otherwise we've wasted some time doing it for just this case.

One thought I had is a sub dialog where you can choose additional data frames. The main dialog stays the same and you select columns for one data frame. If multiple data frames are selected, it will assume it has the same columns as chosen for the first. If not, it doesn't work.

I don't think this is ideal so would be happy to hear a better suggestion!

**Comment by rdstern** [comment]
I think by your option 3 above you mean my Option 1, i.e. where the Year is the original column, that's the importing from the old Instat.  And that's where it is a bit more complicated if the different data frames are for different sets of years?

The main use of this layout is for data coming from the old Instat.  I am assuming that we do not want to go to the trouble of being able to read and old Instat file internally - Genstat can do this.  Instead we would encourage userts to export to Excel (old Version, i.e. xls) and then probably look at the data there before importing into R-Instat.

Overall I like this idea of being able to use multiple data frames in this dialogue.  It could be that you complete the information for the first data frame and then have another control (or button to a sub-dialogue) for "More Stations".

It then depends how general you want to get.  I am thinking that the main use of multiple files is likely to be for my Option 1 above (Old Instat layout with one year per variable).  For the defaults in the other layouts it would then simply do the Append first and then continue as before (if Append has worked OK).

If we get ambitious, then there are other possibilities, particularly when we can import multiple sheets from Excel.  I have seen a few examples where a year of data (layout of 1 column per month) - my Option 2 above, has a year in each Excel sheet.   

I have not seen examples where my option 3 - one day per day of month, i.e. 31 variables, with the month as a record is divided up for different years.  Usually that is a large file, and sometimes with multiple elements, so there is a different issue, namely (at the end) doing an unstack for the elements.

**Comment by rdstern** [comment]
Usually (from the old Instat) the columns are named with the year included.  That's partly because there is the facility to name a sequence of years in the name dialogue.
If not, i.e. if they are x3, x4, then the name of the file usually says the first year and they are consecutive.  Otherwise it was too complicated in the old Instat.

So my solution is simpler, i.e. either diagnose the years from the name - in which case there can be missing years in the sequence - or give the first year and ignore the names, but assume they are consecutive.  If it is anything more complicated, then the user has to do something earlier than this dialogue.  It could be that the names are made clearer in Excel, or we might (later) improve our rename dialogue to also allow a sequence.  I don't think we need anything more in this dialogue.

**Comment by rdstern** [comment]
I also found the source of one of my problems in the Haiti data, which was duplicate days.  This was just once, and I have now found that the problem was that 1988 Dec was twice, and 1987 Dec was absent.  In addition in the data the first 1988 Dec was in the position for the absent 1987 Dec.  So a check of data not in the correct order (within a station) would have found this problem.  Or a check of duplicate values.  

(I would be quite happy if the reorganizing of the data only worked with the data in order, (within a station) because if it is not, then it is probably a problem with the data.  But, at least initially, I am not sure it need be the work of this dialogue.  If we can make the reorganizing easy, then I would like to promote the checking for duplicates, etc as part of a routine.

**Comment by Muthenya** [comment]
@rdstern this what I have come up with for the design of the new dialog. This is for the first option. The other two are beneath it.

![image](https://user-images.githubusercontent.com/32125033/41234169-210462dc-6d94-11e8-835f-f6a44e345d22.png)

**Comment by dannyparsons** [comment]
I would put the "One column per:" label either to the left of the buttons or on top in centre. It also might make sense for these to be normal radio buttons because of the label, but I'm not sure, but worth having a look at that. Or another idea, put the "One column per:" in the label for each radio button and have the text over two lines with "One column per:" as the first line for each.

Are you going to have three sets of controls, each with a group box? That might mean some duplicate receivers like Station but it's probably easiest, otherwise there's a lot of re-positioning of controls.

**Comment by rdstern** [comment]
Looks good:  Let's make **One Column Per** into **Layout:**  There will then be space alongside the buttons.  Then make the first button **Year Columns**, the second and third add **s**, so **Months (1 to 12)** and Days (1 to 31).

**Comment by rdstern** [comment]
Here are some data files:
1. One column per month: 
[Pluviometrie Moustique.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2090462/Pluviometrie.Moustique.xlsx)

2. One column per day-of month.  Ignore the last 3 columns.  This also has an error where there is no Dec 1987 in one station, but Dec 1988 is duplicated.  When you see the problem it is easy to correct in Excel.  I don't think it causes a problem with the reshaping, so let's keep the error there for now.


[Petion_Perrin.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2090535/Petion_Perrin.xlsx)

3. Year in a column.  Here I would initially just allow for the case where the years are given as Y1983, etc

[Climatic_guide_datasets.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2090563/Climatic_guide_datasets.xlsx)
In this file the sheets with Kabete, Katumani, Kurunega, samaru56 are to try.

**Comment by Muthenya** [comment]
I agree with @dannyparsons. I think having the **One Column per:** within each radio button seems okay.
Then @rdstern just for clarification, I guess you mean replacing **One Column per:** with **Layout:**? If so, should I go ahead with the suggestion of having the **Layout:** within the name of each radio button?

**Comment by dannyparsons** [comment]
Roger's suggestion also makes sense. I just think radio buttons as boxes should be self contained without a label because they should just be like yes/no on/off buttons

**Comment by Muthenya** [comment]
I agree. I just want it to be clear on how buttons should be.

**Comment by rdstern** [comment]
Sam has done the function - attached.  He writes:
See attached  -hopefully the documentation makes sense but let me know if not or if you find any bugs.

Any data quality checks should be separate functions so I am ignoring the problems with the data in example number 3. I’m also assuming that sensible month and day columns are going to be added to the data before any reshaping in example 1.

Sam

[examples with data.zip](https://github.com/africanmathsinitiative/R-Instat/files/2097136/examples.with.data.zip)

(When in use, we will have to include adding two columns -in the code - for the case of one column by year.  That's for the month and day of month.  They will rarely be included.  But let's get it working first - as it is.)

**Comment by rdstern** [comment]
In the climatic menu I wonder if there should be a **Climatic > Reshape and Examine** item, which is just before the Climatic > Dates and in the prepare section, so it is at the top of that group.  It has 3 items

1) **Reshape**, which is the dialogue above
2) A copy (for now) of the **Describe > One Variable > Summarise** dialogue.  Later there could be the radio buttons at the top.  The first is Overall and this is the One Variable.  The second is By Station,  and this gives a 2-variable summary for each station.  We need our Describe > Two Variable stuff to be working better before that option is included.
3) A copy of the **Prepare > Data Frame > Replace Values** dialogue.  This is then used to replace (say) -9999 by missing, etc.

**Comment by rdstern** [comment]
Lazarus starting with the second and third options now, because the first option needs to work with year and day of year.
There may then be issues when the Station is not included but there are multiple stations.  Let's check what happens!  Also if the years are not unique and also if the data contains multiple elements.  Or if there are problems with (say) character variables in some of the columns.

But let's get it working for some simple cases and then try to cope with complications.

So we check OK when the fields are completed, ignoring Station, because we may have only a single station.

**Comment by Muthenya** [comment]
I've been working on the dialog and have been having an issue with the multiple receivers. I find that having two single receivers for both the **first** and **last** arguments of the R Function to work better (or easier) as compared to the multiple receiver for each option. 

This is what I propose;
![image](https://user-images.githubusercontent.com/32125033/42035080-b6bab9e4-7aea-11e8-84b9-14f650d20e7a.png)

**Comment by Muthenya** [comment]
Okay. The issue is with the way the multiple receiver handles the variables i.e **first** and **last** variables. It concatenates the variables and treats them as one.

**Comment by rdstern** [comment]
In the discussions above we have suggested a separate sub-menu for this dialogue, plus others that are taken from the Prepare and Describe menus.

I would now like to add another dialogue from the Prepare menu that has just been done, (though there will be changes).  I believe Lazarus already has a copy of the original new sub-menu in his branch?

It is in #4766 Non-numeric Cases.

The order could usefully change to become:

1) **Reshape Data** (Don't need Climatic in the menu item, because it is the Climatic menu.  Keep Reshape Climatic Data as the heading in the dialogue.)
2) **Non-numeric Cases**
3)  **Replace Values**
4) Horizontal line
5) One Variable Summarize

I suggest the new menu could be added soon, even if the Reshape Data item is disabled to start with.

In the climatic menu there is another new item that Shadrack is working on - Length of the season.  There is one further new item to add - perhaps at the same time.

This is a simple Compare Dialogue see #4745.  It will go in Climatic > prepare and just under Transform (and above the horizontal line).  It is called **Compare**.

**Comment by rdstern** [comment]
I hope some use of the dialogue can be completed first.  Then there are 2 extensions, at least to the function that Sam has created.

a) It will (usually) work for just the 2nd (Months, and third (days) tab.
b) For the years there is sometimes a column of length 366, but it could be simplest to produce one.  I think Sam's function currently assumes a Month and day-of-month function.  So this could be an extension to that function.
c) For the third option there will sometimes be an extra variable giving the Element.  It will usually be numeric with 5 being rain, 2 and 3 being max and min temperature etc.  That would be another field in the dialogue for that option.  It isn't impossible for the second option, (months) but not sensible for the first option - years.
d) In the first option (years) it is possible that some datasets will start in a month other than January.  I am not interested in importing them, but it could be good - later - if we cou7ld detect the problem and report.  The feature of the data sets is that there is a special code for February 29th.  This is line 60 when data start on 1st January.  If it is elsewhere, then we report.  To help with the check we may want to ask for this number in the dialogue - it might be optional to give it.

**Comment by dannyparsons** [comment]
Having re-read Hadley Wickham's [tidy data paper](http://vita.had.co.nz/papers/tidy-data.pdf) I think what this dialog is doing is making the data *tidy* according to his definition:

> In tidy data:
> 1. Each variable forms a column.
> 2. Each observation forms a row.
> 3. Each type of observational unit forms a table.

Both 1 and 2 are not true of the data before using the dialog and are true after, and this is only data at one level (daily) so 3 is true.

So I'm suggesting renaming this dialog **Tidy Climatic Data** and the menu could be **Tidy and Examine**? I think it would be good to have this language in R-Instat as it's an important concept and relates to general statistics education. It fits as part of prepare as tidying is just one step in data preparation and there's more data checking and transformation to do after the data is *tidy* which is important for people to know.

**Comment by rdstern** [comment]
I like that!  There is going to be a lot of capacity building on the climatic work, and great to be able to relate to general ideas.  So I support those changes of name.

**Comment by dannyparsons** [comment]
Great, when I hand it back to @Muthenya he can rename these.

**Comment by dannyparsons** [comment]
And in case you need any more convincing table 11 in the paper is exactly one of the wide climatic formats for the dialog! And is described as the most complicated form of messy data because it is also multiple elements.

**Comment by rdstern** [comment]
Three small points so far:
a) In the menu it is called Tidy Data.  In the dialogue it is Tidy Climatic Data.  I would prefer we call it Tidy Daily Data in each case.
b) The default is for Ignore Values on Invalid Dates to be unticked.  Unless you prefer to leave it that way, then I'd prefer the default be to have it ticked.
c) I tried with a nice set from the old Instat - great.  Perfect.
d) then I tried with the data from Malawi with the 3 columns that were character columns.  It correctly gave an error, but I wasn't sure if it trapped the error, or just had left it and it was from the stack not liking different types of column.  (I was using it from VB and it threw me out, but it does that lots anyway.)

**Comment by dannyparsons** [comment]
a) I hope @Muthenya can do this
b) I prefer it unticked so it forces people to decide to ignore them - just thinking that if you have these values you should at least know they are OK to ignore before continuing
d) It should trap that correctly and give a sensible message - it shouldn't get to the point of trying to stack. Can you try again and send me the data if its still an issue?

**Comment by dannyparsons** [comment]
Now one more addition to make element and station receivers available for the Years option. This needs edits to the dialog + R code.

**Comment by Muthenya** [comment]
@dannyparsons have you been able to go through the R Code?

**Comment by Muthenya** [comment]
Okay.

**Comment by Muthenya** [comment]
Should this be closed? Or is it going to remain open because of the improvements (checks) to the Year option?

**Comment by dannyparsons** [comment]
I think we can close and open separate issues for improvements.
