### ISSUE TITLE
Combine Factors - new options

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4662]
There are two parameters to `interaction` which we don't have on the dialog. I think they should be included:

- `sep` the separator, default `"."` - a combo box
- `lex.order` determines order of levels of new factor, default `FALSE` - a checkbox

**Comment by Muthenya** [comment]
@dannyparsons I've already began work on this. I just need some clarification on the separator,. I've already set the default. Which separators are required so that I can set them up? Or should I leave it open for the user to insert based on their need/preference?

**Comment by dannyparsons** [comment]
Let's have a combobox with common separators like `-` `.` `[space]` and editable so they can type their own. It can have the same items as separator option in text dialogs.

**Comment by Muthenya** [comment]
Okay. Thanks.
