### ISSUE TITLE
Start of rains error message

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4663]
When doing the start of the rains:
a) OK is enabled immediately, i.e..before I have ticked any option for the start.  I think that perhaps the first checkbox could be checked by default, and then this would be fine.  
b) With the data given in #4661 I get the following error message.  However it does appear to be working in that it produces the results and they seem to be correct.

**Error running R command(s)
Error in self$get_columns_from_data(col_names, use_current_filter = FALSE) : 
  Not all column names were found in data
The error occurred in attempting to run the following R command(s):
InstatDataObject$add_key(data_name="Petion_Perrin_stacked_subset1_by_STATION_year", col_name=c("Date1", "STATION"))
OK**

**Comment by shadrackkibet** [comment]
I am going to fix this issues.

In b) above, this is happening because of wrong the wrong dataframe on `add_key` function. This is because you had `Petion_Perrin_stacked_subset1_by_STATION_year` dataframe and now when you switched to the original dataframe this was not updated.

**Comment by dannyparsons** [comment]
Ah ok, this is probably the issue here too #4665

**Comment by shadrackkibet** [comment]
I have noticed that in this dataset there are 62 rows of duplicates. So this is part of the problem when creating a key.
![image](https://user-images.githubusercontent.com/26301973/41153719-4303f0e4-6b20-11e8-91aa-826badd64661.png)

**Comment by rdstern** [comment]
Thanks.  That's all in one month.  Very annoying in a way, but great that we are getting these problems now.  It will not be the only time we hit this.
