### ISSUE TITLE
Spell Lengths error message

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4665]
I went on to the spells dialogue - same data from Haiti as the start of the rains problem.

1. Simple use of the dialogue gives me this message;

**Error running R command(s)
Error in self$get_data_objects(data_name)$add_key(col_names, key_name) : 
  key columns must have unique combinations
The error occurred in attempting to run the following R command(s):
InstatDataObject$add_key(data_name="Petion_Perrin_stacked_subset1", col_names=c("Date1", "STATION"))
OK**   

But it seems to give me the result anyway.

2. Please could you check on what happens with missing values?  I would like it to give the result as missing if there is a missing value in the range.  I think it doesn't do that yet?

3. I now went back and did a conditional spell length.  That gave me another error message.  Then it produced a column, but it was all zero.

**Comment by dannyparsons** [comment]
I am not sure why the dialog is trying to add a key from this dialog, however the error creating the key is telling you that "Date1" and "STATION" do not have unique combinations, so this may be one part of a problem.

This doesn't sound like the only problem here though!

**Comment by dannyparsons** [comment]
Ok from what @shadrackkibet said here #4663 this is an issue with the dialog not the unique combinations

**Comment by rdstern** [comment]
Aha, you are right they are not unique combinations.  
Now this is 2 key mistakes I made in this workshop:
1) I got the data in the wrong order with the date column, because of the language issue.
2) I didn't check that the Station by Date should be unique for our climatic analyses.  At least I think so.  Am I right that it doesn't make much sens to continue with these analyses if not.

I am really pleased that I didn't discover the second issue within the workshop, because it takes a bit of time to fix and that would have been a real problem on day 2 of a 2-day workshop!  But it would be good to have this check somewhere?  Perhaps in a few places, but at least in the Define Climatic Data?

This could be "Behind the Scenes" , but it might be better if it were visible, e.g. Have the same check as in the set key dialogue.  It could be the same checkbox as there, with a tooltip to say "Dates should not be duplicated at the same station".  As with the set key dialogue, OK is not enabled unless this comes green!

**Comment by dannyparsons** [comment]
I think this check should be on the Define dialog and the dialog should also add the key so that no other dialogs need to do it. And if they are not unique I think it messes up other analysis so you shouldn't be able to define until that's resolved.
