### ISSUE TITLE
Duplicates dialogue small bug on 3rd option

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4677]
If I am right, then this should be an easy one to fix.  

The 3rd option on the Prepare > Check Data > Duplicates calls a Sam-written function to give the index number of the duplicates.  I tried it on the attached data set and it gave some duplicates, but not all.  I think it is only giving the duplicate index when the whole record is duplicated - which is fine if I was using that option.  But I wanted the duplicate rows for just 2 of the variables, i.e. Date and Station. 

![image](https://user-images.githubusercontent.com/11226469/41242059-806708d6-6d96-11e8-882d-362011b0d459.png)

[Petion_Perrin_All.zip](https://github.com/africanmathsinitiative/R-Instat/files/2090699/Petion_Perrin_All.zip)

The sheet used is Petion_Perrin_stacked_Subset1

**Comment by Patowhiz** [comment]
@Muthenya This is not part of the problem that @rdstern is facing above but I think it will be nice to look at. When I do a filter of say, Date column, then I try checking for duplicates on the filtered data frame, say for station column, I get the shown error. Is this expected?

![duplicates](https://user-images.githubusercontent.com/21179007/42947008-00227c62-8b75-11e8-8bb1-4890b35eec10.JPG)

**Comment by shadrackkibet** [comment]
@Muthenya  you need to set the current filter to false on initialise.

**Comment by Patowhiz** [comment]
@rdstern @Muthenya  would it not be much more desirable if the non duplicates are given value 0 when it comes to Index Number of Duplicates. especially when index is the option selected. I find it inconvenient to have index 1 even for non duplicate, yet the interpretation I think would be where there is an index there is a duplicate and it goes on increasing. i.e 0 - not indexed, 1 - first duplicate occurrence, 2-Second duplicate occurrence... Probably I'm misinterpreting the intention?

**Comment by rdstern** [comment]
Let me see if I understand Patrick's suggestion.

Take a single column which is:
4 5 5 6 7 8 8 8 8 9
I think the current function gives
1 1 2 1 1 1 2 3 4 1

While Patrick would prefer:
0 1 2 0 0 1 2 3 4 1

Am I correct?  If so, then it is just a (simple?) change in the function.  I would be quite happy with that change.  The existing function gives the main things I needed, namely how many repititions, etc.

But the changed function would give everything, plus a bit more, with the zeros.  So happy with the change if any of you can make this change quickly.  If not, then I would ask Sam, who would - I am sure be able to do it in 10 minutes or less.  I'll time him if you like?!

**Comment by Patowhiz** [comment]
> While Patrick would prefer:
> 0 1 2 0 0 1 2 3 4 0
@rdstern yes! 
@Muthenya and I can have a look at the function quickly then get back to you.

**Comment by Muthenya** [comment]
We can do that. Though, I propose if the current issue is resolved it can be merged as the other issues are looked into it.

**Comment by Patowhiz** [comment]
Sounds good.

**Comment by dannyparsons** [comment]
I think the initial implementation is fine as it's giving the number of occurrences so starting at 1 makes sense to me.
