### ISSUE TITLE
Small problem with Unstack

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4679]
I go into R-Instat and (without loading any data) thev first thing I did was to load "your" unstack dialogue, to see if the missing control was now back.

Before the dialogue  loads I get:

**instat
This name cannot start with _
OK**   

Then it seems to load OK.

The second time I go back to the dialogue I don't get this message.  It's just the very first time!

**Comment by dannyparsons** [comment]
This is setting the assignment using the data frame name (which is blank) so you get an invalid name. @Muthenya if you check that the data frame is not blank this will fix this
