### ISSUE TITLE
New dialog for paste?

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4680]
Should we have a dialog which takes a list of columns and pastes them together? The command would be:

`paste(Site, Village, ID, sep = ".")`

This is useful for making unique IDs and not so easy in the calculator, so I think enough to have its own dialog (is `paste` in the calculator??)

I considered whether this is needed because its similar to Combine Factors dialog but I think it's different because:

- Input and output of Combine Factors is factor, whereas paste can have any column as input and outputs character.
- Different concept - Combine Factors uses `interaction` and is doing combinations of the values to create levels, whereas paste just puts values together as strings

Any thoughts?

**Comment by dannyparsons** [comment]
Yes should definitely be in the calculator either way, probably under Strings, although it is general for any column

**Comment by shadrackkibet** [comment]
How is this different from what **combine text column** dialog do?

**Comment by dannyparsons** [comment]
Good point, that is what I wanted so we don't need this new dialog. Then for the calculator do we have paste or str_c in there yet?

**Comment by shadrackkibet** [comment]
Yes we have `str_c` (combine button) on strings keyboard.

**Comment by dannyparsons** [comment]
Ok great, then I don't think we really need paste as well.
