### ISSUE TITLE
Small issue in Make Date

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4702]
In make date with 2 columns, Year and doy(366), I expect day 60 in non-leap years to be NA, i.e. 29 February which doesn't exist.  Instead it repeats 1st March - so 1 March is there twice.

**Comment by bethanclarke** [comment]
There is a bigger issue with make date year and day (366) - the month doesn't change and is always January. I am looking into this

**Comment by shadrackkibet** [comment]
I claim to have addressed the problem reported by @rdstern . However i can't find the second issue reported by @bethanclarke .  Seems to be working fine for me. i.e months are changing.

**Comment by dannyparsons** [comment]
I think we solved Beth's issue caused by using the wrong column, but Beth can confirm if not.
