### ISSUE TITLE
Add back autotransate(Me)

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4706]
I have been working on translations and believe I have resolved the issues which required us to comment out the `autotranslate(Me)` line in some dialogs. Translation is still disabled but I would like to try it in the next version. Could someone find all the commented `autotranslate(Me)` lines and add them back in?
@africanmathsinitiative/developers

**Comment by Muthenya** [comment]
Okay. Let me get right on it.
