### ISSUE TITLE
Changing from text to numeric

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4709]
With the climatic data we often have columns of rainfall and temperature data that appear as character columns.

This is sometimes because there are genuine non-numeric values in the column.  Sometimes it is because some numbers in Excel are stored as text.

I am sure the main issue here is also elsewhere, but I can't find it.

a) I would like to filter to select all non-numeric rows in a column?
b) But the main thing I would like to be able to do is transform to numeric.  This is possible through the calculator, using as.numeric(as.character(column)).  But using right-click usually gives a mess, because this is automatically a labelled column.  And I could not find any options from the Convert dialogue that does any better.

I would really like to resolve this conversion issue quickly.  It messed me up in Haiti and now again in this Malawi workshop.

**Comment by dannyparsons** [comment]
We can have the option to convert to numeric "normally" but this is dangerous when you have some non numeric entries.

**Comment by rdstern** [comment]
I have now had a useful, but not very satisfactory discussion with David and Danny on the reasons for the current situation.  Their context (I think in agriculture) is that the "master" data file is in Excel and hence problems such as we had above should be solved in Excel and then the data re-imported.

My context in the climatology (at least in Malawi) was different.  the data in Excel was specially prepared for this workshop to illustrate how data from 3 stations (and multiple elements) could be analysed using R-Instat.  So it was not a master file in any way.  The preparation was into the old Instat format, making it difficult to make corrections, and also importing was easy, but there are then many steps to get the data into the right "shape" for R-Instat.

So, in this context, we need to be able to make corrections and proceed in R-Instat.  We need that as an option.  In other situations you preach options by context.  I need the option here of being able to edit and correct the data within R-Instat.

This will continue today with the QC in R-Instat.  they have already noticed one day with tmin = 140 degrees and others with tmin or tmax as zero.  I repeat that in this context it is impractical to simply go back to Excel to make these corrections.  The shape of the data in Excel is very different to that needed in R-Instat.  We have exported the data back to Excel (csv file) in the R-Instat shape, but that is now yet another copy of the data.

More generally, in our context, this emphasizes the importance of having the master copy, presumably in CLIMSOFT.  But then we DO need a system of correcting the data in CLIMSOFT.

**Comment by rdstern** [comment]
Even more disturbing with the current situation is that the labels change and this can really mess up the data.  That is one reason it is urgent to make changes
[MZIMBA1.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2117792/MZIMBA1.xlsx)
In this attached file, in the sheet MaxTemp there are 3 columns with problems, namely 2002, 2009 and 2015.
In 2002 all values are numeric, but Excel has 3 of them formatted as text.  (Use the filter in Excel with that column to see that.  In 2009 there is an S on one day and in 2015 one day has the value ".32.4", i.e. has an extra decimal.
So, for example 2015 now comes into R-Instat as text (type c).  But you don't see the labels until you try to convert to numeric.  Now it looks crazy as a set of numbers, but the labels have the .32.4 as the first, so you see it.
I copied 2015 into a duplicate column so I could monitor changes.  I then made it into a factor and it looked OK.  then I made it numeric again - still didn't correct the text value, and back to a factor.  I now found (from the levels/labels dialogue) that a few lavels now had zero frequency.  It had changed a few of the days.  For example on day 339 it had changed 20 to 24.4.  On line 12 23 has become 24.7.  On line 166 24 has become 24.8.  On line 202 the same.

I then corrected the text value into a new column and that became numeric OK - but (of course) with these wrong values.  Now I went from character to factor repeatedly and it went all wrong.  See x2015 below, which is the original compared with x2015a which I have converted a few times.  This is highly dangerous, because the values are all believable - but wrong!
![image](https://user-images.githubusercontent.com/11226469/41636831-ffb1b38c-7450-11e8-83b3-72f2f06f0f36.png)

We can't have software out there that messes up data like this.

**Comment by rdstern** [comment]
I have now some more suggestions on what we could do with the sort of problems above.

I am keen that we can detect and, if necessary, correct non-numeric values within R-Instat, rather than having to go back to Excel.  Here is what is possible now, and I would like discussion on how to make this facility easier to use.

First I note the problems in 2 of the 3 columns above:
a) In column X2002 some values are thought to be numeric, because they are stored as text in Excel.  In fact they contain only numbers and hence the column transforms to numeric OK.
b) In X2009 there is a single non-numeric value, i.e. an S.
c) In X2015 there is a single non-numeric value and this is .32.4 - so an extra . at the front.  That's a bit more awkward - for me at least!

In the calculator, i.e. Prepare > Column: Calculate > Calculation, if I type:
grepl("[^0-9.]",X2009), 
then the resulting column is FALSE except for the S.  So I can filter on the logical column and find the single row.
When I do this for 2002 there are no rows - so I know it is all numeric - well sort of.

Unfortunately my simple expression above does not work for the issue in 2015.  That's because it does not have a problem with multiple decimal points - though the row is non-numeric.

But this is approaching a partial solution.  We could have grepl in our string keyboard (or logical keyboard) and a particular use would be to detect non-numeric values.  Then we can filter.  It would be good if we could combine these ideas and use the filter directly to detect non-numeric values.

This is a good entry on the [subject](https://stackoverflow.com/questions/35573184/checking-all-non-numerical-entries-in-a-data-frame-column-and-delete-or-substitu).

This isn't yet a suggestion for action, but having something in Prepare > Check Data and/or in the calculator and/or in the filter is the way to go.

**Comment by rdstern** [comment]
Happy with all you are adding.  But I would also like to be able to take a character column and filter to all the character (i.e. non-numeric) rows in that column, so I can look and then possibly change those values.  That's what we would do in Excel.  I'd like to make it easy to do that in R-Instat.

**Comment by dannyparsons** [comment]
That's what I would see 1. would do. You could either get a print out, or a logical column, or a filter.... we could have different options on how to show the non numeric cases.

**Comment by rdstern** [comment]
I hope some improvements can be for Version 4.20, which is the current milestone.  But there are different aspects to sorting out the labelled columns, to being able to transform and to be able to edit non-numeric values in an otherwise numeric variable.

I see a full solution as consistent with Version 0.5 and this might even become a topic that moves Version 0.5 back to September, i.e. the current 0.5.1 milestone.

In selecting non-numeric values Danny's code is simply: is.na(x) == is.na(as.numeric(x)).  This then needs an ifelse so the NAs are not included.  If that is a function it can go into the calculator and perhaps into the (new?) filter system.

Other places are in **Prepare > Check Data** and **Prepare > Column: Text**.  And perhaps somewhere in the new Climatic menu.  Let's see.

**Comment by rdstern** [comment]
That's great!  Sounds excellent.
