### ISSUE TITLE
Date picker control doesn't allow for shifted year

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4714]
Tomorrow in Malawi we need the shifted year and shifted doy. 

In the climatic commands, e.g. start of the rains there is a date picker.  If the shifted day of year is used (I started 1 August, this is totally ignored currently by the date picker.  For example I wanted to choose 1 Nov as the earliest day which is day 93 (from 1 August).  I am going to have to give it as 2nd April, which is day 93 from 1 Jan.  Then the dates of the start of the rains seems to work OK.

I don't know if this is a simple adjustment to make, or is quite complicated.

I would like to make this a 4.19 milestone, but realise that might be ambitious.

**Comment by dannyparsons** [comment]
It is not too difficult but just needs careful attention to get right. It would need the shifted start day to be stored in the metadata, but that's easy, and then to read that when setting up the control.

**Comment by rdstern** [comment]
OK, this means that now it is harder for the shifted year than when we typed the day numbers in directly.
As a temporary fix, in version 4.19, could we allow users to type into the formula.  

Otherwise we have to know the number of days (anyway from say 1 August) and then work out the date , e.g. 2 April if this all started from 1 January!  That's contorted!

**Comment by rdstern** [comment]
While this is done, a minor edit is to swap the the order of the day and the month.  Currently the day is first, which is logical in thinking of the day then month, but confusing in this entry.  If the month is first, then it is easier to then adjust the day.  So these should be swapped round.
