### ISSUE TITLE
Should Save and Save As leads to same dialog?

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#4743]
While in Malawi, the participants raised the issue of - 

- When you go to File> Save As and when you click on the Save shortcut on the tool bar they both lead to the Save as dialog. 

-what was desired here was, when you click on the save on the toolsbar, then that should only bring up a warning saying, you will be overwriting the existing data file and not lead to save as dialog.

**Comment by dannyparsons** [comment]
The first time you click Save it goes to Save As because you need to choose how you are saving the first time. After that Save saves to the same location and Save As can save to a different location.

That is the reasoning for the current implementation. Happy to discuss changes to this.

**Comment by Muthenya** [comment]
> The first time you click Save it goes to Save As because you need to choose how you are saving the first time. After that Save saves to the same location and Save As can save to a different location.

I feel this is sensible enough. Are there still discussions on this?

**Comment by dannyparsons** [comment]
If there's further comments we can reopen but I'll close it now.
