### ISSUE TITLE
New climatic dialogue for length of season?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4744]
I propose an additional (simple) dialogue to find the length of the season.

If agreed, then it will go just under the dialogue to calculate the End of the Rains.

It is a very simple dialogue which (unlike the others in this menu) uses the summary data that has been produced on the start and end of the season.

It is (essentially) just the calculation of the End minus the Start.  It is currently done with the Prepare > Column: Calculate > Calculations.  The reason I am suggesting a dialogue is also to cope with the information in the logical columns (for the start and end) at the same time.

It will produce a column of lengths, plus a factor column.  The factor column has 4 levels (plus NA).

The dialogue has our usual selector and 4 receivers.  They Are labelled Start, Start(L), End, End(L).  The Start and End columns are needed for the command.  They may be numeric or dates. The others may be optional - they are restricted to logical columns.

Underneath are the 2 columns to be saved, called Length and Type.

If the Start and End are numeric, then the Length is simply (End - Start).  If Length is <=0 it is set to missing and the Type column is set to be "Not Positive".

The Type column had 4 levels, namely Normal, Not Positive, No Start and No End.  It is also NA when there are missing values.

This may need Beth's help in the R code, for the logical columns.

I also welcome confirmation from Maxwell, David and Danny on the value of this new dialogue.

**Comment by rdstern** [comment]
Reply by Danny:

This seems sensible, and not too difficult as it's just a calculation at the same level. I think I understand the cases for your 4 levels but this might need to be made clear for whoever writes the R code/dialog.

Two thoughts:

What happens if both start and end are missing? Is that "No start"?

It feels like it shouldn't have to be 3 steps to get to this point. We should still have this dialog when you want to do it like this, but couldn't this also be an option in the end of rains dialog? If you enter the start information it calculates the length at the same time.
This is quite a bit more complicated than making the new dialog so it could be for later but this seems like something we should be aiming towards?

**Comment by rdstern** [comment]
Initially to keep this dialogue simple I suggest the structure of the dialogue as above.
But the two columns to be produced are first (as above) the length, i.e. just end minus start.
The second column is (like the start and end) a logical column, just to distinguish between missing data and no length.  So it is (like the start and end) called Occurrence and has the same checkbox.  If either the start or the end are FALSE then this is FALSE.  If either are NA, then this is NA.  So it is only true if both the Start and End are TRUE.

If the length is FALSE then we would have to look back at the earlier columns if we wanted to understand why.  But the main information is there is no length.

**Comment by shadrackkibet** [comment]
Working on this.

**Comment by shadrackkibet** [comment]
What if start and end are both FALSE?
