### ISSUE TITLE
Adding a Compare dialogue including anomalies

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4745]
In the recent Riga workshop we compared satellite and Station data.  This was done using the standard calculator and was then used in reports.

It was suggested that this would make a good additional dialogue.  However, as far as I remember, there were just 2 initial calculations, namely:

Bias = (yi-oi)
Absolute Deviation - |yi-oi|

where y is the satellite value and o is the observed (station) value.

Then we get the mean, and standard deviation of these differences, etc.  Of course we can get the mean and standard devaition just for each station or each station and each month, etc.  That uses our standard Reshape > Summary  dialogue.

I am not convinced that we need a whole now dialogue for this.  We already have the Climatic > Prepare > Transform dialogue that produces additional columns and I suggest these 2 functions could (at least for Pretoria) be an additional Compare button on this dialogue.  

Instead of Element it would have 2 fields, Satellite Element and then Station Element.

There are 2 columns saved.  The first could be Called Bias and the Second Absolute Deviation.  The 2 proposed column names could be bias and absdev, or possibly bias1 and absdev1 if we want successive uses to add to the the index.  

Danny, is anything more needed?

**Comment by dannyparsons** [comment]
I thought there was then two further step
1. calculate the mean of these columns within station
2. bias - mean bias and ad - mean ad

Not sure if it was exactly that but there was something where we needed the mean at the same level to do a further calculation. That's where I think it then requires its own dialog because these steps are not so simple. I also like a new dialog so that we could display some output to the output window which is the same information required for CM SAF validation.

**Comment by rdstern** [comment]
I initially thought that, but then felt that calculating the mean difference and the standard deviations is so easy (and also flexible) with the Reshape > Summary Statistics dialogue, e.g. calculations also by month, that I wondered?  They are also not mutually exclusive, i.e. like the water balance and end of the rains, we could put them there and still have another dialogue that goes to the station level.

**Comment by Muthenya** [comment]
@rdstern I'm not really certain about the designer. Could you please elaborate.

**Comment by rdstern** [comment]
Here is my first go at adding some summary statistics.  (This needs to be critiqued by Danny and then will need his guidance on implementation.)
There is a group box with the heading **Summaries**.  There are then 4 radio buttons in the left hand half of this group box: **Overall, Station, Station & Season, Station & Year**.  These are the factors (or are made into factors.  Then (on the right of these there could (perhaps) simply be the same **Summaries** button as on the main **Prepare > Column: Reshape > Column Summaries** dialogue.  Here it is set initially to Mean and Standard Deviation, so if you do nothing, then those are the summaries you get.  You get them for the bias and the absolute deviation columns, by default.  Then you can also opt for any other summaries if you wish.  Below this are the same 3 check boxes as in the overall Summary dialogue, namely Store Results, Print Results to Output, and Omit Missing Values.  Here initially the Print results and Omit Missing values are ticked.

**Comment by rdstern** [comment]
The compare dialogue also needs to calculate anomalies.  The idea (I think) is simply to calculate (x-mean) for the monthly (or daily) data.  Here the "mean" is the average value over the years for each station for the same month (or doy).  This is done separately for the station and the satellite data.  So we still have 2 columns, one of satellite and the other of station anomalies.  Then these anomalies are correlated. 
So perhaps there could be 2 buttons, one saying **Difference** and the other **Anomaly**.
The difference is what is described above.  

The data could be daily or monthly and it would be good if the dialogue worked equally for both.  

The dialogue could be similar for both buttons, with the same on the rhs, (Station, Date, Year, Within Year).  
The within year field would be Month for monthly data and doy for daily data.  This should be OK whether doy is a factor or numeric.

There is just one checkbox saying Moving Average.  Default is unchecked.  If checked then there is an up-down, with values 1,3,5,7, etc up to 31.

There are again 2 column to be saved, and this time they are labelled Satellite Anomaly and Station Anomaly.

The idea is that for each of the 2 columns it calculates the mean over the years, within the station.  This is calculated either for the month, or the doy, whichever is in that field.  Then it subtracts the mean from the value.  That gives the data for the anomaly columns.

I have been concerned about the daily data, because the means will be "noisy".  So if the moving average checkbox is checked, then it first does a centered moving average of the daily (could be monthly, but not usually used for months) data, before getting the means over the years.  This moving average is within station.  The only other complication is what it does at the end of the records.  That doesn't matter too much so take any sensible option from the moving command used.  I assume it will be the same command used in the **Climatic > Prepare > Transform** dialogue.  

We still have to consider what to do as summaries of these columns.  The Summary system can calculate correlations, so that's a good start.  We may want some plot options?  The forst aim would be to have the calculated columns.

**Comment by dannyparsons** [comment]
I'll start working on the R code for this.

**Comment by dannyparsons** [comment]
Here's my go at the designs in both cases
**Differences**
![15341774435941728600482](https://user-images.githubusercontent.com/11214914/44044528-ba6ac9d8-9f1d-11e8-8b2b-efe6b5dc4228.jpg)
**Anomalies**
![15341774904131383754236](https://user-images.githubusercontent.com/11214914/44044549-cfded700-9f1d-11e8-8843-cbd21e5592bb.jpg)

**Comment by dannyparsons** [comment]
Differences should be straightforward.

For Anomalies, the moving average checkbox can be added but disabled. We won't do that yet.
To save the columns I don't think we need checkboxes. If the receiver is filled in then that's what is calculated.

For Differences both columns are needed but for Anomalies only one is required to calculate something.

We will not do anything on summarising here it will just calculate the new columns. R code examples will be in the next comment.

**Comment by dannyparsons** [comment]
Differences example:

```
bias_calculation <- instat_calculation$new(type="calculation", function_exp="RR_satellite - RR", result_name="bias1", calculated_from = list(Ghana_Data = "RR_satellite", Ghana_Data = "RR"), save=2)
absdev_calculation <- instat_calculation$new(type="calculation", function_exp="abs(RR_satellite - RR)", result_name="absdev1", calculated_from = list(Ghana_Data = "RR_satellite", Ghana_Data = "RR"), save=2)
combined_calculation <- instat_calculation$new(type = "combination", sub_calculations = list(bias_calculation, absdev_calculation))
InstatDataObject$run_instat_calculation(calc=combined_calculation, display=FALSE)
```

**Comment by dannyparsons** [comment]
Anomalies example:

```
grouping <- instat_calculation$new(type="by", calculated_from=list("Ghana_Data"="Station","Ghana_Data"="doy"))
satellite_anomalies <- instat_calculation$new(type="calculation", function_exp="RR_satellite - mean(RR_satellite, na.rm = TRUE)", result_name="RR_satellite_anom", calculated_from = list(Ghana_Data = "RR_satellite"), save=2)
station_anomalies <- instat_calculation$new(type="calculation", function_exp="RR - mean(RR, na.rm = TRUE)", result_name="RR_anom", calculated_from = list(Ghana_Data = "RR"), save=2)
combined_calculation <- instat_calculation$new(type = "combination", sub_calculations = list(satellite_anomalies, station_anomalies), manipulations = list(grouping))
InstatDataObject$run_instat_calculation(calc=combined_calculation, display=FALSE)
```

**Comment by dannyparsons** [comment]
I've added Shadrack here as well as this is the most urgent task for the next release.

**Comment by dannyparsons** [comment]
@shadrackkibet @Muthenya please let me know if you'll be able to complete this before Friday. If not, that's fine, but then I will take over it today.

**Comment by shadrackkibet** [comment]
We are going to work on this starting today afternoon. Hopefully have something by Tomorrow to test.

**Comment by dannyparsons** [comment]
Great thanks. If you would like to do one of the options first - probably Differences is easier - and get that tested and merged first, that might help get it finished quickly.

**Comment by shadrackkibet** [comment]
@rdstern @dannyparsons do you any specific datasets to test this dialog?

**Comment by dannyparsons** [comment]
This is meant to be with two columns measuring the same element, one from satellite and one from a station. I don't have a prepared file with these already, maybe Roger does. You could import from NET cdf and then merge with station data, but that would take time. You could just use two similar columns to test for now e.g. tmax and tmin.

It's important for the difference that it is `satellite - station` and not the other way around.

**Comment by rdstern** [comment]
Give me a  few minutes and I'll attach one.

**Comment by shadrackkibet** [comment]
Thanks for attaching this, We are now done with the first option (Differences). The second option is also easy to do. So we can complete it by tomorrow.

**Comment by dannyparsons** [comment]
Great, do you want to send up what you have now and I'll test?

**Comment by shadrackkibet** [comment]
yap, we can send that for testing.
