### ISSUE TITLE
Adding declustering to the calculation of extremes

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4760]
The extRemes package includes a function called decluster.  I think this would be very useful for us for the **Climatic > Prepare > Extremes** dialogue when it is calculating the peaks over a threshold.

It needs someone better than I am at R to check exactly how it works.  The idea is that peaks over a threshold (say 40mm) should not be (say) neighboring days.  They need to be at least r days apart, where the user chooses r.

If r=1 then this function isn't needed.  If more than 1, then it could be useful prior to the existing filter.

The decluster function seems to produce a column of the same length as the original data, but (in any cluster where there are multiple values more than the threshold, it keeps the maximum and sets all the others to the threshold value.  So then if you take all the values more than the threshold (filter) after this, then it will just give the one value in each cluster.

It also has groups argument, so that neighboring values above a threshold would be OK if they belong to different groups.  We have 2 contenders for different groups, namely maybe different stations and also different years when we are getting the peaks for just a subset of the year.

The function also allows options for missing values.  I am not sure what happens now when there are missing values in the data?  I must check.

**Comment by shadrackkibet** [comment]
@rdstern @lloyddewit please reopen this issue. I initially changed the "plan" but forgot to remove "Fixes" in the PR which led to this being closed. Thanks

**Comment by lloyddewit** [comment]
@shadrackkibet reopened as requested
