### ISSUE TITLE
Dialogue to show non-numeric values

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4766]
I suggest this starts as a very simple dialogue.  It is in the **Prepare > Check Data > Non-numeric Cases**. It is the third in that menu, i.e. below Compare Columns and a horizontal line is just below that.

It starts at least as a very simple dialogue.  There is the usual data selector, which only shows character columns.  I suggest a multiple receiver, but would accept a single receiver if that made things easier.  

It would then simply do a filter to show the rows where the values are non-numeric.

Later there might be options, for example it could provide a count of the number of non-numeric rows in the output window.

We need the R code of course.  From @dannyparsons 
is.na(x) != is.na(as.numeric(x)) comes close, but I thought it also includes missing values as non-numeric.  Perhaps it is all we need?  Otherwise it needs to be adapted a bit.  

Once we have a more general dialogue for filters, then it should also be possible to use the filter dialogue directly.  But, with our audience it would still be useful to have a special dialogue.

**Comment by dannyparsons** [comment]
This code wouldn't show NAs in the filter e.g.
```
> x <- c(1, NA, "1 1")
> is.na(x) != is.na(as.numeric(x))
[1] FALSE FALSE  TRUE
```
If you also want NAs to be included in the filter then use this:
```
> x <- c(1, NA, "1 1")
> is.na(x) | (is.na(x) != is.na(as.numeric(x)))
[1] FALSE  TRUE  TRUE
```

**Comment by dannyparsons** [comment]
At the moment this can't be done as a filter because it doesn't fit our current filter format of [column] [symbol] [value]. The best we could do at the moment is add a logical column and filter on that or print the filtered data in the output window.

**Comment by rdstern** [comment]
I don't want NA in the filter, i.e. I am happy with the first formula.  I just want to know about the non-numeric values.  If we have options, then I don't mind both, but the main idea is simply to locate the non-numeric values.

**Comment by dannyparsons** [comment]
I agree. Since we can already filter for NA in the filter dialog I don't think it's needed here.

**Comment by shadrackkibet** [comment]
Working on this.

**Comment by shadrackkibet** [comment]
@rdstern any comments?
![image](https://user-images.githubusercontent.com/26301973/42807705-29ceadd6-89ba-11e8-99f9-081c3dbd365e.png)

**Comment by rdstern** [comment]
Great.

1. Could you change the "Column" to "Character Column".
2. Align the beginning of the field that currently says logical with the beginning of the field for the input of the comment.  (Lily says width 255.)
3. The name of the resulting column could be nonnum as the prefix - so (if you leave it alone, it goes nonnum1, nonnum2 etc).

**Comment by dannyparsons** [comment]
I would call the title "Find non numeric values" and change "save result" to "Logical column"

**Comment by rdstern** [comment]
Many thanks.  This is a great start.  I am re-opening the issue after discussion with David.  He suggests the improvements would also make a good teaching exercise for the AMI team.

1. The name (in form Main) is currently None Numeric Cases.  It should change to become **Non-numeric Cases**.  At the same time could there be a line underneath this item in the menu.
2. The receiver  becomes a multiple receiver.   (It still produces only a single output column).
3. It will always produce this output column.  There is also a checkbox (default unchecked) that says **Also include individual columns.**  
4.  The data selector is restricted to character columns only.  That's the main use of the facility.  If you wanted it for a factor column, then it is made into a character column.  Currently it shows odd date-type columns, and all the logical columns, etc.  
5. It would be good if there could be some (optional) output in the output window.  So there is a checkbox above the saved column that says **Display summary**.  Default is checked.
6. There is a third checkbox (default unchecked) **Filter to non-numeric cases**.  This would automatically filter the data.

Perhaps the initial work could sort out the dialogue.  Then contact David, who will take you through the steps over skype.

**Comment by rdstern** [comment]
I am therefore reopening this issue

**Comment by rdstern** [comment]
Given the new facility to convert character columns, I checked and this is working fine.  It would be good to consider the extras to the dialogue mentioned above.  It could be good to start with the simplest, i.e. to include a summary?

**Comment by shadrackkibet** [comment]
Which summaries are you interested in here?

**Comment by rdstern** [comment]
I am happy for it to simply run the summary command - the same  as when we use the default of **Describe > One Variable > Summary**.  It is run on the logical column that is produced.
[MZIMBA1.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2273702/MZIMBA1.xlsx)

The attached data set can be used for testing.  The sheet is for maxtemp.  Three columns are character, namely x2002, x2009, x2015.  

If you try them then there is just a single non-numeric value in x2009 and x2015.  x2002 is non-numeric because of the formatting in Excel, but all is OK, i.e. none are numeric.

If you are making this edit to add the summary, then you might as well add the further checkbox "Filter to non-numeric cases" at the same time, even if it is still disabled for now.  

(I don't know how much extra work it is to include that feature - or even to add the multiple receiver.  See above.  Note, that if the multiple receiver is added it still just produces a single logical column.  This is FALSE if all the variables are numeric for that case.  If one or more are non-numeric, then it is set to TRUE.)

**Comment by rdstern** [comment]
I have had an interesting time just now on the following data:
[Pluviometrie Moustique.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2289903/Pluviometrie.Moustique.xlsx)

This is daily rainfall data from Haiti in the "shape" where there is one column per month.  Quite a number of the columns come as character.  There are 2 main problems, first occasionally the decimal point is given as a comma.  Second there are some individual letters, e.g. h or ? occasionally.

This is a simple dialogue that shows how sensitive the amount of work is, to the details of the dialogue.  Currently, with only one column at a time, it takes a long time, and patience to detect and correct the non-numeric values.  And it is a good example where you don't want to set them all to NA, because those with a comma should just change to a full stop.

This does not happen, in the same way, when writing commands instead.  The commands can usually be changed to make the work efficient.  With the menus you are at the mercy of the details of their construction.

**Comment by shadrackkibet** [comment]
So, for now i am going to work on **2,3** and **4**

**Comment by Patowhiz** [comment]
How I wish that instead of producing a logical column with a summary, we could just have the cells in those columns with non numerics highlighted in different colors, then all I will need to do is check on the summary and if I'm not using the filter just scroll quickly to a particular cell. Assuming the logical column is not mandatory.

**Comment by dannyparsons** [comment]
This might be fine for a small number of rows but typically we are using large data for this. For example, we have just used this with Lesotho Met's daily climatic data and with only 20 out of over 100 stations in R-Instat we had about 400,000 rows so it would be impossible to see this by looking at the cells.

However I do agree we would like to have better use of colours in the grid generally as this can be very useful in certain cases.

**Comment by dannyparsons** [comment]
A small and simple improvement would be to be able to give the name of the subset data frame that's produced if you check to do the filter/subset. I've commented that here as I don't think it should prevent the current pull request being merged and I don't expect Shadrack necessarily has time to do this.
