### ISSUE TITLE
Climatic>SPI

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#4783]
Currently when you have `shift>=Time scale ` ok is enabled and on clicking ok you get a Bug

![image](https://user-images.githubusercontent.com/26301973/42862253-60b25c46-8a67-11e8-88ef-183378968a81.png)

I am thinking of checking this values and have a message  "**Shift value must be lower than Scale value, Ok will not be enabled**" when this happens.

@dannyparsons  @rdstern ?

**Comment by dannyparsons** [comment]
That looks ok to me from reading the error message.

**Comment by shadrackkibet** [comment]
Great, I am going to close this then.

**Comment by dannyparsons** [comment]
What I meant was, your suggestion looks ok since this is what the error message says. I don't know much about the calculation but your suggestions looks sensible given the error message.

**Comment by shadrackkibet** [comment]
okay, I will reopen this to get views from others who understand calculation.

**Comment by rdstern** [comment]
There is a more basic issue with the current dialogue that I hope is easy to fix.

It currently produces results in the output window.  This should become an option and the default is to save a column.  The results in the output window are for 12 columns, one for each month, but what is saved should be a single column by year and month.  This should be linked, as often we will use the command more than once, and it will then be good to get all the saved columns in the same data frame.

**Comment by shadrackkibet** [comment]
I am not sure if we can be able to do this with the current functions from SPEI package. @dannyparsons could you please shed some light on how to go about this?

**Comment by rdstern** [comment]
Currently the R-code gives the command without saving the structure.  I tried with Dodoma.  It is a command for monthly data, so first use Climatic > Summary > Climatic Summaries and get the monthly totals of the rain column.  That is of length 948, i.e. 79 times 12.

1. Then we need to set the missing option to TRUE in the SPI dialogue.  I suggest that should be the default?
2. Currently the R code for a simple example is then simply:
**SPEI::spi(data=sum_Rain, scale=1, kernel=list(type='rectangular', shift=0), na.rm=TRUE)**
3. This is actually a modelling dialogue.  Perhaps it should move to be the first item under Climatic > Model.  Then it wouldn't also be quite so prominent in the menu?
4. So we should add the control in the dialogue to save the fitted model and presumably anyway change the command so the last model is saved.  I assume this will change the command into something like:
**last_model <- SPEI::spi(data=sum_Rain, scale=1, kernel=list(type='rectangular', shift=0), na.rm=TRUE)** 
5. Then it would anyway be better if the default use of the dialogue executes the **summary(last_model)** command.  This gives the same printout as currently, but with other useful information.
6. Then it is the second element of the fitted object that is required to be saved, i.e. last_model["fitted"], or last_model[2].  I assume that is similar to the saving of the fitted values from regression that you did before, except this is a time series.  If you look at str(last_model[2]) it is a time series of the right length, i,.e. 948 values in this case.

I hope this helps.  @dannyparsons may be able to add to this and explain better - when he wakes up.  It is early in Canada just now.

**Comment by dannyparsons** [comment]
It returns an object of class `spei`. The fitted values, `last_model$fitted`, is what we want to save. Not so simple yet as this is a `ts` (time series) object and not a data frame or vector. Since we want this as a single column then we can just do `as.vector(last_model$fitted)` and save this as a new column. 
We should think what happens when a filter is applied, because then you won't get something of the right length.
I agree that `summary` should be the default print out.

**Comment by shadrackkibet** [comment]
Thanks for this insights, i can now proceed with the task.

**Comment by rdstern** [comment]
This is now looking great.  

I am re-opening for a small addition.  Could there also be the control to save the model (i.e. the spei object) with a chosen name - just as in the regression models?

This would be underneath the save index.

A second small change is to move the menu item.  It is currently in Climatic > SPI and in the describe section of the menu.    It is more appropriate in the modelling section, so could it move to become Climatic >  Model > SPI.  It could be at the top - above Extremes.
