### ISSUE TITLE
New dialog for export to CM SAF R Toolbox

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4787]
This is a new dialog under Climatic > CM SAF which exports a climatic data frame as an .RData file to be imported into R for use with CM SAF R Toolbox. Here is the code:

```
x <- data.frame(station_name = Station, date = Date, lon = Longitude, lat = Latitude, SIS = SIS)
attr(x, "element_name") <- "SIS"
rio::export(x, "cmsaf_export.RData") 
```

So all this is doing is exporting a climatic data set which has location information for stations with standard column names so it can be imported into CM SAF's R toolbox to be used for mapping. The final column is an "element" column so SIS is just an example, it should be whatever element the user chooses. The second line then adds an attribute to the data frame to indicate which column is the element column, and finally it is saved as an RData file.

So dialog needs the 5 receivers and the controls for choosing where to save the file to and that's it.

The only complication might be needing to have the first 2 lines set up as code that runs before the main export command.

**Comment by shadrackkibet** [comment]
should this have a climatic Tag?

**Comment by shadrackkibet** [comment]
Working on this.

**Comment by shadrackkibet** [comment]
@dannyparsons  i think we need a dataframe here?
 `x <- data.frame(station_name = Station, date = Date, lon = Longitude, lat = Latitude, SIS = SIS)`

**Comment by dannyparsons** [comment]
What do you mean? That looks like the first line of the code from my first message.

**Comment by shadrackkibet** [comment]
I mean do we need an object here?`x <- data.frame(x= ???,station_name = Station, date = Date, lon = Longitude, lat = Latitude, SIS = SIS) `

**Comment by dannyparsons** [comment]
If you have `x = ???` in the data.frame command then that creates a column called x in the new data frame. We don't need that. I'm not sure what you mean by object though. 
The code I wrote originally is what we want, with of course `Station` and `Date` etc. being the columns from the chosen data frame.

**Comment by shadrackkibet** [comment]
Aha!  i realize i confused this with `as.data.frame`. This is okay.

**Comment by shadrackkibet** [comment]
I now understand . Thanks.

**Comment by shadrackkibet** [comment]
@dannyparsons  this is the design for this dialog. Should all the receivers be filled for ok to be enabled?

![image](https://user-images.githubusercontent.com/26301973/43453657-49fde78e-94c3-11e8-82e4-96bf2cf13e9d.png)

**Comment by dannyparsons** [comment]
Looks good. Yes everything is needed to be filed. With station and date being autofilled.
