### ISSUE TITLE
Additional menu item for clearing the output window

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#4792]
@africanmathsinitiative/developers  There is very well designed icon for clearing the output window in the toolbar, still, most of the time I find myself right clicking on the output window to access such functionality. Most apps have a similar functionalities(clearing contents of input controls) built right into the control on the right click menu. We already have a similar one on the script window.  Wouldn't be nicer to also have a menu item for this on right clicking the output window?

<img width="661" alt="output" src="https://user-images.githubusercontent.com/21179007/42959817-b1ddba30-8b92-11e8-8e7c-16f3ba68c42d.png">

**Comment by dannyparsons** [comment]
Yes sounds good to have on right click

**Comment by rdstern** [comment]
I support having this on the right-click menu in the output window.  As you suggest above, there could be a horizontal line before it and it is the bottom item.

I would also then delete this item from the toolbar.

**Comment by Patowhiz** [comment]
This was not implemented. I have decided to leave it for now, it's a long shot

**Comment by Patowhiz** [comment]
The user will now be able to clear the entire contents of the output window or the selected content.

<img width="461" alt="clear output" src="https://user-images.githubusercontent.com/21179007/44045155-5a9b5c62-9f30-11e8-8de0-7ab9d585d48b.png">

**Comment by dannyparsons** [comment]
We didn't discuss if we wanted to be able to clear parts of the output, but I can see this might be useful. Does this work for graphs and tables as well?

If we have this, I can't see how this obviously works with only only item then - if it depends on what's selected. I would have "Delete Selected" and "Clear". I think "Clear" implies "everything" so you can't clear parts of the output.

**Comment by Patowhiz** [comment]
It works for any selected values, text, graphs. We can have Delete and Clear. Then Delete  will be disabled if there is not selection and enabled if there is selection

**Comment by Patowhiz** [comment]
<img width="459" alt="clear output" src="https://user-images.githubusercontent.com/21179007/44048414-e77c3008-9f39-11e8-85bf-7d7229d94b1f.png">

**Comment by rdstern** [comment]
Looks good.  Should it be **Delete Selection** and **Clear All**, or **Clear Window**?

**Comment by Patowhiz** [comment]
Well, it's an output window. I think clear would do. I'll have the delete changed to delete selected

**Comment by dannyparsons** [comment]
That sounds good.
