### ISSUE TITLE
Calculator 

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#4795]
I don't have a specific example where i want this now but i suspect ` %in%` operator should be added as a button somewhere in logical and symbols keyboard.

![image](https://user-images.githubusercontent.com/26301973/42996515-743ef2fe-8c1c-11e8-924b-4e2345034c74.png)

**Comment by dannyparsons** [comment]
yes it should be in the logical. Also, which is an important logical function.

And just looking at the keyboard, why are the open and close bracket buttons not next to each other?

**Comment by rdstern** [comment]
And should we (somewhere) have [[ ]]?

**Comment by dannyparsons** [comment]
yes also useful
