### ISSUE TITLE
Add a modelling dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4801]
In the model menu we currently have a Hypothesis Tests dialogue - below the line.  That's a "halfway house" dialogue where you give the R command.  It has keyboards that correspond to packages and keys that correspond directly to the R functions in those dialogues.

I suggest it would be good to have a second dialogue.  I think I'd call it just **Modelling**or **Model Commands...** is an alternative.  This would start as did our hypothesis tests dialogue with the Stats keyboard, though this time we only need one.  (In hypothesis testing we had Stats1 and Stats2.) 
I would have it below the line in the Model menu and just above the Hypothesis tests. 

I suggest it would be great to have in place soon, (by the AIMS course) so I have given it the 5.1 milestone.  As with the hypothesis tests dialogue it is no substitute for our proper dialogues.  But it continues our process of providing access to much of R, for those who understand and can use single commands.

The **Stats** keyboard could start with the keys **aov, ar, arima, glm, lm, loess, loglin, lowess, spline**.
This is the first keyboard and the others are in alphabetical order.  They could initially include **extRemes, lme4, MASS, and possibly survival**.

The dialogue can start as a copy of the hypothesis testing dialogue with the following initial changes:
a) Change the bottom keyboard for the same keyboard as in the general models.  In that keyboard change 0 for square brackets, i.e.[ ].
b) Get rid of the by checkbox - which is currently disabled.  
c) Keep the dialogue the same size, (as hypothesis testing) because there will be items to add.
d) For now have 2 buttons.  One is **Display Options**, which is the same as for the other modelling dialogues and (iniitally) leads to the same sub-dialogue.
e) The second is **Predict**.  This is disabled for now. 

In extRemes
**fevd, levd**

In lme4
glmer, lmer, nlmer

In the MASS keyboard:
glm.nb, glmmPQL, loglm, polr, rlm.

**Comment by shadrackkibet** [comment]
@Muthenya  could you please create this dialog then we can work on it together?
