### ISSUE TITLE
Raster package and more in Climatic Transform?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4802]
I needed to calculate a circular smoothing function for climatic work recently.  This will become useful generally when we have more plots with the x being the seasonality (day in the year) as well as time series plots (x is the dates or year etc.)

I needed a moving average which is circular.  There is a nice function in the raster package:
**raster::movingFun(prop10,20,circular=TRUE,na=TRUE)**

I couldn't find any other circular moving average?  With our current work on mapping I wonder whether we will need the raster package anyway?  That's a question partly to @JacklineKemboi ?

Then I suggest this could usefully go into the Transform menu of the calculator.  Perhaps it is called CircMov on the key?

And just to add the new functions that I hope we might have in the calculator in Version 5.0, i.e. for the Pretoria workshop.  They include:

1) This circular moving average on the transform keyboard.
2) Daylength added to the dates keyboard (#4749 )
3) Adding %in% #4795 to the logical and symbols keyboard
4) Adding a new Conversions keyboard.  Initially with the weathermetrics package and three keys.  This is from #4341:

This to have (initially) buttons called rain, temp and wind. They would implement 3 different commands, namely

convert_precip(x, old="m",new="i",round=2)
convert_temperature(x,old="c",new="k",round=1)
convert_wind_speed(x,old="kmph",new="kn",round=1)
We found, in Pretoria last year that temperatures were in degrees Kelvin and this would have been useful.
I am sure there will be more conversions later.

**Comment by dannyparsons** [comment]
These seem more like their own dialogs to me. The functions have a lot of parameters and flexibility so I don't think it's so easy for users from the calculator. What about

1) Moving calculation dialog in Prepare. raster::movingFun looks very flexible since you can use any summary and choose if it's circular or not. And then you'd want to do this within station presumably? Which you can't do from the calculator.
2) Conversation dialog in climatic. The functions are not that difficult to use, although you have to know the old and new codes, and there are 3 functions, all climatic so why not make it easier with a simple dialog.

**Comment by rdstern** [comment]
The comment from Danny that these calculator functions look "more like their own dialogs to me", is useful.  I don't see these as mutually exclusive.  Having them in the calculator (in addition) is the parallel of having our hypothesis testing dialogue (and hopefully soon the new modelling dialogue), where we effectively give an R command, while we will also have more helpful dialogues in our usual form.

For Prepare sort of stuff we have the calculator and we could also have a transform dialogue - which we did in the old Instat - for the common transformations.  

So I still suggest we could have a Conversion keyboard in the calculator, which will later have lots of conversions - not just those for climatic data.  And we could also have a Conversions dialogue in **Climatic > Prepare**, which will handle common climatic transformations and these could be the first simple examples.  I was assuming we could do the changes in the Calculator more quickly, so they could be there for the August Version (0.5.0?).

The moving calculation is also partly for this reason of speed.  Danny is correct here that this is an option that will (later?) need to be adapted for the different Stations.

One thought - which might be just as quick - we already have a Climaitc > Prepare > Transform dialogue.
a) Could we just add a **Circular** checkbox to the **Moving tab** to change the function here?
b) Could we also add a **Convert** tab (Could be the first one) and put these conversions in the same dialogue?  

They both have the same feature as the **Prepare > Column: Calculate > Calculations**, and the existing  **Climatic > Prepare > Transform** dialogue, of producing a new column of the same length, i.e. to go into the same data frame as the data in the calculation.

**Comment by rdstern** [comment]
So, if the convert functions from the **weathermetrics** package are to be added, then first we need the package.  Then a Convert tab.  Possibly the first.
Then I suggest the usual selector.  On the right - largely for consistency - there is Station and Date and the Element.

Then beneath are 3 drop downs.  First is with the options for Rain, then Temp then Wind.  This has the label **Element:**,
Then there is a From and a To label each with their own drop down.  The options in **From** and **To** change depending on the setting for **Element**.
If Rain, then From and To contain: Inches, mm, cm
If Temp then: Centigrade, Fahrenheit, Kelvin
If Wind then: • knots: Knots, mph: Miles per hour, mps: Meters per second, ftps: Feet per second, kmph: Kilometers per hour

There is also an up-down Decimals: 0 to 3 default is 1.
See the package for more details

They will run commands such as
convert_precip(x, old="m",new="i",round=2)
convert_temperature(x,old="c",new="k",round=1)
convert_wind_speed(x,old="kmph",new="kn",round=1)

**Comment by dannyparsons** [comment]
> One thought - which might be just as quick - we already have a Climatic > Prepare > Transform dialogue:
> a) Could we just add a Circular checkbox to the Moving tab to change the function here?
> b) Could we also add a Convert tab (Could be the first tab) and put these conversions in this same dialogue?

Yes I think this is a good idea. I suggested because I don't think it's actually much work to add these things to a new or existing dialog compared to the calculator, and would be nicer to use.

**Comment by rdstern** [comment]
In addition to the extra tab, I propose that the Moving tab should be corrected, have an extra option added, and also have a checkbox for circular.

So here is my list for the Moving tab:
a) Currently it seems to ignore the setting for the number of days.  I changed the number from 2 to 3.  Then (as I didn't understand the results I looked at the commands in the script file and found it was still 2.  When I changed it manually to 3 (in the script file) I got the results I wanted.
b) I changed the sum to mean.  The name of the column to be generated didn't change, i.e. it remained at moving_sum - and it gave me the moving sum instead of the mean.  When I clicked in the name field, then it changed to moving_mean (and then gave the mean.

So the code needs to be examined for the existing command.
Then:
c) Add median to the list of the statistics.
d) Change the default from 2 to 3 of the number of days.
e) Add a Position control, with a combo box having the settings Left, Centred, Right.  Default is Right.  Connect this to the Align argument of the rollapply function.
f) Add a checkbox with the label Circular.  Default is unchecked.
g) If the Circular is checked, then use the function from the raster package instead of rollapply.
raster::movingFun(x,3,circular=TRUE,type='to',na=TRUE) 

Here the type argumant corresponds to the align in rollapply, where to = right, around = centred, and from = left.
h) Finally, at least with this setting of **Moving** we need to check what is needed for Ok to be enabled.  I wanted to to use it for summary data where there was a doy, but no year, etc.  If there is a station, then the function should be grouped over that.  But I am not sure what else is needed.  Nothing else is used by the current rollapply, but OK needed most fields to be filled.  We need to check this.

**Comment by Muthenya** [comment]
I have noticed that there is still some work being done on the Transform dialog, so I guess this is waiting for that to be finished unless some of the changes proposed here are being implemented on Beth's pull request.

**Comment by Muthenya** [comment]
@dannyparsons has the **raster** package been installed?

**Comment by dannyparsons** [comment]
Not yet I think, but it doesn't need to be added before the additions to dialogs are made.

**Comment by Muthenya** [comment]
I have made the changes on the Moving option. The package is required for the addition of the Circular Checkbox. Otherwise, all the other additions on the Moving option have already been added.

I've currently began work on adding the conversions tab.

**Comment by rdstern** [comment]
That's great.  Can you add the raster package to your machine, just through RStudio, then it will be available.  Then you can include the circular addition and check that it is working.  
I am ready, once anything is merged, and have the raster package on my installation.

**Comment by Muthenya** [comment]
This is how I have set up the Conversions option.  I thought it would be great to borrow from the designer set up from the Conversions dialog.

![image](https://user-images.githubusercontent.com/32125033/45998634-19873780-c0ac-11e8-86a5-02a74b8fb1bb.png)

**Comment by rdstern** [comment]
Oh.  It looks nice, but is not what I thought would be happening.  We don't need the facility for conversions in 2 places.  I originally thought it would go there - in Transform - but Danny suggested to separate dialogue.  

So the extra tab you have in Transform could now become Cumulative and have the Cumulative sums within Station and Year, as described in #4969.  

And the other changes, on this dialogue, are to the Moving option, with the circular aspect, etc and that's where the raster package comes in.

**Comment by Patowhiz** [comment]
@Muthenya could you share the final design layout for this dialog

**Comment by Muthenya** [comment]
Here it is.
I've picked two options.

![image](https://user-images.githubusercontent.com/32125033/47748691-72924e80-dc9c-11e8-82be-97b2ee6f96fc.png)

![image](https://user-images.githubusercontent.com/32125033/47749018-37444f80-dc9d-11e8-93d4-26c49db041ca.png)

**Comment by Patowhiz** [comment]
Looks nice.
