### ISSUE TITLE
geom point shape strings

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4805]
Once R-Instat uses ggplot2 v.3.0.0 we can use the improvement that the shape of points can now be specified as a string (as well as an integer). I suggest we now just have the strings in our graphics system. The list is here: https://ggplot2.tidyverse.org/articles/ggplot2-specs.html.
Since this will be used by multiple geoms we should define the list in VB and reuse it:
```
("circle", "circle open", "circle filled", "circle cross", 
"circle plus", "circle small", "bullet", "square", "square open", 
"square filled", "square cross", "square plus", "square triangle", 
"diamond", "diamond open", "diamond filled", "diamond plus", 
"triangle", "triangle open", "triangle filled", "triangle square", 
"triangle down open", "triangle down filled", "plus", "cross", 
"asterisk")
```
![image](https://user-images.githubusercontent.com/11214914/43074428-26109ab4-8e75-11e8-9620-da717b75cc41.png)

**Comment by maxwellfundi** [comment]
This is good as the users will not need to know what number represents what shape. Having  list with shape names is much clearer.

**Comment by Ogik99** [comment]
@maxwellfundi can we now go ahead with specifying the string names of the various shape points

**Comment by Ogik99** [comment]
We can use the same approach we applied in defining string names for the linetypes.

**Comment by maxwellfundi** [comment]
@Ogik99  yes thats correct. We can define a list of these then use the list in a similar way as we did for the linetypes.
