### ISSUE TITLE
Changing facet labels

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4809]
The labeller functions in ggplot2 are useful for changing the display of facet labels
https://ggplot2.tidyverse.org/reference/labellers.html
https://ggplot2.tidyverse.org/reference/labeller.html

There's quite a lot here, including providing a list of values to manually override the labels and using mathematical expressions.

What we could do quickly and is useful is to have the option of adding the following to the facet function:

`labeller = label_value` only display level name (the default)
`labeller = label_both` display variable name + level name
`labeller = label_context` display variable name + level name when there is more than one facet factor on the same axis.

The third is not really useful for us at the moment as we don't have two factors on the same axis in our options. But we could have a checkbox on the facets tab which says "include variable name in labels" and that would be very quick.

**Comment by maxwellfundi** [comment]
Working on this now
