### ISSUE TITLE
View Labels/Levels error

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#4820]
I think (/hope) this is quite a quick bug. It is with the "View Labels/Levels" dialog (Prepare > Column: Factor > View Labels). I inputted my variables and pressed OK and got an error.

It worked fine when I then transferred the code to R. From memory the output from this dialog used to open outside of R-Instat so my first guess is the error is to do with that?

Also this error does occur with other data sets. If you wished to replicate it then try with the `efc` data set in the `sjPlot` package.

> Error in file(file, ifelse(append, "a", "w")) : 
>   cannot open the connection
> 
> The error occurred in attempting to run the following R command(s):
> 
> .temp_val <- capture.output(sjPlot::view_df(x=dplyr::select(.data=kisesa_residency, c(sex,entry_type,exit_type)), show.frq=TRUE, show.id=FALSE))
>

**Comment by shadrackkibet** [comment]
I am unable to replicate this Bug. Just using the same dataset on my machine i am getting output on the browser as shown.

![image](https://user-images.githubusercontent.com/26301973/43367172-bab62036-9351-11e8-8bd7-aefd95db8d84.png)

This is the code from R-Instat.
![image](https://user-images.githubusercontent.com/26301973/43367187-e3b422f8-9351-11e8-8c6c-c07e851ae6a2.png)

Please give more details on how you got this bug.

**Comment by lilyclements** [comment]
Interesting! Perhaps it was an issue with having RStudio opened or something. I can't close RStudio at the moment but I'll try replicating later with it closed

**Comment by shadrackkibet** [comment]
@lilyclements did you manage to replicate this?

**Comment by lilyclements** [comment]
I’ve had this issue occur several times but am unsure what the common factor is. It’s only ever occurred to me when RStudio is open, however, it doesn’t occur every time RStudio is open.

So I’m not sure what to suggest since I’m not sure what the issue exactly is.

**Comment by Muthenya** [comment]
@lilyclements has this ever occurred again?

**Comment by lilyclements** [comment]
I don’t use R-Instat very much these days, but when I was playing around on it over summer it happened on several occasions over different weeks

**Comment by Ivanluv** [comment]
I haven't been able to replicate the bug .

**Comment by dannyparsons** [comment]
Thank @Ivanluv. @lilyclements lets look at this this week.
