### ISSUE TITLE
More small items on the calculator

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4828]
1. We now have NA on the logical keyboard, but not TRUE or FALSE.  I don't think they are anywhere else.  Can they be added?
2. This may not be so easy?  In the maths keyboard, when you tick to show arguments on round or signif keys the function also has a digits argument, but this isn't shown.  If easy, then it would be good to show.  Otherwise (perhaps anyway) it is good for a tooltip, perhaps: 
"round(x) to round to whole numbers; round(x,2) to round to 2 decimal places, round(x,-2) to round to the nearest 100".
"signif(x,3) to round to 3 significant figures".

**Comment by shadrackkibet** [comment]
In 2 above, you have to check the checkbox to show arguments before you click any button so that arguments are shown. Vice versa doesn't work at the moment.

 I am going to add tool-tips on the button so that when you hover around the button the tool-tip is shown.

**Comment by shadrackkibet** [comment]
@rdstern can we get tooltips for other buttons so that all can be added? @dannyparsons is suggesting we have all in place.

**Comment by dannyparsons** [comment]
So if I check show arguments and then click round I should get the digits argument? If so that I think that answer's Roger's question?
Happy with tooltips too but it seems a bit strange if it's just one button out of many.

**Comment by shadrackkibet** [comment]
Exactly, that is how it works.

**Comment by rdstern** [comment]
That will be useful and take a bit of time.  I will try keyboard by keyboard!
