### ISSUE TITLE
Problem with New Use date dialog.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#4830]
It seems the new use date dialog is not working. I loaded Guinea dataset and tried to use it to get numeric months but it is not working. Looking at the code on the output window it seems to be okay, I think there is a problem with the new Rcode. 
`# Code generated by the dialog, Use Date`
`InstatDataObject$split_date(data_name="Guinee2", col_name="Date", month_val=TRUE, s_start_month=1)`

On testing the other options none is working.
![image](https://user-images.githubusercontent.com/26301973/43367660-521d6b6c-9359-11e8-9bbf-bcc40d99d32a.png)

**Comment by bethanclarke** [comment]
@shadrackkibet this is odd, I do not get this error when I try running thing code with Guinea2

**Comment by shadrackkibet** [comment]
I will try replicate this Bug a report back.

**Comment by shadrackkibet** [comment]
This problem seems to be fixed elsewhere? I have tried severally to replicate it but i can't. I am going to close this now.
