### ISSUE TITLE
Small edit on the call to the View command.

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4831]
When calling the View command - at least from the right-click on the bottom tab - it gives the command as:
**View(title="diamonds", x=InstatDataObject$get_data_frame(data_name="diamonds"))**
That's if I have the diamonds data frame.
The information says that if the title isn't given, then it defaults to Data = diamonds.  This seems fine and slightly better than we do now.

Does it ever cause a problem if we don't include this argument in the command that is given?  So it would be just 
**View(x=InstatDataObject$get_data_frame(data_name="diamonds"))**

I am using this command at the start of a guide on giving commands in R-Instat and the second form would be slightly simpler to explain.

**Comment by dannyparsons** [comment]
The title is meant to be the title for the viewer. If the default is just as good or better we could remove it.

Also, to make the command even better to understand it could be:
diamonds <- InstatDataObject$get_data_frame(data_name="diamonds")
View(diamonds)

This makes more sense for people to understand and adapt the command.
