### ISSUE TITLE
Issues concerned with commands in R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4835]
This issue is the opposite of what Danny and David keep asking for!  It relates to individual issues that have been raised and perhaps some new ones that will be added for specific tasks once there is general agreement.

Some users of R-Instat may later migrate to RStudio - either completely or partially.  They include the AIMS MSc students for whom we will be using R-Instat in October and also the health students envisioned by Prof Jim Todd in his interest in R-Instat, in relation a b it to Lily's MSc project.

The same could apply to climatic users, many of whom have been exposed to R, but found the learning curve to be rather steep.

[Reading, tweaking and using R commands.docx](https://github.com/africanmathsinitiative/R-Instat/files/2240725/Reading.tweaking.and.using.R.commands.docx)

I attach a guide I have drafted for these users.  It is incomplete, in that the figures are only included for the first main section.  But it would be good to agree on some of the points below, because they would affect both the text and the figures.  And I would welcome feedback of course.  (I have nominated some of the team in this issue.  Happy for any others to also become involved.)
It includes the script window, the log file (including moving to RStudio), and the use of what I have called halfway commands.  This is particularly the Calculator, but also the hypothesis tests, the Prepare > Column: Generate > Enter and hopefully the enhanced File > New dialogue. 

1. We rename **Instat Data Object** as **Data Sheet**, and **Instat Object** as **Data Book**.  David says that is very easy to do.  It affects the code in this guide for every command! 
2. We decide on changes to the toolbar (if any).  
a) Add an item to switch on and off the commands being in the output window.  We don't have a good idea for the icon yet.  Thoughts welcome.
b) Anything else?
3. There are small corrections to be made to the right-click on the log window - see #4822 
4. For the script window
a) Add the short-cut key <ctrl> <enter> to run selection (as in RStudio)
b) As in RStudio, the same key runs the current line if nothing is selected.  (Danny claims this should be fairly easy?)
5. The File > New has an option to include commands that populate the data frame, #4439.

**Comment by rdstern** [comment]
I reply again on these items:
1. I agree that the seemingly small issue of the names is actually important.  We should resolve it quickly and implement.  It will make a small change in almost every line of the R code.  In the new possible names, then Data Sheet and Data Book do seem to relate to Excel - which is fine.  And the idea that sheets can be collected into a book is a clear one.  I don't get this with **Instat data object** and **Instat Object**.   And Instat Data Object (Data Sheet) is used mainly and is quite long!
2. I am happy to start with a facility that affects the future display and not also the past output in the Output window.  This ties with my being more relaxed with the old-fashioned look or R-Instat being fine (for now) given our main market and priorities.
3 and 4. I can accept that more thought may be needed.  But let's try to break this down, so we have a simple but usable system.  For example I am happy with the log file is we just are able to copy and then paste wherever we wish - including into RStudio if it is open.  I don't need clever transfer that is also mysterious.  
5. Very happy with the progress on the File > New ideas.
6. I also have an item 6, on which the work has started!  Namely I envision that a use of small scripts will often be examples from the R packages.  That's a pretty good way to learn about analyses.  So having access to all these examples from the Help menu, with the guides is great.

**Comment by dannyparsons** [comment]
Using the examples from R packages in R-Instat is something I'd be cautious about encouraging. These usually involves creating variables like data frames and vectors which live in your R environment but outside the instat object. And there's two issues with this:

1. Potentially confusing for users e.g. because now there's different "types" of data frames, those in the instat object and those not. Natural questions might then be, how do I get this data frame into the instat object? or the reverse? And this requires knowing instat object code which is not useful.
2. Even if you're ok with that ambiguity, creating variables outside the instat object that stay in the  environment can create nasty bugs and its fairly easy to do e.g. if there's a variable in the R environment with the same name as a column in one of your R-Instat data frames, then the calculator will give incorrect results because it uses the variable not the column. And this is particularly dangerous if your variable is similar to the column because you'll never know it happened. This is one reason why we use `rm()` after every dialog command, but you won't do this from the script window.

I think we can live with these issues with the script window for now because there should be some understanding that this is not a completely stable process so use it at your own risk, but I think that changes if we are suggesting how it can be used and then it gives these problems.

**Comment by rdstern** [comment]
I agree with your caution.  In the guide on commands I have taken an example and used RStudio and also R-Instat.  

Then I have stated that if the data live outside our R-Instat Data Sheet, there is no real point at doing this in R-Instat - we should be using RStudio.  The advantage of R-Instat comes when you do put the data into an R-Instat Data Sheet.  Then you can manipulate the data if you wish, or use one of our halfway (or ordinary) dialogues, or even just use the Script window - though then you do need to know how to get the data out from the Data Sheet first.

**Comment by rdstern** [comment]
On the name change from **Instat data object** and **Instat object** I like the idea of including **sheet** and **book** in the new names  (familiar idea from Excel).  So data_sheet and data_book are clear and simple.  If not, then id_sheet and id_book, with the "id" short for "Informative data" (or Instat data).  This doesn't explicitly mention metadata, so what about **mad_sheet** and **mad_book** with mad standing for "metadata and data".  We could swap them round and have a **dam_sheet** and a **dam_book**! Or even **maid_sheet** and **maid_book**,

**Comment by dannyparsons** [comment]
I think there was a suggestion of using **io** as a shorthand for instat object / input output 
so **io_sheet** and **io_book** is another suggestion.
**instat_sheet** and **instat_book** could be another

**Comment by rdstern** [comment]
Can we now agree on **data_sheet** and **data_book**?  This seems now to be a sensible time for the change.

**Comment by dannyparsons** [comment]
Yes I agree and will make this change. **data_sheet** and **data_book** are consistent with [tidyverse style guide on syntax](http://style.tidyverse.org/syntax.html)

**Comment by Patowhiz** [comment]
@dannyparsons @rdstern I'm working on the solution to hiding future commands for the output window. To proceed, I need your opinions on the comment I made [above](https://github.com/africanmathsinitiative/R-Instat/issues/4835#issuecomment-419492571)

**Comment by rdstern** [comment]
I am happy with your wording.  When commands are shown it says **Hide (future) Commands**.  (I wonder if the brackets are useful.  When they are hidden it says **Show Commands**.

This can already be done through the **Tools > Options** menu.  I assume that when you hide/show on the Right-Click it runs the same code and hence also changes the settings on Tools > Options?

**Comment by Patowhiz** [comment]
This is how it the right click menu will look like. @dannyparsons  @rdstern  I have noticed that switching off the commands does not switch off the comments on the output window. Was this done intentionally?

<img width="407" alt="output window" src="https://user-images.githubusercontent.com/21179007/45290969-866dcf80-b4f9-11e8-97ba-c6a1e12cd82a.png">

**Comment by Patowhiz** [comment]
The `clsRLink ` has been coded to intentionally add the comment  even when `bShowCommands `is false.

![rlink](https://user-images.githubusercontent.com/21179007/45291352-9934d400-b4fa-11e8-8a5d-05b3a69594d4.JPG)

**Comment by rdstern** [comment]
That's right.  We assume the comments and the commands are separate.  I am keen that we encourage the comments - and work on making them more informative.  I am happy that there would be right-click to switch the commands on and off, but you need to go to the Tools > Options dialogue to switch the comments.

**Comment by Patowhiz** [comment]
Okay. Hopefully we will make the comments make sense when commands are hidden, cause right now it looks odd. You have comments saying code generated by dialog and the code is not even available.

**Comment by Patowhiz** [comment]
On the issue of clearing the output window, do we still need that option on the frmMain? It appears to be redundant to me, now that we have clear on the right click.

<img width="765" alt="output window" src="https://user-images.githubusercontent.com/21179007/45291881-0b59e880-b4fc-11e8-8b4b-4244c63751ad.png">

**Comment by dannyparsons** [comment]
I'm not a fan of the option to hide commands in this way, for the reasons Roger mentioned, but I won't object if it's felt to be useful on the right click.

The comments are separate and not part of turning off the commands. This can be done in the dialog. We should have an option to not show comments by default, but as Roger says we don't really encourage this which is why it's not done already.

**Comment by Patowhiz** [comment]
Okay. Then that bit is done.
