### ISSUE TITLE
New Conversions dialogue in Climatic menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4845]
This is not really a new topic, but a new formulation of (parts) of other issues.

In discussion with Danny it seems that the sunshine hours calculation and the conversion of temperatures, etc, should have its own climatic dialogue.

It still needs a bit more discussion on the details of the dialogue.  Here is my go.
a) It is called Conversions and goes in **Climatic > Prepare and just under Transform**.
b) It has 2 of our new-style buttons at the top.  The first is **Units** and the second is **Day Length**.
c) If Units, then:

1. Our ordinary selector.
2. A single receiver label perhaps "Element"
3. At the bottom the control for saving the result, with label Result into:  
4. In the middle there are 3 combo boxes in a row.  The labels could be on top.  The first is labelled **Element** and has the 3 possibilities of Rain, Temperature, Wind.  The second is labelled **From** and the third is labelled **To**.

If Rain, then From and To contain: Inches, mm, cm
If Temp then: Centigrade, Fahrenheit, Kelvin
If Wind then: • knots: Knots, mph: Miles per hour, mps: Meters per second, ftps: Feet per second, kmph: Kilometers per hour

5. There is also an up-down **Decimals**: 0 to 3 default is 1.
See the package for more details

They will run commands such as
convert_precip(x, old="m",new="i",round=2)
convert_temperature(x,old="c",new="k",round=1)
convert_wind_speed(x,old="kmph",new="kn",round=1)

 If Day Length, then:
1. Usual Selector
2. 2 single receivers on the right for **Station** and **Date**.
3. A receiver for Latitude.  This is a bit like the receivers in the Climatic > Prepare > End of Rains in the end of Season bit.  
a) It has 2 buttons, labelled Value and Variable.  
b) When Value is selected, then you type the Value, and after the Value field have a label Decimal.  
c) If Variable, then you enter a column.
d) In the equivalent Climatic > End of Rains there is also a "replace NA with.  We don't need that here.

In the future the latitude (when it is a Variable) can be either from the same data frame as the Station and Date columns, or it could be from a linked data frame.  That's like the End of Rains dialogue.  Unless there is time, for now, have the data (including latitude) in the same data frame.

Then Result into for the result.
This just runs the command geosphere::daylength(lat, doy), and doy can be a date column.

**Comment by shadrackkibet** [comment]
@Muthenya we should make some progress on this dialog before i leave  next week.

**Comment by Muthenya** [comment]
I agree. I've already began work on it. We can have a look at it tomorrow.

**Comment by shadrackkibet** [comment]
@Muthenya this is now done! Please test it.

**Comment by Muthenya** [comment]
@rdstern, @dannyparsons this currently what we have for the designer
![image](https://user-images.githubusercontent.com/32125033/44985788-3c7d6a80-af8a-11e8-84a3-b549f7299ef3.png)

![image](https://user-images.githubusercontent.com/32125033/44985803-4901c300-af8a-11e8-9bc0-c398429b7e64.png)

**Comment by rdstern** [comment]
To me, both look fine.

**Comment by dannyparsons** [comment]
Looks good. On day length, what's value and variable? I assume I type a value or give a variable, but for what? I guess it's the latitude, then this should be made clear on the dialog.

**Comment by Muthenya** [comment]
Okay. This can be a label just above the **value** radio button saying **Latitude** or changing the names of the radio buttons to **Latitude Value:** and **Latitude Variable:** with an **Or** between them.

**Comment by dannyparsons** [comment]
I don't like value and variable, they are a bit vague. I would prefer something like single value and column.

It could all go in a latitude group box.

**Comment by dannyparsons** [comment]
Also for the Units option, the From and To combo boxes depend on the Element combo box. But this isn't shown in the current design, they just look like 3 independent options. I'll send an image of a website where the design makes it clear Element should be chosen first, which is what we want.

**Comment by Muthenya** [comment]
![image](https://user-images.githubusercontent.com/32125033/45289578-30e3f380-b4f6-11e8-9326-d0dfe45eabf6.png)
![image](https://user-images.githubusercontent.com/32125033/45289599-42c59680-b4f6-11e8-9b07-6ccc9e6f12fb.png)

**Comment by rdstern** [comment]
I like this.

**Comment by dannyparsons** [comment]
I would prefer the elements horizontally and as buttons. To me this doesn't improve on my point that it wasn't clear which controls should be modified first. It's not obvious to go left to right. I would also put everything in a group box to show they are linked.

**Comment by Muthenya** [comment]
Danny I've improved on the previous design. I think this is much better but let me hear what you think. I wasn't sure on where to place the decimal up-down.

![image](https://user-images.githubusercontent.com/32125033/45357852-44638d00-b5d0-11e8-8a3c-a72e8ca46861.png)

**Comment by shadrackkibet** [comment]
I would prefer we have normal radio buttons horizontally for Rain, Temperature and wind speed instead of this customized radio buttons.

**Comment by dannyparsons** [comment]
This looks much better to me, thanks. I like the customised buttons. We normally use normal radio buttons when going vertically and customised when going horizontal. But I don't have strong views, @rdstern ?

**Comment by rdstern** [comment]
I like those too.

**Comment by Muthenya** [comment]
@dannyparsons this can now be closed.
