### ISSUE TITLE
Import multiple similar netcdf files 

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4849]
Suggestion from @rdstern 
> It would be good to be able to read data from multiple (similar?) NETCDF files at once.

This could be needed quite often e.g. CM SAF data comes as a zipped tar file containing one netcdf file per time point.

A common operation is to choose a time period (subset of files) and location(s) (subset within each file). This could be done in one step at import.

If we implement this, I would suggest we don't do this directly from a zipped file, but a folder or set of files could be chosen.

**Comment by rdstern** [comment]
The workshop has shown me the importance of being able to do "this".  We are about "making it easy" here to process and compare the tar files from CM SAF.  
In the workshop it is OK for R-Instat to come "behind" the CM SAF toolbox.  But in general it would be much easier for staff wanting to compare satellite and station data if they didn't have to go through the steps to switch the TAR to an nc file using the toolbox.

So yes please.  Ideally though I would prefer to be able to process the tar file.  I would still like to encourage the downloading of daily data and I am not sure it is helpful for staff to have to produce a directory with more than 10,000 files if they download 30 years.  But if that helps the facility to be added easily to R-Instat, then fine.
