### ISSUE TITLE
Rainfall quality control with the Same option

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4854]
It doesn't work!  This is the option in Climatic > Prepare > Rainfall qc that checked whether x or more (default 2) non-zero rainfall values are the same.  

This seems to work fine for temperatures qc, but not for rainfall.  It doesn't give any values and David said the code is still wrong.  (As I guess it was initially.)  It may be easy to fix, given the temperatures qc works, but otherwise he can help.

I tried with Dodoma as usual.  It doesn't give an error, just no true values.  Then we mad 2 values the same in the file at the top - and still nothing!

**Comment by shadrackkibet** [comment]
I have identified this problem. It is easy to fix!
