### ISSUE TITLE
Extending the Make Date dialog: origin option with non-day units

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4864]
I think this may be a relatively simple addition in the Make Date dialogue.
It is where there is a single column and the origin is specified, e.g. midnight on 1 Jan 1970, but the existing numbers are in seconds from that origin.

We already have the structure in place in **Prepare > Column: Date > Make Date > Single Column > Origin > Specify**.

This gives a date picker - looks nice.
a) Change the label Specify to **Specify Date** and add another option to the list **Specify DateTime**.
b) The sort of control is shown [here and looks nice](https://stackoverflow.com/questions/93472/datetimepicker-pick-both-date-and-time). 
c) This gives the time in hours/minutes/seconds and the examples I have seen so far have seconds as the units.  Do we stop there, or also offer further options for situation where the time is given in minutes or hours?  
d) In that case we might have either 3 options for **Specify Time (Seconds), Specify Time (Minutes), Specify Time (Hours)**.  Each would have a different up-down control for the time component.  Or we stick with the single option and add radio buttons with the label **Units** and the 3 options of Seconds, Minutes, Hours.

**Comment by rdstern** [comment]
Sounds good, and much easier to do.  Why did you omit minutes?

**Comment by dannyparsons** [comment]
Sorry, just forgot so: Days, Hours, Minutes and Seconds for the **Units** combo box.

**Comment by dannyparsons** [comment]
For implementing, this could be done with a division operator, which should make the conditions for the units combobox easy to set up. To keep the multiplication that can just be another operator for the denominator.
