### ISSUE TITLE
Add additional Convert item to the right-click menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4865]
This is the (main) right-click menu when you are in the name field.

At the bottom of the Convert to Factor, etc section add **Convert...**  This takes you directly to the **Prepare > Data Frame > Convert Columns** dialogue.

The selected column when right-clicking is automatically put into the receiver in the dialogue.  If a set of columns has been selected in the data frame, then all are put into the receiver.  

The reason for this addition now is that the Convert dialogue now adds extra options to cope more flexibly with labelled data.

**Comment by shadrackkibet** [comment]
We had an issue previously with right click being long! Adding this seems to make the right click longer again?

**Comment by shadrackkibet** [comment]
@rdstern is this feature still needed? We can assign someone. Should be easy to add.

**Comment by rdstern** [comment]
I suggest @dannyparsons should confirm we don't need this item anymore.  

It links to an item in his in-tray that we do need, and that is the convert to numeric - that he is changing, namely #5465.  I think with that, we don't need this one?
