### ISSUE TITLE
Use Date dialogue needs minor addition to year

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4887]
Currently the Year is stated to be only **Numeric**.  This isn't true in that when the month is shifted from January the year column is actually produced as something like "1945-1946" and is defined as a factor, i.e. it is no longer numeric.

- [ ] a) Could there also be the option to produce the name, i.e. a tick in the 3rd position.  
- b) This is disabled when the month is January.  
- [ ] c) If enabled and used, then it produces exactly what is produced now (wrongly stated as numeric.)
- [x] d) If shifted and numeric is ticked, then it produces the numeric value of the year the period starts, i.e. the 1945 in the example above.
- [ ] e) There could usefully be a tool-tip with that option saying something like.  "When the year is shifted, this gives the starting year, e.g. 1984-1985 is given as 1984."
- [ ] f) When the month isn't January it isn't that obvious in the dialogue, that the year is shifted, i.e. that the starting month is not January.  I wonder if the colour could change, or there could be a label after the field that says (shifted year)?  This label would be hidden when the year is January.

**Comment by dannyparsons** [comment]
d. is done.

I have a simpler suggestion. Do a) and when the start is January it still produces a year column but as a factor with the same numeric labels. Then you don't have to do b).

f) something like that would be good. Maybe a label saying *shifted* would appear somewhere

**Comment by rdstern** [comment]
Sounds good.  I like your amended d), which deletes b)!
