### ISSUE TITLE
Adding acknowledgements to R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4890]
In discussions with Jim Hansen, CCAFS he would very much like to see somewhere an acknowledgement that CCAFS has provided some support for R-Instat.

He is also interested in promoting R-Instat through CCAFS and has mentioned having a webinar to launch R-Instat (for climatic analyses).  It would be important that we have our acknowledgements in place by then.

We launched PICSA through a CCAFS organised webinar in late 2016 and this was a useful event.  Much of the organising work was done by CCAFS and that made it pretty simple for us.  

There is a question about the location and who would speak.  But it is quite a nice and timely.  I mentioned that I was also keen to visit WMO.  Jim (CCAFS) would clearly like it to include WMO as well if possible and perhaps GFCS (Global Framework for Climate Change) Secretariat in particular.

I will get in touch with WMO when I return.  It would be good for us to have some ideas before then.

**Comment by rdstern** [comment]
Please could the Acknowledgements item be added to the bottom (?) of the R-Instat Help menu.  The help Context is 151 and the Help ID is Acknowledgements.

**Comment by rdstern** [comment]
Here is the current text:  It isn't very good.  Please improve.  I am also thinking of deleting the 2nd and 3rd paragraphs:

The original Instat started over 30 years ago and was on a BBC microcomputer.  Later, four staff members were the main contributors to the Windows upgrade, namely Ian Dale, Colin Grayer, Joan Knock and Roger Stern, from the SSC, University of Reading.  For the Windows version we would particularly like to continue to acknowledge the support of the UK Met Office, without whose funding that transformation would not have been possible. Their particular interest was the climatic facilities in Instat and now in R-Instat.

We also acknowledge the support of the Statistical Services Centre, University of Reading, that enabled more of the general statistical and data manipulation facilities to be included in the release of Instat+ and also the Department of Applied Statistics for their encouragement to include their statistical "games" within the Instat environment.

Our Statistical Services Centre once were the Biometric Advisors to the DFID Natural resources Division. As part of our proactive work for them, we produced the "good-practice" guides for DFID research projects. We are grateful for their encouragement to distribute this information freely, more widely than to DFID project teams. Their inclusion in Instat and now in R-Instat is an experiment on a further way of distribution.  These guides became a book called "Good Statistical Practice in Natural Resources Research" published by CABI.  We are very grateful that CABI have now given permission for a pdf version of this book to be distributed with this software.

Many people and groups have contributed to R-Instat.  In particular we acknowledge, with many thanks, the contributions, together with the implied vote of confidence, from the 426 people who contributed to our crowd-sourcing campaign in 2015.  The main partners have continued to support the work.  For example we were able to combine training in AIMS Tanzania with development work, while based in their wonderful centre in Bagomoyo.  In the UK the new Stats4SD (Statistics for Sustainable Development) has now migrated from the original Statistical Services Centre (SSC) and has continued to support the development work.

The current programming staff continue to be based at AMI in Western Kenya and SAMI continues to support both AMI and the ADI work.  

In 2016 the funds from the crowd-sourcing campaign were supplemented by funds from CCAFS to facilitate the transformation of R-Instat into a successor to Instat for climatic analyses, and we are most grateful for this support.  We also gratefully acknowledge the  further support for climatic components from the Met Office, UK in 2018.

More recently we had funds from the Global Challenges Research Fund, first to adapt R-Instat to be able to analyse publicly available data on procurement; secondly to be able to add an Options by Context menu to support analyses of on-farm experimental data.

**Comment by maxwellfundi** [comment]
@rdstern will this text be in form of pdf or its already on the help file?

**Comment by dannyparsons** [comment]
I think it can just be a textbox for now.

**Comment by rdstern** [comment]
It could be in both.  It is currently in the help file with context number 151.

**Comment by maxwellfundi** [comment]
@rdstern suggested this should lead to the help which has been addressed in #4999
