### ISSUE TITLE
Emphasise tidy data in more dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4896]
In the File > Open NetCDF menu item an important feature is that the facility also puts the data into a (tidy) data frame.  Could we please emphasise this in the dialogue by changing the title to mention the word tidy.

So Open NetCDF and tidy would be possible or maybe better "Open and Tidy NetCDF file".

The importing of shape files is the same.  In Climatic > > File > Import Shape Files, once in the dialogue I propose we say "Import and Tidy Shape Files"

A further small point.  Is it **Shape Files** or **Shapefiles**?  Currently the menu uses one and the dialogue uses the other.  Please can we be consistent.

**Comment by dannyparsons** [comment]
I think it should be "Import and Tidy NetCDF file" or "Import NetCDF file and Tidy", I think we use Import in general instead of Open.

**Comment by rdstern** [comment]
I suggest **Import and Tidy NetCDF File** .

**Comment by maxwellfundi** [comment]
@Wycklife  Could you please make these changes on the titles of these dialogs?

I have looked up and the correct word is **Shapefile** not Shape File. 

I am also putting this for the next milestone so needs to be done soon.

**Comment by dannyparsons** [comment]
@Wycklife was this change made?
