### ISSUE TITLE
Correct dry spells in start of rains dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4897]
Francis did some good detective work comparing the old Instat to R-Instat for data from Malawi.  The results were identical for almost all years, but sometimes there was a difference.

We tracked it down and it is a simple correction.  When including a dry-spell condition of (say) 9 days, the dialogue implies that 9 days is OK, but more (e.g. 10 days) is not OK.

However the current command has <9, which means 9 days is not OK!  The change is possibly simply to replace <9 by <=9.  However I always get concenred that this might not be perfect, because of possible rounding problems.  It may be OK, because the number of days is sort of a count.  But unless an R-expert is sure this fix is OK I would prefer adding (say) 0.5, so it becomes < 9.5.

**Comment by dannyparsons** [comment]
Since these are our own generated counts I think <= 9 is not a problem.
