### ISSUE TITLE
Replace Values dialog - column types

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4906]
When you add the first column to the receiver the selector is restricted to that type. But when you clear the receiver the selector should now reset to show all columns. Instead it is fixed to the first type set and you can't add different types of columns. The restriction just needs to be removed when the receiver is cleared, this is working correctly on other dialogs e.g. two variable summarise, so should be simple to fix.

**Comment by Muthenya** [comment]
I've just gone through the issue and I've also tried to see how the two variable summarise is working but I've realized that it has the same problem as the replace values dialog, which is that when you clear for the factor type, the selector resets to show all columns but for the numeric type, the restriction is not removed.

@dannyparsons do you have a different dialog that has the same restriction and is working correctly?

**Comment by dannyparsons** [comment]
Thanks for spotting this. I thought it was a dialog issue but it was an issue with the single type option was working in receiver. This should now be fixed, please check.
