### ISSUE TITLE
Filter problem

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4917]
I wonder where we re now on the small improvements to filter, including the dates and particularly the pull-down for TRUE and FALSE.

I gave a workshop today over skype and it went pretty badly.  That means we can learn more.  We had to do nonnum1 == TRUE.  What happens if you mistype, e.g. **nonnum1 = true**, which someone did?

Answer: It is alright in the sub-dialogue.  In the main dialogue, the only sign that it is not right is the  it says "Preview not available" in the Selected preview filter field.  However OK is available.  Press OK (which someone did) and you get the dire message as follows:

**Cannot retrieve data
Error: Could not retrieve data frame:PluviometrieRegionKenscoff from R. Data displayed in spreadsheet may not be up to date.
We strongly suggest restarting R-Instat before continuing.
OK**   

That's pretty dire.  I think it means it too!  I then tried to change the language back from French to English and it gave me the same message.  It did the change though - which it didn't do (of course) for the filter.

We improve the situation a bit by the proposed changes, because TRUE and FALSE would not need to be typed.  (And they must be in English too, so spelling may be a problem.  

I wonder if OK might not be available without a preview  -or are there situations where there might be an acceptable filter, that cannont be displayed?

And could the problem be trapped earlier, so the message doesn't have to be so serious?

**Comment by dannyparsons** [comment]
That could be trapped to prevent this. Once the improvements have been made you won't be able to put invalid values for logical or date columns like this, so that would prevent this being possible in most cases, but there might still be ways to get this problem which we could prevent.

**Comment by rdstern** [comment]
I suggest this is now resolved.  So I am closing this issue
