### ISSUE TITLE
Script,Log and Output Window Colour Styling

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#4932]
It would be good to enhance the styling of texts in these windows for a better look and feel.  This will also help in usage of the script window as the user will easily see the different components in the commands being executed.

Have a look at possible styling in this comment https://github.com/africanmathsinitiative/R-Instat/issues/4381#issuecomment-419367843

**Comment by dannyparsons** [comment]
To achieve multiple colours a RichTextBox, or similar, will be needed.

**Comment by dannyparsons** [comment]
If substantial changes will be made here I'd also like to consider how the operations for these windows will be display. Currently we have everything on a right click, which is ok, but it's not really a good way to display this for more than a couple of operations. A more visible collection of the operations would be better.

This would need some thought on a good design and isn't for anytime soon.

**Comment by lilyclements** [comment]
To extend on this slightly (after reading #7632), in the script window it would make the script a lot more readable if we had colour changes in the R codes (e.g. comments colours, `if`/`else` colours, etc). 
Perhaps as well, but this is a "luxury", offering different skins (or skin options).

**Comment by lloyddewit** [comment]
Fixed in PR #7871
