### ISSUE TITLE
Unwanted items in climatic Menu!

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#4941]
My recent check on climatic menu shows that some items have been added. Is this intentional? if not then this items should be removed.
**climatic>file>shaps!
climatic>maps**

**Comment by rdstern** [comment]
You are right.  These 2 items should be removed.

**Comment by shadrackkibet** [comment]
Great. I can remove this quickly.

**Comment by shadrackkibet** [comment]
@jackykemboi  Sorry, please go ahead and remove this items.

**Comment by jackykemboi** [comment]
I have remove the these items.
@maxwellfundi  Kindly merge
