### ISSUE TITLE
Adding the Taylor diagram to R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4944]
I am not sure if the plotrix package is already installed.  It is in my version of R-Instat.  If not, then I don't really mind if it is installed for the following work, or not.
It has a lot of plotting features that users of R-Instat may value.  One example, from our recent Pretoria workshop is **Taylor diagrams**.  It also has Gantt charts and Australian Met style wind roses.

It is a big package with lots of features and lots of authors including Hadley Wickham.  But the graphs are not ggplot2 graphs.  So I don't expect us to want to do lots of dialogues - at least in the near future.

Instead I propose that they form examples for the "tweaking R-Instat" guide, where these could be done either through our script window, or through moving to RStudio.  And the guide I am writing for AIMS (and now also for Met Services) could give examples.
(This started as a request for the plotrix package.  I think this is now added, but the t=Taylor diagram still remains to be included.  Hence the change of name of this issue.)
It is also useful, to explain some of the complications in R that R-Instat has hidden from users.  For example the Wind roses needs the data in a matrix, rather than in 2 columns, which is the situation with our example and other wind roses.  So it is a good opportunity to explain this sort of stuff.

If plotrix is already installed, then that's fine.  Otherwise this section in the guide can cover adding a new package.

**Comment by dannyparsons** [comment]
It could be a good example of using R functions, if the package is big presumably we're not going to implement all of it's features. I still think we consider which parts could become dialogs, **Taylor Diagrams** for example I think is a good candidate for a dialog if its valued. 
I am ok with non ggplot graphs, especially for very specific plots like Taylor Diagrams and then we just use the function as is, without worrying what it doesn't have that ggplot does.

I wonder how positively it would be received by MET Services if there are useful features that are only accessible by writing commands - possibly tweaking commands is a better thing to show than adding things from a new package (although could be in an Advanced section since some will be keen to move to R)

**Comment by Ogik99** [comment]
@dannyparsons  could we start with initial implementation of the taylor diagrams as we consider other features

**Comment by dannyparsons** [comment]
It is something that has been asked for so I'm happy with having a dialog for it. @rdstern may not agree.
If it is to become a dialog it probably isn't high priority right now.

**Comment by rdstern** [comment]
I suggest the Taylor diagram could now be added.  We could usefully consider whether the version from plotrix or the one from openair is the better to add.
Neither version is a ggplot2 graph, so it would be good to check the use of the ggplotify package at the same time.
There is also a potential good home for the graph as part of the verification dialogues.  There are graphs with the verification package together with a possible dialogue being tested about there inclusion.  We could also usefully also consider the graphs included with the hydroGOF package at the same time.

**Comment by shadrackkibet** [comment]
I am now starting work on this. @rdstern I thought of including this under **Climatic>Prepare>** under the new dialog **Compare: Summary** then below **Compare: Taylor Diagram**.

**Comment by shadrackkibet** [comment]
I drafted the design for this dialog as shown below.

![IMG_20200625_145555_300](https://user-images.githubusercontent.com/26301973/85718452-36c0be00-b6f7-11ea-82f8-c206e70861b6.jpg)

**Comment by rdstern** [comment]
@shadrackkibet as far as I can judge the layout seems fine.  We have elsewhere got, for example Describe > One Variable > Summarise and then Describe > One Variable > Graph underneath which is the same structure that you are proposing.  That might point towards the dialogue being a bit more general, in which case the Taylor might be a button.  It might then be Taylor and Other even.  For now I am happy that the work starts with just Taylor.  For any other graphs it could be sensible for an intern (probably not you) to see the set that is proposed in Verification and hydroGOF (and hydroTSP).  Then evaluate whether a) some might be included as they stand.  b) Whether ggplotify works with them and what that means  c) Whether they are simple enough that writing the corresponding ggplot2 code would be better and d) what other graphs might be added, e.g. boxplots, density plots, scatterplots.

On another point I am getting really happy with these additional dialogues being done reasonably quickly (as you are doing).  Together with the intern's current work, so they can test development branches this means that more of the evaluation work can be done within R-Instat.
