### ISSUE TITLE
Frequencies no longer works

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4946]
I open our diamonds dataset from the library.  I am using the latest merged R-Instat.

I try Describe > Frequencies with any variable.  I now get:

**Error running R command(s)
Error in .subset2(x, i, exact = exact) : subscript out of bounds
The error occurred in attempting to run the following R command(s):
.temp_val <- capture.output(sjPlot::sjtab(data=data_book$get_columns_from_data(data_name="diamonds", col_names="table", force_as_data_frame=TRUE, remove_labels=TRUE, drop_unused_filter_levels=TRUE), show.summary=FALSE, digits=0, ignore.strings=FALSE, auto.grp.strings =FALSE))
OK**

**Comment by rdstern** [comment]
I just checked and the default - change sjPlot::sjtab into sjmisc::frq and data= into x= .  Check on other options, because the names may be different - I got rid of them all and then it works!
a) With the default of the new out= argument it comes into the output window - hooray.
b|) But when I changed to Viewer (rather than Browser) it still came into the browser.  I hoped that the html might also come into the output window.

So a relief that the change could be easy - and an improvement!

**Comment by shadrackkibet** [comment]
Will it be good to have options to output this?  I am suggesting we have two radio buttons:
- **Output as HTML**- This will give output in the browser.
- **Print Result to Output**- This will just print results in the output window.

**Comment by shadrackkibet** [comment]
Currently having `out="browser" `or `out="viewer"` gives output on the browser. So i think we should have this three options but disable **Output as HTML to a viewer** option.

**Comment by dannyparsons** [comment]
Even if the call type is set for the html table, 4 I think? I was hoping one of those would work.
