### ISSUE TITLE
Improve the Two Variables and Three Variables > Frequencies dialogues 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4951]
**Is your feature request related to a problem? Please describe.**
This currently puts the table only in a browser.
The graph has a useful feature, that could be added to include facets.

**Describe the solution you'd like**
For the table it now has an option to put an HTML table in the output.  It would be good to include that.  I am not sure how to do that, but @dannyparsons says it should be easy, or at least possible.  It is odd that these commands are the only ones that put the results into a browser.  Perhaps there should be further discussion on whether that option is kept, perhaps in the sub-dialogue?
For the graph, adding a tick box (at this stage) for would be useful and should be easy.  It just adds facet.grid = TRUE.  Perhaps that might be in the sub-dialogue, on the graphics tab?

**Additional context**
I have always felt that the facility to easily add counts and/or percents to the graphs is useful.  (And frustrating that there seems no control on the size of the font for these, nor can we get rid of the % sign or alter the number of decimals.)  I now find that having the coord flip, plus the option of facets can give presentable graphs - see below for the diamonds data:

![diamonds frequencies](https://user-images.githubusercontent.com/11226469/45535315-f9c35a00-b7f5-11e8-9a66-c1796ddf718c.jpeg)

**Comment by dannyparsons** [comment]
These look much better than the current. I would suggest we make this the default behaviour and that is already an improvement.

**Comment by Muthenya** [comment]
This is the current implementation of the facet.grid option and I've set it as the default. @dannyparsons I need your help on having the HTML table on the output window.

![image](https://user-images.githubusercontent.com/32125033/46608132-591e3c80-cb0c-11e8-97f8-4b7a280d565a.png)

**Comment by Muthenya** [comment]
@rdstern just for clarification, the facet option is only for the **Count** option in the **Graph Frequencies** ?

**Comment by dannyparsons** [comment]
We are still yet to get the tables to display in the output window with these functions so I don't think we can do anything other than a browser still for now.

**Comment by dannyparsons** [comment]
Yes that sounds fine.

**Comment by Gioche6** [comment]
@rdstern , On the Options for the two Variable frequencies, I am thinking of including more graph options like dot, boxplot and violin. They have since been added to the function. I have tested them using the existing code and they are produced well. 

I also noted the current option for line has been disabled for an error it produced. Well, a line option is only used for a line-styled histogram, for which the histogram option does not apply to grouped frequencies in this function. 


Here's where I plan on placing them
![snip8](https://user-images.githubusercontent.com/73229979/141078516-3a2bbc0d-2edb-4702-ba02-f6a7c384e86a.jpg)
.

**Comment by rdstern** [comment]
Great.  This all sounds and looks good

**Comment by rdstern** [comment]
@Gioche6 I am re-opening this issue so we combine the two dialogues and then get rid of the Describe > Three Variables menu.
My main suggestion is that this should be a 3-stage process.  First we improve and test the Three Variable dialogue.
Second we will move it the the current place occupied by the Two Variable Frequencies.
Then we delete the Three Variable menu item (assuming the same has been done for the pivot tables.
Here are my suggested changes:
a) The Name of the dialogue becomes just Frequencies. 
b) Possibly move the first 2 controls on the right-hand side up a bit.
c) Add a checkbox `3/4 Way Frequencies`.  Default unchecked.
d) When unchecked, the 2 grouping controls are not visible.  They become visible when checked.
e) The `Weights `checkbox is disabled in the dialogue.  It is enabled, and seems to work fine in the 2-way frequencies.  It would be good to enable it here too.  I don't know if the code is then there, but I hope so.

It would be good if you could do this first stage, i.e. improve the 3-way frequencies where it is now, so it is ready for a take-over to accommodate both 2-way and 3-way later.
