### ISSUE TITLE
Cumulative distribution on Climatic > Prepare > Transform

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4969]
This is probably a separate **Cumulative** button at the top of this **Transform** dialogue, perhaps at the start.  It would be good to discuss with @volloholic and @dannyparsons may add to this entry.

It is "simply" the cumulative sum, just as we can already do in the calculator.  It is on the Transform keyboard where there is cumsum, cummean, cummax, cummin.  For now I can only think we really need the cumsum, but it will be almost as simple to give them all at the same time.
The part that is not possible with the calculator is that we want to start the cumulative feature again each year and in each station.  
We may want to consider what happens when observations are missing.  The only simple action  is that the cumulative values are then missing from the first missing value to the end of that year..  
Once we have these cumulative sums (in another column) then we can see later how to move towards making the graphs shown in #4285 easier to produce.
If we want to "get clever" then the options I could think of are:
a) to be able to use the shifted year, rather than the January-December year, i.e. whatever is used in the Define Climatic Data.
b) Be able to start cumulating (and possibly end) within the year, rather than at 1 and 366.  In that case, all days up to the start day are (I assume) zero, and all days at the end are the value on the last defined day. (This is OK for the sum, but may not be sufficiently general.  Perhaps they have to be NA?)

**Comment by dannyparsons** [comment]
If we use the base `cumsum()` function then it deals with missing values as you stated. 
The dialog already has station and year receivers - so the year could be shifted year column, which is your a).
b) would be possible with our own function - I think probably getting it to work in the normal way is still where we should start.
I was wondering whether sum, max, min, product are options in a combo box, like we have for the Moving option? It would just be a simple switch of function.

**Comment by rdstern** [comment]
Great.

Yes, I was assuming the options in a combo box may be very little extra work over doing it for just the sum.

**Comment by Muthenya** [comment]
This is the current implementation.

![image](https://user-images.githubusercontent.com/32125033/46024266-13ff1100-c0ef-11e8-9fb0-d1f98e439771.png)

**Comment by rdstern** [comment]
Great
