### ISSUE TITLE
Adding Julian day numbers to Make date dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4974]
**Is your feature request related to a problem? Please describe.**
This is another possible option when there is a single column for the day number and you specify the origin.  There are currently 3 options, namely Excel, Gregorian and Specify.  The data from CHIRPS, etc (from IRI data library have the date column (via NetCDF) as Julian day number.  This is when the origin is 1 January 4713BC.  So 1st January 1981 is day number 2444606.   

**Describe the solution you'd like**
With the current dialogue I first subtracted 2436204.5.  This makes the 1st January 1958 as day 0.  Then I used the existing dialogue with that as the start.  Worked fine.  
That's not how I would program it mind!  It says (Wikipedia) that floor (JD − 1721424.5) = Gregorian day number, which we have.

I hope this might be a quick addition - who would like to take it?

**Comment by dannyparsons** [comment]
@shadrackkibet this should just be another option in the combo box assuming this can be done with the origin parameter? Have a look online to see how others do this for R. If it's anything more complicated than that I suggest leaving it till next version.

**Comment by dannyparsons** [comment]
Here is a solution to this https://stackoverflow.com/a/52309820/6424231

The code is:
```
as.Date(2444606, origin = structure(-2440588, class = "Date"))
[1] "1981-01-01"
```

So we can just add another item to the "Origin" combo box for "Julian Day Number" and use this code in that case.

I've assigned to @Wycklife. Check with @maxwellfundi if you need support.
