### ISSUE TITLE
Add Key dialog

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#4976]
**Describe the bug**
When add key dialog is loaded for the first time Button check unique is enabled. when you click on this you get a bug which is undesirable. So i think this should be disabled as long as the multiple receiver is empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/26301973/45930349-b42a2e00-bf67-11e8-9fc1-48d053773109.png)

**Comment by dannyparsons** [comment]
Agreed, good point.
