### ISSUE TITLE
Help IDs on R-Instat's windows

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4977]
I have added help IDs (and a current blank help) on the different windows in R-Instat.  I don't know whether there will be sufficient improvements in the help file for the update this week, so I have made this a 0.4.24 item.  But the Help Context numbers can be added anytime.  They are as follows:  (I have also given the Help IDs, but I think it is the context numbers that are usually used in the code. 

Spreadsheet (Data View) - Help Context: 134 Help ID: SpreadsheetDataView
Output Window - Help Context: 540 Help Context: OutputWindow1
Log Window - Help Context: 541 Help Context: LogWindow
Script Window - Help Context: 542 Help Context: ScriptWindow1
Column Metadata - Help Context: 543 Help Context: ColumnMetadata2
Data Frame MetaData - Help Context: 544 Help Context:  DataFrameMetadata2

**Comment by Patowhiz** [comment]
All the dialogs outlined here are yet to be fixed. This should still be open.
