### ISSUE TITLE
Help IDs on File and Prepare Menus

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4978]
In **File Menu:**
**Open NetCDF**: Help Context Number is 393
Export > **Export R Objects**: Help Context Number is 554
Export > **Export R Workspace**: Help Context Number is 555
Export > **Export Graph as Image**: Help Context Number is 556

In **Prepare Menu**, this is on the Check Data dialogues:
**Duplicates** : Help Context Number is 547
**Compare Columns**: Help Context Number is 546
**Non-numeric Cases**: Help Context Number is 545
**Anonymise ID Column**: Help Context Number is 552

**Comment by shadrackkibet** [comment]
Working on this.

**Comment by shadrackkibet** [comment]
I have added this help IDs  but seems not work, is there something that needs to be updated for this to work?

**Comment by rdstern** [comment]
For now they won't work.  I have updated my version of the help file, but just on my machine and not even used it yet to produce a chm file.  It is only when this new version is included that the help will go to the right place.  

For now it is enough for the numbers to be added or changed as given in the issues.  

Then I will check later, once the help file is updated.
