### ISSUE TITLE
Help IDs in climatic menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4981]
On the **Climatic > File Menu**

The first is **Import Shape Files**.  Question:  Should it be plural?  I suggest **Import Shape File...** as we only import a single file at a time.  Within the dialogue it is written as Import Shapefiles.  Should it be **Import Shape File** again.
Anyway the Help Context number is 557.

While on the mapping the Dialogue **Check Data > Station Maps** has Help Context number of 558.
And **Check Data > Display Daily** Help Context number is 361.
**Check Data > QC Rainfall** Help Context number is 511
**Check Data > QC Temperatures** Help Context number is 559

In **Tidy and Examine > Tidy Daily Data** Help Context number is 561
In **Climatic > Prepare > Convwesions** Help Context number is 563
In **Climatic > Prepare > Compare** Help Context number is 562
In **Climatic > Prepare > Length of Season** Help Context number is 564
In **Climatic > Prepare > Evapotranspiration** Help Context number is 565
In **Climatic > SPI** Help Context number is 566
In **Climatic > PICSA > Rainfall** Help Context number is 118
In Climatic CM SAF > Plot Region Help Context number is 568
In Climatic CM SAF > Export to CM SAF R Toolbox is 569

**Comment by shadrackkibet** [comment]
@JacklineKemboi is now working on this.

**Comment by shadrackkibet** [comment]
This  can now be closed.
