### ISSUE TITLE
Help IDs in Options by Context Menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4982]
**Define Options by Context Data**.  Help Context is 572
**Prepare > Calculate Difference Between Options** Help Context is 581
**Describe > Compare Two Options** Help Context is 585
**Describe > Compare Multiple Options** (Dialogue not yet enabled) Help Context is 586
The current Model Dialogues seem odd to me.
**Model > Fit Model** looks pretty general to me, but it currently goes to the Model > Three variable > Fit Model Help.  The current Help ID in the dialogue must therefore be 369.  It looks like a special dialogue, so does it have its own help?  If so, then the Help Context for the dialogue in the Options by Context menu is 588.  If it should go to the same help as the Model > General > Fit Model, then that Help Context is 371.

There is also a menu item Model > General Fit Model.  Perhaps that should be just a copy of the same dialogue as Model > General > Fit Model.  Currently it doesn't provide a dialogue, though the menu item is enabled.  What should it do?

I have copied @dannyparsons , because of this last point.

**Comment by dannyparsons** [comment]
Yes fit model should have its own help and the General could go to the General Model dialog

**Comment by shadrackkibet** [comment]
This can also be closed.
