### ISSUE TITLE
Recode Factors among the options upon Right click on column

### ISSUE THREAD

**Issue by mmumbo** [africanmathsinitiative/R-Instat#4987]
Recode factor is so powerful and frequently used feature that should be easily available on just a  Right click to the column name besides being on **Prepare>Column:Factor>Recode Factor**
This was recommended after a discussion with @volloholic  on the same

**Comment by Muthenya** [comment]
If this is agreed I can get to it.

**Comment by dannyparsons** [comment]
We have mentioned that the right click is already quite long. I think we need to decide how we judge what is common enough for the right click. For some data I'm sure **Recode Factor** is used a lot but I'm not sure in general.

**Comment by Muthenya** [comment]
Is this still awaiting further discussion?

**Comment by dannyparsons** [comment]
My opinion would be to not have it on the right click menu. While it's an important dialog, I would think you usually only reorder the levels once and keep that order once you're happy with it. 
I think the right click should be reserved for dialogs that you might use multiple times, like convert. Once you've gone to reorder from the menu once, its in the last dialog shortcut if you need to use it again for other columns.

**Comment by Muthenya** [comment]
I agree @dannyparsons.
