### ISSUE TITLE
Removed unused levels.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#4993]
**Describe the bug**

Why is OK enabled when there is no unused level?. I think it should be disabled!
![image](https://user-images.githubusercontent.com/26301973/46164942-fb7e2a80-c297-11e8-996e-0d97c27339c0.png)

**Comment by dannyparsons** [comment]
I can think of a case you want it to be enabled.
If you're preparing a script to be rerun again, maybe on different data, then you might want to ensure no empty levels, even if your current data doesn't have any, you want it in the script in case it does when it's rerun.

I hadn't thought about this before so it was good to bring up. I don't think that's the reason it is enabled currently but I think we should keep it!
