### ISSUE TITLE
Extending the missing option in the summary statistics dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5006]
**Is your feature request related to a problem? Please describe.**
The missing option is working well in the summaries now.  However it does not cope with the (common) climatic system when data does not start in January, or end in December. 
However the summaries for climatic have the useful feature that the years and months) are (almost) each the same length.
I propose a simple extension to the setting of summaries to missing.

**Describe the solution you'd like**
This goes on the missing tab.  Currently the summary is set to missing if there are too many missing values on a group. 

I'd like the option added to set the summary to missing if the number of non-missing values is too low.

So, for annual summaries you can now have the result is set to missing if num_miss > 25.  The new option is identical except it is if num_nonmiss < 340.

It is a third radio button on the missing options.
The first becomes **Number Missing**.
The second becomes **Percentage Missing**
The new third one becomes Number Not Missing

If you choose it then the line reads: "Summary set to missing when there are less than this value"

Possibly when there are less observations than this value.

I am hoping this might be easy?  If not, then change the milestone!

**Comment by dannyparsons** [comment]
This shouldn't be difficult yes, it's just a slightly different version of the max number of missing.
