### ISSUE TITLE
Add x axis label angle to bar chart + mosaic main dialogs

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5010]
**Is your feature request related to a problem? Please describe.**
When doing bar charts, and now mosaic plots, with a large number of categories and/or long category labels the labels on the x axis often overlap. Finding this option in themes is complicated.

**Describe the solution you'd like**
An option on the main dialog to make the x axis labels angle 90. This could be a simple checkbox to have the angle set to 90.

**Describe alternatives you've considered**
A checkbox also with an nud to specify the angle, where the default is 90 when checked. More flexible than the first option but more complex.

**Comment by dannyparsons** [comment]
This is done on Mosaic Plots but not Bar Chart. This would be a good task for @africanmathsinitiative/developers. The implementation should be very similar to what is already there for Mosaic Plots which is a checkbox also with an nud.

**Comment by Ivanluv** [comment]
@rdstern would this be needed for boxplots too?

**Comment by rdstern** [comment]
It would also be useful for boxplots.

But @dannyparsons and @maxwellfundi what has happened to the idea of having some of the common options on themes on the main themes tab?  I am happy that this could be so common an option for the  bar charts and mosaic plots that it goes on the main dialogue.  In general I was happy that (for other graphs) this could be on the main themes tab.

**Comment by Muthenya** [comment]
I've noticed that the default value for the angle in the plots subdialog is 10 degrees. Could we make them equal such that both the values in the nuds are 90 degrees, or is there a reason for the 10?

**Comment by Ogik99** [comment]
This issue was already resolved using #5141 
This can be closed.
