### ISSUE TITLE
Enhance the Duplicate Column dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5011]
**Is your feature request related to a problem? Please describe.**
When a column is duplicated it would be good to be able to change the type of the column at the same time.  That's often why you want a duplicate.

**Describe the solution you'd like**
This was the one dialogue that could choose the place for the new variable.  That is now redundant.  So the same position in the dialogue could be used to select the new type of the column.

This is simply a set of radio buttons.  I assume some of the code can be the same as the Prepare > Data Frame > Convert Columns.

It is in the same box now used for **Position of Duplicated Column** with the label now saying **Type of Duplicated Column**.  The first and default is Same as Original Column.
Then the other types?
Nice to include Date if default format?

**Comment by Patowhiz** [comment]
@rdstern apart from the date(which I'm not sure on how that can be solved in this dialog), the rest of the issue was solved. 

![dlDuplicate](https://user-images.githubusercontent.com/21179007/86090570-fd030500-bab2-11ea-9ff1-5efa0e72228c.JPG)

**Comment by rdstern** [comment]
@Patowhiz I agree that this can be closed.
