### ISSUE TITLE
PICSA Rainfall Graph Lines needs improvement 

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#5015]
**Describe the bug**
When we have multiple stations and include facets, then add the mean line/median etc it produces a single line which is in all graphs other than producing different lines for each of the facet. 

**To Reproduce**
1. Go to Climatic >PICSA > Rainfall graph
2. Add your variables in the receivers 
3. go to plot options 
4. Add facets click return
5. go to PICSA options sub dialog
6. CLick on the labels tab, then add the mean line
7. Click return 
8. Click OK on the main dialog

**Expected behaviour**
Each graph for different station needs to have a different line because values are diffrent. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9798689/46599716-b6a49000-caf0-11e8-99ae-9a15cb6567ad.png)

**Comment by dannyparsons** [comment]
Here's my response from here https://github.com/africanmathsinitiative/R-Instat/issues/4605#issuecomment-427114922

> According the this question and the ggplot2 documentation the way to do this is either create the summary data frame and use that for the lines or create columns for the summaries in the same data frame. Neither of these are ideal but adding the summaries to the same data frame is probably easiest for us.
> It would be a bit easier if it was always by station but since the sub dialog is accessible it will do strange thing if the facets are changed there. Doing it for general facets is not much harder.
> 
> The code would then change to:
> 
> ```
> dt <- dt %>% group_by(station) %>%
>   mutate(med = median(y))
> 
> ggplot(dt, aes(x = x, y = y)) +
>   geom_boxplot() +
>   geom_hline(aes(yintercept = med)) +
>   facet_wrap(~ station) +
> ```

**Comment by rdstern** [comment]
I think this has now been addressed.  Can it be closed?
