### ISSUE TITLE
PICSA Rainfall dates labels on Y axis have issues with facets

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#5016]
**Describe the bug**
When you create a PICSA Rainafall graph with an one of the options of format as date selected then later add facets throws an error shown below. (sometimes with a swap of order then it works)

**To Reproduce**
1. Go to Climatic >PICSA Rainfall Graph
2. Fill in the all the receivers 
3. Click Ok to produce the graph
4. Go back to PICSA rainfall main dialog, go to PICSA Options and select the format as Date options and select Day Month(1 jan) and Click return
5. Click Okay
6. Go back to PICSA rainfall main dialog then click on Plot options and fill in a facet and click return 
7. Then click OK

**Expected behaviour**
The y axis for the facetted graphs should be in date format selected in PICSA Options subdialog format as date option. 

**Screenshots**
If applicable, add screenshots to help explain your problem, particularly of error messages.
![image](https://user-images.githubusercontent.com/9798689/46600397-b60cf900-caf2-11e8-83d9-0a060d0fbbd2.png)

**R script or commands**

`# Code generated by the dialog, PICSA Rainfall Graphs
Rwanda_daily_RR_Temp1981_2018_by_Station_Name_year <- data_book$get_data_frame(data_name="Rwanda_daily_RR_Temp1981_2018_by_Station_Name_year")
last_graph <- ggplot2::ggplot(data=Rwanda_daily_RR_Temp1981_2018_by_Station_Name_year, mapping=ggplot2::aes(x=as.numeric(x=year), y=as.Date(x=sum_PRECIP, origin="2015-12-31"), colour=Station_Name)) + ggplot2::geom_line(size=0.8) + theme_grey() + ggplot2::theme(panel.background=ggplot2::element_rect(colour="white", fill="white", size=0.5, linetype="solid"), panel.grid.major=ggplot2::element_line(colour="lightblue", linetype="longdash", size=0), panel.grid.minor=ggplot2::element_line(colour="lightblue", linetype="longdash", size=0), panel.border=ggplot2::element_rect(colour="black", fill="NA", size=0), axis.text.x=ggplot2::element_text(angle=90), axis.title.x=ggplot2::element_text(size=14), axis.title.y=ggplot2::element_text(size=14), title=ggplot2::element_text(size=20), plot.subtitle=ggplot2::element_text(size=15), plot.caption=ggplot2::element_text(size=8)) + ggplot2::geom_point(size=3, colour="red") + ggplot2::xlab(label="") + ggplot2::ylab(label="") + ggplot2::scale_y_date(date_label="%d %b") + ggplot2::scale_y_continuous(breaks=seq(from=, to=, by=)) + facet_wrap(facets= ~ Station_Name, dir="h")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="Rwanda_daily_RR_Temp1981_2018_by_Station_Name_year")
data_book$get_graphs(data_name="Rwanda_daily_RR_Temp1981_2018_by_Station_Name_year", graph_name="last_graph")`

**Comment by dannyparsons** [comment]
@stevenndungu @maxwellfundi I guess this is now resolved with the current changes, but can you check?

**Comment by stevenndungu** [comment]
I have tested this..i did not get any error. The reviewer can confirm though

**Comment by Carolnikie** [comment]
Have tested it too and didn't get any error.

**Comment by stevenndungu** [comment]
Thanks @Carolnikie for testing. I just a small code tidy up to do from Danny's comment. Actually let me finish up with now.
