### ISSUE TITLE
QC Rainfall dialog Consecutive option needs a threshold 

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#5017]
**Is your feature request related to a problem? Please describe.**
The Consecutive QC Option needs a threshold option

**Describe the solution you'd like**
its desirable that the consecutive option on this dialog have an NUD where the user can select the threshold of the rainfall they want to consider for the consecutive number of days. 

**Additional context**
![image](https://user-images.githubusercontent.com/9798689/46601828-13a34480-caf7-11e8-9bb4-cacfd636e5f7.png)

**Comment by rdstern** [comment]
In my list of tasks for the rainfall I agree that the consecutive could do with a threshold value.  Perhaps Shadrack could also check for the omit zero in the outlier.  Maybe they could be the same threshold and just set once.  So the threshold box - already there, moves left and is always visible.  Default is 0.05.

The Outlier option which is currently Omit zero becomes "Omit below threshold"
The text on consecutive goes over 2 lines and is (ignoring below threshold).

**Comment by rdstern** [comment]
Could there also be testing of the dry month option.
a) So when there is the sub-dialogue it doesn't initially have the first month ticked.
b) There is a check on the problem that sometimes (I think usually if the threshold isn't changed) the result is null, i.e. there are no months in the output file - when there should be, from the data.

**Comment by shadrackkibet** [comment]
> **Is your feature request related to a problem? Please describe.**
> The Consecutive QC Option needs a threshold option
> 
> **Describe the solution you'd like**
> its desirable that the consecutive option on this dialog have an NUD where the user can select the threshold of the rainfall they want to consider for the consecutive number of days.
> 
> **Additional context**
> ![image](https://user-images.githubusercontent.com/9798689/46601828-13a34480-caf7-11e8-9bb4-cacfd636e5f7.png)

The duplicate issue here #6228. 

> Could there also be testing of the dry month option.
> a) So when there is the sub-dialogue it doesn't initially have the first month ticked.
> b) There is a check on the problem that sometimes (I think usually if the threshold isn't changed) the result is null, i.e. there are no months in the output file - when there should be, from the data.

a) Fixed here #5914
b) Fixed here #6179

> In my list of tasks for the rainfall I agree that the consecutive could do with a threshold value. Perhaps Shadrack could also check for the omit zero in the outlier. Maybe they could be the same threshold and just set once. So the threshold box - already there, moves left and is always visible. Default is 0.05.
> 
> The Outlier option which is currently Omit zero becomes "Omit below threshold"
> The text on consecutive goes over 2 lines and is (ignoring below threshold).

Moved this here #6228 where it belongs.
