### ISSUE TITLE
Changes in the climatic menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5021]
I collect together suggested changes following the Rwanda workshop:
1. Add Stack, Unstack, Append to the Climatic > Tidy and Explore menu.  Together with Merge they are in a small separate section (i.e. horizontal lines round) in the same order as in Prepare, i.e. Stack, Unstack, Merge, Append.
2. Promote and rename the **Climatic > Check Data > Station Maps** to the last item in the **Climatic > Describe** section.  Irt will no longer be station maps.  Let's call it **Mapping...**.
3. Demote the CLIMDEX and SPI indices to the Climatic > Prepare menu.  They are a little section by themselves in the order CLIMDEX, then SPI, just above Evapotranspiration but with a horizontal line to separate.

**Comment by Wycklife** [comment]
@rdstern I have made the changes and i'm asking whether to change the name Tidy and Examine to Tidy and Explore.

**Comment by rdstern** [comment]
Thanks.  Let's leave it as it is now.

**Comment by Wycklife** [comment]
Okay

**Comment by rdstern** [comment]
Thank you for the changes. 

I re-open this issue, because one item could have more prominence.

I was thinking of the Mapping dialogue at the bottom of the Describe section of the climatic menu, rather than under Climatic > Describe > Mapping.

I would like it one level up, i.e. as **Climatic > Mapping** , and just below Climatic > CM SAF.

Thanks
