### ISSUE TITLE
Adding a rugplot to the PICSA rainfall graphs

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5024]
**Is your feature request related to a problem? Please describe.**
The rainfall dialogues on the start and and length of the rains can each produce a logical column.  It would be good if this could also be displayed on the PICSA rainfall graphs

**Describe the solution you'd like**
A rug-plot [see here](https://ggplot2.tidyverse.org/reference/geom_rug.html) would seem ideal.  It would need an additional layer, either in the PICSA options or on the main dialogue.  I suggest an additional tab in the PICSA options, because there will be details of the size and colour of the rug.

**Comment by Ogik99** [comment]
@dannyparsons any additional comments on this.

**Comment by rdstern** [comment]
I hope this can be discussed in the next 2 weeks.  I now realize there are too many issues on this topic!
In #5039 I describe what is remaining and then in #5094 I show my version of a rugplot - which looks quite nice, while in #5120 I discuss some remaining issues.  In #5120 I also wonder about an alternative to the rugplot - though perhaps the alternative and the rugplot could be options.

I am not sure about closing some of the others yet, but suggest this one can be closed.  Having said that - thanks to @Ogik99 for raising the issue now.  Very timely, Yvonne.  Thank you.
