### ISSUE TITLE
Facet by Station in PICSA rainfall graphs

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5025]
**Is your feature request related to a problem? Please describe.**
We often wanted this, and it isn't difficult to go to the plotting options with the current dialogue.

**Describe the solution you'd like**
Either a field on the main dialogue with Facet by Station.  Or a copy of the facet tab on the PICSA options

**Comment by Ogik99** [comment]
@dannyparsons can we go ahead and implement facet option for PICSA rainfall graphs

**Comment by rdstern** [comment]
This is already available in the current dialogue.  I suggest this can be closed
