### ISSUE TITLE
Start of the rains not working well with missing values

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5044]
**Describe the bug**
The start of the rains has a date column and also gives the day number in the year of the start.  They cope inconsistently with missing values in the data.

There may be 2 separate problems.  The one today was on data from Tanzania.  A small sample was sent to Lazarus  It can be used to solve these problems by AMI, but is not then to be shared.

What is clear from the problem today is that the start date ignores missing values, while the day number correctly allows for them.  That's one problem.

The second problem is that, in addition the day number is too cautious, namely if there is a missing value in the year, (or shifted year)  long before the earliest start date, then it still gives missing.
.
**To Reproduce**
In the data sent, 

a) Make the logical columns numeric
b) Tidy the data using Climatic > Tidy > Tidy.
c) Get the shifted year, month doy_s from August.
d) Go to the start with the definition from 1 Nov to 29 Feb of 20mm in 3 days
e) The date and the doy for the start should be consistent.  The doy is correct and the date has ignored missing values.

Now the second problem.  In 2003-4 the startdoy is correctly missing, because Octobr is missing, and hence we don't know the situation on 1st Nov - which is the earliest day considered.

Now change the earliest day to 15 Nov.  In this case the missing in October is irrelevant.  But the startdoy in that year is still missing.

**Expected behaviour**
The two columns should be consistent, both taking proper notice of the missing values.

I guess this could be tricky and may need @dannyparsons or @volloholic to help?

**Comment by dannyparsons** [comment]
These should all be now fixed.
