### ISSUE TITLE
Dialogue for the visdat package

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5064]
I propose this as a new dialogue.  It seems very simple as there are few options - but extremely useful.

The precise layout of the dialogue needs to be discussed.  I suggest there could be a single dialogue for the 3 functions visdat::vis_dat, vis_miss and vis_guess

We can choose between a whole data frame and selected columns in each case (I hope).  And it would be possible to filter also.  In each case it produces a ggplot.

It would go into Prepare > Check Data > Visualise Data.  It could be at the top.  It could also be at the top of the Climatic > Tidy and Examine menu.> Visualise Data

There could then be the three radio buttons Data, Missing and Guess.
Then a checkbox, default checked Whole Data Frame.

If checked, then it just gives the data frame control.  Otherwise it gives our usual control with the columns.  There is also a multiple receiver.  No receiver is needed if the whole data frame.

Then there is a different Options box for each of the three cases.  There aren't many options, so they can all be there.

Then the save graph and that's it!

The code should be simple - I was able to try it all using the Script window - for whole data frames that is.
I suggest this could be a nice small project for one of the new programmers.  Wait though, till Danny has commented on the idea and the structure of the dialogue.

**Comment by rdstern** [comment]
Here are some examples with data from Malawi.

This is the default for vis_dat  

![mzimba1 showing missing and types of data](https://user-images.githubusercontent.com/11226469/47258632-f9257f80-d495-11e8-9c8f-7fe114bc847e.jpeg)

Then here is vis_miss
![missing value plot](https://user-images.githubusercontent.com/11226469/47258646-2b36e180-d496-11e8-8db6-b3ea482087f1.png)

And here is vis_guess with just 4 columns:
![mzimba detecting the character values](https://user-images.githubusercontent.com/11226469/47258649-3db11b00-d496-11e8-8af9-5a6f640630e5.jpeg)

 These are the data:
[MZIMBA1.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2498383/MZIMBA1.xlsx)

**Comment by Ogik99** [comment]
@dannyparsons any further guidance on this

**Comment by dannyparsons** [comment]
These plots all look good. My only question is whether we include any more of these types of missing value plots that come from the `nanair` package described here: https://cran.r-project.org/web/packages/naniar/vignettes/naniar-visualisation.html. Or at least decide how we might split these up into dialogs.

Other plots include `gg_miss_upset`, `gg_miss_var`, `gg_miss_case`, `gg_miss_fct`, `gg_miss_span`, `gg_miss_case_cumsum`, `gg_miss_which`. Some are a bit more complex but look very useful.

Could these all be part of one dialog or split up in a sensible way? I had thought we might split up to have a dialog for general data plots and one for missing value plots but all of these are for missing values except `vis_dat`.

**Comment by Ogik99** [comment]
@dannyparsons I think we can have one dialog with many functions just like the case with the geoms. For starters, we could have vis_guess, vis_miss and eventually add more plots from the nanair package.

**Comment by rdstern** [comment]
I have been discussing this issue with Danny.  We now agree with you as above.
both 
So there would be a single dialogue with options from both visdat and naniar.  We also add the geom_miss_point to the set of geoms, in ggplot.

So, as above, you could start with the dialogue as proposed above, using the three options from visdat.  Once we have each looked in more detail at the naniar options, then we c an examine the order of the buttons that we want.

This will mean that we only get a single graph at a time and we are happy with that restriction.

**Comment by dannyparsons** [comment]
The design should be radio buttons at the top, one for each function - they will need short, sensible names which represent the function.
Then a selector on the left. On the right side two normal radio buttons: 1. Whole data frame 2. Select column. When you select 2. a multiple receiver appears below to choose which columns to include in the graph. If you select 1. it just uses the whole data frame.
At the bottom any additional options for the functions and the usual save control for saving the graph.

I think you can also include `gg_miss_upset`, `gg_miss_var`, `gg_miss_case`, `gg_miss_fct`, `gg_miss_case_cumsum`, `gg_miss_which` on the dialog as they are also simple functions.

**Comment by maxwellfundi** [comment]
This one too moves to next milestone, @Ogik99 is away at the moment

**Comment by Wycklife** [comment]
I've used a different dataset (CSO4.rds) to test this, and it seems to have no error.
