### ISSUE TITLE
Missing parameter(s?) from geom_smooth

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5067]
Colour is missing as a layer parameter for `geom_smooth`. Can it be added to the geom definition? This would be a good time to check if any other parameters are missing from `geom_smooth`.

**Comment by maxwellfundi** [comment]
Great, we will be looking at this today. I remember formula was left out because we did not have editable input textboxes. We can actually revisit that as well.

**Comment by dannyparsons** [comment]
That would be good to look into. The common ones like `colour` are most important to get working.
