### ISSUE TITLE
Small bug on Make Date dialog

### ISSUE THREAD

**Issue by Muthenya** [africanmathsinitiative/R-Instat#5070]
**Describe the bug**
The Make Date dialog has **Ok** enabled even when the receivers are empty. I observed that on the first option, **Single Column**, when **Ok** is enabled there, it's also enabled on the other options.

**Expected behaviour**
**Ok** should be enabled only when the conditions for the specific option are satisfied. In this case, the receivers for the respective options are filled.

**Screenshots**
![image](https://user-images.githubusercontent.com/32125033/47343592-1da87400-d6af-11e8-9d96-a8d7001a719f.png)

**Comment by dannyparsons** [comment]
Good spot thanks. This is a good task for a new programmer.

**Comment by Muthenya** [comment]
@Wycklife you can take this up.
