### ISSUE TITLE
Start of Rains - start date/doy NA values

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#5079]
I had a look into the start of rains bug where if we have a missing value outside of the time interval we are interested in we are given a missing value in the output for `start_doy` but get a start of rains value for `start_date`.
E.g. we are interested in start of rains dates from day 306 to 366, and on day 274 for one year there is a missing value for rainfall. This means that the `start_doy` output value is given as NA.

Part of the issue seems to begin in the following code:

```
start_of_rains_start <- instat_calculation$new(type="summary",
                                               function_exp="ifelse(is.na(ifelse(sum(is.na(Rain))>0, NA, !is.na(start_doy[1]))), NA, start_doy)",
                                               calculated_from=list("Dodoma"="Rain"),
                                               result_name="start_doy",
                                               save=2)
```

The R function being run here is

`ifelse(is.na(ifelse(sum(is.na(Rain))>0, NA, !is.na(start_doy[1]))), NA, start_doy)`

which is basically saying

"If [This Thing] is NA, then replace the start_doy value with NA, otherwise keep the start_doy value"

where [This Thing] counts if there are any missing values in the rainfall. If there are it replaces them with a NA (otherwise it replaces it with a true or false)

From what I can see, this is the part which is checking that there are no missing values in the specified time interval, and if there are any missing values then the start_doy needs to be replaced with a missing value.

The next part is slightly where I've forgotten part of the calculator system. What I suspect is happening is [This Thing] is searching for missing values beyond the time interval specified. This is turn means that it is finding missing values outside of the specified time interval and replacing the actual start_doy value with an NA.

I **think** (but it's been a while since I've worked with the calculator system so a correction would be welcome!) that the following `start_of_rains_combined` tells the above calculation to run for each station and year (`grouping_by_station_year`), and for the time interval specified in the calculation titled `start_of_rains_filter`

```
start_of_rains_combined <- instat_calculation$new(type="combination",
                                                  manipulations=list(grouping_by_station_year, start_of_rains_filter),
                                                  sub_calculation=list(start_of_rains_start, start_of_rains_status))
```

Which means perhaps the bug lays in `start_of_rains_filter` by not specifying the correct time interval to run the check for missing rainfall values in. The `start_of_rains_filter` calculation is given below

```
start_of_rains_filter <- instat_calculation$new(type="filter",
                                                function_exp="doy_366 <= ifelse(is.na(start_doy[1]), 366, start_doy[1])",
                                                calculated_from=list("Dodoma"="doy_366"),
                                                sub_calculations=list(start_of_rains_date, start_of_rains_doy))

```

I don't understand why we are running this calculation. From what I can tell, this is saying that if the start day of rains is a missing value then filter to look at all values less than or equal to day 366. If the start day of rains is not missing, then we filter to look at all values less than the start day of rains.

`doy_366 <= ifelse(is.na(start_doy[1]), 366, start_doy[1])`

I really don't understand why we are running this calculation so don't want to make any suggestions (at this stage) on fixing it. An explanation would be very welcome!

I assume that this is why we are getting missing values however, since this calculation tells the `start_of_rains_start` calculation to replace the first start of rains day with NA if there are any missing values in the interval `doy_366 <= ifelse(is.na(start_doy[1]), 366, start_doy[1])`, rather than in the interval specified by the user (minus a few days depending on their conditions, e.g. Total Rainfall over three days may mean we look a couple of days before the specified interval. I think.).
So I think this function is where the bug lays, and if we fix this interval to contain the correct days then we won't get the NA values when we shouldn't be.

As another point - I don't understand why we are running this `start_of_rains_start` for start_doy and not for start_date?
We have a bug in start_date where we are given the first date of rains despite a missing rainfall value in the doy interval. I think running an equivalent of this for start_date could fix that?

I'm sure this has been reported as a bug elsewhere, but to keep it as one-bug-per-report maybe this one can be discussed here? Otherwise I can copy this into elsewhere.

**Comment by dannyparsons** [comment]
This should now be fixed for start of rains
