### ISSUE TITLE
Option of Not Using a fill when Creating Maps 

### ISSUE THREAD

**Issue by fran2or** [africanmathsinitiative/R-Instat#5084]
**Describe the bug**
You are not able to make a map without selecting a variable to fill (Eg. using districts). It is currently made in such a way that it enforces to put a variable in the **fill** receiver. The **OK** tab is not made accessible to you if the  **fill** receiver is not filled 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Climatic >> Check Data '
2. Click on 'Station Maps'
3. Scroll down to the first data frame which should contain the shape file , adjacent to the receiver you will find the **fill** receiver and then find out the bug described above if you don't fill the **fill** receiver 

**Expected behaviour**
It should allow you create a map without a fill. This is doable if you remove the fill from the script  produced from the **To Script** button
**Screenshots**
**Not the Graph I want**
![image](https://user-images.githubusercontent.com/6714330/47718359-1dc0ea80-dc40-11e8-91b1-c8b8f831740f.png)

**The Graph I want**
![image](https://user-images.githubusercontent.com/6714330/47718556-a2136d80-dc40-11e8-8ef0-6cf4c639515c.png)

**R script or commands**
```
# Code generated by the dialog, Climatic Maps
lso_bnd_admin1_wfp_co <- data_book$get_data_frame(data_name="lso_bnd_admin1_wfp_co")
Lesotho_metadata <- data_book$get_data_frame(data_name="Lesotho_metadata")
last_map <- ggplot2::ggplot() + ggplot2::geom_sf(data=lso_bnd_admin1_wfp_co, ggplot2::aes(fill=adm1_name)) + ggplot2::geom_point(data=Lesotho_metadata, ggplot2::aes(x=longitude, y=latitude)) + theme_grey()
data_book$add_graph(data_name="lso_bnd_admin1_wfp_co", graph=last_map, graph_name="last_map")
data_book$get_graphs(graph_name="last_map", data_name="lso_bnd_admin1_wfp_co")

```
**Correct Script**
```
# Code run from Script Window
lso_bnd_admin1_wfp_co <- data_book$get_data_frame(data_name="lso_bnd_admin1_wfp_co")

Lesotho_metadata <- data_book$get_data_frame(data_name="Lesotho_metadata")

last_map <- ggplot2::ggplot() + ggplot2::geom_sf(data=lso_bnd_admin1_wfp_co) + ggplot2::geom_point(data=Lesotho_metadata, ggplot2::aes(x=longitude, y=latitude)) + theme_grey()

data_book$add_graph(data_name="lso_bnd_admin1_wfp_co", graph=last_map, graph_name="last_map")

data_book$get_graphs(graph_name="last_map", data_name="lso_bnd_admin1_wfp_co")
```

**Details (optional):**
 - Windows 10
 - R-Instat Version [0.4.25]

**Comment by dannyparsons** [comment]
Can you explain first what the reason was for deciding that latitude and longitude should be required?

**Comment by dannyparsons** [comment]
It is also good practice to link to the issue or pull request that you are referring to for the related discussions. I can see a pull request with some of these changes here https://github.com/africanmathsinitiative/R-Instat/pull/5060. Were the discussions on GitHub or just in the office?

**Comment by dannyparsons** [comment]
I agree, that's right. We don't need to try force "interesting" graphs when the simple things might also be useful. Is someone going to take over Jacky's pull request on this?

**Comment by Muthenya** [comment]
I can take this up.

**Comment by dannyparsons** [comment]
@fran2or This is now fixed and will be available in the next released version.
