### ISSUE TITLE
Adding a rug plot to the PICSA rainfall graphs

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5094]
![start with rug plot](https://user-images.githubusercontent.com/11226469/48055625-4ef56980-e1b0-11e8-950f-3e26bc3a6132.jpeg)

I have added (manually) what might be an acceptable rugplot, see above.  It isn't quite right, because it displays missing (last 2 years) as no date, but that would be easy to fix.  I did this by making the status numeric (I couldn't get the logical to show.) and then plotting the rug with the alpha parameter being 1-status.  I set the rug to have no legend and be plotted only on the bottom axis.

I assume this may be quite easy to add, though we may want to explore more options first, e.g. to have 3 possibilities, i.e. faint (as now), bold line as now, and a third for missing?  For other graphs (e.g. rainfall totals, we may want a rugplot just to indicate missing?

**Comment by Ogik99** [comment]
@rdstern  should we add the rugplots option on the PICSA dialogue as a check box perhaps?

**Comment by rdstern** [comment]
I have now looked at this topic in more detail.  

Rug plots are usually designed to add simple lines at the sides of the existing plot.  These little lines are usually the margins of what is in the main plot.
But they don't have to be.  They could show another variable and this was (and still is) my main concern here.  I would particularly like to show which years were censored in graphs of (say) the start and end of the rains.
But it makes sense to include this feature within a general capability to add one or more rug plots to a PICSA graph.
And the rug plots have options that could be included.
**So I suggest a new tab in the PICSA options.  I suggest it be called Rug and is just after lines and before the Panel.**
a) I suggest we will not often need more than one rug.  This would be possible, but for simplicity I suggest the tab has 3 sections, namely **Y-axis, X-Axis and Rug Format**.  (This is like the Lines tab in the same dialogue where there is a Line format box at the bottom of the tab.

a) **The Y-axis is a check- box.**  (It is the equivalent of the "Add Mean Line" checkbox in the Lines tab. )  The default is unchecked.  If checked, then other options become visible - as for the LInes tab.
b)  On the Y-axis it will usually be an "ordinary rug-plot" i.e. for the data.  The additional options will be Left, Right, Both, to indicate which axes to use.  Are these radio buttons or a drop down.  Then there is a checkbox saying **Inside**.  Default is checked.  If unbchecked, then the rug is outside the axes.

c) The X-axis is similarly a checkbox.  The X-axis in PICSA shows the years.  There are 3 options here.  The ordinary rug plot would show the Years that are there.  The opposite would be to show the years that are missing.  That would also be useful.  (That would just swap the missing and non-missing round.  I assume that would be easy to do "on the fly").  The third option would be to use another variable, which we might call "Occurrence".  This would be another column, so we would need the selector.  That column would be missing except in the years when there was no start or end.  IN those years it would give the Years.  
d) Currently that Occurrence column will be designed to have TRUE/FALSE/NA.  I need to check with Danny whether it would be easy to provide the column to go straight into the rug-plot, or the logical column is transformed "on the fly".
e) Then the other options would be Bottom, Top, Both and a checkbox for the Inside.

I assume the Rug format would include Length, Width, Colour.  What else?

**Comment by Ogik99** [comment]
@dannyparsons @maxwellfundi what's are your thoughts on the above
