### ISSUE TITLE
Improving the controls for the French (and other) translations

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5096]
The French translation has moved on a bit in Version 0.4.26.
There are some basic issues still to be resolved as follows:
a) When French (or any other language than English) the custom control at the bottom of the dialogue add a Lan button.  This is very nice and switches the language within that dialogue.  But it is sometimes in an odd (overlapping) place in some dialogues.  @dannyparsons will investigate.
b) In the main custom control to select columns the Data Options button becomes Options des (Donnees) and the Donnees is not there.  That button will be made bigger.
c) In dialogues with check boxes the translations do not work yet.
d) We have many Francophone people here and will be working on translating some of the text.

The main additional improvement that is needed is to go through the dialogues to see where the controls are too short in French so the text is incomplete.  Then to adjust and report on those dialogues.  For example Prepare > Data Frame > View Data the final option in English is Display HTML in Output Window and there is not enough space for the French equivalent.  

When making corrections to the size of the controls look also at the English phrase and consider whether that could be simplified.

It needs someone to go through the dialogues in turn.

**Comment by rdstern** [comment]
I gather the latest version will be used in mid-February in West Africa, - in French. 
It would be good if a start could be made on some of the ideas above.  I have included Maxwell so he could plan this activity?
1. I notice also that the right-click menus are not translated.  
2. The routine job is for the controls to be the appropriate size. 
3. As mentioned above, when finding a control is not wide enough for the French translation, then please check also whether the English phrase can be made shorter.  And report the changes on this thread.
4. An important one is **Define a Filter**.  
a) Notice you can switch languages from the control at the bottom of the dialogue.  This is a brilliant feature.
b) The control for **Define new Filter** needs to be wider.
c) The two radio buttons need each to be a bit wider.  There is plenty of space.
d) **Selected Filter Preview** is my first example where I propose we change it to simply **Filter Preview**  
e) I notice the general problem that in the control at the bottom **Reset** is **Remise a**  I presume it is Remise a zero, which is too long and not great.  I checked with a French speaker and suggest **Relancer** instead.  (That's on the control that is on all dialogues.

I suggest that initially you concentrate on the size of controls.  I think it is non-trivial to make the actual changes - but assume Maxwell will know how.  If not, then wait with those till Danny is back next week.

**Comment by rdstern** [comment]
I have looked at a few more dialogues:
1.) In the dialogue of Column: Reshape > Column Summaries we see:
a) On the lhs the controls are all check boxes - so not translated.  I hope this can be resolved when Danny is back?
b) On rhs it just says Des.  That is going to be Proportion/Pourcentiles.  Let's shorten to Propn and omit Des.
c) The sub-dialogue is practically all check-boxes so isn't translated yet.
2. In the next dialogue - general summaries
a) The heading in the dialogue is not translated.  I wonder why.  I thought that might be automatic.  It is done in the column summaries
3. The next dialogue is stack
a) Change the receiver label to Colonnes pour Empiler
b) Change the label Donnees en form to Donnees Empiles (e acute)
c) Solve the puzzle of why New Data Frame Name is not translated.  I assume it is because it is on custom control.  If so, then that might be another general issue.

Continue with further dialogues in this set.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers please let's begin some of these tasks. Particularly the tasks of checking the size of controls in French for common dialogs like Filter and others. This is really important for the workshops in French in one weeks time.

**Comment by dannyparsons** [comment]
This shouldn't be closed by a single pull request. @Ogik99 its good you linked to this issue but you could have something like "related to #5096" so that it doesn't close the issue when your pull request is merged.

**Comment by dannyparsons** [comment]
I have made the translation suggestions in the file.

@Muthenya can you confirm if all the size changes suggested by Roger have been done.

If so I will close this as other points have been moved to new issues.

**Comment by Muthenya** [comment]
I'm on it.

**Comment by dannyparsons** [comment]
@Muthenya are these ok now?

**Comment by Muthenya** [comment]
There are some more edits I made on the dialogs we had worked on previously. This needs review and it can then be merged. I just need to confirm with you @dannyparsons whether you  made changes on the translations for the Stack dialog.

**Comment by dannyparsons** [comment]
yes I've updated the translation file for the Stack dialog changes, so just designer changes are needed now.

**Comment by Muthenya** [comment]
Okay. This is ready.

**Comment by maxwellfundi** [comment]
Closing this one too and incase something about translations is raised it can go to a new issue.
