### ISSUE TITLE
Adding Try to the File > New dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5097]
The new File > New Data frame is working very well.  I am delighted!

a) Could the **Try** control be added?  It is in the **Prepare > Calculate > Calculations**, and **Prepare > Generate > Enter**.  It would be good to have it, in each of our "half-way" dialogues.
b) Now wakefield is added automatically when R-Instat is loaded I can just have the command r_data(500,the_works) and I get an interesting data set with 49 columns.  This could be added as one the built-in examples perhaps.  (While we await the random option in the dialogue.
We might want to give it as wakefield::r_data(500,"the_works") just to emphasise the package, though it isn't necessary.
c) Would it make sense for some right-click operations to be included - a subset of what is in the script window?  An example I have now would benefit (in the command option) if the first line could just be run separately.  Then the remainder would be run with the last line (as usual) making the data frame.  I can do this now by running the first line from the script window. , but a bit more convenient to simply run from here.

**Comment by dannyparsons** [comment]
Good idea.

**Comment by Patowhiz** [comment]
I'm still struggling to understand how (c) will be more convenient. Generally, the purpose of the dialog is to create a new dataframe, I don't see the feature being so convenient on this dialog. Perhaps I'm missing something.

**Comment by Patowhiz** [comment]
About (a) I'm assuming there is no meaningful output that will be shown, the control will only help to check if the script generated results to an error?

**Comment by Patowhiz** [comment]
In regard to option (b) , I've added 2 wakefield commands;

1. wakefield::r_data_theme(n = 100, data_theme = "the_works")
2. wakefield::r_data_frame(n = 30, id, race, age, sex, hour, iq, height, died, Scoring = rnorm, Smoker = valid)

**Comment by rdstern** [comment]
On a) you are correct.  It could say: "Command(s) produced an error".
Otherwise it could just say Ok.  Ideally it might say "Commands produced a data frame" or even "Commands produced a data frame with xxx variables and yyy rows" - substitute for the xxx and yyy.

**Comment by rdstern** [comment]
On c) you may be right.  I'd be interested to get Danny's ideas too.
A recent example I ran was in #5100, namely:

villages <-sample(1:10,4,prob=c(20,10,8,30,11,24,18,21,6,12)/160)
sort(villages)

vill=rep(c(4,7,8,9),times=c(6,6,6,6))
v4 <- sample(30, 6)
v7 <- sample(18,6)
v8 <- sample(21,6)
v9 <- sample(6,6)
fld <- c(v4,v7,v8,v9)
data.frame(village=as.factor(vill),field=fld)

If you just have the first 2 lines, then the File > New Data Frame generates a simple data frame of length 4.  If you run the whole thing, then it ignores the first 2 lines and gives a data frame at the end.  

Now I am not thinking of all the options, but this dialogue seems useful enough that I might want to save the commands, or load them?  And I wouldn't mind being able to run the first 2 lines first, (i.e. run a selection) then adjust the remaining code and run the rest.

**Comment by Patowhiz** [comment]
I'd go for "Command(s) produced an error" and "Ok". But I'm flexible, @dannyparsons what's your suggestion on this.

**Comment by rdstern** [comment]
I'd be happy with that.

**Comment by dannyparsons** [comment]
That sounds ok. As in the Add Key dialog the text or textbox colour can be red/green for error/no error. Then its very clear.

**Comment by dannyparsons** [comment]
I am not very keen on c) since it means you've got the full power of the script window in the dialog then and could bring a new set of complications to consider.

I think if we had a good dialog for producing samples such as these then I hope this then wouldn't seem as necessary.

**Comment by maxwellfundi** [comment]
@Patowhiz Whats the state of this?

**Comment by Patowhiz** [comment]
In progress

**Comment by maxwellfundi** [comment]
Are you able to report if you can finish this today @Patowhiz by the time of release?

**Comment by Patowhiz** [comment]
I'm still working on a bug in regards to this.

**Comment by maxwellfundi** [comment]
@Patowhiz  Any update on this?

**Comment by Patowhiz** [comment]
Try will be visible and operational for both Construct and Command option
