### ISSUE TITLE
Adding Try to the new Model > Model dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5098]
Could it also be added to this dialogue?

**Comment by dannyparsons** [comment]
Could be, yes.

**Comment by Muthenya** [comment]
@dannyparsons what was the reason for not having the try in the current version?

**Comment by dannyparsons** [comment]
Yes I don't think it was ever considered, so there was never a decision not to have it.

**Comment by Muthenya** [comment]
Okay. @shadrackkibet had implemented this. I think what remains now will be to just test it. I can make the Try button and text box visible again.
