### ISSUE TITLE
Making the pull-down work in the Model > General > Fit dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5104]
This dialogue has the facility to remember the previous functions used.  Just like the **Prepare > Column: Calculations > Calculate** dialogue.  But it is inactive.

It would be good if it could work.  
Could it start with a default formula remembered - doesn't need to be visible, but ok if it is.  It contains simply (1).  This fits a null model.  It is sometimes a useful starting point.

At the same time it would be good if some of the keys in the keyboard (especially + and * were a bit larger.  They are larger in the keyboard in the Model > Model dialogue.

**Comment by Muthenya** [comment]
@rdstern is this what you had in mind?

![image](https://user-images.githubusercontent.com/32125033/48418494-79be5f80-e766-11e8-986f-0fa2041e0bd1.png)

**Comment by rdstern** [comment]
With the brackets round it.  But mainly that it stores the previous models that were used, i.e. that thr down-arrow in that field where you have the 1 should work.
If you look at the calculate dialogue and try 2+3.  Then 4+5.  Then come back to the dialogue and look at this, you will see it has stored those it used before in the session.  I ould like the same field in Model to do the same.  Hope that's clear?

**Comment by Muthenya** [comment]
Yes, that's what it does now. Let me add the brackets.

**Comment by dannyparsons** [comment]
I don't mind having `1` in the dropdown list, and you don't need brackets for it to work, but the textbox part should be blank by default.
