### ISSUE TITLE
Make Date format description

### ISSUE THREAD

**Issue by mmumbo** [africanmathsinitiative/R-Instat#5112]
**Describe the bug**
On the make data diolog, under **Single Column**. The single column dialog is overlying the **Format Description**, so one dialog is hiding the other. I believe this could be fixed

**How it looks**

![image](https://user-images.githubusercontent.com/11607243/48704115-d4443980-ec06-11e8-8b74-606ed2115773.png)

**How it should look like**
![image](https://user-images.githubusercontent.com/11607243/48704160-eb832700-ec06-11e8-86f0-1f22e897e6ea.png)

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers this is easy to fix by bringing the format box on top, and should be done urgently since its quick and an annoying bug.
