### ISSUE TITLE
Date control problem in climatic

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5118]
I occasionally get a developer error in the climatic commands when I press the button to change the start/end dates button that is on most of the dialogues, e.g. Climatic > Prepare > Start of the Rains.  

When it occurs it gives 2 successive messages about invalid dates.  Then I get to the sub-dialogue and it works fine.  So it isn't stopping any work.

The error message comes twice and is with the user control ucrDoyTo, i.e.

**"Developer error: Invalid month and/or day value. For control: ucrDoyTo."**

I have yet to diagnose a sequence that always leads to this.  I think it relates to the use on the same control on multiple dialogues.  This last time I used Climatic > Prepare > Summarise with the dates set to Feb 15 till June 30.  No problems there, but got a problem the first time I did the Start of the Rains afterwards.  I think the problem is the number 30 in June.

Aha, I think the problem is simple to repeat.  
a) Go into the (start of the rains) dialogue for the first time.  Can use Dodoma.
b) Set the day range to be (say) 15 Feb to End April.  (Any value (I think) so it is less than 31 - with April it is no more than 30)
c) Press reset.  Now the day range is set to 1 to 366.
d) Press the day Range button again
This gives the error above.  

Notice there is no issue with the other user control, i.e. I assume called ucrDayFrom so that must be resetting correctly.  The To says 366 (which should correspond to 31), but there is a little left-over problem here.

**Comment by dannyparsons** [comment]
I think this is caused when the month and day values are both changing and so after one is changed you can get an invalid date before the other is correctly updated. i.e. first month changes to April then before day is changed from 31 it has an invalid date. So I think we just need to prevent the checking until both have updated.
