### ISSUE TITLE
Remaining minor issues with PICSA rainfall graphs

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5120]
These are broadly working well.
 
Remaining aspects to be addressed include:

a) The Median line doesn't seem to work.  When I look at the code it seems that some hasn't been changed from the Mean.  So it sort of works if you do Mean and Median together.  But it doesn't do the Median alone, because of the code for the mean.
b) On the Y-axis tab the Specify Lower and Upper limits always reset to be enabled.  They don't seem to do any harm if no numbers are present in the text boxes.
c) On the Y-axis dates there is currently no option to set the lower and upper limits.
d) Still on the Y-axis dates, (when I changed data frame) I set the dates to 5 or 10 days, but it didn't give them.  When I looked at the code they were set back to months - I may have done a reset.  But the dialogue said days and the code said months.

**Comment by rdstern** [comment]
There is a larger task for the PICSA graphs and that is to add a rug plot to the x-axis to indicate the years when no start, etc was possible.  This is at least for the start, end and length.  This needs careful thought.  At this stage we either give it the thought, but, if not, then could we just have a rug plot tab so we show intent?

A second more tricky addition would be to add one or more "special" points to the (line) graphs.  Ideally there would be an up-arrow with a y-value at years (x-value) when the y-value was large (or perhaps small)?  The main use would be for annual totals or daily extremes where there are one or two very large values.  Currently they are included and this can make the graph poor for the remaining values.  If the y-axis is constrained, then the points are excluded completely.  

Ideally the lines would also continue as they are not missing, but excluded.  I don't know how to do this at all?  The main way, with labels - (not sure about the arrow, could be through a filter which then copies the filtered rows into a new data frame.  They are the ones with the large values.  Then giving them is similar to the current methods (label) as giving the mean, median, etc. 

Or - just a minute - could we put the two ideas together?  Instead of a rug-plot we provide a label at the top of the plot.  This could then simply be another column in the same data frame.  The x is the year, the y is the value (at the top of the plot) and the value (in the label) could be either an extreme value or a label, such as "none"   Possibly the extreme value (which is treated as a text) could have optional arrows round it.  That's just icing on the cake!  This could perhaps be an Extremes tab?  No rug tab any more!

**Comment by maxwellfundi** [comment]
@dannyparsons  I hope you will have a chance to have a look a this.

**Comment by dannyparsons** [comment]
We have labelled this to a new milestone for when its needed.

**Comment by rdstern** [comment]
I keep trying to use this dialogue after general use of data.  In that case the Year column (for the x) has not been through our climatic system.  Please can we have a way this can be allowed without necessarily having to define a date column, when we have yearly data now.

One possibility could be to have a right-click option in the x-variable receiver that allows all numeric columns.  There may be other possibilities.

Hgere is a proposed example from my new guide.

![image](https://user-images.githubusercontent.com/11226469/54042405-08cd0880-4198-11e9-9ebf-e50a641f6d31.png)

**Comment by rdstern** [comment]
More issues now.
I have been using the mean label in the PICSA graphs. With facets, the lines seem correct,but the mean value appears to be the overall mean, repeated for each facet, i.e.not the mean for each station.  I was using the Ghana data at 2 stations.
A second problem is the possibility of having 2 facetted variables.  I can use the Plot options to provide Station and Month as the two variables.  However only one of them is then copied into the PICSA main dialogue.  When I return to the Plot options the facet option has been unset.

**Comment by stevenndungu** [comment]
@rdstern @dannyparsons I have a follow - up question on this issue.
On the addition of lower and upper limits for date button on the sub-dialogue. I noticed we have a pre-designed checkbox and lower/down combo boxes. So are to have the limits from the date variable? Such that the combo boxes will have to list the dates on the date variable or the user will be required to write their own dates.

**Comment by stevenndungu** [comment]
I see limits parameter for dates works in a similar way to that of numeric values eg, `limits = c(as.Date("2000-1-1"), as.Date("2015-04-01"))` or  `limits = as.Date(c("2000-1-1", "2015-04-01"))`

**Comment by rdstern** [comment]
I'll leave Danny to reply more precisely, but the "problem" with the dates is that they are for the start of the rains, end of the rains, etc.  So they are dates in the year, but for any year.  They are not dates in giving the year - just month and day.  So I guess that's why there is a special up/down control.
