### ISSUE TITLE
Add Statistical Problem Solving directory to the R-Instat library

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5121]
In the longer term we may need a re-think of the R-Instat library.
In the short term it would be useful to have some of the data sets in the R-Instat library for further AIMS courses to make more use the same problems as in our recent course in Cameroon.  And also for James in his course in Maseno.

One data set would be the R file for the survey that is sort of there already.  But change the names of the variables that currently say "Village.", i.e. have a full-stop at the end of the name.

[Tomato.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2663458/Tomato.xlsx)

Here is tomato.

It would be good to have some sets from the Fuma game.  Perhaps 1 with the game (24 observations), 1 with 1 sample 144 cases.  Perhaps 5 with 10 - 1440 cases and 1 with 100?  Ask Danny.

Then also some (as many as possible) of the data sets from the week 3 assignments.

**Comment by rdstern** [comment]
I am no longer sure about this directory.  Good to discuss.  But I use this thread to also consider the data sets used for illustration when we have help information on the dialogues.

So here is a list of suggestions.  It would be good to have some action for the next version, as they might be useful for James' Maseno course.  So I am suggesting John and Beryl consider and include Maxwell in the discussion.  They might prepare the files and Maxwell could then put them in the right place.  

I start with the ones above, so this message is complete:

1) survey from above, with the small change and I suggest be called **rice_survey** to be clearer.  It is the rds file that is there already, but with the column names changed so the "dot" is not there.
2) **tomato** dataset given above.  It can be called tomato.
3) The datasets from the larger experiment almost as above.  These in a directory called **farmers**.  In this directory there is the excel file containing the program to generate the data.  That file is called **farmersgame**. There are 2 datasets with 10 farmers called farmers10a and farmers10b.  There is one simulation with 100 farmers called farmers100.

Whether these examples are used for the dialogues is up to the documenters.  But now I consider here more examples that we might include in the help files.
4) The famous **diamonds** data from the ggplot2 package.  We already use that in the first tutorial.  We don't need a different copy of that, but it is a good example that we can use.
5) Our dodoma climatic dataset.  I hope to update this file soon, with the more recent years.  It can be used either way.  It is already used in the second tutorial.
6) The **mydata** file from the **openair** package.  Again we leave it where it is.  It is hourly climatic data.
7) The 3 files from James with climatic data for Western Kenya.  One is the **station information**, the second has all variables (about 7 stations), and the third has the rainfall data from about 50 stations. That is in the climatic directory and can stay there.
8) Four files with daily rainfall and temperatures from Rwanda.  I need to write to Meteo Rwanda to see if they can supply an updated version.  I would also like a station file from there.
9) IFAD survey data from Kenya.  I have written to ask whether we can include this file and expect an answer soon.  It may go into a directory called IFAD, because there will also be further files with detailed descriptions, etc.   They could be good to illustrate tabulation etc.
10) The world bank file we use on **procurement**.  Danny is going to try to get more descriptive information on the different variables.  If that is not forthcoming he will write it himself.
11) We could look at an example of **TheWorks**.  We would add this set, which would be generated using the **Wakefield** package.  This is only needed if we do decide to use it in some of the help information.  Perhaps there could be 500 cases?  (This needs some discussion.)
12) Possibly **efc** and **nhanes** from the sjstats (or sjmisc, etc) package.  This is used consistently by those packages.  We are not very happy with those packages, but are still using them.  They are each based on real surveys.
13) We don't have many good examples of experimental data for illustration.  We started to include some of the datasets from the ILRI set.  I suggest they are sensible enough that we look at them again.  The **ILRI project** overall was expensive.  It hasn't been used much, but would be useful to remember if only that this type of project is not started again without realizing what was done before.
14) Also let's not forget the **CAST datasets**.  Doug Sturling is working on then again in 2019.
15) We used an example from Ric on the problem-solving course.  I'll add this one.  It is at 2 levels.

**Comment by maxwellfundi** [comment]
@MainaJohnO  Sounds good, as soon all these datasets are in order i can easily put them in the library. please create the folder and lets collaborate. 
let me know when everything is done.

**Comment by dannyparsons** [comment]
> It would be good to have some sets from the Fuma game. Perhaps 1 with the game (24 observations), 1 with 1 sample 144 cases. Perhaps 5 with 10 - 1440 cases and 1 with 100? Ask Danny.

We can easily make these. There are four types of randomisation: with/without replacement, complete block/rep. Should we have one of each? That means 4 times the number of data sets which gets quite a lot. Or a mixture or all the same type of randomisation? Same question for the 24 obs, it that one design or multiple?

**Comment by rdstern** [comment]
We don't want too many as these will be primarily to discuss analyses, rather than sampling.  And the different sampling schemes don't matter so much with the larger sample size.  I'll check with David, but I suggest perhaps one of each with the 24, choosing ones that clearly show the differences.  Then just one - without replacement for one sample.  Then perhaps 4 with 10 cases - (instead of 5) again one of each type and one of 100 - without replacement.

**Comment by maxwellfundi** [comment]
@ZIRANA11 @MainaJohnO please let me know when your folder is ready  with all the datasets needed for this directory. Its needed for the next release.

**Comment by MainaJohnO** [comment]
Hello Maxwell,

The data sets needed for the next release are ready and accessible in the
drop box folder I shared with you namely *R-Instat Library Copy*

**Comment by dannyparsons** [comment]
Thanks @MainaJohnO. The structure need to be reviewed and the datasets need to be checked that they conform to the style guide before going in. I can do this with @rdstern but welcome others to check too.

**Comment by maxwellfundi** [comment]
@dannyparsons @rdstern could you have a look at these datasets so that i include them in the library by the next release?

**Comment by dannyparsons** [comment]
Yes.

**Comment by maxwellfundi** [comment]
Great, good if this can be done sooner @dannyparsons

**Comment by maxwellfundi** [comment]
@rdstern @dannyparsons A gentle reminder to have a look at these datasets that needs to go to the library by next release.

**Comment by dannyparsons** [comment]
Thanks I will check those and then let you know when its ready for someone to add over into the repo.

**Comment by dannyparsons** [comment]
I've gone through the new library folder. Really happy to see the organisation of the new structure and the consistency we now have in files names/sheet names/column names. I think this makes us look much more professional. So well done @ZIRANA11 and @MainaJohnO.

I made a few small changes to some names. A general point would be to avoid using `data` in the name of a file or sheet e.g. I changed `ghana_data` to `ghana` - every file and data frame contains data so it doesn't really add any information to the name but makes it longer than needed.

There's just one major point. The `western_kenya.RDS` file seems to be the wrong data. It just has one sheet called `samaru_56`. I assume you've accidentally replaced the file. Once that's been corrected, @maxwellfundi please go ahead and replace the library folder with the new one.

The ILRI data sets are still a bit messy too - but this is less urgent to sort out.

**Comment by MainaJohnO** [comment]
@dannyparsons <https://github.com/dannyparsons>  The ILRI and CAST data
files you suggested they remain as they were. Corrected the western_kenya.
RDS file .

**Comment by maxwellfundi** [comment]
Great @dannyparsons I am on it
