### ISSUE TITLE
Small bug on Insert Columns/Rows Dialog

### ISSUE THREAD

**Issue by Muthenya** [africanmathsinitiative/R-Instat#5124]
**Describe the bug**
I've noticed that **Ok** is enabled eve when there is no data loaded. This is the case for both options, that is, **Insert Columns** and **Insert Rows**.

**Expected behaviour**
I think **Ok** should be enabled only when there is a data frame loaded, otherwise where will the inserting happen?

**Screenshots**
![image](https://user-images.githubusercontent.com/32125033/49987660-23228c00-ff85-11e8-8b84-62467966258a.png)

**Comment by dannyparsons** [comment]
Yes I agree, good spot.
