### ISSUE TITLE
Adding to the Model dialogue - 1 - existing keyboards

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5125]
From looking at the Prediction documentation I suggest our new Model > Model dialogue be extended by a) Adding missing keys to the existing keyboards
b) Adding new keyboards
Here is propose the first.  We may then have further issues for each new keyboard or a larger issue for a set of new keyboards.

There are various keys missing from the stats and the MASS keyboards.  They are as follows:
1. From stats
Add nls
Add ppr
Add princomp
2. From MASS
Add lda
Add lqs
Add mca
Add qda

I assume this may be quite easy?  So I wonder who could do this quickly?

**Comment by Ogik99** [comment]
@rdstern which exact method should we put in the functions? 
The documentation for both the MASS and stats functions provide two methods (please see the link below for the ppr function as an example)
https://www.rdocumentation.org/packages/stats/versions/3.5.2/topics/ppr

**Comment by dannyparsons** [comment]
@Ogik99 Has this progressed? If so, please link the pull request to the issue so it can be accessed from here.
