### ISSUE TITLE
Layers options subdialog.(Height Numeric updown)

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5128]
**Is your feature request related to a problem? Please describe.**
In layer parameters(Geom Parameters) tab , Nud for height should allow input such as height = 0.01.

**Describe the solution you'd like**
change the decimal places for nud to increase by 0.01.

**Describe alternatives you've considered**
Using the script window i edited this and on running  i was able to obtain the plot i wanted.
Attached is the plot i want.
**Additional context**

![dialog](https://user-images.githubusercontent.com/26301973/51307323-b137d980-1a3f-11e9-8ce6-a1ddc29e4590.PNG)
![graph](https://user-images.githubusercontent.com/26301973/51307324-b2690680-1a3f-11e9-909e-901f1d174216.png)

**Comment by maxwellfundi** [comment]
One more thing @shadrackkibet, did you mean just for jitter or you have had these challenges with other Height parameters?

**Comment by shadrackkibet** [comment]
I was using jitterplot for this case.Thanks.

**Comment by shadrackkibet** [comment]
There is another issue with use graph dialog, Seems adding layers isn't working anymore in version 0.4.27. I  am going to write up as as separate issue when i find time.
