### ISSUE TITLE
Label points on climatic map dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5134]
From Roger:

> Ask Maxwell and Lazarus, who were in Rwanda when the request was made.  Currently the mapping takes the position of the stations - of course.  I think it now may already be able to display the station names - at least that was the idea.  As soon as it does that, then it should be trivial to alternatively display the information from another column - which is at the "station level", e.g. mean date of the start , mean annual total.  Of course, after that we get into contouring which is another problem I think, but might just be another layer.

So adding the option to label the stations with their name - or any column should be a simple addition.

@maxwellfundi @Muthenya You might want to look into this and support @Ivanluv or @Wycklife to do this - or it could be taken up by @Ogik99 when she gets back.

**Comment by Ogik99** [comment]
#5290

**Comment by Ogik99** [comment]
#5294

**Comment by Ogik99** [comment]
This issue I believe has been resolved with the following
#5290 
#5294

**Comment by maxwellfundi** [comment]
@Ogik99 thanks for the update. Closed this now
