### ISSUE TITLE
Renaming a data frame and only changing the case

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5136]
**Describe the bug**
If you try rename and data frame and only change the case e.g. "Dodoma" to "dodoma" you get an error:

![image](https://user-images.githubusercontent.com/11214914/51737657-348ba780-209e-11e9-8f20-c353f553a160.png)

This looks like an error from reogrid where it does not distinguish between sheet names that only differ by case.

**Details (optional):**
 - R-Instat Version 0.4.27

**Comment by dannyparsons** [comment]
Let's discuss tomorrow.

**Comment by Ivanluv** [comment]
@africanmathsinitiative/developers  when I have a data frame say "Dodoma" and I want to rename it to a similar name but of different case say "dodoma" ,we have implemented this such that the "Dodoma" data frame   worksheet will first be deleted hence the new renamed worksheet "dodoma " will  replace  the deleted worksheet

**Comment by dannyparsons** [comment]
@Ivanluv yes that's correct, which is how we solved this problem. 
Can you also say why we had to do this in relation to the reogrid issue? Also, the change in relation to having sheet names differing by case. It will be useful for others to here the reasoning behind our changes.

**Comment by Ivanluv** [comment]
@africanmathsinitiative/developers  reogrid does not allow renaming of a data frame  with the same name despite  their different cases,therefore we had to delete the existing dataframe and replace it with the newly renamed data frame

**Comment by dannyparsons** [comment]
Thanks. This is an issue with reogrid. We therefore had to also prevent having two data frames with names that only differ by case, the name will be adjusted when importing.
@Ivanluv you were also going to write an issue on reogrid's GitHub to report this? That's important because they might be able to solve this and we won't need these extra checks anymore.

**Comment by Patowhiz** [comment]
@Ivanluv can you clarify the implementation flow to me. You are saving the data frame using the changed name, then deleting the one in memory, then importing the saved one?

**Comment by Ivanluv** [comment]
@Patowhiz  yes thats how its working
