### ISSUE TITLE
Bug when clicking the Lan button in some dialogs 

### ISSUE THREAD

**Issue by Muthenya** [africanmathsinitiative/R-Instat#5150]
**Describe the bug**
This follows from the French translation issue. I take two dialogs for example, the Calculator and Transform Text. 

**To Reproduce**
For the **Prepare > Column Calculate > Calculator**, when you have changed the Keyboard say from **Basic** to **Maths**, then you click the **Lan** button the added keyboard to the right is "cut"**Expected behaviour**

For the **Prepare > Column Text > Transform Text**, the base buttons are "lost" (disappear) when you click the Lan button when you are on the Convertir le cas (convert case), Suppres (Trim) and Sous-chaîne (substring) options.

**Screenshots**
For the Calculator
![image](https://user-images.githubusercontent.com/32125033/52330175-cdf37b80-2a05-11e9-8f93-174ce63984a8.png)

For the Transform Text
![image](https://user-images.githubusercontent.com/32125033/52330155-b7e5bb00-2a05-11e9-9e62-e4da953d3da6.png)

**Details (optional):**
 - OS: [e.g. Windows 10]
 - R-Instat Version [e.g. 0.4.27]

**Additional context**
This might also affect other dialogs with keyboards as well. I will add them here when I come across them.

**Comment by lloyddewit** [comment]
@rdstern I think this is solved now so I am closing this issue.
