### ISSUE TITLE
Translation: Lan button overlaps on some dialogs

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5154]
@rdstern which dialogs did you notice this on?

> When French (or any other language than English) the custom control at the bottom of the dialogue add a Lan button.  This is very nice and switches the language within that dialogue.  But it is sometimes in an odd (overlapping) place in some dialogues.  @dannyparsons will investigate.

**Comment by rdstern** [comment]
I can't find it much now.  I have only checked (so far) when going into a dialogue, not after returning, etc.  The only one with a slight issue I found now is Model > Model.

Maybe it has gone away.

**Comment by lloyddewit** [comment]
@rdstern I think this is solved now so I am closing this issue.
