### ISSUE TITLE
Translation: check boxes do not translate

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5155]
This is because text for our custom control checkbox control is set at run time so text does not get added to resource file.

**Comment by rdstern** [comment]
So do we have to add it manually to the resource file?  If so, then do we have to check and potentially change the resource file every time we edit text on a checkbox?

**Comment by dannyparsons** [comment]
I think what we can do is set the checkbox text in the resource file only, and then modify the code so that it picks the text from the resource file. This would mean only having the text in the resource file so avoiding inconsistency issues. I still need to check how exactly to implement this approach first.

**Comment by lloyddewit** [comment]
@rdstern This is now resolved, so I'm closing this issue.
