### ISSUE TITLE
'New Data Frame Name' text does not translate on dialogs

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5159]
@rdstern is this the case on all dialogs? It is part of a user control so its possible.

**Comment by rdstern** [comment]
No.  Most of the headers seem to be translated.

And now I find that in the File menu, the New data frame is now translated.  But Open Data frame, and Open from Library (i.e. the next 2) are not!

**Comment by dannyparsons** [comment]
Are you talking about the dialog headers? 
I was meaning the label in places like the Stack dialogs where there is a "New Data Frame Name" label for the output that you mentioned is not translated.

**Comment by rdstern** [comment]
Oh yes, there are 2 different things.  Perhaps they should be on separate issues.

**Comment by dannyparsons** [comment]
I made one from your comment that General Summaries header was not translated https://github.com/africanmathsinitiative/R-Instat/issues/5158
But it might be more general than that.

**Comment by lloyddewit** [comment]
@rdstern This is now resolved, so I'm closing this issue.
