### ISSUE TITLE
Temporary switching between languages

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5161]
From @rdstern here: https://github.com/africanmathsinitiative/R-Instat-Translations/issues/3

> The option to switch languages within a dialogue is very nice.  How could we switch languages like that in the menus?
> I suppose one way would be a Language option on the Right click menu? It is disabled if working in English. Perhaps there is a better way, e.g. on the toolbar?

**Comment by dannyparsons** [comment]
I can see the usefulness of this but with an option like these we're then really confusing which language the software is "in". If the menus are now in English I think users will forgot its still really in French and not go to the Options dialog to change it properly.

Unless I've misunderstood your suggestion? I do think we could have a shortcut to changing the language somewhere in Tools or the toolbar to make it quicker.

**Comment by rdstern** [comment]
My reasoning was simply that I found in French, some text in a dialogue was not clear - so I found it very useful to be able to look at the English equivalent.  I think many users will find that to be a useful feature in the dialogue.

It is the same in the menus.  If I am working in French, (and don't understand a menu item) then I might want quickly to see what it is in the base language, i.e. English.    I still want to work in French, but would like to check the translation of this particular item.

**Comment by dannyparsons** [comment]
If you are mainly doing it for one item at a time then how about showing the English on a tooltip or by right clicking or by pressing/holding down a certain key (not sure if that's possible)?

**Comment by rdstern** [comment]
@dannyparsons and @lloyddewit I am back on this topic for easy switching to check the menu items.
Danny mentioned the possibility of having a Tooltip with each item - or at least those that are not obvious.  I would be happy with that - as long as it doesn't get translated!  Usually I am very keen for the system to eventually translate tooltips.  Will there be a way to say that a certain bit should not translate - perhaps a special symbol?

If it isn't going to be on the toolbar, then we could "Promote it" in the Tools menu or add it to View or Help!  I suggest we need 2 items - just like Filters - you can have many languages (filters) and then Return to English (remove all filters).

I still think a button might be neat.  It has a pull down - of course - with the different languages.  Sort of in order as I expect more use of French that others - don't know.  Press and it goes to the first foreign language.  Press again and back to English.  The pull-down let's you choose another language, say French, Portuguese.  Click on Portuguese and it goes into Portuguese.  Then back to English.  But it remembers that Portuguese was pressed.  So press again and now it is a Portuguese/English switch.  I still think that would be nice!

**Comment by lloyddewit** [comment]
Fixed in PR #6572
