### ISSUE TITLE
Packages to add

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#5165]
devtools
ggplotgui

**Comment by dannyparsons** [comment]
devtools is an existing package. You can check in the R setup file to see current packages before suggesting them.

**Comment by dannyparsons** [comment]
I suggest we don't update packages for this version since `ggplotgui` will not be needed and we should have time to test package changes when we update. Let's do this soon after this version before the next.

**Comment by maxwellfundi** [comment]
@dannyparsons  Sounds good. Thank you.
