### ISSUE TITLE
Bug on the Prepare > Column: General > Enter Dialog buttons when translated to French

### ISSUE THREAD

**Issue by Muthenya** [africanmathsinitiative/R-Instat#5168]
**Describe the bug**
The following are bugs when the Enter dialog is in French:

1. Only the closing brackets for both the usual and square brackets appear.
2. The font for the buttons `Rep`, `Seq `and `SEQ2 `are not consistent. All should be in lower case.
3. The  `c()` appears as `(c)`. Which is not right.
4. I'm not certain on the translations of `Lun-` and  `mon+`. Are these correct for month abbreviation and month name respectively?

**Screenshots**
![image](https://user-images.githubusercontent.com/32125033/52468417-bc42dd00-2b99-11e9-9382-56fe735c3887.png)

**Additional context**
For the brackets ,the issue persisted even after making the buttons wider.

**Comment by dannyparsons** [comment]
Thanks. This is probably a machine translation problem then and could be corrected in the translation file.

**Comment by lloyddewit** [comment]
@rdstern The enter dialog seems to have changed since this issue was raised. I no longer see the translation problems described in this issue. Therefore, I am closing this issue.
