### ISSUE TITLE
Split Text into Maximum components

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5194]
In the Split Text dialog we can split a column into components split by a character e.g. `:` but you have to give the number of components (columns) to return. Often you just want the maximum possible number of components and to have blank values when there were less than the maximum in that row.

The dialog uses `stringr::str_split_fixed` where you must specify `n`. There is also `stringr::str_split` which can have `n = Inf` but it returned a list of vectors not a data frame, so we didn't use it.

Is there now a function which does what `stringr::str_split` but returns a data frame/matrix with padded empty values? Or will we have to write our own function for this?

**Comment by Ivanluv** [comment]
@dannyparsons using stringr::str_split with 'simplify=TRUE' as the third argument returns a data frame

**Comment by dannyparsons** [comment]
Excellent! Thanks for finding this!

We could implement this in the dialog now!

I would suggest now having two radio buttons: 
1. "Maximum Number of Components" using `stringr::str_split` with `simplify = TRUE` and 
2. "Fixed Number of Components" using `stringr::str_split_fixed` as it is currently.

Possibly 1. would be the default now.

**Comment by Ivanluv** [comment]
@dannyparsons how am I to implement the designer changes on this?
![image](https://user-images.githubusercontent.com/45068931/53337143-99daee80-3911-11e9-83aa-11b7bd8d02e7.png)

**Comment by dannyparsons** [comment]
The binary columns option remains the same, its a different concept not related to `str_split`. Try it, to figure out what it does.

**Comment by Ivanluv** [comment]
@dannyparsons Is this fine?
![image](https://user-images.githubusercontent.com/45068931/53477147-1f32e000-3a85-11e9-96bc-191483bf1901.png)

**Comment by Ivanluv** [comment]
@dannyparsons ,I think this looks better
![image](https://user-images.githubusercontent.com/45068931/53480631-a33c9600-3a8c-11e9-8e02-b3c7cc458a9c.png)

**Comment by dannyparsons** [comment]
Yes, the second looks better. But I would have them on the right side, under the Split By receiver. With the nud then under them. It's clearer if they are all together.

**Comment by Patowhiz** [comment]
I second Danny on the positioning of the radio buttons

**Comment by Patowhiz** [comment]
@Ivanluv so when I check on the Maximum Number of Components radio button, the ucrNud gets hidden?

**Comment by Ivanluv** [comment]
@Patowhiz  Yes that's how its supposed to work
