### ISSUE TITLE
Reordering a factor with many levels

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5206]
This is (for my first time) not a real issue because I can do it!  But not the way I thought I would.  So I report as a sort of "feature".  It can then be closed, unless there is a better way.  But it does need to be mentioned in our help, because it isn't so obvious to me at least.

The problem was climatic data from 65 stations in Poland.  We displayed them as graphs and they looked surprisingly clear.  Each graph compared station and satellite data as a density plot.  It became clear that the correlations were better at the sites at high altitude.  So the problem is to re-order the stations according to altitude.

We have our **Prepare > Column: Factor > Reorder Levels**, which works well but is a pain for a factor with so many levels.  What I wanted was a data frame at the factor "level".  Which I had - with lat and long and altitude as well as the station names.  Then I sort on altitude, **copy** the column of names (in the new order) and **paste** it in the new names in the dialogue

Which I can do!  Not from Reorder, but in the **Recode Factor** dialogue.  Hooray.  It puts the result into a new column, but if you prefer to overwrite, then just give it the old name.  I am happy.

Perhaps everyone else knew this already?  But I had to try to confirm, because paste doesn't yet work everywhere!

**Comment by dannyparsons** [comment]
This relates to #4421. But as well, having a way to type or paste the new order would be good, probably then with a different control displaying the levels.
