### ISSUE TITLE
Information message when closing filter sub dialog without adding a condition

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5208]
A common issue for users is when they are defining a filter they select the column and set the condition values but don't always know to click the "Add Condition" button.

We could have a really easy help for this by having an information pop up when you click Return and there is a column selected in the receiver. When you click "Add Condition" it clears to receiver so likely if the receiver if filled the user may have forgot to click the button.

I did something like this recently on the Import NetCDF file subdialog - this could have the same information style message box as there.

**Comment by dannyparsons** [comment]
@Muthenya could you take this on?

**Comment by Muthenya** [comment]
Okay.

**Comment by rdstern** [comment]
That's great.  Just to check, there was work earlier on improving the filter sub-dialogue, see #4529 I think?  This was to stop users having to type TRUE, etc.  What has happened to that?
