### ISSUE TITLE
Rename data frame dialog should reset New Name when reopening/changing data frame

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5210]
The rename column dialog works well in that the New Name updates to the current name when you change column. This is really helpful to prevent accidentally overriding a column when new name is still the value from a previous use of the dialog.

The rename data frame dialog doesn't work like this and never updates when you change data frame. I think it should work as the rename column and update on reopen/changing the data frame.

**Comment by Ivanluv** [comment]
@dannyparsons  do you mean it should make changes to the original Data frame?

**Comment by dannyparsons** [comment]
Yes so when I change the data frame, the new name should default to the current name. I think this works now but only the first time or when you reset.

To see issue, load two data frames, then rename one of the data frames. Now when you try to rename the other data frame, the default name is the same as you just renamed, which isn't a sensible default. It could also lead to accidentally replacing a data frame.

I think we just need that what happens on reset now also happens on reopen or when the data frame changes.

**Comment by maxwellfundi** [comment]
@Ivanluv  How is this going? Any progress?

**Comment by Ivanluv** [comment]
@maxwellfundi I am not sure in how to implement this

**Comment by Wycklife** [comment]
This works well well from my review.
