### ISSUE TITLE
Add days_in_month to the Use Date dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5212]
This should (I hope be really easy.  It was needed in this workshop.

In the current workshop I was asked to produce a column from the date that gave the number of days in the corresponding month.  This could usefully be added to our Prepare > Column: Date > Use Date dialogue.  It can go in the second group after the leap year option.

It should be easy, because it is in lubridate and is the days_in_month function.  So I have assumed it could be done for the next release.  It could move if there isn't time.

**Comment by dannyparsons** [comment]
Yes, agreed. I've assigned to @Ivanluv and @Wycklife, whoever needs a task to take up first should do this. It will need edits the R method, if you look at the current R method it should be easy to adapt for this function.

**Comment by Wycklife** [comment]
@africanmathsinitiative/developers What is the appropriate name for the checkbox to be used in this?

**Comment by rdstern** [comment]
It is "Days in Month".
