### ISSUE TITLE
Making more use of plotly?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5228]
Some of the graphs we produce - but not all - can be investigated further with plotly.  And that is fun.

But currently using plotly is sort of "hidden".  Also it doesn't work for all graphs.  For example I think it doesn't work for combined graphs (for example Describe > One Variable > Graph with all variables from diamonds).  But it does work for facets, etc.

So I have 2 suggestions.
a) Could we have a drop-down on the graph item in the toolbar (as we do for the file Open and last 10 dialogues)?  Then it would give the R graph as the first item and interactive graph as the second?  Ideally if you click on the icon itself, then it does as now, i.e. the default action.
b) Ideally the interactive option would only be enabled if the last graph was one that was acceptable to plotly.  I hope that is detectable?

Also if the detection in b) is possible, then the interactive option would also only be enabled in the **Describe > View Graph** dialogue once a graph is chosen.

**Comment by maxwellfundi** [comment]
This seems a very good and also important addition I like how easy it would be to view an interactive graph from the drop down and that is easy to do. Am not sure how easy it is to do the detection of a graph acceptable by plotly. @dannyparsons any ideas?

**Comment by dannyparsons** [comment]
We could check that it is a `ggplot` graph to allow use of plotly which is easy to do in the R code.

**Comment by rdstern** [comment]
I have another question about our use of plotly.  It seems the ideal environment for looking at the outliers in our climatic (or other) data.  When there is a scatterplot, etc you can hover over a point and it tells you the x and the y values.  That's fine, but it would be much better if it could also tell you the value of other variables from the same data frame.  For the climatic data this would be the date variable and perhaps also the station variable.  Alternatively - not quite so good - it could give the row number in the data frame.

Is this possible?

**Comment by dannyparsons** [comment]
Yes you can label a layer with any variable and it will only show when you hover in plotly.

**Comment by rdstern** [comment]
That's exactly what I want.  How do I tell plotly which variable(s) to use?  Can I do this once in plotly, or do we have to add something when we use the dialogue?  Here is an example plot where I would like to do this - and explain how to do it in the new climatic guide graphics section.

![image](https://user-images.githubusercontent.com/11226469/54086818-56c24780-4323-11e9-9303-4e7308816af5.png)

**Comment by dannyparsons** [comment]
You can add text or label as an aes when you create the graph then this will be visible in plotly.

**Comment by rdstern** [comment]
Yes, but then it is there for all points and the whole thing is a mess.  That's already useful, because I can zoom in plotly, but I really only wanted it as an addition in the hover.

![image](https://user-images.githubusercontent.com/11226469/54087213-14026e80-4327-11e9-942d-e0b49cf4212a.png)

**Comment by dannyparsons** [comment]
What was the command for that? It shouldn't add that with text or label aes.

**Comment by rdstern** [comment]
I just added another layer to the scatterplot, see below.  Then called plotly also from the dialogue.

# Code generated by the dialog, Scatter Plot
Dodoma_merge <- data_book$get_data_frame(data_name="Dodoma_merge")
last_graph <- ggplot2::ggplot(data=Dodoma_merge, mapping=ggplot2::aes(colour=month, x=Sunh, y=SDU)) + ggplot2::geom_point() + ggplot2::geom_text(mapping=ggplot2::aes(label=Date), size=2) + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text()) + ggplot2::facet_wrap(facets= ~ month, dir="h")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="Dodoma_merge")
data_book$get_graphs(data_name="Dodoma_merge", graph_name="last_graph")

rm(list=c("last_graph", "Dodoma_merge"))

# Code generated by the dialog, View Graph
plotly::ggplotly(p=data_book$get_graphs(data_name="Dodoma_merge", graph_name="last_graph", print_graph=FALSE))

**Comment by dannyparsons** [comment]
oh no you don't need a `geom_text` layer, just add `label = Date` into `geom_point`.

**Comment by rdstern** [comment]
Brilliant.  I added it to the aes in the script file and it works perfectly.  Now how do I do that from the dialogues?  It is perfect for examining the outliers.  Can I have more than one - so both Station and Date if needed.

**Comment by dannyparsons** [comment]
From the Point Layer Options there should be a receiver for label.
For multiple you could do something like `label = paste(station, date)` (although you couldn't do this from the dialog)

**Comment by dannyparsons** [comment]
We could do something automatic in climatic dialog for this.

**Comment by rdstern** [comment]
I tried the same with boxplots, i.e. adding label = variable and it doesn't seem to work for them.  It just gives the value there.  That would have been very nice for climatic.  It works fine for jitter so that's good.

Great if it can work for boxplot.
That also makes me keen to have the boxplot plus jitter working well,  That's when the jitter is behind the boxplot, so you only see the outliers.  The next problem is that you see each outlier twice (I think); once for the boxplot and then again for the jitter.  If there is no better way then we could presumably have the boxplot outliers in the background colour?

This is a pretty exciting (potential) feature!

**Comment by rdstern** [comment]
I have optimistically changed this to the 0.5.5 milestone in the hope that adding the extra item to the toolbar might be an easy thing to do.  This would be useful as I write the help - particularly on saving the graphs.

The idea would be that the graph icon would stay as it is now - it is already useful.  In addition there would be a pull-down as in the File > Open icon and the last 10 dialogues.  This would give other options for the graphs.  There the three options could be:
**_Interactive_**  (same as Interactive viewer on last graph from Describe > View Graph)
**_R-Viewer_** (same as current toolbar option)
**_View_** (Opens the Describe > View Graph dialogue - to allow easy access to other saved graphs)

I hope this could be easy to do?
