### ISSUE TITLE
Small addition for output window?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5241]
This is very small and only to be done if trivially easy.
I was tidying the output window.  I selected a section and pressed the Delete key.  Nothing happened.
I did my right-click and found it was very easy to delete the selection.
 Would it be natural to be able to use the delete key as well.  Would that be very quick to do?

**Comment by Patowhiz** [comment]
Yes this is a trivial thing and sounds very logical to do

**Comment by Patowhiz** [comment]
What about on pressing the backspace?

**Comment by dannyparsons** [comment]
Yes good idea.

Also, is undo possible?
