### ISSUE TITLE
Changing right-click in reogrid a lttle?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5242]
Currently in R-Instat the main right-click menu is only activated from the name field.  
In Genstat there is a similar right-click menu, but it works from within the grid as well.

It (like R-Instat) has some options that recognise the variable - like convert to factor, and others that simply open a dialogue - like Reorder columns.

I find that I have hardly, if ever, used the special current right-click from within the grid itself.  So I suggest we extend the main right-click, so it can be activated from within the grid as well as from the name field.

I have suggested this for Version 0.4.31.  But it may need discussion, and may not be a trivial change - even if agreed.  If so then change the milestone

**Comment by Patowhiz** [comment]
@rdstern what do you mean by from within the grid the  grid itself? If by that you mean the rows and the cells then it's important to note that context menu's on grids are generally activated on Column, Row and Cell(s) right click. As a standard, depending on what's being selected on the grid the nature or content of the context menu changes based on what could be done on the selected "part" of the grid. For instance it won't make sense to have "Rename Column" when I right click on the row or the cell.

**Comment by rdstern** [comment]
Thanks.  You are phrasing it properly.  So in Genstat it is the same right-click menu irrespective of whether you are in columns or cells.

The reasoning is that you will still be in a column when you are in a cell.  So I am suggesting we don't have a special cell's right click.  It is the same as the column right-click.

I am not suggesting you change the row right-click.

**Comment by rdstern** [comment]
@jkmusyoka agrees with my view.  In this Mozambique workshop we have participants who are much less confident with the mouse etc.  It would have helped them if the right-click for the columns were also activated when you are in a cell.  

So I am repeating my request.

**Comment by Patowhiz** [comment]
Okay, I'll do this

**Comment by rdstern** [comment]
The main problem is that the new toolstrip within the data frame doesn't do anything.
It looks nice, but seems inactive.

At the same time I suggest you omit the Delete Variable from this new toolstrip.
