### ISSUE TITLE
Column metadata with scientific notation

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5244]
In the column metadata, one of the elements is called Scientific and is always FALSE.  Can it be changed to be TRUE.  I wasn't able to edit this field.  If so, then does it display in the grid or just in R?

**Comment by dannyparsons** [comment]
I think I've just disabled editing but can easily allow this. I believe its set up to only allow you to type TRUE/FALSE. It's just for the grid and its on a column by column basis.

**Comment by shadrackkibet** [comment]
@rdstern I think this is now possible. This should be closed? It was fixed here #5790
