### ISSUE TITLE
Adding a right-click to the Column metadata

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5250]
In the Column metadata, see below, the right-click on the left-hand side gives the same as the right-click in the data, when you currently click in the name field.
Please could we add the right-click on the bottom tab.  This could be exactly the same as the right-click on the bottom tab in the actual data.  

That's actually pretty useful, particularly as the metadata is "complete", i.e. for all columns.  And, when you want to see the data, you have that option (last one in the bottom right-click).

I hope that will be easy.  If it would also be easy then (not so important, but consistent), would be the have the same right-click on the lhs in the data frame metadata!  (In the data frame metadata one row is a data frame, and hence equivalent to the tabs in the data and column metadata.

![image](https://user-images.githubusercontent.com/11226469/54424569-17bd3900-470b-11e9-9f8b-fb68f2e56588.png)

**Comment by dannyparsons** [comment]
I think one reason we didn't yet do this was because you can easily delete the date frames from the right clicks and you may think you are just deleting the metadata.

**Comment by rdstern** [comment]
I don't buy that reason.  Anyone thinking they should want to delete all the metadata and leave the data should be suitably punished!
My reasoning is that (as with SPSS) you may want to always have the data on view.  But particularly with the R-Instat restrictions on data that view may sometimes not be as useful as having column metadata + output windows.  That's why we put the right-click on the lhs of this window.  And that's why we should also add the bottom right-click.

**Comment by Patowhiz** [comment]
@dannyparsons if this is agreed on then I'm going ahead to implement it
