### ISSUE TITLE
Add options button to correlations when just 2 variables etc?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5255]
I thought we already had an issue on this topic, but couldn't find it.  I have also found some other problems with the correlations dialogue.  I think they should all be easy?

1. Could we add the Options button to the 2-variable case?  I hope it might be trivial to add?
We now have to treat 2 as an example of many.  This adds an unnecessary step.  
If, for some reason this is difficult, then could we make Many the default, when the dialogue is first opened.

2. When I return to the dialogue (having previously completed it - including a scatterplot (by a factor) from the options I get the following error when I return to the dialogue:

**instat
Developer error: no state of control ucrPnlCompletePairwise satisfies it's condition. Cannot determine how to set the control from the RCode. Modify control setup so that one state can satisfy its conditions.
OK**   
It then goes into the dialogue fine and I can continue.

3. In the Options I have the possibility to save the graph.  In the scatterplot at least it ignores this. and continues with the default of last_graph.

**Comment by dannyparsons** [comment]
We can easily have the Options button for the Two Columns case. The other issues should be easy to solve too.
@africanmathsinitiative/developers someone can take this up.

**Comment by Muthenya** [comment]
@rdstern I haven't been able to reproduce the third problem with the **Save Graph**.

**Comment by rdstern** [comment]
Neither can I now.  So let's assume I got that wrong.  I'll check the dialogue again once the new version is installed.
