### ISSUE TITLE
Minor edit on File > Open

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5261]
![image](https://user-images.githubusercontent.com/11226469/54660494-95e45b80-4ace-11e9-949e-7b1241777448.png)

Here is what I would like on this dialogue.
Currently the file name at the top is left justified, so you have no idea of the name of the file.  The field is also very small. 
If it could be right-justified, as above, then you would know the name of the file you are opening.

**Comment by dannyparsons** [comment]
I think we can also make the box wider.
