### ISSUE TITLE
Data receiver in View dialogue does not clear

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5262]
I used the View Data dialogue to put some data (12 rows - monthly data) into the output Window.
These columns were rainfall totals and also number of rain days.  I first displayed the set of rainfall totals.
![image](https://user-images.githubusercontent.com/11226469/54664020-f6799580-4ada-11e9-96c5-180bb879214f.png)

I then returned to the dialogue.  I **cleared the receiver** (right-click) then Clear), and put in a different set of variables (number of rain days) to display in the output window.

It worked fine, except it displayed what was previously in the receiver, i.e. it ignored the fact the receiver now had a different set of columns to display.

I assume (hope) this issue is just for this dialogue?
I attach a picture of the dialogue with the receiver inconsistent with the output.

![image](https://user-images.githubusercontent.com/11226469/54663679-ff1d9c00-4ad9-11e9-92cd-4e11631c83e5.png)

The previous set of columns are still being displayed.

After reset (of course) I get what I wanted, see below:

![image](https://user-images.githubusercontent.com/11226469/54664345-e4e4bd80-4adb-11e9-80a3-e64423bb1c12.png)

**Comment by lloyddewit** [comment]
Analysis:

- This error only occurs if the `Specify Rows` checkbox is unchecked
- By default, the `Specify Rows` checkbox is checked
- The user unchecks it, which calls `dlgView.FunctionControls_ControlValueChanged(...` 
- This calls `ChangeFunctionParameters()` 
- This calls `ucrBase.clsRsyntax.SetBaseRFunction(ucrReceiverView.GetVariables(True))` (i.e. creates the function that will be called when `OK` clicked)
- This function contains a hard-coded R script that includes the columns currently displayed in the `Variable(s) To View` window (i.e. includes `col_names=c("month", ...`).
- If the contents of the `Variable(s) To View` window is updated then the R script isn't updated and the R script still contains the old column names.

The solution is to ensure that the R script is updated whenever the contents of the `Variable(s) To View` window is updated
