### ISSUE TITLE
More climatic data for the library - Rwanda

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5265]
[Rwanda workshop data.zip](https://github.com/africanmathsinitiative/R-Instat/files/2991658/Rwanda.workshop.data.zip)

There should be a Rwanda folder.  Initially there can be just this file.  I hope, later, there will be an improved version and also other files.

It is for 4 stations

**Comment by MainaJohnO** [comment]
Seen, will work on it and put in the relevant folder
