### ISSUE TITLE
Add scale_x/y_dates option to Plot Options sub dialog

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5266]
Here is a useful graph that is really simple to do, with a line plot
![image](https://user-images.githubusercontent.com/11226469/54754740-25c3fb80-4bdc-11e9-805f-0c3a698fd742.png)

I would now like to scale the x-axis differently, giving a label every (say) 5 years, rather than every 20 years.
In the sub-dialogue, we therefore need to be able to specify the limits and the increment for dates.  Currently, the x-axis has 3 options, i.e. Continuous, Discrete, and Date.  But the Date options have yet to be completed

a) Please could they be, even if initially only partially.  And initially perhaps for the x-axis, though it should be the same for x and y.

In the meantime, I assume I could alter the script file.  I assume that is an easy thing to add?

And, by the way, in the Rwanda workshop we were asked the same question for the inventory plot.  It will greatly enhance the inventory plots to have access to the sub-dialogues.

**Comment by dannyparsons** [comment]
Yvonne was interested in another issue on scales so she may want to take up this one.

There's many options for modifying date scales but I agree we could have something useful that's minimal initially.

**Comment by rdstern** [comment]
Here is another instance, though this may be more complicated.  It is back to my "hobby horse" of having dates within the year - as is now partially possible with the PICSA rainfall graphs.
Here is an example:
![image](https://user-images.githubusercontent.com/11226469/57011388-5777ab80-6bf9-11e9-803a-fcf7fc724202.png)

The x-axis is the day of the year (with day 1 being 1 August - so 31/07/2016 could be the origin.)

**Comment by dannyparsons** [comment]
I've removed the comment relating to formatting a numeric column as a day of year and moved to here https://github.com/africanmathsinitiative/R-Instat/issues/5356 as that's a different (related) issue.

The original comment relates to plotting of a Date column and having options for its display.

This can be solved by adding a "Date" option to the X and Y axis tabs on the Plot Options subdialog. This would implement the `scale_x/y_date` function.

@Ogik99 @maxwellfundi do you want to start looking into this? The first step is to see what the options are for `scale_x/y_date`. There are lots so we don't need to implement them all at first, as Roger's comment above says, some are more important than others.

**Comment by maxwellfundi** [comment]
@dannyparsons  @rdstern at the moment we have discussed and decided to implement the `breaks`` minor breaks` and `labels`

Do you have other things that you would like to included here?

**Comment by Ogik99** [comment]
> @dannyparsons @rdstern at the moment we have discussed and decided to implement the `` breaks`` minor breaks `` and `labels`
> 
> Do you have other things that you would like to included here?

We could add the limit options as well.
https://www.rdocumentation.org/packages/ggplot2/versions/1.0.1/topics/scale_x_date

**Comment by maxwellfundi** [comment]
@dannyparsons We have looked at this with @Ogik99  and we need to have a scale date function the ggplot default class that will be passed through the dialog through to the subdialog then to the ucrAxes.
We also switch from the scale continuous to scale date when the have dates selected. 

Do you have any contrary opinion?  we found that we can not have the scale continuous as well as the scale date function and so the need to swap them.

**Comment by dannyparsons** [comment]
That's all correct. We need new `scale_x/y_date` functions and on the axis tab you choose discrete, continuous or date. You can only have one of these for each axis.
