### ISSUE TITLE
Very small change in Climatic > Check > Temperatures

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5274]
This should be trivial.  In the check.  Please change a < to <= in the code below.  I have put the change that is needed in bold below

Here is the R code:
Code generated by the dialog, Climatic Check Data 
Temperature and pressure
diff_calculation <- instat_calculation$new(type="calculation", function_exp="Tmax - Tmin", calculated_from=list("Dodoma"="Tmax","Dodoma"="Tmin"), result_name="Diff")
diff_test_calculation <- instat_calculation$new(type="calculation", function_exp=**"Diff <= 0**", sub_calculations=list(diff_calculation), result_name="diff")
filter_calculation <- instat_calculation$new(type="calculation", function_exp="diff", calculated_from=list("Dodoma"="Tmax","Dodoma"="Tmin"), sub_calculations=list(diff_test_calculation, diff_calculation), result_name="QC")
filtered_data <- instat_calculation$new(type="filter", function_exp="QC", calculated_from=list("Dodoma"="Tmax","Dodoma"="Tmin"), sub_calculations=list(filter_calculation), save=2, result_data_frame="qcTemp")
data_book$run_instat_calculation(calc=filtered_data, display=FALSE)

It would be good for this to be done this week, before Maxwell goes to Malawi.

**Comment by Muthenya** [comment]
@maxwell I have taken this up.
