### ISSUE TITLE
Change in Climatic > Check > Rainfall QC

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5276]
I have been impressed at how the rainfall and temperature dialogues have worked!
In rainfall, one option is called Consecutive.  It notes whenever there are more than x (default 10) consecutive rain days.
One edit that would be useful, and just may be a small change - I don't know.  It is that the logical is set to true, only from the 10th onwards.  It would be good for it to be true for all days in that sequence, so we see the whole thing?
A second change is likely to take a bit longer.  This would add a threshold to the dialogue for that option.  

But the first is the only urgent one.

**Comment by dannyparsons** [comment]
Actually your first point is much harder but the second should be easier.

**Comment by shadrackkibet** [comment]
I have been working with Theo on his project particularly using QC Rainfall dialog. In addition to above, We have a couple of small issues to report that might be easy to fix.

1. If Large is checked and check say same, then clear one of numeric updowns then Ok is still enabled as shown below.

![bug](https://user-images.githubusercontent.com/26301973/56882857-cec40880-6a5c-11e9-8d76-4ea11d29c7aa.PNG)


2. For the outlier option, the threshold input allows text, this should only allow numerics.

3. For the Dry Month option, Year column is needed. So Ok should be disabled when this option is checked and the Year receiver is empty.

**Comment by rdstern** [comment]
These QC rainfall changes look simple and great they have come from Shadrack.  Possibly move to Milestone 4.33.

**Comment by Wycklife** [comment]
@dannyparsons You can assign this task to me

**Comment by maxwellfundi** [comment]
@Wycklife whats the situation with the first issue here? You fixed 2 and 3 in your PR #5337 ?

**Comment by Wycklife** [comment]
@maxwellfundi I found the first part a bit complicated but I'm still going through it. I will need some help from you.

**Comment by maxwellfundi** [comment]
@Wycklife  can we revisit this

**Comment by rdstern** [comment]
@shadrack can this be closed?

**Comment by shadrackkibet** [comment]
Yes
