### ISSUE TITLE
Climatic > Prepare > Transform small issue 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5280]
I hope this is an easy one to check and fix.  That is if I have understood the command properly.

I wanted to use the Climatic > Prepare > Transform for a very simple calculation, namely to provide a column to give the raindays.
I usually use the calculator and prepare a logical column using (for Dodoma) (rainday <- rain > 0.85).
I tried with the Transform Count, just counting over 1 day.  It seemed to want to count over 2 days, but was inconsistent.  When I returned to the dialogue the code seemed different.  Here is what I get the first time I go into the dialogue with the count being over 1 day:
![image](https://user-images.githubusercontent.com/11226469/55137847-f48e8280-5129-11e9-8a40-b05024f7bd84.png)

Code generated by the dialog, Transform

rain_day <- instat_calculation$new(type="calculation", function_exp="(Rain >= 0.85)", result_name="rain_day", calculated_from= list("Dodoma"="Rain"))
transform_calculation <- instat_calculation$new(type="calculation", function_exp="zoo::rollapply(data=rain_day, width=2, FUN=sum, align='right', fill=NA)", result_name="rainday", sub_calculations=list(rain_day), manipulations=list(), save=2)
data_book$run_instat_calculation(calc=transform_calculation, display=FALSE)
rm(list=c("transform_calculation", "rain_day"))

If I go back to the dialogue it has changed my name back to count and it now generates something different - as follows:

# Code generated by the dialog, Transform

rain_day <- instat_calculation$new(type="calculation", function_exp="(Rain >= 0.85)", result_name="rain_day", calculated_from= list("Dodoma"="Rain"))
transform_calculation <- instat_calculation$new(type="calculation", function_exp="zoo::rollapply(data=rain_day, width=2, FUN=sum, align='right', fill=NA)", result_name="count", calculated_from=list("Dodoma"="Rain"), sub_calculations=list(rain_day), manipulations=list(), save=2)
data_book$run_instat_calculation(calc=transform_calculation, display=FALSE)
rm(list=c("transform_calculation", "rain_day"))

Neither give me the answer I want.

**Comment by dannyparsons** [comment]
@Muthenya can you look into this? It should just need to correctly put `width=1` in this case.
