### ISSUE TITLE
Climatic > Prepare > Climatic Summaries and missing values

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5291]
**Describe the bug**
The dialogue doesn't cope with the missing values options

**To Reproduce**
Use the Ghana data.  Use Date > Infill > Then Add the years, months, etc with Use Date and make into climatic  I provide the data when this is done.

Then use the Climatic Summaries dialogue.  

**Expected behaviour**
It gives missing values whenever anything is missing.  I expected the checkbox as on the general summaries for the Omit Missing, but it isn't there.  Should it be.

Then I tried various options from the missing, and all are ignored.

**Comment by dannyparsons** [comment]
Yes I noticed this before too. Just need to add the same omit missing checkbox as on Column Summaries.
@africanmathsinitiative/developers I would make this a priority task, its important and should be simple.

**Comment by rdstern** [comment]
Thanks.  I agree.

I have now got to that section in the R-Instat climatic guide and could use that checkbox.
In addition to the checkbox the taking account of the missing options in the sub-dialogue is also important.  I hope that will also be easy.  I am writing the guide assuming both have been done.
Thanks
