### ISSUE TITLE
Prepare > Column:Text > Find Replace

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#5295]
The string handling dialog has one of its radio button half hidden and the text not visible. Please see below. 

![image](https://user-images.githubusercontent.com/9798689/55784370-bc375e80-5ab0-11e9-8b95-0e81c27cc246.png)

**Comment by Ivanluv** [comment]
@maxwellfundi  should we have the regax keyboard disabled as below or have it hidden?
![Expect](https://user-images.githubusercontent.com/45068931/55860155-41d41080-5b7c-11e9-840d-60d0655030ff.PNG)

**Comment by maxwellfundi** [comment]
@Ivanluv Please check from the code when the regex keyboard is needed and you can show and hide it. @rdstern When do we need the regex keyboard?

**Comment by Muthenya** [comment]
@maxwellfundi it is required when the Regex radio button is checked but currently both the `regex` and `fixed` radio buttons are hidden since the Include Regular Expressions checkbox (which controls the visibility of the two radio buttons) is currently disabled.

**Comment by Muthenya** [comment]
Could we 
1. Bring the receiver and textboxes up a bit?
2. Move the unseen radio buttons (regex and fixed) to come after the receiver and textboxes?

![image](https://user-images.githubusercontent.com/32125033/56037857-0af72980-5d39-11e9-9750-43d67fda6ae2.png)

**Comment by shadrackkibet** [comment]
The current design looks good (see below). It was updated extensively by @lilyclements in PR #5848.

Regex is a huge topic and discussions started in #5472.

![image](https://user-images.githubusercontent.com/26301973/108604140-097afb80-73bd-11eb-9862-580e444b000e.png)
