### ISSUE TITLE
Calculating climate normals in R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5300]
[climate normals.pdf](https://github.com/africanmathsinitiative/R-Instat/files/3075718/climate.normals.pdf)

We are proposing that R-Instat become the products and applications partner to Climsoft.  A recent request (by Mozambique Met service) is for Climsoft to be able to calculate climate normals.  This would be quite a challenge for Climsoft and we should consider (reasonably urgently) providing this facility in R-Instat.
The WMO guide (attached) is very helpful and what we should use.

There are perhaps three steps towards being able to do these calculations:
1. Be able to do them manually for some stations.
2. Be able to check and improve station records to facilitate the calculations
3. Be able to automate the process, so it is really easy for NMS staff.

When there are good data we can calculate climate normals now, using our Climatic > Prepare > Climatic Summaries (or the main Prepare > Column: Reshape > Column Summaries) dialogue.  I assume the climatic one will soon anyway be able to handle missing values, see #5291.

I propose step 1 is easy and we do it reasonably quickly.  It is an extension of our criteria for calculating summaries when there are missing values.  It extends the missing values calculation in the following way:

The definition in WMO is to calculate the monthly value unless:
a) Observations are missing for 11 or more days in the month (which we can already do)
b) Observations are missing for 5 or more consecutive days in the month - which we can't do.

Some countries use 5 or more instead of 11 above and 3 or more instead of 5 above, which we would automatically accommodate.
I don't think we need to get clever about missing periods that overlap months.  We just look for consecutive missing values in the month.

So we need to be able to add this to our missing criteria and set defaults and we are away.

The WMO guide discusses three main items that I interpret here as Step 2.
a) Being able to **infill missing values** in ways that can be recommended.  This is vague, but we are starting towards this with our work on satellite data.  The WMO guide does not like methods that don't add information (e.g. interpolating) and discusses radar, neighbouring stations, satellite, etc.  
b) Checking on **homogeneity** and being able to adjust.  This is a big and important area that I discuss separately.  We would need to include this by a launch - if we have one! 
c) In homogeneity it particularly mentions changing stations, including automatic stations.  That reminds us that we need to start with facilities to be able to handle within-day records easily - and by the launch!

**Comment by shadrackkibet** [comment]
My target during the internship will be to implement these two topics in R-Instat (Climatic Normals and Homogeneity). I hope the Kenyan Met Staff will find this interesting and easy to do using R-Instat.

**Comment by rdstern** [comment]
I find both to be important.  Both are also useful and interesting for you to write up for your project.  They are of very different sizes.  The climate normals can (I think) be done ok in R-Instat as soon as we have the small addition for missing values.  This also follows well from your earlier work.  I am also ready to write the documentation and can start that now.

Homogenisation is really important and a more formidable task - but I hope "just" means implementing the homogen function from within R-Instat.

**Comment by shadrackkibet** [comment]
I have now implemented R code for this check. Initially did this for the mean. Once that is approved it will be straight forward to do for other summaries. This issue is related to #5310

**Comment by rdstern** [comment]
That would be great.  Do you want someone from AMI to amend the missing tab in the dialogue, or would you wish to do the complete task yourself.

In the code what is needed is to be able to have the number of consecutive missing, at the same time as the total number of missing, as mentioned above.

**Comment by shadrackkibet** [comment]
I am happy to complete the task myself. If someone is willing to join that is highly welcomed.

**Comment by dannyparsons** [comment]
These would be great to work on, thanks Shadrack. I've commented on the summaries changes and happy to discuss the implementation of these different components too.

**Comment by rdstern** [comment]
I have now been looking into this in more detail.  I suggest there are 2 key references.  One (and the main one) is the 2017 climate normals document by WMO, for which the link is right at the top.

A second one is a paper showing what the US has done on its climate normals.  It is consistent, but with slightly different "Normals" to those proposed by WMO.  For example they include quartiles as examples of normals, while the WMO report suggests quintiles.  One reason to include both is to tempt NMSs to think what they would like, rather than simply following one or other.

On the positive side, I think all we need - except for the extra missing value option - is already in our summaries dialogue.  Great.  And given all this flexibility in what to produce, having an R-Instat approach seems fine at this stage.  Once a country decided exactly what they want to do - and has lots of stations - then writing a script would be the way to go.

I am about to draft the chapter in the climatic guide
