### ISSUE TITLE
Fitted values etc not working on some modelling dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5307]
I think this is a general problem, so could use our "standard" survey data and fit any model.  I was using temperature data from Ghana.

I used the **Model > General > Fit Model**.  It works OK, but when I try to **save the fitted values** it gives an error.  It says it needs data of the right length.

The **Model > Two Variable > Fit Model** works fine (as far as I can see.  So copying what is there may be all that needs to be done to fix this.  If so, then please also include **Three Variable** (which I would like to use) and Four Variable at the same time.

(As usual I am finding these problems in writing the climatic guide.  I am now temporarily OK, because I can now use the 2-variable case, then put the correct model into the script.)

I am suggesting that either Steven or Lazarus could fix this?

**Comment by rdstern** [comment]
There are some more issues on the fitted values - even for the two variable case.
a) When the data are filtered, the fitted values are given for all the data.  I had 2 stations and filtered for just one.  When I removed the filter I saw that it had also given fitted values for the data for the other station.
b) Where data is missing the fitted values are also given as missing.  Is there an option for this?  The residuals have to be missing, but the fitted values could be calculated and given.  It is often used as a way of estimating missing values.

**Comment by stevenndungu** [comment]
Looking at this. 

We just did tests of the dialogues using various data sets with @Muthenya since I was not able to reproduce the error. We have found out that the error occurs ONLY when using the temperature data from Ghana. 

This is fairly odd. Investigating the error.

**Comment by rdstern** [comment]
I wonder if this might need a more general (quick I hope) explore?
@stevenndungu mentions the problem of missing values is part of the issue here, because the Ghana data had some missing values.

That is a general problem in regression modelling.  There could be missing values in either the x's or in the y's.  Often it is just in the y's.  In that case one use of the modelling can be to estimate the value also at the missing y.  That links to the prediction idea, namely that you could use the model to predict values at new x's.

In the standard R documentation on the generic fitted function it mentions the use of the functions naresid and napredict to cope with missing values.

More recently there is the **broom** package, which tries to link model outputs to tidyverse.  Should we be using that?  This seems, in general, to link nicely with the idea that we put data into data frames.  It has 3 functions, namely tidy, augment and glance.  It is currently augment we should perhaps be using here?
I am including @dannyparsons and @volloholic here to get their reactions.  Perhaps this is also a time to include Sam or Nicolas in this discussion?
