### ISSUE TITLE
Minor changes to the climatic menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5311]
1. In Climatic > Check Data  the last 2 items are QC Rainfall and QC Temperatures.  Could they please be exchanged.  (The temperatures are more important than the rainfall, so they are first in the guide.  It would be logical to have them in the same order in the menu.
2. In Climatic > Seasonal Forecast Support the last item is Cumulative/Exceedance Graphs.  
a) Delete the s - make it Graph and not Graphs.
b) Keep it there, but have a copy also in Climatic > PICSA.  It should be just under Rainfall Graph. 

At the same time, you may wish to consider an item in #5228, i.e. adding a call to P=plotly from the toolbar.  I really like the current graphics item and use it a lot.  Could that become a double item - like the Open - the first in the toolbar.  So, if you click on the graph picture you get what we have now.  If you use the down arrow, you can choose between R Graph and plotly?

But if this takes too much discussion, then please start with the other minor items above.

**Comment by maxwellfundi** [comment]
@Wycklife  Could you make the changes 1 and 2 in this issue. Should not take much time then i will go through the other part.
