### ISSUE TITLE
Small day range problem

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5315]
I suggest this is a simple problem that anyone can look at.  (It maybe that @maxwellfundi could fix it very quickly.

The Day range sub-dialogue is used by many of the dialogues in Climatic > Prepare.  There are 2 controls, one for the start day and the other for the end day.  

Sometimes the End Day setting depends on the Start Day.  So, **if the Start day setting is changed, then the End day control should refresh**.  Currently it doesn't.

If data are needed, then the Moorings data is a good example, see #5313 for the data.  But Samaru, Nigeria  in the library will do.  

![image](https://user-images.githubusercontent.com/11226469/56847433-b627e700-68d2-11e9-8e99-b0f960821c02.png)

In the figure above first with Fixed start day of Jan 1st and End day is the third option, Length - make it 90.  Press Return.  This is fine.  You get 154 as the start and 154 + 90 as the end.
Now change the Start Day to be Feb 1st.  Press Return.

Now it is wrong.  You get 185 as the start and still 154 + 90 as the end. 

Other situations are more complicated, but I think all may be fixed if the End date refreshes.

**Comment by dannyparsons** [comment]
Looks like the end date just needs to be updated in this case when the start changes. @africanmathsinitiative/developers someone could take this up

**Comment by maxwellfundi** [comment]
@Ivanluv what the situation with this issue?

**Comment by Ivanluv** [comment]
@maxwellfundi  am still looking on it
