### ISSUE TITLE
Order of layers still swapping on ggplot

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5321]
The plotting is holding up much better now, than previously.  And I have been producing many plots for the climatic guide.

But I have (at last) found a simple reproducible example where the order of the layers still swaps (and where it then again says the offending layer can't be edited, because it is on the base layer.

The graph below has 3 layers.  Main one is a boxplot and then the additional layers are a line plot and then a point plot.

![image](https://user-images.githubusercontent.com/11226469/57176071-41f9c000-6e4b-11e9-8180-14d86b50648d.png)

The data are here:
[mooringsplottest.zip](https://github.com/africanmathsinitiative/R-Instat/files/3144139/mooringsplottest.zip)

Main plot is from Moorings and is a boxplot of cumsum against dekad_abbr.

Then add  2 more layers: first is line plot and is for the newyear data frame.  y  is cumsum and x is dekad
second is point plot with the same x and y.  Change the size of the points to 3.5 and the colour to blue.
You should now get the plot above.
(If not, then perhaps the filter needs to be set again for Moorings.)

Now go in and edit both the 2 additional layers and change the x variable to dekadoct.  Do it for both together (one at a time and it is ok).  Now do the plot again.

The blue points have now gone, the order of these layers is now changed and neither can be edited further.

I hope this helps!

**Comment by Ivanluv** [comment]
@maxwellfundi can I take this up?

**Comment by dannyparsons** [comment]
This relates to editing layers issue so good if you can look at this as well.

**Comment by volloholic** [comment]
There are probably now multiple issues mixed up here. I looked quickly at #5397  and #4899 with @rdstern  and the problem was simply that the main geom has not been assigned a position when first set. This is the iposition parameter when adding the geom to the base operator. 
We will follow up this issue over the next day or two.
