### ISSUE TITLE
the one-variable fit no longer works

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5323]
I am looking at fitting extreme value models.

I started with the one variable, which used to work quite well.  

Now it doesn't.  Here is an example of the code generated to fit a normal distribution - just the first 3 lines for now:

**max <- data_book$get_columns_from_data(data_name="ghana_by_year_station", col_names="max")
max <- data_book$get_columns_from_data(data_name="ghana_by_year_station", col_names="max")
last_model <- fitdistrplus::fitdist(method="mle", distr="norm", start=base::mean(x=max), data=base::as.vector(x=max))**

It is quite a complicated package, but getting the initial fit) command to work again could be easy.
a) I notice - the initial line is repeated twice.
b) In the main command the data argument is given last.  That's not a problem, but it is first in the documentation.
c) It is given with the initial base::, which is not needed
d) If I get rid of the start argument in the code, then it works without error.  
e) In fact then the whole code works without error, so I get a picture at the end.

So, I propose that initially the code be examined and simplified.
Also initially try to get it working without the start argument.  (I think it isn't needed for most distributions.
However it IS needed for the extreme value distribution.  (Which is an important one) So, eventually it will have to be given, at least for that distribution.
That may need a bit of Danny help.

**Comment by Ivanluv** [comment]
am taking this up
