### ISSUE TITLE
Small addition to bar charts to reverse the stacking

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5329]
Here is a stacked bar chart:
![image](https://user-images.githubusercontent.com/11226469/57567495-0f634080-73d2-11e9-803a-a5bcd4b7ea40.png)

It has a problem that the low values of the factor in the stacked bars (low wind speeds) are at the top.  I would like them to be at the bottom - seems logical to me!
Like so:
![image](https://user-images.githubusercontent.com/11226469/57567531-7f71c680-73d2-11e9-8d4b-f537a3d2a872.png)

This can be done in the R-code with geom_bar(stat="count",position = position_stack(reverse = TRUE))
Could we offer this in the bar chart options?  It could be labelled as stack - reverse perhaps.

If so, then I presume we should assume it (and try it) for histogram too?

**Comment by dannyparsons** [comment]
In future we need to implement these "function parameters" such as `position_stack`. But for now we can have this as a fixed string as an option for the position, labelled "stack reverse" as Roger suggestions. @maxwellfundi someone can implement this in the geom definition.

**Comment by Ogik99** [comment]
This issue can now be closed.
