### ISSUE TITLE
Adding the circular mean, etc into R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5332]
I write this issue in detail.  I have added it (temporarily) to the first milestone to ensure a quick discussion on the strategy proposed below - rather than the programming.  And the results may be useful for a current MSc essay, which is one reason for the urgency.

I start with the circular mean - which is useful in its own right - later there should be a Circular keyboard for the calculator and a Circular tab for the **Prepare > Column: Reshape > Column Summaries**.  This could even start with the single calculation of the mean.

One question is whether we use a package, or write our own functions.  There are 2 packages for circular statistics, namely **circular** and **CircStats**.  They have lots of things, but neither seem ideal for the simple calculations.  Circular makes you define a new data type - which might be useful - that's a point for discussion.  CircStats is much simpler, but their function for the mean doesn't seem to include the adjustment na.rm=TRUE/FALSE to allow for missing values.

[Here](https://stackoverflow.com/questions/32404222/circular-mean-in-r) is an article on StackOverflow that explains what is happening and usefully discussed (and solves) what happens when the answer is negative!

And Wikipedia has a really simple example to try [here](https://en.wikipedia.org/wiki/Mean_of_circular_quantities). 

If we were to write our own functions, then I am sure we could get Sam to write them for us.

The example I have is in degrees, while the R functions work in radians.  The examples in Wikipedia are 10, 20, 30 degrees, with a mean of 20 degrees.  Then subtract 15 to give 355, 5, 15 and a mean of 5 degrees.

Here is the formula:

a) sinpart <- mean(sin(wd*2*pi/360),na.rm=TRUE)
b) cospart <- mean(cos(wd*2*pi/360),na.rm=TRUE)
Then: c) circmean=atan2(sinpart,cospart)*360/(2*pi)

We could presumably assume the data are in radians only?  We shouldn't fix on degrees, because the circle could also be 360 degrees, or 366 days, or 12 months, or 24 hours.  Perhaps our function could include a Units argument?

So I can now use **Prepare > Column: Calculations > Calculate** to get the circular mean.  Could I also use **Prepare > Column: Reshape > General Summaries** to get the means per day from hourly data, which is what I need now?

What should our strategy be.  I was assuming before that we will probably make good use of the circular (and possibly circstats) packages.  We may do, for the distributions and fitting parts.  But I am now wondering what is for the best for the summary statistics calculations?

**Comment by rdstern** [comment]
If we work anyway on the full circular keyboard (and set of summaries, the formulae are all relatively simple, at least they are once you can calculate the mean as described above.

A clear reference that gives all the formulae is [here](https://ncss-wpengine.netdna-ssl.com/wp-content/themes/ncss/pdf/Procedures/NCSS/Circular_Data_Analysis.pdf).

We would also have Variance, Standard Deviation, Dispersion, Skewness, Kurtosis.

I have tried looking for median and I suggest we ignore that - at least for now.

**Comment by rdstern** [comment]
Now I have looked at the circular package a bit more and am warming to the idea of using it!
I have tried with the data wd = (10, 20, 30) degrees as suggested by Wikipedia.  
Then subtracting 15, so circular mean should be 5 degrees.  
Then (not in Wikipedia) I subtract 10 more so the answer is 355 degrees (which Circular gives as -5 degrees).  

So then I do (mean+360)%% 360 which always makes it positive - to give it as 355 degrees.

In the R-Instat calculator this works fine as:
a) circular::mean.circular(wd/360*2*pi)
This gives a summary if in the results window and just the mean (in radians) if I save it.
b) circular::mean.circular(wd/360*2*pi)*360/(2*pi)
This gives 20 directly, or 5 or -5 for the other data.
c) We do have a function deg to transfer back into degrees.  This is from the circular package
circular::deg(circular::mean.circular(wd/360*2*pi))
This is an alternative to b)
d) circular::**mean.circular**(circular::**circular**(wd,units="degrees"))
This defines wd as circular and in degrees.  It then gives the results directly in degrees.
units could also be "hours", which is useful for us.
One problem is that the mean may be negative.  I think if we add modulo="2pi" in the circular::circular command, then it doesn't matter whether the data are in different units.  So we could have radio buttons to specify radians (default), degrees, hours.  And then we could specify the summary and add the circular command, both for the calculator and the column summaries dialogue.

If we use the circular package, then we also have there:
sd.circular, var.circular, median.circular and medianHL.circular

If this is a simple thing to do then it would be very useful reasonably soon.  @volloholic says it is well within the AMI team's capabilities!

**Comment by rdstern** [comment]
I therefore suggest we start with the calculator, where we can already do everything in the current system, just typing in the commands.

There would be a new small keyboard with overall label Circular

Then keys that can mainly be copied from the summary keyboard.  They are for
mean, median, medianHL, range, sd, var

Then there is a set of radio buttons giving **radians, degrees, hours** as the three options.
Then the command is given as:

circular::command(circular::circular(column_for_analysis, modulo = "2pi", units = "degrees"),na.rm=TRUE or FALSE)

This can sometimes be simplified:
a) If "radians" is chosen, then don't need the units.
b) If range, sd, var, then don't need modulo="2pi"
c) So if using range, sd, var, and the units = "radians" then don't need the circular::circular command at all.  So the command could simply be circular:sd.circular(column for analysis)

Once the keyboard is working, then it will be great to have the same set of facilities in the Climatic Summaries dialogue.  That will have a new Circular tab and could start with the mean - though it may be almost as simple to do the set of keys together.

**Comment by shadrackkibet** [comment]
Adding this to the summaries subdialog is not yet done. So this should remain open.

**Comment by rdstern** [comment]
@Wycklife I have just been looking at the circular keyboard on the calculator.  Great that it is there.
a) I think it has na.rm=FALSE as the default for all the summaries.  The ordinary mean in the summaries keyboard has na.rm=TRUE so it would be good to change to that, on the circular keyboard, for consistency.
b) When you use the option to show the arguments, the end of the command is ,... and the function doesn't run with that.  Good to not have that.
c) Now a larger one.  There should be radio buttons below the keyboard - still part of the group box.  They could say "Units", with the 3 options radians, degrees, hours.  The default is radians.  
d) Then, add into the control.circular=list() modulo="2pi".  I think can be there always, i.e. control.circular=list(modulo="2pi").  If the units are not radians then add **,units = "degrees"** or **,units="hours"** into the list, e.g. control.circular=list(modulo="2pi", units="degrees")

**Comment by rdstern** [comment]
I have been trying to rewrite the circular chapter in the climatic guide.  That gave me a small problem in suggesting how the commands should work in the keyboard.  For example:  
1. The mean is given as follows - when the data are in radians.
circular::mean.circular(circular::circular(x,modulo="2pi"),na.rm=TRUE)
2. When in degrees the mean is:
circular::mean.circular(circular::circular(x,modulo="2pi",units="degrees"),na.rm=TRUE)

These are very complicated!  This is because we are defining the data as circular "on the fly".

Sorry @Wycklife I am suggesting some changes, particularly after discussions with @volloholic 

I suggest the circular keyboard becomes 4 by 4 instead of the current 5 down and 3 across.  There are 2 small additions.  The main one is circular, which defines the variable as a circular one.  That simplifies all the other keys.

Here is my proposed layout:

circular      sd         min   range
mean        var           q1   rho
median   ang.dev     q3   quantile
medianH ang.var   max   A1

The first one, circular has default code:
circular::circular(   ,modulo= "2pi",units="radians")

Then the mean is, 
circular::mean.circular(  ,na.rm=TRUE)  and so on.
The same for all the other location keys, i.e. median, medianH, min, max, q1, q3.
3. For the spread variables i.e. range, sd, var,ang.var, ang.dev , similarly
circular::range.circular(x,na.rm=TRUE)

5.  There are conveniently 2 more spaces on the keyboard.  So add rho (another measure of spread) and quantile.  You already use the quantile for the median and quartiles, but it makes it clear if there is a key.

This is then similar to the keyboard for dates, where we have a date key.  As with Dates we also suggest a new menu item as well, namely
Prepare > Column: Define > Circular  
This will then have a Circular dialogue - that's a separate issue!

**Comment by rdstern** [comment]
@Wycklife the issue has become much simpler, since proposing that we add a set of keys and also a special dialogue to define variables as climatic.
The remaining dialogue is the extra circular tab in the Prepare > Column: Reshape > Column Summaries dialogue.

On this Tab I propose that (unlike the calculator) we assume the relevant columns are circular - defined elsewhere.

I suggest 2 blocks, with one named Location and the other named Scale.

In each we have the usual check-boxes.

So, in Location we have Mean, Median, MedianH, Min, Max, Q1, Q3, ideally also quantile, but that could come later, because it needs and extra control.

In scale we have sd, var, ang.dev, ang.var, rho, range.

**Comment by Wycklife** [comment]
@rdstern Sorry for late reply, I've been away. I'm happy to make these changes right away

**Comment by Wycklife** [comment]
@rdstern On the issue of adding radio buttons, we had a discussion with @shadrackkibet and he suggested not to have it on the keyboard.

**Comment by rdstern** [comment]
@Wycklife welcome back.   That's right now.  As we define data to be circular, before using the functions such as the mean, we don't need the radio buttons any more.  It has made the commands much simpler.

**Comment by shadrackkibet** [comment]
Just to check, Is someone working on the R code for the summaries sub dialog?

**Comment by rdstern** [comment]
@Wycklife is working on circular, but I am not sure if he is yet doing the tab on the summaries dialogue.  That's all that I know.  And that would anyway start at the VB end I assume.

**Comment by Wycklife** [comment]
@shadrackkibet  I thought we were to do it together after the design?

**Comment by Wycklife** [comment]
@rdstern I'm working on the design for the tab. When it's ready then I would like to put it here for discussion before R code is added.

**Comment by shadrackkibet** [comment]
Since we are making an assumption that a column has been defined as circular when we are getting summaries. I think we should add this facility somewhere.

**Comment by rdstern** [comment]
@shadrackkibet yes indeed we should define it somewhere.  That's what is specified in #5474.
In addition there should be an extra circular button in the calculator - I have asked Wycliffe for this that does the definition there.  It just gives the circular::circular command

**Comment by Wycklife** [comment]
@rdstern @shadrackkibet Yes I've added the button. I see it has several parameters, should I just add them all?

**Comment by shadrackkibet** [comment]
Yes, all these parameters should be added for the calculator button.
`circular(x, type = c("angles", "directions"), 
  units = c("radians", "degrees", "hours"),
  template = c("none", "geographics", "clock12", "clock24"),
  modulo = c("asis", "2pi", "pi"), 
  zero = 0, rotation = c("counter", "clock"), names)`

**Comment by rdstern** [comment]
It doesn't matter having all the options, but most are for the graphs - which we don't use.  And the package says it doesn't yet use type.  The 2 important ones are modulo, where the default should be "2pi" and units where the default is the same as the package I think, namely "radians".

**Comment by dannyparsons** [comment]
> @Wycklife I have just been looking at the circular keyboard on the calculator. Great that it is there.
> a) I think it has na.rm=FALSE as the default for all the summaries. The ordinary mean in the summaries keyboard has na.rm=TRUE so it would be good to change to that, on the circular keyboard, for consistency.

I think the "show arguments" is meant to show the default R values for the function. I'm not sure why the default for `na.rm` in ordinary mean is `TRUE`. Shouldn't we be consistent with the R default, and our default in Column Summaries etc. and have `na.rm = FALSE`? If so then the circular functions should also stay as `na.rm = FALSE`?

**Comment by rdstern** [comment]
Oooh, I have just asked Wycliffe to change to TRUE, partly to be consistent with the ordinary mean.  We don't always do the R defaults and I rather liked the flexibility that without the arguments it does the R default.  Then, when you include the arguments it does the other R-option?

**Comment by dannyparsons** [comment]
I think we want consistency whether you show arguments or not. So simplest is to keep the R defaults for "show argument" so its the same as no arguments.

Sorry @Wycklife! I think we are going back to `na.rm = FALSE` in all cases. It was good this came up though as we notice the regular summary functions need changing. Can you make both the circular and summary tabs to have `na.rm = FALSE` for the functions?

**Comment by shadrackkibet** [comment]
The summaries tab is okay, we have `na.rm=FALSE` as the default.

**Comment by Wycklife** [comment]
@dannyparsons Okay, but the tab is okay. Just changing the position only for the tab.

**Comment by dannyparsons** [comment]
Sorry I meant the Summaries Keyboard, I was only meaning the Calculator dialog and the show arguments options.
