### ISSUE TITLE
New possible plot for the climatic data 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5342]
When we use Climatic > Check Data > Display daily

we currently have a table of the daily data.  But we don't have a good graph.  This is the openair::summaryPlot function with the data from one of the Ghana stations.

![image](https://user-images.githubusercontent.com/11226469/57971587-f76a5e80-7987-11e9-8643-3881151b0f12.png)

It (I assume) uses the lattice system, rather than ggplot and there are some things I am not so sure about.  But it is the sort of thing we should have.

I wonder if we might initially test this function more and then perhaps (initially?) include it.  We might later want to prepare our own version in ggplot.

**Comment by rdstern** [comment]
I now think it should be quite easy to prepare our own version using ggplot from the start.  Here is an example with the hourly data and our current line plot dialogue:
![image](https://user-images.githubusercontent.com/11226469/58766278-e2dbb800-857c-11e9-843c-06cb710b5846.png)

This would already be useful.  The code (in ggplot) is simple enough that it might not need a function.

This does not have the strip in the graph above, showing missing values, but that would be an optional extra.  It also doesn't have the histograms, but I don't want those anyway.  (That's a different dialogue, i.e. One Variable (or two variable) Graph.

I would like it to offer the choice between:
a) One element at multiple sites
b) Multiple elements at one site

The graph above is multiple elements and I had to stack myself, to be able to get the facets (and for them to be a single column, and free-scale y.  I also used strip.position="left" - could also be "right" instead of the default "top".  This would be quite useful to have.

I would be happy to start with this.  

If easy, then the option in the openair function include clip = TRUE.  This is a checkbox.  If selected, then you select a percentage and it gets rid of the higher values, e.g. 99 means clip the top 1%, i.e. set them to missing..  This could be a In principle we could clip at the top and bottom, but I would be inclined initially to follow the openair example and just clip the top.  

The dialogue is almost there already.  It is Climatic > Check Data > Display Daily > Graph
Currently that shows a year at a time.  That would change into this dialogue.  It would have the option for single or multiple elements.  Currently it is set to multiple.

**Comment by rdstern** [comment]
An additional point.  With the power of ggplot it should be possible to find a clever way of limiting the axes to percentiles of the data. In the answer to a question on getting rid of outliers in boxplots it has some interesting ideas about coord_cartesian, and scale.y.continuous, see [here](https://stackoverflow.com/questions/5677885/ignore-outliers-in-ggplot2-boxplot).

**Comment by shadrackkibet** [comment]
I personally like the output produced by openair::summaryPlot function and also it will be straight forward to implemnt quickly in R-Instat. I will also discuss this with Samuel to see if this is something they would like.

**Comment by shadrackkibet** [comment]
Now I see the constraint that we might have with `openair::summaryPlot` function. I tried to apply this to Kenya temperature dataset. There are 38 stations in the dataset and now I would like to have this plot per station so that I can check which station has a lot of missing values. This is not possible with `summaryPlot`  but this will definitely be possible with ggplot2 facetting. 

`summaryPlot`
![image](https://user-images.githubusercontent.com/26301973/59483113-8e85e180-8e74-11e9-8982-e3ef4c0c1bf3.png)

This is the plot I would like to have, which is possible by stacking and using Line plot dialog.

![image](https://user-images.githubusercontent.com/26301973/59484152-4a491000-8e79-11e9-8cf6-c5609ff96e17.png)

**Comment by rdstern** [comment]
Interesting.  I also wonder whether adding an optional rug plot will permit the missing values to be shown explicitly.  Also the inventory plot could be useful, if the main emphasis is to see where there are missing values.  And, I hope that the 38 stations could have some useful metadata, for example the region in Kenya - is there anything bigger than a county?  Then we look separately at Western Kenya, etc.

**Comment by dannyparsons** [comment]
Some space could be saved by not having a free y-axis, unless this is desirable.

**Comment by rdstern** [comment]
Here is an example with a rug plot and the Dodoma data
![image](https://user-images.githubusercontent.com/11226469/61433888-69313b00-a92c-11e9-8299-498e3ff87a56.png)

I think it is possibly better with the rug at the top:
![image](https://user-images.githubusercontent.com/11226469/61434067-de047500-a92c-11e9-9cc5-df1cebb45178.png)
Having a colour option for the rug is perhaps useful?
![image](https://user-images.githubusercontent.com/11226469/61434362-a21ddf80-a92d-11e9-8e15-f2d33eef84cd.png)
 And I quite like the option of colour - though we don't need the legend:
![image](https://user-images.githubusercontent.com/11226469/61434718-9bdc3300-a92e-11e9-9b6c-ac765a2ca18b.png)

**Comment by rdstern** [comment]
To do this for multiple elements I stacked the data, then did a line plot.  I then did a simple 
Rug <- ifelse(is.na(value),NA,Date).  The Rug is numeric, so I had to make it into a date with the R origin of 1/1/1970.
Then simply made that into the x-variable on the rug-plot layer.

**Comment by rdstern** [comment]
For multiple sites and a single element here is an example:
![image](https://user-images.githubusercontent.com/11226469/61470046-3f9e0100-a978-11e9-9a1d-c5e74ae2b71c.png)

It has the free-scale for the Y which works quite well here.  I suggest Free scale Y is the default if multiple elements and the same Y is the default for a single element, but you can have free scale then.

**Comment by rdstern** [comment]
Looking at the existing **Climatic > Check Data > Display Daily** I suggest this plot above could be a similar dialogue to the Graph there.
a) The new one could be simply Graph and a 3rd button could be **Graph by Year**.  
a) The existing dialogue is the Graph by Year and could remain.  It is designed particularly for rainfall, but it could be for any (single) element.  That graph by year function needs some minor changes.
1) I suggest the multiple receiver (which is fine for the new dialogue above) becomes a single receiver.  By default (when we have them) it is for rainfall.
2) It adds the option to have either **line or bar** geom.  (Bar is better for rainfall while line is for temperature, etc. )
3) It adjusts for a shifted year.  Currently the Month (x-variable) is always January to December.  It might need the Month field to be added to the dialogue.

Now the new one.  It has roughly the same fields, but could "take over" the multiple receiver from the existing dialogue.  Here the x-axis is the date, so it may not need some of the other receivers.
 I had thought we should choose between one element and multiple stations or many elements and one station.  But here is an example with 10 elements and 2 stations.  So I suggest that the Station field - when it exists - could become the 2nd factor.

![image](https://user-images.githubusercontent.com/11226469/61593503-28f5e500-abd8-11e9-898f-cfd90c13fdc8.png)

This example uses the Ghana data from the library.  The steps (from 1st principles) are as follows:
a) Stack the data for all elements (or the ones you want) and carry the date and station.
b) The data are now (by default) in a variable called value - which is quite a good name.
c) Use Prepare > Column Calculate > Calculations and DateRug > ifelse(is.na(value),date,NA)
d) Use Describe > Specific > Line Plot of value by date, with element as the factor.  Then both element and Station as facets.
e) Add a layer of the Rug, of the DateRug on x (keep y - it doesn't matter.  Then make it a colour and just on side = t (or b).
f) Before running the dialogue need next step - or use script.
g) Graph needs all x-s to be date, so make the DateRug into a date column with the R default of 1/1/1970.  (Currently can't have a date variable in the sub-dialogue, but that should be fixed soon.)

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers I need someone to make designer amendments here.

**Comment by shadrackkibet** [comment]
Now I am going to proceed with this task.

**Comment by rdstern** [comment]
@Ivanluv when I look at the example right at the top it would be better to swap the rugplot round, i.e. give the rug just when there are missing values, rather than when there are not.  I think you just have to get rid of the `!` in the formula.
