### ISSUE TITLE
PICSA Rainfall Graph Issues

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5351]
This is working much better. A couple of issues from testing the newest version. These are in order of importance roughly.

1. When I do facets, and add the mean line, I still get the overall mean, not the mean for each group. The `group_by` is not added in the code. It only gets added when colour is specified.
2. When I add a mean line the display on the label is not rounded. Here's the part of the code. So the `round()` part is not quite right. It should just be `round(.mean_y)`. Looks like its just being added twice in different ways.
`ggplot2::geom_label(mapping=ggplot2::aes(x=-Inf, y=.mean_y, label=paste("Mean:", round(.mean_y, x=mean(x=start_doy, na.rm=TRUE))))`
3. If I only specify the upper limit for dates and not the lower limit, then nothing gets added to the code. I should be able to specify one without the other.
4. When I open the sub dialog for the first time and check the date limits it looks like this. I'm not sure how someone is supposed to know what to type in the boxes that have `NA` currently, either there needs to be a label that says `Day`, but the `NA` is still confusing so better would be a default of `1` then I think its clear without a label. If I leave it as `NA` then it puts the date as "2016/January/NA" so something is wrong there.
![image](https://user-images.githubusercontent.com/11214914/58433428-2f238580-80af-11e9-81dc-26f4b04f8c25.png).
I've just seen its using the same textbox for the numeric and date upper/lower limits, which now makes sense why `NA` appears there. I suggest the code would be much easier if there were separate textboxes for numeric and dates, because they do different things.
5. Minor issue, it accepts any number for the day, so I can put "56 January" and it doesn't complain. It doesn't give an error but the date will comes out as `NA`, so ignored.
6. Very minor issue, the parameters are in the wrong order in `as.Date` here: `ggplot2::scale_y_date(date_labels="%d %b", limits=as.Date(format="%Y/%B/%d", x=c("2016/February/1", "2016/September/30")))`

**Comment by stevenndungu** [comment]
@dannyparsons  on 5 and 6. I am preferring to use NUD in place of the input text boxes for the case of dates only. Reason: The increment is constant and would be easy to set the max,min,defaults (the textbox is not working properly for this case). I hope that is okay?

**Comment by dannyparsons** [comment]
Yes good idea, and then its even clearer what the input should be, the user will already see it is an integer.

**Comment by stevenndungu** [comment]
Okay great.
