### ISSUE TITLE
Filter name should reset when defining a new filter

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5363]
When defining a new filter and typing a name for the filter, if I later define another filter it displays the same name as used previously. This is not really sensible because the rest of the dialog resets since it is a new filter. But currently its too easy for users to overwrite a previous filter.

So I suggest the filter name resets when we define a new filter.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers someone can take this up

**Comment by Ogik99** [comment]
> @africanmathsinitiative/developers someone can take this up

Currently working on this

**Comment by maxwellfundi** [comment]
@dannyparsons  A quick question here. I would like to urgue that, across all other dialogs, we have this behavior of having the previously user typed values in ucr saves for graphs and columns etc. Would this be something that would be sensible generally, or just for this case?

**Comment by dannyparsons** [comment]
The difference with this dialog is that it doesn't open in the same state it was closed, because you are explicitly choosing to define a new filter - so everything should reset. So I do see this as a special case.

Our principle for most dialogs is that they reopen the same as when they were closed. Not saying we shouldn't do this for all dialogs but I think the case is clear for this dialog but we'd need to have a good argument for doing this in general. Good to have that discussion but might not be a quick decision.

**Comment by maxwellfundi** [comment]
Okay, we have fixed it.

**Comment by dannyparsons** [comment]
For columns at least, we decided to have the current data frame columns so that you can see existing columns, replace an existing column or give a name similar to an existing name. That makes sense for columns, For graphs/models I think that's probably less useful but we kept it for consistency.

So, you're suggesting only to see the names of what has already been saved for that dialog? I could see advantages to that because you see names more relevant to what you're doing. It means the first time you use a dialog there's nothing in the drop down?

@dannyparsons A quick question here. I would like to urgue that, across all other dialogs, we have this behavior of having the previously user typed values in ucr saves for graphs and columns etc hence not sure if we want to change this more generally, or just for this case?
