### ISSUE TITLE
Installation Warning - get installer signed

### ISSUE THREAD

**Issue by chrismclarke** [africanmathsinitiative/R-Instat#5365]
**Is your feature request related to a problem? Please describe.**
When you download and install there is a fairly off-putting message displayed

![image](https://user-images.githubusercontent.com/10515065/59034379-d5674c00-8862-11e9-9bfe-dc16f17b2980.png)

You have to click more-info to enable run button

![image](https://user-images.githubusercontent.com/10515065/59034399-e3b56800-8862-11e9-8aab-a41aeb8905f2.png)

**Describe the solution you'd like**
Apply for a licence to have the code verified and signed. There's lots of vendors who offer this service, one of the most reasonably priced (and offers price match) that I've previously looked into is:
https://comodosslstore.com/uk/code-signing

They have packages for windows executables from around £60 (which will remove the message after a threshold of installations complete) or a couple hundred for enhanced signing (which should remove immediately). More general info at:

https://docs.microsoft.com/en-us/windows/desktop/win_cert/windows-certification-portal

**Comment by dannyparsons** [comment]
Thanks Chris, this is definitely on our radar. We have a similar discussion here #5202. I will move your comment there.
