### ISSUE TITLE
Change file extension in Export to CMSAF R ToolBox dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5366]
A very minor change needed to this dialog is that the extension of the file written should be `RData` instead of `Rdata`.

This is just to be compatible with the R ToolBox which expected the extension to be `RData`.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers someone can take this

**Comment by Ivanluv** [comment]
doing this now
