### ISSUE TITLE
Misleading R version Message

### ISSUE THREAD

**Issue by stevenndungu** [africanmathsinitiative/R-Instat#5374]
**Describe the bug**
Wrong R version requirement message. It says it requires 3.5.4 which apparently does not exist.  The message should be r version 3.6.0.

![image](https://user-images.githubusercontent.com/20383893/59348935-1955c780-8d21-11e9-9d51-d244a508cbd2.png)

**what happened exactly**
I had a problem with my R. When I uninstalled and installed again (version 3.6.0). I kept getting the above error.  But finally found a way out to have R-instat run.

**Comment by dannyparsons** [comment]
You're right, 3.5.4 doesn't exist. However, it can work with R 3.5.3, although really you need R 3.6.0 because to use R 3.5.3 you need to install R packages in RStudio using a special script.

I think we could change the message to 3.6.0 for simplicity, although its technically not correct. 
Happy for someone to make this change.

**Comment by stevenndungu** [comment]
Okay, I will make the changes.
"to use R 3.5.3 you need to install R packages in RStudio using a special script." Users will they be provided with the script, just incase they want to use R 3.5.3?
I will put 3.6.0. -  it works with no issues with it.

**Comment by dannyparsons** [comment]
The script is here in the wiki https://github.com/africanmathsinitiative/R-Instat/wiki/Using-R-Instat-with-R-3.5 but I don't think we need mention this in the error message. It is mentioned on the download page already.

**Comment by stevenndungu** [comment]
Nice, thanks. I had not read this.
It would have solved my problem earlier than :)  - rather than getting to 3.6.0.
