### ISSUE TITLE
Two small edits to the SPI dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5375]
This is working ok - at least for the SPI.  
Two small points:
1) Remove the upper limit from the  up-down control for the Time scale.  The limit is currently 24, i.e. it goes from 1 to 24.  There are situations when we want more than this.  The limit of 24 is 2 years if our data are monthly.  But the dialogue also works for 10-day or even daily data, where the limit would be much higher than 24.  So I suggest no top limit at all.  Still fine to have an up-down here, and going from 1 in steps of 1.
2) Currently the detailed results are printed in the output window.  This is partly because earlier it didn't save the resulting column.  Now it does.  I don't mind the model parameters being printed out.  But the detailed results are at least 12 times the length of the data frame.  Ideally printing them would be an option, but if that takes too long, then just don't print.  

I have put this as 5.1 in the expectation that it can be very quick.  Change the milestone if it isn't.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers someone can take this up

**Comment by Ivanluv** [comment]
am taking this up

**Comment by Ivanluv** [comment]
@dannyparsons  how do we implement the second Option

**Comment by dannyparsons** [comment]
the line that prints the output should not be run

**Comment by Ivanluv** [comment]
Great.Thank you
