### ISSUE TITLE
Tidy CLICOM climatic data - some small puzzles

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5383]
The data file provided by Mozambique Met (INAM) provided a series of slightly awkward features to reshape it for R-Instat work.  I don't yet have a copy of the data, but it is like this:
1. There are 69 variables.
2. Variables 1 to 7 are the element number, station code and year/month.
3. Variables V8-V69 are 31 days rain, V8, V10, V12, etc each followed by a flag field in V9, V11, V13, etc.
R-Instat worked perfectly, but was less easy to use than I would have liked.  I can think of many alternative solutions, and give the awkwardness (as I found it) to look for general solutions.

I have suggested the steps to tidy the data, but it was not quite as easy as I would have liked.  I may be missing something!

a) The big issue was that I wanted to put every other variable (X8, X10, X12...) into the receiver.  That's fine, but must be done manually.
b) We could ask INAM to change the input file.  It is comma delimited, but txt.  It is exported from CLICOM - but they don't have CLICOM anymore.  So they can't export again - without the flag fields.  But I think this will take them longer in Excel, and R-Instat reads their file perfectly.  The data read into R-Instat easier than Excel, so I would prefer them to leave their files as they are
c) I tried our **Right-click > Reorder columns**.  That was difficult to use, because the cursor "follows-the variable moved" in the control.  I wonder if we should change that in the control, so it stays where it is.  But I also don'r really want to spend too much time with the original file, because we won't use it later.
d) It might be a common situation to have these 62 columns, rather than 31.  In that case it should be possible to allow for this in the **Climatic > Tidy and Examine > Tidy Daily Data** dialogue?  (If it is common, then sometimes the flag fields might have useful information.)
e) It is an example of "wide" data, and we may want to be able to define "groups" - as SPSS does?
f) For now we just manually enter X8, X10,... into the receiver.

There is a second slight awkwardness to report, but we do have a solution in the pipeline.

The Year/Month is in a single variable, given as "2001-06".
a) Easy to use the **Prepare > Column: Text > Transform > Subset** to get the year and month.
b) But they are variables 70 and 71 and hence not visible.
c) Note they can be visible when we can choose where the results of a calculation can be stored.  So we will solve this minor issue - soon I hope!
d) Currently it is useful for the user to see that it worked.
e) But more important is that the resulting columns are character variables.  This gives an error in the Tidy dialogue.  So we need to right-click and change them to numeric - if we could see them!
f) Maybe the dialogue could be made to be more robust, by including an **as.numeric** for these fields.  Then they wouldn't have to change.
g) I solved this by changing the visible number of columns - I have always hoped the default could (soon?) be made higher than 30?  I could alternatively have changed them in the metadata, but it was useful that they saw the resulting columns.

As I said, it all works.  But I wonder (in the future) what should be done to "make it easy".

**Comment by rdstern** [comment]
I confirm the ideas above, that we now have with the data from the 14 countries.  I suggest 3 edits to the Climatic > Tidy and Examine > Tidy Daily data dialogue.

1. As mentioned above, when there is the 3rd option, i.e. 31 variables with one for each day, could there be an option to "Include Flag Field".  This is a checkbox, at the top to the left of the receiver.  Default unchecked.  If checked, then the receiver expects 62 variables, not 31 with every other one a flag field.  
If that option is used, then there is another option visible (possibly on the left, below the existing 2 options.  It says "Tidy Flags with the Data".  If ticked, then it doesn't unstack, but does deliver both variables, i.e. data in one variable and flag in the second.
2. In this option (i.e. 31 variables) it only works when the year and month fields are numeric.  If they are not, then could the dialogue include an as.numeric( ) so that it works if these are numbers but not stored as such.  This isn't trivial, because I think it does work with the Month stored as Jane, Feb, etc.  (If this is tricky, then ignore.
3. The unstack doesn't work if there are duplicate rows, e.g. 1993-04 typed twice, with one a mistake - one should be 1992-04.  I hope this instance can be detected in the command, so that a message can be given in the output window.  I'll check this with @dannyparsons

**Comment by dannyparsons** [comment]
3. Yes this can give an error/message when there are duplicates and the data won't be produced. I can edit this in the function.

**Comment by rdstern** [comment]
So could this work be shared.  In the tasks above @dannyparsons could perhaps do task 3, for when there are duplicates.  
@Patowhiz then does task 1, for the flag fields.  This is a bigger task.

After discussion with @dannyparsons we drop task 2.  It is more complicated, at least for the months, and not too difficult to ensure that the variables are numeric.

**Comment by dannyparsons** [comment]
I'd like to think about the options for 1. a bit more before we do something. My instinct is to have a separate receiver for the flags, but I know this wouldn't be ideal to use if they come in next to each other.
The changes for 1. and 3. are interlinked so they shouldn't be done simultaneously in different issues and should probably be done together at the same time, so I don't think splitting the tasks between different people is sensible.

**Comment by rdstern** [comment]
Happy for @dannyparsons to take this over.  So @Patowhiz I am taking you off this issue.  It needs Danny for one of items anyway, so (as he says), sensible that he does both.

**Comment by Patowhiz** [comment]
Sounds good.,
