### ISSUE TITLE
Key glyphs for legends - ggplot2

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5387]
[Key glyphs](https://ggplot2.tidyverse.org/reference/draw_key.html) are a new feature of ggplot2 3.2.0 for display of the legend.

Every geom has a new `key_glyph` parameter. It can be one of the `draw_key` functions but easier is just to give the name of the function. There are 16 in the documentation e.g. this is quite nice

```
p <- ggplot(economics, aes(date, psavert, color = "savings rate"))
# key glyphs can be specified by their name
p + geom_line(key_glyph = "timeseries")
```
![image](https://user-images.githubusercontent.com/11214914/59860618-24d76d00-9377-11e9-9598-2e43140efe34.png)

We can easily add the 16 options as a new geom parameter for every geom. Since this explicitly says it is for every geom then we should add this to all the geoms in one go with a for loop.

**Comment by Carolnikie** [comment]
I have reviewed this and it's working well on my side.

**Comment by dannyparsons** [comment]
Thanks for reviewing @Carolnikie. In future, commenting on the pull request about a review of the code is better so its in the same place as the code.
