### ISSUE TITLE
Adding labels to bar chart, etc.

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5398]
We have the Describe > General > Use Summaries dialogue which seems to work ok for bar charts - I haven't checked pie charts.  Here are data with an example:

[Dodoma_normals.zip](https://github.com/africanmathsinitiative/R-Instat/files/3344731/Dodoma_normals.zip)

![image](https://user-images.githubusercontent.com/11226469/60424413-8c4fb100-9bf0-11e9-8918-a64ffc8498d6.png)

Getting this is reasonably easy by adding the label column as a second layer.  But there are some issues to raise, in making it a bit easier.

1. The label layer has the same x and y as the data.  Then, the label is also (just about) the data.  But the default gives many decimal places.  So I used round(column).  I could easily produce a new variable (using the calculator), with the round function.  An alternative would be to allow me to type the round function into that field?  
2. I also used th4 nudge y and made it 3 for the above plot.  That's fine from the layer options.
3. Could we consider having the labels as an option on the main dialogue?  There is plenty of space.  It would be an Add Label checkbox.  If checked then there may be more options, but the obvious would be 
a) The Label - as we assume the same x and y.  Perhaps here is where we could allow typing (maybe as a further option, or by default?  (So could type round.  Or here we could have the round as a further option.  It would only apply to numeric columns.  Then it could add the round function - default is zero, but could include an up-down for decimals - say up to 5. .  
b) Then the nudge x and y I guess
c) Possibly the option to have geom_label or geom_text.  

If this was in place for one example dialogue it would not be so bad that others had to use the (usual) sub-dialogue.

I suggest this is useful and perhaps quite an easy addition to make for AMI?.

**Comment by dannyparsons** [comment]
If we have this for the Use Summaries dialog, shouldn't we also have this for the normal bar chart dialog?

**Comment by dannyparsons** [comment]
Do we actually need anything other than the counts for the label? If so, then we don't need a receiver and its much easier. It's going to be complicated implementing rounding etc. correctly for only numeric labels.

**Comment by rdstern** [comment]
I am adding to this subject a bit now.  There are 2 topics here.  One is adding labels to the bar charts and the other is whether the labels are just for counts or can be for anything.  That's because the formatting is more complicated for the anythings and is always simple for the counts.

The standard bar chart automatically is for a count.  Then  all you give is the x variable and the count automatically becomes the y variable.  That's all very simple.

But bars can be for anything.  That's why the bar chart also allows the stat to be "identity".  But then you have to give the y variable too.  

Here is an example I was asked for last week.  Namely could we have vertical bars (or lines if they are thin)  Here is an example:
![image](https://user-images.githubusercontent.com/11226469/62450039-71c6a580-b763-11e9-9a0e-de17f1ca90a7.png)

I was able to do this from the ordinary **Describe > Specific > Bar Chart** dialogue, through using the Bar Chart options, then simply adding the sum_rain as the Y variable.  Making the stat "identity" and making the width 0.1 (instead of the default of 0.9).
Note also that the x-variable is numeric, and not a factor, and that's good for the labeling of the axis at every 10 years, rather than only every year.  

This is useful!  In the ggplot "system" they have geom_col, which is the same as geom_bar, but with the stat="identity" as the default.  Hence I suggest we have a 3rd button at the top of the dialogue, called Column Chart.  I make this into a separate issue.

**Comment by rdstern** [comment]
@shadrackkibet with the current pull request I suggest it is time to retreat a bit.  I tried again with the survey dataset.  I made a summary of the counts and mean yields by village and variety.  The Add labels is just on the Describe > General > Use Summaries dialogue.
My first example looks like this:
![image](https://user-images.githubusercontent.com/11226469/96679677-0539c580-136c-11eb-8995-ddf2e624414b.png)

There is quite a lot that can be improved on this dialogue and the graph, in addition to the labels.  For example, unlike the ordinary Describe > Specific > Bar Chart, there is no Position control, so this becomes the obvious graph.  Maybe the default should be dodge?
When I make it dodge I get:
![image](https://user-images.githubusercontent.com/11226469/96680023-a163cc80-136c-11eb-8ae7-25ab6177e244.png)

There is enough wrong with this that I suggest sorting out the labels is just one aspect of improving our bar chart graphs dialogues.  
I feel that bar charts should be taken more seriously, partly because they are often used for climatic data - usually when summarised by year.  But this need not be you.  Hence I suggest for now we withdraw this pull request.

Perhaps @dannyparsons or @lilyclements may like to comment?

**Comment by shadrackkibet** [comment]
@rdstern looking into your examples above, my understanding is that the problem with the labels is with positioning. I tried positioning the labels to get graphs below. 
![image](https://user-images.githubusercontent.com/26301973/96994029-c3a84680-1534-11eb-93da-407143d2f536.png)
![image](https://user-images.githubusercontent.com/26301973/96994587-99a35400-1535-11eb-9063-c32c4137553b.png)
![image](https://user-images.githubusercontent.com/26301973/96990870-598da280-1530-11eb-9f20-886abeec02ec.png)

**Comment by rdstern** [comment]
@shadrackkibet that's great and exactly what I would like.  How does that work with the dialogue?

**Comment by shadrackkibet** [comment]
> @shadrackkibet that's great and exactly what I would like. How does that work with the dialogue?

Check that on my PR. Thanks
