### ISSUE TITLE
Reading Excel files when sheet names include spaces

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5407]
**Describe the bug**
When reading Excel files - I tried with xls, but I think the same would apply to xlxs files, the sheet name can have spaces.  The example I had was where the sheet was called Zomba Agric.

Elsewhere in the reading of illegal names we change them.  I assume we are not yet doing that here.
It gave an error message saying "illegal symbol".

I assume anyway that this is the error.  In my example I changed the sheet name to Zomba_Agric and it read fine.
.

**Comment by rdstern** [comment]
Now I have tried the data file again and can't reproduce the problem!  It does seem to cope with spaces in the sheet names as I found with data from Mozambique.
I do have an Excel file that crashes R-Instat however.  It is a horrific structure.  I attach the file to show the problem.  It is the November sheet (the last one, called Novembro 2016).  It has a horrific number of columns - I can't find how to count how many and didn't know Excel could have so many!
That's an option, because I am not sure we even need to cater for this.  But my recent reading of Excel files has provided ideas for (small?) changes, see below:  

[2015 e 2016Edited.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/3464908/2015.e.2016Edited.xlsx)

1) When reading Excel sheets the first one is ticked by default.  Could there be none ticked by default.  
2) There are occasions when I would like multiple strings (or numbers) to be changed to missing.  The example I had recently was when "-" and "--" and "----" were all possible missing value codes.
I was able to do this from the script, by choosing one of the above and then changing to c("-","--","----") in the script.  I assume I could have c("-","--","----",-9999, -99) if it were a mixture.
Could we have a combo box instead of the text field.  It is the same as now when there is a single value, but the pull-down would give some examples.  Then the code adds the c(   ) round it? When there are multiple, i.e. there is a comma, then the user must type the quotes.  They remain optional for a single string.

**Comment by rdstern** [comment]
I wrote to Danny as follows:
"Next question.  I looked through the dlgImportDataset code to see if I could find where you correct an illegal filename in importing to R.  I was hoping it might be easy to extend that to correct an illegal sheet name in Excel - that is giving us a bit of trouble - quite regularly as they can contain a space.  Perhaps correcting a space alone would be useful, but better to be more comprehensive."

He replied: "That should be reasonably easy, I think it's just not being triggered for sheet names."

@maxwellfundi is that something you can do easily or sort out with @Ivanluv or do we need more information or ask Danny to fix?

**Comment by Ivanluv** [comment]
@rdstern am trying this out with an Excel file that has a sheet containing space and its working fine.I however can't seem to find where the sheet names are corrected

**Comment by rdstern** [comment]
@Patowhiz do you have examples where this went wrong?  I tried after @Ivanluv comment above with a space in the sheet name, both in xlxs and xls files.  Like Ivan it doesn't go wrong for me now!

**Comment by Patowhiz** [comment]
There is a number of edits that I'm doing on @Ivanluv PR branch. I'll push the edits and make comments from there

**Comment by dannyparsons** [comment]
@Patowhiz where did you get on this? I also can't reproduce this error now. Are there any changes to be merged for this next version?

**Comment by Patowhiz** [comment]
This has been fixed because of the changes pushed by @Ivanluv .

Inside the ucrSave, the is a subroutine that changes any name passed to it to a valid R name. This name was being overridden incorrectly in the `dlgImportDataset  `dialog. 

```
Private Sub txtInput_Validating(sender As Object, e As CancelEventArgs) Handles txtInput.Validating
        Dim strCurrent As String

        strCurrent = txtInput.Text
        If bAutoChangeOnLeave Then
            If Not IsValid(strCurrent) Then
                'TODO This message should contain the same message from ValidateText()
                'Temp disabled so that change is done automatically
                'TODO Think about more subtle ways to do this without being annoying to the user
                'Select Case MsgBox(Chr(34) & strCurrent & Chr(34) & " is an invalid name." & Environment.NewLine & "Would you like it to be automatically corrected?", vbYesNo, "Invalid Name")
                '    Case MsgBoxResult.Yes
                '        SetName(frmMain.clsRLink.MakeValidText(strCurrent))
                '    Case Else
                '        e.Cancel = True
                'End Select
                SetName(frmMain.clsRLink.MakeValidText(strCurrent))
            End If
        Else
            e.Cancel = Not ValidateText(strCurrent)
        End If
        If Not e.Cancel Then OnNameChanged()
    End Sub
```

@rdstern the sheet names are being passed to the ucrSave and corresponding RFunction in this block in `dlgImportDataset `line 892. Which I must say has lot's of redundancies but still work nevertheless

```
Private Sub clbSheets_ItemCheck(sender As Object, e As ItemCheckEventArgs) Handles clbSheets.ItemCheck
        Dim strSheetNumbers As String

        If Not bSupressSheetChange Then
            dctSelectedExcelSheets.Clear()
            If strFileType = "XLS" OrElse strFileType = "XLSX" Then
                For Each i As Integer In clbSheets.CheckedIndices
                    dctSelectedExcelSheets.Add(i + 1, clbSheets.Items.Item(i).ToString())
                Next
                If e.NewValue = CheckState.Checked Then
                    dctSelectedExcelSheets.Add(e.Index + 1, clbSheets.Items.Item(e.Index).ToString())
                Else
                    dctSelectedExcelSheets.Remove(e.Index + 1)
                End If
                If dctSelectedExcelSheets.Count = 0 Then
                    clsImportExcel.RemoveParameterByName("which")
                    clsImportExcelMulti.RemoveParameterByName("which")
                    ucrBase.clsRsyntax.SetBaseRFunction(clsImportExcel)
                    ucrSaveFile.Show()
                    ucrSaveFile.SetDataFrameNames("")
                ElseIf dctSelectedExcelSheets.Count = 1 Then
                    strSheetNumbers = dctSelectedExcelSheets.Keys.First()
                    clsImportExcel.AddParameter("which", strSheetNumbers)
                    ucrSaveFile.SetName(dctSelectedExcelSheets.Values.First(), bSilent:=True)
                    ucrSaveFile.Focus()
                    ucrBase.clsRsyntax.SetBaseRFunction(clsImportExcel)
                    ucrSaveFile.Show()
                    ucrSaveFile.SetDataFrameNames("")
                Else
                    strSheetNumbers = "c(" & String.Join(",", dctSelectedExcelSheets.Keys) & ")"
                    clsImportExcelMulti.AddParameter("which", strSheetNumbers)
                    ucrSaveFile.SetName(frmMain.clsRLink.MakeValidText(strFileName), bSilent:=True)
                    ucrBase.clsRsyntax.SetBaseRFunction(clsImportExcelMulti)
                    ucrSaveFile.Hide()
                    ucrSaveFile.SetDataFrameNames(lstTempDataFrameNames:=dctSelectedExcelSheets.Values.ToList())
                End If
                bSupressCheckAllSheets = True
                If dctSelectedExcelSheets.Count = clbSheets.Items.Count Then
                    ucrChkSheetsCheckAll.Checked = True
                Else
                    ucrChkSheetsCheckAll.Checked = False
                End If
                bSupressCheckAllSheets = False
                ucrSaveFile.SetAssignToBooleans(bTempDataFrameList:=(dctSelectedExcelSheets.Count > 1))
                RefreshFrameView()
                TestOkEnabled()
            End If
        End If
    End Sub
```

**Comment by Patowhiz** [comment]
Since the only issue remaining here is related to multiple files, I suggest this to be closed. I've counter checked that this issue is solved for now.

**Comment by Patowhiz** [comment]
@rdstern based on my comments above I suggest that this issue be closed.

**Comment by rdstern** [comment]
ok - closing!
