### ISSUE TITLE
Small bug in bar chart

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5409]
This should be a simple one to fix!
In the bar chart one argument is called position.
The default is **stack** and that is fine and works.  The next option is what could be labelled **stack (reverse).**  Currently it is labelled position = position_stack(reverse =TRUE), which looks very odd and out of place there!  That's essentially the code, not the label.

But the bug is more what is what it produces in code, which is **position = position = position_stack(reverse=TRUE)**, i.e. the **position =** is repeated twice.

**Comment by Ivanluv** [comment]
am doing this now

**Comment by Ogik99** [comment]
# 5329

**Comment by Ogik99** [comment]
#5329
