### ISSUE TITLE
Multiple plots strikes again!

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5420]
In the TMA workshop the (known) plotting bugs all were evident on the same day - even the same task.
The one I hope is simple to solve is that when the multiple plots button is used, then when the dialogue is opened again the multiple feature is still there, but it says Single Variable.  I assume this is on all those dialogues.
Try, for example Describe > Specific > Histogram.  Change the Single Variable Button to Multiple and include 2 variables.  Close the dialogue.  Open it again.  Now the Multiple control is still open (correctly) but it says Single Variable - and that's not true and was very confusing today!

Of course if there is also a chance of doing something about the 2 larger problems I would be even happier!  

a) Because of issues when the multiple variables were used, I instead added a second layer in the conventional way.  Then I couldn't edit it, because it mistakenly thought it was produced on the main dialogue.  That has been there for ever!  
b) The multiple is also problematical - at least when facets have been set.

**Comment by Ivanluv** [comment]
The first issue on changing from multiple and single receiver has been fixed

**Comment by rdstern** [comment]
This now needs further investigation to proceed.  So I am closing it, given the obvious bug has been fixed.
