### ISSUE TITLE
Problems with the fit 3-variable model

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5421]
In the **Model > 3 variable > Fit model** it does not cope with missing values in the data.

The **Model > 2 Variable > Fit Model** and the **Model > General > Fit Model** do cope nicely.

@stevenndungu  worked on them and they seem to be working well.  The 3 variable must have been omitted.  This is both for the fitting itself and then for saving the fitted values and residuals etc.

The example I used is the Dodoma data.  From the data, use Climatic > Prepare > Climatic Summaries with the Within Year option, usinf the month_abbr.  Then summarise Tmin, getting the monthly mean.

This is now to be fitted using the **s_year** and the **month_abbr** variables. There are missing values at the top of the monthly summary columns.

There is a second problem that is more general.  In the 2-variable case the residual plots option is disabled.  And it is not ticked.
In the 3 variable and the general case it is also disabled, but ticked.  However there is no plot - at least initially.  When you use the dialogue a few times (3 variable and possibly general, then it appears.  As it is disabled it now appears all the time.

I would like the options to be possible, i.e. individual plots, etc.  I believe @stevenndungu had a problem there, which is why they were disabled.  I copy him in, in case he can advise - even though he has now left.

**Comment by dannyparsons** [comment]
@maxwellfundi can you suggest someone to take this? It should be simple by following what was done for the 2 variable dialog.

**Comment by rdstern** [comment]
I think now @dannyparsons and @volloholic and others have been looking at this issue, which is more general than the 3-variable modelling.

I am probably repeating what you have discovered, but my look is as follows.  The complications are all to do with coping with missing values in the data.  (Later it would be good to also address filters and @volloholic seems to think this is possible now?
a) At least for the 2-variable modelling we now use the option na.action = na.exclude.  This seems to be ok for saving residuals, fitted values, etc, but I am not sure about the plotting.
b) I tried the new ggresidpanel package (in the script window).  It was mentioned in a recent stack-overflow message.  It doesn't mention missing values.  It gives very nice graphs, but not with na.exclude.  When I change to na.action=na.omit the ggresidpanel graphs work fine, but the saving of the residuals, etc don't work.
c) I think we still are using fortify and autoplot?  In the ggplot guide it says that fortify is no longer proposed and to use the broom package instead.  That is suggested as a tool to "tidy" model data - which is just what we want.  

That's as far as I am so far.

**Comment by dannyparsons** [comment]
With @shadrackkibet we discussed a solution which is to use the base plots instead of autoplot. This solves all the issue. I think this was detailed in another issue but I can't seem to find it.

**Comment by rdstern** [comment]
That would be great.

**Comment by shadrackkibet** [comment]
Plotting and saving residuals is now working in most modelling dialogues, and it copes well with missing values. It is only one dialog that I found not working (**Model>Model.**..) which I am going to fix.

**Comment by shadrackkibet** [comment]
@rdstern there is a package called `lindia` that plot all diagnostic plots given a fitted linear model **object**. The function is `gg_diagnose`. This is nice because it produces `ggplot` kind of graphs,  this might be a solution to the problems we had with saving diagnostics plots.  Currently, we are using the base plot function. What do you think?

**Comment by shadrackkibet** [comment]
`performance::check_model()` is another option we could use.
