### ISSUE TITLE
Finding points in a polygon?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5422]
From where we are now, this would be very useful, but I don't know how to do this. 

Here is my problem.  In each country with climatic data we are being given the station data to draw on a map.  The station file needs checking - in each case.  Often, for example in Tanzania, the station file does not include the region, or the district variables.  It would be helpful if it did, both to support checking and also for the plotting.  I have the polygons from the gadm file and also the locations (lat and long from the station file.  

So I would like to do a sort of merge.  I think the answer is [here](https://gis.stackexchange.com/questions/282750/identify-polygon-containing-point-with-r-sf-package/318629#318629)?

If so, then it may be quite easy?  It would certainly be useful and appreciated!  Not just by me!

If it is really easy then I wonder where it should go in the menu system?  It is essentially a merge, but a pretty special one.  Perhaps it should go under the mapping, which would now have a map sub-dialogue and an Add Variables dialogue.

**Comment by dannyparsons** [comment]
The solution in the link looks good for doing this.

**Comment by Ivanluv** [comment]
Any more ideas on how this dialogue should look like?Also what should be the appropriate name of the dialogue?
![image](https://user-images.githubusercontent.com/45068931/63252453-7d908c80-c278-11e9-8eae-25862aa35066.png)

**Comment by rdstern** [comment]
This looks very nice - and simple.  I think the Title could be **_Locating Points from Maps_**.  Each time it will be a single map, but it will often be used by a succession of maps in turn.
Then, in the Shape File group box there is also a single receiver with the label **_Name_**, which is the variable in the shape file that will be reported in the receiving variable.

So I think there could be a slightly different structure.  There is a group box round the Longitude and Latitude with the name Station File.  
Then the single receiver that you have for the Shape File, becomes and ordinary receiver and is labelled Polygon.  That is filled automatically when you have a shape file.  (That is also being done on the improved map dialogue.) 
Then, in the Shape File group box there is also a single receiver with the label **_Name_**, which is the variable in the shape file that will be reported in the receiving variable.  
Then there is just a single column produced.  So Prefix for New Columns: becomes just New Column: and could be Location1, etc.

(Using 2 data frames from the single selector will be the same idea as is done in the Climatic > PICSA > Crops dialogue.  There the first 4 variables are from the file with daily data and the next 2 variables in the season dates group-box needs them from the yearly data frame. )

So how I see this working would be as follows, taking the Kenya data as an example.
If you take the gadm shape file at Level 1, then there is a variable (always) with the polygons.  It also has another variable with the county name.  That's the Name column you give.  
Then the New variable is simply the County name derived from the stated lat and long.  If the Station file also has the County, then these should be the same.  

This could initially be done at Level 0.  Then there is just one row in the gadm file with Kenya in the name column.  The result will then be the added variable at the station level, which will be Kenya or NA if any stations have (mistakenly) given coordinates outside the country.

And Level 2 would allow a check on the ward.

**Comment by Ivanluv** [comment]
Does this look okay?
![image](https://user-images.githubusercontent.com/45068931/63327278-8cd60f80-c336-11e9-8583-ca0485d152c3.png)

**Comment by rdstern** [comment]
Looks very good.  Just delete the s from Columns.

**Comment by Ivanluv** [comment]
Great.Doing that now

**Comment by rdstern** [comment]
@Ivanluv I wonder where the dialogue should go in the climatic menu.  Earlier I was thinking it could be added as Climatic > Mapping > Check Stations, with the current mapping therefore becoming Climatic > Mapping > Map.

Now I wonder if it would go better under Climatic > Check Data.  There could be a line at the bottom or the current options, i.e. under QC Rainfall and the Check Stations or Check Locations.  This repeats the word "Check" but I think that's OK.  Alternatively Station Locations.

**Comment by Ivanluv** [comment]
@rdstern  I think  putting it under Climatic > Check Data would be fine

**Comment by rdstern** [comment]
@Ivanluv  Sounds good.  I agree.

**Comment by dannyparsons** [comment]
How about **Locating Points in Shape File** as the title?

I can see the logic for Climatic > Check Data but I feel its going to be a bit hidden there. Whereas  Climatic > Mapping would be an obvious place to look for this kind of thing.

**Comment by rdstern** [comment]
Happy with that.  I think there will be more dialogues there, so having the Map one level down would also be good.

**Comment by rdstern** [comment]
Is anything happening on this?

**Comment by Ivanluv** [comment]
we are still looking at this

**Comment by rdstern** [comment]
@Ivanluv I wonder of the state of this dialogue?  If it is now quick for you to complete, then that would be great.  It seems, from above, that its position on the menu is now settled.  Otherwise, if there is still quite a bit to do, then it could be a good topic to hand to Antoine?

**Comment by Ivanluv** [comment]
@rdstern I would prefer Antoine to look at it

**Comment by rdstern** [comment]
@HawardKetoyoMsatsi this has quite a long history!  It would be good if you could locate it, and start looking at this issue today.  That would set you up to possibly get support from @shadrackkibet from tomorrow if you need help.

I would put this as higher priority today, even than completing the circular dialogues, where I have just been looking at #6126.  That's an example that is nearly finished, but it may also benefit from you working a bit with @shadrackkibet from tomorrow to complete it.

**Comment by shadrackkibet** [comment]
I can see we can do this using `sf::st_intersects`. @rdstern can you share the station file and shapefile you used from Dodoma? From a quick look, I think we will need two selectors.

**Comment by rdstern** [comment]
Hi @shadrackkibet and @HawardKetoyoMsatsi 

Great that you are working on this.  I suggest we use the data from Kenya to test the system.  These data are well known by the video team and this could involve them in improving that station data.  But the existing file is good for a start.

For the shape files can you try downloading yourselves - partly because it isn't clear what we can include in the library.  [Here is the link](https://gadm.org/download_country_v3.html) to the data I downloaded.  There are different levels and you may wish to download them all, so you can check on Kenya, Counties and sub-counties

Looking forward to this!
