### ISSUE TITLE
Small addition to the Make Date dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5429]
In the Make Date dialogue one option with a single column is for you to specify the origin.  Could we add the R default.  It could simply be given as R. The code should be simple, because it could be adapted from Excel - the origin is 1/1/1970.

**Comment by dannyparsons** [comment]
While looking at this, could the special origins have the date written next to them, so instead of "Excel" it says "Excel (1899/12/30)"? And the same for others? That would mean you don't have to check what each of them mean separately. Then the same for the new R date.
