### ISSUE TITLE
Possible nasty bug after the  Delete sheets dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5440]
I eventually got the following:
![image](https://user-images.githubusercontent.com/11226469/61887538-bf3c4a80-aef9-11e9-8e7d-aaa0908323b3.png)

This was a severe test of R-Instat.  Until this appeared it was holding up well.  I think the problem is with the delete of the sheets, but describe the process I went through.  It was also deliberately quite a test of R-Instat.
[PLUVIOMETRIC_monthly_data_for_dB_02.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/3432274/PLUVIOMETRIC_monthly_data_for_dB_02.xlsx)

Here is the process with the attached file.
a) **Import into R-Instat.**  It is Excel and I imported all 86 (or so) sheets.
b) **Omitted first 2 sheets** and then **Appended the rest**.  Got sheet called Append1 with just under 500,000 rows.
c) **Deleted all the original sheets**, leaving the first 2 and the last one.

After the deletion it initially seemed to have just the Append1 sheet.  I checked the command and it seems ok in what it deleted.  
As shown above, the sheets metadata indicated that there were still 3 sheets.  But the column metadata and the data seemed to indicate just the appended data - until the dreaded picture appeared.

I'll try to repeat.  I did not have the sheets in order when I deleted.

**Comment by rdstern** [comment]
I have discovered a bit more.
I went through the 3 steps again, but carefully deleted the individual sheets in order.  Here was the command, which seems to be ok.  (I put in bold the difference to the one that gives the problem.)
# Code generated by the dialog, Delete Data Frames
data_book$delete_dataframes(data_names=**c("P.17","P.18"**,"P.19","P.20","P.21","P.22","P.23","P.48","P.67","P.113","P.140","P.250","P.260","P.261","P.262","P.265","P.267","P.306","P.309","P.388","P.389","P.390","P.391","P.393","P.410","P.533","P.544","P.546","P.560","P.564","P.592","P.604","P.626","P.627","P.756","P.758","P.772","P.776","P.780","P.796","P.802","P.804","P.809","P.849","P.864","P.931","P.944","P.975","P.1013","P.1014","P.1015","P.1016","P.1017","P.1019","P.1020","P.1021","P.1022","P.1028","P.1053","P.1057","P.1061","P.1062","P.1097","P.1119","P.1159","P.1160","P.1175","P.1180","P.1202","P.1203","P.1221","P.1229","P.1230","P.1231","P.1232","P.1233","P.1234","P.1235","P.1236","P.1237","P.1244","P.1259","P.1281","P.1317"))

I then saved the resulting rds file and started again.
I did the same thing except I started the Delete dialogue by right-clicking on the last sheet to delete, rather than the first.
Then, in the dialogue, I had the other sheets in order.  The command is therefore now:
data_book$delete_dataframes(data_names=**c("P.1317"**,"P.17","P.18","P.19","P.20","P.21","P.22","P.23","P.48","P.67","P.113","P.140","P.250","P.260","P.261","P.262","P.265","P.267","P.306","P.309","P.388","P.389","P.390","P.391","P.393","P.410","P.533","P.544","P.546","P.560","P.564","P.592","P.604","P.626","P.627","P.756","P.758","P.772","P.776","P.780","P.796","P.802","P.804","P.809","P.849","P.864","P.931","P.944","P.975","P.1013","P.1014","P.1015","P.1016","P.1017","P.1019","P.1020","P.1021","P.1022","P.1028","P.1053","P.1057","P.1061","P.1062","P.1097","P.1119","P.1159","P.1160","P.1175","P.1180","P.1202","P.1203","P.1221","P.1229","P.1230","P.1231","P.1232","P.1233","P.1234","P.1235","P.1236","P.1237","P.1244","P.1259","P.1281"))

So, the order of the data frames to delete does seem to be causing the issue.

**Comment by rdstern** [comment]
Just to report that I have since managed to sort out these data and got an inventory graph.  This was before deleting any data frames.  I then went from the last data frame to the first, by right-clicking at the bottom left (where it lists all the data frames) and got the dreaded cross - see above - again.

I clicked to continue, then did delete the data frames, then checked from the bottom tabs that the data are there and ok in R itself.  Then I used File > Save As.  Closed down R-Instat and restarted.  All seems ok now.  It appears to have been working ok, just not showing the data in the grid.

**Comment by dannyparsons** [comment]
@lloyddewit This may be related to #5613. Even if not related, it might be good to look at these two issues together.

**Comment by lloyddewit** [comment]
@rdstern @dannyparsons thanks for the information.

I think we first need to clarify if this is an issue with:
1. The underlying data
2. How the data is displayed

If it is 2 then (as Danny said) this could be related to #5613. 

`clsGridLink.UpdateGrids()` displays the data depending on the values of a number of boolean variables. These variables describe if data exists or has been changed. There is a potential maintainability issue with these variables. If they are not updated correctly when the data is changed then this could lead to unpredictable behaviour in `UpdateGrids`. It would be safer (if practical) to check the data directly with an R call.

I only have the standard files that were installed when I downloaded R-Instat. Is there a way for me to recreate this issue using these files? Or is there another way I can recreate this issue?

Also, I made a pull request for #5613. If this is accepted then please could you test this issue again (it could potentially affect the behaviour)?

**Comment by dannyparsons** [comment]
Here is the data Roger attached above https://github.com/africanmathsinitiative/R-Instat/files/3432274/PLUVIOMETRIC_monthly_data_for_dB_02.xlsx.
@rdstern could you confirm if this bug still exists in the same way now that https://github.com/africanmathsinitiative/R-Instat/issues/5613 is resolved.

**Comment by rdstern** [comment]
@lloyddewit and @dannyparsons I think it is fixed.
There may be a slight oddity in the grid displaying the different data frames, but the deleting seems to work very well now.  And this was a severe test with over 80 data frames.
I also checked repeatedly deleting all the data frames and that is now working fine.

As a report, but no action needed.  The very slight oddity was that when I appended all the data frames and then deleted the individual stations the focus is on the 3rd data frame, with all the appended values.  Then the back arrow on the grid doesn't seem to allow me to return to the 2 first data frames.  But what you right click there all 3 are around and you can choose one.  So delete has worked perfectly. 

So I am closing this issue.

**Comment by lloyddewit** [comment]
@rdstern @dannyparsons I'm happy it appears to be fixed. I'm slightly uncomfortable that I don't fully understand how/why #5613 appears to have fixed it, and how robust this fix is.
