### ISSUE TITLE
Infill missing dates - name change?

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5444]
There is often confusion about "Infill missing dates" because "infilling missing" is also associated with processes that replace missing values in data with estimated values. Whereas in this context by "missing dates" we means rows which are missing not missing values.

Proposed name changes are:
- Insert missing dates
- Insert rows for missing dates
- Fill date gaps
- Pad missing dates

I don't think any of these fully solve the confusion but are improvements. 
Thoughts on these or any other suggestions?

**Comment by rdstern** [comment]
I checked also with Carlos - we both go for **Fill Date Gaps** from the list above.

Or perhaps "Complete dates"., but I think Fill Date Gaps is clear.

**Comment by dannyparsons** [comment]
In `tidyr` language it is called "complete" but I think Fill is more immediately understandable.

I can't think of anything better than **Fill Date Gaps** so we could go for this unless other suggestions?

**Comment by volloholic** [comment]
Happy with 
Fill date gap
or maybe 
Complete date series 
Complete date sequence
Complete date column

**Comment by dannyparsons** [comment]
I quite like **Complete date series** but maybe its too technical compared to **Fill date gaps**.

How well do either of these translate into French (or Spanish)?

**Comment by rdstern** [comment]
Into Spanish Fill Date Gaps is slightly easier.  David, what is the French?

Remplir les lacunes de date? For Fill Date Gaps?

**Comment by dannyparsons** [comment]
Let's go with **Fill date gaps** then.
