### ISSUE TITLE
Crops and multiple stations

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5463]
Currently the crops dialogue doesn't seem to cope with multiple stations.  It works fine with multiple stations, but then the final probabilities add over all the stations.
Could they please add another dimension to the tables so the results are given station-by-station.

The dialogue currently produces 2 data frames called drop_def and crop_prop.  The detailed crop_def is fine.  It has the station information individually.  Then crop_prop (and the output window) summarise the data over years.  They should summarise over both stations and years.

I hope this might be quite a simple extension.

**Comment by dannyparsons** [comment]
Yes I think the raw calculations are being done by station so its just to include station in the subsequent summaries which is not a big task.

**Comment by dannyparsons** [comment]
I am assuming you mean that `crop_prob` should be summarised over years, but split by station. i.e. if 2 stations and 6 crop definitions then 12 probability values (instead of 6). If so, this is now done.

**Comment by rdstern** [comment]
Great.  Exactly.
