### ISSUE TITLE
Adding a column chart button to the bar chart dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5464]
I suggest this could be quite an easy addition.

The current Describe > Specific > Bar Chart dialogue has 2 buttons at the top.  I suggest a third button Column Chart after the Pie Chart.

This is the same as the Bar Chart, but with the stat="identity" as automatic.  It is alternatively geom_col which we have already.  So it can call geom_col.  
a) This is just the same as geom_bar, but with the stat="identity".  So in the properties of the geom I suggest we swap the order.  Currently the order is count, followed by identity - which is correct for geom bar.  I suggest it should be the other way round for geom_col.
b) On the main dialogue There should now be a new receiver.  I assume this should be the usual Y variable - which can therefore be Single/Multiple as for other graphics dialogues.  The existing single receiver is now the X-Variable.
c) Currently this x-variable can take numeric (as well as factors), though it is usually a factor.  Please keep this flexibility, i.e. don't restrict it to a factor.
d) While there, the pie chart option is restricted to a factor column.  Allow this to be (as for the ordinary bar chart) into numeric as well.
e) I suggest the third option could usefully also have the width of the bars on the main dialogue.  We will often want that to be much less than the default of 0.9.    If necessary that can come later.  

The issues of labeling are the same as in #5398 , except that labeling of an ordinary bar chart is just a count, while labeling here needs formatting decisions.  That can come later.

Here is an example of this third option:
![image](https://user-images.githubusercontent.com/11226469/62453528-69259d80-b76a-11e9-82ea-8088c113c247.png)

**Comment by rdstern** [comment]
@Ogik99 I like this addition very much.
a) It gives a developer error when you go into the dialogue.  
![image](https://user-images.githubusercontent.com/11226469/63683627-c73a2380-c7f2-11e9-9635-c8e1d057556a.png)
Then it goes in ok.
b) It seems to reset to the bar chart each time you return to the dialogue.  .
c) It is an alternative to the line chart, etc.  So could you swap the controls for the Y variable and the x-variable.  We usually give the y-variable first.  (There isn't one in the ordinary bar chart, because it is doing a count.
d) The coord-flip option from the bar chart is useful to have on the main dialogue.  We will probably want to add more items there later, but that will do for now.  (Another obvious one would be Bar width, because I often do 0.1 for these rather than the default of 0.9.)  Here is an example:
![image](https://user-images.githubusercontent.com/11226469/63684321-88a56880-c7f4-11e9-96d8-7ba3532a993a.png)

**Comment by rdstern** [comment]
And I am not sure the added factor is sensible as often as for an ordinary bar chart.  But it does no harm.  Here is an example:
![image](https://user-images.githubusercontent.com/11226469/63685782-2484a380-c7f8-11e9-80fa-3c611a3b24dc.png)

So worth including the By Variable (Optional) control and the Position control as in the bar chart.
And in the bar chart it could be called By Variable and not Y variable. (See the Scatterplot for an example)   And when you switch to pie charts - where the option is absent (correctly) the label should also be hidden.

**Comment by dannyparsons** [comment]
So will we then get rid of the "Use Summaries" dialog that currently does bar charts from already summarised data? I guess it won't be needed once we have this.

**Comment by rdstern** [comment]
I am still assuming we may want to have some nicely formatted tables from summary data as the third option.  And I like the concept, so suggest we keep it - at least for now.

**Comment by maxwellfundi** [comment]
@rdstern i think the reason why we had the X variable tarting is because its the only receiver needing to be filled. it would be confusing to have the first receiver not mandatory.

**Comment by Ogik99** [comment]
I managed to have the flip coordinates check box appear in the column chart and the "factor" option (which holds the fill parameter) as well. 
@rdstern , @maxwellfundi could you kindly review this.

**Comment by rdstern** [comment]
I am re-opening this issue - I hope briefly - because the problem of labelling in the column chart is still there.  
![image](https://user-images.githubusercontent.com/11226469/69897203-19359c80-1340-11ea-9983-3732ee9e74fb.png)

This is what it should look like.  And it does - **_but just the first time you use the dialogue_**!  If you complete the dialogue, then get a graph and then return to the dialogue, the labels for the Y and X have changed.  @Ogik99 please check with @volloholic next week as he says this is easy to fix and should also help to simplify things for you in the future.

**Comment by Ogik99** [comment]
![barchart](https://user-images.githubusercontent.com/43957868/70120150-e6134600-167c-11ea-8917-4710b3b56ff9.PNG)

Following discussions made yesterday, this is the suggested design of the dialogue. We got rid of the column chart button and introduced new controls- Y values and Y variable. The Y values control would have two options - "Count" and "Column". If the "Count" option is selected, the user gets a normal bar chart. If the "Column" option is selected, the Y variable receiver appears and a column chart get produced.

**Comment by rdstern** [comment]
@Ogik99, so if I understand correctly, then could the first field be labelled **_X Variable_**.  That would be clear and consistent with the scatterplot, etc.
I like the idea of this change.

**Comment by Patowhiz** [comment]
@Ogik99 is this now ready for review? I would like to go through it and check on the redundancies that we talked about.

**Comment by Ogik99** [comment]
Yes it is ready for review @Patowhiz
