### ISSUE TITLE
Improve one-variable summarise dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5466]
This is a useful dialogue.  I use it a lot, but only in the "default" way where it uses the standard base-R command of **summary**.  Once improved it could also be very useful in teaching.

You can tick the options button to use our own summary statistics.  It would be very useful if this worked well and I make suggestions for discussion on this.  This would also help the production of summary statistics generally in R-Instat, because the sub-dialogue is used by many dialogues.

As a data set for testing I propose the Ghana climatic with a few improvements from the version currently in the library.  Once those are made, then perhaps the "improved" version could be added to the library - as well, rather than instead of the existing set.

So, for the data, open the existing Open From Library > Instat > Browse > Climatic > Ghana > Ghana-two-stations.rds file.  Then:
a) Climatic > Date > Infill Missing Dates (remember to include the station in the dialogue)
b) Climatic > Date > Use Date to add Year, Month_abbr, day_in _year(366) and day_in_month - so 4 columns.
c) Climatic > Define Climatic Data
d) Climatic > Prepare > Transform Then Count, for the column called rainfall, condition 0.85 and the column can be called rainday.

This is what you could save so these steps do not have to be done each time.
Now -  Describe > One Variable > Summarise.  First **on default settings**.  And just use the one column **rainday** for now.

a) Notice the checkbox on missing values.  It is not relevant when the default settings are used.  So it should be made invisible then.

The default summary is quite clear.  Here it is:
![image](https://user-images.githubusercontent.com/11226469/62597494-25ec3b80-b8de-11e9-8f50-9fe720eabb45.png)

Now do the same (for this variable) using the customise and then the options as shown below:
![image](https://user-images.githubusercontent.com/11226469/62597642-a0b55680-b8de-11e9-88b5-f14db5749e71.png)

There are already some nice things here.  In particular we have the n-distinct checkbox.  But notice also that I have checked all the boxes that are given by the default.

You will also have to check the now-visible Missing value checkbox on the main dialogue.  Or almost everything is NA.  It works and here are the results: 

![image](https://user-images.githubusercontent.com/11226469/62597879-5385b480-b8df-11e9-84a8-5409be7bf8ed.png)

There are 2 things to investigate and (hopefully) improve:
a) Why does it go into scientific notation?
b) Could we please have a better order of the results it produces and displays.  Notice the default display goes from smallest to largest.  Could we have all the counts first and then (at least roughly) do the same.  
(This change may also be useful in the more general use of this feature, because it is probably the order that new variables are produced and saved.)

Now a bigger problem:  I usually use this dialogue for all the variables.  So do this:
a) Back to default - i.e. no customise.
b) Right-click in selector and choose Add-all
c) Press OK.
Quite a lot of useful results.

Now press customise and OK:
You get an error, because the customised dialogue only works for numeric data.
 What should we do?  
I started by getting rid of the 2 factor columns, i.e. Station and Month.  Then you get a different error, namely that q(i) is not defined for date variables.  

So get rid of the quartiles.  Then it works for the data columns, the results are now not bad - (except for the order and the scientific notation).  But also the date column is summarised numerically - which is confusing, see below:
![image](https://user-images.githubusercontent.com/11226469/62598676-14a52e00-b8e2-11e9-88aa-37dd09bd9597.png)

And also notice that the counts are all given with decimals, which makes them unclear.  I wonder what we can do about the formatting?

There are questions here, where discussion is needed, before changes are made.  I don't mind if dates and factors are not summarised when the customised version is used.  But they may be in the receiver.  So perhaps they can just be ignored and perhaps a one-line message is given?
Then can we do something about the order and formatting?

This would be very useful.

**Comment by dannyparsons** [comment]
I am about to submit something that addresses all these points. 
The difficult one was the order of the summaries. I think the most robust and simple solution is to have a predefined order of all our summaries. I had a quick go as follows trying to go from small to large and consider groupings (on the summaries subdialog).
Please edit the list for any changes and I can update it.
It might be something where experience using the dialog will give us ideas about a sensible ordering.

```
c("count", "count_non_missing", "count_missing", 
"min", "lower_quartile", "quartile", "median", 
"median_absolute_deviation", "coef_var", "Qn", 
"Sn", "mode", "mean", "trimmed_mean", 
"upper_quartile", "max", "sum", "sd", 
"var", "range", "standard_error_mean", "skewness", 
"skewness_mc", "kurtosis", "outlier_limit", 
"cor", "cov", "first", "last", "nth", 
"n_distinct", "proportion_calc", "count_calc", 
"circular_min", "circular_Q1", "circular_quantile", 
"circular_median", "circular_medianHL", "circular_mean", 
"circular_Q3", "circular_max", "circular_sd", 
"circular_var", "circular_range", "circular_ang_dev", 
"circular_ang_var", "circular_rho")
```

**Comment by dannyparsons** [comment]
And I've modified the layout, I think this is tidier now:

![image](https://user-images.githubusercontent.com/11214914/68788855-27937100-063c-11ea-973c-5106a3b0469b.png)
