### ISSUE TITLE
Adding the gt package?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5469]
It describes itself as" Easily generate information-rich, publication-quality tables from R".  It isn't yet in CRAN but it seems already to be recommended widely - and it is from [RStudio](https://github.com/rstudio/gt)

We will need this sort of feature.  Is this what we need.  I wonder how easily it could be incorporated?

**Comment by shadrackkibet** [comment]
Good to also consider other packages like `kableExtra`  and  `knitr`
