### ISSUE TITLE
New menu item and new dialogue to define circular

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5474]
I propose a new menu item in the Prepare menu.  It is called **_Column: Define_**.   and is below Column: Date and above Column: Reshape.
It can start with just two items.  The first is a copy (at least for now) of Prepare > Data Frame > Convert Columns and is also called **_Convert Columns_**.  Then there is a line.  Under the line is Circular.
This is a new dialogue.  There is the usual data selector restricted to numeric columns.  There is a multiple receiver with the label **To Circular**.  (I can't think of many situations when you will want more than one variable.  So if it is more work, then make it a single receiver.)

There are two sets of the ordinary radio buttons.
One is called Units.  It has 3 options, namely Radians, Degrees, Hours with Radians the default.
The second is Modulo.  It has 3 options, namely Asis, pi, 2pi with 2pi the default.

There are other arguments, but they are mainly for the plotting routines in the package and w are not using those.  So stop there, at least for now.

This just issues the command circular::circular(x, modulo="2pi", units="radians")

Our default is 2pi, so we have to give that, because the package default is asis.  Our default of radians is the same as the package.

If it is a multiple receiver then the other controls remain simple, i.e. if one variable is in degrees and the other is in radians, then you use the dialogue twice.

**Comment by rdstern** [comment]
@AlexSananka  the new circular features in R-Instat are now just about working.  This new dialogue is needed to complete the features.  I wonder if this would be a good task for you to try to do, jointly with perhaps @Wycklife who has been developing the other features in relation to the R Circular package?  It involves quite a lot, but I think should be a relatively easy set of tasks.  I will check with @dannyparsons too.

**Comment by Wycklife** [comment]
I have started working on this issue.

**Comment by shadrackkibet** [comment]
Since I am going to include some components of circular statistics in my essay I am going to support Wycklife on this task.

**Comment by shadrackkibet** [comment]
@rdstern I think we need save control in this dialog. Is it necessary to save the column defined as circular as a new column or we just replace it with the original column? but sometimes the user might still need the original column to proceed with other analysis.

**Comment by rdstern** [comment]
@shadrackkibet   Essentially we are defining a new variable.  I suggest the same control as when we define a variable as a Date, for example.  The default there (and in many dialogues that define new variables) is that a name is proposed by default, but there is also a pull-down with the list of existing variables.  So it is easy to overwrite the existing variable if you wish.

**Comment by shadrackkibet** [comment]
Another point is on other options `zero`,`template` and `rotation`. I think it will be good to have these options in the dialog as well.

**Comment by shadrackkibet** [comment]
Here is the design of the dialog. 
![image](https://user-images.githubusercontent.com/26301973/64912832-7ce6fb00-d73d-11e9-910a-c6fec3cc2af7.png)

**Comment by rdstern** [comment]
I like the layout of this dialogue.  I am not sure about needing the other options - at least at this point.  It will be good to check by examining what else from the circular package we will be including in R-Instat.  I think these options all relate only to the circular graphs.  They use base graphics and I am not sure we need them.  But perhaps I am wrong, either on their uses and on omitting the graphics from the package?

**Comment by dannyparsons** [comment]
Yes I think lowercase `pi` is more standard.

I think these options are what we need now. The others relating to graphs won't be used by R-Instat.

**Comment by shadrackkibet** [comment]
@Wycklife please make this small change and also remember to sort out Tab order on the form. otherwise, this should be ready.
