### ISSUE TITLE
PICSA rainfall graphs - omit Line Options now?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5490]
The PICSA rainfall graphs are a complicated line graph with points etc.
There are 3 option buttons, namely 
Line Options - because it is a line graph
Plot options
PICSA options

We can now use the **_Plot options_** to edit the Line layer in the graph.
So I suggest we omit the LineOptions button.

I still quite like the special button, e.g. Line Options when we have a line graph.  It is just a bit simpler.
Could we therefore replace the Line Options by the PICSA options here.  That would have a sort of logic to it that is consistent with the main graphics dialogues.

**Comment by maxwellfundi** [comment]
@rdstern  Yes, we can simply remove the current **Line Options** and edit the line from the plot options.  @Wycklife please take up this. it should not take too much time.

**Comment by Ivanluv** [comment]
I cant find the Line Options button in the PICSA rainfall graph daialogue

**Comment by rdstern** [comment]
This is done, so I am closing it now.  Roger
