### ISSUE TITLE
PICSA Rainfall graphs with multi-line caption

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5491]
One of the sub-dialogues for PICSA has Title, Sub-Title and Caption.

I suggest some edits to the title tab.
a) Delete the word Graph from Graph Title etc.  It is in a Graph box, so that's clear.
b) Move the controls over a bit and add a checkbox after the font size Default unchecked "As Caption".  If checked then it changes the **_vjust_** argument appropriately, so it is at the bottom left.  I assume this will work.  
My reason for this is that I would like to recommend that PICSA graphs usually have 2 discrete captions.  On the bottom left is the definition used in the graph.  And the bottom right - usual caption is the Source: Tanzania Met Authority (TMA).
c) On my machine the up-down controls don't seem to work very well.  I can type into them, but the up-down arrows don't work much.  I haven't checked them elsewhere.

**Comment by maxwellfundi** [comment]
@rdstern So you mean after the font sizes for all of them or just the caption or just the subtitle. the default for caption goes to bottom right.  If the checkbox would be for all, it would be where I have painted?

![image](https://user-images.githubusercontent.com/9798689/64106110-34643080-cd80-11e9-849c-50e6fecd1ff8.png)

**Comment by rdstern** [comment]
I now don't think my idea will work anyway.  I have been trying to get the subtitle to be on the bottom left of the graph and can't do that.  I thought the vjust would do vertically, what hjust does horizontally.
What is possible is a multi-line caption.  They would then both be on the right.  

We would then (in the dialogue) have Caption 1 and Caption 2 in the dialogue.  Then we add /n to the code between the 2 captions.
What we might do where you have indicated above is Position: Left, Centred, Right for each of them.  This would add the hjust argument.
(We could also consider adding these arguments to the Titles tab in the ordinary plotting dialogues.

**Comment by dannyparsons** [comment]
@maxwellfundi if we had a multi line text box for the caption, would that automatically give a multi line caption on the plot?

**Comment by maxwellfundi** [comment]
@dannyparsons I don't think multiline textbox will have multiline caption. We will need to format the caption to be on two lines

**Comment by rdstern** [comment]
I wasn't even thinking of any change in the coding.  It was just 
a) for the whole text for the caption to be visible and 
b) to tempt users that there could be more text in this caption then one would want in a title or subtitle.  
c) I also don't think it is unreasonable for the user to type the **_\n_** within the text if they want the caption to have a line feed, i.e. to appear on 2 or more lines.  
d) So I am not assuming that the line feeds in the caption would necessarily match the lines in the textbox.  Perhaps I am expecting too much of a multiline textbox?

**Comment by dannyparsons** [comment]
@maxwellfundi why don't you think this will work? The easiest way to know is to try, it shouldn't take more than a few minutes to find out.

**Comment by maxwellfundi** [comment]
@dannyparsons  maybe i wasnt clear, multiline textbox would not automatically give us a multiline caption we will need to have \n after every line if we wanted that.

**Comment by rdstern** [comment]
And I think that is fine.  The multi-line is just so we see it all.  We could even have a tooltip to say put \n for a new line.

**Comment by maxwellfundi** [comment]
okay, if thats the case then am happy to have a multi line caption text box

**Comment by rdstern** [comment]
So I am now suggesting this as a small task for @Wycklife.  In the PICSA rainfall graphs, sub-dialogue for PICSA options, then  Titles tab.  Could you make the Caption text box into multiline and add a tooltip to say "Type \n where you would like a new-line".  The Graph box will have to be a bit larger, but there is plenty of space to move the other controls down a bit.
