### ISSUE TITLE
Auto Switching of Single Receivers Focus on Selector Variables Selections

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#5508]
**Is your feature request related to a problem? Please describe.**
At the moment you have to manually change the focus of the single receiver before selecting the variable you want to use.

**Describe the solution you'd like**
Changing focus of single receivers automatically on selection of variables in the selector

**Additional context**
This issue is in relation to the design changes suggested in issue #5480

**Comment by Patowhiz** [comment]
@dannyparsons I'm not sure if I'm correct about this, at the moment I can see there is only a one way link between the selector and the receiver, in which it's the receiver that knows about the selector and the selector is not aware of any receivers, right? That is, the receiver is the one listening to the selector? If so, then the auto switching of focus issue will necessitate a 2 way binding where also the selector is aware of all the receivers linked to it?

**Comment by dannyparsons** [comment]
Yes that's right, currently the Selector doesn't know about its receivers, so we need to add this as well.

I hope this can be implemented without needing a change on every dialog. Notice that `Receiver.Selector` is a property so we can modify the `Set` method to set up this linking of the receiver to its selector.
The ordering should then be determined by the tab index of the receivers, not the order they are added in, (this will also make sure tab order is set correctly on dialogs!). 
Re-ordering a list is not always very quick so the list of receivers stored in the selector should probably be ordered when the receivers are added, and not each time the focus needs to change.

Please implement this at the receiver level. We can have a switch for enabling/disabling auto switching focus for individual receivers, which can be on by default for single and off by default for multiple. This means we can easily extend it to multiple receivers if we decide to.

**Comment by Patowhiz** [comment]
Okay that was insightful.
