### ISSUE TITLE
Add tooltips to the calculator, logical keyboard

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5520]
This is quite a big job, but very useful, particularly as the help is taking too long.

I hope it is easy, and that @dannyparsons can confirm it would be useful to start on this soon.  I am not sure of the priority, and it depends on other work.

I am also not sure how it will be translated, because we are close to a new system for translations.  Good if tooltips can be considered for translation, if there are alternative ways they can be given?

**_Simple keyboard:_**
^ power or exponent and can also be given as **.  For example 2^3 = 8
Logical and Symbols
< less than.  For example (2 < 3) is TRUE.  (2 < 2) is FALSE, (2 < 1) is FALSE
<= less than or equals.  For example (2 <= 3) is TRUE,  (2 <=2)  is TRUE, (2 <= 1) is FALSE
> greater than.  For example (2 > 3) is FALSE, (2 > 2) is FALSE, (2 > 1) is TRUE
>= greater than or equals.  For example (2 >= 3) is FALSE, (2 >=2) is TRUE, (2 >= 1) is TRUE
== logical equals.  For example (2 == 3) is FALSE, (2 == 2) is TRUE, (2 == 1) is FALSE
!= not equals (opposite of ==). For example (2 ! 3) is TRUE, (2 != 2) is FALSE and (2 != 1) is TRUE
|  logical OR.  For example  (2 < 3) | (2 < 1) is the same as (TRUE | FALSE) which is TRUE
& logical AND.  For example  (2 < 3) & (2 < 1) is the same as (TRUE & FALSE) which is FALSE
! logical NOT.  For example !(2 < 3) is FALSE, !(2  < 1) is TRUE
: colon is from:to.  For example 3:6 is 3, 4, 5, 6. 6:3 is 6, 5, 4, 3 (It is the seq function with a step-length of 1 or -1.)
%%   modulus operator gives the remainder after integer division.  For example 7 %% 3 is 1, 12 %% 3 is 0
%in% is like the match function and returns a logical vector.  For example (11:15 %in% c(11,13)) gives TRUE, FALSE, TRUE, FALSE, FALSE
match (see also %in%) gives the positions of the matching elements.  For example match(11:15, c(11,13)) gives (1,NA, 2, NA, NA). match(11:15,c(11,13),nomatch=0) gives 1, 0, 2, 0, 0)
 
%/% div operator is for integer division.  For example (7 %/% 3) is 2, (13 %/% 3) is 4

**Comment by rdstern** [comment]
I am continuing.  I have started particularly with the logical keyboard, because it is so useful and I find is new to many of our users.
**_when_** is multiple ifelse, for example case_when(1:5>3~20,1:5>1~10) gives NA, 10, 10, 20, 20 
**_ifelse_** is what it says, for example ifelse((1:5 > 3,20,10) gives 10, 10, 10, 20, 20
**_between_** two values, for example between(1:5, 3,4) is FALSE, FALSE, TRUE, TRUE, FALSE
is.na detects missing values, for example is.na(c(1,3,NA, 5)) gives FALSE, FALSE, TRUE, FALSE
**_!is.na_** detects non-missing values, for example !is.na(c(1,3,NA, 5)) gives TRUE, TRUE, FALSE, TRUE
**_duplicated_** detects non-unique values, for example duplicated(c(1:3,2,7)) gives FALSE, FALSE, FALSE, TRUE, FALSE
**_near_** compares 2 variables.  For example sqrt(5)^2 is almost, but isn't exactly 5, however near(sqrt(5)^2,5) is TRUE

**Comment by Wycklife** [comment]
@rdstern I'm almost done with the logical keyboard. Do you have documentation for the rest of the keyboards?

**Comment by rdstern** [comment]
@Wycklife that's great.  I'll try the summary keyboard next, or perhaps circular.

**Comment by Wycklife** [comment]
@rdstern okay, thanks

**Comment by rdstern** [comment]
In the logical keyboard it is looking good.  
a) In the logical tooltip for when add a command 3,20, and 1,10.
b) Add the tooltip for is.na, see above (I forgot the bold in the message there)
c) On the keys is there a better symbol for the :?  It looks a bit odd.  (Not particularly important point, so don't spend long on this.)
d) Activate any and all.

**Comment by rdstern** [comment]
I have changed the title so we have a separate issue for each keyboard.  Then we can close this once the logical keyboard has the tooltips
