### ISSUE TITLE
Export datasets dialog

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5530]
![image](https://user-images.githubusercontent.com/26301973/65868112-5d2c1580-e380-11e9-879e-9dcd172f5b1e.png)
![image](https://user-images.githubusercontent.com/26301973/65868145-6cab5e80-e380-11e9-854b-d4a356daacd4.png)

Is there any reason why we do not have a similar text perhaps(**click Ok to export data)** to notify the user to click ok to export data? Perhaps it could be bolded or change the colour of the text to alert users? Users tend to forget to click Ok thinking that they have saved/exported data.

**Comment by rdstern** [comment]
Good idea, both in its own right and for dialogues to be consistent, when it is sensible.
So, at the same time could we say Export Data to:  and then make the field the same size as for the Save data.

**Comment by dannyparsons** [comment]
Yes it would be good if these were generally more consistent and better at helping users know what to do.

**Comment by Wycklife** [comment]
@rdstern @dannyparsons should I just set the tooltips for the button browser so that the users sees the information (click Ok to export data) Is that okay. My thought.

**Comment by rdstern** [comment]
I like the addition.
a) I hesitate to change the File > Save As at the same time, but if we give that message it is still quite discrete.  Could we move it to the left and add a Now.  So it starts just above the Ok button.
b) The message is now given on the File > Export > Export Data, but the dialogue has changed in size .  And I don't see the file name so clearly.  Perhaps this could be completed quickly, together with @maxwellfundi .  It should be a small and quick change.

**Comment by maxwellfundi** [comment]
Aha @rdstern  I see the issue here, its designer problems. we will get that fixed up.

**Comment by rdstern** [comment]
Here is the Save Dataset dialogue:
![image](https://user-images.githubusercontent.com/11226469/73866779-571dd800-483d-11ea-823a-1bd272b6c83c.png)

The current pull request has this picture for the Export dataset:
![image](https://user-images.githubusercontent.com/11226469/73866994-c1367d00-483d-11ea-8b74-90ab6d988b38.png)

1. The dialogue could be made smaller - preferably the same size as the Save Data.
2. The comment can be moved to be in the same position as in Save Data.
3. There is an odd issue that the edge of the receiver is blanked out.

**Comment by shadrackkibet** [comment]
Looks like these issues were fixed @Wycklife can you confirm?

**Comment by Patowhiz** [comment]
@rdstern @Wycklife were these issues fixed? If so then I think this issue can now be close

**Comment by Wycklife** [comment]
@Patowhiz @shadrackkibet These were fixed, it should be closed.
