### ISSUE TITLE
Add  treemapify::geom_treemap and treemapify::geom_treemap_text to geom list

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5544]
There is a new dialog here #5540 that implements treemap graphs. 
The geoms are `treemapify::geom_treemap` and `treemapify::geom_treemap_text` from the `treemapify` package.
Can these be added to the list of geoms?

Details: https://cran.r-project.org/web/packages/treemapify/index.html and https://cran.r-project.org/web/packages/treemapify/vignettes/introduction-to-treemapify.html

**Comment by Ivanluv** [comment]
@maxwellfundi  can I take this up?

**Comment by maxwellfundi** [comment]
@Ivanluv let me check if there are other changes from the ucegeom that have not been merged.

**Comment by maxwellfundi** [comment]
@Ivanluv You can go ahead with this :-)
