### ISSUE TITLE
Problems with the Describe > General > Graphics dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5552]
I give an example to illustrate the problems.  
I use the library Dodoma data.  I have 4 layers (though the problems may be the same with just 2 levels.
I do first a jitter plot with tmax as the Y and month_abbr as the X.
The second layer is a boxplot.  Same x and y.

I then Edit and make the **_width of the jitter 0.2_** and the **_alpha into 0.1_**.
Then I Edit the boxplot and make the outlier colour into blue
Then edit the jitter again and you see that the width of the jitter is still 0.2, but the alpha argument has become unset.
Interesting!

I don't know how general this problem is.

Three, more problems.
1. In the boxplot colour the first option is Null.  I don't know what this does? I did try it. I would like the option to not display the outliers and that is NA, rather than Null.  I suspect that is what Null is trying to do, so should we change it to NA?
2. When you start the general graphics dialogue the only option is Add and that is correct.  But if you have the 2 layers above and press Reset, then it still leaves the Edit and Delete buttons enabled.  This gives a nasty error if you try them, which (of course) I did! 
3) The dialogue itself is called **General**.  It should be called **Graphics** instead.

**Comment by Patowhiz** [comment]
@dannyparsons @maxwellfundi  why was Null used? I presume there could be a technical reason behind this?

**Comment by Ogik99** [comment]
> @dannyparsons @maxwellfundi why was Null used? I presume there could be a technical reason behind this?

The Null option means that the outliers should take the color of the boxplot. If say the boxplot is red in color, then the color of the outliers will be red by default

**Comment by Ogik99** [comment]
@rdstern if you wish not to see the outliers, simply set outlier.shape = NA

**Comment by Ogik99** [comment]
> @rdstern if you wish not to see the outliers, simply set outlier.shape = NA

However, if you currently set outlier.shape = NA in R-Instat, you will get an error because NA has been set a string. Currently working on this.

**Comment by Ogik99** [comment]
@Wycklife @Ivanluv could you kindly assist me with this minor edit. I am having some issues with my VB, seems like I have to clone R-Instat again :(
Its a simple minor edit on ucrGeom. I am happy to help.

**Comment by Ivanluv** [comment]
@dannyparsons @Patowhiz   I've been looking at this and noticed that the reason for this
>When you start the general graphics dialogue the only option is Add and that is correct. But if you have the 2 layers above and press Reset, then it still leaves the Edit and Delete buttons enabled. This gives a nasty error if you try them, which (of course) I did!

because the edit and delete buttons are not being reset within the `SetRCodeForControl` .For the subdialogues like `sdgPlots ` this does not bring the bug because `SetEditDeleteEnabled()` is run during the `ucrAdditionalLayers` load event
.Adding this funnction to the `SetRCodeForControl` could solve this bug but I dont think if it would be effective.Do you have any suggestions on how to proceed with this?
