### ISSUE TITLE
Add a Try control to the Model > General > Fit dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5561]
In this dialogue the proposed model can be typed.  Mistakes are therefore possible.  So could we have the same Try control that we have on (for example) the Model > Modelling dialogue.

At the same time a small change to the keyboard would be useful.  Instead of 0 there could there be I( ), with the focus then inside the brackets.  That enables an ordinary formula to be included in the model formula.

**Comment by rdstern** [comment]
This is looking good.  The try seems to work well.  The I() button is also added.  However it doesn't seem to copy the contents to the command.
The example I tried was the Instat Intro guide data sets survey data.

I used Yield and the model was fert.  This works fine.  Then I added I(Fert^2).  It said the model was fert + I(fert^2) but still just fitted fert.  I compared with putting the dialogue into the script file and adding the term there and it then works fine.

I have another problem that seems to have appeared - perhaps it was there earlier.  When I reload the dialogue it says as follows:
![image](https://user-images.githubusercontent.com/11226469/68713144-1b080d80-0595-11ea-89b7-9b294beb575a.png)
 Following this it goes correctly into the dialogue.  I hope you might also have this problem, so you could fix it.

**Comment by Ivanluv** [comment]
@rdstern  am not quite sure of how  I() button  should work.Could you help me with this

**Comment by rdstern** [comment]
@Ivanluv the I() button seems fine in that it allows the text to be put into the command.

I think I may have found the problem.  The function needed is I(), where I is capital i.  I wonder if you are using little l instead?  They look the same!

When I type fert + I(fert^2) with thr capital I, then it says it runs without error.  When I use your code it says there is an error.  So I wonder if you are using capital i?
