### ISSUE TITLE
Problem with the Define Climatic Data Autofill

### ISSUE THREAD

**Issue by Dalasce91** [africanmathsinitiative/R-Instat#5562]
**Describe the bug**
I keep getting an error when i use the define climatic data in the climatic menu and the define climatic data dialogue box appears. I used my own dataset and It auto fills all the required fields except for the date.  I tried using the reset option on the dialogue box but the same thing happens. And I am unable to fill the Date field manually.
I tried using the dodoma dataset but the same thing happens. Only in this case, the station field is empty and I am unable to fill it manually.
Please advise

**To Reproduce**
Go to;
Climatic-> Make date
Climatic-> Use date to create columns for Year, Month_Abbr, Day in month, day of year
Climatic-> Define climatic data
Dialogue box appears and auto fills all fields except Date
Reset-> Auto fills all fields except Date and the option "ok" is locked
![Define Climatic Data Issue](https://user-images.githubusercontent.com/56694672/67502475-32cf2e80-f686-11e9-8266-ad6c66983f3f.png)

**Expected behaviour**
The Date field fill automatically, I click "ok" and I am able to define climatic data

**Screenshots**
If applicable, add screenshots to help explain your problem, particularly of error messages.

**R script or commands**
If applicable, add the R commands from the output or log window that produced the problem. Even better, save the log file and attach it to the issue.

**Details (optional):**
 - OS: [e.g. Windows 7]
 - R-Instat Version [e.g. 0.4.22]

**Additional context**

**Comment by rdstern** [comment]
@Dalasce91 that is odd - the data look fine from the screen shot.  Could you send me a copy of the data file?  It could be through github or directly to me.  Thanks  Roger Stern

**Comment by Dalasce91** [comment]
Please receive the attached dataset chitedze.csv. I manually arranged the
dataset, rounded it off to no decimal places and removed data for February
29th. I also sent the raw unsorted data.

Kind regards.

**Comment by Dalasce91** [comment]
I am not sure how to send the data directly to you. But i used the African Maths Initiative email address (instat@africanmathsinitiative.net) as shown in the tutorials. Please let me know if there is another way to send the data.

**Comment by Dalasce91** [comment]
@rdstern I am not sure how to send the data directly to you. But i used the African Maths Initiative email address (instat@africanmathsinitiative.net) as shown in the tutorials. Please let me know if there is another way to send the data.

**Comment by dannyparsons** [comment]
@Dalasce91 this looks odd and it looks like a bug. Could you please also email that data to me: danny@idems.international and I will have a look.

You could try saving your file, restarting R-Instat and trying the dialog again. You could also try to create the date column again. Go to Prepare > Column: Date > Make Date and just use the first option of a single column and choose your Date1 column. Save the new column with a different name.

I hope that helps but we will also look into that issue with the data.

**Comment by Dalasce91** [comment]
Thank you for your response. Will try working with the dialog again. Also sent rhe data to the email address suggested.
