### ISSUE TITLE
Change the time a tooltip is visible

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5567]
Tool-tips have now been added to a variety of commands.  This is currently mainly in the calculator, but I suggest we should extend this feature to other dialogues.

One problem I am having is that the tooltip disappears automatically after a fixed time.  The default, which we are using now is 5000 milliseconds (5 seconds).  I am finding this is too short for some of the recent tooltips - where I have given a short example.

If you move the focus away from a control then it goes off anyway.  So I don't see a big problem if we lengthen this time.

I had a look [here](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.tooltip.autopopdelay?view=netframework-4.8) where there is a description on how to make the change.

I wonder if this could/should be a global change?  I suggest doubling the period it is visible would be useful.  Please could this be discussed and hopefully implemented.

**Comment by shadrackkibet** [comment]
I agree. I suggested it before on Climdex Indices, It is now time to make this change.

**Comment by rdstern** [comment]
I have now added @maxwellfundi to the people here, on the assumption this is an easy (global) change to make.  I suggest a) we now make the change to 10 seconds.
b) In the longer term could we add an option to the Tools > Options dialogue?  It could go in the Commands tab perhaps?
