### ISSUE TITLE
Processing CHIRPS gridded data with R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5573]
We already have some facilities for processing and testing gridded data.  That's why we work with EUMETSAT.  The ICPAC team in Reading last week arrived with CHIRPS estimated rainfall and temperature data and were assuming these would be used for PICSA work in 2 projects from 2020 in Kenya, Uganda, Ethiopia and Somalia.
I report on the success and limits of the current R-Instat in analysing these data.

1. **_Importing and running a script file in R-Instat?_**
The data were supplied in daily netcdf files.  We can't yet read multiple netcdf files so @dannyparsons provided a program - 225 lines to read the files and to then output them as a single rds file.  This was an R file.
a) I was able to read this into the script window directly, using right-click > load script from file.
b) It doesn't run.  The first line is part of a function which continues over about 200 of lines!  The problem seems to start at line 1, i.e. in R-Instat it is running a line at a time.  
c) This is fine in RStudio and runs.  
d) In R-Instat could we have an option to add line numbers as in RStudio?
e) Is there a way that things like this can run?  It would be nice that a separate function provided to prepare data etc, could run?
**_2.  Reading a large file into R-Instat_**
I then read the Kenya file (prepared by Danny) into R-Instat.  It read in very quickly.  It is 5 variables and 15 million rows.  My machine is fast and with 16Gbytes of ram.  I was still surprised that I could read this in.  
I then found certain operations ran out of memory.  I am not clear how the memory works in terms of operations, file sizes, etc.  I was able to select half the area which was then about 7+ million variables and this seems to work reasonably well.  That may be the sort of limit?
I then tried with the Uganda data.  This was over 9 million rows.  Again it was fast for most things:
3) I could **_not define the data as a climatic data set._**  This took a long time in checking for duplicates and then said it didn't have enough memory.  Could we consider setting a limit and then tell users we are not doing this check?
4) I could not do the end of season calculation.  This took forever before saying it didn't have enough memory.  Could we make a check or do something here?
5) Defining a numeric variable as a factor is quite slow.  Not very annoying, but I wonder if the forcats operation would be faster?
6) The steps I went through were as follows:
a) I rounded the X and Y variables to 2 or 3 decimals using Prepare > Column: Calculations and called them lon and lat.
b) I made lon and lat into factors
c) I used Prepare > Column: Factor Combine to make a combined factor called Station or Location.  For Uganda there were 672 "Stations".
d) I used **_Climatic > Date > Use Date_** to make the Year, Month, doy, variables.
e) I omitted the Define Climatic Data step - see above.
f) I found that some dialogues don't yet use our new "climatic system".  So I used the Prepare > Column: Reshape > Column Summaries to get annual totals for each station.  
g) I also got the date of the start.  This seems to work fine.
h) I selected some points and did a PICSA rainfall graph.  That was all for Uganda data.
i) I was given shape files - for the Kenya county and read them in. 
j) I tried a map for the Kenya county, but was not sure how to add all the points.  I tried adding contour plots, but couldn't get them to look right.

So what is the conclusion and what's next?
ICPAC want 2 workshops in Nairobi with R-Instat in 2020, using the gridded data.
a) It held up amazingly well.  Analysing data from 672 "stations" is great to be able to do!
b) It would be good to be able to read their data directly.  Could we even select points in a polygon when we read in?
c) Minor suggestions above.
d) We do need more facilities for comparing gridded and station data - that will be one of the courses.
e) Continuing to improve the mapping would be great.  The function to find the points in polygons would be very useful, as would good contouring etc.

**Comment by rdstern** [comment]
The amount of memory in R-Instat (from memory.limit() = 4095, i.e. 4gbytes.
In RStudio on my machine it is much more.
If I try to change in R-Instat it tells me not to be silly - that is the limit.  Does that mean we are using 32 bit R in R-Instat?  Do we have to do that?

**Comment by rdstern** [comment]
@dannyparsons claims that we deliberately install R for 32 bit machines, because some R users will have that.  But also that we could perhaps install 64 bit R on those machines.  I assume this could be an automatic part of the installation, i.e. to detect whether the computer is 32 or 64 bit and install accordingly.  
I wonder if this could be checked, presumably by @maxwellfundi? even for the next version, which would be used in Ghana in early December.  It could make a big difference now we are processing the gridded datasets.

**Comment by Patowhiz** [comment]
@rdstern This is absolutely possible. There is several way to do this kind of validation. What I see being done in most other major softwares, they give 2 binaries in their websites. a 32 bit and 64 bit version. We could do the same. If someone downloads the 32 bit R-Instat, then it comes packaged with the 32 bit R, for 64 bit then it comes with 64 bit R. I think that simplifies the process and also reduces the download size and hands the control over to the user. Another way would be to have the website detect the user's machines architecture type and suggest the correct version to use(this is now popular)  though we don't have an advanced website and I'm not sure if wordpress can do this.

Also for consistency and probaby to alleviate potential bugs in terms of memory, I don't think if we should have a 32 bit R-Instant using a 64 bit R. In my opinion that could potentially lead to problems.

**Comment by Patowhiz** [comment]
We could also separate the 2 setup files but indicate that 1 requires the other(in the website) and have R-Instat be able to check and download the correct R setup file during installation.

Though I don't know how simple this will be to our target users
