### ISSUE TITLE
Improving the spells dialogue following comments from ICPAC

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5575]
We currently have a spells dialogue, though some find it a bit difficult to use.  In the recent ICPAC training they currently use spells in a different way - a way that I don't like much.  But they asked still for it to be included, as that is the way they would like to process spells.  I can also see an adjustment to their proposed method that could be very useful.
Our current spells analysis takes a period in the year and finds the length of the longest (dry, wet, hot, etc) spell in that period.  For example it calculates the longest dry spell length each year between the date of the start and the end.
The additional option requested is the number of dry spells longer than a specified length.  For example **how many** dry spell in Jan-March period longer than 7 days.  I have never liked this because a very long dry spell in a particular year (say from 3rd Jan to 25 March is just one spell, but it doesn't leave any time for more spells.  So the answer in that year is 1.  While another year could have 5 dry spells of 8 days and sounds much worse.
However, I agree that if this is what a regional centre would like to produce, then we should include it.  Also if we want to critique it, then it is easier if we can produce it and then discuss the use of the results.
And I can also consider an adaptation of the idea that would be useful.  Instead of just giving the number of spells we could also include the number of days in the period belonging to a spell of longer than 7 days.  So, then this would be many days in the first case and just a total of 5 days in the second.  The 2 together could be a very useful summary.

**Comment by rdstern** [comment]
I am now including this in the improvements to do reasonably soon.  It is an interesting one, because (I think) setting a threshold and then finding all the spells longer than this threshold is similar to setting a threshold for extreme values, which we do.
So it is an important feature to have in teaching too.  In particular, why is the threshold method very useful in extremes an d not so obvious in studying extreme spell lengths!

This to be done by @N-thony perhaps including discussions initially with @shadrackkibet who has implemented most of the extremes above a threshold.

**Comment by N-thony** [comment]
> I am now including this in the improvements to do reasonably soon. It is an interesting one, because (I think) setting a threshold and then finding all the spells longer than this threshold is similar to setting a threshold for extreme values, which we do. So it is an important feature to have in teaching too. In particular, why is the threshold method very useful in extremes an d not so obvious in studying extreme spell lengths!
> 
> This to be done by @N-thony perhaps including discussions initially with @shadrackkibet who has implemented most of the extremes above a threshold.

Great. Happy to work on it with @shadrackkibet.
