### ISSUE TITLE
Adding the Random button in File > New Data Frame

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5579]
One cosmetic improvement is the try feature.  It works fine.  
a) After using it, it sort of remains until used again.  Could it clear when there is a change in the entry.
b) When ok could it add the green colour for consistency with the other dialogues with Try.

Please could we activate the Random option in the F**_ile > New Data Frame_** dialogue.  It can be just the same as the current Command button, but move over the 2 Wakefield examples and then I would like to add some more Wakefield, (plus some examples not using Wakefield.  But the Wakefield ones are potentially exciting.
First move over the third example: data.frame(x = 1:30, y = rnorm(30, mean = 100, sd = 15), z = runif(30, min = 10, max = 30)) into the new place.
Add: data.frame(data = replicate(20,rbinom(n=25, p=0.4,size=1)))
Add
data.frame(data = matrix(data=c(rbinom(7300,p=0.4,size=1)*rexp(7300,0.1)), nrow = 365, ncol = 20))
Add 
data.frame(replicate(10,(sample(c(TRUE,FALSE),size=50,replace=TRUE,prob=c(0.3,0.7)))))

In addition to the 2 for Wakefield that are there, add:
a) wakefield::r_data_theme(n = 200, data_theme = "survey") 
b) wakefield::r_data_theme(n=500, data_theme = "survey2") %>% r_na(prob=0.1)
c) wakefield::r_data_frame(n = 50,id, r_dummy(color),r_series(likert,3),grade,grade,grade)

Finally, I would sometimes like to put extra commands in front of the main command.  If they are on different lines it seems to run ok, though the Try button says otherwise.  An important example is set.seed(995) say, so you can have reproducible examples. I would also like to have:
n=25;p=0.1 say, which would be better programming.

If I put them on the same line it says it can't run, because it expects a data frame.

**Comment by Patowhiz** [comment]
I seem to have forgotten the reason as to why we disabled the Random button?

**Comment by Patowhiz** [comment]
Yes. There was a problem with the wakefield package as mentioned in issue #5087. It's why we disabled the button. I'm not sure if the bug was fixed by the author

**Comment by Patowhiz** [comment]
@rdstern 

> a) After using it, it sort of remains until used again. Could it clear when there is a change in the entry.

The try textbox automatically clears on my side every time I make a change in the commands entry.

**Comment by Patowhiz** [comment]
@rdstern I don't understand what you mean by 

> Finally, I would sometimes like to put extra commands in front of the main command. If they are on different lines it seems to run ok, though the Try button says otherwise. An important example is set.seed(995) say, so you can have reproducible examples. I would also like to have:
> n=25;p=0.1 say, which would be better programming.
> 
> If I put them on the same line it says it can't run, because it expects a data frame

**Comment by Patowhiz** [comment]
@rdstern @dannyparsons I went through the first issue #4439 related to this issue. We didn't discuss the designs of the Random option clearly. Any design suggestions?

**Comment by Patowhiz** [comment]
@rdstern can you suggest the comments to add in these new example commands:

> Add: data.frame(data = replicate(20,rbinom(n=25, p=0.4,size=1)))
> Add
> data.frame(data = matrix(data=c(rbinom(7300,p=0.4,size=1)*rexp(7300,0.1)), nrow = 365, ncol = 20))
> Add
> data.frame(replicate(10,(sample(c(TRUE,FALSE),size=50,replace=TRUE,prob=c(0.3,0.7)))))
> 
> In addition to the 2 for Wakefield that are there, add:
> a) wakefield::r_data_theme(n = 200, data_theme = "survey")
> b) wakefield::r_data_theme(n=500, data_theme = "survey2") %>% r_na(prob=0.1)
> c) wakefield::r_data_frame(n = 50,id, r_dummy(color),r_series(likert,3),grade,grade,grade)

**Comment by Patowhiz** [comment]
What should be the default command for wakefield option, the one to be shown when a users selects the option?

**Comment by rdstern** [comment]
I can suggest comments, but my point was simpler than that.  Sometimes, in examples (usually from the R packages) comments are included.  here is an example:
```
# Example linear estimation and design of experiments. D.D. Joshi. 1987
# Professor of Statistics, Institute of Social Sciences Agra, India
# 6 varieties of wheat crop in a BIB whit 10 blocks of 3 plots each.
y <-c(69,77,72,63,70,54,65,65,57,59,50,45,68,75,59,38,60,60,62,
55,54,65,62,65,61,39,54,67,63,56)
varieties<-gl(6,5)
block <- c(1,2,3,4,5,1,2,6,7,8,1,3,6,9,10,2,4,7,9,10,3,5,7,8,9,4,5,6,8,10)
```
Now, with the **command option** this is easy.  I just copy the code and paste - including the comment lines. (I make sure there is just one line for the y above.)
In the Construct option would it also be easy to include these extra lines - comments or otherwise?
Something like this:
![image](https://user-images.githubusercontent.com/11226469/69141120-f4c5fe80-0abb-11ea-81ae-a4228c68a761.png)
I have no problem if this isn't possible - just would like to know if this is easy.

And how about this code?  Is it easy in the Command or Random options?  Is it possible in the Construct?

```
set.seed(12)
n <- 100
xx<-1:n
zz<-runif(n)
yy<-2+1.5*pmax(xx-35,0)-1.5*pmax(xx-70,0)+15*pmax(zz-.5,0)+rnorm(n,0,2)
dati<-data.frame(x=xx,y=yy,z=zz)
```

**Comment by Patowhiz** [comment]
Sorry I meant in the command and wakefield popup that shows the command examples you have told me to hide. The popup has 2 columns. The command and comment column which helps the user what the command is all about.

In regards to commands that span multiple windows the command and random option should be able to handle that. It's what I'm working on. We had not considered this in the last PR that addressed this dialog

```
set.seed(12)
n <- 100
xx<-1:n
zz<-runif(n)
yy<-2+1.5*pmax(xx-35,0)-1.5*pmax(xx-70,0)+15*pmax(zz-.5,0)+rnorm(n,0,2)
dati<-data.frame(x=xx,y=yy,z=zz)
```

**Comment by rdstern** [comment]
Default option is "the works" example

**Comment by rdstern** [comment]
@Patowhiz - looks great.
1. Can you move all the examples that generate random sequences into the random option.  The Wakefield ones are already there.  Move over also the 2nd, 4th,5th and 6th lines from the Command button.  They go on top of the Wakefield ones.
2. I am unconvinced of the need of the Comment column in the examples.  Can that be removed easily?  That would also free thge space so you see more of the commands.  
3. I will describe the examples in the Help.  But is it easy to add the comment as a tooltip instead?  If so, I'll sort out the text for a few more of the examples.
4. I still get an error sometimes when the commands work ok.  For example the command below is copied from the example for the seq.Date function, i,e.:

`seq(as.Date("1910/1/1"), as.Date("1999/1/1"), "years")`


![image](https://user-images.githubusercontent.com/11226469/69213715-cea46b00-0b5c-11ea-8e84-82780f832fd0.png)

**Comment by rdstern** [comment]
Here is an example for the Construct option:
![image](https://user-images.githubusercontent.com/11226469/69219223-4b8a1180-0b6a-11ea-96a9-f956ffeacf25.png)

Here are the commands:
```
# Code generated by the dialog, New Data Frame
data9 <- data.frame(no=c(0,0.5,1,2:28), seq=seq(30,1,-1), place=rep("Kisumu",30), place2=c(rep("Mombasa",10),rep("Nairobi",20)), days=seq(as.Date("2020/4/1"),as.Date("2020/4/30"),"days"), occasions=seq(as.Date("1970/1/1"),by="4 months",length=30))
data_book$import_data(data_tables=list(data9=data9))
```
Here is the data frame generated:

![image](https://user-images.githubusercontent.com/11226469/69219741-6610ba80-0b6b-11ea-9ed5-ab08c4255655.png)

These individual lines could become 6 examples for the Construct option.

For extra examples for the Command option:
data.frame(x=1:30, s=rep("Reading",30),r=seq(1, 6.8, length=30),t=seq(1,60,2))
data.frame(l=1:31,d=seq(as.Date("2013-1-1"),as.Date(2013-1-31),"day"))
data.frame(n=1:12,h=seq(as.POSIXct("2010-1-1 3:0:0"),by="2 hours",length=12))

**Comment by Patowhiz** [comment]
Yes this can be removed easily

> 6. I am unconvinced of the need of the Comment column in the examples. Can that be removed easily? That would also free the space so you see more of the text of each command.

By 2nd do you mean the 3rd? 
`data.frame(x = 1:30, y = rnorm(30, mean = 100, sd = 15), z = runif(30, min = 10, max = 30))`

> 1. Can you move all the examples that generate random sequences into the random option. The Wakefield ones are already there. Move over also the 2nd, 4th,5th and 6th lines from the Command button. They go on top of the Wakefield ones.

@rdstern the command `seq(as.Date("1910/1/1"), as.Date("1999/1/1"), "years")` produces an object of type double which is not a data.frame type that is required for R-Instat, not unless I'm missing something. I know the try okays this but it's cause we are just checking if the command is a correct "functional" one not whether the results produced are of type data.frame, @dannyparsons is there away I can check for data.frame type in the R-Instat objects when running the script directly? 
![typeof](https://user-images.githubusercontent.com/21179007/69227643-35dd1200-0b93-11ea-8967-2c6bd57b534f.JPG)

> 8. I still get an error sometimes when the commands work ok. For example the command below is copied from the example for the seq.Date function, i,e:

**Comment by rdstern** [comment]
Yes the single commands of that type - 
`seq(as.Date("1910/1/1"), as.Date("1999/1/1"), "years")`
in fact the set of 6 commands would only go as examples if they be associated with the Construct option - where there isn't currently an Examples button.  The user would then copy single lines into the Command part of that dialogue.

By the way I also wanted to add more on the importance of this dialogue.  It is becoming a great one for teaching.  But, in addition, there is a new reason as follows:

In our Modelling dialogues, once you have a model, then it is important to be able to Predict.  That uses the model and says what you would get for new x-values.  When you predict with the existing data that's just the fitted values.  The next step is to predict with new data - and for that you need the new data in a new data frame.  So this is all making it really easy to get that new data frame.

**Comment by Patowhiz** [comment]
@rdstern for clarity in your [comment](https://github.com/africanmathsinitiative/R-Instat/issues/5579#issuecomment-555903181) . The example format for the construct will be different 2 the other 2 options. I'm implementing it in such away the pop of the construct examples will have 2 columns, namely; Column Name, Expression. So each line when clicked will add a row to the grid. Unlike the command and Random option where each example when clicked replaces whatever that is there in the textbox.

I hope I've understood your comment well?

**Comment by Patowhiz** [comment]
@rdstern you second example line I think has a syntax error. It lacked the quotes. I have added them

> For extra examples for the Command option:
> data.frame(x=1:30, s=rep("Reading",30),r=seq(1, 6.8, length=30),t=seq(1,60,2))
> data.frame(l=1:31,d=seq(as.Date("2013-1-1"),as.Date(2013-1-31),"day"))
> data.frame(n=1:12,h=seq(as.POSIXct("2010-1-1 3:0:0"),by="2 hours",length=12))

Changed the second example to 
data.frame(l=1:31,d=seq(as.Date("2013-1-1"),as.Date("2013-1-31"),"day"))
