### ISSUE TITLE
Minor changes on the File > Export dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5589]
1. In the File > Export > Export Dataset a minor change is being worked on now, by @Wycklife in #5585.  At the same time, the field for the filename starts much further to the right of the dialogue than the corresponding position in the File > Save As > Save Data As, dialogue.  They should be made the same.  I also look forward to the changes in #5585. 
2. In the File > Export > Export Graph as Image the field for the filename is enabled - though whatever you type is ignored.  Could it be disabled as is the case in the other similar dialogues, for example File > Export > Export R Workspace.

**Comment by Wycklife** [comment]
@rdstern I working on the two.

**Comment by Patowhiz** [comment]
@rdstern were the 2 items fixed? I have a PR touching on these 2 dialogs. I could add in the changes if you were not satisfied with the last PR in regards to this issue. I noticed the file name still starts much further, is the current position of the label "OK" with you?

**Comment by rdstern** [comment]
@Patowhiz please could you check and complete if necessary.
