### ISSUE TITLE
Add examples to the Prepare > Generate > Enter dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5596]
@Patowhiz here is the current Enter dialogue.

I am interested in adding some examples.  If so, then I wonder how this should be done?  
We can have tooltips, of course.
But in addition I wonder about helping users in the writing of examples of the commands as we do in the File > New Data Frame dialogue.

Here there are 2 obvious ways.  We could have a button - as we do in the File > New Data Frame.  I assume that would be quick and easy to do, following the File >New Data Frame work.  It would be just the right-hand side of the formula.  It could go just after the show arguments checkbox.

Or the dialogue automatically remembers past commands.  When you start it is empty.  It could start with a few examples - perhaps below a horizontal line.  

@Patowhiz What do you think?  Should we add the examples?  Would it be very easy with a button?  If so, then I am slightly inclined that way.

I got to this because I would like to build towards a guide to help beginners on their first commands that use these "halfway" dialogues.

**Comment by Patowhiz** [comment]
@rdstern yes we can have a similar "examples" functions like in the data frame dialog. I suggest we have the examples button just above the combobox to be consistent with the data frame dialog and also future dialogs that may need this. I'm have no reservations with having it in another place though.

Please share some of the examples that you have. 

![dlgEnter](https://user-images.githubusercontent.com/21179007/86086373-43a03180-baaa-11ea-9a44-05c7e9432621.JPG)

**Comment by rdstern** [comment]
@Patowhiz happy to have you add this.  Could you move the Show Arguments over a little and put it at the same level to the right of that?

**Comment by Patowhiz** [comment]
Yes I can do that. Will have this ready for your review as soon as you share the examples.

**Comment by Patowhiz** [comment]
@rdstern that is the new design. Awaiting the sample commands.

![dlgEnter](https://user-images.githubusercontent.com/21179007/86311513-3f4e5280-bc29-11ea-96b6-cc8d6ca7702f.png)

**Comment by rdstern** [comment]
@Patowhiz that is great.  I am looking at it now.  I am finding other small items I would like to change.  Happy for you to complete all this, or for Wyclife to do some of the tasks if that fits.  Then I would like @lilyclements to review, because it is a good example where the layout can be really helpful and she is great on this type of detail.

a) I would prefer the Examples button after the Show arguments checkbox, rather than before.  That's a trivial one.
b) I would like @dannyparsons to clarify the need for the seq2 button.  Currently it just gives the seq function again, though there is a seq2 function as well.  But I don't see why we need it.  Danny did explain and it made sense then.
c) I will also provide tooltips for each of the individual keys.
d) Then the Examples button will extend these for examples that are not obvious from a single key (for example `rep(factor(LETTERS[1:4]),c(1,4,2,3))`
e) It will also be useful to change the layout of the keys so that functions can be given properly.  For example having LTRS on a key is confusing, when the function is LETTERS( ).
f) I suggest we have the ordinary (basic) keyboard from the calculator, rather than the special one currently in the ENTER dialogue.

Here are some examples to start with:
1. `4.5` (tooltip: A single number repeated for the data frame)
2. `'Nairobi'` (tooltip a single text repeated for the data frame)
g) (By the way this gives an error when using the Try, but they work fine!)
3. `c(2,3,4)*1.5E02` - gives 300, 450, 600 then repeated for the data frame
4. `factor(c(1,2,3))` - values 1 to 3 with the variable made into a factor
5. `factor(rep(LETTERS[1:4],c(4,3,1,1)))` tooltip: Gives A,A,A,A, B,B,B,C,D as a factor)
6. `factor(rep(c(month.abb[4:7],NA),c(2,1,2,1,2)))` tooltip: Gives Apr, Apr, May, Jun, Jun, Jul, NA, NA) 
7. `c(1:4,10,rep(15,3),20)` (tooltip: A sequence of values 1,2,3,4,10,15,15,15,20)
8. `c(0,seq(1,5,2 ),seq(10,12),15)` (A set of sequences, giving 1,3,5 10,11,12, 15
9. `runif(3,c(0,5,10),c(1,10,20))` (tooltip: Random uniform data from 3 different distributions)
10. `seq(as.Date('1935/3/1'),as.Date('1940/12/1'),'quarter')` A sequence of dates from 1935/3/1, 1935/6/1 ...)

With the ordinary keyboard from the calculator the extra keyboard

**Comment by Patowhiz** [comment]
Most of the items stated are relatively easy. I'm happy to have @Wycklife take over once PR #5878 is merged.  I took up this purposely to demonstrate the custom popup .component.  @Wycklife if you already have a lot I can still proceed and do the new items raised

**Comment by rdstern** [comment]
Thanks @Patowhiz I support your suggestion for @Wycklife to do a "take-over" as soon as you have done the bits that are in your domain.  He has been very efficient on other dialogues involving keyboards and it would be good for him to be comfortable in the corresponding R commands here.

**Comment by rdstern** [comment]
Given the same basic keyboard as the calculator, I suggest 16 keys on the extra keyboard.  10 of these are already there from the existing Enter keyboard:
1)` :` 
2) E
3) c( )
4) NA
5) rep
6) seq
7) pi
8) LETTERS
9) letters
10) months (month.abb, or mon- on existing keyboard) 
Then also 
11) factor - key gives factor( ) 
12) date - key gives as.date(' ')
13) day - key gives 'day'
14) month - key gives 'month'
15) runif  - key gives runif( )
16) rnorm - key gives rnorm( )
