### ISSUE TITLE
Adding a dialogue to install a new (or updated?) R package

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5601]
This is (sort of) just the install.packages("xxx") command and I use this quite often from the script window.
Could we have a simple dialogue to do this.  It could be a new Packages tab in the Tools > Options dialogue.
The R code isn't trivial because it would be good if:
a) It checks first if the package has already been installed.
b) It checks if the package exists - could be a typing error in the name of the package.
This is discussed in stack-overflow for example [here](https://stackoverflow.com/questions/9341635/check-for-installed-packages-before-running-install-packages).

**Comment by rdstern** [comment]
@Ivanluv That's great.  It works already!
1. Could the menu option be called "Load R Package".  And could it be above the Options item - so the Options stays last.
2. I checked lots of different things and really like the check field.  When the package is already installed it said: "Package is installed. Newer version available: 0.1.2 (current: 0.1.1)."  The text doesn't quite fit into the field.  Could you make that just a bit wider - even to the end of the current dialogue.  It is close. 
3. Then I tried to install a new package.  I chose one called **_see_**.  It asks what mirror to install from.  I guess that's useful, but I don't think that RSudio asks that.  Could one be chosen?  Then it gives a list of all the packages, rather than just installing.
a) When I have given the package name, then it should proceed automatically with that installation.
b) An additional feature could be to suggest this option.  This could either be keeping the dialogue as now - when no package is given then Check is correctly disabled.  But you could enable Ok and Script and then it would proceed.
Or you could have radio buttons.  **_Give Package_** and **_Choose from List_**.

**Comment by dannyparsons** [comment]
1. That should be "Install R Package". Load has a separate meaning in R (when you do `library(zoo)` you are "loading" the `zoo` package).

3. @Ivanluv you can fix the repo in the `install.packages()` command (as we did in `available.packages()`) so that it does not ask to choose the mirror site.
