### ISSUE TITLE
Save Column Position not working in regular sequence dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5612]
The save column position was merged and further work is to be in a new pull request.
One dialogue where it exists already is the Prepare > Generate >Regular Sequence.  It doesn't work there, but always puts the calculated variable at the end.  
This dialogue is also in prepare > Column: Date > Generate Dates - also (as expected) it doesn't work there.  In the next dialogue in the menu Prepare > Column: Date > Make Date it does work.

I note that the Make Date dialogue always has variables, from which to make the date, while the Generate regular sequence does not.

**Comment by rdstern** [comment]
@Patowhiz now that (I hope) the detailed question of lining up the button is solved, it would be good to make this change in the position of the saved variable.  For example I notice that now #5611 produces a similar button and it is perfectly lined up.

It would then be really good to have this facility working in each dialogue that adds a variable.  I wonder who would quickly be able to do this.  I am happy to test.

**Comment by Patowhiz** [comment]
@Wycklife is now working on this.
