### ISSUE TITLE
Changes in the Prepare menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5615]
It is currently like this:
![image](https://user-images.githubusercontent.com/11226469/70516627-3b44d100-1b2f-11ea-9809-f70c6c67b310.png)

I suggest 
a) we move Convert Columns above the line - still just below Replace Values.
b) We get rid of the Column Metadata option
(There could be a reason for keeping it - as I get to writing the help - it does give an easy route to renaming columns, adding labels, and also changing the significant figures displayed.  We don't seem to have another way to do that.  
However, if we do that, then I suggest we move it up, so it is just under Rename Column.)
c) We move **_Column Structure_** down to just above **_Colour by Property_**.  And we get rid of that line below the current Column Structure position.
d) We check on the Protect Column and Freeze Columns.  They are disabled and have been there a long time.  Are we going to do anything soon, or should we either hide them for now, or get rid of them?

**Comment by rdstern** [comment]
Now discussed with @dannyparsons and @volloholic .  The items above are agreed with hiding the disabled options.
In addition put a line above the Column: Reshape.  And change Column: Reshape into Data Reshape

**Comment by rdstern** [comment]
@Wycklife is this something you could do this week?  You have been changing the form Main already for the Model menu.  I hope it will be easy?

**Comment by Wycklife** [comment]
@rdstern Yes sure, I have added it on my list of task.
