### ISSUE TITLE
Improving the toolbar and windows easily!

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5616]
Here is our current toolbar:

![image](https://user-images.githubusercontent.com/11226469/70526920-903e1280-1b42-11ea-9c5b-7a583784b2a0.png)

Two icons also include the arrow for a menu, and the File > Open is used here.

I have a small series of suggestions to make the toolbar more useful:

1.  The icon above shows 5 previous files and that is the same as at the bottom of the file menu.  In the file menu 5 is enough, but here we could easily have more and that could be useful.  I suggest 10 here. 
2. In #5228 I suggest having a similar pull-down menu on the graph icon above, particularly to make it easier to use plotly.
3. In the icon for the log window could we have another with **_Log Window_** and **_Script Window_** being the 2 options.
4. Similarly for Column Metadata could we have one with Column Metadata and Data Frame Metadata being the 2 options.
5. Something a bit different and I am not sure where it fits.  Our current windowing system is limited, but useful.  This is not the time for an overhaul.  However, there is one layout that would be very useful on occasions.  I would call it "Swap data and metadata view".   I would use the column metadata much more if that were there.  It would show all variables and the right-click menu ius already there.  
This would be another option on the View menu and then on the new little pull-down menu.

**Comment by rdstern** [comment]
From discussions some of these changes have held up:
a) Past files in drop down could be a list of 10 rather than 5 files.  But in the File menu it should then be 5 with a More button, (or some other way of extending) so you can get 10 there if you wish.  (If that takes a long time to implement, then it is the least important and should be dropped.)
b) Pull down next to the graph icon.  The R-graph (which is on the toolbar) is the first option and plotly is the second.
c) Pull down also on the current log file icon.  The icon should now call the script file instead of the log file.  Then in the pull-down Script File is first and Log File is second.
d) Same on the i icon that calls the column metadata.  The first item is Column Metadata and second is Data Frame Metadata.
e) Extra window option investigated and discussed further - see above.  This may not be completed in the code sprint.

**Comment by shadrackkibet** [comment]
I am now working on this.

**Comment by rdstern** [comment]
It is pretty good, and almost what is needed.
For comparison the first item - Open File shows what I would like.  In turn:
1) The Script Window is close.  When I click on the script it correctly gives me the script window.  But it also opens the pull-down - which is not needed then.  It is correct with the pull-down if I click on the arrow.
2) The Column metadata should go into the metadata when pressed - currently it does not and it only gives the little menu.  The menu works fine.
3) The graph gives the graph correctly.  But I think the pull down menu appears briefly.  It doesn't need to.
When you want plotly you still get the graph.  You should not.
More a question - I will check, but the plotly currently goes to the dialogue.  I suggest - if easy - then it gives the graph directly.
