### ISSUE TITLE
Adding a simple paste into a data frame

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5619]
As I write the help it would now be very useful if we could have a paste into the data frame. 

Previously we have been hesitant, because pasting is complicated to do well.

I don't want to spend long on the pasting, partly because I think we may want to use a new grid control in the future.  But also because it will take forever to do well.  That's why I am suggesting just a single column (variable) at a time.  You have quoted one day for this work and I suggest that this is a good limit (at least for now.)  What can you do (if anything) on the pasting of a single column within a day?   

So, I suggest a very simple paste would be useful and consistent with our current use of R-Instat.  We can (I think) already paste a single variable into the levels/labels dialogue and perhaps elsewhere.  Could we similarly also paste a single variable (column) into a data sheet.  Usually it will be into one with just missing (NAs) currently.  If so, then it simply pastes.  If too short, then some NAs remain (top or bottom).  If too long, then it could give a message, or just paste what it can.
a) If the variable is already there, then it could give a warning.
b) It only pastes down - never across.  One small enhancement is therefore that if the data in the clipboard goes across, then it still works and pastes down.
c) Of course if you can do more, particularly pasting into multiple columns, that's fine.  And it could be as limited as you like, e.g. only when they are empty, or only if they are all numeric, or ...

**Comment by Patowhiz** [comment]
Fundamentally, I'm implementing this in accordance with the design and implementation principles used in popular spreadsheet packages like excel;
1. Users can paste to the whole column. Data will be paste from first row to the end of the copied data. The other rows will not be changed.
2. Users can paste to a column from the selected cell row position. Data will be paste starting from the cell row position.
3. To paste to multiple columns, the paste data rows should be separated by tabs.

However, I have also factored in R-Instat validations
1. If the paste data is longer than the data frame length, the paste data beyond the last row will be ignored.
2. All data paste into a column must be of the data type that the column expects. A single wrong data type value will result to the whole data ignored (Roger, do you prefer this or should the wrong value be skipped? I prefer ignoring the whole data, minimises user unexpected errors and we don't have undo for now).
3. You cannot paste into a column that doesn't exist (this will be done in another feature issue of pasting into the whole data frame).

**Comment by Patowhiz** [comment]
I have also added menu items for pasting as shown below. users can also use Ctrl + V to copy into a cell.

Pasting into column
<img width="292" alt="paste into column" src="https://user-images.githubusercontent.com/21179007/93231867-e56a1d00-f781-11ea-9979-e8155b513d87.png">

Pasting into cell
<img width="323" alt="paste into cell" src="https://user-images.githubusercontent.com/21179007/93231911-f3b83900-f781-11ea-9f8d-e8f63a3e2117.png">

**Comment by dannyparsons** [comment]
This sounds like a sensible starting point.

I would be happy with starting with only allowing to paste into one column at a time. But multiple is also useful if it can be done.

Could you explain what you mean by "Paste into column"? I don't see why there should be separate Paste buttons? There should just be one Paste button - the R method should be the same whether it is a single value/partial column/whole column/multiple columns etc.

Pasting is a very dangerous operation, especially in R-Instat without an undo, so I would like to maximise validation, checks and messages/errors to users not minimise them.

> 1. If the paste data is longer than the data frame length, the paste data beyond the last row will be ignored.

If the paste data is longer than the data frame length then give an error saying "Cannot paste x values into y rows". If the extra data is ignored the user has made an error and won't know about it.

> 2. All data paste into a column must be of the data type that the column expects. A single wrong data type value will result to the whole data ignored (Roger, do you prefer this or should the wrong value be skipped? I prefer ignoring the whole data, minimises user unexpected errors and we don't have undo for now).

This is also important. If any of the data is of the wrong type then give an error, ideally an informative one that says which column the error was from. Note that data type includes factors - values must be an existing level, logical - TRUE or FALSE only. These should be the same checks as we currently have for typing into a single cell. The exception to this is for an "empty" column, which is a logical column of `NA`s only. In this case, any value is allowed because R will define the type based on the values given.

**Comment by dannyparsons** [comment]
Also, I know that the menu is long but I don't like Copy and Paste being on a sub menu, they are good to have quick access to.

**Comment by Patowhiz** [comment]
@dannyparsons thanks for the feedback. 
> Could you explain what you mean by "Paste into column"? I don't see why there should be separate Paste buttons? There should just be one Paste button - the R method should be the same whether it is a single value/partial column/whole column/multiple columns etc.

I used Paste Into Column label just for consistency.  I'm happy to just label it Paste. But then it sounded inconsistent with Rename Column, Delete Column etc. They both end with "column". If we go with just Paste, shouldn't we be also labelling Rename, Duplicate etc ?

> If the paste data is longer than the data frame length then give an error saying "Cannot paste x values into y rows". If the extra data is ignored the user has made an error and won't know about it.

Yes I agree.

On the logical column, do you think it's a good idea to accept values 1 or 0, or rather is a column of 1's and 0's only regarded as logical?

**Comment by Patowhiz** [comment]
@dannyparsons thanks for the feedback. 
> Could you explain what you mean by "Paste into column"? I don't see why there should be separate Paste buttons? There should just be one Paste button - the R method should be the same whether it is a single value/partial column/whole column/multiple columns etc.

I used Paste Into Column label just for consistency.  I'm happy to just label it Paste. But then it sounded inconsistent with Rename Column, Delete Column etc. They both end with "column". If we go with just Paste, shouldn't we be also labelling Rename, Duplicate etc ?

> If the paste data is longer than the data frame length then give an error saying "Cannot paste x values into y rows". If the extra data is ignored the user has made an error and won't know about it.

Yes I agree.

On the logical column, do you think it's a good idea to accept values 1 or 0, or rather is a column of 1's and 0's only regarded as logical?

**Comment by Patowhiz** [comment]
@dannyparsons thanks for the feedback. 
> Could you explain what you mean by "Paste into column"? I don't see why there should be separate Paste buttons? There should just be one Paste button - the R method should be the same whether it is a single value/partial column/whole column/multiple columns etc.

I used Paste Into Column label just for consistency.  I'm happy to just label it Paste. But then it sounded inconsistent with Rename Column, Delete Column etc. They both end with "column". If we go with just Paste, shouldn't we be also labelling Rename, Duplicate etc ?

> If the paste data is longer than the data frame length then give an error saying "Cannot paste x values into y rows". If the extra data is ignored the user has made an error and won't know about it.

Yes I agree.

On the logical column, do you think it's a good idea to accept values 1 or 0, or rather is a column of 1's and 0's only regarded as logical?

**Comment by Patowhiz** [comment]
@dannyparsons thanks for the feedback. 
> Could you explain what you mean by "Paste into column"? I don't see why there should be separate Paste buttons? There should just be one Paste button - the R method should be the same whether it is a single value/partial column/whole column/multiple columns etc.

I used Paste Into Column label just for consistency.  I'm happy to just label it Paste. But then it sounded inconsistent with Rename Column, Delete Column etc. They both end with "column". If we go with just Paste, shouldn't we be also labelling Rename, Duplicate etc ?

> If the paste data is longer than the data frame length then give an error saying "Cannot paste x values into y rows". If the extra data is ignored the user has made an error and won't know about it.

Yes I agree.

On the logical column, do you think it's a good idea to accept values 1 or 0, or rather is a column of 1's and 0's only regarded as logical?

**Comment by dannyparsons** [comment]
I think we can just have a single `Paste` item and this will cover pasting into a cell/column/range etc.

For logical, a 1-0 column is different from a logical column as a different type in R and some functionality will be slightly different so let's not mix them up. It's easy to convert a 1-0 column to logical if you want so I think we can keep it strictly as TRUE/FALSE.

**Comment by Patowhiz** [comment]
@rdstern I need you suggestion on the labelling of the menu toolstrip and their locations.

I would also like to point out a few additions;

1. When you paste from the column right click menu, the implementation assumes the first row of the clipboard data is a header and therefore skips it when pasting to the dataframe.

2. When you paste from a particular cell, the implementation assumes there is no header in the clipboard data. So it pastes all the data.

We can change this implementation if need be. The code is flexible enough.

**Comment by Patowhiz** [comment]
In addition, the pasting can only be done to existing columns. If the current changes are review and agreed on, I'm happy to implement pasting new columns to data frame. I think it's related to this issue.

**Comment by dannyparsons** [comment]
I am not sure what would be most appropriate for the headers assumption. It might be easier to assume no headers even from the Data View header. For example, what should happen if the pasted headers are different from the current ones? Does that rename the columns? That might be useful but not sure we want to do too many things in one go.

**Comment by Patowhiz** [comment]
@dannyparsons from @rdstern PR comments, I've thought more about the headers. 
I think when pasting from the column header, the header should also be renamed. To take up the new name. This will put it consistent with pasting to a newly created column, because the created column should have the pasted header. Again this is also what would happen if I pasted to a spreadsheet. 

If the data doesn't have a header,  then the user can paste from the first cell of the column.

**Comment by Patowhiz** [comment]
I have created issues for pasting to new columns #5991 and pasting new data frame #5992

**Comment by Patowhiz** [comment]
@rdstern I noticed the cell options when I right click on the data grid cell are no longer there. Where should I add this cell paste option.

![cell options](https://user-images.githubusercontent.com/21179007/117341437-f70a4d00-ae56-11eb-91e0-e6507f92276f.png)

**Comment by Patowhiz** [comment]
The requests made by @rdstern have now slightly changed. The menu items will now have label "Paste", in the right click of the column and the cell.

Pasting into column:
![paste into column](https://user-images.githubusercontent.com/21179007/117422136-1f845c80-aed4-11eb-8cbf-5936b162214a.png)

Pasting into cell:
![paste into cell](https://user-images.githubusercontent.com/21179007/117422184-2ca14b80-aed4-11eb-816f-8338f3df576a.png)

In addition, he would like the "Paste" in the Edit menu to work for both pasting into column and pasting from selected cell and also the Ctrl + V shortcut to be enabled. @rdstern can clarify this or create a new issue on the same.
