### ISSUE TITLE
More helpful information at start-up of R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5632]
This suggestion is from a new user, Michael Clapham.

When you start R-Instat it has the message "No data loaded" on the left-hand window and a window waiting for results on the right.

Michael commented that it wasn't clear to him where he might start.  He compared with Excel that would start with a blank sheet - so does the old Instat.

Could we have a more informative message on what the user could do first?  Usually they will either use 
File > New Data Frame, or 
File > Open or 
File > Open from Library.  

Perhaps there might be a picture too?

**Comment by dannyparsons** [comment]
Something simple could be two buttons under the "No data loaded" text: 
- a browse/open from file button that goes directly to their files
- an open from library button that opens that dialog

**Comment by rdstern** [comment]
Could we have 3 buttons (or 4?) and have one for New Data Frame as well?  So
New Data Frame
Open From File
Open From Library
Recent Data Files

**Comment by dannyparsons** [comment]
From #5648 

```
Describe the solution you'd like
As well as No Data Loaded, in the data view area show options from the file menu / help menu to help people get started.

Describe alternatives you've considered
Could just link to the intro wiki?
```

**Comment by rdstern** [comment]
Now MIchael is back in Kenya, could we make progress on this item?  I am not very imaginative so remain with the idea of the buttons for the 4 options.  I can picture those, each of which would call a dialogue.  And the 4th would list recent files.  That could be a way - like Word, or being able to list quite a number.

**Comment by rdstern** [comment]
Having discussed with @dannyparsons we suggest as follows:

Perhaps in a box, at the top it says  `Load Data... ` 
Then 
```
File
> Open From File
> Open From Library
```
These are each live links.  So clicking on File above opens the File menu, while Open from File is the same as File > Open From File.  Similarly Open from Library

This should be quick and easy, so consult if it is starting to take too much time.

**Comment by dannyparsons** [comment]
We can keep the same label that's currently there and change to the text to "Load Data...". Then add 3 labels below, probably in a more normal font size, for the 3 items Roger mentioned. These three could display as links, so in blue and underlined with the mouse changing when hovered over, to indicate they are to be clicked.

**Comment by Patowhiz** [comment]
From the above comments by @rdstern and @dannyparsons , below is the sketch that I have come up with(colours not included).

![sketch](https://user-images.githubusercontent.com/21179007/95954882-b12b6000-0e04-11eb-8e83-0d809c802c1c.jpg)

However, I took time to look into other packages that have designs with contents similar to what is proposed above. I got one that could be contextualised to meet R-Instat uses. Below is a screenshot of what I think we could come up with in regards to R-Instat welcome screen.

I propose hiding the data view and output windows and having the whole screen filled with quick access menus that are discrete as shown below. (Ignore the theme and the contents).

For instance, the Start section links could be replaced with the labels proposed by @dannyparsons and @rdstern. Then the Recent section could have the file paths of files opened by the user before(similar to what we have in the file menu but in this case with the file path information). We could have a more link that opens a pop up that shows more recent files if they are there. I also think we can come up with content for the right section. I'm happy to come up with a sketch with all contents filled if you all find this as a good design.

<img width="925" alt="startup_screen_proposed" src="https://user-images.githubusercontent.com/21179007/95955796-159aef00-0e06-11eb-86b1-d2bcee6843a5.PNG">

**Comment by Patowhiz** [comment]
Will start working on this as soon as I get feedback on either of the designs. I'm happy with either.

**Comment by rdstern** [comment]
@Patowhiz many thanks for looking into this.
I prefer the welcome screen, i.e. the second layout above, rather than the sketch.

Could this just replace the left-hand (i.e. the data) window?
Within this, I like the word **_Welcome_** at the top!  Could be in the top middle of the window?

Then I would now re-instate our New Data Frame....  There is plenty of space and it is then consistent with the File menu.  So, it gives the top 3 options of the File menu just as there:

```
New Data Frame...
Open from File...
Open From Library...
```

@dannyparsons should we add Open and Tidy NetCDF File... to that list?

Then I really like the Recent files as a section and love the More button there, which opens a window for a longer list - as you demonstrated.  Disable it for now if there isn't time.

Then I do like the links to the Help pages, though they are not really ready yet.  And a link to the forthcoming videos would be great. Perhaps that could be added now, but disabled?

(The one feature we don't have, and would become a separate issue - is to be able to set a working directory.) 

I

**Comment by Patowhiz** [comment]
@rdstern yes. We could just replace the data window. But again, I'm thinking why let the **output window** be shown with the new **welcome window**? How do will the 2 relate with each other(do they complement each other? what about in future when we have a feature of changing the working space). There is a clear relationship between the **data window** and **output window**.

@rdstern what about the right section. Do you strongly feel we don't have any Customise options that we could want to expose to the user at this stage. We could have them here.

On the issue of time, I could have this ready in time for the video tutorials being made. we could disable or hide any links not usable now.

**Comment by rdstern** [comment]
My reasoning is a combination of points.
a) The result of using the new welcome screen is to add data into the left-hand window.  Unlike a spreadsheet, the results are in a separate window and that is unaffected.  
b) I am often restarting with a new data set, but continuing an analysis.  So the results window still has graphs, etc.
c) And it would be simpler to finish.  The main things of importance at the start are simply concerned with getting a set of data in.  The welcome screen doesn't need to be more dramatic.  It is sometimes not changing the flow of the analysis, just the data.  (I am repeating myself!)

**Comment by dannyparsons** [comment]
We need to keep the output window visible from start up. As well as what Roger mentions, R code is run when R-Instat starts and it would be wrong for this not to be visible by default.

I like the ideas for the left side view from VS Code, thanks for sharing that. In particular the 3 sections for "Start", "Recent" and "Help". I think we should have exactly the same. Help can have links to the Help documents. Roger could specify which ones should be there.

I would like to keep that "inside" the Data View as we have now and not replacing the Data View. As Roger says that screen is about populating the Data View and I think it's useful that's it's still displayed, mainly for simplicity for users. I could see how a separate start screen could also be sensible possibly, but with the way R-Instat currently starts up, it only makes sense to display the windows as they are. I could see a start screen that covers everything possibly being sensible, but that would need some discussion and to make sense this would need more fundamental changes to R-Instat's start up procedures, which we don't have time to go into right now.

**Comment by Patowhiz** [comment]
@rdstern @dannyparsons thank you. Sounds contextualised well enough. Will start the design now. On starting R-Instat, the Data View window will have 3 sections labelled as; Start, Recent, Help. Each sections will have links similar to what's show in the screenshot above but with content similar to what is the in the menu and as proposed in this issue.

With the new thoughts put forward, @rdstern do you still want the Welcome label (keep in mind, the Data View header label will now always be visible and when Data Book is closed the links will reappear).

**Comment by rdstern** [comment]
@Patowhiz you are right that the Welcome isn't possible as a part of the new screen each time.  If really easy then perhaps at the top, there is **_Welcome to R-Instat_** just the first time R-Instat is loaded.  But that's a luxury!

**Comment by dannyparsons** [comment]
We could try a bigger label at the top for "Welcome" or another suitable place. Might be nice but might not look good, maybe try a few different things and see.

**Comment by Patowhiz** [comment]
@rdstern here is a screenshot of the design. Please suggest the links to add in the Help section. 
The number of recent files shown by default are 5 (just like in the file menu). The "more" button lets you view more recent files.
@dannyparsons I've made the maximum viewable recent files to be 30. But only 5 can be view in the file menu as before. There is a comment in the code that suggest this should added as setting option in the options, probably we can do that in a separate PR?

@rdstern you can now test this in PR #6019

<img width="836" alt="startup_screen_1" src="https://user-images.githubusercontent.com/21179007/96114012-aef10080-0eed-11eb-88b9-b0008f3a029d.PNG">

**Comment by dannyparsons** [comment]
Looks very nice! I think there could be a "Welcome" label at the top in a slightly bigger font. But I don't mind with or without it, maybe it doesn't fit completely because this will appear when you delete all the data as well, so it's not really a "welcome" then. I let Roger decide on that.

The `...` is missing on `New Data Frame` and there shouldn't be a space before the `...`

What does the More button under recent?

In Help I think we should have a selection of things from the Help menu to start with. Newsletter would be a nice one, if we had one! We can add more later. We shouldn't have too many things that require internet and the first ones at least should be offline content.

Yes on number of recent files viewable being an option added in a separate PR.

**Comment by dannyparsons** [comment]
Also can you test what happens when you change the size of the Data View window. Fixed position would be fine, we don't really want them moving about when the window resizes.
