### ISSUE TITLE
Generate random samples from Von Mises distribution

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5638]
**Describe the bug**
Currently, we have a dialog that generates random samples following a chosen distribution. When you select Von Misses distribution in this dialog and click ok, It throws a clear error "could not find function". 

![image](https://user-images.githubusercontent.com/26301973/73132113-e1cd2e80-4016-11ea-9963-1731892c5ecf.png)
This is because the package name is missing. Since we are already using [circular ](https://cran.r-project.org/web/packages/circular/) package we should add to fix the error? There is also [Directional](https://cran.r-project.org/web/packages/Directional/index.html) package which has a similar function. I thought [stats ](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/00Index.html)package has a similar alternative but I couldn't find it.

**Comment by rdstern** [comment]
That is a good one to find.  All that is needed is to add `circular:: `to the code generated.

Then the code is for example:

`random_sample1 <- replicate(n=1, expr=circular::rvonmises(n=3177, mu=pi, kappa=0))`

**Comment by dannyparsons** [comment]
Yes that looks to be the solution, so simple to fix.
