### ISSUE TITLE
Small bug in Open from Library dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5642]
A nice feature of the Open from Library is the extra Help button that gives help on the selected dataset.  The help is inactive until you select a dataset - and that is correct.

Once you have selected a dataset and opened it, then when you return to the dialogue that dataset is no longer selected.  It remembers the package but not which dataset you selected.  You return to the top of the list for that package.

Could it also please remember the file that was selected?  That is in case you now want to check on the Help for those data you have now imported.

If that is not easy to do, then please leave that as it is and disable the Help button again, until a data file is selected.  Currently you can ask for Help without a data file being selected and it gives a nasty error suggesting you restart R-Instat!

@lloyddewit is this another one for you, or are you bored of this type of issue?

**Comment by lloyddewit** [comment]
No, I'm certainly not bored ;).

I understand the issue as follows:

- User selects `File/Open From Library ...`, 
- `Open Dataset from Library` dialog opens, `Help` is greyed-out
- User selects package and data frame
- `Help` is enabled and functions correctly
- User clicks on `OK`, dialog closes and data frame is opened
- User opens `Open Dataset from Library` dialog again
- `New Data Frame` text field shows the first data frame opened
  - It shows the first data frame opened even if other data frames were opened afterwards
- `Help` is enabled, if clicked it displays:

![image](https://user-images.githubusercontent.com/57253949/73257723-9193cf00-41c4-11ea-9faf-5e24aa123c92.png)

I understand that the required behaviour is:

- `Help` is only enabled if a data frame is shown in `New Data Frame`
- If `Help` is clicked then it shows the help for the data frame shown in `New Data Frame`
- `Help` should not display an exception message

Desirable but not essential:

- The data frame list and the `New Data Frame` text field always shows the previous data frame opened

If I misunderstood anything then please let me know, thanks.

P.S. I fly on Thursday and have some (non-IDEMS) tasks to finish first. I may not be able to analyse this issue immediately.

**Comment by dannyparsons** [comment]
That's almost correct. The help button should display the help for the dataset selected from the list.
By default that's the same as the new data frame name, but that can be changed depending on what the user wishes to call the data.
So if they select `diamonds` then change the new data frame name to `diamonds2` then clicking help should still give the help for the `diamonds` dataset.

**Comment by rdstern** [comment]
@lloyddewit you have understood perfectly.  Notice that error message gives the impression you have done something terribly wrong!
The only point to add is that R-Instat usually remembers the previous settings when you return to a dialogue.  That would be consistent here with it remembering the previously opened data frame.  If that is possible (easy I hope), then it is also correct for the help to remain enabled.

**Comment by Patowhiz** [comment]
@rdstern I think I have solved this issue

**Comment by rdstern** [comment]
So I am closing it!
