### ISSUE TITLE
Trivial edit in Prepare > Data Frame > Row Numbers/Names dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5643]
The example I have is File > Open from Library > And the EnvStats package.  The second example is called Air.df.  It opens fine, and the date column is actually in the row numbers.

This needs to be moved into the Data frame and that is exactly what the dialogue does.
The new feature is that the control where you can choose the position of the resulting variable is added here.  
The trivial change is that the text says "Copy Row Names into First Column.  Delete the word First, because that is inconsistent with choosing the variable position.

More important generally is that this is one of many examples where the main edit has been going on for ages - see #4929 or recently #5612.  This was last with @Patowhiz and is another of the examples that just seems to hang around forever.  I hope we can address this more general issue during the code sprint.  The change started in 2017 and it is now 2020 and it is still not complete - though it seems to have disappeared from the active issues?

The milestone is for this trivial change.  But can the changed user control be done also during the code sprint?

**Comment by Patowhiz** [comment]
@Ogik99  and I is on top of this.

**Comment by rdstern** [comment]
But it still remains!  I wonder if Ivan can finally resolve this.  We shouldn't have trivial items going on forever!

**Comment by Ivanluv** [comment]
The editing of  the label text from  "Copy Row Names into First Column "to "Copy Row Names into  Column " seems to be done already

**Comment by rdstern** [comment]
Great.  Let's close it!
