### ISSUE TITLE
Add broom to the Model > Use Model menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5647]
Initially this is easy, but there will then - or in parallel - be more work to do!  This needs advice from @dannyparsons and David.
broom is designed to use models in a tidy way, so I suggest it becomes the first in the tab order of the packages.
a) There are just 3 commands, namely augment, glance, tidy.  They all work trivially, i.e. initially we just put them in as they stand.  Then, for example after an lm(yield~fert) in the Model > Model dialogue, each can just be used as it stand, 
broom::augment(last_model)
broom::glance(last_model)
broom::tidy(last_model)

The results go into the output window.  That's a good start.
But each produces a tibble (data frame) object.  So the next step will be to be able to save the data frame - as an object - which we can do - and then be able to see it in the grid as a tabble (data frame!)
The augment could hopefully be a separate data frame, or add variables to the data frame that produced the model - that's what broom is designed to do.

At the same time there are some minor edits to the Use Model dialogue:
a) It is too wide and that looks messy.  Let's make narrower.
b) It is too short, so the last row is cut off.  Make it a bit longer.
c) More difficult - the Help on General doesn't work - no package called General!  This is a bit more complicated, because there are multiple packages used here.  I am not sure what to do here - it needs a bit of discussion, partly because it should be done quickly!

**Comment by rdstern** [comment]
This is now changed after discussion with @volloholic into 3 dialogues with one for each verb in broom.
They are **_Glance, Tidy, Augment_** in that order.
The Model menu is also changed into the following:
Probability Distributions
----------------------
Fit Model
Compare Models
Use Models
--------------------
Hypothesis Tests...

**_Now within Fit Model_**
One Variable...
Two Variables...
Three Variables...
Four Variables...
----------------
General...
----------------
Model Keyboard...

**_Within Compare Models_**
One Variable...

**_Within Use Models_**
One Variable...
Two Models....
---------------
Glance...
Tidy...
Augment...
----------------
Use Model Keyboard...

Initially the new dialogues from broom are the same as follows:
1. **_Name_** is Glance, or Tidy or Augment
2. Usual data selector just showing Models for the chosen data frame.
3. Multiple Receiver.  Label could be Models
4. Check box with label Display in Output
5. Check box with label New Data Frame Name  and a field for the name.
6. Usual 5 keys at the bottom.

**Comment by Wycklife** [comment]
@rdstern On the model menu, there are some disabled items, should I do away with them?

**Comment by Wycklife** [comment]
@dannyparsons @Patowhiz 
clsGlance.AddParameter("x", clsRFunctionParameter:=ucrModelSelector.ucrAvailableDataFrames.clsCurrDataFrame) How do I set the same for the receiver? I want the function to get whatever is on the receiver and not the selector.
