### ISSUE TITLE
Show data load options instead of just No Data Loaded

### ISSUE THREAD

**Issue by michaelclapham** [africanmathsinitiative/R-Instat#5648]
**Is your feature request related to a problem? Please describe.**
When you open R-Instat for the first time you see No Data Loaded but nothing obvious about how to get Data Loaded.

**Describe the solution you'd like**
As well as No Data Loaded, in the data view area show options from the file menu / help menu to help people get started.

**Describe alternatives you've considered**
Could just link to the intro wiki?

**Comment by dannyparsons** [comment]
duplicate of #5632
