### ISSUE TITLE
New hydroGOF keyboard in the calculator

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5663]
This is a keyboard to compare two numeric variables.  The functions are all taken from the hydroGOF package.  
There are 21 keys, so perhaps 3 across and 7 rows:
1) br2, cp, d
2) KGE,mae,md
3) me, mNSE, mse
4) nrmse, NSE, pbias
5) pbiasfde, rd, rmse
6) rNSE, rPearson, rSD
7) rsr, ssq, VE

Note - give them with the parameters as for the cor function, e.g. hydroGOF::br2(sim=, obs=)
Note - for pbiadfde include plot=FALSE.

Great if the help on this keyboard could link to the R package.

**Comment by Wycklife** [comment]
@rdstern The first key in row number 5 does not exist, I think it should be pbiasfdc. Kindly check if that is true.

**Comment by rdstern** [comment]
Yes you are right.  It should be pbiasfdc.  Good spot.
