### ISSUE TITLE
Remaining points in the save column position

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5682]
David wrote as follows about the Position button:

@Patowhiz This is generally good. The size issue for the button is not to do with your resolution it is because the button is being autosized this is what leads to the funny heights. Given the other components are not being autosized i suggest you could turn this off then get the alignment right with respect to the height of the visible height of the textbox and combobox.
@maxwellfundi once the sizing problem is resolved this can now be merged @rdstern and I have checked and are we can then move on with the implementation.

I hope this can be fixed.  The merged version still has the problem with the regular sequence dialogue - I think you are looking at that?

**Comment by Patowhiz** [comment]
@rdstern I think this can now be closed. The alignment and size issue was solved elsewhere.

**Comment by rdstern** [comment]
Agreed
