### ISSUE TITLE
Climatic summaries does not cope with multiple stations

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5698]
**Describe the bug**
Runs fine, but ignores the Station in the calculation

**To Reproduce**

1. Open from library Guinee > rds file for 2 stations.
2. Check file in Define Climatic Data
3. Now use climatic summaries for rainfall.  Total rainfall for the year is ok.
4. This should give a summary including the Station.  It doesn't! 

**Expected behaviour**
A summary with the Station as the first variable. Instead just:
![image](https://user-images.githubusercontent.com/11226469/74399526-0563e780-4e13-11ea-9d8c-8b2e4927afa1.png)

**R script or commands**
```
# Code generated by the dialog, Climatic Summary
day_filter <- instat_calculation$new(type="filter", function_exp="doy_366 >= 1 & doy_366 <= 366", calculated_from=calc_from_convert(x=list(guinea_2="doy_366")))
data_book$calculate_summary(columns_to_summarise="rain", data_name="guinea_2", factors=c("year"), additional_filter=day_filter, na.rm=TRUE, summaries=c("summary_count_non_missing", "summary_sum"), silent=TRUE
```)

**Comment by Ivanluv** [comment]
@Patowhiz  can I look into this

**Comment by rdstern** [comment]
@Ivanluv that would be great.  Should be very simple.  In the code above if you change:
`factors=c("year")`
into 
`factors=c("station","year") `

For the variable named station, then it works fine.  So that was just omitted.

Thanks

Roger

**Comment by Patowhiz** [comment]
In addition, the form title name is set as "Column Statistics", can you change this to read "Column Summaries".

**Comment by rdstern** [comment]
@maxwell I think this is done and can be closed?

**Comment by rdstern** [comment]
@maxwellfundi I think this is done and can be closed?

**Comment by dannyparsons** [comment]
Seems to be working correctly now.
