### ISSUE TITLE
Minor bugs/features to fix in Open from file dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5700]
The import dialog has several bugs/features that need to be fixed and added. 

- [x] 1. The data frame name textbox needs to be pushed down to be consistent with the other dialogs. The textbox also needs to be resized, currently it's very small.

- [ ] 2. Can we have the option to enter more than 1 missing value representation.

- [x] 3. When importing from file. The maximum rows to skip is currently set as 100. This limits the user, we have found files that require us to skip more than 100 rows. The 100 limit needs to be removed.

- [ ]  4. When importing from excel, the selected sheet changes when I reopen the dialog, can the dialog be made to retain the selected sheet?

<img width="554" alt="1" src="https://user-images.githubusercontent.com/11226469/74430761-74fac680-4e55-11ea-8828-a6f4ec496f92.PNG">

**Comment by rdstern** [comment]
@Ivanluv can you can quickly fix this?

**Comment by Ivanluv** [comment]
I cant try

**Comment by Ivanluv** [comment]
@rdstern  is the  data frame name textbox  to be pushed down after the `New Daataframe Name` label?

**Comment by rdstern** [comment]
It's to be put down near the base buttons just like the way it's been done in the new data frame dialog

**Comment by rdstern** [comment]
In addition, there is another bug we just found. When importing from csv files, the ones that have 2 dots e.g myfile.csv.csv, there is an error thrown. I suspect that this error is due to R not allowing names with dots. This can be fixed by showing to the user an understandable error message or R-Instant can try to rename the data frame name. The same occurs even for the sheet names. Test with file below.

**Comment by Patowhiz** [comment]
In addition, the sheet names sometimes are also named with spaces in between. e.g "Max Copy"

**Comment by Ivanluv** [comment]
@Patowhiz  am not sure on how to go around the  fourth  suggestion on e  retaining  the selected sheets when when importing excel sheets on reopen.Could you help me on this

**Comment by rdstern** [comment]
@Ivanluv and @dannyparsons just to clarify that the discussion above is promarily by @Patowhiz using my machine during the ICPAC workshop.  Of course I would not put so may issues into one message!
As they are all here I report on the issues that we encountered during the workshop.  The open dialogue is really good, but it was stretched to the limit during the workshop.  
1) A data file from Uganda had data from multiple stations, with the first (about) 700 rows for 2 stations.  Then a third station for about 200 rows with a different layout.  So we wanted to skip the first 700 rows and start input for 200 rows (there was a 4th station with yet another layout beneath.  The reading of 200 rows works well.  This is where the limit of skip 100 rows limit was a problem.  It was easy to change in the script file.  I believe that change has been fixed, but there are build errors in the pull request.
2) An increasingly common problem is caused by the fact that Excel **_sheet names_** can have a space in them.  So they are illegal names in R.  We don't cope with illegal names here yet.  I think we make file names legal already, but not the sheet names (which become the data frame names after importing).
3. When importing multiple Excel sheets, when the content is different, there is (sometimes) a problem.  In the workshop with the climatic guide data sets some participants imported both the first sheet and also dodoma.  When you do this, then dodoma does not import the temperature or sunshine correctly.  They are logical variables only.  I think this is because the first (many) rows are missing, so the importing assumes all are missing.  I hope there is a setting that can be changed on the importing command - but I couldn't find it.  I hope that @volloholic can help.
4. The other issues mentioned above are less urgent.  I think the multiple missing values is discussed in another issue.

**Comment by Patowhiz** [comment]
@Ivanluv what's the status of this. I'm happy to look at it

**Comment by Patowhiz** [comment]
@rdstern is it necessary to do multiple values for other file types apart from excel? I've already done for excel file types but I haven't checked if the current R commands (the ones we are using) for other file types  can support multiple missing values

**Comment by Patowhiz** [comment]
@rdstern on your comment in issue #5407, you say

> 2. There are occasions when I would like multiple strings (or numbers) to be changed to missing. The example I had recently was when "-" and "--" and "----" were all possible missing value codes.
> I was able to do this from the script, by choosing one of the above and then changing to c("-","--","----") in the script. I assume I could have c("-","--","----",-9999, -99) if it were a mixture.
> Could we have a combo box instead of the text field. It is the same as now when there is a single value, but the pull-down would give some examples. Then the code adds the c( ) round it? When there are multiple, i.e. there is a comma, then the user must type the quotes. They remain optional for a single string.

Won't the commas only do the job. I thought it will be just easy to have the user separate the missing values representations with just a comma like in the photo below.

![import](https://user-images.githubusercontent.com/21179007/75224269-3e0fa380-57b9-11ea-95e8-4fa3a45dd44e.JPG)

**Comment by rdstern** [comment]
That could work.  But it is a bit complicated - I think - if the missing values are a mixture of strings and numeric. Then the novice user must now type the quotes for the texts.  Currently you don't need the quotes.  I could have Roger or -9 as missing and just type.  I don't want to lose that.

We looked for a possible solution when we discussed before, but can't find it now.  Would it be much harder to keep the current missing value code in that control as we have it now.  Then, underneath there is a checkbox "Multiple Missing Values".  Default is unchecked.  If checked then it opens a second box.  There a single value would be as the first, i.e. no quotes needed if text.  You just type it.  
We reason that it is rare that you will need more than 2 different values.  But, if you do, then the second field is as you have this one - so you could have multiple values there.
What do you think?

**Comment by Patowhiz** [comment]
@rdstern in the dialog, the user doesn't need to type any quotes. The user just types in the missing value. If it's more than one then the user just separates them with a comma. Whether it's a mixture of strings and numbers the user will never have to type in quotes.  I was just responding to your quoted comment to illustrate how I did it differently.

As you can see from the photo above. I just typed in . 
-999.9,101010

The only thing added there was a comma. The dialog will detect this accordingly. What do you think about this?

 My only worry is can ever have missing values that contain commas in themselves?

**Comment by rdstern** [comment]
So I could type -999.9,na,NA,101010?  I would not need to put -999.9,"na","NA",101010?

If I don't need the quotes round texts, then I am happy with your solution.

**Comment by Patowhiz** [comment]
Yes, now you get my point. I'm implementing this for excel sheets only for now.

**Comment by Patowhiz** [comment]
Yes, and you can type as many missing value types as you want as long as they don't have commas in them.

**Comment by Patowhiz** [comment]
@rdstern I've also implemented importing of multiple missing values even for the CSV files. But I must mention that input of 0 as missing value for CSV files will not be supported (Because the rio package uses fread command which recognises 0 as a boolean).

Running the following code in Rstudio
`Sheet2 <- rio::import(file="E:/ICPAC WORKSHOP/VoiMet.csv_1.csv", stringsAsFactors=TRUE, skip=1, na.strings=c("-999","0"))`

Gives me the following error

```
Error in fread(dec = ".", skip = 1, na.strings = c("-999", "0"), input = "E:/ICPAC WORKSHOP/VoiMet.csv_1.csv",  : 
  freadMain: NAstring <<0>> is recognized as type boolean, this is not permitted.
```
So this error will be caught by R-Instat and the user will have to omit the zero as a missing value.
 
I also must mention the **0** as a missing value does not affect the excel import command and it runs fine as a missing value. So the code below will just run fine.

`Sheet2 <- rio::import(file="C:/Users/PatoWhiz/Downloads/Climatic.Data.Sadore.1983.to.2014.xlsx", guess_max=Inf, which=2, na=c("Janvier","0"))`
