### ISSUE TITLE
Duplicate Column resizing

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#5711]
This dialog needs resizing properly

**Comment by Patowhiz** [comment]
I'm pasting @rdstern suggestion here, to be part of the discussions

> I have looked again at this dialogue - and would like it to be merged.
> @Patowhiz I would still like some trivial edits. But if ytou want discussion, then @maxwellfundi please let's merge first and discuss afterwards!
> 
> a) The checkbox says (from numeric). I don't understand that? Should it be (for numeric). Then I think the up-down could be a bit smaller, though perhaps it is that size, because it is a user control. And then the dialogue could be slightly less wide.
> 
> And there is a big gap below this control. Could that gap be smaller?
> 
> But only if it can be merged to get into the next version. Otherwise please ignore the comment and just merge. The discussion above started in May 2018. Let's conclude it soon!

**Comment by maxwellfundi** [comment]
Thank you @Patowhiz

**Comment by Wycklife** [comment]
@maxwellfundi My machine seems to be having a problem mostly when I work on the designer.

**Comment by Patowhiz** [comment]
@Wycklife what's the specific problem?
@Wycklife if you are using Visual Studio 2019, you can change the scale to 100% instead of 150%. That's how I'm able to make changes to the designer without major problems

**Comment by Wycklife** [comment]
@Patowhiz I am currently using 2017. But this has helped resolve the problem. thank you.
Now I can work on this.

**Comment by Wycklife** [comment]
![image](https://user-images.githubusercontent.com/33898404/74930790-5feedc00-53ef-11ea-8d4c-08e0debc393b.png)

 @rdstern  @maxwellfundi  @Patowhiz  I have made some changes on the designer and this is how it is now. Is it okay with you?

**Comment by rdstern** [comment]
I like the dimensions of the dialogue more now.  In the example it is odd, however, to have those factor options when you are changing to numeric?

**Comment by Wycklife** [comment]
@rdstern Should I just leave the dialog as it was before? Or I just carry on with the changes?

**Comment by dannyparsons** [comment]
Is there a pull request related to this to view?

**Comment by Patowhiz** [comment]
My main concern here is the flow of the dialog from the user perspective. Users are already finding it difficult to move from left to right then right to left when using selectors and receivers. Putting the factor options below the selector makes it feel like it's not related to the other options in someway. My suggestion is to have it maintained below the other options.

**Comment by rdstern** [comment]
I have recently been using the new dialogue and can easily live with the current layout.  So, given @Patowhiz comments I'll close this issue
