### ISSUE TITLE
Add a simple keyboard to the filter sub-dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5731]
The need for this should be checked by @dannyparsons.  
We have made some small improvements to the filter sub-dialogue.
It now is different for factors, dates and logical variables.
For numeric variables I suggest we add the same simple keyboard as for the calculator now.  
We need most of the numeric keys, and it does work with simple calculations, e.g. val > (3*2) so it does no harm to have exactly the same calculator.  I hope that might be very simple to add?

And, while on this dialogue, when a factor is selected in the filter, the dialogue gives a choice of levels to select.  Initially the first one is selected - and that is a pain.  So could no levels be selected initially.

**Comment by dannyparsons** [comment]
Happy for this to be added if we feel its useful for some users.

**Comment by Patowhiz** [comment]
I'm struggling to understand how this could be useful to users

**Comment by rdstern** [comment]
Simply for the same reason as in the calculator itself.  If the condition is` year > 1970` then you can use the keyboard instead of typing the numbers 1970.  I notice many of our users do use the keyboard, rather than typing the numbers from their machine.  Just continuing to make it easy!

**Comment by Patowhiz** [comment]
Okay

**Comment by Wycklife** [comment]
@Patowhiz How do I set at cursor position for the combobox instead of a receiver? i.e 
Private Sub cmd7_Click(sender As Object, e As EventArgs) Handles cmd7.Click
        ucrLogicalCombobox.AddToReceiverAtCursorPosition("7")
    End Sub

**Comment by Patowhiz** [comment]
Just check on the AddToReceiverAtCursorPosition() subroutine. Are you using the custom control combobox? In that case I'm not sure if it's the same subroutine is implemented, if not, we may have to implement it at that level to be consistent with how the receivers are implemented.
