### ISSUE TITLE
Issue multiline commands in script window?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5742]
Currently R-Instat commands in the script window are sent to R each line at a time.  I often have to collect lines from simple files for this.  Here is an example:

```
# generate artificial data
set.seed(4321)
x <- 1:100
y <- (x + x^2 + x^3) + rnorm(length(x), mean = 0, sd = mean(x^3) / 4)
my.data <- data.frame(x = x, y = y,
group = c("A", "B"),
y2 = y * c(0.5,2),
w = sqrt(x))

# give a name to a formula
formula <- y ~ poly(x, 3, raw = TRUE)
# no weights
ggplot2::ggplot(my.data, aes(x, y)) +
geom_point() +
geom_smooth(method = "lm", formula = formula) +
ggpmisc::stat_poly_eq(formula = formula, parse = TRUE)
```
This works fine as long as I combine the 4 lines from my.data into a single line and then also the 4 lines for the ggplot2 graph.
I often find a very long line for a ggplot2 command and it would be highly convenient and more readable if they could be split over multiple lines.

Would it be possible for certain ends of line to be recognised as only part of a command.  The 2 above are the most obvious, i.e. + and comma.  It would also be good to be able to define a function and so detecting when { is open and waiting for the closure would also be good.

Might that be all?  Perhaps @dannyparsons can comment?  equals is another possibility.  I am not keen on checking on whether the brackets match, because there can often be mistakes there and so I would prefer that be checked on a single line.

**Comment by Patowhiz** [comment]
For such a change, I suggest using another control for this. Cause this is like building a code editing tool for R. There are open source controls that can help with this.

**Comment by rdstern** [comment]
I had hoped this might be a simple thing to implement.  Are you wanting another control, because this will be complicated to do, or because a new control would also "open the door" to other improvements too?

Let me explain why this change itself would be useful.  I have 3 instances - 2 on tweaking and the third on copying examples of code over from the R packages.
a) The example I gave above is typical of code I try out as an example from a package.  If just + and comma were detected, this would run like that, instead of having to collect the multiple lines together.
b) In my tweaking of a dialogue code, I find it is often for a ggplot2 command.  They easily get pretty long.  They would be much clearer if I could split them into multiple lines and then edit slightly.  Currently I am having to scroll sideways a lot.
c) the same applies to the climatic commands that use our calculation "system".  They are really complicated and would be much clearer to examine and edit if they could be split over multiple lines.

So my request to also check on a function, i.e. an occurrence of { until it closes was the "icing on the cake".  I'd be happy if the code could just detect + and , at the end of lines.  I hoped that might be a simple change to implement within the current system?

**Comment by dannyparsons** [comment]
The symbols we would want to check for initially are: `+` `,` and `%>%`

**Comment by Patowhiz** [comment]
@rdstern yes, I wanted to use a better control that can improve our current code editing and include things syntax error highlighting. 

But for now I'll  just add the above basic features using the current textbox control

**Comment by lloyddewit** [comment]
PR 5769 adds functionality that if a script line ends with '+', ',', or '%>%', then the command may continue onto the next line. This allows commands to be split over multiple lines for readability.

PR 5769 does not add the optional enhancement to allow multi-line functions (enclosed with '{' and '}') to be executed in the script window. 

PR 5769 supercedes PR 5755, so PR 5755 can be closed.

@rdstern please could you test? If you would also like me to implement functionality for multi-line functions then please let me know, thanks.

**Comment by rdstern** [comment]
Exciting.  I'll check after the lecture.

**Comment by shadrackkibet** [comment]
I wonder if it is necessary to have line numbers in the script window.  Might be useful when explaining some code to the users. I hope by doing this we are not re-writing Rstudio!

**Comment by Patowhiz** [comment]
@lloyddewit just a minor mention and probably you know this, for easier access to the pull request links or any other github links you can append a hash just before the number e.g PR #5769.

This also adds an extra functionality from github where as a team we can track what was mentioned where and possibly understand how the 2 are related to each other in future.

**Comment by lloyddewit** [comment]
> @lloyddewit just a minor mention and probably you know this, for easier access to the pull request links or any other github links you can append a hash just before the number e.g PR #5769.

@Patowhiz yes, thanks for the reminder. When I first wrote the comment I tried to do this but it seemed to link to an issue rather than a PR. I edited the comment and it now correctly references the PR. Not sure what I did wrong before.

@rdstern what do you think of @shadrackkibet 's suggestion to have line numbers? I assume that Shadrack is correct and we're not aiming to emulate RStudio's command line interpreter? If we keep adding features to the script window then it may be worth seeing if we can integrate RStudio in some way. The RStudio source code is public. They may also have an API we could use.

**Comment by rdstern** [comment]
@lloyddewit you may hit a nerve with @dannyparsons and/or @volloholic with any suggestion of making the command line interpreter to be like RStudio.  Of course I would like it, because I am quite comfortable in the R-Instat environment, but they keep telling me that I am the lone exception in the world - probably my age they say!

One direction that David is very keen on is that from an R-command you could populate and then open the appropriate dialogue.  I think (hope) that is within the second phase.

I would be quite happy to have the option of line numbers.  The next 2 items for me are to be able to easily add the code to get data (at the start of the script) from an open data frame.  Then also to be able to add results e.g. models, back into the data frame.   That happens automatically if you prepare a dialogue and then press To Script.  But could we make it easy with a separate bit of R-code.  

One solution - already - is simply to choose the appropriate dialogue.  Perhaps we could add a new dialogue at the bottom of R-Objects called "To script".  It could have 2 parts.  The first part is to Select Data frame (or variables)
The second part would be to save results back to the data frame.
It lacks the OK button, but does have the To Script button!

I'll perhaps discuss with Danny.

**Comment by lloyddewit** [comment]
@rdstern maybe it's a compliment to be unique in the world ;)

If you feel that the line numbers and other features are a relative high priority (compared to the the other open issues) then I'd be happy to work on them, please let me know.

**Comment by rdstern** [comment]
@lloyddewit particularly asked me to see whether functions can now be run line-by-line.  I have started from the R for data science book - by Hadley Wickham - of course!  I claim that our first course is sort of teaching data science - except for programming as of now!

His chapter 19 is on functions and the first one is as follows:

```
rescale01 <- function(x) {
  rng <- range(x, na.rm = TRUE)
  (x - rng[1]) / (rng[2] - rng[1])
}
rescale01(c(0, 5, 10))
```
This works fine - wow!  It works when run all together, but I was delighted that it also works when running line-by-line.  
I am really happy so far!
