### ISSUE TITLE
Inventory plot - Date receiver

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5746]
The date receiver on the inventory plot dialog allows any type of variable. It only works with Date columns. It should only allow Date type columns.

**Comment by Ivanluv** [comment]
@dannyparsons  this seems to be working correctly from my end

**Comment by dannyparsons** [comment]
You mean the current version already works in this way?

**Comment by Ivanluv** [comment]
No, sorry.End of rains and start of rains dialogues also seem to have the same issue
