### ISSUE TITLE
More changes in the Model menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5758]
The current Model menu looks like this:
![image](https://user-images.githubusercontent.com/11226469/76141759-3c6a9900-605f-11ea-853b-42eeba23369f.png)

I suggest:
a) This gives too much importance to the Hypothesis tests.  It is reasonable for them to be (instead) within the Fit Model section, because accepting a null hypothesis usually implies that a simpler model is ok.  So I propose that the current Fit Model sub-menu - currently like this:
![image](https://user-images.githubusercontent.com/11226469/76141831-c286df80-605f-11ea-984b-f9103da92159.png)
Should instead move Hypothesis Tests... to below the line, i.e. just above "Model Keyboard".  I further suggest it be called **_"Hypothesis Tests Keyboard..."_**
b) The Model Keyboard... becomes **_"Fit Model Keyboard..."_**
c) See below for the reasoning to also add a new "section above the keyboards with **_Augment Data..._**.  (This moves the broom augment dialogue from Use Model to Fit Model..)

d) I further suggest that the Glance and Tidy dialogues (from broom) are more appropriate in the Compare Models section.  So, there is a line, in the Compare Models section and then Glance and Tidy move there.  I remind you that glance gives a single row for each model.  So it is at the model level.  Tidy gives a row for each parameter of each model - so it is at the parameter level.  

So, they are not Use Model.  Broom works for a single model only - so that would be more appropriate at the Fit Model level.  But we are extending it to provide information (multiple receivers).  So it becomes useful at the compare models menu?

e) The broom **_augment_** dialogue is still at the data level.  This is for a single model and should therefore 1) Have only a single receiver, 2) Be at the Fit Model level and 3) Needs to allow the user to choose what to add to the data.
So, for the menu, I suggest (for now) that it should move to its own little section just above the Fit Model Keyboard...  And it should probably be **_Augment Data..._**? 
f) While changing this menu I suggest we hide (rather than disable) the 4 entries that start with Other. and are currently at the bottom of the Model menu.

**Comment by dannyparsons** [comment]
For reference, `purrr::map_df` can be used to run `broom` commands on multiple models. This will need some thought about implementation because they produce data frames in "long" format with an extra column for "model". So e.g. for `broom::augment` we no longer get something that's the length of the data frame with multiple models. Example below.

```r
library(broom)
library(purrr)

lmfit <- lm(mpg ~ wt, mtcars)
lmfit2 <- lm(mpg ~ hp, mtcars)
models <- list(lmfit, lmfit2)
purrr::map_df(models, broom::augment, .id = "model")
```

**Comment by rdstern** [comment]
Looks purrrfect for the job of multiple models going into a new data frame.  You use augment above, while I thought it would be tidy or glance?
It is also clear that purrr should be important for us.  A "test" is the number of other packages that make use of it.  And lots use purrr!

**Comment by dannyparsons** [comment]
It can be used with any of the `broom` functions. `augment` is the most problematic, because of the length. It works in exactly the same way for the others.

**Comment by rdstern** [comment]
Agreed, but for now at least, we now have just a single receiver for **broom augment**.  And it therefore writes back (usually) into the existing data dataframe - hence the word augment.

It is for **_glance_** and **_tidy_** that broom is for a single model only.  In r-instat we would like these dialogues to be for **_multiple models_**.  Hence great to consider using purrr for the r-code for these 2 dialogues.
