### ISSUE TITLE
Problem with running a single line in the script window

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5759]
Please could you check the action of the script window when you run line by line.

I feel it used to work, but am having problems with it in Version 6.1.  I think it may work initially and perhaps doesn't clear.  I was running the following code, but I think the problem is general and should therefore be easy to fix.
Here is a sample of code:
```
data(PORTw,package="extRemes")
# Gumbel
fit0 <-extRemes:: fevd(TMX1, PORTw, type="Gumbel", units="deg C")

plot(fit0)
```
I think the issue is the same whether I right-click or use ctrl-Enter.  It works fine when I mark a single line and run the selection and I expect the same when running just that line.

**Comment by lloyddewit** [comment]
@rdstern I could not recreate this bug with today's africanmathsinitiative:master branch. Please could you check if the bug still exists? thanks

**Comment by Patowhiz** [comment]
Running of single line works fine on my side too. Probably this was solved in the last commit that touched the running of scripts.

**Comment by lloyddewit** [comment]
@Patowhiz Thanks for testing.
@rdstern Please could you close this issue?

**Comment by rdstern** [comment]
Very happy to close this!
