### ISSUE TITLE
Display of numeric data in R-Instat grid - possibly scientific?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5782]
Here is an example of the display of data currently:
![image](https://user-images.githubusercontent.com/11226469/79838695-4b0cd580-83ab-11ea-90a7-8367e4ba7776.png)

The last variable (p-values) is my concern.  I have set the number of significant figures to 1, but that doesn't help.  (Setting to zero gives either 0 or 1.)  This is going to be a typical display for p-values, where some may be very small, while others are close to 1. 

The metadata allows for scientific, but that option is not active and I don't know if it is allowed in reogrid.
Another option - for us, would be to be able to choose decimals?
Is anything possible easily?

**Comment by shadrackkibet** [comment]
An easy solution to this is to add an option to convert this column to scientific in convert columns dialog , on right-click and by enabling edit of Scientific column in column metadata. Which means we have to check what the user will type into the cell. In that case, we will only allow two options "TRUE/T" or "FALSE/F".
