### ISSUE TITLE
Rename, delete and reorder filters, like graphs and models

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5792]
When a graph, or model, is produced it can be managed using Prepare > R Objects, then View, Rename, Reorder or Delete, see below:
![image](https://user-images.githubusercontent.com/11226469/82137787-0726b800-9813-11ea-92ab-cd7ad720bda2.png)

When filters are produced they are similar objects (to graphs and models) in that they are added to the metadata in the corresponding data sheet.  Hence, when you use File > Save As with the data book, and return later, they are all still available.  However, they cannot be managed.  They don't appear in the dialogues in the R Objects menu, so they cannot be renamed, reordered or deleted.

I suggest this is a @shadrackkibet task  with discussions from @volloholic and possible support from @lloyddewit .  Understanding how this works will be useful generally, so I suggest that @Ivanluv and @Wycklife also follow the initial discussions.  If either can take over some of the work, then that's fine.

**Comment by shadrackkibet** [comment]
Work on this is now done and merged. This can be closed.

**Comment by shadrackkibet** [comment]
@rdstern @maxwellfundi ?

**Comment by shadrackkibet** [comment]
@rdstern I just want to check before I proceed with this task. I thought Renaming of filters was the only task to be done here. Do we need to be able to delete and also reorder filters?

**Comment by rdstern** [comment]
@shadrackkibet yes I thought so.  Otherwise will there be a different way to delete the filters?

**Comment by shadrackkibet** [comment]
Apart from the dialog,  I thought of enabling the user to delete from right click in the selector. This should not only apply to filters, we might want to allow for other objects as well.
