### ISSUE TITLE
Cumulative/Exceedance graph dialog

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5799]
**Describe the bug**
This is a designer question. Is there any reason why the top radio button design look like this? This is not consistent with what we have for top radio buttons. 

There is also an issue with the controls at the bottom, clearly, they are not aligned properly, labels, size, the distance between controls etc

![image](https://user-images.githubusercontent.com/26301973/82787016-4c2f9780-9e6e-11ea-8e16-2710c23fee9d.png)

**Comment by shadrackkibet** [comment]
I would like to reopen this but I can't since I don't have rights to reopen! @rdstern @lloyddewit, please reopen.

@Ivanluv The dialog design is not great. I should have checked this by pulling your branch, that was my fault I didn't review properly! Perhaps @lilyclements can help to sort out this.

1)The radio buttons at the top still overlap. Try moving from one radio button to another to see it.
2)Scale by Combobox and in step of numeric up-down would are not aligned properly! It will be nice to align them with the receivers at the top.
3)Save label is far from the save control.

![image](https://user-images.githubusercontent.com/26301973/87159280-c48cd380-c2c9-11ea-98d4-46d28804334e.png)

**Comment by lilyclements** [comment]
Happy to do this. In the case of Save Graph, this seems to be a larger issue on the whole (see #5866) however there is a way around it in the dialog code.

**Comment by lloyddewit** [comment]
@shadrackkibet I opened the issue again as you requested
