### ISSUE TITLE
Bar chart dialog

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5801]
This is a designer issue: When you change to the column on the Y value Combobox the focus receiver should change.

The Y variable receiver is not well aligned, below there is a control that is visible. See below.

The position label is misplaced see below screenshot.

![image](https://user-images.githubusercontent.com/26301973/82790200-610f2980-9e74-11ea-9da8-e983921698da.png)

![image](https://user-images.githubusercontent.com/26301973/82790635-0d511000-9e75-11ea-84ec-c8ed5ddcaf78.png)

**Comment by rdstern** [comment]
@shadrack, thank you for reminding me.  This is the same as I have raised except you also have the additional point "When you change to the column on the Y value Combobox the focus receiver should change." 

I don't quite understand this point. 

This is a small topic - so perhaps Ivan could discuss with you and quickly undertake both issues together.  I hope it will just be a few minutes of his time.

**Comment by shadrackkibet** [comment]
By focus, I mean the turquoise colour should be on the receiver (Y variable).

**Comment by Ivanluv** [comment]
This seems to be  solved already
