### ISSUE TITLE
Allow '=' to be used instead of '<-' in the script window

### ISSUE THREAD

**Issue by lloyddewit** [africanmathsinitiative/R-Instat#5807]
**Describe the bug**
R-Instat throws an error if a variable is assigned with '='. This is allowed in RStudio and should be allowed in R-Instat also.

**To Reproduce**
Steps to reproduce the behaviour:
1. In R-Instat, select 'View/Script Window' 
2. In the script window type 'Input = ("Hello")'
3. Execute the line (e.g. by ctrl-enter)
4. R-Instat will generate an error:
![image](https://user-images.githubusercontent.com/57253949/83024051-0de0d680-a02e-11ea-9104-53709fbb7435.png)

**Expected behaviour**
In the script window enter:
```
Input = ("Hello")
Input
```
The output window should display:
```
# Code run from Script Window
Input = ("Hello")
Input
[1] "Hello"
```

**Comment by shadrackkibet** [comment]
Thanks, @lloyddewit for bringing up this discussion. My understanding is that `<-` and `=` as the assignment operators are different in R. Although in our structures and the script window I tend to believe you are correct we should allow this. There are other assignments operators which are allowed in R and this is discussed [here](https://stackoverflow.com/questions/1741820/what-are-the-differences-between-and-assignment-operators-in-r) so I think going forward we should also allow `<<-` and other forward alternatives `->` and `->>` .

**Note: An operator can be used like a function in R**.

**Comment by lloyddewit** [comment]
I tried to recreate this bug. The script window now allows the user to assign using `=`. If I follow the test case above, then I still get an error. But I don't think this is a problem. The [R language reference](https://cran.r-project.org/doc/manuals/r-release/R-lang.html) states:
>the ‘=’ sign is used for tagging arguments in function calls and for assigning default values in function definitions

The [R manual](https://stat.ethz.ch/R-manual/R-devel/library/base/html/assignOps.html) states:
> The operators <- and = assign into the environment in which they are evaluated. The operator <- can be used anywhere, whereas the operator = is only allowed at the top level (e.g., in the complete expression typed at the command prompt) or as one of the subexpressions in a braced list of expressions.

In other words the `Input` object only exists in the statement's environment. No object called `Input` is added to the global R environment so R-Instat is correct to raise an error.

Notice the difference between `tmp1` and `tmp2` below. The `<-` assignment does add an object `tmp1` to the R environment. The `=` assigment does not.

Therefore, I think R-Instat's behaviour is valid and I will close this issue.

@lilyclements @Patowhiz If you think this is incorrect, then we can reopen. Thanks


![image](https://user-images.githubusercontent.com/57253949/197385698-3e01cae8-ce29-4a20-8e94-879bb0b4029e.png)

![image](https://user-images.githubusercontent.com/57253949/197385501-b6aa041c-0476-48bd-bb21-54346b20ffad.png)
