### ISSUE TITLE
Enable 2nd button in Model > Fit Model > One Variable

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5810]
This will start by including the t-test, binomial test and proportions from the Mosaic package. They generalise the same functions in the stats package.  
Here is the existing dialogue:
![image](https://user-images.githubusercontent.com/11226469/83309760-0e31cb00-a202-11ea-8444-84282fe00b63.png)

In this dialogue:
a) We change the second button from "Exact Solution" to just say "Test", and add a third button with the label "Estimate".
b) When the second button is active the label with the pull-down changes to **_Test:_**.  It is Estimate: with the third button.
c) Similarly, the Save Model label becomes **_Save Test_** and **_Save Estimate_**.  The field to save the name can move right slightly, so it remains in the same position for all options - and there is enough room for the Save Estimate label.
d) Similarly the default object names are **_test1_** and **_ci1_**, respectively rather than dist1.
e) Similarly the **_Display Options_** and **_Fitting Options_** buttons are hidden.

Now: with the second button, **_now labelled Test_**.  The pull-down menu (which is there and labelled Dist above) has the following tests (at least for now)
1)  **_binomial_** (calls mosaic::binom.test)
2) **proportion**  (calls mosaic:prop.test)
3) **_sign_** (probably calls DescTools::SignTest) 
4) **_t_** (calls mosaic::t.test)
5) Wilcoxon (calls wilcoxon.test)
6) **_Z_** (calls DescTools::ZTest)
### Now some tests for whether the data can be taken as a random sample:
**_A separator first_**.  Then
1) **_Bartel_** (calls DescTools::BartelsRankTest with tooltip: Bartels Rank Test of Randomness)
2) **_br_** (Calls trend::br.test, with tooltip: Buishand Range Test for Change-Point Detection
3) **_runs_** (calls DescTools::RunsTest)
4) **_Sen_** (calls:trend::sens.slope with tooltip: Sen’s slope for linear rate of change) 
4) **_serial corr_** (calls EnvStats::serialcorrelationTest)
4) **_snh_** (Calls trend::snh.test with tooltip: Standard Normal Homogeinity Test (SNHT) for Change-Point Detection)
### Now some tests for normality - all from nortest package
**_Another separator_**
1) **_ad_** (With tooltip: Anderson-Darling test for normality - nortest::ad.test)
2) **_cvm_** (with tooltip: Cramer-von Mises test for normality - nortest::cvm.test)
3) **_lillie_** (with tooltip: Lilliefors (Kolmogorov-Smirnov) test for normality - nortest::lillie.test)
4) **_Pearson_** (with tooltip: Pearson chi-square test for normality - nortest::pearson.test)
5) **_sf_** (with tooltip: Shapiro-Francia test for normality - nortest::sf.test)

With the third button - the new **_Estimate_** button.  Now change the Dist label to **_Estimate_**.  Then the pull-down now has the following options:
1) mean (Calls MeanCI from DescTools)
2) median (Calls MedianCI from DescTools)
3) normal (Calls normCI from MKinfer)
4) poisson (Calls PoissonCI from DescTools)
5) quantile (Calls quantileCI from MKinfer)
6) sd (calls sdCI from MKinfer)
7) variance (Calls VarCI from DescTools)
 
### The final part
Each of these options will have further simple controls under the single receiver.
They will be similar, so I i9nitially give the controls for one or two from each of the new sections:

1) mean from meanCI in DescTools.  Here is the command from DescTools:
MeanCI(x, sd = NULL, trim = 0, method = c("classic", "boot"),conf.level = 0.95, sides = c("two.sided", "left", "right"),na.rm = FALSE, ...)
a) Ignore sd
b) Trim That is between 0 and 0.5.  That's an up-down, with default 0 and max 0.5 in steps of 0.01.  (We already have an example in the Prepare > Data: Reshape > Column Summaries under the More tab.)
c) Method Is that a simple pull down or radio buttons, with the options classic or boot.  Default is Classic.
d) Confidence Level;  Do we already have this anywhere already?  The default is (as in the dialogue) 0.95, other values are 0.8, 0.9, 0.95 (default), 0.99, 0.999, and ideally you can type anything between 0 and 1.  This control is in almost all the options here.
e) Ignore sides - so it always uses the default, which is 2-sided.  This is to be ignored generally.
f) Ignore the na.rm, but include na.rm=TRUE in the resulting R command.

So for this example there are just 3 simple controls.
I hope you can use these "rules" for more examples too.

**Comment by shadrackkibet** [comment]
@rdstern your list above is okay. I will add the Pettit test into your list above. That is common as well. The command is `trend::pettitt.test()`. Then I suggest a different order after the separator as follows with your tooltips above.

1. SNHT 
2. Pettitt 
3. Bartel 
4. br 
5. runs 
6. Sen 
7. serial corr

**Comment by rdstern** [comment]
Great, @shadrackkibet thanks.  Can you edit your changes into the issue above.

**Comment by shadrackkibet** [comment]
I do not have rights to edit. I can only comment.

**Comment by rdstern** [comment]
ok @shadrack - thanks.  I have made the changes.

**Comment by shadrackkibet** [comment]
@rdstern I have taken over this to tidy up code then I will hand over to @Wycklife to proceed with the addition of above tests.

**Comment by rdstern** [comment]
I am looking at the dialogue so far.
a) The null hypothesis on testing is a textbox not an up-down.  It can take only numeric values and they could be negative.
b) You have misunderstood the discussion and the Hypothesis is not needed.  Put the default values into the null-hypothesis.  The third control is not needed. 
c) Add the separator to the categories in the testing as mentioned in the issue details above.
d) I tried with binomial and proportion with a logical variable and it didn't enable OK.  It worked with a factor of 2 levels, but not more levels - perhaps correct - but we need to check with the mosaic binomial and proportions functions in Mosaic.  Can you look carefully at this?  It needs an extra control to define Success: It is a pull-down with the different levels of a factor and possibly the default being the first (or the last.  Maybe the first, but prefer the last.  For now it could be any column and the display is the unique values for a numeric column.
We can discuss if you like.

**Comment by shadrackkibet** [comment]
This was implemented and merged in #6150. Open a new issue if there is anything specific that needs to be fixed.
