### ISSUE TITLE
String handling design

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5830]
The design of this dialog doesn't look good. The labels are not well aligned and the size, spacing of the receiver and inputs, are unnecessarily wide. There is also an empty space on the right which can be substantially minimized by reducing the size of the top radio buttons.

![image](https://user-images.githubusercontent.com/26301973/84384963-7e275480-abf7-11ea-9a86-89159fec4303.png)

**Comment by lilyclements** [comment]
Will fix up the columns spacing and bits.

However, the empty space to the right is from the regex keyboard, this comes up when the checkbox is selected. However, the checkbox is currently disabled (I think, always. However, perhaps I'm misreading the code. It has been a while!)
Happy to make it so the dialog is a reasonable size, and then extends to this size when the regex keyboard is displayed? Like in the calculator dialog. However, I just want to check this in case this idea had been floated before, and decided against for any reason.

**Comment by rdstern** [comment]
That would be great assuming it is easy.  I would also very much like us to be able to include regex before too long, but that may not just be here and isn't a job for now.  There are too many other things to do before that.
