### ISSUE TITLE
Stack (melt) dialog design

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5831]
This dialog has minor designer issues see below-highlighted screenshots.

![image](https://user-images.githubusercontent.com/26301973/84385967-2689e880-abf9-11ea-82f5-8cdf0f7d4328.png)

![image](https://user-images.githubusercontent.com/26301973/84386082-651fa300-abf9-11ea-865c-2ff8f9079b35.png)

**Comment by rdstern** [comment]
Please keep these issues going on any problems you find like this.
From next week @lilyclements is returning to work, partly on her own tasks and also to provide support, particularly on problems involving R.
One task for her is is to remain super-critical about the layout of the dialogue.  This is a good example and I am assigning this issue to her.

**Comment by Patowhiz** [comment]
This issue reminds me to comment on why such design issues become visible only during runtime. At the moment, you can't set the labels of the custom controls in the design view, developers have to rely on doing this in code because the setter methods aren't VB.NET properties(which Visual Studio is fond of), this may prompt trial and error from the developers side to set the correct sizes. See issue #5838

**Comment by rdstern** [comment]
I now have some different points, while we are here!
a) the dialogue is still quite wide.  Is this needed?
b) More important and I will check with @dannyparsons is the name of the dialogue and also the R-code.  It currently uses melt and unstack uses the opposite.  This has now (I think) changed to pivot_longer and pivot_wider.

We also used a different function when you are stacking multiple sets of columns   We need to see whether we prefer to keep that function, or move that also to livot_longer?  

There is another change that would be useful for stack.  I think the default was (in melt) and still is (in pivot_longer) to carry all remaining variables in the data frame.  Our default (in the dialogue) is to carry nothing, and then to carry the specified variables if you do that.  @dannyparsons would like an option in the dialogue to "Carry All Columns".  We think that is the default in the function.  If so, then it would become the default here too.

**Comment by shadrackkibet** [comment]
I am going to close this because this issue was mainly for fixing design issues as referenced on the PR. I have opened a new issue with other different points from @rdstern.
