### ISSUE TITLE
Hide/unhide dialogs - dataframes and columns

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5846]
These dialogs do both hiding and unhiding, but we call the dialogs **Hide Dataframe(s)** and **Hidden Dataframe(s)**. I think the names should be **Hide/Unhide Dataframe(s)** and **Hide/Unhide Column(s)** respectively.

I think we should also be consistent in naming,  one dialog is called **Hide Dataframe(s)** and the other is **Hidden column(s)**. At least the names of multiple receivers are consistent!

![image](https://user-images.githubusercontent.com/26301973/85115801-ec39d000-b224-11ea-8a9e-aaad912beae6.png)

![image](https://user-images.githubusercontent.com/26301973/85115899-18ede780-b225-11ea-9f20-c147196d60bd.png)

**Comment by lilyclements** [comment]
Do we want Hide/Unhide or Hide/Show?

The menu option to get to the columns dialog says "Hide/Show Column(s)", whereas to get to the data frame equivalent, the option says "Unhide"

**Comment by shadrackkibet** [comment]
I am happy for the menu option (toolstrip text) to be changed to **Hide/Unhide Column(s)** for consistency. @rdstern what do you think?
