### ISSUE TITLE
Redo from the script window

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5868]
This might be a duplicate issue. 

In the script window you are allowed to undo. I find it useful to be able to redo as well. This feature can be added on the right click and also enable the shortcut to work, In Rstudio it is **(ctrl+shift+Z)** and I think in  most softwares

**Comment by rdstern** [comment]
Good idea.  I hope this will be a very quick feature for @Patowhiz to do.

**Comment by Patowhiz** [comment]
@rdstern I thought so too, after doing research online, VB.NET doesn't offer any direct redo for the textbox control. Apparently you can only use the same undo functionality to toggle between undo and redo.  But with a custom work around, this is doable

**Comment by shadrackkibet** [comment]
On a side note, I also note that it will be much convenient in future to make some items on the rights click as icons on top perhaps just in the script window? this might also apply to the log window items.

**Comment by Patowhiz** [comment]
@shadrackkibet that's a good suggestion that I think is worth creating an issue for.
