### ISSUE TITLE
Three variable frequencies design

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5871]
This dialog is unnecessarily wide when **Both** option is selected. I suggest the Graph Frequencies options be moved so that the dialog width is maintained when you are in any of the options at the top.

![image](https://user-images.githubusercontent.com/26301973/86013119-76edac80-ba27-11ea-9483-de5f11b3f7c4.png)

**Comment by Ivanluv** [comment]
@africanmathsinitiative/climsoft-developers  am taking this up
