### ISSUE TITLE
More options on extremes for peaks

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5881]
This should involve Caleb once he can be assigned issues.

He has a Word document which is attached.
[extremes-dialogue (1).docx](https://github.com/africanmathsinitiative/R-Instat/files/4880460/extremes-dialogue.1.docx)

It includes a proposed addition to the **_Climatic > Prepare > Extremes_** dialogue at the end of the document.  That is a good start, but it needs some editing.  I propose the following - still a set of controls under the data selector.
There is currently an group box with the label Options.  

I suggest 2 radio buttons. Each has a box - no label for multiple controls.  
1) The first radio button has the label **_Threshold_** and the second has the label **_Investigate Thresholds_**.
2) Towards the bottom of the dialogue there is a control with the label **_New Data Frame Name_**.  This now has a checkbox and the label becomes **_Save New Data Frame_**.  Default is unchecked and it is disabled (though still visible) if the "Investigate Thresholds" button is chosen.
3) There is currently an group box with the label Options.  There will now be 2 group boxes, below each of the 2 radio buttons.  I don't think they need a label.
a) In the first group box (corresponds to threshold) there is the existing control to choose the **_Value_**.
b) Under that is a checkbox (default unchecked) with the label Decluster:  Gap: then an updown control with the minimum 1 and no maximum.  No - let's have a maximum of 99.  Default is 1.  After that is a label **_rows_**.
c) In the second group box I am less sure but possibly, first a set of 3 text fields into which you can type a number.  The first field has the label **_From:_**  the Second has the label **_To:_**  and the third has **_Steps:_** .  There could be defaults that are sensible for rainfall e.g. 30, 60, 5.  (The values could be negative except the third one and that must be positive and more than zero.  If the second value is less than the first, then it steps down rather than up.  - I am sure testers will try that.)
Then there are 3 options, each with a checkbox.  The first is Counts, the second is **_Mean Residual Life Plot_** and the third is **_Parameter Stability Plots_**.

It might be good to show a picture of the new controls, but perhaps they can be constructed from the instructions above and the dialogue then shown?

The R code is not trivial and still needs some investigation.  Here are some points:

a) Currently the analysis simply does a filter.  That is still what is done if the first box is used and there is no declustering and the new Save checkbox is ticked.  
b) In the new dialogue there is some output, which gives the Count at the chosen threshold.  This uses the calculation system and is the **_Counts_** for each station if there are multiple stations in the file.
c) If the Investigate Thresholds option is chosen, then the Counts checkbox would provide the Counts for each station at each threshold.
d) The code for this (in the dialogue) uses the R-Instat calculation "system".  I suggest @shadrackkibet could help here.  It would probably include a loop (I guess) for the multiple thresholds.  (@dannyparsons may be needed to help here?)
e) If the Decluster option is chosen, then the results from Caleb indicate there would be some output automatically.  I did not see how the filtered data would be provided (using the maximum (or minimum) from each cluster, but I presume that is an option from the function?
f) There is then a choice of package for the plotting options.  I look forward to the recommendations for the mean residual life plot and the parameter stability plots.  Caleb gave the impression that the parameter plots are not available from the extRemes package.  They are available and are called threshrange plots.
g) If both checkboxes are ticked for the plots, then it would result in 2 plots being produced.  I hope this isn't a problem?

**Comment by Comfort123977** [comment]
![Pics](https://user-images.githubusercontent.com/58643069/90112879-7c3d5700-dd48-11ea-93da-48548c36dd9d.jpg)

From the data frame choose a variable or an element to which you want to investigate threshold. The station, Date, Year and Day of Year can be automatically filled if the data is already declared as climatic.
**Investigate Thresholds**
The investigate threshold radio button is chosen, we have options for counts, mrlplot and the threshrange plot. The mrlplot and tcplot check buttons can be check to produce two plots. To specify the run length (r), the radio button r can be selected for specification instead of the default.
**Threshold**
When the radio button threshold is selected, one can specify a value above the selected threshold, which can be saved as a new data frame.
To decluster a dataset above a certain threshold, the decluster checkbox can be checked, specifying the threshold.

We are also uploading a new document on using the extRemes package for the mrlplot, threshrange and declustering.
@rdstern kindly review for modifications. Thank you.

**Comment by Cal-Insta** [comment]
Attached is also the new document using the extRemes package for mrl, threshrange plots,
[peaks.pdf](https://github.com/africanmathsinitiative/R-Instat/files/5068026/peaks.pdf)
 and declustering.

**Comment by rdstern** [comment]
I have been looking in more detail at what is needed for this Climatic > Prepare > Extremes dialogue.  I had originally thought that it was straightforward. The main issue (as usual) is that the packages are for a single station.  If this is a good way to start, then fine.  But it would be good for the dialogue to be able to cope with multiple stations.  In what is needed, there are 2 main functions, as follows:

1) mrl plot.  This is reasonably straightforward as an idea.  It plots the mean of the excess data above a range of potential thresholds.  I had originally assumed we would use the extRemes package, but the texmex package is another contender and it uses ggplot graphs.  So the extension may be straightforward using facets.
2) The other important component is to be able to decluster the data, i.e. to omit close high valuers that may have come from the same climatic event.
I wonder if the R gurus, @dannyparsons and perhaps @shadrackkibet could give their inputs first.  Then @Ivanluv is poised to construct the extended dialogue.

**Comment by rdstern** [comment]
I have been examining the declustering options in the different packages.  I am (almost) convinced that the decluster from extRemes should be used.  It has a number of useful options that should be included in the dialogue.  And there are some aspects I still don't understand.  This is largely because of my weakness in using R.  I list some aspects below:

a) I think it can cope (automatically) that the data could be for multiple stations.  I have been trying with the ghana data set.
b) The default command could be `extRemes::decluster(rainfall, 60, r=1,na.action = na.exclude)`  So it just needs the **_variable_** and the **_threshold_**.
c) In the dialogue above that corresponds to the Threshold value (60 in the example), and the value of r (gap), which is 0 in the example above - is that allowed?  The default will be 1.
d) Add a **_Method_** control with perhaps a drop down and default runs, the other option is intervals.  When intervals is chosen, then the r is ignored.  (In the Ghana data I found it interesting that it gave its r = 11 when I used threshold of 30 or 40 and 5, when the threshold was 60mm.  (Useful to understand the "extemal index" calculation.
e) There is an argument called **_groups_** which should be very useful.  But I couldn't get it to work, except for the examples in the manual.  I don't know if groups have each to be the same length - the manual mentions years as a sensible group, which would be ideal for us.  Or perhaps it gets more complicated when there are missing values in the data?  This needs investigation.
f) The results can be plotted and it is an interesting plot.  However, it uses the ordinary graphs and also is tricky when there is a lot of data.  I wonder if we could produce our own graph.  It is simply of the data, but with all values from a cluster that are more than the threshold, put down to the threshold.  Here is an example:

![image](https://user-images.githubusercontent.com/11226469/93457324-bca76c00-f8d6-11ea-989e-47b25d02b1c3.png)

This is neat!  Could we make our own version of the plot.  We could have facets for the stations.
g) The result of the declustering is to produce an object, which I assume we could save?  I don't quite understand the object, i.e. in particular, should we make use of it.  And where are the declustered data in the object?
h) We currently save a filtered version of the data.  I suggest this should now be an option, as we may wish to try different options on declustering, before deciding what to save in our filtered data frame.  Also (I think) the resulting object can be used directly in the fitting process, i.e. by the fevd function.  Is this true?  Do we want to do this ourselves?  If so, then is it instead, or as well as being able to have the filtered data?

I need some help on this aspect.  I think it is worthwhile and powerful.

**Comment by rdstern** [comment]
The second important issue in this dialogue is the mrl plot.  This is to help in choosing the appropriate threshold.  The 2 obvious packages are the mrl function and plot in extRemes and the mrl plot in texmex.
The main problem is that neither function copes currently with the multiple stations that we often have in our data sets.  WE can ignore the stations and, in some instances it will be good to do that.  But we should also be able to produce a separate graph for each station.

a) The extRemes is currently part of R-Instat.  It produces a non-ggplot and also a matrix of data for the plot.  It would not be difficult to produce a ggplot.  Then we could add facets for the stations.
b) The texmex package would have to be added to R-Instat.  It has the advantage of already producing a ggplot.  It also produces a matrix with the information.  

This is a common problem that we have, i.e. to have multiple stations or another factor and to require the results for each station.  @dannyparsons is of the view that the solution should be considered on a case-by-case basis.  So, in this case I wonder if we could add a wrapper to the function, or we could edit the function.  We would certainly have to edit the function if we use the extRemes version.

I suggest initially we look to using texmex unless it isn't well programmed, as it already uses ggplot - and it looks like a useful package for us in the future.  Perhaps @dannyparsons and/or @shadrackkibet could comment first and then either @Comfort123977 or @Cal-Insta could investigate in more detail?
