### ISSUE TITLE
Taylor diagram improvements

### ISSUE THREAD

**Issue by lloyddewit** [africanmathsinitiative/R-Instat#5885]
Related to Issue #4944. The initial implementation of  Taylor diagrams was done in PR #5867. This PR was merged but some small issues remain (see comments from @rdstern below). 

Minor points: Label should be Estimated, and not Estimate.
I wonder about changing both the position and label for the first receiver. Perhaps it could become Facet (Station): and also perhaps moved to be below the Estimated receiver? Then it is just above the Group control.
I suggest we may later only have a single receiver for the Groups. There can be more than one factor here, but the legend is only for the first. But this should not be changed now, so the use of the multiple receiver can be tested.
I have also been looking at the documentation for the Taylor diagram. There is a lot more we can add to this dialogue, including saving the results - possibly as an object or in a new data frame. And options for colours, etc. Also I notice there can be 2 facet variables. I wonder if it might be useful to have a receiver that takes up to 2 variables?

**Comment by N-thony** [comment]
@lloyddewit Can this issue be taken or is it still under discussion?

**Comment by lloyddewit** [comment]
@shadrackkibet You wrote the PR that is related to this issue (PR #5867) so you probably have a good understanding of how to resolve this issue. Do you have any objections if @N-thony works on this issue? Or would you find it more efficient to resolve this issue yourself?
Thanks

**Comment by shadrackkibet** [comment]
@lloyddewit this is a good suggestion thanks. I am happy to hand it over to @N-thony. I am also available to support if needed.

**Comment by shadrackkibet** [comment]
There are more options which can be added into the sub dialog. I suggest we add a button(**Taylor Diagram Options**) disabled for now into this dialog.

**Comment by rdstern** [comment]
I notice that the latest upgrade to the openair package was 6 days ago.  One thing mentioned was "fix bug in TaylorDiagram when group was present.".  @dannyparsons and I found some oddities in interpeting a Taylor dialogue and we did have groups.  So that's interesting!

**Comment by dannyparsons** [comment]
Here's an extract from a message I sent to a user who found similar issue with the Taylor Diagram. It seems the "Normalise" option could be important. I don't know if we should be setting this automatically, or we might get into a mess trying to guess it.

> Looking at the examples in our guide again I think you are right that, the comparisons are not quite correct when the stations are on the same plot. When the stations are on the same plot, the RMSE and Correlation seems to be correct but the standard deviation is slightly off due to the comparison with "observed" being for something slightly different than expected. I've had a look at the documentation for the function again openair::TaylorDiagram, and I think what needs to be done is to "normalise" the values so that the comparisons are correct. Here is what it says about normalisation:
> 
> Should the data be normalised by dividing the standard deviation of the observations? The statistics can be normalised (and non-dimensionalised) by dividing both the RMS difference and the standard deviation of the mod values by the standard deviation of the observations (obs). In this case the “observed” point is plotted on the x-axis at unit distance from the origin. This makes it possible to plot statistics for different species (maybe with different units) on the same plot. The normalisation is done by each group/type combination.
> 
> So I think this is the option needed to correct the plot. I think you are right that your first plot, with the stations separate, is correct, and your second one, is doing slightly incorrect comparisons. If you checked "Normalise" for your second plot I believe it would come out correctly. It would be good to try and confirm. I find it useful to also produce the summaries so you can compare the values with the plot. However, not that when "Normalise" is checked, the RMSE is scaled so it won't be the same as the summary value.

**Comment by shadrackkibet** [comment]
We already have the "Normalise" option in the dialog. I am not sure what exactly needs to be done in this dialog. Do we need to add more options as a sub dialog?

**Comment by dannyparsons** [comment]
I don't think it's more options, but better choices for the current e.g. I don't think we are using station correctly. I think instead of a station receiver we should just have the names of the parameters as the receiver labels and let users choose where to put station. That gives full flexibility, even if a bit harder to use. @rdstern what do you think? This might be a quick way of getting something more sensible without spending more time.

**Comment by shadrackkibet** [comment]
@N-thony could you make these changes in your current PR? Otherwise, I can pick your changes and open a branched PR. Let me know which way you prefer. Thanks

**Comment by dannyparsons** [comment]
@shadrackkibet I suggest you take over since @N-thony has a number of other urgent tasks he's working on.
