### ISSUE TITLE
Adding gev and gpd to the distributions in R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5886]
Ibrahim has also been working on this topic, but he is not yet on github.
There is a list of distributions that is used in at least 3 dialogues.  This does not (yet) include the extreme value distributions and they should be added.  The same list is used in:
a) Model > Probability Distributions > Show Probabilities
b) Model > Probability Distributions > Random Samples
c) Model > Fit Model > One Variable (The general model fitting)

The required functions are available in various packages with the "right names" e.g. evd, evir.  They are also in the extRemes package - that we use already.  There they are under the evd function (e.g. pevd, where the precise distribution is specified by the type argument within the function.  

I don't know whether that would make it more difficult to incorporate?  If we do decide to use it, then perhaps we could have a little function ourselves - and call this function?  That might help us to avoid including the library call when using this feature?

**Comment by shadrackkibet** [comment]
@IbrahimDanDije Here is an issue to attach your findings.
