### ISSUE TITLE
Adding an extreme value dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5887]
This is already provided under Climatic > Model > Extremes.

But that dialogue is simply copied from the old Instat and almost certainly the code and dialogue need to be very different.  

This will almost certainly use the fevd function from the extRemes package.  It allows trends etc and so may be "Interesting" to construct.  
We may also call other functions to use the resulting object, in the same dialogue, or have another new dialogue to Use Extreme Model.  Then this one would become Fit Extreme Model.

We need to ensure that the structure of this (or these) dialogues is consistent with other dialogues in R-Instat.  We may also find that the structure of the equivalent dialogues in the front-end to the extRemes package is helpful?

**Comment by shadrackkibet** [comment]
@Comfort123977 @Cal-Insta I am just about to start looking into this. What are your initial reactions on this subject?

**Comment by Comfort123977** [comment]
Caleb and I are currently working on the new layout, which we intend to upload later.

**Comment by Comfort123977** [comment]
@shadrackkibet Caleb and I have come up with our initial thought on how the dialogue could look like.

The dialogue would contain three main controls or fitting options. The **Distributions** to be considered, the **Estimation methods** and the **Parameter specification** to allow for trends. Each of these options would take a group-box.


1. The first group box would contain a check-box for selecting the distributions to fit the dataset. When this box is checked, then a list of distributions including the GP, Gumbel, GEV, and Exponential can be selected.


2. There is a check-box for estimation methods and when this is checked, options for the estimation methods including the MLE and MOM can be selected.


3. The third is the parameter check-box for specifying the location and scale parameters. Defaults can be set ( 1,1 for location and scale parameters respectively). It would also be designed to accommodate trends by allowing the user to choose a variable (year) in the data to specify the trend.

**Comment by Cal-Insta** [comment]
@shadrackkibet, our initial thoughts on how the dialogue could appear in the shown in the image displayed below. We can make time to discuss more on specifications. Thank you.
![fit_cooo](https://user-images.githubusercontent.com/66616144/88489421-100ed500-cf8c-11ea-90a7-9e3aa5f09782.png)

**Comment by rdstern** [comment]
@Cal-Insta and @Comfort123977 thank you for your suggestions above.  Please have a look at where @Ivanluv has got to, on the possible dialogue.  He has chosen to put some of your suggestions on buttons.  Also (in the current version) his checkbox that says Save Graph is actually Save Model.  He also has a combo control for the distribution.
One difference is that he doesn't yet have a possibility of a parameter for the scale - and I suggest this might be a good idea for him to add.
However, one limitation in your proposal is that the model is only for a single parameter, e.g. year.  The modelling (I think) permits a reasonably full model and I suggest that is much more general.

I do have an additional task for you both now.  I would like the existing dialogue to now be named as **_Fit Extremes_**.  Then there would be a second dialogue with the name **_Use Extreme Model_**.  Many functions in the extRemes package use the model that has been fitted.  If you are happy to do this, then it would become a separate issue that you would make.

You will have to try the different options and I suggest you can do some of this using R-Instat and some using RStudio.  In R-Instat the Model > Use Model > Use Model Keyboard has an extRemes keyboard.  This could be improved, and some of the options may not work!  In addition that is a "halfway" dialogue and it would be good to have a more helpful ordinary dialogue also.  I wonder what the design could be?
