### ISSUE TITLE
Displaying a filter in operation

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5901]
>Yes, this is more general than deleting a filter.  When a filter is in operation the row variable is in red, so you know a filter is being applied.  But which?  I thought - as a separate issue, perhaps youi could right-click in the rows (i.e. on the red bit) and there would be simply a label that Says Filter: Filter2 if a filter is in operation and perhaps Filter: None if no filter is currently applied?

_Originally posted by @rdstern in https://github.com/africanmathsinitiative/R-Instat/pull/5860#issuecomment-658311939_

@rdstern I suggest adding this as part of the label below the data view window which is easy to do.

**Comment by shadrackkibet** [comment]
@dannyparsons @rdstern  what do you think about this? I thought of adding it below as part of the label. For example, if a filter is in operation this will read **Showing 1000 of (54300) | Filter: Filter1 active** if there is no filter it is as it is now.

**Comment by rdstern** [comment]
@shadrackkibet I like that idea.  @dannyparsons?
