### ISSUE TITLE
Additions to the display daily data graph

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5903]
These are suggestions to go on the main dialogue:

1. Have a group box with the label Layout (Facets): Rows
I hope this can work and is easy to produce.  I suggest 5 radio-button options:
a) `Default`  (that is as now with elements in rows and Stations in columns)
b) `All (Grouped by Element) `(This is then a single column.  It groups the variables by Element)
c) `All (Grouped by Station) `
d) `Station`
e) `Element`
f) `Number` (opens up/down control from 1 upwards)
Possibly these options are grouped into 2 sets of 3.  (We need to allow for the data being for a single station.)
2. A second group box  with the label X-Axis.
This provides the same box as in the sub-dialogue now for the x-axis dates.
It could usefully add the control for the angle of the x-axis label.   
3. Could the order of the buttons change so that the Graph buttons are first and the Table is last?  Then the default is the Graph.

**Comment by rdstern** [comment]
Following suggestions by @shadrackkibet the R patchwork package looks useful to add to R-Instat.  I think this enables all we need - that is if I have understood @shadrackkibet suggestions properly.  It also looks useful more generally possibly to enhance our existing Describe > Combine Graphs dialogue.

For this dialogue  I suggest all that is needed can be accomplished through 2 controls on the dialogue.
a) An up-down control with the label Columns.  It is integers and goes from 1 upwards, and the default is 1.  Then all the graphs are laid out vertically.
b) A checkbox (default unchecked) with label **_Order by Station_**.  This is disabled unless there are multiple Stations and also multiple Elements to be plotted.   
I think this should make the R code very easy?  The ordering will be `Station ~ Element`, or `Element ~ Station` when b) applied - I forget the argument name - @shadrackkibet will show.  The number of columns is also an argument.

This will mean the user has to be sensible, but that's ok.  (For example if you have 3 elements and 2 stations, and you say by Station and have 3 columns, then you will have

StationA_tmax, StationB_tmax, StationA_tmin
StationB_tmin, StationA_rain, StationB_rain

which would not be great - but easy to change - the user is working interactively.

**Comment by shadrackkibet** [comment]
@rdstern using your initial suggestions above we have simplified this further while trying to achieve the flexibility required. We suggest the following:

- We change **Free y-axis** checkbox into a combobox with the label **Scale:**. Inside the Combo box we have three options, `Free_y, Free_x, Free`. By default `Free_y`.  Now we use `facet_wrap` which allows free scales.
- A combo box with the label **Facet by:**. In the combo box, we have three options: `Element, Station, Station-Element, Element-Station`. `Element`  is only visible when you have one station i.e station receiver is empty while `Station` is visible when you have multiple stations but with one element in the receiver. The other two `Station-Element, Element-Station` is visible when you have multiple stations and elements. 
- Below we have a checkbox with the label **Column(s):** checked by default, when checked a numeric up-down (default 1) is displayed. Essentially we only allow integers starting from 1.
For convenience purposes, we do not allow changing of rows changing of columns is enough to automatically fix number of rows required.

What do you think?

**Comment by shadrackkibet** [comment]
I also suggest changing the colour of the rug plot to red to be consistent with inventory plot.

**Comment by rdstern** [comment]
Sounds good.  
I did think the rugplot looked clear when black.  Happy to try red for consistency.  I also want to improve the inventory plot later.
Could there be a combobox for the rugplot colour?

**Comment by shadrackkibet** [comment]
Yes, we will add that.

**Comment by rdstern** [comment]
No change needed, but I include an "interesting" graph that uses this dialogue:
![image](https://user-images.githubusercontent.com/11226469/94423608-cd7e9a00-0180-11eb-8d10-da14d5002123.png)
1) It is showing tmin, (X2) tmax (X3) and rain (X5).
2) Sometimes there is a connecting line in the temperaure data that looks odd (like linear interpolation).  It isn't interpolating, but is a date gap.
3) Sometimes there is no connecting line.  That's when there are missing values at either end of the date gap.
4) There are lots of missing values for the rainfall.  That's because the rainfall was only recorded on non-rainy days.  
5) For the rainfall, if there are many years, then the missing rug-plot bits connect up.  Maybe there should be an option for 2 rugs, with one (as now) for missing and a second (different colour) for presence?  The rare one goes second, whichever that is!

Perhaps I now do suggest a small improvement.  Here is my improved plot - (just the rug is different).  

![image](https://user-images.githubusercontent.com/11226469/94426023-d96c5b00-0184-11eb-94c3-2b2378b577f3.png)

Here is the current one:
![image](https://user-images.githubusercontent.com/11226469/94426185-1b959c80-0185-11eb-80fb-7f74cfe2beff.png)

Neither is ideal.  If you just have the absence - as now, then it emphasises the missing values.  With the extra rug it shows the presence and hence misses odd missing values.

Not a bad option perhaps.  I added the code:
 `+ ggplot2::geom_rug(data=Niger10 %>% filter(!is.na(value)), colour="white",sides="b")`  Now there is black for main absence, white for presence and grey (on this theme)  On the dialogue it could be a checkbox with "Second rug to show presence", and possibly also an option for the colour, with default white?

**Comment by shadrackkibet** [comment]
@Ivanluv is there anything remaining here? Otherwise, we can close this.

**Comment by Ivanluv** [comment]
@shadrackkibet there's nothing remaining
