### ISSUE TITLE
Improving the layout: Spacing, aligning etc Enter dialog 

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5907]
The spacing of buttons in the keyboard is not consistent between the two dialogs below. The calculator looks better, I therefore suggest improvement of the layout of the Enter dialog as follows; some of these might apply to the calculator.

- [ ] The buttons should be close to each other like in the calculator
- [ ] The save control should be close to its label
- [ ] Some labels should have colons at the end and labels should not be too far from its corresponding control.
- [ ] Some button text appears small, this can be improved by increasing the font size, bolding etc at least the calculator looks better.
- [ ] Change the position of **Show Arguments** below the Data receiver at the top. Should this be renamed to **Show Parameters**?

![image](https://user-images.githubusercontent.com/26301973/87849435-58c1f080-c8f1-11ea-8a72-1df6abc97e18.png)
![image](https://user-images.githubusercontent.com/26301973/87849793-15b54c80-c8f4-11ea-9c92-ad17e825fd1e.png)

**Comment by Wycklife** [comment]
@shadrackkibet @rdstern Is this still under discussion or should be taken up?

**Comment by rdstern** [comment]
There is more than the above to do on the Enter dialogue.  @Patowhiz has started work on improving the Enter dialogue with the idea that you will continue.  I am keen that the basic keyboard from the calculate also be used entirely (partly for consistency) in Enter.  And there are other changes that are additional to those above in #5596.

**Comment by shadrackkibet** [comment]
The layout in this dialog looks better now. Therefore, I am going to close this issue.
