### ISSUE TITLE
Start of Rains - OK enabled bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#5925]
**Describe the bug**
I came across a minor bug in the "start of rains" dialog where I think OK is enabled in a situation which it should not be. However, I wanted to check in case the issue is instead with the code.

**To Reproduce**
1. Import the Ghana data,
2. Open the Start of Rains dialog, the "station", "date", and "rain" columns are filled.
3. Click to display "Day of Year" and "Date"
4. Click OK

An error comes up since the "day of year" column is not filled in the dialog.
This column needs to be filled because the dialog filters to the days in the year selected from the "Day Range" option.

@rdstern - presumably OK should never be enabled until the "day of year" column is filled. Is this correct?

**Comment by lilyclements** [comment]
@rdstern another question about the OK enabling in this dialog.
Currently OK isn't enabled if "Day of Year" is not selected from the "Display" option box (even if other check boxes are selected).
Is this intentional? If I change the code, it runs fine if "Day of Year" is not checked and instead another checkbox in the "Display Options" is selected.

**Comment by Wycklife** [comment]
@rdstern Can this be taken up or is it still under discussion?

**Comment by lilyclements** [comment]
@Wycklife I've got the code with this fixed in a branch so was just waiting for confirmation before syncing and putting it in a PR.

**Comment by Wycklife** [comment]
@lilyclements Okay, I wanted to pick it up but it's okay if you've fixed it. Thank you for letting me know.

**Comment by shadrackkibet** [comment]
@rdstern any response? Looks like @lilyclements did fix this she is only awaiting your reactions.

**Comment by rdstern** [comment]
@lilyclements and @shadrackkibet no that sounds all good to include and fix.
