### ISSUE TITLE
Compare dialogues moved on frmmain

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5949]
Currently the Compare Dialogues are within the Climatic > Summary menu.
We suggest that most of the operations fit (slightly) better in the Describe part of the Climatic menu.
a) We propose a Main item in the Climatic menu called **_Compare_**.  It is before mapping.
b) Within this main climatic menu the first 2 items are the existing **_Calculation..._** and **_Summary..._**  (No longer called Compare: Calculation, because Compare is the main item.
c) Then there is a line as a separator.
d) Then **_Correlations_**.  This is just c copy of our correlations dialogue
e) Then **_Scatterplot_**.  Just a copy of our current Scatterplot dialogue
f) Then **_Time Series Plot..._**.  This is a new dialogue so add a blank dialogue for now.
g) Then **_Seasonal Plot..._**.  Another new dialogue
h) Then **_Density Plot_**.  This is just the Histogram dialogue, but it defaults to the Density button here.  
i) Then **_Conditional Quantiles_**.  This is a new dialogue so just add a blank one for now.
j) Then **_Taylor Diagram_** with the current Taylor Diagram from the existing climatic > Prepare Menu

**Comment by Wycklife** [comment]
@africanmathsinitiative/developers Is anyone working on the formmain? I have done this but then I realized my branch has conflicts when I try to create a pull request.

**Comment by shadrackkibet** [comment]
I think you might have updated your master branch before #5935 was merged. Make sure your branch is in syc with the main master branch before you continue.

**Comment by Patowhiz** [comment]
In addition to those menu items under the Climatic, I would suggest another menu for the Import From Climsoft Wizard just below the current Import, @rdstern might have a good name for it. Then the PR could be merged and used in PR 5957.
