### ISSUE TITLE
Oddity with circular plots

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5950]
Here is an example of the problem.
Open the standard survey data from the R-Instat library
Use Describe > Specific > Bar Chart
a) Do a Bar chart of the Fert variable.
b) Now return to the dialogue.  And all is fine.  (It has remembered all the settings.)
c) Now use Plot Options > Coordinates and choose Polar Coordinates. Get the Plot.
d) Now return to the dialogue.  All is not fine
It has switched to Pie Chart
When you return to the Bar Chart it has omitted the variable
And it has changed the position option from Dodge to Stack

**Comment by Patowhiz** [comment]
@rdstern I **think** I know what is the problem.
It's the way the dialog is set up to determine the checked radio button from the Rcode. It uses parameter name `coord_polar` to uncheck the radio button Bar Chart. This seems sensible until you activate the polar coordinates. They write into the base operator, passing `coord_polar` as one of its parameters. Thus on reopening the Pie Chart radio button is checked and the previous R code is "jumbled"

Code speaks louder! Check below

Code generated when bar chart radio button is checked
```
# Code generated by the dialog, Bar and Pie Chart

survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x=fert)) + ggplot2::geom_bar(position="dodge") + theme_grey()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))
```


Code generated when pie chart radio button is checked
```
# Code generated by the dialog, Bar and Pie Chart

survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(fill=fertgrp, x="")) + ggplot2::geom_bar(width=1) + theme_grey() + ggplot2::**coord_polar(**theta="y")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))
```

Code generated when bar chart radio button is checked and coordinates added
```
# Code generated by the dialog, Bar and Pie Chart

survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x=fert)) + ggplot2::geom_bar(position="dodge") + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text()) + ggplot2::**coord_polar**(start=0 * pi)
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))
```

How the radio buttons are currently set up in code
```
        ucrPnlOptions.AddRadioButton(rdoBarChart)
        ucrPnlOptions.AddRadioButton(rdoPieChart)
        ucrPnlOptions.AddParameterPresentCondition(rdoPieChart, "coord_polar")
        ucrPnlOptions.AddParameterPresentCondition(rdoBarChart, "coord_polar", False)
```
I'm looking into why it had to be done this way. It's clear that this wasn't critically tested.

**Comment by rdstern** [comment]
@Patowhiz that's a relief and obvious now you explain it.  I was worried this was a more general problem, but your answer shows clearly that it just affects this dialogue.  And we have always had the pie chart as one of our graphs.  It is the only graph that always uses coord_polar.  Now the idea is that any geom could opt to use polar coordinates.  But I can now see that this one is different, and could therefore assume that coord_polar implies a pie chart.

It needs to be solved, but is no longer quite so urgent.  Good to do it in the next few days, but you don't have to work through the night unless that's when you work best.  And take the time that is needed.

**Comment by Patowhiz** [comment]
@shadrackkibet looking at the ggplot in reference to producing these 2 types of plots and my comments above on the nature of the scripts produced. What would be the ideal parameter name to "attach" to in "remembering" the previous checked radio button when reopening the dialog. I'm leaning towards using parameter position of ggplot2::geom_bar but I'm not sure if that is the only way or rather the better or correct way. 

I'm also tempted to do this kind of check manually as I think it's the easiest way but would like to explore using R-Instat custom control "api" in this

**Comment by shadrackkibet** [comment]
I had a quick look into this but I didn't check vb code. I think the reason why that happens is because of `ggplot2::coord_polar()` which is added to the base operator `+` when you use the sub dialog(plot options) and when on **pie-chart** radio button. So when this is added in the subdialog (plot options) and then on reopen `setRcodeForControls` is run which then updates the panel to pie-chart. I do not have a specific solution to fix the problem (not unless you want me to look into the dialog code). I think there is an obvious problem with the code setup which should be easy to fix.

**Comment by Patowhiz** [comment]
@shadrackkibet thank you for your feedback
