### ISSUE TITLE
The circular menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5964]
We need to check that no one else is editing frm main, but this should be quick - I hope.
There is already Structured > Circular, with the Define dialogue.
a) Add `Calculator `below Define (This should have the ordinary Calculator from the Prepare Menu.  Ideally when opened it has the Circular keyboard automatically.
b) Add `Summaries` below that.  Ideally when you open the sub-dialogue it starts initially with the Circular tab.
c) Then a horizontal line
d) Then **_Scatter Plot_**.  This can have a blank dialogue for now.  It will implement the ScatterPlot function from the Circular package.
e) Then Density Plot.  Same as d) from Circular package
f) Then (possibly) Rose Plot.  I need to check so leave this for now.
g) Then a horizontal line.
h) Then Wind Rose with the current Wind Rose dialogue
i) Then Wind/Pollution Rose with a similar dialogue from the Openair package.
j) Then (these next are disabled for now) Percentile Rose, Frequency Rose, Polar Plot, Polar Cluster, Polar Annulus, Polar Frequencies
k) Then a horizontal line
l) Then (also disabled) Circlize.

**Comment by shadrackkibet** [comment]
I discussed this with @HawardKetoyoMsatsi. I think this is a good task for him to get started with some bits of coding in VB with help from others.

**Comment by HawardKetoyoMsatsi** [comment]
I am done working on this issue...
