### ISSUE TITLE
More circular plots from openair package

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5966]
There are 6 more circular plots provided by the Openair package.
Percentile Rose
Frequency Rose
Polar Plot
Polar Cluster
Polar Annulus
Polar Frequency
These may become 6 dialogues or (say) 2 dialogues with 3 radio buttons in each or...?  From a quick look I fail to see the connections that would help in structuring the dialogues.  Once decided they should be easy to construct and code, because they have similar options to the Wind/Pollution Rose function.

This is work initially for @HawardKetoyoMsatsi with @Wycklife probably doing the coding then.

**Comment by HawardKetoyoMsatsi** [comment]
The other kinds of rose plots use different functions, I therefore suggest we have a menu leading to 5 different dialogs for each plot.
![menu](https://user-images.githubusercontent.com/16137042/94418459-f7c85b80-0170-11eb-9eb9-e308e5d4b9f2.jpeg)
