### ISSUE TITLE
Climatic > Compare > Time Series Graph dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5973]
This is the design for a new dialog. I think the menu item is already there for it.

@Wycklife could you create the dialog and sub dialog designs below?

The main dialog has 4 receivers, 3 checkboxes and then a button leading to the subdialog, and a save control to save the graph.

The sub dialog has a group box with a number of checkboxes (just put a few in for now), then a text box, a combo box, and another text box.

I hope that's clear. It doesn't need to be perfect, if you can do the main design quickly that would be helpful. Thanks.

![IMG_20200910_133221](https://user-images.githubusercontent.com/11214914/92729515-59fc2080-f36a-11ea-9283-f1204e2013af.jpg)
![IMG_20200910_133232](https://user-images.githubusercontent.com/11214914/92729510-58325d00-f36a-11ea-924f-93aa5a5c3d5b.jpg)

**Comment by Wycklife** [comment]
@dannyparsons I'm sorry I have just seen this now.  I have done this. Changes are on pr #5965. Kindly get them. I did them earlier
