### ISSUE TITLE
Adding the conditional quantile plot

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5974]
In #5928 we describe the set of dialogues needed for the graphical comparison of station and gridded data.  One of these is the conditional quantiles plot from the openair package.  [Chapter 19](https://davidcarslaw.com/files/openairmanual.pdf) of the sort of book on this openair package describes their use.  
I suggest @HelenaMwangila could design this dialogue and then try to implement it.  Once designed it will be similar to some existing dialogues and this should help with the coding.  The item is already in the menu under Climatic > Compare  > Conditional Quantiles.

As an initial step please could @Wycklife add a blank dialogue for Helena to start.  (At the same time could @Wycklife also add a blank dialogue for the time sereis and the seasonal plots.  Then @dannyparsons will be working on those dialogues, at least initially.

**Comment by HelenaMwangila** [comment]
After looking at the controlQuantile() function, I tried to design a layout of the dialogue.
![image](https://user-images.githubusercontent.com/67306949/93300465-7d5a1c00-f7ff-11ea-97c9-aed6d997edaf.png)
I would like any useful input to improve it, before moving to the next step.

**Comment by dannyparsons** [comment]
This looks good. For the Compare section in general we need to agree on a consistent name for the two column being compared. Lots of different combinations are used in different packages.

I quite like "Reference" and "Estimates" which is general enough for different uses and quite clear which column to put in each place. Reference is a bit more general than Observations and so it would allow, for example, comparing two satellite products.

**Comment by rdstern** [comment]
@N-thony you were asking for a new task.  Could you take this on?  It completes our initial set of dialogues to compare station and satellite data.

**Comment by N-thony** [comment]
@rdstern is sure! I would like to work on this

**Comment by shadrackkibet** [comment]
The option  `openair::conditionalQuantile()` is flexible enough. @N-thony please proceed with this implementation. I am available to support in case you need help.
