### ISSUE TITLE
Seasonality Plots dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5980]
This is the design for the seasonality plots dialog. This is to compare the seasonality of two columns, in general "reference" data and "estimates". The graphs are of summary data based on the seasonality column chosen, but the dialog uses the original (usually daily) data because that is the level where the calculations are done. Because of this the R code is slightly none trivial. Here is the type of output that we want to produce:

The colours are the reference and estimates data, the values on the y-axis as raindays (proportion of days above 0.85) and day of the year on the x-axis. The smooth line is some kind of model fitted to the data and the wiggly line is the 5 day moving average. The moving average line shows us that the curves fit quite well and the curves show that both get the same seasonality shape but the estimates consistently overestimate raindays.

![image](https://user-images.githubusercontent.com/11214914/93075908-66d88700-f67e-11ea-97a3-8849ffe46bc5.png)

There 4 receivers: reference & estimates are the columns to compare, seasonality (X axis) is the seasonal column e.g. day of year or dekad or month etc. The last is station, I forgot it on the design but add it to the bottom. This is optional.

Under reference and estimates there is a drop down box to choose the summary to display (for each value of the seasonality column). The options there are: "Prop Above", Prop Below" and "Mean". For example, for rainfall we would usually use "Prop Above" to give proportion of values above 0.85mm which is rainy days. For temperature, we would usually want "Mean". If "Prop Above" or "Prop Below" is chosen then a text box appears next to it to give the value. Before the text box add a label for ">" or "<".
This is for each column because you may want different summaries for the reference and estimates data e.g. Prop Above 0.85 for reference and Prop Above 5 for estimates.

The check box: "Remove rows with any missing values" is checked by default. This filters the data to only use values where both columns are not missing. This is usually sensible so that the comparisons are using the data time periods. If unchecked, the filter is removed.

The two group boxes set what is displayed on the graph.

The first is "Values" which has a check box to display the points and another to display the moving average. The points is `geom_point()` and moving average adds `geom_line(aes(y = moving))` and adds the calculation: `mutate(moving = raster::movingFun(prop, n = 5, circular = TRUE, na.rm = TRUE))`. A text box appears to set the value of `n` which is `5` by default. Notice that `circular = TRUE` which means the values are "wrapped round" so that, for example, for the day of year the values at 365, 366, 1, 2 and 3 are used in calculating the 5 point moving average for day 1.
I think we could have moving average checked by default with 5 and points unchecked.

The "Smoothing" group box sets what smooth curve is fitted to the data. A smooth curve is useful to see the general shape in a smoother way than the points or moving average which makes it easier to compare. There are different options that do different things but will give similar curves. The options in the drop down box are: "Fourier Series", "Periodic Splines", "Natural Splines" and "LOESS". 
For Fourier Series there are 2 parameters to specify, Harmonics (default 3) and Period (default 366). Harmonics is number of sin/cos pairs to include in the fitting and the period is the length of the seasonal cycle e.g. 366 for day of year.
For Periodic and Natural Splines the d.f. (degrees of freedom) parameter is given, default 6. This is how flexible the line can be basically.
For LOESS the span parameter controls how much of the data is used to fit at each point, so a lower span is more flexible. I suggest our default for this could be 0.5 (the R default is 0.75). It could be a nud with 2 decimal places. The minimum is 0 but it has an unlimited maximum.

Here is the R code to do the dialog. In this example, `zm` is the data frame chosen, `x1` is the reference column and `x2` is the estimates column. `sdoy` is the seasonality column and `station` is the station column.
I've included two versions of the `zm_seasonal` calculation to show how it should work for a proportion and how it should work for a mean.
We always calculate `n` in `zm_seasonal` because this is the needed as the `weight` aesthetics which is important for the fitting to know how many observations make up each point.
I've included all the possible curves in the graph to show how they work but the dialog will never allow such a complex graph. There will only be one `geom_smooth` in the graph at a time.

``` r
# add this function to stand alone functions file
fourier_series <- function(x, n, period) {
  p2 <- "2 * pi"
  h <-  seq_len(n)
  paste0("sin(", x, " * ", h, " * ", p2, " / ", period, ")", " + ", 
         "cos(", x, " * ", h, " * ", p2, " / ", period, ")", 
         collapse = " + ")
}

# if the summary is prop
zm_seasonal <- zm %>%
  # this is controlled by the missing checkbox
  filter(!is.na(x1) & !is.na(x2)) %>%
  mutate(reference = x1 > 0.85,
         estimates = x2 > 0.85) %>%
  # this stacks the data which is needed for the graph
  pivot_longer(cols = c(reference, estimates), names_to = "data", values_to = "thresh") %>%
  group_by(station, data, sdoy) %>%
  summarise(n = sum(!is.na(thresh)),
            prop = sum(thresh, na.rm = TRUE)/n) %>%
  # this is only added if moving average option is selected
  mutate(moving = raster::movingFun(prop, n = 5, circular = TRUE, na.rm = TRUE))

# if the summary is mean
zm_seasonal <- zm %>%
  # this is controlled by the missing checkbox
  filter(!is.na(x1) & !is.na(x2)) %>%
  mutate(reference = x1,
         estimates = x2) %>%
  # this stacks the data which is needed for the graph
  pivot_longer(cols = c(reference, estimates), names_to = "data", values_to = "value") %>%
  group_by(station, data, sdoy) %>%
  summarise(n = sum(!is.na(value)),
            m = mean(value, na.rm = TRUE) %>%
  # this is only added if moving average option is selected
  mutate(moving = raster::movingFun(m, n = 5, circular = TRUE, na.rm = TRUE))

ggplot(zm_seasonal, aes(x = sdoy, y = prop, colour = data, weight = n)) +
  # points
  geom_point() +
  # Moving average
  geom_line(aes(y = moving)) +
  # Fourier series
  geom_smooth(method = "glm", formula = as.formula(paste("y ~", fourier_series("x", 3, 366))),
              method.args = list(binomial(link = "logit")), se = FALSE) +
  # periodic spline
  geom_smooth(method = "glm", formula = y ~ pbs::pbs(x, df = 6),
              method.args = list(binomial(link = "logit")), se = FALSE) +
  # natural spline
  geom_smooth(method = "glm", formula = y ~ splines::ns(x, df = 6), 
   method.args = list(binomial(link = "logit")), se = FALSE) +
  # loess
  geom_smooth(method = "loess", formula = y ~ x, se = FALSE, span = 0.5) +
  # facet by station if given
  facet_wrap(~station)
```

Then there is the usual save control because the output is a graph.

If you're interested in the background here are some links but I suggest looking at the code and getting started on it and not spending lots of time reading:
- A short explanation of why you might use Fourier Series for seasonal data instead of polynomials https://stats.stackexchange.com/questions/224990/whats-wrong-to-fit-periodic-data-with-polynomials
- An explanation of splines with something at the end of natural splines http://www.clayford.net/statistics/using-natural-splines-in-linear-modeling/. Circular splines are almost the same except with additional requirements that the beginning and end of the fitted values line up in the same way it does naturally for the Fourier Series.
- A good explanation of LOESS https://www.itl.nist.gov/div898/handbook/pmd/section1/pmd144.htm 

![seasonality_dialog](https://user-images.githubusercontent.com/11214914/93082790-714c4e00-f689-11ea-833e-a8fb3d78be66.jpg)

@HawardKetoyoMsatsi would like to take this up with help from @shadrackkibet? It's not the most simple dialog but I think it's a good one if you are keen. It does need to be done quite soon so we should discuss priorities with @rdstern if you do take it up. Let us know what you think.

**Comment by HawardKetoyoMsatsi** [comment]
Yes please I will take it up and work on it closely with @shadrackkibet.

**Comment by rdstern** [comment]
@HawardKetoyoMsatsi that is great.  We would like you to move over to this quite quickly, so @dannyparsons may volunteer to "take-over" the work on the circular menu.  There will be plenty to return to, on circular, later.

The seasonality plot also contains some interesting statistical ideas.

**Comment by HawardKetoyoMsatsi** [comment]
I will handle this.
