### ISSUE TITLE
Bug in the R-code for the `make_inventory_plot`

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#6000]
**Describe the bug**
There is a bug when running the Inventory Graph code for a "DOY-Year Plot" when there is no climatic year column defined.

**To Reproduce**
1. Go to `File > Import from Library ...` and import the `ghana_two_stations.RDS` data set. This data set has a date column and not a year column.
2. Go to `Climatic > Check Data > Inventory ...`
3. Enter the Date and Elements, and select `DOY-Year Plot` on the radio buttons
4. There is an error.

This error occurs here because there is not a year column defined in the climatic code in the data set.

The error stems from the R-code for the `data_object_R6.R` file and can be traced to line 2740.

```
      if(is_climatic) {
        if(is.null(self$get_climatic_column_name(year_label))) {
          self$split_date(col_name = date_col, year = TRUE)       # This line is of particular interest where the issue is.
        }
        year_col <- self$get_climatic_column_name(year_label)
      }
...
```

The issue is in the `self$split_date(col_name = date_col, year = TRUE)` since there is no parameter assigned to `year` in the `split_date` function. To fix this, this should read `year_val`.

**Comment by rdstern** [comment]
This is a great find and I like the resulting plot.  Here it is:
![image](https://user-images.githubusercontent.com/11226469/94773223-406f5700-03b3-11eb-859e-c144a2a75e83.png)

This also emphasises (to me anyway) that this is a very useful dialogue and one I cannot find in any package.  But it still needs a lot of improvements and is in an area that we have videos to produce for our contract.  For example we have no control on the size of the labels at the left or right of the dialogue.  They are a fixed size and are not readable.  The dialogue is already quite complicated, so any more flexibility would have to involve a sub-dialogue.  I assume the proper way to do this is to allow the "ordinary" Plot Options sub-dialogue to be included?  @dannyparsons says this is very complicated and he would probably have to do it.  So, I assume this would not be done this time round.  I would like more details from him and also whether there could be something simple (and quicker - perhaps a special **Inventory Options** sub-dialogue?

However this will then become a separate issue.  And this one can be closed once reviewed.
