### ISSUE TITLE
Small addition to Prepare > Check Data > Non-numeric cases

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6002]
@Patowhiz could you add the position control to this dialogue once @lilyclements changes have been merged.  Could you also add the line, so the default position for the saved variable is after the variable in the receiver, once that has been added.  Ideally add a comment to this line, so Lily can repeat it, in further dialogues that she will examine.

**Comment by Patowhiz** [comment]
@lilyclements @rdstern which PR should I wait for? Were the changes merged?

**Comment by lilyclements** [comment]
Yes changes have been merged. It was PR #5943

**Comment by Patowhiz** [comment]
This is not as simple as I thought. The dialog produces the following script;

```
# Code generated by the dialog, Find Non-Numeric Values

non_numerics_calculation <- instat_calculation$new(type="calculation", function_exp="is.na(x=Month) != is.na(as.numeric(x=Month))", calculated_from=list("Dodoma"="Month"), result_name="nonum", save=2)
data_book$run_instat_calculation(calc=non_numerics_calculation, display=FALSE)
summary(object=data_book$get_columns_from_data(data_name="Dodoma", col_names="nonum"))
rm(non_numerics_calculation)
```

@dannyparsons I can't find `data_book$run_instat_calculation` function in `instat_object_R6.R` file. I'm struggling to understand where this function is called from.

Below is how it's being set up in the dialog;

<img width="622" alt="runcal" src="https://user-images.githubusercontent.com/21179007/96180848-ba6b1880-0f3b-11eb-87b2-b609ec5ab6f4.PNG">

To enable the  `ucrSave` control dictate the position of the logical column created I think I need to modify `data_book$run_instat_calculation` function which I'm unable to find it.

**Comment by lilyclements** [comment]
I'm not sure the process to modify it, however, if it helps the `run_instat_calculation` function is written in the `calculations.R` file.

**Comment by Patowhiz** [comment]
@lilyclements thank you.
This is an interesting issue. Current backend functionality that we have for adding and at the same time reordering the columns could not support the feature requested here. 
I have extended that feature, will also be useful in future if we get a similar problem.
There was also a small bug in the `calculation.R`, but I've managed to add the functionality with major change in the  `calculation.R` script file

**Comment by Patowhiz** [comment]
@rdstern you may need to reopen this issue once PR #6067 is merged. We discussed with @dannyparsons in regards to the changes and modifications he has added to the R function that affects this dialog. And changes made in PR #6067 are good and necessary.
