### ISSUE TITLE
Small change to the File > Close Data Book option

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6003]
I assume this will be quick to do. It is an obvious one for @Patowhiz and check back if it is not a small task.

It correctly gives a warning that all data will be lost.  If I don't want to lose any data, then I save, and then use this option.  But it still asks.  Most software would detect that the data have not been changed and only ask if there were changes.  Could this check be made here, so it does not ask if the data have not changed since the last save.

**Comment by Patowhiz** [comment]
@rdstern Will do this once PR #6019 is merged. Changes will affect the same controls.
