### ISSUE TITLE
Correct Expressions Producing Errors On Clicking Try Control In Enter Dialog

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#6018]
Currently in the enter dialog, when you type in a plain numeric or character value as the expression (see screenshot below), the try control gives an error but on clicking ok the command runs successfully and generates a column filled with the typed value. 

The screenshots below can be used to reproduce the error.
Numeric expression
<img width="436" alt="error_1" src="https://user-images.githubusercontent.com/21179007/96009791-c24a9000-0e49-11eb-9c29-b0212902f45c.PNG">

Character expression
<img width="434" alt="error_2" src="https://user-images.githubusercontent.com/21179007/96010022-063d9500-0e4a-11eb-90e8-cccec78fee6b.PNG">

**Comment by Patowhiz** [comment]
We discussed with @Wycklife and found that this was not a problem in the dialog enter.
Upon looking into `ucrTry` control, it runs the script produced by the dialog as internal command through `frmMain.clsRLink.RunInternalScriptGetOutput() `, which internally runs the command through `capture.output( )` R command.

I investigated this further and found the problem is in the `capture.output( )` R command. So, in Rstudio when you run the commands; `capture.output(3)` or `capture.output( "survey")`. An error, `Error in capture.output("3") : bad argument` is thrown (see screenshot from R studio below).

VB.Net `clsRLink.RunInternalScriptGetOutput()` subroutine code;

<img width="408" alt="error_vb" src="https://user-images.githubusercontent.com/21179007/96011100-333e7780-0e4b-11eb-84ca-c8e3af0820d8.PNG">

Running `capture.output()` in Rstudio;

<img width="305" alt="errror_3_rstudio" src="https://user-images.githubusercontent.com/21179007/96011268-5f59f880-0e4b-11eb-8bfc-0143d7d81cf9.PNG">

Looking into the R utils package in regards to the `capture.output` command I found that there is an existing issue about this bug in the [R github repo](https://github.com/HenrikBengtsson/Wishlist-for-R/issues/54).  So according to the github reply [comment](https://github.com/HenrikBengtsson/Wishlist-for-R/issues/54#issuecomment-689008735), looks like the bug was solve in R 4.1.0. I think this should automatically work when R-Instat uses R version 4.1.0.

@rdstern @dannyparsons We could wait and test with that update or explore other ideas to make this work with the current R version used in R-instat. What are your thoughts?

**Comment by dannyparsons** [comment]
That's really great. I have known about this error in `capture.output()` for a while but didn't look into or expect it to be fixed in R! Great that it will be fixed in a new version. it's an annoyance for us but not that crucial as it's only the Try that uses it, so I think we can just wait for the release of the updated version of R.

**Comment by dannyparsons** [comment]
I don't see why we need another issue for this? We can assign this issue to Wycklife to check back on once R 4.1 is released.

**Comment by Patowhiz** [comment]
@dannyparsons yes. An alternative to this could be, to use `frmMain.clsRLink.RunInternalScript`. Runs the command and returns true or false. The downside is it doesn't capture any R error returned.

I'm happy to wait for the next version.

**Comment by dannyparsons** [comment]
yeah that's not really what we want so let's wait.

**Comment by shadrackkibet** [comment]
See another duplicate issue referenced above.
