### ISSUE TITLE
Small change in climatic summaries dialogue?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6025]
Can the data receiver in this dialogue be changed to become a multiple receiver?
I don't know now why we made it a single receiver - I think that was a mistake on my part.

If not easy, then leave it.  But it is a much used dialogue and would be needed for the SPI video as well as in its own right.

Ideally this would be for the forthcoming release?  Is that possible?

**Comment by dannyparsons** [comment]
The code will work exactly the same with multiple columns so it's a simple change on the dialog.
@africanmathsinitiative/developers Can someone available take this up? It's needed urgently but should be simple.

**Comment by Ivanluv** [comment]
Am looking at this

**Comment by shadrackkibet** [comment]
Sorry, @Ivanluv Since I am already working on moving missing values options from the sub-dialog which involves this dialog, I suggest to work on this since I already have an open PR on this dialog.

**Comment by Ivanluv** [comment]
> Sorry, @Ivanluv Since I am already working on moving missing values options from the sub-dialog which involves this dialog, I suggest to work on this since I already have an open PR on this dialog.

Okay
