### ISSUE TITLE
Option to add a method ".IsCurrentReceiver()" to ucrReceiver controls.

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#6027]
In the `Define Surv Object` dialog, I think there needs to be a way to determine which ucrReceiver is currently selected.

For example, if the "Interval" button is checked, then there are three receivers: "Entry Time", "Exit Time", and "Event".

![image](https://user-images.githubusercontent.com/21180424/96441445-7315ae00-1201-11eb-868a-78c93564b6dc.png)

If "Interval2" is checked, there are two receivers: "Entry Time" and "Exit Time".

![image](https://user-images.githubusercontent.com/21180424/96441531-904a7c80-1201-11eb-9699-05faf25b9914.png)

The usual way we handle this in R-Instat does not have more than one receiver present across different radio buttons. In this dialog, if the user has selected "Entry Time" or "Exit Time" on the "Interval" button, then the current selection should stay highlighted if they then click the "Interval2" button.
If instead the user has selected "Event" on the "Interval" button, and then click the "Interval2" button, the "Exit Time" receiver should be highlighted. Hence, I want to run a line like:

```
If ucrInterval.Checked AndAlso ucrReceiverEvent.IsCurrentReceiver() Then
  If ucrInterval2.Checked Then
    ucrReceiverExitTime.SetMeAsReceiver()
  End If
End If
```

However, there is not a way (currently, to my knowledge) to check which ucrReceiver is currently highlighted (i.e., there is not a `ucrReceiverEvent.isCurrentReceiver()` option).
Unless there is an alternative way around this, can a `.IsCurrentReceiver()` option be added to the ucrReceiver controls?

**Comment by shadrackkibet** [comment]
@lilyclements  I found a check to do this. Try doing something like ` ucrSelector.CurrentReceiver Is ucrReceiver`

**Comment by lilyclements** [comment]
Great thanks! It is under
`ucrSelectorFitObject.CurrentReceiver.Name Is "ucrReceiverEvent"`
