### ISSUE TITLE
Another very small change in frmmain climatic

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6031]
Whole @shadrackkibet is changing frmmain in #6030 could this one be done at the same time.

In Climatic > Check Data could you please swap Fill Missing Values and Display Daily.  So Display Daily goes above the line and Fill Missing Values goes below.

**Comment by shadrackkibet** [comment]
This should be closed.

**Comment by shadrackkibet** [comment]
@rdstern @dannyparsons @lloyddewit?
