### ISSUE TITLE
Minor oddity with the new startup window in R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6045]
I have given it the label here reogrid as representing the data window.
There are 3 parts to the content of this new window:

a) Shortcuts to File New, Open and Library
b) Recent files
c) Help information

Now, when you start, a) and the heading for b) and c) appear immediately.  Then there is a pause - a few seconds and then the files for b) appear.

To me this looks odd.  I don't know if you agree?

If so, then could we simply swap b) and c)?  Then it will simply add the recent files to the bottom, when they appear.  And that is at the same time as some commands appear in the output window - so logical and fine?

**Comment by Patowhiz** [comment]
@rdstern I could look into speeding up the display of (b), I didn't do that because I would have had to restructure the sequence of things when starting R-Instat, which would have probably delayed the PR.

Alternatively I could also ensure the heading is only displayed when the recents have loaded. Or rather do both.

I think swapping (b) and (c) would look odd from a UI amd UX perspective.  The idea behind the current design is, the user sees links related to files, then followed by links related to other parts of the software.  Swapping will disorient the flow.

@rdstern I'm happy to do either.

**Comment by rdstern** [comment]
I am happy with either.  And no urgency on this.  It is purely cosmetic and is working fine.  I am using it and am really pleased with the way it works.

**Comment by Patowhiz** [comment]
@rdstern I've made the recent header and files to be displayed when R-Instat is fully "initialised" (and almost the same time the output window displays the initial command). I realised doing so is much safer (`R` has to be initialised first before any opening of file operations) and won't deviate from current loading events much.

I've also optimised the code to prevent unnecessary calls of refreshing the displayed lists of recent file.

The recent files section should now "feel" more natural from the end user perspective.

**Comment by dannyparsons** [comment]
That's an improvement, but it still looks odd for the 3 sections not to appear at the same time. Can you delay the Start and Help sections to appear at the same time as the Recent section?

**Comment by dannyparsons** [comment]
@Patowhiz can you make this change soon? It affects the loading on videos so important to do soon.

**Comment by Patowhiz** [comment]
@dannyparsons Yes. So when starting R-Instat, do we let the grid be displayed with a "No Data Loaded" label, or we just make the left side be blank? i.e until R has fully loaded.

**Comment by dannyparsons** [comment]
Blank until the rest of loaded, the "No Data Loaded" label should be removed.

**Comment by Patowhiz** [comment]
Below is a screenshot of R-Instat during startup. The menu items become visible when recents have fully loaded.

<img width="650" alt="startup" src="https://user-images.githubusercontent.com/21179007/99076393-1f15a380-25cc-11eb-87ff-31f9167bca0e.png">

**Comment by dannyparsons** [comment]
that looks good
