### ISSUE TITLE
Adding three plots dialogs from the circular package in Structur>Circular menu

### ISSUE THREAD

**Issue by Wycklife** [africanmathsinitiative/R-Instat#6060]
These dialogs, Rose Plot (same as wind rose?), Density Plot and scatter Plot already have a placeholder under Circular sub menu in the structured menu. I have been comparing these plots from the circular package and reproducing the same using ggplot2 package. I find it efficient, consistent with our graphics and flexible to extend these plots using ggplot2 rather than those in circular package which uses base graphics. Since the circular package doesn't cope with multiple stations which is of interest to us, I therefore suggest we reproduce these graphics using the ggplot2 system. Initially I am going to proceed with implementation of these dialogs. @rdstern @dannyparsons  what  are your thoughts on this? I also had this discussion with @lilyclements elsewhere.

**Comment by lilyclements** [comment]
Would you mind sharing the code for doing these in the `ggplot2` package? (Just more out of interest than anything else).
