### ISSUE TITLE
Minor addition in the Climatic > Prepare > Climatic Summaries dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6068]
This is to add a 4th button - really the first button - at the start of the top of the dialogue.  It is called Station.  The other 3 buttons will have to become a bit smaller to keep the same size for the dialogue.
The default is still the Year button.
If the Station option is chosen then I am happy that the same other items remain visible, as are on the Year button.  But the Station must be completed for Ok to be enabled.  I don't think that is necessary in general.  

It then works just the same, but for overall summaries - so there will be one row per station.  In a file with just one station, then there is just a single row in the summary data.

I hope this will be easy.  It is needed for one of the videos.  It can be checked by comparing it to the main summary dialogue, where just the Station is used as the By variable.

I assume this will be quite quick for @Ivanluv to do?  Perhaps @shadrackkibet could confirm that?

**Comment by shadrackkibet** [comment]
Yes, this is easy to implement. The summary R function can cope well with this functionality. For example for the mean, maximum, count of non-missing and sum will look like this.

```
data_book$calculate_summary(data_name="guinea_2", columns_to_summarise="rain", factors="station", na.rm=TRUE, summaries=c("summary_mean", "summary_max", "summary_count_non_missing", "summary_sum"), silent=TRUE)
```
Only that I don't see the reason why we need other receivers like Date, DOY and Year etc. It won't be used anywhere in code. Perhaps we just keep them for consistency.

**Comment by shadrackkibet** [comment]
@Ivanluv any progress on this?

**Comment by Ivanluv** [comment]
@shadrackkibet  am looking at this
