### ISSUE TITLE
Improved Copy from reogrid etc

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6071]
I am very happy with the new facilities for pasting into a grid.

I would like to check on the reverse operation, namely copying from the grid - and presumably also from the column and sheet metadata - as an export facility

It currently seems to work pretty well already, but it doesn't copy the names of the variables.  In the metadata the situation is (not surprisingly) the same.

**Comment by dannyparsons** [comment]
@Patowhiz could you check in the reogrid functionality if we can copy the column headers? If not, we may have to implement some of the copying manually, which would be less desirable. We can also request features on the reogrid repo if needed.

For implementation, my suggestion would be that if the first row is part of the selection when copying then that should include the column headers as well.

**Comment by Patowhiz** [comment]
Looking into this

**Comment by rdstern** [comment]
I have found another oddity in the copy from reogrid, so perhaps this can be examined at the same time?  
a) Open research funding rates from dslabs package (add the package if it isn't yet there.)
b) Add a new variable Prepare > Column: Calculate > Regular sequence with 1, 2... 9
c) Make it a factor
d) Copy the first variable with the labels into the clipboard.  
e) Use the levels/labels on the right-click, the labels are 1 to 9.
f) Paste the labels into the dialogue.
g) Press OK - the labels are ignored - still have 1 to 9.
h) Paste the labels into anywhere in Excel
i) Copy from Excel
j) Paste into the labels in Levels/Labels - looks same as before.
k) Press OK - now it works!

A puzzle.  I can demonstrate if you wish!
