### ISSUE TITLE
Trivial change in Prepare > Text > Split

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6074]
![image](https://user-images.githubusercontent.com/11226469/98459523-84643180-2193-11eb-88a6-53e5ddb6916e.png)

What has happened to the Position control here.  Usually it is the right size, but just not quite aligned.  I would love that to be corrected.   But here it has grown fatter and just looks messy!  Could it be resized please.

**Comment by shadrackkibet** [comment]
@HawardKetoyoMsatsi this is another quick one and easy to fix. Are you happy to take over?

**Comment by HawardKetoyoMsatsi** [comment]
@shadrackkibet sure, I will take over this over and fix it.

**Comment by Patowhiz** [comment]
@rdstern I think this issue can now be closed. It was fixed by PR #6162, done by @HawardKetoyoMsatsi .
