### ISSUE TITLE
Climatic boxplots possible improvements

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#6081]
There is a date receiver on the climatic boxplots dialog but it doesn't seem to do anything. Is it needed?

**Comment by dannyparsons** [comment]
Couple of other things from the dialog:

- When having vertical x axis tick marks we should add ` vjust = 0.5` and `hjust = 1` so that the labels line up nicely
- In facets, should we set `drop = FALSE` so that empty factor levels are not removed (especially when using the omit below option)> I got confused with this graph missing two months because I filtered out dry days
![image](https://user-images.githubusercontent.com/11214914/98803458-ad432b80-240c-11eb-9da9-43f83b3aca50.png)

**Comment by rdstern** [comment]
a) I like the idea of lining up.
b) Agreed that Drop = FALSE would make it all clearer.  Is that option available under facets in case we wanted it otherwise?
c) I am still hoping that the date will be useful in this dialogue, because I would like it to be in the label for outliers, etc.

Another question on the graphs - not needed usually for this dialogue.  Can the depth of the heading be altered?  I assume so, but is it easy?

**Comment by dannyparsons** [comment]
Sounds good.

@africanmathsinitiative/developers could someone make these changes on climatic boxplots?

> When having vertical x axis tick marks we should add vjust = 0.5 and hjust = 1 so that the labels line up nicely

and, add `drop = FALSE` to the facet functions.

I'll make a separate issue for adding `drop` to the facets tab on the Plot Options subdialog so we have this option generally.

We'll leave the date receiver then as we hope to use it in future.

**Comment by shadrackkibet** [comment]
I am also taking this up. In addition to the above, I will change `ggplot2::xlab("")` into `ggplot2::xlab(NULL)`. The latter gives more room for the graph below the x-axis.

**Comment by dannyparsons** [comment]
That would be good to give more space. I think the "correct" way to do this in ggplot would be `+ theme(axis.title.x = element_blank())`. That would then be consistent with the themes dialog. Does that also give the extra space? If not, I'm happy with your solution.

**Comment by rdstern** [comment]
@shadrackkibet it would be good to merge these points.  Did you see @dannyparsons query above?
