### ISSUE TITLE
Add drop parameter to facets on Plot Options subdialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#6083]
`facet_wrap()` and `facet_grid()` have a `drop` parameter: 

> If TRUE, the default, all factor levels not used in the data will automatically be dropped. If FALSE, all factor levels will be shown, regardless of whether or not they appear in the data.

This is a useful option to have, especially when filtering. I suggest this is added to the Facets tab on the Plot Options subdialog as a checkbox: "Drop empty factor levels". Default is checked as in R.

@africanmathsinitiative/developers can someone take this up? @maxwellfundi could also support this

**Comment by shadrackkibet** [comment]
I am taking up this.
