### ISSUE TITLE
Removing a filter from Data options and Add button

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#6085]
Currently, when you got a filter say `Filter2` you can just add it into the receiver from data options subdialog and once you click return the filter is activated (red rows on the data frame) and also it remains on the receiver. Can I be allowed to do the reverse? i.e when a filter is already added into the receiver and then cleared, once return is clicked then that specific filter is then removed if active? A tricky feature request!

I also claim that **Add** button should be added here for the filters selector. It is not trivial for the user to know that you have to double click on the filter for it to be added into the receiver especially for users who are used to **Add** button from the selector.

![image](https://user-images.githubusercontent.com/26301973/98934127-a5f64d80-24f2-11eb-9cc9-3f348a111951.png)

**Comment by shadrackkibet** [comment]
@rdstern @dannyparsons any comments?

**Comment by shadrackkibet** [comment]
@rdstern I thought of using a button instead of clearing of the receiver to remove the current filter. When clicked, it removes the current filter and also clears the filter receiver so that the filter is not activated on return. What are your thoughts?
![image](https://user-images.githubusercontent.com/26301973/106114499-a94bbd80-6160-11eb-85dc-04413df8e246.png)

**Comment by rdstern** [comment]
@shadrackkibet I would be quite happy with that.  Currently I use the no_filter to do that.  Clearing within the dialogue would save pressing Return and then having to go back.  @dannyparsons do you agree that we add that button?
