### ISSUE TITLE
Add Not condition to filter

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6101]
Could this be really easy to add.  For now I suggest it could be below the & and or option and we could get rid of the Remove Condition button for now.  It would just reverse the condition, by adding` !`  in front of the condition.

I give an example that I needed recently.  Climatic data from Garoua has 9 days when tmin > 100 degrees.  That is an easy condition to examine.  Then I would like the opposite, namely !(tmin > 100).  That is not the same as (tmin <= 100), because the NAs are also omitted.  So (without the NOT) I have to do (tmin <= 100 ) & (tmin !is.na).

That's not too bad.  But I actually had (tmin>100) | (tmax >100).

I can't see how to do the reverse of that in the filter.  Easy if NOT is available.

While making changes I notice that the preview of a condition such as (Tmin !is.na) in the sub-dialogue appears as just (Tmin).  It is fine in the main dialogue.

**Comment by shadrackkibet** [comment]
@rdstern did you confirm if we still need this?

**Comment by rdstern** [comment]
@shadrackkibet yes please.  It is described in #6101 .  Good example there too!  I hope all that is needed is to add ! to the keyboard?
