### ISSUE TITLE
New bug on PICSA rainfall graph

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6106]
[four_stations_raindays.zip](https://github.com/africanmathsinitiative/R-Instat/files/5602352/four_stations_raindays.zip)

In the graph above I used multiple y of the 3 levels of raindays.  The Name (Station) was a facet, but I don't think that is relevant.

It works fine until I add a line for the mean.  Then it gives an error as follows:
![image](https://user-images.githubusercontent.com/11226469/100341783-f2eb2100-2fd4-11eb-8f26-7243163da14f.png)

**Comment by rdstern** [comment]
While editing I used facets from the main dialogue.  the default, with 2 stations is for the facets to give 2 columns.  The more obvious is 2 rows, so the years can be compared at the 2 sites.  Could there be a similar pull-down control as in the climatic boxplot dialogue to specify the way of doing facets?

**Comment by N-thony** [comment]
@dannyparsons I would like to work on this issue.
