### ISSUE TITLE
Packages for the next version

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#6108]
@africanmathsinitiative/developers please add any new packages for the next version here. Also, add a link to any PR that uses the package.

**Comment by shadrackkibet** [comment]
- texmex #6107

**Comment by dannyparsons** [comment]
- `zyp` for dialogs on NCMP coming soon

**Comment by Ivanluv** [comment]
- `DEscTools` and `MKinfer` for the one variable fit model  #6004

**Comment by dannyparsons** [comment]
`texmex` and `zyp` added to 0.6.5

`DEscTools` and `MKinfer` can be added in 0.7.0 if PR is merged by then.

Closing this and creating a new issue for next release.
