### ISSUE TITLE
Adding Sadore dataset to  the R-Instat library

### ISSUE THREAD

**Issue by Wycklife** [africanmathsinitiative/R-Instat#6112]
This is a new climatic dataset from Niger. It should be added in the Instat > Browse > Climatic > Niger > Sadore >Sadore.RDS.

**Comment by rdstern** [comment]
Just to mention not to have a special directory called Sadore.  It can go into the Niger directory along with other datasets from the same country.

**Comment by lloyddewit** [comment]
@Wycklife This PR seems to be covered by PR #6113. Can we close this PR? thanks

**Comment by Wycklife** [comment]
@lloyddewit This is an issue being fixed by PR  #6113.

**Comment by lloyddewit** [comment]
@Wycklife yes, you are correct. Sorry I misread this as a PR. I deleted my comment above.
