### ISSUE TITLE
Problem in code for Rainfall quality control

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6115]
[niger_4_dly_forqctest.zip](https://github.com/africanmathsinitiative/R-Instat/files/5657361/niger_4_dly_forqctest.zip)

Here is the file I have been using.  

The test that is failing is the detection of a consecutive sequence of rain days.  The default test is that a sequence of more than 10 consecutive rain days is filtered and reported as suspicious.  
Here is the code that is used:

```
# Code generated by the dialog, Climatic Check Data Rainfall
cumulative_calculation <- instat_calculation$new(type="calculation", function_exp="cumsum(rain > 0) - cummax(((rain > 0) == 0)*cumsum(rain > 0))", calculated_from=list("Data"= "rain"), result_name="Wet_days")
cumulative_test_calculation <- instat_calculation$new(type="calculation", function_exp="Wet_days > 10", sub_calculations=list(cumulative_calculation), result_name="wet_days")
grouping <- instat_calculation$new(type="by", calculated_from=list("Data"="Name"))
rainfall_filter <- instat_calculation$new(type="filter", function_exp="wet_days", sub_calculations=list(cumulative_test_calculation), manipulations=list(grouping), result_data_frame="qcRain", save=2)
data_book$run_instat_calculation(calc=rainfall_filter, display=FALSE)

rm(list=c("rainfall_filter", "cumulative_test_calculation", "cumulative_calculation", "grouping"))

```

The reason it doesn't work is because of the missing values in the data.  So I fixed the problem, by leaving the code as above and just replacing the missing values by zero, i.e. a not-rainy day.  Then it correctly detects 2 months in Niamey and Zinder when clearly the wrong variable was entered as rainfall.  So it should be a simple fix.

**Comment by dannyparsons** [comment]
That's right, missing values make `cumsum` return all `NA`s after the first missing value. `cumsum` doesn't cope with missing values other than this. We could fix in a number of ways, just need to think what's the most usable.

**Comment by rdstern** [comment]
@dannyparsons a second problem with this dialogue is the detection of dry months.  I suggest this should be simpler to solve.  It works fine if you select months to omit from the check.  But otherwise it finds no problems and so always delivers an empty data frame.  That's misleading.  I wonder who could fix that?

And @dannyparsons on the missing value problem above there must be a simple function/calculation to replace missing by zero (on the fly) before doing the cumsum.  I am happy you want to have an ideal solution, but could we get someone to implement this in the meantime?  It is in error in the current version.

**Comment by shadrackkibet** [comment]
@dannyparsons on the first problem. I think we can easily fix it with `ifelse()` what do you think?
```
x <- 1:100
x[c(20,15,35,49)] <- NA
cumsum(ifelse(is.na(x),0,x) > 0) - cummax(((ifelse(is.na(x),0,x) > 0) == 0)*cumsum(ifelse(is.na(x),0,x) > 0))
```

**Comment by shadrackkibet** [comment]
The second problem is as a result of the setup of the dialog which should be easy to fix.

**Comment by shadrackkibet** [comment]
@rdstern this dialog is mainly meant for rainfall Qc I think it should autofill element receiver with rainfall.

**Comment by shadrackkibet** [comment]
@HawardKetoyoMsatsi are you able to work on this? Happy to provide support if needed.

**Comment by HawardKetoyoMsatsi** [comment]
Sure, Let me fix this this.

**Comment by HawardKetoyoMsatsi** [comment]
I would like someone else take up this task. I may not be able to handle it.

**Comment by rdstern** [comment]
Great that the first - and most important part of this issue is now fixed.
@shadrackkibet said there would be a second pull request for the second point.  Sorry, but from its repeated use I have a third point that should be very simple to add, hopefully at the same time.  
The second test is the number of identical values and 2 is the default for rainfall.  It then says (ignoring zero).  In the command this is the condition `> 0`
Could (ignoring zero) be replaced by > and then a filed with a number - default 0, or 0.05.  It has to be numeric and I find I would like to ignore identical values < 1mm so I would then have 0.95.  I would like the minus sign to be allowed, so we could have `-0.05` if we wanted to include zeros.

**Comment by shadrackkibet** [comment]
The duplicate issue here #5017.

**Comment by dannyparsons** [comment]
Shouldn't there also be a rain day threshold for the consecutive option as well? 
If so, I would suggest there should be a dialog option for rain day threshold that will apply to all the options, instead of multiple options for this. Slightly less flexible but clearer I think.

Also, for "Dry Month" there is a label called "Missing Values Threshold" but what it's used for is the monthly rainfall total. So shouldn't this be something like "Monthly rainfall less than"?

**Comment by shadrackkibet** [comment]
> Shouldn't there also be a rain day threshold for the consecutive option as well?
If so, I would suggest there should be a dialog option for rain day threshold that will apply to all the options, instead of multiple options for this. Slightly less flexible but clearer I think.

@rdstern any comments on this? If you agree then I treat this as a separate PR and would essentially need reorganizing controls in the dialog.

> Also, for "Dry Month" there is a label called "Missing Values Threshold" but what it's used for is the monthly rainfall total. So shouldn't this be something like "Monthly rainfall less than"?

I will included this change in my current PR.

**Comment by shadrackkibet** [comment]
Opened a new issue outlining what is remaining. Therefore I am going to close this.
