### ISSUE TITLE
Improve design of SPI/SPEI dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#6117]
Once the SPI/SPEI dialog updates are merged here #6116 the dialog design could be improved. I suggest:

- The SPI/SPEI option becomes button type radio buttons at the top of the dialog
- Kernel Type becomes a combo box
- Time Scale should include "Month" in some ways as it's a number of months. Possibly "Time Scale (Months)"

It would be good to consider the general positioning of the options on the dialog to see if there's a nicer way to organise them.

@lilyclements are you able to take this task?

**Comment by lilyclements** [comment]
Happy to take this on
