### ISSUE TITLE
NCMP Dialogs

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#6131]
This is for a new menu of dialogs: Climatic > NCMP. NCMP stands for National Climate Monitoring Products. They are defined by WMO https://www.metoffice.gov.uk/hadobs/opace2_tt_ncmp/. In the folder here https://github.com/africanmathsinitiative/R-Instat/tree/master/instat/static/InstatObject/R/Backend_Components/NCMP each file defines a function which is based on R scripts produced by WMO for NCMP.

The calculations follow a series and the dialogs needs to be done in order. The output from previous steps are the input to the next steps.

So there will be 6 dialogs in the sub menu:
- Indices
- Variogram
- Region Average
- Trends Graphs
- Count Records
- Summary File

Here is a script showing how to use the functions [script.zip](https://github.com/africanmathsinitiative/R-Instat/files/5721139/script.zip). Here is the data used in the scripts [monthly (2).zip](https://github.com/africanmathsinitiative/R-Instat/files/5721142/monthly.2.zip)

In the R files I've tried to describe all the parameters so the dialog designs should be quite straightforward. The input are mainly data frames and column names. I suggest we don't include the optional parameters on the dialogs for now, so that we get main functionality working first.

All but the last function requires station metadata input. I suggest this could be done on a sub dialog, similarly to as described for another dialog https://github.com/africanmathsinitiative/R-Instat/issues/6110. Doing it this way means we only need to create one subdialog and use it in all the main dialogs that need it. The parameters are consistent across the functions.

Most of the functions have a `ncmp_folder` parameter which should be a folder selection. See the Import from IRI dialog for how this is done.

The design should be straightforward based on the parameters. There are a couple of dialogs with some differences:

**Region Average**
For `p4_region_average` there are two data frame inputs required (a2 and a3). But for a3 we don't need to choose any columns so I suggest to have the normal controls for a2 data and columns, and then use a `ucrDataFrame` to choose a3 data. That should mean there's enough room on the dialog.

**Trends Graphs**
Here we need a3 and a4 data and columns, so I suggest we use two `ucrSelectorByDataFrameAddRemove` controls, so the dialog will sort of be in two sections, like Export to CPT dialog.

**Comment by lilyclements** [comment]
Looking at these nuds for the start/end year options throughout the various R-codes. I have some questions:

1. Where these nuds are optional, should I have a checkbox leading to the nud to ask if they want to alter the value?
2. What should I set the default values as? Additionally, I'm not sure what the minimums/maximums should be. I can see what works with the Ghana sample data set given, but does this apply to other data sets?

Additionally, how should I handle the metadata sub-dialog and the TestOK - are you happy with it giving an error if you click OK but don't fill in the metadata sub dialog?

**Comment by dannyparsons** [comment]
The optional nuds can be left out for now. We need to think a bit more how we want to set those.

For the subdialog, maybe something similar to the Import NetCDF dialog with a message box. It doesn't need to be that detailed though to give the missing information.
![image](https://user-images.githubusercontent.com/11214914/103297299-edc42c00-49ef-11eb-9836-99b2df11fcdf.png)

**Comment by lilyclements** [comment]
> For the subdialog, maybe something similar to the Import NetCDF dialog with a message box. It doesn't need to be that detailed though to give the missing information.

Thanks for this. As a small side-note "until" is spelt wrong in that dialog message. Is it okay for me to fix this in the PR with the NCMP dialogs, or should I do a new PR?

**Comment by dannyparsons** [comment]
That could be in the same, thanks.
