### ISSUE TITLE
bar charts needs corrections and possibly single_multiple option

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6135]
I have indicated @dannyparsons, not that I expect him to do this - and it isn't urgent - but to confirm the two points below a) that it is easy? b) Good to not disable the option buttons.

There are 2 bar chart dialogues.  One in the Describe > Specific and the other in Describe > General > Use Summaries.
In the other graphs the main receiver has a Single/Multiple option.  This is absent from the bar charts.  I needed it recently and so had to do stacking first.  If simple, then please could we add this feature?

At the same time the Multiple option disables the Plot Options and also the special options for that type of plot.  I still use those by switching between single and multiple.  Could this "feature" be reviewed?

[ghana_2_stations_for_rainnormals.zip](https://github.com/africanmathsinitiative/R-Instat/files/5746266/ghana_2_stations_for_rainnormals.zip)

Here is the data file I used.

Here is an example of the graph I wanted:
![image](https://user-images.githubusercontent.com/11226469/103197730-87031d80-48de-11eb-8e92-b60bc5bd7228.png)

**Comment by rdstern** [comment]
@N-thony there is an urgent issue with the bar charts that I mentioned in the discussion in #6488 - see the example there.  It may take longer to include the multiple receiver - and may need help from @dannyparsons or shadrack, but checking on the positions of the controls should be quick to do.

**Comment by rdstern** [comment]
@N-thony after discussing with @volloholic it is clear that this is difficult conceptually and we are in danger of going round in circles.

Here is where I have got to, so far.

a) A distinction is between Frequency and Value.  That's currently what we have as the Y-variable as Count or Variable.  So we effectively move that control to the top and replace the Bar Chart buttons by 2 buttons, namely Frequency and Value.
b) Then the X-Variable label is replaced by Y-Variable: when you have the value button.
c) And this is a Single/Multiple control - as it is for most of the other plotting dialogues.  The idea is that when you have the Frequency button, then this is what is the X-Variable now.  When you have the Value button it is what is currently in the Y-variable. 
d) We still need the Position options for both of these buttons.  Now we have got rid of the Y-value control, there is more space on the right-hand side, so it could stay there.  However, with the first button (Frequency) it is irrelevant unless the Optional factor is chosen.  So it should go below that.
e) Then an important new one, which needs to be specified in detail.  On the left we will have a Label label! This is followed by a pull-down giving popular options for the labelling of the bars.  That's after the next round of improvements above are merged.  
f) Also for later we currently have Flip Coordinates as a simple checkbox.  That will become Orientation.  It will hopefully change from a checkbox to multiple options, namely Horizonal, Vertical, Circular.  Hopefully the circular will just move to polar coordinates.  Hopefully this will give a pie chart for s simple bar, and a donought chart if an extra factor is used.  Then we can get rid of the pie chart button at the top.  But keep it there for now.

**Comment by rdstern** [comment]
I hope an improved version of the bar charts can be merged.  This is stoll work in progress.

a) I would like back-to-back bar charts.  This would include population pyramids and other bar charts where one side is for males and the other for females.

Here are some examples:
![image](https://user-images.githubusercontent.com/11226469/121548024-94334500-ca04-11eb-95ff-33df061967d7.png)

Checking on google for back-to-back bar charts gives a lot of support.  One complication is to allow the x-axis to remain positive as shown in the examples above.  So it goes up for both men and women, etc.  

One solution I have seen is to use 2 facets for these, but that is messy in our system as I may want to use facets for other things.  My real dilemma is also how to include these in the bar chart dialogue?

Second is the issue of pie charts (and donut charts - including nested donut charts.  They could be relatively easy if they are (as now) further radio buttons at the top of the bar chart dialogue.  But they are essentially bar charts with polar coordinates.  Could they therefore become an Orientation option, which includes the coord-flip, and also polar together?

![image](https://user-images.githubusercontent.com/11226469/121549932-2daf2680-ca06-11eb-9432-31e3aa8464e8.png)

(While there I also wonder about what sort of graph the lines above are?)

Compared to these, the options related to adding labels is easier.  We have a labels checkbox that adds geom_text.  This can be done in all generality through the sub-dialogue, but it would be good to start this off on the main dialogue.  I assume what is shown is the count, or the value.  Then there is the position of the label, the size and the colour.  How can we do this simply, even if more options would require the sub-dialogue?

I am adding @shadrackkibet and @lilyclements in the hope that they may be interested to help.

**Comment by rdstern** [comment]
I have been reflecting and discussing the above observations in more detail.  @lloyddewit I suggest this issue could be closed once the existing changes in the bar charts are done.  There remain three challenging controls to add.  I suggest they each be their own issue instead.

**Comment by lloyddewit** [comment]
> 
> 
> I have been reflecting and discussing the above observations in more detail. @lloyddewit I suggest this issue could be closed once the existing changes in the bar charts are done. There remain three challenging controls to add. I suggest they each be their own issue instead.

@rdstern Do you know which PRs implement the 'changes in the bar chart'? Or are these PRs not yet opened?
I assume that the 'three challenging controls' are not yet started.

**Comment by rdstern** [comment]
@lloyddewit two of them are started, namely back to back bar charts are in #6525 and pie charts are in #6526 .  I am still reflecting on the important - and large - area of adding labels - that's the third option.
