### ISSUE TITLE
Small problem to fix on Climatic > Dates > Infill dates

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6156]
You will see this with any example of climatic data.  It has appeared recently.  The command works, but adds an extra odd liner in the output window.  Here is an example.  I think it is the new use of the dplyr commands.  It is the summaries line below which appears every time.

```
# Code generated by the dialog, Fill date gaps
data_book$infill_missing_dates(data_name="Quel", date_name="date", factors="station")

`summarise()` ungrouping output (override with `.groups` argument)
No missing dates to infill
```

**Comment by shadrackkibet** [comment]
Can I suggest this to be taken up by @HawardKetoyoMsatsi?
