### ISSUE TITLE
Filter doesn't overwrite?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6181]
I have considered this as a small bug - but you may disagree?  

I had filter1 for a data frame.  It was incorrect.  So I chose to name the new filter as filter1 to replace it.  It doesn't allow me to do that.  I think it should.

We can delete filters now, so I assume this should be an easy change?

**Comment by shadrackkibet** [comment]
@rdstern can you demonstrate this bug elsewhere? perhaps a skype? Looks like it is an easy one to fix but I can't seem to replicate it. Is it from the filter dialog or renaming of filters?

**Comment by shadrackkibet** [comment]
I now understand this problem. It is actually an issue with preview update and not filter overwrite. You can already overwrite a filter silently. I thought this is something that the user might not want and therefore good to alert the user with a message in the output window when this happens.
