### ISSUE TITLE
Climatic boxplot dialog generates 'argument "x" is missing, with no default' error

### ISSUE THREAD

**Issue by lloyddewit** [africanmathsinitiative/R-Instat#6185]
This bug was identified by @lilyclements when she peer reviewed PR #6086 'Improvements on climatic boxplots (adding drop, vjust, hjust and xlab(NULL))'. @shadrackkibet suggested that we document this bug as a new issue.

@lilyclements wrote:

> While exploring things for 1. I came across a bug (which occurs whether it is `as.factor` or `make_factor`).
On first opening, input a variable under "Date", "Element", and "Year". Keep the corresponding ucrInput for "Year" as "None", and do not input a variable under "Within Year". Click OK and there is an error since no parameter is read into the `as.factor` function (It is important that this is done on the first opening of the dialog since it doesn't occur if I change the ucrInputYear to "X Axis" and then back to "None").
The error only occurs for me if "Within Year" is never filled. Try with a data set that doesn't autofill the receivers and then only fill in "Date", "Element", and "Year".
```
Error in is.factor(x) : argument "x" is missing, with no default

The error occurred in attempting to run the following R command(s):
dodoma <- data_book$get_data_frame(data_name="dodoma")
last_graph <- ggplot2::ggplot(data=dodoma, mapping=ggplot2::aes(y=rain, x=as.factor())) + ggplot2::geom_boxplot() + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text(angle=90, hjust=1, vjust=0.5)) + ggplot2::xlab(NULL)
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="dodoma")
data_book$get_graphs(data_name="dodoma", graph_name="last_graph")
```
Please see PR #6086 for additional supporting information.

**Comment by rdstern** [comment]
@N-thony perhaps you could examine this issue above as some others with the same controls are also corrected.
a) The Station and Year controls do not remember their settings.  For example, with multiple stations - e.g. Niger data, set station to Facet wrap and it works fine.  When you return it has reset to null.  Same for the Year control.  Could they remember.
b) A minor point is not to have any element in the control.  Currently it is PRECIP and that is not a good default.  Better to have nothing.

**Comment by N-thony** [comment]
> @N-thony perhaps you could examine this issue above as some others with the same controls are also corrected. a) The Station and Year controls do not remember their settings. For example, with multiple stations - e.g. Niger data, set station to Facet wrap and it works fine. When you return it has reset to null. Same for the Year control. Could they remember. b) A minor point is not to have any element in the control. Currently it is PRECIP and that is not a good default. Better to have nothing.

@rdstern @lloyddewit I did the investigation on the item a) and I found that this bug of always keeping ucrInputStation and ucrInputYear with `None` as a selected item on reopening of the dialogue is due to the translation. If @lloyddewit agrees with this I can directly fix it in my PR by setting those two controls in the database `DoNotTranslate` or it can be done in a separate PR.

**Comment by lloyddewit** [comment]
> @rdstern @lloyddewit I did the investigation on the item a) and I found that this bug of always keeping ucrInputStation and ucrInputYear with `None` as a selected item on reopening of the dialogue is due to the translation. If @lloyddewit agrees with this I can directly fix it in my PR by setting those two controls in the database `DoNotTranslate` or it can be done in a separate PR.

@N-thony Thank you for identifying this. Please fix by updating the database as you suggested, in a separate Pr if possible. In your PR, please:
- include screenshots showing exactly what changed in the database
- also update the `translations/translateIgnore.txt` file to ensure that these controls won't be translated in future R-Instat versions

Thanks!

**Comment by ChrisMarsh82** [comment]
@shadrackkibet to check to see if fixed

**Comment by shadrackkibet** [comment]
The initial bug reported by Lily above still exist. Hence the reopen.
