### ISSUE TITLE
Add at least quintiles to summary statistics

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6194]
The WMO normals include quintiles.  In our videos I followed the lead from the US and produced quartiles instead.  The main WMO reviewer commented:

"The climate normals video re precipitation demonstrates the calculation of quartiles, following the US approach. It is rightly stated that WMO recommends quintiles. I guess,  R-Instat has the ability to calculate quintiles too, hasn't it? Your confirmation will be welcomed."

We can already produce any percentiles, so quintiles - but only 1 at a time.  We can produce both quartiles together, so that's easier.  I suggest as follows:

a) On the main summary sub-dialogue we move the Range up so the block for Min, Max, Range is smaller.  We also decrease the space between blocks so there is plenty of room for another.  
b) Then there is a choice.  We could simply:
Option 1: Add another block with the label Quintiles.  Then it has 4 entries, namely 20%, 40%, 60%, 80%.  The names could be p20, p40, p60, p80.
Option 2:  Change quartiles to Quartiles & Terciles - often Terciles are used in the seasonal forecast.  Then add the Terciles, possibly call each of them p33, p67, so the full names become p25, p33, p67, p75 in that order.  (Those names are reasonably helpful also.)
Then add a further block called Deciles & Quintiles.  This has 8 entries, namely 10% (called p10), 20%, 30%, 40% on the first row and then 60%, 70%, 80%, 90% on the second row.  

I prefer option 2, but it might make the tab look a bit cluttered.  Before coding, do others, particularly @dannyparsons and @volloholic have views?

I have suggested @shadrackkibet as he can probably do this very quickly.  But is could be others?

**Comment by shadrackkibet** [comment]
>  I guess, R-Instat has the ability to calculate quintiles too, hasn't it? Your confirmation will be welcomed."

Yes, this is already possible under **more** Tab in the summaries sub dialog. We just use `quantile` function with `probs = 0.2 or 0.4 or 0.6` etc.

I think your option 2 is much more comprehensive and looks into the "future" requests and also include WMO's request and much more. I think there is enough space for this on this Tab if you agree with putting **groups** (common, numeric etc) side by side.

**Comment by rdstern** [comment]
Thanks @shadrackkibet .  I have alsop checked with @dannyparsons who supports option 2.  On layout I assume it is another block on the main Summaries tab.

Move the Range to be with Min and Max, so that block can be thinner.  Then decrease the space between blocks and there should be enough at the bottom for the additional block.

In the quartiles make the labels short, so all 4 can go on a single line.
