### ISSUE TITLE
Correcting and improving the general and other modelling dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6197]
There are real problems with this facility.  As a simple test I tried to do a simple logistic model.  I was using these data:

[class.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/5903667/class.xlsx)

The description of the analysis is [here](https://stats.idre.ucla.edu/r/dae/logit-regression/).

I quickly got this error and am stuck and having to restart.
![image](https://user-images.githubusercontent.com/11226469/106453764-b11da180-6481-11eb-885b-cac4c4bcea51.png)

But I suggest fixing the error is secondary to a bit of an overhaul of the way we are doing the fitting as I explain below.  This will be instructional - and challenging - for @shadrackkibet and I hope @lilyclements might also usefully get involved.

We were working towards a system that was very clever, but possibly too clever.  I therefore suggest we take a step back on cleverness and get a good working system first.  Once it is working well, then can add further aspects later.

The dependent variable starts it off.  We currently try to do different things if it is integer, etc and we don't consider integer-type data elsewhere in R-Instat.  What could be useful could be to note the type of data for the y-variable and report that.  @dannyparsons does that nicely in the Describe > Two Variables > Summarise and Graph.  

It is the same problem in Model > Fit > 2 Variable, 3 Variable and General.

The important distinctions are that the Y can be numeric or categorical or ordered categorical (Or perhaps even logical for binary data).  They are easy to report on.  If we take binary data from the example it is defined as integer, so I suggest it is reported as such, or maybe as numeric.  We could make it numeric!

So I suggest we have all the options for glm for any type of data.  That means we have to be sensible ourselves (at least initially), because R-Instat isn't helping us.  So, the pull-down has Normal first - and then uses lm automatically, then a line and then all the options for glm below.  (I am not sure where the glm links go currently because the Model Options is disabled.  Perhaps they should go there, because there is a default for each distribution.  

Then, we try later to build some checks.  For example Poisson models should have non-negative data, but do they have to be integer?  And, if so, then what about quasi-Poisson?

Then there is non-linear models, ordered categorical data models and multinomial models and hierarchical models, but let's add them later.  We can use them (except nnet) now via the model-fitting keyboards.

**Comment by shadrackkibet** [comment]
@rdstern we need to discuss this in general before work starts. Perhaps a Skype involving @lilyclements  @volloholic and/or @dannyparsons will be good. I see this will have implications into the way modelling dialogs were initially conceptualised. I think there is an advantage to the "clever" system otherwise it won't be useful to model in R-Instat (making things easier).

**Comment by rdstern** [comment]
@shadrackkibet agreed, but I think we can make good progress a bit more "step-by-step".  
The "very clever" system has the problem that nothing is happening.  Meantime a sort of "minimally clever system" could be really useful now and is sorely needed.  And I think could be really easy to do, from where we are now.
I also feel it is important and useful for you to play a hand in this, but not that you get "sucked in" to this area.  That would divert you too much from more important (for you and R-Instat) climatic tasks!

Perhaps we (maybe with @volloholic who devised the very clever system) can chat briefly first.  My proposed tasks are simple and (I hope) quick!  Namely the Model > Fit > General at least works for glm.  

And (if it would take longer for Ivan than you) the Model > 2 variable > Fit code is tidied - is tidied, so we continue progress on R-Instat for training purposes.
