### ISSUE TITLE
Small bug in the display of the column metadata

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6206]
This is certainly in the Column metadata and possibly also in the data frame metadata.

![image](https://user-images.githubusercontent.com/11226469/106895177-cf84d680-66e7-11eb-91d6-050ff63bc61f.png)

The first 2 fields in the column  (and dataframe metadata are the variable (or data frame) name, followed by the label.  When the label is empty - as it often is, then the name field spreads out and sometimes into the following fields.  If there is something in the label field, then it is sensibly truncated.

**Comment by rdstern** [comment]
@Patowhiz is still quiet, so I am suggesting @N-thony might be able to look at this?

**Comment by rdstern** [comment]
Here is another example.  I can send @N-thony the file once work starts, but don't want it to become public on github

![image](https://user-images.githubusercontent.com/11226469/109123375-ad5c0280-7741-11eb-9b9d-85506dd2df04.png)

**Comment by Patowhiz** [comment]
This possibly relates to how the reogrid is being filled and how it correctly casts the data types displayed.  Will be interested to see how this is solved.

**Comment by N-thony** [comment]
> This possibly relates to how the reogrid is being filled and how it correctly casts the data types displayed. Will be interested to see how this is solved.

Exactly!

**Comment by rdstern** [comment]
@N-thony a simple solution to this problem is to swap the order of the class and the label variables in the column and data frame metadata.  The class is always supplied so that solves the issue.  @dannyparsons is happy with this "solution".

**Comment by Patowhiz** [comment]
@rdstern @N-thony yes that could be a simple solution and could certainly work, but it will be good if we could understand what's causing this. That knowledge could be transferrable elsewhere when such a problem is observed. I suggest debugging this through a deduction process until we alienate the actual cause of this.

**Comment by Patowhiz** [comment]
@rdstern @N-thony I've looked into this problem and now I have a solution.
If we go by @rdstern suggestion, there is only 2 solutions to this;
1. Change the underlying R code that gets the metadata, to make it return the columns data already rearranged. This would involve changing how the R codes script gets the attributes from the columns of the data frame(and of course major testing to make sure nothing is broken).
2. Change the way the column metadata grid is being filled, when you look at the current VB.NET, all the grids are universally filled with data from the given data frame. So this could involve writing a custom function for just this one grid that checks the column names from the data frame and rearranges them while filling this grid.

From above, both options seemed like huge changes to me in regards to a small problem! Which got me thinking that the suggested solution is not ideal and is not easy as it seems.

So @N-thony I combed the `ReoGrid` [library](https://reogrid.net/document/cell/) and found 1 line of code that could do the magic.
@rdstern @N-thony what the below line does is and I quote;

> Like Excel, ReoGrid will display a cells text overflowing its cell.
> This behavior could be disabled by changing worksheet settings:

`sheet.DisableSettings(WorksheetSettings.View_AllowCellTextOverflow)`

Now it's a question of where do we want this code placed, which I think will be determined by whether we want this behavior switched off for all grids or just this column metadata grid, a question that can be answered by @rdstern.

**Comment by N-thony** [comment]
> @rdstern @N-thony I've looked into this problem and now I have a solution.
> If we go by @rdstern suggestion, there is only 2 solutions to this;
> 
> 1. Change the underlying R code that gets the metadata, to make it return the columns data already rearranged. This would involve changing how the R codes script gets the attributes from the columns of the data frame(and of course major testing to make sure nothing is broken).
> 2. Change the way the column metadata grid is being filled, when you look at the current VB.NET, all the grids are universally filled with data from the given data frame. So this could involve writing a custom function for just this one grid that checks the column names from the data frame and rearranges them while filling this grid.
> 
> From above, both options seemed like huge changes to me in regards to a small problem! Which got me thinking that the suggested solution is not ideal and is not easy as it seems.
> 
> So @N-thony I combed the `ReoGrid` [library](https://reogrid.net/document/cell/) and found 1 line of code that could do the magic.
> @rdstern @N-thony what the below line does is and I quote;
> 
> > Like Excel, ReoGrid will display a cells text overflowing its cell.
> > This behavior could be disabled by changing worksheet settings:
> 
> `sheet.DisableSettings(WorksheetSettings.View_AllowCellTextOverflow)`
> 
> Now it's a question of where do we want this code placed, which I think will be determined by whether we want this behavior switched off for all grids or just this column metadata grid, a question that can be answered by @rdstern.

@Patowhiz this sounds good. Thanks.

**Comment by Patowhiz** [comment]
@N-thony will you look into where the above code can be placed or would you like me to do it? I'm happy with both.

**Comment by N-thony** [comment]
> @N-thony will you look into where the above code can be placed or would you like me to do it? I'm happy with both.

Let me try it again, then I will let you know.

**Comment by Patowhiz** [comment]
Okay thanks.

**Comment by N-thony** [comment]
> Okay thanks.

@Patowhiz once again I have tried the quoted code above, but it is not working since in our case the label column is empty. I think by the default reogrid doesn't allow text from a column to go over text of the next column if not empty. The code above works in case you want to enable/disable code to go over the next column only if the next column is not empty otherwise it will go over as it is in our case. We can discuss it again or you can try it from your end, I may misunderstand that. Thanks.

**Comment by Patowhiz** [comment]
@N-thony thanks for testing it out. 
The code above is from their library documentation and explicitly states the behavior I expected. 

I noticed there was a similar bug reported by a `reogrid` user who tried the same code but didn't work as expected. See their github [issue 301](https://github.com/unvell/ReoGrid/issues/301) which was fixed and closed on 3rd April 2021. 

@dannyparsons @lloyddewit what version of the `reogrid` library are we currently using? There is a bug that  was fixed in regards to the `reogrid` library. We are facing the same bug here because I think we don't have the latest `reogrid` library version.  

@rdstern @N-thony I suggest we wait for @lloyddewit or @dannyparsons feedback before we explore other options. If we update to the latest `reogrid` version then I think the code I've suggested above will work.

**Comment by lloyddewit** [comment]
@Patowhiz We seem to be using ReoGrid v2.1.0, the latest is 3.0.0.
@N-thony Please could you test with 3.0.0 to see if this solves the issue? I'm happy to discuss if needed

![image](https://user-images.githubusercontent.com/57253949/125604682-b8337149-1baa-4188-a924-f349ca1f2386.png)

**Comment by Patowhiz** [comment]
@lloyddewit thanks for checking this out. Would be interesting to see what other new features and fixed bugs we have been missing once the new reogrid version is merged

**Comment by rdstern** [comment]
Agreed.  An obvious one would be to be able to select non-adjacent variables.
