### ISSUE TITLE
View dataframe dialog - Change the default option position at the top

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#6234]
The default option in this dialog is All columns. I suggest we move this option to the left of this dialog so that we have All columns then choose columns so that it is consistent with other dialogs where we use custom radio buttons at the top.

![image](https://user-images.githubusercontent.com/26301973/108815233-2c77fc00-75c5-11eb-8b15-b62e4b70dd7b.png)

**Comment by rdstern** [comment]
Agreed, and really happy with the detailed work that @shadrackkibet is proposing and doing.  This consistency is particularly useful for the beginner users that we have and where we emphasise that R-Instat helps to "make it easy"
