### ISSUE TITLE
Adding data entry - grid (spreadsheet) style - to R-Instat for daily climatic data

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6250]
I specify the problem, using Zambia Met service as a case study.  I suggest a simple solution could be useful more generally.

Zambia Met would like to update the daily records of rainfall and max and min temperature in 6 stations in Southern and Eastern Province. Their current data is in Clicom format.  It imports easily into R-Instat and is easy to tidy.  They currently have 2 data entry staff.  The data typically start in 1950 and is reasonably complete to about 2010.  It is then very patchy for the recent years.

We think we have a solution to this problem, which is for them to download and install Climsoft.  Then import the existing station and current data.  Then add the new months of data.  This will be combined with capacity-building, in that modest funds will be used to invite a Zambia Met person for 2 weeks from each province.  They will arrive with the data to be entered and then work with HQ staff to enter the data.

This is part of a more general problem.  Zambia has over 40 stations and 10 provinces.  Maybe this formula could be used for all their stations.  I assume (in addition) it also has daily rainfall data from many volunteer stations, but this was not discussed.

Staff have found it easy to download, install and use R-Instat.  

Now Climsoft has good data entry facilities for these data, but it still lacks a grid-style data entry system - which was a feature of its Clicom predecessor.  We have long wanted to add a grid-style data entry system to Climsoft.  

The Zambia situation is common, and is also reflected in Mozambique.  

It would be even simpler for Zambia Met if they could initially use a spreadsheet, or R-Instat, to enter these daily data.  Perhaps any proposed grid-style data entry system for Climsoft could also be included in R-Instat?  I explore what is needed here, particularly to check if a usable (limited) system could be easy to provide for R-Instat.  Then Zambia Met could start with R-Instat and add Climsoft later for more general data management of the climatic database.

I note that the 41 stations includes many other elements, but Zambia Met are happy to start with these three.  I should mention that a next stage in R-Instat will be the quality control.  This is already quite good in R-Instat, but temperaure QC could be enhanced if more temperature elements, e.g. dry bulb and wet bulb.

There are also other data, on a 3 or 4 hr basis.  But a simple solution for data entry of just daily data would be very useful to many services.

In Climsoft the Station details must be entered before the daily records can be added.  I suggest our proposed solution could include the same restriction, partly because it could simplify the process.
Similarly element information could be available.

In Climsoft there is also flag information that may be entered at the same time.

Most of the data entry sheets include monthly totals.  They are obvious for rainfall, but are often included for many elements and provide an excellent check.  (Of course if there is a difference it may be because of data entry or from original calculation errors.)

Often (as in Zambia) there will be some station data already, and the task will be to enter the gaps.  They will usually be at least monthly gaps.  In some circumstances there may be shorter gaps to infill.  Sometimes a new station may be added.

How could we start doing this?  Is there something we could specify, in R-Instat, It could be useful in R-Instat even if it starts with the entry of single elements - as in Climsoft - with additional facilities coming later.  

The Genstat grid system has included a general data entry facility with double-entry capabilities for many years.  This is general.  I wonder if something very simple could be setup quickly?

It may be that a simple solution is possible, but using a third package, maybe Excel or Open Office, or even something else.  I wonder what the options are?

**Comment by rdstern** [comment]
I discussed with @volloholic who is happy with the idea, but suggested a (possibly) simpler system.
This is to enter the data into the eisn't to the existing data frame, rather than making new ones.  I specify how this might work.  It is for data already entered and reasonably tidy, but I specify below how it could easily be adapted for new data.
a) Button at the top with Daily and Monthly as the 2 labels.  Initially Monthly is disabled.  (It may be easy to include?)
b) Use Climatic > Infill - possibly improve the dialogue a bit first - specified below.  This to give the new end-point for existing data.  Possibly add option to just change the end date .
c) Climatic > Use Date and get the Year, Month, Day of year and day of month.  Possibly delete these variables if got earlier as they will now have missing values. 
d) Right-click and duplicate variable - so the entry isn't to the existing data.  e.g. tmax adds tmax1.
e) Now use the new Climatic > Tidy and Examine > Enter dialogue.  
f) This initially has the ordinary data selector and a single receiver - for the element to be entered.  I guess it might as well be a multiple receiver?
g) There is a field for the Station.  It may fill automatically.  Not needed if just one station.  If filled, then you need to choose the Level, i.e. which station is to be entered.
h) The Date variable is in another receiver.  This is filled automatically and must exist.  Then there is a date picker for the **_Starting date_** for data entry. 
i) Label **_Show from_** <up-down> (with zero as default and integer values, no particular high value.) **_rows earlier_**  This is to start the grid - optionally - a bit earlier than when you start entry.  If at the start or the number specified takes you past the start, then start at the start.

This now opens a grid control.  It has the Station, Date, Year, Month, Day of Month fields and then just the variables specified.
Now you enter the data.  I assume it doesn't involve R except at the end.  

You can update any time, just by pressing Ok.  When you return to the dialogue it is as you left it.  The one neat feature could be for the starting date to move on as you enter.  So when you return the default is for you to continue.

I think this is Ok as a system and simpler than entering separately.as I suggested above.

New data.  Then we just use the existing File > New  For entry of rainfall we might specify 2 variables as follows.  If agreed then the part below becomes a new small issue for an enhancement to File > New

Change the Command example from:
`data.frame(l = 1:31, d = seq(as.Date("2013-1-1"), as.Date("2013-1-31"), "day")) 
`
to 
data.frame(date = seq(as.Date("2021-1-1"), as.Date("2021-1-31"), "day"),rain=as.numeric(NA))
add another one for monthly data:
data.frame(date = seq(as.Date("2019-1-1"), as.Date("2020-12-31"), "month"),rain=as.numeric(NA),tmin=as.numeric(NA),tmax=as.numeric(NA)) (where I assume there must be a better way of specifying the 3 variables?

**Comment by rdstern** [comment]
@Patowhiz I have been discussing the provision on R-Instat for Zimbabwe Met Service.  Our support for this would be funded by WFP.  There is an element of data rescue in the initial work, and they need to start with R-Instat and then add climsoft later.

Hence the data entry, probably as described here, becomes a high priority for the version at the end of March.  I hope that is not too much work and will be possible.

**Comment by Patowhiz** [comment]
@N-thony @rdstern below is a sketch of what I understood from our discussions. You can add more suggestions to it.

![climatic](https://user-images.githubusercontent.com/21179007/111442084-0b648000-8719-11eb-8dd9-29359a0faa52.jpg)

**Comment by N-thony** [comment]
> @N-thony @rdstern below is a sketch of what I understood from our discussions. You can add more suggestions to it.
> 
> ![climatic](https://user-images.githubusercontent.com/21179007/111442084-0b648000-8719-11eb-8dd9-29359a0faa52.jpg)

Great @Patowhiz , designing this now.

**Comment by rdstern** [comment]
Great.  I wonder about the Starting date on the left instead, below the selector.  There is plenty of space there.

**Comment by N-thony** [comment]
> > @N-thony @rdstern below is a sketch of what I understood from our discussions. You can add more suggestions to it.
> > ![climatic](https://user-images.githubusercontent.com/21179007/111442084-0b648000-8719-11eb-8dd9-29359a0faa52.jpg)
> 
> Great @Patowhiz , designing this now.

@Patowhiz can we use DatagridView?

**Comment by dannyparsons** [comment]
The choice of grid depends on the needs. If DatagridView has all the features we need then use this, as it's the simplest. 
The alternative is to use ReoGrid, but this adds an external dependency so only use this if there is a functionality in reogrid that we need which is not in DatagridView.

**Comment by N-thony** [comment]
@Patowhiz @rdstern below is the initial design of the Climatic Data Entry dialog. We can proceed to the next step if you are happy with that. @Patowhiz I have a couple of questions for you. Can we discuss? Thanks
![image](https://user-images.githubusercontent.com/68591383/111483153-3791f800-873d-11eb-8646-441141d0b001.png)

**Comment by dannyparsons** [comment]
Thanks. How about the grid being in a sub dialog on it's own? Then it can be longer and wider.

Also, why reogrid?

**Comment by N-thony** [comment]
> Thanks. How about the grid being in a sub dialog on it's own? Then it can be longer and wider.
> 
> Also, why reogrid?

@dannyparsons I have not work a lot about reogrid before but I see it is used a lot in R-Instat. But I think for instance what we need about data entry can be done by either reogrid or datagridview

**Comment by dannyparsons** [comment]
I have discussed with Roger and David. We agreed on:

- Keep reogrid as the grid, but write the code such that it would be easy to replace reogrid with another grid in future if needed. This can be achieved by having functions which contain reogrid specific code.
- Move the grid into a sub dialog. The sub dialog should be expandable and the grid expands with the subdialog. This will allow users to make the grid large if they wanted.

**Comment by Patowhiz** [comment]
@dannyparsons what will be the label of the button? And should we put the starting date in the subdialog or have it just in this main dialog. 

@dannyparsons and also do we have an inbuilt functionality that could allow the levels of the station selected to be shown in the selector?

**Comment by dannyparsons** [comment]
> @dannyparsons what will be the label of the button? And should we put the starting date in the subdialog or have it just in this main dialog.

Something like "Enter Data". Roger might suggest something. I think it might be easier for the starting date to stay on the main dialog, so that the grid can easily expand, but I don't mind too much.

> @dannyparsons and also do we have an inbuilt functionality that could allow the levels of the station selected to be shown in the selector?

Yes we have `ucrInputFactorLevels`. It's a combo box which shows factor levels from a linked receiver. So I think use this. It will be easier than getting the selector to display them.

**Comment by dannyparsons** [comment]
@rdstern Should there also be an end date control? If I know there is one month of missing data to fill in I don't want to see the whole set of data.

Another idea, @Patowhiz @N-thony can we highlight the cells that have changed in the grid so that the user can review the changes they have made?
Another feature might be to have a checkbox to filter the grid to only show the rows with changes made, useful for review. This can come later. Let's get the main functionality working first.

**Comment by rdstern** [comment]
@Patowhiz and @N-thony possibly yes to the End date control I suppose.  However I was assuming we may want to restrict more than this.  I would also be happy if this has a maximum length, perhaps one year, i.e. 366.  So instead of an end date there could be an up-down of the number of rows (days) to show.  I'd like to be able to show a few days, optionally, before the first date entered.  You can choose that by specifying entry to start just before your date.  So perhaps the maximum is (say) 400 rows.  

Very occasionally you may want longer.  Is there a way in the control that the up-down can stop at 400 (say), but you can type any positive number?

My concern is that I would like to encourage users to press OK reasonably frequently.  Then it is saved to the data frame, which (in turn) is backed up regularly.

 I was assuming that the first day would advance, so it will always show the next day to be entered.  Then, if you press OK and come back

I reflected on @Patowhiz idea, of a Transform field and I suggest we could have that now already.  That can start simply, because the main use will be to enter data as whole numbers and then divide by 10.  A second example that fits will be inches to mm, where we divide by 25.4.  This will later be more complicated with fahrenheit to centigrade.

**Comment by dannyparsons** [comment]
For @Patowhiz and @N-thony, focus on getting the main functionality working first. Keep our suggestions in mind but don't let it distract you from the initial implementation.

**Comment by dannyparsons** [comment]
@N-thony Here is a function to get the data entry for the data grid (`DataBook` and `DataSheet` versions).

Note that `station` and `station_name` are optional (for one station) and `end_date` is also optional. Feel free to adapt as needed.

``` r
DataBook$set("public", "get_data_entry_data", function(data_name, station, date, elements, station_name, start_date, end_date) {
  self$get_data_objects(data_name)$get_data_entry_data(station = station, date = date, elements = elements, station_name = station_name, start_date = start_date, end_date = end_date)
})

DataSheet$set("public", "get_data_entry_data", function(station, date, elements, station_name, start_date, end_date) {
  cols <- c(date, elements)
  if (!missing(station)) cols <- c(station, cols)
  curr_data <- self$get_columns_from_data(cols)
  if (!missing(station)) curr_data <- curr_data[curr_data[[station]] == station_name, ]
  curr_data <- curr_data[curr_data[[date]] >= start_date, ]
  if (!missing(end_date)) curr_data <- curr_data[curr_data[[date]] <= end_date, ]
  if (nrow(curr_data) == 0) stop("No data in range.")
  # Convert to character to they display correctly in VB grid.
  curr_data[[date]] <- as.character(curr_data[[date]])
  if (!missing(station)) curr_data[[station]] <- as.character(curr_data[[station]])
  # Order columns in correct order for data entry.
  if (!missing(station)) {
    out_data <- data.frame(curr_data[[station]], curr_data[[date]], curr_data[elements])
    names(out_data) <- c(station, date, elements)
  } else {
    out_data <- data.frame(curr_data[[date]], curr_data[elements])
    names(out_data) <- c(date, elements)
  }
  out_data
})
```

Here's an example:

```r
dodoma_entry <- data_book$get_data_entry_data(data_name = "dodoma", date = "date", elements = c("rain", "tmax"), start_date = as.Date("1981/01/01"), end_date = as.Date("1981/12/31"))
ghana_entry <- data_book$get_data_entry_data(data_name = "ghana", station = "station", station_name = "Tamale", date = "date", elements = c("rainfall"), start_date = as.Date("1981/01/01"), end_date = as.Date("1981/12/31"))

```

**Comment by N-thony** [comment]
> @N-thony Here is a function to get the data entry for the data grid (`DataBook` and `DataSheet` versions).
> 
> Note that `station` and `station_name` are optional (for one station) and `end_date` is also optional. Feel free to adapt as needed.
> 
> ```r
> DataBook$set("public", "get_data_entry_data", function(data_name, station, date, elements, station_name, start_date, end_date) {
>   self$get_data_objects(data_name)$get_data_entry_data(station = station, date = date, elements = elements, station_name = station_name, start_date = start_date, end_date = end_date)
> })
> 
> DataSheet$set("public", "get_data_entry_data", function(station, date, elements, station_name, start_date, end_date) {
>   cols <- c(date, elements)
>   if (!missing(station)) cols <- c(station, cols)
>   curr_data <- self$get_columns_from_data(cols)
>   if (!missing(station)) curr_data <- curr_data[curr_data[[station]] == station_name, ]
>   curr_data <- curr_data[curr_data[[date]] >= start_date, ]
>   if (!missing(end_date)) curr_data <- curr_data[curr_data[[date]] <= end_date, ]
>   if (nrow(curr_data) == 0) stop("No data in range.")
>   # Convert to character to they display correctly in VB grid.
>   curr_data[[date]] <- as.character(curr_data[[date]])
>   if (!missing(station)) curr_data[[station]] <- as.character(curr_data[[station]])
>   # Order columns in correct order for data entry.
>   if (!missing(station)) {
>     out_data <- data.frame(curr_data[[station]], curr_data[[date]], curr_data[elements])
>     names(out_data) <- c(station, date, elements)
>   } else {
>     out_data <- data.frame(curr_data[[date]], curr_data[elements])
>     names(out_data) <- c(date, elements)
>   }
>   out_data
> })
> ```
> 
> Here's an example:
> 
> ```r
> dodoma_entry <- data_book$get_data_entry_data(data_name = "dodoma", date = "date", elements = c("rain", "tmax"), start_date = as.Date("1981/01/01"), end_date = as.Date("1981/12/31"))
> ghana_entry <- data_book$get_data_entry_data(data_name = "ghana", station = "station", station_name = "Tamale", date = "date", elements = c("rainfall"), start_date = as.Date("1981/01/01"), end_date = as.Date("1981/12/31"))
> ```

Thanks @dannyparsons

**Comment by Patowhiz** [comment]
Initial example of the R script code generated by the dialog.
```
# Code generated by the dialog, Climatic Data Entry

Date1 <- data_book$get_columns_from_data(data_name="Sheet1", col_names="Date1")
data_book$save_data_entry_data(data_name="Sheet1", station_name="ACHEGO", date=Date1, elements=data_book$get_columns_from_data(data_name="Sheet1", col_names=c("Tmin","Tmax")), start_date=as.Date(x="1950/3/23"), data_changed=,,20,21
,,25,22
,,21,26
,,30,24
,,31,36, rows_changed=c(0,1,2,3,4))
rm(Date1)
```

**Comment by dannyparsons** [comment]
Here's the function for updating data after data entry:

``` r
DataBook$set("public", "save_data_entry_data", function(data_name, new_data, rows_changed) {
  self$get_data_objects(data_name)$save_data_entry_data(new_data = new_data, rows_changed = rows_changed)
}
)

DataSheet$set("public", "save_data_entry_data", function(new_data, rows_changed) {
  if (nrow(new_data) != length(rows_changed)) stop("new_data must have the same number of rows as length of rows_changed.")
  curr_data <- self$get_data_frame(use_current_filter = FALSE)
  for (i in seq_along(rows_changed)) {
    for (k in seq_along(names(new_data))) {
      print(rows_changed[i])
      print(names(new_data)[k])
      curr_data[rows_changed[i], names(new_data)[k]] <- new_data[i, names(new_data)[k]]
    }
  }
  self$set_data(curr_data)
}
)
```

with example.
Note `rows_changed` should be a vector `c()` I just did this for simplicity. The rows may not be consecutive in general.

```r
# Setting working directory, sourcing R code and loading R packages
setwd(dir="C:/Users/Danny/source/repos/R-Instat/instat/static/InstatObject/R")

source(file="Rsetup.R")

data_book <- DataBook$new()

ghana <- rio::import(file="C:/Program Files/R-Instat/0.6.6/static/Library/Climatic/Ghana/ghana_two_stations.RDS")
data_book$import_RDS(ghana)

ghana <- data_book$get_data_frame(data_name = "ghana")

ghana_entry <- ghana %>% 
  filter(station == "Saltpond" & date %in% seq.Date(as.Date("1999/1/1"), as.Date("1999/1/10"), by = 1)) %>%
  select(station, date, rainfall)
ghana_entry$rainfall <- 100

data_book$save_data_entry_data(data_name = "ghana", new_data = ghana_entry, rows_changed = 19937:19946)

ghana <- data_book$get_data_frame(data_name = "ghana")

ghana %>% 
  filter(station == "Saltpond" & date %in% seq.Date(as.Date("1999/1/1"), as.Date("1999/1/10"), by = 1)) %>%
  select(station, date, rainfall)
```

I will also adapt `get_data_entry_data` such that it includes the correct row numbers.

**Comment by dannyparsons** [comment]
@N-thony please add the following line to `save_data_entry_data` just before the last line `self$set_data(curr_data)`. This will add an output message:

`cat("Values updated in:", length(rows_changed), "rows.\n")`

**Comment by Patowhiz** [comment]
> Change the Command example from:
> 
> `data.frame(l = 1:31, d = seq(as.Date("2013-1-1"), as.Date("2013-1-31"), "day"))`
> 
> to
> 
> `data.frame(date = seq(as.Date("2021-1-1"), as.Date("2021-1-31"), "day"),rain=as.numeric(NA))`
> 
> add another one for monthly data:
> 
> `data.frame(date = seq(as.Date("2019-1-1"), as.Date("2020-12-31"), "month"),rain=as.numeric(NA),tmin=as.numeric(NA),tmax=as.numeric(NA))` (where I assume there must be a better way of specifying the 3 variables?
> 

@rdstern what will be the tooltips for the 2 examples outlined above.

**Comment by rdstern** [comment]
I am delighted that the basic system is now (almost) working.  However, I suggest there are a number of enhancements we should try to include, before unveiling it.  

I hope the basic system plus a few enhancements, that we could mention separately, could be included.  I suggest most may be quite simple.

a) **_End Date:_** We need an end date.  I suggest the default end date is the end of the same month as the start date.  It has a similar control, but that is the value that it takes initially once the start is completed.  Even if the start is 31 month, then it is just the one day.  (But it can be change to any value (within the data) and not less than the start date.

b) **_Viewing:_**  I suggest another multiple receiver View Element(s) (Optional).  They are elements added to the data entry grid, but locked, so there is no entry possible.  (There is a slight problem of the order of these extra elements, if they are not the same order as in the grid.  I suggest a simple rule is applied, based on the order in the main grid.  The View elements could eithe be before, or after the entry elements.  One simple rule, if the first view is earlier in the main grid, than the enter elements, then they are all before.  Or they are all after.)
c) **_Locking:_** We need to be able to lock variables.  Currently we can even change the date variable.  Locking all that is not entered, should also result in the TAB key going sensibly from row to row.  This will facilitate entry by date, rather than by variable.
d) **_Transforming:_** We have a transform checkbox.  If checked it opens a pull-down control.  You can choose a transformation, or type in a number.  If you type a number, then it divides by that number, before copying back to the data.  The three initial default options are 10 (to divide by 10, so no decimals need be entered),  inch to mm (to divide by 25.4) and F to C (to subtract 32 and divide by 9/5) 
e) **_Adding or Correcting:_**  Now an important one.  This is possibly ordinary radio buttons, or even our special ones.  We are usually `Adding`, and the other 2 options are `Correcting 1 Day` and `Correcting Multiple Days`.   I hope this will be easy to do.  When we are Adding, then we replace missing values by data.  We don't change existing data.  When we Correct, it will often be for a single day, i.e. usually just one value.  So the End Day isn't visible.  Corrections for multiple days brings back the end date control.
f) Just to build on that aspect of Adding v Correcting.  Usually we will be adding.  If we are adding and the period we select has data, then we are not allowed to enter.  I assume that check is easy.
g) **_Restricting entry._**  I suggest there be 2 sorts of restriction.  First is what characters are allowed.  Second (possibly) a simple range check.  We keep them simple in the sense that the characters and checks apply to all variables entered together.  So, if we want different checks for rainfall and temperatures, then we enter them separately.  Note it isn't impossible that we want to enter some character variables.  But usually data will be numeric and we could start with those.  
h) **_Reporting:_**  I suggest reporting is very important and can make good use of the Comments data frame.  Let's wait till that's done.
i) **_Monthly totals:_**  This is in climsoft and we need to do this.  I'm not sure how - yet.
j) **_Double Entry:_**  I think we get this (almost) for free.  We have a Compare function already - though I am not sure that is quite right.  If separate data frames, then the arsenal package has an interesting seeming function, and allows tolerances that we might find useful.

**Comment by rdstern** [comment]
I now put together the suggestions for the changes above for the data entry.  The existing dialogue looks like this:
![image](https://user-images.githubusercontent.com/11226469/112451611-9cf17480-8d4d-11eb-8204-68f7014ba3d6.png)



When you click to enter data it looks like this:
![image](https://user-images.githubusercontent.com/11226469/112451354-4f750780-8d4d-11eb-86fd-3c2479dd3fcd.png)

So far so good.
Suggested Changes:
a) **_Menu item_**.  Must be updated in the sprint.  Currently it says Data Entry.  We need the "..." afterwards.  If you agree with my suggestions below, then this could change to:
Daily Data Entry...   .   and also below that
Monthly Data Entry...  or Data Entry Monthly...  (Initially this is made invisible
(Note on menu:  We will soon need Climatic > File > "Export For Climsoft...".  It is invisible for now?  At the same time change Export **_to_** CPT... to Export **_for_** CPT... )

b) At the top of the dialogue, replace the text in the 2 radio buttons, by Add and Edit  They can remain disabled for now if you like.  
Under them, for Add the first option is Month and the second is Range.
Under Edit the first option is Day, Second is MOnth and the third is Range. 

(Currently we are only Editing and the Day option could come later.  The only difference - which is big for the use, but not for programming - I hope - is that Adding can only change values that are currently missing.  In Edit you can change any values.

c) Change the multiple receiver Elements:  label to Edit (Elements): Then, under this control, have a second multiple receiver called `View (Optional):`  This is for other elements.  Usually they are other variables, but no harm done if a variable is there twice.  (And in the correction mode we assume this would be automatic that there would be 2 copies.)  

d) Protection:  The **_View variables_** are copied into the Data Entry form, and protected.  (I presume this would use `cell.Readonly = true` in reogrid?) This protection (i.e. view mode) needs to be done anyway for the Date Variable. 

e) Hence if you want to edit (correct) the Date variable, then include it, in the list of variables to be edited.  Hence the change in label name above, to emphasise the Edit - usually for elements.   The date also appears first, but that is protected.

e) **_Implement the Month option_**   This is the same as the dialogue now except either the date picker chooses months and not days - or should there be 2 controls for year and month?  What's easier to use?  This gives the same grid, but for a single month.  So there need not be an End Date - which we want for the Range option (that's what we have now.

f) Add an Ending Date control below the Starting date one and implement.

g) Make the Data Entry butto  a bit smaller.  On the same row and to the right, add a `Check Data` button.  Disabled for now.  It will open a sub-dialogue with checks to be done once Ok is pressed.

h) Add a `Transform` checkbox.  If checked it opens a pull-down into which you can type.  Initial default is 10 and then Inch to mm and F to C.  Perhaps just have 10 there for now.

i) Have a `Restrict Entry` label, with a set of options: Default is numeric, others are Numeric (no decimal), All.

j) Have a `Default Value` checkbox.  Default unchecked.  If checked you can type a number - default is 0.  That changes all values to 0.

k) Add a Reset button in the Data entry grid.

**Comment by dannyparsons** [comment]
@Patowhiz @N-thony Here are the minimum requirements from Roger's list:

a) Menu items (simple)

b) At the top of the dialog, replace the text in the 2 radio buttons, by Add and Edit. 
They can remain disabled for now. Edit is selected.
Under them, there is a Period option with a dropdown.
When Add is selected the options are: Month and Range.
When Edit is selected the options are: Day, Month and Range.

For Day option - A date picker to choose a single day. One row in the grid.
For Month option - A date picker to choose a single month. One month in the grid. I think this can be done like this:
```vb
dateTimePicker1.Format = DateTimePickerFormat.Custom
dateTimePicker1.CustomFormat = "mm yyyy"
```
We may need to update the R functions to account for this.

For Range option - Two date pickers for the start and the end dates.

c) Change elements label to "Elements to edit". Add another multiple receiver for "Variable to View".

d) The view variables are added to the grid after the element columns but cannot be edited. They are not included in the data.frame() of edits. Also, agreed with Roger that the date column should not be editable.

g) Add a "Check Data" button but make it disabled. Add a tooltip which says "Data checking facilities not yet implemented"

k) Add a Reset button in the subdialog which refreshes the grid back to the original values. Have a pop up for users to confirm this.
