### ISSUE TITLE
Import ERA5 files

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6253]
We now have a dialogue Climatic > File > Import from IRI Data Library.
We need a similar dialogue for Climatic > File > Import ERA5 Data, or Import Copernicus ERA5 Data?

I hope the existance of the IRI dialogue will make it easier to construct this dialogue.

@dannyparsons to specify and then allocate to someone.

**Comment by dannyparsons** [comment]
Here's the dialog design. It's similar to Import from IRI. The subdialog to "login" is for the two parameters to `ecmwfr::wf_set_key()`. Initially the subdialog won't do the login, just sets the parameters. `ecmwfr::wf_set_key()` is the `user` parameter to the main function. Have it assigned to `user` as in the example. Later we might want to run the login from the subdialog and check it's successful.

The create account is a label with a link to https://cds.climate.copernicus.eu/user/login

Initially dataset just has one item: "ERA5 hourly data (single levels)". There are at least 3 others that would be good to add after.

Resolution will display as "Resolution: 0.25 x 0.25" with 0.25 x 0.25 in red (eventually it will change depending on the dataset).

Initially elements just has the popular elements from here https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=form. Use the same names as on the form to display. For the code the names are: `'10m_u_component_of_wind', '10m_v_component_of_wind', '2m_dewpoint_temperature',
            '2m_temperature', 'mean_sea_level_pressure', 'mean_wave_direction',
            'mean_wave_period', 'sea_surface_temperature', 'significant_height_of_combined_wind_waves_and_swell',
            'surface_pressure', 'total_precipitation'`

Later we can have elements selected from a selector to a multiple receiver, but this needs more setup work.

For time selection, currently only Range is enabled.

Currently it downloads data in chunks of one month per file. So "Save Downloaded Files To" is a Folder Selector. 

Also, if importing, it will be one sheet per month, which isn't ideal. We can fix this in the R code later, but initially I suggest "Do not import" is checked by default.

There's a lot of improvements from this initial design but I think this will already be useful.

The requesting is quite slow, so only try with 2 or 3 months at a time for testing. I know Roger will request if this can be running in the background instead. That's a possible improvement.

![IMG_20210328_184707](https://user-images.githubusercontent.com/11214914/112762176-3f338580-8ff6-11eb-930f-10db0b2234fa.jpg)

![IMG_20210328_184718](https://user-images.githubusercontent.com/11214914/112762180-435fa300-8ff6-11eb-9cd7-337780319a35.jpg)

Here is the R function for importing.

```r
DataBook$set("public", "import_from_cds", function(user, dataset, elements, start_date, end_date, lon, lat, path, import = TRUE, new_name) {
  all_dates <- seq(start_date, end_date, by = 1)
  all_periods <- unique(paste(lubridate::year(all_dates), sprintf("%02d", lubridate::month(all_dates)), sep = "-"))
  all_days <- c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31")
  all_hours <- c("00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00")
  area <- c(lat[2], lon[1], lat[1], lon[2])
  pb <- winProgressBar(title = "Requesting data from CDS", min = 0, max = length(all_periods))
  nc_files <- vector(mode = "character", length = length(all_periods))
  for (i in seq_along(all_periods)) {
    y <- substr(all_periods[i], 1, 4)
    m <- substr(all_periods[i], 6, 7)
    curr_dates <- all_dates[month(all_dates) == as.numeric(m) & year(all_dates) == as.numeric(y)]
    d <- sprintf("%02d", lubridate::day(curr_dates))
    request <- list(
      dataset_short_name = dataset,
      product_type = "reanalysis",
      variable = elements,
      year = y,
      month = m,
      day = d,
      time = c("00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00"),
      format = "netcdf",
      area = area,
      target = paste0(dataset, "-", paste(elements, collapse = "_"), "-", all_periods[i], ".nc")
    )
    info <- paste0("Requesting data for ", all_periods[i], " - ", round(100 * i / length(all_periods)), "%")
    setWinProgressBar(pb, value = i, title = info, label = info)
    ncfile <- ecmwfr::wf_request(user = user, request = request,
                                 transfer = TRUE, path = path,
                                 time_out = 3 * 3600)
    if (import) {
      nc <- ncdf4::nc_open(filename = ncfile)
      self$import_NetCDF(nc = nc, name = new_name)
      ncdf4::nc_close(nc = nc)
    }
  }
  close(pb)
})
```

Example:

```r
user <- ecmwfr::wf_set_key(user = "xxx",
                   key = "xxx",
                   service = "cds")

data_book$import_from_cds(user = user, dataset = "reanalysis-era5-single-levels", 
                          elements = "total_precipitation", start_date = as.Date("1999/1/1"),
                          end_date = as.Date("1999/1/31"), lon = c(20, 20.3), lat = c(50, 50.3), 
                          path = "C:/Users/Danny/Downloads")
```
