### ISSUE TITLE
Minor Issue with the position button in Row Numbers/Names dialog

### ISSUE THREAD

**Issue by Wycklife** [africanmathsinitiative/R-Instat#6254]
The position button is not aligned in Prepare>Data Frame> Row Numbers/Names. Click on the first option (Copy Row Names Into Columns).

**Comment by shadrackkibet** [comment]
This is a general issue in the save control that should be easy to fix from the designer. @HawardKetoyoMsatsi @N-thony are you happy to take up this?

**Comment by rdstern** [comment]
Aaah yes.  Interesting to know what it does when the item being saved isn't a column in the data, but another object.  I see that Save Model etc also now has the position button!

**Comment by shadrackkibet** [comment]
@rdstern this is a bug that was introduced by the changes in #6230. It affects dialogs that use save controls.

**Comment by rdstern** [comment]
@shadrackkibet good you found it so quickly.  @Patowhiz is looking into it.  More generally it exposed a failure of our testing, i.e. when a user control is changed then we should be aware that it could affect many dialogues.  That's the whole idea of the user controls after all.  Often we like that, but this is an example that is a bit more complicated.  

It shows where we (testers  and developers alike) need to be aware and especially careful.  @lloyddewit may also have further comments.

**Comment by lloyddewit** [comment]
> It shows where we (testers and developers alike) need to be aware and especially careful. @lloyddewit may also have further comments.

I agree with @rdstern. Testing is an art. We should not only test the directly changed functionality but also try and think of possible side-effects that the change may have caused. Not easy!
