### ISSUE TITLE
Simplify the use of the merge dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6265]
This dialogue works well.

The one complication is that when you click on Merge Options, the resulting sub-dialogue looks more daunting than need be.  I suggest the Merge Options button be renamed as `Joining Columns`.  There is a second button on the right - or below the Joining Columns button.  It says `Columns to Include`.  

This stops the need for the sub-dialogue to be tabbed.  

Further, I suggest on the columns to merge by that it always goes to the second button at the top if there are no joining columns, i.e. if the main dailogue was red rather than grey.

**Comment by dannyparsons** [comment]
Generally agree. Joining options can be further simplified by only having the choice of choosing the pairs - but by default the ones with the same name are already filled in.
