### ISSUE TITLE
Display of data types in the R-Instat grid

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6266]
Currently we define some types of data.  This could usefully be extended - at least visually in the grid.
For example, from the structured menu, we can define columns to be `circular`.  Then this is noted in the column metadata, but nothing is indicated in the name in the grid.
We can now define columns as `survival`.  This is not noted (currently) in the metadata, nor the grid.
We will have low flow variables etc.  there are lots of different ones.
We define dates as D.  So far this is for daily data.  We have date-time and time coming.  How do we show this in the grid.

@volloholic suggestion is simple, and is as follows:
a) We use D - or should it be d for date, or date-time or time.  They are all a date-time sort of thing.
b) We use s for structured, so this could be survival, circular, low-flow.  It just indicates that it is defined.

Separately to this is that details of the structure, and the type of date is given in the metadata.  So that needs to be added for the survival.  

This needs @dannyparsons to check.  If agreed it needs to be implemented.

If quicker for him to do than explain, then he should.  Otherwise he could suggest who implements.

**Comment by dannyparsons** [comment]
I would prefer different codes for different types of columns. I don't see a problem with users learning a few codes, particularly as they may not use all of them regularly, and only a few will be in a particular dataset.

I feel that the general codes will be less useful and ambiguous, I don't really see an advantage to grouped codes.

**Comment by rdstern** [comment]
So, I now know what you don't want!  

a) Do you want to keep D for date, or change it to d?
b) What do you want for date-time?  Also d or perhaps d_t?
c) And t for time
d) Then are you happy with s for structure, or would you like a different code for each type.  So perhaps c for cu=ircular, s for survival, etc

As you can gather, I really don't mind, but would just like us to make a decision!

**Comment by rdstern** [comment]
I understand this is now resolved and @dannyparsons will implement.
a) Date variables will continue to be denoted as D.  They will be extended, so date time variables and time variables will also be denoted as D in the grid.  @dannyparsons will determine how they are shown in the column metadata.
b) Other data types will now change to also have capital letters.  In particular, (f) will become (F), and (o.f) will become (O.F).  (c) will become (C).
c) Structures for variables will become (S).  Currently this is for example for circular data.  Later also for time series data.
d) Types of data for specific Application areas will become (A).  Initially tis is for survival data, later for low flow data etc.
