### ISSUE TITLE
Define climatic data is not (fully?) remembered from one session to another

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6268]
This was mentioned by Rachel.  

When she returned to R-Instat and opened an rds file defined as climatic, she claimed that it didn't remember that it had been defined.  @dannyparsons mentioned he knew of that bug.  

I hadn't noticed it myself.

**Comment by dannyparsons** [comment]
I tested this by:

- Loading Dodoma from the climatic guides dataset Excel file
- Create a date column and define as climatic
- Checked autofilling happened in a few dialog
- Confirmed metadata had correct properties
- Saved the file
- Closed R-Instat and reopened and opened the file
- Checked the autofilling in the same dialogs
- Also checked metadata was still the same

I didn't notice any issue. So I will close this issue now.

It may have been an issue with a specific dialog, or a certain file got changed somehow. If we discover this we can reopen this issue.
