### ISSUE TITLE
Default names should start without a number

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#6271]
Default column/data frame/object names currently go in sequence e.g. `date1, date2, date3, ...` until an available name is reached.

I suggestion optionally allowing the sequence to start without a number e.g. `date, date1, date2, date3, ...`

This option can be the default. It will ensure more concise names and avoiding numbers unnecessarily.

**Comment by rdstern** [comment]
I would prefer that, e.g. starting with date.  I assume it is just one global change?

**Comment by dannyparsons** [comment]
Yes, global for all dialogs. I assume this default is sensible in general. It can be changed back on individual dialogs if desired.

**Comment by rdstern** [comment]
Great.  Can you do, or allocate to someone?
