### ISSUE TITLE
Improve the One Variable Frequencies Graph

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6279]
The one variable frequency graph could be very useful in teaching and in simple data processing.  
It has just been corrected, so it now works.  But there are many ways that options could be added to improve it.  The commands could also be improved in at least 2 ways.  This could be an early job for @HawardKetoyoMsatsi. 

- [x] Everything in the R code is in 1 line.  This makes it difficult to edit the graph options in the script window.  Here is a simple example.

```
# Code generated by the dialog, One Way Frequencies

last_graph <- sjPlot::plot_grid(x=list(x=sjPlot::plot_frq(data=data_book$get_columns_from_data(data_name="survey", col_names="yield", force_as_data_frame=TRUE, remove_labels=TRUE, drop_unused_filter_levels=TRUE),show.prc=FALSE,show.values=FALSE)))
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")

rm(last_graph)

```
In most dialogues the data frame is got first, and then the data are processed.

- [x] The frequency graph is drawn in a grid.  This is needed if more than 1 variable is plotted - I assume facets can't be used?  But it isn't needed for a single variable.  So could just sgPlot::plot_frq be used then directly?

Then James, John and Tobias can start their work.  This function has many options that could usefully be included on the dialogue, and hence the plots.  I also don't know why they are labelled A, B, etc and not with the names of the variables.    

As a start I found:

- [x]  The line option doesn't work.  The box, violin histogram do work.  The dot is OK.

- [x] We can control the size, i.e. width of the bar.  If small, then it becomes a vertical line - looks quite nice.

- [x] I couldn't get the colors to change - needs a bit more work.

- [x]  I can't see how to get the name of the variable included.  But it does automatically include the label - unless you say otherwise.  (Nice to have encouragement to use variable labels.)

**Comment by lilyclements** [comment]
As pointed out #6270 - can the parameter positions be added to this dialog too when these changes are made?

**Comment by shadrackkibet** [comment]
@rdstern @maxwellfundi @HawardKetoyoMsatsi Just before I start work on this, I notice from the sprint this is in review can someone explain why? Is it just misplaced?

**Comment by shadrackkibet** [comment]
1) @rdstern you say "The line option doesn't work". What exactly did you do? using which dataset? this is the sort of statement that doesn't help the programmer! Can you give more details? 
For example in my case.

- I loaded the usual survey data
- I change to Graph option
- Using `field` and `size`
- In the subdialog I change to line
- I got the following graph.

![image](https://user-images.githubusercontent.com/26301973/111874802-d28e0a80-89a7-11eb-837a-976a96d2ff26.png)

2) You also mention histogram, violin and boxplot here I do not see either of these in **Describe>One variable>Frequencies.**

**Comment by rdstern** [comment]
@shadrackkibet you are right that I should have been clearer, but I couldn't make it work for anything!  Now, I repeated with your example - also worked for me!  And using yield works too! - so that's a puzzle!

You ask about histogram, violin and boxplot.  That's part of what I hope James and the interns will examine and specify.  The function in sjplot has added many new options, so it would be good to consider what should be added, and how.  This sort of analysis fits well with James' teaching of descriptive statistics, so appropriate for him and the interns to examine.

**Comment by shadrackkibet** [comment]
I do not think the first point really matters. We have this kind of long code elsewhere. I really want to be convinced that breaking the code here will make things easy and that it will be useful to the user. @dannyparsons what do you think?

**Comment by shadrackkibet** [comment]
@rdstern another enhancement that could be done is to change and enable/disable the tab selected in the subdialog depending on the top radio button selected.

**Comment by dannyparsons** [comment]
Cleaner code would be nice but not essential. 
A simple improvement would be to set an assign_to to `sjPlot::plot_frq ` so that this is on a separate line first.
An assign_to for the columns would also be useful, but this would need to be done in the receiver and it's less obvious what name should be used for getting multiple columns. So I would leave this part for another discussion.
