### ISSUE TITLE
Improve the graphics in R-Instat through the addition of more geoms

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6293]
My claim is that we would substantially enhance the graphics capabilities in R-instat if we had more geoms.  I also had the impression that @maxwellfundi became quite a whizz at doing this efficiently.  If so, then perhaps this is also something that @Karakacha and @TobbyKe could take over, with initial instruction from @maxwellfundi?

Now the list is getting long and later perhaps we should worry about that!  For now I suggest the additions are far more important than adapting that control

On that supposition here is my initial list to add:

a) The remaining geoms in ggplot2.  I suggest we should have them all.  And there are some that sound really useful!  I have put the obviously important ones in bold below.
b) The geoms in ggridges as mentioned in #6278 
c) geoms and some stats from ggpmisc see  #5744 and #5037

From ggplot2
area
bin2d
blank
crossbar
errorbar
errorbarh
**function**
hex
linerange
path
**qq**
qq_line
quantile
**raster**
rect
**spoke**
steps

If you are able to proceed, then I suggest you do a number of pull requests, because there are quite some enhancements here.  Not one for each geom, but perhaps 4 or 5 overall with suitable names.  for example geom_spoke seems to be useful for circular data.

**Comment by maxwellfundi** [comment]
@rdstern I have been adding these and i have a few questions

1. On **bin2d** - I am unsure of all the parameter values possible for `stat `and `position`- Stat has bin2d and position has identity. What other would you like me to add?
2.  on **geom_function** could you provide the other parameters that can be added on there?
3. on **qq** what other distributions can be added? I only have - `stats::qnorm` at the moment

**Comment by maxwellfundi** [comment]
I think these are more general, for example statistical transformations - `stat `Are they general for these graphs- Would it be a common list of transformations @rdstern  or they would be different for each graph?
