### ISSUE TITLE
Minor bug in Climatic>Prepare>Climdex dialog

### ISSUE THREAD

**Issue by Wycklife** [africanmathsinitiative/R-Instat#6295]
**Describe the bug**
I am updating video script 12(Preparing Data: Summarizing Rainfall Data) using the Climdex Indices dialog. All the receivers are filled automatically except for max_temperature

**To Reproduce**
1. Load the ghana_2_stations.RDS
2. Go to Climatic > Prepare > Climdex

**Expected behaviour**
All the receivers should be filled automatically.

See below:
![image](https://user-images.githubusercontent.com/33898404/111628926-cb2cfc80-8801-11eb-9e2d-59325f85ad8c.png)

**Comment by MeSophie** [comment]
@dannyparsons  tmax  variable in the data is defined as tmax in the metadata and is also define as climatic. Now is filling automatically.  Then I will close the issue.

![image](https://user-images.githubusercontent.com/106779233/224707111-cda363d7-c131-46a3-bc79-2cf9528cc26c.png)
