### ISSUE TITLE
Add more buttons to simplify the use of the script window

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6311]
I have been using the script window quite a lot recently and have become fairly skilled at <Ctrl><Alt><T> to run a selection.  I can run All by clicking at the top.  Could we have a few more icons or buttons?
a) Keep `Run All`
b) Add `Run Current LIne` - as in RStudio
c) Add `Run Selection`
d) Possibly add `Clear 
`
They could be buttons or possibly icons with a tooltip each?

This needs a bit of discussion.  If we can agree, then I assume it will be easy to do?

**Comment by shadrackkibet** [comment]
All these are very easy to add since we already have them on the right click. If agreed, I think we can as well add icons like in Rstudio. The only concern is that we should not rewrite Rstudio instead we should encourage the use of the log window.

**Comment by Patowhiz** [comment]
@rdstern below is a screenshot of the buttons available in my R-Studio. R studio combines the run selection functionality with run current line into 1 button. The single button just detects whether there is a selection, if not, it runs the current line. Should we also combine the 2 buttons; **Run Current Lin**e and **Run Selection** ? Or would you like to still have them separate.

![rstudio](https://user-images.githubusercontent.com/21179007/122793303-e4659f00-d26f-11eb-86f7-1d0ee5db7027.PNG)
