### ISSUE TITLE
Adding a further option to the Climatic > Dates > Fill Date Gaps dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6327]
This is for @dannyparsons to check that it is sensible, and then I hope it is a very quick job for @shadrackkibet who has already worked on this dialogue.  It is to support the new data entry.

We will sometimes want to extend the climatic data frame to enable data entry for a new year at the end - sometimes even at the start.  One way is to use the Fill Date Gaps dialogue.  

I assume (usually) an initially tidy (climatic) data frame.  Extending in one direction (or the other) would be easier if we extend the options in the limits pull-down.

We currently have Data Limits and Fixed limits.  Could we also have `Fixed End Limit `and `Fixed Start Limit`  They would open just a single copy of the calendar control.  That would make life easier.

I assume, and hope this is a pretty trivial addition?

**Comment by dannyparsons** [comment]
This is a good way to extend the data.

On your suggestion, what you're essentially asking for is that `Data Limits` and `Fixed Limits` are separate for start and end. This sounds good to me and adds the flexibility we need.

So it's something like
Start: Data / fixed limit
End: Data / fixed limit

I'm not looking at the dialog so not sure about the design but this is the idea. And should then not be difficult to implement, but it would require changing the R function.

If that makes sense, I think Shadrack could implement this.
