### ISSUE TITLE
Language option as dropdown instead of radio buttons

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#6358]
We'll soon have more languages so I think the language choice in the Options dialog should be a dropdown combo box instead of radio buttons.

A non urgent simple task for someone to take up.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers Could someone take this up? We would like it for the next release.

**Comment by Ivanluv** [comment]
Am looking at these
