### ISSUE TITLE
Focus not set correctly in Climatic Summary dialog

### ISSUE THREAD

**Issue by lloyddewit** [africanmathsinitiative/R-Instat#6366]
In PR #6363 , @shadrackkibet  wrote:

> 
> 
> I noted that when the receiver focus is on one of the hidden receivers e.g "Within Year" then click on "Daily" focus is not set. Same case for "Station".
> ![image](https://user-images.githubusercontent.com/26301973/113102440-b93a5900-9206-11eb-9a06-4e2f9ad4cd59.png)

This issue should be resolved.

Further details can be found in PR #6363 .

**Comment by shadrackkibet** [comment]
@HawardKetoyoMsatsi this should be easy one to fix.
