### ISSUE TITLE
Adding options when importing multiple files

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6378]
Currently this import is only for the default settings.  That is ok for importing from SPSS, Stata or SAS, so this is already useful.  But with csv or text files it would be good to include options, particularly to select missing values.

At the same time, the label to import multiple files has made the dialogue wider.  It would be good to reduce the width, so it is no wider than is needed by the preview window.  REduce the space after the File: label and the Browse button could be slightly smaller.  Finally, if needed the main field width could also be reduced slightly.

**Comment by Patowhiz** [comment]
@rdstern if we reduce the file label and browse buttons, will the the translations fit?
