### ISSUE TITLE
Another small bug in the File > Open dialogue! 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6379]
I thought this was fixed?  It maybe a result of the complicated code, so perhaps @Patowhiz can sort it when he does the refactoring.  Or maybe before!

![image](https://user-images.githubusercontent.com/11226469/113498555-d8d2c980-9505-11eb-9132-5cf8b490ecf3.png)

The image shows the problem.  I have returned to an Excel data file.  No sheets are marked, but Ok is enabled.  It also actually works!  It takes the first data frame, then ignores the first variable and gives 9 one-column data frames, with one for each variable.  

But better if Ok were disabled if no sheets are being imported!

**Comment by Patowhiz** [comment]
@rdstern I'm unable to reproduce this bug. Could you retest using the latest changes from the master.
