### ISSUE TITLE
Bug when deleting a data frame and then drawing a graph

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6383]
**Describe the bug**
When deleting a data frame I got the following message:
![image](https://user-images.githubusercontent.com/11226469/113539201-1f432980-95d5-11eb-9fcb-debcd8110f45.png)

**To Reproduce**
a) I used the germany merged data.  This is for 4 stations.
b) I did quite a lot of analyses before - and had R-Instat open a long time.
c) I then Filtered by factor with Station as the factor
d) I selected one station and then did a plot for this station.
e) Then I returned to the filter, and made it a subset instead.
f) I then chose the 4 months - December to March for further study.  This was intended to be a filter.  But the seting was still subset, so I got another data frame.
g) So I returned and did the filter properly.
h) Then deleted the data frame with the subset - and that gave the error. 

I have not had that error before.

I was using the new R-Instat version 0.7.0

This is the command:

```
# Code generated by the dialog, Delete Data Frames
data_book$delete_dataframes(data_names="griefswald_subset")
```

I now see that it did delete the data frame!
So I tried to continue - with a graph and got:
![image](https://user-images.githubusercontent.com/11226469/113541399-0e48e700-95da-11eb-86f9-0600a038bc3b.png)

I found that I could save the rds file.  So I then closed the data file and opened it again.  (I did not close R-Instat.)  I have worked for another hour on various tasks without a problem.  I then did produce a yearly summary dataset.  When I dewleted that, I got the same error as started this issue.  Again, it did delete the data frame so I am continuing.

I take the opportunity to report a second aspect.  It may be related, because I have continued with the same data.  I have been using the correlations dialogue, with the gGally graph for a scatterplot.  It has been working fin, but I have now changed data frames and it gives an error.  Here is the code generated:

```
# Code generated by the dialog, Correlation

sunh <- data_book$get_columns_from_data(data_name="arkona", col_names="sunh")
sunh_sat <- data_book$get_columns_from_data(data_name="arkona", col_names="sunh_sat")
last_model <- cor.test(x=sunh, y=sunh_sat, alternative="two.sided", exact=NULL, method="pearson")
data_book$add_model(model_name="last_model", model=last_model, data_name="arkona")
data_book$get_models(data_name="arkona", model_name="last_model")
arkona <- data_book$get_data_frame(data_name="arkona", remove_attr=TRUE)
last_graph <- GGally::ggscatmat(data=arkona, columns=c("sunh", "sunh_sat"), color="month_abbr")
 
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="arkona")
data_book$get_graphs(data_name="arkona", graph_name="last_graph")
rm(list=c("last_model", "sunh", "sunh_sat", "last_graph", "arkona"))

```
The error is as follows:
![image](https://user-images.githubusercontent.com/11226469/113605108-1aff2680-963e-11eb-933f-5a4acf54b3ef.png)

It generates the graph fine.  The problem is at the line with the first data book.  Is this anything to do with the changes in the way we now save the graphs?

I again saved the rds file and opened it again.  Now the graph runs fine for arkona.  I went back to griefswald, and still ok.  And back to arkona.  Now it all works ok.  Puzzling?

I saved the file and generated another data frame.  Then deleted it.  At least that error is repeatable.  Here is the data file:

[germany_griefswald_plus.zip](https://github.com/africanmathsinitiative/R-Instat/files/6259735/germany_griefswald_plus.zip)

**Comment by rdstern** [comment]
So with the changes.
a) Open Dodoma and do a boxplot - for example, e.g. boxplot of tmax by month
b) Open Dodoma again and it comes into dodoma1.  Now do a boxplot on dodoma1

![image](https://user-images.githubusercontent.com/11226469/116892037-4d914480-ac27-11eb-8ba8-385d9ae31c1c.png)

**Comment by shadrackkibet** [comment]
I tried to replicate the bug reported by @rdstern as follows.

- Load any data set 
- Do any graph say scatterplot
- Delete the data frame
- Load any dataset again
- Do any plot
