### ISSUE TITLE
Add an option to the Compare Columns Dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6393]
There is a `Prepare > Check Data > Compare Columns` dialogue currently.
I propose we add 2 radio buttons at the top.  The first is `By Row` and the second is `By Value`
The option described below is to add is `By Row`.  The existing dialogue is comparing `By Value`.

The `By Row` should be simpler! Its main use is to compare 2 numerical variables, row, by row, though I consider below the situation with other types of column.
1. I suggest, the usual data selector and 2 single receivers, just as in the dialogue already.  The labels for those receivers can be the same.
2. And (initially) it writes out a logical variable - as does the other option.  And this is TRUE if the 2 values are the same and FALSE otherwise.  And there is also (like the other option), simply the same report in the output window namely the number of TRUE and FALSE.
3. Possibly, as now, allow any type of data.  But check that the data are the same type when press OK.  If not give a message.  Maybe once one control is completed, only allow the same type in the other field?
4. If numeric then there is a tolerance with an option, into which you can type, but there are some suggestions.  0 is an option, as is 0.05, and 0.001 and 1E-10.  Default can be 0.
5. Then the function can be `abs(first - second) <= tol`.
6. I hope this might work for logical, dates as well?
7. I assume for factor variables or character variables the tolerance isn't needed, and the function is simply `(first == second)` ?

(Note that 2 character variables can also be close, though not identical.  But then we would use the Prepare > Column: Text > Distance dialogue.)

 I am assuming that this compare will work with filtered data.  So, if the data are filtered, then (if a new variable is chosen) it is missing for all the data outside the filter.  If an existing (logical) variable is chosen then the results would "slot in" to part of that variable.  

In the next comment I mention extensions to this "system" that could be discussed/implemented.  But I am keen to get something simple that works for now.

**Comment by rdstern** [comment]
I have added @shadrackkibet and @dannyparsons into the discussion as I consider possible extensions to the basic comparison option.
a) Could the 2 variables be in separate data frames?
b) Could the receivers be multiple?  So you could compare (say) 3 variables with 3 from a second set.  I would still have only 1 logical variable produced, which would be TRUE is all 3 (say) pairs match, and FALSE is there is any difference.  All variables must be of a single type.
c) Could the equivalents of a filter be included on the dialogue.  Perhaps just those rows where the flag field was changed.  Or even particular dates and a particular station - assumein Station and Dates are key fields.

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern  Giving an error message after a different datatype has been entered in the second receiver conflicts with restricting the second receiver from accepting a different datatype. Could we just allow the datatype same as the one entered in the first receiver to be displayed in the selector so that the second receiver's input will be restricted to the datatype displayed in the selector?
Two dataframes could be used but if they are of different number of rows a sensible comparison will be achieved up to the number of rows of the smaller data frame.
