### ISSUE TITLE
Adding the writing of flag fields to the new data entry system

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6394]
This is an important part of the data entry system.  It is to add "flag fields" to the data files as well as adding the data.  The main use will be to be able to kn ow which rows have been updated in the data, and hence to be able to selct those rows/dates for export  (to climsoft)

It is possible they can be for other purposes too, once the facility is done.  We thought this would have to be @dannyparsons but now suggest that @N-thony could set up the checkbox, and then @shadrackkibet would be able to do this, with guidance from @volloholic .  I hope that's ok?  By "do this" I hope that Shadrack would be able to write the R-code for this component.  Then @Patowhiz and @N-thony can include it within the data entry system.

This was item 14 in the improvements to the data entry system.  It is copied below here:

(Antoine/Danny) Add a checkbox in the sub-dialogue, default unchecked. Label is Add flag field data. Currently this is just to add the the saving code (Danny to do?) when Ok is pressed. It does the following:
a) If not present, then it creates those variables. If a variable is tmax, then its name could be tmax_flag. It is a factor variable. Ideally perhaps it has 3 levels, plus NA. It is NA when tmax is originally NA, data, where there are data that are unchanged, edit, when data have been changed, and add, when NAs have become data, and changed, when an add row is edited. Initially all we need is to distinguish between unchanged and changed, so we can filter on the changed values to write back to Climsoft.)
b) Once the flag variable is present it just writes back to it, similarly to writing to the data.
c) As I write this I wonder whether it could be simpler if the flag variables are present in the grid, possibly after all the other variables. They are visible, but are completed automatically?
d) Maybe it would be simpler if the flag fields were made, before editing starts if they are going to be used? Perhaps when the box it ticked it could check that the corresponding flag fields exist. There could be a button to Make flag variables which is disabled if they already exist and to that effect. This would add the flag variable(s)
e) So the R-code can assume the flag variables already exist.  I suggest there should be a separate (Setup) dialogue to produce these variables.  And they would be as follows:
1) They are called rain_fl, tmax_fl, etc.  
2) They are factor variables with 4 defined levels.  0) NA when the data variable is NA. 1) `data` when the variable has data. 2) `edit`, when an existing value is changed, 3) `entry` when a new value is entered 4) `change` when a new value is entered and then changed.  
3) So, to start with a flag variable is either all NA, or a mixture of `data and NA`.  If any data values are changed, then they become `edit` - they become edit if they are "changed", even if the actual value doesn't alter.  If an edit value is changed again, it stays as edit.  If an NA is changed, then it becomes `add`.    I am currently suggesting that if edit is changed to NA, or add is changed back to NA, they are still noted as edit or add.

**Comment by Patowhiz** [comment]
Could the "Add flag fields" checkbox label be a bit more descriptive or probably a tool tip explaining what it means to have it checked. It wasn't instantly clear to me though I guess the data entry personnel will have been trained on this dialog.
