### ISSUE TITLE
A null reference exception triggered in the translation file

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#6396]
**Describe the bug**
There is an exception triggered in the `Translation.vb` file line 75 when you click "Yes" from auto-recovery options. 

**To Reproduce**
- Load any dataset.
- Do some analysis, say use any dialog
- Then close R-Instat
- Restart again. Hopefully, recovery options are shown, click "Yes".

![image](https://user-images.githubusercontent.com/26301973/114002007-26806680-9865-11eb-8b88-6d820ba9227f.png)
![image](https://user-images.githubusercontent.com/26301973/114002979-0f8e4400-9866-11eb-870f-e0e6cd669dda.png)

In the current version (0.7.0) I get the following.
![image](https://user-images.githubusercontent.com/26301973/114003833-c2f73880-9866-11eb-830e-01b98474664a.png)

I, therefore, tag @lloyddewit and @dannyparsons because you have recently been working on the translation.

**Comment by shadrackkibet** [comment]
Interesting to also note that the directories are pointed to Danny's directories in my currently installed version.
![image](https://user-images.githubusercontent.com/26301973/114005353-2170e680-9868-11eb-9a11-6d09d9e1b16c.png)

**Comment by lloyddewit** [comment]
@shadrackkibet Thank you for detecting and documenting this. I am able to recreate the error.
Clarification: the bug is only triggered when I close R-Instat by ending it's process (e.g. from within the debugger). The bug is not triggered when R-Instat exits normally.
I will fix this bug.

**Comment by lloyddewit** [comment]
Fixed in PR #6413
