### ISSUE TITLE
Completing the Position control for saving new variables

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6397]
This system is just-about working.  I am going resaonably systematically through the dialogues where it is used.  I am particularly looking for 4 things:
a) Does it work - I am hoping for that.  That's called `Work`.
b) Is the Position button nicely aligned, it was various sizes and slightly off centre.  I call that `Align`.
c) Is the label about the saving ok? In some cases the control was pushed to the left and obscured the label.  I call that `Adjust`.
d) Is the default position ok.  Often the new variable relates to an existing one, and the obvious default is next to it.  That's called `Default` and I'll explain in detail when this occurs.

**_Prepare >Data Frame_**
1. Row names/Numbers:  ok

**_Prepare > Check Data_**
1. Duplicates:  Align.  Also Default:The new variables always come at the end.  For the third option it is simple, because there is a single receiver.  The default should be after the variable.  For the first option it takes a whole data frame, so the existing is fine.  The middle option takes multiple Variables.  Ideally the default is after the last variable in the multiple receiver.  I hope that will be easy.  (That will usually be the last variable in the data frame, but happy with the rule that what is last in the receiver is the basis for the position.
2. Compare Columns.  Align. also Adjust: Change to `Save result for second column: `  Default to after 2nd column.  It is currently at the end.
3. Non-Numeric.  Adjust:  Add colon and here there is too much space after the label.
4. Anonymise. Align, Change name from Hash to hash.  Default to after variable - currently at end.

**_Prepare > Calculator_**
Add colon ":" to Save Result.  Now also a challenge.  If a variable is clicked to go into the formula, is this detected?  If so, then default to after the last variable.  If tricky, but first variable is possible, then after that.  (But don't spend too long on this.  For example you may recall a formula and then not know.  Leave that.  Possibly have to leave with the End being the default.  Alternatively, is it easy to detect the current active variable in the data frame.  If so, then it might be easy for the default to be after that variable. 

**_Prepare > Column: Calculate_**
1. Regular Sequence.  Align.  This is another example where there is no variable.  Could it also go after the current variable in the grid, if that exists.  Otherwise at the end.
2. Enter.  There is a big gap after the label Enter Result into which should be smaller.  There is no position control yet.  As with the others, ideally after the current active variable, or at the end.
3.  Duplicate   Align only!
4. Row Summaries.  Align.  After last variable.
5. Rank.  Align. After variable chosen.  (Also change label of variable to Column to Rank, i.e. get rid of the s.
6. Poly: Align.  Move control over a bit.  Then default is after the variable.
7. Random Samples.  Align.  Ok at the end here.
8. Permute.  Align.  After variable being permuted.

That's it for round 1!  There is quite enough here!
@Patowhiz you are welcome to do this, or you could start and then hand over to someone else, once the main programming is completed?

**Comment by Patowhiz** [comment]
Waiting for more.

**Comment by rdstern** [comment]
@Patowhiz asked for more instances!
**_Prepare > Column: Factor_**
Recode Numeric.  Move saving control over.  Add the Position button - default after column.
Count in Factor.  Alignment.  Default name to be count, not Count, i.e. all lower case.  (Position has the correct default.)
Recode Factor: Alignment.  Change default to after factor variable.
Combine factor: Alignment.  Change default to after last variable in receiver.

More to come!
Also Climatic > Compare > Calculation doesn't have the Position buttons yet - I forgot them!

**Comment by rdstern** [comment]
This is written on 23rd April.  @Patowhiz is handling the position control in the above posts.  This covers (I hope) each situation that the position control adds a new variable to the data frame.  Then @Ivanluv is "taking over" and implementing the improvements on the remaining dialogues.

I repeat the 3 aspects of the issue.
`Align` is where the position button is not neatly aligned.  It is sometimes too low, and sometimes too large.  
`Work` is situations where the button doesn't work well.  Usually this means changing the default, so when one variable produces another, the default position is just after the the producing variable.
Adjust is where the label preceding the new variable needs to be adjusted.  Sometimes a colon needs to be added.  Often the space for the label needs to be larger,  (And we need to examine this again once the French version is fully implemented.  We should also be more systematic in the actual label.  

### Prepare Menu
a) **_Check Data > Compare Columns_**: (closed pull request #6414 by Shadrack:)  So centre the buttons at the top, add a colon in the position control label, sort out Alignment of the position control button and check that the default is to put the new (logical) variable after the second column.  If easy (and only if easy) note the blank space, where Shadrack suggests the size of the dialogue might change with the setting of the top button.
b) Column: Text > Find/Replace just align.  It is already correctly putting the replacement just after the variable.  Let's call it `New Column:`
c)  Column: Text > Transform.  Align.  Call it `New Column:`.  Work - put it just after the column - like the find-replace above.
d) Split - all seems ok!
e) Combine:  Align.  Work, move it to after last variable - it is currently at the end.
f) String Distance:  Align.  Change label to New Column: It is correct in the positioning of the new variable.

**Comment by Patowhiz** [comment]
> Also implement in Climatic > Compare > Calculation. It doesn't have the Position buttons yet - There are 2 and I forgot them!

@rdstern should the the new column be after station element?

![station element](https://user-images.githubusercontent.com/21179007/116520748-f9354000-a887-11eb-998a-f3c05006c388.PNG)

**Comment by rdstern** [comment]
@Patowhiz yes - that would be good as the default.

**Comment by Patowhiz** [comment]
Items remaining here;

> a) Check Data > Compare Columns: (closed pull request #6414 by Shadrack:) So centre the buttons at the top, add a colon in the position control label, sort out Alignment of the position control button and check that the default is to put the new (logical) variable after the second column. If easy (and only if easy) note the blank space, where Shadrack suggests the size of the dialogue might change with the setting of the top button.

> Also implement in Climatic > Compare > Calculation. It doesn't have the Position buttons yet - There are 2 and I forgot them!

**Comment by Patowhiz** [comment]
All items in the issue have been fixed. @rdstern @lloyddewit this is ready for your review.
I've now added code changes to the last remaining item (dialog  Climatic > Compare > Calculation).
