### ISSUE TITLE
Adding the select facility for variables as a partner to the filter system

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6426]
This has 2 parts.  It builds on, and supersedes topics mentioned in #4372, in #4957 and also in #6263 and in #4009.
The first part is to (probably) replace the current Prepare > Data Frame > Hide/Show Columns with a new Select Columns dialogue.
a) There will still be the Hide Columns (and Restore Hidden Columns) on the right-click menu as described in #4372, together with information on what is hidden at the bottom - just like for rows when there is a filter.
b) The main dialogue will include hide as an option.  It will probably be largely like the main Prepare > Data Frame > Filter dialogue, so the data selector has selects as objects.  You can choose to define a new select, or use an existing one.  One thing you can do with a select is to hide the columns.
c) As with filter, another route to select is from the Data Options button on each main dialogue.  This currently takes you to a version of the Filter dialogue, but just for that data frame.  Now that will change with an additional button, so you can opt for Rows or Columns.

![image](https://user-images.githubusercontent.com/11226469/115952616-dfd67180-a4de-11eb-9a05-b851fc274f92.png)

It is already here.  Do we keep these tabs - just what we want, or change them to radio buttons?

Currently when you choose Columns it is almost blank.  This would change to be like the dialogue for Rows.
I suggest it can for now be almost an exact copy of this.  
So the data selector is for selections.  Replace Filter by Selection in most of these controls.  Perhaps on the Rows option change Selected Filter Preview to just Filter Preview.  Then on the Columns have Select Preview.

d) Now the Select sub-dialogue.  This is a parallel of the Filter sub-dialogue and many parts are the same.  Here I start the suggestions on the structure of this sub-dialogue:

![image](https://user-images.githubusercontent.com/11226469/115952915-bae2fe00-a4e0-11eb-978d-b44320083e94.png)

1) It has the usual data selector at the left-hand side - though it is only needed for one of the options.
2) It has the same controls below, i.e. 
![image](https://user-images.githubusercontent.com/11226469/115953001-02698a00-a4e1-11eb-9b59-ed2a87a55f0c.png)
But the main box has a single entry - just Condition.
And Filter becomes Select, so Select Preview, and Select Name

3) Then the Filter By  becomes Select By: And the single receiver becomes a pull down with the options specified below.
![image](https://user-images.githubusercontent.com/11226469/115953218-12359e00-a4e2-11eb-9e57-6f50fe7f177d.png)

The keyboard moves down and may be different.
The Add Condition button remains.
The two controls above change depending on which option is chosen in the pull-down.

The pull-down contains:
a) columns
b) starts_with
c) ends_with
d) contains
e) matches
f) num-range
g) where
h) last_col
i) What else?

These are described in the tidyselect package as well as under select in dplyr.

Now, if it is `columns`, then there is simply a multiple receiver..  Then the Add button is enabled and once one or more columns are selected, the Add Condition is enabled.  The action is then to take the columns and generate c(column1, column2,...) as the condition.
We need to allow for !, i.e. Not.  That could be a checkbox, but I think it could also be added to the list of buttons once the condition is added?  (This has also been suggested for the filter - see issue #6101 

If it is `starts_with`   then the field just receives a string, so the Add Condition becomes `starts_with("string")`There is also a checkbox (default ticked) with `Ignore Case` as the text
Same for `ends_with`, and also `contains` 
(I am not sure about `matches` and `where`.  Where looks very powerful, and there might be some examples given.
If num_range then there are 2 more controls in addition to the string one which is called `Prefix`.  The next is called range.  It us usually something like 10:15.  I haven't checked whether it can be 3,5,8,11, presumably adding c to become c(3,5,8,11).  Then there is a check-box and if checked, then digits can be a pull-down with values 1, 2, 3, 4.  T(this allows for 001, 002, 003, etc if given as 1:3.
 The & and or (|) work just the same as the filters.  

Then selects should be just like filters, so you can rename them, delete them etc.

The details and implementation will benefit from nifty R skills, so am suggesting the @shadrackkibet and @Cal-Insta could perhaps work together on this.

**Comment by shadrackkibet** [comment]
@Cal-Insta are you available to work on the design for this dialog? We already have a new empty dialog i.e `dlgSelectColumns`

**Comment by Cal-Insta** [comment]
@shadrackkibet yes I am available to work on it.

**Comment by shadrackkibet** [comment]
Okay, please continue.

**Comment by rdstern** [comment]
Some datasets have variable labels.  Interesting to see how they work with select.  This site may be [useful](https://stackoverflow.com/questions/57395444/keeping-column-labels-when-using-the-select-function-with-dplyr
)
Also I noticed that @Cal-Insta was going to work on this function as of 21 June.  What has happened since?  I knopw @shadrackkibet will work on select in the sprint.  Is there anything from Caleb to build on?

**Comment by Cal-Insta** [comment]
Shadrach and I had a discussion on this issue some time ago. I will share the design I came out with @shadrackkibet.

**Comment by Cal-Insta** [comment]
Shadrach and I had a discussion on this issue some time ago. I will share what I came out with @shadrackkibet.

**Comment by dannyparsons** [comment]
Another useful option could be Column Range where you specify a range of columns between a start and end column. It's not vital to have right now, because we can do it with a list of columns, but when there's a clear group in a specific range this would be a bit easy to do, especially if you want to choose 100+ columns.. I found it from the selection document here https://dplyr.tidyverse.org/reference/select.html

**Comment by dannyparsons** [comment]
The the way this is now implemented in R, it's simple to add any additional parameters to the selection functions, so I suggest we add any of these from the functions which may be useful.

For the issue with `num-range` we can add the `width` parameter, which deals with the leading zeros issue.

**Comment by rdstern** [comment]
@shadrackkibet now Select is working can we clarify the hide and show possibilities and dialogues.  Here is the current dialogue:
![image](https://user-images.githubusercontent.com/11226469/134761861-a66860e4-6e47-4b72-a5f6-b54737fcaa35.png)
 I mention some details and then have my main question!
a) Could it be Select Columns at the top - as in the menu.
b) We have the word Apply already for the group box.  So the labels could be Within Data Frame to New Data Frame?

Now my main question is what we will mean by the "Apply"?  The new data frame will have the same number of rows - although a filter may be in operation - and just those columns.

In the same data frame, Apply now means Apply in the Data Selector.  But the Data Frame and the column meta-data are currently unaffected.  I see 2 options once complete.
a) Apply means to hide in all 3 views, So, it is hidden in the data selector in dialogues, in the visible data frame and also in the column metadata.
b) Have option as checkboxes in this dialogue - Default is all ticked.  Data Selector.  Data View.  Column Metadata.

I don't have strong views.  Most of the time we will want to Hide in all 3?

But also we currently have a Prepare > Data Frame > Hide/Show Columns dialogue.  I assume we don't need that anymore?

And we used to have that also on the pull-down.  I suggest we put it back.  It could go just above Filter.  For simplicity I suggest it also be called Select Columns.  Do we then want a Remove Selection also - as we have for the Filter.

So finally - I like the current position of the Select Columns - I had thought it would replace the Hide/Show, but it is better roughly where it is.  But I also like the Filter and Remove Filter at the bottom of the right-click pull-down.  So I suggest (for consistency) you put Select Column(s) before Filter in the Prepare > Data Frame menu.
