### ISSUE TITLE
Problems with the French translation version

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6454]
This is partly just for information for @lloyddewit and partly for @N-thony because he will be interested in improving the French version.
It is largely occasions where the labels are too long in French.  But there are some other issues too - as we expected.

It is not yet in order, but just as I use the dialogues:
a) Prepare > Data: Calculations  > Enter
![image](https://user-images.githubusercontent.com/11226469/117166884-b101aa80-adbe-11eb-927e-5e9ec11d1d89.png)

- [x] Why is the header (ENTREE) in capitals?  It is in lower case in English. (moved this part of the issue to issue #6464)
- [x]  The 2 controls in the data line are too long.  The first also is important to fix soon, because the first numbers typed are hidden.  
- [ ] The keys are translated.  Is this correct?
- [x] Not visible here, but if you press Lan to go into English, then the label (Entrer les resultats dans) stays in French.  (Fixed in PR #6469)

**Comment by lloyddewit** [comment]
@N-thony Thank you for the quick chat. As discussed:
- I converted @rdstern 's list into checkboxes (according to https://guides.github.com/features/mastering-markdown/  'If you include a task list in the first comment of an Issue, you will get a handy progress indicator in your issue list.')
- You will implement point 2 above (please put an x in the checkbox above when done)
- I will implement the other 3 points above
- We'll work in separate PRs (my changes are outside the dialog box so I don't expect conflicts)

If I missed/misunderstood anything, then please let me know, thanks

**Comment by N-thony** [comment]
> @N-thony Thank you for the quick chat. As discussed:
> 
> * I converted @rdstern 's list into checkboxes (according to https://guides.github.com/features/mastering-markdown/  'If you include a task list in the first comment of an Issue, you will get a handy progress indicator in your issue list.')
> * You will implement point 2 above (please put an x in the checkbox above when done)
> * I will implement the other 3 points above
> * We'll work in separate PRs (my changes are outside the dialog box so I don't expect conflicts)
> 
> If I missed/misunderstood anything, then please let me know, thanks

@lloyddewit I have done point 2, thanks.

**Comment by N-thony** [comment]
![image](https://user-images.githubusercontent.com/68591383/117567650-4d78c500-b0bd-11eb-968a-be33a390c9fd.png)
This is fixed in PR #6457.

**Comment by lloyddewit** [comment]
@rdstern This issue is resolved apart from:
- The keys are translated. Is this correct?

Would you like these keys to be translated?

**Comment by lloyddewit** [comment]
> 
> 
> @rdstern This issue is resolved apart from:
> 
>     * The keys are translated. Is this correct?
> 
> 
> Would you like these keys to be translated?

@rdstern Thank you for the discussion on 20 May. You confirmed that it was OK to translate the keys and this issue could be closed.
