### ISSUE TITLE
Add machine translation into Portuguese?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6455]
@dannyparsons says this is a pretty trivial thing to do?  If so, then could we do this for the next release.  If so I would like to get back to the team in Mozambique on this, because I suggest it could make a big difference there?

I have Isabel, who has agreed to help and Tomas who works for INAM (Met service).  That's a start on looking at it.  And it isn't a feature that others are likely to use accidentally and get confused by!

If so, then I know the control will change, but perhaps temporarily we just replace Swahili by Portuguese?  Or should we include machine translation into Swahili too and I'll also use this as an excuse to get back in touch with Tanzania Met.

There will still be quite a bit of work perfecting the translation - which I hope UK Met may help to support.  I don't see this initial step as affecting that aspect.

**Comment by lloyddewit** [comment]
@rdstern Thanks for the quick chat. As discussed:
- if @dannyparsons (or his delegate) generates new Portugese JSON files, then I'll create a new translation database 
- @Ivanluv should also include a `Portugese` option in the combo box in PR #6452
- No ther code changes needed
- Other languages, like Swahili, can also be added but I suggest we first resolve some of the open translation issues in issue #3721. If we do this then users reviewing our translations can focus more on the actual language translation, without being distracted by issues with the mechanism. It will also look more professional.

**Comment by lloyddewit** [comment]
Fixed in PR #6471 and PR #6485
