### ISSUE TITLE
Another bug in Data Entry dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#6462]
**Describe the bug**
![image](https://user-images.githubusercontent.com/68591383/117453101-d4eef880-af44-11eb-964b-2e6a608004fc.png)

**To Reproduce**
1. Go to Climatic>Tidy and Examine>Daily Data Entry.
2. Select the station to be entered from the station pull-down (Agades) and add the element to the receiver.
3. Select the dates for the entry
4. Click on the Enter data button and Click return.
5. Repeat 2) by selecting another station (Bimi N'Konni).
6. Keep the selected date and click Enter data button.
7. The grid load the previous data with Agades as selected station
**Expected behavior**
I think the grid should load the new data according to the selected station name.

**Comment by rdstern** [comment]
That's correct.  Changing the level (i.e. the station, should change to a new version of the grid.

This dialogue is pretty complex.  I am pleased that it is being tested in this way and not surprised we are finding the occasional glitch.
