### ISSUE TITLE
French translation language issues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6464]
A trivial one - but Date in the fig below doesn't have the colon.  (:) .  It does in the English?

And a nice translation problem.  Perhaps I can learn how to suggest these in the right place - but is it ok to make suggestions here too.

Station is translated as Gare, which is correct, but only as a railway station.  It should be Station - here!

**Comment by rdstern** [comment]
I assume the very common issue of the label being the wrong length, like Donnees being longer than Data also is added here, because that is a change in the program - though in the dialogue rather than code?
I was interested that you included Gare and Station here?

**Comment by lloyddewit** [comment]
> 
> 
> I assume the very common issue of the label being the wrong length, like Donnees being longer than Data also is added here, because that is a change in the program - though in the dialogue rather than code?
> I was interested that you included Gare and Station here?

- Issues with labels being the wrong length should **not** be included in this issue because this needs to be fixed in the code
- The Gare/station issue, and the issue with the colon, **should** be included in this issue, because this needs to be fixed in the JSON files

**Comment by lloyddewit** [comment]
@rdstern I removed the translation label from this issue because this seems to be reserved for translation mechanism issues. What's your view?

**Comment by N-thony** [comment]
- Climatic > Check Data > Inventory:  Date Order is translated as Commande par date, it should be **Ordre des dates** here.
- Climatic > Check Data > Inventory:  Facet by is translated as Facette de, it should be **Facette par** here.
- Climatic > Check Data > Inventory: Element has space with (s). It doesn't have in English.
-  Climatic > Check Data > Inventory: Comment doesn't have the colon (:). It does in English.
-  Climatic > Check Data > Fill Missing Values: Station, Element, Type, Observed, Estimated, Imputed, True Values(Optional) have space with the colon. (:) . They don't in English.
- Climatic > Check Data > Fill Missing Values: Date doesn't have the colon. (:) . It does in English.
- Climatic > Check Data > Fill Missing Values: row has space with (s). It doesn't in English.
- Climatic > Check Data > Climatic boxplot: Station, Date, Element, Year have space with the colon. (:) . They don't in English.

**Comment by lloyddewit** [comment]
> 
> 
> I have added a json label and applied it here. Is that ok?

@rdstern Thanks, I edited the translation labels, and added some explanatory text, I hope that's OK

**Comment by lloyddewit** [comment]
I found some more French translations that need changing. I think they are parameters and should not be translated.
I will soon add functionality so that text like this is not translated. In the meantime, could this be fixed via CrowdIn?
- Standard_deviation: format@@0 Standard_deviation
- Extreme_value: Valeur_extrême
- Students_t: Étudiants_t
- Gamma_With_Shape_and_Scale: Gamma_de forme et d'échelle
- Gamma_With_Shape_and_Mean: Gamma_avec la forme et la moyenne
- Gamma_With_Zeros: Gamma_avec Zeros
- No_Distribution: Pas de distribution

**Comment by N-thony** [comment]
@lloyddewit this can be close too.
