### ISSUE TITLE
Another problems with the French translation version

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#6465]
This contains a couple of dialogues that have problems with the French translation.
a. Climatique>Dates>Date d'utilisation
![image](https://user-images.githubusercontent.com/68591383/117699902-a5025800-b1c5-11eb-8453-ff9eb2d16f1e.png)

1. Jour de la semaine, Année bissextile are too long and not display properly. Perhaps Jour de Semaine, and Année Bissextile with some space between them.
2. Jour en mois should be Jour du Mois referring to Day in Month in the English Version.
3. Abbé is not a good translation of Abbreviation that is cut to Abbr. in the English version.
4. Relancer should be Réinitialiser referring to Reset in the English version.
5. OK, k should be lower case
b. Climatique>Définir les données climatiques
![image](https://user-images.githubusercontent.com/68591383/117702914-6cfd1400-b1c9-11eb-9fc6-e879c268ef30.png)

1. Vérifier les doublons button label is too long and doesn't display properly. Perhaps move the input a bit right and extend the button size.
c. Right on any column in Vue de données > Étiquettes/Niveaux
![image](https://user-images.githubusercontent.com/68591383/117703842-7470ed00-b1ca-11eb-9842-245af8f9c857.png)

1. Ajouter le facteur button label is too long. Perhaps extend the button size also change the label to Ajouter le niveau du facteur
d.  Climatique>Dates> Remplir les ecarts de date
![image](https://user-images.githubusercontent.com/68591383/117705761-be5ad280-b1cc-11eb-976f-807f8c5c88a8.png)

1. De facteurs should Par facteurs referring to By factors in the English version.
2. Remplir les vides de date form text to Remplir les ecarts de date.

e. Climatique>Ranger et examiner>Résumer une variable

![image](https://user-images.githubusercontent.com/68591383/117706850-18a86300-b1ce-11eb-9ced-518aa226135d.png)

1. Variable(s) de résumer should be Variable(s) à résumer referring to Variable(s) to summarise in the English version.
2. Par défaut is hiding Personnalisé, Perhaps move Personnalisé a bit right.
e. Climatique>Ranger et examiner>Données quotidiennes bien rangées
![image](https://user-images.githubusercontent.com/68591383/117707628-0bd83f00-b1cf-11eb-859a-fb6d9f115d62.png)

1. Nouveau nom de tableau de données is too long and hiding the input text control perhaps move it a bit right.
2. Colonnes de mois (12), Colonnes du jour (31/62) are not displaying properly, perhaps extend a bit the radion button so that the texts will display properly.

f. Préparer>Colonne:Texte>Transformer
![image](https://user-images.githubusercontent.com/68591383/117708734-75a51880-b1d0-11eb-8cab-91e3896ef6d8.png)

1. Convertir le cas radio button label is too long, perhaps extend the radio button size.
2. Valeur de départ, Valeur de fin labels are too long, perhaps move the nud controls a bit right.

**Comment by lloyddewit** [comment]
@N-thony Thank you for these excellent observations. I suggest we resolve the actual English->French translations via issue #6464 , and the presentation problems (e.g. labels too long) in this issue.

**Comment by N-thony** [comment]
@lloyddewit this can be close.
