### ISSUE TITLE
Reading of multiple txt files

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6476]
I am trying to read (climatic) data of course.  There are multiple files per element, with one file per year.  In a file that is shared the tmax has missing as -100 and reading an individual file it works fine reading 31 rows.  There are 13 columns with the day of the month plus one for each month:
![image](https://user-images.githubusercontent.com/11226469/118721317-9863ac80-b822-11eb-8ee7-099df742f8e6.png)

These are txt files and in the import dialogue I use the fixed width option as shown below:
![image](https://user-images.githubusercontent.com/11226469/118721487-d8c32a80-b822-11eb-84c5-150ae10e2932.png)

When I switch to read the multiple files is changes to csv as shown below and doesn't read the 31 rows.  It reads 28 usually and 29 in a leap year.

![image](https://user-images.githubusercontent.com/11226469/118721769-2e97d280-b823-11eb-9ece-f7155c75d805.png)

**Comment by Patowhiz** [comment]
@rdstern below is a screenshot of one of the files. Line 28 and below have empty spaces as missing values and my findings suggest that `rio` struggles with "guessing" all the contents of the rows correctly.  I confirmed this by even importing a single file with such contents using `rio`. After discussing with @dannyparsons I think we may have to now also enable the 2 other text radio buttons for multiple files import. This may involve wrapping another command around the `readr` commands that read these types of files correctly.

 
![fixed width file](https://user-images.githubusercontent.com/21179007/119852357-14fe2700-bec4-11eb-9afd-6d92ed52eb24.PNG)
