### ISSUE TITLE
A simple - maybe - problem with data imported from Excel

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6483]
Here is a simple data set in Excel.
[Voluntary stations_muchinga.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/6531626/Voluntary.stations_muchinga.xlsx)
I would like to import the data into R-Instat and the get the mean of the latitude data.

a) I can do it easily in Excel.  Just use the sum button and ask for the mean.  
b) But I want to import into R-Instat and then analyse
c) When I import the lat has odd characters (in the grid view) and hence the variable is a character variable.
![image](https://user-images.githubusercontent.com/11226469/119336859-0d513f00-bc86-11eb-9236-e4a281746479.png)

d) When I look in R, the odd character appears as a space. 
e) If I try converting to numeric, it tells me 30 values are non-numeric.
f) So what should I do?

Looking up the answer maybe[ here](https://stackoverflow.com/questions/52722846/how-can-i-remove-non-numeric-characters-from-strings-using-gsub-in-r):

Can I "tidy" these data already in R-Instat - with an existing dialogue?  Does it need a new dialogue or a new option in an existing dialogue?

My main aim is to get rid of odd symbols/characters in numeric variables.  But note that an extension of the same option could be useful for character variables - see the station variable here?

**Comment by Patowhiz** [comment]
@rdstern the odd character is because of a different issue. I did research on it sometime back, I will link my comment to this issue. I agree the odd symbols are caused by the spaces in the numerics, you can check and see this in R-Instat **View Data Frame** option or R-Studio data viewer. 

I did try to convert to numeric and it converted fine. I think we can start by solving the display problems first.

**Comment by rdstern** [comment]
@Patowhiz has helped by identifying that the "diamonds" in the display of the lat and long variables above are actually (mainly) leading and trailing spaces.
So I can trim the lat and long variables first.  Then the problem almost disappears.

For long (longitude) it does disappear.  So the trimmed data converts nicely into numeric.  

Hence initially a  @dannyparsons question.  In the conversion to numeric I don't see a problem if we add the trim routine automatically?  Could we do this.  It is (I suggest for us another) important step on making the conversion more painless.

There seems to be a small "sting in the tail" in converting the lat variable.  In 1 row the data are - 11.22 (Given by 1<diamond>11.22.  The stringr commands don't seem to be able to detect it as a space.  I checked by adding a space in another row and they are happy with a string given as -<space>.  

So I note this for reference now.  It may be solved by fixing the display of these data in the grid.

**Comment by Patowhiz** [comment]
This issue share the same problem explained in issue #6024.
