### ISSUE TITLE
Add language toggle button to subdialogs

### ISSUE THREAD

**Issue by lloyddewit** [africanmathsinitiative/R-Instat#6490]
R-Instat can now be displayed in English, French and Portuguese. Additional languages are planned. 
If you select a language that is not English, then a 'lan' button appears on each dialog. This allows you to toggle between your selected language and English.
If you toggle to English, and then open a subdialog, then the subdialog is still displayed in the non-English language.

It would be nice to also toggle languages in sub dialogs.

Some options:
- Display the subdialog in the same language as currently displayed in the main dialog
- Add a 'lan' button to the subdialog

@rdstern Do you have any other ideas or preferences?

**Comment by rdstern** [comment]
I had assumed we would add a Lan button to the sub-dialogues.  .  But, now you give me the option I quite like what I hope is the simplicity of the Lan button, just being on the main dialogue and then also applying to the sub-dialogues.  

The only down-side is that iyou suddenly wanted something in English, then you have to nip back to the main dialogue to do this.  But if we add it to the sub-dialogue could it be exactly the same as on the main dialogue?  So when you click on the button it automatically applies to the whole dialogue and subdialogue(s?)  It is identical code.  

I notice that when in Portuguese, it always starts again in Portuguese, so it doesn't remember.  I think that's fine too.

Is that causing trouble, or an easy way I can have "my cake and eat it"?

**Comment by rdstern** [comment]
After discussion with @dannyparsons he suggests the simplest to implement, and possibly to use, is to add the Lan button to the user control also on sub-dialogues.  Then to consider the button as a simple toggle on each form.  When you leave the form it returns to the selected language, e.g. French.  So, when you are on a main dialogue you can look at the English.  When you close that form it does not remember, and so when you return you are back in the French.

When you go to a sub-dialogue - that is another form.  It is in French.  You can toggle to English if you wish.  (Different tabs, e.g. the graphics sub-dialogue) are still the same form.  But press Return and you go back to the main form.  If you now press the sub-dialogue again, it has returned to French.

I assume when you return to the main dialogue, from the sub-dialogue then the main dialogue will also have returned to French.  I am not sure about that and am relaxed either way.  So the toggle is just a temporary look at the English for understanding.  If you want to stay with English longer, then go back to English!

**Comment by lloyddewit** [comment]
@N-thony Thank you for all your help with the translations. Please could you also implement the above proposal from @rdstern. I think that the subdialog 'lan' button can be implemented in the same way as the dialog 'lan' button. I'm happy to discuss if needed.
There may be a new release for 11/06/21. Please would it be possible to complete the implementation of this issue a few days before this release to allow time for review and testing?
