### ISSUE TITLE
Improve French translations

### ISSUE THREAD

**Issue by lloyddewit** [africanmathsinitiative/R-Instat#6512]
I suggest that we use this PR to document French translation issues that we come across.

In PR #6510, @rdstern wrote:

> 
> 
> I did find some curious translations in passing, but they aren't for here! log in the 2-variable model is translated as journal (like the log of activities, rather than the log function.) So I checked in the calculator and it is fine there - log stays as log. However the next key is tan and that is translated as brun (colour tan!)

**Comment by lloyddewit** [comment]
Comments from @rdstern in PR #6513:
> 
> 
> This looks good. I saw you solved your remaining issue of being able to add the translation to the calculation keyboard, which is where I started.
> This showed (possibly) a potential problem for those translations. The first is sqrt that is translated as racine. The tooltip is `frsquare root. For example sqrt(3) = 3 ^ 0.5 = 1.732`.
> 
> Another example is ceiling, translated as plafond. The tooltip is `frInteger above the given value. For example ceiling(3.5)=4, ceiling-3.5 = -3`
> 
> In each case we want to translate the first part, but we don't want to translate the formulae. So `ceiling` can be translated, but not `ceiling(` . Or perhap[s nothing when the sentence has an = sign.
> 
> I then looked at the column summaries. Here there isn't the fr and instead the translation is implemented - fine.
> 
> ![image](https://user-images.githubusercontent.com/11226469/120968283-907f9400-c760-11eb-89f8-4f4afaf424f4.png)

**Comment by lloyddewit** [comment]
The Toolbar Help button tool tip text is incorrectly translated into French (see PR #6529).
To fix this, the CrowdIn translation of 'He&lp' needs to be correctly translated (e.g. to '&Aide').
@dannyparsons do you know why the text of some tool bar buttons conatins an '&'?

**Comment by lloyddewit** [comment]
This spreadsheet was added to PR #6580 by @rachelkg . It describes additional open French translation issues.

[R-Instat.translation.changes.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/6830937/R-Instat.translation.changes.xlsx)

**Comment by lloyddewit** [comment]
> 
> 
> The Toolbar Help button tool tip text is incorrectly translated into French (see PR #6529).
> To fix this, the CrowdIn translation of 'He&lp' needs to be correctly translated (e.g. to '&Aide').
> @dannyparsons do you know why the text of some tool bar buttons conatins an '&'?

@rdstern I spoke to @dannyparsons about this a while ago (but forgot to document). he said that the '&' was added to indicate the shortcut key for that button. This causes problems for the translation. 
As far as I know, the shortcuts on the tool bar buttons are not visible, so the user probably doesn't know about them. Also when I tested I couldn't get the tool bar button shortcuts to work. If tool bar button shortcuts are essential then there may be other ways to implement them.
Do you have any objections if we remove the '&' from the tool bar buttons' tool tip text?

**Comment by rachelkg** [comment]
Hi Have updated my excel sheet. Here is the new version. I have also made a new sheet which only have translation comments, without any wider layout issues. 
[Just translation issues.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/6918259/Just.translation.issues.xlsx)
[R-Instat translation changes.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/6918260/R-Instat.translation.changes.xlsx)

**Comment by rachelkg** [comment]
Here is the newest iteration of the translation issues document. 
[R-Instat translation changes Aug 19th.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/7034669/R-Instat.translation.changes.Aug.19th.xlsx)

**Comment by rachelkg** [comment]
And one more newer version
[R-Instat translation changes Aug 24th.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/7042151/R-Instat.translation.changes.Aug.24th.xlsx)

**Comment by lloyddewit** [comment]
This issue is from 20+ months ago. I think all the points raised are fixed in 0.7.10.
