### ISSUE TITLE
Read data from lists in new package dslabs

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6514]
The dslabs package package is described as follows:

`"Datasets and functions that can be used for data analysis practice, homework and projects in data science courses and workshops. 26 datasets are available for case studies in data visualization, statistical inference, modeling, linear regression, data wrangling and machine learning."`

It provides the examples for the Harvard book on data science called ["Introduction to Data Science"](https://rafalab.github.io/dsbook/).  We are using this book on the Pakistan course.

I have checked and all except 2 of the data sets read trivially into R-Instat from the library.  The 2 awkward ones are brea and tissue_gene_expression.  They each produce a list.  This generates an error and (I think) half the data are read in.  I guess it might be producing multiple data frames and it currently just reads one of them.

a) Could this be corrected
b) Could the issue to add this package also be included for the next version.

**Comment by Patowhiz** [comment]
> The 2 awkward ones are brea and tissue_gene_expression. 

@rdstern just for clarity, when you say, **brea**,  you mean **brca**? I could only find **brca** in the package [documentation](https://cran.r-project.org/web/packages/dslabs/dslabs.pdf).

**Comment by rdstern** [comment]
@Patowhiz yes - brca and one other produce a list.
