### ISSUE TITLE
Adding Swahili as a 4th language!

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6520]
The documentation team, particularly @berylwaswa are very keen to add Swahili into R-Instat.  I am interested, (as they are keen), for 3 reasons:
a) Fits well with our uses of the software.  Great reason to write back to TMA as it could become a winner in Pakistan.
b) Shows how easily (I hope) that a language can be added
c) Good test of a language that might be sort on modern technical terms

Could @dannyparsons please confirm that we can add the machine translation - if easy, please add.
Then could @Ivanluv please add Swahili to the drop-down

Then they will be ready to go.  Good then to introduce @berylwaswa (and also Rachel for the French) to crowdin.

**Comment by rdstern** [comment]
@Ivanluv could you add Swahili back into the language options.

**Comment by Ivanluv** [comment]
@rdstern  I have made the addition
