### ISSUE TITLE
Add pie and donut charts back to the bar chart dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6526]
Pie charts were implemented very simplistically in R-Instat.  They need to be there again.  

There could also usefully be multiple pie, i.e. multiple circles and also donut charts with one or more rings.  This means (like bar charts) there can be 2 factors, though they are only sendible if the second factor has relatively few levels, i.e. a limited number of rings

[Here](https://biostats.w.uib.no/creating-a-multiple-pie-donut-chart/) is one of a number of sites that discuss these possibilities.  

In the bar chart dialogue there are 2 alternative ways of implementing these options:

a) We could have Pie Charts and Donut charts as 2 further radio buttons at the top - or a single button for both
b) We could have an Orientation pull-down dialogue, for Both the coord flip, possibly called Vertical (default) Horizontal and the Polar (pie), Polar (Donut) as options.

I would prefer the Orientation pull-down.  It fits well with the concept of polar in ggplot, and it downplays the importance of pie charts - which I am happy with too!.  

Here are some examples - again from MICS survey snapshots:

![image](https://user-images.githubusercontent.com/11226469/121752624-6e8f6400-cb08-11eb-88c0-342fb203d923.png)

![image](https://user-images.githubusercontent.com/11226469/121752694-97175e00-cb08-11eb-930a-75b8d4e903f9.png)

![image](https://user-images.githubusercontent.com/11226469/121752737-b2826900-cb08-11eb-85ba-7554c977f050.png)

**Comment by lilyclements** [comment]
I've had a look at the bar chart dialog and how things are running at the moment. 

Currently there are options that are running for "bar chart" that can run in R for "pie chart", and vice versa - for example:
* In R-Instat we offer a `x` and `fill` parameter for "bar chart", but only a `fill` parameter for "pie chart".
However, in R, a pie chart with an `x` parameter is just a donut chart.
* The `position` parameter also changes whether the polar graph is a pie (`position = "stack"`) or a donut (`position = "dodge"`). Currently `position` is only an option for "bar chart".

So the main dialog can look like it currently does under the "Bar Chart" option with a few amendments:
1. At least one of the "X-Variable" or "By Factor" receivers should be filled - they do not need to both be filled.
2. The "Position" label and input should be visible for all options
3. Currently colons are missing so these should be added
4. Currently under "bar chart" if you change the input from "Value" to "Variable", you can see part of a label under another label
5. If you change the input from "Value" to "Variable", "OK" should not be enabled if the y-variable receiver is empty (currently, OK is enabled under pie chart which results in a bug).
6. There is the additional orientation option which can be a input box with "horizontal", "vertical", and "polar" as options - or alternatively, it could be done with check boxes (see below).


**Orientation Option:**
Overall I think it is pretty straight forward to combine bar and pie (and donut) to be on the same "page".

The "vertical" R code always runs with additional layers added if "horizontal" or "polar" are selected.
Additionally, there is a way to "flip" the co-ordinates for the polar option.
Since the R code for the "horizontal" and "polar" changes are layers that are "added", and that the polar co-ordinates can be flipped in R, I wonder if instead of an orientation pull down we have two check boxes:

"Flip Co-ordinates" and "Polar Co-ordinates".

```
library(ggplot2)
data(diamonds)

fun_1 <- ggplot(diamonds, aes(x = cut)) + geom_bar()
```

* If "Flip Co-ordinates" **is** selected and "Polar Co-ordinates" **is not** selected then to function run then we just add `coord_flip()`, 
`fun_1 + coord_flip()`
* If "Flip Co-ordinates" **is not** selected and "Polar Co-ordinates" **is** selected then to function run then we just add `coord_polar(theta = "y")`, 
`fun_1 + coord_polar(theta = "y")`
* If "Flip Co-ordinates" **is** selected and "Polar Co-ordinates" **is** selected then to function run then we add the `coord_polar` function but change the `theta` value to be `x` instead:
`fun_1 + coord_polar(theta = "x")`

The four resulting plots are:
![image](https://user-images.githubusercontent.com/21180424/121917135-b4c50d00-cd2c-11eb-8d5d-2ca931b0d788.png)

As a result, I suggest we have the "orientation" option as two checkboxes. However is there anything I've missed where a drop down box is preferred?

**Comment by lilyclements** [comment]
I'll add some R-code here for the other options with the `fill` parameter:

```
library(ggplot2)
library(gridExtra)
data(diamonds)

fun_1 <- ggplot(diamonds, aes(x = cut)) + geom_bar()
```

**Just the `fill` parameter is given and `x = ""`**
Since the `fill` parameter is given, the `position` parameter can change

```
#position = "stack"
fun_1 <- ggplot(diamonds, aes(x = "", fill = color)) +
  geom_bar(position = "stack")
a <- fun_1 + labs(subtitle = "fun_1")
b <- fun_1 + coord_flip() + labs(subtitle = "fun_1 + coord_flip()")
c <- fun_1 + coord_polar(theta = "y") + labs(subtitle = "fun_1 + coord_polar(theta = y)")
d <- fun_1 + coord_polar(theta = "x") + labs(subtitle = "fun_1 + coord_polar(theta = x)")
grid.arrange(a,b,c,d, top = "For position = stack")
```

![image](https://user-images.githubusercontent.com/21180424/121918783-4b45fe00-cd2e-11eb-8080-8201533fb330.png)

```
# position = "dodge"
fun_1 <- ggplot(diamonds, aes(x = "", fill = color)) +
  geom_bar(position = "dodge")
a <- fun_1 + labs(subtitle = "fun_1")
b <- fun_1 + coord_flip() + labs(subtitle = "fun_1 + coord_flip()")
c <- fun_1 + coord_polar(theta = "y") + labs(subtitle = "fun_1 + coord_polar(theta = y)")
d <- fun_1 + coord_polar(theta = "x") + labs(subtitle = "fun_1 + coord_polar(theta = x)")
grid.arrange(a,b,c,d, top = "For position = dodge")
```

![image](https://user-images.githubusercontent.com/21180424/121918878-5d27a100-cd2e-11eb-9c80-3e04d9edf51a.png)

**Both the `fill` and `x` parameters are given**
Since the `fill` parameter is given, the `position` parameter can change
```
# position = "stack"
fun_1 <- ggplot(diamonds, aes(x = cut, fill = color)) +
  geom_bar(position = "stack")
a <- fun_1 + labs(subtitle = "fun_1")
b <- fun_1 + coord_flip() + labs(subtitle = "fun_1 + coord_flip()")
c <- fun_1 + coord_polar(theta = "y") + labs(subtitle = "fun_1 + coord_polar(theta = y)")
d <- fun_1 + coord_polar(theta = "x") + labs(subtitle = "fun_1 + coord_polar(theta = x)")
grid.arrange(a,b,c,d, top = "For position = stack with an x parameter given")
```
![image](https://user-images.githubusercontent.com/21180424/121919130-9d871f00-cd2e-11eb-967f-a8b2aee25030.png)

```
# position = "dodge"
fun_1 <- ggplot(diamonds, aes(x = cut, fill = color)) +
  geom_bar(position = "dodge")
a <- fun_1 + labs(subtitle = "fun_1")
b <- fun_1 + coord_flip() + labs(subtitle = "fun_1 + coord_flip()")
c <- fun_1 + coord_polar(theta = "y") + labs(subtitle = "fun_1 + coord_polar(theta = y)")
d <- fun_1 + coord_polar(theta = "x") + labs(subtitle = "fun_1 + coord_polar(theta = x)")
grid.arrange(a,b,c,d, top = "For position = dodge with an x parameter given")
```
![image](https://user-images.githubusercontent.com/21180424/121919198-ae379500-cd2e-11eb-940d-4d0e1ec94cac.png)

**Just the `x` parameter is given**
See the plots in the post above.

Note this also works for other `position` options, e.g. `position = "jitter"`, etc

**Comment by lilyclements** [comment]
Update: PR #6517 changes this dialog to be in terms of three radio buttons at the top "Frequency", "Value", and "Pie".

I suggest instead that there are two options "Frequency" and "Value":

1. "Value" can stay as it is.
2. "Frequency" could have the new checkbox: "Polar Coordinates".

Then the code for the this new checkbox under frequency is the same as outlined above:

```
library(ggplot2)
data(diamonds)

fun_1 <- ggplot(diamonds, aes(x = cut)) + geom_bar()
```

* If "Flip Coordinates" is selected and "Polar Coordinates" is not selected then to function run then we just add `coord_flip()`,
`fun_1 + coord_flip()`
* If "Flip Coordinates" is not selected and "Polar Coordinates" is selected then to function run then we just add `coord_polar(theta = "y")`,
fun_1 + coord_polar(theta = "y")
(( If "Flip Coordinates" is selected and "Polar Coordinates" is selected then to function run then we add the `coord_polar` function but change the theta value to be `x` instead:
`fun_1 + coord_polar(theta = "x")`



Note that:
1. At least one of the "X-Variable" or "By Factor" receivers should be filled - they do not need to both be filled.
2. The "Position" label and input should be visible whether polar co-ordinates is checked or not
3. Currently colons are missing so these should be added
4. The new "Back to back" checkbox can also be added in, and only visible for the "Frequency" radio button, and when polar coordinates are not checked (see issue #6525 )

**Comment by lilyclements** [comment]
This should also work for the "Value" radio button. This is a lot slower when considering a data size the size of `diamonds` however. 

But to display the sort of results, I'll show an example in R, I'll give with a new sample data set.

```
# create data frame
my_df <- data.frame(
  class = c("1", "2", "3", "3", "4"),
  val = c(50, 60, 50, 100, 40),
  x = c("a", "a", "a", "b", "b")
)

# Without an X variable, with a Y variable, and with Position = "stack"
fun_1 <- ggplot(my_df, aes(x = "", y = val, fill = class)) + geom_bar(position = "stack", stat = "identity")
a <- fun_1 + labs(subtitle = "fun_1")
b <- fun_1 + coord_flip() + labs(subtitle = "fun_1 + coord_flip()")
c <- fun_1 + coord_polar(theta = "y") + labs(subtitle = "fun_1 + coord_polar(theta = y)")
d <- fun_1 + coord_polar(theta = "x") + labs(subtitle = "fun_1 + coord_polar(theta = x)")
grid.arrange(a,b,c,d, top = "No x variable; position = stack")

# Without an X variable, with a Y variable, and with Position = "dodge"
fun_1 <- ggplot(my_df, aes(x = "", y = val, fill = class)) + geom_bar(position = "dodge", stat = "identity")
a <- fun_1 + labs(subtitle = "fun_1")
b <- fun_1 + coord_flip() + labs(subtitle = "fun_1 + coord_flip()")
c <- fun_1 + coord_polar(theta = "y") + labs(subtitle = "fun_1 + coord_polar(theta = y)")
d <- fun_1 + coord_polar(theta = "x") + labs(subtitle = "fun_1 + coord_polar(theta = x)")
grid.arrange(a,b,c,d, top = "No x variable; position = dodge")

# With an X and Y variable, and with Position = "stack"
fun_1 <- ggplot(my_df, aes(x = x, y = val, fill = class)) + geom_bar(position = "stack", stat = "identity")
a <- fun_1 + labs(subtitle = "fun_1")
b <- fun_1 + coord_flip() + labs(subtitle = "fun_1 + coord_flip()")
c <- fun_1 + coord_polar(theta = "y") + labs(subtitle = "fun_1 + coord_polar(theta = y)")
d <- fun_1 + coord_polar(theta = "x") + labs(subtitle = "fun_1 + coord_polar(theta = x)")
grid.arrange(a,b,c,d, top = "X variable; position = stack")

# With an X and Y variable, and with position = "dodge"
fun_1 <- ggplot(my_df, aes(x = x, y = val, fill = class)) + geom_bar(position = "dodge", stat = "identity")
a <- fun_1 + labs(subtitle = "fun_1")
b <- fun_1 + coord_flip() + labs(subtitle = "fun_1 + coord_flip()")
c <- fun_1 + coord_polar(theta = "y") + labs(subtitle = "fun_1 + coord_polar(theta = y)")
d <- fun_1 + coord_polar(theta = "x") + labs(subtitle = "fun_1 + coord_polar(theta = x)")
grid.arrange(a,b,c,d, top = "X variable; position = dodge")

```

![image](https://user-images.githubusercontent.com/21180424/122210957-1eb0f400-ce9e-11eb-9b45-a7da13ddf19c.png)

![image](https://user-images.githubusercontent.com/21180424/122210930-18227c80-ce9e-11eb-88e1-f0c85c372fe3.png)


![image](https://user-images.githubusercontent.com/21180424/122210900-10fb6e80-ce9e-11eb-9d58-73889e50fa03.png)

![image](https://user-images.githubusercontent.com/21180424/122210881-08a33380-ce9e-11eb-96f4-ab067b9aed30.png)

**Comment by rdstern** [comment]
@lilyclements those examples look great.  And just to mention with the Value button, it is almost always used (for bar charts) on data that have been summarised.  So, even with facets I would think it is very rare that the number of rows would exceed (say) 1000.  

This also fits with the Tufte principle, namely that you are using ink (a lot) to draw each bar (or arc).  So it is very wasteful and should usually not be used when there are many observations.  Of course, using ..count.. is different, because then there can be lots of data, but not then many bars.

**Comment by rdstern** [comment]
Damn I have just spent the morning and was about to report my "discovery"! for pie charts and donut charts!  Now, reporting it here I find I have now almost caught-up with what @lily has produced 3 weeks ago above!

So, I am back again to having the pie (and donut) charts to be a polar checkbox on the bar chart dialogue, rather than a button at the top.  

Below I give the code I used for the (usual) survey data.  

There are 2 parts to the "trick".  When we have this:

![image](https://user-images.githubusercontent.com/11226469/125168049-683de780-e19b-11eb-8aea-b468a056b7a0.png)

That's using summary data from the survey.  Now the counts (or any other summary are the Y, but we don't want an x.  This would work as I want, if only this combination allowed Ok to be enabled.  You see the other factor is the Fill, which we do want.

That's the passport to the bar chart I did want (which @lilyclements shows above, and which I haven't been able to get so far.  Namely:

So, put in any x you like (any variable)  and then use the secript button and then replace the x variable by `""`

So the code is as follows:

```
survey_by_village <- data_book$get_data_frame(data_name="survey_by_village")
last_graph <- ggplot2::ggplot(data=survey_by_village, mapping=ggplot2::aes(x="", y=count, fill=village)) + ggplot2::geom_bar(stat="identity") + theme_grey()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey_by_village")
data_book$get_graphs(data_name="survey_by_village", graph_name="last_graph")
rm(list=c("last_graph", "survey_by_village"))
```
And the graph isL

![image](https://user-images.githubusercontent.com/11226469/125168318-f1095300-e19c-11eb-981e-7ddd7fc4df30.png)

You can see that this is ready to make a good pie chart, when going to polar and it does.

Remember it is the y and not the x that goes to polar, i.e. the counts.  So add coord_polar("y") and you get a nice pie chart.
To get a nice donut you could make the value (say 2) Then you get the same graph, but going from an x of 1.5 to 2.5.  

(I think you could do this anyway.  It is ignored by the pie chart.  But then do xlim(0.5,2.5) To get a donut chart.  I need to check these limits.  






```
# Code generated by the dialog, Bar and Pie Chart

survey_by_village <- data_book$get_data_frame(data_name="survey_by_village")
last_graph <- ggplot2::ggplot(data=survey_by_village, mapping=ggplot2::aes(x=2, y=count,fill=village)) + ggplot2::geom_bar(position="stack", stat="identity") + theme_grey()+coord_polar("y")+xlim(0.2,2.5)
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey_by_village")
data_book$get_graphs(data_name="survey_by_village", graph_name="last_graph")
rm(list=c("last_graph", "survey_by_village"))

# Code generated by the dialog, Bar and Pie Chart

survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x="", fill=village)) + ggplot2::geom_bar(stat="count") + theme_grey()+coord_polar("y")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))

# Code generated by the dialog, Bar and Pie Chart

survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x=2, fill=village)) + ggplot2::geom_bar(stat="count") + theme_grey()+coord_polar("y")+xlim(0.2,2.5)
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))

# Code generated by the dialog, Bar and Pie Chart

survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x=variety, fill=village)) + ggplot2::geom_bar(stat="count",position="stack") + theme_grey()+coord_polar("y")+xlim(0.2,3.5)
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
last_graph
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))   
```

**Comment by lilyclements** [comment]
This is interesting. I didn’t realise about the option to set x as a fixed value but that looks great. 

If polar checkbox is checked, then am I correct in saying that
* either x or y can be filled (or as a fixed value?)
* or just fill can be filled (and x = “”)
* or fill and one of x or y can be filled

What about changing the coord_polar parameter to be the same as the variable in the aes, and use a dodge position parameter? Is this equivalent to a “flip coordinates” since the x and y axis names do change

Eg using your code above

```
# if x is the same in the coord polar argument as the aesthetics argument 
survey <- data_book$get_data_frame(data_name="survey")
last_ graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x="", fill=village)) + ggplot2::geom_bar(position="dodge") + theme_grey()+coord_polar("x")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
last_graph
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))   
```


```
# if x is differen in the coord polar argument to the aesthetics argument 
survey <- data_book$get_data_frame(data_name="survey")
last_ graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x="", fill=village)) + ggplot2::geom_bar(position="dodge") + theme_grey()+coord_polar("y")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
last_graph
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))   
```

**Comment by rdstern** [comment]
I have now looked a bit further at these (new to me) geoms etc.

Let's start with Lollipop charts.  I took data from the hh dataframe from the Pakistan MICS survey, and got the percentage using Urdu from each district.  Here is my data frame:

And here is the dialogue:

![image](https://user-images.githubusercontent.com/11226469/125188924-a1269c80-e22d-11eb-9937-4d6dcb1c6b37.png)

with the resulting bar chart:

![image](https://user-images.githubusercontent.com/11226469/125189034-33c73b80-e22e-11eb-9304-696387fb9941.png)

The code is as follows:

```
# Code generated by the dialog, Bar and Pie Chart

hh_by_HH7 <- data_book$get_data_frame(data_name="hh_by_HH7")
last_graph <- ggplot2::ggplot(data=hh_by_HH7, mapping=ggplot2::aes(x=HH7, y=percent_urdu)) + ggplot2::geom_bar(position="dodge", stat="identity") + theme_grey() + ggplot2::coord_flip()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="hh_by_HH7")
data_book$get_graphs(data_name="hh_by_HH7", graph_name="last_graph")
rm(list=c("last_graph", "hh_by_HH7"))

```
Now, suppose we ass ggalt and code geom_lollipop.  Then just changing geom_bar to geom_lollipop i.e

```
hh_by_HH7 <- data_book$get_data_frame(data_name="hh_by_HH7")
last_graph <- ggplot2::ggplot(data=hh_by_HH7, mapping=ggplot2::aes(reorder(x=HH7,X=percent_urdu), y=percent_urdu)) + ggalt::geom_lollipop() + theme_grey() + ggplot2::coord_flip()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="hh_by_HH7")
data_book$get_graphs(data_name="hh_by_HH7", graph_name="last_graph")
rm(list=c("last_graph", "hh_by_HH7"))
```
This seems a "bargain, so we could do this!?
Here is the resulting lollipop graph.
![image](https://user-images.githubusercontent.com/11226469/125190700-5b220680-e236-11eb-8194-a1ff933e9777.png)

You will notice I have also added the sorting - which would be equally useful for the bar charts.  It just adds the reorder function to the R code.  So Order could be a new checkbox.  If checked, then there could be another checkbox, with ascending as the label.  If checked it simply does minus the sorting variable.

I couldn't quite see how to do this with the frequency option and then ..count.., which I think is now better written as stat(count)?

If putting this option in as a possible checkbox, then also consider allowing the colour and size of the point to be specified on the main dialogue.  And the special option button would change to Options Lollipop

 

.

**Comment by rdstern** [comment]
@N-thony I suggest you could add simple pie and donut charts in the existing back-to-back pull request.  My initial suggestion is as follows:
a) You implement Ok when either the x (for frequency) is not empty, or when the Fill is not empty.  In the value case you need the Variable and then either the X or the by.
b) You put the Polar checkbox back.  Next to it you have a small group box for 2 option buttons.  They are O Donut O Pie.  This box is always visible, but disabled unless you have the right combinations.  (For now, while we are testing, it can always be enabled.)  I think for Frequencies it needs the Variable (X) to be empty.  For Value it needs just a single Y variable.  
c) We may later want some further options for either the pie or the donut.  For now use the code below for the pie to dictate the correct R code.  I think it is coord_polar("y") each time and you need x = "" for the pie chart and possibly x=2 for the donut chart.  You need width = 1 for each.  I think you need xlim(0.2,2.5) for the donut charts.
d) Here is the code for pie charts from the [Data Visualisation with [R](https://rkabacoff.github.io/datavis/Univariate.html#pie-chart) book.

```
# create a basic ggplot2 pie chart
 plotdata <- Marriage %>%
    count(race) %>%
    arrange(desc(race)) %>%
    mutate(prop = round(n * 100 / sum(n), 1),
           lab.ypos = cumsum(prop) - 0.5  *prop)
  
  ggplot(plotdata, 
         aes(x = "", 
             y = prop, 
             fill = race)) +
    geom_bar(width = 1, 
             stat = "identity", 
             color = "black") +
    coord_polar("y", 
                start = 0, 
                direction = -1) +
    theme_void() 
```

**Comment by lilyclements** [comment]
**Reorder by Frequency**

> I couldn't quite see how to [reorder by frequency] with the frequency option and then ..count.., which I think is now better written as stat(count)?

We can do it with the frequency option by the `fct_reorder` function in the `forcats` package (for `geom_bar` only)

e.g. using the `diamonds` data set:

```
library(ggplot2)
ggplot2::ggplot(diamonds, ggplot2::aes(fct_infreq(color), fill = cut)) +
  ggplot2::geom_bar(position = "stack", stat = "count") +
  theme_grey() +
  ggplot2::coord_flip()
```

![image](https://user-images.githubusercontent.com/21180424/126074597-1c94157b-a8fa-4dab-a5ff-a781079e5d00.png)


**Donut/Pie Options**

Looking at the various options we have a frequency and a value option where:
**Frequency:** `geom_bar`, and then an optional `+ geom_polar()` after `geom_bar`. (i.e., not `geom_lollipop()`?)
**Value:** `geom_bar`, `geom_lollipop`, and then an optional `+ geom_polar()` after `geom_bar`.
Is this correct?

As @rdstern says - when we use the Value or Frequency option, a pie vs a donut plot is made by changing `x = ""` to `x = 2` and adding an `+ xlim()` option.
However, on the Frequency option, an `x` and `by` variable can be given. In the case that an `x` variable is given,  and polar coordinates are run, the plot isn't really a pie-chart.
I'm not sure if a donut or pie radio button should be given in this instance.

e.g. a windrose-esque plot is created if `x`, `fill`, and `coord_polar` all run:
```
ggplot(diamonds, aes(x = cut, fill = color)) +
  geom_bar() +
  coord_polar()
```
![image](https://user-images.githubusercontent.com/21180424/126075978-aceebb45-f2ee-4fe6-976f-b3a43d0b9d00.png)


Then this can change to a donut-style plot if `theta = "y"` in the `coord_polar` function
(Side note: if we have `y = ...` in the `aes` function and `theta = "y"`, then the plot is windrose-style - similarly so if both parameters are `x`.
If one is `y` and the other is `x` then we get a donut-style plot.)
```
ggplot(diamonds, aes(x = cut, fill = color)) +
  geom_bar() +
  coord_polar(theta = "y")
```
![image](https://user-images.githubusercontent.com/21180424/126076027-494c7134-bb9d-4b1e-8d4c-336ebe62b114.png)

Playing with the `position` parameter can also create other plots - such as a "race track" plot
```
ggplot(diamonds, aes(x = cut, fill = color)) +
  geom_bar(position = "fill") +
  coord_polar(theta = "y")
```
![image](https://user-images.githubusercontent.com/21180424/126075991-c1fcfccf-570e-42fe-9cb1-16117725dbef.png)

@rdstern 
1. Does the `fct_reorder` code above do what you want it to do for the Frequency option?
2. Do we want to offer changing the `theta` parameter in `coord_polar` to create to a more windrose-esque plot?
3. How should we handle the instance where the user is on "Frequency", both variables are given, and a polar plot is selected? Is there a way to make a pie chart here that I have missed, or should we not allow the user to specify which type of polar plot as directly, or is there an alternative solution?

**Comment by N-thony** [comment]
@rdstern this issue seems to be fully solved, could we close it? Thanks

**Comment by rdstern** [comment]
ok
