### ISSUE TITLE
Minor problems with the split dialogue 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6532]
[data to split.zip](https://github.com/africanmathsinitiative/R-Instat/files/6651387/data.to.split.zip)

These data need to be split:
Here is the dialogue in Prepare > Column: Text > Split

Note I have masse the prefix into x and am using a space to split the components.
a) The first time I ran this, it worked - well almost:

Here is the command it generated:

```
# Code generated by the dialog, Split Text Column
V1 <- data_book$get_columns_from_data(data_name="data", col_names="V1", use_current_filter=FALSE)
split <- stringr::str_split(string=V1, pattern=" ", n=Inf, simplify=TRUE)
data_book$add_columns_to_data(data_name="data", col_name="split", col_data=split, use_col_name_as_prefix=TRUE, before=FALSE)
```
It correctly identified the pattern = " " , but it ignored my request for the prefix geing x and insisted it still be split.  So it generated columns split1, to split8.

b) I deleted the variables and ran again.  

The dialogue still looks as shown, but now, although space is shown in the dialogue it has another bug.  The code now is as follows:

```
# Code generated by the dialog, Split Text Column
V1 <- data_book$get_columns_from_data(data_name="data", col_names="V1", use_current_filter=FALSE)
split <- stringr::str_split(string=V1, pattern="Comma ", n=Inf, simplify=TRUE)
data_book$add_columns_to_data(data_name="data", col_name="split", col_data=split, use_col_name_as_prefix=TRUE, before=FALSE)
```

It now says pattern = "Comma " in the code,  i.e. Comma + <space> and so doesn't now work well at all!

**Comment by shadrackkibet** [comment]
@lloyddewit if memory serves me right. Did we agree that you are going to check that this is fixed from your open PR?

**Comment by lloyddewit** [comment]
> 
> 
> @lloyddewit if memory serves me right. Did we agree that you are going to check that this is fixed from your open PR?

@shadrackkibet Yes correct, this issue will close automatically when PR #6621 is merged
