### ISSUE TITLE
Small improvement in geom_text and geom_label

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6549]
I first put this improvement in a more general context.  We need to be able to add labels (and texts) to our plots.  Here is an example.  It is from the R Graphics cookbook which is available [here](https://r-graphics.org/index.html).

![image](https://user-images.githubusercontent.com/11226469/122962581-79a28980-d37d-11eb-86ea-87a833f76467.png)

This shows the small improvement we need in geom_text and geom_label.  Here is a screenshot from the existing sub-dialogue for geom_text:
![image](https://user-images.githubusercontent.com/11226469/122963732-74920a00-d37e-11eb-8d73-95fe61bb639b.png)

Looking at the code above for the graph, we already have position = dodge.  We need to add further options to include position = position_dodge(0.9).  So, in the pull-down, that should be added, i.e. position_dodge (I notice we already have position_jitterdodge(), which is similar.  There are others I assume.  

And when any of these are given, then we need to add a pull_down to be able to give the 0.9.  I assume 0.9 could usefully be the default (it is the default width of bars).

There is also position=position_stack where the obvious argument is hjust.  There is a second - reverse =  TRUE or FALSE
I am not sure we need position = position_jitterdodge() - that is mainly for jittered point, not for texts.  But position = position_nudge could be useful to add.  That has an x and a y to include.

So, I think we could consider getting rid of jitterdodge and include dodge, stack and nudge.  That is unless we have a single user control for this, which is included in more geoms?

**Comment by lilyclements** [comment]
I've come across the `ggrepel` package for labelling and text functions (https://cran.r-project.org/web/packages/ggrepel/vignettes/ggrepel.html). Unlike in `ggplot2` functions, `ggrepel` functions have "Text labels repel away from each other, away from data points, and away from edges of the plotting area (panel)". 

e.g.
![image](https://user-images.githubusercontent.com/21180424/126139937-789f16e1-413b-4b5c-8994-c3f40c517eb4.png)

All parameters and default values in `ggplot2::geom_text` are in `ggplot2::geom_text_repel` (except for `check_overlap` which can mean that some text labels are removed in `ggplot2::geom_text`) so it should not mean a big change if we opt to use it, but `ggrepel` can add more labelling options to the plot.
