### ISSUE TITLE
Small point on our base control in multiple languages

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6563]
Here is an example with our base control:

![image](https://user-images.githubusercontent.com/11226469/123769433-38503380-d8c1-11eb-9806-947d099a647b.png)

I am interested in the base control with the Comment line.  A trivial point is that the text could move over  very slightly, so the colon is clear.  But this is on every dialogue and I wonder if it could be translated?  There is an initial sentence, and then (I assume) the name of the dialogue as shown in the top left.  This then appears in the script and output windows, or can be edited by the user.

(That reminds me that we are inviting users to be using R-Instat with their own language settings on their machines.  I must mention this to our language testers, so we are prepared for possible problems!)

**Comment by lloyddewit** [comment]
@rdstern Thanks, I referenced this issue in issue #3721

**Comment by rdstern** [comment]
@lloyddewit I looked in a bit more detail.
I notice that the initial text for the comment (currently in English of course) is in the Comments Tab of the `Tools > Options` dialogue.
![image](https://user-images.githubusercontent.com/11226469/124586642-97c4bb00-de4e-11eb-8a13-088270686a2e.png)

This is where any change with translation would go presumably.  I note also that this dialogue is treated differently to others.  The Help button does not (yet?) allow the translation into English.  (And it doesn't figure in the last 10 dialogues used - which I suggest is ok.)
