### ISSUE TITLE
Add a reorder feature to bar charts

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6582]
Could you add a Reorder checkbox to the bar (and pie chart dialogue.  Default is unchecked.
If checked, then there could usefully be 4 options, namely Ascending, Descending, Reverse, None

In these options Ascending and Descending will be the common ones.  Ascending simply adds the reorder function to the command, DEscending makes it a minus!

![image](https://user-images.githubusercontent.com/11226469/124350954-88940200-dbef-11eb-94b4-3768fc786de3.png)

To reverse the order of the bars look [here](https://stackoverflow.com/questions/42710056/reverse-stacked-bar-order) perhaps.

Note that this will also apply to the lollipop charts that we are doing by adding geom_segment to the point plots.

**Comment by N-thony** [comment]
Great, I will work on this ASAP PR #6682 is merged.

**Comment by N-thony** [comment]
@rdstern I think now the bar chart dialog is ready for this issue to be implemented. I would like to add this into the bar chart dialog during the sprint. What do you think?
