### ISSUE TITLE
File > Open no longer reading multiple SPSS files

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6583]
It has read them in the past.  Now I get this message:
![image](https://user-images.githubusercontent.com/11226469/124364846-febe5600-dc3b-11eb-96a9-91aaa7032567.png)

It generated the following code, so I don't see how it could have worked?
```
# Code generated by the dialog, Import Dataset
files <- rio::import(file="C:/Users/RogerStern/Dropbox (SSD)/R-Instat Documentation/Data/Pakistan/Pakistan Punjab MICS6 Datasets")
data_book$import_data(data_tables=files)

rm(files)
```

I tried also with some climatic txt files - which worked and generated as follows:
```
# Code generated by the dialog, Import Dataset
files <- lapply(X=stats::setNames(object=list.files(path="C:/Users/RogerStern/Dropbox (SSD)/Roger/IDEMS/Pakistan workshops/F-ABAD/MAXT - Copy", pattern="\\.txt$", full.names=TRUE, ignore.case=TRUE), nm=tools::file_path_sans_ext(x=list.files(path="C:/Users/RogerStern/Dropbox (SSD)/Roger/IDEMS/Pakistan workshops/F-ABAD/MAXT - Copy", pattern="\\.txt$", full.names=FALSE, ignore.case=TRUE))), FUN=readr::read_table2, skip=4)
data_book$import_data(data_tables=files)

rm(files)

```

**Comment by Patowhiz** [comment]
@rdstern could you confirm that PR #6625 fixes this issue?

**Comment by rdstern** [comment]
Yes @Patowhiz I checked that aspect with the MICS data - 8 SPSS files - as part of the testing.  It imported fine.

**Comment by Patowhiz** [comment]
@rdstern thanks. Once PR #6625  is merged this will be fixed.
