### ISSUE TITLE
Improve appearance of language toggle button on tool bar

### ISSUE THREAD

**Issue by lloyddewit** [africanmathsinitiative/R-Instat#6588]
The language toggle button in the R-Instat tool bar is currently labelled 'Lan'. 
Could the appearance of this button be improved?
Please review the discussion and suggestions in PR #6572.

**Comment by rachelkg** [comment]
I am happy to have this assigned to me, though I am afraid I do not know how to add the new icon to the tool bar. Could be a good job for @Patowhiz. Would you be able to take this on Patrick? 

In summary of the discussion, it seems people agree: 
That  the world symbol is a good choice for the tool bar. 
That the button toggles just the menu to English and back. 
That if possible there should be a tooltip which changes from "Switch menus back to English" when in (say) another language; and if in English Switch language for menus back from English.

**Comment by lloyddewit** [comment]
>
> That if possible there should be a tooltip which changes from "Switch menus back to English" when in (say) another language; and if in English Switch language for menus back from English.

@rachelkg , @rdstern For simplicity, could you accept a fixed tool tip that says something like 'Toggles the main window menus between the current language and English."

@rachelkg @Patowhiz @N-thony I think this task is a better fit for @N-thony rather than @Patowhiz . @N-thony kindly agreed to do this.

@rachelkg We would really still value your aesthetic input. @N-thony may ask you to provide a design for the button.

**Comment by rachelkg** [comment]
![108932826_m](https://user-images.githubusercontent.com/85707390/124972457-3e3fc600-dfdf-11eb-8c17-83861bd0abe5.jpg)

**Comment by N-thony** [comment]
> ![108932826_m](https://user-images.githubusercontent.com/85707390/124972457-3e3fc600-dfdf-11eb-8c17-83861bd0abe5.jpg)
> Here is the icon. I confirmed with the team that it was ok to buy this one, and have done so.
> 
> @lloyddewit yes having a static tooltip is fine. @N-thony please could you make the tool tip "Changes menu language to and from English."
> 
> Let me know if you need anything else.
> 
> Thanks,
> 
> Rachel

@rachelkg thanks for the icon and tooltip text suggestion. I will then go ahead to implement it.

**Comment by rdstern** [comment]
Just a trivial addition I add an English to make it simpler.  "Changes the menu language to English, anf from English"
