### ISSUE TITLE
.ctor errors found for two dialogs

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6591]
Hello, 

I am trying to make an adjustment in layout to Model - Fit Model - One Variable - Display Options - Likelihood tab. When I try to open it in visual studio I get this error message. Visual studio says it may become unstable and could result in data loss if i ignore it. Can anyone clarify what this means and how to resolve it? @rdstern @shadrackkibet 

Thank you 

![Error message](https://user-images.githubusercontent.com/85707390/125001393-5d524e00-e007-11eb-80a2-202303526f7d.png)
sage.

**Comment by rachelkg** [comment]
This is also the case for sdgOneVarCompareModels.vb

**Comment by lloyddewit** [comment]
@Gioche6 this issue looks similar to issue #6697 . You fixed this in PR #6736 . Please could you try and the issue above also? thanks
