### ISSUE TITLE
I Can't find Graph and Display Options subdialog in Visual Studio

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6595]
Hello @Ivanluv, 

I am having trouble tracking down a subdialog that I need to edit the layout of. Model - Two variable Fit Model - Graph and Display Options. 
![Graph and Display Options](https://user-images.githubusercontent.com/85707390/125118206-385fe880-e0a4-11eb-859a-25d1896ea19d.png)
 Might you be able to help with this? 

Thanks, 

Rachel

**Comment by Ivanluv** [comment]
@rachelkg sorry for the late response. Search for `sdgSimpleRegOptions` in the solution explorer

**Comment by rachelkg** [comment]
@Ivanluv Thank you!

**Comment by shadrackkibet** [comment]
Thanks, @rachelkg for your question. This has actually pointed out an inconsistency in the naming. The naming of dialogs and sub-dialogs should go hand-in-hand with their actual names eg **Graph and Display Options** should be renamed to `sdgGraphAndDisplayOptions`. This will make it easy to find dialogs, especially for new contributors.

I am just putting this on record here and therefore you do not need to change the name now.
