### ISSUE TITLE
Ticks in View menu not centered 

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6602]
Hello @shadrackkibet, 

I noticed that the ticks in the blue boxes of the view menu are not centered. They seem to be aligned to the top left. Would that be something that we could easily change? I think it would look much tidier. 

Thanks, 

Rachel 
![View menu](https://user-images.githubusercontent.com/85707390/125533720-a8414bc0-723c-4f05-be0c-c00750d3689f.png)

**Comment by shadrackkibet** [comment]
Thanks, @rachelkg for pointing this out. We also have such issues with the toolbar icons (Dataframe/Column Metadata, script and log window). I investigated before and couldn't find an easier way to position ticks. Therefore this requires some bits of research to fix.

**Comment by rachelkg** [comment]
Thanks @shadrackkibet. I am not the right person to decide how important this is and how much time should be invested. andy thoughts @rdstern?
