### ISSUE TITLE
Wind/pollution Rose dialog empty 

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6603]
Hello @HawardKetoyoMsatsi, 

I have found that the Wind/Pollution Rose dialog is empty. @rdstern suggested that you might know whether it should be deleted or fixed. 

Thanks, 

Rachel
![Wind Pollution Rose](https://user-images.githubusercontent.com/85707390/125535435-4685f3d7-a29d-4dfd-8e1c-f3e40884b786.png)

**Comment by HawardKetoyoMsatsi** [comment]
Hello @rachelkg. 
From my end everything seems to be working fine. Try pulling the most recent changes and check if the problem still persists. The related PR #6400 was merged a week ago.

**Comment by rachelkg** [comment]
@HawardKetoyoMsatsi Thanks, I will pull the most recent version and recheck.
