### ISSUE TITLE
Renamed Scatter to Point Plot Menu

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#6609]
I noticed that the scatter plot menu has been renamed to  Point Plot.
The dialog header still reads Scatter Plot, this needs to be changed to Point Plot also.

@rdstern also partly suggests that dialog header could be Scatter/Point Plot. I suggest the menu to also be labelled the same.

**Comment by maxwellfundi** [comment]
@anastasia-mbithe if this has not been done Could you help @derekagorhom to get it done as one of his initial tasks.

**Comment by anastasia-mbithe** [comment]
@maxwellfundi do we have to rename the menu name to Scatter/Point Plot? Since @rdstern had previously suggested I change it to Point(Scatter) Plot, which is already in place.

**Comment by shadrackkibet** [comment]
Let us close this issue for now. We agreed to use `Point(Scatter) Plot` for now. So nothing to change.
