### ISSUE TITLE
Add dot plots to the histogram dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6615]
I am now following the order of graphs in the book on [Data Visualisation with R](https://rkabacoff.github.io/datavis/Univariate.html#dot-chart).  It has a section in chapter 3 on dotplots.  They are shown there as a simple alternative to a histogram - and particularly when the dataset isn't too large.

@HawardKetoyoMsatsi I am combining this addition for you to do, and also to use this example to introduce @Cal-Insta to being able to make simple improvements to a dialogue.  Here is what I suggest:
a) @HawardKetoyoMsatsi to add `Display as Dotplot `checkbox to the dialogue, just as you have done to add rifdgeplots to the density option on the same dialogue.
b) So, when the checkbox is checked the Histogram Options button will also change to become Dotplot Options.
c) @Cal-Insta to test the changes, using an example from his own data, and also the example from the book
d) The example from the book then considers options to make the plot better.  Check that these are all available from the sub-dialogue.
e) It could be useful to have some of these options available on the main dialogue.  Some will be equally useful whether the display is a histogram or a dotplot.  Others might be for just one or other?  If you think it would be useful, then propose which of these options could be on the main dialogue.  
f) Assuming there are some, then perhaps @HawardKetoyoMsatsi adds the first option and @Cal-Insta then adds the others.

**Comment by HawardKetoyoMsatsi** [comment]
@Cal-Insta please how is the testing going on.

**Comment by Cal-Insta** [comment]
@HawardKetoyoMsatsi the display as dot plot works ok. I think we can now look at the plot options.
