### ISSUE TITLE
Add  rcookbook and ggmap packages to R-Istat

### ISSUE THREAD

**Issue by Wycklife** [africanmathsinitiative/R-Instat#6616]
These packages are partly to be able to use all the datasets in the book called Data Visualisation with R. These should be included in the next release.

**Comment by shadrackkibet** [comment]
@Wycklife Thanks for adding the request. Just to note that we always want to manage additions of new packages in a single PR. In this case, we already have a new PR (#6562) so you should have this as a comment there and make sure you reference a PR that requires these packages.
