### ISSUE TITLE
Small change and some questions on the general Graphics dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6633]
The initial change is trivial.  At the start there is only one real control and that is the Plot Options.  Please could that control be moved, so it is in the same place as in the other dialogues.

@shadrackkibet the reason I am suggesting you for this is that I wonder what else we might add to this main dialogue that is perhaps different to the other plotting dialogues, and that might make it a more attractive dialogue to use.  Here are my initial suggestions.  Unless they are easy, and obviously sensible to you, this is for reactions and discussion initially.
a) A button with label `Main variable`s  Perhaps that's the equivalent to (say) Boxplot Options on the ordinary graphics dialogues.  If used, then it opens a dialogue with the usual(?) controls.  So Variable Selector on left.  Possibly even Single/Multiple, for Y, X Variable, Factor OPtional, and then Also Facet Variable - possibly even 2 facet variables.  This would also give access (automatically) to the Data Options:

![image](https://user-images.githubusercontent.com/11226469/126511290-439cd0d4-00c1-4f5a-8c83-0079d1f5e317.png)

Bit like this.  Not sure there what Group is there for?  So, roughly this plus Facet or Facet 1, Facet 2.  The factor (Optional)might be labelled as Variable (Fill) and perhaps the Groups could be Variable (Colour).

We might not allow the Single/Multiple as this could complicate the code - at least initially.
This adds the first part of the command, so something like:
`last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(y=yield, x=village, colour=fertgrp, fill=fertgrp)) + `

plus the facet part of the command!  No geom, because we don't have any yet.

Then  on the right-hand side we add some options that could apply to the dialogue as a whole.
a) Theme
b) Legend
c) Coord-flip
d) Title, Subtitle, Caption
e)? what else?

We still have to build up the layers, but it becomes quite nice (and simple) to use?

**Comment by rdstern** [comment]
@N-thony After discussion with @volloholic here are now the suggestions for the new design.
a) The dialogue is "deeper", so the current Layers control moves downwards.  It is below the "usual" data selector, shown above.
b) Add the "usual data selector as shown above, i.e. Data Frame + Variables + Add + Data Options
c) On the right - again as shown above - have the usual 3 receivers, i.e. Single/Multiple. x variable, and the third is labelled Fill/Colour:  (The word optional is omitted.
d) the R code from these receivers gives the ggplot function, with mapping =  aes(y= , x = , colour = , fill =
e) If the y variavbles are multiple, then variable is generated (as for many specific dialogues and the fill/colour has this variable.  
f) Later there may be a checkbox with label Stacked variable into x.
g) The Layer control is on the left-hand side, below the data selector.
h) the current Plot Options button moves to the middle of the dialogue, below the Data Options button.
i) There is a new Facets button, below the new position of the plot options.  This goes to the usual sub-dialogue, but straight to the Facets tab.  Possibly the Facets checkbox will be ticked then too.
j) There is similarly a Themes button, below the Facets, which takes you straight to the Themes tab in the sub-dialogue.

**Comment by shadrackkibet** [comment]
This is enough for work to start. I will give my inputs when we have some of this in the dialog. @N-thony please proceed with the task.

**Comment by rdstern** [comment]
@shadrackkibet thanks for that input.  It will be good to have the changed version of this dialogue in time for the sprint and then to discuss further.  I see that as a parallel of discussions we will have on the new bar chart by then.  And they can be driven by examples of use of the current dialogues.

**Comment by shadrackkibet** [comment]
@rdstern absolutely! @N-thony please feel free to get in touch if you need any help to make progress. Let's work on these points and have something to push further during the sprint which is approaching fast. Let the work do the talking!

**Comment by N-thony** [comment]
> @rdstern absolutely! @N-thony please feel free to get in touch if you need any help to make progress. Let's work on these points and have something to push further during the sprint which is approaching fast. Let the work do the talking!

Sure! I will then consider this as an urgent task, I will start to work on it by tomorrow morning after my chat with @rdstern.
