### ISSUE TITLE
Small bug to fix on visdat dialogue, plus an improvement

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6637]
[data-es-2009.zip](https://github.com/africanmathsinitiative/R-Instat/files/6870776/data-es-2009.zip)

Here is a file that can be used for the Prepare > Check Data > Visdat dialogue

It is useful to draw a sample.  I suggest 0.1.  Here is the dialogue - slightly different data

![image](https://user-images.githubusercontent.com/11226469/126831699-bf1e84c5-d222-4982-86cd-ea07a675395e.png)

And here is the result:
![image](https://user-images.githubusercontent.com/11226469/126831845-772b305e-fb26-4ee1-8f88-6d015a2b0efa.png)

Here is (roughly) the code generated - though on a slightly different file:

```
# Code generated by the dialog, Visualise Data

es_2009_2019 <- data_book$get_data_frame(data_name="es_2009_2019")

last_graph <- visdat::vis_dat(es_2009_2019 %>% dplyr::filter(as.logical(rbinom(n=nrow(es_2009_2019), size=1, prob=0.01))), sort_type=FALSE, palette="default", warn_large_data=TRUE, large_data_size=5900000) 
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="es_2009_2019")
data_book$get_graphs(data_name="es_2009_2019", graph_name="last_graph")
rm(list=c("last_graph", "es_2009_2019"))

```
It works fine the first time.  Here is (roughly) the graph:

![image](https://user-images.githubusercontent.com/11226469/126831488-ca25fcbe-0bf6-430c-9416-efd389ebe145.png)

a) There is one problem to fix.  When you return to the dialogue and run again, then it gives an error.  When you examine the code the second line is now this:

`last_graph <- visdat::vis_dat(dplyr::filter(as.logical(rbinom(n=nrow(es_2009_2019), size=1, prob=0.01))), sort_type=TRUE, palette="default", warn_large_data=TRUE, large_data_size=5900000)

When you compare with the line above you can see it has now omitted this part: `es_2009_2019 %>% `
`
b) It would occasionally be good to be able to control the size of the x-text.  Here it is too large (with 130 variables) to be able to read clearly.  Now the result is a ggplot2 object, so we can add to it.  So there could be a checkbox with something like "Adjust size of variable names.  Default is unchecked.  If checked, there is an up-down.  I am not sure what the default is in the current code. (Try experimenting a bit, or look in the vid_dat function.  The up-down could be (perhaps) from 1 in steps of 0.1 to 15?  Then add the code if used as follows+
`+ ggplot2::theme(axis.text.x=ggplot2::element_text(size=5.0))`

**Comment by ChrisMarsh82** [comment]
Closing issue as now fixed
