### ISSUE TITLE
Boxplot Count Variable dialog

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6647]
Hello, 

I have found a Dialog titled Boxplot Count Variable, it is present in Visual Studio and I found the term in the Crowdin content. However, I cannot find it in r-Instat. Could anyone tell me which menu it is in? or How I might find it? I have asked @rdstern and he says he has never heard of it. 

On that note, would it be useful to have a search function in R-Instat? For people who do not know which menu to find things under. Or is this a very complicated/unnecessary idea? 

Thanks, 

Rachel 
![Boxplot Count Variable](https://user-images.githubusercontent.com/85707390/127228175-87091c3d-d41b-4caf-9cd6-b18e7aeeef71.png)

**Comment by shadrackkibet** [comment]
@rachelkg this is one of the dialogs that was added at the start of the project. It is no longer needed and therefore it cannot be found in the menu. Actually, we have a plan to delete these kind of dialogs from the project as described in the issue https://github.com/africanmathsinitiative/R-Instat/issues/6481. 

You also mention that we should have a search function for dialogs. I think this is much more on the documentation. I, therefore, suggest that we have a section under help that lists the dialogs as per the menu (Perhaps we have it already but I don't think it's up to date).

**Comment by rachelkg** [comment]
I will not worry about the translation then. 

Thanks for the explanation @shadrackkibet
