### ISSUE TITLE
Changing text

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6660]
Hello, 

I am not sure who to address this question to. I am having some trouble making changes to the English text. In the One Way Frequency dialog I have been asked to omit One-Way from the name. I am also trying to change Ascending Frequencies and Descending Frequencies to just Ascending and Descending. I have made changes like these before without issue but in this instance it doesnt seem to be going through. I make the change in Visual Studio in the properties window, and they show up in visual studio correctly. However; when I run R-Instat the text changes to not show up (though other layout alterations I have made do).  

I have been asked to change the names of a few dialogs: Import and Tidy NetCDF file and Import and Tidy Shapefile, to Import NetCDF file and Import Shapefile. Here i am having the same problem and I have a further question. Once I have changed the name of the dialogs how to I change the associated menu items. 

Any insight much appreciate. 

Thank you, 

Rachel 
![Frequencies](https://user-images.githubusercontent.com/85707390/128263768-c6d404ee-a9c2-4a2a-b3b0-188e4fc577c8.png)
![Import net cdf](https://user-images.githubusercontent.com/85707390/128263802-92d2e1cf-9fff-46c0-9ab6-a6294d532869.png)

**Comment by shadrackkibet** [comment]
In addition to changing the `text` property. Could you also change the `name` property? For example `mnuClimaticFileImportandTidyNetCDF` to `mnuClimaticFileImportNetCDF`. For the controls try also changing the `name` property to something else and that should work.

**Comment by rachelkg** [comment]
Thanks I will try this
