### ISSUE TITLE
Correct the Regular Sequence dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6672]
@maxwellfundi if you are introducing the new interns then here is a simple bug to correct in the Prepare > Calculate > Regular Sequence dialogue.  Here is a screen shot:

![image](https://user-images.githubusercontent.com/11226469/129389865-7be4c8a4-cfbd-4daa-819b-74870717c594.png)

It looks very untidy now and the Position control is obviously in the wrong place.
a) I suggest the preview be moved up in the dialogue, so there is room for the Position button to go after the main control - which it is, in other dialogues.
b) While there it seems a shame not to line up the 4 main controls for From, To, etc.  When doing that lining, make sure the spacing works for the dates button as well as for numeric columns.  And that the spacing is ok if the language changes.

**Comment by derekagorhom** [comment]
Hello @maxwellfundi 
i will get working on it
