### ISSUE TITLE
Bad Parameter or Other API misuse bug

### ISSUE THREAD

**Issue by Wycklife** [africanmathsinitiative/R-Instat#6680]
I keep on getting this bug whenever I start R-Instat. This occurred after I updated and pulled the current changes from R-Instat into my branch. @africanmathsinitiative/developers Could someone help me fix it? See the screenshot below:

![API problem](https://user-images.githubusercontent.com/33898404/129721975-68c10a81-ad9c-40d0-99a8-2b507e48d5e2.PNG)

**Comment by shadrackkibet** [comment]
Fixed this by deleting the bin folder and then build afresh!
