### ISSUE TITLE
PCA Options subdialog, Save Tab Empty

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6686]
Hi All, 

I have noticed that the PCA Options subdialog, Save Tab Empty. Is it waiting to be filled or should it be removed. 

Thanks, 

Rachel 

![PCA Options](https://user-images.githubusercontent.com/85707390/130127324-dcfc0407-98c9-4080-bbd6-26add6b31739.png)

**Comment by shadrackkibet** [comment]
This is an incomplete dialog case and it has been partly because the dialog has not been used a lot! However, this is something that should be easy to complete and I also noted that there are bugs in this dialog that need to be fixed if not restructuring the dialog.

**Comment by N-thony** [comment]
> We basically need to use the save control to save the outputs.
> 
> @rdstern could you please confirm what we would like to save from this dialog. The graphics are the obvious ones we would like to save. Not sure if we want to save the other outputs, they look interesting and we might want to examine them further?

@rdstern what do you say?
