### ISSUE TITLE
Sub-dialogues not (always?) available for new bar chart dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6690]
I had attached the data file, but this seems to be a more general bug?  With the current master and the survey data in the simplest form:

![image](https://user-images.githubusercontent.com/11226469/130351819-018b54a9-ea8e-4c9f-b42b-5d7c6caf8237.png)

If I now press Plot Options I get:
![image](https://user-images.githubusercontent.com/11226469/130351896-a8b68420-5039-4511-a340-7ebfafedfefb.png)

Perhaps @shadrackkibet could check quickly on his current branch, or maybe this is a job for @N-thony ?

**Comment by N-thony** [comment]
> I had attached the data file, but this seems to be a more general bug? With the current master and the survey data in the simplest form:
> 
> ![image](https://user-images.githubusercontent.com/11226469/130351819-018b54a9-ea8e-4c9f-b42b-5d7c6caf8237.png)
> 
> If I now press Plot Options I get:
> ![image](https://user-images.githubusercontent.com/11226469/130351896-a8b68420-5039-4511-a340-7ebfafedfefb.png)
> 
> Perhaps @shadrackkibet could check quickly on his current branch, or maybe this is a job for @N-thony ?

I would like to try to fix it but I think @shadrackkibet is working on this dialogue.

**Comment by rdstern** [comment]
@N-thony if you are happy to look, then I don't think he is working on it just now, and I don't think a change on this aspect is likely to cause a serious conflict anyway.

**Comment by N-thony** [comment]
> > I had attached the data file, but this seems to be a more general bug? With the current master and the survey data in the simplest form:
> > ![image](https://user-images.githubusercontent.com/11226469/130351819-018b54a9-ea8e-4c9f-b42b-5d7c6caf8237.png)
> > If I now press Plot Options I get:
> > ![image](https://user-images.githubusercontent.com/11226469/130351896-a8b68420-5039-4511-a340-7ebfafedfefb.png)
> > Perhaps @shadrackkibet could check quickly on his current branch, or maybe this is a job for @N-thony ?
> 
> I would like to try to fix it but I think @shadrackkibet is working on this dialogue.

@rdstern I also noticed this bug concerning plot options sub dialogue that I think right to report it here too.
It seems to be general, after making any change in the sub dialogue this bug appears at least if you reset the dialog. 
![image](https://user-images.githubusercontent.com/68591383/130359852-0cb60c75-7e9e-46ac-97c0-fbb33c14c59e.png)

**Comment by shadrackkibet** [comment]
@Ivanluv this is the bug introduced by the new feature on annotating. Should be quick to fix.

**Comment by Ivanluv** [comment]
@shadrackkibet  am fixing that now

**Comment by N-thony** [comment]
> @shadrackkibet am fixing that now

I think have fixed that, check PR #6691

**Comment by Ivanluv** [comment]
@N-thony I can see your PR #6691  has fixed the annonations bug 

> > @shadrackkibet am fixing that now
> 
> I think have fixed that, check PR #6691. I think it is these lines that creating the bug. @Ivanluv what do you think since I'm not getting the need of that?
> ![image](https://user-images.githubusercontent.com/68591383/130411943-5d47a2f4-91e2-4fb0-95ad-2a1708d14eec.png)

However, the code you have commented is used in setting up the x and y controls which might introduce more errors

**Comment by N-thony** [comment]
> @N-thony I can see your PR #6691 has fixed the annonations bug
> 
> > > @shadrackkibet am fixing that now
> > 
> > 
> > I think have fixed that, check PR #6691. I think it is these lines that creating the bug. @Ivanluv what do you think since I'm not getting the need of that?
> > ![image](https://user-images.githubusercontent.com/68591383/130411943-5d47a2f4-91e2-4fb0-95ad-2a1708d14eec.png)
> 
> However, the code you have commented is used in setting up the x and y controls which might introduce more errors

Thanks, I have commented just to know the need of that. Now I got it.

**Comment by Ivanluv** [comment]
@N-thony I can have  a look at that

**Comment by ChrisMarsh82** [comment]
@shadrackkibet to check to see if this is fixed

**Comment by shadrackkibet** [comment]
@Ivanluv I think we fixed this somewhere. Could you please confirm then we can close? Will appreciate it if you could point to the issue that fixed it. Thanks

**Comment by Ivanluv** [comment]
@shadrack this was fixed by @N-thony thrugh PR #6691
