### ISSUE TITLE
Error when opening OneVarCompareModels.vb

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6697]
Hello @Patowhiz and @lloyddewit, 

I receive this error when I try to open sdgOneVarCompareModels.vb

Thanks, 

Rachel
![sdgOnevarCompareModels](https://user-images.githubusercontent.com/85707390/130489349-ff06d7d1-f3df-490b-9e95-f9d84ebe7f6e.png)

**Comment by Patowhiz** [comment]
@Gioche6 we can have a look at this together.

**Comment by lloyddewit** [comment]
This is fixed in PR #6736
