### ISSUE TITLE
File cannot be imported when running in French. 

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6698]
Hello @Patowhiz and @lloyddewit, 

Partick and I noticed that when running in French we could not import a file which imported correctly in English. Please see the error below. As I understood it, patrick thought it was to do with Automatic being translated to Automatique but he would be able to clarify this further. 

Thanks, 

Rachel 
![File cannot be imported](https://user-images.githubusercontent.com/85707390/130489756-072911ce-ccbe-4707-9b46-b6fdf5f9b3cb.png)

**Comment by lloyddewit** [comment]
Resolved in R-Instat 0.7.10
