### ISSUE TITLE
Save Urc issues in Load Dataset from Library, Row names and Numbers, Add Key and Recode Numeric Into Quantiles

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6700]
Hi @Patowhiz,

 In Open Dataset from Library the Save area is not displaying properly. You should be able to see a colon at the end of Nouveau nom de tableau de donnees, when I make the item bigger instead of moving the box over it just makes the white box really big but it still does not show the colon and it looks cut off.  

![Open data set from library](https://user-images.githubusercontent.com/85707390/130510148-74c70180-df7a-4183-ae49-9cba516a5c57.png)

In Row Names and Numbers the position button is only just visible poking out from behind the white box. This should be shorter so that the Position button is fully visible. I know that it is the position button poking out as if you click on it it opens the positioning subdialog. 

![Row Names or numbers no position button](https://user-images.githubusercontent.com/85707390/130510423-d78f75ea-3b10-4f7c-8bd3-e89e5ba8b5f5.png)

In the Add Key dialog the Text box is very far away from Key (the translation is Cle so this is not necessary for the French). However, if I resize the control it doesn't move the box closer to its title it just cuts the box off.  

![Add key](https://user-images.githubusercontent.com/85707390/130512780-5c8c5315-4e6c-43db-9ad2-8c74b8d6b5e3.png)

In the Recode Numeric into Quantile, this does not display correctly in English either 

![Recode numeric into Quantiles](https://user-images.githubusercontent.com/85707390/131556340-33a1d555-0d39-4c6e-b54f-0f8a2d51c364.png)

**Comment by rachelkg** [comment]
Hi @shadrackkibet and @Patowhiz, 

I am just bringing this back up as it has not been resolved. it is also a problem in the English display so i think is important to fix. 

Thanks, 

Rachel

**Comment by rachelkg** [comment]
HI @Patowhiz, 

Is this resolved? I don't see it being so in the new version. Please could you give me an update. 

Thanks, 

Rachel

**Comment by lloyddewit** [comment]
One of the changes requested above is for the Add key dialog. The change requires an update to the `ucrSave` control. If we make the change, then it will negatively affect all the other dialogs that use this control. We could enhance `ucrSave` so that it automatically repositions the input fields based on the length of the label but I don't think this is worth it. So I suggest we leave the Add Key dialog unchanged.
