### ISSUE TITLE
Change Corruption risk index menu item and dialog name

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6701]
Hello @Patowhiz, 

Please could you change a menu item and related dialog name for me. 

The menu item Corruption Risk Index should be changed to Corruption Risk Index (CRI)
![Menu Corruption Risk Index](https://user-images.githubusercontent.com/85707390/130511162-c504b496-4844-46b3-9c18-084a40661287.png)

The menu item Calculate Corruption Risk Index (CRI)... Should be Define Corruption Risk Index (CRI)
![Menu item define cri](https://user-images.githubusercontent.com/85707390/131553315-e359b667-d825-45ca-86e8-485ee202f45f.png)

And the dialog called Define CRI should be changed to Define Corruption Risk Index (CRI)
![Define CRI](https://user-images.githubusercontent.com/85707390/130511254-d875f666-94cb-424f-b28f-e16cc7594812.png)

Thank you. 

Rachel

**Comment by Patowhiz** [comment]
@Gioche6 please have a look at this. Thanks

**Comment by Gioche6** [comment]
The issue  have been fixed . However, the text is not changing in run time because of the translation issue. Once @lloyddewit has fixed the translation issue, it will automatically change.
