### ISSUE TITLE
Change Menu Item and Dialog name Define Corruption Outputs

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6702]
Hi @Patowhiz, 

Please could you change a menu item and dialog name. 

The Menu item needs to change from Define Corruption Risk Output Variables to "Define Corruption Indicators". 
![Menu Define Corruption Risk Output Variable](https://user-images.githubusercontent.com/85707390/130513959-8b95cd20-2e85-4bdf-9c68-ff510ed7a0ec.png)

And the dialog is currently named Define Corruption Risk Output but should be "Define Corruption Indicators" also. 
![Define Corruption Outputs](https://user-images.githubusercontent.com/85707390/130514059-1fb07576-9a00-4595-9826-5e3307bdab2e.png)

Thanks, 

Rachel

**Comment by Patowhiz** [comment]
@Gioche6 please have a look at this. Thanks.
