### ISSUE TITLE
Inconsistencies between menu item names and dialog names

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6710]
Here is a link to the google doc of the list of Inconsistencies I have found between the Menus and Dialog names. (https://docs.google.com/spreadsheets/d/1Mm7q_BvLJ3bENA1iWqzDdNr9KMeZv6a1/edit?usp=sharing&ouid=109004489783210984776&rtpof=true&sd=true)

While I think this is a good start, I am by no means claiming that it is comprehensive. It is just those that were highlighted by inconsistencies in the French.

There are also certainly instances where discrepancies between the Menu items and Dialog names seem logical and I have therefore not mentioned:
When the menu item needs to be shorter
When the menu steps add information (eg Menu: Describe - Two variable - Graph; opens dialog: Two Variable Graph)
Certain times when the menu item opens to a differently named dialog which is opened in a certain setting which enables the user to complete that task (eg menu Climatic - Dates - Generate Dates; opens dialog Regular Sequence on the Dates Tab).

**Comment by lloyddewit** [comment]
@rdstern Do you agree with @rachelkg 's proposals above. Should we go ahead and make the dialog names consistent with the menu names?
Note: I assigned myself and labelled as a translation issue because if the above is done, then I'll need to update the translation database.

**Comment by lilyclements** [comment]
I had a little look at the excel file just out of interest, and noticed we sometimes say "or" and sometimes use "/" for the dialog names. Is there a reason for the difference or (/) should we always use the same across all names?

**Comment by rachelkg** [comment]
Thank you for pointing this out @lilyclements I will take a look and enquire.

**Comment by rachelkg** [comment]
Hello All, 

Feedback on the "/ vs or" is that ideally menu items should use / while dialog names should use or. If you come across any of these please point them out or update them. 

I have gone over the list of inconsistencies with @rdstern and he has decided on the updates. These are recorded in the attached excel document. @Patowhiz or @Gioche6 would you be able to take a look at the list and update the related menu and dialog names please? I hope that the document is clear but if not please don't hesitate to contact me with questions. 

As I mentioned before I am not claiming that this is a comprehensive list. It is just those that were highlighted by inconsistencies in the French so everyone please feel free to add any instances that you come across. 

Thanks, 

Rachel 

[Inconsistencies between Menu and Dialog names.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/7156493/Inconsistencies.between.Menu.and.Dialog.names.xlsx)

**Comment by Gioche6** [comment]
@rachelkg , @rdstern, @Patowhiz  , I will go ahead and update the related menu and dialog names.

**Comment by Gioche6** [comment]
@rachelkg , I noted there is no clear information given about the Menu or Dialog update needed for  : Structured - Circular - Summaries, as indicated in  line 6 of the  [Inconsistencies between Menu and Dialog names.xlsx](uhttps://github.com/africanmathsinitiative/R-Instat/files/7156493/Inconsistencies.between.Menu.and.Dialog.names.xlsx), 

What changes do you suggest for this menu and dialog?
Thank you.

**Comment by Patowhiz** [comment]
@rachelkg this is a useful list, I've also been concerned for a while now on the inconsistencies when it comes to titles and labels. The other inconsistency that bothers me is the issue of plot vs graphs. We use "plot" in our menu items but use "Save Graph" in our dialogs. @rachelkg @rdstern shouldn't we use one term? or is there a logical reason for this? Same for the menu item "View last graph".

**Comment by Patowhiz** [comment]
> @rachelkg , I noted there is no clear information given about the Menu or Dialog update needed for : Structured - Circular - Summaries, as indicated in line 6 of the Inconsistencies between Menu and Dialog names.xlsx,
> 
> What changes do you suggest for this menu and dialog?
> Thank you.

@Gioche6 I think its just the same dialog used in `Prepare - Data Reshape - Column Summaries`, so I think the suggested changes are the same.

**Comment by rachelkg** [comment]
Hello all, 

Sorry for the late reply. @Patowhiz and @Gioche6 Line 6 should have no changes made to the Menu Item Names (Structured - Circular - Summaries ) but the dialog should be Column Summaries. 

As @Gioche6 points out this opens the same dialog as Prepare - Data Reshape - Column Summaries so I don't think you need to  change it twice. Leaving it blank was a confusing way for me to present it though, I should have made it clearer. My apologies. 

@Patowhiz Thanks for bringing up the graph vs plot question. I will looking to this and get back to you. 

Thanks very much for all your work on this.

**Comment by rachelkg** [comment]
@Patowhiz Thank you for bringing up the graph vs plot issue. I have discussed this with @rdstern and the we should follow is: 

- plot is used which it is a specific item such as a Boxplot, Density Plot or Inventory Plot
- graph is used to denote the general thing so one would say Combine Graphs or Display Graph Results. 

There may be instances where these are incorrectly applied so please feel free to point these out if you come across them. 

Thanks,
 
Rachel

**Comment by Patowhiz** [comment]
@rachelkg that sounds good. Thanks.
