### ISSUE TITLE
Capitalisation issue in Calculate Difference Between Options

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6713]
Hello @Patowhiz, 

The menu item Calculate DIfference Between Options should not have a capital I second letter. It should be Calculate Difference Between Options. Please could you change it. 

Thanks,

Rachel 
![Calculte Difference](https://user-images.githubusercontent.com/85707390/131749863-8fb35c9b-2bf3-469e-99ad-01318863c0f0.png)

**Comment by Patowhiz** [comment]
@Gioche6  can you please have a look at this? The menu can be found at the frmMain. Thanks.

**Comment by Gioche6** [comment]
The issue  have been fixed . However, the text is not changing in run time because of the translation issue. Once @lloyddewit has fixed the translation issue, it will automatically change.
