### ISSUE TITLE
Inserting French characters ("é", "è", "à", ....) in R-Instat

### ISSUE THREAD

**Issue by IssoufKon** [africanmathsinitiative/R-Instat#6717]
**Is your feature request related to a problem? Please describe.**
In our daily use of R-Instat, we have noticed that R-Instat does not recognize certain characteristics specific to the French language such as "é", "è", "à", "ê", "ô", "ï",.....   Since R-Instat will also be used to support projects in French-speaking Africa, it will be good to insert these corrections if possible. 

**Describe the solution you'd like**
We want R-Instat to recognize these French characters ("é", "è", "à", "ê", "ô", "ï") in its future version. 

**Describe alternatives you've considered**
Recognition of French characters. 

**Additional context**
![image](https://user-images.githubusercontent.com/88491307/132145598-2be145ad-ebbb-48bc-b732-727418d96bda.png)
![image](https://user-images.githubusercontent.com/88491307/132145605-a054d1af-f493-4a3f-9334-754d02cce261.png)

**Comment by rdstern** [comment]
@IssoufKon just to confirm that the first figure above is from the reogrid , i.e. from the spreadsheet view of the data.  I thought this was fixed  - or there is a pull request on this by @Patowhiz? I expect he will comment. 
I wonder if the second is from the output window? 
This is useful for you to raise, because I hope the forthcoming workshop (january 2022) will use the French version.

**Comment by Patowhiz** [comment]
@rdstern yes, PR #6555 fixes symbol's that seemed to be french accent characters even though they are just spaces. It Is yet to be merged. 
I'm not sure if this issue is related to it. 
@IssoufKon @rdstern can I get sample data data to confirm this?

**Comment by Patowhiz** [comment]
@rdstern @IssoufKon  would be useful to get the feedback on my above comment, since we have @dannyparsons around.

**Comment by Patowhiz** [comment]
@rdstern @lloyddewit this was fixed by PR #6555 and can now be closed. Thanks.
