### ISSUE TITLE
Errors NOT translated to the selected languages

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#6719]
@lloyddewit @rdstern probably this is intentional. 
I've consistently noticed that developer errors are not translated to the language selected. I'm assuming the same happens for other errors.
Perhaps this could be something to be discussed in future.

**Comment by lloyddewit** [comment]
@Patowhiz Thanks for reporting this issue. It's not intentional but is known. It's already mentioned in issue #3721:

![image](https://user-images.githubusercontent.com/57253949/132252224-5208a435-84a3-45d2-91e3-8e27c4e4ac87.png)
