### ISSUE TITLE
Add lollipop option to the bar chart dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6726]
We recently (I think) added geom_lollipop to the list.

This is a sort of bar chart.  It is (in geom terms) also a segment plus point.  But, as there is a geom lollipop I suggest the best place is in the bar chart dialogue.  It can be a single checkbox, on the left, perhaps after Polar.  If checked, then we use geom_lollipop rather than geom_bar, so the bar options button should change to Lollipop Options.
There should be 2 more controls on the same line as the Lollipop checkbox.  They are labelled Size, and Colour and use those controls from the Lollipop sub-dialogue.
This should be implemented for both the current options of the bar chart dialogue.

**Comment by lloyddewit** [comment]
> @N-thony I am re-opening this, because I can't get a good lollipop chart. This is work you did earlier. And I suggest these are needed, because they are used to analyse the R-Instat evaluation data. You may wish to work with one of the interns, because there is a general feature also to correct. Lollipop first. I'll sort out some data and add it here. There seem to be 2 problems - at least! a) The code gives not just a lollipop, but also a bar chart. The geom lollipop is instead of the bar chart. b) When you use lollipop the button changes to Lollipop Options. But it still gives bar chart. It should give Lollipop.
> 
> Also, cosmetic options on this dialogue. It currently looks a bit overwhelming. So: c) Make the first Reorder label into a checkbox. Default unchecked. The control is only visible when checked. d) I think the 2nd Reorder, and also Position are only when the By Factor (Optional): is not empty. So make them not visible until that is filled.
> 
> There is a related issue on the plotting geoms. But that will be separate and should involve an intern. A careful one!

I reopened this issue because of the above comments that @rdstern made in PR #6734.

**Comment by N-thony** [comment]
@MeSophie can you try this?
