### ISSUE TITLE
Making the Resulting Variable Numeric if the Content is the Row Number.

### ISSUE THREAD

**Issue by Gioche6** [africanmathsinitiative/R-Instat#6740]
A suggestion to make the resulting variable numeric if the contents is the row number in the:

 Prepare Data Frame > Row Numbers dialogue >Copy Row into Column Option.

**Comment by Vitalis95** [comment]
> A suggestion to make the resulting variable numeric if the contents is the row number in the:
> 
> Prepare Data Frame > Row Numbers dialogue >Copy Row into Column Option.

@rdstern, what is you take on this?
