### ISSUE TITLE
Add word clouds into R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6765]
Add the ggwordcloud package to R-Instat.  We need word clouds for the text processing work, see the [text mining book](https://www.tidytextmining.com/index.html) Chapter 2.
There are 2 parts to this work.
a) Add 2 geoms to the current list.  I suggest that @HawardKetoyoMsatsi could do this quickly?  He seems to have good experience in this task.
b) Add the options to the relevant diallogue.  They are essentially just frequency plots for words, so I suggest the obvious location is the Bar Chart dialogue.  This is now `Bar Chart/Treemap/Wordcloud`.  Although this is the obvious place, perhaps the bigger importance of Bar Charts could be recognised by the menu title `Bar Charts plus Treemap/Wordcloud`.   This is a simple addition and I suggest it could be done, with support, by @anastasia-mbithe as she has done the similar treemap option on the same dialogue.

**Comment by shadrackkibet** [comment]
@anastasia-mbithe anything remaining on word clouds? Should we close this issue?

**Comment by anastasia-mbithe** [comment]
@shadrackkibet Yeah we should close it.

**Comment by shadrackkibet** [comment]
Ann, thanks for checking. Could you reference the exact PR's that fixed this? Then I am happy to close it.

**Comment by anastasia-mbithe** [comment]
It was Pull Request #6805

**Comment by shadrackkibet** [comment]
What about adding geoms?

**Comment by anastasia-mbithe** [comment]
That part was done by @HawardKetoyoMsatsi

**Comment by shadrackkibet** [comment]
@HawardKetoyoMsatsi?

**Comment by anastasia-mbithe** [comment]
Adding geoms was PR #6785
