### ISSUE TITLE
Formatting table output for mmtable2

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#6770]
We have introduced `mmtable2` into R-Instat to create summary tables. The package works similar to `ggplot2` where layers are added through `+` to enhance or change the table.

There is a vignette [here](https://ianmoran11.github.io/mmtable2/articles/Some-minimal-examples.html) which has three sections:
* Adding headers  - we have done this already in the summary and frequency tables dialogs.
* Combining tables  - looks exciting and I'm sure will be introduced into R-Instat in the future!
* Formatting tables  - what we are interested in for this issue

Formatting tables allows changes to be made to the mmtable2 object using the `gt` package. There is some sample code for formatting tables at the bottom of this comment, but it looks like there are many different areas where we can format the tables.

## Formatting Tables

`cells_format` - this is to format the cells in the tables
`header_format` - this is to format the headers in the tables
`table_format` - this is to format the `mmtable2` object altogether

For these functions 

* The first parameter states what to format
E.g. for `header_format`, which header to format.
E.g.2. for `table_format`, `cells_body` from the `gt` package can be read in to specify which rows or columns or cells to format.

* The second parameter they can take is `style` which specifies how to format it.
E.g. `style = list(cell_text(...))` where `cell_text` is from the `gt` package.

From a quick look, `cell_borders` and `cell_fill` are other parameters that can be read into `style = list(...)`. 

So one task is to explore what, if any, other parameters can be read into the `style = list(...)` function from the `gt` package. A quick glance at the `tab_style` help page in the `gt` package suggests it is only these three, however perhaps there are more that I have missed.

Another task is to then look at what parameters these functions can take.
That is, what parameters `cell_text` can take in R, and similarly so for `cell_fill` and `cell_borders`.

## Titles, Captions, Etc.
The `table_source_note` function is another layer that can be added. This takes arguments from `gt::tab_source_note`, so the parameter this takes is `source_note` with the value as a string of what the caption should say.

From a quick look of the `gt` package, `tab_header` is another layer that can add a title and subtitle to the `mmtable2` object. 

A third task is what else from the `gt` package works as a new layer for an `mmtable2` package. It might be worth looking at the [vignette](https://cran.r-project.org/web/packages/gt/gt.pdf).
From a quick google, https://gt.rstudio.com/articles/intro-creating-gt-tables.html discusses other bits to add (such as footnotes) so it could be worth having a look there. 

## Other Options 
`header_merged_cols()` is another option in the `mmtable2` function to edit the headers
Are there any other options?

Finally, we then want to take all of these bits and plan a dialog or sub-dialog to format the `mmtable2` object in R-Instat.

## R Code
```
#remotes::install_github("ianmoran11/mmtable2")

library(gapminder)
library(dplyr)
library(tidyr)
library(stringr)
library(purrr)
library(gt)
library(mmtable2)

gapminder_mm %>% 
  filter(var != "Life expectancy") %>% 
  mmtable(cells = value) +
  header_top(year) +
  header_left(country) +
  header_top_left(var)  +
  header_left_top(continent)  +
  cells_format(cell_predicate = T, style = list(cell_text(align = "right"))) +
  header_format(header = year, style = list(cell_text(align = "right"))) +
  header_format("all_cols", style = list(cell_text(weight = "bolder"))) +
  header_format("all_rows", style = list(cell_text(weight = "bolder"))) +
  table_format(
    locations = cells_body(rows = c(1,3,5,7,9,11)),
    style = list(cell_borders(sides = "top",color = "grey"))) + 
  table_source_note(source_note = "Excerpt of the Gapminder data on life expectancy, GDP per capita, and population by country." )
```

(As a side note, I can see some functions called `cols_hide` and bits in the `gt` package, perhaps that would be an interesting avenue to explore later for editing mmtable2 objects. However, that is not to do with formatting).

**Comment by Ivanluv** [comment]
> So one task is to explore what, if any, other parameters can be read into the style = list(...) function from the gt package. A quick glance at the tab_style help page in the gt package suggests it is only these three, however perhaps there are more that I have missed.

> Another task is to then look at what parameters these functions can take.
> That is, what parameters cell_text can take in R, and similarly so for cell_fill and cell_borders.

The style function only take the three parameters i.e  `cell_fill`, `cell_text `and `cell_borders`.

The `cell_text ` function takes the parameters :
- `color ` -text colour
-`font` -font name
-`size `- size of the font ,options: `"xx-small "`,` "x-small"`, `"small"`, `"medium"` ,`"large"`,` "x-large"` `,"xx-large"`
-`align `-text alignment ,options: `center`,  `left`, `right`,  `justify`
-v-align - vertical alignment of the text in the cell ,options: `"middle"` ,`"top" `,`"bottom"`
-`style `- the text style ,options are : `"normal" `,`"italic "`,` "oblique"`
-`weight `- weight of the font  ,options are : "normal", `"bold"` ,`"lighter"` ,`"bolder"`
-`stretch` - allow of text_based keywords to describe the degree for condensation or expansion and the options are `"ultra-condensed" `, `"extra -condensed" `,` "condensed"`, `"semi -condensed" `, `"expanded" `,`"extra -expanded"` ,` "ultra-expanded" `
-`decorate` -allow for text decoration effect to be applied options are `"overline"`, `"line-through"`, `"underline"`
-`transform `- Allow for transformation of text opitions are : `uppercase` ,`"lowercase"`,` "capitalize"`
-`whitespace `- a whitespace represantation  ,options are :`"normal"`,` "nowrap"`,`"pre"`, `"pre-wrap"`, `"pre_line"`,`"break-space"`
-`indent `-indentation of texts which is numeric

for the `cell_fill `function we have the parameters:
-`colour `-which is the fill colour
-`alpha `-an optional alpha transparency value for the colour as single value in the range of 0-1

for the `cell_borders `function we have the parameters ;
-`side `-Borders side to be modified ,options include `"left",` `"right"`, `"top"`, `"bottom"`
-`colour`
-`style `-options are `"solid"`, `"dashed"` ,`"dotted"`
-`weight `- weight of the border line which is a numeric value

**Comment by Ivanluv** [comment]
We can add headers to the table  using the `tab_header `function which takes the parameters:

- `data ` -the `mmtable `object in our case

- `title ` -text to be used as the title

- `subtitle ` -text to be used as the subtitle

2.  `tab_footer` Adds fotnote. Parameters:
     `data`
     `label `- text to be used as the label
     `location `- for these there are a couple of options : 
              `cells_title` function that has the `group` parameter which takes either the `title `or `subtitle` 
              option
              `cells_body `function
              `cells_stubhead `function
3. `table_source_note`  adds the source note .Parameter:
   `source_note `- text to be used as the source note

**Comment by lilyclements** [comment]
Looks good. Can you put which packages these functions are in? I can't find the `tab_footer` function in either the `gt` or `mmtable2` package, and wanted to explore it a bit to see how it performs compared to the `tab_footnote` function we discussed earlier this week.

**Comment by lilyclements** [comment]
@Ivanluv this looks great. Perhaps for a suitable next step can you sketch out a sdg design for these, following a similar layout to the ggplot2 sdg design

For example there could be a labels tab something like this?
 I’m unsure from your comments how the footnote for the body and stubhead work, so this will have to be amended to account for that.
Additionally you might have a better solution to do this tab. Maybe you need a checkbox for the source note too. 

Have a look and sketch a design for a suitable sdg 

![F028A930-7DF1-4A7C-BD56-48990C74B975](https://user-images.githubusercontent.com/21180424/140306953-12186efe-ed78-48ea-b13d-428695c1e4ba.jpeg)

**Comment by lilyclements** [comment]
@Ivanluv thank you for the designs - it's looking really good so far.

Some small comments:

**Titles Tab:**
* Looks good, extend the group box to contain the footnote checkboxes as well as the title/subtitle options
* Is a checkbox needed for the title/subtitle options? The titles text are given in a new function so having a checkbox can mean that the title/subtitle function can be removed/added easily.
* How about footnotes for the cells with `cells_body()`? Perhaps the user could input the coordinates for it - I'm not sure, what do you think?

**Header Tab**
* We can specify beyond "All rows" and "All columns" using the `table_format` command. For example to make changes to each odd row you could put:
 ```
table_format(
    locations = cells_body(rows = c(1,3,5,7,9,11)),
    style = list(cell_borders(sides = "top",color = "grey")))
```
However, this is more something to note for the future. I think for now it is fine that we limit to just all cols/rows, especially since that is the option in the `mmtable2` function.
* Multiple arguments can be chosen for the `style` parameter (e..g `header_format("all_cols", style = list(cell_text(...), cell_fill(...)))` so these should be checkboxes not radio buttons. Perhaps each checkbox could have a group box leading from it with the parameter options inside?
* Default options and limitations should be noted: 
For cell_fill: `colour = "#D3D3D3"`, `alpha` is limited to 0-1
For cell_borders: `sides = "all"`, `colour = "#000000"`, `style = "solid"`, `weight = px(1)`.
* Is there a reason why you have put the control options in these orders? The order of the options should follow a similar order to the parameter orders in the function usually. For example, for the "Borders" option, the "Sides:" control should be first.

**Table Tab**
* Looks good, and I agree with the options chosen. Is there any particular reason why you chose these parameters from the function? I'm only wondering out of interest.
* How about a checkbox for "Add stubhead".
If checked then an input can be visible, alongside a checkbox. The function `gt::tab_stubhead` can run.
`gt::tab_stubhead` takes two parameters: `data` (which can be read in automatically), and `label`, which can take the text from the now-visible input.
A checkbox can also run if checked to add a footnote. This can work similar to the other footnote options given earlier.

**Comment by Ivanluv** [comment]
**Title Tab**
> Is a checkbox needed for the title/subtitle options? The titles text are given in a new function so having a checkbox can mean that the title/subtitle function can be removed/added easily.

 -A checkbox is for the title/subtitle is a good idea and can I have that added 
>How about footnotes for the cells with cells_body()? Perhaps the user could input the coordinates for it - I'm not sure, what do you think?

-We can have this added and maybe restrict the input as Numeric or Numeric List

**Header Tab**
>Multiple arguments can be chosen for the style parameter (e..g header_format("all_cols", style = list(cell_text(...), cell_fill(...))) so these should be checkboxes not radio buttons. Perhaps each checkbox could have a group box leading from it with the parameter options inside?

-Thank you for the suggestion of having the style controls as checkboxes. Also having the respective parameter leading in their group box is a good idea

**Table Tab**
>Looks good, and I agree with the options chosen. Is there any particular reason why you chose these parameters from the function? I'm only wondering out of interest.

These were the only parameters that could fit within the design space I had ,but I will add the other parameters in the sub dialogue

**Comment by Ivanluv** [comment]
@lilyclements maybe I can go ahead and have the sub dialogue design created then its easier to make changes when it already existing

**Comment by rdstern** [comment]
@N-thony the main item (I think) is the formatting of the table output in ways that parallel the graphics sub-dialogue.  This was started by Ivan and then @rachelkg prepared a document on how this could be completed.
@lilyclements discussed this topic with John on her recent visit and I think he has started the work and has an initial pull request.

I have another small separate improvement that could usefully be added and possibly merged separately.  This is to add the missing options button to this summary dialogue - as well as the 2 variable summarise dialogue.  It is the same button as in the One Variable summarise and also in the Prepare > Reshape > Column Summarise dialogue

**Comment by N-thony** [comment]
@anastasia-mbithe after our discussion, you are happy this over. We can work this together.

**Comment by rdstern** [comment]
@anastasia-mbithe  one item that seems not to be working on the main table dialogue is the order that the summaries are presented.  The up-down is there, but nothing seems to happen when the order is changed.
This links to a request for the sub-dialogue, which is to be able to rename those summaries.  This could use the same sort of grid as is provided in the Prepare > Data Frame > Rename > Multiple.  Maybe @N-thony can help on this, as he did the rename dialogue.  This will be an additional tab on the sub-dialogue.
