### ISSUE TITLE
Adding Chrolopleth Map to the Heat Map Dialog.

### ISSUE THREAD

**Issue by EstherNjeriLiberatta** [africanmathsinitiative/R-Instat#6782]
This is similar to a heat map with a few slight differences. It creates a map with regions that are coloured according to variable values and uses` geom_polygon` to draw the map.
Once the data is in the correct format, it can be plotted, mapping one of the columns with data values to fill.

Here is an example:

![choropleth map](https://user-images.githubusercontent.com/74548350/134149514-77a3f21b-7b76-44dc-9150-082693d69af3.jpg)

We can use `scale_fill_viridis()` as the heatmap to get a more diverse colour range. Which can be improved to have more colours.

Here is an example of the design of the dialog:

![Choropleth design](https://user-images.githubusercontent.com/74548350/134150952-1b55383f-3ea9-4cba-961a-b75d5a76a19b.jpg)

@rdstern and @shadrackkibet

**Comment by rdstern** [comment]
@EstherNjeriLiberatta that's great.  Would you like to add it.  As you say, it uses geom_polygon, rather than tile for the map.  You might also like to add the geom point to the dialogue (if it works) just as you do for the heat map?

**Comment by EstherNjeriLiberatta** [comment]
@rdstern Yes I would, I will try adding geom_point as well.
