### ISSUE TITLE
Swap data and metadata has problems when a script window is opened.

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6787]
With wide data it is often more useful to have the column metadata window open instead of the data.  Here is an example where I hav e chosen to swap the 2 windows:

![image](https://user-images.githubusercontent.com/11226469/134478193-8b0c1f6b-06c4-436d-82b2-d2ec338e12ac.png)

Now, every dialogue has a script button.  This opens a 3rd window above the 2 main windows - at least it does when there is the data window.  But after swapping the 2 windows I get this!

![image](https://user-images.githubusercontent.com/11226469/134478712-42c59075-564d-4210-8aa2-a48df9ea20a7.png)

That's not at all what I want.  I simply want to keep the 2 windows as before, i.e. column metadata on left and Output on the right.  And then the script window above.  That's what I get with the data on the left.  

I hope this is easy to fix?

**Comment by shadrackkibet** [comment]
I think we had identified this problem when @N-thony added the swap feature. I don't think it is something hard to fix.
