### ISSUE TITLE
Implementing a Prepare > Column: Calculations > Transform dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6791]
@rachelkg is now updating the help in R-Instat.  She typifies what we hope will be a common user of R-Instat.  She tells me that the Prepare > Calculator dialogue is pretty scary!

In the original Instat (long before R-Instat was born, we also had a calculator.  But we also had a Transform dialogue so users could do common data transformations without needing the general, but scary for some, calculator.

Here are some screen shots from that dialogue.  I suggest we produce an adapted version for R-Instat.
![image](https://user-images.githubusercontent.com/11226469/134626291-1b38592d-4ae7-4361-be36-0f9e4ebae5a5.png)

Here is a common transformation.  Notice the Inverse button so the inverse of log is exponential, etc.  Also a preview button to examine the formula!

In that dialogue, in the "old Instat", the "other Transformations button gives the following options:

![image](https://user-images.githubusercontent.com/11226469/134627644-b5ba76c7-72aa-4038-b49d-aca774d65966.png)

I suggest we need the equivalent in R-Instat.  I propose as follows:
![image](https://user-images.githubusercontent.com/11226469/134628083-2b762b62-5adc-4b16-ac59-2bb2080d1b20.png)

We use the existing Prepare > Column: Calculations > Ranks dialogue, which we rename to be Transform.  We might, at the same time, move it up one place, though I am not sure.  What is nice is that I propose a new name for the Menu item to be Column: Numeric!  That's neat, and important, because the 3 main types of data are Numeric, Factor, Character.  And that's what we now have in R-Instat!  

There will be quite a lot to do in this dialogue.  I suggest we merge in bits, as we go along.  I further suggest we have a new rule on the merging, i.e. we make everything visible as soon as it is ready, and have tooltips to mention when disabled items are not yet available.  That will make writing the help much easier.

The need for this dialogue came when writing the help for Sort.  We already have a general and powerful Sort (on right-click and in the Prepare > Data Frame menu).  But it sorts on multiple columns and carries the whole data frame.  How do we sort a single variable, leaving everything else undisturbed.  This should be in the calculator, but it is an omission there - that's another issue!  In the old Instat sort and Rank are both in this transform menu.

So, I propose the new Transform (from Rank) has the following buttons at the top.
Numeric, Non-negative, Sort, Rank.  
a) Rank is already there.
b) Add sort.  That's simple - just the Sort command, with a checkbox labelled Decreasing checked by default.  (This isn't the R default, but I suggest you often want to see the large observations.  There is a second checkbox, with label Missing Last, default is TRUE it is checked by default.  If unchecked, then make it FALSE.  So always include it in the command.
c) Add numeric button.  That's the default and is for any numeric variables.
This has a series of options.  They could be in a pull-down, but I suggest a set of radio buttons is useful here.  
O Round - this is the Round function.  It is followed by an up-down with label Digits and default 0 (that's the default in the function.) It has to be integer and can be negative.  
O Signif - is the similar signif function.  Max value of 22 and default 3.  0 is allowed, but I assume -ve values are meaningless, so are not allowed.  Please test this.
O Scale (This might be left for now!)  There are 4 Combo boxes into which you can type a number.  Labels are Subtract, Multiply, Divide, Add.  In the pull down there is 0 default, 32 and mean!  In Multiply, 1 is the default and there is also 5 in the pull down.  In Divide 1 is the default, and there is 9 and sd in the pull down.  In Add 0 is the default and 32 is in the pull-down.
( So easy to do (x-mean/)sd or (x-32)*5/9 as examples!  Is this possible/easy?
O Lag
O Lead
O Difference
Note for these 3, check with the function used in the calculator, to pad the data, so the resulting variable is the required length.  There is also an up-down in each case, with default 1.  I am not sure about whether 0 is sensible and assume negative values are not.  No particular upper limit.

That just leaves the Non-negative tab.  That could be more fun.  I like the options in the old Instat, with the Add constant

I am assigning this to @shadrackkibet temporarily, for discussion.  I suggest it is an excellent task for an intern once the details are agreed!

**Comment by N-thony** [comment]
@rdstern I'm taking this over. Hopefully @shadrackkibet will agree with me.

**Comment by shadrackkibet** [comment]
@N-thony the plan was to have one of the intern working on this. It is the sort of work that is nice for newbie to learn more. Happy for you to work on it if you don't have some other work.

**Comment by N-thony** [comment]
> @N-thony the plan was to have one of the intern working on this. It is the sort of work that is nice for newbie to learn more. Happy for you to work on it if you don't have some other work.

That is okay @shadrackkibet. I was thinking you will be working on it since it is assigned to you. We can keep the plan then for one of the intern.

**Comment by shadrackkibet** [comment]
Just to note that I did discuss with @anastasia-mbithe and he is working on this task.

**Comment by N-thony** [comment]
> Just to note that I did discuss with @anastasia-mbithe and she is working on this task.

Okay, I'm almost done with it but I will leave it then. Thanks.

**Comment by shadrackkibet** [comment]
![image](https://user-images.githubusercontent.com/26301973/135615835-23731e4d-9e62-4e45-8460-fdf2ad8629f7.png)
@N-thony here is your response to my comment yesterday which I can't see anymore (I had to retrieve this screenshot from my inbox). Perhaps you deleted it? It clearly shows that you agreed to the proposal for an Intern to proceed with the task.
It is very important to keep a record of all discussions here on git. Please don't delete them because it breaks the context of the discussion. This is not only for discussants but for others to follow the discussions as well and for future records.

Please also note that when you react using emojis people don't get a notification on your reactions. You better write it in the text so that we can see it. If something is still not clear then perhaps a quick call is better to clarify things.

@lloyddewit do you have any suggestions on the use of emojis? Perhaps we need to enable notifications on emojis?

**Comment by N-thony** [comment]
> ![image](https://user-images.githubusercontent.com/26301973/135615835-23731e4d-9e62-4e45-8460-fdf2ad8629f7.png) @N-thony here is your response to my comment yesterday which I can't see anymore (I had to retrieve this screenshot from my inbox). Perhaps you deleted it? It clearly shows that you agreed to the proposal for an Intern to proceed with the task. It is very important to keep a record of all discussions here on git. Please don't delete them because it breaks the context of the discussion. This is not only for discussants but for others to follow the discussions as well and for future records.
> 
> Please also note that when you react using emojis people don't get a notification on your reactions. You better write it in the text so that we can see it. If something is still not clear then perhaps a quick call is better to clarify things.
> 
> @lloyddewit do you have any suggestions on the use of emojis? Perhaps we need to enable notifications on emojis?

@shadrackkibet this is fine, it is my fault. I didn't let you know that this morning I had a discussion with @rdstern, and suggested me to do it quickly.

**Comment by lloyddewit** [comment]
> @lloyddewit do you have any suggestions on the use of emojis? Perhaps we need to enable notifications on emojis?

@shadrackkibet Yes, you're correct, I didn't realize that there are no notifications for emojis. The developers should be aware of this. I added a note to the Wiki [here](https://github.com/africanmathsinitiative/R-Instat/wiki/GitHub-notes).

P.S. I saw that GitHub has some open issues related to this - some developers want it, some don't.

![image](https://user-images.githubusercontent.com/57253949/136031139-afdeb935-cbbd-4f35-9ded-90cc8cf43fed.png)

**Comment by rdstern** [comment]
As mentioned above could you consider a Scale button at the top as well.
My thinking is that this could have 4 checkboxes in the following order:
Subtract
Multiply
Divide
Add

Each has a pull-down and I hope there can be tooltips for some of the values
Among the transformations here we are trying to be general, but also facilitate common scaling of the data.  So you can type into each pull-down, or choose from the set provided.

For Subtract the default is 0 and in the pull down is 32, 1970, mean, min
For Multiply the default is 1 and other values are 0.6214, 5, 9, 24, 25.4, 1440
For Divide, the default is 1 and other values are 5, 9, 24, 25.4, 365.25, 1440, sd, range
For Add the default is 0 and other values are 32, 273.15

So, to standardise can do (x - mean)/sd.  Fahrenheit to celsius is (x - 32)*5/9, and reverse is x*9/5+32
Ideally we have tooltips to explain some of the constants and the function is also shown - and perhaps can be edited???

**Comment by rdstern** [comment]
I thought that should change to be called Standardize?  What does the current Scale button do?  Doesn't it just standardize (i.e. subtract mean and divide by sd?)

**Comment by anastasia-mbithe** [comment]
@shadrackkibet This was fixed in PR #6840
