### ISSUE TITLE
Change Non-numeric cases menu item

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6818]
Hello, 

I have noticed that in the prepare menu there is an item called 'Non-numeric cases...', please could it be changed to 'Non-Numeric Values...'

I wasn't sure who to assign this too so please could you @shadrackkibet pass it on to the right person. 

Thanks, 

Rachel  
![2021-10-04_16-19-55](https://user-images.githubusercontent.com/85707390/135937322-eb03aa87-26c2-4511-8fe4-03726e7d405f.png)

**Comment by shadrackkibet** [comment]
@derekagorhom I thought this is a good task to start! you can liaise with @mmulahvictor who is currently working on the main form to make this change. What do you think?

**Comment by derekagorhom** [comment]
Hello @shadrackkibet please this check this file and let me know if it ok. i also sent the same file to @mmulahvictor for him to check also
![Screenshot (348)](https://user-images.githubusercontent.com/76208189/136003586-3cb9dd6e-08b3-4d14-a085-ceaa1179706e.png)

**Comment by shadrackkibet** [comment]
This is looking good @derekagorhom. Well done.

Please create a Pull request then we can review and merge.
