### ISSUE TITLE
Change unstack to use pivot_wider

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6871]
This is the partner to the stack (pivot longer) that has been changed recently.

It should be easy.  The Factor to unstack by is the names_from argument
The variable to unstack is values_from
The carry columns is id_cols.
However, the default is to carry all remaining variables, so if there are no carry variables, then I guess id_cols should be empty?

There are 2 small, but useful additions
A checkbox, default unchecked with label Add Prefix to Variable Names.  If checked it opens a field into which a text can be typed (adds the argument manes_prefix
A checkbox, default unchecked with label Fill Missing Values.  If checked it opens a field into which a number can be typed, default is 0. (adds the argument values_fill)

**Comment by N-thony** [comment]
> @rdstern I did discuss this with @Gioche6 earlier in the week and he was happy to work on it. Perhaps he has even started work.

@shadrackkibet I will leave it then to @Gioche6.
