### ISSUE TITLE
Correction and puzzle in Prepare > Column: Text > Find/Replace

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6872]
I have a simple correction to make.
The first option is called `Word Count`.  It should be just `Count`.

Now the puzzle.  I am also including @lloyddewit in case our translation system is connected to the puzzle.

When I use the pattern and type e it works.  But when I return to the dialogue, then `e` has become `and`

I used the example below:

```
fruit <- c("apple", "banana", "pear", "pineapple")
str_count(fruit, "a")
str_count(fruit, "p")
str_count(fruit, "e") 
```

It seems to be just e.  I tried lots of others.  Maybe returned to the dialogue 25 times.  Then it started to give me an error that it was out of memory.  I simply report this.  The e changing to and seems consistent, but the error was on your branch where the dialogue has been improved.

**Comment by lloyddewit** [comment]
@N-thony Please could you investigate this first (following the priorities agreed with your team leader). If you're able to recreate and narrow down to a translation action, then please let me know.
Thanks
