### ISSUE TITLE
Resolving issues after merging the paging of wide data sets

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6882]
I am making a new issue here.  @shadrackkibet comments about aspects that no longer work are important to fix before any new release.  This is in #6707.

After his comments I tried closing the data book.  I use it quite often and it used to return to our (now quite nice) front screen.  Now is appears not to work.  In fact it does work, in the sense that when you open a new data frame, then all the old ones disappear.  But when you delete it is as though nothing has happened.

Shadrack also mentions his new select features.  The action with filters is sort of ok, but not perfect.  I wonder what else there is to fix?

**Comment by N-thony** [comment]
I have tried to load the quelimane.RDS dataset and I'm getting the following error
![image](https://user-images.githubusercontent.com/68591383/139633146-423223f4-da3a-43dc-92c8-d80f6bc60acd.png)
![image](https://user-images.githubusercontent.com/68591383/139633224-f3e85dba-de58-4d27-a7a8-e413d9c2d8a4.png)

Here is the dataset: [quelimane6.zip](https://github.com/africanmathsinitiative/R-Instat/files/7451233/quelimane6.zip)

**Comment by rdstern** [comment]
There is a very minor point on deleting all **_visible_** columns.  It should direct you to `Prepare > Data Frame > Delete Columns/Rows`.  I had a data frame with 83 rows and wanted to delete 81-83.  (these were the only visible ones.   I certainly didn't want to delete the whole data frame!

**Comment by N-thony** [comment]
I have tried to open the script window but unfortunately, I'm getting the error in the screenshot below
![image](https://user-images.githubusercontent.com/68591383/140041028-8a178dea-ec1b-4dfc-8889-94fc0ed69abb.png)
![image](https://user-images.githubusercontent.com/68591383/140024623-7dda97c0-67e1-49e7-a616-df78b2f9a153.png)

**Comment by rdstern** [comment]
I am also concerned there could be serious speed issues with the new system.
I opened a large set of files - both fairly long and fairly wide.  Took 40 seconds on version 0.7.2 and 30 seconds longer on the merged version.  I can live with that.  But then:
a) Converting one variable to be a factor 15 seconds.  Almost instantaneous  - certainly less than 2 seconds earlier
b) Describe > One Variable > Summarise for that variable, 13.8 seconds on merged version and less than 1 second earlier.

It may all have nothing to do with the changes to the grid, but it is all now disturbingly slow when the data set is non-trivial.

**Comment by dannyparsons** [comment]
I'll leave this issue open for now, but I've separated the bugs into separate issues. Although these are likely all related, it's easier for testing and tracking to have them in separate issues. If you find any more bugs please create a new issue.

**Comment by dannyparsons** [comment]
Closing this as the main speed issue is resolved and other points are captured in other issues.
