### ISSUE TITLE
Change the associated Describe menu option from 'Bar Chart...' to 'Bar Charts plus Treemap/Wordcloud...'

### ISSUE THREAD

**Issue by lloyddewit** [africanmathsinitiative/R-Instat#6887]
When PR #6805 is merged, please change the associated Describe menu option from 'Bar Chart...' to 'Bar Charts plus Treemap/Wordcloud...'. This change was already implemented in PR #6781 but we closed this PR because of merge conflicts (see screenshot from PR below).

![image](https://user-images.githubusercontent.com/57253949/139396824-a83b115e-25ec-4f37-9259-87f5e6cbca12.png)

**Comment by rdstern** [comment]
@lloyddewit I am closing this issue - hope you are ok.  We are changing the name at the top of the dialogue, but I am happy with our recent strategy where we keep those names as simple as possible.  

I am suggesting other changes to the bar chart dialogue, and wondered about starting from here.  But simpler to make a new issue.

**Comment by lloyddewit** [comment]
@rdstern yes, happy to close this issue
