### ISSUE TITLE
Minor improvements needed in the Prepare > Column: Text > Transform dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6890]
I think these should all be quite simple to add. @shadrackkibet I wonder who could be asked to do them?

a) Change the first Button from `Convert Case` to just `Case`.  There are 2 more buttons to add.
b) In the Case option, add a 4th option to the pull-down, for str_sentence.  It completes the options in stringr under the Case heading in the documentation.
c) For Pad Label the 3 buttons with Side: and have the Width before these 3 buttons. Make the default for Width 20 instead of 1.
c) Add another 2 buttons, namely `Truncate` after Pad, for str_trunc and `Wrap` after Trim for str_wrap.
d) Implement these 2 options.  For wrap, just include Width (same way as for the Pad option, and with a default of 40.  So omit the indent or exdent arguments.  For Trunc have Width first, as for Pad now.  Then Side, as for Pad, but with the 3rd option `Middle`.  Omit the Ellipsis argument.

**Comment by N-thony** [comment]
> I think these should all be quite simple to add. @shadrackkibet I wonder who could be asked to do them?
> 
> a) Change the first Button from `Convert Case` to just `Case`. There are 2 more buttons to add. b) In the Case option, add a 4th option to the pull-down, for str_sentence. It completes the options in stringr under the Case heading in the documentation. c) For Pad Label the 3 buttons with Side: and have the Width before these 3 buttons. Make the default for Width 20 instead of 1. c) Add another 2 buttons, namely `Truncate` after Pad, for str_trunc and `Wrap` after Trim for str_wrap. d) Implement these 2 options. For wrap, just include Width (same way as for the Pad option, and with a default of 40. So omit the indent or exdent arguments. For Trunc have Width first, as for Pad now. Then Side, as for Pad, but with the 3rd option `Middle`. Omit the Ellipsis argument.

@shadrackkibet do you have a plan for this?

**Comment by rdstern** [comment]
@EstherNjeriLiberatta this has now been merged.  Apologies, but I have a trivial change to suggest.  One reason in the issue above to change `Convert Case `to just `Case` was so the buttons could each be made narrower.  

Now - with the 2 extra buttons and them all quite large, the dialogue is very wide, just to accommodate the buttons.  Could you make them all smaller, please, so the dialogue isn't quite so wide.

**Comment by EstherNjeriLiberatta** [comment]
@rdstern No problem.

**Comment by ChrisMarsh82** [comment]
@shadrackkibet to check and close issue if complete

**Comment by shadrackkibet** [comment]
Fixed in #6897
