### ISSUE TITLE
Bug when trying to load quelimane dataset

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#6891]
I have tried to load the quelimane.RDS dataset and I'm getting the following error
![image](https://user-images.githubusercontent.com/68591383/139633146-423223f4-da3a-43dc-92c8-d80f6bc60acd.png)
![image](https://user-images.githubusercontent.com/68591383/139633224-f3e85dba-de58-4d27-a7a8-e413d9c2d8a4.png)

Here is the dataset: [quelimane6.zip](https://github.com/africanmathsinitiative/R-Instat/files/7451233/quelimane6.zip)

**Comment by shadrackkibet** [comment]
@N-thony could you move this to #6882 because this is caused by the recent merge of the PR that added pagging.

**Comment by ChrisMarsh82** [comment]
@N-thony Can you send me this dataset?

**Comment by N-thony** [comment]
> @N-thony Can you send me this dataset?

Sure. Here is the dataset. [quelimane6.zip](https://github.com/africanmathsinitiative/R-Instat/files/7505953/quelimane6.zip)
