### ISSUE TITLE
Add regex sub-dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6893]
@N-thony I am not sure whether this will work out, but it is worth a try.
a) Change the expressions to expression in the dialogues, and the checkbox to a regex button.  If you press the button then you get a sub-dialogue - just like the Position button.
b) The heading is Construct regex expression.  Then there is a field into which you can type.  Underneath is the keyboard (together with the tooltips) from the calculator.  Initially just the 3 by 5 block at the bottom of the character keyboard:
![image](https://user-images.githubusercontent.com/11226469/139705664-f81a4a76-3125-4779-9ce8-f3ea8b055841.png)

Then just Return and Help as usual.  The help context number is 89.  
When you press Return it copies the field, from the sub-dialogue, into the pattern. control on the main dialogue.

It is worth a try!

**Comment by lloyddewit** [comment]
This issue is partially fixed in PR #7062:

![image](https://user-images.githubusercontent.com/57253949/148187099-2fe954b8-bed9-46d4-a632-7a165bcbb8a5.png)

**Comment by ChrisMarsh82** [comment]
Closing issue as code merged
