### ISSUE TITLE
Adding problem solving files to R-Instat Library

### ISSUE THREAD

**Issue by Kelvin-23** [africanmathsinitiative/R-Instat#6896]
After discussing with Roger, there are a few files that are supposed to be added to the next version of R-Instat and then can be read from the File > Open From Library > Instat > Browse.  A new directory called Problem Solving is to be made into the R-Instat data library. 

I will upload the files so that they can be added as soon as possible.
[AIMS Cameroon paper survey data.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/7466026/AIMS.Cameroon.paper.survey.data.xlsx)
[Islands Data Table1-2.csv](https://github.com/africanmathsinitiative/R-Instat/files/7466030/Islands.Data.Table1-2.csv)
[millet_data.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/7466031/millet_data.xlsx)
[odk_form_aims_cameroon_survey.xls](https://github.com/africanmathsinitiative/R-Instat/files/7466032/odk_form_aims_cameroon_survey.xls)
[rice_survey.csv](https://github.com/africanmathsinitiative/R-Instat/files/7466033/rice_survey.csv)
[SPS Course evaluation_18-19.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/7466034/SPS.Course.evaluation_18-19.xlsx)
[Statistical.Problem.Solving.Survey.csv](https://github.com/africanmathsinitiative/R-Instat/files/7466035/Statistical.Problem.Solving.Survey.csv)
[tomato.csv](https://github.com/africanmathsinitiative/R-Instat/files/7466036/tomato.csv)

**Comment by shadrackkibet** [comment]
@Kelvin-23 thanks for reporting this. I understand this kind of request should be added to https://github.com/africanmathsinitiative/R-Instat-Data repo.  We no longer manage the addition of data files here. Therefore I suggest you move this [here](https://github.com/africanmathsinitiative/R-Instat-Data/issues)

**Comment by Kelvin-23** [comment]
@shadrackkibet thank you for the information, the issue is now moved.
