### ISSUE TITLE
Small problem with the new Prepare > Factor > Recode dialogue 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6898]
The following shows the problem with the new merged code.
The example is from the library, Instat, Climatic Niger sadore.xlsx.  Read the second sheet, and omit 4 lines so it is named correctly.
Then make Mois into a factor and then use the dialogue.
The Mois variable has 14 levels - not 12 as it should.
Change Janvier to janvier and then also Fevrier to fevrier.  Then press Ok.
The command generated is as follows:
```
# Code generated by the dialog, Recode Factor
Mois <- data_book$get_columns_from_data(data_name="Sadore", col_names="Mois", use_current_filter=FALSE)
Mois_recoded <- forcats::fct_recode(.f=Mois, `mars`="mars", `avril`="avril", `mai`="mai", `juin`="juin", `juillet`="juillet", `aout`="aout", `septembre`="septembre", `octobre`="octobre", `novembre`="novembre", `decembre`="decembre", `fevrier`="Fevrier", `janvier`="janvier")
data_book$add_columns_to_data(data_name="Sadore", col_name="Mois_recoded", col_data=Mois_recoded, before=FALSE, adjacent_column="Mois")
```

You can see it correctly changes from Fevrier, but not from Janvier - see the code above.  So the resulting factor still has 13 levels - and not 12.

**Comment by N-thony** [comment]
> The following shows the problem with the new merged code. The example is from the library, Instat, Climatic Niger sadore.xlsx. Read the second sheet, and omit 4 lines so it is named correctly. Then make Mois into a factor and then use the dialogue. The Mois variable has 14 levels - not 12 as it should. Change Janvier to janvier and then also Fevrier to fevrier. Then press Ok. The command generated is as follows:
> 
> ```
> # Code generated by the dialog, Recode Factor
> Mois <- data_book$get_columns_from_data(data_name="Sadore", col_names="Mois", use_current_filter=FALSE)
> Mois_recoded <- forcats::fct_recode(.f=Mois, `mars`="mars", `avril`="avril", `mai`="mai", `juin`="juin", `juillet`="juillet", `aout`="aout", `septembre`="septembre", `octobre`="octobre", `novembre`="novembre", `decembre`="decembre", `fevrier`="Fevrier", `janvier`="janvier")
> data_book$add_columns_to_data(data_name="Sadore", col_name="Mois_recoded", col_data=Mois_recoded, before=FALSE, adjacent_column="Mois")
> ```
> 
> You can see it correctly changes from Fevrier, but not from Janvier - see the code above. So the resulting factor still has 13 levels - and not 12.

Wow, this is a bit challenging since the .AddParameter overwrites parameters with the same name. And using the code from https://rdrr.io/cran/forcats/man/fct_recode.html the new label in R-Instat is considered a new label. @dannyparsons what do you think about this? Maybe to find another way to handle this with forcats::fct_recode(...)?
