### ISSUE TITLE
Possible problem with the Levels/Labels dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6900]
This bug may be to do with the new paging, but I think it could have arisen because of changes to the right-click Levels/Labels dialogue.  At least that is worth a check.
What I was doing is not sensible, but it still should not give an error.  It will be good to see if you can repeat it?
a) Load the example data called words from the stringr package.
b) Change the variable to a factor and then use Levels/Labels.  It confirms that each word is different!
c)  Now load sentences from the stringr package
d) Make this into a factor and again use the Levels/Labels 
e) Delete the sentences data frame
f) Now use Levels/Labels again on the words dataset.  
It gives me an error on the master copy and throws me out of the program.  The error message implies it is still looking for the sentences data.
Are you able to repeat it?  
I tried also with one > Variable Summary instead of Levels/Labels and that didn't give an error.  I also tried the Levels/Labels in Version 0.7.2 and that worked fine.

If you can get the error - hope so.  That would be a good one to fix

**Comment by rdstern** [comment]
I have now found another bug in this dialogue and am delighted, because this is within a topic we should investigate more generally.
This one is also present in Version 0.7.2, so has not been introduced by recent changes.
Again, please see first if you can repeat it!
a) Open the diamonds dataset from the library.  It is the first example in the ggplot2 package.
b) It has 10 variables, of which 3 are (ordered) factors and the other 7 are numeric.
c) Make those 7 numeric variables into factors.  The one called price is what causes the problem, so you can start there if you prefer.
d) Now use right-click and the Levels/Labels dialogue.  Once in the dialogue you can look at any of the factor variables.  I often look at just one, and then right-click on others as I examine them. 
e) They have between 127 and 554 levels - except for price and that has 11602 different levels.
f) Close, or press OK on the Lavels/Labels dialogue after price.  
g) Then I am stuck.  The program freezes.

**Comment by N-thony** [comment]
> I have now found another bug in this dialogue and am delighted, because this is within a topic we should investigate more generally. This one is also present in Version 0.7.2, so has not been introduced by recent changes. Again, please see first if you can repeat it! a) Open the diamonds dataset from the library. It is the first example in the ggplot2 package. b) It has 10 variables, of which 3 are (ordered) factors and the other 7 are numeric. c) Make those 7 numeric variables into factors. The one called price is what causes the problem, so you can start there if you prefer. d) Now use right-click and the Levels/Labels dialogue. Once in the dialogue you can look at any of the factor variables. I often look at just one, and then right-click on others as I examine them. e) They have between 127 and 554 levels - except for price and that has 11602 different levels. f) Close, or press OK on the Lavels/Labels dialogue after price. g) Then I am stuck. The program freezes.

@rdstern I did the steps above, on my side when I right click on any other factor except price then Levels/Labels, all seems okay, and even select price from the selector and then click Close/Ok. But right-click from price and try going to Levels/Labels, it is the program freezes.

**Comment by N-thony** [comment]
> This bug may be to do with the new paging, but I think it could have arisen because of changes to the right-click Levels/Labels dialogue. At least that is worth a check. What I was doing is not sensible, but it still should not give an error. It will be good to see if you can repeat it? a) Load the example data called words from the stringr package. b) Change the variable to a factor and then use Levels/Labels. It confirms that each word is different! c) Now load sentences from the stringr package d) Make this into a factor and again use the Levels/Labels e) Delete the sentences data frame f) Now use Levels/Labels again on the words dataset. It gives me an error on the master copy and throws me out of the program. The error message implies it is still looking for the sentences data. Are you able to repeat it? I tried also with one > Variable Summary instead of Levels/Labels and that didn't give an error. I also tried the Levels/Labels in Version 0.7.2 and that worked fine.
> 
> If you can get the error - hope so. That would be a good one to fix

@rd you are right, I was able to repeat the 6 steps above, and I got the error that threw me out of the program. And when I have deleted the sentences datasets, it was still present in the Data View.

**Comment by N-thony** [comment]
> > This bug may be to do with the new paging, but I think it could have arisen because of changes to the right-click Levels/Labels dialogue. At least that is worth a check. What I was doing is not sensible, but it still should not give an error. It will be good to see if you can repeat it? a) Load the example data called words from the stringr package. b) Change the variable to a factor and then use Levels/Labels. It confirms that each word is different! c) Now load sentences from the stringr package d) Make this into a factor and again use the Levels/Labels e) Delete the sentences data frame f) Now use Levels/Labels again on the words dataset. It gives me an error on the master copy and throws me out of the program. The error message implies it is still looking for the sentences data. Are you able to repeat it? I tried also with one > Variable Summary instead of Levels/Labels and that didn't give an error. I also tried the Levels/Labels in Version 0.7.2 and that worked fine.
> > If you can get the error - hope so. That would be a good one to fix
> 
> @rdstern you are right, I was able to repeat the 6 steps above, and I got the error that threw me out of the program. I also confirm that deleting the data frame is failing sometimes.

@rdstern I think this will be fixed when the deleting of the dataset from Data View will become stable.
