### ISSUE TITLE
Change "Random Subset" to be consistent with Tidyverse

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#6903]
I have been looking at the dialogs in the "Data Reshape" sub-menu to check for consistencies with Tidyverse.

Under `Prepare > Data Reshape > Random Subset` the dialog currently uses the functions `data.frame`, `replicate`, and `sample` to randomly sample n rows from a column in the data frame. 
`replicate` and `sample` can be updated to use functions from the `Tidyverse` set of packages.

### **`replicate`**
`replicate` is a function from the base package. Instead, `rerun` in the `purrr` package can be used.

`replicate(n = ..., expr = ...)`

can just change to

`purrr::rerun(.n = ..., expr = ...)`

Changes made:
* the function `replicate` changes to `rerun` in the `purrr` package.
* the parameter `n` changes to `.n`

### **`sample`**
`sample` is a function from the base package. Instead, `sample_n` in the `dplyr` package can be used.
The parameters remain similar between the two options.

```
sample(x = <variable>, 
       size = <value>,
       replace = <logical>)
```

can just change to

```
dplyr::sample_n(tbl = data.frame(<variable>),
                size = <value>,
                replace = <logical>)
```

* the function `sample` changes to `sample_n` in the `dplyr` package.
* the parameter `x` changes to `tbl`
* `tbl` now equals a `data.frame` function with the variable as a parameter in the data.frame function
* `replace = FALSE` remains the default.

The `sample_frac` option could potentially be added.
This function takes the sample parameters as `sample_n`, but the `size` parameter can only take values between 0 and 1 inclusive. This is because the `size` option is now the fraction of rows to use.

@rdstern what do you think of these suggestions?

**Comment by lilyclements** [comment]
We could also change the dialog name to "Random Sample"?

**Comment by rdstern** [comment]
@EstherNjeriLiberatta could you take this on.  For now don't change the name, but change to functions to use tidyverse as suggested by @lilyclements above.

In our review the tidying in R-Instat was praised and I am keen to strengthen this component further.
