### ISSUE TITLE
Dialog names to change for consistency with Tidyverse

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#6904]
I have been looking at the dialogs in the "Data Reshape" sub-menu to check for consistencies with Tidyverse.
Some dialogs have names inconsistent with Tidyverse and the functions used.

1. `Prepare > Data Reshape > Merge` uses the set of `mutate-joins` functions in the `dplyr` package.
@rdstern would it make sense to change this dialog name to "Join" instead of "Merge"?

2. `Prepare > Data Reshape > Append` uses `bind_rows` from the set of `bind` functions in the `dplyr` package.
@rdstern would it make sense to change this dialog name to "Bind Rows" instead of "Append"?
(Additionally, the default naming structure for this dialog is currently calling a new data frame "Append_1". Elsewhere in the software we use lower case letters throughout so "append_1")

**Comment by dannyparsons** [comment]
I like to be consistent with other conventions when we can. But I think the priority is clear names for our users.

I think some of the tidyverse names are good function names but quite technical for a non-programmers. I do think we should mention this in the help file though. We could mention the R command and "also known as".

I quite like our "Append" concept as I think that's easy to visualise compared to Bind Rows. 

I'm not so sure on Join vs Merge. Join is also the database term which some people will know. Although I quite like Merge as it gives the impression of sideways i.e. row merging. Join could also sound like "append" so might be confusing.

Maybe we should also check the terms used in other software.

@volloholic might have a view on this from workshops in East/West Africa where these operations are used a lot. We should also think about the translation of these into other languages.

**Comment by dannyparsons** [comment]
For the naming, yes it should be lower case!

**Comment by rdstern** [comment]
In the latest version we have replaced Stack by Stack (Pivot_Longer) and Unstack has become Unstack (Pivot_Wider).  I still find Stack is quite a simple idea.
So could we consider having Append (Bind Rows) as the new item?
And Merge could become Merge (Join)?

I note in passing that TidyVerse has Bind Rows and also its partner, namely Bind Cols!  I know the reasons David and Danny don't want a dialogue for Bind Cols as a dialogue.  In the new Help I am proposing to tell those who read carefully about Bind Cols!  But this would have to proceed via the script window - changing Rows to Cols and I suggest this is a useful idea that if you would like to do this, then it can be available, but is not encouraged!

Also agree with @lilyclements that our new data frames should be in lower case.

**Comment by dannyparsons** [comment]
Happy with the additional names in brackets.

**Comment by EstherNjeriLiberatta** [comment]
Hello, @rdstern has anyone worked on this already?

**Comment by shadrackkibet** [comment]
@EstherNjeriLiberatta thanks for volunteering to work on this, please proceed.
