### ISSUE TITLE
Data View Window not clearing contents after trying to delete a dataset that is loaded.

### ISSUE THREAD

**Issue by EstherNjeriLiberatta** [africanmathsinitiative/R-Instat#6912]
I loaded a dataset from the library and realised it was the wrong one. I decided to delete it but it didn't clear. I also tried to close the data book but it didn't clear as well.

To reproduce the bug
1. Try and import any dataset either from the library, creating a new one, or from a file.
2. Once data is loaded, right-click on the tab at the bottom and click on `delete`.
3. See error.
4. You could also go to File and scroll down to `Close Data Book` and click on that.
5.  You will notice nothing happens on the Data View window.

What is expected is the data view window to have cleared its contents after clicking on delete or clear form.

Note: Once you click on delete/ close data book and try importing a new dataset, it automatically replaces the one you had even if it was not cleared from the data view window.

**Comment by N-thony** [comment]
> I loaded a dataset from the library and realised it was the wrong one. I decided to delete it but it didn't clear. I also tried to close the data book but it didn't clear as well.
> 
> To reproduce the bug
> 
> 1. Try and import any dataset either from the library, creating a new one, or from a file.
> 2. Once data is loaded, right-click on the tab at the bottom and click on `delete`.
> 3. See error.
> 4. You could also go to File and scroll down to `Close Data Book` and click on that.
> 5. You will notice nothing happens on the Data View window.
> 
> What is expected is the data view window to have cleared its contents after clicking on delete or clear form.
> 
> Note: Once you click on delete/ close data book and try importing a new dataset, it automatically replaces the one you had even if it was not cleared from the data view window.

I also loaded the survey dataset, and after deleting it, the Data View was still showing some information about the survey data set.
![image](https://user-images.githubusercontent.com/68591383/140991526-3978c8d4-aee4-42bc-b057-87292021449f.png)

**Comment by EstherNjeriLiberatta** [comment]
@N-thony It was clearing before. The bug must have appeared recently.

**Comment by N-thony** [comment]
> @N-thony It was clearing before. The bug must have appeared recently.

Yes, and in some case, it is not even clearing anything like when I have tried to delete the sentences dataset in the screenshot below, it was still there. I think the clearing is not stable, in some cases, it is clearing but not properly and in some others, it is just ignored, but you can see the output script of deleting in the Output Window.
![image](https://user-images.githubusercontent.com/68591383/140992725-658344e4-8fdf-4d68-a813-229a1e5aeef9.png)

**Comment by shadrackkibet** [comment]
This will be fixed in  #6908
