### ISSUE TITLE
Opening windows on start-up

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6914]
Why do I keep doing these things!
Anyway I tried opening the script window straight from from the start-up menu.  Then (next time round) the column metadata window.  here is the message I get.

![image](https://user-images.githubusercontent.com/11226469/141069703-90cb6add-2434-4a13-9c23-314f40d81ead.png)

It works ok in Version 0.7.2.
When I have opened a data frame first it is fine.

**Comment by N-thony** [comment]
@rdstern I think this is a duplication of #6895 and it may be fixed by #6909,

**Comment by rdstern** [comment]
@N-thony thanks.  Good - I'll close mine!

**Comment by dannyparsons** [comment]
I'll just reopen this so that we make sure to check this is solved by #6909

**Comment by ChrisMarsh82** [comment]
This is fixed in #6909
