### ISSUE TITLE
Adding an option to the Structure > Circular > Define dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6932]
Here is the current dialogue:
![image](https://user-images.githubusercontent.com/11226469/141265968-a4f32890-b00e-4f15-913e-b36e5fc04f91.png)

There is also template, which should be added:
See the guide for the circular package, page 25 and add a third group box called template.  The default should be None.  
At the same time change the default for Modulo to Asis.
Test this out by input of the wind data and it should plot nicely with the geographic coordinates.
These are the options from the circular guide:
`template = c("none", "geographics", "clock12", "clock24")`

And the Description is as follows: ```
template: how the data should be plotted. This set modulo, zero and rotation to some suitable values. For instance for ’geographics’: zero=pi/2 and rotation=’clock’.
It is also used to set default labels on the plots.
```

There is data called wind that is in the circular library - see the description and example in the package documentation for how that should be plotted.  Then confirm that it plots nicely - we have the dialogue - once the data are defined as geographic.

Here is also a copy of the data organised better than with the package.
[circular with summary.zip](https://github.com/africanmathsinitiative/R-Instat/files/7520228/circular.with.summary.zip)

Separately, once this works @Wycklife could add the data to the R-Instat library.  We store climatic data by country, so this could be in Climatic > Italy.

**Comment by derekagorhom** [comment]
Thank you
I will start working on it

**Comment by derekagorhom** [comment]
Hello @rdstern 
i was able to add the template to the dialogue box 
but i keep getting warnings of bad parameter
![Screenshot (361)](https://user-images.githubusercontent.com/76208189/143004736-5ec21eb5-92d9-41c6-8d93-d8a431be546a.png)

**Comment by rdstern** [comment]
That seems to be a common problem!  Perhaps @N-thony can help if there isn't someone in Maseno for this point?

**Comment by N-thony** [comment]
> That seems to be a common problem! Perhaps @N-thony can help if there isn't someone in Maseno for this point?

@rdstern sure. @derekagorhom do you have an open PR on this?

**Comment by derekagorhom** [comment]
@N-thony not yet
as i did not know if it create an error

**Comment by N-thony** [comment]
> @N-thony not yet as i did not know if it create an error

Okay, can you share your Skype ID so that we can chat?

**Comment by derekagorhom** [comment]
> > @N-thony not yet as i did not know if it create an error
> 
> Okay, can you share your Skype ID so that we can chat?

Derrick Agorhom

**Comment by ChrisMarsh82** [comment]
@shadrackkibet to check to see if issue is complete
