### ISSUE TITLE
Problem with the filter feature when it is applied in most of the dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#6941]
This seems to be a general issue in the system with the filter feature. In most of the dialogues I have been testing, I tried to filter the data before and when clicking on the Ok button I keep getting the following error in the screenshot below but when I ignore the filter all seems okay.

This is with the Climatic>Prepare> SPI/SPEI dialogue, filtering the year > 1940
![image](https://user-images.githubusercontent.com/68591383/141456216-1ba97355-5bf5-4181-8f06-63c9b1344e04.png)

**Comment by dannyparsons** [comment]
@N-thony This is the same issue we looked at before where the receiver/selector needs to be set to ignore the current filter when adding a new column. Do you remember the property to set for this? I can't remember which dialog we did this for last time.

**Comment by N-thony** [comment]
> @N-thony This is the same issue we looked at before where the receiver/selector needs to be set to ignore the current filter when adding a new column. Do you remember the property to set for this? I can't remember which dialog we did this for last time.

@dannyparsons yes, the property we used was ### .bUseFilterData = False with the Conversion dialog.

**Comment by dannyparsons** [comment]
Yes, that's it, we need the same here I think when getting the same.

**Comment by N-thony** [comment]
> Yes, that's it, we need the same here I think when getting the same.

Okay @dannyparsons, a part of the Spells dialogue, there are a couple of dialogues that the Filter doesn't work yet. 
May I list them and temporary fix the bug with this property if needed?

**Comment by dannyparsons** [comment]
Yes please do.
