### ISSUE TITLE
Replace `splines::ns` in Seasonal Comparisons dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#6942]
Seasonal Comparisons dialog currently uses `splines::ns` for the Natural Splines option but the package has been removed from CRAN.

There may be an option for this in the `splines2` package or elsewhere. We need to find some kind of replacement.

**Comment by N-thony** [comment]
> splines2

@dannyparsons I think equivalent here in splines2 is **"splines2::naturalSpline"**

**Comment by dannyparsons** [comment]
thanks that looks sensible. CnnCan you try it out in the dialog and see if it can be used in the same way?

**Comment by N-thony** [comment]
> thanks that looks sensible. CnnCan you try it out in the dialog and see if it can be used in the same way?

@dannyparsons happy to do that.
