### ISSUE TITLE
Enable the possiblity to run simultaneaoulsy multiple instances of R-Instat?

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#6950]
This option was recently disabled after introducing the open from file feature i.e. the possibility to load a dataset into R-Instat directly by right-clicking on the file (.RDS file). The reason that multiple instances were disabled is to avoid users being confused when trying to load the dataset by right-clicking on the dataset file into R-Instat when there are multiple instances.

This is easy to fix but I did a quick check on that and then I found that when trying to load a dataset into R-Instat when right-clicking on its file when there are multiple instances, it load the dataset into the last instance of R-Instat that was launched and this is a bit tricky if the user to load it into the first instance for example.

This corresponds to item f) in issue #6947

**Comment by rdstern** [comment]
Can we get @ChrisMarsh82 view on this issue.  I don't have a big problem with the right-click on a file opening into the last instance, when R-Instat is already running.  I would prefer though (like Excel) that it loads into a new instance of R-Instat.

**Comment by ChrisMarsh82** [comment]
I agree that opening a new instance when using the right click seems like the more standard way of doing things and therefore the least confusing to users.

**Comment by rdstern** [comment]
@N-thony so great if we could reinstate this feature.  Then I can have the test version running at the same time as a released version, etc.
