### ISSUE TITLE
Designer Problem with the Save label and Save control for the Missing Values Dialog

### ISSUE THREAD

**Issue by Gioche6** [africanmathsinitiative/R-Instat#6962]
The label for the save control appears slightly behind the the save control limiting it's full visibility. 
![image_2021_11_18T16_46_08_202Z](https://user-images.githubusercontent.com/73229979/142473560-0ecca4f8-3d42-4b6c-afbb-5bfa8236a2c4.png)

**Comment by N-thony** [comment]
@Gioche6 I couldn't have this design bug.
![image](https://user-images.githubusercontent.com/68591383/142482191-b7cbc491-bd40-4ab4-bdf8-2b46befc84e2.png)

**Comment by Gioche6** [comment]
The bug only appears for the updated branch only . If your Branch is updated recently, say today. You will find the bug.

**Comment by N-thony** [comment]
> @N-thony The bug only appears for the updated branch only . If your Branch is updated recently, say today. You will find the bug.

It is the case, I mean updated, but still not getting the bug.
