### ISSUE TITLE
Models>Fit Model>General

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#6972]
One problem that students experienced while using this dialog is the confusion between the "error" in the ANOVA and the syntax error that you get when you click the Try **button** from this dialog.

![image](https://user-images.githubusercontent.com/26301973/142758643-8faeab2b-261f-4519-9301-e79bbc89d817.png)
![image](https://user-images.githubusercontent.com/26301973/142758685-32c2bd02-4c6d-4443-abc2-ece724f8276a.png)

I suggest we change this to `Model runs without syntax error` and `Model produced a syntax error or no output to display.`. @rdstern what do you think?

**Comment by shadrackkibet** [comment]
@dannyparsons what do you think about this change?

**Comment by dannyparsons** [comment]
It's not just a syntax error that can cause an error. How about "Model runs ok". Can't think of anything that good.
And then the other message should also change then: "Problem detected running model or no output to display."

Also, I found this guide on error messages which I think is very good https://uxplanet.org/how-to-write-good-error-messages-858e4551cd4

**Comment by dannyparsons** [comment]
I've expanded on the error message discussion here #7032

**Comment by dannyparsons** [comment]
Is the "or no output to display" required for the model dialog? It's a bit confusing. I think this was carried over from the Calculator?
