### ISSUE TITLE
Packages for the next release

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#6976]
Looks like we missed out to add `ggwordcloud` (https://github.com/africanmathsinitiative/R-Instat/pull/6805 #6785) into the list of packages so that it can be added for the release. Please add for the next release.

**Comment by dannyparsons** [comment]
Thanks @shadrackkibet. Can you or someone please add this package by doing a PR as described here? https://github.com/africanmathsinitiative/R-Instat/wiki/Information-for-developers#how-to-add-a-new-r-package

We can now add packages in this way without needing to document in an issue, and the new packages will be added to the next release.
