### ISSUE TITLE
Error trying to reverse y-axis order

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6978]
I hope we can soon make progress on some of the outstanding issues on the plot sub-dialogue.  There are a lot of improvements needed, but now I have also a specific error that possibly hints to awkward code more generally.  The message is as follows and I explain below how I stumbled over it.
![image](https://user-images.githubusercontent.com/11226469/141963379-ff4fdba1-7166-4df7-9a15-4e7550dc584d.png)

I understand the message.  However I then unticked the option (in Y axis) that produced the error, but the error persists - so possibly the code remains?

Here is the graph I had:
![image](https://user-images.githubusercontent.com/11226469/141963982-12f36d38-ea39-4e29-87dc-cde0652a220a.png)

I decided to try reversing the Y axis, so the months would go down rather than up.  Slightly to my surprise I found reverse on the Y-axis tab - so tried it.

Here is the R-code generated:

```
# Code generated by the dialog, Histogram Plot
sadore <- data_book$get_data_frame(data_name="sadore")
Tmx <- data_book$get_columns_from_data(data_name="sadore", col_names="Tmx")
Mois <- data_book$get_columns_from_data(data_name="sadore", col_names="Mois")
last_graph <- ggplot2::ggplot(data=sadore, mapping=ggplot2::aes(x=Tmx, y=Mois)) + ggridges::geom_density_ridges(mapping=ggplot2::aes(x=Tmx, y=Mois)) + ggridges::geom_density_ridges(mapping=ggplot2::aes(x=Tmn)) + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text()) + ggplot2::xlab(label="Tmin & Tmax") + ggplot2::scale_y_continuous(labels=scales::percent_format(), trans="reverse")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="sadore")
data_book$get_graphs(data_name="sadore", graph_name="last_graph")

``` 

I begin to see the problem.  When I untick it does change, but it still gives me the scale_y_continuous addition to the command, i.e.

```
# Code generated by the dialog, Histogram Plot
sadore <- data_book$get_data_frame(data_name="sadore")
Tmx <- data_book$get_columns_from_data(data_name="sadore", col_names="Tmx")
Mois <- data_book$get_columns_from_data(data_name="sadore", col_names="Mois")
last_graph <- ggplot2::ggplot(data=sadore, mapping=ggplot2::aes(x=Tmx, y=Mois)) + ggridges::geom_density_ridges(mapping=ggplot2::aes(x=Tmx, y=Mois)) + ggridges::geom_density_ridges(mapping=ggplot2::aes(x=Tmn)) + theme_grey() + ggplot2::xlab(label="Tmin & Tmax") + ggplot2::scale_y_continuous(labels=scales::percent_format())
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="sadore")
data_book$get_graphs(data_name="sadore", graph_name="last_graph")

```
So, the error message persists.

**Comment by N-thony** [comment]
@Vitalis95 any progress?

**Comment by Vitalis95** [comment]
> @rdstern, do we need the y-axis values to be in percentage in histogram? This is the dialog; ![image](https://user-images.githubusercontent.com/89011415/176144369-9a32b37f-d2d2-48b4-b920-73abeb6e131d.png)
> 
> this is the output generated when ticked the option (in Y axis); ![image](https://user-images.githubusercontent.com/89011415/176144760-15434583-c039-4677-8ae4-4635b11fb558.png)
> 
> Also for the Frequency Polygon, do we need the y-axis values to be in percentage ? This is the dialog; ![image](https://user-images.githubusercontent.com/89011415/176146312-50429b6e-f364-45e6-99c1-cb244ea1a9ed.png)
> 
> This is the output generated; ![image](https://user-images.githubusercontent.com/89011415/176146502-25ab18f2-726f-4f9f-b116-bf0066c5534c.png)
> 
> The error above you have raised , occurs because the percentage parameter(`ggplot2::scale_y_continuous(labels=scales::percent_format()`) has been added to all the buttons(histogram, density,frequency polygon) yet under density we have a control `Percentages` as shown below which passes the same parameter That is why when you unticked the option (in Y axis) it still gave you the scale_y_continuous addition to the command ![image](https://user-images.githubusercontent.com/89011415/176147583-3cd9cb41-ad80-4b08-a6cb-83680ba0a160.png)


@rdstern , What is your take on this?

**Comment by N-thony** [comment]
> > @rdstern, do we need the y-axis values to be in percentage in histogram? This is the dialog; ![image](https://user-images.githubusercontent.com/89011415/176144369-9a32b37f-d2d2-48b4-b920-73abeb6e131d.png)
> > this is the output generated when ticked the option (in Y axis); ![image](https://user-images.githubusercontent.com/89011415/176144760-15434583-c039-4677-8ae4-4635b11fb558.png)
> > Also for the Frequency Polygon, do we need the y-axis values to be in percentage ? This is the dialog; ![image](https://user-images.githubusercontent.com/89011415/176146312-50429b6e-f364-45e6-99c1-cb244ea1a9ed.png)
> > This is the output generated; ![image](https://user-images.githubusercontent.com/89011415/176146502-25ab18f2-726f-4f9f-b116-bf0066c5534c.png)
> > The error above you have raised , occurs because the percentage parameter(`ggplot2::scale_y_continuous(labels=scales::percent_format()`) has been added to all the buttons(histogram, density,frequency polygon) yet under density we have a control `Percentages` as shown below which passes the same parameter That is why when you unticked the option (in Y axis) it still gave you the scale_y_continuous addition to the command ![image](https://user-images.githubusercontent.com/89011415/176147583-3cd9cb41-ad80-4b08-a6cb-83680ba0a160.png)
> 
> @rdstern , What is your take on this?

@rdstern what do you think?

**Comment by lloyddewit** [comment]
@Vitalis95 Thank you for fixing this issue in PR #7644.
Unfortunately, these changes broke the master build so I had to revert the PR.
Please could you reimplement in a new PR?
Thanks and sorry for the inconvenience.

**Comment by N-thony** [comment]
@Vitalis95 can you an update about this?
