### ISSUE TITLE
Add a Degrees button to the Climate > Prepare > Transform dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6990]
This can be an extra button at the end of the existing ones.  Make the buttons smaller, so the size of the dialogue can remain the same.  I would even prefer the dialogue to become narrower.  Perhaps the radio buttons for Multiple Spells and Water Balance could go on 2 lines.
Then keep the Station and Date fields, though these functions don't need those to be there, so the results, i.e. Ok enabled is not dependent on them.  Then there will be one or two temperature variables.  There is a checkbox first, default checked, with label "Use Max and Min" If checked, then there are 2 fields, labelled Tmax and Tmin respectively - so instead of the Year and Element in the other options.  If unchecked, then there is a single receiver, with label Tmean.  
With this option Ok is enabled once either Tmax and Tmin are filled, or Tmean is filled.
Then the rest go into the Options group-box.

There are 5 options and each has a radio button.  So you choose one of them.  They are labelled Diurnal Range, Tmean, HDD, GDD and Modified GDD.
There are tooltips as follows:
Diurnal Range is the difference between Tmax and Tmin, (Tmax - Tmin)
Tmean is the average daily temperature, (Tmax + Tmin)/2
HDD = Heating Degree Days. If the baseline = 15 degrees then HDD is (15 - tmean).  HDD = 0 if tmean is more than 15.
GDD = Growing (or Cooling) Degree Days.  If the baseline = 15 degrees, then GDD = (tmean - 15), or 0 if tmean is less than 15
Modified GDD is just GDD if tmean is less than the upper limit.  If baseline = 15 degrees and limit = 30 degrees, then Modified GDD = 30 - 15 if tmean is more than 30 degrees.   

For HDD and GDD there is an up-down into which you can type.  Label is `Baseline:` and default is 15.  It can go up or down in steps of 0.1 and there is no particular limit.  It could even go negative - though unlikely!

So Diurnal Range = tmax - tmin.  It is visible, but disabled if tmean is given
Tmean = Tmax - Tmin.  Also disabled if tmean is given.
The other 3 are available for both options
HDD =  (baseline - tmean) * (tmean < baseline)
GDD = (tmean - baseline) * (tmean > baseline)
MGDD = (min(limit,tmean) - baseline) * (tmean > baseline)

Please check what happens if people make the limit < baseline!  We may wish to exclude this, but I'd like to know what happens first!

**Comment by anastasia-mbithe** [comment]
When the limit< baseline, it returns a negative value when the logic is True , and returns a 0, when the logic is False.

**Comment by rdstern** [comment]
@anastasia-mbithe I can't see the pull request on this issue?
