### ISSUE TITLE
Bug when trying to run in the Window script a regular expression containing hashtag

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7014]
I'm actually looking for a good example where we can test the system with regular expression. I found this example below where they use the Twitter dataset, extracting the hashtags from the tweets using the regular expression: `hashtags = str_extract_all(data$tweets, "#\\S+")`

I tried the code provided in the example first with R Studio, and it works well then I have tried with R-Instat first with the Script Window and I'm getting the error in the screenshot below. After investigating the bug, I found that in the Script window, it is considering all lines containing hashtags as commented lines that why after running `hashtags = str_extract_all(data$tweets, "#\\S+")` it is giving the error when running the following line

Here is the link to the example https://methods.sagepub.com/base/download/DatasetHowToGuide/regular-expressions-in-isis-twitter-2016

![image](https://user-images.githubusercontent.com/68591383/144075459-fb9cac84-0b89-4b21-99c2-78bc2149135c.png)

**Comment by lloyddewit** [comment]
@N-thony 
I tried to test this but could not recreate the error.
I believe the error probably still exists but the URL above is broken, I do not have the required data file and my R skills are not good enough to create an alternative script.
If you know of any way I could recreate the problem, then please let me know. Thanks!

**Comment by lloyddewit** [comment]
@rdstern 
Note to above: I haven't tested it fully but I think RScript (and therefore ctrl-enter run) processes `=` correctly as an assignment operator.

**Comment by lloyddewit** [comment]
> I have pulled your branch but I still get the same error.

@N-thony even if you execute one statement at a time using ctrl-enter?
