### ISSUE TITLE
Problem with the Output Window when trying the Climatic > Check data > Inventory Plot

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7015]
I have tried to plot the inventory of the `Dodoma ` data using the `Inventory Plot` but I'm getting the following error in the screenshot below.
![image](https://user-images.githubusercontent.com/68591383/144192352-0f5b3990-08b0-4063-8a73-e01f2f79ad38.png)

**Comment by N-thony** [comment]
> I have tried to plot the inventory of the `Dodoma ` data using the `Inventory Plot` but I'm getting the following error in the screenshot below. ![image](https://user-images.githubusercontent.com/68591383/144192352-0f5b3990-08b0-4063-8a73-e01f2f79ad38.png)

Same with `Climatic > Check Data > QC Rainfall dialogue`

**Comment by rdstern** [comment]
Can you give more details, e.g. exactly the dialogue, and also the command that was generated.  Was it the dodoma.rds, or dodoma from the Excel file?

**Comment by N-thony** [comment]
> Can you give more details, e.g. exactly the dialogue, and also the command that was generated. Was it the dodoma.rds, or dodoma from the Excel file?

I have tried with `Dodoma.RDS` and using the `Inventory Plot dialogue` as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/68591383/144231061-d35ed3b5-3c87-4c54-8588-d0b695d486e1.png)

**Comment by rdstern** [comment]
@N-thony you are right, and we used this dialogue a lot in the recent Namibia course.  Now @dannyparsons it doesn't run any more for the same Namibia examples in the merged version.
