### ISSUE TITLE
Developer error under Climatic > Check data > Display daily dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7016]
**Describe the bug**
This message appears when opening the dialog after the first run.

**To Reproduce**

1. Go to Climatic > Check data > Display daily dialogue
2. Fill any variable in the Elements multiple receiver and then Click Ok
3. Then re-open again the dialogue, you will get the message in the screenshot below.

![image](https://user-images.githubusercontent.com/68591383/144199817-d7970817-7e77-456f-ac00-5343df5964eb.png)

**Comment by EstherNjeriLiberatta** [comment]
@N-thony I'll work on this.
