### ISSUE TITLE
The Try textbox on the Calculator should not editable & Message Textbox on Remove Unused Levels

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#7023]
@africanmathsinitiative/developers Someone please take this up.

**Comment by N-thony** [comment]
> @africanmathsinitiative/developers Someone please take this up.

@dannyparsons I think even the input control should also be not editable just the last on top ucrBase on the Remove Unused Levels dialogue?

**Comment by dannyparsons** [comment]
Yes, well spotted, also there.

**Comment by lloyddewit** [comment]
> > @africanmathsinitiative/developers Someone please take this up.
> 
> @dannyparsons I think even the input control should also be not editable just the last on top ucrBase on the Remove Unused Levels dialogue?

@mmulahvictor I just merged PR #7057. Did this PR also fix the comment from @N-thony above?
Thanks for clarifying
