### ISSUE TITLE
Correcting the dialogue title on Climatic > Prepare > Evapotranspiration dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7026]
The current title is `Evapotraspiration ` but it should normally be called `Evapotranspiration `.

In addition, the `Wind Speed` groupbox is correctly spelled but the Receiver is not `WindSpeed`, it should be changed to `Wind Speed` and the checkbox is called `Wind`. Perhaps the checkbox should be called  `Wind Speed` and get rid of the label of the Receiver once checkbox checked the receiver will appear?

![image](https://user-images.githubusercontent.com/68591383/144401277-042d26bc-e67d-4b93-b87b-ee4648438640.png)

**Comment by Gioche6** [comment]
@N-thony , I'll take this up.

**Comment by N-thony** [comment]
> @N-thony , I'll take this up.

@Gioche6 sounds good.
