### ISSUE TITLE
Quarter Abbr produced from Use Date dialog should be a factor not a character

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#7027]

**Comment by N-thony** [comment]
@dannyparsons  this could be done with `make_factor`. right?

**Comment by dannyparsons** [comment]
Yes.

**Comment by N-thony** [comment]
> Yes.

Okay, that should be quick to fix then.

**Comment by dannyparsons** [comment]
From looking further at the code, it needs some rewriting as it's very inefficient:

> Also, looking at the above I also see why the code runs very slowly for this. Because it is looping for each value, which is extremely inefficient.
> There are much simpler ways of changing the values.
> I think this needs to be redone in a simpler and more efficient way.
> @shadrackkibet Could you look at this too?
> 
> This should only need to be two lines, something like:
> 
> q <- lubridate::quarter(col_data, with_year = with_year, fiscal_start = s_start_month)
> q <- quarter_label(q, fiscal_start = s_start_month)
> The second function just does a replace of the numeric values with the labels.
