### ISSUE TITLE
Small bug with the Evapotranspiration dialogue after changing the Language

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7036]
**Describe the bug**
This bug happens after changing the Language and trying to reopen the Evapotranspiration dialog from the Last 10 Dialogs menu.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Climatic > Prepare > Evapotranspiration dialogue
2. Click on Close
3. Then go to Tools > Options > Languages  then change the Language for example to French if the Language was different from French when running R-Instat
4. Click Ok, Then on the Main Toolbar, under the Last 10 Dialogs menu, click on Evapotranspiration and nothing will happen

**Expected behaviour**
It should normally open the Evapotranspiration directly with the translated Language.

![image](https://user-images.githubusercontent.com/68591383/144701938-3777f970-48bf-45c9-b357-dcdbc29f06c1.png)

**Comment by N-thony** [comment]
> **Describe the bug** This bug happens after changing the Language and trying to reopen the Evapotranspiration dialog from the Last 10 Dialogs menu.
> 
> **To Reproduce** Steps to reproduce the behaviour:
> 
> 1. Go to Climatic > Prepare > Evapotranspiration dialogue
> 2. Click on Close
> 3. Then go to Tools > Options > Languages  then change the Language for example to French if the Language was different from French when running R-Instat
> 4. Click Ok, Then on the Main Toolbar, under the Last 10 Dialogs menu, click on Evapotranspiration and nothing will happen
> 
> **Expected behaviour** It should normally open the Evapotranspiration directly with the translated Language.
> 
> ![image](https://user-images.githubusercontent.com/68591383/144701938-3777f970-48bf-45c9-b357-dcdbc29f06c1.png)

@lloyddewit I have noticed that PR #7040 fixes also this issue.

**Comment by lloyddewit** [comment]
> @lloyddewit I have noticed that PR #7040 fixes also this issue.

@N-thony thanks, good spot! I linked this issue to PR #7040 .
