### ISSUE TITLE
No row right click menu on Linux version

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#7044]
The row right click menu doesn't seem to appear on the Linux version.

Not a huge problem if this isn't possible with that grid, but if it's easy to put in it should be there.

**Comment by ChrisMarsh82** [comment]
@dannyparsons This works, however, you need to have a row selected. The grid switches between being able to select rows and columns. This switch takes place when row/column headers are clicked. Therefore it doesn't select the row the first time it is clicked (if in column select mode) but will select it on the second click.
