### ISSUE TITLE
Adding Help to each right-click menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7067]
When teaching with R-Instat the tutorials and our courses introduce the right-click menus early on.  
These menus don't yet all have their own Help option.

This issue proposes a Help option be the bottom option in each right-click menu, for the data grid, and also have a separator line above it.  
Currently there is a Help option on right-click in the Script window, Log window.  
In the data window there is no help option on the right-click menus.  I suggest it be added and should go to the right click option - help context 146.  This is for all  3 right-click menus.   

In addition, the script window now has 3 buttons to help its use.  Could there be another Help button as well.  It will be the same location as the right-click on the window, i.,e go to context number 542.

In the old output window it is also there - at least in Version 7.3.1, but without the line.  In the new output window there is no right-click, but there are tabs at the top.  @ChrisMarsh82 Could help be added to these?  The help context is 540.
Also, @ChrisMarsh82 I think you mentioned you don't like the right-click menus?  So you may have problems with this issue.  Good to get your reaction, before @Wycklife possibly adds the help buttons to the data window right-click menus.

**Comment by Wycklife** [comment]
@rdstern @ChrisMarsh82 I would like to proceed with fixing this issue. Are you all okay with it?
