### ISSUE TITLE
Additional small changes in the Climatic > Prepare > Transform dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7069]
I hope this is small enough that it can be included in the changed being made currently to this dialogue by @anastasia-mbithe.  It would then be helpful to be able to capture the new dialogue for a small guide being written.
a) Change the buttons, so the Count  (currently the second button comes before Cumulative.  Thren still make the first button the default, so Count is now the default.
b) Change the number typed to be a pull-down with some options.  Still allow typing into the control.  The options can be 0, 0.85, 2.45, 4.85, 9.85, 24.85.  And make the default 0.85 instead of zero.

**Comment by anastasia-mbithe** [comment]
@rdstern  on point b) so the defaults for both the lower and upper pull-downs will be 0.85?(ucrInputSpellLower and ucrInputSpellUpper?

**Comment by rdstern** [comment]
@anastasia-mbithe that's well spotted.  The default for the condition is >= and so I hadn't noticed that!
Does the calculation work if the default for the second (for between and outer) is 0? So it is between 0.85 and 0?  If so, then the second one could be zero.  It can remain as just to be typed in, i.e. doesn't need to be a pull-down.

**Comment by anastasia-mbithe** [comment]
@rdstern it works either way (0.85,0) or (0,0.85). Am thinking since the first one is set as a minimum point and the second as the maximum point, then maybe having it as 0 and 0.85 respectively is just okay.

**Comment by rdstern** [comment]
@anastasia-mbithe If either is ok, then I prefer (0.85, 0) as the default setting is >= and hence only the first is shown.  So it appears as 0.85 >= and that is what I usually use to give the count of rain days.

**Comment by anastasia-mbithe** [comment]
@rdstern that's okay,  but we will have a problem when it comes to between and outer. i.e when we have X<=0 & X>=0.85 meaning, when we have between we will have an output which we would get when using outer and vice versa. Not unless we have the functions interchanged.

**Comment by anastasia-mbithe** [comment]
@shadrackkibet This was fixed in PR #7068
