### ISSUE TITLE
Small corrections to Prepare > Data Frame > Insert Columns/Rows

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7075]
a) The dialogue need not be so wide.
b) The pull-down currently gives alternative missing values only - and they seem to give an error.  Instead, keep NA as the default and have 0, "Kisumu", "New Zealand", TRUE, FALSE as other possibilities.

@shadrackkibet could you suggest someone?

**Comment by mmulahvictor** [comment]
@shadrackkibet I will do this issue.
