### ISSUE TITLE
Radio buttons not displaying on all dialogs

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#7079]
Some of the controls on dlgConversions do not seem to display correctly now. The controls at the top do not display and some other controls appear to be missing, although they are there in design mode.

This may have been as a result of conflicts from the change made to all dialog.

The controls need to be correctly repositioned and checked they display correctly at run time.

@N-thony Could you take this up as you worked on this dialog recently?

**Comment by N-thony** [comment]
> Some of the controls on dlgConversions do not seem to display correctly now. The controls at the top do not display and some other controls appear to be missing, although they are there in design mode.
> 
> This may have been as a result of conflicts from the change made to all dialog.
> 
> The controls need to be correctly repositioned and checked they display correctly at run time.
> 
> @N-thony Could you take this up as you worked on this dialog recently?

@dannyparsons sure. I went through some of the dialogs and I think this problem is more general in the system. I'm investigating on how to solve it.

**Comment by dannyparsons** [comment]
Ok, thanks, could you make a note of which dialogs have issues?

**Comment by dannyparsons** [comment]
This seems to be an issue with radio buttons and caused by making the panel auto size = true
@ChrisMarsh82 is looking into this now. It should hopefully be a fix that can be done on the panel control and then works everywhere.

**Comment by rdstern** [comment]
Just to confirm that the top buttons don't display anywhere.  I started with File > New Data Frame, but it seems to be general.

**Comment by dannyparsons** [comment]
This should be fixed now in the latest version by #7083
