### ISSUE TITLE
Improve the Describe > One Variable > Summarise dialogue and possibly 2-variable and 3-variable?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7081]
I use the data from the R-Instat review as an example:

I use the one variable summarise and wanted to get the sum (as in the review) and also the number of occasions with more than zero.
Here is the output:
```

# Code generated by the dialog, One Variable Summarise
data_book$summary(data_name="Scores", na.rm=TRUE, count_test="'>'", count_value=0, j=1, return_output=TRUE, summaries=c("count_calc", "summary_count_non_missing", "summary_count", "summary_sum"), columns_to_summarise=c("BlueSky","Deducer","JASP","jamovi","RAF","Rattle","Rcmdr","R_Instat","RKWard"))

                  BlueSky Deducer JASP jamovi RAF Rattle Rcmdr R_Instat RKWard
count                  43      43   43     43  43     43    43       43     43
count-non-missing      43      37   39     40  37     38    37       43     35
sum                   359     102  224    235  59    110   686      290    100
count-calc             NA      NA   NA     NA  NA     NA    NA       NA     NA

```
The main changes I would like are to the layout.  But here there is an oddity in the calculation.  What am I doing wrong?  The omit missing values option is ticked?  The count-calc is count values > 0, i.e. the number of values of 1 or more.  
This points to the urgency of doing something here.  But now I remember that we had the same issue with our Describe > Specific > Summary Tables dialogue.  And we solved the problem there!

Aha I have the solution in general.  One thing I would like is to be able to control the orientation, i.e. choose whether it is the variables or the summaries that go down.  I am sure there will be more.  But this is (almost) a special case of the Summary tables dialogue.  I say almost, because that dialogue is limited to numeric variables to summarise, while here we can summarise any type - though dates become numeric!  Anyway we can summarise factors and ordered factors include max and min.  (Do we want an option to do ordinary summarise on numeric levels of a factor - I guess not???)
We might give the results separately for the factors and the variates?

And I suggest these special cases will also be ok for the 2-variable and 3-variable summarise as well!  We will have a limited set of options - that's to keep it simple.  If you want full generality then you go to the main dialogues under the Specific menu.

I assume this is mainly work for @Ivanluv, with possible guidance from @lilyclements.  He will, I hope, be able to sub-contract some of the work to one of the interns?

**Comment by Ivanluv** [comment]
@lilyclements should I use the mmtable2 for these improvements?

**Comment by lilyclements** [comment]
@Ivanluv yes that sounds like a good suggestion
