### ISSUE TITLE
Save control not visible and dialogs with variable sizes have wrong size

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7091]
![image](https://user-images.githubusercontent.com/11226469/148839941-b19a5526-45b6-4d73-aced-9e56ed65415b.png)

The save control does not show the variable. See above.  This is also a problem with the Prepare Column: Calculator dialogue, so I guess it is general for the control.

The calculator is a dialogue that changes size, depending on the keyboard.  Now it just seems to get larger!
![image](https://user-images.githubusercontent.com/11226469/148840309-c6e55f22-e519-4f85-80dd-6c7745cf92b6.png)

This is fun and it goes on wider!

**Comment by Ivanluv** [comment]
I have also found the save control error on the summary Table dialogue and it occurs on all other dialogues using it
