### ISSUE TITLE
Small labeling issue with Climatic > Prepare > Climdex Indices dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7092]
There is a small issue with the label text not showing correctly as shown in the screenshot below
![image](https://user-images.githubusercontent.com/68591383/148897402-bde652ab-c313-4265-b590-6ab35dfcb0d7.png)

**Comment by derekagorhom** [comment]
Hello @N-thony 
can i work on this one

**Comment by derekagorhom** [comment]
![Screenshot (Climdex Dialogue)](https://user-images.githubusercontent.com/76208189/148910032-1e7c56a8-0755-4c70-9e95-6c93ca5f8537.png)
@N-thony please check this screenshot of the Climdex dialogue
