### ISSUE TITLE
Model > Probability Distributions > Show Model dialogue needs correction

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7099]
@dannyparsons it is another dialogue that is rather large!
So is Prepare > Column: Numeric > Random Samples.

I have been through the Prepare dialogues from Numeric downwards and haven't found any others.

**Comment by dannyparsons** [comment]
Yes, this is anywhere that has the Distribution and Parameters control. Also found on Compare Models and Add New Distributions sub dialog. Fixed in the linked PR.
