### ISSUE TITLE
The combobox containing the list of packages seems to be missing on Open Dataset From Library dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7101]
Here is the screenshot of the current version
![image](https://user-images.githubusercontent.com/68591383/149015078-df7def9d-f0b5-4eff-8eb7-eb1466b22298.png)

But we normally have

![image](https://user-images.githubusercontent.com/68591383/149015235-081ee1a8-c949-42cb-8259-771a96b22188.png)

**Comment by rdstern** [comment]
@dannyparsons I confirm this problem.  Is this another side-effectissue from the Linux work?
