### ISSUE TITLE
Text file preview doesn't display in Linux version

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#7113]
The text file preview in the Import from File dialog doesn't display in the Linux version.

I think this is because it is directly reading the file from VB and the path uses `\` instead of `/`, which won't work in Linux.

If this is changed to `/` in the code, it should work for Windows and Linux.

If someone can make this change and confirm it works in Windows still then I can test in Linux too.

![image](https://user-images.githubusercontent.com/11214914/149193035-44609005-7e45-4dcd-9a24-e55f9556e42b.png)

**Comment by rdstern** [comment]
@Gioche6 you bravely volunteered for the other small change for this dialogue.  I hope this will be equally simple at the same time.

**Comment by Gioche6** [comment]
@rdstern , I'll take this up.
