### ISSUE TITLE
Investigate and (hopefully) implement HTML in the new output window

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7121]
A number of our existing dialogues produce results in html.  This currently displays in a browser.  It would be great if this could be in the output window instead?

The dialogues include:
Prepare > Column: Factor > View Levels/Labels 
Describe > One Variable > Rating Table
Describe > One Variable > Frequencies (optional)
Describe > Specific > Frequency Tables
Describe > Specific > Summary Tables

**Comment by Patowhiz** [comment]
@rdstern I'm looking into this.
