### ISSUE TITLE
Small design bug in the Climatic Data Entry Sub Dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7134]
The Add flag fields is above the cancel button. It needs to be moved a bit on the right side.
![image](https://user-images.githubusercontent.com/68591383/149897582-a040d24d-fa85-4eb1-9d5c-13c5758200e8.png)

**Comment by derekagorhom** [comment]
@N-thony  you can close this issue now, the pull request has been merged with the master
