### ISSUE TITLE
Add option on File > New Data Frame to provide variable names

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7147]
This follows from discussion item #7130 and need not wait until the Prepare > Rename > Multiple Option has improved.  That has open issues 3396 and 6897 that will soon (I hope be implemented)

On the File > New data Frame the default option isnow be an empty data frame.  There should be an option, either through a checkbox, or a button, to give the variable names (for each variable), plus possibly the Variable labels and also (possibly) the type.  

It would have the following columns in the grid:
Name - initially data1, data2, -----
Type, initially just Numeric, Factor, Character - default Character
Levels - only possible for Factor Variables
Default - initially filled with NA  (See Prepare > Data Frame Add Variables/Rows for code for this)
Label - ideally, but might make it too wide?

**Comment by N-thony** [comment]
> This follows from discussion item #7130 and need not wait until the Prepare > Rename > Multiple Option has improved. That has open issues 3396 and 6897 that will soon (I hope be implemented)
> 
> On the File > New data Frame the default option isnow be an empty data frame. There should be an option, either through a checkbox, or a button, to give the variable names (for each variable), plus possibly the Variable labels and also (possibly) the type.
> 
> It would have the following columns in the grid: Name - initially data1, data2, ----- Type, initially just Numeric, Factor, Character - default Character Levels - only possible for Factor Variables Default - initially filled with NA (See Prepare > Data Frame Add Variables/Rows for code for this) Label - ideally, but might make it too wide?

@rdstern I will work on this.

**Comment by N-thony** [comment]
@rdstern I have implemented the first part which is the design on the option to provide variable names as show in screenshot below. At this stage, could @shadrackkibet help with R code required here? Thanks.
![image](https://user-images.githubusercontent.com/68591383/152317077-99b66802-cf95-4034-8e29-1d7cf057ec8e.png)

**Comment by Patowhiz** [comment]
One of the items that we discussed with @N-thony was about the **Default** column. @rdstern I was wondering as to why we need that column if the option suggests that it's about creating an **Empty** data frame? 

I'm of the opinion that a data frame with defaults is NOT an empty one(If I'm wrong then consider this comment null and void). 
If a user wants a data frame with defaults they could use the **Construct** option, where we could include expressions that produce defaults for different column types.
