### ISSUE TITLE
Implement delete in reogrid

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7149]
This relates to discussion item #7130.  See the figure and message there in item g.  It says delete will be implemented in future versions.  I propose now is the time for that future version.
It should delete items from a single cell and also allow a set of cells to be deleted.  This will usually be cells in a single variable.  Ideally any set of cells could be deleted, but I would be ok if (at least for now) we restricted the delete to be within a single variable, if deleting in multiple variables together adds a lot of complications.
Let's be clear that delete replaces the contents by missing (NA).  The dimensions of the data frame remain the same.  Deleting a column, or a row, where the dimensions change, is already implemented.

**Comment by shadrackkibet** [comment]
@derekagorhom this is the idea in R. Please try it out. If you find it difficult to make progress then let me know.

```
replace_values_with_NA <-  function(data, row_index, column_index){
  #check that row & column indexes are within the dataframe else stop!
  data[row_index,column_index] <- NA
  return(data)
}

```

**Comment by derekagorhom** [comment]
@ChrisMarsh82 this issue should be added to team two To Do list
