### ISSUE TITLE
Check sub-directories when using File > Import with multiple files

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7154]
Only add this feature if it is a small job! (@dannyparsons says this is easy to do. )

A powerful feature of this dialogue is the ability to import multiple files of the same type into successive data frames.
The way this is used is fine and is as follows:
a) Go to a directory that contains these multiple files, e.g. 8 SPSS files (each xxx.sav). Click on any one of them.
![image](https://user-images.githubusercontent.com/11226469/150727244-dcaa4eb1-cfa6-42d6-bf50-cbcbc9ec5884.png)

b) Use the "All files of this type" checkbox, to go up a directory.  It then allows the importing of all these files.  (We could add checkboxes later to be able to select the files we want - default would be all?
![image](https://user-images.githubusercontent.com/11226469/150727632-dd49081b-4ae7-44f5-b1a1-6aae08ffc8f7.png)

c) However I now also have an example where this is not quite enough.  These are DHS data, also SPSS files,  that can be unzipped.  This gives 8 directories, each with 3 files, one of which is the SAV file.  So going up to the directory is not enough.  I would like to go up one more level:

![image](https://user-images.githubusercontent.com/11226469/150728233-0d46979d-dab6-4de4-b608-4de850d9a6f2.png)

What I would like is now another checkbox after the "All files of this type" .  It is only visible when All files is checked. It is disabled by default.  It is followed by the up-arrow symbol you see on the browse dialogue.  (So the whole control is small and unobtrusive.  If checked it moves up another directory - to DHS in this case.

The detection of the multiple files than has also to register those it finds from sub-directories too.

**Comment by dannyparsons** [comment]
Yes, this just needs the `recursive = TRUE` option in `list.files` in R.

If the "Files found" number is done in VB, I guess there is a way to do this too. Otherwise, this could be done via R (if it isn't already).

**Comment by N-thony** [comment]
> Yes, this just needs the `recursive = TRUE` option in `list.files` in R.
> 
> If the "Files found" number is done in VB, I guess there is a way to do this too. Otherwise, this could be done via R (if it isn't already).

Looking into this.
