### ISSUE TITLE
New R package rcorpora in the next release

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7160]
The information in the wiki mentions either needed in dialogues or for data.  This is a package for datasets.  We discuss it quite a lot in the new help.
@Wycklife grateful if you could do the pull request as described in the wiki [here](https://github.com/africanmathsinitiative/R-Instat/wiki/Information-for-developers)

**Comment by dannyparsons** [comment]
`rcorpora` doesn't store datasets in the standard way an R package does and therefore these would not be currently accessible through the Library datasets dialog.

The way I could think to include this would be in the New Data Frame dialog, sort of like we do for `wakefield`. However, I'm not sure it's that important to do this for this package.

I've removed the milestone but we may just want to close this?

**Comment by rdstern** [comment]
Yes, but the datasets are so attractive it would be a shame not to have them.  I have put information in the help file and there could usefully be an example in the File > New Data Frame dialogue.

**Comment by rdstern** [comment]
![image](https://user-images.githubusercontent.com/11226469/151209557-745ae05a-0f50-4b94-a370-4e8ab60829c3.png)

**Comment by dannyparsons** [comment]
That's not really a tidy data frame! You can force it as a funny data frame with `data.frame` but it should be a one column data frame with the names and the description is in the metadata or removed. We could make them into nice data frames with a dialog, but that's probably more than we want to do. 
I'm not sure we should be showing these in the help in this format. They are interesting lists/one column data frames. Is that sensible for the help?

**Comment by rdstern** [comment]
Here is my favourite - which is much better than I have found elsewhere:
![image](https://user-images.githubusercontent.com/11226469/151213185-0a0b19b9-6b44-44c0-970f-b285b6b9ea17.png)

And I am quite happy that there is still some tidying to do - it is a good example to show how to tidy multiple names by getting rid of the prefix!

And there are more really nice examples.

**Comment by dannyparsons** [comment]
A developer can add it by following the steps here https://github.com/africanmathsinitiative/R-Instat/wiki/Information-for-developers#adding-a-new-r-package-to-r-instat

**Comment by rdstern** [comment]
@dannyparsons that sounds good.  At the top of this - now long - sequence I asked whether @Wycklife could do that.  This all seems a bit like "There's a hole in my bucket" song.  
So, @Wycklife could you please follow the instructions for the `rcorpora` package to be added.  At the same time - or perhaps a different pull request could you also arrange for the `mlbench` package to be added.  That's another package I thought we had, but got missed out, because I don't ask properly!  It is also data sets and for machine learning.  Thanks

**Comment by dannyparsons** [comment]
Sounds good. And just to mention that in general if a new package is added for a particular dialog then that can (and should) be done in the same PR as the dialog is in. That should help make sure we don't miss packages out as they get added at the same time as software changes.

For packages for datasets they can be added in their own PRs.

**Comment by Wycklife** [comment]
@rdstern I already took this up. I will have a pull request created in the course of the week.
