### ISSUE TITLE
Hide Drop empty Rows and All files of this type checkboxes

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#7173]
- When there is no file selected i.e the path is empty these checkboxes should not be visible?

- I also wonder why the preview message - "Preview not implemented for this type of file" is displayed here. Please hide the message or we change it to something else like "No file selected"

Note: Be aware of empty space in between controls.
 
- Why is Ok enabled? When I click Ok error!
![image](https://user-images.githubusercontent.com/26301973/151306836-8e02d81a-561c-45c1-9728-fc088f608c7a.png)
 

@rdstern what do you think?

- To replicate select a file and click reset.

![image](https://user-images.githubusercontent.com/26301973/151305149-647fb0ab-93fe-4a78-a71f-403a1aac9946.png)

**Comment by N-thony** [comment]
@shadrackkibet could @mmulahvictor try this out? I can support him if needed once @rdstern agreed?
@mmulahvictor what do you think?

**Comment by mmulahvictor** [comment]
> @shadrackkibet could @mmulahvictor try this out? I can support him if needed once @rdstern agreed? @mmulahvictor what do you think?

@N-thony I can try this out.
