### ISSUE TITLE
Duplicate Column Factor, Ordered Factor and Numeric options mixed up

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7198]
Hello @Patowhiz, 

I have notices that the Factor Options and Numeric Options are mixed up on the Duplicate column dialog. As in, when the Factor or Ordered radio button is selected the Numeric options show up but when the Numeric radio button is checked the Factor options show up.  Would you be able to resolve this or assign someone who can please? 

Thanks, 

Rachel 

![2022-02-03_15-06-20](https://user-images.githubusercontent.com/85707390/152444252-c0b52a7b-ad76-49d6-9858-708eab78ceba.png)
![2022-02-03_15-06-32](https://user-images.githubusercontent.com/85707390/152444256-45256568-f4d0-4146-9431-451382a43c47.png)

**Comment by Patowhiz** [comment]
@rachelkg I'm looking into this.
