### ISSUE TITLE
Improve the Position control to allow for selects

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7202]
You notice I am using the noun here.  "a select" is to columns what "a filter" is to rows.  And a feature of R-Instat is that they are objects in the data book.
When a select is active you only see those variables in the grid and in the data selector.  Many dialogues have a Position control.  That dictates the position of further column(s).
Two options in the Position control are `Start` and `End`.  I propose that, when a select is in operation, they become the Start and End of the selection?  I assume that will need a change to the code.
More important is their role in the select?  I suggest the default is for them to be added to the current select?  Otherwise the results of a calculation won't be visible in the selected data frame, or in the data selector.  And it would then be a pain to do a further calculation on that variable.    
Whether we need an option in the Position control to not add to the selection I am not sure.  But my claim is that selects need to be dynamic.  
I am assigning @shadrackkibet because he needs to assess exactly what should be done.  Then I assume he will allocate the work - probably to Patrick, as he wrote the Position control.
(I also feel we are sort of on the right track with the current set of user controls.  If we hadn't a position button/control then we would have to produce it now, - with the changed role of start and end.)
And this sort of thing is also showing that select is one of our ways of "taming" the wide data sets.  I know there is a lot needed to improve the data selector as well, but that doesn't diminish the importance of the select feature.

**Comment by shadrackkibet** [comment]
@rdstern I suggest we implement this in a similar way we insert rows after/before when a filter is in operation. Your suggestion is doable but brings another complexity when you remove a selection. What happens with those columns inserted into a selection? Do we merge the selection with the whole data frame?

Do we want to encourage users to create a copy of the selection or do we want users to mess around with the original copy? Sometimes things can go wrong! I claim the option to create a copy of your selection becomes really useful which is generally good practice when you are manipulating your dataset.

**Comment by rdstern** [comment]
In your comment above, line 1, I think you mean select, when you say filter.
If I have understood your hesitation correctly I suggest it can be simpler than you are making it.  Of course we can choose to put the select variables into a new data frame.  Then there isn't a problem, because there isn't a select there.
When the select is applied I suggest simply that the selected variables always (or usually) include any new variables that we make while the select is operational.  So with our survey if we select just yield and calculate yield1 <- 2*yield, then the current selection now has yield and yield1.  In the Position options everything refers to the select.  So start and end automatically become the start and end of the select.

If we were to want a select that is just that original set of variables then make a new select that is the same as the one that is active, before adding variables to the existing one.

**Comment by shadrackkibet** [comment]
This is what I mean in line 1.

- Load Survey
- Filter to only remain with Village = "SABEY"
- Insert two empty rows at the end
- These two rows are not visible because the filter is in operation.
- Now remove the filter-  You see the rows that have been inserted!

If we implement select in a similar way then it is consistent with filters.

Your suggestion above implies select object is now updated i.e the definition used to obtain selection may or may not hold anymore because a selection object has now been updated (we don't do this for filter objects!).

**Comment by rdstern** [comment]
ok, thanks.
I still feel that a major use of select will be to analyse parts of a wide datasets.  Currently, when we have more than 30 variables and produce a new one at the end, I find it annoying that I don't see it.  Usually I would like to.  And the many commands that add more columns shows this is a pretty common task.  (Unlike adding rows, which I rarely do.)  I have no problem with adding an option to include these rows in the filter, but I can't remember having needed that.  With columns adding residuals and fitted values to a data frame is another example where I would be happy that they are at the end of the selection (say) and visible.

And the filter does update in the other direction, (which I have used) namely when you filter for all values of temperature > 100 and then correct the temperatures, then they disappear automatically from the filter.

**Comment by rdstern** [comment]
@shadrackkibet I have just had a good discussion with @dannyparsons that included this feature on selects when new variables are added.  He had an excellent addition.  When you define a select - called roger, say, then add a variable while the select is in operation.  It doesn't change roger, but it adds a new select, called roger_.  And roger_ expands to include the new variable.  Now you are using roger_ so when further variables are added, they simply add to the expanding version!  And, when you look at the list, then  they are together.  That's why it is better to have roger_ compared to _roger!

@dannyparsons is happy to discuss this with you in terms of what is needed in the code.  Now we have built on this idea, in that Select has a Type and you choose one:
O Make Expanding Copy (Initial Default)
O Expanding
O Fixed

Make expanding copy is what I have described above.
If roger is expanding, then it behaves like roger_, i.e. it expands./
If roger is fixed, then any new variables are not part of roger.  (So you don't see them in the selection.)

**Comment by rdstern** [comment]
@shadrackkibet I have temporarily added the bug label here, because I think many commands don't work when a select is in operation.  This probably applies to any dialogue that creates a new variable?  
I noticed first with the Prepare > Column: Numeric > Row Summaries.  Now the example below is from Prepare > Column: Calculator.  I used the survey data and selected the numeric variables, then did yield * 2, and tried to save it.  This now gives the error:
![image](https://user-images.githubusercontent.com/11226469/155933903-0d9f2785-b518-4b99-ab11-5bce84f02756.png)

In the commands generated:
```
# The dialog, Calculations

survey <- data_book$get_data_frame(data_name="survey", use_current_filter=FALSE)
attach(what=survey)
calc <- yield*2
data_book$add_columns_to_data(data_name="survey", col_name="calc", col_data=calc, before=FALSE)
```
It is the last line above, namely `data_book$add_columns_to_data` that has to change.
