### ISSUE TITLE
Implement skimr in Describe > Two Variable > Summarise Dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7204]
The proposed changes should wait for implementation until the current work by @Ivanluv is merged.  But the possible changes can be designed and investigated while waiting.  It may be made redundant, after discussions with Danny,  by the similar suggested work in #7213.  Not sure yet, so keeping both open for now and with Ivan suggested for both.

This is to implement the skim function from the skimr package, which is one of the packages in tidymodels.  This is designed as a pipe friendly replacement for the summary function that we use currently as the default.  My initial view - without a detailed investigation is as follows:
1) I like the existing summary function and use it often.  So we might add skim as an additional (so third) option rather than using it instead of summary.
2) Like summary it should be sensible for any type of variable.  That's useful for this dialogue, where I often simply choose all variables.
3) If we do decide to add it, then I suggest the radio buttons move to the usual top of the dialogue as in most other dialogues with options that change the controls on the dialogue.
4) One reason for adding it would be to also use it for the 2, variable (with one by variable) and in the 3-variable, (with 2 by variables).  We don't (yet) have anything there that can cope with mixed data types in the multiple receiver.  Please can this be checked at the same time.
5) The skimr allows flexibility in which summaries are produced.  This could be assessed in the investigation, but I assume we won't need this, as the third option - with our own summaries is available for that.

This is a good task for a quick initial assessment by @shadrackkibet and then allocation to an intern.

**Comment by shadrackkibet** [comment]
@Ivanluv are you working on this?

**Comment by Ivanluv** [comment]
@shadrackkibet not yet.

**Comment by shadrackkibet** [comment]
@derekagorhom do you want to try out this task?

**Comment by rdstern** [comment]
@shadrackkibet and @derekagorhom I suggest starting with the related #7213 describes the possible task better.  I am pretty convinced about 2 variable!

**Comment by derekagorhom** [comment]
> @derekagorhom do you want to try out this task?

yes please

**Comment by rdstern** [comment]
@derekagorhom let me suggest how you start and then report on what you are trying.
It claims to be like the R summary command, but better.  So first (either in RStudio or R-Instat) you should understand what it offers.
a) Like summary it should be ok with any data type.  So ok with numeric, factor, character, logical, date.
b) In addition, the results should be tidy - in the output window
c) This probably means they can be saved into a new data frame?
d) Then it should be possible (easy) to add a BY, which is usually a factor.  Then we can have lots of variables by a factor in the 2-variable dialogue.  

Nice challenge to try installing the package (skimr) in R-Instat and then trying parts of this in R-Instat?  That would be good, but otherwise (if that takes you too long) use RStudio.

If all ok, what would you suggest in the dialogue?  So the initial product is your report and recommendation.

**Comment by derekagorhom** [comment]
> 

Thank you @rdstern  for the explanation and recommendations. I will begin using Skimr package in Rstudio first to have a better understanding of how it works, after that i will give my report

**Comment by shadrackkibet** [comment]
@derekagorhom any progress? Any suggestions for the dialog? You may want to have a design on paper just to paint a picture of how it looks like.

**Comment by derekagorhom** [comment]
> @derekagorhom any progress? Any suggestions for the dialog? You may want to have a design on paper just to paint a picture of how it looks like.

Hello @shadrackkibet i was still working on some other pull request so i have not began any design on this package yet. but i will get a design available soon

**Comment by derekagorhom** [comment]
> I have some suggestion for the Skimr dialogue ![IMG_20220217_092542_268](https://user-images.githubusercontent.com/76208189/154448269-20508f6a-2758-4cb6-9910-a2fbd5f997a5.jpg)
> 
> @shadrackkibet are there any buttom that needed to be added

i made this dialogue based on the results i have from R studio which gave output like this 
![Screenshot skimr](https://user-images.githubusercontent.com/76208189/154449404-ac55ce82-927b-41be-9b69-12e239b39ffa.png)

**Comment by rdstern** [comment]
Hi @derekagorhom that is a good start.  I am thinking of it added to this dialogue:
![image](https://user-images.githubusercontent.com/11226469/154570969-ada5f149-1311-4d6a-a2c2-cdf81f6d7169.png)

So, at the top there would be skim, as you have, and the second option would be Customised (as in one-variable)
With your skim option there would still be the multiple and the single, but the othe3r options would be then very different.

Also:
a) Ok would be enabled, even if the single receiver is left empty.  Then it would effectively be a single set of variables, which ties with the example you gave.  (That could also go as an option on the one variable, but I don't think it isd necessary to have it there as well.
b) Your examples above are all for numeric variables.  Please could you try (as in the 1 variable) with a mix of types.  So, numeric, factor, character, date.  Like the summary I expect it won't complain, but I want to see what it does.
c) Then please try with the by.  And does the by have to be a factor, or will mit treat other types as though they are a factor.
d) And, I assume, with the by and without, that (as it is a tibble) that the results can be saved into a data frame?
Then we are ready to go and add it to the dialogue.

**Comment by derekagorhom** [comment]
Thank you @rdstern, 

I will work on the other data types and send the result here.

**Comment by rdstern** [comment]
Thanks.  If you look at our one-variable summarise you will see that any data type is ok for that function.  But, of course it can't give the same summary statistics.  That's easy6 there, because the results are not in a tidy shape.  So, I wqould expect most of these summary values here to be NA - but let's see.

**Comment by derekagorhom** [comment]
@rdstern 
i used `ghana_tamale_saltpond1%>% dplyr::group_by(month_abbr) %>% skim()` from the skim package and had the these results for Numeric, Character and Logical. 

Please can you have a look and confirm if that is what you expected the package to provide

![Character](https://user-images.githubusercontent.com/76208189/154909789-9f242fad-d0f0-4486-96fc-91134b70eae4.png)
![logical](https://user-images.githubusercontent.com/76208189/154909796-8f9d3ba2-c5e1-4fa4-b26c-f2cde5d4533e.png)
![numeric](https://user-images.githubusercontent.com/76208189/154909799-1cb60a2e-c02e-4efe-a9f3-4e23fc002635.png)
![Positxt](https://user-images.githubusercontent.com/76208189/154909803-d3d7322a-6034-4ebc-b979-20893718b607.png)

**Comment by derekagorhom** [comment]
for factors i used `chickwts %>% dplyr::group_by(weight) %>% skim()` and had this result

![Screenshot (397)](https://user-images.githubusercontent.com/76208189/154910821-36f3cfd9-e2ed-4eee-a201-8224ea79c97f.png)

**Comment by rdstern** [comment]
@derekagorhom I think it may be time you tried something in R-Instat - which  can run R commands.  
I notice the presentations above are not particularly great, but hope for better things.  The main point is not what happens with variables of different types, but what happens when you consider them together.
So how are the results displayed in a tidy way when you analyse combinations of a factor, date, character numeric, together - and then by a factor.
Currently in the 2 variable dialogues the multiple receiver can be anything - but only of 1 type at a time.  In contrast the multiple receiver for one variable can have a mixture of data types.  I am hoping the skim command can allow (like the one variable summary) a mixture of data types in the multiple receive, by an (optional) single receiver, that is probably a factor.  And, because the results are tidy, that they can (also optionally) be saved into a data frame.

**Comment by derekagorhom** [comment]
> @derekagorhom you have been quiet for the past week. Is this because of lots of other work, so perhaps @shadrackkibet should re-allocate this task? Or are you working on it. Your sketches above, adding the extra button at the top of the current Two Variable Summarise dialogue, would seem to be fine.

Yes @rdstern  sorry for being absent for awhile, i had some discussions with Ivan and i will be adding the button to the current two variable summarise dialogue

**Comment by derekagorhom** [comment]
our problem was that skim separates the results of the data types and also because of how it is coded
eg `skim(iris,.......)`
 there was no need for `the summary textbox`, `option textbox `and` the second variable`

**Comment by rdstern** [comment]
What about: 


```
iris %>%
  dplyr::group_by(Species) %>%
  skim()
```
That's in the [vignette](https://cran.r-project.org/web/packages/skimr/vignettes/skimr.html)

I assume, for 2 variables you would include that factor, and possibly also allow for a second factor?

**Comment by derekagorhom** [comment]
![customize](https://user-images.githubusercontent.com/76208189/156344296-f94e7d22-98da-4357-a2dc-02ddd74e63c5.png)

This is for the original 2 Variable summarise

**Comment by derekagorhom** [comment]
![skim](https://user-images.githubusercontent.com/76208189/156344467-f1625aef-a644-4555-99e5-cadb7bea9b1c.png)


This is how the skim dialogue would look it... but we add other items to it

**Comment by derekagorhom** [comment]
> What about:
> 
> ```
> iris %>%
>   dplyr::group_by(Species) %>%
>   skim()
> ```
> 
> That's in the [vignette](https://cran.r-project.org/web/packages/skimr/vignettes/skimr.html)
> 
> I assume, for 2 variables you would include that factor, and possibly also allow for a second factor?

![skimNew](https://user-images.githubusercontent.com/76208189/156348888-b90dfc88-9434-411d-a5d5-d010e87214ae.png)

Would this be ok for the Skim dialogue?
