### ISSUE TITLE
Add ggpairs to the Describe > Two Variables > Graphs dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7212]
I suggest this is a clear "low-hanging" fruit.

This addition will be a new radio button at the top called Pairs.  I don't then have a good name for what is there now, which could be perhaps "By".

In the current dialogue there is a multi0ple receiver, plus a single receiver.  And the multiple rece3iver can only have variables of one type.
 The Pairs just looks at variables 2 at a time.  So, there is just the same data control plus a multiple receiver.  And it runs the GGally::ggpairs command.  The multiple receiver can take at least factors or numeric, so start with no restrictions.  Let's explore what happens with dates, character, logical, etc.

We already use this command with numeric variables in the Describe > Multivariate > Correlations dialogue.  Here we will include a variety of options, some on the dialogue and others on an Options sub-dialogue.  It is a very rich resource!

**Comment by rdstern** [comment]
We now have the ggpairs dialogue working and here are 2 nice examples from tutorial 1.

![image](https://user-images.githubusercontent.com/11226469/202861816-6b5a7acd-b19f-42ad-b206-1f5855f1b59d.png)

Now there is something missing from these plots and that is the legend.  We don't know which colour corresponds to which group, etc.

Here is the dialogue:
![image](https://user-images.githubusercontent.com/11226469/202862050-22a7b192-0ba8-4b07-8f53-c0d394633ae3.png)

I suggest we need to implement the Plot Options sub-dialogue at least for the legend.  There is a legend option in the dialogue and then either:
a) We complete this issue once there is an option of adding the legend, or
b) We also check from the ggpairs what else might usefully be included in the sub-dialogue.

For the legend, I tried initially by getting the ggpairs script, but I couldn't resolve the puzzle of adding a legend.  It needs better R than mine.

So sorting out the R code - I think codes for different options is the first step.  The default is, as now, with no legend!
Then I assume adding it to the dialogue should be quite simple.
@N-thony who could start on this one?

**Comment by N-thony** [comment]
@rdstern I think this will be good for @MeSophie to work on it, it will help her more on understanding the coding concept of R-Instat.

**Comment by N-thony** [comment]
@MeSophie can you take this over?
