### ISSUE TITLE
Width of initial row in reogrid?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7221]
Here is a data frame.  It has 3 million rows.  But the initial (zero column) has a fixed width, so you only see the first 5 numbers.
My main question is whether we can change the width of this initial column?

Danny's view is that it will be easy if it is a property of reogrid.  Otherwise it will be tricky or impossible.  I only want the change if it is easy.
While there could you also che3ck whether reogrid allows anything to be done in the top left-hand corner of the grid?  It has a sort of right-angle triangle there now.  Like input a symbol, or change the colour?  This is not to do with the first column, but could indicate a change of status, in some way in the future.

![image](https://user-images.githubusercontent.com/11226469/153454353-c1c49cc5-9ed9-4910-a03e-5c693fcb3484.png)

**Comment by Patowhiz** [comment]
@rdstern could you email or share here the dataset? Would be helpful for debugging and testing. Thanks.

**Comment by rdstern** [comment]
@Patowhiz There are plenty.  For example File > Open from Library > Datasets (default) and choose USJudgeRatings.  This has just 4 letters, but if you use Prepare > Data Frame > Row Numbers/Names and you see the information is much wider.

Numerically it only shows 5 numbers, so not complete when there are data rows more than 100000.

**Comment by Patowhiz** [comment]
@rdstern the ReoGrid seems to not have this feature as a setting option. I have asked them in issue https://github.com/unvell/ReoGrid/issues/468 in their repo. 

In the meantime, I suggest manually calculating the length of the longest row header and just setting it's pixels equivalent as the width of the row header.

**Comment by rdstern** [comment]
@Patowhiz sometimes the row variable is quite wide, e.g. mtcars in the datasets provided.  I've copied the row contents into the initial row for clarity:
![image](https://user-images.githubusercontent.com/11226469/170968575-0ad4dee6-5d2e-43ec-986c-b9ce1a576340.png)

I notice there that 7 characters are sometimes shown as well, e.g. Lincoln, Cadilla.  If we could have 7 numbers shown, i.e. up to 9999999, then I would be quite happy.  See below for the problem:
![image](https://user-images.githubusercontent.com/11226469/170969518-cced54c0-c151-4cc8-907d-cec709519e4c.png)

So, just a bit wider would do fine, to show 7 numbers rather than 5, or perhaps a slightly smaller font?.  If long, then right-justified, would also be ok, but not in general, for the mtcars it is nice left justified.

What do you think?

**Comment by Patowhiz** [comment]
@rdstern for the `ReoGrid`. I would suggest always showing the entire contents. `ReoGrid` seems to not have a setting option that allows a user to increase or reduce the length of the row header (I think they typically just replicated what is possible in excel, and my excel version doesn't allow this).

I've been looking into how we can align the row header contents after adjusting it's width. So far, I've been unable to do this. I've added this as an issue https://github.com/unvell/ReoGrid/issues/469 in `ReoGrid` repo.

Please note, the datagridview of VB.NET allows the user to be able to increase and reduce the row header, and it also automatically left align the row header contents.

Have a look at what I have managed to implement in PR #7510
