### ISSUE TITLE
A simple addition to the Prepare > Column: Numeric > Transform dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7236]
@shadrackkibet I am assuming this is work for @anastasia-mbithe because it is "her" dialogue - and it is looking very good now.
But please check that this is a useful addition.  And possibly you should quickly do it, because it may take longer to explain!

We need to be able to do simple logical calculations - and this dialogue is the place to do it!
So please add another radio button on the first set, i.e. the set that starts with Round.
The label is Logical.
If chosen then it gives a choice of operator, from ==, downwards.  For most of these options there is a smallish field for a number to be typed.  
The order of the operators, and I assume the code is exactly the same as in the Filter sub-dialogue.  Which is why I wonder if @shadrackkibet might choose to do it quickly?  We might as well have even the options isna, so identical - deliberately - to the filter options!
Good for teaching too.  I find logical calculations are surprisingly new to many people!

**Comment by shadrackkibet** [comment]
@anastasia-mbithe could you work on the designer part of this? Please add the following;
- A radio button named "Logical" 
- When clicked it open up a non-editable Combobox and a Textbox

Let me know when you are done. Thanks
