### ISSUE TITLE
Moving Column Structure Dialogue  from the Prepare Menu to Options by Context Menu (Soon to be Experiments Menu) 

### ISSUE THREAD

**Issue by fran2or** [africanmathsinitiative/R-Instat#7239]
**Is your feature request related to a problem? Please describe.**

There has been a discussion between @rdstern, @volloholic and I about moving the column structure dialogue (Prepare > Data Frame > Column Structure)  to the current Options by Context Menu (Options by Context Menu > Define Options by Context Data ) which will soon be changing to the Experiments Menu (Experiments > Define Experiments > On - Station Type ). We think the column structure dialogue will be more relevant under this menu as an option for the On - Station  data type structure definition. For more information  on the Experiments Menu, please check out Discussion #6879. 

**Describe the solution you'd like**

I suggest that the column structure dialogue (Prepare > Data Frame > Column Structure) is moved to the current Options by Context Menu (Options by Context Menu > Define Options by Context Data ) as soon as is possible so that its code is not lost and is easily available for when we decide to move forward with the Experiments Menu.

**Comment by N-thony** [comment]
@rdstern how about this? Could @Vitalis95 try this? Thanks.

**Comment by rdstern** [comment]
That affects frmmain, so need to check with @shadrackkibet first.  We are trying to be efficient about changes to frmmain.

**Comment by Vitalis95** [comment]
@shadrackkibet , can I take up this task? It affects frmmain.

**Comment by shadrackkibet** [comment]
Sure. Please work on it.

**Comment by Vitalis95** [comment]
@fran2or @rdstern ,   There exists a Define options By Context Data dialog at the Options by Context Menu > Define Options by Context Data where am suppose to add the column structure dialogue from prepare menu. Can we add it to Options by Context > Prepare?
![image](https://user-images.githubusercontent.com/89011415/154970076-c7d5c812-3009-4b82-85f5-d73575925a8c.png)

![image](https://user-images.githubusercontent.com/89011415/154969724-1c930270-4e02-4dda-beb0-aca2699c17db.png)

**Comment by fran2or** [comment]
> @fran2or @rdstern , There exists a Define options By Context Data dialog at the Options by Context Menu > Define Options by Context Data where am suppose to add the column structure dialogue from prepare menu. Can we add it to Options by Context > Prepare? ![image](https://user-images.githubusercontent.com/89011415/154970076-c7d5c812-3009-4b82-85f5-d73575925a8c.png)
> 
> ![image](https://user-images.githubusercontent.com/89011415/154969724-1c930270-4e02-4dda-beb0-aca2699c17db.png)

@Vitalis95 I think what we want is to have the **column structure** and the current **define options by context data** dialogs under the same sub menu and not under different sub menus as proposed in your earlier question to us. I hope the current proposed fix #7250  implements it as discussed in the discussion #6879 . As shown in the snippet below,  the sub menu is  **Define** , should contain _On - Station_  (this is supposed to be the column structure dialog) and  the _On - Farm_ (this will be the define options by context data sub menu) dialogs. I hope this helps otherwise  I am happy to talk through it on a call. 

![image](https://user-images.githubusercontent.com/6714330/155334095-4ac9f424-aa08-4f29-b442-6255f2ed5664.png)
