### ISSUE TITLE
Improve the Prepare > Column: Numeric > Row Statistics dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7240]
This started small, but has grown in what I consider to be a most satisfactory way.  Most changes are simple, but I hope @lilyclements can confirm my suggestions for the new R code and also provide (at least) some simple examples.

Here is the current dialogue:
![image](https://user-images.githubusercontent.com/11226469/154447025-badc6f7c-2a42-4a11-a6c9-0cff6b9c5262.png)

Here is the corresponding R code:
```
# Code generated by the dialog, Row Summaries

row_summary <- base::apply(X=data_book$get_columns_from_data(data_name="Scores", col_names=c("BlueSky","Deducer","JASP","jamovi","RAF","Rattle","Rcmdr","R_Instat","RKWard"), force_as_data_frame=TRUE, use_current_filter=FALSE), MARGIN=1, FUN=mean)
data_book$add_columns_to_data(data_name="Scores", col_name="row_summary", col_data=row_summary, before=FALSE, adjacent_column="RKWard")

rm(row_summary)
```
My suggested changes to the dialogue are as follows:
a) Two radio buttons at the top.  Label first, namely `Summaries: `.  Then `Single` and `Multiple`
b) The Single option is what we have now, namely each row of data gives a single summary.  Multiple is new, described below.
c) In Single swap the `Count and Standard Deviation`.  Also change Number of Missing to `Number Missing`
d) (This needs confirmation from Lily).  Get rid of the User Defined button, but have a 9th radio button labelled User Defined.
e) If User defined is chosen, then open a drop down with a text field into which you can type a command.  The drop down can include   (some of) the 8 existing ones, plus a few more to be decided.
f) Now the code generated.  First the existing code has a very long first line.  Could you separate getting the data, from using it.  That is usually done.
g) Second is that we use apply.  We would like to use tidyverse when appropriate and dplyr has rowwise [here]
 (https://dplyr.tidyverse.org/articles/rowwise.html).  @lilyclements I assume we should use it?  I even wonder whether we could use code with a pipe in - as is usual in tidyverse?
h) in the user defined, could we include log?  @lilyclements Could we get both the log of the mean and the mean of the logs?

Part 2 - now the multiple, which was my starting point.
I wanted to get the ranks - row by row.
This produces 9 variables above and putting rank works fine.  So here we are producing 9 columns.  What else might we have?  Well deviations from mean, standardised values compared to the others in the rows.  Hopefully therefore Used Defined too.

I assume this will be a simple set of tasks after a Lily check?  So anyone could be assigned.

I am keen on this, because in our review I reminded Bob that we do have row statistics.  (It is one of his categories.)  So, before too many people look in detail I'd like to be sure we do it well!

**Comment by EstherNjeriLiberatta** [comment]
@africanmathsinitiative/developers I'm taking this up.

**Comment by rdstern** [comment]
@EstherNjeriLiberatta this is good progress.  
a) Could you move the radio buttons over a bit to the left, so that the user defined - where you type - can be somewhat wider.
b) After an error - try typing a function Esther - which doesn't exist in R I think! Then it gives a reasonable error message.  But it also then gives a developer error every time I go back into the dialogue.  After you are in, then it is alright.

![image](https://user-images.githubusercontent.com/11226469/155877258-f42c1411-3b4a-40b6-be0b-314433d1ee83.png)


c) Add a checkbox above the buttons and on the right for `Omit Missing Values`.   This is already in various dialogues, e.g. Prepare > Data: Reshape > Column Summaries.  Default is unchecked.  If checked, then, after the FUN you will need to add na.rm = TRUE I think.  That will also apply to the user defined functions.
More in next comment

**Comment by rdstern** [comment]
This is for reference and uses the matrixStats package.  This is already loaded into R-Instat (I wonder where we use it?) 
It already produces all we need for the Multiple (I think!).  There:
a) I am particularly keen on ranks
b) Range seems to produce 2 variables, i.e. Min and Max
c) A third obvious option is quantiles (when we have more than 1.  They all work already, from a slight adaptation of your existing code.  One improvement (in R) would be to provide better names:

```
# The dialog, Row Summaries

columns <- data_book$get_columns_from_data(data_name="relig_income", col_names=c("X..10k","X.10.20k","X.20.30k","X.30.40k","X.40.50k","X.50.75k","X.75.100k","X.100.150k","X.150k"), force_as_data_frame=TRUE)

row_summary1 <- matrixStats::rowRanks(as.matrix(columns),dim.=c(18,9))
data_book$add_columns_to_data(data_name="relig_income", col_name="row_summary1", col_data=row_summary1, before=TRUE)

rm(list=c("row_summary1", "columns"))

# The dialog, Row Summaries

columns <- data_book$get_columns_from_data(data_name="relig_income", col_names=c("X..10k","X.10.20k","X.20.30k","X.30.40k","X.40.50k","X.50.75k","X.75.100k","X.100.150k","X.150k"), force_as_data_frame=TRUE)

row_summary1 <- matrixStats::rowRanges(as.matrix(columns),dim.=c(18,9))
data_book$add_columns_to_data(data_name="relig_income", col_name="row_summary1", col_data=row_summary1, before=TRUE)

rm(list=c("row_summary1", "columns"))

# The dialog, Row Summaries

columns <- data_book$get_columns_from_data(data_name="relig_income", col_names=c("X..10k","X.10.20k","X.20.30k","X.30.40k","X.40.50k","X.50.75k","X.75.100k","X.100.150k","X.150k"), force_as_data_frame=TRUE)

row_summary1 <- matrixStats::rowQuantiles(as.matrix(columns),probe=(c(0.25,0.5,0.75)))
data_book$add_columns_to_data(data_name="relig_income", col_name="row_summary1", col_data=row_summary1, before=TRUE)

rm(list=c("row_summary1", "columns"))

```

**Comment by lilyclements** [comment]
@rdstern first, apologies that it has taken more than a few days to get to this.

1. I agree that we should use `rowwise()` instead of `apply`. It is consistent with our tidyverse codes, and I think it is easier to understand too - especially if using user defined functions.

One difference is that `apply` creates a vector whereas `rowwise` works with a data frame to produce a data frame.

Using your example, we currently would run the following code
```
# Code generated by the dialog, Row Summaries

row_summary <- base::apply(X=data_book$get_columns_from_data(data_name="Scores", col_names=c("BlueSky","Deducer","JASP","jamovi","RAF","Rattle","Rcmdr","R_Instat","RKWard"), force_as_data_frame=TRUE, use_current_filter=FALSE), MARGIN=1, FUN=mean)

data_book$add_columns_to_data(data_name="Scores", col_name="row_summary", col_data=row_summary, before=FALSE, adjacent_column="RKWard")
```

With `rowwise()`, we would no longer be selecting columns and adding a new column to the data frame. But instead updating the data frame,

```
Scores <- data_book$get_data_frame(data_name="Scores")

row_summary <- Scores %>% dplyr::rowwise() %>% dplyr::mutate(Mean = mean(c(BlueSky, Deducer , JASP, jamovi, RAF, Rattle, Rcmdr, R_Instat, RKWard)))

data_book$import_data(data_tables=list(Scores = row_summary))
```

The only issue I can see here is that this would create a data frame called "Scores1" to avoid overwriting the "Scores" data frame. There might be a way to overwrite that.


2. I don't see why we can't use `log`, unless I'm misunderstanding something

3. @rdstern how are you currently running ranks in R-Instat with multiple columns? I'll work from there to get the R code for a tidyverse method - or is this currently not an option in R-Instat?

**Comment by lilyclements** [comment]
@rdstern just saw your comment on ranks, so ignore my third point in the above message. I checked and we don’t directly yet use any functions from the matrixStats package, it’s just loaded in. I’m not sure why!

**Comment by lilyclements** [comment]
@rdstern yes we can call the proposed "More pull-down" functions. The `rowRanks` can also look as outlined above. @EstherNjeriLiberatta this should be ready now to make more changes using `rowwise()` and the `matrixStats` functions.

**Comment by EstherNjeriLiberatta** [comment]
Thank you @lilyclements
