### ISSUE TITLE
Convert 2 digit year to 4 digits

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#7254]
This would be useful to add in the (Climatic) Conversions dialog. It's fairly simple to do but not completely trivial for users to know how to do in the calculator.

It just needs a one line function. There should be an option of a base year to know what the year is i.e. if the base year is 1930 then anything above 30 has 19 added to the front of it and anything below has 20 added.

The reverse is less commonly needed and already easy in the Transform Text dialog so I don't think we need that also.

**Comment by anastasia-mbithe** [comment]
Hello @dannyparsons, so what I get is that, this should be added as another top radio button in the Conversions dialog. Am I right?
