### ISSUE TITLE
Update the correlations dialog to use the newer corrr package

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#7257]
A new `corrr` package is discussed on issue #6121. So here, I will outline potential ideas to edit in the "Multivariate > Correlations" dialog.

We currently have two options on the Correlation dialog - "Two Columns" and "Multiple Columns".

**I'll start with "Multiple Columns":**

"Multiple Columns" currently runs `cor`, which gives a correlation matrix between the specified variables.

I suggest we replace the function in the "Multiple Columns" tab with `correlate` from the `corrr` package. The parameters do not change, so should be a very simple change.

```
library(corrr)
data(mtcars)

# currently for a kendall method and missing as complete.obs:
cor(x = mtcars, method = "kendall", use = "complete.obs")

# with the new function in the corrr package
corrr::correlate(x = mtcars, method = "kendall", use = "complete.obs")
```

If we wanted, we can introduce other options.

1. Specify the value in the diagonal with a `diagonal` parameter in the function. E.g.
` corrr::correlate(x = mtcars, method = "kendall", use = "complete.obs", diagonal = "Hello")`
2. The `fashion` function gives a few extra options we could include. The user can then decide the number of decimal places, if they want the initial zero, or how to display NAs:
`cor_table <- corrr::correlate(x = mtcars, method = "kendall", use = "complete.obs", diagonal = "Hello")`
`fashion(cor_table, decimals = 2, leading_zeros = TRUE, na_print = "")`
3. Get just the triangular of the correlations with the `shave` function
`cor_table <- corrr::correlate(x = mtcars, method = "kendall", use = "complete.obs", diagonal = "Hello")`
`fashion(shave(cor_table))`

![image](https://user-images.githubusercontent.com/21180424/156200150-44699612-de78-4a01-95e3-fe5f44d543b2.png)

So we can add 
1. An option "Display on diagonal" with an input, default "NA" in. This is linked to the `diagonal` parameter.
2. An option "Decimal Places:" with a nud. This is linked to adding the `fashion` function and the `decimals` parameter
3. An option "Display NAs" with an input. This is linked to adding the `fashion` function and the `na_print` parameter
4. A checkbox "Leading zeros", default `TRUE`. If `FALSE`, this is linked to adding the `fashion` function and the `leading_zeros` parameter.
Option 2-4 might be less trivial because they add the same function. @rdstern do you think we want this?

**Onto "Two Columns"**

Currently we use `cor.test` which performs a correlation test between the two given variables. We can use the `correlate` function, but then lose the formalised test.

@rdstern presumably we want to keep the test in here? In which case, we can keep this option as `cor.test`.
If not, then all the functionality laid out above still work, but now in the `correlate` function, `x` is a variable, and a new `y` argument is used for the second variable.
`correlate(x = mtcars$mpg, y = mtcars$cyl)`.
I'll expand on this if you think we should use `correlate` here too.

**Sub dialog**
In the `corrr` package is `rplot`, but this does not seem to do anything that we do not already have in the "Correlation Plot" option.
In the output, we can just read in correlation object from the `corrr` package. E.g., for the "Correlation Plot" option:

```
last_model <-  corrr::correlate(x = mtcars, method = "kendall", use = "complete.obs")
GGally::ggcorr(last_model)
```

There is another plot but the output does not seem to work properly for me. I'm not sure why this is.

**Comment by rdstern** [comment]
@lilyclements this all sounds good.  The one additional item I wonder about is the saving of the correlations in a new data frame?  I thought that was one of the reasons it was part of the tidyverse stuff, and that would be nice to add, if I have understood correctly.
I am also keen to include the correlation dialogue in the Describe > Two Variables dialogues as well as having it here on multivariate.

**Comment by lilyclements** [comment]
Yes it saves as a tibble. It’s very easy to then saving it as a new data frame. We can then add another checkbox then to “Save as data frame”?
I’ve written up on correlation in Describe > Two Variables in issue #7259

**Comment by rdstern** [comment]
Sounds good.

I saw #7258, which does have correlations, when both types are numeric as part of Describe > Two Variables > Summarise.  In addition I am thinking of also including the whole correlations dialogue, separately as Describe > Two Variables > Correlations.

**Comment by lilyclements** [comment]
@rdstern sounds good - would the correlations dialog in Describe > Two Variables > Correlation only have the option to compare variables against one other variable?

**Comment by rdstern** [comment]
@lilyclements no, I was thinking the full correlations dialogue.  It is (like other dialogues in this menu still just looking at the columns in pairs.

**Comment by rdstern** [comment]
I quite liked this [article on corrr](https://drsimonj.svbtle.com/exploring-correlations-in-r-with-corrr).  This seemed to show that fashion() gave blanks for the diagonal, which looked clear.  Do we want the diagonal to have a pull-down with the values NA (default, 1, and blank), where blank becomes ""?
Do we want to add rearrange?  I really like the idea of being able to see the correlations in a logical order.  I also liked all the options for the missing values!  
And (perhaps in the future(?) I really liked some of the things you could do with focus?  You don't just get correlations you use them!
We definitely should have the options to just look at half the matrix!
You mention that we already do the plots.  But I also wonder about adding the rplot function there.  It says it is particularly used after rearrange and shave, which is interesting!

**Comment by Vitalis95** [comment]
@lilyclements  @rdstern  I have run the following code in R before implementing it in VB, when I add the diagonal parameter it will not recognize the decimal parameter from the fashion function.  But when I remove the diagonal parameter it specify the number of decimals according to the  decimals you have specified in the parameter.

```
cor_table <- corrr::correlate(x = mtcars, method = "kendall", use = "complete.obs", diagonal = "Hello")
fashion(cor_table, decimals = 2, leading_zeros = TRUE, na_print = "")
```
![image](https://user-images.githubusercontent.com/89011415/157265419-c527d8da-6e5c-442f-b848-c518dbef66f6.png)

![image](https://user-images.githubusercontent.com/89011415/157265739-5f94de61-1157-4b41-b1ca-81877c5d2bd4.png)

**Comment by lilyclements** [comment]
@Vitalis95 interesting spot. How about if the diagonal is a numerical value, like 1? Perhaps it’s because “Hello” makes it into a character variable then the decimal places do not work correctly.

**Comment by Vitalis95** [comment]
@lilyclements the value to set the diagonal to is typically numeric or NA, I will add a tooltip on the  display diagonal textbox explaining that. 
The `na_print` parameter from the fashion function replaces `diagonal=NA` with the value you have specified in `na_print`
Also, it replaces upper triangular generated by the `shave` function with value you have specified in `na_print`  .The triangular should be blank
Can we do away with that parameter?
Thanks

**Comment by Vitalis95** [comment]
If `na_print=" "` blank , it will not replace the upper triangular and `diagonal=NA`

**Comment by lilyclements** [comment]
@Vitalis95 I’m suggesting we have a little test in R to confirm whether the issue indeed occurs for strings and doesn’t occur for numerical values.
Can try running the code in R with the diagonal set as a numeric value, and then see if the decimal places argument works?
Also try setting it as a numerical value with several decimal places (say, 3) and then try the decimal place argument to reduce it to, say 2.
If these work then I suggest we allow the diagonal to be set to a numerical value only (or NA). 

As for na_print, what if the user didn’t want to have a blank triangle and had other NAs which werent in the diagonal? I’m not sure if we should remove it completely as an option?
