### ISSUE TITLE
Update correlations in the Describe > Two Variables > Summarise dialog to use the newer corrr package

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#7258]
A new corrr package is discussed on issue https://github.com/africanmathsinitiative/R-Instat/issues/6121. So here, I will outline potential ideas to edit in the "Describe > Two Variables > Summarise" dialog.

Currently if both receivers contain a numerical variable, correlation summaries are performed using the `data_book$cor` function.

The `correlate` function in the `corrr` package can be an alternative function to consider here, and would not require much change to the code:

```
# currently:
data_book$cor(data_name = "mtcars", x_col_names = c("mpg", "hp"), y_col_name = "cyl")

# instead:
cor_table <- corrr::correlate(mtcars %>% dplyr::select(c(mpg, hp, cyl)))
corrr::focus(cor_table, cyl)
```
_where mpg, hp are in the x-receiver, and cyl in the y receiver._

Note that I'm suggesting we use `dplyr::select` instead of our usual method of `$get_columns_from_data`. This is because we would have to run `$get_columns_from_data` for both the variables in the x receiver and in the y receiver. The x receiver may contain multiple variables, hence the object returned by `$get_columns_from_data` is a data frame. However, the y receiver will be a vector. This causes an issue in R.

```
E.g.
x_cols <- data_book$get_columns_from_data(data_name = "mtcars", col_names = c("mpg", "hp"))
y_col <- data_book$get_columns_from_data(data_name = "mtcars", col_names = c("cyl"))

corrr::correlate(x = x_cols, y = y_col)
# gives error
```

**Comment by rdstern** [comment]
@lilyclements I am also liking the code you are suggesting.
@Ivanluv you will anyway be working on that dialogue, for the tabulation part, so could you take this on?
Is corrr already one of the R-Instat packages?  If not, then could it also be added through this pull request?
