### ISSUE TITLE
Navigating the grid using keyboard arrows

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#7273]
In Excel, you can always navigate around the cells using keyboard arrows. I think this is a nice to have feature in the data view window.  
![image](https://user-images.githubusercontent.com/26301973/156886777-9ca28297-928e-467d-8ffe-92d4ea0ba5f2.png)

**Comment by rdstern** [comment]
Agreed - didn't realise it didn't!

**Comment by N-thony** [comment]
@mmulahvictor can you try this? Let me know if you need help.

**Comment by mmulahvictor** [comment]
@N-thony I will try it out.
