### ISSUE TITLE
Sort out labelling in factor (and possibly in character?) variables

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7275]
When I have a labelled factor variable I can edit the levels and labels with the right-click Levels/Labels (same as Prepare > Factor >Levels/Labels dialogue.  This runs the databook set_factor_levels function e.g. 

```
# The dialog, Labels/Levels
data_book$set_factor_levels(data_name="survey", col_name="fert2", new_labels=c("None4","0.5","1","1.5","2","2.5","Max4"), new_levels=c(0.2,0.5,1.0,1.5,2.0,2.5,3.5))
```
This works fine.  I can edit either the levels, or the labels, and this works fine.  I can also make the labels not unique.  But I can't make the levels not-unique.  If the factor isn't labelled, then non-unique labels will reduce the number of levels.  If it is labelled, then the number of levels stays the same, because they have different levels.  I am happy with all this.

But the `Prepare > Factor > Recode Factor` does (seemingly) roughly the same thing, except it gets in a (big) mess with labelled data.  It has 4 radio buttons at the top.  They don't know about labels, so the labelling doesn't change.  I suggest either our labelling function is done after its function, or we may delete labels first and then reinstate the new labels afterwards.  Then sometimes the levels will be NA and that's fine (I hope!).

I have checked the other factor functions briefly and I think they are ok!

And I think character operations lose the labelling so that's ok too.  

That's a relief.  I think a) the levels/labels is working ok, and there is just the one dialogue in the factors to correct. 

It is good that @shadrackkibet and @N-thony are together this week, and I hope this will turn out to be simple.

**Comment by N-thony** [comment]
> When I have a labelled factor variable I can edit the levels and labels with the right-click Levels/Labels (same as Prepare > Factor >Levels/Labels dialogue. This runs the databook set_factor_levels function e.g.
> 
> ```
> # The dialog, Labels/Levels
> data_book$set_factor_levels(data_name="survey", col_name="fert2", new_labels=c("None4","0.5","1","1.5","2","2.5","Max4"), new_levels=c(0.2,0.5,1.0,1.5,2.0,2.5,3.5))
> ```
> 
> This works fine. I can edit either the levels, or the labels, and this works fine. I can also make the labels not unique. But I can't make the levels not-unique. If the factor isn't labelled, then non-unique labels will reduce the number of levels. If it is labelled, then the number of levels stays the same, because they have different levels. I am happy with all this.
> 
> But the `Prepare > Factor > Recode Factor` does (seemingly) roughly the same thing, except it gets in a (big) mess with labelled data. It has 4 radio buttons at the top. They don't know about labels, so the labelling doesn't change. I suggest either our labelling function is done after its function, or we may delete labels first and then reinstate the new labels afterwards. Then sometimes the levels will be NA and that's fine (I hope!).
> 
> I have checked the other factor functions briefly and I think they are ok!
> 
> And I think character operations lose the labelling so that's ok too.
> 
> That's a relief. I think a) the levels/labels is working ok, and there is just the one dialogue in the factors to correct.
> 
> It is good that @shadrackkibet and @N-thony are together this week, and I hope this will turn out to be simple.

@rdstern @shadrackkibet I will try this out as we discussed ASAP PR #7208 will be merged. Thanks.
