### ISSUE TITLE
Small bug on the Climatic > Check Data > Inventory Plot Dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7280]
**Describe the bug**
This bug seems to be there for long, it occurs under Missing option by checking `Summary, Details and Save Details` checkboxes.
I tried this with the `Dodoma` dataset

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Climatic > Check Data > Inventory Plot Dialogue
2. Click on Missing option
3. Then add any variable you wish, in my case I have added `rain`
4. Then check on `Summary` and `Details` checkboxes then click OK, if you observe the output window it clearly runs the `climatic_missing function` for Summary checkbox and `climatic_details` for Details option and print the output of both functions
5. Then back to the dialogue, now check `Save Details` cehckbox, it does the same thing explained in 4 but here it ignores to print the output from `climatic_details function`
6. Then back again to the dialogue and click OK, you will get the bug shown in the screenshot below

![image](https://user-images.githubusercontent.com/68591383/157416009-0b6d6f4f-4a2c-49dd-a872-c071129295ee.png)

**Comment by EstherNjeriLiberatta** [comment]
@N-thony I'll work on this.

**Comment by N-thony** [comment]
I found that the problem was coming from `.SetPrefix()` parameter name  of the `Save Details` control  which is `climatic_details`. To fix this we simply need to change the `.SetPrefix()` to something like `details` maybe.

I suggest also to hide the `ucrSaveDetails` when `Details` checkbox is unchecked since we are only saving the details. @rdstern do you agree?
