### ISSUE TITLE
File > Export > Export Dataset UI issues

### ISSUE THREAD

**Issue by geoo89** [africanmathsinitiative/R-Instat#7286]
**Steps to reproduce**
- File > Export > Export Dataset
- Pick destination file ('Save As' field)
- Select data frame(s) to export
- After selecting data frame, the filename is removed from the destination ('Save As') field.

**Expected behaviour**
Filename should remain there.

![image](https://user-images.githubusercontent.com/678199/157667018-ab7f399e-7854-43a6-ab54-a947a8170fae.png)

**Details:**
 - OS: Ubuntu 18.04 (docker-version)
 - R-Instat Version: Commit [cdddbdf](https://github.com/IDEMSInternational/r-instat-docker/commit/cdddbdf665956dbd88505b8e093b26619b844413) from https://github.com/IDEMSInternational/r-instat-docker
Also occurs on Windows, version 0.7.4

**Comment by Patowhiz** [comment]
@geoo89 very true. I've fixed this in PR #7328 .
