### ISSUE TITLE
Default selected sheet in dialog is different from currently displayed sheet

### ISSUE THREAD

**Issue by geoo89** [africanmathsinitiative/R-Instat#7288]
**Describe the bug**
With many common data operations that refer to a specific data frame, a different data frame than the currently shown one is selected by default. This can be confusing. 

**To Reproduce**
- Open two sheets (say, A and B)
- Select A to be displayed
- Prepare > Data Frame > Filter
- If A is selected in the filter dialog, cancel. If B is selected in the filter dialog, this is an instance of this issue and you can stop here.
- Select B to be displayed
- Prepare > Data Frame > Filter
- A is selected in the filter dialog

**Expected behaviour**
By default, select the currently shown sheet in the filter dialog.

**Screenshots**
![image](https://user-images.githubusercontent.com/678199/157668460-de55389d-8a4a-4051-b3e1-0f73eebe2619.png)

**Details:**
 - OS: Ubuntu 18.04 (docker-version)
 - R-Instat Version: Commit [cdddbdf](https://github.com/IDEMSInternational/r-instat-docker/commit/cdddbdf665956dbd88505b8e093b26619b844413) from https://github.com/IDEMSInternational/r-instat-docker

**Additional context**
This issue is common to many dialogs, also e.g. Prepare > Data frame > Sort or Prepare > Data Reshape > Column Summaries.
There might be a rationale for this (e.g. do a variety of different column summaries one after the other on the same data set), but the behavior is unintuitive.

**Comment by Patowhiz** [comment]
@rdstern @dannyparsons this relates to our email conversation.

My quote

> When a user changes the selected sheet, it’s hard for them to notice that the dialogs are not using the selected sheet data frame. I think it will be good to show a red warning just beside the selector, just to notify the user.

@dannyparsons response quote

> This was also pointed out by Bob. But we like dialogs opening as they were closed. I like your idea of some kind of indication when the grid sheet is different from the dialog selected sheet - a red warning might be too much, but I think the general idea.

I think the conversation on the way forward can proceed here.

**Comment by Patowhiz** [comment]
@rdstern I'm now looking into this.

**Comment by Patowhiz** [comment]
@rdstern in  https://github.com/africanmathsinitiative/R-Instat/issues/7304#issuecomment-1077362079 says

> @Patowhiz on this issue, and as someone who has often done the analysis on the wrong data frame, because I had forgotten to change it, I still roughly repeat my comment from #4712. This is that I also like our simple rule that the dialogue "remembers" its previous settings. They include the original data frame when it was last used. Of course, if that data frame has been deleted, (or renamed?) then things might be different. But otherwise I am ok that it remembers. I sometimes look at a dialogue without a dataframe present. Then I open a data frame. Then I return to the dialogue, and there is no data frame there, because there wasn't the first time. I am even happy with this. But I would quite like to be alerted when my current data frame that I am looking at, is different from the one I last used in the dialogue. Currently we alert users to the presence of a filter (or select) by putting row numbers in red. Perhaps we could do the same with the data frame name? Or, just put it in bold, or italic, or something?
