### ISSUE TITLE
Small changes in the Prepare > Check Data > Duplicates dialogue 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7299]
1. Could the name of the dialogue be Duplicate Rows.  That is at the top of the dialogue and hopefully also the Menu item (unless that should wait for other changes to the menus - see #7297 .
2. The most used option is the second, namely Selected Variables.  So could that become the first button, and hence the default when you first use the dialogue.  The Data Frame is then second.  The Successive values remains the last button.
3. In the 3rd radio button below the selector, the label i Index Number of Duplicates.  Then the pull down has the first entry as Count.  Please swap them, so the first entry is Index.
4. Currently this control doesn't "remember" the setting when you return to the dialogue.  Could it please remember.

@shadrackkibet who can do these.  It should only taker a few minutes?

**Comment by derekagorhom** [comment]
@rdstern we looked into this issue with @Patowhiz  and we also realized that the dialog is producing duplicate R commands. I wonder if this was intentional.

What the dialog produces;
```
# Code generated by the dialog, Duplicate Rows

dup <- duplicated_count_index(x=data_book$get_columns_from_data(data_name="date_example", col_names="week", use_current_filter=FALSE), type="index")
data_book$add_columns_to_data(data_name="date_example", col_name="dup", col_data=dup, before=FALSE, adjacent_column="week")

dup <- data_book$get_columns_from_data(data_name="date_example", col_names="dup")
data_book$add_columns_to_data(data_name="date_example", col_name="dup", col_data=dup, before=FALSE, adjacent_column="week")
summary(object=data_book$get_columns_from_data(data_name="date_example", col_names="dup"))
rm(list=c("dup", "dup"))
```

What we think it should be producing;
```
# Code generated by the dialog, Duplicate Rows

dup1 <- duplicated_count_index(x=data_book$get_columns_from_data(data_name="date_example", col_names="week", use_current_filter=FALSE), type="index")
data_book$add_columns_to_data(data_name="date_example", col_name="dup1", col_data=dup1, before=FALSE, adjacent_column="week")
summary(object=data_book$get_columns_from_data(data_name="date_example", col_names="dup1"))
rm(list=c("dup1", "dup1"))
```

If the current duplicated R commands is not correct, should we correct it in PR #7305 or in a new PR?
