### ISSUE TITLE
Problem when running 64 bit?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7301]
@shadrackkibet @Patowhiz does anyone else get this problem with the master version.

I have been running the current Any CPU and this has been working fine.  But I prefer 64 bit, so changed to that option.  Now I get:

![image](https://user-images.githubusercontent.com/11226469/158168349-7b8010eb-22f9-470d-a7d4-e01ab105866b.png)
This is at the bottom of the screen and the message above comes repeatedly.

When I change back to Any CPU I am ok again!

**Comment by shadrackkibet** [comment]
@rdstern try the following.

Navigate to the `bin` folder and delete it then try again.

For example, my `bin` folder is in the following path.

`C:\Users\SHADRACK\Source\Repos\R-Instat\instat\bin`

**Comment by rdstern** [comment]
@shadrackkibet magic - seems ok now.  Many thanks

**Comment by Patowhiz** [comment]
@rdstern R-Instat now also relies on other libraries, for instance SQLite. Changing the preferred platform architecture (32 bit or 64 bit) requires you to also use the appropriate library architecture target. Not doing so results to such errors.

@rdstern I think you can now close this issue. Thanks.
