### ISSUE TITLE
Confirm and correct error in Non-numeric dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7310]
We are now just about complete in our use of factors and labels in R-Instat.  This is making it easy to transform data between character, factor and numeric.
When you make a factor (or character?) into a numeric variable and it has some non-numeric values, then it invites you to check, and that loads the Prepare > Check Data > Non-Numeric Values dialogue.
a) Now that dialogue currently only accepts character variables, but it accepts a factor from this route.  So my first suggestion is that it should accept factors generally as well as character variables.
b) Here is an example where it seems to me to get the answer wrong for a factor.  And it is different for the factor and the character variable.  
1. With the usual survey data, make fert into a factor.  Then, with Levels/Labels make 0 into None and 3 into Max. 
2. Now try to make it numeric and it notes that 12 values are not-numeric.
3. Click to check, and it goes to the Nonum dialogue.
4. Accept and the result is FALSE for all rows!  That's wrong - it just said 12 values are not numeric!
5. Make fert into character
6. Try nonum again - and it gives the correct answer.  12 values are non-numeric.

@shadrackkibet please confirm that I am right here.  This anomaly needs to be corrected.  
Assuming so, please can @N-thony make the correction.  @shadrackkibet may give the R-code, but it should be evident, because it is detected in the popup when I tried to make the factor numeric (but that code isn't in the results window.)

**Comment by shadrackkibet** [comment]
@N-thony this can be simply solved by changing the `function_exp` parameter to `function_exp="is.na(as.numeric(as.character(x=fert)))"`. Please check that it works in general otherwise you could do this only when a column is a `factor`.

Perhaps it is safer to use `function_exp="is.na(fert) != is.na(as.numeric(as.character(x=fert)))"`. We rely on coarsion here which is dangerous!

**Comment by rdstern** [comment]
Thanks @shadrackkibet for the R code.
