### ISSUE TITLE
Controlling the numerical display in grid controls 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7316]
This has come because of the new contrasts dialogue.  It is now looking great as a teaching tool.  I record here a particular improvement that would also be useful.
In addition this is an example of a dialogue where we would like to press Ok and then look at the dialogue again.  We can always get last dialogue, but it would be even better if we could opt to keep it open.  That's issue #7180 

Here I would like to be able to set the precision of values in a grid.  Even in the masin grid, we don't (I think) have an easy option for displaying variables with a fixed number of decimals.  3 is usually perfect for polynomials in contrasts. 
![image](https://user-images.githubusercontent.com/11226469/158767878-91832b3b-2733-4426-ad07-64dfc8445a61.png)
 
The Factor Data Frame has the same issue in an ordinary grid.

What can we do? 

This might usefully be a @dannyparsons question. to start with.  It isn't urgent.

**Comment by N-thony** [comment]
> This has come because of the new contrasts dialogue. It is now looking great as a teaching tool. I record here a particular improvement that would also be useful. In addition this is an example of a dialogue where we would like to press Ok and then look at the dialogue again. We can always get last dialogue, but it would be even better if we could opt to keep it open. That's issue #7180
> 
> Here I would like to be able to set the precision of values in a grid. Even in the masin grid, we don't (I think) have an easy option for displaying variables with a fixed number of decimals. 3 is usually perfect for polynomials in contrasts. ![image](https://user-images.githubusercontent.com/11226469/158767878-91832b3b-2733-4426-ad07-64dfc8445a61.png)
> 
> The Factor Data Frame has the same issue in an ordinary grid.
> 
> What can we do?
> 
> This might usefully be a @dannyparsons question. to start with. It isn't urgent.

@rdstern is this okay? I have fixed number of decimals to 3.
![image](https://user-images.githubusercontent.com/68591383/159855539-b8f67774-c758-42f5-8b70-c6d43ff3327d.png)

**Comment by rdstern** [comment]
@N-thony that looks perfect.  I would like to check also with simple examples, like -1, 1, 0 0.  They should remain as simple integers

**Comment by anastasia-mbithe** [comment]
@rdstern, can we close this issue since it was fixed in PR #7411 ?

**Comment by N-thony** [comment]
@anastasia-mbithe you are right.
