### ISSUE TITLE
Issues in the Prepare>Date>Make Date dialog 

### ISSUE THREAD

**Issue by anastasia-mbithe** [africanmathsinitiative/R-Instat#7319]
@Patowhiz and I have been looking at the Prepare >Make Date Dialog, specifically the Year and day of the Year option.
We noticed 3 issues;
1. The dialog positions the new column at the end of the dataset instead of after the date of the year column. 
2. The cut-off up down control does not reset back to 0(current original value).
3. The selector should allow only numeric variables since the option only accepts numeric variables as Year or day of the year.

@rdstern are the 3 issues intentionally implemented that way or they are just bugs.

@rdstern, I do not understand the cut-off concept, suppose we have 2 digit year column(yy) of values 0-90 and we intend to make a 4 digit year column(yyyy) from 1900 to1990, what will be the cut off then? And what about if we want from year 2000 to 2090.

**Comment by N-thony** [comment]
I also notice that when you click the `Origin radio button` under the `Single Column` option, it opens pull-down control without a default value.
![image](https://user-images.githubusercontent.com/68591383/159850702-2142453a-b5f5-4dd4-90d2-39f2f720006f.png)

**Comment by N-thony** [comment]
I think the observations are correct, @anastasia-mbithe can you try to solve those 4 points raised above?Thanks.

**Comment by anastasia-mbithe** [comment]
@rdstern, what should be the cut-off for 2000 in this dialog, while making a two digit year?
