### ISSUE TITLE
Two small improvements to the Prepare > Data Frame > Row Numbers/Names dialogue 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7323]
This is a simple task and should only take a few minutes I hope.
1) The first option says Copy Row Names into Column.  Change this into `Copy Row Numbers or Names into a Column`
2) Move the other options down, so there is room for a checkbox for this option.
3) Add a checkbox (default checked) with label Make the Column into a Key for the data Frame.

When checked it runs the same code as in the Prepare > Keys and Links and also prints the information in the output window, as is done when you run the Keys dialogue with that column.

(To see what's needed take any data frame (e.g. mtcars from the datasets.  Then run the current Row Numbers/Names dialogue and then the Prepare > Keys and Links > Make Key dialogue and make the row variable into a key.  (With our new "system" we will avoid that step.
@shadrackkibet who should be doing this?

**Comment by anastasia-mbithe** [comment]
@rdstern Should I link the new checkbox (add key) to the first radio button only? Since its the only one creating a new column.

**Comment by rdstern** [comment]
@anastasia-mbithe that's right.  It is only needed for the first option
