### ISSUE TITLE
Possibly corrected feature in PICSA graphs has resurfaced

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7332]
Here it is:  I thought this was fixed ages ago?  It is an extremely annoying bug, because we are getting reasonable statistics wrong.  

![image](https://user-images.githubusercontent.com/11226469/160344270-97a907a2-bbcf-4fed-8b17-b5770db4ef34.png)

Here is another example:

![image](https://user-images.githubusercontent.com/11226469/160344733-7d7e37c9-f88d-4d85-b8ac-fc94b0939250.png)

I checked with the development version (above was earlier, in case we have introduced this:

![image](https://user-images.githubusercontent.com/11226469/160347850-520c6448-b95b-4454-b43e-cedbaea0f572.png)

**Comment by N-thony** [comment]
@rdstern I will have a look of this.

**Comment by N-thony** [comment]
@rdstern I have been looking into this then I found that when we were running the code for both Facets option `row` or `column` we were missing to add  `dplyr::group_by(station)` that is why result was still the same.

ChomaChipata_merged_by_station_s_year <- data_book$get_data_frame(data_name="ChomaChipata_merged_by_station_s_year")
ChomaChipata_merged_by_station_s_year <- ChomaChipata_merged_by_station_s_year %>% dplyr::group_by(station) %>% dplyr::mutate(.median_y=median(x=sum_Rain, na.rm=TRUE))
last_graph <- ggplot2::ggplot(data=ChomaChipata_merged_by_station_s_year, mapping=ggplot2::aes(y=as.numeric(x=sum_Rain), colour=station, x=s_year)) + ggplot2::geom_line(size=0.8) + ggplot2::geom_point(size=3, colour="red") + ggplot2::geom_hline(mapping=ggplot2::aes(yintercept=.median_y), size=1.5) + ggplot2::geom_label(mapping=ggplot2::aes(x=-Inf, y=.median_y, label=paste("Median:", round(.median_y))), hjust=0, vjust=-0.3) + ggplot2::theme(panel.grid.major=ggplot2::element_line(colour="lightblue", linetype="longdash", size=1), panel.grid.minor=ggplot2::element_line(colour="lightblue", linetype="longdash", size=1), panel.border=ggplot2::element_rect(colour="black", fill="NA", size=0), axis.text.x=ggplot2::element_text(angle=90, size=12, vjust=0.4), axis.title.x=ggplot2::element_text(size=14), axis.title.y=ggplot2::element_text(size=14), title=ggplot2::element_text(size=20), plot.subtitle=ggplot2::element_text(size=15), plot.caption=ggplot2::element_text(size=8), axis.text.y=ggplot2::element_text(size=12), panel.background=ggplot2::element_rect(colour="white", fill="white", size=0.5, linetype="solid")) + ggplot2::xlab(label="") + ggplot2::ylab(label="") + ggplot2::facet_grid(facets=. ~ station)
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="ChomaChipata_merged_by_station_s_year")
data_book$get_graphs(data_name="ChomaChipata_merged_by_station_s_year", graph_name="last_graph")
rm(list=c("last_graph", "ChomaChipata_merged_by_station_s_year", "ChomaChipata_merged_by_station_s_year"))
