### ISSUE TITLE
Error when I import SPSS data

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#7337]
I get the error in the screenshot below when I try importing spss data. Please note this error was not there just a few days ago.

The data
[ZZHR62FL.zip](https://github.com/africanmathsinitiative/R-Instat/files/8372183/ZZHR62FL.zip)

The error
![import_error](https://user-images.githubusercontent.com/21179007/160629799-d452f83c-1b03-4e1e-9235-0497fcee0404.PNG)

**Comment by Patowhiz** [comment]
@rdstern @lloyddewit @shadrackkibet 
This bug is a fairly recent addition. And it may have affected other places as well. 
I have traced it to `append_to_variables_metadata` function which is called in numerous places.

Error stack trace
```
Error in if (property == labels_label && new_val == "") { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In self$set_data(data, messages) :
  Not all column names are syntactically valid. make.names() and iconv() will be used to force them to be valid.
2: NAs introduced by coercion 
3: In self$add_defaults_variables_metadata(self$get_column_names()) :
 
 Error in if (property == labels_label && new_val == "") { : 
  missing value where TRUE/FALSE needed 
```

Old Function
```
DataSheet$set("public", "append_to_variables_metadata", function(col_names, property, new_val = "") {
  if(missing(property)) stop("property must be specified.")
  if(!is.character(property)) stop("property must be a character")
  if(!missing(col_names)) {
    #if(!all(col_names %in% self$get_column_names())) stop("Not all of ", paste(col_names, collapse = ","), " found in data.")
    if(!all(col_names %in% names(private$data))) stop("Not all of ", paste(col_names, collapse = ","), " found in data.")
    for(curr_col in col_names) {
      attr(private$data[[curr_col]], property) <- new_val
      self$append_to_changes(list(Added_variables_metadata, curr_col, property))
    }
  }
  else {
    for(col_name in self$get_column_names()) {
      attr(private$data[[col_name]], property) <- new_val
    }
    self$append_to_changes(list(Added_variables_metadata, property, new_val))
  }
  self$variables_metadata_changed <- TRUE
  self$data_changed <- TRUE
}
)
```

New Function
```
DataSheet$set("public", "append_to_variables_metadata", function(col_names, property, new_val = "") {
  if (missing(property)) stop("property must be specified.")
  if (!is.character(property)) stop("property must be a character")
  if (!missing(col_names)) {
    # if(!all(col_names %in% self$get_column_names())) stop("Not all of ", paste(col_names, collapse = ","), " found in data.")
    if (!all(col_names %in% names(private$data))) stop("Not all of ", paste(col_names, collapse = ","), " found in data.")
    for (curr_col in col_names) {
      if (property == labels_label && new_val == "") {
        attr(private$data[[curr_col]], property) <- NULL
      } else {
        attr(private$data[[curr_col]], property) <- new_val
      }
    }
    self$append_to_changes(list(Added_variables_metadata, curr_col, property))
  } else {
    for (col_name in self$get_column_names()) {
      if (property == labels_label && new_val == "") {
        attr(private$data[[col_name]], property) <- NULL
      } else {
        attr(private$data[[col_name]], property) <- new_val
      }
    }
    self$append_to_changes(list(Added_variables_metadata, property, new_val))
  }
  self$variables_metadata_changed <- TRUE
  self$data_changed <- TRUE
})
```

Notice where 
`self$append_to_changes(list(Added_variables_metadata, curr_col, property))` has been added in the new function? Clearly misplaced.

And also the code line check ` if (property == labels_label && new_val == "")`  is a recent addition which I struggled to understand what it's doing.

@rdstern @shadrackkibet do you have an idea about which issue relates to the addition of these lines?

**Comment by rdstern** [comment]
@Patowhiz good to discuss with @N-thony.  We have been trying to sort out labelling v factors in datasets, and I thought had been making progress.  BHut it seems at a heavy price.  Good spot!  SPSS produces labelled data when imported, so it is possible that that has been affected.

Just the sort of problem we usually spot after a new version is released.  It could be a good example to both correct and improve a bit on both documentation and working practices at the same time.

**Comment by N-thony** [comment]
> @Patowhiz good to discuss with @N-thony. We have been trying to sort out labelling v factors in datasets, and I thought had been making progress. BHut it seems at a heavy price. Good spot! SPSS produces labelled data when imported, so it is possible that that has been affected.
> 
> Just the sort of problem we usually spot after a new version is released. It could be a good example to both correct and improve a bit on both documentation and working practices at the same time.

@rdstern you are right, and also very carefully on reviewing the code. @Patowhiz thanks for the spot, this error was introduced in #7247 by `self$append_to_changes(list(Added_variables_metadata, curr_col, property))`, hopefully now we fixed it as disucssed. :)

**Comment by Patowhiz** [comment]
More updates.

I've traced the error to the `new_val` argument. That additional check of  new_val == "" is the source of the error `missing value where TRUE/FALSE needed`. 

For some reasons, which I don't know and according to the code its shouldn't, the argument at times has length zero and yet it's never missing. I've confirmed it's never missing (it shouldn't anyway because it has default value set on it).

**Comment by Patowhiz** [comment]
@rdstern @N-thony Now I fully understand the source of the problems.

We actually do have places that do `append_to_variables_metadata(new_val = NULL)`. 
So doing  `if( new_val == "" )` like in this case will definitely throw `missing value where TRUE/FALSE needed`.

I think this is not easy to spot as it required checking several areas where this function is called (and it's in many places).
Solution is to just include a NULL check in that function.

Thanks

**Comment by N-thony** [comment]
> @rdstern @N-thony Now I fully understand the source of the problems.
> 
> We actually do have places that do `append_to_variables_metadata(new_val = NULL)`. So doing `if( new_val == "" )` like in this case will definitely throw `missing value where TRUE/FALSE needed`.
> 
> I think this is not easy to spot as it required checking several areas where this function is called (and it's in many places). Solution is to just include a NULL check in that function.
> 
> Thanks

@Patowhiz nice, something like  ` if (property == labels_label && is.null(new_val))` should work?
