### ISSUE TITLE
Extend select when data has value labels

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7340]
Now I know why the sj packages includes searching in value labels.  I am afraid we need it in select.  @shadrack, it will become clear when you look at the SPSS data I sent in skype.
These data are excellent candidates for select, because there are quite a number of variables.  Some are labelled.  I was assuming the labelled variables would be the ones that become factors.  It is still important to be able to choose those variables with value labels.  But we need to go further, because some numeric variables, like age, are also labelled.  For example BH4Y Variable Label (Year of birth) also has value labels  `Inconsistent = 9997,  NO RESPONSE = 9999`

So I would like to be able to select variables with value labels that contain "NO RESPONSE" say!  

Interesting!

**Comment by shadrackkibet** [comment]
It is easy to extend the selection to include a value label. We can have a checkbox that opens up input to type the text.
