### ISSUE TITLE
Small addition needed in the Prepare > Column: Factor > View/Delete Labels dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7341]
This should be a very simple task.  @shadrack to allocate.

It is on the View button:

It is a 4th option in the Display Options group.  That box can start higher, then add another checkbox at the bottom, default unchecked.  The label is `Max Labels:`.  If checked it opens an updown with default 15.  It can go up or down in integer jumps.  I assume down to 1, but try and check.  Can use MICS survey data.  If checked, then it adds max.len = value to the command.

**Comment by shadrackkibet** [comment]
@anastasia-mbithe this is an easy one to add. Let us know here if you experience any challenges.
