### ISSUE TITLE
New bug in regular sequence dialogue?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7359]
Am I right?  I thought this was (at last working fine?
I think @Patowhiz fixed this dialogue, but perhaps @N-thony can check whether I am right about this bug.
[survey for merge.zip](https://github.com/africanmathsinitiative/R-Instat/files/8424141/survey.for.merge.zip)
This is the file I prepared to check a merge dialogue.  Here are the steps I took:
a) In survey1, which is of length 34
b) Go into Prepare > Numeric > Regular Sequence
c) Make the 34 into 6.  It now says it will extend the sequence.
d) Press Ok.  It works fine
e) I now realise I meant to use survey (which is of length 36). So go back to the dialogue and change to survey data frame.
f) Oh, it still thinks that survey is of length 34.
g) No matter I'll press Reset.  Well that changes my 6 to 34, but still thinks the data frame is of length 34?
h) So, give in an press Ok - this gives the old error that the recent correction was supposed to resolve!!!
i) Now go back to survey 1 (length 34) and press reset.  Now it does a proper reset, but takes me back to the survey data frame.  Now it recognises the 36!
j) I insist on survey1 and go back and put my 6 back.  It worked before, but now it insists there are 36 there and doesn't work anymore!

**Comment by N-thony** [comment]
> Am I right? I thought this was (at last working fine? I think @Patowhiz fixed this dialogue, but perhaps @N-thony can check whether I am right about this bug. [survey for merge.zip](https://github.com/africanmathsinitiative/R-Instat/files/8424141/survey.for.merge.zip) This is the file I prepared to check a merge dialogue. Here are the steps I took: a) In survey1, which is of length 34 b) Go into Prepare > Numeric > Regular Sequence c) Make the 34 into 6. It now says it will extend the sequence. d) Press Ok. It works fine e) I now realise I meant to use survey (which is of length 36). So go back to the dialogue and change to survey data frame. f) Oh, it still thinks that survey is of length 34. g) No matter I'll press Reset. Well that changes my 6 to 34, but still thinks the data frame is of length 34? h) So, give in an press Ok - this gives the old error that the recent correction was supposed to resolve!!! i) Now go back to survey 1 (length 34) and press reset. Now it does a proper reset, but takes me back to the survey data frame. Now it recognises the 36! j) I insist on survey1 and go back and put my 6 back. It worked before, but now it insists there are 36 there and doesn't work anymore!

@rdstern you are right, I'm able to reproduce this. I think the control are not updating the R code correctly.
