### ISSUE TITLE
Issues with ucrInputs events

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#7367]
`ucrInput`    
This custom control has redundant event `ContentsChanged` which is already part of `ucrCore` as `ControlContentsChanged`. References to `ContentsChanged` should be removed to avoid future confusion at dialog and other custom controls level. For instance dialogs using  `ucrInputTextBox` can just listen to `ControlContentsChanged`.

`ucrInputTextBox` 
This control doesn't raise `ControlValueChanged` when `TextChanged` event of it's textbox is raised. 
It only raises `NameChanged` when event Validating is raised which in turn raises `ControlValueChanged`. 
This is contrary to ucrReceiverSingle which raises `ControlValueChanged` when `TextChanged`.  Should we make them be consistent? the both use TextBox control for inputs.

Same applies to `ucrInputComboBox` control, it only raises  `OnControlContentsChanged` when event cboInput.TextChanged is raised

**Comment by Patowhiz** [comment]
@lloyddewit your suggestions on this issue will be highly appreciated.

**Comment by rdstern** [comment]
@Patowhiz what do I test here?

**Comment by lloyddewit** [comment]
> @Patowhiz what do I test here?
@rdstern I responded in PR #7368

**Comment by lloyddewit** [comment]
> @lloyddewit your suggestions on this issue will be highly appreciated.

Happy to give feedback. I'll do this when I review PR #7368
