### ISSUE TITLE
File export as a single file is always available?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7379]
Here is an example:
![image](https://user-images.githubusercontent.com/11226469/163668137-80f61fe7-4717-49ce-aff5-a0d939567e2d.png)

I can export multiple data frames in a wide variety of formats and the option to export as a single file seems always available?  Is this true, or only for Excel?  For other formats, like csv or SPSS I assume I would get multiple files?

**Comment by Patowhiz** [comment]
@rdstern click on the  **Save as single file** checkbox and see what happens. I think that will answer your question.
The checkbox option  is the one that determines what file types will be available for single files.

Remember, originally we designed this form to do that automatically. But later it was generally agreed that was not the preferred design.

**Comment by rdstern** [comment]
@Patowhiz   Aha - thanks.  I can write the help now!

**Comment by Patowhiz** [comment]
So you can close this issue.
