### ISSUE TITLE
Add (Merge) Columns has problem with example for the Help

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7382]
The data are 3 files from the climdex.pcic package.  They are 3 separate elements.  The longest is tmin, so add the others to that.
This works fine with the left-join in the ordinary merge, but gives an error in this dialogue. 
![image](https://user-images.githubusercontent.com/11226469/163684494-91e5787e-017d-48aa-a60b-2cbc3ce76208.png)

I would like to merge the flag field as well, but that's an option.  It is not needed, and should be deleted from the joining variables as shown above.  When merging I get:
![image](https://user-images.githubusercontent.com/11226469/163684530-31890f70-296e-4a58-b0fe-3be0c8b84622.png)

As mentioned, the left join works fine in the usual merge dialogue and does just what I think this dialogue should do.

**Comment by N-thony** [comment]
@rdstern that is correct, the two datasets don't have the same legngth therefore for it to work you needed just to check `New Data Frame` to create a new dataframe see screenshot below and it works fine. I will add a check for the length in this case a give a message if the length is not the same to check `New Data Frame`
![image](https://user-images.githubusercontent.com/68591383/163686703-78b722a6-0c6a-4b0f-ba80-deb2f8ef4459.png)

**Comment by rdstern** [comment]
No it should still work with a left join.  That's why the example we used before had 2 observations missing in the second data, i.e. was only of length 34.
