### ISSUE TITLE
Something seems changed in the filter system?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7384]
In the merged version the filter system doesn't seem to work.
a) When I do filter from Factor, say using Village from the survey data, it doesn't work in that none of the villages are then defined as filters - I selected all the villages and it all works fine in Version 0,7.4.
b) When I define a filter, then it does work, and the filter is made correctly.  But it isn't saved as a filter.  So, if I delete the operation of the filter, then it isn't there to redo next time.

**Comment by N-thony** [comment]
> In the merged version the filter system doesn't seem to work. a) When I do filter from Factor, say using Village from the survey data, it doesn't work in that none of the villages are then defined as filters - I selected all the villages and it all works fine in Version 0,7.4. b) When I define a filter, then it does work, and the filter is made correctly. But it isn't saved as a filter. So, if I delete the filter, then it isn't there to redo next time.

I'm looking at this.

**Comment by N-thony** [comment]
@rdstern this problem is more general, it was introduced in PR #7322. It happens when the dataset is updated (deleting or adding a column to the dataframe) for example with adding column you can try to recode factor variable with `Recode Factor dialogue` it will create a `new recoded column` and when you reopen the dialogue, the `new recoded column` is not listed in the selector, same when you delete a column from the `Data View`.

**Comment by N-thony** [comment]
> @rdstern this problem is more general, it was introduced in PR #7322. It happens when the dataset is updated (deleting or adding a column to the dataframe) for example with adding column you can try to recode factor variable with `Recode Factor dialogue` it will create a `new recoded column` and when you reopen the dialogue, the `new recoded column` is not listed in the selector, same when you delete a column from the `Data View`.
Here is another example
![image](https://user-images.githubusercontent.com/68591383/163807150-84cb89ab-7618-489b-b4ae-7cfc5930f39d.png)

**Comment by N-thony** [comment]
@Patowhiz could you look into this since you worked on #7322?

**Comment by Patowhiz** [comment]
@N-thony okay.

**Comment by Patowhiz** [comment]
@rdstern I think this can be closed now. It was fixed by PR #7393 which has been merged.

**Comment by Patowhiz** [comment]
Oh! It's now closed. Thanks.
