### ISSUE TITLE
Problem refreshing the selector when new variables are produced?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7396]
@Patowhiz I think this is general, but here is the example I used.
a) Opened sentences data from the stringr package.  
b) Used Prepare > Column: Text > Find/Replace and 
c) Option replace and replace a by z.  Used option replace All.  So got another character variable.
d) Wanted to do more on the new variable, but it isn't in the selector.  Try as I might, I can't get it into the selector, when just that data frame is open.
e) Open another data frame.  I used survey, but I think anything will do.
f) Back to the Find/Replace dialogue and change to the new data frame.  Don't need to do anything, except go back to the old data frame.
g) Now it is ok.  I have the new variable available.

**Comment by Patowhiz** [comment]
@rdstern I think this was fixed in PR #7393, which has now been merged. Could you try testing this with the latest changes in the master.

If it's been fixed then I think this issue can now be closed.

**Comment by rdstern** [comment]
@Patowhiz yes it seems to be resolved.  Great.  Closing!
