### ISSUE TITLE
Minor changes in the Prepare > Column: Text > Transform dialogue?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7398]
These are just cosmetic changes and I would like discussion, by one or two developers, even though they are trivial to do.  Perhaps @lilyclements could consider with whom?

a) I use this dialogue regularly, but the only option I have used is the last - namely Substring.  We seem to have an informal convention that the initial top radio button is the one on the left.  I am not sure we need that convention?  If you agree, we don't need it, then perhaps we could have Substring as the default.  If we keep to the convention, then perhaps move Substring to be the button on the left?
b) The dialogue is wide, purely because of the size of the top buttons.  Most of the other options are pretty trivial compared to our usual use of this top-radio-button feature in R-Instat.  Could (most of) the other buttons be made smaller, so the dialogue can be made considerably smaller - i.e. not so wide.

**Comment by derekagorhom** [comment]
hello @rdstern can i work on this?
