### ISSUE TITLE
Another small bug when trying to delete a dataframe from Data View window

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7400]
This bug occurs when trying to delete a data frame from the Data View Window. You can try with any dataset.
Right click on the dataframe name from the Data View window as shown in screenshot below, and then click Delete
![image](https://user-images.githubusercontent.com/68591383/164644107-3bf3fbfa-1c57-4c49-af70-15ffce0b6c69.png)
Then you get this error
![image](https://user-images.githubusercontent.com/68591383/164644338-604efe7b-a695-4944-8a96-762b9dbf1dda.png)
I suspect that this bug is introduced with the new change made in the `ucrSelector`

**Comment by N-thony** [comment]
> This bug occurs when trying to delete a data frame from the Data View Window. You can try with any dataset. Right click on the dataframe name from the Data View window as shown in screenshot below, and then click Delete ![image](https://user-images.githubusercontent.com/68591383/164644107-3bf3fbfa-1c57-4c49-af70-15ffce0b6c69.png) Then you get this error ![image](https://user-images.githubusercontent.com/68591383/164644338-604efe7b-a695-4944-8a96-762b9dbf1dda.png) I suspect that this bug is introduced with the new change made in the `ucrSelector`. @Patowhiz can you look at it?

**Comment by Patowhiz** [comment]
yes thanks.
