### ISSUE TITLE
Small correction and code check on Column: Text > Distance dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7405]
The small correction is that the Method control currently doesn't remember its previous setting.  
I understand you may also be checking the quality of the code.  Here is an example where I wonder if the R code can be improved?  That should probably involve discussion.
Most dialogues seem to generate code in 3 parts:
a) getting the data frame, or the variables from the data book.
b) Doing something on them - here stringdist
c) Doing something with the results

Here is an example where a) and b) are done together and (to me) that makes for complicated R code.  Perhaps this could be examined?

**Comment by lilyclements** [comment]
@anastasia-mbithe why is this in "blocker"?

**Comment by anastasia-mbithe** [comment]
@rdstern, We can close this. The first part was fixed in #7419. For the second part, we couldn't recreate the bug, and the code works fine.

**Comment by anastasia-mbithe** [comment]
I am closing this since it was fixed in #7419
