### ISSUE TITLE
Should we rename the use graph menu/dialog to Rename graph?

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#7418]
@rdstern I looked into the **Use Graph** dialog, and the main functionality that makes it different from **View Graph** is it's ability to rename the graph. 

Shouldn't we just name it **Rename Graph**? 
The word use graph to me, meant like I want to use the graph, as it is, for other functions like combine it with others etc.

**Comment by Vitalis95** [comment]
@rdstern, Can I rename the graph?
I can do this task

**Comment by rdstern** [comment]
@Patowhiz I am closing this issue, which we discussed.  We agreed it is not rename graph, but indeed it is correctly a Use graph!  It was a good discussion!
