### ISSUE TITLE
Minor bug with the Prepare>Data Frame>Rename Columns Dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7422]
In the Rename Column Dialogue, under Multiple option, `OK button` seems to still be disabled though the grid is filled as shown in the screenshot below
![image](https://user-images.githubusercontent.com/68591383/165487444-94f259ec-d586-4178-a394-9489cdc72f5a.png)

@derekagorhom  can you have a look at it?

**Comment by derekagorhom** [comment]
@N-thony i am having problems implementing  the Contains function to check if the column name contains any spaces
