### ISSUE TITLE
Bug in ucrBase - "Ok" and "To Script" repeated

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#7428]
The "OK" and "To Script" words on the ucrBase are repeated (see image below)

<img width="336" alt="image" src="https://user-images.githubusercontent.com/21180424/165750357-f13e56bc-7246-41c1-bfbc-28b84ad0292a.png">

**Comment by Ivanluv** [comment]
This seems to be fixed

**Comment by shadrackkibet** [comment]
@lilyclements can you confirm then we can close?
