### ISSUE TITLE
Error Message when running code for the Summary table

### ISSUE THREAD

**Issue by Ivanluv** [africanmathsinitiative/R-Instat#7446]
When running the Summary table code, I seem to be getting an error that was previously not there.
@lilyclements I wonder whether this could this be from the changes we have made in the `summary_ table` function?
Am using the survey dataset in this illustration
![image](https://user-images.githubusercontent.com/45068931/166681986-1bbfd080-bbd2-4150-8b52-e9436f9d6987.png)

![image](https://user-images.githubusercontent.com/45068931/166682062-e7888e30-8ecd-48a1-8cf1-87b7076c61de.png)

![image](https://user-images.githubusercontent.com/45068931/166682178-c321dddb-e3d0-4989-b509-abd4b812bec1.png)

**Comment by lilyclements** [comment]
@Ivanluv I have made the fixes so it is ready to review in #7463. The issue occurred from fixing the conflicts last week after this file was edited on multiple branches. In future, when there are R code changes we should merge it into the master branch, and then update your branch (as oppose to merge into your branch)
