### ISSUE TITLE
Mapping problem

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7448]
@lloyddewit This is (I think) another example of the same error you have fixed elsewhere?

It occurs when you produce a map and then try to add facets - bottom right.

![image](https://user-images.githubusercontent.com/11226469/166685150-7858dd25-d7cd-47df-8efe-6e506d0dd9f7.png)

It crashes out with the code below:

# Code generated by the dialog, Climatic Maps
gadm36_GHA_1 <- data_book$get_data_frame(data_name="gadm36_GHA_1")
GMet_Stn_corrected <- data_book$get_data_frame(data_name="GMet_Stn_corrected")
last_map <- ggplot2::ggplot() + ggplot2::geom_sf(data=gadm36_GHA_1, mapping=ggplot2::aes()) + theme_grey() + ggplot2::geom_point(data=GMet_Stn_corrected, mapping=ggplot2::aes(x=Lon, y=Lat)) + ggplot2::facet_wrap(dir="h", facets=,  ~ Station.Type) + ggrepel::geom_label_repel(data=GMet_Stn_corrected, mapping=ggplot2::aes(x=Lon, y=Lat, label=abbr))
data_book$add_graph(graph_name="last_map", graph=last_map, data_name="gadm36_GHA_1")
data_book$get_graphs(data_name="gadm36_GHA_1", graph_name="last_map")

@Patowhiz has shown me how to get round this and get the required results.  They are without the command, which is ok!

![image](https://user-images.githubusercontent.com/11226469/166685466-433fcf09-e0aa-462f-852d-7610a4ffe44f.png)

I hope this can be fixed, as were the others, but he also plans to (temporarily) catch this situation, if there are other instances, so the don't crash out during the courses.

**Comment by N-thony** [comment]
> @lloyddewit This is (I think) another example of the same error you have fixed elsewhere?
> 
> It occurs when you produce a map and then try to add facets - bottom right.
> 
> ![image](https://user-images.githubusercontent.com/11226469/166685150-7858dd25-d7cd-47df-8efe-6e506d0dd9f7.png)
> 
> It crashes out with the code below:
> 
> # Code generated by the dialog, Climatic Maps
> gadm36_GHA_1 <- data_book$get_data_frame(data_name="gadm36_GHA_1") GMet_Stn_corrected <- data_book$get_data_frame(data_name="GMet_Stn_corrected") last_map <- ggplot2::ggplot() + ggplot2::geom_sf(data=gadm36_GHA_1, mapping=ggplot2::aes()) + theme_grey() + ggplot2::geom_point(data=GMet_Stn_corrected, mapping=ggplot2::aes(x=Lon, y=Lat)) + ggplot2::facet_wrap(dir="h", facets=, ~ Station.Type) + ggrepel::geom_label_repel(data=GMet_Stn_corrected, mapping=ggplot2::aes(x=Lon, y=Lat, label=abbr)) data_book$add_graph(graph_name="last_map", graph=last_map, data_name="gadm36_GHA_1") data_book$get_graphs(data_name="gadm36_GHA_1", graph_name="last_map")
> 
> @Patowhiz has shown me how to get round this and get the required results. They are without the command, which is ok!
> 
> ![image](https://user-images.githubusercontent.com/11226469/166685466-433fcf09-e0aa-462f-852d-7610a4ffe44f.png)
> 
> I hope this can be fixed, as were the others, but he also plans to (temporarily) catch this situation, if there are other instances, so the don't crash out during the courses.
@Patowhiz you have added the condition to prevent this bug and I think this is more general however the problem is still there, if you observe the `R code` above, you will find that there is a problem in  `ggplot2::facet_wrap(dir="h", facets=, ~ Station.Type)` the second parameter since to not have the value. I have partially fixed this in PR #7454.

**Comment by Patowhiz** [comment]
@N-thony agreed.
