### ISSUE TITLE
Renaming multiple columns - Make it easier. 

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#7460]
**Is your feature request related to a problem? Please describe.**
When I select **Multiple** option on the rename column dialog box, I can only convert to a case to or clean name. 

**Describe the solution you'd like**
I would like to be able to rename multiple columns at one go by having - for each column selected for renaming, a corresponding text box to appear to type in the new column name.  

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/9798689/167127502-5fc63708-560f-49cb-9b94-b8346bf056bf.png)

**Comment by N-thony** [comment]
> **Is your feature request related to a problem? Please describe.** When I select **Multiple** option on the rename column dialog box, I can only convert to a case to or clean name.
> 
> **Describe the solution you'd like** I would like to be able to rename multiple columns at one go by having - for each column selected for renaming, a corresponding text box to appear to type in the new column name.
> 
> **Describe alternatives you've considered** None
> 
> **Additional context** ![image](https://user-images.githubusercontent.com/9798689/167127502-5fc63708-560f-49cb-9b94-b8346bf056bf.png)

@maxwellfundi in the new version, I think that is possible
![image](https://user-images.githubusercontent.com/68591383/167128088-9859560b-5e52-4333-b3d4-4a6dc1937303.png)

**Comment by maxwellfundi** [comment]
@N-thony  Thank you so much. I think I need to update my version. I am on 0.7.4.

**Comment by rdstern** [comment]
Hi @maxwellfundi @N-thony has improved the rename considerably and I really like it now.  There still remains one further option to add.  I wonder if you will need it?
We are preparing Version 0.7.5 now, ready for a workshop on Monday.  So it should be up soon.
