### ISSUE TITLE
Combine the three plot options buttons in Climatic Maps to one similar with the Ok button?

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7472]
This is found during the KMD workshop, we found that it will be simple if we can combine the three plot options buttons to one similar to the `Ok button` with the small arrow on the right where when you click, you will have the remaining option i.e `S.F options` and `Map options`.
![image](https://user-images.githubusercontent.com/68591383/168523244-d99e84bc-8517-48cd-8dd3-2f11ad65c513.png)
@rdstern this is how it looks after combining the three options
@lilyclements what do you think?
![image](https://user-images.githubusercontent.com/68591383/168599927-3f230bcf-641e-42d9-b4f1-0835268129e6.png)

**Comment by lilyclements** [comment]
@N-thony This is interesting! What happens if you press the "Options" button and not the little arrow next to it?

**Comment by rdstern** [comment]
@N-thony I'm changing my mind - it should still say Plot Options!  And - like the other down arrows, the Plot Options is repeated there as the first of the 3 options.
@lilyclements I hope you like it?  If so, then we will just have the single Plot Options button on all the graphics.  Quite a number have multiple alternatives, like Labels Ridge Plots, etc.  They might even be "complete" for each dialogue.  So not change for each of the top buttons.

**Comment by N-thony** [comment]
@lilyclements if you are happy with this change, I will push it to be merge quickly so that it will be used as an example during our `tidying design session`.
