### ISSUE TITLE
Add new arithmetic keyboard to the calculator

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7483]
This keyboard will take some designing - 
a) I assume the keyboard could be called Arithmetic.
b) The top-left button could be called bigq and would produce gmp::as.bigq( ).
c) the R-Help button will call the gmp package.
d) Using this key will then be combined with the ordinary +, - , * / and power keys from the main keyboard.  I wonder about a small change to those keys (except ^ to have a space either side.  Perhaps @lilyclements can confirm.
e) Another general change I suggest is for the default to have the Save Result checkbox ticked by default.  It is what we often want.
Then we should investigate other keys on thew new keyboard (from the gmp package) and perhaps related?  I like prime which implements the gmp::is.prime( ) function and gmp::factorial

**Comment by anastasia-mbithe** [comment]
@rdstern, do we have factorials for, bigq, rational numbers?
