### ISSUE TITLE
Minor bug with the Climatic >Check Data> Climatic Boxplot Dialogue

### ISSUE THREAD

**Issue by EstherNjeriLiberatta** [africanmathsinitiative/R-Instat#7485]
**Describe the bug**
Code that seems to omit the options available in the station's combo box when plot options are applied.

**To Reproduce**
I used Rwanda.RDS dataset. 
1. Go to 'Climatic menu'
2. Click on 'Check Data'
3. Scroll down to 'Boxplot'
4. Add in your variables. For the `Station` combo box, change the value from `None` to `Facet Wrap/Row/Column`and click ok.
6. Go back to the dialogue, click on Plot Options then Y-axis, and customize your scale.
7. Return to the dialogue and click ok. 

**Expected behaviour**
The graph generated should have facets just as the initial one had. You'll notice the omitted code.

**Screenshots of dialogue and R output**

![image](https://user-images.githubusercontent.com/74548350/169274192-00c3b6e8-9aff-4880-8b67-c57c6b5857f6.png)

![image](https://user-images.githubusercontent.com/74548350/169275085-a10781da-0db6-40f4-a4c0-2225272df6a3.png)

![image](https://user-images.githubusercontent.com/74548350/169273990-ebc7381f-8d44-4bc4-b28d-50f69b0dbf8d.png)

![image](https://user-images.githubusercontent.com/74548350/169274450-74875765-b82f-47c0-a7ee-82e326eb8774.png)

**Comment by rdstern** [comment]
@EstherNjeriLiberatta well explained.  A work-around is to go to the offending control (Station) on the main dialogue and re-affirm (click again) on facet wrap.  Then it is happy.  I wonder if this can help to identify why the control is not updated automatically.

**Comment by EstherNjeriLiberatta** [comment]
@rdstern I have opened a PR that fixes the bug. Thank you.
