### ISSUE TITLE
VB.Net Designer Error

### ISSUE THREAD

**Issue by Wycklife** [africanmathsinitiative/R-Instat#7489]
I have been getting this error whenever I try to open dlgCalculator designer from VB.Net solution Explorer.
How do I fix it?

![image](https://user-images.githubusercontent.com/33898404/169540928-4520f33f-3ec8-4221-a5e9-924084326c15.png)

**Comment by Patowhiz** [comment]
@lloyddewit that's weird.
@N-thony are you also getting the error explained by @Wycklife above?

**Comment by Patowhiz** [comment]
@Vitalis95 kindly also check if you are also getting the error explained by @Wycklife above?

**Comment by N-thony** [comment]
> > @lloyddewit that's weird. @N-thony are you also getting the error explained by @Wycklife above?
> 
> @Patowhiz I still get the error above, though I have updated my VS Community 19 version to 16.11.15

@lloyddewit @Patowhiz I tried again today, and it works
![image](https://user-images.githubusercontent.com/68591383/171810599-28331650-514a-4272-b73a-3a5108ff5b8f.png)
