### ISSUE TITLE
Improve the mapping dialogue in R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7494]
The Climatic > Mapping > Map dialogue was very popular in the recent climatic workshops.  There is currently a small improvement to the Plot Options button waiting to be merged (#7481).  This issue is to investigate a further related improvement in that dialogue.
The dialogue has the option to add points (usually station positions) and they can be labelled.  So, that adds geom_point and geom_label to the plot.  
But, when I use the plot options button I do not find those geoms in the list.  It just has the geom_sf from the left hand panel.  It would be good to "register" all the geoms, so they can be edited.  One obvious edit is to decrease the size of the labels, so more are visible.  Another could be to change geom_label into geom_text?
Once they are properly detected, then these geoms should also be added to the new drop-down that was implemented in #7481.
I am mentioning @N-thony here, though he may wish to allocate this.  I am sure he will need to be involved though.

**Comment by N-thony** [comment]
@EstherNjeriLiberatta thanks for moving this in the blocker, could you explain the issue that is blocking your progress?
