### ISSUE TITLE
Small change in PICSA rainfall graphs dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7498]
@N-thony has made a change in the Plot options dialogue for the Mapping dialogue.  I suggest we apply this feature to other plotting dialogues, and start with the Climatic > PICSA > Rainfall Graphs.  

Now this is different to our other graphics dialogues in a small way.  In most of the others, I mainly use the Plot Options button and then (rarely) the Box Options or Jitter Options, etc.  Here I almost always use the PICSA options button, and only rarely the more general Plot Options.
So, I suggest either:
a) Keep the PICSA Options as it is. So the 2 buttons remain.  Also put the Down arrow on the Plot Options, and include Plot Options Line Options, Point Options there.
b) Have PICSA Options as the only button and the Down arrow on this button has PICSA OPtions, Plot Options, Line Options, Point Options.

**Comment by N-thony** [comment]
> @N-thony has made a change in the Plot options dialogue for the Mapping dialogue. I suggest we apply this feature to other plotting dialogues, and start with the Climatic > PICSA > Rainfall Graphs.
> 
> Now this is different to our other graphics dialogues in a small way. In most of the others, I mainly use the Plot Options button and then (rarely) the Box Options or Jitter Options, etc. Here I almost always use the PICSA options button, and only rarely the more general Plot Options. So, I suggest either: a) Keep the PICSA Options as it is. So the 2 buttons remain. Also put the Down arrow on the Plot Options, and include Plot Options Line Options, Point Options there. b) Have PICSA Options as the only button and the Down arrow on this button has PICSA OPtions, Plot Options, Line Options, Point Options.

@derekagorhom once PR #7481 is merged, it will be easy to implement this.

**Comment by N-thony** [comment]
> > @N-thony has made a change in the Plot options dialogue for the Mapping dialogue. I suggest we apply this feature to other plotting dialogues, and start with the Climatic > PICSA > Rainfall Graphs.
> > Now this is different to our other graphics dialogues in a small way. In most of the others, I mainly use the Plot Options button and then (rarely) the Box Options or Jitter Options, etc. Here I almost always use the PICSA options button, and only rarely the more general Plot Options. So, I suggest either: a) Keep the PICSA Options as it is. So the 2 buttons remain. Also put the Down arrow on the Plot Options, and include Plot Options Line Options, Point Options there. b) Have PICSA Options as the only button and the Down arrow on this button has PICSA OPtions, Plot Options, Line Options, Point Options.
> 
> @derekagorhom once PR #7481 is merged, it will be easy to implement this.

@derekagorhom you can work on this anytime now.
