### ISSUE TITLE
Add a menu for Crop Models

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7532]
This will be specified by me together with Sophie and Francis, once Sophie is on github.
I suggest the Options by Context Menu will (at the same time) be called Experiments
I also suggest we have a main menu item called Crop Model.  This will implement the apsimx package in R-Instat.  

a) One initial item could be Examples, which will open any of the built-in examples of data.  This will be a simple dialogue to implement the apsim_example function.    The command runs fine and all that needs to be added is to put the data into data frames in R-Instat.
b) Then I don't want Sophie to get stuck on the climatic data part.  And I hope she can work with Amsale on this aspect, so Sophie concentrates on the actual crop modelling.  On the other hand it looks as though using satellite-based data, e.g. chirps, is really easy.  So perhaps that can be included.
c) So then we move to using Apsim for crop modelling, assuming we have a met file.  The Apsim documentation says to use their gui, i.e. to simply use Apsim separately from R-Instat.  If that's best and there is nothing we can add into R-Instat to make that process easier, then so-be-it.  So here is where I need you to be able to use ApSim yourself, so you can provide guidance on what could usefully be added into R-Instat (if anything) the make Apsim easier, for R (Instat) users.

**Comment by N-thony** [comment]
@EstherNjeriLiberatta I think the first step for this will be to add the crop menu.

**Comment by EstherNjeriLiberatta** [comment]
@N-thony Thanks, will do.

**Comment by MeSophie** [comment]
@rdstern @N-thony  @Amsale2022 , This is the sketch of Apsimx-Examples dialog, It will import the apsimx file. 
If anyone of you have anything to add, it is highly appreciated.

![IMG_20220712_180603_792](https://user-images.githubusercontent.com/106779233/178523705-4a2065da-3092-4e11-aa25-2f35e16c70d8.jpg)

**Comment by N-thony** [comment]
> @rdstern @N-thony @Amsale2022 , This is the sketch of Apsimx-Examples dialog, It will import the apsimx file. If anyone of you have anything to add, it is highly appreciated.
> 
> ![IMG_20220712_180603_792](https://user-images.githubusercontent.com/106779233/178523705-4a2065da-3092-4e11-aa25-2f35e16c70d8.jpg)

@MeSophie  can you add just on top of the base button the `input text  control` for naming the data frame?
See the screenshot below.
![image](https://user-images.githubusercontent.com/68591383/179913988-a90f256e-4395-453c-ab1b-055f67bb1ff6.png)

**Comment by rdstern** [comment]
@MeSophie I first wish to check that apsimx is being installed in the new version of R-Instat.  Please can you check, and make an issue of this, if not.  Otherwise your examples dialogue won't work anyway.

Then, could you write a script to run apsimx for an example of a model.  Choose an example where all the climatic elements already exist, and without any missing values.  In general getting the climatic data (rain, tmax, tmin, sunshine, or radiation) for multiple years and without missing values is a big deal.  But I want to concentrate initially on running the model once we have that.

I assume you could prepare the script to run in R-Instat, but you may be more comfortable just using RStudio and that will be fine.  Ideally 2 examples  a) Single year or season, and b) Multiple years.  But just one will be fine to start with.

Then the corresponding script in R-Instat will have to add getting the data for apsimx out of respective data frames (data book) and putting the results back in.  That can come later.  Let's see it first in RStudio.
