### ISSUE TITLE
Unhide Data Frame seems to not work

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7533]
I have tried this by loading `dodoma` and `ghana` datasets but you can try with any datasets, then I have hidden `ghana` by clicking on Hide in dataview sheet menu context, it is fine  then when I tried to `Unhide` using `Hide/Unhide Data Frame` dialogue, it seems to not work.
The code generating by the `Hide/Unhide Data Frame` dialogue is 
![image](https://user-images.githubusercontent.com/68591383/172569048-c2727cfc-471b-4496-9df8-3555781a1ecf.png)
But it works when I change this code to
![image](https://user-images.githubusercontent.com/68591383/172569230-308de93b-c5bb-4c56-88a1-1c4f4576b4cf.png)
@shadrackkibet @lilyclements what do you think? I have check with recent version of R-Instat this seems to not work too.

**Comment by shadrackkibet** [comment]
I tried to replicate this bug but I failed. Below is the log file showing the steps. I loaded `Survey` and `mtcars` datasets. I did hide then unhide `mtcars` from the dialog and all seems to work as expected.

What is not intuitive from the dialog is how to unhide datasets. We should find ways to make it intuitive to the user that to unhide you have to remove items from the multiple receiver.

```
# Setting working directory, sourcing R code and loading R packages
setwd(dir="C:/Users/SHADRACK/Source/Repos/R-Instat/instat/bin/Debug/static/InstatObject/R")
source(file="Rsetup.R")
data_book <- DataBook$new()
options(dplyr.summarise.inform=FALSE)
# Option: Number of digits to display
options(digits=4)
# Option: Show stars on summary tables of coefficients
options(show.signif.stars=FALSE)
# Code generated by the dialog, Import Dataset
new_RDS <- readRDS(file="C:/Program Files/R-Instat/0.7.4/static/Library/experimental_survey.RDS")
data_book$import_RDS(data_RDS=new_RDS)
rm(new_RDS)
# Code generated by the dialog, Import From Library
utils::data(package="datasets", X=mtcars)
data_book$import_data(data_tables=list(mtcars=mtcars))
# Code generated by the dialog, Hide/Unhide Data Frame(s)
data_book$set_hidden_data_frames(data_names="mtcars")
# Code generated by the dialog, Hide/Unhide Data Frame(s)
data_book$set_hidden_data_frames()
```

**Comment by lilyclements** [comment]
@N-thony @shadrackkibet I also could not replicate this error.
Can we try and get into a habit that when giving bug reports, we attach the output script in a file as well as give a detailed outline? (This is quite straight forward now we have a Save option on the Output Window script?)

**Comment by N-thony** [comment]
> @N-thony @shadrackkibet I also could not replicate this error. Can we try and get into a habit that when giving bug reports, we attach the output script in a file as well as give a detailed outline? (This is quite straight forward now we have a Save option on the Output Window script?)

@lilyclements it works but the problem I found as Shadrack explained above, is you need to remove the `dataframe` from the receiver and then run again, it may be good to re-design this dialogue, it seems not friendly to use it from my view.
![image](https://user-images.githubusercontent.com/68591383/172618656-1fb4e764-8a34-4b7c-91fa-f0eeae32e311.png)

**Comment by lilyclements** [comment]
@N-thony i see. So perhaps if the data selector only displayed hidden data frames? Then you put in the receiver data frames to redisplay?

**Comment by lilyclements** [comment]
@shadrackkibet this sounds like a really good idea. I think it would simplify the dialog for the user. We could do a similar idea in the hide/show columns dialog too?

**Comment by shadrackkibet** [comment]
@rdstern I agree with your suggestion in b) for c) I wouldn't say I like hiding things completely in our metadata windows. I am happy with using properties to show when things change - TRUE or FALSE (Perhaps we use colours to alert the user when something has changed). In this case, we are hiding or unhiding. In some instances, we change the properties of columns. I claim that is exactly why do have these windows therefore complete hiding is contrary to the existence of these windows - Apart from showing the actual metadata, they act as some easier to use (visual) "logs" to keep track of what has changed.

**Comment by rdstern** [comment]
@shadrackkibet I could "buy that" perhaps for the data frame metadata, i.e. to have TRUE and FALSE for hidden data frames.  But are you sure for the column metadata?  Remember we sometimes have over 7000 variables and it could be much higher.  I suggest it would sometimes be very useful to just view the selected variables there.

**Comment by N-thony** [comment]
@Vitalis95  can you check with @shadrackkibet on how to implement some of these changes suggested above?
