### ISSUE TITLE
Change the specific plots to the new system

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7556]
I am suggesting @EstherNjeriLiberatta for this, as (I am afraid) you did the PICSA and mapping graphs very well!

a) I suggest there be a single button, just `Plot Options`.  And it has the same pull-down as for the mapping dialogue.  
b) Then the first option is also Plot Options.
c) This is followed by each of the remaining options for that dialogue, and they could be in alphabetical order.
d) I suggest they don't change for the different options at the top.  So, for example, for bar charts it is the same whether the top radio button if Frequency, Value, Treemap or Wordcloud.
e) Then simply include each of those, including label and lollipop, etc.

**Comment by N-thony** [comment]
> @EstherNjeriLiberatta any progress?

@EstherNjeriLiberatta I have added @Fidel365 to help you on this since we have many dialogues where these changes are needed and also for him to have something to work on. As discussed you were happy to share some dialogues with him, I hope everything is going well.
