### ISSUE TITLE
A bug for PICSA plot option - V0.7.6

### ISSUE THREAD

**Issue by Amsale2022** [africanmathsinitiative/R-Instat#7566]
I am testing the R-Instat v0.7.6 candidate version and encounter an error when using the PICSA Plot option:
**Climatic > PICSA Rainfall Graphs**, then **PICSA Options, Lines, Add Mean Lines**. The plotting works but does not allow to add the mean line. A screenshot of the error message is attached.
Thanks.

![PICSA Plot option](https://user-images.githubusercontent.com/104636673/174285438-b80f8962-03f6-4ce0-9797-dd2975971fdf.png)

**Comment by N-thony** [comment]
> I am testing the R-Instat v0.7.6 candidate version and encounter an error when using the PICSA Plot option: **Climatic > PICSA Rainfall Graphs**, then **PICSA Options, Lines, Add Mean Lines**. The plotting works but does not allow to add the mean line. A screenshot of the error message is attached. Thanks.
> 
> ![PICSA Plot option](https://user-images.githubusercontent.com/104636673/174285438-b80f8962-03f6-4ce0-9797-dd2975971fdf.png)

@Amsale2022 thanks for reporting, this bug was also reporting in #7534 which is fixed in PR #7561 actually merged, hopefully it iwll be in the final release of 0.7.6

**Comment by Amsale2022** [comment]
@N-thony thanks. However, the issues is a bit different from #7534 where the mean was miscalculated when multiple y-variable are used but plots are produced. Here, the plot is not being produced rather interrupted with the error message.

**Comment by N-thony** [comment]
> @N-thony thanks. However, the issues is a bit different from #7534 where the mean was miscalculated when multiple y-variable are used but plots are produced. Here, the plot is not being produced rather interrupted with the error message.

@Amsale2022 okay, can you update your local master with the latest changes and then try it again? if it still there then we can find how to fix it.

**Comment by N-thony** [comment]
@derekagorhom please check if you can reproduce this bug.

**Comment by derekagorhom** [comment]
hey @Amsale2022, i tried reproducing the bug you mentioned (i.e using the the single variable), but it produces a result for me. 
![Screenshot (434)](https://user-images.githubusercontent.com/76208189/175897012-c605e90c-c32e-4ab1-a5a7-be0eb9d46781.png)

would you like to schedule a meeting so that we can solve this issue?

**Comment by Amsale2022** [comment]
@N-thony thanks for looking at the issue and for the discussions. It is working with the updated master. I also checked the mean calculation separately and works fine. Hence you may close the issue.

Thanks
Amsale
