### ISSUE TITLE
Minor bug when trying to rename a dataframe from Data Frame MetaData Grid

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7568]
I always get this error when I try to rename a dataframe from Data Frame MetaData Grid
![image](https://user-images.githubusercontent.com/68591383/175254059-e324993f-5ed3-4723-9eb8-cec8181a15bc.png)

**Comment by N-thony** [comment]
@derekagorhom any progress on this?

**Comment by derekagorhom** [comment]
I am working on it
