### ISSUE TITLE
Correct spacing between the Point(Scatter) plot dialogue.

### ISSUE THREAD

**Issue by EstherNjeriLiberatta** [africanmathsinitiative/R-Instat#7573]
**Describe the bug**
This is not a bug but a request for change in the dialogue design. There appears to be too much space between the dialogue.

**To Reproduce**
1. Go to 'Describe menu'
2. Click on 'Specific Tables/Graphs'
3. Scroll down to 'Point(Scatter) Plot' 
4. See dialogue

**Screenshots**
![image](https://user-images.githubusercontent.com/74548350/175953368-992fd338-ca4e-41c3-b272-9cec00342a09.png)

**Comment by N-thony** [comment]
@EstherNjeriLiberatta any progress?
