### ISSUE TITLE
Bug when trying to load csv file with the French translation

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7590]
I'm able to load this data under the `English translation` but when I switch to `French translation`, I'm no longer able to load.
Here is the loading under English translation
![image](https://user-images.githubusercontent.com/68591383/177304246-2ccf5c60-e25e-4132-8c5c-3c9ab996aae4.png)

this is what I get when I switch to French
![image](https://user-images.githubusercontent.com/68591383/177304362-f3d69e04-8464-4eba-ac8d-6a37634dc1a8.png)

this is the file [kisii_pyreth_data.csv](https://github.com/africanmathsinitiative/R-Instat/files/9045460/kisii_pyreth_data.csv)

**Comment by N-thony** [comment]
> I'm able to load this data under the `English translation` but when I switch to `French translation`, I'm no longer able to load. Here is the loading under English translation ![image](https://user-images.githubusercontent.com/68591383/177304246-2ccf5c60-e25e-4132-8c5c-3c9ab996aae4.png)
> 
> this is what I get when I switch to French ![image](https://user-images.githubusercontent.com/68591383/177304362-f3d69e04-8464-4eba-ac8d-6a37634dc1a8.png)
> 
> this is the file [kisii_pyreth_data.csv](https://github.com/africanmathsinitiative/R-Instat/files/9045460/kisii_pyreth_data.csv)

@lloyddewit could we discuss this?

**Comment by lloyddewit** [comment]
@N-thony Thank you for finding and documenting this bug.
I agree that setting the controls to `DoNotTranslate` seems the best solution.

> to prevent such bug I suggest if we can set all the input controls, nud controls, input text controls to DoNotTranslate. What do you think?

Do you mean just the controls in this dialog?
If yes, then I agree. Basically any control that creates an enumeration parameter (e.g. `Automatic`) should be set as `DoNotTranslate`.

**Comment by N-thony** [comment]
> 

@lloyddewit ideally it will be good setting the controls to any susceptible dialogues.
