### ISSUE TITLE
Menu items translating inconsistently

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7597]
Hello @lloyddewit and @N-thony, 

I am reviewing the French version in Preparation for the DRC course in August. I have noticed that some menu items that are present and correctly translated in Crowd-in are not translating. I am also pretty sure that these used t be translated correctly. Please see examples below. 
![2022-07-07_11-04-45](https://user-images.githubusercontent.com/85707390/177843357-090f222e-b888-41e7-93ad-4be6da0e34e0.png)
Here Two/Three Variables, Specific Tables/Graphs and Visualise Data
![2022-07-07_11-03-51](https://user-images.githubusercontent.com/85707390/177843466-fce0a652-970e-40aa-9d2f-b23503ee7896.png)
Here Column: Calculator, The whole submenu of Column: Numeric. **Data Book** is slightly different in that it is not translated but i do not see it in crowd in to translate.

**Comment by lloyddewit** [comment]
Resolved in R-Instat 0.7.10
