### ISSUE TITLE
French lay out issues in the Import from file dialog

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7598]
Hello @N-thony and @lloyddewit, 

Apologies for bombarding you. This is a dialog that we did not address on the first round as it was complicated and due to be updated. It has a number of issues. @N-thony please could you review it and correct them?

- Top Checkbox: Tous les fichier de ce type (type is not visible)
- Première ligne est les noms de colonnes (I updated the crowd-in translation to noms instead of en-têtes but cannot think of a shorter version than that. @N-thony can you think of a good way to shorten it or to expand the box?)
- Chiane de valeur manquante  the text overlaps the box. I have updated this to Valeurs manquantes in Crowd-in so this may resolve itself, but perhaps you could check.
- Convertir des chaînes en colonnes de facteur Checkbox: facteur cut off. 
- Nouveau nom de tableau de données: the colon at the end is cut off. 
- Drop Empty Row and Columns Checkbox: Not translated, perhaps this is simply a new item that is not yet in the system? I cannot see it in crowdin. 
- Is Cannot import this file with the current options.... message is not translated. Should it be? (some of the messages do not than that is ok.)
![2022-07-07_10-48-05](https://user-images.githubusercontent.com/85707390/177850888-38ecda13-9871-408b-9891-b5937245426c.png)

I also noticed that when I check the Import all files of this type box, I get a different view. This has a message that is translated but disappears off the page. 
![2022-07-07_10-51-47](https://user-images.githubusercontent.com/85707390/177853630-b26098b8-6ea8-4a9a-896c-fd3f2b25af6b.png)

**Comment by N-thony** [comment]
@derekagorhom can you help @Fidel365 on this? Thanks.

**Comment by rachelkg** [comment]
This view also has similar problems: 
![2022-07-22_15-30-26](https://user-images.githubusercontent.com/85707390/180576781-7a3c3b7e-48b4-4f11-abf6-bfa56af70c63.png)

**Comment by Fidel365** [comment]
@rachelkg, is this not the same dialogue we have been working on in this PR, we have been fixing overlapping in this dialogue

**Comment by rachelkg** [comment]
@Fidel365 it is the same dialog but a different view, therefore different options/layers are visible. Please make sure that you check resolve the issues on all the layers of this dialog. 

Thanks, 

Rachel

**Comment by Fidel365** [comment]
@rachelkg , we already worked on this in PR #7622
