### ISSUE TITLE
New Data Frame dialog translation issues

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7599]
Hello @N-thony and @lloyddewit, 

On all: 
New data frame name, the box slightly overlaps the French text cutting off the colon. 
On the empty tab:
the variable Name and Variable Label checkboxes are not translated. (These are not in crowd-in).
![2022-07-07_12-18-08](https://user-images.githubusercontent.com/85707390/177855329-7ad341be-849a-46a5-9e8c-adf7b05d8bec.png)

On the other tabs:
the Try button is not translated. (This is in crowdin and has previously been correctly translated elsewhere.)
![2022-07-07_12-18-15](https://user-images.githubusercontent.com/85707390/177855362-56d7f333-5cf5-4b7d-9f09-1ebec23a4add.png)

Thanks, 

Rachel

**Comment by MeSophie** [comment]
This Dialog has some modifications I added Variable Name, Variable Label, Lists, Levels and Name in Json file. 
For New Data Frame >Construction, Try is still Try in french version.

![image](https://user-images.githubusercontent.com/106779233/196474294-c8826298-4edc-483d-9e18-d79d831a604e.png)


For New Data Frame > Lists I added Category and Show Command. 

![image](https://user-images.githubusercontent.com/106779233/196475917-7c3cf8e0-e20f-4c7c-ae9b-641b43fc0360.png)

@N-thony and @lloyddewit Please have a look.

I am also wondering if I need to add this lits in the Json File.

![image](https://user-images.githubusercontent.com/106779233/196476838-2fa75f6e-c128-4ea7-b824-d3a326588f15.png)

**Comment by lloyddewit** [comment]
@MeSophie Thank you for identifying this.
The easiest way to spot text that is not currently translated is to select Russian. I think that only the 6 strings highlighted below need to be added to the JSON file. After the CrowdIn translations are done, and the database updated, then the strings should then translate automatically.

There's no mechanism yet to translate the column headings in the 'Construction' panel, or the pull-down lists in the 'Lists' panel. So we don't need to add these strings to the JSON files.

@MeSophie I think you already added 'Lists' (but not 'Lists:') to the JSON file in PR #7921. Please could you add the remaining 5 strings? 
Thanks!

![image](https://user-images.githubusercontent.com/57253949/197145055-5d911455-ac5c-4692-bbdb-afc429ce71ba.png)


![image](https://user-images.githubusercontent.com/57253949/197145238-932156de-e44b-4a28-87dc-d286bbbfd429.png)

![image](https://user-images.githubusercontent.com/57253949/197145453-bc5e717d-8a57-4fea-951c-6e0139251990.png)

**Comment by MeSophie** [comment]
@N-thony please can you close this issue?

**Comment by lloyddewit** [comment]
Everything fixed in R-Instat 0.7.10.
Some controls may still need to be repositioned for the longer languages (French/Russian)
