### ISSUE TITLE
Save as dialog translation does not reflect the Crowdin text

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7600]
Hello @lloyddewit, 

This is more of an oddity than a big issue. In crowdin Save Data As is translated as 'Enregistrer les données sous' however, in R-Instat the title of this dialog Save Data As is 'Enregistrer des données comme'.
![2022-07-07_13-03-29](https://user-images.githubusercontent.com/85707390/177864613-8d9ad9b6-5eb3-49c9-bd77-b7bf5732fd83.png)
![2022-07-07_13-18-52](https://user-images.githubusercontent.com/85707390/177864678-94dda5ba-0a22-4c88-9304-de82d9a086c8.png)
![2022-07-07_13-02-59](https://user-images.githubusercontent.com/85707390/177864697-ea3436d9-ed2f-4738-bba9-b9780cb8ec7c.png)

**Comment by MeSophie** [comment]
@N-thony and @lloyddewit this translation is still **Enregistrer les données à** in R-Instat.  

![image](https://user-images.githubusercontent.com/106779233/196465209-c1d981f1-a1d2-479e-b0ac-07df61630242.png)

**Comment by lloyddewit** [comment]
@MeSophie Thank you for spotting. If we change the English text in this dialog to 'Save Data As:` and also change the JSON file, then this should fix this issue.
Please could you do this? thanks

![image](https://user-images.githubusercontent.com/57253949/197149453-8609baeb-255b-45b8-97d6-488062617703.png)
