### ISSUE TITLE
Export Data... dialog not translating

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7601]
Hello @lloyddewit and @N-thony 

Though I am in the french version. This dialog is showing up completely in english. 
![2022-07-07_13-25-18](https://user-images.githubusercontent.com/85707390/177865546-4dbf0588-e1c9-434d-9e50-8215aeedab26.png)

Though the menu item is translating correctly:
![2022-07-07_13-25-43](https://user-images.githubusercontent.com/85707390/177865614-fd2318dc-7b31-43d5-aba7-2c1c30a918af.png)

**Comment by lloyddewit** [comment]
@rachelkg Thank you for finding and documenting these translation issues (also for issues #7597 and #7598). Thank you also for adding the correct translation labels to these issues.
@N-thony and I discussed the translations a couple of days ago. I understand that there is a French language workshop coming up and we would like the next release to be ready in time for this workshop. We'd like the new release to be focussed on French translations. There are a number of recent CrowdIn updates that we haven't merged yet (see PR #6569). There are also new dialogs and enhancements that haven't yet been added to the translation database, or tested in French.

@rdstern @N-thony Please could we discuss the French translations next week and agree the best way ahead?

Thanks

**Comment by rachelkg** [comment]
Thanks @lloyddewit thanks so much for your response. Just to let you know my plan, I will be off all of next week but back after the 18th, and intend to keep checking through the first few menus and the tutorial process then. Thanks, Rachel

**Comment by MeSophie** [comment]
@N-thony I think we can close this issues. What do you think? We already solve this through #7701.

**Comment by MeSophie** [comment]
@N-thony Please can you close this issue?

**Comment by MeSophie** [comment]
@N-thony This issues is already solved with through #7701. So I will close it.

![image](https://user-images.githubusercontent.com/106779233/213160842-f993d30d-ea4f-491a-b0f3-f818f5b11886.png)
