### ISSUE TITLE
Rename Columns Dialog Title and Tab titles not translating

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7602]
Hello @lloyddewit and @N-thony, 

In the Prepare > Data frame > Rename Columns The title of the dialog is not translated and neither are the top tabs, Single (In crowdin), Rename With (Not in crowdin).
![2022-07-07_13-29-22](https://user-images.githubusercontent.com/85707390/177866530-53fe153d-da25-4f8d-9b15-e0654c75df36.png)

**Comment by derekagorhom** [comment]
@N-thony this has been solved (except for the tabs) so i am closing this
