### ISSUE TITLE
Extend the drop-down on the Add control?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7606]
This may need some discussion, so we do the right thing here.

![image](https://user-images.githubusercontent.com/11226469/178095912-ecb14589-d388-4d05-8d21-cb0ba69aca15.png)

@Patowhiz and @ChrisMarsh82 I am suggesting Chris may have a view here, because he never liked my right-click in the data selector!

a) The drop-down should be added to the selector also when it is selecting data frames.  For example here:
![image](https://user-images.githubusercontent.com/11226469/178099632-c9cc206b-a0f6-4808-81b7-5f61c73201da.png)

b) The reviewer also questioned whether we should have an` Add/Drop `button, rather than just the `Add,` as we have now.  If so, then I assume we could call it `Add` (as now), when the focus is on the data selector.  And this could change to `Drop`, when the focus is on a receiver?  There we have Clear on the current right-click and this would then be included on the drop down.  It might be there anyway, but disabled unless it is relevant.

**Comment by Patowhiz** [comment]
c) It's about time we implemented drag and drop as a standard between the selector and the receivers.
d) I should be able to reorder the items in the receiver. This makes sense for certain dialogs in which the order of the contents in the receiver matters.

**Comment by rdstern** [comment]
@Patowhiz and perhaps @N-thony may have a view here.  I now feel the DRC participants would have liked and Add/Drop button instead of just the Add?  Some of them are less experienced than most climatic users so far, and the easier we can make it, the better.

**Comment by Patowhiz** [comment]
It's about time we also implement a drag and drop!

**Comment by rdstern** [comment]
@N-thony there are some good suggestions here.  But just one of them - namely a) above was requested on the recent workshop.  It now looks inconsistent to have the drop-down on dialogues that involve variables and not on those that involve data frames.  I assume this may be a very quick change, so could we implement that one, (as a partial implementation of this issue, while waiting for others to be further discussed.  If it is not a quick change, then don't do it yet.
