### ISSUE TITLE
A bug while Importing dataset using File>Import from File in French version

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7615]
**Describe the bug**
When importing dataset using File>Import From File in French version, I get the following error;

![image](https://user-images.githubusercontent.com/106779233/178740432-e8ca7f94-3b0e-4a0c-aa24-a387b6536e95.png)

But when I  use English version to import the same dataset , it works fine as shown below;

![image](https://user-images.githubusercontent.com/106779233/178740960-877abd03-a33d-4c7c-beef-22bd9fcb1d45.png)

**Comment by N-thony** [comment]
@MeSophie thanks for reporting this bug. @lloyddewit will it be good to merge PR #7591 that attends to fix this? Thanks.
