### ISSUE TITLE
Improve the wakefield keyboard in Prepare > Calculator 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7618]
When using the wakefield keyboard, when there is a data frame, the first argument for each key is always (n = length...) where length is the length of the data frame.  Currently the command is given, for example, as 

wakefield::age(n = , x = 20:35 , prob = NULL, name = "Age")

or 

wakefield::age()
if the arguments are not shown.  
I would like it to be wakefield::age(n = 36).  I suppose it could be wakefield::age(n = nrow(survey)) if that is easier to do?

**Comment by anastasia-mbithe** [comment]
Am closing this because it was fixed in PR #7904
