### ISSUE TITLE
Add a control of factor level order to the Describe > Two/Three Variable > Pivot Table dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7620]
This is a pretty amazing resource for data exploration.
One limitation is that factors appear in alphabetical order.  It ignores the special ordering we may have.

Often that isn't too much of a problem, but sometimes it is!
Note that a factor we may wish to have in the factor-level order may not be given in the dialogue initially.  
The vignette recognises the problem and gives an example where the levels of a factor are defined.
In our case we could just have a receiver on the dialogue that gives the factor name.  Then the order would be the R-Instat order.  Ideally this would be a multiple receiver, but a single would be useful - at least for a start.

Perhaps @lilyclements could have a quick look at the R code needed?  Then @Ivanluv could add the control?  The label might be Factor Levels.  Perhaps there could be a tooltip to say something like.  `Use when default (alphabetical) order of factor levels is inappropriate.`

**Comment by lilyclements** [comment]
@rdstern I've written some code here to rearrange the factor levels.

@Ivanluv this should be ready for use in R-Instat

```
# Rearrange the factor levels for survey for the example
survey <- survey %>% 
  dplyr::mutate(village = forcats::fct_relevel(village, c("NIKO", "NANDA", "SABEY", "KESEN")))

# Then in the dialog:
# 1. Getting the factor levels in the right format:
# Use the levels function to get the survey_levels
survey_levels <- levels(survey$village)
# Add \" around each level
survey_levels <- paste0("\"", survey_levels, "\",")
# flatten it into a single vector
survey_levels <- stringr::str_flatten(survey_levels)

# 2. This looks more complex than it is. Most of this is a string, with the survey_levels variable read in.
relevel_variables <- paste0("function(attr) {
  var sortAs = $.pivotUtilities.sortAs;
  return sortAs([", survey_levels, "]); }")

# 3. Then read it into the sorters parameter value
last_table <- rpivotTable::rpivotTable(data=survey,
                                       rows=c("village","field","size"),
                                       cols="village",
                                       sorters = relevel_variables)
last_table
```
