### ISSUE TITLE
Remove or find an alternative to "signmedian.test" R package

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#7626]
The message from CRAN reads as follows;

![image](https://user-images.githubusercontent.com/26301973/179350160-18245fb4-2cde-499a-9d8d-e008cd4a2642.png)

We are still installing this package for some reason. Good to check where it is used and find an alternative. If not possible we can save the archived version for use.

**Comment by rdstern** [comment]
@shadrackkibet could you check in the code as well?  I tried, and can see we load it.  But I can't see that we use it anywhere.  If I am right, let's just delete it from the set of packages.

**Comment by shadrackkibet** [comment]
As far as I can see.

In 2017 it was used in the One variable Fit model see https://github.com/africanmathsinitiative/R-Instat/pull/2912/files/5db975eae2a176d1714437f0ffc3906ce3810fd6
I believe we've changed this dialog since then and therefore this package is no longer used anywhere. Therefore we should remove it.
