### ISSUE TITLE
Missing Translations in Right Click menus

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7645]
Hello @lloyddewit and @N-thony, 

i am continuing my run through if the tutorial in R-Instat in preparations for August 1st. 

I have noticed that there are items in each of the right-click menus that are not translating. 

Interestingly, though the column right click menu and the data frame right click menus look almost identical in terms of content, their translations are different. Levels/labels is translated in the column right click menu but not in the data frame right click menu. 

Thanks, 

Rachel
![2022-07-22_10-42-33](https://user-images.githubusercontent.com/85707390/180495730-14137560-01df-4995-9ab9-6539790a8f2a.png)
![2022-07-22_10-43-27](https://user-images.githubusercontent.com/85707390/180495752-57526652-a094-4e8a-a4c7-ee1700cafcf4.png)
![2022-07-22_10-43-42](https://user-images.githubusercontent.com/85707390/180495760-2f2cb506-ce48-4923-8b96-06becf3b41ae.png)
![2022-07-22_10-43-57](https://user-images.githubusercontent.com/85707390/180495765-cdbfac1c-8e77-417d-8106-8449289d19e6.png)

**Comment by rachelkg** [comment]
One more. This is the right-click menu in the variable selector.
![2022-07-22_10-59-00](https://user-images.githubusercontent.com/85707390/180497256-890b9428-bed8-4f8a-8900-bfde3bae86ef.png)

**Comment by rachelkg** [comment]
Hello @N-thony and @lloyddewit, 
 
This is still and issue and also happened on the Add button's drop down menu. Can these be resolved in time for the next release?

Thanks, 

Rachel 

![2023-01-04_14-34-34](https://user-images.githubusercontent.com/85707390/210662924-c1a8a2a5-364a-42b8-b8ab-adfc1913c77f.png)

**Comment by rachelkg** [comment]
Oh and this one. 
![2023-01-04_16-07-57](https://user-images.githubusercontent.com/85707390/210673154-8b00a4a0-5a66-4f99-b53e-5eb9061d4cd7.png)

**Comment by rachelkg** [comment]
I find this to be completely baffling but sometimes the right click menu shows as above with most of it translated and other times it shows up like this, with most items not translated. I have yet to find any rhyme or reason to when i see one or when the other, in both instances the program is set to French and the menu items are appearing in French. I am not using different versions of the program and have not made any updates to it between uses. Any thoughts? 

![2023-01-04_16-35-09](https://user-images.githubusercontent.com/85707390/210675829-c632c1b2-86a6-406b-a60a-0df880083245.png)

**Comment by lloyddewit** [comment]
Everything resolved in R-Instat 0.7.10, or covered by issue #3721.
