### ISSUE TITLE
Items not translated on the Correlations dialog

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7647]
Hello @lloyddewit and @N-thony, 

There are items on the correlations dialog that are not translated in the French version.

Multiple Variable: In crowdin
Two variables:  In crowdin

Display Options box content not in Crowdin

Data Frame Name: not in Crowdin (but Dataframe Name is, perhaps we could update to this?)

First Variable: in crowdin
Second Variable: in crowdin
Model Name: not in crowdin

Thanks, 

Rachel 
![2022-07-22_11-35-56](https://user-images.githubusercontent.com/85707390/180502897-d43467a7-c02f-4d68-a5c7-6e165b3c7b81.png)
![2022-07-22_11-36-13](https://user-images.githubusercontent.com/85707390/180502904-1c634754-45c9-4c24-a4e9-b84052e2a6bd.png)

**Comment by rachelkg** [comment]
In the correlation graph and display options subdialog there is also an untranslated option. 

Reverse Legend Order: (not in crowdin).
![2022-07-22_12-00-28](https://user-images.githubusercontent.com/85707390/180506282-086c2f0e-549a-4e21-888c-b9d65bdc64a0.png)

**Comment by lloyddewit** [comment]
Resolved in R-Instat 0.7.10
