### ISSUE TITLE
Line plot dialog french layout issues

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7650]
Hello @lloyddewit, @N-thony and @rdstern 

Roger please weigh in on this Ajouter des box which is showing up in English and french.

The line plot dialog has a lot of layout issues which result in the text being cut off in french and there are also a number of items that appear in english in the french version. 

Line, Smooth, Dumbell and Slope not translated 

Line view:
Actually there is also an in the English version too, where a checkbox says Ajouter des. In the French version this checkbox appears too, should it be there? If so what should it say? 
Add Line of best Fit text cut (Ajouter une ligne de )
Add SE not translated not in crowdin
Use path or Step not translated not in crowdin
Path Options not translated not in crowdin

Smooth view
Ajouter des checkbox is again there in English and French versions. Not clear to me what it means as the text is cut off and the same in english and french.
smooth Options box not translated

Dumbell view:
Dumbell options not translated not in crowdin

Slope view: 
Label, text and line options not translated

I looked at updating the layout myself but this dialog looks very complicated and I did not want to mess things up further. could someone more experienced with programing be assigned to it please? 

Thanks, 

Rachel 
![2022-07-22_15-48-05](https://user-images.githubusercontent.com/85707390/180578096-42295e92-29a0-4828-a1fa-0a80399ded58.png)
![2022-07-22_15-47-51](https://user-images.githubusercontent.com/85707390/180578101-d80ce6dc-b84b-4197-b925-1ce27034dd6b.png)
![2022-07-22_15-47-34](https://user-images.githubusercontent.com/85707390/180578111-1adb1476-aa28-4e37-83a9-710e8a93a88d.png)

**Comment by derekagorhom** [comment]
This has been solved
