### ISSUE TITLE
 Error message when using the Display daily data dialog in R-Instat 0.7.7 with French translation.

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7671]
When clicking on **Display Daily Data** (Climatic>Check Data>Display Daily Data), an error message appears before the dialogue interface is displayed. 

![Error1](https://user-images.githubusercontent.com/106779233/181613646-89267d34-7f9a-4949-a0d5-65a708043528.png)

After filling the **Display Daily Data** dialog and clicking ok we receive another error message as showing below.
![Error2](https://user-images.githubusercontent.com/106779233/181614513-c87a7b33-aa01-44b5-8c8c-ecce2117825f.png)

**Comment by N-thony** [comment]
@derekagorhom can you fix the first problem i.e the developer error? 
The second problem is due to the translation `Noir` is not recognized by `R` therefore the input control was not supposed to be translated. This is already fixed in the merged version.

**Comment by derekagorhom** [comment]
I agree with @lloyddewit, i tried to recreate the error but everything looks fine on my end
@N-thony please did you encounter the errors when you tried to recreate it?

**Comment by N-thony** [comment]
> @N-thony @derekagorhom I tried to recreate the issue using dialog settings related to above. I did not get a developer error. If I removed one of the elements, then I was able to get a developer error (see below). However the error was not related to translations. Please could you confirm the above and close this issue if appropriate? Thanks!
> 
> ![image](https://user-images.githubusercontent.com/57253949/182118002-a4d7096c-9bc4-4f59-9b61-f4d85be91d94.png)

@lloyddewit the bug reported above by Sophie was due to translation and it was reported by using version 0.7.7 but this was already fixed in the merged version.
We can close this if there is not one the above errors in the merged version

**Comment by lloyddewit** [comment]
@N-thony @derekagorhom Thanks for the feedback, I'll close the issue
