### ISSUE TITLE
Translation issues when we right click on one column.

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7673]
Using the French translation of R-Instat 0.7.7 when you make a right click on one column, the some sub-menu which is still in English (**Delete Cells, Paste , Filter Rows, Select Columns, Remove Column Selection and Help**). 

![colonne](https://user-images.githubusercontent.com/106779233/181632539-2a9d08ef-b7bf-452e-a175-1b54faef086b.png)

**Comment by N-thony** [comment]
> Using the French translation of R-Instat 0.7.7 when you make a right click on one column, the some sub-menu which is still in English (**Delete Cells, Paste , Filter Rows, Select Columns, Remove Column Selection and Help**).
> 
> ![colonne](https://user-images.githubusercontent.com/106779233/181632539-2a9d08ef-b7bf-452e-a175-1b54faef086b.png)

@MeSophie  **Levels/Labels** is not translated too, please add it in the Json file.

**Comment by N-thony** [comment]
@MeSophie you missed to add  **Remove Column Selection and Help**

**Comment by MeSophie** [comment]
@N-thony  the menu already has **Help** and **Levels/Labels**
