### ISSUE TITLE
PICSA Menu French translation issues

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7679]
PICSA menu items are not translated. 
![2022-07-28_14-17-12](https://user-images.githubusercontent.com/85707390/181643205-58d02a42-5905-425a-bcd8-32a8e4d039a3.png)

The titles of PICSA Temperature Graphs and PICSA General Graphs and PICSA Crops are not translated.  
![2022-07-28_14-43-48](https://user-images.githubusercontent.com/85707390/181643335-57a91dbb-6b63-46d3-ab97-e6c35f777ca8.png)

The Plot Options, Line Options and Point Option buttons not translated.
![2022-07-28_14-39-51](https://user-images.githubusercontent.com/85707390/181643464-d74d7c90-2e9d-46f4-82eb-17df252f8511.png)

**Comment by rachelkg** [comment]
Hello @N-thony 
I have also noticed that when I open plot options the Y Axis view looks like this in R-Instat but when i go to change it and resolve the overlapping and misalignment issues in visual basic it looks like this. Could someone more experienced resolve this please?
![2022-08-03_15-38-53](https://user-images.githubusercontent.com/85707390/182724659-cdf11001-0dcd-4ebc-bcf4-ab4b2159916e.png)
![2022-08-03_15-41-00](https://user-images.githubusercontent.com/85707390/182724729-d2cee61a-3ecf-4e64-86e8-56b958c35da0.png)

**Comment by N-thony** [comment]
@rachelkg it is a `user control` used there for the axes options, have a look of the `ucrAxes` and see if you can make the chnages
![image](https://user-images.githubusercontent.com/68591383/182779053-258e3465-0dd9-48ea-9825-f46cf58e3cf0.png)

**Comment by rachelkg** [comment]
@N-thony Thank you!

**Comment by MeSophie** [comment]
Fixes (Partially) in Crowdin.

**Comment by N-thony** [comment]
> @N-thony everything is solved in this issue except Plot Options, Line Options and Point Options (PICSA>Rain Graph >Graph Options) that are translated in Crowdin but not in R-Instat.

@MeSophie sounds good, @Vitalis95 can you check this too and make the changes in your branch?

**Comment by N-thony** [comment]
@MeSophie @Vitalis95 is this completed?

**Comment by lloyddewit** [comment]
Everything in this issue is solved apart from the pull down menu translation. This is covered in issue #3721.
