### ISSUE TITLE
Translation issues in Filter Rows Dialogue.

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7699]
Using the French translation of R-Instat 0.7.7 in **Filter Rows** dialog (Filter Rows>Define New Filter>Add), the notification message which appears when you forget to **add filter** before **return** is in English  and **Select All Levels** is Still in English.

![Screenshot 20(message error en francais)](https://user-images.githubusercontent.com/106779233/182016628-ea32e753-a30e-4e91-85e3-9ac31c014191.png)

**Comment by lloyddewit** [comment]
'Select All Levels' is translated in R-Instat 0.7.10.
The popup message is covered by issue #3721.
