### ISSUE TITLE
Correct misleading message in Tools > Install R package dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7707]
Here is an example:

![image](https://user-images.githubusercontent.com/11226469/182029131-22ac1232-d57e-40ce-bf0e-a421b366577f.png)

If you give an incorrect name, so there is no package in CRAN, then it says so.  

This seems to be an acceptable package name, but it is not (currently) in CRAN.  I get the same message with the mmtable2 package?

The splines package has been archived.  Perhaps a better message could be

`Not a current CRAN package.  Perhaps it has been archived.`

**Comment by N-thony** [comment]
@rdstern I also noticed that when you click Reset button nothing happen.
![image](https://user-images.githubusercontent.com/68591383/197519146-dc9dfcd2-4c59-4f3a-b78b-3d707bf3f866.png)
