### ISSUE TITLE
Please check possible error in results for 3-way frequencies dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7741]
In writing the help for the Describe > 2/3 Variables > 3-way frequencies dialogue I suggest the R-commands are giving the wrong answers.  I hope someone can check this - possibly also using RStudio to confirm.

I have been using our usual rice survey data.  I have reordered the fertgrp factor, so it goes 0, 0.5-2, > 2, but that is not particularly relevant (I have also tried without that).

Here is a simple example:
![image](https://user-images.githubusercontent.com/11226469/183395898-9ba1cd6d-66da-48f9-aaec-c5149c796b01.png)

Here are some answers:
![image](https://user-images.githubusercontent.com/11226469/183396253-1aaa330f-1b5b-44d2-bd6b-04d3e1611414.png)
 The numbers are all correct, but associated with the wrong villages!  The table shows that Nanda has 7 observations.  If you look at the data it is Kesent that has 7 and Nanda has 14 observations.

The graph option is also similarly wrong, i.e. in the villages associated with the frequencies.

If you try with a numeric sort of factor, then I think it is ok.  For example make fert the third variable above (and variety and village the first 2, then I think it is ok.)

Please can this be investigated - and quite urgently.  It could be our R-code, but I don't see how - here it is:

```
# Code generated by the dialog, Three Variable Frequencies
survey <- data_book$get_data_frame(data_name="survey", drop_unused_filter_levels=TRUE)
survey %>% dplyr::group_by(village) %>% dplyr::select(variety, fertgrp, village) %>% sjPlot::sjtab(show.summary=FALSE, digits=0, fun="xtab")
```

**Comment by N-thony** [comment]
@derekagorhom can you try this? I'm happy to support you.

**Comment by derekagorhom** [comment]
> @derekagorhom can you try this? I'm happy to support you.

ok i will have a look at it

**Comment by N-thony** [comment]
@derekagorhom I think this is fixed in PR 7916, have a look.
