### ISSUE TITLE
Translation issue in Convert to Numeric dialog

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7742]
Using the French translation of R-Instat 0.7.7 the explication giving by Convert to Numeric dialog (right click on the column > convert to numeric) is  in English  (refer to figure ).

![image](https://user-images.githubusercontent.com/106779233/183617972-b957ba02-6d7a-4738-809e-4f6d000f4646.png)

**Comment by lloyddewit** [comment]
This is covered by issue #3721
