### ISSUE TITLE
Translation issue trying to close R-Instat

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7746]
Using the French translation of R-Instat 0.7.7 the confirmation message trying to close  R-Instat is in English (refer to figure ).

![image](https://user-images.githubusercontent.com/106779233/183624214-ff0943e9-5e1c-4246-8f32-47bf6cf3eca7.png)

**Comment by lloyddewit** [comment]
This is covered by issue #3721
