### ISSUE TITLE
Translation issue on Data Frame, Check Data, Column:Numeric, and Data Reshape sub-menu of Prepare menu

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7749]
Using the French translation of R-Instat 0.7.7 there are some sub-menus text and dialog text in **Prepare** menu which are still in English (refer to figures )

![image](https://user-images.githubusercontent.com/106779233/183629687-7e800548-4b9b-4ef5-a774-e81706e014be.png)

1- Prepare>Data Frame
![image](https://user-images.githubusercontent.com/106779233/183630219-11be310b-5275-4460-a15c-59adfd7bc447.png)

2-Prepare>Check Data
![image](https://user-images.githubusercontent.com/106779233/183630708-14273cd7-1835-42fd-a2f4-0665988c9a63.png)

3-Prepare>Column:Numeric (all dialog text  are not translate)
![image](https://user-images.githubusercontent.com/106779233/183630950-0ce85ebc-7b29-41fb-816a-7adf93deabb0.png)

4-Prepare>Data Reshape
![image](https://user-images.githubusercontent.com/106779233/183631650-4815108d-8c2a-489c-a750-c2f18bdba782.png)

**Comment by MeSophie** [comment]
I noticed that  **Random Split...** and **Scale/Distance...** are already translate in Crowdin but still in English in R-Instat. For **Merge (Join)...** and **Stack (Pivot Longer)...** I fixes it in Json file.
Please @lloyddewit and @N-thony  can you have a look ?

![image](https://user-images.githubusercontent.com/106779233/196410461-b3adeb07-a5b5-42ba-9eb1-a9d65d0672c7.png)

![image](https://user-images.githubusercontent.com/106779233/196412487-9399e88b-e0cb-40e2-857c-ddfbfbfab6ac.png)

![image](https://user-images.githubusercontent.com/106779233/196413094-e56c0b79-ff42-4652-8f91-86053e4efd40.png)

It is also the same  with **Number of Preview Rows:** (Tools>Options>Import).

![image](https://user-images.githubusercontent.com/106779233/196415278-88f2a952-8cbb-4710-9936-6170e76e5f73.png)

![image](https://user-images.githubusercontent.com/106779233/196415349-123cf5b1-623c-45b1-98de-d8b53be7a40d.png)

**Comment by N-thony** [comment]
@MeSophie good, it is probably that those controls are not in the database or maybe they are but named differently.
@Vitalis95 would you like to look at it?

**Comment by Vitalis95** [comment]
@MeSophie , could check if these texts are in the Json file. You can add them if there are not there so that I can add them to the database
![image](https://user-images.githubusercontent.com/89011415/196430070-9daa82b1-7c00-4435-b4b7-be4d2566c246.png)
![image](https://user-images.githubusercontent.com/89011415/196430214-ed6bec71-177c-49dc-8cc3-b5e1678b0449.png)

**Comment by MeSophie** [comment]
@Vitalis95 I added **Display As Data Frame, Centre, Whole Data Frame and Distance.**  the rest was already in the Json file.

**Comment by lloyddewit** [comment]
> @Vitalis95 I added **Display As Data Frame, Centre, Whole Data Frame and Distance.** the rest was already in the Json file.

@MeSophie I understand these were added in PR #7921, it's always good to reference the PR.

@Vitalis95 did you start this yet? if not I'm happy to look at it, let me know

Thanks!

**Comment by Vitalis95** [comment]
@lloyddewit , I have started looking at it

**Comment by lloyddewit** [comment]
@Vitalis95 Thank you for the database changes in PR #7926.
The prepare menu now seems to translate completely apart from 2 strings.
Tools/options/import and Prepare/Data Reshape/Scale Distance dialog also have some untranslated text.
I think all of these should be reolved when PR #7908 and PR #7927 are merged, apart from:
- Number of Preview Rows:
- Scale/Distance
- Selected Variables
- New Data Frame Name:

![image](https://user-images.githubusercontent.com/57253949/197486149-3d77af98-94a5-4b07-967f-d86dd73fa660.png)

![image](https://user-images.githubusercontent.com/57253949/197487302-235851f4-c87b-4d7c-b0b1-2afc17ef5570.png)

![image](https://user-images.githubusercontent.com/57253949/197492836-5d75a03f-f7a6-43ec-bd01-0694809108e6.png)

![image](https://user-images.githubusercontent.com/57253949/197493247-9bdb70cb-f178-46db-be6f-102180ae608a.png)

**Comment by lloyddewit** [comment]
PR #7908 has now been merged. Most of the problems above have been resolved. The only remaining problems are shown below. I think we can solve most of these by adding text to the JSON file. When PR #7927 is merged, then I'll test again.

----

In the Tools/Options dialog, the window needs to be moved to give space for the Russian translation:

![image](https://user-images.githubusercontent.com/57253949/198529965-2065a518-8b70-4ed3-a4df-1996873209a4.png)

![image](https://user-images.githubusercontent.com/57253949/198530065-17000da9-b4bc-48a5-851f-47818ba079d0.png)

In the Prepare / Data Reshape menu:

![image](https://user-images.githubusercontent.com/57253949/198530971-0eff23aa-8985-47d7-8db2-778c645bcc0a.png)

In the Prepare / Data Reshape / Scale/Distance dialog:

![image](https://user-images.githubusercontent.com/57253949/198534333-b7bae9cf-6c49-4e54-b04a-e08450ea0b28.png)

**Comment by N-thony** [comment]
@MeSophie can you check if this is now fixed and probably close this issue?

**Comment by MeSophie** [comment]
@N-thony  we still have **Selected Variables** , **Scale/Distance**,  and **Whole Data Frame** in english.

![image](https://user-images.githubusercontent.com/106779233/202925645-06be1ce2-fba3-4954-b700-c0c405931b32.png)

![image](https://user-images.githubusercontent.com/106779233/202925670-42a67e71-781b-4bb2-b47a-4fb747325140.png)

![image](https://user-images.githubusercontent.com/106779233/202925715-8d3c09f4-552d-49f4-aac0-ce0a086fc936.png)

**Comment by N-thony** [comment]
@MeSophie I think those controls are missing in the database, @Vitalis95 can you check if they are missing and add them in the database?
