### ISSUE TITLE
Translation issue in Check Station Location Dialog.

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7768]
By using R-Instat 0.7.8, we have some words in Check Station Location Dialog (Climatic>Mapping>Check Station Location Dialog) which are not translate. **Also all the comments generated by comment box are in English no matter the dialog we are using.**
![image](https://user-images.githubusercontent.com/106779233/184340428-1dacfa95-e9d4-478a-b6da-33381e763661.png)

**Comment by N-thony** [comment]
@lloyddewit this is fixed except the text in the box i.e 
![image](https://user-images.githubusercontent.com/68591383/188596579-cd9237de-34cf-42af-b3cb-d2ef031f7f46.png)
