### ISSUE TITLE
Dialogues where the layout in French is incomplete

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7792]
I simply list dialogues I have found where problems remain:
I have started with the Climatic menu:

a) Export to cpt.  The top radio buttons 2 and 3 seem incomplete

b) Climatic > Tidy and Examine > Stack.
![image](https://user-images.githubusercontent.com/11226469/185665578-e3e10830-3b06-4262-9221-4227b9c4d46b.png)
The plusiers line may be inclmplete.  It is certainly odd when the checkbox is checked.
c) In the same dialogue - and in many, the line below is complete, but without the colon that is there in English and it would be good if the receiver were moved just a bit to the right.  See the same in the unstack dialogue and append, and others.
d) One way frequencies.  Last option, when checked the receiver overlaps the label.  (The translation to English is odd if the Lan button is pressed.  It stays in French.)
e) Dates - nothing found
f) Define climatic Towards the bottom check duplicates is incomplete in French.
g) Climatic >Check data > Inventory Missing button at top.  Then when save details is checked the control needs to move right.
h) QC rainfall dialogue - missing months button is incomplete in French.  And next control overlaps.
![image](https://user-images.githubusercontent.com/11226469/185671540-87bb93dd-c13f-4a50-a372-10b94b799af1.png)
i) The position control, see below - the C is not available in the French.
![image](https://user-images.githubusercontent.com/11226469/185672079-44725732-aa07-460b-b39b-3fdd1370c28a.png)

j) The Climatic > Prepare menu now.  Starting with Transform.  Multiple Spells at the top.  Is that complete in French?
![image](https://user-images.githubusercontent.com/11226469/185672527-1e78cece-be3b-481a-a999-b889ff0bd5c9.png)
k) Transform there Day length  in incomplete see below:
![image](https://user-images.githubusercontent.com/11226469/185673895-8ced8315-17d3-4539-a3d1-76e742ea2254.png)

**Comment by rachelkg** [comment]
@rdstern issue 
a) changed layout and updated crowdin translation
b) I have passed this on to Antoine as it was too complicated for me see issue: Layout issues with french version of Stack (Pivot) dialog #7794
c) is a problem with the Save.urc I would love to see it resolved but have not been able to get anyone to work on it, I have mentioned it again to Antoine in issue #7794. Please see issue #6700 for more details[https://github.com/africanmathsinitiative/R-Instat/issues/6700]
d) I resolved most of the issues in this but found a new one which I couldn't fix so passed on to Antoine in issue: French Layout issue in One Variable Frequencies Dialog #7795 (It looks like maybe the french text is under the english but that doesnt me sense
![2022-08-19_14-10-21](https://user-images.githubusercontent.com/85707390/185708030-8267f107-a3de-4ec3-b1d3-628b2df32c27.png)
e) nothing to do 
f) changed layout
g) changed layout
H) changed layout
i) changed layout
j) yes that is the complete translation
k) changed layout

I have just the changes up in pull request #7796 @rdstern please check it.

**Comment by rachelkg** [comment]
Please close this once you have checked the pull request as I have made separate issues for the bits Antoine will do. 

Thanks, 

Rachel

**Comment by lloyddewit** [comment]
I think this is all resolved in R-Instat 0.7.10
