### ISSUE TITLE
Layout issues with french version of Stack (Pivot) dialog 

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7794]
Hello @N-thony, 

This one looks too complicated for me to feel confident changing it. Please could you do it? 

I have circled the layout issues in red. The Nouveau nom....issue is a recurring issue with the Save.urc which affects many dialogs so it would be great to finally have this solved. 

There are also some database issues as a number of items are not translated, what would you like me to be doing about these?  

![2022-08-19_13-21-42](https://user-images.githubusercontent.com/85707390/185701695-8375e9a4-bab8-4295-b66e-ba3d2c7d3b7e.png)
![2022-08-19_12-27-56](https://user-images.githubusercontent.com/85707390/185702574-f089038c-9a91-49c5-a0c0-490de7899ba3.png)

Thanks, 

Rachel

**Comment by rachelkg** [comment]
Here are some more examples of the Save Urc issue
![2022-08-19_13-34-28](https://user-images.githubusercontent.com/85707390/185703413-ac3f5ed9-d031-4235-9f1d-035cd9090728.png)
![2022-08-19_13-34-44](https://user-images.githubusercontent.com/85707390/185703417-21379dda-fe5a-4740-b224-9895111f162a.png)
![2022-08-19_13-36-36](https://user-images.githubusercontent.com/85707390/185703422-7bffd394-6360-4e22-9143-de099e970537.png)

Please see issue #6700 for more details[https://github.com/africanmathsinitiative/R-Instat/issues/6700]

**Comment by N-thony** [comment]
@derekagorhom any progress?

**Comment by N-thony** [comment]
@derekagorhom can you check if this is fix then close it?

**Comment by N-thony** [comment]
> @derekagorhom can you check if this is fix then close it?

@derekagorhom can you check if everything is solved here and then close it?

**Comment by lloyddewit** [comment]
Problems resolved in R-Instat 0.7.10
