### ISSUE TITLE
Small improvement to the File > New Data Frame dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7799]
I am now using this dialogue for some videos.  Please could @N-thony check that these are sensible.  Then perhaps they can be done by @anastasia-mbithe who is currently doing something else on this dialogue.
a) There is a default for the numeric option that currently says 1,10.  I keep changing that, when the dataframe is longer than 10 rows.  Please change it to 1,1000000.  Then it is still ok if the data frame is shorter.
b) When the option is checked to be able to supply the initial names and types, make the default to have the first variable numeric with the 1,1000000 set, see below:

![image](https://user-images.githubusercontent.com/11226469/185786094-6637aee7-4ded-4281-84d2-04305eae6e90.png)
 
(This is not the case if that option isn't checked.  Then - as now, you just get 2 variables each with NA.)

**Comment by N-thony** [comment]
@rdstern yes this seems simple, @anastasia-mbithe can do it.

**Comment by N-thony** [comment]
@anastasia-mbithe any progress?
