### ISSUE TITLE
Bug in Climatic Inventory Dialog

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#7803]
The climatic inventory dialog throws an error shown below.
<img width="353" alt="inventory" src="https://user-images.githubusercontent.com/21179007/185988003-3a60758d-5644-4d8e-acff-66fe66ba174a.png">

@N-thony this can also be fixed by anyone. Thanks

**Comment by Vitalis95** [comment]
@N-thony, I have used Dodoma dataset with defaults but I could not get that bug, @Patowhiz are there options you selected?

![image](https://user-images.githubusercontent.com/89011415/186107203-a58ec0eb-7761-4db7-99b5-8383be218f57.png)

**Comment by Vitalis95** [comment]
I am closing this issues after discussing it with @Patowhiz , I couldn't get the bug from my side.
