### ISSUE TITLE
Extend the integer keyboard still further

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7818]
There is still more in the primes package we can add.  @anastasia-mbithe I am really pleased with the way you have been able to implement this keyboard.

a) Do we still need the prime key at the bottom.  I am not sure what it is adding now?
b) nth prime needs a tooltip, e.g. Gives the n-th prime.  For example nth_prime(1000)= 7919.  Also when you include the parameters, it is given as `n =`.  That is incorrect, it should be `x =`.
c) Change the function behind Factorize.  Currently it uses the function in DescTools.  I would prefer the one in primes, i.e. primes::prime_factors( )
d) Add a row giving gcd, scm, coprime.   The tooltips are as follows:
`gcd `Greatest common divisor, for example gcd(18,42) = 6
`scm` Smallest common multiple, for example scm(18,42) = 126 (= 7*18 & 3*42)
`coprime` Also called mutually prime, for example coprime(30,77) = TRUE. (30 = 2*3*5, 77 = 7*11)
e) Add phi (maybe on same row with gcd, scm, coprime) tooltip is Euler’s Totient Function. For example phi(12) = 4 (1, 2, 5, 7 are less than 12 and coprime)

Then also:
f) Move the 2nd row down to a block on its own. 
g) Add 6 keys labelled twin, cousin, sexy and then on another line third, triplets, k_tuple

The tooltips are: 
Twin primes, for example, twin(0,10) gives (3,5), & (5,7)
Cousin primes, for example cousin(0,20) gives (3,7) & (13,17)
Sexy primes (6 in Latin is sex!), for example sexy(0,40) gives (23,29) & (31,37)
Third cousin primes, for example third(0,100) gives (89,97)
Sexy prime triplets, for example triplets(0,100) gives (47, 53, 59)
k_tuple general formula for all these keys.  For example k_tuple(0, 10, c(0,2)) gives twin primes

The full function names are:
k_tuple(min, max, tuple)
twin_primes(min, max)
cousin_primes(min, max)
sexy_primes(min, max)
sexy_prime_triplets(min, max)
third_cousin_primes(min, max)

The code I used was, for example:
`rep(primes::third_cousin_primes(0,10000),len=1000)`

for a data frame on length 1000.  It should fill in the length automatically.  This is not ideal, but it works.  It repeats the sequences to the length of the data frame.
I would prefer to have the sequence just once and then use the `length` function to make the resulting variable the right length.  This is a bigger task.  Possibly it adds a length option in the Position button.

**Comment by anastasia-mbithe** [comment]
@rdstern , for point (a) we had the prime key to generate prime numbers equal to the number of rows. For instance, we could use it to generate the first 1000 prime numbers. So, should we keep it, or it's not needed?

**Comment by N-thony** [comment]
@anastasia-mbithe how is it going with this?
