### ISSUE TITLE
Check on stem and leaf in Describe > One Variable > Frequencies dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7820]
For @N-thony to allocate.

Try any set of data, e.g. the usual survey data plotting the yield.
Use Describe > One Variable > Frequencies > Stem with the yield.

Nothing seems to be plotted.  

This is a text graph, not a high-resolution plot.  I am not sure whether that is the problem?

**Comment by Ivanluv** [comment]
@rdstern  the `stem` function does not seem to produce high resolution plots. All examples in the `stem` function documentation are  producing text graphs

**Comment by rdstern** [comment]
Yes, but the merged #6858 seemed to produce these text plots earlier.  It was by @EstherNjeriLiberatta and I am not sure what has changed since, so we no longer get the graph.  Oh - I tried again and now we do!!!  I'll check more, but close meanwhile!
