### ISSUE TITLE
Improvements to Define New Filter dialog

### ISSUE THREAD

**Issue by Vitalis95** [africanmathsinitiative/R-Instat#7860]
@Patowhiz  In Filter Rows dialog, I am using survey dataset and I want to filter Kesen and Nanda Villages, the control `Select Levels:` should update automatically to show that I have selected 2 Levels i.e `Levels: 2`

![image](https://user-images.githubusercontent.com/89011415/189122583-2baed282-5ca8-48c1-ab3e-57763f98b45f.png)

**Comment by N-thony** [comment]
@Vitalis95 how is it going with this? Also remember to update the board.
