### ISSUE TITLE
Adding a new lists keyboard into the calculator

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7886]
Here is an example of a dataset, where a variable contains a set of simple expressions
[superabundant20.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/9597668/superabundant20.xlsx)
Here it is in R-Instat:
![image](https://user-images.githubusercontent.com/11226469/190988252-ffd9cae2-8782-4ad4-ba5c-5bea86c28d6b.png)
In this data frame I got the 3rd variable from the integer keyboard, using the divisors key.  I then transformed the data into the 4th variable.  
I would like to have a simple way of evaluating that variable.  We are (I assume) doing such things behind the scenes, because an initial exploration led me to the `pander`, `evaluate` and `lazyeval` packages.  And all these are already installed in R-Instat.
It would be a good addition to the Prepare > Column: Numeric > Transform dialogue and also (of course) in the Calculator.
It would be good to know the feasibility of this soon, even if there isn't time soon to do the programming.  I assume it can be done by someone in Innodems, but @lilyclements might be quicker in working out whether and how, it should be done.

(Currently I use the third variable, a) subset from 3 to -2 to get rid of c(   ), b) then split to put it into multiple columns, c) and then make them numeric, and d) then do a row summary.)

**Comment by rdstern** [comment]
@lilyclements I asked Danny about this and he has put me right, in an exciting way.  If you take the divisors, in the example above, then they are in an `R list`.
 And R can operate on lists.  He suggested sapply, which works fine, but I wonder about the difference between sapply and vapply?

Anyway this is exciting (for me anyway - and I hope more generally.  All we need for what I wanted is 

sapply(divisors,sum)

I tried and here it is for a data frame that started with the numbers 1 to 100, and then got the prepare > calculator > integer > divisors key, which gives a `list`. 

![image](https://user-images.githubusercontent.com/11226469/206899922-0d2d9ec5-ae97-4618-a1fe-e0c2240d42be.png)

But here I tried with most of the functions from the summary keyboard.  And they (almost all) seem to work.  

So could we please have a new Lists keyboard.  Base it on the existing Summary keyboard.

Keys could be as follows:
a) length, sum, mean, min, max
b) median, mode1, var, sd, mad 
c) IQR, distinct, anyDup, first, last
d) nth, quantile, fivenum, ssq

Explanations and code to come.

**Comment by lilyclements** [comment]
@rdstern looks good! Are you happy with the code needed for this new keyboard? (I assume so if it has come from the current code in R-Instat).

> And R can operate on lists. He suggested sapply, which works fine, but I wonder about the difference between sapply and vapply?

In the documentation for the `apply` functions, it says that 
"`vapply` is similar to `sapply`, but has a pre-specified type of return value, so it can be safer (and sometimes faster) to use." 

For example:
```
a <- NULL
a[[1]] <- c(1, 2, 3, 4)
a[[2]] <- c(1, 2, 3, 4, 5, 6, 7)

sapply(a, sum)
vapply(a, sum) # gives an error
vapply(a, sum, FUN.VALUE = numeric(1)) # is fine because FUN.VALUE is specifed
```

**Comment by rdstern** [comment]
@lilyclements thanks for the input.  There is currently a (small?) problem on the display of the data in the R-Instat grid, that @N-thony is fixing - and I think he is working on that now.

a) Then I am happy with that keyboard above - so far - as the top half.  It should be headed Numeric
Then there will be another set of keys that say String (Character) and give functions to deal simply with a list of strings.  I'll give that below.

b) I am excited by this, but must be careful that we don't take it too far - at least for now.  We will still need a bit more to get data into these lists and then out again - into multiple columns.  

c) In particular we already have a dialogue Prepare > Column: Text > Split to split a string into components.  That produces many variables, but `stringr::string_split(string_variable, " ", Inf)`  works fine in the calculator and produces a list.  So we need to add the key.  (Perhaps we have an option in the dialogue, with the default being as now.   

d) We already have the Prepare > Column: Text > Combine dialogue in the calculator and it (I assume) can produce a text or a list?




One use is in the gtextra package, where a cell in the table can be a simple line graph (or histogram).  And that is when the column contains a list.

And, in the example above, the divisors are an example of a multiple response!  That's a pretty neat idea, for when we come to look at multiple response more generally in our tabulation!

I know lists in general can be more exciting, but we will probably stop with these simple lists here, i.e. where all the elements are either numeric or character.  Maybe later we will have some more examples.

**Comment by rdstern** [comment]
@derekagorhom could you now have a go at this new keyboard?
It is called `List`
Here are the keys:

a) length, sum, mean, min, max
b) median, mode1, var, sd, mad
c) IQR, distinct, anyDup, first, last
d) nth, quantile, fivenum, ssqd, missing

For almost all these are just simple adaptations of the function in the summary keyboard.
a) So, for length it is:
`sapply(column, where cursor is ,length) ` so the same function as the summary keyboard.
`sum, mean, min, max` are the same on this row.  Just the command, the na.rm=TRUE comes below.
b) `median, mode1, var, sd, mad `are the same as in the summary keyboard.  Note that mode1 is statip::mfv1
c) `IQR, distinct, anyDup, first, last` are also the same as the summary keyboard. Some are from dplyr, but that's fine. 
d) `nth, quantile, fivenum, ssqd, missing `  The first 2 are simple.  
1) nth is from dplyr as in summary.  
2) quantile is simpler than in summary, because we'll just allow one quantile here.  So sapply(  ,quantile,prob=0.5) could be given with 0.5 as the default.
3) For now, omit fivenum
4) ssqd is to be the sum of squares of the digits!  
5) missing, just delivers the code` ,na.rm = TRUE`.  (This isn't needed as it is in the summary keyboard, so good to have a key to explain it and then it can easily be added to any command when needed.)

**Comment by derekagorhom** [comment]
![image](https://user-images.githubusercontent.com/76208189/213432968-c6929a37-8889-41c9-8bac-577f0c6345ae.png)

**Comment by rdstern** [comment]
I have had advice from @dannyparsons on other functions on the lists - and particularly on changing the numbers in a list variable to produce another list.  I write these now and they will be another section in this keyboard, but needs to wait until it is complete.

Here is an example:
`sapply(pascal,function(x) round(x/sum(x)*100,3))`
This might be a `round` key.  
Perhaps 
`sapply(  ,function(x) x/sum(x)) `might be a `proportion` key
`sapply(  ,function(x) 100*x/sum(x))` is a `percent` key
`sapply(  ,function(x) round(x,3))` would be `round`
And many other functions from the maths keyboard could also be included, so:
`sapply(  ,function(x), sqrt(x)) `could be a `sqrt` key and there are others.

`sapply(  ,function(x) x/10)` could be a curious `+-*/^` key.  The default is dividing by 10, but you can change the operator and value.

**Comment by derekagorhom** [comment]
> @derekagorhom could you now have a go at this new keyboard? It could be called `List (numeric)` Here are the keys: They are in a block called `Summary:`. There will be a second block - possibly in a separate pull request - called `Calc:`. That's described below this message.
> 
> Anyway in `Summary:` a) length, sum, prod, min, max b) range, mean, median, mode, mode1 c) ssq, var, sd, mad, IQR d) distinct, anydup, first, last, nth e) quantile, digitsum, sumd, fivenum, missing
> 
> For almost all these are just simple adaptations of the function in the summary keyboard. a) So, for length it is: `sapply( ,length) ` so the same function as in the summary keyboard. `sum, prod, min, max` are the same on this row. Just the command, in this keyboard. (the na.rm=TRUE comes below). For example prod is `sapply( ,prod) ` b) `range, mean, median, mode, mode1` For range do, `lapply( , range) ` Here mean, median, mode and mode1 are the same as in the summary keyboard. Note that mode is `lapply( ,statip::mfv)` and gives another list. And mode1 is `sapply( ,statipmfv1)`. c) `ssq, var, sd, mad, IQR, distinct ` For ssq do `sapply( , function(x) {sum(x*x) } )`.. The rest are the same as the summary keyboard, with the sapply first. Some are from dplyr, but that's fine. d) `distinct, anydup, first, last, nth, quantile `
> 
>     1. distinct and anydup are simple.
> 
>     2. first, last, nth are from dplyr as in summary.
> 
>     3. quantile is simpler than in summary, because we'll just allow one quantile here.  So `sapply(  ,quantile,prob=0.5)` could be given with 0.5 as the default.
> 
> 
> e) `quantile, digitsum, sumd, fivenum, missing`
> 
>     1. quantile is `lapply(  ,quantile,prob=c(0.2,0.5,0.8))` as the default.
> 
>     2. digitsum just uses the key from the integer keyboard, so `sapply(  ,DescTools::DigitSum)`.  Then sumd is `sapply(sapply(  ,DescTools::DigitSum),sum)`.
> 
>     3. fivenum is lapply(  ,fivenum)
> 
>     4. missing, just delivers the code` ,na.rm = TRUE`.  (This isn't needed as it is in the summary keyboard, so good to have a key to explain it and then it can easily be added to any command when needed.)

@rdstern sorry to disturb you but could you explain how the code for `var, sd, mad, IQR, distinct, anydup, first, last and nth` should be for the calculator because i keep getting no output responses when i try producing results

**Comment by rdstern** [comment]
@derekagorhom I assume your question above is now resolved, ad you seem to have almost finished these two parts of the keyboard.  The sumd should be for an ordinary list, because it uses the DeskTools functions, which works for individual values.  It gives the sum of the digits in each number in the lists.  The code is above.

**Comment by rdstern** [comment]
A third (and hopefully last) section in this keyboard is called Transform and uses keys from the Transform and logical keyboards.

Three rows of 5 keys each:  First row:
a) `sort` with code `sapply(  ,sort, FALSE)` and tooltip `sort values into ascending order.  (Change FALSE to TRUE for descending)`
b) `rank` with code `sapply(  ,rank)` and tooltip `ranks of values with average for tied values`
c) `lag` with code `sapply(  ,dplyr::lag)` and tooltip `lag values by one observation, so NA starts each list`
d) `lead` with code `sapply(  dplyr::lead)` and tooltip `opposite to lag, so NA is last value`
e) `diff` with code `sapply(  ,diff)` and tooltip `differences between successive elements`

Second row:
a)` scale` with code `sapply(  ,function(x) {round(scale(x),3)})` with tooltip `scale each list, by subtracting the mean and dividing by the sd`
b)` cumsum` with code `sapply(  ,cumsum)`  with tooltip `cumulative sum of elements in each list. (replace by cummin, cummax, cumprod, or dplyr::cummean for other cumulative functions)`
c) `movsum` with code `sapply(  ,zoo::rollsum,3,NA)` with tooltip `moving sum of elements in each list (replace by rollmax, rollmean or rollmedian for others)`
d) `rev` with code `sapply(   ,rev)` with tooltip `reverse the data in each list.`
e)` omit.na` with code sapply(  ,na.omit) with tooltip `drop NA values`

Third row
a) `ifelse` with code` sapply(  , function(x) {ifelse(x < 10, -1,1)})` with tooltip `replace the condition and the TRUE, FALSE values with those of your choice`
b)` mod (%%)` with code `sapply(  ,function(x) {x %% 10})` with tooltip `gives the remainder from division by 10, or a number you choose.  For example 28 %%8 = 4`
c) `div (%/%)` with `code sapply(   ,function(x) { x %/% 10})` with tooltip `gives the value after integer division by 10, or a number of your choice.  For example 28 %/% 8 = 3`
 d) `>` with code `sapply(   , function(x) { x > 10 })`  with tooltip `gives TRUE or FALSE depending on the condition.  (Use >=, <, <=, ==, != as well)`
 e) `duplicated` with code `sapply(  ,duplicated)` with tooltip `gives TRUE for any duplicates and FALSE otherwise`
