### ISSUE TITLE
The Factorize Key Error

### ISSUE THREAD

**Issue by berylwaswa** [africanmathsinitiative/R-Instat#7895]
I have been testing the calculator and have worked with the basic, integer, probability, and transform keyboards. 
I was working on the rice/chess problem when I got stuck because of an error on the factorize key, on the integer keyboard. 
 I wanted to produce the factors for numbers in a column but instead, it kept bringing an error.
On the first attempt, I got an error that said I had not installed the primes package, so I did. 
Then I got another error that I have now shared a screenshot of.

I started by creating a data frame with one column named x1 with 64 rows.
Then added a column of x1-1 and named it x1a
Next I added a column of 2^x1a. Here we have found the number of rice grains on each square.
Next to find the total sum of rice grains in all squared I used Prepare>Calculator>Transform Keyboard(Cumsum).
I then went to the integer keyboard in the calculator to find the prime numbers using is_prime key.
This worked okay but on wanting to find the factors for the numbers in the column for the total number of rice grains I got an error. Below are the steps I followed and got the error;

1. Go to Prepare>Column: Calculator
2. Click on Basic, then choose Integer
3. Click on factorize and add the variable to factorize
4. See an error

When the procedure is followed, I expect to have a column of the factors of each of the numbers in the column I am factorizing.

Here are two screenshots that follow each other when I click Ok.
![f2](https://user-images.githubusercontent.com/28622260/192753413-d898f181-1624-45d8-a55b-0a8db336dbc3.PNG)
![factors](https://user-images.githubusercontent.com/28622260/192753423-28c5f744-782a-4330-b8e1-2345b779b631.PNG)

I hope this can be fixed soon because the rice/chess problem is in the series of videos to be produced soon.

**Comment by N-thony** [comment]
@berylwaswa I think this is due to your R version, I found out that 4.1.3 has this function under `primes package` so you need to upgrade your R version and run again

**Comment by berylwaswa** [comment]
Okay thank you.

**Comment by anastasia-mbithe** [comment]
Since we solved this issue by removing Primes::prime_factors() function from the factorize key and using only DescTools::Factorize() function which works well, am closing this issue.
