### ISSUE TITLE
Minor bug on Prepare > Data Frame > Rename

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7938]
I think this is simple for @N-thony to do, or allocate, as it has happened on other dialogues.  But it just may be tricky - and then we have to leave it as a "feature" rather than a bug.

When you rename multiple and then click ok when you are still in the last variable you have renamed then this last variable is ignored.  I don't know enough to suggest that the Ok key should close the previous control, or clicking somewhere else could close it?  I continually type new names as a, b, c and then Ok, to find the new names are a and b but not c!

**Comment by N-thony** [comment]
@mmulahvictor any progress with this?

**Comment by rdstern** [comment]
@N-thony just to report that this issue arose in the recent workshop and was one of the minor inconveniences for the participants.  @mmulahvictor remains silent as far as I am concerned, even though I thought he was returning a month ago.  Should we give up on him?
