### ISSUE TITLE
Adding Expand to the Stack dialogue?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7941]
I need a second opinion on my solution and the location of this function.  I have been very pleased to find it.

It builds on the problem I raised in #7929 where the data were frequencies.  I wanted the be able to stretch out the data to show how it would have looked in "ordinary" form.  

I have now found a solution in the package called `vcdExtra`.  We already have vcd (Visualising Categorical Data) and have recently added `vcdExtra`, which contains many interesting data sets and a function we need, see below.  In a vignette called [Creating and manipulating Frequency Tables](https://cran.r-project.org/web/packages/vcdExtra/vignettes/A_creating.html) we have the following:

![image](https://user-images.githubusercontent.com/11226469/198544179-ad387dce-2a8a-432c-90f7-10227574d920.png)

So this generalises the task from Beryl where we entered a single variable plus frequencies.  

But, particularly for teaching  it would be good to show what it would look like as "ordinary data".  Now I think this is the function called expand.dft, from the vcdExtra package.  

But, where should it go?  I suggest it is not important enough to be a menu item on its own.  I think of it as a bit like stack (pivot longer) so suggest it should become a third button there.  It could be just called Expand.  

It would have the usual data selector.  Then a multiple receiver called Factors: and a single receiver, called Frequencies:
This is an option in the vcdExtra function to change the names of the resulting factors.  I suggest this be ignored.
Then the resulting data frame is specified.

The columns are made into a data frame and then handed to the function.

Please check what happens if the combination of factor levels is less than the number of frequencies.  So, in the example above, what would happen if you only gave a single factor?  I assume we should trap that.  On the other hand I assume there could be examples with zero frequencies and that row could then be omitted.  So, in the example above would the function still work if one frequency were zero, so there were just 5 rows of data.  Or should there always be exactly 6 rows.  So should the check be that the combinations of factor levels is equal to the number of rows of (frequency) data, or less than or equal to? 

Perhaps @lilyclements could do a quick check that this is all sensible.  But I am now even more convinced that this would be a useful addition.  If so, it should be a simple addition to make.  And,  @N-thony has already specified that the vcdExtra package needs to be added.

My reasoning is that most of the datasets in the tidyr package and also those in histdata are frequencies.  So they appear more often than I had thought before.  Good that they are well understood!

**Comment by N-thony** [comment]
@rdstern I have added vcdExtra in PR #7934

**Comment by rdstern** [comment]
@N-thony great - thanks
