### ISSUE TITLE
Improve the New Data Frame dialogue

### ISSUE THREAD

**Issue by berylwaswa** [africanmathsinitiative/R-Instat#7957]
@N-thony on the new data frame dialogue, when I change the type of the first variable to a factor, the 1,1000 is not cleared. Please make it such that when the variable is a factor the 1,1000 is cleared since it's not relevant anymore. Below is an image of what the dialog looks like when the first variable is changed to factor.
![New Data Frame 11_10_2022 2_21_16 PM](https://user-images.githubusercontent.com/28622260/201081165-3486d388-bef6-41dc-8432-73ab42c85537.png)

**Comment by rdstern** [comment]
@berylwaswa in the video you could (behind the scenes) change the 1,1000 to NA, which is what the correction will probably do.
@N-thony that correction isn't quite so obvious, but (for simplicity) I suggest that is what you do?  It would be ok for the 1,1000 to apply, even if it is a factor, though it doesn't now.  If I just make it a factor it currently makes it just the level 1, which is clearly wrong.
One (interesting) possibility is that, If it stays as 1,0000 and then Beryl puts in 2 values - as the levels in the example she does, (say a,b) then it effectively becomes 1,2 to be consistent. and gives the labelled values as a,b,a,b....
At the same time I suggest you drop (or do better) for the last 2 options, namely letters(1,10) and LETTERS(1,10).  Let's try and do better as follows:
If you keep them then you need to put the rep in the code so the data frame can be any length.  (Try now with a data frame of length 14 and it gives an error.  And also it will then work fine for factors or character.  So if those variables are left as numeric or integer, then the R command that is generated should change the variable to be character.
