### ISSUE TITLE
Uninstalled apsimx package.

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7974]
I am working on a new dialog (apsimx examples) for crop simulation. This dialog needs the apsimx package to be able to run its models package which is not yet installed in R-instat. Please can this package be part of the pre-installed package?  

![image](https://user-images.githubusercontent.com/106779233/203497051-9204a1a2-08d2-4d99-b136-54f0ae853d50.png)

**Comment by rdstern** [comment]
@N-thony can you arrange that, either by writing the corresponding issue in the required way, or by showing @MeSophie how she can do that.

**Comment by N-thony** [comment]
> @N-thony can you arrange that, either by writing the corresponding issue in the required way, or by showing @MeSophie how she can do that.

@rdstern sounds good
