### ISSUE TITLE
Possible menu changes in the Describe menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7986]
@lilyclements I would like to check when we meet on Monday, before any implementation.  I would also like @N-thony view, because he is pretty good on design!  Once agreed, then perhaps he can suggest who could implement.
@lloyddewit you may have other ideas and the changes may not be quite so trivial, because I am suggesting small wording changes and we need to remember the language translation implications.  
Here is the One Variable:
![image](https://user-images.githubusercontent.com/11226469/204091933-82970c28-7bff-4a1a-91e6-d4a2a2ff7508.png)

I am suggesting that is ok.
Here is the 2/3 variable:
![image](https://user-images.githubusercontent.com/11226469/204091788-961be369-e954-4c9b-9f36-06191ae374fb.png)

a) I suggest the Pivot Table should move to the top and have a line underneath, just like the Visualise Data  in the 1 Variable.  I suggest it can be a really important feature in R-Instat.  It is currently a hidden-jewel.  We need to document it and have a video, see #7985.  I don't think it quite warrants moving to the main menu, but having it at the top will give it more prominence - as we wish.
b) Should we also extend the name, because it has tables and graphs?  So we could still leave the name as it is.  Or we could change it to `Pivot Table/Graph`.  Or we could follow the pivot-table package word and so call it `Pivot Table/Chart`.  I am using chart essentially as a synonym of graph.  This might however be confusing.  What do you think between a) Leaving it at Pivot Table, or Table/Graph or Table/Chart?
c) While we are making that change I would like to simplify, and consider separating the next item

![image](https://user-images.githubusercontent.com/11226469/204092356-8566eb84-d868-4bac-b1dc-55cbabdbb317.png)

I suggest deleting the word Specific and having 2 separate entries, namely `Tables `and then `Graphs`.  The Tables will currently go to just the single item.  But later we may have Multiple Responses, so that may be a second.  
The Graph will then go to the set of graphs as now?

**Comment by N-thony** [comment]
> @lilyclements I would like to check when we meet on Monday, before any implementation. I would also like @N-thony view, because he is pretty good on design! Once agreed, then perhaps he can suggest who could implement. @lloyddewit you may have other ideas and the changes may not be quite so trivial, because I am suggesting small wording changes and we need to remember the language translation implications. Here is the One Variable: ![image](https://user-images.githubusercontent.com/11226469/204091933-82970c28-7bff-4a1a-91e6-d4a2a2ff7508.png)
> 
> I am suggesting that is ok. Here is the 2/3 variable: ![image](https://user-images.githubusercontent.com/11226469/204091788-961be369-e954-4c9b-9f36-06191ae374fb.png)
> 
> a) I suggest the Pivot Table should move to the top and have a line underneath, just like the Visualise Data in the 1 Variable. I suggest it can be a really important feature in R-Instat. It is currently a hidden-jewel. We need to document it and have a video, see #7985. I don't think it quite warrants moving to the main menu, but having it at the top will give it more prominence - as we wish. b) Should we also extend the name, because it has tables and graphs? So we could still leave the name as it is. Or we could change it to `Pivot Table/Graph`. Or we could follow the pivot-table package word and so call it `Pivot Table/Chart`. I am using chart essentially as a synonym of graph. This might however be confusing. What do you think between a) Leaving it at Pivot Table, or Table/Graph or Table/Chart? c) While we are making that change I would like to simplify, and consider separating the next item
> 
> ![image](https://user-images.githubusercontent.com/11226469/204092356-8566eb84-d868-4bac-b1dc-55cbabdbb317.png)
> 
> I suggest deleting the word Specific and having 2 separate entries, namely `Tables `and then `Graphs`. The Tables will currently go to just the single item. But later we may have Multiple Responses, so that may be a second. The Graph will then go to the set of graphs as now?

@rdstern I think we can leave `Two/Three Variables` since we are using only texts for menu items title and to make it consistents with other menu items specially with `One Variable`
I agree with items a) and b) i.e `Pivot Table/Graph` since Graph is the word the most used in R-Instat, I think they are still some part called differently and it will be good to make it consistent all depending on which type of graphic is produced.

**Comment by rdstern** [comment]
@N-thony, what do you think?  

I also like @lilyclements suggestion to simplify the menu items for the graphics dialogues.  I think it was Shadrack who wanted the more comprehensive items, and they don't seem to be so appropriate for our intended audience.

**Comment by N-thony** [comment]
> @N-thony, what do you think?
> 
> I also like @lilyclements suggestion to simplify the menu items for the graphics dialogues. I think it was Shadrack who wanted the more comprehensive items, and they don't seem to be so appropriate for our intended audience.

@rdstern that sounds good to me and happy with @lilyclements's suggestion. I think if all is good @derekagorhom can start making the changes?

**Comment by N-thony** [comment]
> @rdstern @N-thony I also agree with parts a and b. I think `Pivot Table/Graph` is ok too. To c) - I agree that it could be less confusing to the user to separate our tables and graphs so I agree there too.
> 
> Can we also change the names of the plots to more simplified names, for example,
> 
> ```
> Bar Chart...
> Boxplot...
> Histogram...
> Scatter Plot...
> Line Plot...
> Map...
> ```

@lilyclements I just changed the Plot in capital letters for `Scatter Plot...` `Line Plot...`

**Comment by N-thony** [comment]
> @N-thony that Sounds fine and if @derekagorhom is ok, then I would be happy for him to make the changes. I just question the last entry above, where the current `Map/Choropleth/Contour/Heatmap Plot...` has become `Map...`? I would very much like that, but when you take that option the resulting dialogue only has Heat Map. So the other options in the menu are currently just our wishful thinking! Hence, for now I suggest that this be called Heat Map... and also it should move to go under the horizontal line, so it is seen to be a special map. And we should work to provide all those options as soon as possible and then return to the Map..., above the line, as suggested by @lilyclements.

@rdstern I agree with this, I also had a quick check `Line/Smooth/Dumbell/Slope` dialogue, the title is Line Plot, but if you change the option to `Smooth` or `Dumbel` or `Slope` it is still Line Plot as dialogue, perhaps in such case we can make it dynamic, anytime you change the option the title also change?
![image](https://user-images.githubusercontent.com/68591383/204735108-99cc6365-47bd-4187-946b-43bf498ceff8.png)
