### ISSUE TITLE
Import from library Instat Collection Browse

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7994]
Hello @Patowhiz and @N-thony 

I have noticed that when you use the Import From Library > Load from Instat Collection > Browse it opens to the library initially. But if you then navigate away from the R-Instat library to use a different file, the next time it does not revert back to the library, instead it remembers the random place that the user when to and reopens there. I think that it would be better for it to always open to the R-Instat library even if the user  have gone to a different location previously. Is that possible? 

Thanks, 

Rachel 

![2022-11-29_13-49-09](https://user-images.githubusercontent.com/85707390/204656933-31b4f07a-417f-4851-88a3-5a5d974c3623.png)

![2022-11-29_13-51-00](https://user-images.githubusercontent.com/85707390/204656945-0eb4d891-86f8-47cb-8d77-7c17ef795b5c.png)

**Comment by Patowhiz** [comment]
@rachelkg yes it is possible. @N-thony would be good to have this solved in the next release.

**Comment by N-thony** [comment]
@rachelkg I had a quick check of this and the code seems fine, and when I tried with the released version it always open to the library initially. If you try running R-Instat with the visual studio version, it will not as expected.

**Comment by N-thony** [comment]
@MeSophie can you close this if solved?
