### ISSUE TITLE
Unresponsive Compare Columns dialog

### ISSUE THREAD

**Issue by berylwaswa** [africanmathsinitiative/R-Instat#8024]
**Describe the bug**
I was using the sleep data from the mosaic package and entered a second column for the words with some errors in the data entered. I then went to the compare columns dialog to compare those two columns but there was no output. I added the first column to compare then the second pressed okay, the dialog closed as though a third logical column would appear but nothing appeared, not even in the output window, there was no evidence of something working out.
I created a new dialog with two numeric columns x1 and x2, both columns I entered the same values but then changed two so that in two rows, x1 had a different value to what was in x2. I then went to the compare columns dialog and still, there was no output.
**To Reproduce**
1. Go to File>Import from Library, select Mosaic package then open the sleep data.
2. Make a copy of the words column, but make at least two mistakes.
3. Go to Prepare>Check Data>Compare Columns
4.  Add the columns to compare to their respective receivers 
5. Press Ok.
6. No output is seen. No new column and no commands in the output window.

**Expected behaviour**
I expect to have a new logical column called compare at the end of the data frame but nothing appears.
**Screenshots**
![Compare Columns 12_19_2022 10_26_39 AM](https://user-images.githubusercontent.com/28622260/208379590-820d569d-36e4-408f-9639-b1b14fa4ee47.png)

**R script or commands**

# Code generated by the dialog, Compare Columns

rm()

**Additional context**
When I go to check the r script it's blank.
@N-thony please get time to look at the dialog.

**Comment by N-thony** [comment]
@berylwaswa I tried to reproduce the issue above and I did get the new column as expected and the output. Perhaps you should update your master branch and try again?
![image](https://user-images.githubusercontent.com/68591383/208407455-c23d8038-339a-4e5b-8ca8-8a35e486abe4.png)

**Comment by berylwaswa** [comment]
Thank you @N-thony . The issue has been resolved.
