### ISSUE TITLE
New Menu items not available for translation in Crowdin

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#8040]
Hello @lloyddewit and @N-thony, 

I have also noticed new menu items appearing untranslated in R-Instat such as these Two-Way and Three-Way Frequencies. I cannot find these in Crowdin to translate. 

There seems to be a lot of issues especially in the describe menu which I know has had a lot of updates to its structure. This includes some items that have been translated in crowdin but are not showing up correctly yet. 

Have these just not been sucked in to the system yet. If so, do you have a next round scheduled? Could these issues be address for the January 23rd release? Roger will be teaching using a translated version soon after that and is hoping that it will be as good as can be for that. 

It seems as though there are as many untranslated items as there were when this was checked a couple of years ago. Is this just because things keep getting updated in the program and that throws the translation off? If so could we have a system whereby when changes are made, there is an additional step to ensure the translation moves along too? 

Thanks very much, 

Rachel 

![2023-01-04_10-54-05](https://user-images.githubusercontent.com/85707390/210628611-d3c68abb-1ce2-4c88-a796-2d42545916e8.png)

![2023-01-04_10-55-34](https://user-images.githubusercontent.com/85707390/210628895-3a9bcb58-3cd6-4fe7-9557-e8e66ceb3f2c.png)

**Comment by N-thony** [comment]
@rachelkg I did discuss with @lloyddewit and we agree that we will automatically update the translation before the release if needed. It seems from your comment above we need to update the translation and do some corrections in CrowdIn.
@lloyddewit could we update the translation for the next release?

**Comment by rachelkg** [comment]
@N-thony and @lloyddewit, 

There are terms in R-Instat that are not in CrowdIn so I think the JSON file needs to be updated, new translations need to be made and then the terms need to be put back in to R-Instat. 

But there are also items that are in CrowdIn translated which are not showing up in French. For example in the right-click menus. I wonder why this would be happening?

**Comment by N-thony** [comment]
@MeSophie can you look at it?

**Comment by lloyddewit** [comment]
I think the items above are fixed in R-Instat 0.7.10. So I will close this issue.
