### ISSUE TITLE
Please add Italian to the set of R-Instat languages

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8041]
@lloyddewit there are ideas, in Italy, to have maths camps, and teaching English would also be important in this sort of activity.  So, adding the machine translation of Italian would be highly appropriate.

It is also timely as we will - for the first times - be making steps early this year - to improve the translation with partner teams - starting with French, Portuguese and probably Russian.

**Comment by lloyddewit** [comment]
resolved in PR #8087
