### ISSUE TITLE
Add an option to put summaries into a list?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8043]
Some of the calculator keys, like factorise produce list variables and we are sort of able to cope with them.

@lilyclements In the gtextras package there is a nice example that we will be wanting to include in our new tables stuff where dplyr produces a list.  How could we do this ourselves?  I give the code below from [here](https://jthomasmock.github.io/gtExtras/).

![image](https://user-images.githubusercontent.com/11226469/211250826-6567f806-f66a-43c7-9441-e6acd7bb6d9a.png)

This shows the production and also the use of the results.  

Maybe a better alternative now is to leave the summaries in multiple variables and implement the unite function from tidyr?  See [the last entry here](https://stackoverflow.com/questions/15237995/combining-variables-together-into-a-list). 

If we do, then I suggest we add the option into our Column: Text menu?  I suggest yes, and it could just be another option in the Prepare > Column: Text > Combine function?  

If so, then I note the opposite of Unite is sort of Separate , but that seems already to be out-of-date, [see here](https://tidyr.tidyverse.org/reference/separate_wider_delim.html).  And this could add to, or replace our current Split dialog.

**Comment by lilyclements** [comment]
Links with #8082

**Comment by lilyclements** [comment]
Copied to #8082 so will close this now
