### ISSUE TITLE
Add factorize2 and primorial keys to the integer keyboard

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8052]
a) @derekagorhom could the `conf.design` package please be added to R-Instat.
b) Then add a factorize2 key after factorize on the integer keyboard.
c) Then move the digitsum key, so it fills the 2nd row of keys.
d) Then everything else just moves down - so Fibonacci and lucas now start the 3rd row.
e) The new tooltip for the factorize2 could say `Like factorize, but with simpler layout of results.  But much slower for large data sets.`

For the record, this package is written by a very prominent Australian statistician.  We could usefully write to him about the code to see whether he may wish to improve it.  Up to 10,000 it is quick.  It is considerably slower for 100,000 observations.  For 1 million the DescTools package took about 13 seconds, while this took about 30 minutes - so about 100 times slower.  

Useful that the main aim in this package is factorial designs, i.e. statistics!

Could you also add a primorial key to the end of the primes block of keys.

The code is `sapply(  ,primes::primorial_n)`  And the tooltip is Gives the primorial (like the factorial, but just the primes up to the number) for a variable.  For example primorial(c(7,8,9)) = 2*3*5*7 = (210, 210, 210)

**Comment by derekagorhom** [comment]
@rdstern whiles looking into the `conf.design` package i noticed for the generic function and methods for factorization the equation used in R was;
`factorize(x, divisors = primes(max(x)), ...)`. 
was that the equation you wanted for the factorize2 in the integer keyboard?
