### ISSUE TITLE
French DB Translation Issues in Describe Menu

### ISSUE THREAD

**Issue by derekagorhom** [africanmathsinitiative/R-Instat#8053]
Pulls Requests will be made to fix issues relating to the incorrect translations for the describe menu. 
other areas will added as we move along. 

@N-thony, @lloyddewit is this ok for you

**Comment by lloyddewit** [comment]
@derekagorhom ok for me, thanks
Not sure if we need to open an issue in this case, we could just create a PR not linked to an issue. But opening this issue is also fine.

**Comment by derekagorhom** [comment]
@lloyddewit i think can close this issue now
