### ISSUE TITLE
mmtable2 package not found for Customised radio button (Describe>One Variable>Summarise)

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#8065]
Using the customised radio button (Describe>One Variable>Summarise) on R-Instat merge version I got the following bug.
The mmtable2 package cannot be found.

![image](https://user-images.githubusercontent.com/106779233/213386573-118c1918-9f6e-46de-94c1-fe4dc0cc21a9.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Describe>One Variable>Summarise'
2. Select variable(s) 
3. Click on 'Ok'

Using the R-Instat 0.7.8, we do not get this error and the result is displayed normally.

![image](https://user-images.githubusercontent.com/106779233/213400904-f4d13601-6bbf-4750-8e3d-34987094bc14.png)

**Comment by N-thony** [comment]
@MeSophie is this fixed?

**Comment by MeSophie** [comment]
> @MeSophie is this fixed?

@N-thony Yes . So I will close the issue.
