### ISSUE TITLE
Error with list variables and precision

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8067]
I hope the figure shows the error:

![image](https://user-images.githubusercontent.com/11226469/213634517-cb7f4607-f8fd-48ad-bcaf-66e6899aaefb.png)

@N-thony this may be an easy fix, but please try the problem for yourself, because it is followed by a possible further problem.  It may need discussion with @ChrisMarsh82 ?

Get it in the now usual way for lists.  So a New data frame with values say 1 to 100 in x1.  Then the calculator and any list variable in x2 - say divisors.

Now get the column metadata.  The list variables have NA for the precision.  You see from some of the other variables above that it may sometimes be useful to change that.  So, above I made it 3 and that caused the problem shown.

I am ok if list variables (at least for now) don't allow the signif element to be changed, but I don't like this error occurring.

I started again and tried other options in the metadata, but this seems the only one that gives this problem. 

But also, before fixing, could you also check what happens after this error, because R-Instat can still be used, but it is painful.  So try ignoring the advice and see what happens too.  I am not sure about the value of the advice, which may occur elsewhere.

So what happens currently is as follows:
a) It closed the data frame and gave the front screen.  When I try with multiple data frames it just closes the offending one..
b) I then started again - but without closing R-Instat - because I hadn't done much.
c) It seems to work fine - except I get the same error message many times (well perhaps 5 times) each time I press Ok.  That's the same problem if I keep working on another data frame, when more than one were used initially.

**Comment by ChrisMarsh82** [comment]
I've tried to recreate this error but am unable to do so. I am able to change the signif_Figures on both list and character. The R script doesn't actually do anything but I don't get the error.
![image](https://user-images.githubusercontent.com/84872334/213684335-ce0d765f-2e75-453a-92f3-ad77f07e9f1b.png)
@N-thony are you able to recreate this?

I assume in order to change the significant figures this would need to be done when the list column is created/calculated.

**Comment by N-thony** [comment]
@ChrisMarsh82 I have tried with the divisors example `x3 = DescTools::Divisors(x1)` and I got the following message. It seems to be a problem in the R code?
![image](https://user-images.githubusercontent.com/68591383/213690500-7164bb09-41e8-472f-803e-d0bffa7e5cbb.png)

**Comment by ChrisMarsh82** [comment]
@N-thony Make a change so Signif_Figure is not editable if the class is 'list'
Check that changing the value of a list field within the DataView Grid is possible if this cannot be changed then it should be disabled too.
