### ISSUE TITLE
Allowed multiple R scripts to be opened and managed as tabbed windows

### ISSUE THREAD

**Issue by lloyddewit** [africanmathsinitiative/R-Instat#8071]
This issue was created automatically from one of the check boxes in issue #7989.

**Comment by rdstern** [comment]
@lloyddewit exciting that work on this issue is progressing.

I take the opportunity to mention that a common way of opening a script window is from a dialogue, and they all have a script button.  Currently they add to the bottom of the exiting script (because there is only one).  We already have the option on the script button to Keep the dialogue open or to close it.  Perhaps now there might be additional options to Open a new tab or add to the current tab?

**Comment by lloyddewit** [comment]
@rdstern Thank you for the ideas.

> We already have the option on the script button to Keep the dialogue open or to close it. Perhaps now there might be additional options to Open a new tab or add to the current tab?

If we add options to the existing pull down, then we would need 4 options ('new tab and keep dialog open', 'new tab and close dialog' etc.). I think this would be too confusing. My preference would be always to add the script to the end of the currently open tab (and move the cursor to the end of the new text). If the user prefers different behaviour, then could we add options to the Options dialog that would apply to the whole session?

>  it may perhaps be automatic. So if you are currently in a new tab then it is all that's there. If you are in a tab with existing commands, then (as now) it adds to the bottom?

I'm not sure I understand. Do you mean that we just write to the currently open tab?

> Might there be a point about the names of the tabs? If so, then a new tab might have the last name of the dialogue perhaps - with allowance if that name already exists.

In Rstudio (and all other script editors I know), the tab name is the name of the file associated with that tab. In RStudio, tabs that have not yet been saved are called 'Untitled1', 'Untitled2' etc.). I think this will be clearest for the user. If we name the tab after the dialog that last added to it, then it may not be clear to the user if the tab is saved, and our naming system will be more complex. My preference is for the RStudio approach but I'm happy to discuss if needed.

**Comment by rdstern** [comment]
Happy with the Rstudio approach on names.

My "automatic" is just what you have suggested.  I now like it much more than the 4 options on the Script button.  So it always adds to the bottom of the currently open script window.  And then - as you say - moves the cursor to the end of the text.  So, if I want it to add to a new tab, then I just have to open it first!  Then it is the current tab.

In summary, my comments were not needed - and just designed to delay you!  Thankfully not for too long.
