### ISSUE TITLE
Add a Use Table dialogue?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8081]
@lilyclements and @anastasia-mbithe I am really pleased with the additions to the display of tables you are working on.  Having well formatted tables is key to our reproducible work and so much easier now that we are in control of the html output ourselves.

This issue is to raise two more aspects.  - now just this one, as it has become larger!
1) I note that gt can export rtf, latex, word as well as html.  I note that the input to these options is a gt table object and we are working on saving objects.  I wonder how easy this might be.  It may become a second dialogue?  We have a Use Graph dialogue and perhaps we need a Use Table one?  

This could become a simple adaptation of the modelling idea too where we have Fit Model and then Use Model.?

As I look in the gt guide I note that quite a number of the functions assume a gr table as the first argument, so I am warmin g to the task of proposing a Use Table dialogue.  I suggest it will probably call the same Format Table sub-dialogue as one option, but might have some key aspects on the main dialogue - like the different export type perhaps?

**Comment by Patowhiz** [comment]
@rdstern the `gt` package seems to be very interesting in terms of formats, styling etc.
I haven't looked at the package in detail yet, but what I'm keen on before these dialog is;
1. What R object types does the package expect as it's parameter, for instance, can it take `htmlwidgets` as it's input? Note this can be a big limiting factor before even designing the use table dialog.
2. What can the package do with the tables, for instance, can it combine tables?
3. What else can it do and how is that significant to the packages that we use for producing tables. If it can work with all the packages that we use for tables, should we use it as the standard for working with all our table outputs?
4. What are the other leading table making packages? Briefly why are they not as useful as the `gt` package.

@anastasia-mbithe if you could write up detailed answers to some of the above questions, it would be very useful information in regards to the table outputs.

**Comment by rdstern** [comment]
@Patowhiz gt is interesting indeed and what's even more exciting is gt plus the gtExtras package, which is pretty new.

This is part of our plan to show that data visualisation is even more than ggplot2.  Nothing against ggplot2, but good descriptive statistics is graphs + tables.  And now the distinction between has become very blurred.  But it will still be nice to make an obvious table include some graphs and also some graphs that include some table-type stuff.

I'd be delighted if you and @anastasia-mbithe could make some progress on the use of gt, during the sprint - and perhaps even "finish" during the next one - so in a month or two.  This comes from @lilyclements suggestion to use the mmtable2 package for our tabulation stuff, even though it isn't in CRAN.  And mmtable2 uses gt for the presentation stuff.
