### ISSUE TITLE
Revise the data frame right-click menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8096]
This should wait until work has started on the HTML viewer for data frames - see #8095.

Then I find the order of items in this menu to be inconsistent from the Prepare > Data Book menu.  I don't see a reason for that.

So change to the following:
```
Rename
Reorder
Copy
Delete
Hide
Unhide
---------------
Add Comment
```
`View (HTML) `  (Note this is the only addition)
`R Viewer `         (Note the slight change in name.
```
-------------------
Help
```

**Comment by MeSophie** [comment]
This is solved through PR #8292.
