### ISSUE TITLE
Missing packages in Version 0.7.8

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8109]
@derekagorhom and @N-thony I don't know if there are many missing, or just that we forgot to ask for them to be included?
I was checking that the bigz, etc is now updated.  Then on the integer keyboard I found that Zseq is not installed.  Neither is primes?  I assume there could be more that need to be added - or added again?

**Comment by rdstern** [comment]
the package conf.design isn't there either.  @ChrisMarsh82 might there be a defined set of packages missing from the build?

**Comment by derekagorhom** [comment]
I am looking into this

**Comment by derekagorhom** [comment]
@rdstern , @ChrisMarsh82 i checked install_packages.R and found out from the three missing packages on conf.design was still there 
![image](https://user-images.githubusercontent.com/76208189/217466676-11e5fd16-7c54-4a29-bd8d-02eda8f0a271.png)
are you ok with me making a PR for this or Chris can add them

**Comment by ChrisMarsh82** [comment]
@derekagorhom if you make a PR for the missing packages and tag me I will check the build.
