### ISSUE TITLE
Cosmetic point in Line Plot 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8115]
This is a very minor point that may have been missed in the recent changes.  The dialogue is looking nice now - and is powerful.

![image](https://user-images.githubusercontent.com/11226469/217636222-442835b9-cf3f-4e2c-8f57-d4846cefc5f0.png)

Please can the `Add se` checkbox be moved back, so it lines up with `Add Valleys `checkbox.  It looks odd so far to the right.

**Comment by MeSophie** [comment]
@rdstern this Is what I have in the Merge version of R-Instant.

![image](https://user-images.githubusercontent.com/106779233/217797682-1bb5d8ee-3c25-456b-b612-e8bb285a9385.png)

![image](https://user-images.githubusercontent.com/106779233/217797987-02284cb1-4263-4693-af11-4ba2a406dbdd.png)

There is not `Add SE` in `Line rdo` .

**Comment by rdstern** [comment]
@MeSophie thanks for looking at this.  In the Line option click on  `Add line of best fit`  then you'll see it.
