### ISSUE TITLE
Label feature in Scatterplot not working

### ISSUE THREAD

**Issue by COLIEWO** [africanmathsinitiative/R-Instat#8128]
While performing **data visualization** of the murders data from the dslabs package, I realized that the Scatterplot option has a label feature but it does not impact the graph output. 

The path I used to **load the data** is;
File-> Import from Library-> Load from R-> from package (dslabs)-> Data(murders)-> Ok

The path to get to the **scatterplot** for analyis:
Describe-> Graphs -> Scatterplot

The pictorial below is the pop up window to input the variables.

![image](https://user-images.githubusercontent.com/124562645/218047321-357147fa-5f2b-47d3-8a1c-2c915ee4bb8d.png)

The **output** does not include labels for the data points

![image](https://user-images.githubusercontent.com/124562645/218047596-864a0419-4f0c-40c9-a83e-6505263aa184.png)

**Comment by rdstern** [comment]
@COLIEWO thanks for finding this and @MeSophie has now made the changes.

Could you now check the bar chart dialogue critically as well.  In particular check if we can still get pie charts? Also anything else at the same time.

**Comment by COLIEWO** [comment]
@rdstern I will check on that and advise.
@MeSophie thank you!

**Comment by N-thony** [comment]
> @rdstern I will check on that and advise. @MeSophie thank you!

@COLIEWO can you use R-Instat version 0.7.9 for this? Then same time it will be also your test on this version? I can send it on Slack.

**Comment by COLIEWO** [comment]
@N-thony I just checked and it isn't updated on the new version.

**Comment by N-thony** [comment]
> @N-thony I just checked and it isn't updated on the new version.

you mean this?
![image](https://user-images.githubusercontent.com/68591383/222372248-f1283f65-1f89-4e0c-80de-c9348fbf31d8.png)

**Comment by MeSophie** [comment]
> @COLIEWO thanks for finding this and @MeSophie has now made the changes.
> 
> Could you now check the bar chart dialogue critically as well. In particular check if we can still get pie charts? Also anything else at the same time.
> 
> @MeSophie improving these graph dialogues (and then I need to document them) is now high on my list to be able to show how wonderful R (and R_Instat) are. I hope you don't object to continuing some of your work in this area?

@rdstern I don't have any problem to work also on this area.

**Comment by COLIEWO** [comment]
@N-thony I mean the label feature.

**Comment by N-thony** [comment]
> @N-thony I mean the label feature.

Okay, this is still in the PR which is not merged yet, maybe it will be in the final release.
I was suggesting that you use version 0.7.9 for your testing and see if things works fine there before the final release.
I just sent you R-Instat 0.7.9 on Slack.

**Comment by COLIEWO** [comment]
Okay sure, I already downloaded it.

**Comment by N-thony** [comment]
> Okay sure, I already downloaded it.

Good
