### ISSUE TITLE
Code produced for the Describe > One Variable > Summarise dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8136]
I like to think of the code from most dialogues in 3 sections:

a) Get the data from the data frame
b) Execute the function specified in the dialogue - here the summary function
c) Often save an object in the data sheet and then display in the output window or in the grid, or both. 

@Patowhiz here steps a) and b) are together.  I hope, in instances like this, they can be separated.  Do you agree?  I think it helps for users to be able to read and maybe tweak to commands?

**Comment by Patowhiz** [comment]
Yes. It's good that @anastasia-mbithe fixed this. Should be like that for all the dialogs.
