### ISSUE TITLE
More R packages to be added again into the February release

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8150]
@N-thony and @ChrisMarsh82 the `prediction` package is still available (it is with a small p), but it is another package that seems not to be included in the January release.

![image](https://user-images.githubusercontent.com/11226469/219592233-737a5496-0d3b-4e69-a86a-f1d8e0da7bf8.png)

It is used in the Model >Use Model > Use Model keyboard

I also found agridat that used to be available, is now omitted?

**Comment by derekagorhom** [comment]
@rdstern also in the Model > Fit Model > Hypothesis Test Keyboard... the `coin` and `verification` packages are missing 

![image](https://user-images.githubusercontent.com/76208189/220844171-352fcf58-5dbf-4f61-a96c-18d129bf8fd3.png)

**Comment by rdstern** [comment]
Interesting and well spotted @derekagorhom .  On my machine I found coin was there, but verification was not - as you say.

@ChrisMarsh82 this (or these) are further packages to check they are included again in the next version?

**Comment by derekagorhom** [comment]
@lloyddewit this issue has been closed by PR #8180 so this can be closed
