### ISSUE TITLE
Changing the File > New Data Frame and the Edit > Script dialogue to streamline running scripts in R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8151]
I build on comments introduced elsewhere.
We currently can prepare and execute scripts from 3 places:
a) `File > New Data Frame `  has a commands option.  It executes the commands to build a data frame.  The code provides the data frame and an extra line is then added to include the resulting data frame in the new, or existing data book.
b) The suggestion is to delete this option from the File > New Data Frame dialogue.  This has the plus point of deleting a complicated option, that is perhaps a bit daunting to our main audience for R-Instat as it the first dialogue that some may use - and they may be beginners.
c) @lloyddewit I note, however, one feature we will lose is the `Try control`.  I like that feature and it is also on the other "halfway" dialogues.  Could it, perhaps become a button directly available from a script window.  It opens effectively a single sub-dialogue, with just this one control.  And then a Return, etc, because you return to the script window.  The only difference from the current Try control is that it opens the sub-dialogue.  It is already there on our existing halfway dialogues.  Then it tries the marked code?
d) I also assume we will enhance and keep the `Edit > Script dialogue`.   It is designed to help users to construct a typical script if they start "from scratch".  It is an alternative to the To Script button on each dialogue.  
e) I don't have any sentimental attachment to this dialogue - just suggest it could remain pretty useful.  It is designed particularly to make it easy to include the "special" R-Instat components to get a data frame and also to write results back into a data frame or to the results window.

![image](https://user-images.githubusercontent.com/11226469/219849065-eddfdbad-218e-4044-b672-c6bb1d07de14.png)

f) Assuming we will keep it, then one simple change - even in the February release - could be to disable the Ok button.  So, when you are happy with the code you then do the ToScript and that sends it to the current script window. 

g) The New Data Frame could add a first option to the Data Frame shown above.  It would be O New Data Frame and the existing one becomes O Get Data Frame.  

h) I quite like the one-line examples that are in the current File > New dialogue and they might be included.  Bigger ones could perhaps be loaded from a file, or we might only allow the load into the ordinary script windows.  Aha this is becoming a bit more complicated!

i) If we keep the dialogue, in some form, then we should also check if the code side can include all your enhancements?  We could also check on alternatives.  I assume one of your new script windows will be read only and will include the log file?  Might another script window (or all of them) permit the sort of assistance that this dialogue is providing? 

j) So I explore an alternative.  I am not sure I want to clutter up all your script windows with many more controls.  But could there be a Construct (script) window, with them.  Or, you already have an option to open a new script window, perhaps it could alternatively be a new construct window?

**Comment by lloyddewit** [comment]
@rdstern Thank you, I suggest we discuss in our next catch up, along with issue #8068, and agree the best way ahead.

**Comment by rdstern** [comment]
@lloyddewit at least for now I propose we keep the File > New Data Frame in its current form.  But we change the radio-buttons at the top.

Here they are now:

![image](https://user-images.githubusercontent.com/11226469/229064290-2f382c35-7ab4-477e-8bd8-ca77a5b764ca.png)


) Empty is now the default - and that's fine.  But I don't like the name, because the default isn't quite empty!.  So let's change that to `New`
2) Then Lists is east to use, and should therefore come next.  But it includes an option to view the command.  So let's separate the `Lists` button a bit from the `New` button.
3)  Then the other 3 are together (but after the Lists which is after the New.  They are in the order `Random, Construct, Command`.  They each then include the Try key.  They also provide some interesting examples.  

Now I am inclined to still keep the Ok button active for these 3 options, while the help will encourage users to use the To Script normally.  

@lloyddewit are you ok with this for now?  Would you prefer that we disable Ok, to make the poi9nt that the are adding a special command and it's very easy to then Run All from the script window?

Once agreed, then perhaps @derekagorhom could make these simple changes?

And one task please for you, or to suggest who could do this.  Could there be a short document on how to locate the data_book$import_data code in R-Instat and could there be the documentation for this function? It is the only function added from any of the options in this dialogue.

I'll then add it to the R-Instat help and be able to sort out the documentation for some more of the R-Instat key functions.

**Comment by lloyddewit** [comment]
@rdstern Thank you, I'm happy with all these proposals.
I'm OK with leaving the `OK` button enabled for now because I assume some users will just want a new data frame without wanting to see the R code.

>  Could there be a short document on how to locate the data_book$import_data code in R-Instat and with the documentation for this function? It is the only function added from any of the options in this New Data Frame dialogue.

Did you mean 'write the documentation'? If so, then someone who understands the subtleties of R may be a good person. @lilyclements could be a strong candidate.

**Comment by rdstern** [comment]
@derekagorhom I think this should be quite quick?  It is just to change the word Empty to New as the first radio button and then make it a reasonable size and the default - as now.  Then make Lists the second, sort of by itself.  Then Random, Construct, Commands - in that order and together - as now.  Thanks.

**Comment by derekagorhom** [comment]
@rdstern as i was trying to make the changes this evening i run into a problem where New could not be changed from Empty; Here is it in VB
![Screenshot (579)](https://user-images.githubusercontent.com/76208189/229313383-e362009a-46ce-4fd4-b21f-e84a2a5dabbf.png)
And here is it when i run it
![Screenshot (578)](https://user-images.githubusercontent.com/76208189/229313418-894db534-9c6e-4657-b70f-b63c51e521ef.png)
maybe @lloyddewit can suggest otherwise but I tired changing the database translation of the rdoEmpty text to New and it worked. so that means i have to do two PRs for this changes, One for the changes in the database translation and the other for the other layout changes.

**Comment by rdstern** [comment]
@derekagorhom that's interesting.  That's a good question for @lloyddewit though I think he is on leave for this week.
Meantime can you line up the right of Command with the right of the box below, and separate Random, Construct, Command, from the Lists button.  Make New just slightly less wide and line the left also with thre lerft of the box below.  So there are effectively 3 buttons, with New separate from Lists that is separate from the other 3 - and they remain together.

Then we'll wait for Stephen's input.

**Comment by lloyddewit** [comment]
> I tried changing the database translation of the rdoEmpty text to New and it worked. so that means i have to do two PRs for this changes, One for the changes in the database translation and the other for the other layout changes.

@derekagorhom Yes, you are correct. I don't think anyone else is changing the database at the moment so, if you think this PR can be merged quickly, then you could add the database change to this PR (only if you prefer this). 
Thanks

**Comment by lloyddewit** [comment]
@derekagorhom Please ignore my comment above. I saw that you already made the database change in PR #8254 . I merged it.
thanks

**Comment by rdstern** [comment]
@lloyddewit we currently can give (and edit) commands from 3 dialogs - if I ignore the halfway dialogs.

I have been trying examples of code in your sctipt windows and currently they all seem to work.  So, this seems a good time to reflect on what is easy in the script windows and possibly get rid of the editing options in the File > New Data Frame and in the Edit > Script dialog.

This relates partly to the editing capabilities in the script windows and particularly to the addition of ordinary R code, to take advantage of facilities in R-Instat.  That's particularly the data view facilities, so that data can be viewed and saved in a data book.  And scripts could start from data in a data book if useful.  

So we will often wish to add a few lines to standard scripts to take advantage of R-Instat.  How can we make that easy to do?

I start with the File > New Data Frame.  It has 3 things that we don't yet have in the script windows.

a) A set of mainly one-line examples of data that can be generated.  They generate random samples and illustrate the use of some of the basic R commands.   
b) There is a Try button, which I like.
c) It adds the command automatically so the data are displayed in an R-data frame.

I started this morning with the supposition that we should make it easy to add these facilities in the script windows, and then delete the facility from this dialog.

However, as I use it, I find it is quite nice - and a pretty neat teaching tool.  So, I now suggest it also provides a good illustration of what we are trying to do in R-Instat.  Namely, you can use the dialog simply - you don't have to know about commands.  (That's the first option).  
The second option is about lists.  The defauly there is not to veiw the R command, but you can opt to see it if you want.
The third to the fifth option write, and use R commands.  They are ni9ce examples too and really easy to access.  So, not a bad way to start with learning a bit about R commands.

You are seeing the power of even a single line of R code =- particularly if you choose a suitable package.  

So I now propose we leave this dialog as it is.  The one question I pose is whether we disable (or half disable) the Ok button for the 3 options, Random, Construct and Command?  By half-disable I am wondering if the down arrow can be enabled without the main button.  We could then explain this - that we encourage the route of `To Script`, which is more transparent?

Finally here I repeat the question from above:

) @lloyddewit I note, however, one feature is the Try control. I like that feature and it is also on the other "halfway" dialogues. Could it, perhaps become a button directly available from a script window. It opens effectively a single sub-dialogue, with just this one control. And then a Return, etc, because you return to the script window. The only difference from the current Try control is that it opens a sub-dialogue. Then it tries the marked code?

**Comment by rdstern** [comment]
@lloyddewit I do suggest we get rid of the Script dialog.  Instead we have an Add (or Insert) button.

This will add a single line of code wherever you are in the script file.
The Add button opens a simple sub-dialog, as follows:
a) Label Name for a field into which you can type a name - this could be a paste from a name in the script window.
b) Task, label which is a drop down.  Initially it might just have Library, Make data frame, Use Data Frame.  
c) Possibly an optional Options Label If ticked it opens a field into which you could type some options.
d) Maybe underneath there is a Command: label that shows the R-Instat or R command generated.
e) Then the usual Return, Help, Cancel buttons

**Comment by rdstern** [comment]
@lloyddewit I am delighted you are positive about the potential of a library of scripts - issue #8497 .  I spent the weekend reflecting on the ideas above, and looking at more scripts.

I now hope you are equally supportive about the idea above of an `Add` button on the script window, which would make it easy to add specific lines of R code to an existing script. Here is the current window:

<img width="475" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/f5d4332e-0059-4354-9d0c-feefdd9a3102">

I suggest there is plenty of space for an Add button as described above.  I hope it will be quick to add.  If you agree then I would give it even higher priority than the code improvements that you are now starting.  I assume it could be implemented by one of the team, but think you may wish to do this yourself.

The purpose is to make it easy to adapt standard R code, to take advantage of the script being in R-Instat. If needed I would be happy to demonstrate what it would do.

I also hope, in the future, it might be easy also to add a second button for Try.  This is not as urgent, unless it is simple to do the two together.  This would be disabled unless some lines of code are selected in the currently open window.  Then the try button would open a simple sub-dialog and possibly (at the same time) run the same try code, that is on each of the halfway dialogs.  Or it might just open the sub-dialog and you would need to press the Try again, that is part of the control.

**Comment by lloyddewit** [comment]
@rdstern I would be very happy if we remove the script dialog and implement an 'Add' button in the script window instead. @N-thony could assign this to one of his team. It will create a merge conflict with PR #8494 but I can recover from this.

**Comment by rdstern** [comment]
@N-thony I would be happy to chat to you about this and perhaps even demonstrate.  I hope it may be simple to add.  It is  important in 2 ways, namely first to add a valuable feature to R-Instat and second, to simplify - because we also get rid of a useful, but unwieldy facility.
Perhaps you may wish to do this one yourself?  If not, then I wonder about Derrick?

I would be happy to explain and demonstrate over skype.  This could either be just to you, perhaps to help you decide.  Or, if you allocate, then it could involve them too.

**Comment by rdstern** [comment]
After discussions with @lilyclements I am hoping it may be possible to add a purrr (really 3 r's) tab and that would be incredible!  This is Lily's recommended ways of doing loops in R.  It is what is usually a problem in point and click software.  Making it easy to add a loop would be a major improvement and just could be a very low hanging fruit!

I am hoping to merge #8544 as soon as possible, so am making that a partially pull request, so we can continue with this feature later.
