### ISSUE TITLE
Selector's "add" button drop down and right click menu translations

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#8196]
@africanmathsinitiative/developers 
In the screenshot below, the sections highlighted are not being translated in Portuguese. I suspect it's the same for other languages too. Please note the selector header still remains as "Variables". That should be translated in all dialogs
<img width="960" alt="3" src="https://user-images.githubusercontent.com/21179007/223117671-3afb73b9-a4aa-40e8-acb2-bd9a342d6055.png">

**Comment by Patowhiz** [comment]
When you right click on the selector. The menu items are also not translated.
<img width="960" alt="4" src="https://user-images.githubusercontent.com/21179007/223118235-b4314e67-8219-403e-b2ce-918487e79af7.png">

**Comment by MeSophie** [comment]
@N-thony I remember that we already have and issue related with this, and the last time @lloyddewit  said that the is not yet the mechanism to translate them. This problem is alredy fixed?

**Comment by lloyddewit** [comment]
> @N-thony I remember that we already have and issue related with this, and the last time @lloyddewit said that the is not yet the mechanism to translate them. This problem is alredy fixed?

@MeSophie Yes, of the four things circled above, I think at least two currently have no translation mechanism implemented. Please leave this with me (no further action needed from your side), thanks
