### ISSUE TITLE
Hide or disable some sub-dialog on Structured menu.

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#8214]
On `Structured` menu, there are some sub-menu which are not yet functional : `Low-Flow`, `Times series`, `Climatic`, `Procurement`, and `Options by context`. Can we just Hide or Disable them?

@N-thony and @lloyddewit what do you think?

**Comment by lloyddewit** [comment]
@rdstern @N-thony If a menu option does not have any user functionality associated with it, then for me it should be:
- deleted if there are no immediate plans to implement the functionality
- or hidden if the functionality is currently being developed and will be merged within a few weeks

What's your view?

**Comment by N-thony** [comment]
> @rdstern @N-thony If a menu option does not have any user functionality associated with it, then for me it should be:
> 
> * deleted if there are no immediate plans to implement the functionality
> * or hidden if the functionality is currently being developed and will be merged within a few weeks
> 
> What's your view?

@lloyddewit I'm happy with your two points above especially the first one, I don't see the reason of having a menu when there is no implemented functionality to it.

**Comment by lloyddewit** [comment]
@MeSophie Thank you for spotting this. Please could you hide the non-functional menu options?
Thanks!
