### ISSUE TITLE
Temp Max and Temp Min are not automatically filled in Climndex

### ISSUE THREAD

**Issue by WezzieBanda** [africanmathsinitiative/R-Instat#8224]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'climatic'
2. Click on 'prepare'
3. Scroll down to 'climndex'

**Expected behaviour**
I expect temp max and temp min to be automatically filled in just like precipitation

 - OS: [e.g. Windows 10]
 - R-Instat Version [e.g. 0.7.9]

**Comment by MeSophie** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behaviour:
> 
> 1. Go to 'climatic'
> 2. Click on 'prepare'
> 3. Scroll down to 'climndex'
> 4. See error
> 
> **Expected behaviour** I expect temp max and temp min to be automatically filled in just like precipitation
> 
> * OS: [e.g. Windows 10]
> * R-Instat Version [e.g. 0.7.9]

@WezzieBanda Please can you give me the name of the data set that you use? I'm not able to reproduce the error.

**Comment by MeSophie** [comment]
Me  used niger_4_stns_linked_station_data.RD from library and it's working nicely.
![image](https://user-images.githubusercontent.com/106779233/227232074-79bd9df8-a839-4e31-a7a3-f0befb3bf18f.png)

**Comment by WezzieBanda** [comment]
![Uploading 1679587571372.jpg…]()
@MeSophie I am using Malawi climatic Data which is not in the library

**Comment by WezzieBanda** [comment]
![1679587571393](https://user-images.githubusercontent.com/106272881/227266071-14971887-13ca-46a9-9cf3-e0729aebbc23.jpg)
