### ISSUE TITLE
The Describe > Tables dialogue (Summary option) clears when the dialogue is reopened

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8230]
@anastasia-mbithe could you quickly fix this problem?

![image](https://user-images.githubusercontent.com/11226469/227005125-7f23dc41-2009-4e77-951d-80788b260159.png)

I have just done this summary table.  When I return to the dialogue the factors have been cleared.  They should have remained.

I think that the summaries will be cleared if the focus is on the factors.  

Of course they should both remain in the way they were when Ok was last pressed.

I assume this will be simple to fix?

**Comment by anastasia-mbithe** [comment]
@rdstern this problem is fixed in #8027

**Comment by rdstern** [comment]
@anastasia-mbithe thanks

**Comment by rdstern** [comment]
I am closing this, because - as Ana says it has been fixed in #8027
