### ISSUE TITLE
Returning the focus to the original location?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8256]
@Patowhiz I hope this mightbe a simple change that is automatically applied to all dialogues.  That is, if we agree.  Here is the boxplot dialogue completed:
![image](https://user-images.githubusercontent.com/11226469/229760967-32acae06-24d8-4be5-b796-93f0fe9cb56d.png)

When you go in the first time, the focus - so coloured - is on the Y variable.  Filling it in usually puts the focus as shown above - so in a place rarely used.

When I return it is usually either to change what is plotted - so the original variable with the focus.  Or it is to change some of the options, in which case I don't care where the focus is.

With beginners - one of my pre-occupations now - I suggest it would be simpler if the focus was always on the original first receiver, every time the dialogue is re-opened.

If agreed, then could this be a "rule" and programmed just in one place - or do we have to tweak each dialogue?

**Comment by Patowhiz** [comment]
This is already programmed. The developer just needs to change the focused control when reloading the dialog. That should just be 1 line. Alternatively we could implement this internally at the selector control level, this will affect all dialogs using the selector.
Also the order in which the receivers are added to the selectors matters a lot.

**Comment by rdstern** [comment]
@N-thony Patrick says this is just a single line change?  I wonder if it might be a really quick one to do?

**Comment by rdstern** [comment]
@N-thony you saw in the workshop why this is needed!  It must be done carefully and I hope is just a few minutes job?  Then @Patowhiz could check it, because it affects many dialogs.

**Comment by rdstern** [comment]
@N-thony when you are back, could you look at this one?  I think it should be quicker for you (or Patrick) to do, than to allocate?
