### ISSUE TITLE
Minor Changes to Insert Column/Rows

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#8262]
Hello @lloyddewit and @Patowhiz, 

![2023-04-05_13-45-15](https://user-images.githubusercontent.com/85707390/230227092-53f2c19e-4635-4c7f-b388-7550c556a231.png)
Please could you change (or ask someone to change) the text on here to say "Value:" (Instead of "Default Value:") and "Column(s) Name/Prefix:" (Instead of Prefix for Inserted Column(s):).

I am sending this to you, because - although this is pretty trivial - I assume labels must be changed carefully, because of the implications for different languages.  I could make these changes myself, if I knew more about this complication.

Thank you, 

Rachel

**Comment by lloyddewit** [comment]
@rachelkg Thanks for raising the issue. If you ever want to learn how to change the translations, then feel free to ask one of the developers (@Vitalis95 is currently team lead), or you could ask me.
