### ISSUE TITLE
Change the Help option from right-click menus and Windows

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8278]
We have a variety of right-click menus.  Within them the Help does different things.  This issue proposes consistency.  

a) In the **_column metadata _**, if you right-click in the Window, then there is just the Help

![image](https://user-images.githubusercontent.com/11226469/233776050-bcbabde6-eb42-4903-b486-bcc0ace65844.png)

If you choose it then you go to that window in the herlp file

![image](https://user-images.githubusercontent.com/11226469/233776179-fba2203c-7629-4576-affb-e089d6f8d8c8.png)

I suggest we keep that, as it is.

b) Same for the Data Frame meta-data.  I suggest no change.

c) The new Script/Log window has both a help button and also has help at the bottom of the right-click menu:

![image](https://user-images.githubusercontent.com/11226469/233776703-1234701b-6e1d-4a7f-aeea-4f4104c79e5e.png)

They both go to the Script Window.  We need to change the help file, because there is now a Log/Script Window, but I suggest we keep both options.  So I propose no change.

d) The data view has 3 right-click menus.  I suggest we change the context number, so they each go to the Data View Window in the help file.  So change the context number for each of them to 134.  @derekagorhom could you do this?

e) @ChrisMarsh82 The output Window does not yet have a right-click menu, or a help button.  It has plenty of tab-type buttons.  If you agree, then please could **_Help_** be added, or could there be a right-click with Help, or both?  The help context number is 540.    

f) @Patowhiz the Maximise window currently has a File button, but not a Help button.  If you agree then could one be added, or a right-click with Help, or both?  The Context is 590.  The help file currently has a Browser Window - becasue that is what we needed before.  I propose to call it **_Maximise Window_**, if you can't suggest a better name. 

g)  The only other right-click (I think) are in the dialogues.  They go to a **_Controls in Each Dialogue_** entry in the help and I propose to leave that - at least for now.

**Comment by N-thony** [comment]
@derekagorhom is this issue completely fixed?
