### ISSUE TITLE
Add a new option for the density ridges

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8283]
This is a useful [article](https://cran.r-project.org/web/packages/ggridges/vignettes/introduction.html)

Here is an example of the code:

```
ggplot(iris, aes(x = Sepal.Length, y = Species)) + 
  geom_density_ridges(rel_min_height = 0.01)
```
Could you add this to the layer parameters for the geom_density_ridges.  It could be calle min_height.  The default is 0.01 and perhaps it could be an up-down from 0 to 0.1 in steps of 0.001, but perhaps start with that and I'll check.

At the same time, could you change the up-down for scale.  It could go from 0 to 5 in steps of 0.1.  Currewntly it goes in steps of 1.

That's a good start!  But the article also uses the other 2 geoms that we have and that give further options on the ridges - and I have been asked to produce a graph with colours related to temperature.  So later is would be good to be able to do this as well.

![image](https://user-images.githubusercontent.com/11226469/233825213-9f42dbba-3c26-4ddd-a3da-e97c703602ce.png)

**Comment by rdstern** [comment]
@anastasia-mbithe I am re-opening this issue, so the extra layer parameter can also be added to the density_ridges_gradient in addition to the density ridges that has already been merged.  Then I will specify a special version of the dialog for the climatic menu.

**Comment by rdstern** [comment]
Didn't reopen it!

**Comment by N-thony** [comment]
@anastasia-mbithe any plan on this?

**Comment by rdstern** [comment]
@MeSophie I am reopening this issue and I wonder if there are a few more changes you can make.
a) In the geom_density_ridges there are now colour or especially fill parameters.  Could you add them please.
b) In the code that is generated, see below, it did not execute the minimum height, that I specified.  

```
# Dialog: Histogram Plot

Mozambique_3_stations <- data_book$get_data_frame(data_name="Mozambique_3_stations")
last_graph <- ggplot2::ggplot(data=Mozambique_3_stations, mapping=ggplot2::aes(x=TMPMIN, y=month_abbr, fill=Station_Name)) + ggridges::geom_density_ridges(rel_min_height=0.030) + ggridges::geom_density_ridges2() + theme_grey() + ggplot2::theme(plot.caption=ggplot2::element_text(), plot.title=ggplot2::element_text(size=20), plot.subtitle=ggplot2::element_text(), axis.text.x=ggplot2::element_text()) + ggplot2::labs(title="", subtitle="", caption="") + ggplot2::facet_wrap(facets= ~ Station_Name, dir="h")
data_book$add_object(data_name="Mozambique_3_stations", object_name="last_graph", object_type_label="graph", object_format="image", object=check_graph(graph_object=last_graph))
data_book$get_object_data(data_name="Mozambique_3_stations", object_name="last_graph", as_file=TRUE)
rm(list=c("last_graph", "Mozambique_3_stations"))
```

The reason is that after the density ridges it added `+ ggridges::geom_density_ridges2() `  This nullifies whatever we added into the density ridges.  I don't see why this ever need be added, so please could it be deleted from the code generated here.
