### ISSUE TITLE
Improve and fix bugs on the bar chart dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8288]
@COLIEWO is working on this topic, and so this issue may partly be dealt with elsewhere.  @derekagorhom I hope you can start on these points, and @COLIEWO will be the main tester.  Perhaps @WezzieBanda also

Here is the current bar chart dialogue:
![image](https://user-images.githubusercontent.com/11226469/234498087-b3be685e-d2f6-4f5d-8e28-e2ccf1bb4e8f.png)

a) Change the title to just `Bar Charts`.  (We don't give much importance to Pie Charts, so let's not keep it in the title.)
b) None of the 3 controls `Reorder Frequency, Reorder and Position` remember their settings when you re-open the dialogue.  They should all remember.  @lloyddewit Derek mentioned that you may be doing something to fix this?  I now note that this control was ok in Version 0.7.6.  I wonder what has happened? 
c) The position of the 3 addutional `Add Labels` controls is messy.  And they are incomplere in Russian - at least.  I suggest moving all 3 to be on the same horizontally, with `Position `moved to perhaps start just below the A of Add Labels.  Maybe the same horizontally as `Colour and Size`, so moving the Add Labels checkbox up slightly.  Check that each label is wide enough that is shows completely in Russian, and maybe also check the French also.

@COLIEWO is likely to be adding to this issue as we explore the dialogue more fully

**Comment by derekagorhom** [comment]
@lloyddewit when trying to make title name change for this dialogue, it did not have the name change as expected.... does this need another change in the database before it shows the change?

**Comment by lloyddewit** [comment]
@derekagorhom yes, you are correct, we'll need to change the database before you see the name change. I'm currently working on the database so I will make the change for you in a different PR. I assume that only part `a)` requires a database change. Is that correct?

**Comment by derekagorhom** [comment]
@lloyddewit yes... thank you for the quick response

**Comment by rdstern** [comment]
I have now found an item d) to add, and there may be more as I (and @COLIEWO ) test the dialogue more!

![image](https://user-images.githubusercontent.com/11226469/235339782-5847c441-2ede-4550-9ccf-eb381ef4b58b.png)

The bar chart can even be used when the x variable is numeric, rather than a factor, - though it is often not very sensible.
When this is a variate, as shown above than the ascending and descewnding options don't work, and give an error.  The correction is simple.

Here is the code generated - 

`last_graph <- ggplot2::ggplot(diamonds, mapping=ggplot2::aes(x=forcats::fct_infreq(f=carat), fill="")) + ggplot2::geom_bar(position="dodge", stat="count") + theme_grey()`

The descending option has added `x=forcats::fct_infreq(f=carat)`.  Please add an as.factor, to the code for both ascending and descending, so it becomes `x=forcats::fct_infreq(f=as.factor(carat))`

**Comment by lloyddewit** [comment]
> b) None of the 3 controls Reorder Frequency, Reorder and Position remember their settings when you re-open the dialogue. They should all remember. @lloyddewit Derek mentioned that you may be doing something to fix this? I now note that this control was ok in Version 0.7.6. I wonder what has happened?

@derekagorhom please note that PR #8293 may solve (some of) these issues.

**Comment by COLIEWO** [comment]
On the **Add Labels** feature, is it possible to specify the variable like in the **Scatter Plot** dialog? 
Currently it automatically picks the **Single Variable**.

![image](https://user-images.githubusercontent.com/124562645/235591790-306efd07-c511-4827-bcac-a1b4c0869589.png)

**Comment by COLIEWO** [comment]
@derekagorhom I suggest a correction for the bar chart label for position 'In' whose part code is currently `geom_text(stat="count", mapping=ggplot2::aes(label=..count..), position=position_dodge(width = 0.9), vjust=5, colour="black", size=4)` whose output is as below (this is just one example where the 'fair' category labels are misplaced);

| Fig. 1 | Fig. 2 |
| ------------- | ----------- |
| ![image](https://user-images.githubusercontent.com/124562645/237056357-68071311-2897-412b-abc3-66dffee7013d.png) |  ![in](https://user-images.githubusercontent.com/124562645/237057590-67d45179-0f14-4703-b9d2-5b80cd44aecb.png) |

Changing `vjust=5` to `vjust=1.5` makes the labeling better (reducing the size of the labels makes it better);
![in1](https://user-images.githubusercontent.com/124562645/237060009-4abbe3e4-a6f8-4f48-97db-b310315b8b53.png)

**Comment by WezzieBanda** [comment]
If I decide to include facets in the main bar chart dialogue under plot options, two factor options pop up. The first factor option is mandatory, while the second factor option is optional. To enhance user-friendliness, I was contemplating an automatic filling of the "first factor option" when there is only a single factor variable.

![Capture23](https://github.com/africanmathsinitiative/R-Instat/assets/106272881/4c1a89bd-8213-45a0-8f96-e1d52f77e349)

**Comment by rdstern** [comment]
@N-thony here is a reference on [bar and pie charts](https://r02pro.github.io/bar-charts.html)

I hope (in the sprint) we can get a set of options, so we can get "ordinary" pie charts.  It may be that we just need to choose the options correctly, but I don't know how to do that with a single variable, in the dialog?

Also a serious bug I reported.  Do a very simple bar chart, say survey data and village.  Then use the plot options down arrow and choosefor the bar chart.  Then don't do anything, just return.  Then press Ok and you get an error.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/1059b92e-9835-4c12-ab31-ab1b57d4592b)

I assume that's because there are no x variable.  It used to be ok.  Here it is in Version 7.6:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/908707b2-e742-464b-9542-30262b94dfc3)

**Comment by rdstern** [comment]
@N-thony at last I can get (proper) pie charts from our existing bar chart dialog.  But not quite how I would like.  I use our usual survey data.  For a simple pie chart I make a new column that is a constant - say 1 everywhere - I call it calc.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/0bcb8485-5177-4e3e-9dce-9bad2c175d51)

Then without polar it is this:
![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/f7da97d1-a324-41d2-a4f5-4ff06bdeda15)

And, changing to Polar gives this!

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/320c8080-2870-4bf3-8416-0af4d20b709c)

And notice the calc (always 1) is now the y variable.  

If I put Variety instead of the dummy column, then I get nice donut charts:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/e4dcbf65-9ffa-4770-9034-cca6f97ea47f)


Then we need to use the Fill option.  Stack is quite fun and may sometimes also be of interest.

Maybe @COLIEWO could check whether the labelling works on this?

I am releived that we can do this.  I wonder whether we keep to this way - which is sort of odd for the simple pie (having to make a dummy variable), but not impossible.  Or do we swap the variables round for a pie, and make a dummy variable when we need to?

**Comment by rdstern** [comment]
@N-thony I have just found a serious bug in the new bar chart dialog.  I assume it must have come from the recent improvements, because it is not there in Version 0.7.6.  

When I use the Plot options it does not include the geom's aethestics - the x and y, see below.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/215d1f7e-3859-4fa2-9fad-7ff0672dd1fa)


So then it gives an error when you try to run.

This seems to be general, so for any data set and for any of the options, e.g also for treeplot.
