### ISSUE TITLE
Deleting a variable, should also delete a key, if the variable was part of it.

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8296]
A dataframe needs a set of key columns before it can be used to add Comments.

I recently had an error when trying to add another comment.  I found the cause of the error was that I had deleted the columns that made up the key.  The key still remained, but of course was no longer usable.  I then tried to delete the unusable key and it wouldn't let me do this.
I suggest that we should never allow this situation to occur.  Whenever variables are deleted, then, if any are also part of a key, the key is also deleted.  

@Vitalis95 perhaps you could allocate this.  I realise it may be a bit tricky to program.  But we already do have a dialogue to View and Delete keys.  We would just have to check if the column being deleted is part of a key. (Presumably the Comment code checks this?)  If so, then run that delete key code first.   The delete key dialogue also gives a message in the output window and that would also be good to include when the column is deleted.

**Comment by Vitalis95** [comment]
After discussing this issue with @lilyclements, she suggested that we should modify the delete command so that it can account for the above issue . Lily can we have a look at it?
