### ISSUE TITLE
Prepare > Check Data > View/Delete Labels doesn't work when there is just one variable

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8336]
@N-thony this should be very simple to get anyone to fix.  It happens with any datset I think?

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/551e02fe-b765-4d6b-92a0-bff990ad9550)

The problem is only with a single variable to process - which is why I never noticed before.  I always used it with more than 1!

**Comment by N-thony** [comment]
@rdstern we can force the date to always be a data frame. @MeSophie see the screenshot below on line 2 where the change is supposed to be made, I have added `force_as_data_frame = TRUE`, can you make the change?
![image](https://github.com/africanmathsinitiative/R-Instat/assets/68591383/41d63c45-ab02-4095-ad7c-605d2b995096)
