### ISSUE TITLE
Lower case in Portuguese translation

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8340]
@rachelkg thank you for your offer to check this in the database:

Here are the first 3 instances - `Climatic and Experiments` on the main menu and `Copy` on the Edit menu.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/6aee981c-0985-4d20-b56e-a80e9fda3851)

Contrasts on Factor menu:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/73b61d78-9b46-4d9d-8347-900b71fe3951)

Multivariate on Describe menu

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/ee01299f-e367-4bec-a16d-26baf790d772)

date on thye climatic menu.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/92227f95-be32-4fbf-b91e-264bcc35f660)

Experiments on the View menu.  There I notice that the English just says Experiments and could usefully be changed to Experiments Menu.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/33d39e12-4b4d-4b8b-8460-16c078b0159d)

Windows on the Help menu:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/d1b33578-f55e-46ae-be0b-50b281fa7657)

**Comment by rachelkg** [comment]
Hello @rdstern, @N-thony and @lloyddewit, 

I have looked at the examples of this on Crowdin and I feel that my findings are inconclusive. I would say that most of the items to seem to be Capitalised in Crowdin, though a couple weren't. I am not sure what to make of that. I have corrected the items I found, though I am not convinced it is solely a Crowdin problem. Sometimes as in with the Windows example, the lower case option was present as a suggestion but shouldn't have been taken as the translation. Sorry this is not more helpful. Hopefully it makes more sense to someone else. 

Let me know if you want me to do anything more on this. 

Thanks, 

Rachel 

![2023-06-08_15-27-00](https://github.com/africanmathsinitiative/R-Instat/assets/85707390/35df6758-0eae-44f2-9b93-4b5d82c474bc)

This on was lower case and I corrected, does that need to be reviewed by someone? 
![2023-06-08_15-06-39](https://github.com/africanmathsinitiative/R-Instat/assets/85707390/79d7b283-300d-4f68-b885-ea75f8f66803)

This one should be correct, i don't see any lower case option
![2023-06-08_15-05-01](https://github.com/africanmathsinitiative/R-Instat/assets/85707390/e4086fbf-bddc-49d6-b702-a4fa3f7747c9)
Same with this one
![2023-06-08_15-04-06](https://github.com/africanmathsinitiative/R-Instat/assets/85707390/a41b0337-156e-45c6-bc62-9c1e38ef0de2)
