### ISSUE TITLE
 Add enhancements to Climatic > Inventory dialog

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8342]
There are 3 small changes and then one tricky one!  The small ones first:

a) When you first use the Missing Option, could the Summary be enabled by default.
b) When you first select Datails, could the Months be the default, rather than the days.  Also make Date Order the default, rather than Element Order.
c) When it produces a data frame, could it add the key fields.  That needs the Station Name (if used), Element, From and Level variables.

The next one is trickier, so perhaps implement and merge these 3 changes first. @N-thony I suggest @Vitalis95 for this, but you may perfer someone else?  

d) The trickier one!  Could it add the cum (or even the cum1) variable - not both, which I have added by hand in the data frame below.  This needs a nifty bit of e-programming - probably @lilyclements and then implemented by @Vitalis95 ?

This adds a new variable to help the dialog be used more efficiently.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/071cae74-9f7c-4bbf-85f0-51caab6e8fe0)

I think it is only added when the option is by month, and possibly only when the result is saved.  It facilitates the use of filters to look at the different sort of missing months (or Days, or Years!)

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/d298c1d5-6f99-47c9-b14d-0b4ae09bc169)
 
The column cum starts as zero.  Then look at the last 3 rows above.  All 3 elements were missing for the same set of months.  So the last value gives a 3 there.  (That's useful, because there only were 3 elements.  So if they were all missing, then perhaps the data sheets were never sent to the HQ?  So good to look to see if there is a copy at the station.)

The 2 rows above that were an example where rainfall was entered, but not tmax and tmin.  So there is a 2 there!  (Then the data must have been sent to HQ because one element was entered.)

Happy if that is all that can be done.  The complication is  when there is an overlap in the dates.  So I have added 0.5 to the number of rows above of the overlap.  I am then particularly interested in the 2.5, which says there are some months there that may have data at the station only!  So I could then filter on > 2!

**Comment by N-thony** [comment]
@Vitalis95 any progress?

**Comment by lilyclements** [comment]
@rdstern I am looking at this now with @Vitalis95 and we have noticed that you have for the first three rows of "Cum": 0, 0, 3
Why do we want the first two as 0? Would it be okay if this were 3, 3, 3?

**Comment by rdstern** [comment]
@lilyclements yes, that would be fine
