### ISSUE TITLE
Split the Climatic > Tidy and Examine menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8348]
Please proceed with these changes.  (I earlier wrote:  Please do not implement this issue, until others, including some of @N-thony and @Patowhiz and @rachelkg and @lloyddewit have given their views.)  I have some views now, and would like to proceed!

The climatic > Tidy and Examine menu is currently as follows:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/4aa06b96-20a4-4f98-88c8-1ced70a50180)

I have proposed the addition of Pivot Tables to the bottom of this menu.  This will make it the longest menu un the whole of R-Instat! (The Prepare > Data Frame is the only other one that comes close.)

I have recently been pretty happy with some of the menu changes - particularly to the describe menu.

I have also been happy with the way that the climatic courses go steadily down the climatic menu.  I now tentatively propose we split this climatic Tidy and Examine menu.  

If so the first half becomes `Tidy Data` and the Second would be `Examine and Edit. `

Then the Tidy Data is the first 2 sections, so down to Append.

The Examine and Edit would swap the order of the remaining parts, so the 7 items would become:

One Variable Summarise...
One Variable Graph...
One Variable Frequencies...
----------------------
Pivot Table...
--------------------
Setup for Data Editing
Daily Data Editing
Compare Columns

(Note the change in name - no entry anymore that's for Climsoft!)

I am growing to like this as I write it.  

In addition I find I sometimes need the `Transform Text` and `Split Text` dialogs from the Prepare menu.  With the new setup I propose they could become a small 3rd section of the `Climatic > Tidy Data` menu.

What do you think?

**Comment by rachelkg** [comment]
I think this sounds good. I think smaller menus are less daunting and clarifies the order of tasks. However, I think this is only good if users do not have to flip back on forth between menus. I think we should think about carefully is whether any of the tasks from the second menu sometimes need to be used earlier. For example, would one sometimes use a summary early on to check for missing values? If so, then I think it is less good to have them separated as you would have to switch back and forth between menus which is confusing.
