### ISSUE TITLE
Small errors on the paging in the grid when there is a filter or a large data frame

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8350]
I show with the diamonds data where I have filtered for the cut == Ideal diamonds.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/b776eed5-0e78-4800-aed2-8b09793cc047)

and also 

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/1c8c1840-eb2b-4767-b1db-671300a8b2f6)

In each case thery should now go to 22 as that is the limit with the filter applied.

There is the same problem with the selection of columns, plus an additional bug to correct.

In the library you could try with the rockart data from the daag package.  I used the hh dataframe from the MICS survey.  I selected 106 variables out of the 329.  It still says 1-7 where it should change and say 1 to 3.

In addition the first number in the brackets is wrong.  when I have the first window, so first 50 columns, it says (50/329).  If I move to the second set it says (100/329).  It should alsways say (106/329) to reflect the number of variables selected.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/de98e7ea-eb42-461b-87d3-2d3aea158d8a)

@N-thony I wonder who is best placed to do this.

**Comment by N-thony** [comment]
@Fidel365 can you have a look of this? I can guide you on fixing this.

**Comment by Fidel365** [comment]
@N-thony , Okay

**Comment by N-thony** [comment]
@Fidel365 any progress?

**Comment by rdstern** [comment]
@N-thony for checking again.  I hope the sprint will help R-Instat to become more solid!

I tried (for schools) with a data frame of length 10 million.  I used File > New Data Frame.  And also changed x1 to go from 1 to 10,000,000.

Then I used the calculator and multiplied by 9, into x2.  Then I used digitsum and I think there may be an error in the last observation.  Then I wanted to see what was happening up to 1 million.  I found the size of the paging control needs to be wider and I don't think the up-down can cope with 10 thousand pages yet?  There need not be an upper limit.

**Comment by N-thony** [comment]
@rdstern I did try this and I found the message we are displaying at the bottom of the Grid is not correct, I tried to reproduce with a dataset of 5000 rows and filtered rows `x1: >=3000 and <=5000` I get the message still 1:1000 but in the grid it starts from 3000 up to 3999 for that page according to the filter. If this is fixed, the paging will probably be fixed too.
![image](https://github.com/africanmathsinitiative/R-Instat/assets/68591383/d7d7bb0c-90a7-413b-a0cb-715212494fc2)

**Comment by N-thony** [comment]
@Fidel365 can we hold this? We need a quick check with @ChrisMarsh82 on Wednesday then implementation will be quicker.

**Comment by Fidel365** [comment]
@N-thony , ready when you are

**Comment by N-thony** [comment]
@ChrisMarsh82 @Fidel365 could we have a quick call?

**Comment by N-thony** [comment]
@Fidel365 I'm ready, we can have a call about this.

**Comment by rdstern** [comment]
@N-thony is this finished?  Can the issue be closed?
