### ISSUE TITLE
Undersized graph output in new release 0.7.14

### ISSUE THREAD

**Issue by COLIEWO** [africanmathsinitiative/R-Instat#8361]
**Describe the bug**
The graph that appears on the **Output Window** is quite small and thus incomprehensible. One is therefore mandated to **Maximise** in order to make sense on the graph.

**Expected behaviour**
Previous versions had a clear output graph without need to maximise to make sense of the variables.

**Screenshots**
Below is a sample screenshot for scatterplot (+ with facets), line graph and barchart;
![image](https://github.com/africanmathsinitiative/R-Instat/assets/124562645/7b5e23a4-9f8a-4885-983e-b56d5941e4a4)

**Details (optional):**
 - R-Instat Version [ 0.7.14]

**Comment by rdstern** [comment]
@COLIEWO I agree.  If you go to Tools > Options > Output Window, then you can change the 300 in maximum height for outputs, to a larger number.  I made it 500 and queried whether this should be done as the new default for this release.  I suggest you could also try that.  

@Patowhiz suggested other values might be better and that the best value for graphs might not be right for the output when tables.  I suppose the best value may also depend on the screen resolution and haven't checked that.  

So, I felt we needed to get the release and so left it with the original value he produced.  We don't always seem to be very good completer-finishers!

**Comment by Patowhiz** [comment]
@COLIEWO interesting that you found the mandate of using maximise as bothering. 
@rdstern I agree in we can increase the size. We can also explore the option of having multiple height options for different output formats.
@rdstern also notice how the comments will look for all our existing users, I wonder whether we should enforce the new comment if an older release is detected?

**Comment by Patowhiz** [comment]
@N-thony @rdstern I think this has now been fixed.

**Comment by rdstern** [comment]
@Patowhiz and @N-thony I agree - it is now 0.5 rather than the 0.3 thumbnail. I will be brave and close this.
