### ISSUE TITLE
New bug has appeared in the Climatic > Prepare > Climatic Summaries dialog?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8362]
@lloyddewit it is in the Day Range control and is curious.  I am concerned that it is ok in the previous versions, and I just found it by chance.  And it is odd.  I hjope there is an obvious reason and not an indication that similar oddities may be elsewhere?

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/e3293065-4fa3-4654-bb9e-62ac3e9a6cda)

What is also odd (comforting or not?) is that we have the same control in various other later dialogs in the same menu and there it is fine.  For example:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/c88ee5f3-15df-4fbb-99d3-5c00a7d9ebe0)

When I run the dialog it works, because it is still a valid condition.  Here is the code:

```
# Diálogo: Resumo Climático

day_filter <- instat_calculation$new(type="filter", function_exp="1 & doy <= 366", calculated_from=calc_from_convert(x=list(Mozambique_3_stations="doy")))
data_book$calculate_summary(columns_to_summarise=c("TMPMAX","TMPMIN"), data_name="Mozambique_3_stations", factors=c("Station_Name", "year"), additional_filter=day_filter, j=1, summaries=c("summary_count_non_missing", "summary_mean", "summary_min", "summary_max"), silent=TRUE)
rm(day_filter)


```

**Comment by lloyddewit** [comment]
@rdstern I investigated which commits caused this issue and traced the problem back to PR #8327 which was merged on 16 May.
@Vitalis95 please could you analyse the changes you made in this PR and try and resolve this issue?
thanks!

**Comment by Vitalis95** [comment]
> @rdstern I investigated which commits caused this issue and traced the problem back to PR #8327 which was merged on 16 May. @Vitalis95 please could you analyse the changes you made in this PR and try and resolve this issue? thanks!

I will, thank you.

**Comment by rdstern** [comment]
@Vitalis95 and @lloyddewit many thanks.  That's a big relief too, because it indicates that this problem only applies to this dialog.  And it is not sufficiently serious to need more than include the fix in the next release.
