### ISSUE TITLE
Include tooltips on selected menu items?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8384]
@N-thony and @lilyclements I would like your confirmation that this is a good idea, before we proceed.  @lloyddewit I'd value your view too, partly as it may be a tricky extra, (or not?) given the tranlsations.

My suggestion is to add a tooltip for quite a number of the R-Instat menu items, starting with the Describe > Graph ones.  

Here are the graph menu items in 0.7.6 and now:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/3a9ab403-6a85-4148-b0f8-30dbe3285d67)

I much prefer the simpler/cleaner items now, but having the tooltips would add a way to show just how many different types of graph we have.  

In addition, if you agree, then the different types mainly relate to different options of the top radio buttons. 

Here is a possibility for the graphs:

1) Bar Chart.  Tooltip:  Bar, Column, Lollipop, Pie, and Donut Charts, plus Treemaps and Wordclouds
2) Boxplot.  Tooltip. Boxplot (including Tufte), Jitter and Violin Plots
3) Histogram: Histograms, Dotplots, Density and Ridge Plots and Frequency Polygons
4) Line:  Line Plots, Smoothed Plots, Dumbbell and Slope Plots

I am warming to this task.  For example with one-variable Frequences we have hidden Stem and Leaf plots there.

5) Describe > One Variable > Frequencies.  Tooltip: Table or Graph.  Also Stem and Leaf Plots
6) Describe > One Variable > Rating Data.  Tooltip: Table, Stacked Graph or Likert Graph

And there are also some in the Prepare menu where tooltips could be useful?

So I further suggest looking to add tooltips to other some dialogs that have a top set of radio buttons

**Comment by N-thony** [comment]
> @N-thony and @lilyclements I would like your confirmation that this is a good idea, before we proceed. @lloyddewit I'd value your view too, partly as it may be a tricky extra, (or not?) given the tranlsations.
> 
> My suggestion is to add a tooltip for quite a number of the R-Instat menu items, starting with the Describe > Graph ones.
> 
> Here are the graph menu items in 0.7.6 and now:
> 
> ![image](https://user-images.githubusercontent.com/11226469/246170076-3a9ab403-6a85-4148-b0f8-30dbe3285d67.png)
> 
> I much prefer the simpler/cleaner items now, but having the tooltips would add a way to show just how many different types of graph we have.
> 
> In addition, if you agree, then the different types mainly relate to different options of the top radio buttons.
> 
> Here is a possibility for the graphs:
> 
> 1. Bar Chart.  Tooltip:  Bar, Column, Lollipop, Pie, and Donut Charts, plus Treemaps and Wordclouds
> 2. Boxplot.  Tooltip. Boxplot (including Tufte), Jitter and Violin Plots
> 3. Histogram: Histograms, Dotplots, Density and Ridge Plots and Frequency Polygons
> 4. Line:  Line Plots, Smoothed Plots, Dumbbell and Slope Plots
> 
> I am warming to this task. For example with one-variable Frequences we have hidden Stem and Leaf plots there.
> 
> 5. Describe > One Variable > Frequencies.  Tooltip: Table or Graph.  Also Stem and Leaf Plots
> 6. Describe > One Variable > Rating Data.  Tooltip: Table, Stacked Graph or Likert Graph
> 
> And there are also some in the Prepare menu where tooltips could be useful?
> 
> So I further suggest looking to add tooltips to other some dialogs that have a top set of radio buttons

@rdstern this sounds good to me, it will really enhance user experience and improve usability. And since it offers additional information about the menu item, providing clarity and context to the user.

**Comment by lloyddewit** [comment]
I don't see any issues with translations.

**Comment by lilyclements** [comment]
@rdstern I agree, I think this would be really useful to have in as well

**Comment by lloyddewit** [comment]
@derekagorhom @N-thony Thanks
