### ISSUE TITLE
Possible changes to the Describe menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8421]
I am becoming increasingly comfortable with the describe menu.  It is reasonably short and pretty clear.
I need others, particularly @volloholic to check my suggestions below.  I'd also welcome comments of course from anyone else.

a) This has arisen, because I have, at last, found a simple graph that is very easy to do with the `Describe > General > Graphics` dialog. 
 And it doesn't seem possible with any of the options in our `Describe > Graphics` dialogs.  

It is described [here.](https://ggplot2.tidyverse.org/reference/scale_discrete.html) .  

b) This Describe > General > Graphics dialog is much more important than its current position in the menu.  Hence I propose the 2 following changes:

1) Here is the current Graphics menu:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/da04cbd0-b15a-43ae-b349-31f53700e370)

I propose to get rid of the line below heatmap.  So there are just 2 sections so far.  They correspond to common graphs and particular graphs.  Later we will, I hope include maps in the heatmaps dialog.  That will change the name and move it above the line.

2) Then a line underneath and one entry, called General, which is the current Graph dialog that is currently hidden in the Describe > Graphics > General menu.

3) Then we keep the Describe > General menu item
We delete The Column Summaries dialog from here and also the Use Summary dialog.  It is currently a pretty feeble version of the bar chart dialog.

a) We add a copy of the Pivot-table dialog.  Just the same as in the Describe > 2/3 Variables > Pivot Table.
b) Then a horizontal line
c) Then keep the General graph dialog there.
d) Add a copy of the Tables dialog.

**Comment by Fidel365** [comment]
@rdstern , I'm working on this

**Comment by lilyclements** [comment]
> a) This has arisen, because I have, at last, found a simple graph that is very easy to do with the Describe > General > Graphics dialog.

@rdstern Is this referring to `geom_jitter()`? If so, we could add it as a checkbox on the scatterplot dialog to "jitter points". If this is selected then we run `geom_jitter` instead of `geom_point` in the dialog.

**Comment by rdstern** [comment]
@lilyclements oh you are right.  Adding geom_jitter does the job nicely.  And I have been looking for ways to add interesting options to the scatterplot dialog.

**Comment by rdstern** [comment]
@Fidel365 and @N-thony I am afraid I have yet another change to suggest for the Describe menu.

a) I have persuaded @volloholic that the pivot tables are more for exploration and hence are not appropriate in the Describe > General menu.  And the other 2 items are repeated.  So please delete the General menu item.
b) The Graphs menu currently looks as below:

<img width="288" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/b66783a5-dc5d-4138-b716-37aaec90e87c">
Could you change Graphics... to `General... `and `miove it to the top`.  The current line above Graphics, now also moves to be `below General...`

Many thanks
