### ISSUE TITLE
Position sub-dialog may not always work correctly and overwriting an existing variable is too easy! 

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#8434]
@derek, please see my suggestion below.  I think there is a really easy, and general, solution.

When I use the Position Sub-dialog from the Calculator it does not always work. It generally seems to work if i choose to position the new column at the beginning or the end of the data frame but it sometimes doesn't work when i try to position the new column before or after a column within the data frame. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Calculator'
2. I used the Integer Keyboard to make a factorial column.
3. Use the Postion sub-dialog to place the new column in different places.
4. See where it comes up.

As you can see in my screen shot I have asked for fact2 to come after the fact column but it has been placed at the end of the data frame after the fives column. 
![2023-07-11_16-28-49](https://github.com/africanmathsinitiative/R-Instat/assets/85707390/33905999-e6d3-47d8-b8c4-b17d02db346b)

@rdstern could you have a look and maybe suggest someone else too? I am hoping someone could just play around with this and see if they experience the same thing or if perhaps I am doing something wrong. 

Thanks. 

Rachel

**Comment by rdstern** [comment]
@derekagorhom I now think I have an easy solution to this problem.
When you use the control you have 3 options on the name to save the column.
a) You can leave R-Instat to choose the name.  Then, it chooses a new name - usually by adding 1,2, etc to the last name.  That's fine.
b) You can choose to overtype an existing variable.  That works fine - and you have chosen to do it.  The next time it returns to its default (new) name.  That is also fine.
c) You can choose a new name yourself, so not an existing name.  When you return, it remembers this new name and you must then always change it, or you will overtype your new variable repeatedly.  This option is not fine.  Instead, please use b) instead.  So, when you return it suggests the default name again.

For example with a File > New Data Frame 2 variables with names x1 (with data) and x2 (all NA).  Use the calculator and the name it suggests is called calc.

If you leave it, then it produces a new column called calc.  Then the next time it will write to calc1, etc.  That's fine.
If you make it overwrite x2, then the next time, it will again suggest calc, and that's fine.
If you give it a new name - say derek - then, when you return I would like it to suggest calc, just as it would have done when you overtype x2.
