### ISSUE TITLE
Add to toolbar to facilitate showing R commands

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8444]
@N-thony is this a possible task for @derekagorhom?  @Patowhiz can help with the code, if this is needed.

Here is the current toolbar with the current down-arrow for the log/script window.  It is ticked when the log/script is open and not otherwise.

<img width="424" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/85dbcdea-9469-4453-8b2f-038b39f84d50">

Could you add 2 further entries underneath that
```
Show R Commands
Show Comments
```
@Patowhiz as I write this I wonder whether the placing is correct in the toolbar.  Instead I wonder about adding a new down arrow after the Output icon, and putting them there?  That seems more logical?

When R commands are shown in the output window, then this is ticked.  Likewise with the comments.
When you click on either of them it doesn't necessarily change those settings. Instead, it opens the T`ools > Options > Output Window `tab, (see below) so you can change the settings.  Then the toolbar items are ticked or unticked, depending on those settings.

<img width="367" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/fd86384f-521f-4833-a3d8-7866f4964c1a">

**Comment by Patowhiz** [comment]
@lloyddewit @rdstern @derekagorhom I understand that this was closed when PR #8484 was merged.
I still have an open https://github.com/africanmathsinitiative/R-Instat/pull/8484#issuecomment-1690434334 that requires your feedback.
