### ISSUE TITLE
Allow the user to easily reopen previously opened scripts

### ISSUE THREAD

**Issue by lloyddewit** [africanmathsinitiative/R-Instat#8487]
On 08/08/23 @rdstern wrote:

Having a list of past used scripts.

When using RStudio I have the past scripts as buttons at the top. Could we have a similar list in R-Instat.
And we have a very discrete way we could provide the list! Could it be added to the down arrow which is next to the Log/Script window. There is just one entry there currently, and it just says whether the window is open or not. We might keep that, but underneath is the recent scripts we have opened and saved.

I got to this recently when I was sent a set of data, in Excel and a script - so with an R extension. I used File > Open for both and it was equally simple. The data went to a data frame and the script went to the script window. I saved my own copy of the data as an RDS file and the code as an R file.

Now I returned today and the RDS file is available and in 3 places! It is on the front screen and is on the File menu and is on the toolbar drop-down. But my R file is nowhere?

So the initial opening is the same for data and code. But then it is different. We could, of course, save the R file in the list of past files, just like a data file, so that's another option. I am thinking that we are less obtrusive about the R files - but just as convenient. (I am also asking if the liobrary icon on the toolbar could have its drop-down, because we currently don't save a copy of those either. Though that's slightly different, because I anticipate that list just from opening a library file, not from saving a special copy.)

**Comment by rdstern** [comment]
@N-thony after discussion with @lloyddewit please could you allocate this task - which is partly a further improvement in the toolbar.  I asume that this may be to @derekagorhom, as he has worked effectively on improvements to the toolbar before.  It may be that you could take a part of this yourself?

Note that File > Open can be used for data files - with an R extension.  The come automatically into the current script window.

Re-using past data files has 3 short-cuts currently as I show here:

<img width="469" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/4254b2c1-425d-4c31-8e7f-fe6e2568f219">

1 above is in the front menu.  Please could you also add the R files to this list, as well as data files.
2 above is that the same list is at the bottom of the file menu.  Could you please add recent R files to this list.
3 above is the drop-down from the toolbar.  Please leave this, as it is.  Do not add R files here.  Instead add them to the script/log window drop down.

<img width="384" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/47a5848a-14d4-45d7-a165-c64130d71f16">

This item on the drop down currently has the single item.  Please keep that an put a line below and then add the list of scripts recently used, below that item.

There is a 4th way to re-use items, and that is to re-use them from the library, see below.

<img width="405" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/8fc16b4e-404d-4532-a08d-d5e9679c7861">

I am really liking the pull-downs on our toolbar.  Please also add it to the Open from Library item.  Then be able to reuse past library items as well, either from an R package (hopefully) or from the R-Instat part of the library.  Note that detecting an item to re-use here, will have to be done when it is opened.  We don't save library items.

This option is for both the R packages and for the R-Instat part.  From R-Instat it is for both data and script files.  (If either is difficult to do, then start with what is easy!

I hope this will be easy, but this sequence of tasks may become a set of small pull requests.

**Comment by derekagorhom** [comment]
@N-thony , I am working on it

**Comment by rdstern** [comment]
@derekagorhom I wonder where you have got to, on this?  And I would like here to split the task and also - of course - add something.
But I hope we can start small.  I would be helped if your report gave more detail "I am working on it" tells me very little.  I learn nothing about your time-scale, nor on which parts of the list above you are working on.

<img width="353" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/4d4301d9-e7e8-4690-8bdf-cdf71fd51412">

Items 1 and 2 are about adding scripts to the list of files at the start and at the bottom of the File menu.

I hope this is what you have started on?  Anyway I strongly suggest you try to do this first and hope it may be easy and quick.  It is a convenient stopping place too, so we can merge the changes when you have done that.  

@N-thony I would also like to query a small addition for @derekagorhom which I think you asked for earlier?  I am not sure whether there is a specific issue on this?

When I click on a file it currently automatically opens the File > Import from File menu.

Could we arrange that a double-click misses out that stage and just opens the data frame or script directly?  

(I note that I think you arranges, in the Open from Library that double-click on a data set is the same as selecting it (single click) and then pressing Ok?)
