### ISSUE TITLE
Make Output names consistent in the View menu and the Toolbar button

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#8496]
@derekagorhom we have `Output Window` in the toolbar and in the View menu we have only `Output`. Can you rename it for consistency?
![image](https://github.com/africanmathsinitiative/R-Instat/assets/68591383/9e8c4a9a-b24a-4623-95af-a55896080cc6)

![image](https://github.com/africanmathsinitiative/R-Instat/assets/68591383/45ab8652-38a6-4ce3-b37b-db60884ef997)

**Comment by lloyddewit** [comment]
@N-thony @rdstern If we change the View menu to display 'Output Window', then this will be inconsistent with the other View menu options.
Should we could change the toolbar pulldown menu to read 'Show Output' instead?
