### ISSUE TITLE
Small correction needed for the Pivot tables dialog

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8511]
@MeSophie I hope this will be trivial and won't have knock-on effects in the climatic use of the dialog?
For our usual survey data I usually use it this way:

<img width="313" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/a10c758c-a9e0-494d-a82d-5af9b1fe79a7">

When I return to the dialog the `Numeric Variable (Optional) ` is unticked.  
When I tick it, the variable from before is remembered.  So it is just so it remembers to keep the tick.

I hope you have never had a simpler request?

**Comment by MeSophie** [comment]
This issue is already solved and PR merge so I will close it.
