### ISSUE TITLE
Translation problem with Climatic > Tidy Data and others

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#8576]
@MeSophie here is the English version we have `Stack` and `Unstack`
![image](https://github.com/africanmathsinitiative/R-Instat/assets/68591383/86bc10b2-e62d-4565-817d-e1fa440f9c61)
but when you change it to French we get both `Depiler`
![image](https://github.com/africanmathsinitiative/R-Instat/assets/68591383/2b08aad9-2194-4219-ab4e-c0410dc48d01)

**Comment by MeSophie** [comment]
> > Also, in Climatic > Tidy Data > Unstack, can you make this checkbox wider for the French text to fit? ![image](https://user-images.githubusercontent.com/68591383/275411975-508a641c-8e49-4fab-9045-0a4219d110c2.png)
> 
> I have alredy provided the solution here to fix this

@N-thony Yes I saw it before. The mistake is mine sorry for that. I removed the colon I added
