### ISSUE TITLE
Bug on Climatic > Prepare > Boxplot

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#8577]
When you open the dialogue in French version for the first time, the three input controls don't have the default values
<img width="401" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/68591383/bb4f0fe4-adff-428b-bf13-c9518b191f29">
@derekagorhom have a look of this.

**Comment by derekagorhom** [comment]
@N-thony i think this is the reason
![Screenshot (592)](https://github.com/africanmathsinitiative/R-Instat/assets/76208189/99f9039d-b30e-4e17-b3d7-43c3c78d4e30)
I can make the Database changes but the `None` and `X Axis` in drop down has not been translated into french
