### ISSUE TITLE
Small problem in Column summaries sub-dialog

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8588]
@N-thony this should be able to be fixed by anyone.  It is a much unused sub-dialog.  I explain the example:

In R-Instat > Open from Library > Datasets > ACRAdmissions data.

Then Prepare > Data Reshape > Column Summaries.  Complete as shown below.  Also just one summary the sum.

<img width="631" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/9623427b-df93-41cb-9561-88073d8383ae">

After the summaries button, press the Percentages button - bottom right on the main dialog.  Tick the box, and you should get the Fig shown above.  So the receiver isn't shown!

If you click on the one button at the top that is enabled, then the receiver appears.  From then on, it appears all the time.  It is just the first time you go in - at least with this sequence.

**Comment by Patowhiz** [comment]
@rdstern my **Datasets** package doesn't seem to have the **ACRAdmissions** data.
@derekagorhom does you have?

**Comment by derekagorhom** [comment]
@Patowhiz Roger is the UCBAdmissions rather
![Screenshot (599)](https://github.com/africanmathsinitiative/R-Instat/assets/76208189/e5205ffb-8fd9-46ba-91c5-e9e09a813d79)

**Comment by Patowhiz** [comment]
@rdstern the screenshot below shows an oddly added control in the summaries sub-dialog. What is it used for?
For reasons which I don't quite understand, whenever it's parameter is added, it causes this bug.

<img width="368" alt="1" src="https://github.com/africanmathsinitiative/R-Instat/assets/21179007/3cdcc116-45c2-4601-b142-ae8fdf87446f">

**Comment by Patowhiz** [comment]
@rdstern @derekagorhom I also noticed that if I go to Prop and Percentages options first before the summaries options, I don't get this bug.
