### ISSUE TITLE
add geom_categorical_model to the geoms and also to the list in the general graph dialog

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8594]
@MeSophie this geom comes from the moderndive package that is described as follows:

"Datasets and wrapper functions for tidyverse-friendly introductory linear regression, used in ``Statistical Inference via Data Science: A ModernDive into R and the Tidyverse"

you already added the other geom, namely geom_parallel_lines.

I would like the new geom, in our list of geoms and also included in the new list that is in the general graphics dialog.

This package is mentioned in teaching statistics - and I suggest we could usefully query, at the end of the year whether we see if they could mention R-Instat!

**Comment by MeSophie** [comment]
This is solved through PR #8589
