### ISSUE TITLE
Implement Reset of Edit > Paste New

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8625]
<img width="438" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/9473a935-22bd-46fc-9767-9044dd284522">

@Patowhiz or @N-thony I pasted an example of data into this dialog.

Then I wanted to try a different example.  But I can't get rid of this example.  I assume Reset should do that, but it doesn't.

It seems very insistent that I have 4 rows, even if I delete them manually.  Am I doing something wrong?  The only waY I could find was to restart R-Instat.

Oh no!  When I start again it is still there!

<img width="440" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/9f65f062-d6bb-401c-a3c1-8a8a7a0a7314">

I know I don't like pasting very much, and it seems it is taking its revenge in a serious way!  Does this really mean I can only use this dialog for one set of data and it is then there forever?

**Comment by Patowhiz** [comment]
@rdstern thanks for raising this. The paste dialog automatically gets data from the operating system clipboard when you open it.  You have to refresh preview when you copy another set of data while the dialog is still open. 

Note, you don't have to paste using any shortcuts, it's either you reopen the dialog, click on refresh preview or reset button.

I'm surprised why reset doesn't refresh the preview, it should! I'll test and revert back to you.

**Comment by rdstern** [comment]
@Patowhiz many thanks for the quick reply.  This was mainly me not understanding the settings, as I still had the same (or similar) set of lines copied.  It shows how important it is for me to get the help written properly.

**Comment by Patowhiz** [comment]
Does the reset work now?
If it does,  we can close the issue?

**Comment by rdstern** [comment]
I am closing - but it has been useful!
