### ISSUE TITLE
Oddity on dialog could be a language issue?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8668]
@lloyddewit here is a little-used dialog we plan to show in the WMO course on Wednesday.

<img width="376" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/762cd383-7517-4e96-92ac-e50b491c17e2">

I don't really understand the dialog, but it has various oddities in the text in the items labelled 2, 3, 4 and 7.

I wonder if that's the language translation problem again?  If so, then is that something @N-thony can correct?

**Comment by lloyddewit** [comment]
@rdstern It's hard to say what it is without further investigation. I suggest that @N-thony looks into it. If he wishes, then he and I can always have a short chat about it.
