### ISSUE TITLE
Fixing the tab order on Climatic > Check Data > Display Daily dialogue and other dialogues

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#8681]
@Fidel365 some dialogues don't have the correct tab orders, can you correct so that the `return focus` I have recently implemented works well in those dialogues. One of the dialogue I found so far is `Climatic > Check Data > Display Daily`. We can have a quick chat and will show how to fix it, it is very simple to do.
![image](https://github.com/africanmathsinitiative/R-Instat/assets/68591383/5005f030-2f4d-4569-a7ff-1a02bc853419)

**Comment by Fidel365** [comment]
@N-thony sure
