### ISSUE TITLE
Up arrow lost in File > Import?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8706]
@N-thony here is Version 0.7.6 opening multiple DHS files:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/02debe23-f7a7-4cdc-b72a-c34d3062fac2)

In the merged version the up-arrow top right is no longer visible.  I wonder what has happened?

**Comment by derekagorhom** [comment]
@rdstern , @N-thony I still have the `up arrow` on my master (recently updated)
![image](https://github.com/africanmathsinitiative/R-Instat/assets/76208189/ea0d5751-130e-4fc4-a78a-bda99f1dc9db)

**Comment by rdstern** [comment]
Yes, interesting.  On my test version it also worked for other examples.  For this example I find that the latest 0.7.17 works:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/f581aae6-a531-40d6-817a-40ab73d2b573)


But in the visual studio version it isn't there?

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/4474bb5e-0e6b-43d9-8fd7-bc8c903d3089)

**Comment by derekagorhom** [comment]
@rdstern can you perhaps try to update it again. I will check with Vitalis and Fidel if they have the same problem as yours

**Comment by rdstern** [comment]
@derekagorhom good suggestion!  I updated and it has returned again!  So I'm closing this issue for now at least!
