### ISSUE TITLE
Fault in boxplot dialog when using sub-dialog

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8739]
@MeSophie etc

**Comment by rdstern** [comment]
@N-thony could you allocate please.  I thought @MeSophie, but she already has quite a lot for James.


a) When doing the violin plot it works with a single variable and no x given explicitely.  For example carat for the ggplot2 diamods data.
It does this by adding `x=""` into the code.  But if you return to the dialog and use the down arrow to go into the Violin plit sub-dialog, then out again and try, then it gives an error.  And the `x="" is no linger in the code.

(Curiously I think there should be the same problem with the boxplot, but it seems ok.)

b) On the main dialog in the left button at the top it should just say `Boxplot`.  Please delete the `\Tufte Boxplot` from the label.

c) If easy could you swap the second and third buttons, so the second is Violin and the third is Jitter.  (Don't do this change if it could cause complications.

**Comment by lilyclements** [comment]
Completed
