### ISSUE TITLE
Possible additions tor R-Instat scripts for smooth running in R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8774]
Here is the script.  It is copied from the [ggmosaic package vignette](https://cran.r-project.org/web/packages/ggmosaic/vignettes/ggmosaic.html).
I have added lines, so (except for the last line) it runs interactively in R-Instat.

I have 2 questions:
@lloyddewit all runs fine except the last line.  Is that an R issue, or an R-Instat script problem.
@Patowhiz It produces 6 ggplot graphs in turn.  I thought the Insert > Get Data Graph option would be what I need to add the graph to the R-Instat data book and then display it in the output Window.  I couldn't see how to use it.  I assume we need to add the same code as when getting the graph from a dialog.

Unless it is far quicker for you to do the work, than to supervise I would prefer you add instructions for Sophie, Vitalis, or Derrick.  I would like them to become expert users of the R-Instat script window and this should help.

Here is the code:

```
# Load library "ggmosaic"
library(package="ggmosaic") #added: RDS


flights <- fly  %>%
  filter(!is.na(do_you_recline), !is.na(rude_to_recline))
# Save data frame(s) "flights"
data_book$import_data(data_tables=list(flights=flights))  #added:RDS


  
  
bar_examp <- ggplot(data = flights) + 
  geom_mosaic(aes(x=product(do_you_recline), fill = do_you_recline), divider="vbar") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  labs(y="Do you recline?", x = "", title = "Bar Chart")
bar_examp #added:RDS

spine_examp <- ggplot(data = flights) + 
  geom_mosaic(aes(x=product(do_you_recline), fill = do_you_recline), divider = "vspine") +  
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  labs(y="Do you recline?", x = "", title = "Spine Plot")
spine_examp #added:RDS
stackbar_examp <- ggplot(data = flights) + 
  geom_mosaic(aes(x=product(do_you_recline, rude_to_recline), fill = do_you_recline),
              divider=c("vspine", "hbar")) +   
  labs(x="Is it rude to recline?", y = "Do you recline?", title = "Stacked Bar Chart")
stackbar_examp  #added:RDS
mosaic_examp <- ggplot(data = flights) +
  geom_mosaic(aes(x = product(do_you_recline, rude_to_recline), fill = do_you_recline)) +   
  labs(y="Do you recline?", x="Is it rude to recline?", title = "Mosaic Plot (2 variables)") 
mosaic_examp  #added:RDS
mosaic2_examp <- ggplot(data = flights) +
  geom_mosaic(aes(x=product(eliminate_reclining, do_you_recline, rude_to_recline), fill = do_you_recline, alpha = eliminate_reclining)) + 
  scale_alpha_manual(values =c(.7,.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) + 
  labs(y="Do you recline?", x="Eliminate reclining?:Is it rude to recline?", title = "Mosaic Plot (3 variables)")
mosaic2_examp  #added:RDS

ddecker_examp <- ggplot(data = flights) +
  geom_mosaic(aes(x=product(do_you_recline, eliminate_reclining, rude_to_recline), fill = do_you_recline, alpha = eliminate_reclining), divider = ddecker()) + 
  scale_alpha_manual(values =c(.7,.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) + 
  labs(y="Do you recline?", x="Eliminate reclining?: Is it rude to recline?", title = "Double Decker Plot")
ddecker_examp #added:RDS

spine_examp + bar_examp + mosaic_examp + stackbar_examp + mosaic2_examp + ddecker_examp + plot_layout(ncol = 2) 
#This last line gives an error.  It runs with just one plus, so 2 greaphs, but no more.
```

**Comment by Patowhiz** [comment]
@rdstern a quick execution of the script gave the error below in R studio.

<img width="685" alt="1" src="https://github.com/IDEMSInternational/R-Instat/assets/21179007/68647cbc-26f8-4ad4-9839-6fd33dfbca84">

**Comment by rdstern** [comment]
@Patowhiz thanks.  If the last goes wrong similarly in RStudio, then there is nothing in this issue for @lloyddewit !

But the specification, for the Insert dialog, to facilitate the ggplot graphs going into the data sheet, and then being displayed in the output window - and your maximise window, remains and would be a very useful feature.  I thought that was already there, in Get Data > Graph, but it didn't seem to do that?

**Comment by Patowhiz** [comment]
@rdstern you have to add the graph to the data book before you can get graph. So use the Save Data tab to get the add object of type graph script, then use the Get Data tab to get the script for getting object of type graph.

**Comment by rdstern** [comment]
@Patowhiz many thanks - I got it to work.  Very exciting.  Here is my first ggplot image from a script, in the output window!

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/7f031158-0a6a-4f08-a3c1-5b2b1456eb44)

But, as you said, I had to use Save Data and then Get Data.  Then I had to edit the Get Data code, so it displayed, rather than assigning it as an object.

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/277ee610-a99c-4124-b502-41a517b6e712)

Could we have a checkbox under the word Graph, with label `Display`.  Default is checked.
If checked, then it adds the second line (just as you get with the dialog.)  So it then saves the object in the Data Book and then displays it in the output window.

I assume this will be a small task for you, and probably quicker than explaining to someone else?

**Comment by Patowhiz** [comment]
@rdstern sounds like a good suggestion. However, implementing it may deviate from the current design philosophy of the dialog, where Get Data tab is for reading from the data book and Save Data is for writing to the data book. Introducing this feature might blur the lines between functionalities, disrupting the design and usage philosophy, and unintentionally complicating the learning curve for users.

Moreover, this raises questions about consistency, such as whether similar checkboxes should be added for other functionalities like Data Frame. It prompts a broader inquiry into the initial decision to separate these functionalities, a decision we both comprehend well.

If you persist in wanting to add this feature, I am open to including it. However, I recommend a careful consideration of the implications on design and usability.

**Comment by rdstern** [comment]
@Patowhiz I am persisting!  One of our principles is "Making it easy".  We produce those 2 lines with every dialog that produces a graph.  The graphs seem to be different in running scripts to other objects, because - without this feature - they only display in the R viewer.  That's a big weakness of our current system, partly because the R-viewer as set, can only display a single graph.

**Comment by Patowhiz** [comment]
@rdstern, it's not just about graphs; it also applies to HTML output formats. It's crucial to distinguish between the output "system" and the script dialog, as these are two distinct issues that shouldn't be conflated. Their intentions differ significantly, and one doesn't expose the weaknesses of the other.

Regarding the idea of appending the two lines to every dialog that generates an output object, the rationale behind this practice lies in the fact that other dialogs read and write from the data book, aligning with their implicit design philosophy. The script dialog, however, operates under a different paradigm. The introduction of the proposed checkbox challenges the accuracy of labeling the tab as 'Save Data' since it essentially duplicates the functionality already present in the Get Data tab. This calls into question the original decision to separate these functionalities.

Upon further reflection on your suggestion, I'm contemplating the possibility of introducing a 'View Data' tab. This tab could generate scripts for viewing data frames, columns, and output objects without necessitating their addition to the data book. The generated scripts would invoke the appropriate output system corresponding to the selected option. This approach might provide a more cohesive solution to this and other current challenges. If you agree, I'll recommend this option.

However, considering your persistence, my comments should not stop the addition of the checkbox.

**Comment by Patowhiz** [comment]
@Vitalis95 could you attempt adding the checkbox as suggested by @rdstern? All you need is to use the code generated in save data and update it with parameters of the get data controls.

**Comment by rdstern** [comment]
@Patowhiz you write:

"Upon further reflection on your suggestion, I'm contemplating the possibility of introducing a 'View Data' tab. This tab could generate scripts for viewing data frames, columns, and output objects without necessitating their addition to the data book. The generated scripts would invoke the appropriate output system corresponding to the selected option. This approach might provide a more cohesive solution to this and other current challenges. If you agree, I'll recommend this option."I

If I understand this suggestion correctly, then this would be great.  I am already preparing the documentation to discuss what happens when you use R-Instat in different ways.  At one extreme you automatically put the data straight into an R-Instat Data Book.  That's automatic from the menu/dialog approach.  At the other extreme you can run an R-script from start to end, without putting the data into a data book.  Then you don't make use of the special grid (I assume you can't), or the metadata windows.  You work simply from the script to the output window.  You can still, of course use the R-viewer to look at your data, etc.

**Comment by Patowhiz** [comment]
@rdstern my recommendation would allow you to work with the data and output objects without having to put them in the data book.

**Comment by rdstern** [comment]
@Patowhiz oh, of course.  And I assume we start with the output objects, because they are standard R objects.

**Comment by Patowhiz** [comment]
@rdstern yes. I'm assuming you have now agreed that the checkbox should now not be added? And we should have another tab labelled 'View Data' after the 'Save Data' tab?

**Comment by rdstern** [comment]
@Patowhiz oooh no.  I thought we might be agreed now.  I am delighted with you View addition.  But we are adding more "Options by Context", in the way different users can use R-Instat.  For many users I would like to encourage them to use the R-Instat data book.  And in that case I am keen to make it as easy as possible for them to "tweak" the existing R code to do so!  So I was delighted you asked @Vitalis95 to add this.
