### ISSUE TITLE
The Use of the term Save

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#8938]
Hello @Patowhiz, @rdstern, @volloholic and @dannyparsons,

![2024-04-17_13-34-09](https://github.com/IDEMSInternational/R-Instat/assets/85707390/f2de0031-da39-4197-8756-c52bfded95c6)
![2024-04-17_13-35-40](https://github.com/IDEMSInternational/R-Instat/assets/85707390/bb0b14fe-9964-416b-a316-dba0b1ad1a7c)

I have been writing the help and in working through the save options. I have noticed that we use the word save for two different things and I find that confusing. 

1. In the file menu we use save and save as for what I think most people understand save to mean. You save an item and then it appears in a place on your computer and you can reopen it. 
2. On the graph dialogs or table dialogs there is a Save Graph or Save table checkbox which brings up a box for you to add a name. In my understanding this stores the object in the metadata so that you can then recall it using the R Objects dialogs or save it to your computer using the Export as Image dialog. 

I believe it is confusing to have these very different tasks called the same thing. When I click on the Save Graph check box and give it a name i assumed it would be saved to my computer but it is not, instead i still need to export and save it. I propose that we rename this Store so that it is clear that the object is being kept but that users don't think it has been saved. 

Does this make sense? Does anyone else have thoughts on this? I feel curious whether I am the only one. 

Thanks. 

Rachel

**Comment by rachelkg** [comment]
Thanks to everyone for your feedback so far. Based on what people have said it sounds as though this is a valid point and important distinction, but we also want to make sure we are minimizing disruption.  As such I propose that for now we add tool tips to these save items, saying something like "checking this will store this object in the data-book for further use." @rdstern perhaps you could decide exactly what the tool tips will say and specify who would add them. 

Then in the documentation we make sure that we are clearly denoting this distinction. Including a page and or video about data-books in the getting started section of the moodle site. This will be based on the Help section relating to this. 

We keep an eye out for this as R-Instat is used in training session and if this come up as a problem we consider other options then. 

Thanks, 

Rachel

**Comment by Patowhiz** [comment]
@rdstern @rachelkg I like the tooltip idea. This should help with the distinction and minimise any disruption that could affect existing R-Instat users. 
I also don't have any strong objections in regards to using the word "store".

**Comment by rdstern** [comment]
@MeSophie I am delighted you have started work on this.  I also hope you will include the Calculate dialog.  It was an interesting alternative by @N-thony to call it Append for the calculator, but with the use of the Position button it is sometimes not an append.  It is always stored, so I'd prefer to just stick with Store.  Is that ok by you @N-thony ?
