### ISSUE TITLE
double click on ucrReceiver

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#894]
Should we have more options to remove selected variables from the receiver? @rdstern 
We propose to have a double click with a tool tip to help people see. 
We also suggest a click and drag option may be useful...   @dannyparsons @volloholic

**Comment by dannyparsons** [comment]
Good ideas.

Currently the delete key deletes selected variables (or the only variable
in the single receiver). I thought having the backspace key doing the same
would be good.

Double click also sounds good, although I don't see it working for removing
more than one variable. If you've selected multiple variables, after the
first click you've lost your multiple selection. @rdstern do other packages
do this? But it will still work well for removing one at a time.

Click and drag was something @rdstern was keen on. I will discuss all this
with him today.

**Comment by dannyparsons** [comment]
I've now added some functionality here:

a) the backspace key removes selected variables
b) added a context right click menu in the multiple receiver to delete selected and clear all
c) Double click in selector adds selected to receiver
d) Double click in receiver removes selected
e) Removed the column header "Selected Variables" in the multiple receiver
f) Removed the name of the Data Frame as a Group title in the selector when there is a Data Frame selector above.

**Comment by dannyparsons** [comment]
More features (eg. dragging) still to be implemented but probably not urgently.

**Comment by dannyparsons** [comment]
Additional right click menu item needed in selector is "Add all" which selects all columns and add them to receiver

**Comment by Lunalo** [comment]
I am working on this

**Comment by dannyparsons** [comment]
When the current receiver is Single, we shouldn't be able to add all. Currently it doesn't crash but it adds the last variable, so not that useful.
Can we disable Add All when the current receiver is Single? @Lunalo This shouldn't take too long, so if you get stuck let me know.

**Comment by maxwellfundi** [comment]
@Lunalo  whats the status of this?

**Comment by dannyparsons** [comment]
The small additions here haven't been implemented, they should be quick, as I said in January.

**Comment by dannyparsons** [comment]
@Lunalo I have done this now as it took 5 minutes to do.
