### ISSUE TITLE
Minor issues in the "Line Plot" dialog

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#9312]
I've seen two very minor issues in the Line Plot dialog when using the multiple receiver:

1. We should have `colour = variable`, not `fill = variable`
2. `geom_line` shouldn't have `colour="blue"`, as this overwrites us colouring it by variable! It makes having the multiple receiver option redundant.

### Reproducible Example

* Use the Dodoma data in the R-Instat library
* Go to "Describe > Graph > Line Plot"
* Click "Multiple Receiver", and put `tmin` and `tmax` in the receiver
* Put `date` in the single receiver:

![image](https://github.com/user-attachments/assets/1b8b2598-7a93-4935-b06e-0f09be5c6cf5)

* Click OK

**It gives this plot with this code:**

![image](https://github.com/user-attachments/assets/22b08f70-f594-4f2a-ad0d-29f0ca92c2b8)

```
# Dialog: Line Plot
dodoma <- data_book$get_data_frame(data_name="dodoma", stack_data=TRUE, measure.vars=c("tmin","tmax"))
last_graph <- ggplot2::ggplot(data=dodoma, mapping=ggplot2::aes(y=value, **fill=variable**, x=date)) + **ggplot2::geom_line(colour="blue", size=0.8**) + theme_grey() + ggplot2::theme(legend.position="none")
data_book$add_object(data_name="dodoma", object_name="last_graph", object_type_label="graph", object_format="image", object=check_graph(graph_object=last_graph))
data_book$get_object_data(data_name="dodoma", object_name="last_graph", as_file=TRUE)
```

**We want this plot with this code:**

![image](https://github.com/user-attachments/assets/7f19ca16-e9a2-43e5-81ab-0e790cfd3a96)

```
# Dialog: Line Plot
dodoma <- data_book$get_data_frame(data_name="dodoma", stack_data=TRUE, measure.vars=c("tmin","tmax"))
last_graph <- ggplot2::ggplot(data=dodoma, mapping=ggplot2::aes(y=value, **colour =variable**, x=date)) + **ggplot2::geom_line(size=0.8)** + theme_grey() + ggplot2::theme(legend.position="none")
data_book$add_object(data_name="dodoma", object_name="last_graph", object_type_label="graph", object_format="image", object=check_graph(graph_object=last_graph))
data_book$get_object_data(data_name="dodoma", object_name="last_graph", as_file=TRUE)
```

That is, 

1. For this option, we should have `colour = variable`, not `fill = variable`
2. `geom_line` shouldn't have `colour="blue"`, as this overwrites us colouring it by variable! It makes having the multiple receiver option redundant.

**Comment by rdstern** [comment]
@lilyclements many thanks.  I hope you have been using Version 0.8.0 for this?  I think it is now fixed in the merged version and done by @MeSophie ?

![image](https://github.com/user-attachments/assets/76226636-a654-4c19-8805-6063206c7486)

**Comment by lilyclements** [comment]
@rdstern my mistake, thanks!
