### ISSUE TITLE
Left or Centre align forms and dialogs title

### ISSUE THREAD

**Issue by deaspo** [africanmathsinitiative/R-Instat#939]
I have observed that the form and dialogs titles are left aligned in some of the team members laptops while for others they are centre aligned. What should be the case and how can we ensure that these settings are consistent on everybody's laptop? @africanmathsinitiative/instat

**Comment by dannyparsons** [comment]
This still needs to be looked into and generally the dialog properties need to be checked to make sure they are consistent. For example, some dialogs have a different style for the Close (X) button in the top right. I think this is just a property in the design view that can be changed. 
Probably this is not urgent.

**Comment by maxwellfundi** [comment]
This looks like it was fixed as well. trying to get rid of old issues that were fixed so that we focus now on after Beta

**Comment by dannyparsons** [comment]
This is interesting, the form titles are on the left on some machines and centre on others. Would be good to understand why this is.

**Comment by dannyparsons** [comment]
Believe this is not possible to change with WinForms and is dependant on user's Windows settings. This doesn't need to be consistent across machines.
