### ISSUE TITLE
Output Window Spacing

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#998]
Spacing needs to be sorted out for the Output Window. Sometimes we have single spaces, sometimes double etc.

The spacing should be one empty line after the R code or output so that there is a space before the next comment.

```
# dlgSummaryBarOrPieChartcode generated by the dialogSummary Bar Or PieChart
survey_temp <- InstatDataObject$get_data_frame(data_name="survey")
(ggplot(data=survey_temp,mapping=aes(x=Village.,y=Field)) + geom_bar(width=1,stat="identity")) + geom_bar(stat="identity")

# dlgOneWayANOVAcode generated by the dialogOne Way ANOVA
survey_temp <- InstatDataObject$get_data_frame(data_name="survey")
aov(data=survey_temp,formula=Yield ~ Village.)
```

**Comment by dannyparsons** [comment]
Still needs to be fixed. This can be fixed by modifying the RunScript method of clsRLink.

**Comment by maxwellfundi** [comment]
This needs to be fixed. @dannyparsons

**Comment by dannyparsons** [comment]
This should be fixed by new output window. Can someone now check that spacing is sensible? Maybe @lilyclements @maxwellfundi

**Comment by lilyclements** [comment]
So I imported my dataset, then ran a one variable graph and got a double space between them. After that I've only had single spaces. Upon re-opening, a double space occurs again between import of dataset and then running something new (e.g., a new dialog, changing something to a factor, etc)

This is the only time I can find that this issue occurs

**Comment by dannyparsons** [comment]
With the new output window this should be much improved now. However, if the call type is incorrect for a dialog it may give an extra space for output even if there is none. @africanmathsinitiative/developers be on the lookout for this and check the call type if there's a problem.

**Comment by dannyparsons** [comment]
This should still be checked on individual dialogs but this is not a general issue anymore.
